### ISSUE TITLE
Multiple document handling breaks if --- found anywhere in the document.

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#1004]
So, the idea was to support yaml files that contain multiple documents. This works, in most cases, by detecting using `---` as a delimiter to split documents. Problem arises though when `---` is not used as a delimiter but its part of string.

For example: https://github.com/syndesisio/syndesis/blob/master/app/deploy/syndesis-restricted.yml#L355

**Comment by iocanel** [comment]
@hrishin: I think that you worked on the initial implementation of this, so could you please have a look?

**Comment by rohanKanojia** [comment]
@hrishin : Are you working on this? If not, can i pick it up?
