### ISSUE TITLE
use exec copy file to pod too slow

### ISSUE THREAD

**Issue by Mrwangjinxin** [fabric8io/kubernetes-client#1008]
My client version is 3.1.8
When i use k8s web socket api directly, every thing is ok.
But when i use your client, the upload speed is only about 1Kb per second.

my code is:

    public void uploadFile(KubernetesClient client,
                           String namespace,
                           String podName,
                           String containerName,
                           String desFilePath,
                           InputStream inputStream) throws IOException {
        ExecWatch watch = client
                .pods()
                .inNamespace(namespace)
                .withName(podName)
                .inContainer(containerName)
                .redirectingInput()
                .redirectingError()
                .exec("tar", "xf", "-", "-C", "/");
        TarArchiveEntry entry = new TarArchiveEntry(desFilePath);

        try (TarArchiveOutputStream tarOut = new TarArchiveOutputStream(watch.getInput());
             ByteArrayOutputStream byteOut = new ByteArrayOutputStream();) {

            byte[] bytes = new byte[4096];
            int count;
            while ((count = inputStream.read(bytes)) > 0) {
                byteOut.write(bytes, 0, count);
            }

            entry.setSize(byteOut.size());
            tarOut.putArchiveEntry(entry);
            byteOut.writeTo(tarOut);
            tarOut.closeArchiveEntry();
        }
    }

**Comment by Mrwangjinxin** [comment]
I found the reason!!! Is the PipedInputStream issue:
https://stackoverflow.com/questions/28617175/did-i-find-a-bug-in-java-io-pipedinputstream
I solved it by Reflect set the buffer size!
Can you guys please support set the PipedInputStream's buffer size?

**Comment by ashofthephoenix** [comment]
i used reflections(as above) to speed it up and it worked - although it doesn't write all the bytes, also tends to throw pipe closed/read end exceptions. any ideas?

**Comment by zxbu** [comment]
I  solved it by other way, not reflect.
I think it is a better way


`
        PipedInputStream pipedInputStream = new PipedInputStream(1024 * 1024);  // pipeSize is 1m
        PipedOutputStream pipedOutputStream = new PipedOutputStream(pipedInputStream);

        kubernetesClient.pods()
                .inNamespace(namespace)
                .withName(podName)
                .inContainer(containerName)
                .readingInput(pipedInputStream)
                .exec("tar", "xf", "-", "-C", "/");

        TarArchiveEntry entry = new TarArchiveEntry(path);
        try (TarArchiveOutputStream tarOut = new TarArchiveOutputStream(pipedOutputStream); ByteArrayOutputStream byteOut = new ByteArrayOutputStream();) {

            byte[] bytes = new byte[4096];
            int count;
            while ((count = inputStream.read(bytes)) > 0) {
                byteOut.write(bytes, 0, count);
            }
            entry.setSize(byteOut.size());
            tarOut.putArchiveEntry(entry);
            byteOut.writeTo(tarOut);
            tarOut.closeArchiveEntry();
        }
`

**Comment by mrjgreen** [comment]
We believe this issue is having a huge impact on the speed of Jenkins Builds when running the kubernetes plugin, which makes extensive use of the `exec` call in this library. It would improve build times by an order of magnitude in some cases if we could resolve this issue.

I'm not familiar enough with this library to know where to start with a potential fix - is anyone on this thread able to suggest where a possible fix should go?

**Comment by msb217** [comment]
I have a solution for the slow upload https://github.com/fabric8io/kubernetes-client/issues/868#issuecomment-514352742
