### ISSUE TITLE
Kubernetes Connection is not closed.

### ISSUE THREAD

**Issue by hemanik** [fabric8io/kubernetes-client#1013]
When running tests using OpenShift/Kubernetes the following warning is thrown:
```
WARNING: A connection to https://api.starter-us-east-2.openshift.com/ was leaked. 
Did you forget to close a response body? To see where this was allocated, 
set the OkHttpClient logger level to 
FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
```
On setting the level to FINE, the logs shows this coming from [WatchConnectionManager.java#L145](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java#L145).

```
Feb 15, 2018 10:52:18 PM okhttp3.internal.platform.Platform log
WARNING: A connection to https://192.168.42.69:8443/ was leaked. Did you forget to close a response body?
java.lang.Throwable: response.body().close()
    at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:143)
    at okhttp3.RealCall.captureCallStackTrace(RealCall.java:78)
    at okhttp3.RealCall.enqueue(RealCall.java:87)
    at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.java:180)
    at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:427)
    at io.fabric8.kubernetes.clnt.v3_1.dsl.internal.WatchConnectionManager.runWatch(WatchConnectionManager.java:145)
    at io.fabric8.kubernetes.clnt.v3_1.dsl.internal.WatchConnectionManager.<init>(WatchConnectionManager.java:97)
    at io.fabric8.kubernetes.clnt.v3_1.dsl.base.BaseOperation.watch(BaseOperation.java:701)
    at io.fabric8.kubernetes.clnt.v3_1.dsl.base.BaseOperation.watch(BaseOperation.java:689)
    at io.fabric8.kubernetes.clnt.v3_1.dsl.base.HasMetadataOperation.periodicWatchUntilReady(HasMetadataOperation.java:200)
    at io.fabric8.kubernetes.clnt.v3_1.dsl.base.HasMetadataOperation.waitUntilReady(HasMetadataOperation.java:227)
    at io.fabric8.openshift.clnt.v3_1.handlers.DeploymentConfigHandler.waitUntilReady(DeploymentConfigHandler.java:78)
    at io.fabric8.openshift.clnt.v3_1.handlers.DeploymentConfigHandler.waitUntilReady(DeploymentConfigHandler.java:33)
    at io.fabric8.kubernetes.clnt.v3_1.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl$1.run(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:105)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```
Just want to ensure if this is because of some missing call in cube to close the client or if it is something related to f8-client.

**Comment by rohanKanojia** [comment]
I've been looking into `WatchConnectionManager`'s code and till now I don't have any clear idea. The warning says that response body is not getting closed, but I don't see any condition in the code where body is not getting closed. This warning message is quite intermittent, though I'm not saying this is not a valid bug. Even if i try to ensure that response body gets closed always(by putting `response.body().close()` in finally block, like [this](http://paste.opensuse.org/2628803). Still I get this warning message :( .

I also tried producing a simple test case for this:
```
		try {
			OpenShiftClient openshiftClient = new DefaultOpenShiftClient();
			String namespace = openshiftClient.getNamespace();
			String templateFilePath = System.getProperty("user.dir")
					+ "/src/main/resources/wordpress-template.yml";

			Template template = openshiftClient.templates()
					.inNamespace(namespace)
					.load(new FileInputStream(templateFilePath)).get();
			openshiftClient.templates().inNamespace(namespace).create(template);

			KubernetesList resourceList = openshiftClient.templates().inNamespace(namespace)
					.withName(template.getMetadata().getName()).process();
			openshiftClient.lists().inNamespace(namespace).create(resourceList);
			
			final CountDownLatch latch = new CountDownLatch(1);
			// This section should reproduce our warning!
			Watch watch = openshiftClient.pods().inNamespace(namespace).withLabel("name", "wordpress-mysql-example").watch(new Watcher<Pod>() {
				public void eventReceived(
						io.fabric8.kubernetes.client.Watcher.Action action, Pod pod) {
					if(Readiness.isReady(pod)) {
						latch.countDown();
					}
				}

				public void onClose(KubernetesClientException arg0) {
				
				}
			});
			
			latch.await(10, TimeUnit.MINUTES);
			logger.log(Level.INFO, "Closing client now... ");
			openshiftClient.close();
		} catch (Exception exception) {
			exception.printStackTrace();
		}
```

Unfortunately I'm not able to reproduce above warning with this test case also(I might be missing something :-) ). After discussing this with main 
authors, I can think of the following possibilities of why this could be happening:

1.) This warning could be referring to another connection; While using `Watch`, if somehow connection is dropped, k8-client triest to reconnect.
    These reconnection attempts use exponential back off. It could be possible that we might be getting connection leak warning from previous
    connection.

2.) It could also be a side effect of us cloning the OKHttpClient object, see [WatchConnectionManager.java#L85](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java#L85).

that being said, I need to look into `OkHttp` code to see the root cause.

**Comment by piyush1594** [comment]
Hey @rohanKanojia This seems to be like not fixed yet. I am still seeing this error. You can check the logs of my latest PR here https://circleci.com/gh/fabric8io/kubernetes-client/tree/pull%2F1060 You will still see that warning.

**Comment by rohanKanojia** [comment]
I fixed this during the watch of any resource and tested it on https://github.com/arquillian-testing-microservices/openshift-deployment-testing. Looking at the logs I'm not sure if it's coming from Watch*Managers. We use Okhttp almost everywhere in this project. Perhaps @hemanik could tell if she is still facing this issue.

**Comment by jeff-1amstudios** [comment]
I still see it with version `4.0.3`

**Comment by rohanKanojia** [comment]
@jeff-1amstudios : Yeah, the patch which I sent for fixing this got reverted as you can see. Will try to jump back on this soonish.

**Comment by rohanKanojia** [comment]
@traviswinter : ah, I tested it with case provided by OP itself. Yes, I'm working on getting these leaks fixed this sprint.

**Comment by rohanKanojia** [comment]
@traviswinter : bdw, Could you please provide a test case also from which I can reproduce leaks and debug better? Last time they were quite intermittent.

**Comment by traviswinter** [comment]
Sorry @rohanKanojia , just saw this message now.  Our process is a little convoluted so its difficult to reproduce outside of it.

We have a watcher built from a Kubernetes Client that, when it receives an event, queries the cluster for data.  The querying varies depending on factors, but generally we run similar code to "ReplicaSetList replicaSetList = kubeClient.extensions().replicaSets().inAnyNamespace().list();" for each of the resources and that's where I'm seeing the leak on response.  It seems to happen mostly for Deployments, ReplicaSets, and DaemonSets - I have not seen it occur for Nodes or Pods to my knowledge.

Does that help?

**Comment by ljnelson** [comment]
Just lurking, but the message is definitely coming from the OkHttp client: https://github.com/square/okhttp/blob/5b37cda9e00626f43acf354df145fd452c3031f1/okhttp/src/main/java/okhttp3/ConnectionPool.java#L266-L271

**Comment by ljnelson** [comment]
Last comment: I am no expert in this codebase or in OkHttp, but shouldn't this response be closed? https://github.com/fabric8io/kubernetes-client/blob/f7843cff15b239e4466167f63c599fc9ca4e4146/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java#L379

**Comment by ljnelson** [comment]
I did find a place where a `ResponseBody` does not seem to be closed: https://github.com/fabric8io/kubernetes-client/blob/f7843cff15b239e4466167f63c599fc9ca4e4146/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java#L428

**Comment by nevenr** [comment]
Hi,
still the same behavior in 4.10.1
```
20200513:113920.620 [OkHttp ConnectionPool] WARN  okhttp3.OkHttpClient - A connection to https://some.host:443/  was leaked. Did you forget to close a response body?
java.lang.Throwable: response.body().close()
	at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:144)
	at okhttp3.RealCall.captureCallStackTrace(RealCall.java:89)
	at okhttp3.RealCall.enqueue(RealCall.java:98)
	at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.java:183)
	at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:436)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.runWatch(WatchConnectionManager.java:158)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.<init>(WatchConnectionManager.java:100)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.<init>(WatchConnectionManager.java:105)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:786)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:772)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:73)
	...
	at java.lang.Thread.run(Thread.java:748)
```
Regards,
N.

**Comment by rohanKanojia** [comment]
@nevenr : Could you please share a reproducer?

**Comment by nevenr** [comment]
Hi @rohanKanojia ,
this is happening when using **watch** API:
```
final CustomResourceDefinition myCrd = new CustomResourceDefinitionBuilder()
	.withApiVersion("apiextensions.k8s.io/v1")
	.withNewMetadata()
	.withName("things.mygroup.io")
	.endMetadata()
	.withNewSpec()
	.withGroup("mygroup.io")
	.withVersion("v1alpha1")
	.withScope("Namespaced")
	.withNewNames()
	.withKind("Thing")
	.withSingular("thing")
	.withPlural("things")
	.withListKind("ThingList")
	.endNames()
	.withPreserveUnknownFields(true)
	.endSpec()
	.build();


Config config = new ConfigBuilder().withMasterUrl("https://some.host:443/").build();
OpenShiftClient client = new DefaultOpenShiftClient(config);

final NonNamespaceOperation<Thing, ThingList, DoneableThing, Resource<Thing, DoneableThing>> thingClientNonNamespaced = client.customResources(myCrd, Thing.class, ThingList.class, DoneableThing.class);
final NonNamespaceOperation<Thing, ThingList, DoneableThing, Resource<Thing, DoneableThing>> thingClient = ((MixedOperation<Thing, ThingList, DoneableThing, Resource<Thing, DoneableThing>>) thingClientNonNamespaced).inNamespace("my-namespace");

thingClient.watch(new Watcher<Thing>() {
	@Override
	public void eventReceived(Action action, Thing resource) {
		System.out.println("action = " + action);
		System.out.println("resource = " + resource);
	}

	@Override
	public void onClose(KubernetesClientException cause) {
		System.out.println("cause = " + cause);
	}
});
```

When remote API endpoint is not accessible (is down, authentication error, 404 page not found) OkHttp yield  "A connection to {}  was leaked. Did you forget to close a response body?".

Regards,
N.
