### ISSUE TITLE
[upgrade] support for Kubernetes/Openshift v1.9/v3.9

### ISSUE THREAD

**Issue by hrishin** [fabric8io/kubernetes-client#1020]
To enabled support for Kubernetes/Openshift v1.9/v3.9, need to upgrade kubernetes-model.

**Comment by titou10titou10** [comment]
+1
ie in v1.9, `"Deployments"``  are no more in the extension namespace...

**Comment by zepouet** [comment]
Hello,

Just to understand who use it ? Openshift ? It is why you don't need mandatory to update it to the last release. I think it is normal as the usecase.  Thanks about the work !

Best regards,

**Comment by piyush1594** [comment]
Fixed in #1103 Closing this.
