### ISSUE TITLE
sometimes, delete deployment get a NullPointerException

### ISSUE THREAD

**Issue by Mrwangjinxin** [fabric8io/kubernetes-client#1022]
maybe deployment.getStatus().getObservedGeneration() is null ?
{
  "methodName": "reap",
  "fileName": "DeploymentOperationsImpl.java",
  "lineNumber": 167,
  "className": "io.fabric8.kubernetes.client.dsl.internal.DeploymentOperationsImpl$DeploymentReaper",
  "nativeMethod": false
}

**Comment by wei0313** [comment]
I have seen the similar issue on mine. However, when I put sleep (1 second) after the deletion, i no longer see the issue. I don't know why.

**Comment by rohanKanojia** [comment]
Hmm, Issue looks intermittent. Not sure whether to prioritize it or not :confused:
