### ISSUE TITLE
Support for ImageStreamImport in OpenShiftClient

### ISSUE THREAD

**Issue by bjartek** [fabric8io/kubernetes-client#1025]
OpenShift has an import-image command that imports tags from a given imageStream. Is it possible to get support for this in the client?

**Comment by bjartek** [comment]
I tried to create a PR here, but adding the ImageStreamImport in the genrate code in model resulted in generated java files that would not compile.

**Comment by bjartek** [comment]
I do not know why this was closed. It should be open.

**Comment by piyush1594** [comment]
Hey @bjartek 

Can you explain more, exactly what problem you are facing?

Thanks

**Comment by bjartek** [comment]
The OpenShift api exposes an endpoint to import one or more tags in an imageStream. https://docs.openshift.com/container-platform/3.7/rest_api/apis-image.openshift.io/v1.ImageStreamImport.html

There are no functionality to do the same in this client and no Model object to marshal the resource from the server. 

Or did you mean what is my problem when I tried to create the PR? I could always just create the PR.

**Comment by bjartek** [comment]
See linked issue for what we have to do now in order to get this to work. Basically create our own representation of the ImageStreamImport object. Note that in boober we do not use kubernetes-client only kubernetes-model.

**Comment by piyush1594** [comment]
@bjartek This issue needs to be in the model. Kubernetes Client uses model for all the objects. Opened issue https://github.com/fabric8io/kubernetes-model/issues/326 and raised PR https://github.com/fabric8io/kubernetes-model/pull/325 to resolve this. Closing this.

**Comment by bjartek** [comment]
Thanks!
