### ISSUE TITLE
New v3.1.9 release?

### ISSUE THREAD

**Issue by cdancy** [fabric8io/kubernetes-client#1031]
Any chance we could get a new point release spun up as you've resolve some critical issues around security that we've been waiting for. Thanks AOT!

**Comment by oscerd** [comment]
Yes, I believe it's time for a new release.

**Comment by cdancy** [comment]
@oscerd so it's coming soon? :)

**Comment by oscerd** [comment]
Probably by the end of week.

**Comment by cdancy** [comment]
@oscerd awesome and thanks!

**Comment by oscerd** [comment]
3.1.10 released

http://repo2.maven.org/maven2/io/fabric8/kubernetes-client/3.1.10/

**Comment by cdancy** [comment]
@oscerd fantastic and thanks for the quick response/release!

**Comment by cdancy** [comment]
@oscerd random question: do you guys have a "projects that use this library" section or ever thought about creating one? I ask because I'm the current maintainer of the up and coming [gradle-kubernetes-plugin](https://github.com/bmuschko/gradle-kubernetes-plugin) and also the maintainer of the fairly popular, at least in the gradle world, [gradle-docker-plugin](https://github.com/bmuschko/gradle-docker-plugin) and we're trying to do for _kubernetes_ what we did with _docker_ which is to say make things stupid-simple for gradle users wanting to work with either of these technologies. We've decided on using this library in the backend to communicate with kubernetes as it appears to be the most mature whilst also supporting OpenShift (which I dislike and think is a huge pain in the @$$). We'd like to get as much exposure as possible if you guys have something. I've already put links to this project on our page, letting folks know what we're using, so hopefully that will, as the project gets bigger and the community more involved, drive more traffic to you guys (it certainly did for the `docker-java` library which we used in the backend for the `gradle-docker-plugin`).

**Comment by oscerd** [comment]
I believe is a good idea to have something in the README that list project using kubernetes-client. Lets wait for comments from the team btw :-)

**Comment by piyush1594** [comment]
Hey @cdancy 

We already have a plan regarding that, you can see the issue #935. I am not sure about the ETA of this but yaa it's in our list.

Thanks

**Comment by cdancy** [comment]
Commented on the ISSUE. Thanks again guys!

**Comment by cdancy** [comment]
@piyush1594 @oscerd or any other developer or whomever is releasing and prioritizing things: any chance that #1016 could be taken seriously? You guys currently publish a pseudo uber jar but it doesn't have all dependencies baked in. Any chance you guys could add this functionality as part of your normal releases? As part of work getting our initial `v1.0.0` release out of the door for the [gradle-kubernetes-plugin](https://github.com/bmuschko/gradle-kubernetes-plugin) we really need a proper shaded version of this library as we build on top of this and NOT having a proper shaded version gets end-users into all sorts of situations when running with gradle. Previously, and for other plugins we produce, we've created proper shaded versions of dependent libraries ourselves but I'm making a final plea for you guys to implement this so that we don't have to host/write yet another library to do this on behalf of the given project.

**Comment by oscerd** [comment]
cc @iocanel
