### ISSUE TITLE
About PetSet how to use?

### ISSUE THREAD

**Issue by swqmaven** [fabric8io/kubernetes-client#1052]
in fabric8.kubernetes.client 1.4.20 version How to use PetSet create in java client?

**Comment by piyush1594** [comment]
Hey @swqmaven 

Can you please elaborate. What is the problem you are facing with this? Thanks

**Comment by swqmaven** [comment]
@piyush1594 how to use java client to create a petset resource ? example code?

**Comment by piyush1594** [comment]
Hey @swqmaven 

You can import the PetSet class from
```
import io.fabric8.kubernetes.api.model.extensions.PetSet;
import io.fabric8.kubernetes.api.model.extensions.PetSetBuilder;
```

You can create a PetSet object like this
```
PetSet petSet = new PetSetBuilder().withNewMetadata().withName("web").endMetadata().withNewSpec().withServiceName("nginx").endSpec().build();
```

I think other operations like create, get, list and all will work fine. I just tried creating PetSet Object, it worked fine. 

Hope it resolves your problem.

Thanks

**Comment by swqmaven** [comment]
@piyush1594  thanks .  I know how to create a PetSet obj  but i cant find interface or service  how to create this obj  in KubernetesClient . or .extensions()? 
I used fabric8.kubernetes.client 1.4.20 version

**Comment by piyush1594** [comment]
@swqmaven 

I think there may be something like this
```
client.extensions().petSets().inNamespace("default").create(petSet);
```
Not sure, as I never used it.

**Comment by swqmaven** [comment]
@piyush1594  in my version can't  find this in client extensions() . do you have? what's the version?

**Comment by piyush1594** [comment]
@swqmaven Support of PetSet is not there in client right now.
