### ISSUE TITLE
How to skip autofilling of Config properties while using ConfigBuilder?

### ISSUE THREAD

**Issue by ekoshkin** [fabric8io/kubernetes-client#1058]
It is not clear how not to auto fill config properties when creating k8s client, e.g.
`new DefaultKubernetesClient(new ConfigBuilder().build())`

[Related issue](https://github.com/JetBrains/teamcity-kubernetes-plugin/issues/29) in TeamCity K8S support plugin.

**Comment by piyush1594** [comment]
@ekoshkin 

`Config config = new ConfigBuilder().withNamespace("").withMasterUrl(connectionURL).withUsername(username).withPassword(password).build(); `

In this way, you can override the values, but I think if you don't then default values will be filled. Maybe I am wrong but this I have observed over time.

Thanks

**Comment by ekoshkin** [comment]
@piyush1594 You are right. Default values will be used if no values were specified explicitly.
This makes different authentication strategies hard to implement since client code should provide empty values for all autofilled properties to make sure config was built correctly.
One of examples - access to k8s API from application running itself in k8s (as described [here](https://github.com/JetBrains/teamcity-kubernetes-plugin/issues/29))

**Comment by ekoshkin** [comment]
Specifically I wonder if there are any plans to actually fix this?
```
//In future releases (2.4.x) the public constructor will be empty.
  //The current functionality will be provided by autoConfigure().
  //This is a necessary change to allow us distinguish between auto configured values and builder values.
  @Deprecated
  public Config() {
    autoConfigure(this, null);
  }
```

**Comment by traviswinter** [comment]
Wanted to bump this issue - we hit this regularly when running unit tests against config specifically.  If its on a machine that has a specified kubeconfig, it auto-loads those values.  Seems pretty hacky to have to work around, especially when that comment is in the Config default constructor.

I see two options:

1. We remove the autoConfigure from the default constructor as per the comments.  This means that users already utilizing this behaviour will need to explicitly call autoConfigure as per the comment.
2. Add a new constructor that takes a boolean for autoConfigure.  This would leave the current functionality, but provide a way to explicitly create a Config without the autoConfigure.  This seems more hacky but would allow backwards compatibility for users.

I'll create a PR for 1) just to get the discussion going.
