### ISSUE TITLE
How to  disable validation for kubernetes-model？

### ISSUE THREAD

**Issue by tangchn** [fabric8io/kubernetes-client#1059]
When spring-boot and kubernetes-client are used together, write operations via kubernetes-client become slowly(**200ms** -> **6000ms**).

I traced the method and found that validation is executed in the `build()` method(eg. `ReplicationControllerBuilder.java`).  

The reason that validation in kubernetes-model is **activated** is that spring-boot-web include the validation jar:

```
<dependency>
    <groupId>org.hibernate</groupId>
    <artifactId>hibernate-validator</artifactId>
    <version>5.3.6.Final</version>
</dependency>
```

However, I can not exclude the hibernate-validator because spring need  validator to validate the Bean.

**Comment by yybear** [comment]
I meet the same problem, Did you solve it?

**Comment by guanchao-yang** [comment]
@tangchn @yybear Do you have any better way, maybe we can provide one default validator impl to ignore kubernetes-client model

**Comment by zackb** [comment]
Any luck here? I am facing the same issue. Did upgrading to 4.x fix the problem? It looks like the code in `ValidtionUtils.java` creates the `Validator` only once rather than on each call. This caused Class.forName on each call when using spring/hibernates validator.
