### ISSUE TITLE
Any plan to support kubernetes 1.10.x？

### ISSUE THREAD

**Issue by zhanjiejun** [fabric8io/kubernetes-client#1062]
Any plan to support kubernetes 1.10.x？

**Comment by zepouet** [comment]
I wonder the same question. Is it compatible without using news feature of K8S 1.10 ?

Thanks a lot.

**Comment by elonmia** [comment]
Any updates on this issue?

Thanks a lot

**Comment by piyush1594** [comment]
Right now, work is going on to support 1.9, which is here #1020

**Comment by philmtd** [comment]
I'd also love to see support for Kubernetes 1.10.x. Creating binary ConfigMaps does not work with the current version.

@zepouet We use this with a k8s 1.10 cluster and it works - the new features don't, though.

**Comment by rohanKanojia** [comment]
I've opened #1235 for upgrading kubernetes-model to latest kubernetes version. So closing this one
