### ISSUE TITLE
kubernetes-server-mock does not set Deployment status

### ISSUE THREAD

**Issue by kunickiaj** [fabric8io/kubernetes-client#1071]
It seems that kubernetes-server-mock does not set the status field of a created deployment. This means that .scale() cannot be called in a test and will cause an NPE if scale is called with wait=true.

Not sure if this is intentional, or just functionality that needs to be added.

**Comment by iocanel** [comment]
@kunickiaj I assume that you are using kubernetes-server-mock in CRUD mode, right?

Yes, in this case the mock server can't possibly know about status. I am not sure of a strategy we could implement in order to support something like this. I am open to discussion though.
