### ISSUE TITLE
Rolling Update StatefulSet Fail when Updating Spec->Selector

### ISSUE THREAD

**Issue by zhoulu312** [fabric8io/kubernetes-client#1076]
I have problem when trying to do rolling update on a stateful set. It seems the implementation is trying to update /spec/selector/matchLabels/deployment in statefulset before actually doing the update [code](https://github.com/fabric8io/kubernetes-client/blob/696a7b60f276f3727ea6743495115416aa2ab929/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RollingUpdater.java#L112).

However, Kubernetes server will reject the api call: 
`{"kind":"Status","apiVersion":"v1","metadata":{},"st
atus":"Failure","message":"StatefulSet.apps \"zookeeper-21d5295dd09747d4b3eb711462bb21e5\" is invalid: spec: Forbidden: updates to statefulse
t spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.","reason":"Invalid","details":{"name":"zookeeper-21d
5295dd09747d4b3eb711462bb21e5","group":"apps","kind":"StatefulSet","causes":[{"reason":"FieldValueForbidden","message":"Forbidden: updates to
 statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.","field":"spec"}]},"code":422}`

The invocation in my code is like:
`k8client.apps().statefulSets().inNamespace(namespace).withName(name).rolling.replace(statefulSet)`

Am I missing something using the rolling update for statefulset here? 

My Kubernetes server version is 1.9.7, fabric8 client version is 3.1.11.

**Comment by zhoulu312** [comment]
I was able to do rolling update on statefulset by using
`k8client.apps().statefulSets().inNamespace(namespace).withName(name).cascading(false).replace(statefulSet)`
My understanding is this will skip scaling down pods in the client and let kubernetes cluster to totally handle update process. My cluster version is 1.9.7, so it will do rolling update on the statefulset if the update strategy is set as "rolling".

**Comment by bfink13** [comment]
The exact definition of cascading() is still a little fuzzy to me when it comes to StatefulSet, but from what I've seen so far it does seem that `rolling()` and `cascading(false)` do the same thing when it comes to StatefulSets. Maybe we can just override `rollUpdate()` to use `cascading(false)` instead?

**Comment by weiyuanzhuang** [comment]
k8client.apps().statefulSets().inNamespace(namespace).withName(name).cascading(false).patch(statefulSet) may help.
it won't scale the pod num to zero then create pod with new vision. 
True rollingUpdate is aplied to statefulSet update.
