### ISSUE TITLE
PATCH did not remove key if value is null (did not match "kubectl patch" behaviour)

### ISSUE THREAD

**Issue by zjjhzx** [fabric8io/kubernetes-client#1079]
**Problem**

When I use kubectl to patch a secret, key will be removed if value == null.
When I use kubernetes-client to patch, value will be replace by null.

**Demo**

- kubectl test

command
``` shell
kubectl create secret generic test-path-null --from-literal=username=produser --from-literal=password=Y4nys7f11
kubectl patch secret test-path-null -p '{"data":{"username":null,"password":"WTRueXM3ZjEx"}}' --v=8
kubectl describe secret test-path-null
kubectl delete secret test-path-null
```
result - key for 'username' is deleted

```
Name:         test-path-null
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
password:  9 bytes
```

- kubernetes-client test

command
``` java
String namespace = "default";
String name = "test-path-null";

KubernetesClient client = new DefaultKubernetesClient();
Secret secret = client.secrets().inNamespace(namespace).withName(name).get();
secret = .secrets()
            .inNamespace(namespace)
            .withName(name)
            .patch(secret);

kubectl create secret generic test-path-null --from-literal=username=produser --from-literal=password=Y4nys7f11
kubectl patch secret test-path-null -p '{"data":{"username":null}}' --v=999
kubectl describe secret test-path-null
```
result - value for key 'username' is null

``` java
java.lang.AssertionError: 
Expected :2
Actual   :1
 <Click to see difference>


	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	...
```

**Discussion**

In kubernetes,  [rfc7386](https://github.com/kubernetes/kubernetes/blob/f8ffbd9d618324750a9f1bd9d0363fcef83786c1/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go#L31) is implemented. But the lib we are using [zjsonpatch](https://github.com/flipkart-incubator/zjsonpatch) only support [rfc6902](https://github.com/flipkart-incubator/zjsonpatch). 

[Strategic Merge Patch](https://github.com/kubernetes/community/blob/e5aeecb27cd2475007b4e81960604f26cd35cd48/contributors/devel/strategic-merge-patch.md#delete-directive)
According to this document, maybe the right op is "DELETE" for key "username", NOT "REPLACE".

Maybe we should consider replacing lib with other implements, such as [java-json-tools/json-patch](https://github.com/java-json-tools/json-patch)?

**Comment by ovaldi** [comment]
This problem still exists, why is this issue closed?

**Comment by rohanKanojia** [comment]
@ovaldi : Fabric8 Kubernetes Client Patch API has improved quite a lot. We now support providing explicit patch types and providing raw Patch strings in DSL. I also wrote a blogpost about this few months ago[0]. In OP's case, we can delete `username` from Secret data like this:
```java
client.secrets()
    .inNamespace("default")
    .withName("test-path-null")
    .patch(PatchContext.of(PatchType.JSON), "[{\"op\": \"remove\", \"path\":\"/data/username\"}]");
```

[0] https://itnext.io/patch-kubernetes-resources-in-java-using-fabric8-kubernetes-client-25e0c68b9cb5
