### ISSUE TITLE
statefulset scale

### ISSUE THREAD

**Issue by howfree** [fabric8io/kubernetes-client#1095]
I created some pods with Kind "StatefulSet",  
how to scale them  by kubernetes-client (Java)  like: kubectl scale --replicas=10  -f koala-decoder.yaml?  
I didn't find related Java codes  in its example folder.
Thanks.

**Comment by piyush1594** [comment]
Hey @howfree 

It can be achieved using 

`client.apps().statefulSets().withName("repl1").scale(5, true);`

Thanks

**Comment by piyush1594** [comment]
Closing it for the time being
