### ISSUE TITLE
Unable to create LimitRange from yaml

### ISSUE THREAD

**Issue by Sufod** [fabric8io/kubernetes-client#1098]
Hi,

I'm encountering a problem to create LimitRange for a namespace.

Everything is working fine if I create the LimitRange object using the DSL, but when I'm trying to load it from a Yaml, I get this exception: 

> io.fabric8.kubernetes.client.KubernetesClientException: No handler found for object:LimitRange(apiVersion=v1, kind=LimitRange, metadata=ObjectMeta(annotations=null, clusterName=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, initializers=null, labels=null, name=limits, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=LimitRangeSpec(limits=[LimitRangeItem(_default={cpu=Quantity(amount=200m, format=null, additionalProperties={}), memory=Quantity(amount=512Mi, format=null, additionalProperties={})}, defaultRequest={cpu=Quantity(amount=50m, format=null, additionalProperties={}), memory=Quantity(amount=192Mi, format=null, additionalProperties={})}, max=null, maxLimitRequestRatio=null, min=null, type=Container, additionalProperties={})], additionalProperties={}), additionalProperties={})
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.<init>(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java:116)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient$4.<init>(DefaultKubernetesClient.java:130)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.resource(DefaultKubernetesClient.java:130)

The Yaml I'm using is fine (working with kubectl).

Here is my code:

`

        if (ns != null) {
            HasMetadata limitRanges = client.limitRanges().load(IOUtils.toInputStream(resources.get("limitRanges"), "utf-8")).get();
            client.resource(limitRanges).inNamespace(namespaceName).createOrReplace();

            // ResourceQuota compute-resource
            HasMetadata computeResources = client.resourceQuotas().load(IOUtils.toInputStream(resources.get("computeResources"), "utf-8")).get();
            client.resource(computeResources).inNamespace(namespaceName).createOrReplace();

            // ResourceQuota object-counts
            HasMetadata objectCounts = client.resourceQuotas().load(IOUtils.toInputStream(resources.get("objectCounts"), "utf-8")).get();
            client.resource(objectCounts).inNamespace(namespaceName).createOrReplace();
        } else throw new SmiteException("No namespace with name " + namespaceName);

`

By looking in 

io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl line 116, then looking at line 282,

it seems that the method handlerOf which should return the handler for an object of kind LimitRange isn't working.

I don't know how I can change the code to register the LimitRange handler, if someone know how to do this it would be really helpful for me !!

Thanks.

**Comment by piyush1594** [comment]
@Sufod 

Thanks for opening the issue. Raised PR #1120

**Comment by piyush1594** [comment]
Closed in #1120
