### ISSUE TITLE
Do you have plan to support Istio v1alpha3 routing API

### ISSUE THREAD

**Issue by zxbu** [fabric8io/kubernetes-client#1102]
Hi:
Do you have planto support Istio ?
Istio 0.8 is LTS version, It would be wonderful if kubernetes-client will support  Istio v1alpha3 routing API.
This is introducation: https://istio.io/docs/reference/config/istio.networking.v1alpha3/

**Comment by hrishin** [comment]
@zxbu [Istio Java API](https://github.com/snowdrop/istio-java-api) could address this need?

**Comment by zxbu** [comment]
@hrishin Thanks, It give me a lot of help, I can use it just only little work. 
By the way:
Do you have plan to totally  support  Istio in kubernetes-client like Deployment Ingress ?
