### ISSUE TITLE
Query parameters are not correctly processed if set in `masterUrl`

### ISSUE THREAD

**Issue by lordofthejars** [fabric8io/kubernetes-client#1104]
https://github.com/fabric8io/kubernetes-client/issues/1089

**Comment by piyush1594** [comment]
@lordofthejars This is by mistake or any reason for this?

**Comment by lordofthejars** [comment]
@piyush1594 Not a mistake it is just to create a branch with the correct issue number.

**Comment by piyush1594** [comment]
Why do you want to create a branch or so? I did not get

**Comment by lordofthejars** [comment]
Because I never work on master, so I create a branch from master containing the local issue number. Then I work there and finally I send the PR from my branch to master (upstream).

**Comment by rohanKanojia** [comment]
@lordofthejars : that's fine, but I think what @piyush1594 is asking here is why have you created another issue for that. If you just need issue number you can use #1089 , right?

**Comment by lordofthejars** [comment]
Ah right I didn't see that it was duplicated.

Duplicated by https://github.com/fabric8io/kubernetes-client/issues/1089

**Comment by piyush1594** [comment]
@lordofthejars I also follow the same process as you do. But I mean the same Rohan said. You got it and fixed it. Thanks
