### ISSUE TITLE
Deployment replace doesn't work for Volume (ConfigMap type) and VolumeMount

### ISSUE THREAD

**Issue by CathySha** [fabric8io/kubernetes-client#1146]
I use ConfigMap as Volume in the deployment.
I'm trying to update a deployment with different Volume and VolumeMount.(see example below)
I tried all the following ways:
1) client().extensions().deployments().inNamespace(namespaceName).withName(deploymentName).replace(deployment);
2) client().extensions().deployments().inNamespace(namespaceName).withName(deploymentName).createOrReplace(deployment);
3) client().extensions().deployments().inNamespace(namespaceName).withName(deploymentName).cascading(false).replace(deployment);
4) client().extensions().deployments().inNamespace(namespaceName).withName(deploymentName).edit().editSpec().editTemplate().editSped().removeAllFromVolumes(volumes).endSpec().endTemplate().endTemplate().endSpec().done();
5) client().extensions().deployments().inNamespace(namespaceName).withName(deploymentName).edit().editSpec().editTemplate().editSped().removeFromVolumes(volume).endSpec().endTemplate().endTemplate().endSpec().done();

All the above commands don't work!...
I also tried :
client().extensions().deployments().inNamespace(namespaceName).withName(deploymentName).edit().editSpec().editTemplate().editSped().AddToVolumes(volume).endSpec().endTemplate().endTemplate().endSpec().done();
and it works.
i.e. only ADD works, but REMOVE doesn't work....

Is it a BUG or not ?
Did I use it in the right way?
I just want to update the deployment with different Volumn (ConfigMap type) and VolumnMount, how should I do?
Thank you!

Example:
The old Deployment is like this: (I only show the main part)

kind: Deployment
metadata:
  name: d2
  namespace: n1
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: x.x.x.x
        imagePullPolicy: IfNotPresent
        name: c2
        resources:
          limits:
            cpu: "1"
            memory: "4294967296"
          requests:
            cpu: 300m
            memory: "536870912"
        volumeMounts:
        - mountPath: /var
          name: configmapvolume1
        - mountPath: /var/a
          name: configmapvolume2
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: a.yml
            path: a.yml
          name: a
        name: configmapvolume1
      - configMap:
          defaultMode: 420
          items:
          - key: c.yml
            path: c.yml
          name: a
        name: configmapvolume2

The new Deployment is like this:(I only show the main part)

kind: Deployment
metadata:
  name: d2
  namespace: n1
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: x.x.x.x
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: "4294967296"
          requests:
            cpu: 300m
            memory: "536870912"
        volumeMounts:
        - mountPath: /var/b
          name: configmapvolume1
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: b.yml
            path: b.yml
          name: b
        name: configmapvolume1

**Comment by CathySha** [comment]
@oscerd As I mentioned above, I tried to use `edit()`, but only ADD worked, REMOVE didn't work. Do you know how to resolve this problem? Thank you.

**Comment by oscerd** [comment]
What version of client are using? What version of Kubernetes or Openshift  are using the client against?

**Comment by oscerd** [comment]
@piyush1594 @rohanKanojia can you give a look here when you have time?

**Comment by CathySha** [comment]
@oscerd 
kubernetes server version v1.9.2
io.fabric8:kubernetes-client: 3.1.10
io.fabric8:kubernetes-model:2.0.8
io.fabric8:zjsonpatch:0.3.0

**Comment by CathySha** [comment]
I’ve found the reason. There was a parameter named "rollbackRevision" and it was set with value 0 in the `deployment` (the input of function `replace`). Because of this parameter, the replace operation always rollback to the previous version. After deleting this parameter (set it to null), the following function works well:
`client().extensions().deployments().inNamespace(namespaceName).withName(deploymentName).replace(deployment);`
