### ISSUE TITLE
Role, RoleBinding, ClusterRole, ClusterRoleBinding handlers are registered with wrong key

### ISSUE THREAD

**Issue by leogps** [fabric8io/kubernetes-client#1152]
https://github.com/fabric8io/kubernetes-client/blob/0f30508c851155f3bf5f717cc381d8ae4b17e1da/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/handlers/KubernetesRoleHandler.java#L38

It should be "Role" not "KubernetesRole". Using Class.getSimpleName() returns the class name. 

Similar issue in the following classes:

- KubernetesRoleBinding

 --> RoleBinding; Affected class KubernetesRoleBindingHandler.

  

- KubernetesClusterRole

 --> ClusterRole; Affected class KubernetesClusterRoleHandler.

  

- KubernetesClusterRoleBinding

 --> ClusterRoleBinding; Affected class KubernetesClusterRoleBindingHandler.

**Comment by fnan-avq** [comment]
Is there any plan to fix this in a coming release ?

**Comment by rohanKanojia** [comment]
Yeah, we'll fix this in coming release

**Comment by traviswinter** [comment]
@rohanKanojia - do you know if there was a reason Kubernetes was added to the front of those class names?  Just to avoid collision with the Openshift resources?  Would this be as simple as renaming them in the kubeschema.json?

**Comment by rohanKanojia** [comment]
ah, no. I need to check

**Comment by rohanKanojia** [comment]
@traviswinter :You're right Kubernetes was added in order to avoid collision with Openshift Role Bindings(Since they were implemented before); I think we need to remove prefixes from here to rename it: https://github.com/fabric8io/kubernetes-client/blob/99cae30b6c162eacc61e9c2c9ef319deaa5b9e28/kubernetes-model/cmd/generate/generate.go#L196-L200

But I'm afraid doing this might break backward compatibility for openshift users.

**Comment by batsatt** [comment]
Can you just change the getKind() implementations to return the correct string constant instead of the (simple) class name? 

We are blocked on this bug.

**Comment by batsatt** [comment]
I've worked around this for now by making renamed copies of the classes and manually registering them. (And no, modifying getKind() was not enough.)

**Comment by traviswinter** [comment]
@rohanKanojia - What do you think we should do here?  Any idea on how we can prevent breaking of Openshift backwards compatibility?  I was looking into just checking for "Kubernetes"+getKind() in Handler but that could potentially break the OpenShift handlers as well.

Going to try and get more familiar with this code (now that I found out how to add the Eclipse key-bindings to IntelliJ :)) so I can be more productive.

**Comment by rohanKanojia** [comment]
@traviswinter : This is creating lots of confusion among users. I think we should move forward with renaming these classes to their proper names and rename Openshift classes with prefixes( I think this would make more sense).

@iocanel @oscerd : thoughts???

**Comment by oscerd** [comment]
+1, makes sense.

**Comment by rohanKanojia** [comment]
@traviswinter : Would be awesome if you can find time to fix this. You just need to rename classes in `generate.go` and resolve some conflicts in client code due to newly  generated model. Otherwise, I would try to send PR this weekend :-)

**Comment by traviswinter** [comment]
@rohanKanojia , sure - can take a stab at it this afternoon.  Any recommendation for the prefixes?  Simply call it "Openshift"+kind?  Would this simply trade the issue from Kubernetes to Openshift?  Or does Openshift require a different pattern for creating their resources?

**Comment by rohanKanojia** [comment]
@traviswinter : No, it's the same pattern. It's just that for an Openshift object  we read from an openshift vendor directory(in case of RoleBinding `github.com/openshift/api/authorization/v1`). If I'm not wrong these Role bindings were introduced earlier in Openshift and then came into kubernetes(the generated classes also look similar). Now kubernetes also supports them so as an openshift user I would prefer to use kubernetes based RoleBindings(that's just my opinion ;-) ).

**Comment by traviswinter** [comment]
Looks like the generate.go changes were not enough - changes to kube-schema.json were required as well, or am I doing something wrong? :)

The generated classes themselves will need to be changed as well for 
 return KubernetesRole.class.getSimpleName();  to work in KubernetesRoleHandler.java.

**Comment by singhania** [comment]
In which version this will be released ?

**Comment by rohanKanojia** [comment]
@singhania : It would be available in next release i.e 4.1.2

**Comment by PMarci** [comment]
Could this be the cause of my Kubernetes RoleBinding fragment not being picked up by the `fabric8-maven-plugin`? It's located in the same (default) directory as other fragments, which are created successfully. I can also see from the logs and by inspecting the generated OpenShift manifest that the equivalent OpenShift RoleBinding is in fact generated.
