### ISSUE TITLE
Are Multiple Resource Types Supported?

### ISSUE THREAD

**Issue by RisingPhorce** [fabric8io/kubernetes-client#1154]
Does the fabric8 kubernetes client support the equivalents of the kubectl commands:

```
kubectl get all

kubectl get all -l "appName=sample"

kubectl get po,svc,deploy
```

I know that client.load(InputStream is) returns multiple types with the common supertype of HasMetadata, but I want to query the cluster for multiple resource types in a single query.

Thanks for the excellent work on the fabric k8s client!

Thanks.

**Comment by rohanKanojia** [comment]
@RisingPhorce : Hm, as per my knowledge this feature is not there in kubernetes-client. But I think this would be a good addition to our project :) . Thoughts @oscerd @iocanel ?
