### ISSUE TITLE
Create a 3.x branch

### ISSUE THREAD

**Issue by oscerd** [fabric8io/kubernetes-client#1167]
Some projects are still using Kube-client 3.1.x or 3.0.x, it would be good to have a branch for them where we can backport useful fixes and releasing patched version of K8s client for 3.x

**Comment by oscerd** [comment]
@rohanKanojia may you can have a look at this.

**Comment by rohanKanojia** [comment]
@oscerd : okay, I see. Could you please put some light on some of my queries?

1.) So which openshift versions are we targetting in terms of compatibility in case of `3.x`? From where 
     Should we branch off from master in order to create `3.x`?
2.) How long are we planning to support these `3.x` releases?
3.) How is it's release timeline going to be like, would we be releasing two releases everytime we 
     release? Or would this be specific to FUSE's use case only?

**Comment by oscerd** [comment]
1) We have to think about it, but probably between 3.7 and 3.9. I don't think we have to branch from master, probably we should branch from the last 3.x tag.
2) Until someone ask to backport on old version :-)
3) Each time there is a fix on 3.x we may release a new patched version. I don't think there will be too much. For Fuse this is the case, but it may happen also for other users/organizations.

**Comment by rohanKanojia** [comment]
Okay, I think we should be branching off from 9595df88ed9557db42e6160ef52020be7bdbc561. I've also created a [label](https://github.com/fabric8io/kubernetes-client/issues/labels) for 3.x so that we can keep track of changes which we would be cherry-picking onto this new branch. I've tagged some PRs which I felt were related to `3.x`. For PRs merged since last 3.2.0 release, I guess I have to take a look and cherry-pick one by one :)

**Comment by lburgazzoli** [comment]
I guess we need also a 3.1.x

**Comment by oscerd** [comment]
yeah. Then we need to take care of the release.

**Comment by rohanKanojia** [comment]
## Update

I've updated these branches as per latest master, @oscerd  @lburgazzoli Please take a look and see if I've missed some commit.

**Comment by oscerd** [comment]
looks good to me. Thanks @rohanKanojia

**Comment by rohanKanojia** [comment]
Closing it since branches have been created :-)
