### ISSUE TITLE
Non-daemon dispatcher thread leak

### ISSUE THREAD

**Issue by rvansa** [fabric8io/kubernetes-client#1169]
I am registering a watcher on pods and despite both the watcher and the client are closed, I have a non-daemon `OkHttp Dispatcher` thread left running. 

I believe this is happening because the `WatchConnectionManager` creates a new `OkHttpClient` but it does not release its resources in `close`: it releases the websocket, it's own executor but not the dispatcher.

**Comment by rohanKanojia** [comment]
@rvansa : Hey, This creation of new client in WatchConnectionManager was intended for stopping connection leaks. But I it got reverted in #1157 . Could you please test it again with SNAPSHOT version and see if it's still reproducible?

https://github.com/fabric8io/kubernetes-client/blob/3bf0cc75fb7cb66aed7788a93e50b1a46ee09ce2/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java#L81-L90
