### ISSUE TITLE
Use v1beta1 for CronJob

### ISSUE THREAD

**Issue by chrisjs** [fabric8io/kubernetes-client#1172]
Currently `v2alpha1` is being used & deprecated since k8s 1.8. The recommended version is `v1beta1`.

This is a followup issue to the conversation starting at https://github.com/fabric8io/kubernetes-client/issues/770#issuecomment-411082595

@rohanKanojia - would be great if this made it into next weeks release, thanks!

**Comment by rohanKanojia** [comment]
Right now in kubernetes-model, we are using `v2alpha1` as default apiVersion, we need to change there also https://github.com/fabric8io/kubernetes-model/blob/8c739e796e841ffea858306254d7de6d6451304c/cmd/generate/generate.go#L159
