### ISSUE TITLE
Send empty/null response to Callback for exec commands that have no textual feedback.

### ISSUE THREAD

**Issue by emilojkovic** [fabric8io/kubernetes-client#1173]
The [ExecPipesExample](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ExecPipesExample.java) uses an ExecWatch object and InputStreamPumper to execute a command in a pod. 

When a command with textual feedback (ie. `ls`, `pwd`, `echo "Hello World"`, etc.) is executed, the Callback object provided to the InputStreamPumper is correctly called with the response text. However, when a command with no feedback is executed (ie. `cd`, `touch hello.txt`, etc.) is executed, the callback function is not called at all.

Because of this, there is no signal that the command has finished executing. I would like to request for a null/empty string/some other default representing null to be sent back through the websocket & InputStreamPumper/Callback for commands that do not have textual feedback. This will standardize the way all commands are executed into a pod (it will always return something -- either the response text or a null) and will allow users to recognize when any command has finished executing.

**Comment by rohanKanojia** [comment]
@emilojkovic : Yeah, it makes sense to provide response in use cases where we don't get any textual feedback. This issue doesn't seem that complicated. Would be really awesome if you could submit a quick PR for this :)
