### ISSUE TITLE
Impersonate-Extra keys may be specified multiple times

### ISSUE THREAD

**Issue by gastaldi** [fabric8io/kubernetes-client#1179]
According to https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation, the `Impersonate-Extra` HTTP header can be specified multiple times, however `RequestConfig.setImpersonatorExtra` only accepts a single value for each entry.

**Comment by rohanKanojia** [comment]
@gastaldi : Did you filed this via accident ;-) ?
