### ISSUE TITLE
Explicit sleep on the thread can make tests flaky

### ISSUE THREAD

**Issue by bartoszmajsak** [fabric8io/kubernetes-client#1182]
I see there are tests which wait until the resource is destroyed by explicitly waiting 30s. This has two problems at least:

  * it doesn't guarantee that condition is met 
  * if it's met faster we waste time sitting idle and the whole build is slower for no reason

https://github.com/fabric8io/kubernetes-client/blob/7ea9ce885f9fad72949db6e3f5cc8dceb8ce8766/kubernetes-itests/src/test/java/io/fabric8/openshift/RouteIT.java#L106

If there is a way in the client to check if the resource does not exist we could think about using polling instead? For example by using this little library https://github.com/awaitility/awaitility/

**Comment by rohanKanojia** [comment]
@bartoszmajsak : Yep, I remember you pointed this out earlier also. But somehow I forgot to get rid of these .

**Comment by piyush1594** [comment]
@bartoszmajsak @rohanKanojia I actually did this for RT's we can do the same thing here also https://github.com/fabric8io/kubernetes-client/pull/1121/files

**Comment by rohanKanojia** [comment]
@dev-gaur : Would you like to work on this??
