### ISSUE TITLE
Resources export

### ISSUE THREAD

**Issue by pk044** [fabric8io/kubernetes-client#1187]
Is exporting resources currently supported? Right now I am serializing them with Gson and I have to exclude certain fields to make them eligible to be imported later. I am not sure if this way is correct, since your model is made a little bit different - at least regarding the requests in container's requests:

Serialized object:

``"resources":{
                     "requests":{
                        "cpu":{
                           "amount":"100m"
                        },
                        "memory":{
                           "amount":"256Mi"
                        }
                     }
                  }``

Same .json resource, present and working on Kubernetes:

``"resources": {
              "requests": {
                "cpu": "100m",
                "memory": "256Mi"
              }
            }``

When I load my exported resource, I get this in return:

`io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: http://localhost:8001/apis/apps/v1/namespaces/default/replicasets/moldy-oyster-mysql-8477595487. Message: ReplicaSet in version "v1" cannot be handled as a ReplicaSet: v1.ReplicaSet: Spec: v1.ReplicaSetSpec: Template: v1.PodTemplateSpec: Spec: v1.PodSpec: Containers: []v1.Container: v1.Container: Resources: v1.ResourceRequirements: Requests: unmarshalerDecoder: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$', error found in #10 byte of ...|:{"cpu":"","memory":|..., bigger context ...|":1},"resources":{"limits":{},"requests":{"cpu":"","memory":""}},"terminationMessagePath":"/dev/term|.... Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=ReplicaSet in version "v1" cannot be handled as a ReplicaSet: v1.ReplicaSet: Spec: v1.ReplicaSetSpec: Template: v1.PodTemplateSpec: Spec: v1.PodSpec: Containers: []v1.Container: v1.Container: Resources: v1.ResourceRequirements: Requests: unmarshalerDecoder: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$', error found in #10 byte of ...|:{"cpu":"","memory":|..., bigger context ...|":1},"resources":{"limits":{},"requests":{"cpu":"","memory":""}},"terminationMessagePath":"/dev/term|..., metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={})`

It loads correctly when i fix the json file as shown for the config present on Kubernetes.

So if I want to export the resources, I have to fix the values by registering a JsonSerializer that fixes the mappings for certain classes.

Is there any possibility to make this better?

**Comment by rohanKanojia** [comment]
There is a method in SerializationUtils for deserializing to yaml:
https://github.com/fabric8io/kubernetes-client/blob/e36599078376894e30f2ca41a8fb1fb14f4fe310/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/FullExample.java#L117-L120
