### ISSUE TITLE
How can I get the “Terminating” status in io.fabric8.kubernetes-client

### ISSUE THREAD

**Issue by cainzhong** [fabric8io/kubernetes-client#1189]
I am curious about how can I get the "Terminating" status? Is there a corresponding method in io.fabric8.kubernetes-client of "kubectl describe pod [pod name]"
For detail, please see https://stackoverflow.com/questions/52033483/how-can-i-get-the-terminating-status-in-io-fabric8-kubernetes-client

**Comment by jeff-1amstudios** [comment]
```
Pod p = ...;
boolean isTerminating = pod.getMetadata().getDeletionTimestamp() != null;
```

**Comment by rohanKanojia** [comment]
@cainzhong : Were you able to resolve this? If yes, can we close this issue?

**Comment by rohanKanojia** [comment]
@cainzhong : Polite ping, is this issue still valid?

**Comment by grubbins** [comment]
> ```
> Pod p = ...;
> boolean isTerminating = pod.getMetadata().getDeletionTimestamp() != null;
> ```
> 
> Thats how kubectl does it

Thankyou! I have spent far too long reading docs and random other pages I googled trying to find this nugget of information. Now I can finally reconcile the pod objects with what `kubectl` is telling me. :)
