### ISSUE TITLE
how to delete pod forcely?

### ISSUE THREAD

**Issue by lxl910915** [fabric8io/kubernetes-client#1195]
The function as "kubectl delete pod podName --grace-period=0 --force" ?

**Comment by piyush1594** [comment]
Hey @lxl910915 

Can you please try this if it resolves your problem.

```
client.pods().inNamespace(namespace).withName(podName).withGracePeriod(0).delete();
```

**Comment by liuchaoheliang** [comment]
not right now, --force ,how to make

> Hey @lxl910915
> 
> Can you please try this if it resolves your problem.
> 
> ```
> client.pods().inNamespace(namespace).withName(podName).withGracePeriod(0).delete();
> ```

can't resolve this problem, the command --force , how to use the client-api implement?

**Comment by rohanKanojia** [comment]
@liuchaoheliang : Hi, Have you checked if there is such implementation of force deletion in kubernetes rest api? I think it can be implemented

**Comment by skonto** [comment]
@rohanKanojia it seems that force is just a flag to make sure user know what he is doing.
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/delete/delete.go#L160
So graceperiod=0 should do the job.

**Comment by yuwzho** [comment]
> Hey @lxl910915
> Can you please try this if it resolves your problem.
> client.pods().inNamespace(namespace).withName(podName).withGracePeriod(0).delete();

Can we delete one more pods?

**Comment by rohanKanojia** [comment]
@yuwzho : Could you please elaborate what you're saying?

**Comment by yuwzho** [comment]
@rohanKanojia I have some pods to force delete (no specific label set, just names), can I make it in one(as less as possible) api call to save network overhead.

**Comment by rohanKanojia** [comment]
umm, just names. I don't think so. But if you have full objects then you can do something like:

```
client.resourceList(new PodListBuilder().withItems(pod1, pod2, pod3).build()).withGracePeriod(0).delete()
```

**Comment by yuwzho** [comment]
Thank you very much! It solves my problem!
