### ISSUE TITLE
Various improper InterruptedException catch blocks

### ISSUE THREAD

**Issue by ljnelson** [fabric8io/kubernetes-client#1201]
There are several cases in the codebase where `InterruptedException` is caught and then wrapped inside a `KubernetesClientException`.  Here is one arbitrary example:

https://github.com/fabric8io/kubernetes-client/blob/f7843cff15b239e4466167f63c599fc9ca4e4146/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java#L220-L222

As [Brian Goetz writes](https://www.ibm.com/developerworks/library/j-jtp05236/index.html#2.1), the proper way to deal with a caught `InterruptedException` that you're not going to rethrow is to ensure that the thread's interrupted status is properly set.

I would propose that catch blocks of this form contain a `Thread.currentThread().interrupt();` call before throwing the `KubernetesClientException`.

I'll try to submit a PR that addresses this.

**Comment by ljnelson** [comment]
See PR #1202.

**Comment by rohanKanojia** [comment]
Closed via #1202
