### ISSUE TITLE
watch custom resource 

### ISSUE THREAD

**Issue by WywTed** [fabric8io/kubernetes-client#1203]
### what should i take care when watching custom resource
```
client.customResources(dubboServiceCRD, DubboService.class, DubboServiceList.class, DoneableDubboService.class)
                    .inNamespace("wuhuhu").withName(serviceName)
                    .watch(new Watcher<DubboService>() {
                        @Override
                        public void eventReceived(Action action, DubboService resource) {
                            System.out.println("receive: pause");
                            System.out.println(action);
                            System.out.println(resource);
                        }

                        @Override
                        public void onClose(KubernetesClientException cause) {
                            System.out.println("close: pause");
                            System.out.println(cause);
                        }
                    });
```

**Comment by WywTed** [comment]
First, i tried in another cluster and it succeeded， but there was a new problem is  when watching the custromResouce, it threw an exception about deserialize, so i follow the source code and found that the class must defined under the special package name:

#### KubernetesDeserializer.java
```
PACKAGES = new ArrayList<String>(){{
            add("io.fabric8.kubernetes.api.model.");
            add("io.fabric8.kubernetes.api.model.apiextensions.");
            add("io.fabric8.kubernetes.api.model.apps.");
            add("io.fabric8.kubernetes.api.model.authentication.");
            add("io.fabric8.kubernetes.api.model.authorization.");
            add("io.fabric8.kubernetes.api.model.batch.");
            add("io.fabric8.kubernetes.api.model.extensions.");
            add("io.fabric8.kubernetes.api.model.networking.");
            add("io.fabric8.kubernetes.api.model.policy.");
            add("io.fabric8.kubernetes.api.model.rbac.");
            add("io.fabric8.kubernetes.api.model.storage.");
            add("io.fabric8.openshift.api.model.");
        }};
```
i created the new package use these names, move class into the package and it succeed.

**Comment by salaboy** [comment]
Are you getting something like this:

 Caused by: io.fabric8.kubernetes.client.KubernetesClientException: resourceVersion: Invalid value: "v1beta1": strconv.ParseUint: parsing "v1beta1": invalid syntax
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onFailure(WatchConnectionManager.java:198)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:543)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:185)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
 ?

**Comment by WywTed** [comment]
yes i remembered that i saw this.

**Comment by salaboy** [comment]
@WywTed yeah.. that is because the object mapper doesn't have the type.. I will try to create a PR to fix that..

**Comment by Shairam** [comment]
> First, i tried in another cluster and it succeeded， but there was a new problem is when watching the custromResouce, it threw an exception about deserialize, so i follow the source code and found that the class must defined under the special package name:
> #### KubernetesDeserializer.java
> 
> ```
> PACKAGES = new ArrayList<String>(){{
>             add("io.fabric8.kubernetes.api.model.");
>             add("io.fabric8.kubernetes.api.model.apiextensions.");
>             add("io.fabric8.kubernetes.api.model.apps.");
>             add("io.fabric8.kubernetes.api.model.authentication.");
>             add("io.fabric8.kubernetes.api.model.authorization.");
>             add("io.fabric8.kubernetes.api.model.batch.");
>             add("io.fabric8.kubernetes.api.model.extensions.");
>             add("io.fabric8.kubernetes.api.model.networking.");
>             add("io.fabric8.kubernetes.api.model.policy.");
>             add("io.fabric8.kubernetes.api.model.rbac.");
>             add("io.fabric8.kubernetes.api.model.storage.");
>             add("io.fabric8.openshift.api.model.");
>         }};
> ```
> 
> i created the new package use these names, move class into the package and it succeed.

@WywTed  Will you be able to elaborate on this please ?

**Comment by WywTed** [comment]
Maybe you can try to create a package named with one of these below
~~~
PACKAGES = new ArrayList<String>(){{
            add("io.fabric8.kubernetes.api.model.");
            add("io.fabric8.kubernetes.api.model.apiextensions.");
            add("io.fabric8.kubernetes.api.model.apps.");
            add("io.fabric8.kubernetes.api.model.authentication.");
            add("io.fabric8.kubernetes.api.model.authorization.");
            add("io.fabric8.kubernetes.api.model.batch.");
            add("io.fabric8.kubernetes.api.model.extensions.");
            add("io.fabric8.kubernetes.api.model.networking.");
            add("io.fabric8.kubernetes.api.model.policy.");
            add("io.fabric8.kubernetes.api.model.rbac.");
            add("io.fabric8.kubernetes.api.model.storage.");
            add("io.fabric8.openshift.api.model.");
        }};
~~~
and put your crd class file under the package, or even you can follow the resource code and debug it.

**Comment by rohanKanojia** [comment]
@WywTed : Is watch for custom resources working for you? If yes, Could you please document how to have watch with Custom resources?

**Comment by salaboy** [comment]
Yes, I got it working as well, an example can. be found here: https://github.com/salaboy/k8s-operator

**Comment by Shairam** [comment]
@WywTed Thank you so much .

**Comment by WywTed** [comment]
> @WywTed : Is watch for custom resources working for you? If yes, Could you please document how to have watch with Custom resources?

You can see https://github.com/salaboy/k8s-operator/blob/master/src/main/java/org/salaboy/k8s/operator/AppsOperator.java from salaboy's repository.

**Comment by salaboy** [comment]
@WywTed not the best code ever.. but I hope that it helps to exemplify the watches in action.. 
also if you guys give me a "star" to the repo I will appreciate it :)

**Comment by salaboy** [comment]
Also.. the CRDs for that repo, and the instructions can be found here: https://github.com/salaboy/extending-k8s-with-spring-cloud

**Comment by WywTed** [comment]
> @WywTed Thank you so much .

No problem.
I don't try the latest version, maybe it doesn't exist in the latest version.
We've change to use [kubernetes-client](https://github.com/kubernetes-client/java) to operate k8s resource.

**Comment by Shairam** [comment]
> > @WywTed : Is watch for custom resources working for you? If yes, Could you please document how to have watch with Custom resources?
> 
> You can see https://github.com/salaboy/k8s-operator/blob/master/src/main/java/org/salaboy/k8s/operator/AppsOperator.java from salaboy's repository.

This is also helpful. Thank you

**Comment by Shairam** [comment]
> > @WywTed Thank you so much .
> 
> @Shairam No problem.
> I don't try the latest version, maybe it doesn't exist in the latest version.
> We've change to use [kubernetes-client](https://github.com/kubernetes-client/java) to operate k8s resource.

@WywTed  Btw is [kubernetes-client](https://github.com/kubernetes-client/java) a standard kubernetes client to be used for Java ?

**Comment by rohanKanojia** [comment]
@Shairam : Yes, it's the official client. We're discussing to rename our repo to avoid conflict #1452

**Comment by rohanKanojia** [comment]
But our client is well adopted  and more popular

**Comment by WywTed** [comment]
> > > @WywTed Thank you so much .
> > 
> > 
> > @Shairam No problem.
> > I don't try the latest version, maybe it doesn't exist in the latest version.
> > We've change to use [kubernetes-client](https://github.com/kubernetes-client/java) to operate k8s resource.
> 
> @WywTed Btw is [kubernetes-client](https://github.com/kubernetes-client/java) a standard kubernetes client to be used for Java ?

@Shairam Yes, it is. From the account info(or organization) [kubernetes-client](https://github.com/kubernetes-client) just has been verified by [kubernetes.io]( https://kubernetes.io/docs/reference/using-api/client-libraries/)

**Comment by Shairam** [comment]
Alright thank you @WywTed  :) .

**Comment by Shairam** [comment]
> But our client is well adopted and more popular

@rohanKanojia  Btw is there any documentation for [kubernetes-client](https://github.com/kubernetes-client/java) to perform watch operation for Custom Resources? Could you please suggest me if there is one ?

**Comment by WywTed** [comment]
![image](https://user-images.githubusercontent.com/12699301/59250635-6d49a900-8c5a-11e9-8e2e-bf0b32b811d0.png)
![image](https://user-images.githubusercontent.com/12699301/59250824-e6e19700-8c5a-11e9-99ad-c57e222b28d2.png)

KubernetesDeserializer.java
![image](https://user-images.githubusercontent.com/12699301/59250935-27d9ab80-8c5b-11e9-8751-4c2b1d87bdb4.png)
![image](https://user-images.githubusercontent.com/12699301/59251007-5bb4d100-8c5b-11e9-9041-c061c20a14a4.png)

From the picture, you can see, first you should create package with the special name defined in the source code and put your own CRD class under the special package.

**Comment by rohanKanojia** [comment]
@WywTed : Thanks a lot for helping. @Shairam there is one example : https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java#L164


But I think it would be nice if we add one example dedicated to watching custom resources which is well documented. Could anyone please raise a PR please?
