### ISSUE TITLE
Support for resource type PrometheusRule

### ISSUE THREAD

**Issue by jsjjdzg** [fabric8io/kubernetes-client#1205]
Can you please add support for resource type PrometheusRule

We would like to be able use resource fragments of this kind using the F-M-P.

fabric8io/fabric8-maven-plugin#1377

**Comment by rohanKanojia** [comment]
PrometheusRule is a custom resource, it's support was added in #1472 . There is a pending PR in fabric8-maven-plugin in fabric8-maven-plugin regarding this: https://github.com/fabric8io/fabric8-maven-plugin/pull/1626

**Comment by jsjjdzg** [comment]
thank you~
