### ISSUE TITLE
How to force delete pods by use kubernates-client  api ?

### ISSUE THREAD

**Issue by liuchaoheliang** [fabric8io/kubernetes-client#1211]
sometimes the pods can't delete, use 'withGracePeriod(0)' method desn't work  ... 
kubectl delete pod app-test st --force --grace-period=0
--force   : Does this parameter have interface implementation?

**Comment by rohanKanojia** [comment]
@liuchaoheliang : Is there any such endpoint in kubernetes api for force deletion? Do you have any idea?

**Comment by rohanKanojia** [comment]
Duplicate of #1195
