### ISSUE TITLE
Watch resource versions not correctly tracked resulting in 410 errors on reconnect

### ISSUE THREAD

**Issue by JonathanO** [fabric8io/kubernetes-client#1214]
The WatchConnectionManager incorrectly compares new and current resource versions, leading to it losing track of the resource versions. If it's disconnected and attempt to reconnect this will often lead to a 410 due to a too old resource version being sent on the new watch request.

This happens because resource versions are currently only being updated in the WatchConnectionManager if `currentResourceVersion.compareTo(newResourceVersion) < 0`. Since these variables are Strings this comparison results in in e.g. an update from "9" to "10" being discarded since "9".compareTo("10") > 0.

According to https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#concurrency-control-and-consistency the resourceVersion should be treated as an opaque value, so this comparison could probably be considered incorrect behaviour even if it worked as intended. There's no need to do the check (or the compareAndSet) since messages are guaranteed to be processed in order.

**Comment by ljnelson** [comment]
@rohanKanojia Do you mind if I backport this to the 3.x branch, which currently is (incorrectly, right?) at `3.2-SNAPSHOT`?  I'd like to:
* Backport this fix
* Change the version of various `pom.xml`s to `3.2.1-SNAPSHOT` or whatever is appropriate to indicate that the next release is not `3.2.0` but something else
