### ISSUE TITLE
jackson-dataformat-yaml dependency (2.7.7) ageing 

### ISSUE THREAD

**Issue by k-wall** [fabric8io/kubernetes-client#1223]
The Jackson dependency jackson-dataformat-yaml is currently version 2.7.7 which ageing.
Can kubernetes-client release 4.0.5 be used safely with a newer Jackson release (such as 2.9.5)?

I ran the kubernetes-client, tag 4.0.5, tests against 2.9.5 successfully.  I'm happy to submit a PR if it helps.

**Comment by rohanKanojia** [comment]
@k-wall : Yes, it would be awesome if you could make a PR for this ;-)
