### ISSUE TITLE
Extend and move integrations tests

### ISSUE THREAD

**Issue by rhuss** [fabric8io/kubernetes-client#1226]
Currently, we have integration checks for OpenShift 3.6.0, 3.6.1, 3.7.0 and 3.9.0 running on CircleCI.

Since these tests occupy most of our CircleCI queue (they also take a bit to run) and also the latest versions (3.10 and 3.11alpha are missing), I recommend:

* Moving out these test to the CentOS CI
* Disable tests on 3.6.0 and 3.6.1 (I don't think that they are used significantly) and increase the minimum requirement on OpenShift for kubernetes-client
* Add tests for 3.10 and 3.11alpha

**Comment by rohanKanojia** [comment]
hm, makes sense @iocanel @oscerd thoughts??
