### ISSUE TITLE
VolumeNodeAffinity support

### ISSUE THREAD

**Issue by skonto** [fabric8io/kubernetes-client#1234]
Is this supported somehow?  https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#volumenodeaffinity-v1-core

**Comment by rohanKanojia** [comment]
We can consider adding it's support after upgrading model to v1.11

**Comment by skonto** [comment]
Thanx @rohanKanojia I would like to use it for local testing here: https://issues.apache.org/jira/browse/SPARK-24902

**Comment by skonto** [comment]
Btw @rohanKanojia this is not new to 1.11 this is missing form previous versions too: https://kubernetes.io/blog/2018/04/13/local-persistent-volumes-beta/ like 1.10

**Comment by rohanKanojia** [comment]
Right now client only supports resource type till 1.9 :-( . We haven't upgraded it to 1.10 or 1.11 since then... Although we would be updating model soon.
