### ISSUE TITLE
[Upgrade] Support for Kubernetes/Openshift v.1.11/3.11

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#1235]
We need to  upgrade kubernetes model in order to add support for new Kubernetes resources as requested by community users in #1062 and #1234

**Comment by traviswinter** [comment]
Is there any reason not to update to the latest v1.12?

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md

**Comment by rohanKanojia** [comment]
No, there isn't :P . Since earlier upgrades have been like this( to a version less than the latest release), I thought so.

**Comment by rohanKanojia** [comment]
It wasn't chosen, I just did it seeing previous releases ;-) . Model is generated via [kubernetes-model](https://github.com/fabric8io/kubernetes-client/tree/master/kubernetes-model) project(which got merged into client recently). There is a go script which generates model: [generate.go](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-model/pkg/schemagen/generate.go). Upgrading model is not trivial and it takes lots of effort for moving classes due to changed schema after every update.

**Comment by rohanKanojia** [comment]
Yes, this is in progress. Will provide a PR when ready.

**Comment by davidkarlsen** [comment]
Should the README be updated to reference the updated support?
BTW: 1.13 has been released :)
