### ISSUE TITLE
Unable to pull full repository on Windows 10

### ISSUE THREAD

**Issue by traviswinter** [fabric8io/kubernetes-client#1238]
When I try to pull this repository on my Windows 10 environment I get 2 issues around the filepath length and invalid filename characters.

Example filepath length issue:
kubernetes-model/vendor/github.com/openshift/origin/cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/pkg/client/clientset_generated/internalclientset/typed/settings/internalversion/fake/fake_settings_client.go: Filename too long

Setting "git config --system core.longpaths true" allows me to get to the next issue

Example invalid filename length issue:
error: unable to create file kubernetes-model/vendor/github.com/openshift/origin/cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/cmd/svcat/testdata/responses/clusterserviceclasses?fieldSelector=spec.externalName=user-provided-service.json: Invalid argument

This one is trickier - I can just not pull down the openshift origin, but I'm wary to trust the tests without the full repo.

Can anything be done to support us whacky Windows users?

**Comment by rohanKanojia** [comment]
Seems like this is side-effect of #1216 , are you able to pull other branches; like 3.x/3.1.x??

**Comment by traviswinter** [comment]
> Seems like this got introduced after #1216 , are you able to pull other branches; like 3.x/3.1.x??

Yes!  I was able to import 3.1.x without issue.  Looks like you were correct in your find - any way we can fix it?  Maybe modify those test cases?

**Comment by traviswinter** [comment]
@rohanKanojia - Any idea if this could be fixed?  I was hoping to contribute a little more regularly but this is an annoyance for sure.

**Comment by traviswinter** [comment]
@rohanKanojia - Managed to get a Linux VM up, have all the CLI components working at the project builds.  Do you use a specify IDE?  Eclipse seems to vomit on the maven plugins - (at 44,000 errors currently).

**Comment by rohanKanojia** [comment]
@traviswinter : I use IntelliJ .
