### ISSUE TITLE
VolumeSnapshot support

### ISSUE THREAD

**Issue by pk044** [fabric8io/kubernetes-client#1240]
Are there any chances for https://kubernetes.io/blog/2018/10/09/introducing-volume-snapshot-alpha-for-kubernetes/ support?

Thanks!

**Comment by rohanKanojia** [comment]
@pk044 : Hi, yes there are chances. But can't give any concrete ETA. We do have model upgrade in mind which can introduce these new resources in client. Maybe in the coming sprint we can prioritize it.

**Comment by pk044** [comment]
@rohanKanojia oh, im very sorry then - i should have looked deeper into it before creating an issue here. thank you for the reminder though!
