### ISSUE TITLE
OpenShiftOAuthInterceptor gets new token each time

### ISSUE THREAD

**Issue by Exosik** [fabric8io/kubernetes-client#1241]
After this change:
https://github.com/fabric8io/kubernetes-client/commit/c1a6b10c799d5bef6198f37d331fd344950855a3#diff-1f50b87d0d0cacc403fa370cc659ace2

token is not persisted and each request generates new one.

Possible solution:
move/duplicate "synchronized" section (lines 80-87) to line 67

**Comment by rohanKanojia** [comment]
@Exosik :Would really appreciate if you could raise a PR ;-) .
