### ISSUE TITLE
PodPriority support

### ISSUE THREAD

**Issue by onursatici** [fabric8io/kubernetes-client#1244]
would be nice to have `PodPriority` support: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#example-priorityclass

**Comment by rohanKanojia** [comment]
We would add it after upgrading kubernetes model to the latest kubernetes version

**Comment by balexx** [comment]
@rohanKanojia do you have estimates on when that's happening?

**Comment by rohanKanojia** [comment]
I'm going to prioritize this in coming sprint

**Comment by grzegorzgoldapl** [comment]
Is there any ETA on this?
