### ISSUE TITLE
ExecWebSocketListener always combines stdout and stderr

### ISSUE THREAD

**Issue by PaulFurtado** [fabric8io/kubernetes-client#1246]
Combining stdout and stderr into a single stream makes it impossible for clients to discern stdout from stderr. It's critical for an exec implementation to treat these as separate streams. In unix programming, stderr is meant for logging (not just errors) and stdout is meant for output.

For example if you were to send the command:
```
tar -cvf - /some/directory
```
the contents of the tar file generated from the directory is written to the stdout stream and the logging of all of the files in the tar file is written to the stderr stream, so combining these streams results in a corrupt tar file and no log messages.

This was broken in https://github.com/fabric8io/kubernetes-client/pull/1176 which was intended to fix @emilojkovic's issue https://github.com/fabric8io/kubernetes-client/issues/1173.

In 1173, the problem was that the [ExecPipesExample](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ExecPipesExample.java) was only pumping the stdout stream and not doing anything with the stderr stream. To solve this, I believe @emilojkovic could have simply made their code add another InputStreamPumper for stderr. If that wasn't working, then there is another bug we need to track down.

For convenience in cases like @emilojkovic's, it may make sense to add a `combineOutput` option, however.

My teammate @daniel-chu and I are happy to make a PR to fix this, but we're curious how we should proceed. @emilojkovic would your original issue have been solved if you had added an InputStreamPumper for the error stream?

cc: @rohanKanojia who reviewed the original PR

**Comment by rohanKanojia** [comment]
I think either we should revert that commit on master, or make an exception for cases where commands do not provide textual feedback. Thoughts @iocanel @oscerd ??

**Comment by PaulFurtado** [comment]
Ah, I actually had wrote up a comment talking about how to deal with commands that lack textual feedback but I must have forgotten to post it. When I have some free time today I'll write it up again. In essence, there are three channels here: stdout, stderr, and error. The error channel always completes. It provides a v1.Status object reporting the command's exit code and other error conditions.

**Comment by PaulFurtado** [comment]
So internally, most normal use cases want simple, blocking behavior of executing a command and getting back its output. With this code below, you basically just call exec and get back an ExecResult object containing the exit code and the stdout/stderr strings. The exit code comes from parsing the v1.Status object off of the error channel. Currently, it's not that useful to expose the error channel as a stream because the only thing written to it is that status object, it would be awesome in fabric8 facilitated that.

It might be worth implementing a blocking style like this code below directly in fabric8 so people don't get stumped by the callback API and dealing with output streams. I think, the most useful thing would probably be for the exec method's return value provide a method to wait for the command to finish and get the status information. Even more awesome would be if it provided an option to capture stdout/stderr as well. Seems like this could be implemented without breaking the current API.

But yeah, the below shows that you can definitely run commands that do or don't return any output without any issues. We should definitely revert the commit that broke stderr.
```java
package com.hubspot.connect.kubernetes.client;

import java.io.ByteArrayOutputStream;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Arrays;
import java.util.Optional;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicReference;

import com.hubspot.connect.kubernetes.client.exception.ExecTimeoutException;
import com.hubspot.connect.kubernetes.client.model.SimpleExecResult;

import io.fabric8.kubernetes.api.model.Status;
import io.fabric8.kubernetes.api.model.StatusCause;
import io.fabric8.kubernetes.client.KubernetesClient;
import io.fabric8.kubernetes.client.dsl.ExecListener;
import io.fabric8.kubernetes.client.dsl.ExecWatch;
import io.fabric8.kubernetes.client.utils.Serialization;
import okhttp3.Response;

public class SimpleExec {

  private final KubernetesClient client;
  private final String namespace;
  private final String podName;
  private final String container;
  private final long timeoutMillis;

  public SimpleExec(KubernetesClient client,
                    String namespace,
                    String podName,
                    String container,
                    long timeoutMillis) {
    this.client = client;
    this.namespace = namespace;
    this.podName = podName;
    this.container = container;
    this.timeoutMillis = timeoutMillis;
  }

  public SimpleExecResult exec(String... arg) throws ExecTimeoutException {
    // TODO fabric8's client doesnt encode query param args at the moment https://github.com/fabric8io/kubernetes-client/issues/1247
    // but in the meantime we need to escape them ourselves
    String[] escapedArgs = Arrays.stream(arg)
        .map(c -> {
          try {
            return URLEncoder.encode(c, "UTF-8");
          } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(e);
          }
        })
        .toArray(String[]::new);

    ByteArrayOutputStream stdOutStream = new ByteArrayOutputStream();
    ByteArrayOutputStream stdErrStream = new ByteArrayOutputStream();
    ByteArrayOutputStream errChannelStream = new ByteArrayOutputStream();

    CountDownLatch latch = new CountDownLatch(1);
    AtomicReference<Optional<Throwable>> propagatedError = new AtomicReference<>(Optional.empty());
    ExecListener execListener = new ExecListener() {
      @Override
      public void onOpen(Response response) {
      }

      @Override
      public void onFailure(Throwable t, Response response) {
        propagatedError.set(Optional.of(t));
      }

      @Override
      public void onClose(int code, String reason) {
        latch.countDown();
      }
    };

    try (ExecWatch watch = client.pods().inNamespace(namespace).withName(podName).inContainer(container)
        .writingOutput(stdOutStream)
        .writingError(stdErrStream)
        .writingErrorChannel(errChannelStream)
        .usingListener(execListener)
        .exec(escapedArgs)) {
      boolean success = latch.await(timeoutMillis, TimeUnit.MILLISECONDS);
      if (!success) {
        String errorMessage = String.format("Exec with args %s timed out after %d millis", Arrays.toString(escapedArgs), timeoutMillis);
        throw new ExecTimeoutException(errorMessage);
      }
    } catch (InterruptedException e) {
      throw new RuntimeException(e);
    }

    if (propagatedError.get().isPresent()) {
      throw new RuntimeException(propagatedError.get().get());
    }
    return new SimpleExecResult(stdOutStream.toByteArray(), stdErrStream.toByteArray(), getExitCode(errChannelStream));
  }

  private int getExitCode(ByteArrayOutputStream errChannelStream) {
    Status status = Serialization.unmarshal(errChannelStream.toString(), Status.class);

    if (status.getStatus().equals("Success")) {
      return 0;
    }
    return Integer.parseInt(status.getDetails().getCauses().stream()
        .filter(cause -> cause.getReason().equals("ExitCode"))
        .map(StatusCause::getMessage)
        .findFirst()
        .orElseThrow(() -> new RuntimeException(String.format("Status is not SUCCESS but contains no exit code - Status: %s", status.toString()))));
  }
}
```

```java
package com.hubspot.connect.kubernetes.client.model;

import java.io.UnsupportedEncodingException;

public class SimpleExecResult {
  private final byte[] stdout;
  private final byte[] stderr;
  private final int exitCode;

  public SimpleExecResult(byte[] stdout,
                          byte[] stderr,
                          int exitCode) {
    this.stdout = stdout;
    this.stderr = stderr;
    this.exitCode = exitCode;
  }

  public byte[] getStdout() {
    return stdout;
  }

  public byte[] getStderr() {
    return stderr;
  }

  public int getExitCode() {
    return exitCode;
  }

  public String getStdoutString(String encoding) throws UnsupportedEncodingException {
    return new String(stdout, encoding);
  }

  public String getStderrString(String encoding) throws UnsupportedEncodingException {
    return new String(stderr, encoding);
  }

}
```

```java

+package com.hubspot.connect.kubernetes.client.exception;
+
+public class ExecTimeoutException extends Exception {
+  public ExecTimeoutException(String message, Exception cause) {
+    super(message, cause);
+  }
+
+  public ExecTimeoutException(String message) {
+    super(message);
+  }
+
+  public ExecTimeoutException(Exception cause) {
+    super(cause);
+  }
+}
```

**Comment by oscerd** [comment]
> I think either we should revert that commit on master, or make an exception for cases where commands do not provide textual feedback. Thoughts @iocanel @oscerd ??

I'm ok with reverting this.

**Comment by oliviercoma** [comment]
@PaulFurtado Thanks for your code, it's exactly what I needed for the exit code.
I noticed a small issue though: onClose will not be called in case onFailure is called. Hence, latch will not count down, and timeout will happen => success = false. Consequently, ExecTimeoutException will be thrown instead of propagating the exception.

**Comment by daniel-chu** [comment]
Good catch, thanks @oliviercoma - looks like they're mutually exclusive https://github.com/fabric8io/kubernetes-client/blob/1d09dd8a4d847f1b7811a37a6a746c399856d888/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java#L59
