### ISSUE TITLE
URL parameters are not escaped in many methods

### ISSUE THREAD

**Issue by PaulFurtado** [fabric8io/kubernetes-client#1247]
In some cases this makes it impossible to pass certain arguments to APIs. In other cases, if a user of this client is handling untrusted user input, it can be a security issue since end users would be able to inject arbitrary unintended parameters into URLs.

If you look at the exec function in https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java the code for putting command arguments in the URL is currently written as:
```java
    public ExecWatch exec(String... command) {
        StringBuilder sb = new StringBuilder();
        String[] actualCommands = command.length >= 1 ? command : EMPTY_COMMAND;

        sb.append("exec?command=");

        boolean first = true;
        for (String cmd : actualCommands) {
            if (first) {
                first = false;
            } else {
                sb.append("&command=");
            }
            sb.append(cmd);
        }
```

So if you call it with:
```java
exec("/bin/sh", "-c", "echo test 2>&1");
```
the command errors out because `&` gets interpreted by the api servers as starting another query parameter and `2>` alone is invalid shell syntax.

Exec isn't the only place this is an issue, it happens in a lot of other places too. Is there a reason to construct  URLs manually with a StringBuilder instead of using okhttp's HttpUrl.Builder class? http://square.github.io/okhttp/3.x/okhttp/okhttp3/HttpUrl.Builder.html

**Comment by oliviercoma** [comment]
This issue should get more attention. It can cause security issues!

**Comment by PaulFurtado** [comment]
Bump

**Comment by rohanKanojia** [comment]
@oliviercoma @PaulFurtado : I would be more than happy to integrate a PR in order to fix this issue. Could anyone of you please raise a PR to fix this if you have some time? Otherwise I would try to fix this before next major release.

**Comment by akvishwakarma27** [comment]
@rohanKanojia I want to fix this issue

**Comment by rohanKanojia** [comment]
@akvishwakarma27 : cool, Would you like to create a PR to fix this?

**Comment by akvishwakarma27** [comment]
@rohanKanojia Sure give me sometime i will create PR and post it here
