### ISSUE TITLE
Anyway to connect to insecure Kubernetes?

### ISSUE THREAD

**Issue by jwlai** [fabric8io/kubernetes-client#1249]
Hi I have a cluster deployed via Docker and see in the config that it added these values... 
 - cluster:
    insecure-skip-tls-verify: true
    server: https://localhost:6445

and then a client-certificate-data and client-key-data

Is there a way to do the insecure-skip-tls-verify in the kubernetesClient?

**Comment by zhoujianhui** [comment]
just set your builder "withTrustCerts(true)"
