### ISSUE TITLE
No adapter available for type:class io.fabric8.kubernetes.client.BatchAPIGroupClient

### ISSUE THREAD

**Issue by carljmosca** [fabric8io/kubernetes-client#1252]
Getting this error on OCP 3.9 with openshift-client  4.1.0

**Comment by rohanKanojia** [comment]
ah, could you please try with 4.0.7? Will get it fixed in next release.

**Comment by carljmosca** [comment]
I am getting the same error.  Should 4.0.7 work with OCP 3.9?

**Comment by rohanKanojia** [comment]
Yes, it is supposed to. This means there was some problem during release process :-( . I think you can use 4.0.4 in the meantime.

**Comment by carljmosca** [comment]
I did not notice earlier but I was getting warnings on the build when I was using the openshift-client.  Apparently there's something about the dependency of the kubernetes-client and commonly named jars.  I assume this is harmless but it did make me want to try the kubernetes-client.

The 4.0.7 version gives this error:

An error occured while processing cronjobs:: Operation: [create]  for kind: [CronJob]  with name: [hello]  in namespace: [moscac-test]  failed.

(I added the name to the CronJob example out of curiosity it but it fails the same with and w/o a name.)

**Comment by rohanKanojia** [comment]
@carljmosca : Are you sure you had set cluster url correctly?

**Comment by carljmosca** [comment]
@rohanKanojia yes, I am beyond that error now and wondering about possible permission issue:

need a bit more than this: An error occured while processing cronjobs:: Operation: [create]  for kind: [CronJob]  with name: [hello]  in namespace: [moscac-job-demo]  failed.

**Comment by carljmosca** [comment]
I don't have minishift running currently but I am willing to try it.  Are you able to run this on the platform or external to it only?

**Comment by carljmosca** [comment]
WIth respect to the Openshift vs Kubernetes clients, this is the warnings I mentioned (or meant to) earlier:

kubernetes-client-4.0.7.jar, openshift-client-4.0.7.jar define 3 overlapping classes: 
  - io.fabric8.kubernetes.client.ConfigFluent
  - io.fabric8.kubernetes.client.ConfigFluentImpl
  - io.fabric8.kubernetes.client.ConfigBuilder
maven-shade-plugin has detected that some class files are
present in two or more JARs. When this happens, only one
single version of the class is copied to the uber jar.
Usually this is not harmful and you can skip these warnings,
otherwise try to manually exclude artifacts based on
mvn dependency:tree -Ddetail=true and the above output.
See http://maven.apache.org/plugins/maven-shade-plugin/

**Comment by carljmosca** [comment]
@rohanKanojia are you able to make this work with the Openshift client or the Kubernetes client?

**Comment by rohanKanojia** [comment]
Umm, I'm not sure what is your question. Are you talking about whether I tested this on Openshift/Kubernetes. I tested it on Openshift, but I can check on minikube also. Or Are you talking about the objects provided by client dsl OpenshiftClient/KubernetesClient? I just updated url for it to work. let me check on minikube also

**Comment by carljmosca** [comment]
I am sorry, I am asking about the client that was, or could be, used.  I don't get the originally reported error when I use the kubernetes client.

**Comment by rohanKanojia** [comment]
@carljmosca : Hey, kubernetes-client `4.1.1` has been released. I checked the jar and now it has got BatchAPIGroupClient. I think we can close this issue. Could you please verify?

**Comment by rohanKanojia** [comment]
Closing this, please reopen if not working
