### ISSUE TITLE
4.1.0 release's pom.xmls versioned 4.0-SNAPSHOT.

### ISSUE THREAD

**Issue by k-wall** [fabric8io/kubernetes-client#1253]
There appears to be a problem with the 4.1.0 release's configuration management.  The pom.xml that comprise the release refer to 4.0-SNAPSHOT rather than the release's version number, 4.1.0. The issue is present on the top-level POM and the children.

The problem appears both in the 4.1.0 tagged files on GitHub:

https://github.com/fabric8io/kubernetes-client/blob/v4.1.0/pom.xml
https://github.com/fabric8io/kubernetes-client/blob/v4.1.0/kubernetes-client/pom.xml

and within the release artefacts themselves:

`curl -L  https://github.com/fabric8io/kubernetes-client/archive/v4.1.0.tar.gz | tar Oxvfz v4.1.0.tar.gz kubernetes-client-4.1.0/pom.xml
`
```
(snip)
  <groupId>io.fabric8</groupId>
  <artifactId>kubernetes-client-project</artifactId>
  <version>4.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>Fabric8 :: Kubernetes :: Project</name>
(snip)
```

**Comment by rohanKanojia** [comment]
ah, apologies for the inconvenience caused. We recently merged kubernetes-model into client and also changed release scripts for project. Looks like I missed something. I will push a fix soon. Could you please use v4.0.4 instead in the meantime?

**Comment by rohanKanojia** [comment]
@k-wall : Hi, I've updated v4.1.0 tag on GitHub and remove all occurrences of 4.0-SNAPSHOT for the time being. Could you please check if it helps your use case? Otherwise, we can do a quick release for 4.1.1 by the end of today or tomorrow. On maven central, I couldn't find poms versioned as 4.0-SNAPSHOT.

**Comment by k-wall** [comment]
@rohanKanojia source code management best practices say it is best not to update a tag once a release made from it is public even if mistakes were made.  Better to bump the minor version and put out a new release.

**Comment by rohanKanojia** [comment]
@k-wall : Hey, kubernetes-client `4.1.1` just got released. Could you please try that out? I checked pom this time and it looks fine. Are we good to close this issue?

**Comment by rohanKanojia** [comment]
@k-wall : Closing this one ;-)
