### ISSUE TITLE
create statefulset, get  A connection to https://kubernetes.default.svc was leaked. Did you forget to close a response body?

### ISSUE THREAD

**Issue by yuandy** [fabric8io/kubernetes-client#1258]
When kubernetesClient.apps().statefulSets().inNamespace(namespace).create(zooPod), get 
WARNING: A connection to https://kubernetes.default.svc was leaked. Did you forget to close a response body?
java.lang.Throwable: response.body().close()

**Comment by traviswinter** [comment]
Seems similar to https://github.com/fabric8io/kubernetes-client/issues/1228 - does this happen everytime you run the code?  Are you running multiple calls at the same time?  Trying to diagnose the issue myself :)
