### ISSUE TITLE
can't seem to replace entities

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/kubernetes-client#126]
I can't seem to replace an entity with an updated version of it as follows
https://gist.github.com/jstrachan/1d7554dcf21f0db1d9ad

I wonder why we null out the resourceVersion - i thought that was required so that it can check for optimistic locking/update tracking?
https://github.com/jstrachan/kubernetes-client/blob/changes/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/HasMetadataOperation.java#L87-87

**Comment by jstrachan** [comment]
FWIW replacing the use of `.replace(entity)` with this code worked around it for now but it'd be nice to be able to just use a replace() function...
```
                    // TODO this should work!
                    // openShiftClient.oAuthClients().withName(name).replace(current);
                    openShiftClient.oAuthClients().withName(name).delete();
                    current.getMetadata().setResourceVersion(null);
                    openShiftClient.oAuthClients().create(current);
```

**Comment by jimmidyson** [comment]
Setting the resource version to null is allowed & should work fine. There is retry logic in master, duplicated from the official golang client, which should prevent this error from occuring. Can you try with that please?

**Comment by jimmidyson** [comment]
This should now be sorted.
