### ISSUE TITLE
Unable to build repo

### ISSUE THREAD

**Issue by traviswinter** [fabric8io/kubernetes-client#1260]
Tried on both Windows 10 and Ubuntu 18.0.4.  Getting issue running mvn install on the model project.  Is there an official repo setup guide?  Or are there some common known quirks contributors are using to get past this?

Running on OpenJDK 8 (tried 7 as well but there were complaints about improper version)

[INFO] Reactor Summary:
[INFO]
[INFO] Fabric8 :: Kubernetes :: Project 4.1-SNAPSHOT ...... SUCCESS [  3.933 s]
[INFO] Fabric8 :: Kubernetes Model Parent ................. SUCCESS [  0.404 s]
[INFO] Fabric8 :: Kubernetes Model Annotator .............. SUCCESS [  0.622 s]
[INFO] Fabric8 :: Kubernetes Model ........................ FAILURE [ 41.456 s]
[INFO] Fabric8 :: Kubernetes :: Java Client ............... SKIPPED
[INFO] Fabric8 :: Kubernetes :: Server Mock ............... SKIPPED
[INFO] Fabric8 :: Openshift :: Java Client ................ SKIPPED
[INFO] Fabric8 :: Openshift :: Server Mock ................ SKIPPED
[INFO] Fabric8 :: Kubernetes :: Client Examples ........... SKIPPED
[INFO] Fabric8 :: Kubernetes :: Platforms ................. SKIPPED
[INFO] Fabric8 :: Kubernetes :: Platforms :: Karaf ........ SKIPPED
[INFO] Fabric8 :: Kubernetes :: Platforms :: Karaf :: Features SKIPPED
[INFO] Fabric8 :: Kubernetes :: Platforms :: Karaf :: Tests SKIPPED
[INFO] Fabric8 :: Kubernetes :: Tests ..................... SKIPPED
[INFO] Fabric8 :: Kubernetes and Openshift :: UberJar 4.1-SNAPSHOT SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 47.616 s
[INFO] Finished at: 2018-11-09T11:10:46-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project kubernetes-model: Compilation failure: Compilation failure:
[ERROR] bootstrap class path not set in conjunction with -source 1.7
[ERROR] No SupportedSourceVersion annotation found on io.sundr.builder.internal.processor.BuildableProcessor, returning RELEASE_6.
[ERROR] Supported source version 'RELEASE_6' from annotation processor 'io.sundr.builder.internal.processor.BuildableProcessor' less than -source '1.7'
[ERROR] No SupportedSourceVersion annotation found on io.sundr.builder.internal.processor.ExternalBuildableProcessor, returning RELEASE_6.
[ERROR] Supported source version 'RELEASE_6' from annotation processor 'io.sundr.builder.internal.processor.ExternalBuildableProcessor' less than -source '1.7'
[ERROR] No SupportedSourceVersion annotation found on io.sundr.resourcecify.internal.processor.ResourcecifyProcessor, returning RELEASE_6.
[ERROR] Supported source version 'RELEASE_6' from annotation processor 'io.sundr.resourcecify.internal.processor.ResourcecifyProcessor' less than -source '1.7'
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :kubernetes-model

**Comment by rohanKanojia** [comment]
ah, this could be due to switching from glide to dep

**Comment by traviswinter** [comment]
That looks to have been merged today - but I've been having these issues since about Tuesday? (went on gitter but no one seems to be there :))

**Comment by rohanKanojia** [comment]
ah, yeah. I'm also facing build failures on ubuntu, I was only able to build using `skipTests` option:
```
[INFO] Compiling 20 source files to /home/harish/Documents/sr/kubernetes-client/kubernetes-model/kubernetes-model/target/test-classes
[WARNING] bootstrap class path not set in conjunction with -source 1.7
[WARNING] No SupportedSourceVersion annotation found on io.sundr.builder.internal.processor.BuildableProcessor, returning RELEASE_6.
[WARNING] Supported source version 'RELEASE_6' from annotation processor 'io.sundr.builder.internal.processor.BuildableProcessor' less than -source '1.7'
[WARNING] No SupportedSourceVersion annotation found on io.sundr.builder.internal.processor.ExternalBuildableProcessor, returning RELEASE_6.
[WARNING] Supported source version 'RELEASE_6' from annotation processor 'io.sundr.builder.internal.processor.ExternalBuildableProcessor' less than -source '1.7'
[WARNING] No SupportedSourceVersion annotation found on io.sundr.resourcecify.internal.processor.ResourcecifyProcessor, returning RELEASE_6.
[WARNING] Supported source version 'RELEASE_6' from annotation processor 'io.sundr.resourcecify.internal.processor.ResourcecifyProcessor' less than -source '1.7'
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ kubernetes-model ---
[INFO] Surefire report directory: /home/harish/Documents/sr/kubernetes-client/kubernetes-model/kubernetes-model/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Error: Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Fabric8 :: Kubernetes :: Project 4.1-SNAPSHOT ...... SUCCESS [  6.065 s]
[INFO] Fabric8 :: Kubernetes Model Parent ................. SUCCESS [  1.192 s]
[INFO] Fabric8 :: Kubernetes Model Annotator .............. SUCCESS [  3.328 s]
[INFO] Fabric8 :: Kubernetes Model ........................ FAILURE [03:22 min]
[INFO] Fabric8 :: Kubernetes :: Java Client ............... SKIPPED
[INFO] Fabric8 :: Kubernetes :: Server Mock ............... SKIPPED
[INFO] Fabric8 :: Openshift :: Java Client ................ SKIPPED
[INFO] Fabric8 :: Openshift :: Server Mock ................ SKIPPED
[INFO] Fabric8 :: Kubernetes :: Client Examples ........... SKIPPED
[INFO] Fabric8 :: Kubernetes :: Platforms ................. SKIPPED
[INFO] Fabric8 :: Kubernetes :: Platforms :: Karaf ........ SKIPPED
[INFO] Fabric8 :: Kubernetes :: Platforms :: Karaf :: Features SKIPPED
[INFO] Fabric8 :: Kubernetes :: Platforms :: Karaf :: Tests SKIPPED
[INFO] Fabric8 :: Kubernetes :: Tests ..................... SKIPPED
[INFO] Fabric8 :: Kubernetes and Openshift :: UberJar 4.1-SNAPSHOT SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:36 min
[INFO] Finished at: 2018-11-09T23:36:31+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project kubernetes-model: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/harish/Documents/sr/kubernetes-client/kubernetes-model/kubernetes-model && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -javaagent:/home/harish/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/home/harish/Documents/sr/kubernetes-client/kubernetes-model/kubernetes-model/target/jacoco.exec -jar /home/harish/Documents/sr/kubernetes-client/kubernetes-model/kubernetes-model/target/surefire/surefirebooter7494231426606755601.jar /home/harish/Documents/sr/kubernetes-client/kubernetes-model/kubernetes-model/target/surefire/surefire3589246889914717184tmp /home/harish/Documents/sr/kubernetes-client/kubernetes-model/kubernetes-model/target/surefire/surefire_07346036085694413981tmp
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :kubernetes-model
harish@harish-Inspiron-3521:~/Documents/sr/kubernetes-client$
```
looks like there is some problem in surefire or in surefire configuration that's causing this problem.

**Comment by rohanKanojia** [comment]
I found [this](https://stackoverflow.com/a/53016532/2830116) StackOverflow Post. Maybe https://issues.apache.org/jira/browse/SUREFIRE-1588 is the reason for failure

**Comment by ljnelson** [comment]
See if adding `-DargLine='jdk.net.URLClassPath.disableClassPathURLCheck=true'` to the `mvn` command line "fixes" the problem.

**Comment by rohanKanojia** [comment]
@traviswinter : In my case I was able to resolve this after upgrading to surefire `3.0.0-M1`

**Comment by traviswinter** [comment]
Works for me with the surefire upgrade
