### ISSUE TITLE
Issue deploying ReplicaSet to extensions/v1beta1

### ISSUE THREAD

**Issue by traviswinter** [fabric8io/kubernetes-client#1271]
When attempting to deploy the following resource:

> apiVersion: extensions/v1beta2
> kind: ReplicaSet
> metadata:
>   name: nginx-deployment2-10101
> spec:
>   replicas: 1
>   selector:
>     matchExpressions:
>       - {key: app, operator: In, values: [nginx]}
>       - {key: deployer, operator: In, values: [distelli]}
>       - {key: deployer, operator: NotIn, values: [fake]}
>       - {key: working, operator: Exists}
>       - {key: testing, operator: DoesNotExist}
>   template:
>     metadata:
>       labels:
>         app: nginx
>         deployer: distelli
>         working: test
>     spec:
>       containers:
>       - name: nginx
>         image: nginx:1.13.3

I get the following exception:

> https://cluster:6443/apis/apps/v1beta2/namespaces/emeka1/replicasets. Message: ReplicaSet in version "v1beta2" cannot be handled as a ReplicaSet: no kind "ReplicaSet" is registered for version "extensions/v1beta2". Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=ReplicaSet in version "v1beta2" cannot be handled as a ReplicaSet: no kind "ReplicaSet" is registered for version "extensions/v1beta2", metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}) resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={})

We build the HasMetadata object and push it through the following code:

`kubeClient.resource(resource).inNamespace(namespace).createOrReplace();`

It looks like Deployments work with extensions/v1beta1, but ReplicaSets do not regardless of namespace provided (or no namespace).

**Comment by rohanKanojia** [comment]
@traviswinter : Does it work when you are using `apps/v1`?

**Comment by traviswinter** [comment]
@rohanKanojia - I checked and v1beta2 is not in my cluster API so that was one issue.  extensions/v1beta1 is however, and I'm still getting the same issue: 

> Error with Kubernetes
> io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.10.18.87:6443/apis/apps/v1beta1/namespaces/default/replicasets. Message: the server could not find the requested resource. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=the server could not find the requested resource, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).
> 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:478) ~[kubernetes-client-4.1.1.jar:?]
> 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:417) ~[kubernetes-client-4.1.1.jar:?]
> 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381) ~[kubernetes-client-4.1.1.jar:?]
> 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344) ~[kubernetes-client-4.1.1.jar:?]
> 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:227) ~[kubernetes-client-4.1.1.jar:?]
> 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:812) ~[kubernetes-client-4.1.1.jar:?]
> 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:386) ~[kubernetes-client-4.1.1.jar:?]
> 	at io.fabric8.kubernetes.client.handlers.ReplicaSetHandler.create(ReplicaSetHandler.java:44) ~[kubernetes-client-4.1.1.jar:?]
> 	at io.fabric8.kubernetes.client.handlers.ReplicaSetHandler.create(ReplicaSetHandler.java:33) ~[kubernetes-client-4.1.1.jar:?]
> 	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java:135) ~[kubernetes-client-4.1.1.jar:?]
> 	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java:59) ~[kubernetes-client-4.1.1.jar:?]

As you can see, its using the latest 4.1.1 release and still not working.  I tried a Deployment against extensions/v1beta1 and it worked fine.  I tried a ReplicaSet with apps/v1 and it deployed fine.  Just the extensions/v1beta1 that its not pathing correctly.  I tried the exact same yaml using kubectl and there were no issues.

Looks like it should be supported - problem with the API routing in the client?
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#replicaset-v1beta1-extensions

**Comment by rohanKanojia** [comment]
@traviswinter : This is due to `apiGroup` being not picked from resource body here:
https://github.com/fabric8io/kubernetes-client/blob/e36599078376894e30f2ca41a8fb1fb14f4fe310/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java#L95-L103

We should add a case for extracting apiGroup also from resource body, just like apiVersion
