### ISSUE TITLE
How to do a rolling update to a deployment

### ISSUE THREAD

**Issue by coderDemo** [fabric8io/kubernetes-client#1281]
How to do a rolling update  a deployment
just change the image versoin

**Comment by VitZhou** [comment]
I also encountered the same problem

**Comment by rohanKanojia** [comment]
Duplicate of #1064

**Comment by coderDemo** [comment]
do like this
`        kubernetesClient.apps().deployments().inNamespace(namespace).withName(serviceToUpdate)
                .edit().editSpec()
                .editTemplate().editSpec().editContainer(0).withImage(newImage).endContainer().endSpec()
                .endTemplate().endSpec().done();
`

**Comment by coderDemo** [comment]
@VitZhou
