### ISSUE TITLE
How to generate auto-generated file?

### ISSUE THREAD

**Issue by stewart-yu** [fabric8io/kubernetes-client#1283]
/help wanted

   I want to use diff API type by replace the repo in https://github.com/fabric8io/kubernetes-client/blob/v4.1.0/kubernetes-model/glide.yaml#L28-L29, using https://github.com/kubernetes/kubernetes. 
   How can i to re-generated the file in https://github.com/fabric8io/kubernetes-client/tree/v4.1.0/kubernetes-model/kubernetes-model/src/main/resources/schema directory?
any one can provider more details step?

**Comment by rohanKanojia** [comment]
Not sure I understand your question. You can simply run build in kubernetes-model by doing a `make` in your working directory. We are not using glide anymore, take a look at Gopkg.lock

**Comment by stewart-yu** [comment]
Forgot it, i using v4.1.0 branch
https://github.com/fabric8io/kubernetes-client/tree/v4.1.0/kubernetes-model

**Comment by stewart-yu** [comment]
@rohanKanojia Thanks for you attention
FYI

- In Branch: `v4.1.0`, the API from `https://github.com/openshift/kubernetes.git` now , but i want it from `https://github.com/kubernetes/kubernetes.git`, where i should change? 
- and then how to re-generated the file in https://github.com/fabric8io/kubernetes-client/tree/v4.1.0/kubernetes-model/kubernetes-model/src/main/resources/schema directory

I'm newer for 'kubernetes-client', could you help me?

**Comment by rohanKanojia** [comment]
I think you should change here: https://github.com/fabric8io/kubernetes-client/blob/827f2c9eaa9067e4150eb8716e447a625245fedd/kubernetes-model/glide.yaml#L24-L28

But I'm not sure how it's gonna impact client. On master we've moved away from glide and are not using dep. Any specific reason you're working on 4.1.0 branch? It's not clear to me what you're trying to achieve.

**Comment by stewart-yu** [comment]
Thanks for your reply. I will check it later

**Comment by stewart-yu** [comment]
i occured anothers problems, have you any idea to fix it? @rohanKanojia 
when i run ` make`, the output like:
```
CGO_ENABLED=0 GO15VENDOREXPERIMENT=1 go build -a ./cmd/generate/generate.go
vendor/github.com/PuerkitoBio/purell/purell.go:33:2: found packages precis (benchmark_test.go) and main (gen.go) in /ycj/kubernetes-model-upstream/src/github.com/fabric8io/kubernetes-model/vendor/golang.org/x/text/secure/precis
vendor/golang.org/x/text/secure/bidirule/bidirule.go:31:2: found packages bidi (bidi.go) and main (gen.go) in /ycj/kubernetes-model-upstream/src/github.com/fabric8io/kubernetes-model/vendor/golang.org/x/text/unicode/bidi
vendor/golang.org/x/net/idna/idna.go:39:2: found packages norm (composition.go) and main (maketables.go) in /ycj/kubernetes-model-upstream/src/github.com/fabric8io/kubernetes-model/vendor/golang.org/x/text/unicode/norm
make: *** [gobuild] Error 1
```

**Comment by rohanKanojia** [comment]
@stewart-yu : ah, they seem like some dependency issues to me(not very good at go though :disappointed: ). During model upgrade I had trouble resolving them with glide so we switched to dep. Could you please try your changes onto latest master instead of 4.1.0 branch? Would be awesome could you please share your branch or a wip PR for the discussion to proceed.

**Comment by stewart-yu** [comment]
/close 
close it, and i fixed it now
thanks for you help @rohanKanojia
