### ISSUE TITLE
Why is KubernetesDeserializer in a package named "internal"?

### ISSUE THREAD

**Issue by seglo** [fabric8io/kubernetes-client#1285]
You must use `KubernetesDeserializer.registerCustomKind` in order to successfully watch `CustomResourceDefinitions`, as implemented in [`CRDExample`](https://github.com/fabric8io/kubernetes-client/blob/v4.1.0/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java).  Yet this type is in a package named "internal".  Does this imply it shouldn't be used by library users?  Should it be moved?

**Comment by rohanKanojia** [comment]
I think it won't be a problem if we move it out of internal package.

**Comment by awaj1234** [comment]
هل سعر البرنامج 5000دولار
