### ISSUE TITLE
Support for DnsConfig

### ISSUE THREAD

**Issue by Dafnafrank** [fabric8io/kubernetes-client#1287]
Hi,
I would like to add the possibility to config as bellow (under Spec)

dnsPolicy: "None"
dnsConfig:
  nameservers:
    - 10.0.0.0
  searches:
    - someurl.com
  options:
    - name: rotate

I could not find a way to do this, Is it supported? (I am using version v3.1.13)
I know there is a way to set the DnsPolicy but could not find how to set the DnsConfig.
final Deployment deployment = new DeploymentBuilder()
            .withNewSpec()//spec
            .withReplicas(replicas)
            .withStrategy(new DeploymentStrategy(strategy)
            .withSelector(new LabelSelector(null, labels))
            .withNewTemplate()//spec.template
            .withNewSpec()//spec.template.spec
            **.withDnsPolicy(dnsPolicy)**
            .endSpec()
            .endTemplate()
            .endSpec()
            .build();

**Comment by Dafnafrank** [comment]
@rohanKanojia 
Hi, Any update to when this release is planned?

**Comment by rohanKanojia** [comment]
@Dafnafrank : I'm planning to release this weekend. We upgraded model to 1.12.12 so it should work with 1.11: https://github.com/fabric8io/kubernetes-client/blob/96d5516587679e458e41450a61a3b680c1347733/kubernetes-model/Gopkg.lock#L165-L170

**Comment by rohanKanojia** [comment]
@Dafnafrank : it might be because of mismatching api versions. Check whether the object you're posting has deprecated apiVersion `extensions/v1beta1`

**Comment by Dafnafrank** [comment]
Thanks for the answer! 
I moved my question to a different issue (https://github.com/fabric8io/kubernetes-client/issues/1291)

**Comment by rohanKanojia** [comment]
@Dafnafrank : kubernetes-client 4.1,.1 has been released. Could you please recheck and close this issue?

**Comment by rohanKanojia** [comment]
Closing this, please reopen if not working as expected
