### ISSUE TITLE
Add a stale bot.

### ISSUE THREAD

**Issue by dev-gaur** [fabric8io/kubernetes-client#1290]
Adding a stale bot would close the issues which were created long ago and might not be relevant now. We can always triage the issues which the bot closes up and re-open them if they are still valid. This might be a good way for some cleansing.

https://github.com/probot/stale

**Comment by rohanKanojia** [comment]
@iocanel @oscerd : thoughts??

**Comment by oscerd** [comment]
I hate stale bot. Really. But in this case it makes sense to close old issues.

In other projects it's really boring.

**Comment by dev-gaur** [comment]
`is:issue is:open created:<2018-01-01 `  lists 126 open issues. All of them probably won't be valid for the current Kubernetes version.

If we add the stale bot, prepare for a flood of stale notification mails! :joy:

**Comment by oscerd** [comment]
:sob:

**Comment by rohanKanojia** [comment]
@dev-gaur : It's been a week since I merged stale bot PR. Why is it not working? Could you please check what we missed?
