### ISSUE TITLE
the API version in the data (extensions/v1beta1) does not match the expected API version (apps/v1)

### ISSUE THREAD

**Issue by Dafnafrank** [fabric8io/kubernetes-client#1291]
Hi,
I am using latest client version (4.1-SNAPSHOT) with kubernetes 1.11.0.
When creating now a deployment we get the error:
"the API version in the data (extensions/v1beta1) does not match the expected API version (apps/v1)"
We create the deployment using:
.extensions()
.deployments()
.inNamespace(namespace)
.create(deployment);

This worked perfectly till now on older client (3.1.8) and same kubernetes version 1.11.0

**Comment by rohanKanojia** [comment]
@Dafnafrank : Deployment has been moved to apps since 4.0.0, Could you please try creating  deployment like this::
https://github.com/fabric8io/kubernetes-client/blob/96d5516587679e458e41450a61a3b680c1347733/kubernetes-itests/src/test/java/io/fabric8/kubernetes/DeploymentIT.java#L66-L91

**Comment by traviswinter** [comment]
If you have no issues deleting them first, I would suggest running the deletion for the extensions:

client
.extensions()
.deployments()
.inNamespace(namespace)
.withName(deploymentName)
.delete();

Then just create it in the apps deployment:

client
.apps()
.deployments()
.inNamespace(namespace)
.withName(deploymentName)
.createOrReplace(deployment);

**Comment by Surykat** [comment]
Hello. I'm facing issue related to this one I guess:

My deployment is using `apiVersion:extensions/v1beta1` at Kubernetes v1.12

client.apps().deployments().inNamespace(DEFAULT_NAMESPACE).create(deployment) works fine, but createOrReplace returns error mentioned in this thread. 

I'm using v4.2 client.

**Comment by rohanKanojia** [comment]
try `client.extensions().deployments.inNamespace(DEFAULT_NAMESPACE).createOrreplace(yourDeployment)`

**Comment by Surykat** [comment]
> try `client.extensions().deployments.inNamespace(DEFAULT_NAMESPACE).createOrreplace(yourDeployment)`

I did, behaviour is exactly the same.

**Comment by rohanKanojia** [comment]
Could you please share full stacktrace and code(along with your deployment spec) which reproduced this error?

**Comment by Surykat** [comment]
```
Stacktrace:

io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://192.168.99.100:8443/apis/apps/v1/namespaces/somenamespace/deployments/somename. Message: the API version in the data (extensions/v1beta1) does not match the expected API version (apps/v1). Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=the API version in the data (extensions/v1beta1) does not match the expected API version (apps/v1), metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:484)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:423)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:387)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:350)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleReplace(OperationSupport.java:267)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleReplace(OperationSupport.java:249)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleReplace(BaseOperation.java:740)
        at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.lambda$replace$1(HasMetadataOperation.java:99)
        at io.fabric8.kubernetes.api.model.apps.DoneableDeployment.done(DoneableDeployment.java:27)
        at io.fabric8.kubernetes.api.model.apps.DoneableDeployment.done(DoneableDeployment.java:6)
        at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:105)
        at io.fabric8.kubernetes.client.dsl.internal.RollableScalableResourceOperation.replace(RollableScalableResourceOperation.java:159)
        at io.fabric8.kubernetes.client.dsl.internal.DeploymentOperationsImpl.replace(DeploymentOperationsImpl.java:98)
        at io.fabric8.kubernetes.client.dsl.internal.DeploymentOperationsImpl.replace(DeploymentOperationsImpl.java:45)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:386)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:381)

```

Deployment DSL:

`DeploymentBuilder()
                .withApiVersion("extensions/v1beta1")
                .withKind("Deployment")
                .withNewMetadata()
                    .withName("somename")
                    .withNamespace("somenamespace")
                .endMetadata()
                .withNewSpec()
                    .withNewStrategy()
                        .withType("RollingUpdate")
                        .withNewRollingUpdate()
                            .withMaxSurge(new IntOrString(1))
                            .withMaxUnavailable(new IntOrString(0))
                        .endRollingUpdate()
                    .endStrategy()
                    .withNewTemplate()
                        .withNewMetadata()
                            .addToAnnotations("annotation", "true")
                            .addToLabels("app", "val")
                        .endMetadata()
                        .withNewSpec()
                            .addToContainers(new ContainerBuilder()
                                    .withNewName("somename")
                                    .withImage("somecontainer")
                                    .withImagePullPolicy("IfNotPresent")
                                    .withPorts(new ContainerPortBuilder().withContainerPort(8000).build())
                                    .withResources(new ResourceRequirementsBuilder()
                                            .addToRequests("cpu", new Quantity("500m"))
                                            .addToRequests("memory", new Quantity("250Mi"))
                                            .addToLimits("cpu", new Quantity("500m"))
                                            .addToLimits("memory", new Quantity("350Mi"))
                                            .build())
                                    .build())
                        .endSpec()
                    .endTemplate()
                .endSpec()
                .build();`

Client:

`client.apps().deployments().inNamespace("somenamespace").createOrReplace(deployment);`

**Comment by wind57** [comment]
is there an equivalent for ingress? I am trying : 

```
client.extensions().ingresses().inNamespace(NAMESPACE).create(ingress);
```

and getting the same:

```
Message: the API version in the data (networking.k8s.io/v1) does not match the expected API version (extensions/v1beta1).
```

I am on version 5.5.0

**Comment by wind57** [comment]
nvm, sorry, the API is diff slightly:

```
client.network().v1().ingresses().inNamespace(NAMESPACE).create(ingress);
```
