### ISSUE TITLE
I get a wrong result when use exec  and params contains '&'

### ISSUE THREAD

**Issue by zxbu** [fabric8io/kubernetes-client#1297]
When the cmd like this 
```
            String cmd = "test -f /data/config.bak && mv -f /data/config.bak /data/config"
            
            kubernetesClient.pods()
                    .inNamespace(namespace)
                    .withName(podName)
                    .writingOutput(pipedOutputStream)
                    .writingError(System.err)
                    .exec("bash", "-c", cmd);
```

but  `mv -f /data/config.bak /data/config` will not run .

I think the reason is   url encoder/decoder, So I try like this, and it worked:

```
           String cmd = "test -f /data/config.bak && mv -f /data/config.bak /data/config"

            kubernetesClient.pods()
                    .inNamespace(namespace)
                    .withName(podName)
                    .writingOutput(pipedOutputStream)
                    .writingError(System.err)
                    .exec("bash", "-c", URLEncoder.encode(cmd, "UTF-8"));
```

**Comment by rohanKanojia** [comment]
I think we need to encode command here as well: 
https://github.com/fabric8io/kubernetes-client/blob/31ddcea6d95cd9a12be6f5ea0aa6285e7ee0d3bf/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java#L235-L240

**Comment by karthikmg** [comment]
Hi @rohanKanojia 

I would like to fix this issue.
This is my first time contributing to open source.

I will use the same **URLEncoder.encode(cmd, "UTF-8")** fix and send a pull request.
