### ISSUE TITLE
client.load(new FileInputStream(args[0])).createOrReplace(); throws nullPointer if resource spec file has "generateName" or resource type "role"

### ISSUE THREAD

**Issue by ajaygk95** [fabric8io/kubernetes-client#1299]
Hello,

I am using io.fabric8 kubernetes java client api (4.1.0) to apply resources from a spec yaml.
1. In the pod spec if i use 
  metadata:
     generateName: ag-pod
Then a null pointer exception is thrown.
2. If the resource spec file has the "role" or "roleBinding" resource a null pointer execption is thrown.

kubectl apply -f <file.yaml> applies these resources without any error.

Please go through the discussion in the below link for further  information.
https://stackoverflow.com/questions/53501540/kubectl-apply-f-spec-yaml-equivalent-in-fabric8-java-api/53522718?noredirect=1#comment94367827_53522718

Cluster information:
io.fabric8: kubernetes-client -> 4.1.0
bash-4.2# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by ajaygk95** [comment]
Thanks @rohanKanojia for the quick reply. 
How can i take [PR 1300](https://github.com/fabric8io/kubernetes-client/pull/1300) and test. Should i build the project with this PR changes or is there a maven jar available ?

**Comment by rohanKanojia** [comment]
You would need to build project with this PR changes, simply pull PR using command:
```
git fetch upstream pull/1300/head:pullRequest1300 && git checkout pullRequest1300
```
and then build a snapshot doing plain `mvn clean install -DskipTests`

**Comment by rohanKanojia** [comment]
@ajaygk95 : Since #1300 has been merged, you should be able to get RoleBindings working now. It should be available in next release. About `generateName`, Could you please try the latest version `4.1.1` which has support for kubernetes 1.12.2?

**Comment by ajaygk95** [comment]
@rohanKanojia : Will test `generateName` with latest 4.1.1 kubeenetes-client api and let you know. 

Does v4.1.1 include [#1300](https://github.com/fabric8io/kubernetes-client/pull/1300). ?

**Comment by rohanKanojia** [comment]
No, I was talking about your comment on `NullpointerException` when using `generateName`

**Comment by ajaygk95** [comment]
> 
> 
> @rohanKanojia : Will test `generateName` with latest 4.1.1 kubeenetes-client api and let you know.
> 
> Does v4.1.1 include [#1300](https://github.com/fabric8io/kubernetes-client/pull/1300). ?

generateName is not working with 4.1.1 or master as well if i use client.load(new FileInputStream(args[0])).createOrReplace().

One small information, whenever my pod-spec.yaml has generateName then
kubectl apply -f <pod.yaml> will FAIL but
kubectl create -f <pod.yaml> will work.

I saw from this [link](https://github.com/kubernetes/kubernetes/issues/44501#issuecomment-294255660) that kubectl apply and create will function differently. 
Does this help.

**Comment by ajaygk95** [comment]
> 
> 
> You would need to build project with this PR changes, simply pull PR using command:
> 
> ```
> git fetch upstream pull/1300/head:pullRequest1300 && git checkout pullRequest1300
> ```
> 
> and then build a snapshot doing plain `mvn clean install -DskipTests`

I built the master branch of fabric8io/kubernetes-client as [#1300](https://github.com/fabric8io/kubernetes-client/pull/1300) was merged  and Role/Role-Bindings are working fine with client.load(new FileInputStream(args[0])).createOrReplace();

Thanks for the help.

**Comment by rohanKanojia** [comment]
@ajaygk95 : np, stay tuned for next release ;-) . Can we close this for now?

**Comment by ajaygk95** [comment]
Yes :)
I will try few things for generateName and if still doesn't work will raise a new ticket. Thanks

**Comment by max5599** [comment]
Hi @ajaygk95, did you find a way to fix the issue with generateName? I'm using the version 4.1.2 and I'm still having the issue.
Thx

**Comment by ajaygk95** [comment]
Hi @max5599. No generateName is still not working with the latest fabric8 client.

**Comment by rohanKanojia** [comment]
@max5599 @ajaygk95 : Could any of you please file an issue separately for `generateName` support?

**Comment by ajaygk95** [comment]
> 
> 
> @max5599 @ajaygk95 : Could any of you please file an issue separately for `generateName` support?

Created. [1373](https://github.com/fabric8io/kubernetes-client/issues/1373)
