### ISSUE TITLE
Unable to customize Jackson ObjectMapper

### ISSUE THREAD

**Issue by viniciusccarvalho** [fabric8io/kubernetes-client#1308]
Hi there, I'm trying to use the library with Kotlin, and I'm reading some CRDs that I have defined, but because the `WatchHTTPManager` class creates a mapper without allowing customization: https://github.com/fabric8io/kubernetes-client/blob/79132f3348d24acb677de3ee20a96da8d1c67c84/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchHTTPManager.java#L51 I can't create add a module to jackson object mapper. Is there a way around this? Adding custom modules on jackson may be required for other usages besides kotlin

Regards

**Comment by salaboy** [comment]
@viniciusccarvalho damn.. I am stuck with this one as well. We might better provide a PR to fix it and hope for a release :)

**Comment by jkremser** [comment]
probably `WatchHTTPManager` class should be initializing the `mapper` field by calling `Serialization.jsonMapper()`, because that one can be easily customized by something like:

```java
Serialization.jsonMapper().configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, 
false);
```

**Comment by novakov-alexey** [comment]
Also faced with issue when trying to deserialize Scala case classes

**Comment by novakov-alexey** [comment]
thanks to @jkremser, I am able to customize mapper like this:
```
Serialization.jsonMapper().registerModule(DefaultScalaModule)
```

**Comment by manusa** [comment]
This should no longer be an issue after #1963 
`WatchHTTPManager` now uses `Serialization` class

Following should work now:
```
Serialization.jsonMapper().configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, 
false);
```
