### ISSUE TITLE
kubernetes versionInfo returns null

### ISSUE THREAD

**Issue by leogps** [fabric8io/kubernetes-client#1309]
The below always returns null because the implementation is not constructing the endpoint properly and is failing to complete the HTTP request correctly.
`VersionInfo versionInfo = kubernetesClient.getVersion();`

In the ClusterOperationsImpl#fetchVersion method, it should be 
`Builder requestBuilder = (new Builder()).get().url(this.config.getMasterUrl() + "/" + this.versionEndpoint);`
The path separator is missing.

Line 43:
https://github.com/fabric8io/kubernetes-client/blob/59e5b9d0f318f4f78f417efaec34050ed8122b8f/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ClusterOperationsImpl.java

**Comment by rohanKanojia** [comment]
Strange, I tested this but it's working for me. Could you please share the Config object which you use to create client?

**Comment by candyleer** [comment]
I have the  same problem,I found the root cause.
we config the client by `Config.fromKubeconfig("")` ,in this method,the masterUrl will not ignore if the `masterUrl` is end with slash,but in default config,the `masterUrl` will detect slash,that makes the problem occur.
```java
 private static boolean loadFromKubeconfig(Config config, String context, String kubeconfigContents, String kubeconfigPath) {
   ....
      if (currentCluster != null) {
        config.setMasterUrl(currentCluster.getServer());
        config.setNamespace(currentContext.getNamespace());
```
```java
private static Config autoConfigure(Config config, String context) {
   ...
    if (!config.masterUrl.endsWith("/")) {
      config.masterUrl = config.masterUrl + "/";
    }
    return config;
  }
```
maybe i can send a pr to fix this?

**Comment by candyleer** [comment]
@rohanKanojia  I have create PR very simple ,#1329
