### ISSUE TITLE
Conflicting ResourceHandler when two different object kinds exist

### ISSUE THREAD

**Issue by geoand** [fabric8io/kubernetes-client#1313]
When trying to load Istio resources from a yaml file that contains an Istio `Policy` using the [Istio Java API](https://github.com/snowdrop/istio-java-api) (which is an extension kubernetes client), I am seeing the following exception:

`java.lang.ClassCastException: me.snowdrop.istio.api.authentication.v1alpha1.Policy cannot be cast to io.fabric8.openshift.api.model.v4_0.Policy`

I tracked down the issue and it seems to be due to how `ResourceHandler` is determined when such a handler is needed.

Basically the `handlerOf` methods in `NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl` and `NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl` simply use the resource `kind` to determine the handler.
And in case of Istio on Openshift, there are two conflicting resources named Policy.

I propose that the apiVersion be used as well.
That can either be done by appending the apiVersion to the existing `getKind` method of `ResourceHandler` (not good in my opinion) or adding getApiVersion to `ResourceHandler` (which is cleaner but would break every `ResourceHandler` implementation).

I'd be glad to supply a PR for this based on your feedback

cc @iocanel @metacosm @mocenas

**Comment by iocanel** [comment]
We need to also take apiVersion into consideration.

**Comment by iocanel** [comment]
@rohanKanojia I think that this needs to be closed, judging by knative Service not conflicting with vanilla Service.
