### ISSUE TITLE
Emergency: additionalProperty ERROR

### ISSUE THREAD

**Issue by Zephery** [fabric8io/kubernetes-client#1315]
After i set additionalProperty to create route, is use createOrplace to replace it, but additionalProperty can't be carried;

create route
![image](https://user-images.githubusercontent.com/14806207/50890684-9eb51300-1435-11e9-968f-8c064d1587cc.png)

and then i replace it
![image](https://user-images.githubusercontent.com/14806207/50890736-bbe9e180-1435-11e9-831f-e368118c938e.png)

but it turns out 'TCPPort:<nil> TCPMode:false' was not carried

here is k8s'logs
![image](https://user-images.githubusercontent.com/14806207/50890289-dec7c600-1434-11e9-9087-c171e9ee7234.png)

**Comment by Zephery** [comment]
@fusesource-ci

**Comment by Zephery** [comment]
Class HasMetadataOperation->replace method->
D doneable = (Doneable)this.getDoneableType().getDeclaredConstructor(this.getType(), Function.class).newInstance(item, visitor);
can't transfer item's additionalProperty to visitor

here is jdk10 code:
![image](https://user-images.githubusercontent.com/14806207/50942623-3feaaa80-14c4-11e9-8d33-b41edcff423e.png)

and variables:
![image](https://user-images.githubusercontent.com/14806207/50942691-7e806500-14c4-11e9-9b5a-747de39c140e.png)

**Comment by Zephery** [comment]
@fusesource-ci

**Comment by oscerd** [comment]
fusesource-ci is a CI job.

**Comment by Zephery** [comment]
Ah~~~~ do u know how to fix this? 
additionalProperties

**Comment by rohanKanojia** [comment]
@Zephery : let me try to reproduce it

**Comment by rohanKanojia** [comment]
@Zephery : yeah, it's not carried. I'm not even sure what purpose it serves. But could you please describe your use case? Why do you need to set something in `additionalProperties` field? I don't see any such field in Route spec.

**Comment by Zephery** [comment]
well, "tcpMode" and "TCPPort: TCPMode:false" are user-defined, i  add it to route and make haproxy to support tcp. But fabric8io/kubernetes-client don't have tcpMode and TCPPort field, so i add it in additionalProperties. When i create route, it success. but when i use createOrReplace method to replace it, additionalProperties can't by carried
