### ISSUE TITLE
Not able to delete job using ttlSecondsAfterFinished

### ISSUE THREAD

**Issue by krishnag9** [fabric8io/kubernetes-client#1320]
This is my spec that I have used to create the job

V1JobSpec jobspec = new V1JobSpec();
jobspec.setTemplate(template);
jobspec.setTtlSecondsAfterFinished(360);

apiInstance.createNamespacedJob(namespace, job, null, null, null);

The above has to create a job and a pod which is happening correctly. So when the job completes it has to delete the job and pod after 360 seconds which is not happening.

**Comment by rohanKanojia** [comment]
@krishnag9 : I think you're using official client. Via fabric8 kubernetes client you can do it like this: https://github.com/fabric8io/kubernetes-client/blob/ea92133a305b79f84673a4a14df19a7c2ae7ff61/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/JobTest.java#L175-L220

**Comment by krishnag9** [comment]
> @krishnag9 : I think you're using official client. Via fabric8 kubernetes client you can do it like this:
> 
> [kubernetes-client/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/JobTest.java](https://github.com/fabric8io/kubernetes-client/blob/ea92133a305b79f84673a4a14df19a7c2ae7ff61/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/JobTest.java#L175-L220)
> 
> Lines 175 to 220 in [ea92133](/fabric8io/kubernetes-client/commit/ea92133a305b79f84673a4a14df19a7c2ae7ff61)
> 
>    Job job1 = new JobBuilder().withNewMetadata() 
>      .withNamespace("test") 
>      .withName("job1") 
>      .withResourceVersion("1") 
>      .endMetadata() 
>      .withNewSpec() 
>      .withParallelism(0) 
>      .endSpec() 
>      .withNewStatus() 
>      .withActive(1) 
>      .endStatus() 
>      .build(); 
>    Job job2 = new JobBuilder().withNewMetadata() 
>      .withNamespace("ns1") 
>      .withName("job2") 
>      .withResourceVersion("1") 
>      .endMetadata() 
>      .withNewSpec() 
>      .withParallelism(0) 
>      .endSpec() 
>      .withNewStatus() 
>      .withActive(1) 
>      .endStatus() 
>      .build(); 
>    Job job3 = new JobBuilder().withNewMetadata().withName("job3").withNamespace("any").and().build(); 
>   
>   server.expect().withPath("/apis/batch/v1/namespaces/test/jobs/job1").andReturn(200, job1).once(); 
>   server.expect().withPath("/apis/batch/v1/namespaces/test/jobs/job1").andReturn(200, new JobBuilder(job1) 
>      .editStatus().withActive(0).endStatus().build()).times(5); 
>   server.expect().withPath("/apis/batch/v1/namespaces/ns1/jobs/job2").andReturn(200, job2).once(); 
>   server.expect().withPath("/apis/batch/v1/namespaces/ns1/jobs/job2").andReturn(200, new JobBuilder(job2) 
>      .editStatus().withActive(0).endStatus().build()).times(5); 
>   
>    KubernetesClient client = server.getClient(); 
>   
>    Boolean deleted = client.batch().jobs().inAnyNamespace().delete(job1, job2); 
>    assertNotNull(deleted); 
>   
>    deleted = client.batch().jobs().inAnyNamespace().delete(job3); 
>    assertFalse(deleted); 
>  } 
>   
>  @Test(expected = KubernetesClientException.class) 
>  public void testDeleteWithNamespaceMismatch() { 
>    Job job1 = new JobBuilder().withNewMetadata().withName("job1").withNamespace("test").and().build(); 
>    Job job2 = new JobBuilder().withNewMetadata().withName("job2").withNamespace("ns1").and().build();

Is it not possible to do with official client

**Comment by krishnag9** [comment]
Is it not possible to delete using official client

**Comment by rohanKanojia** [comment]
@krishnag9 : I don't know since I haven't used it. But I think there must be a way, file an issue on their repository to know more.
