### ISSUE TITLE
kubernetes-model jar contains a log4j.properties file

### ISSUE THREAD

**Issue by vanzin** [fabric8io/kubernetes-client#1327]
This can interfere with user's applications (e.g. if they bundle a configuration file with their app, now it becomes dependent on classpath ordering for things to work).

e.g. https://issues.apache.org/jira/browse/SPARK-25590

Just checked 4.1.1 and it's still there;

```
$ jar tf ~/Downloads/kubernetes-model-4.1.1.jar  | grep log4j
log4j.properties
```

**Comment by vanzin** [comment]
Oops my bad wrong project.

**Comment by vanzin** [comment]
err, seems that model is indeed part of this project now, so reopening. Sorry for the noise.

**Comment by rohanKanojia** [comment]
@vanzin : ah, I see. @iocanel @oscerd Any ideas what purpose does it serve in kubernetes-model? They seem to be added in this commit: https://github.com/fabric8io/kubernetes-model/commit/26bca2df50e5eaf5363e5aa1e79b3a0d855d20b0 

I'm not sure it's relevant anymore(maybe it was used in fabric8-cd context ... ). @vanzin Could you please create a PR to remove this?
