### ISSUE TITLE
Migrate from JUnit 4 to JUnit 5 for the kubernetes-server-mocks

### ISSUE THREAD

**Issue by sdavids13** [fabric8io/kubernetes-client#1331]
More and more systems are migrating to junit5, it would be nice to have the server-mocks provide native JUnit5 suppoert

**Comment by ricardozanini** [comment]
Hi @dev-gaur! are you currently working on this? Do you accept contributions? :)

**Comment by rohanKanojia** [comment]
@dev-gaur @kunal-kushwaha : Are you guys working on it? If not, Could you please unassign issue so that someone else can pick it up?

**Comment by kunal-kushwaha** [comment]
@rohanKanojia: Apologies for the delay. I'm working on it currently was just looking into a few other issues. I'll reference this issue in the coming days.
