### ISSUE TITLE
Please clarify the difference for the kub clients and IAM token expiration

### ISSUE THREAD

**Issue by antonalechnovic** [fabric8io/kubernetes-client#1334]
1. Please clarify what is the difference between this and official kubernetes client?
2. If the token is expired when using "exec" with AWS IAM Authenticator in kubeconfig, does sdk refreshes the token by calling AWS IAM authenticator automatically?

Thanks,

**Comment by rohanKanojia** [comment]
This project was started way before the official kubernetes client. I uses kubernetes sources to generate model for kubernetes resources whereas official uses swagger schema. Plus we've got a fluent DSL for kubernetes resources  and we also support Openshift.

I don't think it refreshes the token, but need to check. Could you please take a look at https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L511 and verify?

**Comment by antonalechnovic** [comment]
Thanks, I've checked the source, it appears to set OAuth token just once, when I call 

aws-iam-authenticator token -i someName
```
{"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1alpha1","spec":{},"status":{"expirationTimestamp":"2019-01-30T15:16:10Z","token":"k8s-aws-v1.someToken"}}
```
I get expirationTimestamp which is about 15 minutes. I will check call hierarchy but I don't see anything refreshing the token.

**Comment by rohanKanojia** [comment]
@antonalechnovic : oh, I see. Could you please create a PR to resolve this issue?

**Comment by jglick** [comment]
#1224 did not implement expiry yet.

**Comment by jglick** [comment]
Compare https://github.com/kubernetes-client/java/issues/290 in the official client.
