### ISSUE TITLE
Determine return code of command executed using exec on a pod.

### ISSUE THREAD

**Issue by ScrapCodes** [fabric8io/kubernetes-client#1336]
Is there a way to determine the return code of the command run by 
```scala
val execWatch = client.pods()
        .withName(podName)
        .writingOutput(baosOut)
        .writingError(baosErr)
        .exec("sh", "-c", command)
```
 In the api, I could not spot a way to capture the exit code of the process run as a result of the given command.

**Comment by ScrapCodes** [comment]
Hi, any update on this issue?

**Comment by rohanKanojia** [comment]
looks like a valid issue, If you have time feel free to submit a PR

**Comment by FerranAgulloLopez** [comment]
Hello:) Any updates on this?

**Comment by shawkins** [comment]
This has been implemented by #3813

**Comment by FerranAgulloLopez** [comment]
True, thanks a lot!

**Comment by shawkins** [comment]
Resolving as a duplicate of #3813
