### ISSUE TITLE
How to use Probe actions on a pod.

### ISSUE THREAD

**Issue by ScrapCodes** [fabric8io/kubernetes-client#1337]
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#probe-v1-core

Actions like ExecAction, HttpGetAction, etc. Classes are available, but I could not find a test or example, in the code base.

**Comment by oscerd** [comment]
Contributions are welcome.

**Comment by eshan1925** [comment]
Hello, 
I am new to Open Source Contributions and also new to this project. May I know what is to be done for this issue in a detailed way?
And providing some sources would be a big help.
Thankyou
