### ISSUE TITLE
Is there a way to query the cluster for an existing priority class?

### ISSUE THREAD

**Issue by Dafnafrank** [fabric8io/kubernetes-client#1344]
Before creating a pod with a certain priority class name, I would like to query the cluster whether this priority is indeed defined in the cluster.
How can I query this?
Thanks

**Comment by rohanKanojia** [comment]
```
client.scheduling().priorityClass().withName("high-priority").get();
```

Please take a look at this example: https://github.com/fabric8io/kubernetes-client/blob/e3a5b393b6d5a2a367feb1b15fca9e1e805fdf2e/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/PodPriorityExample.java#L43-L60
