### ISSUE TITLE
NPE IpAddressMatcherTest

### ISSUE THREAD

**Issue by KurtStam** [fabric8io/kubernetes-client#1351]
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.428 s - in io.fabric8.kubernetes.client.dsl.base.TestUnmarshal
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   IpAddressMatcherTest.testIpRangeMatcher:36 » NullPointer
[INFO] 
[ERROR] Tests run: 51, Failures: 0, Errors: 1, Skipped: 1
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Fabric8 :: Kubernetes :: Project 4.1-SNAPSHOT ...... SUCCESS [ 12.345 s]
[INFO] Fabric8 :: Kubernetes Model Parent ................. SUCCESS [  0.496 s]
[INFO] Fabric8 :: Kubernetes Model :: Common .............. SUCCESS [  1.993 s]
[INFO] Fabric8 :: Kubernetes Model Annotator .............. SUCCESS [  1.093 s]
[INFO] Fabric8 :: Kubernetes Model ........................ SUCCESS [02:17 min]
[INFO] Fabric8 :: Kubernetes :: Java Client ............... FAILURE [ 21.730 s]

**Comment by rohanKanojia** [comment]
Closed via #1350
