### ISSUE TITLE
Is there a Follow Log option?

### ISSUE THREAD

**Issue by epayano** [fabric8io/kubernetes-client#1360]
I see examples for tailing `N` lines with `getLog()` and `watchLog()`, but is there an example of a following a log? I'm referring to the `-f` option when grabbing a pods log.

**Comment by rohanKanojia** [comment]
Looking at the code, it looks like default is follow option. Have you tried without `tailingLines()` parameter?

https://github.com/fabric8io/kubernetes-client/blob/31ddcea6d95cd9a12be6f5ea0aa6285e7ee0d3bf/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java#L192

**Comment by epayano** [comment]
@rohanKanojia thanks! lets closed this
