### ISSUE TITLE
kubernetes-server-mock 4.1.2 NoSuchMethodError

### ISSUE THREAD

**Issue by mariogeorgievft** [fabric8io/kubernetes-client#1368]
Having kubernetes server mock with 4.1.2 results in 

```
[OkHttp Http2Connection] ERROR o.a.z.server.NIOServerCnxnFactory - Thread Thread[OkHttp Http2Connection,5,main] died
java.lang.NoSuchMethodError: okhttp3.internal.http2.Http2Stream.takeHeaders()Lokhttp3/Headers;
	at okhttp3.mockwebserver.MockWebServer$Http2SocketHandler.readRequest(MockWebServer.java:940)
	at okhttp3.mockwebserver.MockWebServer$Http2SocketHandler.onStream(MockWebServer.java:913)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable$1.execute(Http2Connection.java:628)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
It fixes the missing com.sun.tools.jar when using Java 11, however it appears that it has some kind of inconsistency with the mockwebserver dependencies regarding OkHttp3.

**Comment by mariogeorgievft** [comment]
Downgrading to kubernetes-server-mock 4.1.0 fixes the issue, however mvn complains about  Could not find artifact com.sun:tools:jar:1.7 at specified path which is normal, since JDK 11 does not have the tools.jar? 

Any ideas guys?

**Comment by mariogeorgievft** [comment]
Ok doing this and excluding it on 4.1.1 version fixes the issue, but can someone give me confirmation that this actually is ok to do.
```
<dependency>
			<groupId>io.fabric8</groupId>
			<artifactId>kubernetes-server-mock</artifactId>
            <version>4.1.1</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.sun</groupId>
                    <artifactId>tools</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by rohanKanojia** [comment]
@mariogeorgievft: Could you please share a test which produces this `NoSuchMethodError`? I suspect this might be coming from mockwebserver.

**Comment by rohanKanojia** [comment]
@mariogeorgievft : Polite ping, did you get time to test this issue?

**Comment by mariogeorgievft** [comment]
Hello, the problem is indeed from the mockwebserver. 

Test case would be creating a service/config map using the KubernetesServer with true https and true crudMode.

**Comment by rohanKanojia** [comment]
@mariogeorgievft : Tests for creating a ConfigMap are already there in our test suite, Is it something like this? But they don't seem to reproduce your error. 

https://github.com/fabric8io/kubernetes-client/blob/31ddcea6d95cd9a12be6f5ea0aa6285e7ee0d3bf/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ConfigMapCrudTest.java#L32-L60
