### ISSUE TITLE
Add an example for Job Controller

### ISSUE THREAD

**Issue by kolorful** [fabric8io/kubernetes-client#1371]
The repo currently has an example for Cronjob Controller. It would be nice to have an example code for [Job Controller](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/) as well.

**Comment by rohanKanojia** [comment]
@kolorful : Could you please create a PR for this? ;-)

**Comment by kolorful** [comment]
@rohanKanojia  yep submitted https://github.com/fabric8io/kubernetes-client/pull/1372/commits

I was reading the contribution guide and it says assign to issue to myself, but didn't figure out how to do that :)

**Comment by kolorful** [comment]
I think I misunderstood how issue and PR as suppose to work... Didn't know PR will create its own issue. This issue seems a dupe to #1372 now, how could we link them together? 

Sry about the mess, still very green to this.

**Comment by kolorful** [comment]
Dupe #1372, close
