### ISSUE TITLE
Add support for resizeChannel in ExecWebSocketListener

### ISSUE THREAD

**Issue by juju812** [fabric8io/kubernetes-client#1374]
After walk through the `ExecWebSocketListener` I found that currently `resizeChannel` is not supported. 
Is there any plan to support it? Or any other work around here to resize tty while bash execution?

Thx.

**Comment by juju812** [comment]
seems like we can construct command with env to initialize terminal size like this:

```
exec("env", "TERM%3Dxterm", "COLUMNS%3D" + columns, "LINES%3D" + lines, "bash")
```

but without `resizeChannel` support we can't adjust the size online

**Comment by rohanKanojia** [comment]
@juju812 : Hmm, Could you please create a PR for this?

**Comment by juju812** [comment]
@rohanKanojia the workaround is just used for execute bash with tty. If a PR is need, in my view it can be added as an exec example.

Or I need to implement the `resizeChannel` in `ExecWebSocketListener`?

**Comment by rohanKanojia** [comment]
@juju812 : if you have time to create PR with full implementation, then please do. Otherwise, we can add workaround as an example too to resolve confusion if someone else faces the same issue.

**Comment by juju812** [comment]
@rohanKanojia A quick PR is created for the workaround. 

And about the `resizeChannel` implementation, unfortunately I don't have time now, but I'll inform you if I start handling this.

**Comment by rohanKanojia** [comment]
@juju812 : Much appreciated, Thanks :+1:

**Comment by 4qing** [comment]
Hello, I now need this function to implement a web terminal that can dynamically change the size. I want to know if k8s supports this function. Which api is specific, I don’t seem to find this api on the k8s offical document.Thanks! @juju812

**Comment by rohanKanojia** [comment]
@4qing : Maybe you can pick it up where @juju812 left.... We still need to implement resizeChannel in ExecWebSocketListener.

**Comment by 4qing** [comment]
Excuse me, I am bothered again, I looked at the python client implementation,[https://github.com/kubernetes-client/python/pull/515/](https://github.com/kubernetes-client/python/pull/515/),it send message by this way : 
```python
self.k8s_stream.write_channel(4,
                                      json.dumps({"Height": rows,
                                                  "Width": cols}))
```

In our project, it seems that the message is sent in the following way:
```java
private void send(byte[] bytes) throws IOException {
        if (bytes.length > 0) {
            WebSocket ws = webSocketRef.get();
            if (ws != null) {
                byte[] toSend = new byte[bytes.length + 1];
                toSend[0] = 0;
                System.arraycopy(bytes, 0, toSend, 1, bytes.length);
                ws.send(ByteString.of(toSend));
            }
        }
    }
```
Is this function changed the first bit of the array to 4 and then sends the message?
@rohanKanojia

**Comment by candyleer** [comment]
hope for this feature...need resize channel too.

**Comment by candyleer** [comment]
@4qing  hi, do you have any idea how to implement this feature?

**Comment by candyleer** [comment]
@juju812  can you provide the idea of how to implement or some document about this feature,we can help to implement this

**Comment by 4qing** [comment]
Yes, I have some ideas, but it is limited by my low level, it may be ugly, and I have not participated in the open source project before. If you are willing to wait, I can try to contribute this weekend. @candyleer

**Comment by candyleer** [comment]
@4qing  the resize channel,the streamId is 4?

**Comment by 4qing** [comment]
> @4qing the resize channel,the streamId is 4?

yes

**Comment by candyleer** [comment]
@4qing amazing! does anywhere have the specification for this protocol?, eg, 1 for message 2 for err,3 for errorChannel ,4 for resizeChannel

**Comment by 4qing** [comment]
> @4qing amazing! does anywhere have the specification for this protocol?, eg, 1 for message 2 for err,3 for errorChannel ,4 for resizeChannel

I don't know ,I see the python code and try it,and this repo send common data is 0

**Comment by candyleer** [comment]
@4qing thanks,recently I need the resize channel too,so I will learn and may make a PR to support this.

**Comment by candyleer** [comment]
I know in `io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener#send`

**Comment by candyleer** [comment]
I  read the kubenetes code and I know how to do in java client,I will make a PR today

**Comment by 4qing** [comment]
高山仰止，景行行止，虽不能至，心向往之，阿里就算了，向apache 的commiter致敬！
