### ISSUE TITLE
Update compatibility matrix for 4.1.2

### ISSUE THREAD

**Issue by skonto** [fabric8io/kubernetes-client#1376]
There was a new release recently: https://github.com/fabric8io/kubernetes-client/issues/1358 but compatibility matrix is not up to date and we are facing some issues in this one https://github.com/apache/spark/pull/23814 so we are trying to figure out the state of things.

**Comment by rohanKanojia** [comment]
@skonto : We haven't updated model since 4.1.1, I think it should be the same as previous release.
