### ISSUE TITLE
fabric8 deployment Historical release version （历史发布版本 ）API

### ISSUE THREAD

**Issue by wangchuanjian** [fabric8io/kubernetes-client#1377]
怎么实现获取 fabric8 deployment 历史发布版本 API

**Comment by rohanKanojia** [comment]
यकीन नहीं होता कि मैं आपका सवाल समझ गया हूं। क्या आप मुझे बता सकते हैं कि ऐतिहासिक रिलीज से आपका क्या मतलब है? क्या आप kubernetes API लिंक को इंगित कर सकते हैं जो इस मुद्दे को और स्पष्ट कर सकता है? कृपया देखें कि https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kernernetes/examples/DeploymentExamples.java पर यह देखने के लिए कि तैनाती का उपयोग कैसे किया जाता है। इस एपीआई में।

उम्मीद है की वो मदद करदे।

**Comment by wangchuanjian** [comment]
> यकीननहींहोताकिमैंआपकासवालसमझगयाहूं。क्याआपमुझेबतासकतेहैंकिऐतिहासिक रिलीजसेआपकाक्यामतलबहै ？क्याआपkubernetes APIलिंककोइंगितकरसकतेहैंजोइस मुद्देकोऔरस्पष्टकरसकताहै ？कृपयादेखेंकि https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kernernetes/examples/DeploymentExamples.java परयहदेखनेकेलिएकितैनातीका उपयोगकैसेकियाजाताहै。इसएपीआईमें。
> 
> उम्मीदहैकीवोमददकरदे。

There is no example of what I want inside.

**Comment by wangchuanjian** [comment]
> यकीननहींहोताकिमैंआपकासवालसमझगयाहूं。क्याआपमुझेबतासकतेहैंकिऐतिहासिक रिलीजसेआपकाक्यामतलबहै ？क्याआपkubernetes APIलिंककोइंगितकरसकतेहैंजोइस मुद्देकोऔरस्पष्टकरसकताहै ？कृपयादेखेंकि https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kernernetes/examples/DeploymentExamples.java परयहदेखनेकेलिएकितैनातीका उपयोगकैसेकियाजाताहै。इसएपीआईमें。
> 
> उम्मीदहैकीवोमददकरदे。


I want to get deployment historical results through the fabric8io API.

**Comment by rohanKanojia** [comment]
@wangchuanjian : Maybe you're looking for something like this:
```
        List<DeploymentCondition> deploymentConditionList = client.apps().deployments().inNamespace("thisisatest").withName("nginx").get().getStatus().getConditions();
        for(DeploymentCondition deploymentCondition: deploymentConditionList) {
          log("Last transition time: ", deploymentCondition.getLastTransitionTime());
          log("Last Update time: ", deploymentCondition.getLastUpdateTime());
          log("Message: ", deploymentCondition.getMessage());
          log("Reason: ", deploymentCondition.getReason());
          log("Type: ", deploymentCondition.getType());
          log("Status: ", deploymentCondition.getStatus());
        }
```
