### ISSUE TITLE
Is there support for Java 9+

### ISSUE THREAD

**Issue by sskmail14** [fabric8io/kubernetes-client#1379]
Hai All,

I dont know whether is this a better place to ask this question. But still going for it.

Has Java 9(Modularity) support started for this module?

**Comment by rohanKanojia** [comment]
@sskmail14 : Umm, this library is compatible till jdk 11, see #1265 . I haven't tried JDK 9 yet; Do you think any changes are supported on our side in order to support modularity also?

**Comment by rohanKanojia** [comment]
@sskmail14 : Did you get time to revisit this? Could you please check and confirm?
