### ISSUE TITLE
Test coverage missing for multiple resources

### ISSUE THREAD

**Issue by dev-gaur** [fabric8io/kubernetes-client#1381]
The following resources don't have any test coverage

  - [ ] Endpoints
  - [ ] PersistentVolumeClaim
  - [ ] PersistentVolumes
  - [ ] SubjectAccessReview
  - [ ] PodPreset
  - [ ] HorizontalPodAutoscaler
  - [ ] Namespace
  - [ ] ResourceQuota

**Comment by kunal-kushwaha** [comment]
@dev-gaur @rohanKanojia 
Aren't tests already provided for SubjectAccessReview in SubjectAccessReviewAuthTest.java? 

https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/SubjectAccessReviewAuthTest.java

**Comment by rohanKanojia** [comment]
Yeah, but they seem to be testing only basic things. You can add some more tests to that class if you want. I'm also okay if we leave it as it is.

**Comment by rohanKanojia** [comment]
You can add a test for [CustomResourceDefinition](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/) resource also

**Comment by kunal-kushwaha** [comment]
Alright 👍
