### ISSUE TITLE
Enable Dependabot to update dependencies

### ISSUE THREAD

**Issue by gastaldi** [fabric8io/kubernetes-client#1383]
It would be nice if https://dependabot.com were enabled in this repository to automatically update dependencies to their latest versions whenever they are available 

Example: https://github.com/fabric8-launcher/launcher-backend/pull/684

**Comment by rohanKanojia** [comment]
@gastaldi : Thanks for the suggestion. I think it's a good idea.

@oscerd @iocanel @lordofthejars @dev-gaur WDYT?????

**Comment by oscerd** [comment]
It makes sense here. +1.

**Comment by gastaldi** [comment]
Enabled in https://app.dependabot.com/accounts/fabric8io
