### ISSUE TITLE
ValidatingWebhookConfigurationOperationsImpl should be a NonNamespaceOperation

### ISSUE THREAD

**Issue by leogps** [fabric8io/kubernetes-client#1387]
When dealing with ValidatingWebhookConfiguration, namespace should not be specified in the url.
However, when creating a ValidatingWebhookConfiguration throws an exception as it ends up appending namespace to the url.

The following code constructs the URL incorrectly.

```
ValidatingWebhookConfiguration validatingWebhookConfiguration = new ValidatingWebhookConfiguration();
//.....
//.....
//.....
try(KubernetesClient kubernetesClient = new DefaultKubernetesClient(config)) {
            kubernetesClient
                    .resource(validatingWebhookConfiguration)
                    .createOrReplace();
}
```

Constructs:

> https://<server-url>:<server-port>/apis/admissionregistration.k8s.io/v1beta1/namespaces/default/validatingwebhookconfigurations

Instead of:

> https://<server-url>:<server-port>/apis/admissionregistration.k8s.io/v1beta1/validatingwebhookconfigurations

Reproducible with: kubernetes-client-4.1.2.jar

**Comment by rohanKanojia** [comment]
@leogps : Could you please create a quick PR to resolve this?

**Comment by rohanKanojia** [comment]
We need to add this method somehow, but it's autogenerated: https://github.com/fabric8io/kubernetes-client/blob/a33f01b5c71eea2a2f20c354580bb804aa4dc9f2/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/StorageClassOperationsImpl.java#L38-L41

**Comment by leogps** [comment]
I see that the implementation makes use of [jsonschema2pojo](http://www.jsonschema2pojo.org/) to auto-generate the pojos and seems like the Handler and the OperationImpl are also auto-generated. I am not sure how exactly this is accomplished.
Also, a git-blame on [StorageClassOperationsImpl](https://github.com/fabric8io/kubernetes-client/blob/a33f01b5c71eea2a2f20c354580bb804aa4dc9f2/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/StorageClassOperationsImpl.java#L38-L41) suggests that it was copied off of an auto-generated class.
Maybe, that is the way to go about this.

The ideal solution might be to fix the auto-generate logic to include the method properly. 
Also isResourceNamespaced() doesn't suffice I guess. The checkNamespace() should be overridden to return null as OperationSupport#checkNamespace assumes a namespace and resolves to default even if the metadata does not include namespace.

**Comment by rohanKanojia** [comment]
@leogps : I think you're right. If we copy that class from target to dsl, and make changes onto it, it gets overridden. let me create a quick PR myself

**Comment by leogps** [comment]
Just checking if the fix is available in a newer build?

**Comment by rohanKanojia** [comment]
Yeah, you can verify via building snapshot from master

मंगल, 26 मार्च 2019, 08:57 को leogps <notifications@github.com> ने लिखा:
