### ISSUE TITLE
Does the kubernetest-client support NetworkAttachmentDefinition creation? 

### ISSUE THREAD

**Issue by wei0313** [fabric8io/kubernetes-client#1424]
Hi
Does the k8s-client support NetworkAttachmentDefinition? If so, what's the resource type? Is there any examples on this? 

Thanks

**Comment by rohanKanojia** [comment]
@wei0313 : umm, Is it a custom resource?

**Comment by wei0313** [comment]
@rohanKanojia  Yes it is. it's a type introduced by multus plugin.

**Comment by wei0313** [comment]
This is the error message I received 
code
`resources = client.load(new FileInputStream(fileName)).get();`

Exception
`Caused by: com.fasterxml.jackson.databind.JsonMappingException: No resource type found for:k8s.cni.cncf.io/v1#NetworkAttachmentDefinition`

**Comment by rohanKanojia** [comment]
Umm, creation of crds is not that straghtforward right now :-( . Although it's going to be done soon. For now, Please take a look at 
https://github.com/fabric8io/kubernetes-client/blob/7e23f8368a658deeb5cadfbf9b01a12f434b8445/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java#L42-L50

**Comment by wei0313** [comment]
@rohanKanojia  thanks! does that mean I should load the CRD that's for the k8s.cni.cncf.io then resource will be recognized?

**Comment by wei0313** [comment]
@rohanKanojia
I have another question regarding the API. I am looking at the option of adding validation. I am adding my CRDBuilder with `.....withNewValidation().withNewOpenAPIV3Schema().withProperties().endValidation().endSpec().build()`

My question is the "withProperties()" part: I am not sure in what format I should store the in the Map<String, JSONSchemaProps>. Could you provide an example? 

CRD
`....
validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            config:
                 type: string`

**Comment by rohanKanojia** [comment]
Custom resource support got added in #1472 , you can now create resources without having to provide any Pojos, for more information see: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/RawCustomResourceExample.java
