### ISSUE TITLE
Cleanup properties in pom.xml

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#1437]
I would do the following chnages:

1. Group together in a distinct chunk all version properties.
2. Group together in a distinct chunk options version properties.
3. Group togther in a distinct chunk all maven plugin properties
4. Group everyhting else together.
5. Remoce all bundles from pom.xml and into the karaf pom (as they are not needed throughout the rest of the project).

**Comment by iocanel** [comment]
I am wondering if the arquillian bits also need to move away from main pom.

**Comment by rohanKanojia** [comment]
starter issue, still valid
