### ISSUE TITLE
Release 4.2.0

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#1438]
I think we have good enough issues to make a new release. We should do a release as soon as possible.

Thoughts @iocanel @oscerd @gastaldi

**Comment by iocanel** [comment]
I have one additional issue I am working on and hopefully, I'll have a PR
during the weekend.

Either way let's get 4.2.0 early next week.

**Comment by candyleer** [comment]
hope for new version too

**Comment by rohanKanojia** [comment]
https://repo1.maven.org/maven2/io/fabric8/kubernetes-client/4.2.0/
