### ISSUE TITLE
Don't use System.currentTimeMillis for measuring durations

### ISSUE THREAD

**Issue by slandelle** [fabric8io/kubernetes-client#1449]
Using wall clock for measuring time is a very bad idea as NTP can update it anytime, so it might just forward or backward.

You should be using `System.nanotime` instead as it's monotonic.

`System.currentTimeMillis` is being used in `HasMetadataOperation`, `ServiceOperationsImpl` and `BaseOperation` for timeouts.

I suspect weird `HasMetadataOperation#periodicWatchUntilReady` documented as `The need for that is that in some cases a pure watcher approach consistently fails.` is because of this.

We encountered super weird timeouts on a slow machine and it was fixed when we reimplemented `waitUntilReady` based on `System.nanotime` and dropped `periodicWatchUntilReady`.

**Comment by girishramnani** [comment]
I can work on this issue but just would like if someone can verify that this https://github.com/fabric8io/kubernetes-client/pull/1451 was closed because this issue is no longer needed?

**Comment by kunal-kushwaha** [comment]
@rohanKanojia Am I required to document this change in CHANGELOG.md file as well
