### ISSUE TITLE
Generate CustomResource Spec Pojo from Go code or Yaml.

### ISSUE THREAD

**Issue by GrigorievNick** [fabric8io/kubernetes-client#1458]
I want use fabric8 with spark operator, here is spec [SparkAppliactionAPi](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/api.md#sparkapplication-api)
Does any simple way to generate pojo or scala case class for [SparkApplicationSpec](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/api.md#sparkapplicationspec) exist?
Form Yamls or from Go Code?
I try use http://www.jsonschema2pojo.org/ but don't get result.

**Comment by rohanKanojia** [comment]
We need this feature in https://github.com/fabric8io/fabric8-maven-plugin in order to create CRDs via resource fragments.

**Comment by thousandhu** [comment]
I also do the same thing as @GrigorievNick .

**Comment by rohanKanojia** [comment]
@GrigorievNick @thousandhu : Hi, now you can create custom resources directly from yaml in Fabric8 Kubernetes client. Here is an example:

https://github.com/fabric8io/kubernetes-client/blob/141668a882ed8e902c045a5cd0a80f14bd17d132/kubernetes-itests/src/test/java/io/fabric8/kubernetes/RawCustomResourceIT.java#L72

**Comment by rohanKanojia** [comment]
But creating Pojos is not supported at the moment :-(

**Comment by GrigorievNick** [comment]
@rohanKanojia But this API does not have some features like `awaitUtilReady`.

**Comment by rohanKanojia** [comment]
@GrigorievNick : oh, Yeah. Does typed api support `awaitUntilReady` functionality? I think we can add this functionality in typeless api also.

**Comment by rohanKanojia** [comment]
I think this issue is quite important, we should provide some way to automate the creation of Custom Resources POJOs based on some configuration

**Comment by rohanKanojia** [comment]
Related to  https://github.com/fabric8io/kubernetes-client/issues/3642

**Comment by rohanKanojia** [comment]
We have this capability with java generator now https://github.com/fabric8io/kubernetes-client/blob/master/doc/java-generation-from-CRD.md
