### ISSUE TITLE
deployment of new custom resource 

### ISSUE THREAD

**Issue by nzazulinsky** [fabric8io/kubernetes-client#1461]
Hello,

we have a k8s cluster that in one of the namespaces running seldon-core (new custom resource), we are able to deploy with "kubectl apply".

but when running it via our pipeline with fabric8 client (4.1.3) we getting below exception:
"No resource type found for:machinelearning.seldon.io/v1alpha2#SeldonDeployment"

What is the best way to do it (kubectl apply to new CR that the cluster is familiar with)?

**Comment by rohanKanojia** [comment]
@nzazulinsky : Hi, I've worked on improving custom Resource support, I created #1472 recently which ease basic CRUD operations for CustomResources. 

https://github.com/fabric8io/kubernetes-client/blob/f773e1053572f00af4206423366e7375693b737a/kubernetes-itests/src/test/java/io/fabric8/kubernetes/RawCustomResourceIT.java#L57-L100

I hope that would ease CustomResource operations, it would be available in next release.

**Comment by rohanKanojia** [comment]
available in kubernetes client v4.2.2 , for usage please check https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/RawCustomResourceExample.java
