### ISSUE TITLE
Deleting resource race condition

### ISSUE THREAD

**Issue by stanlyDoge** [fabric8io/kubernetes-client#1474]
Issue: After updating from `4.1.2` to `4.2.0` I am encountering a race condition while deleting resources.

Lets say I have this piece of code and the `configMap` `RESOURCE_NAME` is created before:
```
client.configMaps().inNamespace("myproject").withName(RESOURCE_NAME).delete();
ConfigMap deleted = client.configMaps().inNamespace("myproject").withName(RESOURCE_NAME).get();
if (deleted == null) {
    System.out.println("OK");
} else {
    fail("Failed to delete Resource");
}
```
This is 99% failing.

The resource is deleted and cannot be found by `oc get configmap -n myproject` but during the test, it is still there.
Even when I run this test in debug mode it passes.
If I put `Thread.sleep(1000);` right after the first line, everything is ok.

Platform:
 ```
$ oc version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
```

**Comment by rohanKanojia** [comment]
Hmm, i've also faced a delay in performance since we merged #1433

**Comment by stanlyDoge** [comment]
I've uploaded minimal reproducer code [here](https://drive.google.com/open?id=1Ri55lzJg2uJlvu8p8hNCSjeuo6dkrKHy)

**Comment by rohanKanojia** [comment]
cc @iocanel

**Comment by stanlyDoge** [comment]
Not fixed in 4.2.1

**Comment by rohanKanojia** [comment]
Yeah, but that bouncycastle thing was fixed, right??

**Comment by stanlyDoge** [comment]
Yes, it is. Thank you.

**Comment by zhengzepeng** [comment]
I face the problem like that,but when i use Thread.sleep to do some delay,it doesn't work~the resource still here,it can't delete!!!!!!
My kubernetes version is 1.11.0,and kubernetes-client is 4.2.2~

**Comment by iocanel** [comment]
The tested in the description is not valid, meaning that the API server doesn't guarantee that deletion is going to happen before returning.

This is also the case for kubectl and oc.

Now if we have performance related issues, making things even worse, then we should look into it.

**Comment by tombentley** [comment]
@iocanel can you point to where that's documented? I only found https://github.com/kubernetes/kubernetes/issues/33196, which suggests delete is _usually_ synchronous from the PoV of an apiserver client, and gives specific circumstances where it is async.

**Comment by iocanel** [comment]
@tombentley: No, I don't have a pointer to the documentation, I am mostly speaking from experience, what I notice from using the client, kubectl and oc. The most common example that comes to mind is `oc project delete`, which usually takes a while until the resource is actually deleted.

The link you provided makes it a lot clearer on under what conditions an operation is async, but it verifies that there are indeed async operation.

From the client perspective, there aren't much we can do. I am wondering if it's possible to use `waitUntilCondition` in order to provide a way to wait for async operations.

**Comment by victornoel** [comment]
I've opened #3246 that is related to this.
I'm thinking maybe the  following is a good workaround (I haven't tested it yet):
```jav
client.batch().v1().jobs()
    .inNamespace(namespace)
    .withName(name)
    .waitUntilCondition(Objects::isNull, 10, TimeUnit.SECONDS);
```

See also https://github.com/kubernetes/kubernetes/issues/42594 for the corresponding behaviour in kubectl.
