### ISSUE TITLE
patch failed when delete deployment due to missing key: /status/availableReplicas 

### ISSUE THREAD

**Issue by firebook** [fabric8io/kubernetes-client#1477]
When I try to delete a deployment, in some times, delete is failed, in the log, I found
`
doc is missing key: /status/availableReplicas
`
Why:
sdk try to patch 'spec/replica' of replicaset  to 0, request as below:
1. sdk get replicaset, and set 'spec/replica' to 0, this is replicaset1
response: 
`
status=ReplicaSetStatus(availableReplicas=20, conditions=[], fullyLabeledReplicas=20, observedGeneration=2, readyReplicas=20, replicas=20, additionalProperties={}), additionalProperties={})
`
2. k8s replicaset controller update status/availableReplicas to 8
3. sdk get current replicaset from k8s, this is replicaset2
`
status=ReplicaSetStatus(availableReplicas=8, conditions=[], fullyLabeledReplicas=8, observedGeneration=2, readyReplicas=8, replicas=8, additionalProperties={}), additionalProperties={})
`
4. k8s replicaset controller update status/availableReplicas to 0 
5. sdk jsondiff replicaset1 and replicaset2, generate patch body
diff:
`
[{"op":"replace","path":"/status/availableReplicas","value":20},{"op":"replace","path":"/status/fullyLabeledReplicas","value":20},{"op":"replace","path":"/status/readyReplicas","value":20},{"op":"replace","path":"/status/replicas","value":20}]
`
4. sdk patch the body as above, but now the availableReplicas of replicaset in k8s is 0, when the value is 0, with 'omitempty', k8s set it to null, and patch will failed
log:
`
E1228 14:25:56.117896   13378 status.go:64] apiserver received an error that is not an metav1.Status: jsonpatch replace operation does not apply: doc is missing key: /status/availableReplicas
`

I think sdk should not patch 'status' to k8s, k8s controller is able to control 'status'.
Jsondiff should remove the 'status' field.

**Comment by wgliang** [comment]
I have encountered a similar problem:

`Logging error output: "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\" ,\"message\":\"jsonpatch replace operation does not apply: doc is missing key: /status/availableReplicas\",\"code\":500}\n`
