### ISSUE TITLE
Webhook Example

### ISSUE THREAD

**Issue by martojdk** [fabric8io/kubernetes-client#1485]
Would you provide example for setting up webhook server like this one - https://book.kubebuilder.io/beyond_basics/sample_webhook.html ?

**Comment by rohanKanojia** [comment]
@kunal-kushwaha : Would you like to pick this issue? Would appreciate if you could look into this and provide model/dsl support if not present.

**Comment by kunal-kushwaha** [comment]
@rohanKanojia: Sure thing, I'll look into it.
