### ISSUE TITLE
Add installation manual for maven

### ISSUE THREAD

**Issue by izhangzhihao** [fabric8io/kubernetes-client#1493]
I'm a new bee to maven, today it takes me a while to fix `Could not resolve dependencies for project xxx: Failure to find io.fabric8:kubernetes-model:bundle:4.13 in xxx, blabla blabla...`. It appears that users should add these lines to pom.xml

```xml
<plugins>
  <plugin>
    <groupId>org.apache.felix</groupId>
    <artifactId>maven-bundle-plugin</artifactId>
	<version>2.5.4</version>
    <extensions>true</extensions>
  </plugin>
</plugins>
```

**Comment by rohanKanojia** [comment]
Did you face any problem here: https://github.com/fabric8io/kubernetes-client/blob/master/CONTRIBUTING.md#getting-source-code ? Would be awesome if you could share feedback on how it can be improved...
