### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/commons/collections/MapUtils

### ISSUE THREAD

**Issue by Ladicek** [fabric8io/kubernetes-client#1495]
This PR https://github.com/fabric8io/kubernetes-client/pull/1487 made Commons Collections a hard dependency of Fabric8 Kubernetes Client 4.2.1, even though depending on Fabric8 Kubernetes Client 4.2.1 does _not_ transitively bring in Commons Collections. This manifests as `java.lang.NoClassDefFoundError: org/apache/commons/collections/MapUtils` at runtime when calling `myKubernetesClient.load(myInputStream).createOrReplace()`.

**Comment by rohanKanojia** [comment]
@Ladicek : ah, Could you please raise a PR to fix this? I would do a release again .

**Comment by Ladicek** [comment]
Just running `mvn clean install` locally :-)

**Comment by traviswinter** [comment]
Is this fix in now? @rohankanojia is there a plan to release with this fix in the short term?

**Comment by rohanKanojia** [comment]
Hi Travis, let me release today

**Comment by traviswinter** [comment]
Awesome! Thanks!

**Comment by rohanKanojia** [comment]
4.2.2 has been released: https://repo1.maven.org/maven2/io/fabric8/kubernetes-client/4.2.2/
