### ISSUE TITLE
Unable to create  namespaced custom resource of type PrometheusRule by a provider (monitoring.coreos.com)

### ISSUE THREAD

**Issue by sanchitraizada** [fabric8io/kubernetes-client#1497]
I am running into multiple issues with using fabric8 API for creating custom resource type for PrometheusRule.
Basically, current code is limited in what can be done with CRD (refer to https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java and https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDLoadExample.java).

We need to create "namespaced" custom resource of type PrometheusRule object. The desired url endpoint could be something like https://{masterURL}/apis/monitoring.coreos.com/v1/namespaces/monitoring/prometheusrules but we end up https://{masterURL}/apis/apiextensions.k8s.io/v1v1beta1/customresourcedefinitions.

With this introduction, I am jumping into details on the issues:
Firstly, any CRD object created comes from CustomResourceDefinitionOperationsImpl  (crdoi) which sets the Plural as “customresourcedefinitions” (along with API GroupName and version)
https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceDefinitionOperationsImpl.java#L40
APIGroupName/Version aren’t too sticky and I am able to reload it from CRD def but  plural is final and so, I have limited options with plural.

Second is CustomResourceDefinitionOperationsImpl   extends HasMetadataOperation (which extends BaseOperation which extends OperationSupport). URL is constructed at https://github.com/fabric8io/kubernetes-client/blob/62d43cdda82d296b3e29519308bf4a715abb8f8e/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java#L132.  Note the code looks at “!isResourceNamespaced()” but CustomResourceDefinitionOperationsImpl  blantantly set is to false  https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceDefinitionOperationsImpl.java#L52 and this messes up URL construction – i.e. instead of desired https://{masterURL}/apis/monitoring.coreos.com/v1/namespaces/monitoring/prometheusrules , we get https://{masterURL}/apis/monitoring.coreos.com/v1/customresourcedefinitions
For this, I am able to extend CustomResourceDefinitionOperationsImpl  and setting isResourceNamespaced() right. 

 Just wondering if something else had similar issues - I did see https://github.com/fabric8io/kubernetes-client/issues/1205 but it was very generic.

**Comment by rohanKanojia** [comment]
Have you tried creating it like this: 

https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-itests/src/test/java/io/fabric8/kubernetes/RawCustomResourceIT.java

It's on version 4.2.1

**Comment by sanchitraizada** [comment]
Thanks Rohan for responding but seems like the API 
https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-itests/src/test/java/io/fabric8/kubernetes/RawCustomResourceIT.java#L72
is deprecated/no longer exists.

**Comment by rohanKanojia** [comment]
which api? previous one or the one I shared?

**Comment by sanchitraizada** [comment]
client.customResource(customResourceDefinitionContext)

Basically, the API in interface KubernetesClient which creates customResource with context.
AFAIK, they now need to pass in resourceType, listClass and doneClass

  @Override
  public <T extends HasMetadata, L extends KubernetesResourceList, D extends Doneable<T>> MixedOperation<T, L, D, Resource<T, D>> customResource(CustomResourceDefinition crd, Class<T> resourceType, Class<L> listClass, Class<D> doneClass) {
    return customResources(crd, resourceType, listClass, doneClass);
  }

**Comment by rohanKanojia** [comment]
Yeah, we added one more way to create custom resources(without having to provide POJOs).

**Comment by sanchitraizada** [comment]
Strange, for me compilation fails
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project {MY_PROJECT}: Compilation failure
[ERROR]{MY_FILE}:[116,62]  no suitable method found for customResource(io.fabric8.kubernetes.client.dsl.base.OperationContext)
[ERROR]     method io.fabric8.kubernetes.client.KubernetesClient.<T,L,D>customResource(io.fabric8.kubernetes.api.model.apiextensions.CustomResourceDefinition,java.lang.Class<T>,java.lang.Class<L>,java.lang.Class<D>) is not applicable
[ERROR]       (cannot infer type-variable(s) T,L,D
[ERROR]         (actual and formal argument lists differ in length))
[ERROR]     method io.fabric8.kubernetes.client.KubernetesClient.customResource(io.fabric8.kubernetes.client.dsl.base.CustomResourceDefinitionContext) is not applicable
[ERROR]       (argument mismatch; io.fabric8.kubernetes.client.dsl.base.OperationContext cannot be converted to io.fabric8.kubernetes.client.dsl.base.CustomResourceDefinitionContext)
[ERROR] 

I seem to be using v4.2.1
<dependency>
      <groupId>io.fabric8</groupId>
      <artifactId>kubernetes-client</artifactId>
      <version>4.2.1</version>
    </dependency>
<dependency>

**Comment by rohanKanojia** [comment]
Could you please provide a reproducible sample?

**Comment by sanchitraizada** [comment]
We can use the same example as https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-itests/src/test/java/io/fabric8/kubernetes/RawCustomResourceIT.java

`package com.walmart.platform.tsdb.util;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.InputStream;
import java.nio.file.Paths;
import java.util.Map;

import io.fabric8.kubernetes.api.model.apiextensions.CustomResourceDefinitionSpec;
import io.fabric8.kubernetes.client.Config;
import io.fabric8.kubernetes.client.ConfigBuilder;
import io.fabric8.kubernetes.client.DefaultKubernetesClient;
import io.fabric8.kubernetes.client.KubernetesClient;
import io.fabric8.kubernetes.client.KubernetesClientException;

public class TestMe {

	private static final String RULE_DEF = 
			"apiVersion: monitoring.coreos.com/v1\n" + 
			"kind: PrometheusRule\n" + 
			"metadata:\n" + 
			"  labels:\n" + 
			"  name: rule.yaml\n" + 
			"  namespace: monitoring\n" + 
			"spec:\n" + 
			"  groups:\n" + 
			"  - name: test-prometheus-scraper5\n" + 
			"    rules:\n" + 
			"      - alert: Prometheus scraping errors\n" + 
			"        expr: >-\n" + 
			"          count(up == 0)>0\n" + 
			"        for: 5m\n" + 
			"        labels:\n" + 
			"          page: test_page_id1\n" + 
			"          team: myteam\n" + 
			"        annotations:\n" + 
			"          summary: \"Prometheus Scraping has been Failed 05\"\n" + 
			"          description: |\n" + 
			"            Check failing services";
	private static final String PASSWORD = "XYZ";
	private static final String USERNAME = "USER_NAME";
	private static final String MASTER_URL = "YOUR_MASTER_URL";
	
	public static void main(String args[]) {

		updateKubernetesUsingFabric8Client(MASTER_URL, "monitoring",
				USERNAME, PASSWORD, RULE_DEF);

	}

	public static void createFromCRD(KubernetesClient client, String promRuleDef) {
		CustomResourceDefinitionSpec spec = null;
		try {
			io.fabric8.kubernetes.client.dsl.base.CustomResourceDefinitionContext customResourceDefinitionContext = new io.fabric8.kubernetes.client.dsl.base.CustomResourceDefinitionContext.Builder()
					.withName("animals.jungle.example.com").withGroup("jungle.example.com").withVersion("v1")
					.withPlural("animals").withScope("Namespaced").build();

			System.out.println("Upserting CRD...");

			InputStream targetStream = new ByteArrayInputStream(promRuleDef.getBytes());
			Map<String, Object> object = client.customResource(customResourceDefinitionContext).create("monitoring",
					targetStream);

			System.out.println("Updated Custom Resource Definitions - DONE!");
		} catch (Exception e) {
			e.printStackTrace();

		}

	}

	public static void updateKubernetesUsingFabric8Client(String masterURL, String namespace, String uName,
			String uCredential, String promRuleDef) {
		Config config = null;

		KubernetesClient client = null;
		try {
			config = getConfig(masterURL, namespace, uName, uCredential);
			client = new DefaultKubernetesClient(config);

			createFromCRD(client, promRuleDef);
			// createWithObject( client);

		} catch (KubernetesClientException e) {
			System.out.println(e.getMessage() + " - " + e);
		} catch (Exception e) {
			System.out.println(e.getMessage() + " - " + e);
			e.printStackTrace();
			// _slf4jLogger.error(e.getMessage(), e);
			Throwable[] suppressed = e.getSuppressed();
			if (suppressed != null) {
				for (Throwable t : suppressed) {
					System.out.println(t.getMessage() );
					// _slf4jLogger.error(t.getMessage(), t);
				}
			}
		} finally {
			if (client != null) {
				client.close();
			}
		}
	}

	private static Config getConfig(String masterURL, String namespace, String uName, String uCredential ) {


		Config config = null;
		File caCertFile,  clientCertFile,clientKeyFile = null;
		
		String userHome = System.getProperty("user.home");
		caCertFile = Paths.get(userHome, ".sledge", "ca.pem").toFile();
		clientCertFile = Paths.get(userHome, ".sledge",  "admin.pem").toFile();
		clientKeyFile = Paths.get(userHome, ".sledge",  "admin-key.pem").toFile();
		config = new ConfigBuilder().withMasterUrl(masterURL)//.withApiVersion("v1")
					.withPassword(uCredential)
					.withNamespace(namespace)
					.withUsername(uName)
					.withCaCertFile(caCertFile.getAbsolutePath())
					.withClientCertFile(clientCertFile.getAbsolutePath())
					.withClientKeyFile(clientKeyFile.getAbsolutePath())
					.build();

		return config;
	}

}
`
----

**Comment by rohanKanojia** [comment]
@sanchitraizada : I tried reproducing your example. I think there is some problem in your custom resource yaml itself, Are you able to create it with plain `kubectl create -f` command? I wasn't able to create it, when I tried I got:
```
~/go/src/github.com/fabric8io/kubernetes-client/kubernetes-examples/src/main/resources : $ oc create -f prometheous-rule-cr.yml 
Error from server (NotFound): error when creating "prometheous-rule-cr.yml": namespaces "monitoring" not found
```

When I tried some other custom resource example from internet, like [this](https://github.com/coreos/prometheus-operator/blob/master/example/user-guides/alerting/prometheus-example-rules.yaml) I was able to create custom resource:
Code:
```
      CustomResourceDefinition prometheousRuleCrd = client.customResourceDefinitions().load(RawCustomResourceExample.class.getResourceAsStream("/prometheous-rule-crd.yml")).get();
      client.customResourceDefinitions().create(prometheousRuleCrd);
      log("Successfully created prometheous custom resource definition");

      // Creating Custom Resources Now:
      CustomResourceDefinitionContext crdContext = new CustomResourceDefinitionContext.Builder()
        .withGroup("monitoring.coreos.com")
        .withPlural("prometheusrules")
        .withScope("Namespaced")
        .withVersion("v1")
        .build();

      client.customResource(crdContext).create("myproject", RawCustomResourceExample.class.getResourceAsStream("/prometheous-rule-cr.yml"));
      log("Created Custom Resource successfully too");
```
Result:
```
~/go/src/github.com/fabric8io/kubernetes-client/kubernetes-examples : $ oc get crd
NAME                                                                     CREATED AT
hellos.test.fabric8.io                                                   2019-04-17T09:23:49Z
openshiftwebconsoleconfigs.webconsole.operator.openshift.io              2019-04-10T07:26:57Z
prometheusrules.monitoring.coreos.com                                    2019-04-22T10:23:18Z
servicecertsigneroperatorconfigs.servicecertsigner.config.openshift.io   2019-04-10T07:23:03Z
~/go/src/github.com/fabric8io/kubernetes-client/kubernetes-examples : $ oc get prometheusrules.monitoring.coreos.com
NAME                       AGE
prometheus-example-rules   17s
~/go/src/github.com/fabric8io/kubernetes-client/kubernetes-examples : $ 

```

**Comment by rohanKanojia** [comment]
@sanchitraizada : Did you get time to check this? I think we can close this issue.

**Comment by sanchitraizada** [comment]
Sure - we can close this.
