### ISSUE TITLE
Unable to update a Pod using createOrReplace

### ISSUE THREAD

**Issue by traviswinter** [fabric8io/kubernetes-client#1502]
We recently upgraded from 4.1.3 to 4.2.2 and there appears that some validation changed occurred that is being hit from createOrReplace() from a kubeClient.load() resource.

Previously if I ran the following Pod yaml through the following code twice, it would create the first time and then update the second time:

> kind: Pod
> apiVersion: v1
> metadata:
>   name: defaultpod1
> spec:
>   containers:
>     - name: myfrontend
>       image: nginx

`  	Config config;
	try {
		config = Config.fromKubeconfig(contents);
		
	  	final KubernetesClient kubeClient = new DefaultKubernetesClient(config);

	  	String yaml = POD_YAML.trim();
		InputStream yamlIS;
		try {
			yamlIS = IOUtils.toInputStream(yaml, StandardCharsets.UTF_8.name());

			List<HasMetadata> list = kubeClient.load(yamlIS).get();
			
			for (HasMetadata resource: list) {
				kubeClient.resource(resource).inNamespace("test").createOrReplace();
			}
		} catch (IOException e) {
			e.printStackTrace();
		}
	} catch (IOException e1) {
		e1.printStackTrace();
	}
`

When I run the code with the latest 4.2.2 release I see the following:

> Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://10.10.10.10:6443/api/v1/namespaces/test/pods/defaultpod1. Message: Pod "defaultpod1" is invalid: [spec.containers[0].name: Required value, spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)

Is this the new behaviour? If so, it seems very odd - loading is basically useless for updating based on YAML if that is the case.

We noticed similar behaviour with Service's and StatefulSets, so perhaps something changed on the backend?

**Comment by traviswinter** [comment]
After investigating it looks like something changed in the HasMetadataOperation that causes the resourceVersion to be null.

This is the 4.2.2 pod being sent n PodOperationsImpl.handleReplace():
>Pod(apiVersion=v1, kind=Pod, metadata=ObjectMeta(annotations={}, clusterName=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, initializers=null, labels={}, name=defaultpod1, namespace=resttest, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=PodSpec(activeDeadlineSeconds=null, affinity=null, automountServiceAccountToken=null, containers=[Container(args=[], command=[], env=[], envFrom=[], image=nginx, imagePullPolicy=null, lifecycle=null, livenessProbe=null, name=myfrontend, ports=[], readinessProbe=null, resources=null, securityContext=null, stdin=null, stdinOnce=null, terminationMessagePath=null, terminationMessagePolicy=null, tty=null, volumeDevices=[], volumeMounts=[], workingDir=null, additionalProperties={})], dnsConfig=null, dnsPolicy=null, enableServiceLinks=null, hostAliases=[], hostIPC=null, hostNetwork=null, hostPID=null, hostname=null, imagePullSecrets=[], initContainers=[], nodeName=null, nodeSelector={}, priority=null, priorityClassName=null, readinessGates=[], restartPolicy=null, runtimeClassName=null, schedulerName=null, securityContext=null, serviceAccount=null, serviceAccountName=null, shareProcessNamespace=null, subdomain=null, terminationGracePeriodSeconds=null, tolerations=[], volumes=[], additionalProperties={}), status=null, additionalProperties={})

This is the 4.1.3 pod being sent n PodOperationsImpl.handleReplace():
> Pod(apiVersion=v1, kind=Pod, metadata=ObjectMeta(annotations={}, clusterName=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, initializers=null, labels={}, name=defaultpod1, namespace=resttest, ownerReferences=[], resourceVersion=10250245, selfLink=null, uid=null, additionalProperties={}), spec=PodSpec(activeDeadlineSeconds=null, affinity=null, automountServiceAccountToken=null, containers=[Container(args=[], command=[], env=[], envFrom=[], image=nginx, imagePullPolicy=null, lifecycle=null, livenessProbe=null, name=myfrontend, ports=[], readinessProbe=null, resources=null, securityContext=null, stdin=null, stdinOnce=null, terminationMessagePath=null, terminationMessagePolicy=null, tty=null, volumeDevices=[], volumeMounts=[], workingDir=null, additionalProperties={})], dnsConfig=null, dnsPolicy=null, enableServiceLinks=null, hostAliases=[], hostIPC=null, hostNetwork=null, hostPID=null, hostname=null, imagePullSecrets=[], initContainers=[], nodeName=null, nodeSelector={}, priority=null, priorityClassName=null, readinessGates=[], restartPolicy=null, runtimeClassName=null, schedulerName=null, securityContext=null, serviceAccount=null, serviceAccountName=null, shareProcessNamespace=null, subdomain=null, terminationGracePeriodSeconds=null, tolerations=[], volumes=[], additionalProperties={}), status=null, additionalProperties={})

Notice that resourceVersion is missing in the first object

**Comment by traviswinter** [comment]
After further investigation it looks like the Kubernetes API does not allow what I was doing with Pods (eg. load in a Pod yaml once for create, then do it again for update). That error does appear in 4.1.3. This is still an issue for updating a service however:

> Service "backup" is invalid: metadata.resourceVersion: Invalid value: "": must be specified for an update

**Comment by rohanKanojia** [comment]
@traviswinter : Hi, I haven't read the issue completely. Is it still valid? Were you able to resolve it somehow? Or is it still there on 4.4.0 ?

**Comment by dzwicker** [comment]
Ping
