### ISSUE TITLE
Edit on Ingress to update LoadBalancerIngress returns HTTP Status 200, but Ingress is not actually updated

### ISSUE THREAD

**Issue by shahpankil** [fabric8io/kubernetes-client#1503]
I am developing my own IngressController(like nginx with my service as LoadBalancer). So I watch for Ingress objects and after I have parsed them I try to update the IngressStatus by adding the LoadBalancerIngress of my IngressController. 
My test-ingress of a hello_world service which leverages my IngressController is mentioned below:
"
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    kubernetes.io/ingress.class: "ingresscontroller"
spec:
  rules:
  \- host: localhost
    http:
      paths:
      \- backend:
          serviceName: hello-world-service
          servicePort: 18080
        path: /tenant1/playground/hello_world/api/v2
"
Once above Ingress is added, I try to edit the IngressStatus and update the LoadbalancerIngress(with hostname/ip of my IngressController).
I have tried following 4 fabric8io client API's(from the IngressWatcher in my IngressController) and all them succeeds but, the LoadBalancerIngress does not get added/updated to the test-ingress.
API 1:
`kubernetesClient.extensions().ingresses().inNamespace(ingress.getMetadata().getNamespace()).withName(ingress.getMetadata().getName()).edit().editStatus().editLoadBalancer().addToIngress(lbiItem).and().and().done();`

Patch Diff: [{"op":"add","path":"/status/loadBalancer/ingress","value":[{"hostname":"localhost","ip":"127.0.0.1"}]}]

OKHTTP Client Request : {method=PATCH, url=https://localhost:6445/apis/extensions/v1beta1/namespaces/playground/ingresses/test-ingress, tag=null}

OKHTTP Client Response : {protocol=http/1.1, code=200, message=OK, url=https://localhost:6445/apis/extensions/v1beta1/namespaces/playground/ingresses/test-ingress}

API 2:
`kubernetesClient.extensions().ingresses().inNamespace(ingress.getMetadata().getNamespace()).withName(ingress.getMetadata().getName()).edit().editStatus().editLoadBalancer().addNewIngressLike(lbi).and().and().and().done();`

Patch diff: [{"op":"add","path":"/status/loadBalancer/ingress","value":[{"hostname":"localhost"}]}]

OKHTTP Client Request : {method=PATCH, url=https://localhost:6445/apis/extensions/v1beta1/namespaces/playground/ingresses/test-ingress, tag=null}

OKHTTP Client Response : {protocol=http/1.1, code=200, message=OK, url=https://localhost:6445/apis/extensions/v1beta1/namespaces/playground/ingresses/test-ingress}

API 3:
`kubernetesClient.extensions().ingresses().inNamespace(ingress.getMetadata().getNamespace()).withName(ingress.getMetadata().getName()).edit().editStatus().editLoadBalancer().addNewIngress("localhost","127.0.0.1").and().and().done();`

Patch diff: [{"op":"add","path":"/status/loadBalancer/ingress","value":[{"hostname":"localhost","ip":"127.0.0.1"}]}]

OKHTTP Client Request : {method=PATCH, url=https://localhost:6445/apis/extensions/v1beta1/namespaces/playground/ingresses/test-ingress, tag=null}

OKHTTP Client Response : {protocol=http/1.1, code=200, message=OK, url=https://localhost:6445/apis/extensions/v1beta1/namespaces/playground/ingresses/test-ingress}

API 4:
`kubernetesClient.extensions().ingresses().inNamespace(ingress.getMetadata().getNamespace()).withName(ingress.getMetadata().getName()).edit().editStatus().editLoadBalancer().addAllToIngress(lbilist).and().and().done();`

Patch diff: [{"op":"add","path":"/status/loadBalancer/ingress","value":[{"hostname":"localhost","ip":"127.0.0.1"}]}]

OKHTTP Client Request : {method=PATCH, url=https://localhost:6445/apis/extensions/v1beta1/namespaces/playground/ingresses/test-ingress, tag=null}

OKHTTP Client Response : {protocol=http/1.1, code=200, message=OK, url=https://localhost:6445/apis/extensions/v1beta1/namespaces/playground/ingresses/test-ingress}

Please note the patch diff for each API is different as I was trying to update with multiple/different values for LoadBalancerIngress->hostname & LoadBalancerIngress->IP
The patch diff is the value as calculated by method OperationSupport.handlePatch

My kubernetes server version is : Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3"
Client version is : Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3"
fabric8io client library: 4.1.1 (compile group: 'io.fabric8', name: 'kubernetes-client', version: '4.1.1')

As there is no direct example of updating IngressStatus, I tried to follow the example @ https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ReplaceExamples.java

Questions:
1. Does adding a new LoadBalancerIngress to a empty list cause issue while updating ?
2. Could this be related to https://github.com/fabric8io/kubernetes-client/issues/502 ?
3. Does there seem to be issue with my code or does it seem to be a library defect?

**Comment by rohanKanojia** [comment]
Shouldn't you be editing spec instead?

**Comment by shahpankil** [comment]
The API to assign new IP to a service of type ClusterIP is available under editStatus. Also status and LoadBalancerIngress are available under editStatus. 
questions :
1. Do you mean to say that object model for fabric8io is different than kubernetes ingress model ? 
2. Any specific reason why shall I use editSpec to assign new IP and not editStatus? 
3. If I need to use editSpec, then how do I assign the Controller's public IP to a service using a gateway? There does not seem to be a API after I do editSpec to update LoadBalancerIngress and assign the IP.

**Comment by shahpankil** [comment]
I captured the HTTP request/response. I am noting them below.
Request(from fabric8io client):
-------------------------------
PATCH https:Content-Type:application/json-patch+json;charset=utf-8
Content-Length:104
Host:localhost:6445
Connection:Keep-Alive
Accept-Encoding:gzip
User-Agent:okhttp/3.9.1
[{
		"op": "add",
		"path": "/status/loadBalancer/ingress",
		"value": [{
				"hostname": "localhost",
				"ip": "127.0.0.1"
			}
		]
	}
]


Response from API server:
-------------------------
HTTP/1.1 200 OK
Content-Type:application/json
Date:Tue,30 Apr 2019 10:58:03 GMT
Content-Length:2976
{
	"kind": "Ingress",
	"apiVersion": "extensions/v1beta1",
	"metadata": {
		"name": "test-ingress",
		"namespace": "playground",
		"selfLink": "/apis/extensions/v1beta1/namespaces/playground/ingresses/test-ingress",
		"uid": "d34ca984-6b36-11e9-974d-00155db3200b",
		"resourceVersion": "3789857",
		"generation": 1,
		"creationTimestamp": "2019-04-30T10:58:02Z",
		"annotations": {
			"kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"extensions/v1beta1\",\"kind\":\"Ingress\",\"metadata\":{\"annotations\":{\"kubernetes.io/ingress.class\":\"ingresscontroller\"},\"name\":\"test-ingress\",\"namespace\":\"playground\"},\"spec\":{\"rules\":[{\"host\":\"localhost\",\"http\":{\"paths\":[{\"backend\":{\"serviceName\":\"hello-world-service\",\"servicePort\":18080},\"path\":\"/tenant1/playground/hello_world/api/v2\"}]}}]}}\n",
			"kubernetes.io/ingress.class": "ingresscontroller"
		}
	},
	"spec": {
		"rules": [{
				"host": "localhost",
				"http": {
					"paths": [{
							"path": "/tenant1/playground/hello_world/api/v2",
							"backend": {
								"serviceName": "hello-world-service",
								"servicePort": 18080
							}
						}
					]
				}
			}
		]
	},
	"status": {
		"loadBalancer": {}
	}
}

As seen above, the patch is successful, but the object state has not changed.
questions:
1. Is this a issue with fabric8io client ?
2. Is the patch generated correctly ?
3. Is it fine to only rely on http status from API server?  If not, is this fabric8io client defect ?
