### ISSUE TITLE
Impossible copy or read a directory from a pod

### ISSUE THREAD

**Issue by franciscoRdiaz** [fabric8io/kubernetes-client#1507]
Hi,

When I try to copy or read a directory from a pod to localhost, kubernetes-clien doesn't return any error but the directory is not copied either.

```
if (filePath != null && !filePath.isEmpty()) {
            File file = new File(filePath);
            try (InputStream is = client.pods().inNamespace(SYSTEM_NAMESPACE)
                    .withName(podName).dir(filePath).read()) {
                result = new BufferedReader(new InputStreamReader(is)).lines()
                        .collect(Collectors.joining("\n"));
                logger.info("File content: {}", result);
            } catch (Exception e) {
                logger.error("Error reading test results' file");
                e.printStackTrace();
            }
        }
```

I've found the problem in your code. There are two errors in the class PodOperationsImpl but they are easy to fix. Is necessary to do the test? At this moment there is no test for this fuctionalities and I have implemented the changes in my local and the work correctly. Can I do the PR directly?

**Comment by rohanKanojia** [comment]
we do have a test to check these, see https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-itests/src/test/java/io/fabric8/kubernetes/PodIT.java#L168

**Comment by franciscoRdiaz** [comment]
That test is for reading files, not for reading directories, but it would be very similar. If there was a test for this functionality, someone would have found the problem. The difference is in the following line,:
`InputStream is = client.pods().inNamespace(currentNamespace).withName(pod1.getMetadata().getName()).dir("/msg").read()`
To copy directories you have to change `.file` by `.dir`

**Comment by rohanKanojia** [comment]
oh, I see. Could you please raise a PR to fix this if you have time?

**Comment by franciscoRdiaz** [comment]
Sure.
