### ISSUE TITLE
Is it possible to stream Pod logs?

### ISSUE THREAD

**Issue by roksolana-d** [fabric8io/kubernetes-client#1511]
I am trying to get pod logs in real-time using watchLog method. My application runs about 10 minutes so I need this time to get all the logs. However, to get the whole log I had to set thread sleep which is not the best practice.
So is it possible to stream logs in some way until the application terminates?

Here is the way I tried to do it:

```
    val driverPod = client.pods()
      .inNamespace("default")
      .withName("spark-driver")
     .watchLog(System.out)

    Thread.sleep(600000)
```

I tried to get the logs based on the pod status phase, the result was constantly repeated piece of log in the console instead of streaming the log:

```
    val driverPod = client.pods()
      .inNamespace("default")
      .withName("spark-driver")

    while(driverPod.get.getStatus.getPhase != "Terminated"){
      driverPod.watchLog(System.out)
    }
```

**Comment by rohanKanojia** [comment]
I think there is, see below example(but without passing any parameter to `tailingLines()`: https://github.com/fabric8io/kubernetes-client/blob/94bba0b23effd38992d0219a8aecc2c009989d48/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/PodLogExample.java#L51-L56

**Comment by roksolana-d** [comment]
I tried using tailingLines, but it does not work without parameters and I need the whole log of the pod not just part of it. Also, this example shows usage of Thread sleep and it's not what I am looking for.

**Comment by rohanKanojia** [comment]
Sorry, I meant without `tailingLines`... Looking at the code, it looks like default is follow option. Have you tried without `tailingLines()` parameter and without `Thread.sleep`?

https://github.com/fabric8io/kubernetes-client/blob/31ddcea6d95cd9a12be6f5ea0aa6285e7ee0d3bf/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java#L192

**Comment by roksolana-d** [comment]
Yes, I tried without tailingLines method call.  The result is exactly the problem I am asking about. I have to set up Thread sleep because without it the application will terminate after some default time period.

**Comment by rohanKanojia** [comment]
Okay, so if you don't want to use `Thread.sleep` maybe you can use `waitUntilCondition` functionality like this:
```
         KubernetesClient client = new DefaultKubernetesClient();
         LogWatch watch= client.pods().inNamespace(namespace).withName(podName).watchLog(System.out));
         client.pods().inNamespace(namespace).withName(podName).waitUntilCondition(  r -> r.getStatus().getPhase().equals("Running"), 30, TimeUnit.MINUTES);
```

But you need to provide wait a timeout period.

**Comment by roksolana-d** [comment]
@rohanKanojia Thank you very much! It works without Thread sleep now.
I have implemented it a bit differently in Scala:

```
    driverPod.waitUntilCondition( new java.util.function.Predicate[Pod] {
      def test(pod: Pod): Boolean = pod.getStatus.getPhase.equals("Terminating")
    },15, TimeUnit.MINUTES)
```

**Comment by sachinkaushik** [comment]
Hi @rohanKanojia ,

I'm working on similar feature, I want to get live streams of logs of Job resource. But I have created a web socket using that, live logs will be shown to end user on UI.

How can I get live streams of Job logs using below code, without putting BufferedReader in while loop, Im getting an error as InputStream pipeline is closed



`LogWatch watch= userClient.batch().v1().jobs().inNamespace(nameSpace).withName("log-job").watchLog();
			LOGGER.info("--- started watching---- {}" );
			InputStream output = watch.getOutput();
			BufferedReader reader = null;
			try {
				reader = new BufferedReader(new InputStreamReader(output));
				String line = reader.readLine();
				userClient.batch().v1().jobs().inNamespace(nameSpace).withName("log-job").waitUntilCondition(r -> r.getStatus().getSucceeded() == 1, 30, TimeUnit.MINUTES);
			} catch (IOException e) {
				LOGGER.error("--- error----", e );
			}finally {
				try {
					output.close();
					if(Objects.nonNull(reader))
						reader.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
			 #}`

**Comment by rohanKanojia** [comment]
@sachinkaushik : Could you please share code where you're setting up log watch call? maybe it's getting closed before you're trying to read it.

**Comment by shawkins** [comment]
> How can I get live streams of Job logs using below code, without putting BufferedReader in while loop, Im getting an error as InputStreamPumper - Error while pumping stream , InputStream pipeline is closed

An inputstream will need to be read in a loop, whether it is in your code or via the inputstreampumper.  Generally you shouldn't need to use the pumper - but instead use the watchLog call that accepts an OutputStream.  To react to the data as it comes in you can provide something like:

```
watchLog(new OutputStream() {
      
      @Override
      public void write(int b) throws IOException {
        throw new RuntimeException("not used");
      }
      
      @Override
      public void write(byte[] b, int off, int len) throws IOException {
        // do something with the bytes
      }
      
    });
``` 

Of course we should probably additionally offer a higher level abstraction / callback to make this clearer - so that you could just do:

watchLog(buffer -> {consume buffer})

**Comment by sachinkaushik** [comment]
@rohanKanojia I'm using same code that I mentioned above also.


'''LOGGER.info("--- started watching---- {}" );
			InputStream output = watch.getOutput();
			BufferedReader reader = null;
			try {
				reader = new BufferedReader(new InputStreamReader(output));
				String line = reader.readLine();
                                 //sample code to send logs to queue
                                  messagingTemplate.convertAndSendToUser(line);
				userClient.batch().v1().jobs().inNamespace(nameSpace).withName("log-job").waitUntilCondition(r -> r.getStatus().getSucceeded() == 1, 30, TimeUnit.MINUTES);
			} catch (IOException e) {
				LOGGER.error("--- error----", e );
			}finally {
				try {
					output.close();
					if(Objects.nonNull(reader))
						reader.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
			 }```

**Comment by hdelatorre** [comment]
@sachinkaushik Would you be ok sharing how you're doing the web socket as well?  perhaps in a different repo?

**Comment by manusa** [comment]
This is how this is done in [YAKD](https://github.com/manusa/yakd), converting the InputStream into an event producer:

https://github.com/manusa/yakd/blob/6ba2ea98db589564a139ff92f1a5f9facc912d70/src/main/java/com/marcnuri/yakd/pod/PodService.java#L79-L111
