### ISSUE TITLE
Change context/cluster programmatically

### ISSUE THREAD

**Issue by kchrusciel** [fabric8io/kubernetes-client#1512]
Is there any way to change context/cluster using kubernetes client?

**Comment by rohanKanojia** [comment]
what kind of context? Are you talking about [config](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/JobExample.java#L41) object?

**Comment by kchrusciel** [comment]
I talking about `kubectl config set-context CONTEXT_NAME`

**Comment by wemu** [comment]
sorry for digging this out - but I ran into the same question. I am looking for the analog feature from kubectl:

```
kubectl config current-context
kubeint

kubectl config use-context kubeint
Switched to context "kubeint".
```

I only found a way to determine the current context:

```
import io.fabric8.kubernetes.api.model.Config;

Config config = KubeConfigUtils.parseConfig(new File(kubeConfig));
List<NamedContext> contexts = config.getContexts();
System.out.println("Current Context: " + config.getCurrentContext());
```

but no way to change the context or pass it into the KubernetesClient.
Is this not yet supported or is it hidden somewhere else?

**Comment by rohanKanojia** [comment]
@wemu : I think all code related to `Config` is inside https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java 

Could you please check if we are supporting setting context there? If not, I think we should try to add this feature.

**Comment by wemu** [comment]
Thanks for the pointer! Indeed the Config class in the client package has that functionality. 

I was using the ConfigBuilder but there is a more suitable method on the Config directly:

```
Config config = new ConfigBuilder().build(); // no context?
Config cfgWithContext = Config.autoConfigure("kubeint");

KubernetesClient client = new DefaultKubernetesClient(cfgWithContext);
```

I thought it should be on the client but kubectl behaves the same way (set the config, then execute commands). So that actually looks ok.
It is a bit inconvenient to read the available contexts via the model.Config api and then use it via the client.Config api - but so far it looks ok for what I plan to do.

Thanks!

**Comment by pedro93** [comment]
+1 on this feature. 

My particular use-case is to check in the client API what context the client is currently in and if it's one of a selected few run additional code (e.g: port-forward a few services).

**Comment by LeiYangGH** [comment]
i also met this issue. need a way to specify the context. following code not work(running but still pointing to default context)
```
			Config cfg = Config.autoConfigure( "my context");
			KubernetesClient client = new DefaultKubernetesClient(cfg);
```

**Comment by adietish** [comment]
> i also met this issue. need a way to specify the context. following code not work(running but still pointing to default context)
> 
> ```
> 			Config cfg = Config.autoConfigure( "my context");
> 			KubernetesClient client = new DefaultKubernetesClient(cfg);
> ```

That's unexpected. The exact same code [works very well for me](https://github.com/redhat-developer/intellij-kubernetes/blob/master/src/main/kotlin/org/jboss/tools/intellij/kubernetes/model/context/ContextFactory.kt#L27-L28). Is there the possibility that the context that you're specifying doesn't exist?

**Comment by LeiYangGH** [comment]
@adietish  today i ran the same code and **succeeded**. 
don't remember what happend last time.

**Comment by rohanKanojia** [comment]
Shall we close this issue? Or maybe we should close it after someone documents this?

**Comment by adietish** [comment]
The "challenge" for this is that a change in context also affects whatever property it may contain:
* cluster
* namespace
* user
* etc. (?)

A navie implementation would turn `Config#autoConfigure(Config config, String context)` (https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L235) public, allowing one to pass in the current config. What I think could be improved though is that there's no need to re-read the config file. Changing those values could be based on the current ones. 
On the other hand, switching the kube config file (and not just the Config wrapper) to a new current config requires having it parsed. Currently no reference to this (parsed) file is kept, it's garbaged once it was used in `Config#tryKubeConfig`.
Thoughts?

**Comment by rohanKanojia** [comment]
@adietish : Thanks for your input :+1: . Let's keep this issue open. We'll revisit this later in upcoming sprints.

**Comment by adietish** [comment]
@rohanKanojia I can provide a PR since I can use it.

**Comment by rohanKanojia** [comment]
@adietish : If you have time, please feel free to submit PR. Thanks a lot for your efforts :+1:

**Comment by shawkins** [comment]
I think we should remove the never stale tag.  It's unlikely that we'll be able to make progress on this.  Since the context influences things like the ssl context, which require reloading the httpclient, switching the context is effectively creating a different client.  It's much simpler to recommend the user maintain a mapping of config/context to client (which could hold references to the full kubeconfig if desired), rather than doing that internally.  If some higher level abstraction / factory makes sense to propose to the project from there, we can pursue incorporating it.
