### ISSUE TITLE
Invalid token when reusing the DefaultKubernetesClient to create pods

### ISSUE THREAD

**Issue by bmbferreira** [fabric8io/kubernetes-client#1522]
I'm reusing a DefaultKubernetesClient to create a namespace and then a pod in that namespace. And I'm doing this multiple times but sometimes I get this error when creating the pod:
```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at:
https://172.20.0.1/api/v1/namespaces/worker-0341fbc8-namespace/pods. 
Message: No API token found for service account "default", retry after the token is automatically created and added to the service account. 
Received status: Status(apiVersion=v1, code=500, details=StatusDetails(causes=[], group=null, kind=serviceaccounts, name=create pod, retryAfterSeconds=1, uid=null, additionalProperties={}), kind=Status, 
message=No API token found for service account "default", 
retry after the token is automatically created and added to the service account, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), 
reason=ServerTimeout, status=Failure, additionalProperties={}).
```

However, if I don't reuse the DefaultKubernetesClient, this never happens. Why? Should I always create a new client before creating a new pod?

Thanks for the help.

**Comment by HillebrandtOldenberg** [comment]
I have the same issue. With 2 Java methods:

**Method 1**
```
createNamespace
createPod
<...>
deleteNamespace
kubernetesClient.close();
```

**Method 2**
```
createTheSameNamespaceAgain
createAnotherPod
<...>
deleteNamespace
kubernetesClient.close();
```

I get the `No API token found for service account "default", retry after the token is automatically created and added to the service account` message when creating the second pod.

@bmbferreira, did you solve it?

**Comment by bmbferreira** [comment]
@HillebrandtOldenberg as far as I remember, I ended up re-creating a new client for every different call. :disappointed:

**Comment by HillebrandtOldenberg** [comment]
@bmbferreira I found that if I introduce a `Thread.sleep(1000)` between `createTheSameNamespaceAgain` and `createAnotherPod`, the issue disappears. It also disappears if I create another client for every method. A bit annoying but eh. @rohanKanojia or @iocanel , would appreciate if you could take a look at this.

**Comment by shawkins** [comment]
Removed the never-stale given the changes that have been made related to token refresh - in particular #4951 ensures consistent refresh from any token source.
