### ISSUE TITLE
How to list all events for Custom Resources?

### ISSUE THREAD

**Issue by csviri** [fabric8io/kubernetes-client#1524]
Hi,
I'm implementing an operator, and watching for events of custom resources. Considering a situation when my operator was not running for a while I would like to list events, for the custom resources. In particular DELETE events, since as I see I always get the last event for all existing custom resource objects, am I right?

So is there a api implemented to list events for custom resources? I can't find it :(

Thank you!

**Comment by rohanKanojia** [comment]
@csviri : So basically you want to `watch` your custom resource? Am I right? There is watch functionality in older api for custom resources(not sure that works though) https://github.com/fabric8io/kubernetes-client/blob/12fa0993793baa9ba1835c36f2fa696bd739a1b9/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java#L164-L170

**Comment by rohanKanojia** [comment]
But we have made custom resource operations a bit less typed using this new approach, but this doesn't have watch functionality right now: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/RawCustomResourceExample.java

**Comment by csviri** [comment]
Yes, the watch is what I needed, and used. Now I realized that there are no explicet events for this in k8s. 
So, thank you.

**Comment by rohanKanojia** [comment]
I'll close this if you're able to get that watch working.

**Comment by csviri** [comment]
Yes I was, thank you.
