### ISSUE TITLE
Failed to parse the kubeconfig.

### ISSUE THREAD

**Issue by sudheshpn** [fabric8io/kubernetes-client#1525]
When i use jenkins to deploy my application to k8s master node which is on v1.14.1 i get the below exception. I have configured the credentials so that jenkins can log into my k8 master node and parse the file kubeconfig file. I remember the similar set up used to be working in previous version where as its not working in 1.14.1

May 15, 2019 12:04:14 PM io.fabric8.kubernetes.client.Config loadFromKubeconfig
SEVERE: Failed to parse the kubeconfig.
com.fasterxml.jackson.databind.JsonMappingException: YAML decoding problem: while scanning a simple key
 in 'reader', line 5, column 1:
    RVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVa ... 
    ^
could not find expected ':'
 in 'reader', line 6, column 1:
    WTVsNFlUcVkyRDNQZlRHbDg2ZEVNVW9O ... 
    ^
 (through reference chain: io.fabric8.kubernetes.api.model.Config["clusters"]->java.util.ArrayList[0]->io.fabric8.kubernetes.api.model.NamedCluster["cluster"])
        at com.fasterxml.jackson.dataformat.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465)
        at com.fasterxml.jackson.dataformat.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280)
        at com.fasterxml.jackson.dataformat.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:225)
        at com.fasterxml.jackson.dataformat.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
        at com.fasterxml.jackson.dataformat.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
        at com.fasterxml.jackson.dataformat.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168)
        at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:351)
        at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:655)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:267)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)

kubeconfig file

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1EVXhOVEE0TkRRek5sb1hEVEk1TURVeE1qQTRORFF6Tmxvd0ZU
RVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTlo4ClczazlPQ1ZCbHgxeFNNdmgrVkJiUTBPODBmNmlGaEdrc3hrREhQcjdhMGxtOXM5a0VZVU4rR1BIQlZDNnZ2MWYKWForRnFjT1ZmTUVTejZoVElmSTVsMU1zaHdhMjNr
WTVsNFlUcVkyRDNQZlRHbDg2ZEVNVW9OUHBMdnVkcVF6TQp1WElmVEE0bk1mYUVFTW45WU52aWVMVWlBcEdSUnVVVjNzTXYxaVNkM3grYzQvOWFDUWVid0IrejRtVVhETTY2Ckw3L01ML0ZnUnp3dzB2L2hrQm5wQXhQbnlwdmhja3ZsMDdvWDRKMWk2YytoemVPZTN2YWU5VUxBTkJ4NjZHOWIKZ1ExRmVU
eklNMFdjMCtPRlE1WFFkbzlyWVdNa3p5UCtwT0YxSFdoSCtqbURzYVFqZXUvb3VvMWZuWTJncXVJeApQbXkyRU1qZ1NueUVaSjZiczlrQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFNRjhDWWlML1dY
bitkOVFDN0xKRFVWNFk1V0kKT1l1ckpNUURlWTl2VzFoeTI3ZmFMdjNzRDF4NHJzOS9DSjV5YjhnTVZtSk1pWFRWbUFPRTloOFAxNkJ0TGdNTQp3YWxobmxXN0d6aExlT2FZZmR3azBqaGI2YzNUUTFJRXFxR05tRklCWThjaGNxVXRZblhkY2UyUFNFT2ZBb0tnCm1tcm5CZ1RYQ2tPd2xoYVNkZFdKcUZZ
RGt1OHNOQWVyZUZNek5WVHNqWFZrcGQ2M3VlWE9JWS9lUWhKMU0reXEKY0xNUWFSeUtMRzAyUU40Ly8wUXJMdkFtSjlDOFVaSFZObWs1MVVzSGE1MkZQckk0ekJhbWRIekpoVnZ2enZmZAo5NEd0ZFJ4S1pjKzZwQk1ETEtGbXpoVmxTRGZvVXBhNFlxcjhDeHUvRVdUdmt6WTZkSEp3OFBkZ1M1ND0KLS0t
LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://10.142.0.10:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRxZ0F3SUJBZ0lJTno0b21KanE4SWt3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB4T1RBMU1UVXdPRFEwTXpaYUZ3MHlNREExTVRRd09EUTB
NemhhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXhqS0gwQStNdDR2Z2luSzEKa1RvdGtVMjJ2K0VYdndBLzdmZ2F0cnRFNzdJYnM3T2J
BM3dGMDhEMHlsZnZScTNqNzh5S25OZE1ycnVUSjdrbgpGL3k0ZzhmVUF0OTI0Y2F6K0U1V0xLWk5GUWFrSFB5YXNFNzBqSUJyYndHR0lpd0ZINXNNbEJMUUF5MkF3UDRNCmJpY1FrdHJSb2pNNHdRZmhBdHV3eXpFVjA0bm1QZTRlQ3hjWHNnQy9nSGovSzdSNzN1KzNzOVA5M1RaeHpUS1MKTCt2MUVyejV
hWTRnY1hVMVMzS3ZmRUxleU9uOEdNNDdNZGNUN1NSejk3aS9yZGxZdDFsWnBhRVFOTkRCdmxobgpSQ3lRek5uRlc5Z0V5MGY0aUZZZkZDbUZub2pvWHI2Rjg0MnNia0UzaGUxNzVIdmd2eU9GR1VMOHI0eDRpeDlRCmNrblBNd0lEQVFBQm95Y3dKVEFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJ
Bd3dDZ1lJS3dZQkJRVUgKQXdJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBUDhiZnVNVWNrdzZkREszWDlreVNEN3lLWkh2YXdhbituNgp0WGlYKytONzFJakxyRTNiSi8vMnM3Z1pWaDlDRVBwYzNYc054UVFDa3luVmdYd2NvUlFQT0lhRGhYMTRnc0UrCmRtRnFpVU1iQ3A4ZWM1ZitvSHZBSEJ0UEF
4OWtNSDFSelQ3WWIycWtxN0VZbnQzUXhDZ0hQdWxPTGNVUkE5dWsKUjZ3UVBabjVSM1U2ei8wcWdYRlU1VUhyTmpaR0ZKazNWajZFc2R2cjM4T1pBZDg2MVc0VkovSzV4eXk0UUpMWQp2SjJSSTdRbDFjYzlhUThzd0FwMzhUUjhBY3p1TThzbnFnb3lWZnhlWDFlTzJPdlhkVjZIWXkya0RSbEh4cHR3CkJ
lTUNqcWhScUdrNmp2UHVRRUJYZGM5MG50QUxFVkhXa0xCR3pRWVNKUWwyektZVm5pcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBeGpLSDBBK010NHZnaW5LMWtUb3RrVTIyditFWHZ3QS83ZmdhdHJ0RTc3SWJzN09iCkEzd0YwOEQweWxmdlJxM2o3OHlLbk5kTXJydVRKN2tuRi95NGc4ZlVBdDkyNGNheitFNVdMS1pORlF
ha0hQeWEKc0U3MGpJQnJid0dHSWl3Rkg1c01sQkxRQXkyQXdQNE1iaWNRa3RyUm9qTTR3UWZoQXR1d3l6RVYwNG5tUGU0ZQpDeGNYc2dDL2dIai9LN1I3M3UrM3M5UDkzVFp4elRLU0wrdjFFcno1YVk0Z2NYVTFTM0t2ZkVMZXlPbjhHTTQ3Ck1kY1Q3U1J6OTdpL3JkbFl0MWxacGFFUU5OREJ2bGhuUkN
5UXpObkZXOWdFeTBmNGlGWWZGQ21Gbm9qb1hyNkYKODQyc2JrRTNoZTE3NUh2Z3Z5T0ZHVUw4cjR4NGl4OVFja25QTXdJREFRQUJBb0lCQUIzSjFuUEZBb2RMdExIYQpUOFBHRkxjMEVQV0I1VW5GeGRZRVppOTBzZ1c4cFVFN0MxOVlzcCtDN3NmQ3M2blIxT0pqd2FtVkNtZHd0Y3RRCm5ybVNPRUZHTlc
xQkhPTU9ORnBybTdRV1FwdVlaZTRkWVRxQ2cycmlta01TM1pBaFFadmdkK0dCZWxZZjdxd1QKQXRkRGM5QStweWRUdjRIenB6UUF4TytsTHZ5ZUIyMlhWZW8wOEIzVU9DVEtHaVBnUTEvbnllNXBxYWVtRUozTgpMWWpVcSswaHg5d2ZxWFdNQ2gwRFBjYlU4SXpIK0YrOTFSYnJVcENQcS9hbVp6Zzg1QjB
WcHBtSXNqUUlmdnlBCjExaEJEUkpKVkxabUFQdFQ1WEYrK0NwNXlXWEdIY0JFbVpEV0hsL1V5NWhTRHZrMjVqWWY0NyszN1cwS2VycDIKUUxhTGJ1RUNnWUVBMDAwZGszeXFNbHYxS3R5TXhtT09OMWVoNEYxVDVBakdHVnJlSWF0RGRmWGJkOFRZV05oVgp6cUY0cWFjenhOaTRNZjl0WVZRMkxZZExrLzJ
RUVQvM283dFBvTlVpS2hHbXV3N2lEOVNXNGlFQ0V0cW4rdWx6CnR4TGFidjh5SnpYVWhHMmtIUXRJbnM5Q0NVVU4xTHJGMVZQYjJwUmN4Y0RCczRoc0F3UkdXRGtDZ1lFQThCL0kKenlFa1V1T3VZYm5hRG9YZGFXQzBkQTBxNTRnSk5melBJUDB4bVd0dUNLTWNjMDdBcys0dzEwR3RqUzg3ZXNrZAp4by9
ONERjY2ZLSzRBMkJxZ2lZbHpKYUJNV0tQckFIQUtCc2JmdDMrRlpYQXhDU01XUVdDRnhGdTBraDlhSUdMCnJZai95T2U4NitYNFhKZEpvVC82YlhRRHFFWjcrVzhBSmw5TXFzc0NnWUVBcVdkRDlRQ1hldlJhcEZoWnpKdjQKWXNveEQ2NERHZWttMlNFT3diT0t6RUdtQ0dtYWdmQS9Ld0F0dXVaQURPc3J
FWHFVK05rSTdvdHZ2bUFsalFwNQp3WnpraEM4Ynl0cUg3NlJJL1NRVks0b0hIWktMNWcvUUk5QkxxMzJSZWZvZ1BXT2hsVjk4ZzBYcXpYKzlUUFhJCnNmVWZhQ2hXRUgwdlRuNXJDaWdkTlpFQ2dZRUE2cTBGb25rdmVOc1A2RzZzMEJqQVJXYS90ZFBRcEt0czVSaUkKamlNbHdGMGdFc3ptMTBLV1RzTnh
kRTY2QVF1eVE5UWVoNXF2aUh3VUdUTW1TQmFJd1YzcS8wSHdUWVdZQ0hGRgpqV3pBdUlMWStkdDdvN1pjZS94SUlhZGwrWm5qQnFubEN0cWpzWVBhUFdwcUNvUEk4QkVJL01PdmQxdzdlWkdrClFkeE5uM1VDZ1lCcTJJWXRER2Vkd0pqZ2t5QTRYUlVXU0tmaEJ6bGRFamRnWGcwbWZaWGZPWWVxbUptRk1
weG4KT293UDdSZTdEN0loNzZ3OTRZMC8vTFZ5Q2I2R2cvK3F6NnpYVVJvZDJCVlVLcjhSQ3lJdnB5WFBRd1hRVzlBTAphNFV1QTRObFZaSUhXazN4V1NTU3lKMmNIT3VCRXVNZzhKZmppT2R4QytIeHU5YU5GOC9IalE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

**Comment by rohanKanojia** [comment]
This client is not fully compatible with Kubernetes 1.14, I hope to get #1442 soon
