### ISSUE TITLE
Edit custom object name whil creating

### ISSUE THREAD

**Issue by roksolana-d** [fabric8io/kubernetes-client#1526]
I would like to change the custom object name dynamically in the moment of creation. I tried to edit custom object name but there is an exception on the edit method call:

```
[info] SparkExampleIntegrationTest:
[info] it_tests.SparkExampleIntegrationTest *** ABORTED ***
[info]   java.lang.IllegalStateException: Not Found
[info]   at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.makeCall(RawCustomResourceOperationsImpl.java:150)
[info]   at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.get(RawCustomResourceOperationsImpl.java:83)
[info]   at it_tests.SparkExampleIntegrationTest.beforeAll(SparkExampleIntegrationTest.scala:45)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:212)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
[info]   at it_tests.SparkExampleIntegrationTest.run(SparkExampleIntegrationTest.scala:17)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:321)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:489)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```
I would like to get the name of the custom object from the environment variable in yaml. Is it possible to do that during custom object creation?
Here is the code I used to create crd, custom object and edit the name of the custom object after its creation:
 ```
 val client: KubernetesClient = new DefaultKubernetesClient()
  val crdContext = new CustomResourceDefinitionContext.Builder()
    .withGroup(crdGroup)
    .withVersion(crdVersion)
    .withPlural(crdPlural)
    .withScope("Namespaced")
    .build()

val sparkCustomResource = client.customResource(crdContext)
sparkCustomResource.create(crdNamespace, loadYaml(sparkAppFile))

sparkCustomResource.get(crdNamespace, crdInstanceName)
      .get("metadata")
      .asInstanceOf[util.HashMap[String, Object]]
      .put("name", crdNewInstanceName)
```

**Comment by rohanKanojia** [comment]
I'm not sure  whether it's even possible to rename kubernetes resources. Are you able to achieve the same thing via `kubectl edit`??

**Comment by roksolana-d** [comment]
No, I was trying to achieve that but it does not work that way.

**Comment by rohanKanojia** [comment]
You can't change name of a Kubernetes resource after creating it.

**Comment by roksolana-d** [comment]
I understand. But how can I change it while creating a custom object? As I wrote I want to get the name from the environment variable.

**Comment by rohanKanojia** [comment]
convert your file into `Map<String, Object>` using jackson and then try changing it's name by casting :
```
((Map<String, Object>)ret.get("metadata")).put("name", "newModifiedname");
```
in next release you would get a method to load your custom resource into a map:
```
  Map<String, Object> ret = client.customResource(context).load(fileStream)
```
for now you can use jackson like we're doing internally here:
https://github.com/fabric8io/kubernetes-client/blob/12fa0993793baa9ba1835c36f2fa696bd739a1b9/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java#L52-L62

I haven't tried it myself, but I think it should work for you.

**Comment by roksolana-d** [comment]
Thanks! It works with a map.
