### ISSUE TITLE
Can't delete service 

### ISSUE THREAD

**Issue by zhengzepeng** [fabric8io/kubernetes-client#1544]
I delete the service like that:

> KubernetesManager.getClient().services().inNamespace(service.getMetadata().getNamespace()).withName(service.getMetadata().getName()).delete();

But i found the service resource still exist！！！！

So i see the source code,i found if i delete the service like that :

>         
        String serviceName = "demo1";
        OperationContext context = new OperationContext();
        context = context.withOkhttpClient(((DefaultKubernetesClient) client).getHttpClient()).withConfig(client.getConfiguration()).withCascading(true);
        ServiceOperationsImpl serviceOperations = new ServiceOperationsImpl(context);
        serviceOperations.inNamespace("default").withName(serviceName).delete();

the service resouce can delete！I just change the cascading parameter(the default value is false,i just set the cascading to true)！

My kubernetes-client version is 4.2.2,and my apiserver version is 1.11.0

**Comment by zhengzepeng** [comment]
This time i just test the service,but i remember it cant delete everything if i use the api before~So i think this is a bug~please help！

**Comment by rohanKanojia** [comment]
Can you share your service yaml so that we can try to reproduce it on our machine?

**Comment by zhengzepeng** [comment]
I run my api-server in the docker(no k8s environment)，so i found the problem！Today i test the kubernetes-client api in the k8s environment,and i found everything is ok！(same api-server)
So i think i missing to run some dependent images！It is my fault and i will find it out！
Thanks to help!!!!
