### ISSUE TITLE
Operation: [list] for kind: [Namespace] with name: [null] in namespace: [null] failed.

### ISSUE THREAD

**Issue by boroda4436** [fabric8io/kubernetes-client#1545]
**What happened**:
Operation: [list]  for kind: [Namespace]  with name: [null]  in namespace: [null]  failed.

**What you expected to happen**:
Expected to create a namespace and receive next msg on the UI: _Successfully created default namespace with name cbs-namespace_

**How to reproduce it (as minimally and precisely as possible)**:
1. Clone the project: https://github.com/boroda4436/kubernetes-demo.git
2. Add your Google Compute credentials key to resources/google_credentials.json and change your project name in application.properties
3. Run main app
4. Visit http://localhost:8080/ and click CREATE CLUSTER
5. After cluster will be deployed - click CREATE_NAMESPACE

Create namespace command will fail and you will see error message right in your browser:

### Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue May 21 11:58:46 EEST 2019
There was an unexpected error (type=Internal Server Error, status=500).
Operation: [create] for kind: [Namespace] with name: [null] in namespace: [null] failed.
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [Namespace]  with name: [null]  in namespace: [null]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:328)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:321)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.lambda$createNew$0(BaseOperation.java:336)
	at io.fabric8.kubernetes.api.model.DoneableNamespace.done(DoneableNamespace.java:26)
	at com.boroda.kubernetes.demo.controller.KubeClusterController.createBasicNamespace(KubeClusterController.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

### ALSO:
I even can't get list of services on my kube-cluster:
Visit: http://localhost:8080/cluster/get-services

**ERROR:**
There was an unexpected error (type=Internal Server Error, status=500).
Operation: [list] for kind: [Service] with name: [null] in namespace: [default] failed.
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Service]  with name: [null]  in namespace: [default]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:148)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:551)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:65)
	at com.boroda.kubernetes.demo.controller.KubeClusterController.getServiceList(KubeClusterController.java:84)

**Comment by rohanKanojia** [comment]
@boroda4436 : Could you please provide a simple test case using kubernetes client which can reproduce your error?

**Comment by bchupika** [comment]
@rohanKanojia Thanks for the reply!
I have created a simple demo app. You may find the URL in the description.
Basic steps are:
1) I am creating a new cluster on the GCP using 
`       Container containerService = createContainerService();
        Container.Projects.Zones.Clusters.Create request =
            containerService.projects().zones().clusters().create(projectName, ZONE, requestBody);`
`        Operation response = request.execute();`
2) I am trying to create a namespace:
`        try (KubernetesClient client = clientFactory.create()) {
            client.namespaces().createNew().withNewMetadata().withName(NAMESPACE_NAME).endMetadata().done();
        }`

On step 2 I am receiving the error.
Please note that I am using kube cluster 1.12 version and basic auth is disabled by default.  Only ca cert data is present.

**Comment by boroda4436** [comment]
@rohanKanojia Thanks for the reply!
I have created a simple demo app. You may find the URL in the description.
Basic steps are:

1) I am creating a new cluster on the GCP using
`Container containerService = createContainerService(); Container.Projects.Zones.Clusters.Create request = containerService.projects().zones().clusters().create(projectName, ZONE, requestBody);
Operation response = request.execute();`

2) I am trying to create a namespace:
`try (KubernetesClient client = clientFactory.create()) { client.namespaces().createNew().withNewMetadata().withName(NAMESPACE_NAME).endMetadata().done(); }`

On step 2 I am receiving the error.
Please note that I am using kube cluster 1.12 version and basic auth is disabled by default. Only ca cert data is present.

**Comment by boroda4436** [comment]
updated a demo project https://github.com/boroda4436/kubernetes-demo
Now you can specify cluster version.
Note that everything is ok with 1.11.8-gke.6, but at the same time demo is not working with 1.12.7-gke.10

**Comment by boroda4436** [comment]
@rohanKanojia, hi! Have you any ideas about why this occurs?

**Comment by rohanKanojia** [comment]
As far as I know this client only supports till kubernetes 1.12.2

**Comment by boroda4436** [comment]
Thank you, @rohanKanojia!
Do you have any road map to support the newest k8s versions?

**Comment by rohanKanojia** [comment]
There is a PR already for updating schema to 1.14.2 #1543

**Comment by boroda4436** [comment]
What I have found: the library is working fine with any version of GKE or kubernetes ONLY IF you have obtained credentials like: gcloud container clusters get-credentials ... and performed some action with kubectl, like: _kubectl describe serviceAccount default_.
I guess that this library should works well without such manipulations

**Comment by boroda4436** [comment]
**SOLVED:** It was required to refresh the Google OAuth2 token and pass to kubeclient. Works fine for all versions. 
**IMPLEMENTED** in this [commit](https://github.com/boroda4436/kubernetes-demo/commit/5d67baba0780d58d6bd3d0ce03bad73047112671)
