### ISSUE TITLE
ConfigMap class not found

### ISSUE THREAD

**Issue by roksolana-d** [fabric8io/kubernetes-client#1552]
I needed to define config map from source file instead of the map so I converted file source into the map and passed it to addToData method in ConfigMapFluentImpl class.
I wanted to contribute this functionality so it would be possible to read data from files into config maps, however, I was not able to find ConfigMapFluentImpl class as well as ConfigMap class definition in this repository. IntelliJ IDEA cannot find these classes in sources as well, 
Also, I have found out that this class is in an archived kubernetes-model repository. 
So I wanted to ask is it even possible to add such functionality?

**Comment by rohanKanojia** [comment]
Our model is generated from kubernetes go source. Have you build your project(`mvn clean install`) before opening up in IntelliJ?

**Comment by roksolana-d** [comment]
Yes, I have built it with maven. I can view the files by following the source, however, I can not find them in kubernetes-model part of the repo. Also, I get the message - `Generated source files should not be edited. The changes will be lost when sources are regenerated`.

**Comment by rohanKanojia** [comment]
These files are generated from json schema(see https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-model/kubernetes-model/src/main/resources/schema/kube-schema.json), they are not supposed to be part of repo since they are generated in `target/` directory after compilation

**Comment by roksolana-d** [comment]
Thanks, now I understand. But which sources exactly should I alter in order to extend the functionality in such a way that config map could be created from a file and not only key/value, a map?

**Comment by rohanKanojia** [comment]
@roksolana-d : polite ping, were you able to resolve your issue? It should work on 4.4.2 I think.
