### ISSUE TITLE
Statefulset isReady with readiness probe

### ISSUE THREAD

**Issue by Incarnation-p-lee** [fabric8io/kubernetes-client#1556]
If I deployment one statefulSet with readiness probe, from my understanding it will check the readiness probe for isReady validation. But from below, it seems only check on status and spec replicas for isReady. If I understanding correctly, replicas available doesn't mean the pods of statefulset readiness, right ? Please correct me if something misunderstanding, thanks a lot.

https://github.com/fabric8io/kubernetes-client/blob/716e667307224473129a15a98cced5b5ae2da5f2/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java#L97

**Comment by marekadare** [comment]
If I understand it correctly the spec object is the specified/desired state and status the current state.
For me the problem is that these ready checks never work, because the current state gets never updated.
