### ISSUE TITLE
How to use port-forward feature?

### ISSUE THREAD

**Issue by dodalovic** [fabric8io/kubernetes-client#1557]
Hi, I'm trying to figure out how to use port-forwarding. Are there some samples of how to use it? Also - how do I manage connections? Is this done for me, or I need to call something (and when)? 

Many thanks for the great tool!

**Comment by rohanKanojia** [comment]
@kunal-kushwaha : Could you please look into it? I think it would be nice if we add an example of port forwarding.

**Comment by kunal-kushwaha** [comment]
> @kunal-kushwaha : Could you please look into it? I think it would be nice if we add an example of port forwarding.

@rohanKanojia : Alright 👍
