### ISSUE TITLE
creating new CRD 

### ISSUE THREAD

**Issue by FridMehdi** [fabric8io/kubernetes-client#1558]
@rohanKanojia please some help i went create New CRD by folllowing your example but no result 
in this repo https://github.com/FridMehdi/kafka-operator/tree/master/src/main/java/nb/kafka/operator
i have already two classes and models 
`KafkaTopicCustomResourceManager KafkaTopicCustomResourceManager.java`
but i need just to know how it organized and how could i consume a CRD.yml 

could you please take a look in this repos tkyou man  #

**Comment by rohanKanojia** [comment]
hmm, we've introduced a new way to create custom resources:

https://github.com/fabric8io/kubernetes-client/blob/0e033fdeb116cd45fb4fac17749ba0145a7c213c/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/RawCustomResourceExample.java#L36-L50

**Comment by FridMehdi** [comment]
@rohanKanojia  tkyou for your reply ok and how i could load my CRD what is the role of class CRDLoadExample.java https://github.com/fabric8io/kubernetes-client/blob/0e033fdeb116cd45fb4fac17749ba0145a7c213c/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDLoadExample.java 
and could you please present any example of CRD.yml file

**Comment by rohanKanojia** [comment]
this is just an example class demonstrating how to use client to create CRDs

**Comment by rohanKanojia** [comment]
I'm saying you can create custom resources easily if you use my suggested approach. This is supported on latest client, v4.2.2

**Comment by FridMehdi** [comment]
ok @rohanKanojia tkyou for the clarification  
the problem is when i update <version.fabric8.k8s.client>3.0.1</version.fabric8.k8s.client> to 4.2.2 i cannot find class Deployement any more i think it was replaced by another thing io.fabric8.kubernetes.api.model.extensions.Deployment

**Comment by rohanKanojia** [comment]
in 4.x deployment can be found in io.fabric8.kubernetes.api.model.apps.Deployment

**Comment by rohanKanojia** [comment]
@FridMehdi : Were you able to resolve your issue? If yes, can we close this?
