### ISSUE TITLE
why i can't find 'ConfigBuild.java' in github resource?

### ISSUE THREAD

**Issue by chentging** [fabric8io/kubernetes-client#1560]
issue is the title
![image](https://user-images.githubusercontent.com/29357333/58797497-be421780-8632-11e9-9dce-707455e75ba4.png)

**Comment by rohanKanojia** [comment]
@chenlein : Umm, were you able to find it before? In what versions?

**Comment by chentging** [comment]
@rohanKanojia any version all not find `ConfigBuild.java` file in github repo,  in maven jar can find `ConfigBuild.class` , but no source, i only want to see `ConfigBuild.java` source code
![image](https://user-images.githubusercontent.com/29357333/58798730-f8f97f00-8635-11e9-9826-9f5bab165135.png)

**Comment by rohanKanojia** [comment]
Not sure about ConfigBuild, but there is one ConfigBuilder.java which is generated via sundrio, it's not a part of source code. It's generated in your target/ directory after you do `mvn clean install`

**Comment by chenlein** [comment]
@rohanKanojia @chentging : I can not find it, just only one ConfigBuilder.class in kubernetes-model-x.x.x.jar！And，kubernetes-model-x.x.x.jar is generated via `mvn clean install`.

**Comment by rohanKanojia** [comment]
What is output of this command on top of your directory?
```
find . -iname ConfigBuilder.java
```

**Comment by chentging** [comment]
@rohanKanojia 
oh, I'm sorry, I don't correctly write the issue title, I want to say "ConfigBuilder.java" .
My output is the same as you .
![image](https://user-images.githubusercontent.com/29357333/59168588-fa143a00-8b68-11e9-87b6-ac3715a36c64.png)

Is `ConfigBuilder.java` generated via `io.sundr:sundr-codegen:jar` ?

**Comment by rohanKanojia** [comment]
yes

**Comment by chentging** [comment]
@rohanKanojia Thanks a lot, I will close this issuse
