### ISSUE TITLE
OpenShift Client -- Images API is missing

### ISSUE THREAD

**Issue by leogps** [fabric8io/kubernetes-client#1572]
OpenShift client has imageStreams and imageStreamTags methods but does not have the images() method. 
However, I see that corresponding model (Image, ImageList, etc) already exists in the library.
Moreover, the imageStreams() API makes use of the Image and ImageList objects. It would be nice to have the images() method in OpenShift Client. Saves us from extending the OpenShift Client.

The REST API is already part of the generate.go:
https://github.com/fabric8io/kubernetes-client/blob/a909fda0daf0ad91ccd02e2f02c66f47d33f54d0/kubernetes-model/cmd/generate/generate.go#L25

oc tool example:
```
oc get images

oc get images sha256:....
```

**Comment by rohanKanojia** [comment]
Hmm, I think we need to add support for it in dsl.
