### ISSUE TITLE
how to get the real name of a pod

### ISSUE THREAD

**Issue by intellij-rainbow-brackets** [fabric8io/kubernetes-client#1576]
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

I tried 
```
CRD crd = ???
crd.getMetadata().getName()
```

but it returned like "task-mrq2h", but when I use the `kubectl get pod`, it turns out that the real name of the pod is "task-mrq2h-1235138403", can someone show me how to get the real name correctly?

**Comment by intellij-rainbow-brackets** [comment]
Or how can I filter the pods by name?

**Comment by intellij-rainbow-brackets** [comment]
I got it worked with: 
1. operate the delete operation on the `crdClient` not on the `k8sClient`
2. delete with a `cascading` operation

Hope this can help someone, but the last question is not answered, and I didn't find it from docs:

How can I filter the pods by name?

**Comment by rohanKanojia** [comment]
I'm not able to understand your question. Why are you not using labels/match selectors for filtering our pods?

**Comment by rohanKanojia** [comment]
@intellij-rainbow-brackets : Were you able to resolve your issue?

**Comment by intellij-rainbow-brackets** [comment]
Well, not really, I want to fuzzy search with a resource name, but still don't know how to achieve. I think a example would be great.😁

On Jun 12, 2019, at 6:05 PM, Rohan Kumar <notifications@github.com<mailto:notifications@github.com>> wrote:


@intellij-rainbow-brackets<https://github.com/intellij-rainbow-brackets> : Were you able to resolve your issue?
