### ISSUE TITLE
How to use DeploymentRollback ?

### ISSUE THREAD

**Issue by Zephery** [fabric8io/kubernetes-client#1577]
i can't find any example to use DeploymentRollback.........please help

**Comment by rohanKanojia** [comment]
Not sure, I think we're missing support there.

**Comment by Zephery** [comment]
My project needs it, i don't know how to realize that. Do you know how to use it for temporary?

**Comment by Zephery** [comment]
anyone can help?

**Comment by rohanKanojia** [comment]
we need to add it's support I think. I can try next weekend if i get time.

**Comment by Zephery** [comment]
1111

**Comment by rohanKanojia** [comment]
I've added support for DeploymentRollback in https://github.com/fabric8io/kubernetes-client/pull/1920
