### ISSUE TITLE
Replace of Job should add extra selector property to the resource

### ISSUE THREAD

**Issue by victornoel** [fabric8io/kubernetes-client#1586]
Hi,

I'm trying to use the `createOrReplace` method available on `client.inNamespace(namespace).batch().jobs()`.

I load a job definition from a file and I expect it to be created or replaced in case it already exists. The assumption is that kubernetes will re-run the job in case the replacement is different from the one already deployed.

The problem is that the API of kubernetes answers with 422 and the following type of errors:
```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://cluster-xxxxxx.hcp.westeurope.azmk8s.io/apis/batch/v1/namespaces/dev/jobs/myjob. Message: Job.batch "myjob" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value....
```

So I added a selector on the job, but then I get the following error:
```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://cluster-xxxxxx.hcp.westeurope.azmk8s.io/apis/batch/v1/namespaces/dev/jobs/optigrid. Message: Job.batch "myjob" is invalid: [spec.template.metadata.labels[controller-uid]: Required value: must be '36910c27-8e83-11e9-bd3c-72b51ec2d813', spec.template.metadata.labels[job-name]: Required value: must be 'myjob', spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/name":"app", "app.kubernetes.io/instance":"app1"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: `selector` not auto-generated, spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"app1", "app.kubernetes.io/name":"app"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable, ....
```

I feel like `replace` should be reading from the existing job and retrieve the needed values for the selector. A bit like how `kubectl apply` is able to update a resource by merging it with the upstream one.

Without this, I don't see how `createOrReplace` can be used successfuly, but maybe I am mistaken about what `createOrReplace` is there for?

**Comment by rohanKanojia** [comment]
Hmm, this is a problem, we're facing something similar in https://github.com/fabric8io/fabric8-maven-plugin/issues/1648

**Comment by rohanKanojia** [comment]
@victornoel : Do you have time to look into this issue? Would really appreciate if you could raise a PR to fix this. Otherwise, I would try to find some time next weekend

**Comment by victornoel** [comment]
@rohanKanojia honestly, I'm pretty sure I won't be able to, both because of time and skills :)

That being said, another (less desirable I think) solution would be to simply say that we should wait for something like https://github.com/kubernetes/enhancements/issues/555 to solve it API-side.

**Comment by dlafreniere** [comment]
Bump. We're facing this issue as well

**Comment by rohanKanojia** [comment]
@dlafreniere : Which version are you using? 4.8.0?

**Comment by dlafreniere** [comment]
yes.

to give some context, I'm looking at reproducing the behaviour of `kubectl apply -f job.yaml`. 
When I run that in debug, I see that kubectl will call a PATCH on the existing job. However, `createOrReplace` seems to try calling PUT.
