### ISSUE TITLE
OpenShiftAdapter uses deprecated APIs to check if cluster is an OpenShift cluster

### ISSUE THREAD

**Issue by adambkaplan** [fabric8io/kubernetes-client#1587]
The OpenShift DevEx team has identified two issues with the `OpenShiftAdapter.isOpenShift` [1] method used by kubernetes client:

1. It checks the `/oapi/` path, which has been deprecated in 4.1
2. It starts walking from the root path`/` to see if the apiserver supports OpenShift components. The OpenShift auth team wants to prevent discovery at the root level - this blocks their effort [2].

[1] https://github.com/fabric8io/kubernetes-client/blob/master/openshift-client/src/main/java/io/fabric8/openshift/client/OpenshiftAdapterSupport.java#L48-L76
[2] https://github.com/openshift/origin/pull/23049

**Comment by gabemontero** [comment]
according to @enj `the fix would be to just use `/apis` directly
`

**Comment by gabemontero** [comment]
hey @akram would opening a corresponding jira somewhere be a good idea wrt getting the appropriate visibility / priority on this ?

**Comment by rohanKanojia** [comment]
this doesn't look complicated; Could anyone please raise a PR to fix this? :-)

**Comment by gabemontero** [comment]
ok @waveywaves and I looked at this a bit today as part of the transfer of openshift/jenkins to the devtools team

I gave him a couple of suggestions of how to switch this, but that was after only looking at the code for the first time while with him

Ultimatlely, we need a masterURL/api http rest invocation in BaseOperation that serializes into a class similar RootPath.class

But of course if @rohanKanojia knows better please chime in

do be aware that this problem will be blocking the 4.2 release of openshift, so it will a high priority for our managment

associated bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1729522

**Comment by akram** [comment]
@gabemontero we are now tracking it also as a blocker in under DEVEXP-390 jira

**Comment by gabemontero** [comment]
We are doing some research here today.

the k8s model in this client does not appear to have an APIGroupList a la https://docs.okd.io/latest/rest_api/apis/v1.APIGroupList.html or an APIGroup a la https://docs.okd.io/latest/rest_api/apis/v1.APIGroup.html

those are the items returned when you hit <master url>/apis

there is a io.fabric8.kubernetes.model.annotation.ApiGroup but that must be related to the common apiGroup field in all objects (or that is my best guess)

there is also a io.fabric8.kubernetes.client.APIGroupExtensionAdapter class that attempted to interrogate api groups, but it was leveraging root paths, so of course per the description here we cannot use it

@waveywaves attempted to regenerate the model to see if we can find these classes but it is failing for him.

we need a maintainer of this repo to get the model sorted out so the APIGroupList response from hitting <master url>/apis can be sanely interrogated.

And given this is an OpenShift 4.2 blocker that has been open for a month, we'd like to get some expedited focus for this.

@pradeepto - can you help us get some focus on this?

@adambkaplan @enj fyi

**Comment by rohanKanojia** [comment]
@gabemontero : Hi, I would need to look into this closely. At first look, it seemed like an easy fix, but from your research, it looks more involved. I will prioritize this in my list.

**Comment by rohanKanojia** [comment]
@gabemontero: Question, why are you using this client for Openshift 4.x when we haven't provided it's support yet?

**Comment by gabemontero** [comment]
@rohanKanojia my recollection was that the api objs for the <master url>/apis endpoint were the same for 3.x vs. 4.x.  The /apis endpoint has existed for several release.  I happened to be in the 4.x documentation and pulled it from there.

You should be able to bring up the REST api documentation for the 3.11 branch and find it as well.

But if you have trouble with that, let us know and I will get you a pointer.

**Comment by rohanKanojia** [comment]
yeah, that would be helpful. Thanks!

**Comment by gabemontero** [comment]
api group:  https://docs.okd.io/3.11/rest_api/apis/v1.APIGroup.html
api group list: https://docs.okd.io/3.11/rest_api/apis/v1.APIGroupList.html

**Comment by rohanKanojia** [comment]
Thanks for the links. I have some doubts. Still, I don't have a clear picture of what your issue is.

 I don't understand why do we need these resources for overriding behavior of `isOpenshift()` method? You said in your first comment that you need to use `/apis` rather than `/oapis` . Wouldn't providing a way to override current behavior solve your problem? Why do we need to have a REST invocation in BaseOperation(or did you mean REST invocation while checking `isOpenshift` and in response you would get `APIGroup`/`APIGroupList`)?

**Comment by gabemontero** [comment]
I am not sure I know how to elaborate further than what @adambkaplan put in the description at https://github.com/fabric8io/kubernetes-client/issues/1587#issue-456255465

But I'll try:
- /oapis is getting deprecated .... so generally speaking, as a long term option, that is not ideal; it would help your official support for 4.x as you said earlier if you use the 3.x api that is blessed in 4.x as well
- same with root path ... your use of root path will eventually not work there; in fact this client's use of it is blocking that feature work, so if we can start moving at least some of your paths to be better suited, it helps those efforts down the line
- we are *NOT* asking you to employ new APIs that are only available in 4.x;  only that you use existing 3.x APIs that will continue to work in 4.x
 - finally, yes, if there is a way for the openshift sync plugin that @akram and @waveywaves now own to supply the implementation for the `isOpenshift` method, that is a viable path as well.  And I'm guessing more expedient.  If that is what you meant by `Wouldn't providing a way to override current behavior solve your problem?`

**Comment by rohanKanojia** [comment]
@gabemontero : I've raised a PR to add APIGroup. What are the next steps? I can go ahead and refactor that method for that REST call implementation if it's a good approach and backward compatible for 3.11 and 3.10.

**Comment by gabemontero** [comment]
@rohanKanojia - just to be clear, you technically mean both APIGroup and APIGroupList, right?  Where APIGroupList is literally a list of APIGroup.

Next, once that model change can be made available to the fabric8io/kubernetes-client/openshift-client code, then yes, I think you can refactor the isOpenshift method in however way you see fit so that we can execute a <master api server url>/apis invocation to get the APIGroupList, where once iterates over it and does a similar string compare for suffixes of ".openshift.io".

And yes, APIGroup and APIGroupList are available via the /apis endpoint for both 3.10 and 3.11.

**Comment by rohanKanojia** [comment]
@gabemontero : I've released 4.3.1 which contains that fix, please try it out and share feedback whether it's working for you or not. Feel free to reopen if it doesn't work

**Comment by akram** [comment]
@rohanKanojia we have tested it against a 3.11 and 4.2 OpenShift cluster in the jenkins-sync-plugin and it seems to do well.
Thank you for your responsiveness!
