### ISSUE TITLE
HorizontalPodAutoscaler apiVersion v1

### ISSUE THREAD

**Issue by Zephery** [fabric8io/kubernetes-client#1589]
HorizontalPodAutoscaler's apiVersion in kubernetes1.14 change to v1, and HorizontalPodAutoscalerSpec change a lot, please support it

**Comment by chamhaw** [comment]
Are you sure? In kubernetes 1.14, HorizontalPodAutoscaler model has nothing changed, But you simply removed all Metrics options in beta apis.
