### ISSUE TITLE
Why do list classes implements raw KubernetesResourceList?

### ISSUE THREAD

**Issue by tombentley** [fabric8io/kubernetes-client#1596]
In kubeneteres-model the `*List` classes implement the raw type `KubernetesResourceList`, for example

```
public class DeploymentList implements KubernetesResource, KubernetesResourceList
```

But `KubernetesResourceList` is generic in the element type `E`, so oughtn't it be `implements KubernetesResourceList<Deployment>`?

**Comment by iocanel** [comment]
What you say seems right! Don't recall if this was by choice or by accident.

**Comment by tombentley** [comment]
It's a problem because, for example, it means that javac ends up warning about unchecked casts in our client code. Obviously it's only a warning, so is easily worked around, but it would be nice if we didn't have to `@SupressWarnings("unchecked")`.

**Comment by tombentley** [comment]
This is still a problem, AFAIK.

**Comment by tombentley** [comment]
Actually, it looks this like has been fixed.
