### ISSUE TITLE
Add method to specify DeleteOptions propagationPolicy

### ISSUE THREAD

**Issue by dsimansk** [fabric8io/kubernetes-client#1614]
I haven't found a way to specify `propagationPolicy` for the delete operation. 

In a log I can see the currently `orphanDependents` is used with boolean value, but in fact that option is already [Deprecated](https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/types.go#L464-L469) in K8s.

Would it be possible to add such config method?

```
INFO: {"apiVersion":"v1","kind":"DeleteOptions","gracePeriodSeconds":0,"orphanDependents":false}
```

https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#setting-the-cascading-deletion-policy

**Comment by rohanKanojia** [comment]
I think #1742 would solve this
