### ISSUE TITLE
Error on deploying a horizontal Pod autoscaler on kubernetes 1.15.0 cluster.

### ISSUE THREAD

**Issue by ScrapCodes** [fabric8io/kubernetes-client#1633]
### On trying to create a autoscaler as follows
```
kubernetesClient.autoscaling().horizontalPodAutoscalers().createOrReplace(hpa)
```
```scala
private def hpaMetrics =  new MetricSpecBuilder()
    .withType("Resource")
    .withNewResource()
      .withName("cpu")
      .withTargetAverageUtilization(50)
      .endResource()
    .build()

  def hpa(config: MicroServiceClusterConfig): HorizontalPodAutoscaler = {

    val name = s"${config.clusterPrefix}-${config.clusterName}"
    new HorizontalPodAutoscalerBuilder()
      .withApiVersion("autoscaling/v2beta2")
      .withKind("HorizontalPodAutoscaler")
      .withNewMetadata()
        .withName(name)
        .withLabels(Services.labels(config.clusterPrefix).asJava)
        .endMetadata()
      .withNewSpec()
        .withMaxReplicas(5)
        .withMinReplicas(1)
        .withNewScaleTargetRef()
          .withApiVersion("apps/v1")
          .withKind("ReplicaSet")
          .withName(name)
          .endScaleTargetRef()
      .withMetrics(hpaMetrics)
      .endSpec()
      .build()
}
```
### Following error is produced.
 ```io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://<...>:6443/apis/autoscaling/v2beta2/namespaces/default/horizontalpodautoscalers. Message: HorizontalPodAutoscaler.autoscaling "tefd3f-testing" is invalid: [spec.metrics[0].resource.target.type: Required value: must specify a metric target type, spec.metrics[0].resource.target.type: Invalid value: "": must be either Utilization, Value, or AverageValue, spec.metrics[0].resource.target.averageUtilization: Required value: must set either a target raw value or a target utilization].```

**Comment by ScrapCodes** [comment]
Client version used 4.3.0

**Comment by rohanKanojia** [comment]
what's your kubernetes  version?

**Comment by rohanKanojia** [comment]
ohk, for 1.15.0 this client isn't compatible
