### ISSUE TITLE
Creation using RC/Service/Namespace temlpates

### ISSUE THREAD

**Issue by parikhyash** [fabric8io/kubernetes-client#165]
I was looking at the creation example where builders are used to create k8s components.
I wanted to know if there's a way to pass a json/yaml to the constructor for creation.

If I was creating a service whose spec had many ports, it would be painful to define all of these in the builder. The amount of code would be very large.

Instead, a better option would be to pass the json and maybe internally ObjectMapper could be used to map it to the k8s model.

**Comment by jimmidyson** [comment]
Not quite sure what you're asking. Sorry! Can you explain a bit more please?

**Comment by parikhyash** [comment]
@jimmidyson Updated it now. Hit enter too early

**Comment by jimmidyson** [comment]
@parikhyash Ah that makes more sense :)

You can do that with `client.pods().inNamespace(...).load(is).create()`, where `is` is an `InputStream` of JSON or YAML.

You can do this with any type, including possibly most usefully, lists so `client.lists().inNamespace("ns").load(is).create()`.

**Comment by parikhyash** [comment]
Awesome. Thanks @jimmidyson
