### ISSUE TITLE
Incompatibe with Android

### ISSUE THREAD

**Issue by derEisele** [fabric8io/kubernetes-client#1650]
I'm trying to build a Kubernetes Client for Android using this awesome library. To circumvent automatic file loading from `.kube/config`, I'm using `Config.fromKubeconfig(String kubeconfigContents)` to initialize the configuration. Never the less this method tries to load the file from `.kube/config` which is quite annoying with Androids very restricted file access in mind.

So could someone familiar with this project and the ConfigBuilder in particular please delete this line finally as it should have been done over 2 year ago according to the deprecation warning.
https://github.com/fabric8io/kubernetes-client/blob/9ac1ff90f35ebdd7da66286c847e2d07e2b97caa/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L200

This is the deadly line of code:
https://github.com/fabric8io/kubernetes-client/blob/9ac1ff90f35ebdd7da66286c847e2d07e2b97caa/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L468

And a stack trace:

```
W/System.err: java.lang.NoSuchMethodError: No virtual method toPath()Ljava/nio/file/Path; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-libart.jar)
W/System.err:     at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:468)
        at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:215)
        at io.fabric8.kubernetes.client.Config.<init>(Config.java:200)
        at io.fabric8.kubernetes.client.Config.fromKubeconfig(Config.java:448)
        at io.fabric8.kubernetes.client.Config.fromKubeconfig(Config.java:442)
        at <My Code>
```

This is version 4.3.1 for the record.

**Comment by rohanKanojia** [comment]
hmm, need to prioritize this....

**Comment by gastaldi** [comment]
@derEisele I created https://github.com/fabric8io/kubernetes-client/pull/1693 which allows you to specify a System property (`-Dkubernetes.disable.autoConfig`) to disable auto-configuration in the Config constructor. Can you give it a try before we merge it ? Thanks
