### ISSUE TITLE
Could not find artifact io.fabric8:openshift-client:pom:4.3-SNAPSHOT 

### ISSUE THREAD

**Issue by Nancy-Chauhan** [fabric8io/kubernetes-client#1675]
I get the error when I am trying to build the project with clone :
```
Could not find artifact io.fabric8:openshift-client:pom:4.3-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots)
```

**Comment by szbrain** [comment]
[WARNING] The POM for io.fabric8:openshift-client:jar:4.3-SNAPSHOT is missing, no dependency information available
Downloading from nexus: http://127.0.0.1:8081/repository/maven-public/io/fabric8/openshift-client/4.3-SNAPSHOT/openshift-client-4.3-SNAPSHOT.jar
