### ISSUE TITLE
ServiceAccount seems to be only read when ~/.kube exists

### ISSUE THREAD

**Issue by gastaldi** [fabric8io/kubernetes-client#1676]
By looking at https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L216 it seems it only attempts to use it when `~/.kube` exists, which does not exist in an Operator image

Also https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L401-L402 seems wrong, as an exception is thrown if the file does not exist

**Comment by iocanel** [comment]
Hi @gastaldi,

The intention of the code was:

Try reading `.kube/config` if it doesn't exist try reading the service account and so on.

From a quick glimpse at the code, it seems to me that it's aligned with the intention.

Can you please clarify, what is the expectation and what is actually happening?

**Comment by gastaldi** [comment]
@iocanel that's correct, I closed the issue already. I was having a RBAC problem but while debugging I figured out that the authentication code wasn't the problem. Sorry about the noise :)
