### ISSUE TITLE
HTTPIngressRuleValueFluentImpl removeFromPaths can't working

### ISSUE THREAD

**Issue by tony-Ma-yami** [fabric8io/kubernetes-client#1679]
i want remove HTTPIngressPath from paths used by removeFromPaths(HTTPIngressPath... items), but in this method implement, it will be create a new Object of HTTPIngressPathBuilder every time. is it a bug ?

**Comment by JiechengHe** [comment]
我遇到了和你一样的问题，而且通过debug我觉得是一个bug。你有没有别的解决办法？

**Comment by JiechengHe** [comment]
I have encountered the same problem as you, and I think it is a bug through debug. Do you have any other solutions?

**Comment by tony-Ma-yami** [comment]
Yes, you can create one or more new paths add in paths override the old path, hope can help you
