### ISSUE TITLE
Get Annotations : kubectl describe deployments/$SERVICE -n $Namespace

### ISSUE THREAD

**Issue by Nancy-Chauhan** [fabric8io/kubernetes-client#1681]
I want to get annotations information using kubernetes client for the following command on CLI. When I use the following command on CLI, it generated specific information which contains annotations also : 
```
kubectl describe deployments/$SERVICE -n $Namespace
```

 I use the following function to get the deployment list . But I only want the information related to annotations.
```
AppsV1Api api1 = new AppsV1Api();
V1DeploymentList response = api1.listDeploymentForAllNamespaces(null, null, null, null, null, null,null,null,null);
System.out.println(response);
```

Is there any way to generate this via kubernetes client - java?

**Comment by rohanKanojia** [comment]
Are you sure you're on right github repository? Your code is of official kubernetes client. This is fabric8 kubernetes client's github repo. Anyway, you can get annotations like this in our case:
```
  KubernetesClient client = new DefaultKubernetesClient();
  System.out.println("Annotations: " + client.apps().deployments().inNamespace("ns").withName("deployment1").get().getMetadata().getAnnotations().toString());
```

**Comment by Nancy-Chauhan** [comment]
Yes @rohanKanojia  Thank you so much for the help . I am actually trying to list all the namespaces using this client and trying to get annotations of all listed namespaces

**Comment by rohanKanojia** [comment]
`client.namespaces().list()` should be able tor return all namespaces to you. You can iterate over `NamespaceList` in order to filter it according to your needs

**Comment by Nancy-Chauhan** [comment]
Thank you so much @rohanKanojia
