### ISSUE TITLE
when I user api delete deployment ,but pod cant not delete 

### ISSUE THREAD

**Issue by wangjianxiang** [fabric8io/kubernetes-client#1689]
when I user api delete deployment ,but pod cant not delete pod belong to deployment

**Comment by rohanKanojia** [comment]
Which version are you using? Is `cascading()` is set to true?

**Comment by wangjianxiang** [comment]
I use kubernetes-client 4.2.1，how to set up cascading()? when create deployment to set up?

**Comment by rohanKanojia** [comment]
Try on version 4.4.0 there is cascading (true) in dsl

मंगल, 6 अग॰ 2019, 15:16 को Xtjian <notifications@github.com> ने लिखा:

**Comment by wangjianxiang** [comment]
Can you show me your code  where  to set up  cascading (true)

**Comment by wangjianxiang** [comment]
Thank you very much for your reminder. I know the problem. I've tried to fix it.
