### ISSUE TITLE
Retrieve CPU and Memory resource Usage of a Node

### ISSUE THREAD

**Issue by varun93** [fabric8io/kubernetes-client#1700]
I am trying to retrieve a node's CPU and Memory Resource usage. Similar to what `kubernetes describe node NODE_NAME` would provide.

```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests     Limits
  --------           --------     ------
  cpu                925m (23%)   320m (8%)
  memory             848Mi (10%)  602Mi (7%)
  ephemeral-storage  0 (0%)       0 (0%)
``` 

These numbers are the totals for all the pod requests/limits in the node. I was hoping to find this information in the [getStatus](https://static.javadoc.io/io.fabric8/kubernetes-model/4.4.1/io/fabric8/kubernetes/api/model/NodeStatus.html) method. But couldn't find any relevant there.

My approach was to aggregate this information from the pods present in the node. But as I see `kubectl describe pod POD_NAME` doesn't reveal the pod resource usage information. 

So my question is if there is a way to retrieve cpu  and memory resource usage of a node using the Fabric Client?

**Comment by coki230** [comment]
@varun93 how do you fix it, i have the same confuse with you.

**Comment by varun93** [comment]
The resource requests and limits of a node from kubectl is aggregated by querying from the containers in the node. So essentially you need to query resource requests and limits from the underlying containers in the node and aggregate them yourself.

**Comment by coki230** [comment]
@varun93 thank you
