### ISSUE TITLE
with 4.4.1 HorizontalPodAutoscalerSpecBuilder found no metric method

### ISSUE THREAD

**Issue by sunxianchao** [fabric8io/kubernetes-client#1707]
i can't find method to set metric in HorizontalPodAutoscalerSpecBuilder class
![image](https://user-images.githubusercontent.com/1154766/62994867-a7207100-be90-11e9-9f22-ffaae36ef46a.png)

**Comment by rohanKanojia** [comment]
@sunxianchao : HorizontalPodAutoscaler's spec has changed a bit since past kubernetes releases, which kubernetes version are you using? Is metric supported on latest releases also(like 1.14 or 1.15) ?

**Comment by chamhaw** [comment]
> @sunxianchao : HorizontalPodAutoscaler's spec has changed a bit since past kubernetes releases, which kubernetes version are you using? Is metric supported on latest releases also(like 1.14 or 1.15) ?

What has it changed?
in v1 apis, HorizontalPodAutoscalerSpec still has 4 fields as before. (scaleTargetRef, minReplicas, maxReplicas, targetCPUUtilizationPercentage).
After your fix [#1590](https://github.com/fabric8io/kubernetes-client/pull/1590) we can not use extension hpa metrics anymore.

**Comment by rohanKanojia** [comment]
What? But I have updated HorizontalPodAutoscalerSpec to align with v1 apis.

**Comment by rohanKanojia** [comment]
Have they been changed again in 1.15 release? These specs are parsed from kubernetes source itself.

**Comment by chamhaw** [comment]
@rohanKanojia 
No, nothing changed in 1.15 release.
and yes, Kubernetes v1 apis never have supported extra hpa metrics.
But Fabric8-client users have been using extra hpa metrics via the HorizontalPodAutoscalerSpec model. Your aligning break the client compatible.

**Comment by rohanKanojia** [comment]
ah, sorry for that. I wonder if we can accommodate both of these somehow to keep everyone happy. I'll fix this before next release.
