### ISSUE TITLE
Replace ci.fabric8.io jobs with c̶i̶r̶c̶l̶e̶C̶I̶ other workflows

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#1714]
![Screenshot from 2019-08-19 13-11-36](https://user-images.githubusercontent.com/13834498/63247541-e4b33e80-c282-11e9-9a20-2a80acbe64d6.png)
We need to replace these jobs as ~ci.fabric8.io is going to shut down soon~

**Comment by manusa** [comment]
I think we can switch everything to GitHub actions so we have some consistency.

We can also implement a GitHub App > bot so that it takes care of stuff like merging, PR assigning, validation, etc.

### See also
- https://developer.github.com/apps/
- https://github.com/probot/probot

**Comment by rohanKanojia** [comment]
Till now apart from the merge job, everything is migrated to Github Actions.

**Comment by shawkins** [comment]
Resolving as out of date.
