### ISSUE TITLE
createOrReplace function does not work properly for custom defined resources

### ISSUE THREAD

**Issue by abinet** [fabric8io/kubernetes-client#1724]
I'm trying to use createOrReplace function for some CDR but it returns HTTP 422 (Unprocessed entity) on second call. This happens because resource version is not provided in metadata: "mycrd.charts.helm.k8s.io "test" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update". 

Probably it is releated to https://github.com/kubernetes/kubernetes/issues/70674

**Comment by rohanKanojia** [comment]
Could you please share some code snippet which is causing this? That might help in figuring out whether it's kubernetes issue or client's issue.

**Comment by abinet** [comment]
It's hard for me to provide code snippet but here are the steps to reproduce:
- deploy some custom resource definition
- use fabric8 createOrReplace function to deploy some custom defined resource (like mentioned by @doctapp ScheduledSparkApplcation) initially
- use fabric8 createOrReplace function to update CDR 
- you get HTTP Error 422 on second call

As I already wrote most probably it is a k8s issue but it makes createOrReplace function useless for CDRs.

**Comment by Silvakilla** [comment]
I have the same issue with edit. We try client.customResource(context).edit(namespace,name,stream) and it runs directly into an HTTP 422. With createOrReplace it works just fine, not sure whats wrong here.

**Comment by doctapp** [comment]
Seems for CRDs, and most k8s resources, you need to first do a GET to read metadata.resourceVersion and then add it to the PUT request. If both match the PUT will succeed, otherwise it's a 422.

**Comment by rohanKanojia** [comment]
Just wondering if we should modify our `createOrReplace` for this. Or it is a bug in kubernetes?

**Comment by Silvakilla** [comment]
@doctapp 
It works, just getting the existing resource and then adding the resourceVersion to the edited resource. 

@rohanKanojia 
Not sure if it is really a bug of more of a "security feature". Normally you  can get the resource via its name, but you can only change it with the current got resourceVersion. To make life easier, atleast for now, you could add that to edit and createOrReplace or leave it up for the user of the lib.
