### ISSUE TITLE
How to configure multiple instances

### ISSUE THREAD

**Issue by shenhonglei** [fabric8io/kubernetes-client#1735]
How to configure multiple instances, I have three k8s, can we let kubernetes-client read configuration information from the database. Is there such an example?

**Comment by rohanKanojia** [comment]
I'm not sure that's possible using one instance of client, you can have three different instances of client using three different configs.

**Comment by FreddyShen** [comment]
> I'm not sure that's possible using one instance of client, you can have three different instances of client using three different configs.

Thank you for your advice, but it's not what I want.

I want to use a kubernetes-client instance to switch between different k8s or openshift.

**Comment by walnut-tom** [comment]
#### This is my experience, you can try.
```
        String configContent = "configuration information from the database";
        Config config = Config.fromKubeconfig(configContent);
        DefaultOpenShiftClient client = new DefaultOpenShiftClient(OpenShiftConfig.wrap(config));
        Assert.assertNotNull(client);
```

**Comment by shawkins** [comment]
Resolving as a duplicate of #1512
