### ISSUE TITLE
How to create pull secrets?

### ISSUE THREAD

**Issue by PascalKu** [fabric8io/kubernetes-client#1737]
Hey there,

is it possible to create k8s pull secrets using this api equivalent to this command line?

```kubectl create secret docker-registry --dry-run=true test --docker-server=null --docker-username=test --docker-password=lol -o yaml > docker-secret.yaml```

Thanks for each contribution!

**Comment by zhangzerui20** [comment]
Can we do this?

**Comment by zhangzerui20** [comment]
Like Http api:

`POST /api/v1/secrets HTTP/1.1
Authorization: Bearer $TOKEN
Accept: application/json
Connection: close
Content-Type: application/json'

{
  "kind": "Secret",
  "apiVersion": "v1",
  ...
}`

**Comment by zhangzerui20** [comment]
Can we do this?

**Comment by rohanKanojia** [comment]
@zhangzerui20 @PascalKu : Unfortunately, I don't think we support `--dry-run` like `kubectl` does, but I think we can achieve the above like this(not very pretty, though :disappointed: ):

```
        String dockerConfigStr = "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"dGVzdDpsb2w=\"}}}";

        Secret secret = new SecretBuilder()
                .withNewMetadata().withName("test").endMetadata()
                .withType("kubernetes.io/dockerconfigjson")
                .withData(
                        Collections.singletonMap(".dockerconfigjson",
                                Base64.getEncoder().encodeToString(String.format(dockerConfigStr, null, "test", "lol").getBytes())))
                .build();

        Files.write(Paths.get("/home/rohaan/docker-secret.yml"), SerializationUtils.dumpAsYaml(secret).getBytes());
```
