### ISSUE TITLE
CertUtils.getInputStreamFromDataOrFile wrong parameter order

### ISSUE THREAD

**Issue by kesyu** [fabric8io/kubernetes-client#1745]
In https://github.com/fabric8io/kubernetes-client/blob/8072213af9f04132eb27169472dd239f2b21ca3e/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L679 the function getInputStreamFromDataOrFile is called with parameters file and data, but the function expects it the other way around: https://github.com/fabric8io/kubernetes-client/blob/8072213af9f04132eb27169472dd239f2b21ca3e/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/CertUtils.java#L59

**Comment by rohanKanojia** [comment]
@kesyu : oh, Could you please raise a quick PR to fix this?

**Comment by kesyu** [comment]
Sure

**Comment by rohanKanojia** [comment]
@kesyu : much appreciated, Thanks.

**Comment by kesyu** [comment]
@rohanKanojia Can't raise the PR, I only have read permission to the repository.

**Comment by oscerd** [comment]
You need to fork the repository, create the branch on your fork and then open a PR against the original one.

**Comment by kesyu** [comment]
@oscerd Ah, I see, thanks.

**Comment by rohanKanojia** [comment]
closed via #1747
