### ISSUE TITLE
Got wired exception when creating job

### ISSUE THREAD

**Issue by liketic** [fabric8io/kubernetes-client#1748]
I got the following error when trying to create job:
```
Failure executing: POST at: https://master-url/apis/batch/v1/namespaces/data-ingestion/jobs. Message: jobs.batch "job-name" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=batch, kind=jobs, name=job-name, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=jobs.batch "
```

So there is a retry logic when calling the job api ?  Thank you!

**Comment by kunal-kushwaha** [comment]
@liketic: Looks like the resource that you're trying to create already exists.

**Comment by liketic** [comment]
@kunal-kushwaha Thank you for your reply. Actually, that's what I'm trying to say, the job is not exist absolutely, because I always create job with a random name. I thought maybe this SDK will auto retry if the create API response a failure, for example, caused by network issue.

**Comment by kunal-kushwaha** [comment]
@rohanKanojia: Can you please look into this and provide your feedback if you get time?

**Comment by rohanKanojia** [comment]
as far as I know we don't have any retry logic in our api. @liketic : Could you please share your job resource yaml so that we can try to reproduce this?
