### ISSUE TITLE
java.lang.ClassNotFoundException: io.fabric8.kubernetes.api.model.ExecEnvVar

### ISSUE THREAD

**Issue by hsamgle** [fabric8io/kubernetes-client#1755]
plz check about io.fabric8.kubernetes.client.Config.java 

i can't import io.fabric8.kubernetes.api.model.ExecEnvVar etc

i have checked kubernetes-model-4.1.0.jar but not found this class file

maven version is 
     
        <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>kubernetes-client</artifactId>
            <version>4.4.2</version>
        </dependency>

**Comment by manusa** [comment]
[`kubernetes-model-4.4.2.jar`](https://repo1.maven.org/maven2/io/fabric8/kubernetes-model/4.4.2/kubernetes-model-4.4.2.jar) does contain the requested class.

Please recheck your pom and update your dependencies.
