### ISSUE TITLE
Portforwarding is broken

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#1759]
It fails consistnently in openshift 3.x, with an error like:

    Caused by: java.util.concurrent.RejectedExecutionException: Task io.dekorate.deps.okhttp3.RealCall$AsyncCall@5e20ab3f rejected from java.util.concurrent.ThreadPoolExecutor@4846507f[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]

Noticed that when I tried to upgrade decorate to 4.5.1.

Used git bisect and found that the offending commit is: 6c20171e4b4ba21d8aa30fb711490dffe207c682

Need to fix the issue introduced in this commit and add test to prevent this from happening again.

**Comment by rohanKanojia** [comment]
@iocanel : Sorry for this. Are you working on fixing this? Shall I pick it up instead?

**Comment by iocanel** [comment]
@rohanKanojia FYI

**Comment by iocanel** [comment]
> @iocanel : Sorry for this. Are you working on fixing this? Shall I pick it up instead?

No need to apologize. It happens :-D
I am done for tonight! I could have a second look tommorow. Feel free to pick it up if you want.

**Comment by rohanKanojia** [comment]
I'm aware of this. @stanlyDoge pointed this out in #1709 . I would take a look into this in tomorrow evening.

**Comment by iocanel** [comment]
From the top of my mind and just by looking at the code it seems that the issue is that we internally open and close an instance of the client. Why is that a problem? Because when we close the client we also close the underlying http client and its thread pools. So, if we reuse those thread pools (e.g. watch, websockets etc) we are getting an error.

Now, on top of that we have a secondary issue, We do perform the `api groups check` per request, so for every single http request on openshift we check if api groups are enabled. IMHO, this should be done once per instance, or once per url across all instances (static).

I took a stub at it, will let you know where I get.
