### ISSUE TITLE
The bundle version of kubernetes-client v4.5.1 is missing ServiceLoader files

### ISSUE THREAD

**Issue by kzhang-dsg** [fabric8io/kubernetes-client#1760]
The bundle version of kubernetes-client v4.5.1 is missing ServiceLoader files:

Download the jar from maven repo: https://repo1.maven.org/maven2/io/fabric8/kubernetes-client/4.5.1/kubernetes-client-4.5.1-bundle.jar

Open the jar file -> META-INF/services, the following two files are missing from the folder:
io.fabric8.kubernetes.client.ExtensionAdapter
io.fabric8.kubernetes.client.ServiceToURLProvider

**Comment by rohanKanojia** [comment]
strange, I'm able to see these files in https://repo1.maven.org/maven2/io/fabric8/kubernetes-client/4.5.1/kubernetes-client-4.5.1.jar

**Comment by kzhang-dsg** [comment]
Right, the non-bundled version has those files. Only the bundled version in mvn is missing those files.

**Comment by kzhang-dsg** [comment]
Just checked, the latest v4.5.2 and v4.6.4 bundles also have the same problem.

**Comment by rohanKanojia** [comment]
@kzhang-dsg : Thanks for looking into this. Could you please fix this problem if you have time? I can take a look but not sure very soon :-(

**Comment by kzhang-dsg** [comment]
@rohanKanojia Could you please give me the commands you used to generate the bundle? I will use the same command and troubleshoot from there.

**Comment by manusa** [comment]
Relates to #2057

**Comment by manusa** [comment]
Try to fix all bundling issues and remove newly hard-coded file in #2101 following #2064 approach in scope of this issue.
