### ISSUE TITLE
[Feature Request] Ability to upload files to a pod.

### ISSUE THREAD

**Issue by orendain** [fabric8io/kubernetes-client#1765]
**Feature Requested:**
A method for **_uploading_** files to a pod.

**Context:**
There was some discussion in a different thread (#868) about how to go about achieving this.  @rohanKanojia mentioned that read/copy operations were added.  However, what is missing is the ability to _upload_ files to pods.

There have been a number of discussions around the need for this, and a few of us have implemented our own solution for doing this.  It'd be great to get something officially supported by this library, as some of the workarounds people have been employing are less than optimal.

**Related issues and similar feature requests:**
#868 
#476
#353 
#1008

**Comment by rohanKanojia** [comment]
@dev-gaur : Would this be something you would like to work on?

**Comment by manusa** [comment]
Implementation with project current status can be easily achieved:

_i.e. upload local file to pod_
```
public Boolean upload(Path path) {
  final int uploadBufferSize= 8092;
  try {
    final ExecWatch ew = redirectingInput(uploadBufferSize)
      .exec("sh", "-c", String.format("base64 -d - > %s", getContext().getFile()));
    try (
      final Base64OutputStream b64Os = new Base64OutputStream(ew.getInput(), true, 0,
        new byte[]{'\r', '\n'});
    ) {
      Files.copy(path, b64Os);
      b64Os.flush();
    }
    return true;
  } catch (IOException ex) {
    throw KubernetesClientException.launderThrowable(ex);
  }
}
```

The main drawback with this approach has to do with the following line:

https://github.com/fabric8io/kubernetes-client/blob/0502f77ade9b3d10ec2dd4ee4dbfb6fc475a7cb6/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/NonBlockingInputStreamPumper.java#L57

This will cause a performance bottleneck as the thread will sleep for at least 50ms (+ scheduler wait, etc.) each time the PipedInputStream buffer fills. This can be overcome by providing a larger buffer, but it probably isn't a good idea and still won't fix the problem when uploading very big files.

To overcome all of these problems, I'm performing a complete implementation of the command REST request using a specific WebSocketListener.
