### ISSUE TITLE
WatchConnectionManager does not respect user specified pingInterval

### ISSUE THREAD

**Issue by igorcalabria** [fabric8io/kubernetes-client#1767]
Hi everyone, is there a reason why https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java#L85 overrides user's specified `pingInterval` with a fixed value of 30 seconds? Is this a specific requirement of kubernetes? If that's not the case I could provide a PR that reverts this

**Comment by rohanKanojia** [comment]
@igorcalabria : oops, I did it in order to deal with `ping not received within x seconds`. Yeah, it would be great if you could raise a PR to override this default value. But if value is not specified, `pingInterval` should be kept to 30 seconds only.

**Comment by igorcalabria** [comment]
@rohanKanojia I have provided the PR
