### ISSUE TITLE
io.fabric8.kubernetes.client.KubernetesClient - Missing Javadoc 

### ISSUE THREAD

**Issue by rohtakdev** [fabric8io/kubernetes-client#1772]
Javadocs are necessary for developers to understand the interfaces and start consuming them. It will really great to have Javadoc at least on KubernetesClient.

**Comment by rohanKanojia** [comment]
@rohtakdev : Hi, I agree with you on this. It would be nice to provide at least 60% javadoc coverage across the project. Would you like to create a PR to add some docs, just to get started?

**Comment by rohanKanojia** [comment]
Not stale, I think this is quite important. let me take this up
