### ISSUE TITLE
WatchConnectionManager - Exec Failure - java.io.EOFException: null

### ISSUE THREAD

**Issue by brentpearson** [fabric8io/kubernetes-client#1773]
I've got a Java application that uses kubernetes-client to create a job, and then set a watch on it. I recently started seeing a new warning msg in the application log.

I'm using K8s 1.15.3 (which I don't think is officially supported by the client yet, but still wanted to see if anyone could help out with this issue), and kubernetes-client 4.5.2.

I have a K8s cluster with 3 master nodes and 1 worker/minion node (adding more, but was testing one first when I came across this issue).

The Java application has been working without this warning for the past ~1.5 years, but I recently updated K8s from a 1 master node 1.13 cluster to a 1 master node 1.15.3 cluster. That required updating the client from 3.2.0 to 4.4.2. I *wasn't* seeing this warning at that point (with the 1 master 1.15.3 K8s), but then I updated my cluster to have 3 masters. The warning started then, so I tried updating the client to 4.5.2, but it's is still occurring.

So onto the actual issue.
I create the client object with:
```
    final Config config = new ConfigBuilder().withMasterUrl("MASTER_1_ADDRESS").build();
    final KubernetesClient client = new DefaultKubernetesClient(config);
```
I successfully create the job, get the job name, then set the watch with:
```
    public Watch createWatch(
        final String jobName, 
        final Watcher<io.fabric8.kubernetes.api.model.batch.Job> k8sJobWatcher)
    {
        return client.batch().jobs().withName(job.id).watch(k8sJobWatcher);
    }
```

The job successfully runs to completion, and my watch even gets all the updates (I think... I should compare with old logs to make sure), and my application runs fine, as being notified of the job completion goes.

However, I get this warning (and related msgs) in the log, repeating every 4 seconds until the job completes:
```
[WARN ][WatchConnectionManager][OkHttp MASTER_1_ADDRESS...] - Exec Failure
java.io.EOFException: null
        at okio.RealBufferedSource.require(RealBufferedSource.java:61) ~[okio-1.15.0.jar:?]
        at okio.RealBufferedSource.readByte(RealBufferedSource.java:74) ~[okio-1.15.0.jar:?]
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117) ~[okhttp-3.12.0.jar:?]
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101) ~[okhttp-3.12.0.jar:?]
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274) [okhttp-3.12.0.jar:?]
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214) [okhttp-3.12.0.jar:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206) [okhttp-3.12.0.jar:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [okhttp-3.12.0.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[DEBUG][WatchConnectionManager][OkHttp MASTER_1_ADDRESS...] - Submitting reconnect task to the executor
[DEBUG][WatchConnectionManager][scheduleReconnect|Executor for Watch 574252868] - Scheduling reconnect task
[DEBUG][WatchConnectionManager][scheduleReconnect|Executor for Watch 574252868] - Current reconnect backoff is 1000 milliseconds (T0)
[DEBUG][WatchConnectionManager][reconnectAttempt|Executor for Watch 574252868] - Connecting websocket ... io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@223a6744
[DEBUG][WatchConnectionManager][OkHttp MASTER_1_ADDRESS...] - WebSocket successfully opened
```

Any idea why this started happening?

I'm going to reset the cluster and go back to a single master node to see if the issue is really related to going from a single master to three masters.

**Comment by lalithsuresh** [comment]
@brentpearson I was running into the same problem on version 4.6.0 even with just a single master. The problem stopped appearing after upgrading to 4.6.1. I could not figure out why it was happening, but one symptom I noticed is that the corresponding watches stop receiving events (I was using informers, but also tested it directly with watches -- I was subscribing to pod and node events).

**Comment by chhsiao1981** [comment]
I recently encountered this problem as well～

Turns out that there is timeout setting in my load-balancer for the multi-master cluster～
Removing the timeout setting solved the problem～

**Comment by puneetloya** [comment]
I am seeing this issue to with Kubernetes 1.15 and 1.16

**Comment by FuyaoLi2017** [comment]
I notice the same error when I deployed the operator and didn't add any CR to it for 5-7 days. The operator will run into such error and fail to reconcile anything. My fabric8 version is 5.5.0
