### ISSUE TITLE
KubernetesList.list().delete(resources) orphanDependents semantics change between 4.1.3 and 4.5.2

### ISSUE THREAD

**Issue by k-wall** [fabric8io/kubernetes-client#1775]
We upgraded our application from 4.1.3 to 4.5.2 and notice a behavioural change in the API.

In 4.1.3 `KubernetesList.list().delete(resources)` sent the following for each resource:

`{"apiVersion":"v1","kind":"DeleteOptions","orphanDependents":false} `

whereas in 4.5.2 the same code results in:

`{"apiVersion":"v1","kind":"DeleteOptions","gracePeriodSeconds":0,"orphanDependents":true}`

so the semantics of the delete are now different.

We restored the old behaviour by changing application as follows:

`resources.getItems().forEach(resource -> client.resource(resource).cascading(true).delete());`

I see the note in the CHANGELOG about the propagation policy feature, but nothing alerts a user to the API change.  Was this change intentional?

**Comment by rohanKanojia** [comment]
so, you're saying list deletion is not `cascading=true` by default? I remember I changed deletion to be `cascading=true` by default in order to align api behavior with `kubectl`'s.

**Comment by k-wall** [comment]
@rohanKanojia exactly, I am saying  KubernetesList.list().delete(resources) no longer sends a cascading deleted.  At 4.1.3 it did send a cascading delete.    We changed our code to adapt to the new behaviour so it is no longer an issue for us, but I wanted to flag up in case it helps others.

**Comment by rohanKanojia** [comment]
crap, this is not desired behavior.

**Comment by novakov-alexey** [comment]
I think I hit this issue in `4.6.0` version as well :-( 
Also, I have weird behaviour when trying to remove resources one by one: first resources is removed from Kubernetes all others are still alive.

**Comment by k-wall** [comment]
@novakov-alexey yes, I'm seeing other problems too with this upgrade in our project which I would characterise as weird problems removing resources.  Unfortunately, I don't have the capacity at the moment to dig deeper and find root cause.

**Comment by rohanKanojia** [comment]
This seems to be introduced from #1742
