### ISSUE TITLE
Tekton Extension "nodeSelector" 

### ISSUE THREAD

**Issue by stephen-harlow** [fabric8io/kubernetes-client#1776]
I'm currently trying to use the Tekton extension code examples [(something like this)](https://github.com/fabric8io/kubernetes-client/blob/master/extensions/tekton/examples/src/main/java/io/fabric8/tekton/api/examples/PipelineResourceCreate.java), but I'm running into some issues. When I try to recreate the pipeline example from [here](https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md#task-inputs-and-outputs), all of the code works as expected, **except** for the last TaskRun. I can create the PipelineResources and Tasks. But when I try to execute that section that creates the TaskRuns, I get this as a response:

 ```Failure executing: POST at: https://kubernetes/apis/tekton.dev/v1alpha1/namespaces/default/taskruns. Message: Internal error occurred: admission webhook "webhook.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "nodeSelector". Received status: Status(apiVersion=v1, code=500, details=StatusDetails(causes=[StatusCause(field=null, message=admission webhook "webhook.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "nodeSelector", reason=null, additionalProperties={})], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Internal error occurred: admission webhook "webhook.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "nodeSelector", metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=InternalError, status=Failure, additionalProperties={}).```

I know that the other sections are being created as designed, since when I manually do a ```kubectl apply -f <YAML.yaml>``` (where YAML.yaml is a yaml file with just the TaskRun), the pod appears in the Kubernetes Service I'm using. 

**Dependency Section of pom.xml Involved**
```xml
<dependency>
	<groupId>io.fabric8</groupId>
	<artifactId>tekton-client</artifactId>
	<version>4.4.0</version>
</dependency>
<dependency>
	<groupId>io.fabric8</groupId>
	<artifactId>kubernetes-client</artifactId>
	<version>4.4.0</version>
</dependency>
<dependency>
	<groupId>io.fabric8</groupId>
	<artifactId>kubernetes-model</artifactId>
	<version>4.4.0</version>
</dependency>
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-kubernetes-config</artifactId>
	<exclusions>
		<exclusion>
			<groupId>io.fabric8</groupId>
			<artifactId>kubernetes-client</artifactId>
		</exclusion>
		<exclusion>
			<groupId>io.fabric8</groupId>
			<artifactId>kubernetes-model</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```

```java
try ( TektonClient client = ClientFactory.newClient(new String[]{"--api-server","https://kubernetes", "--namespace", "default"})){
	TaskRun buildDockerImage = new TaskRunBuilder()
			.withNewMetadata()
			.withName("build-docker-image-from-git-source-task-run-" + version)
			.endMetadata()
			.withNewSpec()
			.withTaskRef(
					new TaskRefBuilder().withName("build-docker-image-from-git-source-" + version).build())
			.withNewInputs()
			.addNewResource().withName("docker-source").withResourceRef(new PipelineResourceRefBuilder().withName("skaffold-git-" + version).build()).endResource()
			.addNewParam().withName("pathToDockerFile").withValue("Dockerfile").endParam()
			.addNewParam().withName("pathToConext").withValue("/workspace/docker-source/examples/microservices/leeroy-web").endParam()
			.endInputs()
			.withNewOutputs().addNewResource().withName("builtImage").withResourceRef(new PipelineResourceRefBuilder().withName("skaffold-image-leeroy-web-" + version).build()).endResource()
			.endOutputs()
			.endSpec()
			.build();
	return client.taskRuns().create(buildDockerImage).getMetadata().getName() + "\n";

}
```

**Comment by stephen-harlow** [comment]
I have modified the pom to use the most recent version of the kubernetes-model/client and the tekton-client and I still receive the same error. 
```xml
<dependency>
	<groupId>io.fabric8</groupId>
	<artifactId>tekton-client</artifactId>
	<version>4.5.2</version>
</dependency>
<dependency>
	<groupId>io.fabric8</groupId>
	<artifactId>kubernetes-client</artifactId>
	<version>4.5.2</version>
</dependency>
<dependency>
	<groupId>io.fabric8</groupId>
	<artifactId>kubernetes-model</artifactId>
	<version>4.5.2</version>
</dependency>
```

**Comment by stephen-harlow** [comment]
After further research, I discovered that the most recent version of Tekton (0.7.0) "removed podSpec in favor of podTemplate" [(See Here)](https://github.com/tektoncd/pipeline/releases/tag/v0.7.0). Is there a timeline on when the tekton-client will be compatible with 0.7.0?

**Comment by iocanel** [comment]
@stephen-harlow: Hi Stephen, it seems that both tekton and knative are moving really fast :-D and we do have a hard time catching up! Having said that any kind of contribution is more than welcome! 

Note, that most stuff are generated so it should require too much effort.

Now, I intended to bump knative soon so I may as well try to bump tekton too, if I have the time.
