### ISSUE TITLE
informer deadlock

### ISSUE THREAD

**Issue by dongbintop** [fabric8io/kubernetes-client#1782]
version:V4.6.0

SharedProcessor.java
shouldResync()
lock.readLock().unLock() -> lock.writeLock().unLock()

![image](https://user-images.githubusercontent.com/20614772/65658323-cac30380-e059-11e9-9fd7-250360dfaba4.png)

**Comment by dongbintop** [comment]
@rohanKanojia

**Comment by rohanKanojia** [comment]
@dongbintop : Thanks a lot for noticing :+1: Let me fix this.
