### ISSUE TITLE
Create or replace on operation seems broken

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#1789]
In some cases it seems that:

     client.resourceList(generated).createOrReplace()

Is not working as expected.

See:  https://github.com/dekorateio/dekorate/issues/345

**Comment by rohanKanojia** [comment]
@iocanel : Could you please share contents of the generated which might help in debugging?

**Comment by rohanKanojia** [comment]
If you were getting 422, then this might be related https://github.com/kubernetes/kubernetes/issues/70674 .

**Comment by iocanel** [comment]
@rohanKanojia: Can we make sure that `deleteExisting()` works as expected?

  I'll update dekorate to always use `deleteExisting()` if this it works fine.

**Comment by rohanKanojia** [comment]
I would test this and report on Monday
