### ISSUE TITLE
Provide the ability to select knative version as we select api groups.

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#1790]
Once #1788 goes in, we will have 3 apiVersion available for knative:

- v1alpha1
- v1beta1
- v1

This means 3x Hanlders and 3x Operations.

The default knative client will be using v1 but maybe it makes sense to be able to fallback to a v1beta1 client or v1alpha one. The process could be similar to what we currently have for apiGroups via `adapt`.

**Comment by shawkins** [comment]
Marking as resolved as we no longer need explicit handlers / operations most of the time.  Also any version selection is up to the user.
