### ISSUE TITLE
! is not required in the example

### ISSUE THREAD

**Issue by DarshanMurthy** [fabric8io/kubernetes-client#1795]
It seems like "!" is recognized as a logical operator.

https://github.com/fabric8io/kubernetes-client/blob/0f83674fbd7b7f748e4afb995f47eecc4f1a342e/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/WaitUntilReadyExample.java#L41

**Comment by rohanKanojia** [comment]
@DarshanMurthy : Could you please create a PR to fix it?
