### ISSUE TITLE
Issue on EC client cert (BouncyCastle)

### ISSUE THREAD

**Issue by torrescd** [fabric8io/kubernetes-client#1796]
KubernetesClientException("JcaPEMKeyConverter is provided by BouncyCastle, an optional dependency. To use support for EC Keys you must explicitly add this dependency to classpath.");

I have no clue to how do that.

Shouldn't be managed by bouncycastle-api like in kubernetes-plugin?

Regards!

**Comment by rohanKanojia** [comment]
It's a heavy dependency that's why we didn't add it to main jar. You can add it in your project like done here: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-tests/pom.xml#L109

**Comment by torrescd** [comment]
Great, thanks!

It would be nice to have some mechanism to achieve that without rebuilding the plugin anyway.

Regards.

**Comment by torrescd** [comment]
I have done a pull request regarding this topic.

https://github.com/fabric8io/kubernetes-client/pull/1798
