### ISSUE TITLE
Missing "/" in request url while using customresource client

### ISSUE THREAD

**Issue by LegendJ** [fabric8io/kubernetes-client#1803]
## Problem
- while using `client.customResource(csvContext).create()` for creating customresource, I'm running into this Exception below, my client is initialized from a kubeconfig file whose apiserver endpoint is https://x.x.x.x:7443. 
```
java.lang.IllegalArgumentException: Invalid URL port: "7443apis"
	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1397)
	at okhttp3.HttpUrl.get(HttpUrl.java:916)
	at okhttp3.Request$Builder.url(Request.java:165)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.getRequest(RawCustomResourceOperationsImpl.java:264)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.makeCall(RawCustomResourceOperationsImpl.java:223)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.validateAndSubmitRequest(RawCustomResourceOperationsImpl.java:239)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.create(RawCustomResourceOperationsImpl.java:70)

```
## Cause
- After debuging the source code ,I find code lines below.
https://github.com/fabric8io/kubernetes-client/blob/90dfe6443d0caf1dbd015a32e6a635f0a96ced48/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java#L410

## Personal Opinion
I think we should append"/" before append("apis/") which should be looked like this
```
urlBuilder.append("/")
  .append("apis/")
  .append() // others
```
- kubeconfig file do not contain "/" in server's endpoint
- In most cases, `config.getMasterUrl()` shall return the host without "/", right?

**Comment by rohanKanojia** [comment]
@LegendJ : Strange, my minikube also has apiserver endpoint like yours but I don't face this error:

```
 18 - cluster:
 19     certificate-authority: /home/rohaan/.minikube/ca.crt
 20     server: https://192.168.99.100:8443
 21   name: minikube
```

But I think appending a `/` explicitly does no harm

**Comment by rohanKanojia** [comment]
@LegendJ : Hi, I've created a PR for fixing this. Could you please build a snapshot and test it whether it's working for you or not?

```
git clone <repo-url>
git fetch origin pull/1804/head:pullReq1804 && git checkout pullReq1804
mvn clean install -DskipTests
# Use 4.6-SNAPSHOT instead of 4.6.0
```

**Comment by rohanKanojia** [comment]
@LegendJ : polite ping, Did you get time to try it out?

**Comment by LegendJ** [comment]
@rohanKanojia sorry for the delay, I've test it just now and it worked fine. you can close the issue now

**Comment by rohanKanojia** [comment]
@LegendJ : You mean you tested my PR or you were unable to reproduce the issue itself?

**Comment by LegendJ** [comment]
@rohanKanojia using the new, PR verision

**Comment by rohanKanojia** [comment]
oh, okay. I would merge it and notify you on next release
