### ISSUE TITLE
Unable to create Template on OCP4

### ISSUE THREAD

**Issue by mchoma** [fabric8io/kubernetes-client#1805]
I am getting

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://api.domain:6443/oapi/v1/namespaces/namespace/templates. Received status: Status(apiVersion=v1, code=404, details=null, kind=Status, message=null, metadata=null, reason=null, status=null, additionalProperties={}).
```
With 4.1.1 it was OK.

Template is version `v1`
```yaml
{
    "kind": "Template",
    "apiVersion": "v1",
    "metadata": {
        "annotations": {
```
Creating with 
```
	public Template createTemplate(Template template) {
		return templates().create(template);
	}
```

I understand this is somehow related to [1] and [2]. As this  worked with `4.1.1` is this regression?

But I am not sure what is now correct solution for this. Correct Update templates objects to `template.openshift.io/v1`? Templates are not ours, so there may be some resistance to do so argumenting change is initiated by client change. 

What could be workaround for this? Can we set template.setApiVersion("template.openshift.io/v1"); in our code to make it work on OCP4?

[1] https://github.com/fabric8io/kubernetes-client/issues/1684
[2] https://github.com/fabric8io/kubernetes-client/issues/1631

**Comment by mchoma** [comment]
@gastaldi ^^^ could you have a look please?

**Comment by gastaldi** [comment]
Yes, this is a fix that was introduced in 4.4.2 AFAIK. Because the `oapi` endpoint no longer exists in OpenShift 4.x, it's necessary to change the `apiVersion` in the template to `template.openshift.io/v1`) (explicitly call `template.setApiVersion("template.openshift.io/v1")` may also work)

There are other resources that may need this change, see https://issues.jboss.org/browse/RHOAR-124 for more details

**Comment by mchoma** [comment]
@gastaldi how do you explain we run Templates in version `v1` with client version `4.1.1` with no problem on OCP4?

**Comment by gastaldi** [comment]
Initial support for OpenShift 4 was introduced in 4.1.0, but there are cases where it would still hit the `oapi` endpoint. 
  
Can you confirm 4.1.1 hits `/apis/template.openshift.io/v1/namespaces/{namespace}`?

**Comment by gastaldi** [comment]
Also worth mentioning that changing the template does not impact OpenShift 3.x

**Comment by gastaldi** [comment]
Ok, then this seems to be a regression

**Comment by mchoma** [comment]
@rohanKanojia  We are still using workaround `template.setApiVersion("template.openshift.io/v1")`. Given this issue is fixed, should it work now without that workaround?
