### ISSUE TITLE
Deleting DeploymentConfig takes ~ 1 minute

### ISSUE THREAD

**Issue by mchoma** [fabric8io/kubernetes-client#1808]
profiler data for `4.6.0` client
![Screenshot from 2019-10-14 09-19-53](https://user-images.githubusercontent.com/10402702/66735367-6e881e00-ee66-11e9-9f0d-331528925eb6.png)

For comparision profiler data for `4.1.1` client
![Screenshot from 2019-10-14 08-31-15](https://user-images.githubusercontent.com/10402702/66735408-8f507380-ee66-11e9-82ee-5321bf0f0120.png)

**Comment by rohanKanojia** [comment]
maybe because it's now deletion is  `cascading=true` now? Does `cascading(false)` help in reducing deletion time.

**Comment by mchoma** [comment]
We use `.cascading(false)` by default `resource(hasMetadata).withGracePeriod(0).cascading(false).delete();`

**Comment by dsimansk** [comment]
Well, we started to mess with parameters after client upgrade. However, I'm pretty sure order wasn't changed though.

**Comment by manusa** [comment]
I also noticed this problem and located the source being this statement timing out (hence the 1 minute delay):
https://github.com/fabric8io/kubernetes-client/blob/fc82d6006d636306b56313447ba5ac5818d00105/openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/DeploymentConfigOperationsImpl.java#L140-L143

The problem should be fixed after #1887
