### ISSUE TITLE
How to set timeoutSeconds parameter for the watch method

### ISSUE THREAD

**Issue by wxl86697716** [fabric8io/kubernetes-client#1821]
![image](https://user-images.githubusercontent.com/13344339/67138534-5570da00-f277-11e9-8589-dcaab476a5b1.png)
![image](https://user-images.githubusercontent.com/13344339/67138576-3fafe480-f278-11e9-8a53-ce10acbe502d.png)
![image](https://user-images.githubusercontent.com/13344339/67138674-89e59580-f279-11e9-81a9-bce7871b0f5d.png)

**Comment by rohanKanojia** [comment]
I think you can do it via setting `KUBERNETES_WEBSOCKET_TIMEOUT_SYSTEM_PROPERTY` in your project

**Comment by wxl86697716** [comment]
@rohanKanojia   Thank you for your reply.
I don't think `KUBERNETES_WEBSOCKET_TIMEOUT_SYSTEM_PROPERTY` works the same way as `timeoutSeconds`.
I tried to configure the WebsocketTimeout parameter, but did not stop watch after the specified time.
![image](https://user-images.githubusercontent.com/13344339/67140190-96261e80-f28a-11e9-8857-5eae5fe00379.png)

**Comment by rohanKanojia** [comment]
oh, I see. You can also try setting it in config object during initializing client(not sure whether you've already tried it or not):
```
    // Add websocket timeout in milliseconds
    Config config = builder.withWebsocketTimeout(10000).build();
    try (final KubernetesClient client = new DefaultKubernetesClient(config)) {
        // Do your stuff
    }
```

**Comment by rohanKanojia** [comment]
oh, I see that you already tried it(sorry, just noticed the screenshot). It should work ideally. Could you please share more details? A test case (in code) and openshift version which you're testing against.

**Comment by wxl86697716** [comment]
I can confirm that the account used has access rights.
I want to use the Java SDK to do the same thing as curl, which automatically stops when the watch API is called after a period of time.

I tried the following version：
Openshift version: `OKD_3.11` and `OCP_3.11`
fabric8.openshift-client: `4.6.1` and `4.1.1 `


#get token
`curl -u admin:xxxxxxxxx -kv -H "X-CSRF-Token: 1" "https://my-osc.yzh.com:8443/oauth/authorize?client_id=openshift-challenging-client&response_type=token"`

#use token call watch API (The connection automatically disconnects after 30 seconds, this is what I want.)
`curl -H "Authorization: Bearer 6Nujp0kpfGrwGJrrvN9ZTLgsWqp8yZZJKPpRezIl8aA" -H 'Accept: application/json' -X GET -k "https://my-osc.yzh.com:8443/api/v1/watch/nodes?resourceVersion=0&timeoutSeconds=30"`

#java （Target: print "close" in 30 seconds and stop）
```
OpenShiftConfig config = new OpenShiftConfigBuilder()
        .withOpenShiftUrl(url).withMasterUrl(url)
        .withUsername(userName).withPassword(password)
        .withTrustCerts(true).withDisableHostnameVerification(true)
        .withWebsocketTimeout(30000)
        .build();
OpenShiftClient client = new DefaultOpenShiftClient(config);
client.nodes().withResourceVersion("0").watch(new Watcher<Node>() {
    @Override
    public void eventReceived(Action action, Node node) {
        System.out.println(action.name() + "\t"
                + node.getMetadata().getName() + "\t"
                + node.getMetadata().getResourceVersion());
    }
    @Override
    public void onClose(KubernetesClientException cause) {
        System.out.println("close");
    }
});
```
