### ISSUE TITLE
Is there any API corresponding to top command?

### ISSUE THREAD

**Issue by udit0612** [fabric8io/kubernetes-client#1822]
I wants to  run a top command 

` kubectl top nodes`

My output should be like this
```
NAME           CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
k8s-master     74m          3%     2666Mi          65%
worker-node1   924m         92%    1266Mi          27%
```

How can i achieve these i didn't see any option of top command in the api

**Comment by rohanKanojia** [comment]
I think we have it now in latest release(i.e 4.7.0). You can see example here: https://github.com/fabric8io/kubernetes-client/blob/403a6c56d92d2e178e981cf80b20fbce37438d18/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/TopExample.java#L37-L73
