### ISSUE TITLE
client.resourceList() bug

### ISSUE THREAD

**Issue by xskerik** [fabric8io/kubernetes-client#1823]
I used **client.load()** for loading external configs.
These configs are in yaml format and contains several items seperated with **---**
It worked pretty good. When configs contains 3 parts, then 3 parts were returned.

Since I need to hold my configs in memory (due to generating unique name on the fly) I switched to **client.resourceList()**.
The error has occured,  now, the method returns only 1 item for the same config.

I use client in version 4.6.1.

**Comment by xskerik** [comment]
Example of my k8s config
`
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-SANDHASH
  labels:
    app: app-SANDHASH
  namespace: dev
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-SANDHASH
    spec:
      initContainers:
        - name: init-wait-mongo
          image: alpine
         ....
---
kind: Service
apiVersion: v1
metadata:
  name: app-SANDHASH
  namespace: dev
spec:
  selector:
    app: app-SANDHASH
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 31080
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: app-configmap-SANDHASH
  namespace: dev
data:
  ....
`

**Comment by kunal-kushwaha** [comment]
@xskerik : Can you please share your Java file? I ran both client.load() and client.resourceList() for loading multiple documents and got same number of items. How can I reproduce this error?

**Comment by manusa** [comment]
The logic in these methods was changed in scope of https://github.com/fabric8io/kubernetes-client/issues/1874 and your bug could also be related to that.
Could you please check if your issue is fixed in [v4.8.0](https://github.com/fabric8io/kubernetes-client/releases/tag/v4.8.0)?
