### ISSUE TITLE
How to get results similar to `kubectl get pod`

### ISSUE THREAD

**Issue by zhangzerui20** [fabric8io/kubernetes-client#1826]
Can sdk get results similar to kubectl get pod?

like command : 
`kubectl get pod`

NAME                                                READY     STATUS    RESTARTS   AGE
xxx-xxx-provider-689df7b7c8-fn9zr   1/2         Error           1               25s
test-xxx-5c48b54979-857db              2/2         Running     0              14m

**Comment by zhangzerui20** [comment]
I want to get the status of pod.

**Comment by rohanKanojia** [comment]
Does `client.pods().inNamespace("default").withName("my-pod").get().getStatus()` doesn't give the information you require? I'm not you would get information in pretty much the same format as kubectl provides. Could you please check?
