### ISSUE TITLE
can not rolling updateImage fro deployments

### ISSUE THREAD

**Issue by Laggar** [fabric8io/kubernetes-client#1829]
when I use below code to roll update the deployments ,then throw exception . (can not modify the selector)
"
 client.apps().deployments().inNamespace(namespace)
                    .withName(deployName)
                    .rolling()
                    .updateImage(imageName);
"
exception is:

Message: Deployment.apps "kmsp-deployment-nginx" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"deployment":"d91ff25d7685452a3e0ce7f082c54cfa", "k8sSvcName":"nginx"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.selector, message=Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"deployment":"d91ff25d7685452a3e0ce7f082c54cfa", "k8sSvcName":"nginx"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable, reason=FieldValueInvalid, additionalProperties={})], group=apps, kind=Deployment, name=kmsp-deployment-nginx, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Deployment.apps "kmsp-deployment-nginx" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"deployment":"d91ff25d7685452a3e0ce7f082c54cfa", "k8sSvcName":"nginx"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).

**Comment by rohanKanojia** [comment]
which version of k8s-client are you using?
