### ISSUE TITLE
what‘s the Kubernetes 1.13.X 's Compatibility Matri?it didn't write it in readme.txt

### ISSUE THREAD

**Issue by zhangxingdeppon** [fabric8io/kubernetes-client#1837]
hi.buddies,I did read the document readme.txt,but I don't find the Compatibility Matri about  Kubernetes 1.13.X.just read this information.but not 1.13.x :
![image](https://user-images.githubusercontent.com/16789841/67748632-51f30500-fa66-11e9-9ccc-f743a24758cb.png)

**Comment by rohanKanojia** [comment]
We usually update compatibility matrix during kubernetes-model upgrade. I would say current version is fully compatible with Kubernetes 1.13.x versions.

**Comment by zhangxingdeppon** [comment]
@rohanKanojia ok,I got it ,thanks

**Comment by Marten2016** [comment]
hello. buddies, I have read the document readme.txt too, but I also don't find the Compatibility Matri about Kubernetes 1.5.X, is there any suggestion?
