### ISSUE TITLE
Duplicate resources on classpath

### ISSUE THREAD

**Issue by zregvart** [fabric8io/kubernetes-client#1847]
The `kubernetes-client-*.jar` and `openshift-client-*.jar` both ship with `resource-*.vm` within them. I don't know if these files are loaded at runtime, they seem to be a part of code generation, so perhaps not.

If they're loaded at runtime there is no guarantee on what file will be read, it might depend on the order of jars on the classpath or on some heuristic of the class loader being used. In that case it might be better to name them differently for each jar to guarantee that the correct version is loaded.

If they're not needed at runtime it would be best that they're not shipped in jars.

**Comment by zregvart** [comment]
Do you see this as a problem? Do you need any help with this?

**Comment by rohanKanojia** [comment]
@zregvart :Hi Zoran, thanks for your bug report. We will fix this bug before next release

**Comment by manusa** [comment]
These files are actually Velocity compliant templates used by https://github.com/sundrio/sundrio to generate classes at compile/build time.

There should not be used during runtime and therefore, you're right, should not be part of the jar package.

I'm submitting a PR to exclude them from the jars.
