### ISSUE TITLE
Trust based on cacert file not on individual cert

### ISSUE THREAD

**Issue by sbueringer** [fabric8io/kubernetes-client#1855]
Hi,

we have the use case that we have to rollover the CA certificates of our Kubernetes clusters. Therefore we add multiple CAs to the root-ca-file (Kube Controller Manager:  `--root-ca-file=/etc/kubernetes/pki/ca.crt`). This file is then mounted into every Pod under `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`. k8s.io/client-go then establishes a trust to every certificate in the ca file. Apparently fabric8io/kubernetes-client only trusts the first certificate. 

We could fix the trust on the current ca by exchanging the order of the certificates in the ca file. What we actually need is a trust on both CAs at the same time.

As far as I know this should be implemented in CertUtils.java | createTrustStore > https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/CertUtils.java#L101

Looks like the `generateCertificate` method only parses the first certificate in the `pemInputStream`

**Comment by manusa** [comment]
Related to: #2163
