### ISSUE TITLE
Support "test" operation in JSON Patch for PATCH calls

### ISSUE THREAD

**Issue by nhoughto** [fabric8io/kubernetes-client#1858]
As per `io.fabric8.zjsonpatch.JsonPatch` it appears you only support `remove/replace/add/move` operations as part of JSON Patch and not `test` or `copy`. In particular the `test` operation is important as it allows a caller to do atomic patch operations (compare and set), where an API call will fail if a a value (like resourceVersion) is different to what is expected, this is an important primitive for api consumers.

I'm currently working around it via extending `PodOperationsImpl` but this is fragile and quite specific to my usecase, a more general solution would be great.

```
public static PodOperationsImpl wrapPatch(PodOperationsImpl operation) {
        return new PodOperationsImpl(operation.getContext()) {

            @Override
            protected <T> T handlePatch(T current, T updated, Class<T> type) throws ExecutionException, InterruptedException, KubernetesClientException, IOException {
                ArrayNode diff = (ArrayNode) JsonDiff.asJson(patchMapper().valueToTree(current), patchMapper().valueToTree(updated));

                ObjectNode testOp = JSON_MAPPER.createObjectNode();
                testOp.put("op", "test");
                testOp.put("path", "/metadata/somekey");
                testOp.put("value",(JsonNode)null);
                diff.insert(0, testOp);

                //normal op
                RequestBody body = RequestBody.create(JSON_PATCH, JSON_MAPPER.writeValueAsString(diff));
                Request.Builder requestBuilder = new Request.Builder().patch(body).url(getResourceUrl(checkNamespace(updated), checkName(updated)));
                return handleResponse(requestBuilder, type, Collections.<String, String>emptyMap());
            }

        };
    }
```

and then

```
wrapPatch(client.pods().withName(pod.getMetadata().getName())).patch(pod);
```

http://jsonpatch.com/

**Comment by brimworks** [comment]
This seems pretty useful, I'm not sure why this got closed. How are you supposed to implement atomic operations in Kubernetes?

**Comment by nhoughto** [comment]
yep atomic operations is why i needed it, my hack is a bit fragile but supporting it properly shouldn't be that hard i'd think

**Comment by rohanKanojia** [comment]
@brimworks: Hello, as per the latest improvements in Patch API, you can also provide your own raw Patch string like this:

```java
Depoyment deployment = getDeployment();

PatchContext patchContext = new PatchContext.Builder()
        .withPatchType(PatchType.JSON)
        .build();

kubernetesClient.apps().deployments()
        .inNamespace(deployment.getMetadata().getNamespace())
        .withName(deployment.getMetadata().getName())
        .patch(patchContext, "[{\"op\": \"test\", \"path\":\"/metadata/labels\", \"value\":null}]");
```
Do you think this is something which can help your use case?

**Comment by nhoughto** [comment]
seems like it would solve for my usecase as described in the issue
