### ISSUE TITLE
delete deployment success but accidentaly the related pod failed to delete, the related pod became orphan pod 

### ISSUE THREAD

**Issue by zhangxingdeppon** [fabric8io/kubernetes-client#1859]
hi, buddies, when we use the fabric8io/kubernetes-client client version 4.6.1, I met a problem, can you give me some idea?does the code have problem?  thanks.

The delete deployment code:

<pre><code>
kubernetesClient.apps().deployments().inNamespace("aipaas-notebook").withName("qhdwy7nphrlyvthd-notebook").withPropagationPolicy("Background").delete();
</code></pre>

The kubernetes version:

<pre><code>
[root@ecs-5274-0318501 audit-log]# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

</code></pre>

The problem describtion:

delete deployment success but accidentaly the related pod failed to delete, then the related pod  became orphan pod. 
for example  `c941didor23xe64s-notebook-67fdfd8d5d-hfwpw` , it became a orphan pod, you can see the below details:

<pre><code>
[root@ecs-5274-0318501 audit-log]# kubectl get pod -n aipaas-notebook 
NAME                                         READY   STATUS    RESTARTS   AGE
c941didor23xe64s-notebook-67fdfd8d5d-hfwpw   1/1     Running   0          29h
hdxm0mv32dt3na1f-notebook-8666dbb64b-5s2kh   1/1     Running   0          3d9h
kqjmtuww7xegzpq2-notebook-6f79c7c944-jfprn   1/1     Running   0          25m
rxq23nh19ezx6zb2-notebook-dd788f8b5-f4qxn    1/1     Running   0          7d
ynzjbg3i0045jeyz-notebook-646fd6bc77-5nrw7   1/1     Running   0          6d23h
</code></pre>

<pre><code>
[root@ecs-5274-0318501 audit-log]# kubectl get deploy -n aipaas-notebook 
NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
rxq23nh19ezx6zb2-notebook   1/1     1            1           7d
ynzjbg3i0045jeyz-notebook   1/1     1            1           6d23h

</code></pre>

<pre><code>
[root@ecs-5274-0318501 audit-log]# kubectl get rs -n aipaas-notebook 
NAME                                   DESIRED   CURRENT   READY   AGE
rxq23nh19ezx6zb2-notebook-dd788f8b5    1         1         1       7d
ynzjbg3i0045jeyz-notebook-646fd6bc77   1         1         1       6d23h
</code></pre>

according to  the kubernetes audit log, you will find the delete step, delete the replicaset and then delete the deployment. I feel confused, why not delete the deployment and then delete replicaset; 
in addition, when delete replicaset, the replicaset parameter `PropagationPolicy("Background")` wasn't set, just  the deployment parameter set the `PropagationPolicy("Background")`.
![image](https://user-images.githubusercontent.com/16789841/68368998-3083ce80-0174-11ea-9da2-8d82c951e3cc.png)
the kubernetes audit log:
<pre><code>
112160 {"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"RequestResponse","auditID":"baf52e7f-1c2b-4e02-83da-ac14e7b00ced","stage":"ResponseComplete","requestURI":"/apis/apps/v1/namespaces/aipaas-notebook/replicasets/c941didor23xe64s-notebook-67fdfd8d5d","verb":"delete","user":{"username":"kube-apiserver-kubelet-client","groups":["system:masters","system:authenticated"]},"sourceIPs":["172.16.1.123"],"userAgent":"okhttp/3.12.6","objectRef":{"resource":"replicasets",       "namespace":"aipaas-notebook","name":"c941didor23xe64s-notebook-67fdfd8d5d","apiGroup":"apps","apiVersion":"v1"},"responseStatus":{"metadata":{},"code":200},"requestObject":{"kind":"DeleteOptions","apiVersion":"apps/v1","orphanDepende       nts":true},"responseObject":{"kind":"ReplicaSet","apiVersion":"apps/v1","metadata":{"name":"c941didor23xe64s-notebook-67fdfd8d5d","namespace":"aipaas-notebook","selfLink":"/apis/apps/v1/namespaces/aipaas-notebook/replicasets/c941didor       23xe64s-notebook-67fdfd8d5d","uid":"e642b93d-0036-11ea-a14a-fa163ebce782","resourceVersion":"33839865","generation":3,"creationTimestamp":"2019-11-06T01:43:57Z","deletionTimestamp":"2019-11-06T01:44:07Z","deletionGracePeriodSeconds":0       ,"labels":{"app":"c941didor23xe64s-notebook","pod-template-hash":"67fdfd8d5d"},"annotations":{"deployment.kubernetes.io/desired-replicas":"0","deployment.kubernetes.io/max-replicas":"1","deployment.kubernetes.io/revision":"1"},"ownerR       eferences":[{"apiVersion":"apps/v1","kind":"Deployment","name":"c941didor23xe64s-notebook","uid":"e551794a-0036-11ea-ac9e-fa163efea19e","controller":true,"blockOwnerDeletion":true}],"finalizers":["orphan"]},"spec":{"replicas":0,"selec       tor":{"matchLabels":{"app":"c941didor23xe64s-notebook","pod-template-hash":"67fdfd8d5d"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"c941didor23xe64s-notebook","pod-template-hash":"67fdfd8d5d"}},"spec":{"volumes       ":[{"name":"c941didor23xe64s-notebook","persistentVolumeClaim":{"claimName":"c941didor23xe64s-pvc"}}],"containers":[{"name":"c941didor23xe64s-notebook","image":"172.16.1.222:10004/notebook/jupyter/r-notebook_limit_token:v1.0.1","ports       ":[{"name":"jupyter","containerPort":8888,"protocol":"TCP"}],"env":[{"name":"NVIDIA_VISIBLE_DEVICES","value":"none"}],"resources":{"limits":{"cpu":"1","memory":"1Gi"},"requests":{"cpu":"250m","memory":"256Mi"}},"volumeMounts":[{"name"       :"c941didor23xe64s-notebook","mountPath":"/src/notebooks/"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"d       nsPolicy":"ClusterFirst","nodeSelector":{"node":"worker"},"securityContext":{"runAsUser":999,"fsGroup":999},"schedulerName":"default-scheduler"}}},"status":{"replicas":1,"fullyLabeledReplicas":1,"readyReplicas":1,"availableReplicas":1       ,"observedGeneration":1}},"requestReceivedTimestamp":"2019-11-06T01:44:07.808218Z","stageTimestamp":"2019-11-06T01:44:07.811289Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":""}}
112161 {"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"RequestResponse","auditID":"3cd4f92d-6e31-440d-96d2-cef3cc2e2785","stage":"ResponseComplete","requestURI":"/apis/apps/v1/namespaces/aipaas-notebook/deployments/c941didor23xe64s-notebook","verb":"delete","user":{"username":"kube-apiserver-kubelet-client","groups":["system:masters","system:authenticated"]},"sourceIPs":["172.16.1.123"],"userAgent":"okhttp/3.12.6","objectRef":{"resource":"deployments","namespace"       :"aipaas-notebook","name":"c941didor23xe64s-notebook","apiGroup":"apps","apiVersion":"v1"},"responseStatus":{"metadata":{},"status":"Success","code":200},"requestObject":{"kind":"DeleteOptions","apiVersion":"apps/v1","propagationPolic       y":"Background"},"responseObject":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Success","details":{"name":"c941didor23xe64s-notebook","group":"apps","kind":"deployments","uid":"e551794a-0036-11ea-ac9e-fa163efea19e"}},"re       questReceivedTimestamp":"2019-11-06T01:44:07.813136Z","stageTimestamp":"2019-11-06T01:44:07.822674Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":""}}
</code><pre>

**Comment by zhangxingdeppon** [comment]
through audit log, look the replicaset deleted log,  you will find keywords `"finalizers":["orphan"]`.

**Comment by zhangxingdeppon** [comment]
@rohanKanojia  could you have any ideas?

**Comment by rohanKanojia** [comment]
@zhangxingdeppon : I'm not so aware about propagation policies. I usually do `cascading(true)` when deleting children resources. Could you please create a small test case for me to reproduce? I can try fixing this whenever I get time.

**Comment by zhangxingdeppon** [comment]
@rohanKanojia okay, I created a test case about it, just `cascading(true)`, but  it's similar to previous situation, firstly delete replicaset and then delete deployment, when delete replicaset, it also is  `"finalizers":["orphan"]`.

**Comment by rohanKanojia** [comment]
@zhangxingdeppon : let me add this issue to my list and get back to you

**Comment by rohanKanojia** [comment]
@zhangxingdeppon : Could you also please share your Deployment manifest if possible?

**Comment by rohanKanojia** [comment]
@zhangxingdeppon : Sorry but I was unable to reproduce this behavior. Here is what I did:

- Spin a simple deployment like this: `kubectl run nginx --image=nginx --replicas=1`
- Run the following code: 
```
            client.apps().deployments().inNamespace("default")
                    .withName("nginx")
                    .withPropagationPolicy("Background")
                    .delete();
```

When I ran this code I couldn't see any orphaned pod:
```
~/go/src/github.com/fabric8io/kubernetes-client : $ kubectl get all                                      
NAME                         READY   STATUS    RESTARTS   AGE                                            
pod/nginx-7bb7cd8db5-lvns8   1/1     Running   0          84s                                            
                                                                                                         
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE                                
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   7h2m                               
                                                                                                         
NAME                    READY   UP-TO-DATE   AVAILABLE   AGE                                             
deployment.apps/nginx   1/1     1            1           84s                                             
                                                                                                         
NAME                               DESIRED   CURRENT   READY   AGE        
replicaset.apps/nginx-7bb7cd8db5   1         1         1       85s       

... Run code in IntelliJ

~/go/src/github.com/fabric8io/kubernetes-client : $ kubectl get all       
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE 
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   7h2m

```
I tried on Kubernetes Client v4.6.3 and minikube. Here is it's version:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

Could you please check what I could have missed for reproducing your issue?

**Comment by zhangxingdeppon** [comment]
@rohanKanojia I known, but it just occasionally happened,  maybe you can open the kubernetes audit log to check the details about api  request, after that you will find that all delete request is  ` delete replicaset` with `"finalizers":["orphan"]`,  I think it shouldn't `"finalizers":["orphan"]`.
this is my deployment yaml:
<pre><code>
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2019-11-12T09:13:35Z"
  generation: 3
  labels:
    app: ysepymind4id48ah-notebook
  name: ysepymind4id48ah-notebook
  namespace: aipaas-notebook
  resourceVersion: "35431468"
  selfLink: /apis/extensions/v1beta1/namespaces/aipaas-notebook/deployments/ysepymind4id48ah-notebook
  uid: b468a8d2-052c-11ea-ac9e-fa163efea19e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ysepymind4id48ah-notebook
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ysepymind4id48ah-notebook
    spec:
      containers:
      - env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: none
        image: 172.16.1.222:10004/library/jupyter/pyspark-notebook_spark_ver_2.3.1:v1.0.0
        imagePullPolicy: Always
        name: ysepymind4id48ah-notebook
        ports:
        - containerPort: 8888
          name: jupyter
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /src/notebooks/
          name: ysepymind4id48ah-notebook
      dnsPolicy: ClusterFirst
      nodeSelector:
        node: worker
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 999
        runAsUser: 999
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ysepymind4id48ah-notebook
        persistentVolumeClaim:
          claimName: ysepymind4id48ah-pvc
</code></pre>

**Comment by k-wall** [comment]
I might be hitting the same issue myself - on 4.6.2.  I see the issue sporadically.   I believe the issue is a race in `io.fabric8.kubernetes.client.dsl.internal.DeploymentOperationsImpl.DeploymentReaper#reap`.

I too am deleting deployments using a PropagationPolicy background:

```
 client.apps().deployments().inNamespace("default")
                    .withName("mydep")
                    .withPropagationPolicy("Background")
                    .delete();
```

The `DeploymentReaper#reap` code scales the deployment to 0 replicas, and then `waitForObservedGeneration()`. It then proceeds to delete the replicaset *without* passing the propagation/cacade wishes of the caller.

In the unlucky case (the one that leaves the pods orphaned), the request to delete the replicaset arrives with the server and is processed *before* the request to scale pods to zero is actioned.

I can see two possible fixes for this (untested):

1. scaling should await deployment.getSpec().getReplicas() becoming zero i.e. call `oper.scale(0, true)`
1. propagation/cacade wishes from the caller to the call deleting the replicaset resource. `io.fabric8.kubernetes.client.dsl.internal.DeploymentOperationsImpl.DeploymentReaper#reapMatchingReplicaSets`

**Comment by rohanKanojia** [comment]
@k-wall : Thanks for looking into this. I am good with second option.
