### ISSUE TITLE
Support for kubernetes 1.17

### ISSUE THREAD

**Issue by Lionelpang** [fabric8io/kubernetes-client#1872]
Is there any plan to support kuberentes 1.16?How to join in your development and get the latest version of kubernetes model?

**Comment by rohanKanojia** [comment]
Yes, I'll add this in 1-2 weeks.

**Comment by rohanKanojia** [comment]
Kubernetes 1.17 just got released few days ago see [this](https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-release-announcement/https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-release-announcement/), Shall I upgrade the model to Kubernetes 1.17 instead?

**Comment by jorsol** [comment]
The potential risk is that some updated model removes old API, or in other words if API graduated to stable, deprecates API that was in beta, like for instance the CRDs is stable in 1.16, and I think the beta API is going to be removed in 1.19, that would break apps that uses beta API to target older versions of K8s.

Other than that, I don't see why not upgrade to Kubernetes 1.17, actually it looks weird that the model/support for Kubernetes is behind a few months, maybe really few people use "edge" versions, but if there is no issue with backwards compatibility it should be upgraded to the latest version.

**Comment by rohanKanojia** [comment]
cool, Thanks @jorsol for the feedback! let me try to upgrade to 1.17

**Comment by Lionelpang** [comment]
Good, looking forward to supporting kubernetes 1.17. How long can I support it?

**Comment by rohanKanojia** [comment]
I'm planning to release v4.7.0 before Christmas, this change should get in that.

**Comment by Lionelpang** [comment]
Great, looking forward to v4.7.
