### ISSUE TITLE
which release version adapt to Kubernetes 1.5.X ?

### ISSUE THREAD

**Issue by Marten2016** [fabric8io/kubernetes-client#1873]
hello. buddies, I have read the document readme.txt, but I still don't find the Compatibility Matri about Kubernetes 1.5.X, is there any suggestion?

**Comment by rohanKanojia** [comment]
@Marten2016 : hmm, that's quite old version. Try using `1.3.92` or `3.0.3` and see if it works

**Comment by Marten2016** [comment]
> @Marten2016 : hmm, that's quite old version. Try using 1.3.92 or 3.0.3 and see if it works

it's really an old version, thank you very much.
