### ISSUE TITLE
Selecting custom kube config for the library in springboot

### ISSUE THREAD

**Issue by contactreji** [fabric8io/kubernetes-client#1879]
Hello guys

We have a requirement where we run a springboot app in multiple config profiles. We use ```fabric8io/kubernetes-client``` library to communicate with remote k8s cluster to launch deployments of certain resources.

Our requirement is to point to different k8s cluster. (having the springboot jar run 3 instances with 3 config profiles in the same vm) 

Kube config file is at ```$HOME/.kube/config ```. We wanna have like ```$HOME/.kube/config _dev```, ```$HOME/.kube/config_stage```, and ```$HOME/.kube/config_prod```

How do I force my app to pick up custom kube config files instead of pointing to the default ``````$HOME/.kube/config ``` alone?

**Comment by rohanKanojia** [comment]
I think there is a system property to override this behavior: `KUBERNETES_KUBECONFIG_FILE` . Could you please try it out and see if it helps your use case?

**Comment by contactreji** [comment]
Thanks @rohanKanojia . I overrid the property called ```kubeconfig``` and it did the magic. passed the location/name of the new file as jvm argument and it worked.
