### ISSUE TITLE
Editing an ingress to remove a path does not seem to work

### ISSUE THREAD

**Issue by pseernam** [fabric8io/kubernetes-client#1885]
I've created the following ingress using kubernetes-client's Ingress Java APIs, the API version being extensions/v1beta1

```
Name:             www
Namespace:       test
Default backend:  default-http-backend:80 (<none>)
Rules:
  Host                                                                           Path  Backends
  ----                                                                           ----  --------
  www.test.k8s-clsuter
                                                                                 /ingress/www-1   ingress-www-1:8080 (<none>)
                                                                                 /ingress/www-2   ingress-www-2:8080 (<none>)
Annotations:
  kubernetes.io/ingress.class:        f5
  virtual-server.f5.com/http-port:    80
  virtual-server.f5.com/ip:           controller-default
  virtual-server.f5.com/round-robin:  round-robin
```
The yaml file for the above 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: f5
    virtual-server.f5.com/http-port: "80"
    virtual-server.f5.com/ip: controller-default
    virtual-server.f5.com/round-robin: round-robin
  creationTimestamp: 2019-12-01T22:41:56Z
  generation: 3
  name: www
  namespace: test
  resourceVersion: "16542082"
  selfLink: /apis/extensions/v1beta1/namespaces/test/ingresses/www
  uid: c72bcdc3-148b-11ea-a72b-0050568ddf82
spec:
  rules:
  - host: www.test.cluster
    http:
      paths:
      - backend:
          serviceName: ingress-www-1
          servicePort: 8080
        path: /ingress/www-1
     - backend:
          serviceName: ingress-www-2
          servicePort: 8080
        path: /ingress/www-2
status:
  loadBalancer:
    ingress:
    - ip: 174.31.71.100
```

Now, I want to delete one of the paths in the ingress above and I am doing that using the following:

```
kubernetesClient.extensions().ingresses().inNamespace("test").withName("ingress-www-1").edit()
        .editOrNewSpec().editLastRule().editHttp().removeFromPaths(path).endHttp().endRule()
        .endSpec().done();
```

I can see that the right ingress path resource is being deleted and the removeFromPaths call itself goes through fine based on logs I have:

Deleting HTTPIngressPath(backend=IngressBackend(serviceName=ingress-www-1, servicePort=IntOrString(IntVal=8080, Kind=null, StrVal=null, additionalProperties={}), additionalProperties={}), path=/ingress/www-2, additionalProperties={}) from existing IngressResource's backend www

Even after the above if I try getting the ingresses using kubectl, I see that the path I tried deleting has not been deleted:

kubectl describe ing www -n test

```
Name:             www
Namespace:       test
Default backend:  default-http-backend:80 (<none>)
Rules:
  Host                                                                           Path  Backends
  ----                                                                           ----  --------
  www.test.k8s-clsuter
                                                                                 /ingress/www-1   ingress-www-1:8080 (<none>)
                                                                                 /ingress/www-2   ingress-www-2:8080 (<none>)
Annotations:
  kubernetes.io/ingress.class:        f5
  virtual-server.f5.com/http-port:    80
  virtual-server.f5.com/ip:           controller-default
  virtual-server.f5.com/round-robin:  round-robin
```

Is it possible that I am missing something with the 'removeFromPaths' ingress API call?

**Comment by TianMingChen** [comment]
你好，请问这个问题你是怎么解决的呀？

**Comment by TianMingChen** [comment]
hello,how do you solve this problems?

**Comment by rohanKanojia** [comment]
@TianMingChen : Could you please try using `.patch()` with Ingress? Maybe this should work:

```java
try (KubernetesClient client = new DefaultKubernetesClient()) {
  client.network().v1()
      .ingresses()
      .inNamespace("default")
      .withName("ingress-wildcard-host")
      .patch(PatchContext.of(PatchType.JSON), "[{\"op\": \"remove\", \"path\":\"/spec/rules/0/http/paths/0\"}]");
}
```

**Comment by TianMingChen** [comment]
> 

ok,thank you ,it's work on delete path,but when i want to add a path,it seem to have a problem throw exception,this is my code,it's any wrong?
 ```
 client.extensions().ingresses().inNamespace("pkslow3").withName("ingress-http2")
                    .patch(PatchContext.of(PatchType.JSON),
                            "[{\"op\": \"add\", \"path\":\"/spec/rules/0/http/paths/\"}], \"value\": \"[{path:/m2(/|$)(.*), backend:[{serviceName:myapp,servicePort:8090}]}]\"");
```

**Comment by TianMingChen** [comment]
> @TianMingChen : Could you please try using `.patch()` with Ingress? Maybe this should work:
> 
> ```java
> try (KubernetesClient client = new DefaultKubernetesClient()) {
>   client.network().v1()
>       .ingresses()
>       .inNamespace("default")
>       .withName("ingress-wildcard-host")
>       .patch(PatchContext.of(PatchType.JSON), "[{\"op\": \"remove\", \"path\":\"/spec/rules/0/http/paths/0\"}]");
> }
> ```

Ok,thank you ,it's work on delete path,but when i want to add a path,it seem to have a problem throw exception,this is my code,it's any wrong?
```
client.extensions().ingresses().inNamespace("pkslow3").withName("ingress-http2")
                   .patch(PatchContext.of(PatchType.JSON),
                           "[{\"op\": \"add\", \"path\":\"/spec/rules/0/http/paths/\"}], \"value\": \"[{path:/m2(/|$)(.*), backend:[{serviceName:myapp,servicePort:8090}]}]\"");
```

**Comment by TianMingChen** [comment]
> > @TianMingChen : Could you please try using `.patch()` with Ingress? Maybe this should work:
> > ```java
> > try (KubernetesClient client = new DefaultKubernetesClient()) {
> >   client.network().v1()
> >       .ingresses()
> >       .inNamespace("default")
> >       .withName("ingress-wildcard-host")
> >       .patch(PatchContext.of(PatchType.JSON), "[{\"op\": \"remove\", \"path\":\"/spec/rules/0/http/paths/0\"}]");
> > }
> > ```
> 
> Ok,thank you ,it's work on delete path,but when i want to add a path,it seem to have a problem throw exception,this is my code,it's any wrong?
> 
> ```
> client.extensions().ingresses().inNamespace("pkslow3").withName("ingress-http2")
>                     .patch(PatchContext.of(PatchType.JSON),
>                            "[{\"op\": \"add\", \"path\":\"/spec/rules/0/http/paths/-\", \"value\": {\"path\":\"/m3(/|$)(.*)\", \"backend\":{\"serviceName\":\"myapp2\",\"servicePort\":\"8090\"}}}]");
> ```

I have solve this problem when i down the fabric8 version like this:
```
   <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>kubernetes-client</artifactId>
<!--            <version>5.10.1</version>-->
            <version>4.9.2</version>
        </dependency>
```
```
  client.extensions().ingresses().inNamespace("pkslow3").withName("ingress-http2")
                    .edit().editOrNewSpec()
                    .editFirstRule().editHttp().addToPaths(httpIngressPath).endHttp().endRule().endSpec().done();
```

**Comment by rohanKanojia** [comment]
@TianMingChen : Umm, that's strange. I'm able to add a new path with JSON patch strategy like this:
```java
client.network().v1()
    .ingresses()
    .inNamespace("default")
    .withName("ingress-wildcard-host")
    .patch(PatchContext.of(PatchType.JSON), "[{\"op\":\"add\",\"path\":\"/spec/rules/0/http/paths/1\",\"value\":{\"backend\":{\"service\":{\"name\":\"service5\",\"port\":{\"number\":80}}},\"path\":\"/bar5\",\"pathType\":\"Prefix\"}}]");
```

In 5.x version of client, we had changed `edit()` method, you can check [v5 Migration Guide](https://github.com/fabric8io/kubernetes-client/blob/master/doc/MIGRATION-v5.md#editable) . Now edit operation should be done it this:

```java
client.network().v1()
    .ingresses()
    .inNamespace("default")
    .withName("ingress-wildcard-host")
    .edit(i -> new IngressBuilder(i)
        .editSpec()
          .editFirstRule()
            .editHttp()
              .addNewPath()
                .withPath("/bar4")
                .withPathType("Prefix")
                .withNewBackend()
                .withNewService()
                  .withName("service4")
                  .withNewPort().withNumber(80).endPort()
                .endService()
                .endBackend()
              .endPath()
            .endHttp()
          .endRule()
        .endSpec()
        .build())
```

**Comment by TianMingChen** [comment]
> @TianMingChen : Umm, that's strange. I'm able to add a new path with JSON patch strategy like this:
> 
> ```java
> client.network().v1()
>     .ingresses()
>     .inNamespace("default")
>     .withName("ingress-wildcard-host")
>     .patch(PatchContext.of(PatchType.JSON), "[{\"op\":\"add\",\"path\":\"/spec/rules/0/http/paths/1\",\"value\":{\"backend\":{\"service\":{\"name\":\"service5\",\"port\":{\"number\":80}}},\"path\":\"/bar5\",\"pathType\":\"Prefix\"}}]");
> ```
> 
> In 5.x version of client, we had changed `edit()` method, you can check [v5 Migration Guide](https://github.com/fabric8io/kubernetes-client/blob/master/doc/MIGRATION-v5.md#editable) . Now edit operation should be done it this:
> 
> ```java
> client.network().v1()
>     .ingresses()
>     .inNamespace("default")
>     .withName("ingress-wildcard-host")
>     .edit(i -> new IngressBuilder(i)
>         .editSpec()
>           .editFirstRule()
>             .editHttp()
>               .addNewPath()
>                 .withPath("/bar4")
>                 .withPathType("Prefix")
>                 .withNewBackend()
>                 .withNewService()
>                   .withName("service4")
>                   .withNewPort().withNumber(80).endPort()
>                 .endService()
>                 .endBackend()
>               .endPath()
>             .endHttp()
>           .endRule()
>         .endSpec()
>         .build())
> ```

OK,it's work ,thank you ! happy new year !

**Comment by rohanKanojia** [comment]
@TianMingChen : Good to hear :) . Happy new year to you as well :tada:
