### ISSUE TITLE
Parsing different quantity formats

### ISSUE THREAD

**Issue by avmohan** [fabric8io/kubernetes-client#1895]
Is there an equivalent of https://github.com/kubernetes/apimachinery/blob/adc6f4cd9e7d28fc1c1e5efc658d940d55c0f356/pkg/api/resource/quantity.go in java?

**Comment by rohanKanojia** [comment]
I think we have a class, try searching `Quantity` in codebase.

**Comment by avmohan** [comment]
The class is there - https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-model/kubernetes-model/src/main/java/io/fabric8/kubernetes/api/model/Quantity.java -  but it doesn't actually "parse" it into a proper typed value.

**Comment by avmohan** [comment]
To clarify I was looking for something equivalent to https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/custom/Quantity.java

Do you think it's a good addition?

**Comment by rohanKanojia** [comment]
Yes, I do think it's a valuable addition.

Our Quanity.java has been deprecated as per latest kubernetes releases. We need to modify it. Actually it's already there in model for parsing go structs, but https://github.com/kubernetes/apimachinery/blob/adc6f4cd9e7d28fc1c1e5efc658d940d55c0f356/pkg/api/resource/quantity.go doesn't follow standard kubernetes types format. Our go script assumes all structs in types.go, I think we need to manually generate Quantity.java for this to work.

**Comment by rohanKanojia** [comment]
seemd related to #885

**Comment by rohanKanojia** [comment]
@avmohan : Hi, I've created a PR to support this use case of comparing different Quantity objects of different formats. Could you please see if this would fulfil your use case or you are looking for something more flexible(like converting Quantities from one to other as implemented in official client)?

**Comment by avmohan** [comment]
Thanks @rohanKanojia . This would work.
