### ISSUE TITLE
Log missing last chunk of data

### ISSUE THREAD

**Issue by rvansa** [fabric8io/kubernetes-client#1896]
My application writes some logs just before its pod is being deleted. I was able to get these consistently using `oc log ... -f` but I am less successful with the programmatic client:
```java
LogWatch logWatch = client.pods().inNamespace(NAMESPACE).withName(podName).watchLog();
int nread;
while ((nread = logWatch.getOutput().read(loggingBuffer)) > 0) {
   output.write(loggingBuffer, 0, nread);
}
if (nread < 0) {
   logWatch.close();
   output.close();
}
```
Am I using a wrong pattern?

**Comment by rvansa** [comment]
I've checked `PipedInput/OutputStream` that's used internally and it seems that the writer even does not wake up the receiver until it fills up the buffer. That's not really the case here but may cause other trouble. Also `PipedInputStream` returns `available() == 0` after we've read all buffered data despite the output thread might be still blocked.

**Comment by rohanKanojia** [comment]
@rvansa : Hi, Thanks for this bug report. Would you like to  raise a PR to fix this issue to start a discussion?

**Comment by rvansa** [comment]
@rohanKanojia I don't have a PR (or even working solution) ready yet; I've also found that sometimes I am using `watchLog` where `getLogReader` would be sufficient. I have a feeling that using pumper in combination with these piped streams in `LogWatchCallback` is the best solution these days; I would rather let use code do the polling directly on the response object.
Let me get more insight into that.

**Comment by rvansa** [comment]
Actually `getLogReader` and `getLog` has its drawbacks, too. If I am expecting kind of binary output reading it as `char`s isn't really suitable. The least putting the possibly tens-of-megabytes response into single `String` instance.

**Comment by rvansa** [comment]
Just for the record; in the end I've decided to do the HTTP request reading logs myself. Exposing the `InputStream` this way through `watchLog().getOutput()` rather than shoveling it through the piped streams would work better for me:

```java
PodOperationsImpl impl = (PodOperationsImpl) podResource;
URL url = new URL(impl.getResourceUrl().toString() + "/log");
Request.Builder requestBuilder = new Request.Builder().get().url(url);
Request request = requestBuilder.build();
Response response = ((HttpClientAware) client).getHttpClient().newCall(request).execute();
return response.body().byteStream();
```
