### ISSUE TITLE
how can i get pod status like kubectl 

### ISSUE THREAD

**Issue by phantooom** [fabric8io/kubernetes-client#1906]
kubectl get pod return container status this is code.

https://github.com/kubernetes/kubernetes/blob/aedeccda9562b9effe026bb02c8d3c539fc7bb77/pkg/kubectl/resource_printer.go#L692-L764

is there any function return pod status.phase like `kubectl get pod`?

**Comment by rohanKanojia** [comment]
I think you can get phase like this:
```
String phase = client.pods().inNamespace(namespace).withName(podName).get().getStatus().getPhase();
```

Could you please try and check if it helps your use case?
