### ISSUE TITLE
Cannot scale deployment

### ISSUE THREAD

**Issue by johnhec** [fabric8io/kubernetes-client#1918]
I scale the deployment using the following code：
`client.apps().deployments().inNamespace(ns).withName(name).scale(2)`
when I delete the deployment of my server created by crd, I expect the deployment will automatically resume via the code above. but it will get the following error：
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.128.34.38:6443/apis/apps/v1/namespaces/ocean-op-ns/deployments/ocean-cluster-ocean-gateway-api. Message: deployments.extensions "ocean-cluster-ocean-gateway-api" not found. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=extensions, kind=deployments, name=ocean-cluster-ocean-gateway-api, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=deployments.extensions "ocean-cluster-ocean-gateway-api" not found, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).

I wish to know how can i scale the deployments.

**Comment by rohanKanojia** [comment]
Does it work when you try to edit `Deployment` object rather then using `scale` method? Is your `Deployment` of type `extensions/v1beta1` or `apps/v1`? If it's the first case, then you should use `client.extensions()` dsl endpoint.

**Comment by johnhec** [comment]
> Does it work when you try to edit `Deployment` object rather then using `scale` method? Is your `Deployment` of type `extensions/v1beta1` or `apps/v1`? If it's the first case, then you should use `client.extensions()` dsl endpoint.

if I view the yaml through `kubectl get deployment.apps/ocean-cluster-ocean-service-ai -n ocean-op-ns -o yaml` the yaml shows apps/v1. if I view the yaml through `kubectl get deployment ocean-cluster-ocean-service-ai -n ocean-op-ns -o yaml` the yaml shows extensions/v1beta1. what type is it?

**Comment by rohanKanojia** [comment]
Hmm, :confused: I think it might be `extensions/v1beta1` . Try doing the same operation using `client.extensions()` dsl and see if it works.

**Comment by johnhec** [comment]
> Hmm, 😕 I think it might be `extensions/v1beta1` . Try doing the same operation using `client.extensions()` dsl and see if it works.

I have tried by client.extensions(). but it doesn't work.

**Comment by rohanKanojia** [comment]
I just tried scaling a deployment myself and was able to do so. Could you please check whether your deployment has correct namespace/name?

**Comment by johnhec** [comment]
> I just tried scaling a deployment myself and was able to do so. In logs, it looks like apiserver is not able to find resource specified in request(404). Could you please check whether your deployment has correct namespace/name?

namespace/name is right. When i delete the deployment, the deployment is down. At this time, it execute the code `scale(2)`. In internal code, it will send a get request to get deployment. But at this time, the deployment has been deleted, so the request failed. Then throw error, scale fails

**Comment by johnhec** [comment]
> > I just tried scaling a deployment myself and was able to do so. In logs, it looks like apiserver is not able to find resource specified in request(404). Could you please check whether your deployment has correct namespace/name?
> 
> namespace/name is right. When i delete the deployment, the deployment is down. At this time, it execute the code `scale(2)`. In internal code, it will send a get request to get deployment. But at this time, the deployment has been deleted, so the request failed. Then throw error, scale fails

If the deployment is not deleted ,it will not throw error, scale is true. but if i do not delete the deployment, how can I test that the scale is correct？

**Comment by rohanKanojia** [comment]
Could you please share your Deployment spec? Let me try to create it and scale it on my minikube instance.

**Comment by johnhec** [comment]
> Could you please share your Deployment spec? Let me try to create it and scale it on my minikube instance.
>>kubectl describe deployment.apps/ocean-cluster-ocean-service-ai -n ocean-op-ns
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-12-27T11:42:52Z"
  generation: 1
  labels:
    app: ocean-service-ai
    deployed: yckj
    ocean.io/OceanCluster: ocean-cluster
    ocean.io/kind: OceanCluster
  name: ocean-cluster-ocean-service-ai
  namespace: ocean-op-ns
  resourceVersion: "18423410"
  selfLink: /apis/apps/v1/namespaces/ocean-op-ns/deployments/ocean-cluster-ocean-service-ai
  uid: 8678bcb3-6749-4a4f-91db-9dffdcbb783c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ocean-service-ai
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ocean-service-ai
        deployed: yckj
        ocean.io/OceanCluster: ocean-cluster
        ocean.io/kind: OceanCluster
      namespace: ocean-op-ns
    spec:
      containers:
      - args:
        - ocean-service-ai
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: harbor.cloudwalk.work/ocean/prod-ocean:20191218
        imagePullPolicy: Always
        name: ocean-service-ai
        ports:
        - containerPort: 31301
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /ocean/configfiles
          name: config-volume
          readOnly: true
        - mountPath: /ocean/logs
          name: hostpath-volume
          subPathExpr: $(POD_NAME)
      dnsPolicy: ClusterFirst
      nodeSelector:
        network: ok
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: ocean-service-ai.properties
            path: ocean-service-ai.properties
          name: ocean-cluster-configmap
        name: config-volume
      - hostPath:
          path: /home/logs/ocean
          type: ""
        name: hostpath-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-12-27T11:42:58Z"
    lastUpdateTime: "2019-12-27T11:42:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-12-27T11:42:52Z"
    lastUpdateTime: "2019-12-27T11:42:58Z"
    message: ReplicaSet "ocean-cluster-ocean-service-ai-fdf9c7b47" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

**Comment by rohanKanojia** [comment]
Looks like your `Deployment`'s name is ` ocean-cluster-ocean-service-ai` not `ocean-cluster-ocean-gateway-api`

**Comment by johnhec** [comment]
> Looks like your `Deployment`'s name is ` ocean-cluster-ocean-service-ai` not `ocean-cluster-ocean-gateway-api`

this is anthoer deployment. it aslo not work for scale

**Comment by johnhec** [comment]
> Looks like your `Deployment`'s name is ` ocean-cluster-ocean-service-ai` not `ocean-cluster-ocean-gateway-api`

>kubectl get deployment.apps/ocean-cluster-ocean-gateway-api -n ocean-op-ns -o yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-12-28T09:51:53Z"
  generation: 1
  labels:
    app: ocean-gateway-api
    deployed: yckj
    ocean.io/OceanCluster: ocean-cluster
    ocean.io/kind: OceanCluster
  name: ocean-cluster-ocean-gateway-api
  namespace: ocean-op-ns
  resourceVersion: "18651565"
  selfLink: /apis/apps/v1/namespaces/ocean-op-ns/deployments/ocean-cluster-ocean-gateway-api
  uid: 1b4167ee-0f44-414b-bf78-e46be4d07d81
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ocean-gateway-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ocean-gateway-api
        deployed: yckj
        ocean.io/OceanCluster: ocean-cluster
        ocean.io/kind: OceanCluster
      namespace: ocean-op-ns
    spec:
      containers:
      - args:
        - ocean-gateway-api
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: harbor.cloudwalk.work/ocean/prod-ocean:20191218
        imagePullPolicy: Always
        name: ocean-gateway-api
        ports:
        - containerPort: 31401
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /ocean/configfiles
          name: config-volume
          readOnly: true
        - mountPath: /ocean/logs
          name: hostpath-volume
          subPathExpr: $(POD_NAME)
      dnsPolicy: ClusterFirst
      nodeSelector:
        network: ok
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: ocean-gateway-api.properties
            path: ocean-gateway-api.properties
          name: ocean-cluster-configmap
        name: config-volume
      - hostPath:
          path: /home/logs/ocean
          type: ""
        name: hostpath-volume
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2019-12-28T09:52:00Z"
    lastUpdateTime: "2019-12-28T09:52:00Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-12-28T09:51:53Z"
    lastUpdateTime: "2019-12-28T09:52:00Z"
    message: ReplicaSet "ocean-cluster-ocean-gateway-api-584466d99f" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2

this is ocean-cluster-ocean-service-ai  deployment spec. but it do not work for scale.
**I have a question, why deployment `scale` need to send a get request to get deployment status. At this time, the deployment has been deleted, so the request definitely fails. What's the point of doing this？**

**Comment by johnhec** [comment]
> Does it work when you try to edit `Deployment` object rather then using `scale` method? Is your `Deployment` of type `extensions/v1beta1` or `apps/v1`? If it's the first case, then you should use `client.extensions()` dsl endpoint.

I have try to edit `Deployment`, it also throw the same error.
