### ISSUE TITLE
Can't replace Service when upgraded | spec.clusterIP: Invalid value: "": field is immutable.

### ISSUE THREAD

**Issue by cedar715** [fabric8io/kubernetes-client#1925]
Following is the code snippet used to create Service resource. It is failing when I upgraded Fabric8 from 4.1.1 to 4.6.4.

```
ParameterNamespaceListVisitFromServerGetDeleteRecreateWaitApplicable<HasMetadata, Boolean> load =
                kubernetesClient.resourceList(resourceDescriptor)
 final List<HasMetadata> res = load.createOrReplace()
```
resourceDescriptor is a String holding the Service manifest file.

> Failed to apply : 
> apiVersion: v1
> kind: Service
> metadata:
>   name: httpbin
>   labels:
>     app: httpbin
> spec:
>   ports:
>     - name: http
>       port: 5511
>       targetPort: 8080
>   selector:
>     deploymentconfig: httpbin
>  : io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://xxx:8443/api/v1/namespaces/xxx/services/httpbin. Message: Service "httpbin" is invalid: spec.clusterIP: Invalid value: "": field is immutable. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.clusterIP, message=Invalid value: "": field is immutable, reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Service, name=httpbin, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Service "httpbin" is invalid: spec.clusterIP: Invalid value: "": field is immutable, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).

**Comment by rohanKanojia** [comment]
@cedar715 : Thanks for your bug report. I can confirm that I can reproduce this issue. It's strage I'm not able to reproduce if I create service like this:
```
     client.services().inNamespace("default").createOrReplace(svc);
```
But I can reproduce this error when I do it your way:
```
		String resourceList = "apiVersion: v1\n" +
					"kind: Service\n" +
					"metadata:\n" +
					"  name: httpbin\n" +
					"  labels:\n" +
					"    app: httpbin\n" +
					"spec:\n" +
					"  ports:\n" +
					"  - name: http\n" +
					"    port: 5511\n" +
					"    targetPort: 8080\n" +
					"  selector:\n" +
					"    deploymentconfig: httpbin";


			ParameterNamespaceListVisitFromServerGetDeleteRecreateWaitApplicable<HasMetadata, Boolean> load = client.resourceList(resourceList);
			final List<HasMetadata> res = load.inNamespace("default").deletingExisting().createOrReplace();

```
