### ISSUE TITLE
why 4.6.3 api not support MetricsSpec

### ISSUE THREAD

**Issue by wangjianxiang** [fabric8io/kubernetes-client#1934]
before i use 4.2.1 api has MetricsSpec method it is OK！ Now I upgrade api  to 4.6.3 ，My program can't run 。What should I do?

**Comment by rohanKanojia** [comment]
@wangjianxiang : Hi, I had mistakenly changed `HorizontalPodAutoscaler` to `autoscaling/v1`. I have reverted this in https://github.com/fabric8io/kubernetes-client/pull/1778 . It should be available in next release.

**Comment by wangjianxiang** [comment]
thank you. When will the next version be available? I would like to know the exact time

**Comment by rohanKanojia** [comment]
@wangjianxiang : Fabric8 Kubernetes Client [v4.7.0](https://search.maven.org/artifact/io.fabric8/kubernetes-client/4.7.0/jar) has been released. It would contain your fix for `HorizontalPodAutoscaler`

**Comment by wangjianxiang** [comment]
OK OK! thanks
