### ISSUE TITLE
Error while running tests if jenkins is running on top of openshift

### ISSUE THREAD

**Issue by guilhermecgs** [fabric8io/kubernetes-client#1935]
Hi folks

I am running the exact same test [as this one](https://github.com/fabric8io/kubernetes-client#crud-mode).  In my local comnputer it works just fine. However, during my build pipeline, ir fails miserably.
The build pipeline is using jenkins on top of openshift to create worker pods to execute the tests.

It looks like the KubernetesClient is confused about which openshift to use: 1) the mock openshift server OR 2) the real openshift used by jenkins?

**Is my assumption correct? How to solve it?**

`[2020-01-08T19:36:48.535Z] mytest> testInCrudMode STANDARD_OUT
DEBUG [ticket=:fase=] --- [    Test worker] io.fabric8.kubernetes.client.Config      : Trying to configure client from Kubernetes config...
DEBUG [ticket=:fase=] --- [    Test worker] io.fabric8.kubernetes.client.Config      : Did not find Kubernetes config at: [/home/jenkins/.kube/config]. Ignoring.
DEBUG [ticket=:fase=] --- [    Test worker] io.fabric8.kubernetes.client.Config      : Trying to configure client from service account...
DEBUG [ticket=:fase=] --- [    Test worker] io.fabric8.kubernetes.client.Config      : Found service account host and port: 10.26.0.1:443
DEBUG [ticket=:fase=] --- [    Test worker] io.fabric8.kubernetes.client.Config      : Found service account ca cert at: [/var/run/secrets/kubernetes.io/serviceaccount/ca.crt].
DEBUG [ticket=:fase=] --- [    Test worker] io.fabric8.kubernetes.client.Config      : Found service account token at: [/var/run/secrets/kubernetes.io/serviceaccount/token].
DEBUG [ticket=:fase=] --- [    Test worker] io.fabric8.kubernetes.client.Config      : Trying to configure client namespace from Kubernetes service account namespace path...
DEBUG [ticket=:fase=] --- [    Test worker] io.fabric8.kubernetes.client.Config      : Found service account namespace at: [/var/run/secrets/kubernetes.io/serviceaccount/namespace].
 INFO [ticket=:fase=] --- [WebServer 57955] okhttp3.mockwebserver.MockWebServer      : MockWebServer[57955] starting to accept connections
Gradle Test Executor 1 finished executing tests.

mytest > testInCrudMode FAILED
    io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.

        Caused by:
        java.net.SocketException: Connection reset
`

**Comment by manusa** [comment]
This is really strange as the KubernetesServer (Mock) provides KubernetesClient with an instance of OKHttpClient that should connect to the Mocked server.

Can you provide some code or any way to reproduce the issue so that we can take a look?

**Comment by guilhermecgs** [comment]
hi @manusa ,

I figured out what caused the error.

The jenkins runner was using a proxy configured using environment variables.
Since the client was connecting using localhost, the proxy blocked.

After configuring gradle with NO_PROXY=localhost,127.0.0.1 .  it worked.

However, it was quite painful to figured out. The only information I had was 

>     Caused by:    java.net.SocketException: Connection reset

Maybe the client should log more info

**Comment by manusa** [comment]
Hi @guilhermecg,

Thanks for the update.

I'm not sure if we can provide more information in logs as the error probably had the origin OK Http library
