### ISSUE TITLE
Item needs to be one of [Node, Deployment, ReplicaSet, StatefulSet, Pod, DeploymentConfig, ReplicationController], but was: [Service]

### ISSUE THREAD

**Issue by wangjianxiang** [fabric8io/kubernetes-client#1936]
hello, I ran into a problem with version 4.6.3，before i use 4.6.3 api  in  kubernetes (1.11.1) ,it is no problem，but now i use 4.6.3 api in  kubernetes (1.16.1) ，My program is abnormal，Show failed to create service。

`[ERROR] 2020-01-08 22:44:40.953 [http-nio-8082-exec-8] DeployKubeServiceImpl - 创建service default-http-backend10013401610214失败
java.lang.IllegalArgumentException: Item needs to be one of [Node, Deployment, ReplicaSet, StatefulSet, Pod, DeploymentConfig, ReplicationController], but was: [Service]
	at io.fabric8.kubernetes.client.internal.readiness.Readiness.isReady(Readiness.java:79) ~[kubernetes-client-4.6.3.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.waitUntilReady(BaseOperation.java:1032) ~[kubernetes-client-4.6.3.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.waitUntilReady(HasMetadataOperation.java:227) ~[kubernetes-client-4.6.3.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.ServiceOperationsImpl.waitUntilReady(ServiceOperationsImpl.java:93) ~[kubernetes-client-4.6.3.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.ServiceOperationsImpl.waitUntilReady(ServiceOperationsImpl.java:40) ~[kubernetes-client-4.6.3.jar:?]
	at com.sgcc.devops.resource.service.impl.DeployKubeServiceImpl.createDefaultService(DeployKubeServiceImpl.java:1000) [cloud.container.resource-1.0.1-SNAPSHOT.jar:?]`

**Comment by wangjianxiang** [comment]
Can you help me see my problem?

**Comment by rohanKanojia** [comment]
@wangjianxiang : Could you please share the code which caused this error so that I can reproduce this on my machine?

**Comment by wangjianxiang** [comment]
OK ,  I find the question.
`public Result create() {
    	 boolean acceptIp = false;
         if(!getDeployModel().isDnsEnable()){
             acceptIp =true;
         }
        String systemCode =getDeployModel().getSystemCode();
        String domainName = getDeployModel().getDomainName();
        String containerPath="/" +getDeployModel().getContentPath();
        int port = Integer.parseInt(getDeployModel().getExposePort());
        Ingress ingress = new Ingress();
        Map<String, String> annotations = new HashMap<>();
        String loadBalanceId = getDeployModel().getLoadBalanceId();
        annotations.put("nginx.ingress.kubernetes.io/proxy-body-size", "2000m");
        annotations.put("kubernetes.io/ingress.class",loadBalanceId);
        annotations.put("nginx.ingress.kubernetes.io/affinity","cookie");
        annotations.put("nginx.ingress.kubernetes.io/session-cookie-name","INGRESSCOOKIE");
        annotations.put("nginx.ingress.kubernetes.io/session-cookie-hash","sha1");
        annotations.put("nginx.ingress.kubernetes.io/upstream-hash-by","sticky");
        if(acceptIp){
            annotations.put("nginx.ingress.kubernetes.io/ssl-redirect","false");
            }
        //回转数据超时时间   响应超时时间
        SysComCode readSec = commonParameter.getReadSec();
        SysComCode sendSec = commonParameter.getSendSec();
        if(null!=readSec){
            annotations.put("nginx.ingress.kubernetes.io/proxy-read-timeout",readSec.getComCode());
        }
        if(null!=sendSec){
            annotations.put("nginx.ingress.kubernetes.io/proxy-send-timeout",sendSec.getComCode());
        }
        ObjectMeta objectMeta = new ObjectMeta();
        objectMeta.setAnnotations(annotations);
        objectMeta.setName(systemCode);
        ingress.setMetadata(objectMeta);
        List<IngressRule> rules = new ArrayList<>();
        IngressRule ingressRule = new IngressRule();
        if(!acceptIp){
            ingressRule.setHost(domainName);
        }
        HTTPIngressRuleValue httpIngressRuleValue = new HTTPIngressRuleValue();
        List<HTTPIngressPath> paths = new ArrayList<HTTPIngressPath>();
        HTTPIngressPath httpIngressPath = new HTTPIngressPath();
        httpIngressPath.setPath(containerPath);
        IngressBackend backend = new IngressBackend();
        backend.setServiceName(systemCode);
        IntOrString intOrString=new IntOrString();
        intOrString.setIntVal(port);
        backend.setServicePort(intOrString);
        httpIngressPath.setBackend(backend);
        paths.add(httpIngressPath);
        httpIngressRuleValue.setPaths(paths);
        ingressRule.setHttp(httpIngressRuleValue);
        rules.add(ingressRule);
        IngressSpec ingressSpec = new IngressSpec();
        ingressSpec.setRules(rules);
        ingress.setSpec(ingressSpec);
        ingress = get_kube().extensions().ingresses().inNamespace(KubernetesConstants.NAMESPACE).createOrReplace(ingress);
        try {
            get_kube().extensions().ingresses().inNamespace(KubernetesConstants.NAMESPACE).withName(systemCode).waitUntilReady(commonParameter.getDeployTimeOut(), TimeUnit.MINUTES);
        } catch (InterruptedException e) {
            e.printStackTrace();
            return new Result(false,"失败");
        }
        logger.info("ingress更新成功");
        return new Result(true,"");
    }`

Look this, On version 3.1.2, there is no problem executing the code ，
On version 4.6.3, an exception occurred in the execution code. The exception code is (get_be(). Extensions(). Expressions(). Innamespace (kubernetesconstants. Namespace). Withname (systemcode). Waituntilready (commonparameter. Getdeploytimeout(), timeunit. Minutes);)
