### ISSUE TITLE
Impersonate-Group cause trouble after adapting to OpenShiftClient

### ISSUE THREAD

**Issue by Halgaswatta** [fabric8io/kubernetes-client#1945]
We upgraded fabric8/kube-client to its latest 4.7.0 and we use impersonate-user functionality to deploy namespaced resources in OpenShift and came across that it is throwing Impersonate-Group is null when we use adapted OpenshiftClient.

Below code breaks even though I have not set any Impersonate-Group, it still return true and go inside the if condition. After than it fails saying Impersonate-Group == null. 

https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/ImpersonatorInterceptor.java#L47

**Comment by rohanKanojia** [comment]
@Halgaswatta : Could you please provide a simple test case to reproduce this?

**Comment by rohanKanojia** [comment]
@Halgaswatta @cedar715: Shall we close this issue? @cedar715 told me that he was able to get it resolved.

**Comment by rohanKanojia** [comment]
@Halgaswatta @cedar715: Polite ping. Still facing this issue? If not, shall we close it?

**Comment by harshajith** [comment]
I have only given impersonate-user while creating the client, however had to set impersonate-group  to null explicitly to get it to work as it throws a NPE otherwise.
