### ISSUE TITLE
Error:java: java.lang.NoClassDefFoundError: io/fabric8/kubernetes/api/model/Doneable

### ISSUE THREAD

**Issue by wangyushuai** [fabric8io/kubernetes-client#1949]
Hi, 
Firstly, I execute `mvn clean install` after clone this project;

But, when I try run a unit test, found this error!

![image](https://user-images.githubusercontent.com/8596105/72324442-ee33bc00-36e5-11ea-916f-b2275c4118e4.png)

How I can fix it, Thanks!

**Comment by manusa** [comment]
Try to run `mvn clean install` from your console, it looks like IntelliJ had some trouble compiling Kubernetes-model module, so the rest of you module compilations failed too.

**Comment by manusa** [comment]
Hi @wangyushuai 
I think were already able to submit your PR, so probably this is not a problem anymore.
Could you please confirm by closing the issue or add a comment if you're still having problems?

**Comment by wangyushuai** [comment]
I try `mvn clean package` again  in my console, problem has been solved！ Thanks ！ @manusa
