### ISSUE TITLE
Can't get openshift URL withen deployed MS

### ISSUE THREAD

**Issue by alonir** [fabric8io/kubernetes-client#1959]
Hi

i am trying to get the external URL of an open shift withing MS which is using the fabric 8 java client.
Looks like i am getting only internal IP which can't be used outside.
i tried masterUrl and more fields but can get only the internal IP.
Is there a way to get the external host or is it planned it future releases?

**Comment by alonir** [comment]
I see no comments so I'll Try to explain with a question. 
How can i get the external URL of an open shift cluster within a deployed MS, currently i am getting only internal IP.

**Comment by manusa** [comment]
I'm not really understanding what you want to accomplish and if this is related to the client.

The client autodetects cluster's settings ([directly-accessing-the-rest-api](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/#directly-accessing-the-rest-api-1)) and accesses the cluster using the internal `kubernetes.default.svc` hostname.

If you want to get the external URL of the cluster (which may or may not be exposed), I'm guessing you'll have to provide this information manually to your Pod (I don't know, maybe OpenShift provides this functionality out of the box).
