### ISSUE TITLE
Duration parsing doesn't work according kubernetes implementation

### ISSUE THREAD

**Issue by famartinrh** [fabric8io/kubernetes-client#1964]
I noticed the parsing of io.fabric8.kubernetes.api.model.Duration doesn't work like it's equivalent in kubernetes.
https://github.com/fabric8io/kubernetes-client/blob/30c0656123cbe48b5e6f4d269ab8c480baebf290/kubernetes-model/kubernetes-model/src/main/java/io/fabric8/kubernetes/api/model/Duration.java#L90

That algorithm should behave like the one implemented in kubernetes
https://github.com/kubernetes/kubernetes/blob/a38096a0696514a034de7f8d0cc5a3ec5e7da8ff/vendor/github.com/go-openapi/strfmt/duration.go#L92
Which is inspired in the scala implementation of Duration
https://github.com/scala/scala/blob/f4b153a37770a03e02381e00c678d10922bc8231/src/library/scala/concurrent/duration/Duration.scala#L57

**Comment by manusa** [comment]
Relates to:
- #1282
- #1919
