### ISSUE TITLE
Quantity getAmountInBytes can not work

### ISSUE THREAD

**Issue by Tammo0987** [fabric8io/kubernetes-client#1965]
The method pow of BigDecimal is used in the getAmountInBytes of the Quantity class, but three cases are throwing an ArithmeticException, because the parameter of pow can not be less than zero.

![image](https://user-images.githubusercontent.com/22091805/73089871-72045a00-3ed7-11ea-925e-4090a908ab7e.png)

**Comment by rohanKanojia** [comment]
I think https://github.com/fabric8io/kubernetes-client/pull/1937 shall fix this issue

**Comment by rohanKanojia** [comment]
@Tammo0987 : I just released v4.7.1 which contains #1937 . Could you please check whether you're still facing `ArithmeticException` when using Quantity?

**Comment by Tammo0987** [comment]
**@rohanKanojia :** Sorry for the duplicate. The new release v4.7.1 works for me. Thank you :)
