### ISSUE TITLE
Working with Podsecuritypolicies is broken using k8s1.17 due to api version change

### ISSUE THREAD

**Issue by tobexyz** [fabric8io/kubernetes-client#1968]
In k8s1.17 PodSecurityPolicies were dropped from the api version "extensions/v1beta1". 
They are now part of the api version "policy/v1beta1" as mentioned here https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

The kubernetes-client in Version 4.7.0 still uses the api version "extensions/v1beta1" for PodSecurityPolicies.

Please support the new api version. 

Thx.

**Comment by rohanKanojia** [comment]
@tobexyz : Looks like I missed it during upgrade. Would you like to create a PR for this? Just need to change `PodSecurityPolicy` to `policy.PodSecurityPolicy`:

https://github.com/fabric8io/kubernetes-client/blob/cf186055d12925d5abf78d534db6c0f5618ecec9/kubernetes-model/cmd/generate/generate.go#L177
