### ISSUE TITLE
How to configure nodePort

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/kubernetes-client#197]
See SO
http://stackoverflow.com/questions/33419749/how-to-get-the-nodeport-using-fabric8-java-api-for-kubernetes

@iocanel doe the fluent DSL have a withNodePort or is there something missing in our client library?

**Comment by iocanel** [comment]
Yes, it does! I added a comment on SO. Not sure if there is more to be done here.

**Comment by davsclaus** [comment]
Thanks
