### ISSUE TITLE
is fabric8io kubernetes-client suuport dex or any oidc ?

### ISSUE THREAD

**Issue by yeganeahmadnejad** [fabric8io/kubernetes-client#1980]
hi 
I've used dex for authentication in kube8
now want to use this client , but I  cant find any param to set idp-certificate-authority-data or idp-issuer-url in  buildconfig()
is there any support?

**Comment by wing011203** [comment]
@yeganeahmadnejad , You can try Config.fromKubeconfig method, it accepts a argument to contain the kube config file content, as far as I can see it can parse the idp-certificate-authority-data or idp-issuer-url.
But the thing is that though the information can be parsed, there is something wrong with the code, I have raised a ticket #1997 to track, you can check it.

**Comment by rohanKanojia** [comment]
@wing011203 : Hi, Could you please create a PR to propose your changes to existing method?
