### ISSUE TITLE
Enable Sonarcube code analysis on project

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#1981]
We're already using sonar cloud for analyzing PRs and project in Fabric8 Maven Plugin and Docker Maven Plugin. It seems to be working well lately. 

I think we should enable it here as well. We just need to enable project on sonarcloud and add circleci jobs for analyzing PRs https://github.com/fabric8io/fabric8-maven-plugin/blob/master/.circleci/config.yml

**Comment by manusa** [comment]
Maybe it's a good time to introduce GitHub Actions in the project and leverage a little the CircleCI build resources.

Right now we're running actions for IT both in [JKube](https://github.com/eclipse/jkube/actions) and unofficially for [FMP](https://github.com/manusa/fmp-integration-tests/actions) and they are working quite well.

**Comment by rohanKanojia** [comment]
@manusa : Yeah, that's a good idea. Right now we're running tests on Openshift instance only but in case of Jkube we're also running on Kubernetes. We should be testing on both platforms.

**Comment by manusa** [comment]
Sonar scanning is working:
- https://sonarcloud.io/dashboard?id=kubernetes_client
- https://github.com/fabric8io/kubernetes-client/actions/runs/48034811
- https://github.com/fabric8io/kubernetes-client/actions/runs/48207189
