### ISSUE TITLE
How can I use "withPipelineResourceBinding()" to define taskRun resources?

### ISSUE THREAD

**Issue by jwkim1993** [fabric8io/kubernetes-client#1987]
**Issue description**
I recently use tekton-client extension to make taskRun with Java.

I tried to define new input resources, and I found withPipelineResourceBinding() function in ".withNewSpec().withNewInputs().addNewResource()".

There are "withName(), withNewResourceSpec()" functions in the above funtion, so that I thought this is to define resources.

However, when I use the function, a runtime error occurs.

> Message addmission webhook "webhook.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "pipelineResourceBinding".

How could I use this function properly?

Or, if that function is not for resource definition, what is the right function?

Thanks for replying.

**Comment by majian159** [comment]
+1

**Comment by rohanKanojia** [comment]
@majian159 @jwkim1993 : Hi, we've updated our tekton client to `v0.11.0-rc2` . Could you please check on the latest master if this is still an issue?

**Comment by rohanKanojia** [comment]
@majian159 @jwkim1993 : I haven't tried this myself on a tekton setup, but I think you should be able to create a `TaskRun` like this(I found one `TaskRun` object in tekton [docs](https://github.com/tektoncd/pipeline/blob/master/docs/taskruns.md#example-taskrun):
```
      TaskRun taskRun = new TaskRunBuilder()
        .withNewMetadata().withName("read-repo-run").endMetadata()
        .withNewSpec()
        .withNewResources()
        .withInputs(new TaskResourceBindingBuilder()
          .withName("read-task")
          .withResourceRef(new PipelineResourceRefBuilder().withName("go-example-git").build())
          .build())
        .endResources()
        .endSpec()
        .build();
      client.taskRuns().inNamespace("default").create(taskRun);
```
Am I understanding your question correctly? Could you please share some code sample to elaborate your question a bit ?

**Comment by majian159** [comment]
TaskResourceBindingBuilder miss withName and withResourceRef.
![image](https://user-images.githubusercontent.com/10176784/78228891-d52af200-7501-11ea-91ef-88c0b8321078.png)

only PipelineResourceBinding.
i can't find the definition of PipelineResourceBinding in tekton.
@rohanKanojia

**Comment by rohanKanojia** [comment]
@majian159 : Which version are you trying it on? Actually tekton upgrade hasn't been released yet. Would it be possible for you to build project and test SNAPSHOT version?

**Comment by rohanKanojia** [comment]
@majian159 : On SNAPSHOT version, I'm able to see these
![Screenshot from 2020-04-02 16-06-42](https://user-images.githubusercontent.com/13834498/78240105-259f5100-74fc-11ea-8846-4ad9061201a7.png)

Maybe I should add some example for this
