### ISSUE TITLE
hostname not verified when connecting ipv6 cluster

### ISSUE THREAD

**Issue by leehoawki** [fabric8io/kubernetes-client#1991]
Hello
I am using the kubernetes client to connect an ipv6 cluster via [fd00::13] and get the following exception,

javax.net.ssl.SSLPeerUnverifiedException: Hostname fd00::13 not verified:
...
subjectAltNames: [fd01:0:0:0:0:0:0:1, fd00:0:0:0:0:0:0:13, ...]

I tried the full address (fd00:0:0:0:0:0:0:13) but it seems that the okhttp will transform it into fd00::13 automatically and it get the same error mesage

**Comment by periklis** [comment]
@leehoawki I run into the same issue on OpenShift 4.x and my troubleshooting concludes that the client falls back to use the variables `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT` from the pod environment when no kubeconfig is provided, which AFAIU are not populated with hostnames. Following the official k8s docs on [accessing a cluster](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod), I fixed my deployment that uses this client by setting the `KUBERNETES_MASTER` to `https://kubernetes.default.svc `. Alternatively you can in the system properties the `kubernetes.master` property as the [docs](https://github.com/fabric8io/kubernetes-client#configuring-the-client) suggest.

This is possibly a solution for #1744, too.
