### ISSUE TITLE
the Improvement "Fix #1800 Schedule reconnect in case of HTTP_GONE when watching" is gone 

### ISSUE THREAD

**Issue by yybear** [fabric8io/kubernetes-client#1992]
the improvement "Fix #1800 Schedule reconnect in case of HTTP_GONE when watching" in 4.6.1 release.
but in 4.6.4 release, this  improvement is gone, client just closes the connect not try to reconnect. 
i don't find any description about it from 4.6.2 to 4.6.4 release.
so why removing this improvement?

**Comment by rohanKanojia** [comment]
This was reverted since it was not aligning with standard watcher behavior, see this conversation: https://github.com/fabric8io/kubernetes-client/pull/1800#issuecomment-549561724

**Comment by yybear** [comment]
I see，thanks!
