### ISSUE TITLE
Refactor SharedInformers

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#2010]
## Description

Shared Informers module was implemented simply by porting the Go-client implementation.

Although everything works fine, there's still room for improvement.
- Create more testable code (clear separation of concerns, and interface segregation)
- Add unit tests to verify implementation
- Check concurrency implementations and thread safety

Relates to:
- #1961
- #1894 - #1951 
- #1384 - #1728
- #1075 
- #2489

**Comment by shawkins** [comment]
After the Informable change I think this can be resolved.  The only thing I don't like about the remaining impl is how the resync logic functions - but it matches the go client so it's probably not worth tweaking further.

**Comment by shawkins** [comment]
Marking as resolved based upon the last comment.

**Comment by manusa** [comment]
@shawkins Thank you very much for your tremendous effort making this happen.

I'm sure that our Shared Informer implementation and all the extra-features around it are some of the main differentiating traits that make the Fabric8 client special and maybe better as compared to its competition.

:raised_hands:
