### ISSUE TITLE
CRD Delete not working | Jackson deserialization of empty response not working

### ISSUE THREAD

**Issue by reste85** [fabric8io/kubernetes-client#2023]
Hi,
We've a strange behaviuor. We're deleting a CRD in our tests, and the mocked server (and also the official kubernetes server) returns 200 with an empty body. 

At this point the client throws an exception, due to the fact that the empty body can't be deserialized to an hashmap. The problem arises in the following function of the class "RawCustomResourceOperationsImpl": 

`private Map<String, Object> makeCall(String url, String body, RawCustomResourceOperationsImpl.HttpCallMethod callMethod) {
        Request request = body == null ? this.getRequest(url, callMethod) : this.getRequest(url, body, callMethod);

        try {
            Response response = this.client.newCall(request).execute();
            Throwable var6 = null;

            Map var7;
            try {
                if (!response.isSuccessful()) {
                    throw requestFailure(request, createStatus(response));
                }

                var7 = (Map)this.objectMapper.readValue(response.body().string(), HashMap.class);
            } catch (Throwable var17) {
                var6 = var17;
                throw var17;
            } finally {
                if (response != null) {
                    if (var6 != null) {
                        try {
                            response.close();
                        } catch (Throwable var16) {
                            var6.addSuppressed(var16);
                        }
                    } else {
                        response.close();
                    }
                }

            }

            return var7;
        } catch (Exception var19) {
            throw KubernetesClientException.launderThrowable(var19);
        }
    }`

`var7 = (Map)this.objectMapper.readValue(response.body().string(), HashMap.class);` is the one that is giving problems to us, deserializing an empty string ("") to hashmap.

We're using fabric8 kubernetes client version 4.8.0 & kubernetes-server-mock 4.8.0

**Comment by rohanKanojia** [comment]
Did you mean Kubernetes client v4.8.0? Or is it really 2.8.0?

**Comment by reste85** [comment]
> Did you mean Kubernetes client v4.8.0? Or is it really 2.8.0?

Yeah sorry, Kubernetes fabric8 client 4.8.0

**Comment by reste85** [comment]
In my opinion, this should be an easy fix:

1st idea)
- Before performing the readValue method of the Jackson ObjectMapper, check if the body is an empty string. If yes return an empty map.

2nd idea)
- Some config of the ObjectMapper should do the trick, parsing an empty string in an empty map

if you want i can provide a PR with the solution

**Comment by reste85** [comment]
The code i've provided in the first post is a decompiled code. More specifically the method is the following: 

`private Map<String, Object> makeCall(String url, String body, HttpCallMethod callMethod) {
    Request request = (body == null) ? getRequest(url, callMethod) : getRequest(url, body, callMethod);
    try (Response response = client.newCall(request).execute()) {
      if (response.isSuccessful()) {
        return objectMapper.readValue(response.body().string(), HashMap.class);
      } else {
        throw requestFailure(request, createStatus(response));
      }
    } catch(Exception e) {
      throw KubernetesClientException.launderThrowable(e);
    }
  }`

**Comment by reste85** [comment]
The code i've provided in the first post is a decompiled code. More specifically the method is the following: 

`private Map<String, Object> makeCall(String url, String body, HttpCallMethod callMethod) {
    Request request = (body == null) ? getRequest(url, callMethod) : getRequest(url, body, callMethod);
    try (Response response = client.newCall(request).execute()) {
      if (response.isSuccessful()) {
        return objectMapper.readValue(response.body().string(), HashMap.class);
      } else {
        throw requestFailure(request, createStatus(response));
      }
    } catch(Exception e) {
      throw KubernetesClientException.launderThrowable(e);
    }
  }`

**Comment by rohanKanojia** [comment]
@reste85 : I would appreciate if you could create a PR for the fix :-)

**Comment by reste85** [comment]
> @reste85 : I would appreciate if you could create a PR for the fix :-)

My PR is ready, but i can't push on the fix branch:

"ERROR: Permission to fabric8io/kubernetes-client.git denied to reste85."

**Comment by oscerd** [comment]
You need to fork the project and push the branch on your fork

**Comment by reste85** [comment]
Thank you, i've opened the PR
