### ISSUE TITLE
edit statefulset call method task 3~4 seconds

### ISSUE THREAD

**Issue by Mrkoalay** [fabric8io/kubernetes-client#2026]
client version is 4.6.4.
`  client.apps().statefulSets().inNamespace(appName).withName(clusterName)
                        .edit()
                        .editSpec()
                        .withReplicas(replicas)
                        .endSpec()
                        .done();`

Running the above program will take more than 20 seconds.  why?

**Comment by rohanKanojia** [comment]
Are you able to reproduce this on `v4.8.0` too?

**Comment by Mrkoalay** [comment]
> Are you able to reproduce this on `v4.8.0` too?

thanks, I'll try

**Comment by dev-gaur** [comment]
@Mrkoalay any feedback?

**Comment by Mrkoalay** [comment]
> @Mrkoalay any feedback?

 It worked！haha

**Comment by Mrkoalay** [comment]
> Are you able to reproduce this on `v4.8.0` too?

It worked！thanks
