### ISSUE TITLE
Include Tekton Trigger into the Tekton extension

### ISSUE THREAD

**Issue by jeffmaury** [fabric8io/kubernetes-client#2043]
The Tekton extension only supports Tekton Pipeline. We should add support for Tekton Triggers as well

**Comment by jeffmaury** [comment]
Still relevant

**Comment by Fabian-K** [comment]
I´m also interested in this! If no one is already working on this I can try to contribute it. Do you see this as a new extension or should this be added to the existing tekton extension?

**Comment by rohanKanojia** [comment]
@Fabian-K : Thanks a lot! In my opinion, it should be added to existing tekton extension

**Comment by manusa** [comment]
Please go ahead! Thank you very much.
