### ISSUE TITLE
OpenshiftClient  getVersion returns null for Openshift ContainerPlatform v4

### ISSUE THREAD

**Issue by sbouchet** [fabric8io/kubernetes-client#2046]
While working on an issue on the IntelliJ openshift connector (https://github.com/redhat-developer/intellij-openshift-connector/issues/119), I noticed that the client.getversion() does not return proper version info for V4

while on v3, the endpoint is hardcoded to "version/openshift" and return a result, the same endpoint for v4 does return a 404, and then the versionInfo is null.

**Comment by rohanKanojia** [comment]
@sbouchet : oh, Do you what endpoint is there in Openshift 4?

**Comment by rohanKanojia** [comment]
okay, so on Openshift 4 it seems to be this:
```
~/work/repos/fmp-demo-project : $ curl localhost:8001/version
{
  "major": "1",
  "minor": "14+",
  "gitVersion": "v1.14.6+b294fe5",
  "gitCommit": "b294fe5",
  "gitTreeState": "clean",
  "buildDate": "2020-01-06T18:46:07Z",
  "goVersion": "go1.12.12",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```
We need to modify handle this via interceptor

**Comment by sbouchet** [comment]
@rohanKanojia : looks like it is the kubernetes version, not the openshift version...

**Comment by rohanKanojia** [comment]
@sbouchet : oh, yeah :eyeglasses:  , need to check what's the updated endpoint and modify accordingly.

**Comment by rohanKanojia** [comment]
I think maybe it's this:
http://localhost:8001/apis/config.openshift.io/v1/clusterversions 
```
{
  "apiVersion": "config.openshift.io/v1",
  "items": [
    {
      "apiVersion": "config.openshift.io/v1",
      "kind": "ClusterVersion",
      "metadata": {
        "creationTimestamp": "2020-01-30T04:05:33Z",
        "generation": 2,
        "name": "version",
        "resourceVersion": "44758",
        "selfLink": "/apis/config.openshift.io/v1/clusterversions/version",
        "uid": "c301755d-4315-11ea-9872-52540022f9dd"
      },
      "spec": {
        "channel": "stable-4.2",
        "clusterID": "c92835a5-395d-4448-840d-6a223f9a02c7",
        "upstream": "https://api.openshift.com/api/upgrades_info/v1/graph"
      },
      "status": {
        "availableUpdates": [
          {
            "force": false,
            "image": "quay.io/openshift-release-dev/ocp-release@sha256:e5a6e348721c38a78d9299284fbb5c60fb340135a86b674b038500bf190ad514",
            "version": "4.2.16"
          }
        ],
        "conditions": [
          {
            "lastTransitionTime": "2020-01-30T04:05:35Z",
            "status": "False",
            "type": "Available"
          },
          {
            "lastTransitionTime": "2020-01-30T04:31:38Z",
            "message": "Cluster operator monitoring is still updating",
            "reason": "ClusterOperatorNotAvailable",
            "status": "True",
            "type": "Failing"
          },
          {
            "lastTransitionTime": "2020-01-30T04:05:35Z",
            "message": "Unable to apply 4.2.14: the cluster operator monitoring has not yet successfully rolled out",
            "reason": "ClusterOperatorNotAvailable",
            "status": "True",
            "type": "Progressing"
          },
          {
            "lastTransitionTime": "2020-01-30T04:05:36Z",
            "status": "True",
            "type": "RetrievedUpdates"
          }
        ],
        "desired": {
          "force": false,
          "image": "quay.io/openshift-release-dev/ocp-release@sha256:3fabe939da31f9a31f509251b9f73d321e367aba2d09ff392c2f452f6433a95a",
          "version": "4.2.14"
        },
        "history": [
          {
            "completionTime": null,
            "image": "quay.io/openshift-release-dev/ocp-release@sha256:3fabe939da31f9a31f509251b9f73d321e367aba2d09ff392c2f452f6433a95a",
            "startedTime": "2020-01-30T04:05:35Z",
            "state": "Partial",
            "verified": false,
            "version": "4.2.14"
          }
        ],
        "observedGeneration": 1,
        "versionHash": "kEuk9MZ8sK4="
      }
    }
  ],
  "kind": "ClusterVersionList",
  "metadata": {
    "continue": "",
    "resourceVersion": "62446",
    "selfLink": "/apis/config.openshift.io/v1/clusterversions"
  }
}
```

**Comment by sbouchet** [comment]
This API is only available in admin role :( 
i got an exception : 

Response{protocol=http/1.1, code=403, message=Forbidden, url=https://api.crc.testing:6443/apis/config.openshift.io/v1/clusterversions}

version is 4.2.13 from admin console

![Capture d’écran de 2020-03-09 13-43-05](https://user-images.githubusercontent.com/600414/76213930-01f22f00-620c-11ea-8f95-a96a73749458.png)

**Comment by sbouchet** [comment]
I forgot to mention that we're still using a pretty old version ( 3.2.0 ) ...

**Comment by rohanKanojia** [comment]
Do you mean old version of OpenShift?Don't worry we won't be breaking backward compatibility in this case.

**Comment by sbouchet** [comment]
No, sorry I mean old openshift-client version. Maybe it can fix or improve the current issue.
I'll try and let you know.

**Comment by ValVal89** [comment]
Issue is still present. OpenshiftClient getVersion does not return null, but OpenshiftClient  getVersion().getMajor() and OpenshiftClient  getVersion().getMinor() return null in both cases  for Openshift ContainerPlatform v4.
We use io.fabric8 openshift-client of the  latest version 4.10.2

**Comment by rohanKanojia** [comment]
@ValVal89 : oh, that's strange. I remember I tested it on Openshift v4.2. I'll test again whenever I get time.

**Comment by ValVal89** [comment]
@rohanKanojia : thank you. getVersion().getGitVersion() - this is also returns null

**Comment by rohanKanojia** [comment]
Actually `/version` endpoint is no longer supported in Openshift v4, I couldn't find GitVersion property in response. See my previous comment https://github.com/fabric8io/kubernetes-client/issues/2046#issuecomment-596433351
