### ISSUE TITLE
[Quantity] parsing of 129e6

### ISSUE THREAD

**Issue by skabashnyuk** [fabric8io/kubernetes-client#2052]
I've got unexpected to me result 1000000 instead of 129000000.
I think it's because here https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-model/kubernetes-model/src/main/java/io/fabric8/kubernetes/api/model/Quantity.java#L124
there is no multiplication on the amount. 
Can someone confirm? If yes would you like me to submit a patch?

**Comment by rohanKanojia** [comment]
Yes, please submit a patch. Thanks for noticing.
