### ISSUE TITLE
Is diff'ing yaml supported?

### ISSUE THREAD

**Issue by vxe** [fabric8io/kubernetes-client#2056]
The equivalent kubectl command:

```
# Compares the current state of the cluster against the state that the cluster would be in if the manifest was applied.
kubectl diff -f ./my-manifest.yaml
```

thanks and great work on this project!

**Comment by vxe** [comment]
don't need a complete example just asking if its possible with the current implementation

**Comment by manusa** [comment]
I don't think this is possible with our current implementation
Probably your best bet is to fetch the resource using our dsl, and then convert it to a String (e.g. `Serialization.asYaml`) which you can then compare with any Java diff tool with the contents of your file.
