### ISSUE TITLE
Tekton Client is missing ServiceLoader file for ResourceHandler

### ISSUE THREAD

**Issue by Fabian-K** [fabric8io/kubernetes-client#2057]
Hi,

the Tekton client is missing the ServiceLoader file for `META-INF/services/io.fabric8.kubernetes.client.ResourceHandler`.

If I understand it right, this entry is generated using `resource-handler-services.vm` however I can´t find the correct settings of the pom.xml for this file to be attached to the jar. Do you have any hint on how that is done?

Thanks,
Fabian

**Comment by manusa** [comment]
Hi,

I'm not really sure, but I think the file is generated by sundrio given this configuration:
https://github.com/fabric8io/kubernetes-client/blob/fce60d13bd3f4e98353686a75e24c4cbe819352e/extensions/tekton/client/src/main/java/io/fabric8/tekton/client/CodeGen.java#L26

I can see the file is being generated: 
![image](https://user-images.githubusercontent.com/488391/76594663-0499a080-64fa-11ea-8824-800e66f69062.png)

But as you say, not included in the jar:
![image](https://user-images.githubusercontent.com/488391/76594775-4aeeff80-64fa-11ea-9b55-a86683e5e545.png)

We'll investigate, there's probably some misconfiguration for tekton-client project.

**Comment by manusa** [comment]
Same issue is affecting:
- knative-client

**Comment by manusa** [comment]
Hi @Fabian-K 
I submitted #2064 to address the missing files in the affected jar bundles.
