### ISSUE TITLE
does createOrReplace() support --prune and --prune-whitelist?

### ISSUE THREAD

**Issue by vsevel** [fabric8io/kubernetes-client#2063]

**Comment by matthyx** [comment]
Hello @vsevel looks like it's not yet implemented - either in this client or in the official k8s.io clients...

And this for a reason: it looks like nobody really finished the work in `kubectl` and there was a debate 3.5 years ago on how to finalize this flag, please see:
https://github.com/kubernetes/kubernetes/pull/35220#issuecomment-255231265
https://github.com/kubernetes/kubernetes/pull/35220#issuecomment-255236360

That being said, it doesn't prevent us from providing something similar tailored to our needs...

**Comment by shawkins** [comment]
Closing this issue as out of date.  It's still in alpha, but the replacement is an apply-set https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#kubectl-apply-prune-1 - that should be significantly less work being a server side construct.
