### ISSUE TITLE
What is the api corresponding to the command of kubectl get certs

### ISSUE THREAD

**Issue by javydreamercsw** [fabric8io/kubernetes-client#2074]
I've spent most of the day today trying to figure out where I can get this from the client.

Just trying to replicate the command:

> kubectl get cert -A

**Comment by rohanKanojia** [comment]
@jamesnetherton : Hi, Since which version is this command supported in Kubernetes? I'm trying on `kubectl` v1.17.0 and minikube v1.6.2 but it's not recognizing it:
```
~/go/src/github.com/fabric8io/kubernetes-client : $ kubectl get certs -A
error: the server doesn't have a resource type "certs"
~/go/src/github.com/fabric8io/kubernetes-client : $  kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
~/go/src/github.com/fabric8io/kubernetes-client : $ minikube version
minikube version: v1.6.2
commit: 54f28ac5d3a815d1196cd5d57d707439ee4bb392
~/go/src/github.com/fabric8io/kubernetes-client : $
```

Do I need to enable some addon to use this?

**Comment by rohanKanojia** [comment]
As per my knowledge I don't think we are supporting certificate support in DSL. But I think it can be added once I find out the endpoint being hit from this command.

**Comment by javydreamercsw** [comment]
It works on 1.17.0 for me.

<img width="867" alt="Screen Shot 2020-03-19 at 10 50 53 AM" src="https://user-images.githubusercontent.com/2817343/77086417-c3a8fc80-69cf-11ea-834b-0d4e55695656.png">

**Comment by javydreamercsw** [comment]
Looks like I had a typo on the initial command.

**Comment by rohanKanojia** [comment]
@javydreamercsw : Could you please share logs with `kubectl get cert -v=8` ? that might help in finding out which endpoint is it hitting?

**Comment by javydreamercsw** [comment]
Is there a way to share that privately? This is from work and want to avoid exposing stuff.

**Comment by rohanKanojia** [comment]
oh, I see. You can remove sensitive data. I'm only concerned with the endpoint. Or you can share some example on your local minikube setup(Sadly I'm not able to see this on my minikube)

**Comment by javydreamercsw** [comment]
kubectl get cert -v=8
I0320 15:32:39.905989   23864 loader.go:375] Config loaded from file:  /home/ssm-user/.kube/config
I0320 15:32:39.917663   23864 round_trippers.go:420] GET https://6551B4499A23D7EDE0F66964B2372ABD.gr7.us-east-2.eks.amazonaws.com/apis/certmanager.k8s.io/v1alpha1/namespaces/ping-cloud/certificates?limit=500
I0320 15:32:39.917810   23864 round_trippers.go:427] Request Headers:
I0320 15:32:39.917832   23864 round_trippers.go:431]     Accept: application/json;as=Table;v=v1beta1;g=meta.k8s.io, application/json
I0320 15:32:39.917847   23864 round_trippers.go:431]     User-Agent: kubectl/v1.17.0 (linux/amd64) kubernetes/70132b0
I0320 15:32:40.369332   23864 round_trippers.go:446] Response Status: 200 OK in 451 milliseconds
I0320 15:32:40.369557   23864 round_trippers.go:449] Response Headers:
I0320 15:32:40.369581   23864 round_trippers.go:452]     Audit-Id: 6b93cb26-c487-44d4-839e-c0e93b769399
I0320 15:32:40.369597   23864 round_trippers.go:452]     Content-Type: application/json
I0320 15:32:40.369612   23864 round_trippers.go:452]     Content-Length: 2893
I0320 15:32:40.369625   23864 round_trippers.go:452]     Date: Fri, 20 Mar 2020 15:32:40 GMT
I0320 15:32:40.369671   23864 request.go:1017] Response Body: {"kind":"Table","apiVersion":"meta.k8s.io/v1beta1","metadata":{"selfLink":"/apis/certmanager.k8s.io/v1alpha1/namespaces/ping-cloud/certificates","resourceVersion":"3028888"},"columnDefinitions":[{"name":"Name","type":"string","format":"name","description":"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names","priority":0},{"name":"Ready","type":"string","format":"","description":"Custom resource definition column (in JSONPath format): .status.conditions[?(@.type==\"Ready\")].status","priority":0},{"name":"Secret","type":"string","format":"","description":"Custom resource definition column (in JSONPath format): .spec.secretName","priority":0},{"name":"Issuer","type":"string","format":"","description":"Custom resource [truncated 1869 chars]

**Comment by rohanKanojia** [comment]
@javydreamercsw : Hi, I checked and seems like `Certificates` is a Custom Resource. I was looking on internet about `Certificates` and I found https://github.com/jetstack/cert-manager/issues/1473 

Could you please confirm if this is the case?

**Comment by javydreamercsw** [comment]
Have no clue.

**Comment by rohanKanojia** [comment]
@javydreamercsw : Could you please check if you get CRD related to `Certificate` custom resource when you do `kubectl get crd`

**Comment by javydreamercsw** [comment]
This few seemed related:
```
sh-4.2$ kubectl get crd
NAME                                          CREATED AT
...
certificaterequests.certmanager.k8s.io        2020-04-09T21:29:54Z
certificates.certmanager.k8s.io               2020-04-09T21:29:54Z
challenges.certmanager.k8s.io                 2020-04-09T21:29:54Z
clusterissuers.certmanager.k8s.io             2020-04-09T21:29:54Z
...
```

**Comment by rohanKanojia** [comment]
I think `certificates.certmanager.k8s.io ` is the one we're looking for

**Comment by rohanKanojia** [comment]
We have a separate API for using Custom Resources. Please checkout our typed API[0] and typeless API[1] for dealing with Custom Resources.

[0] https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#customresource-typed-api
[1] https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#customresource-typeless-api

**Comment by rohanKanojia** [comment]
@javydreamercsw : polite ping, Did you get time to try out our customResource API for access `Certificate` custom resource? Here is a simple example on how to do it via typeless API:
```
        try (KubernetesClient client = new DefaultKubernetesClient()) {
            CustomResourceDefinitionContext crdContext = new CustomResourceDefinitionContext.Builder()
                    .withGroup("certmanager.k8s.io")
                    .withPlural("certificates")
                    .withScope("Namespaced")
                    .withVersion("v1alpha1")
                    .withName("certificates.certmanager.k8s.io ")
                    .build();

            Map<String, Object> list = client.customResource(crdContext).list("ping-cloud");
            JSONObject jsonObject = new JSONObject(list);
            JSONArray itemList = jsonObject.getJSONArray("items");
            System.out.println("list : " + itemList.length());
        }
```

 I think this issue can be closed.
