### ISSUE TITLE
KubernetesDeserializer registration for CustomResources broken

### ISSUE THREAD

**Issue by Fabian-K** [fabric8io/kubernetes-client#2075]
The current implementation in `CustomResourceOperationsImpl` passes the wrong apiVersion and Kind values to `KubernetesDeserializer.registerCustomKind(...)`. 

apiVersion and Kind for a CustomResourceDefinition are always `apiextensions/v1beta1` and `CustomResourceDefinition`.

The values from the spec needs to be passed for registering the custom kind in the deserializer.

**Comment by bbeaudreault** [comment]
Would it be possible to get this fix included in a release? I tried upgrading to 4.9.0 and this is causing issues.

**Comment by rohanKanojia** [comment]
@manusa @oscerd : thoughts?? Shall we cut a minor release 4.9.1 or shall we proceed towards major 5.0.0 release?

**Comment by oscerd** [comment]
4.9.1 I guess

**Comment by bbeaudreault** [comment]
Thanks both! 4.9.1 would be appreciated. Looks like there have been a few bug fixes in the last month.

**Comment by manusa** [comment]
I think the only breaking changes as of now in master are the model upgrades for Tekton and Knative. Not sure how you usually proceed with this situations.

I don't mind releasing now and after the split. Regarding version numbering, whatever we usually do for similar cases (the project is quite lenient regarding semver).

**Comment by rohanKanojia** [comment]
@bbeaudreault : We have released v4.9.1 . Could you please try it out and share feedback?

**Comment by bbeaudreault** [comment]
Thanks for getting that out! I was able to pull it into my project and tests are now passing. If I run into any other issues, I'll let you know.
