### ISSUE TITLE
Can't watch specific resource entity

### ISSUE THREAD

**Issue by oleksiys** [fabric8io/kubernetes-client#208]
When I try to set the watch for a specific resource entity, like pod:

        Watch watch = client.pods().inNamespace("default")
                .withName(podName).watch(new Watcher<Pod>() {
.....
        });

I see an error in the log:
watch.onClose io.fabric8.kubernetes.client.KubernetesClientException: Connection unexpectedly closed

Most probably it happens, because the watch as query parameter could be set only for resource entity list, but not the specific resource, to set a watch for a specific resource different URL has to be used, like:
http://host:port/api/v1/watch/namespaces/default/pods/pod_name

**Comment by jimmidyson** [comment]
Thanks for the report! Fixing now.
