### ISSUE TITLE
how to get metrics by client api 

### ISSUE THREAD

**Issue by damozhiying** [fabric8io/kubernetes-client#2082]
```
sudo kubectl top node
185.xx.yy.110     878m         2%     18481Mi         29%         
185.xx.yy.111     2571m        8%     18440Mi         29%         
185.xx.yy.112     921m         2%     12111Mi         19%   
```
how to get  node metrics  and custom metrics by client api

**Comment by damozhiying** [comment]
i want to get node metrics then custom loadbalance by node cpu,mem usage

**Comment by damozhiying** [comment]
how to get node cpu and memory usage percentage

**Comment by rohanKanojia** [comment]
@damozhiying : Could you please check if this helps your use case:

https://github.com/fabric8io/kubernetes-client/blob/15f3597bf3f198059945ff5717a8205bbf4986c3/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/TopExample.java#L30-L66

**Comment by damozhiying** [comment]
@rohanKanojia thanks a lot
now ,can get metrics from client.top().nodes().metrics(); but the client api can't get node physics cpu,so can't get cpu usage percentage

**Comment by rohanKanojia** [comment]
Umm, client returns the deserialized response from metric server. I think `kubectl` calculates percentage itself from the data provided. Would it be possible for you to do that too?

**Comment by damozhiying** [comment]
client.top().nodes() ，how to filter some node?

**Comment by rohanKanojia** [comment]
I think there is one more method: `client.top().nodes().metrics("nodeName");`

**Comment by damozhiying** [comment]
@rohanKanojia thanks a lot
normal condition， we want to filter some node by label='xxx', client.top().nodes().metrics("nodeName") can get only one node metrics

**Comment by rohanKanojia** [comment]
@damozhiying : ah, that doesn't seem to be supported as of now :-( . Would you like to create a PR to add this functionality? Just need to add a method here to append labels in request url: 
https://github.com/fabric8io/kubernetes-client/blob/15f3597bf3f198059945ff5717a8205bbf4986c3/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NodeMetricOperationsImpl.java#L27-L47

**Comment by damozhiying** [comment]
@rohanKanojia thans a lot ,let me try commit a pr

**Comment by bearxsh** [comment]
> Umm, client returns the deserialized response from metric server. I think `kubectl` calculates percentage itself from the data provided. Would it be possible for you to do that too?

Now, I only get used CPU and memory. how can I get a total capacity of CPU and memory to calculate usage percentage?
