### ISSUE TITLE
Does version 4.9.0 supports to CRUD Ingress which 'apiVersion: networking.k8s.io/v1beta1'

### ISSUE THREAD

**Issue by cainzhong** [fabric8io/kubernetes-client#2088]
Example yaml:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
....
```

**Comment by rohanKanojia** [comment]
@cainzhong : I think this can help https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/IngressTest.java

**Comment by cainzhong** [comment]
> @cainzhong : I think this can help https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/IngressTest.java

Thanks for your reply. I already do that. I can see some code `/apis/extensions/v1beta1` in your given link. I think it doesn't meet my expectations. I want some the apiVersion of Ingress is **`networking.k8s.io/v1beta1`**

**Comment by rohanKanojia** [comment]
@cainzhong  : I think for that we should probably update our Ingress object in our model: https://github.com/fabric8io/kubernetes-client/blob/8321522e75d0e6f5b5ef0aadea3d82f07beff758/kubernetes-model/cmd/generate/generate.go#L191

**Comment by rohanKanojia** [comment]
I think for now you can try overriding default `apiVersion` by specying it in the object you pass to client. Should work for create or patch operations..
