### ISSUE TITLE
Getting mutatingwebhookconfiguration

### ISSUE THREAD

**Issue by sidharthnayyar** [fabric8io/kubernetes-client#2090]
I'm trying to use fabric8 to get details of a mutatingwebhookconfiguration in my cluster. Unfortunately I can't seem to figure out how to do it!

I thought I could use client.resourceList to get all mutatingwebhookconfigurations (or use it to search for the one that I want) but I'm obviously doing it wrong.

List<HasMetadata> data = context.getClient().resourceList(new MutatingWebhookConfigurationBuilder().build()).get()

I tried specify name in the builder to try to find specific mutatingwebhookconfiguration but that didn't find it either.

Is there anyway this can be done via fabric8?

**Comment by manusa** [comment]
Relates to #887

**Comment by rohanKanojia** [comment]
I think we added support for MutatingWebhookConfiguration in recent releases. You can access it like this:

https://github.com/fabric8io/kubernetes-client/blob/14c5aff1fe13e6978dd1255995b4394a357e9554/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/V1MutatingWebhookConfigurationTest.java#L57-L58
