### ISSUE TITLE
Add @Nonnull-Annotation to the functions

### ISSUE THREAD

**Issue by opensource21** [fabric8io/kubernetes-client#2092]
It would be great specially when use this library from kotlin, if alle methods get a @Nonnull-Annotation. In a first step you could define all methods of a class with @Nonnull(when = When.MAYBE). This would help because the fields in the model are mostly nullable.
See https://kotlinlang.org/docs/reference/java-interop.html#jsr-305-support

**Comment by opensource21** [comment]
What a pitty that there's no reaction on it expect a bot.

**Comment by opensource21** [comment]
Is the project dead?

**Comment by manusa** [comment]
Hi @opensource21 
As you can see by [the number of commits](https://github.com/fabric8io/kubernetes-client/commits/master) and activity, the project is not dead.
We are really trying to make this a community driven project so PRs are welcome and greatly appreciated.
