### ISSUE TITLE
can we support create multi pods in one request

### ISSUE THREAD

**Issue by Aitozi** [fabric8io/kubernetes-client#2098]
Hi, i am new to this project, when i try to create serval pods in one create call to speed up the request, but i get 

```
java.lang.IllegalArgumentException: Too many items to create.
```

I am doubt that why this operation is nor supported?

**Comment by rohanKanojia** [comment]
@Aitozi : Could you please try this out?
```
client.resourceList(new PodListBuilder().addToItems(pod1, pod2, pod3).build()).createOrReplace()
```

**Comment by Aitozi** [comment]
Thanks @rohanKanojia , it works. another question: why createOrReplace() here not just create() api like used in client.pods().create()? I just want to create the list of pods or throw exception if there already exists (do not want to replace).  Is there a doc can refer to ?

**Comment by rohanKanojia** [comment]
@Aitozi : Actualy `createOrReplace()` is equivalent of `kubectl apply`, it does a POST if resource doesn't exist. Otherwise it does a PUT

**Comment by rohanKanojia** [comment]
Umm, Unfortunately we don't have any docs to refer to at the moment. Maybe I should work on some kind document for common use cases :thinking:

**Comment by Aitozi** [comment]
Got it ! Thanks for your patient explain :)
