### ISSUE TITLE
Support automatic refreshing for expired OIDC tokens

### ISSUE THREAD

**Issue by eugene-krivobokov** [fabric8io/kubernetes-client#2111]
Hi!
We use oidc authentication. [Our code](https://github.com/avito-tech/avito-android/blob/develop/subprojects/gradle/kubernetes/src/main/kotlin/com/avito/utils/gradle/Kubernetes.kt) is running inside Gradle plugin.
I've found that id-token is not refreshing automatically. 
To mitigate this I've reused this mechanism from the official kubernetes client:

```kotlin
import io.fabric8.kubernetes.client.OAuthTokenProvider
import io.kubernetes.client.util.FilePersister
import io.kubernetes.client.util.KubeConfig

private fun oauthTokenProvider(config: File): OAuthTokenProvider {
    val kubeConfig = KubeConfig.loadKubeConfig(config.inputStream().reader())
    val persister = FilePersister(config)
    kubeConfig.setPersistConfig(persister)

    return OAuthTokenProvider { kubeConfig.accessToken }
}
```

```kotlin
Config.fromKubeconfig(kubernetesCredentials.context, configContents, "").apply {
       ...
       requestConfig.oauthTokenProvider = oauthTokenProvider(configFile)
}
```
https://github.com/avito-tech/avito-android/pull/297/files#diff-47071b3c0f7eebf84051f6b86e0558d9R55

Does the library support it?

**Comment by rohanKanojia** [comment]
@eugene-krivobokov: Hi, Thanks a lot for your bug report. I'm not sure if our library supports this as of now. I think we should try to integrate it as it seems to be a very common use case. @oscerd  @manusa @iocanel WDYT??
