### ISSUE TITLE
[tekton] keep v1alpha1 api

### ISSUE THREAD

**Issue by Fabian-K** [fabric8io/kubernetes-client#2115]
Hi,

with the update 0.11.0, tekton added API version v1beta1. The old API version v1alpha1 is still supported.

The pull request https://github.com/fabric8io/kubernetes-client/pull/2020 removed the model definitions for v1alpha1 and added v1beta1. This forces projects using the client to migrate to the new API version (even if tekton still allows the creation of v1alpha1). Is it possible to keep both and e.g. mark v1alpha1 as deprecated? From the model point of view, this should be quite easy. I'm not sure about the TektonClient API though...

Best regards,
Fabian

**Comment by rohanKanojia** [comment]
Hmm, as far as I know right now there is only 1 *Handler/*OperationsImpl class generated per Tekton resource. Need to check how we can provide these classes specific to apiGroups

**Comment by Fabian-K** [comment]
Hi @rohanKanojia, 

looks like the generation part is simple (although I did not test it thoroughly yet)
https://github.com/Fabian-K/kubernetes-client/tree/tekton-multiple-version-support

The tricky part is the entry point from a client perspective. I could think of `client.v1alpha1().pipelines()...`or `client.pipelines().v1alpha1()...`

**Comment by rohanKanojia** [comment]
I like `client.v1alpha1().pipelines()..` and `client.v1beta1().pipelines()..`

@iocanel @manusa @oscerd : WDYT??

**Comment by rohanKanojia** [comment]
@Fabian-K : Hi Fabian, Have you started working on this issue? I was thinking if I could pick it up instead.

**Comment by Fabian-K** [comment]
@rohanKanojia not on the entrypoint, but the generation should be completed in https://github.com/Fabian-K/kubernetes-client/tree/tekton-multiple-version-support. Feel free to continue from there. Note, however, that this builds on top of my generator rewrite :)
