### ISSUE TITLE
Support ResourceVersion for updating metadata

### ISSUE THREAD

**Issue by dlangerenken** [fabric8io/kubernetes-client#2116]
In kubectl, you can run `kubectl label pods mypod foo=bar --namespace my-name --resource-version="313"` and it will refuse updating the pod when the resource version is not equal. It will throw the exception "the object has been modified; please apply your changes to the latest version and try again".

This does not seem to be supported in kubernetes-client:

```java
kubernetesClient.services().inNamespace(namespace).withName(resourceName).edit() //
        .editMetadata()
        .withResourceVersion("13213414141") // definitely does not match existing one
        /**/.addToLabels(Collections.unmodifiableMap(labels)) //
        .endMetadata() //
        .done();
```
No matter whether I use N, N-1, N+1 as a resource version - all updates of my metadata succeed.

There seems to be a method called "lockResourceVersion" for services/config-maps, but this requires me to replace my entire service. This is not really an option.

If concurrency safe updating of labels is not supported yet - Would you be considering to add it to your future versions?

See https://stackoverflow.com/questions/61019387/concurrency-safe-updating-of-labels-with-kubernetes-client?noredirect=1#comment108026550_61019387

Thank you!

**Comment by AllenField** [comment]
try this:

```
Service service = client.services().inNamespace(namespace).withName(resourceName).get();
service.getMetadata().setLabels(Collections.unmodifiableMap(labels));

client.services().inNamespace(namespace).withName(resourceName).lockResourceVersion(service.getMetadata().getResourceVersion()).replace(service);
```
