### ISSUE TITLE
[knative] Service.status is always null

### ISSUE THREAD

**Issue by Fabian-K** [fabric8io/kubernetes-client#2117]
Hi,

when I retrieve the knative services via the KnativeClient, the status is always null. I think that might be introduced with https://github.com/fabric8io/kubernetes-client/pull/2030 - my guess is the missing no argument constructor?!

Thanks,
Fabian

**Comment by rohanKanojia** [comment]
@Fabian-K : Thanks for your bug report. Could you please raise a quick PR to fix this issue?
