### ISSUE TITLE
Question: why java.lang.NullPointerException when deployment.getStatus().getAvailableReplicas() == 100

### ISSUE THREAD

**Issue by HillebrandtOldenberg** [fabric8io/kubernetes-client#2129]
After I scale a hello-word deployment to 100 pods:
`kubernetesClient.apps().deployments().inNamespace(testNamespace).withName(deploymentName).scale(100, true);`

I want to wait until all 100 pods become available:
`kubernetesClient.apps().deployments().inNamespace(testNamespace).withName(deploymentName).waitUntilCondition(deployment -> (deployment.getStatus().getAvailableReplicas() == 100), 2, TimeUnit.MINUTES);`
or
`        kubernetesClient.apps().deployments().inNamespace(testNamespace).withName(deploymentName).waitUntilCondition(deployment -> (deployment.getStatus().getAvailableReplicas().equals(100)), 2, TimeUnit.MINUTES);`

But, when I run it, I get the Cucumber error:
```
Step failed
java.lang.NullPointerException
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.waitUntilCondition(BaseOperation.java:1079)
```

Am I using the `getStatus().getAvailableReplicas()` methods wrong?

**Comment by rohanKanojia** [comment]
@HillebrandtOldenberg : Which version of client are you using? Your usage seems fine to me. I checked some exiting examples of waitUntilCondition and they were similar too. Strange thing is it's failing at null `condition`:
https://github.com/fabric8io/kubernetes-client/blob/3e4518a6181dd8b3abb4329ca59f910351128d5a/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/JobExample.java#L70

**Comment by HillebrandtOldenberg** [comment]
> @HillebrandtOldenberg : Which version of client are you using? Your usage seems fine to me. I checked some exiting examples of waitUntilCondition and they were similar too. Strange thing is it's failing at null `condition`:
> https://github.com/fabric8io/kubernetes-client/blob/3e4518a6181dd8b3abb4329ca59f910351128d5a/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/JobExample.java#L70

That would be 4.9.0.

**Comment by manusa** [comment]
Probably the field availableReplicas doesn't get populated in the server response.

Could you try with a null check (e.g. `Optional.ofNullable(deployment.getStatus()).map(DeploymentStatus::getAvailableReplicas).orElse(-1).equals(100)`) and see if the condition is met?

**Comment by HillebrandtOldenberg** [comment]
The `availableReplicas` field is indeed not populated; checked with `kubernetesClient.apps().deployments().inNamespace(testNamespace).withName(deploymentName).get().getStatus()`.

I don't understand how to implement your line of code. If I try:
`     kubernetesClient.apps().deployments().inNamespace(testNamespace).withName(deploymentName).waitUntilCondition(deployment -> Optional.ofNullable(deployment.getStatus()).map(DeploymentStatus::getAvailableReplicas).orElse(-1).equals(100));`

I get:
`Expected 3 arguments but found 1`

**Comment by HillebrandtOldenberg** [comment]
Isn't there a method that provides the same functionality as the command `kubectl rollout status deployment.v1.apps/hello-world` does?

**Comment by manusa** [comment]
> The `availableReplicas` field is indeed not populated; checked with `kubernetesClient.apps().deployments().inNamespace(testNamespace).withName(deploymentName).get().getStatus()`.
> 
> I don't understand how to implement your line of code. If I try:
> ` kubernetesClient.apps().deployments().inNamespace(testNamespace).withName(deploymentName).waitUntilCondition(deployment -> Optional.ofNullable(deployment.getStatus()).map(DeploymentStatus::getAvailableReplicas).orElse(-1).equals(100));`
> 
> I get:
> `Expected 3 arguments but found 1`
```
kubernetesClient.apps().deployments().inNamespace(testNamespace).withName(deploymentName).waitUntilCondition(deployment -> Optional.ofNullable(deployment.getStatus()).map(DeploymentStatus::getAvailableReplicas).orElse(-1).equals(100), 2, TimeUnit.MINUTES);
```
This line of code can also be written as (bascially nullchecking availableReplicas field):
```
kubernetesClient.apps().deployments().inNamespace(testNamespace).withName(deploymentName).waitUntilCondition(deployment -> Optional.ofNullable(deployment.getStatus() != null && deployment.getStatus().getAvailableReplicas() != null && deployment.getStatus().getAvailableReplicas().equals(100), 2, TimeUnit.MINUTES);
```

**Comment by HillebrandtOldenberg** [comment]
Yep, these commands work. Thank you very much :) Much appreciated!

But then, what is the difference between your null check and the `waitUntilReady` method?(`kubernetesClient.apps().deployments().inNamespace(namespaceName).withName(deploymentName).waitUntilReady(2, TimeUnit.MINUTES);`)

**Comment by manusa** [comment]
> Yep, these commands work. Thank you very much :) Much appreciated!
> 
> But then, what is the difference between your null check and the `waitUntilReady` method?(`kubernetesClient.apps().deployments().inNamespace(namespaceName).withName(deploymentName).waitUntilReady(2, TimeUnit.MINUTES);`)

The difference is that with your method you are waiting until a given (arbitrary) condition fulfills (hence `waitUntilCondition`), so in your case, that there are **exactly** 100 available replicas. This is a dynamic value, so even if the deployment exists, the condition will be checked every 500ms to verify if it returns true else it will retry until the timeout is reached (this is the base implementation for most of the resources).

https://github.com/fabric8io/kubernetes-client/blob/7ea72c87c0ea1325b46f45da7fb4e4602d198e89/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java#L1071-L1093

With the `waitUntilReady` method, you are checking for the existence of the resource (base implementation for most of the resources) and that the [resource is ready](https://github.com/fabric8io/kubernetes-client/blob/7ea72c87c0ea1325b46f45da7fb4e4602d198e89/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java#L61), so as soon as the resource exists in the cluster and that it has some replicas the condition will fulfill, regardless of the number of available replicas.

https://github.com/fabric8io/kubernetes-client/blob/7ea72c87c0ea1325b46f45da7fb4e4602d198e89/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java#L102-L118
