### ISSUE TITLE
provide an equilvalent to .get() which fails if the resource is missing with a meaningful error message describing the namespace/name/labels being filtered

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/kubernetes-client#213]
I like the default of say

```
kubernetes.replicationControllers().withName("cheese").get()
```

returning null if not found.

It would be nice to add a version of this which returns a non-null value or throws a meaningful exception.

e.g. if you do something like...

```
ReplicationController rc = kubernetes.replicationControllers().withName("cheese").require()
```

if `cheese` doesn't exist it would be nice to get some exception like `new ResourceNotFoundException("ReplicationController cheese is not found in default namespace")`.

It then avoids doing these kinds of assertions at a higher level. These are kinda handy when writing test cases etc

**Comment by iocanel** [comment]
Ooops! I accidentially closed this one!
