### ISSUE TITLE
Decouple openshift-model dependency from kubernetes-client

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#2141]
## Description
After model split (#2108 #2137) we have to keep a dependency to `openshift-model` in `kubernetes-client` as some of the classes still import OpenShift specific model types (`io.fabric8.openshift.api.model.*` e.g. `ClusterOperationsImpl`)

Classes with such imports should segregated with resulting classes moved to `openshift-client` module.

## Blocked by
- #2137

**Comment by rohanKanojia** [comment]
Actually earlier entire model was inside `kubernetes-model` jar. We didn't have much choice earlier, but I think after decoupling we can achieve this.
