### ISSUE TITLE
PropagationPolicy is ignored

### ISSUE THREAD

**Issue by Fabian-K** [fabric8io/kubernetes-client#2147]
Hi,

when setting a propagation policy for the delete operation this is ignored

```
client.resource(item).withPropagationPolicy("Foreground").delete()
```

Generated request:
```
--> DELETE https://127.0.0.1:32774/apis/sources.knative.dev/v1alpha1/namespaces/site/githubsources/github-source
Content-Type: application/json; charset=utf-8
Content-Length: 67

{"apiVersion":"v1","kind":"DeleteOptions","orphanDependents":false}
--> END DELETE (67-byte body)
```

PS: propagation policy not being propagated. Nice 🤪!

**Comment by rohanKanojia** [comment]
Umm, Need to check. Does it work with you use item with DSL? For example, `client.pods().inNamespace("foo").withName("some").withPropagationPolicy("Foreground").delete()`

I can see propagation policy being appended in code, but need to check whether control comes here when using generic resource API:
https://github.com/fabric8io/kubernetes-client/blob/16bd97fb010fad230ab7851d8e2b9286a739f38a/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java#L220-L227

**Comment by Fabian-K** [comment]
Currently tracing this... so far I found this where it is lost

https://github.com/fabric8io/kubernetes-client/blob/f70bb953d4b257a774b08a79ca6a3b94e206e9cf/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java#L162

**Comment by rohanKanojia** [comment]
Yeah, it then calls resource-specific handler which is a generated class

**Comment by rohanKanojia** [comment]
I think you would need to modify this

https://github.com/fabric8io/kubernetes-client/blob/f70bb953d4b257a774b08a79ca6a3b94e206e9cf/kubernetes-client/src/main/resources/resource-handler.vm#L100-L102

**Comment by Fabian-K** [comment]
Have it working locally. I´ll open a PR

**Comment by Fabian-K** [comment]
😏 applying this to the entire project is no fun, especially knative. IMO it makes more sense to first apply  https://github.com/fabric8io/kubernetes-client/pull/2134 to knative as well and then continue with this

**Comment by rohanKanojia** [comment]
#2178  should be able to fix this issue

**Comment by rohanKanojia** [comment]
#2178 is merged. I think we can close this
