### ISSUE TITLE
Tekton schema uses tekton_v1alpha2_ prefix for pipeline.v1beta1 

### ISSUE THREAD

**Issue by jeffmaury** [fabric8io/kubernetes-client#2148]

**Comment by rohanKanojia** [comment]
@Fabian-K recently submitted a PR for rewrite for tekton generator #2134 . I think that would cover this issue since he removed hardcoded schema names

**Comment by rohanKanojia** [comment]
#2134  has been merged. I think this issue can be closed.

**Comment by Fabian-K** [comment]
Hi @jeffmaury what prefix do you refer to?

**Comment by jeffmaury** [comment]
The one in the generated schema

**Comment by Fabian-K** [comment]
This one? https://github.com/fabric8io/kubernetes-client/blob/v4.9.1/extensions/tekton/model/src/main/resources/schema/tekton-schema.json#L3611

If yes, that is only an internal reference that should not surface in any way to clients using the library. Do you face any issues with this?

**Comment by jeffmaury** [comment]
It's confusing for people (like me) wanted to reuse the generated schema
