### ISSUE TITLE
TektonMockServer: get fails for v1alpha1, works for v1beta1

### ISSUE THREAD

**Issue by Fabian-K** [fabric8io/kubernetes-client#2158]
Hi,

I´m facing a strange issue with the TektonServer mock. When I create a taskrun and try to get it afterwards, the TektonServer returns 404. This works when using v1beta1. It also works (for both v1beta1 and v1alpha1 when not getting the single task run but instead listing all taskruns.

This is using a local build of master. Any idea what is going on ?! 😲

Code:

````
tkn.v1alpha1().taskRuns().create(
        io.fabric8.tekton.pipeline.v1alpha1.TaskRunBuilder()
                .withNewMetadata().withName("run")
                .endMetadata()
                .build()
)
assertThat(tkn.v1alpha1().taskRuns().withName("run").get()).isNotNull
````

Logs:
````
// CREATE
INFORMATION: MockWebServer[54885] starting to accept connections
[Test worker] WARN io.fabric8.kubernetes.client.internal.VersionUsageUtils - The client is using resource type 'taskruns' with unstable version 'v1alpha1'
--> POST https://localhost:54885/apis/tekton.dev/v1alpha1/namespaces/test/taskruns
Content-Type: application/json; charset=utf-8
Content-Length: 79

{"apiVersion":"tekton.dev/v1alpha1","kind":"TaskRun","metadata":{"name":"run"}}
--> END POST (79-byte body)
INFORMATION: MockWebServer[54885] received request: POST /apis/tekton.dev/v1alpha1/namespaces/test/taskruns HTTP/1.1 and responded: HTTP/1.1 202 OK
<-- 202 OK https://localhost:54885/apis/tekton.dev/v1alpha1/namespaces/test/taskruns (112ms)
Content-Length: 79

{"apiVersion":"tekton.dev/v1alpha1","kind":"TaskRun","metadata":{"name":"run"}}
<-- END HTTP (79-byte body)

// GET
--> GET https://localhost:54885/apis/tekton.dev/v1alpha1/namespaces/test/taskruns/run
--> END GET
<-- 404 Client Error https://localhost:54885/apis/tekton.dev/v1alpha1/namespaces/test/taskruns/run (3ms)
Content-Length: 0
<-- END HTTP (0-byte body)
INFORMATION: MockWebServer[54885] received request: GET /apis/tekton.dev/v1alpha1/namespaces/test/taskruns/run HTTP/1.1 and responded: HTTP/1.1 404 Client Error
````

**Comment by rohanKanojia** [comment]
Umm, strange. There is a test for `v1alpha1` in mockwebserver:

https://github.com/fabric8io/kubernetes-client/blob/master/extensions/tekton/tests/src/test/java/io/fabric8/tekton/test/crud/V1alpha1PipelineCrudTest.java

**Comment by rohanKanojia** [comment]
Are you facing this issue in real server too?

**Comment by rohanKanojia** [comment]
@Fabian-K : Shall we close this issue?

**Comment by Fabian-K** [comment]
Yes, this is now resolved in master :)

**Comment by rohanKanojia** [comment]
@Fabian-K : We have released a new version of Fabric8 Kubernetes client which contains your fix for this. See twitter announcement[0]. Thanks a lot for your work on these extensions. Bdw, Did we get your Twitter username right? 

[0] https://twitter.com/fabric8io/status/1257266173005254656

**Comment by Fabian-K** [comment]
Awesome, thanks for this! 🤩 Updating the dependencies in my projects now... :)
