### ISSUE TITLE
Dose any method to set resourceVersion in list options?

### ISSUE THREAD

**Issue by allwmh** [fabric8io/kubernetes-client#2165]
Dose any method to set resourceVersion in list options that we can query result from apiserver just from apiserver cache?

In our case, we dost not use the k8s recommend style(list + watch cache the resource in client informer cache), we use list resource from apiserver period, that not with resourceVersion "0", so that apiserver will send request to etcd, that way give big pressure to apiserver, the apiserver's memory increase very fast. So a method to set resourceVersion in list options is very important.

**Comment by rohanKanojia** [comment]
@allwmh : Hi, I've created a PR to support this:
```
client.services().inNamespace("myproject").list(new ListOptionsBuilder()
  .withLimit(1L)
  .withContinue(null)
  .build());
```

Were you talking about list in regular operations or in our SharedInformer API too?

**Comment by allwmh** [comment]
3ks

**Comment by rohanKanojia** [comment]
@allwmh : Could you please try it out on v4.10.1 and provide feedback?
