### ISSUE TITLE
How to use patch on custom resources?

### ISSUE THREAD

**Issue by csviri** [fabric8io/kubernetes-client#2166]
Hi,
I would like to add / delete some attributes using patch on custom resources. However its not clear to me how this should work using current API. (In my case I would like to add a finalizer)  
This is the API I try to use
```java
MyCustomResource resource = createMyCustomResourcePatchPojo() ;
MixedOperation  resourceOperation = .... ; 
resourceOperation.inNamespace(resource.getMetadata().getNamespace())
   .withName(resource.getMetadata().getName())
   .patch(resource);
```
I assume this should be then a merge patch like defined here:
https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/#use-a-json-merge-patch-to-update-a-deployment

And in this RFC: https://tools.ietf.org/html/rfc7386

Does this mean that I should only set values that will be added / altered in the custom resource POJO? And other values should be null? But then how should I delete a field? 

Thanks!

(also Is there a way to use similar to [Json-P](https://javaee.github.io/jsonp/)  ?)

**Comment by rohanKanojia** [comment]
I think you can try `createOrReplace()` here is an example:
https://github.com/fabric8io/kubernetes-client/blob/a97aeb90b2c8f0a1e3623429d59101d98912f6e4/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/TypedCustomResourceApiTest.java#L92-L94

**Comment by rohanKanojia** [comment]
We have a typeless api also with which you can use plain json/HashMap to deal with Custom Resources: https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#customresource-typeless-api

**Comment by csviri** [comment]
@rohanKanojia the `createOrReplace` is what I want to avoid, since its not a patch. It could lead to "lost update problem" if I don't use optimistic locking (e.e. lock version) - what I want to also avoid here.

But will check the typeless api, thank you!

**Comment by janotav** [comment]
@csviri have you managed to figure out how to safely patch using this library?

**Comment by csviri** [comment]
@janotav no. (We took other appraoch for unrelated reasons.)
