### ISSUE TITLE
Can't close a watch

### ISSUE THREAD

**Issue by MartinPodval** [fabric8io/kubernetes-client#217]
I continue in solving of the problem which is described in #205. It's not possible to close a watch because it discard client's internal `ThreadPoolExecutor`, see #205 for all details.

The original fix is still not working as `OkHttpClient` 's `clone` method does shall copy so the cloned instance shares the same `ThreadPoolExecutor`. Thus, closing one of these two client instances causes that the second one is discarded as well.

However, it needs some conceptual solution. I mean my code is following:

```java
client.endpoints().withLabels(labels).watch(watcher)
```

In fact, the `watch` method now clones `client`. This is tricky.

My current workaroud is to create a new client always when I need to watch something. Actually, IMHO this is probably the best solution. But how can a user find it out that this is the correct way how to do a watching?

**Comment by jimmidyson** [comment]
Thanks for the report.

I have fixed the `close` functionality last night to not discard the `ThreadPoolExecutor` on `watch.close()`. See #216 for details. Thread pool is only closed on actual client close.

I originally misunderstood the functionality of `OkHttpClient`'s `clone` method as you described above.

Hopefully in next release you shouldn't have to create a new client every time.
