### ISSUE TITLE
[Feature] Support BOOKMARK events

### ISSUE THREAD

**Issue by webskin** [fabric8io/kubernetes-client#2171]
Kubernetes Server API is able to send regulary BOOKMARK events :

https://kubernetes.io/docs/reference/using-api/api-concepts/#watch-bookmarks

We could imagine that :

```java
client.namespaces()
  .withResourceVersion(resourceVersion)
  .watch(allowBookmarks, watcher)
``` 

And may be also an option to automatically restart a watch from a Bookmark if it is the last received event.

```java
client.namespaces()
  .withResourceVersion(resourceVersion)
  .watch(allowBookmarks, autoRestartWatchFromBookmarkOn410, watcher)
``` 

```java
        class KubernetesObjectWatcher implements Watcher<Namespace> {

            @Override
            public void eventReceived(Action action, Namespace kubernetesObject) {
                if (action.equals(Action.BOOKMARK)) {
                  // Do some action like storing Resource Version found in kubernetesObject
                }
            }

            @Override
            public void onClose(KubernetesClientException e) {
              ...
            }
        }
```

Exemple in the GO client :  

https://github.com/kubernetes/client-go/blob/ce0298a60b3c4651540b2beaf8f9e98a871ab2a3/tools/cache/reflector.go

https://github.com/kubernetes/client-go/blob/ce0298a60b3c4651540b2beaf8f9e98a871ab2a3/tools/cache/reflector.go#L479

https://github.com/kubernetes/client-go/blob/ce0298a60b3c4651540b2beaf8f9e98a871ab2a3/tools/cache/reflector.go#L517

https://github.com/kubernetes/client-go/blob/ce0298a60b3c4651540b2beaf8f9e98a871ab2a3/tools/cache/reflector.go#L266

**Comment by webskin** [comment]
Any news ?

**Comment by rohanKanojia** [comment]
Sorry for late reply, We have taken this issue in our current sprint: https://github.com/eclipse/jkube/projects/23

**Comment by joyliu329** [comment]
any news for :


11.26.98.32
1628138594
logback
__tag__:__client_ip__:106.11.218.18
level:ERROR
location:io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onMessage(AbstractWatchManager.java:256)
message:Invalid event type
thread:OkHttp https://11.186.78.31:6443/...
throwable:java.lang.IllegalArgumentException: No enum constant io.fabric8.kubernetes.client.Watcher.Action.BOOKMARK
	at java.lang.Enum.valueOf(Enum.java:238)
	at io.fabric8.kubernetes.client.Watcher$Action.valueOf(Watcher.java:46)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onMessage(AbstractWatchManager.java:233)
	at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.onMessage(WatcherWebSocketListener.java:93)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:322)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:621)
	at java.lang.Thread.run(Thread.java:849)

**Comment by rohanKanojia** [comment]
Sorry, we haven't been able to deliver it in the previous sprint due to some other priorities. We'll be happy to integrate a PR for this in case anyone is interested.

**Comment by laxmikantbpandhare** [comment]
assign - @laxmikantbpandhare

**Comment by rohanKanojia** [comment]
I think we need to add BOOKMARK field to this enum to get rid of this IllegalArgumentException:
https://github.com/fabric8io/kubernetes-client/blob/7e747ca61c0097562622eb53b9f008cc6d5e82fb/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Watcher.java#L46-L48

We also need to check if the current implementation supports allowing watch bookmarks via `watch(ListOptions, Watcher<T>)` implementation. If it doesn't support it, we need to make changes for it to work.

a DSL method `.allowWatchBookmarks()` can be added as well which will set `allowWatchBookmarks=true` in watch list options
