### ISSUE TITLE
persistentVolumeClaim.getSpec().getStorageClassName() returns null

### ISSUE THREAD

**Issue by HillebrandtOldenberg** [fabric8io/kubernetes-client#2172]
Given a PVC:
```
PersistentVolumeClaim persistentVolumeClaim =
    new PersistentVolumeClaimBuilder()
        .withNewMetadata()
        .withName("pvc-with-no-class-specification")
        .withNamespace(namespaceName)
        .endMetadata()
        .withNewSpec()
        .withAccessModes("ReadWriteOnce")
        .withNewResources()
        .addToRequests("storage", new Quantity("3Gi"))
        .endResources()
        .endSpec()
        .build();
kubernetesClient
    .persistentVolumeClaims()
    .inNamespace(namespaceName)
    .createOrReplace(persistentVolumeClaim);

LOGGER.info(
    "Creating '"
        + persistentVolumeClaim.getMetadata().getName()
        + "' PersistentVolumeClaim ...");
try {
  Thread.sleep(20 * 1000);
} catch (InterruptedException e) {
  e.printStackTrace();
}
LOGGER.info(
    "Created '" + persistentVolumeClaim.getMetadata().getName() + "' PersistentVolumeClaim");
```

Requesting its storage class name using the object will return `null`:
```
System.err.println(
    "storage class name: " + persistentVolumeClaim.getSpec().getStorageClassName());
```

But using the kubernetesClient (on which, I assume, is the exact same resource), will return the expected result:
```
LOGGER.info(
    "storage class name2: "
        + kubernetesClient
            .persistentVolumeClaims()
            .inNamespace(namespaceName)
            .withName(persistentVolumeClaim.getMetadata().getName())
            .get()
            .getSpec()
            .getStorageClassName());
```

I use k8s v.1.18, so the `DefaultStorageClass` admission controller is enabled by default, which should assign the default storage class in `namespaceName` to the `persistentVolumeClaim`.

**Comment by rohanKanojia** [comment]
Umm, I think difference between both is that you're requesting resource from apiserver in latter case. So it fetches object from apiserver after creation(I think kubernetes apiserver handles assignment of `StorageClass` upon creation).

When using builder it's not set since you have to post your object to apiserver and that field hasn't been populated yet.

**Comment by rohanKanojia** [comment]
@HillebrandtOldenberg: Polite ping, Were you able to find time to revisit this?

**Comment by HillebrandtOldenberg** [comment]
Yep, your explanation was the answer, forgot to close :)
