### ISSUE TITLE
Support for multiple values in KUBECONFIG variable

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#2174]
We need to check how the client is handling the case when `KUBECONFIG` variable has multiple values. If present, we should print a warning about which `kubeconfig` did we read for client operations.

Orignal issue: https://github.com/quarkusio/quarkus/issues/8946

**Comment by rohanKanojia** [comment]
@manusa @iocanel : I checked and looks like multiple values are already being handled:

https://github.com/fabric8io/kubernetes-client/blob/2f857a9f74c8f21c7dbc6637a40292763bb8cfee/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L469-L483

**Comment by manusa** [comment]
:smile:

So basically to fulfill the AC defined in my [comment](https://github.com/quarkusio/quarkus/issues/8946#issuecomment-621144866) we just need to change the log level.
