### ISSUE TITLE
Reuse http client when adapting client

### ISSUE THREAD

**Issue by jimmidyson** [fabric8io/kubernetes-client#218]
Currently when we adapt a client to e.g. `OpenShiftClient` we create a new instance of `OkHttpClient`. This creates a separate `ThreadPoolExecutor` which may be wasteful considering the client is using the same config to create the `OkHttpClient` instance.

One intricacy to deal with if we do this is making sure we don't close the underlying `ThreadPoolExecutor` until every client using it is closed. Could get tricky.

Thoughts @iocanel?

**Comment by iocanel** [comment]
@jimmidyson: You are going to love it !!!

The main reason why the adapt method doesn't reuse the same client, is that it doesn't have visibility to it.

**Comment by jimmidyson** [comment]
Sort it out! ;)

**Comment by iocanel** [comment]
return new DefaultOpenShiftClient(client.adapt(OkHttpClient.class), OpenShiftConfig.wrap(client.getConfiguration()));

**Comment by jimmidyson** [comment]
That'll work...

How to deal with not closing the thread pool until we're really done with it?

**Comment by jimmidyson** [comment]
Complete!
