### ISSUE TITLE
KubernetesClient#customResources takes CustomResourceDefinition, when CustomResourceDefinitionContext would suffice

### ISSUE THREAD

**Issue by bbeaudreault** [fabric8io/kubernetes-client#2199]
As you can see in [KubernetesClient.java#L112](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java#L112), in order to query for custom resources you need to provide a full `CustomResourceDefinition` object. However, in [CustomResourceOperationsImpl.java#L54-L71](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CustomResourceOperationsImpl.java#L54-L71), you really only use the `crd.spec.group`, `crd.spec.version`, `crd.spec.names.kind`, `crd.spec.scope`, `crd.spec.names.plural`. These are all available in [CustomResourceDefinitionContext.java](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/CustomResourceDefinitionContext.java).

`CustomResourceDefinition`s may have started out simple, but have grown complex with openapi spec validations, defaulting, etc. From an API perspective, it's confusing to expect a full CRD to be passed in here. If one doesn't have access to the full spec, one might feel obligated to fetch it from kubernetes before calling the functions. Slimming the requirements down to just CustomResourceDefinitionContext would reduce the ambiguity in the interface and be simpler to build anyway.

Thoughts? Some other functions in KubernetesClient already take a CustomResourceDefinitionContext, for example the raw custom resource operations function.

**Comment by rohanKanojia** [comment]
@bbeaudreault : Nice catch, I think it's a good idea to replace full `CustomResourceDefinition` with CRDContext :+1:
