### ISSUE TITLE
Suppress "Trying to configure client from Kubernetes config..." message

### ISSUE THREAD

**Issue by HillebrandtOldenberg** [fabric8io/kubernetes-client#2200]
Is there a way to suppress the following messages?

```
06:16:07.014 [main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client from Kubernetes config...
06:16:07.014 [main] DEBUG io.fabric8.kubernetes.client.Config - Found for Kubernetes config at: [<file path>].
```

Since it is advised to create a new client in every method, at least, from what I get from the [examples](https://github.com/fabric8io/kubernetes-client/tree/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples) and the [CHEATSHEET.md](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md), these two messages repeat a lot.

**Comment by rohanKanojia** [comment]
I think this problem can be easily tackled by configuring your application's log level.
