### ISSUE TITLE
BaseOperation#waitUntilCondition never fetches state from server

### ISSUE THREAD

**Issue by bbeaudreault** [fabric8io/kubernetes-client#2204]
https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java#L1104-L1126

waitUntilCondition calls `get()`, which does not actually get anything from the server. So the condition will never succeed. The next method up is waitForReady, which calls `fromServer().get()`, which _does_ work as expected. These two methods should likely be refactored so that waitForReady simply calls waitForCondition.

Additionally, the current approach of polling every 500ms is relatively abusive of the kubernetes API servers. Imagine if you had a bunch of clients all doing that in a cluster. It probably makes sense for these functions to use a Watch instead, or at the very least backoff on some schedule.

**Comment by rohanKanojia** [comment]
@bbeaudreault: Hi, Sorry for late reply. We would be happy to integrate a PR to fix this issue. Could you please create a PR for this whenever you get some time?

**Comment by bbeaudreault** [comment]
No worries. I am planning to try updating our internal fork to use a watcher here instead. I'll report back progress here as I have it, and submit a PR if it looks good. It might be a bit before I can get to this work, but I think it'd be a good improvement to have.
