### ISSUE TITLE
Event model classes from core/v1 have been lost

### ISSUE THREAD

**Issue by cheinema** [fabric8io/kubernetes-client#2205]
Since #2137 (v1.10.0) the model classes
- `io.fabric8.kubernetes.api.model.Event`
- `io.fabric8.kubernetes.api.model.EventList`
- `io.fabric8.kubernetes.api.model.EventSeries`

from the `core/v1` API are missing. They were included in `kubernetes-model-4.9.1.jar`, but are now missing in `kubernetes-model-core-4.10.0.jar`.

**Comment by rohanKanojia** [comment]
They are in https://repo1.maven.org/maven2/io/fabric8/kubernetes-model-events/4.10.1/

**Comment by cheinema** [comment]
Nope, these are the model classes of the (deprecated) `events/v1beta1`. They are not compatible with each other.

See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#event-v1-core vs.
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#event-v1beta1-events-k8s-io

They can also be distinguished by `kubernetes_core_Event` and `kubernetes_events_Event` in `kube-schema.json`.

**Comment by rohanKanojia** [comment]
ah, I see. Apologies for inconvenience. Let me add them back.

**Comment by cheinema** [comment]
@rohanKanojia Can you please take a look at `KubernetesClient#events`? Due to #2137 the import statements of the event classes have been changed ([diff](https://github.com/fabric8io/kubernetes-client/pull/2137/files#diff-3a558b08b1868fb2a61929295164c19d)). In my oppinion they must be switched back to `io.fabric8.kubernetes.api.model.*`.

**Comment by rohanKanojia** [comment]
Actually, I moved core events to `client.v1().events()`

**Comment by cheinema** [comment]
Ahh, I see. Thank you for the hint.

**Comment by rohanKanojia** [comment]
@cheinema : Do you know if `events/v1beta1` is used anywhere?

**Comment by manusa** [comment]
`client.events()` should be reverted to call the API version that was called previously (i.e. `v1`), in order to avoid breaking backwards compatibility.

As a way to move forward, the method should be annotated with Deprecated and a JavaDoc line added indicating the recommended new approach `client.v1().events()`.

**Comment by rohanKanojia** [comment]
@manusa @cheinema : I will update #2206 to have `client.events()` using `v1` Events. Thanks for your feedback.
