### ISSUE TITLE
How deleting a deployment in fabric8 kubernetes-client works?

### ISSUE THREAD

**Issue by wangyang0918** [fabric8io/kubernetes-client#2209]
In Flink project, we are using the following code to delete a deployment. We start a Flink master deployment in the K8s cluster and it will call the  `stopAndCleanupCluster` when all jobs finished. However, we find that it could not work and have a high probability the deployment could not be deleted, instead the replication has decreased to 0.

So when delete a deployment via fabric8 kubernetes-client, does it decrease the replication to 0 first? And then delete the deployment and replicationset. Right?

I really appreciate for your help and any suggestion.

```
	public void stopAndCleanupCluster(String clusterId) {
		this.internalClient
			.apps()
			.deployments()
			.inNamespace(this.nameSpace)
			.withName(KubernetesUtils.getDeploymentName(clusterId))
			.cascading(true)
			.delete();
	}
```

**Comment by rohanKanojia** [comment]
`cacading()` has been marked as deprecated. Please use `withPropagationPolicy()` instead

**Comment by wangyang0918** [comment]
@rohanKanojia Thanks a lot for your quick response. Do you mean `withPropagationPolicy` set to `Foreground` could solve this problem?

If the deleting deployment is not a one-step operation, then it might be not be executed completely, especially we do this in the deployment itself.

**Comment by rohanKanojia** [comment]
I think `cascading(true)` should also be able to delete `Deployment` and its dependents. It sets `orphanDependents` fields to `false` in [`DeleteOptions`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#deleteoptions-v1-meta). 

But I would suggest you should set using `withPropagationPolicy` set to `Foreground` or `Background` for deletion operations

**Comment by wangyang0918** [comment]
@rohanKanojia So do you mean the deleting deployment only send one http request to K8s apiserver? If not, it might not be executed completely.

**Comment by rohanKanojia** [comment]
Yes, deletion is just an API request to Kubernetes APIServer

**Comment by wangyang0918** [comment]
Thanks a lot. It is really strange that the deployment is not deleted. And the replication has been set to 0 instead.

**Comment by rohanKanojia** [comment]
Which version are you using?

**Comment by zhengcanbin** [comment]
> Yes, deletion is just an API request to Kubernetes APIServer

The Flink community is using V4.5.2, that is not a one step request

**Comment by rohanKanojia** [comment]
Umm, that's pretty old version. Could you please try on v4.9.0 or v4.9.1 instead?

**Comment by rohanKanojia** [comment]
@wangyang0918: I'm not sure if LeaderElection support is there in 4.5.2. I remember you once requested it and our team added it. Are you not using it?

**Comment by zhengcanbin** [comment]
> Umm, that's pretty old version. Could you please try on v4.9.0 or v4.9.1 instead?

@rohanKanojia I notice the latest version is v4.10.1, is it safe that we use it in production?

**Comment by rohanKanojia** [comment]
ah, We recently split the Kubernetes Model into smaller jars per apiVersion in #2137 . But it has introduced some regressions #2195, #2201 and #2205 

If you're not affected by these bugs, you can upgrade. We have plans on fixing them and then cutting a stable release.

**Comment by zhengcanbin** [comment]
> ah, We recently split the Kubernetes Model into smaller jars per apiVersion in #2137 . But it has introduced some regressions #2195, #2201 and #2205
> 
> If you're not affected by these bugs, you can upgrade. We have plans on fixing them and then cutting a stable release.

Got it. Thank you @rohanKanojia!

**Comment by wangyang0918** [comment]
Bumping the version to 4.9.1 could fix our problem. @rohanKanojia Thanks a lot for you help.
