### ISSUE TITLE
Uberjar: Package rewrite issues in META-INF/services

### ISSUE THREAD

**Issue by cheinema** [fabric8io/kubernetes-client#2218]
Since #2137 (v1.10.0) not all references in `META-INF/services/io.fabric8.kubernetes.clnt.v4_10.ResourceHandler` contained in the Uberjar `kubernetes-openshift-uberjar-4.10.0-versioned.jar` are rewritten to the versioned package notation.

**Comment by rohanKanojia** [comment]
I think https://github.com/fabric8io/kubernetes-client/pull/2203 should take care of this. Do you see this issue on master SNAPSHOT as well?

**Comment by rohanKanojia** [comment]
Umm, yeah. The issue is still there in the master as well :-(
