### ISSUE TITLE
how can i deploy jar to my nexus

### ISSUE THREAD

**Issue by phantooom** [fabric8io/kubernetes-client#2220]
i change some code & build jar. but how can i deploy it to nexus.

[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy (injected-nexus-deploy) on project kubernetes-client-bom: Execution injected-nexus-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy failed: Nexus connection problem to URL [my nexust url ]: 404 - Not Found -> [Help 1]

my other project use this url and run mvn deploy  works.

**Comment by rohanKanojia** [comment]
@phantooom : polite ping, Is this still an issue? Looks like some misconfiguration on your side. Could you please check and report back?
