### ISSUE TITLE
list pods of service

### ISSUE THREAD

**Issue by 1542254356** [fabric8io/kubernetes-client#2230]
Is it correct to list pods of service 
```
client.pods().inNamespace(namespace)
                .withLabel("run="+service)
                .list().getItems();
```

**Comment by rohanKanojia** [comment]
@1542254356 : Hi, Sorry for late response. Maybe you already figured it out... But I think you should list with labels like this:
```
PodList podList = client.pods().inNamespace(namespace)
                .withLabel("run", service)
                .list();
```

**Comment by rohanKanojia** [comment]
@1542254356: polite ping, Is this still an issue? Could you please provide some update on this?
