### ISSUE TITLE
Unable to get a service url

### ISSUE THREAD

**Issue by sjmittal** [fabric8io/kubernetes-client#2233]
Hi,
I am following the example as listed here:
https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ServiceExample.java

My service is described as:
```
Name:              objectstore-service
Namespace:         objectstore-runtime
Labels:            <none>
Annotations:       <none>
Selector:          app=objectstore
Type:              ClusterIP
IP:                10.106.97.40
Port:              http-minio  9000/TCP
TargetPort:        9000/TCP
Endpoints:         172.18.0.7:9000
Session Affinity:  None
Events:            <none>
```

However when I try:
`kubernetesClient.services().inNamespace("objectstore-runtime").withName("objectstore-service").getURL("http-minio")`

I get `null`.

Is there any thing I am missing here.
Does the url depend on type of service and there is some other way to get the url for service of type `ClusterIP`.

Thanks
Sachin

**Comment by rohanKanojia** [comment]
Yeah, you're right. I think we are missing a  Service implementation for type `ClusterIP` :-( . These all services are loaded by `ServiceLoader` here:
https://github.com/fabric8io/kubernetes-client/blob/cc916a2bd5a55c03a666ed1c6f6a3a409cde06e0/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ServiceOperationsImpl.java#L122-L132

I think we need to provide it like we're doing for NodePort:
https://github.com/fabric8io/kubernetes-client/blob/cc916a2bd5a55c03a666ed1c6f6a3a409cde06e0/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/URLFromNodePortImpl.java#L27-L49

**Comment by sjmittal** [comment]
I did check the implementation, however I am not able to find any class that gives the `clusterIp` field's value in the service status object.
I am talking about this field's value when we describe a service via `kubectl`.
`IP:                10.106.97.40`

Any ideas?

**Comment by rohanKanojia** [comment]
I think I misunderstood your problem, you just want `ClusterIP` field. You can access it like :
```
String clusterIPSvc = kubernetesClient.services()
  .inNamespace("objectstore-runtime")
  .withName("objectstore-service")
  .get()
  .getSpec().getClusterIP();
```

**Comment by sjmittal** [comment]
Yes this works.
I feel `service.getURL("port-name")` should also include urls based on `<clusterIP>:<targetPort>` or `<clusterIP>:<port>` for atleast services of type `ClusterIP`.
I suppose we may need to add a class:
```
public class URLFromServiceClusterIPImpl implements ServiceToURLProvider { 
...
}
```
which fetches these urls.
