### ISSUE TITLE
Compatibility with GKE workload identity

### ISSUE THREAD

**Issue by tchiotludo** [fabric8io/kubernetes-client#2240]
I am not really sure of that, but I've the feeling the client is not compatible with special [workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) for gke. 

I don't see any occurence on `http://metadata.google.internal`, the metadata server used by google to distribute the access token for a GKE with workload identity.

Is this something that you want to support or not ?

**Comment by rohanKanojia** [comment]
@tchiotludo: Hi, right now we don't have access to GKE cluster in order to test client. Would appreciate if you could try it out and contribute some documentation/compatibility matrix related to it.
