### ISSUE TITLE
QuantityBuilder#withAmount doesn't respect the unit anymore

### ISSUE THREAD

**Issue by jahstreet** [fabric8io/kubernetes-client#2242]
After the client `v4.7.0` release `QuantityBuilder` no longer respects the unit passed with the `withAmount` method (which seems to be caused by https://github.com/fabric8io/kubernetes-client/pull/1921).

For the following statement:
```
new QuantityBuilder(false).withAmount("256Mi").build()
```
now simply drops the unit suffix, which has not been so in the previous versions.
Now the same statement should look like this:
```
new QuantityBuilder(false).withAmount("256").withFormat("Mi").build()
```

Is it expected to be changed so or it is a bug?
This is a breaking change, so are there any plans to fix that to support the backwards compatible behaviour?

**Comment by venkatakarunakar** [comment]
Thank you @jahstreet. This fixed the memory unit conversion.
