### ISSUE TITLE
Why does the Client receives an Modified on Delete?

### ISSUE THREAD

**Issue by bframke** [fabric8io/kubernetes-client#2245]
We are currently having a problem in understanding something, when we add a Resource via a Rest Interface and save it to a cache and create a custom resource from it, it works fine and does no additional step to do anything.

When we delete the CR the Watcher receives an Delete and it also gets deleted from cache. When we delete it via the Rest Interface we first remove it out of the cache and then the Resource from Kubernetes. While doing that the Watcher receives a Modified Event and directly after that a Delete Event.

Somehow the Kubernetes sends a Modified Event, if I'am understanding it correctly or is there something else happening there? Because it does not make any sense to have a Modified Event on Delete.

**Comment by bframke** [comment]
With the usage of the ReflectorWatcher with the InformerAPI this is no longer happening.

**Comment by rohanKanojia** [comment]
@bframke Umm, I don't understand your problem. Could you please elaborate? How did you manage to use ReflectorWatcher directly?

**Comment by bframke** [comment]
We did not use the ReflectorWatcher directly, after we were sure that the normal Watcher is having problems (maybe a sync problem between the resourceVersions), because of alot of code changes we did on that part, we tried to find a solution and stumbled upon this article https://medium.com/@rohaan/introduction-to-fabric8-kubernetes-java-client-informer-api-b945082d69af and used this approach with the InformerAPI and ReflectorWatcher and so far it works fine.
