### ISSUE TITLE
Question: Why the latest release has decreased minor version?

### ISSUE THREAD

**Issue by stanlyDoge** [fabric8io/kubernetes-client#2248]
Is there any specific reason?

**Comment by rohanKanojia** [comment]
@stanlyDoge : Not sure whether I understand your question or not. Are you saying about moving from 4.9.x to 4.10.x ?

**Comment by manusa** [comment]
The most recent release is [4.9.2](https://github.com/fabric8io/kubernetes-client/releases/tag/v4.9.2) which contains a much demanded patch.

The [latest version](https://repo1.maven.org/maven2/io/fabric8/kubernetes-client/maven-metadata.xml) is 4.10.1 which contains [new features and improvements](https://github.com/fabric8io/kubernetes-client/compare/v4.9.2...v4.10.1) not included in 4.9.2.
![image](https://user-images.githubusercontent.com/488391/82888799-165fe100-9f4a-11ea-9932-8fafde78e5c8.png)
![image](https://user-images.githubusercontent.com/488391/82889124-90906580-9f4a-11ea-962e-e539a1c478f0.png)
![image](https://user-images.githubusercontent.com/488391/82889161-9e45eb00-9f4a-11ea-87ab-138b2e8def6f.png)

**Comment by stanlyDoge** [comment]
@manusa thanks for explanation! :)
