### ISSUE TITLE
KubernetesClientException when using ribbon loadbalancing

### ISSUE THREAD

**Issue by janakec19** [fabric8io/kubernetes-client#2250]
I am trying to communicate from microservice in one project (demo1-oci-dev) tomicroservice in other project(demo2-oci-dev) in openshift .
Using , Spring cloud kubernetes , feign client for communication.
Getting below exception,  Can anyone please help me to resolve this issue.

Error creating bean with name 'ribbonLoadBalancingHttpClient' defined in org.springframework.cloud.netflix.ribbon.apache.HttpClientRibbonConfiguration: Unsatisfied dependency expressed through method 'ribbonLoadBalancingHttpClient' parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ribbonLoadBalancer' defined in org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.loadbalancer.ILoadBalancer]: Factory method 'ribbonLoadBalancer' threw exception; nested exception is io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://xx.xxx.x.x/api/v1/namespaces/demo1-oci-dev/endpoints/demo2.demo2-oci-dev. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. endpoints "demo2.demo2-oci-dev" is forbidden: User "system:serviceaccount:demo1-oci-dev:default" cannot get endpoints in the namespace "demo1-oci-dev": no RBAC policy matched.

**Comment by rohanKanojia** [comment]
> Forbidden!Configured service account doesn't have access. Service account may have been revoked. endpoints "demo2.demo2-oci-dev" is forbidden: User "system:serviceaccount:demo1-oci-dev:default" cannot get endpoints in the namespace "demo1-oci-dev": no RBAC policy matched.

Looks like a permissions issue. Are you sure your `ServiceAccount` has correct permissions? If not could you please allocate it using this command:
```
oc create clusterrolebinding default-pod --clusterrole cluster-admin --serviceaccount=<namespace>:demo1-oci-dev
```
