### ISSUE TITLE
ClassCastException NetworkPolicy

### ISSUE THREAD

**Issue by nbn** [fabric8io/kubernetes-client#2251]
Hi, trying to add a network policy on an openshift client cause me some problems

Having a policy in a yaml file:

    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
        name: some-name
    spec:
       xxxx

And trying to read the file using the client.load(..).get() method, gives me this error:

    java.lang.ClassCastException: io.fabric8.kubernetes.api.model.extensions.NetworkPolicy cannot be cast to io.fabric8.kubernetes.api.model.networking.NetworkPolicy
    at io.fabric8.kubernetes.client.handlers.networking.v1.NetworkPolicyHandler.edit(NetworkPolicyHandler.java:40)
    at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.acceptVisitors(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:332)
    at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.get(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:324)
    at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.get(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:65)

Not sure why there seems to be two implementations api.model.networking and api.model.extensions, 

I use kubernetes-client and openshift-client in version 4.10.0

**Comment by rohanKanojia** [comment]
Does it work when you use `client.network().networkPolicies().load("...")`?

**Comment by nbn** [comment]
Yes it does. I have taken the time this morning to create these two tests. Loading the network policy directly is ok, but loading as part of a list fails.

    @Test
    public void canLoadNetworkPolicy() {
        InputStream resourceAsStream = NetworkPolicyLoadBugTest.class.getResourceAsStream("/network/allow-namespace.yaml");
        DefaultOpenShiftClient client = new DefaultOpenShiftClient();
        NetworkPolicy policy = client.network().networkPolicies().load(resourceAsStream).get();
        Assert.assertEquals("allow-from-another-namespace", policy.getMetadata().getName());
    }
    
    @Test
    public void canLoadListWithNetworkPolicy(){
        InputStream resourceAsStream = NetworkPolicyLoadBugTest.class.getResourceAsStream("/network/allow-namespace.yaml");
        DefaultOpenShiftClient client = new DefaultOpenShiftClient();
        List<HasMetadata> itemsList = client.load(resourceAsStream).get();
        Assert.assertEquals(1, itemsList.size());
    }

I have some time at hand and will see what I can find in a debugger, but what is the semantic difference between those two classes?

**Comment by nbn** [comment]
Boiled it down to the serialization. Where the `client.network().networkPolicies().load(...)` sets the base type, the `client.load(...)` does not.

    @Test
    public void serializationWithType() {
        InputStream resourceAsStream = NetworkPolicyLoadBugTest.class.getResourceAsStream("/network/allow-namespace.yaml");
        Object unmarshal = Serialization.unmarshal(resourceAsStream, io.fabric8.kubernetes.api.model.networking.NetworkPolicy.class);
        Assert.assertEquals(io.fabric8.kubernetes.api.model.networking.NetworkPolicy.class, unmarshal.getClass());
    }

    @Test // fails
    public void serializationFromStream() {
        InputStream resourceAsStream = NetworkPolicyLoadBugTest.class.getResourceAsStream("/network/allow-namespace.yaml");
        Object unmarshal = Serialization.unmarshal(resourceAsStream);
        Assert.assertEquals(io.fabric8.kubernetes.api.model.networking.NetworkPolicy.class, unmarshal.getClass());
    }

Which results in the extension class instead

    java.lang.AssertionError: 
    Expected :class io.fabric8.kubernetes.api.model.networking.NetworkPolicy
    Actual   :class io.fabric8.kubernetes.api.model.extensions.NetworkPolicy

**Comment by rohanKanojia** [comment]
I think wrong handler is getting picked up when we are calling `load()` method. Need to check why
