### ISSUE TITLE
kubernetesClient.services() giving stale spec values

### ISSUE THREAD

**Issue by satyamsah** [fabric8io/kubernetes-client#2252]
I am polling the status of loadBalancerIP of the service to change to non-null or proper IP formed value like below.
```
void myMainMethod(){
    String endPointIPAddr = waitAndReturnPublicIPIfReady();
   if (endPointIPAddr == null || endPointIPAddr.toLowerCase().contains("pending") || 
     endPointIPAddr.toLowerCase().contains("none") ){
             myMainMethod(); //retry myMainMethod() for some threshold
    }else{ 
      log.info("I am happy to get an actual endPointIPAddr {}",endPointIPAddr);
   }
 
}
```

```
String waitAndReturnPublicIPIfReady() {
log.Info("spec {}",kubernetesClient.services().inNamespace(namespace).withName("ingress-nginx").fromServer().get().getSpec());

 return kubernetesClient.services().inNamespace(namespace).withName("ingress-nginx").get().getSpec().getLoadBalancerIP();
}
```

Here 
`,kubernetesClient.services().inNamespace(namespace).withName("ingress-nginx").fromServer().get().getSpec())` always gives the same output noted below, basically all the values except some  are null and also the loadBalancerIP is also null:

`ServiceSpec(clusterIP=10.96.219.159, externalIPs=[], externalName=null, externalTrafficPolicy=Cluster, healthCheckNodePort=null, loadBalancerIP=null, loadBalancerSourceRanges=[], ports=[ServicePort(name=http, nodePort=30740, port=80, protocol=TCP, targetPort=IntOrString(IntVal=null, Kind=1, StrVal=http, additionalProperties={}), additionalProperties={})], publishNotReadyAddresses=null, selector={app.kubernetes.io/name=ingress-nginx, app.kubernetes.io/part-of=ingress-nginx}, sessionAffinity=None, sessionAffinityConfig=null, type=LoadBalancer, additionalProperties={})
`

Is there any other specific method to get the updated spec values?

**Comment by rohanKanojia** [comment]
Why are you polling instead of using watch? You can simply get updated value on MODIFIED event.

**Comment by satyamsah** [comment]
Do you have related example code and doc to lookout for the Watch concept.

**Comment by rohanKanojia** [comment]
Try doing it like mentioned in this doc[0]. Here is full example of a watch[1]

[0] https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#service
[1] https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/WatchExample.java

**Comment by satyamsah** [comment]
```
myMain(){
  setupSparklineNginxService("abc")
  waitAndReturnPublicIPIfReady("abc)
}
```

**service creation:**
```public Service setupSparklineNginxService(String namespace) {
        try {
            Service service = new ServiceBuilder()
                    .withNewMetadata()
                        .withName("ingress-nginx")
                        .withNamespace(namespace)
                        .withLabels(labelMap)
                    .endMetadata()
                    .withNewSpec()
                        .withType("LoadBalancer")
                        .withSelector(labelMap)
                        .addNewPort()
                            .withName("http")
                            .withPort(80)
                            .withTargetPort(new IntOrString("http"))
                        .endPort()
                    .endSpec()
                    .build();
            return kubernetesClient.services().create(service);
        } catch (Throwable e) {
            throw new KubernetesAPIClientAPIException("Failed to setup Sparkline Nginx Service.", e);
        }
    }```

I am calling the below method waitAndReturnPublicIPIfReady just after above svc creation:

```
    public String waitAndReturnPublicIPIfReady(String namespace, int nAwaitTimeout) {
        String zeroTo255
                = "([01]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])";
         String IP_REGEXP
                = zeroTo255 + "\\." + zeroTo255 + "\\."
                + zeroTo255 + "\\." + zeroTo255;
         Pattern IP_PATTERN
                = Pattern.compile(IP_REGEXP);

        final CountDownLatch readyLatch = new CountDownLatch(1);
        try (Watch watch = kubernetesClient.services().inNamespace(namespace).withName("ingress-nginx").watch(new Watcher<Service>() {
            @Override
            public void eventReceived(Watcher.Action action, Service resource) {
                if(action.equals(Action.MODIFIED)){
                    log.info("Action  MODIFIED {}",action);
                    String lbIP = resource.getSpec().getLoadBalancerIP();
                    if(lbIP != null && IP_PATTERN.matcher(lbIP).matches()){
                        readyLatch.countDown();
                        lb =lbIP; // lb is the global variable which is already set to null
                        log.info("LB VALUE {}",lb);
                    }
                    log.info("LB {}",lb);
                    log.info("INSIDE eventReceived");
                }else{
                    log.info("Action {}",action);
                }
            }
            @Override
            public void onClose(KubernetesClientException e) {
                log.info("Watcher onClose WITHOUT EXCEPTIOn");
                if (e != null) {
                    log.info("Watcher onClose");
                    readyLatch.countDown();
                }

            }
        })) {
            readyLatch.await(nAwaitTimeout, TimeUnit.SECONDS);
        } catch (KubernetesClientException | InterruptedException e) {
            log.error("Could not watch svc", e);
        }
        log.info("LOADBALANCER IP {} ", lb);
        return lb;
    }```

The output is :
`Action: ADDED` . 
That means MODIFIED never got called.

what extra needed to be done here. How the MODIFIED action will be triggered. Do I need to sleep for sometime in between the two method call inside myMain().

**Comment by satyamsah** [comment]
@rohanKanojia or @manusa or anyone, can someone help here.

**Comment by rohanKanojia** [comment]
How are you modifying your service? I suspect it's not getting modified/edited

**Comment by satyamsah** [comment]
Hi @rohanKanojia. I don't have use case to modify my service and so not modifying my svc. 
I thought  was status Action will change to `MODIFIED` by k8s master/kubeapi which my above code will catch till `nAwaitTimeout` period expires. 

 As a reminder. The main reason of opening this issue was: even after calling( or polling) for the service for 20 retries with 30 sec timedelay between each retry, the fabric 8 API `kubernetesClient.services().inNamespace(namespace).withName("ingress-nginx").fromServer().get().getSpec()).getLoadBalancerIP()` gave `null`. But on the otherhand,  kubectl shows the real public IP.

So, do I really need watcher in this case. If yes. how will I modify my logic. If not, is it a bug on the method `kubernetesClient.services().inNamespace(namespace).withName("ingress-nginx").fromServer().get().getSpec())` API which has only store stale data or wrong data.

**Comment by rohanKanojia** [comment]
Umm, you're looking for load balancer IP, maybe you should try reading this field:
```
 String ip = client.services().inNamespace(namespace).withName("ingress-nginx").get().getStatus().getLoadBalancer().getIngress().get(0).getIp()
```

I have not tried this myself.

**Comment by satyamsah** [comment]
yes, it works, thank you.
