### ISSUE TITLE
Feature Request: Pod Exec support sizeQueue.

### ISSUE THREAD

**Issue by johnking0099** [fabric8io/kubernetes-client#2257]
There's no way to pass terminal window resize events to api-server through fabric8 client.
This is already supported by `kubectl exec` command.
Please consider add this feature.

**Comment by manusa** [comment]
https://github.com/kubernetes/kubectl/blob/master/pkg/util/term/resize.go

**Comment by johnking0099** [comment]
Attach some usable codes:

https://github.com/kubernetes/client-go/blob/master/tools/remotecommand/remotecommand.go#L108

https://github.com/kubernetes/client-go/blob/master/tools/remotecommand/v3.go#L45

**Comment by shawkins** [comment]
Is there additional support needed beyond ExecWatch.resize?
