### ISSUE TITLE
sundr.io codegen includes unshaded copy of commons-lang 2.4

### ISSUE THREAD

**Issue by randalloveson** [fabric8io/kubernetes-client#2259]
Just upgraded to client version 4.10.1 and started noticing NoSuchMethodErrors in commons-lang classes. I'm on commons-lang 2.6 in my project and there's an unshaded copy of 2.4 coming in with sundr.io codegen.

My question is, are the sundr.io dependencies runtime or compile-time dependencies? I don't know anything about sundr.io but "codegen" sounds like a compile-time dependency. Can they simply be excluded?

If they're required at runtime, I think this would have to be fixed upstream. There's an issue about it already (https://github.com/sundrio/sundrio/issues/153) but it doesn't sound like it got prioritized/resolved.

**Comment by rohanKanojia** [comment]
@randalloveson : Could you please upgrade to 4.10.2 and see if it resolves the issue?

**Comment by randalloveson** [comment]
Well would you look at that, released 3 hours ago. :+1:

Haven't finished running my tests or anything but I see the sundr stuff gone from the classpath, so I assume it's fixed. Thanks!

**Comment by randalloveson** [comment]
4.10.2 is working for me.

**Comment by manusa** [comment]
Relates to: #2195 
Fixed by: #2254

**Comment by frrivero** [comment]
Hi, adding io.kubernetes.java-client dependency is including sundr-cogeden.commons-lang:2.4 and is overwriting my StringUtils class, which is causing some methods to disappear, I have a direct dependency on commons-lang:2.6 and still gets overwritten.
kube-client:10.0.0

**Comment by manusa** [comment]
> Hi, adding io.kubernetes.java-client dependency is including sundr-cogeden.commons-lang:2.4 and is overwriting my StringUtils class, which is causing some methods to disappear, I have a direct dependency on commons-lang:2.6 and still gets overwritten.
> kube-client:10.0.0


Hi @frrivero 
Are you sure you commented in the right repo?
This is the issue repository for the awesome **fabric8** java client :wink: 
You seem to be referencing the official (but less awesome :stuck_out_tongue_winking_eye: ) [java client](https://github.com/kubernetes-client/java).
Or are you using both :flushed: ?

**Comment by frrivero** [comment]
> > Hi, adding io.kubernetes.java-client dependency is including sundr-cogeden.commons-lang:2.4 and is overwriting my StringUtils class, which is causing some methods to disappear, I have a direct dependency on commons-lang:2.6 and still gets overwritten.
> > kube-client:10.0.0
> 
> Hi @frrivero
> Are you sure you commented in the right repo?
> This is the issue repository for the awesome **fabric8** java client 😉
> You seem to be referencing the official (but less awesome 😜 ) [java client](https://github.com/kubernetes-client/java).
> Or are you using both 😳 ?

You are correct, wrong repo, guess I'll check this one out :-)
