### ISSUE TITLE
Is posible to check whether an action is allowed?

### ISSUE THREAD

**Issue by jorsol** [fabric8io/kubernetes-client#2264]
`kubectl` has the command `auth can-i`, it's possible to replicate this using kubernetes-client?

* https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-can-i-em-

**Comment by jorsol** [comment]
I'm trying to somewhat mimic the `kubectl auth can-i `command, but other than the SelfSubjectAccessReview is buggy, there is another request: the `can-i` command resolves shortcuts and groups, if I check the resource `deploy`, but the role is set to `deployment`, I get an allowed false response.

**Comment by rohanKanojia** [comment]
I think `SelfSubjectAccessReview` API has been fixed and it can be used. Please checkout this example: https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#selfsubjectaccessreview
