### ISSUE TITLE
missing ApiServices object?

### ISSUE THREAD

**Issue by sidharthnayyar** [fabric8io/kubernetes-client#2266]
Hi,

I'm using fabric8's kubernetes client but I'm getting an issue that I want to be able to handle APIService resources. Unfortunately I cannot find any subclass of HasMetadata for this kubernetes resource. 

I might be missing something - could someone guide me to where it is please?

Thanks

**Comment by rohanKanojia** [comment]
Could you please point location of go struct in Kubernetes sources? I don't see any struct named `APIService` in main [API](https://github.com/kubernetes/api) and [apimachinery](https://github.com/kubernetes/apimachinery)

**Comment by sidharthnayyar** [comment]
Hi, 

oh I don't see it there. The only reference I see is in apimachinery:
https://github.com/kubernetes/apimachinery/blob/2c7f8d2b0fd88820221837de89cf0e33cdf1347e/pkg/api/meta/testrestmapper/test_restmapper.go#L151

It's for the apiservices resource in apiregistration group:

```
> kubectl api-resources
NAME                 SHORTNAMES   APIGROUP                       NAMESPACED   KIND
...
apiservices                       apiregistration.k8s.io         false        APIService
...
```

**Comment by sidharthnayyar** [comment]
Hi,
It seems to be the in kube aggregator repo: https://github.com/kubernetes/kube-aggregator/blob/38ec12439d0daf3ee4e060c5bc4e658fca93b161/pkg/apis/apiregistration/v1/types.go#L144
