### ISSUE TITLE
Exception when loading yaml file with [spec.additionalPrinterColumns[0].JSONPath: Required valu

### ISSUE THREAD

**Issue by gilbirenberg** [fabric8io/kubernetes-client#2279]
Hi
For Kub 1.6.x and up they change the JSONPath to jsonPath when you creating a CRD yaml file
for some reason using your client i get the execetpion saying the JSONPath is needed (this is the old way) my client is the latest and my kub is 1.16 version
Any ideas?
Gil

**Comment by rohanKanojia** [comment]
Could you please share sample yaml and code with which we can reproduce this issue?

**Comment by gilbirenberg** [comment]
This is the file i am trying to load to my kube system using the code:
kubernetesClient.load(new FileInputStream(new File(file.toAbsolutePath().toString()))).createOrReplace();

[https://raw.githubusercontent.com/coreos/kube-prometheus/master/manifests/setup/prometheus-operator-0alertmanagerCustomResourceDefinition.yaml](url)

**Comment by manusa** [comment]
@rohanKanojia could you please verify if this was fixed by any of our recent changes to CustomResourceDefinition...

**Comment by rohanKanojia** [comment]
@gilbirenberg: On 4.11.x, When I try to load Yaml like this I don't get any error, CRD seems to be created for me:

```java
try (KubernetesClient client = new DefaultKubernetesClient()) {
    client.load(PrometheusAlertManagerCRDLoad.class.getResourceAsStream("/alertmanager.yml")).createOrReplace();
}
```
