### ISSUE TITLE
server.expect().post() not returing mock response

### ISSUE THREAD

**Issue by SurPatidar** [fabric8io/kubernetes-client#2282]
Hi,
I tried to mock response for create custom resource as below.  but  client.customResource(customResourceDefinitionContext).create("ns1", jsonObject);  always return request object back not the mock response which is expected. 
Please check below test method. I have created jsonResponseObject by updating name and size and returning but not getting excepted response.
Log:
Jun 12, 2020 10:21:26 PM okhttp3.mockwebserver.MockWebServer$4 processOneRequest
INFO: MockWebServer[64574] received request: POST /apis/test.fabric8.io/v1alpha1/namespaces/ns1/hellos/ HTTP/1.1 and responded: HTTP/1.1 200 OK

Actual Response: 
{metadata={name=example-hello}, apiVersion=test.fabric8.io/v1alpha1, kind=Hello, spec={size=3}}

Expected Response
{metadata={name=response-example-hello}, apiVersion=test.fabric8.io/v1alpha1, kind=Hello, spec={size=4}}

Code:
```
public void testCreate() throws IOException {
        String jsonResponseObject = "{\"apiVersion\": \"test.fabric8.io/v1alpha1\",\"kind\": \"Hello\"," +
                "\"metadata\": {\"name\": \"response-example-hello\"},\"spec\": {\"size\": 4}}";
        
      String jsonObject = "{\"apiVersion\": \"test.fabric8.io/v1alpha1\",\"kind\": \"Hello\"," +
        "\"metadata\": {\"name\": \"example-hello\"},\"spec\": {\"size\": 3}}";
       server.expect().post().withPath("/apis/test.fabric8.io/v1alpha1/namespaces/ns1/hellos").andReturn(201, jsonResponseObject).once();
      KubernetesClient client = server.getClient();

      Map<String, Object> resource = client.customResource(customResourceDefinitionContext).create("ns1", jsonObject);
      assertEquals("example-hello", ((Map<String, Object>)resource.get("metadata")).get("name").toString());
    }
```

**Comment by rohanKanojia** [comment]
@SurPatidar : That's strange, we have exact same test which is running for us:

https://github.com/fabric8io/kubernetes-client/blob/f1e892ac4908c0c54d80f875fd6109674800d5a3/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java#L78-L87

**Comment by rohanKanojia** [comment]
I'm a little bit confused. Why would you want to have a different response returned when you create something?

**Comment by SurPatidar** [comment]
> I'm a little bit confused. Why would you want to have a different response returned when you create something?

You are right but let think, when you are calling create API then might be we can receive a different response or response with some additional details as well based on API implementation.

In our case, We are using cronjobber.hidde.co/v1alpha1 for tzcronjobs which is returning some additional details in response like creationTimestamp,generation, uid etc that we want to check using test case. 

In below call when we are running a service in real, client.customResource(customResourceDefinitionContext).create("ns1", jsonObject); 
returning a response with some additional details which we need to handle using response payload. but we are not able to mock the return response.

I tried the same Test which you are referring and there is no meaning to use below line as this line is not executing.  
server.expect().post().withPath("/apis/test.fabric8.io/v1alpha1/namespaces/ns1/hellos").andReturn(HttpURLConnection.HTTP_CREATED, jsonObject).once();

**Comment by SurPatidar** [comment]
> @SurPatidar : That's strange, we have exact same test which is running for us:
> 
> https://github.com/fabric8io/kubernetes-client/blob/f1e892ac4908c0c54d80f875fd6109674800d5a3/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java#L78-L87

You can comment below line and run. You will get same response. Test case returning the request object not the andReturn mock response

server.expect().post().withPath("/apis/test.fabric8.io/v1alpha1/namespaces/ns1/hellos").andReturn(HttpURLConnection.HTTP_CREATED, jsonObject).once();

**Comment by rohanKanojia** [comment]
hmm, I see. We need to check why it's behaving like this.

**Comment by manusa** [comment]
Hi @SurPatidar 
We added a test case trying to reproduce but everything works as expected.
https://github.com/fabric8io/kubernetes-client/blob/f1d695d59ce50a9067639df0b79855f03096adc8/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceTest.java#L81-L95

**Comment by manusa** [comment]
We are closing this issue now, please report again if you are still facing problems with this issue.
