### ISSUE TITLE
Using Kubernetes-Certificates while creating a pod

### ISSUE THREAD

**Issue by HarmeetKaur94** [fabric8io/kubernetes-client#2283]
I want to pass my self-signed certificate as a request parameter in pod creation API and through which I want to know whether user has the permission to create a pod in that namespace. How this can be achieved.

**Comment by rohanKanojia** [comment]
Could you please elaborate on your use case? I think there is an option in `Config` class to provide certificates:
```
Config config = new ConfigBuilder()
        .withCaCertFile("/path/to/file")
        .build();
try (KubernetesClient client = new DefaultKubernetesClient()) {
    // Do stuff
    client.pods().inNamespace("ns").list();
}
```

**Comment by HarmeetKaur94** [comment]
I have used the exact same way to provide certificates. The problem is that while passing these certificates the Kubernetes client connects to every namespace present in that cluster what I want is that it should connect to the namespace only which is mentioned in the csr.

**Comment by rohanKanojia** [comment]
Does using the `.withNamespace("yournamespace)` parameter inside config help?
