### ISSUE TITLE
Question: How to create APIService and push it to kubernetes?

### ISSUE THREAD

**Issue by gilbirenberg** [fabric8io/kubernetes-client#2286]
Hi
I have a yaml file that is kind is APIService, i would like to push this using the kub client api into my kubernetes env, is this possible? and if yes how?

**Comment by rohanKanojia** [comment]
Related to #2266

**Comment by rohanKanojia** [comment]
I think we need to add it into our model. I don't think it's included right now.

**Comment by gilbirenberg** [comment]
When do you think this can be done? Can this be done by me?  can i take the code and this function and use it in my organisation?

**Comment by rohanKanojia** [comment]
Yes, I think adding it should not be too hard. You only need to make some small changes inside this file:
https://github.com/fabric8io/kubernetes-client/blob/9a5ae2a2d55af81da169c0b6e89bf2f3987fd49b/kubernetes-model-generator/kubernetes-model-core/cmd/generate/generate.go#L38-L50

1. Add import for the package
```
aggregator "k8s.io/kube-aggregator/pkg/apis/apiregistration/v1"
```
2. Add Objectsyou want in available types:
```
  ApiService                               aggregator.APIService
  ApiServiceList                           aggregator.APIServiceList
```
3. Provide package mapping to whatever package you feel right:
```
{"k8s.io/kube-aggregator", "aggregator.k8s.io", "io.fabric8.kubernetes.api.model.aggregator", "kubernetes_aggregator_"},
```
4. Build model inside `kubernetes-model-generator/kubernetes-model-core`:
```
make
```

**Comment by rohanKanojia** [comment]
Our project uses the Apache 2.0 license, so I think your organization should be able to use it.

**Comment by rohanKanojia** [comment]
This issue is already fixed via https://github.com/fabric8io/kubernetes-client/pull/2307
