### ISSUE TITLE
 CustomResourceDefinitionsOperationsImpl uses v1beta1 API instead of v1

### ISSUE THREAD

**Issue by coopstah13** [fabric8io/kubernetes-client#2287]
```
  public CustomResourceDefinitionOperationsImpl(OperationContext context) {
    super(context.withApiGroupName("apiextensions.k8s.io")
      .withApiGroupVersion("v1beta1")
      .withPlural("customresourcedefinitions"));
    this.type = CustomResourceDefinition.class;
    this.listType = CustomResourceDefinitionList.class;
    this.doneableType = DoneableCustomResourceDefinition.class;
  }
```
Would be good for this to use the non-beta API. This would require the client drop support for < 1.16 of k8s unless it is possible to let the fluent builders support both versions of the API.

**Comment by rohanKanojia** [comment]
If we just modify exiting CustomResourceDefinition to use v1, someone may report issue that we dropped v1beta1 CustomResourceDefinition

Hmm, I'm thinking of adding an additional DSL endpoint `apiextensions()`.
Then you could be able to use it like this:

```
   // For apiextensions/v1
   client.apiextensions().customResourceDefinitions().v1().createOrReplace(crdV1);
   // For apiextensions/v1beta1
   client.apiextensions().customResourceDefinitions().v1beta1().createOrReplace(crdV1beta1)
```

**Comment by coopstah13** [comment]
That looks good to me, but i might suggest that the default for `.customResourceDefinitions()` would be to use the `v1`?

**Comment by rohanKanojia** [comment]
Hmm, okay. we can modify old api entrypoint to use apiextensions/v1

**Comment by coopstah13** [comment]
i meant for the new apiextensions() based one, sorry!
