### ISSUE TITLE
How to pause a deployment

### ISSUE THREAD

**Issue by 1725762388** [fabric8io/kubernetes-client#2295]
I want to pause a deployment，I do the test according to the document
Deployment deployment = client.apps().deployments()
      .inNamespace("default")
      .withName("nginx-deployment")
      .rolling()
      .pause();
But there's no pause command. My version number is 4.10.2.
The first time I published an issue, I hope I can understand what I didn't express clearly

**Comment by rohanKanojia** [comment]
@1725762388 : #2272 which contains support for Deployment pause was merged 3 days ago. You should be able to use it whenever next release is available.

**Comment by rohanKanojia** [comment]
I think this code should be able to do it:
```
Deployment deployment = client.apps().deployments()
      .inNamespace("default")
      .withName("nginx-deployment")
      .rolling()
      .pause();
```
