### ISSUE TITLE
openshift-model has unresolvable osgi-import

### ISSUE THREAD

**Issue by joshiste** [fabric8io/kubernetes-client#2309]
the `io.fabric8:openshift-model:4.10.2` imports package `io.fabric8.kubernetes.internal` in its MANIFEST.MF but this package is private to `kubernetes-model-core`. 

Having a quick look on the sources the culprit seems to this import: https://github.com/fabric8io/kubernetes-client/blob/2ed58668ab6a0f83e038844d96efbbf4eea92a9c/kubernetes-model-generator/openshift-model/src/main/java/io/fabric8/openshift/api/model/Template.java#L30

**Comment by rohanKanojia** [comment]
@joshiste : Thanks a lot for your bug report. Would you like to contribute a PR to fix this issue?

**Comment by joshiste** [comment]
... my proposed fix would be to move the HasMetadataComparator into a public package. k?

**Comment by rohanKanojia** [comment]
I'm okay with moving it to public package as long as it doesn't break anything ;-)
