### ISSUE TITLE
OpenShiftClient: add support for ProjectRequest template parameters

### ISSUE THREAD

**Issue by Obirah** [fabric8io/kubernetes-client#2311]
When creating a ProjectRequest, the OpenShift API substitutes the five parameters 

- "PROJECT_NAME"
- "PROJECT_DESCRIPTION"
- "PROJECT_DISPLAYNAME"
- "PROJECT_ADMIN_USER"
- "PROJECT_REQUESTING_USER" 

into the corresponding template, see docs: https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#modifying-the-template-for-new-projects

So far I have not found a way to set the PROJECT_ADMIN_USER and PROJECT_REQUESTING_USER in the client, when creating a ProjectRequest with the ProjectRequestBuilder. 

It would be cool to have support for that, because right now I have to work around it by getting the template from the API, processing it in my code and then creating all the resources from a `KubernetesList`.

If I have just overlooked the feature and there's a way to do it, please let me know and I'll close the issue.

**Comment by rohanKanojia** [comment]
I've added a method in `projects()` in #2376 with which you can create a project with specified parameters. Do you think this would match your use case:
```
try (OpenShiftClient client = new DefaultOpenShiftClient()) {
    client.projects().createProjectAndRoleBindings("rokumar", "Rohan Kumar", "rokumar", "developer", "developer");
}
```

**Comment by Obirah** [comment]
Hi @rohanKanojia,

thank you very much for your addition! :) I'm sure it is useful to a lot of people, but unfortunately it does not solve my use case. We're using a customized ProjectRequest template that - amongst other additional resources - contains more than just the four RoleBindings that "createProjectAndRoleBindings" creates.

We replaced the template "project-request" in the "default" namespace. Therefore, with the oc client, whenenver we do "oc new-project" our template is being used correctly.

In order to reflect that in the fabric8 client, I think one would need to adapt the "client.projectrequests()" portion and also the "ProjectRequestBuilder" but I'm not entirely sure if that's possible or if my workaround by processing the complete template in my code is the way to go.

Maybe you can give your thoughts on that.

**Comment by rohanKanojia** [comment]
I'm not sure I fully understand your use case. We can make changes in projectrequests(), but not in`ProjectRequestBuilder` since it is a generated resource.
