### ISSUE TITLE
Replacing ingress with createOrReplace ignores changes to annotations

### ISSUE THREAD

**Issue by BartXZX** [fabric8io/kubernetes-client#2312]
Hi guys, 

I am replacing Kubernetes resources with `client.resourceList(yaml).inNamespace(namespace).createOrReplace()`, but my ingresses do not get replaced when only the annotations have changed. I use this for example to set/unset the `nginx.ingress.kubernetes.io/whitelist-source-range` annotation.
It looks like `ResourceCompare#equals` compares only labels, and not annotations.

Is this intentional, and do I need to work around this, or is this a bug?

**Comment by rohanKanojia** [comment]
Related to #2292

**Comment by BartXZX** [comment]
@rohanKanojia Do you expect the related ticket to fix this issue?

**Comment by rohanKanojia** [comment]
Umm, yeah. We're planning to refactor behavior of `createOrReplace` to do `create()` first and in case it fails with 409 do a `replace`
I think right now we're checking whether object has changed or not ourselves which is not aligning with kubectl behavior in my opinion.

**Comment by BartXZX** [comment]
Great! I've worked around it for now with a delete and apply, but this is less than ideal in case DNS decides to propagate the delete and not the create due to the timing of the ingress creation. Do you have an idea of when #2292 might be picked up?

**Comment by rohanKanojia** [comment]
It's already in our Sprint backlog: https://github.com/eclipse/jkube/projects/6 . We would try it pick it whenever we can.

**Comment by rohanKanojia** [comment]
I think this issue should be fixed via #2372 , I've added a test for this case here:

https://github.com/fabric8io/kubernetes-client/blob/14cae945ee20ce1ac980d492e53d388aa93eb371/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/NetworkingV1beta1IngressTest.java#L206-L229

**Comment by rohanKanojia** [comment]
Closing this issue. But feel free to reopen if it doesn't work for you or you face any other problems.
