### ISSUE TITLE
Fetch job logs should wait for the job's associated pod to be ready

### ISSUE THREAD

**Issue by ktotawar** [fabric8io/kubernetes-client#2314]
I am using watchLog with provided output stream for k8s jobs and I see that the stream is not populated with job logs since the pod is not ready (I see error message saying container is waiting to start in the file output stream) . If I fetch the associated pod for the job and wait for it to be ready before adding log watch then it works fine. I think the code in JobOperationsImpl which gets the associated pods for k8s job should wait for pod readiness instead of the consumer. 

_Originally posted by @ktotawar in https://github.com/fabric8io/kubernetes-client/issues/1188#issuecomment-647836221_

**Comment by rohanKanojia** [comment]
Umm, Shall we do this? Right now even `kubectl` throws the same error:
```
kubernetes-client : $ kubectl create -f ~/work/k8-resource-yamls/test-job.yml && kubectl logs -f job/pi 
job.batch/pi created
Error from server (BadRequest): container "pi" in pod "pi-h5x56" is waiting to start: ContainerCreating

```
