### ISSUE TITLE
waitUntilCondition: configurable poll rate

### ISSUE THREAD

**Issue by sbaier1** [fabric8io/kubernetes-client#2315]
Currently, `waitUntilCondition` still polls the current state from the API server every 500ms(!!) statically, which is pretty damn often IMHO.

It seems to me like this is pretty harsh on the API server to be queried that frequently when waiting for a condition like a roll-out of a Deployment finishing.

Can you overload the method to add a parameter to configure the poll rate, or a function parameter to allow custom back-off functions, or just straight implement exponential back-off that resets when the resource changes or something like that?

**Comment by rohanKanojia** [comment]
Umm, Could you please share kubernetes-client version? I remember this was refactored to use watcher in https://github.com/fabric8io/kubernetes-client/pull/2239

**Comment by sbaier1** [comment]
Oh sure, sorry. I am using `4.10.1`, so it makes sense that this is outdated on my part. 

I've been encountering problem with `4.10.2` that prohibited me from upgrading to the latest version and therefore i have not upgraded yet:

I'm using `DefaultKubernetesClient#load(InputStream)` to load a rendered template, which worked in `4.10.1` but throws a Jackson exception like `No resource type found for:Deployment` in `4.10.2`. Should i raise an issue for this instead?

**Comment by rohanKanojia** [comment]
@sbaier1 : Yes, that would be appreciated.
