### ISSUE TITLE
How to achieve "istioctl kube-inject" effects with Java code

### ISSUE THREAD

**Issue by DragonSuper** [fabric8io/kubernetes-client#2318]
Console command:
`kubectl apply -f bookinfo.yaml`

Java Code:
`
Deployment deployment = new DeploymentBuilder()
...
.build();
client.apps().deployments().inNamespace("test").create(deployment);
`

Console command:
`kubectl apply -f <(istioctl kube-inject -f yaml/istio-bookinfo/bookinfo.yaml)`

I want to do it in Java code,What should I do?.
Thanks!

**Comment by manusa** [comment]
Hi @DragonSuper 
You can take a look to https://github.com/snowdrop/istio-java-api. Maybe you can use the provided API for your specific use-cases.
