### ISSUE TITLE
Create Config without using auto-configure functionality or setting env variables

### ISSUE THREAD

**Issue by Fabian-K** [fabric8io/kubernetes-client#2319]
Hi,

I´m looking for a away to create a Config without using auto-configuration functionality while not relying on env variables or properties.

Currently when constructing a config like this, it still invokes the auto-configuration. I instead want to explicitly use the values provided (as they differ in terms of authorization from what is provided via auto-configuration)

```kotlin
val config: Config = ConfigBuilder()
                    .withCaCertData(...)
                    .withUsername(...)
                    .withNamespace(...)
                    .withOauthToken(...)
                    .withMasterUrl(...)
                    .build()

val client = DefaultKubernetesClient(config)
```

Is this already possible and I´m just not seeing it? :)

Thanks, Fabian

**Comment by rohanKanojia** [comment]
@Fabian-K : Hi, extremely sorry for the late reply. I think you might already have figured it out yourself. I checked code and there seem to be property `kubernetes.disable.autoConfig` which might do the trick for you. I'm not

https://github.com/fabric8io/kubernetes-client/blob/c87dd30165fdc6f196d1f588f54088e6989f133c/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L217-L221

**Comment by Fabian-K** [comment]
No problem, thanks for the reply!

Properties and Env Values are depending on the environment not always straight forward to set. I also somehow feel that it should be possible to say in code: "use exactly these config values which I provide".

The no-argument constructor is deprecated for some time now (2017). What do you think about removing the autoConfigure part from it and simply return an empty config? This way, the ConfigBuilder would not include auto-configuration any more. To make the breaking change obvious, this could be a private constructor, used e.g. by a new static method Config.empty().

**Comment by rohanKanojia** [comment]
I'm afraid that changing the default behavior of `ConfigBuilder` might break backward compatibility. I've seen lots of people using that `ConfigBuilder` to create client `Config`. But I agree this method has been deprecated for a long time. @manusa @oscerd  What do you think about Fabian's suggestion?

**Comment by Fabian-K** [comment]
An alternative might be to offer a new static method `Config.empty()` that uses a new private constructor `Config(Boolean autoConfigure)`

**Comment by oscerd** [comment]
We can do that, maybe by moving to 4.11.x and stress this in the release note. I don't think this is a change requiring a major bump like moving to 5.x
