### ISSUE TITLE
Deserialization Failure in AdmissionRequest

### ISSUE THREAD

**Issue by p3rsephone** [fabric8io/kubernetes-client#2330]
When trying to use an AdmissionReview, I get this:
```
Unable to deserialize property 'request' because of: Unable to deserialize property 'object' because of:  Cannot infer a type for unmarshalling into: io.fabric8.kubernetes.api.model.HasMetadata
```

I also seem to be getting the same errors when running the [AdmissionReviewTest](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/AdmissionReviewTest.java)

**Comment by rohanKanojia** [comment]
@p3rsephone : Were you able to resolve this? I tried running `AdmissionReviewTest` but I didn't face error you reported. Perhaps some misconfiguration in your project?

**Comment by p3rsephone** [comment]
Yes, not really sure what went wrong, but I no longer get that error in the `AdmissionReviewTest`
