### ISSUE TITLE
watchLogs for deployment is broken starting in 4.10.2

### ISSUE THREAD

**Issue by longwa** [fabric8io/kubernetes-client#2342]
Starting with 4.10.2, trying to watch logs on a deployment fails:
```
def watchLog = client.apps().deployments().inNamespace("k8s-test-f4772a").withName("testdeployment").watchLog(System.out)
```
The error indicates that it can't find the ReplicaSet:
```
Caught: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://x.x.x.x:6443/apis/apps/v1/namespaces/k8s-test-f4772a/replicasets/testdeployment?labelSelector=app.kubernetes.io%2Fname%3Dtestdeployment%2Capp.kubernetes.io%2Finstance%3Dtestdeployment. Message: the server could not find the requested resource. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=the server could not find the requested resource, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).
```

Looking at the error, it seems like maybe it's trying to find a replicaSet specifically named "testdeployment" (I'm assuming that's what the last part of the path means), but the replica sets are obviously named with a hash so maybe this lookup is too selective and should just be using the labels to match it.

Running the same test with 4.10.1 works fine.

**Comment by rohanKanojia** [comment]
I think somehow https://github.com/fabric8io/kubernetes-client/pull/2239 broke this behavior. Let me try to revert to old behavior

**Comment by rohanKanojia** [comment]
It's not just for Deployment, I checked it's broken for Jobs too
