### ISSUE TITLE
Javadoc missing from Maven central for 4.10.x releases

### ISSUE THREAD

**Issue by rvesse** [fabric8io/kubernetes-client#2346]
Seems something has changed in your release process for the 4.10.x releases as I am no longer to obtain Javadoc JARs for those releases from Maven central

For example 4.10.2 has the following content (https://repo1.maven.org/maven2/io/fabric8/kubernetes-model/4.10.2/):

![Screenshot 2020-07-13 at 12 34 07](https://user-images.githubusercontent.com/2104864/87300105-2f761e80-c505-11ea-9582-24105ef0891d.png)

Compared to 4.9.2 content (https://repo1.maven.org/maven2/io/fabric8/kubernetes-model/4.9.2/):

![Screenshot 2020-07-13 at 12 34 51](https://user-images.githubusercontent.com/2104864/87300153-461c7580-c505-11ea-90cb-7837de3d4866.png)

This is kinda strange since Maven Central generally requires Javadoc JARs to be present in order to sync artifacts to there (at least via the channels I've published to Maven Central in the past e.g. Sonatype OSS repo)

Please can you ensure that Javadoc is getting published in the future (and ideally publish it for the 4.10.x releases where it is missing)

**Comment by manusa** [comment]
Kubernetes-model acts just a pom dependency aggregator for split kubernetes-model modules (#2108 #2137 ).

You can find JavaDoc for each individual model package, e.g. https://repo1.maven.org/maven2/io/fabric8/kubernetes-model-core/

![image](https://user-images.githubusercontent.com/488391/87300599-6866c100-c50e-11ea-8d3d-b401dc67459c.png)

**Comment by rohanKanojia** [comment]
We should probably update javadoc link to Kubernetes Model in README too:

https://github.com/fabric8io/kubernetes-client/blob/29049672d488c4b8e4616451a068a6af5da3f5af/README.md#L16

**Comment by rvesse** [comment]
@manusa Thanks for the pointers, that makes sense

@rohanKanojia Yes this was where I was coming unstuck, I was trying to view the Javadocs on `javadoc.io` as I had done for previous releases and it was failing to find anything which led me to dig into what was present on Maven central

**Comment by rohanKanojia** [comment]
Np, I've added a PR to add links to javadoc for new splitted packages: https://github.com/fabric8io/kubernetes-client/pull/2347

**Comment by rohanKanojia** [comment]
Shall we close this issue?

**Comment by rvesse** [comment]
@rohanKanojia Yes this has been addressed by your doc updates, thanks!
