### ISSUE TITLE
Provide an information about Kubernetes' version in the documentation

### ISSUE THREAD

**Issue by MartinPodval** [fabric8io/kubernetes-client#236]
As Kubernetes team released v1.1, I was searching for which version is supported by this client. Can you please provide Kubernetes version in readme?

**Comment by ramukima** [comment]
Pod exec commands work only with 1.2.0-alpha.* versions, I tried with 1.2.0-alpha.5.

**Comment by jimmidyson** [comment]
Yeah exec is special as in we only support websockets for exec which requires Kubernetes the 1.2 alphas sadly. We'd be happy to get a SPDY implementation so we can exec with older versions of Kubernetes.

Other than exec, we should support any version >= 1.0.
