### ISSUE TITLE
how to get yaml string for object

### ISSUE THREAD

**Issue by sanqingshan** [fabric8io/kubernetes-client#2363]
how to get yaml string for object like this

```
kubectl get pod xxxx -o yaml
```
is it dump object to yaml directly?

**Comment by rohanKanojia** [comment]
could you please try this:
https://github.com/fabric8io/kubernetes-client/blob/1d4a122314ae3bccb25aaccc15fb24c70a10e312/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/FullExample.java#L118

**Comment by sanqingshan** [comment]
> could you please try this:
> https://github.com/fabric8io/kubernetes-client/blob/1d4a122314ae3bccb25aaccc15fb24c70a10e312/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/FullExample.java#L118

thank,i wil try it
