### ISSUE TITLE
metadata.resourceVersion: Invalid value: 0x0: must be specified for an update

### ISSUE THREAD

**Issue by matthyx** [fabric8io/kubernetes-client#2364]
Affected version: 4.10.3

This seems like a bug introduced by: https://github.com/fabric8io/kubernetes-client/blame/1ebaf2fae020a65da0f1fedeb0de735286192581/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java#L698

It happens when I call `client.customResource(prometheusRuleContext).createOrReplace(namespace, objectAsJsonString)` to create any CRD against an OpenShift 3.11 cluster.
It worked fine with kubernetes-client 4.10.2

I think the `metadata.resourceVersion` should be set when updating a resource - so there should be a test to remove that metadata only when creating the CRD.

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://cluster:8443/apis/monitoring.coreos.com/v1/namespaces/test/prometheusrules/test-alert-config. Message: prometheusrules.monitoring.coreos.com "test-alert-config" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.resourceVersion, message=Invalid value: 0x0: must be specified for an update, reason=FieldValueInvalid, additionalProperties={})], group=monitoring.coreos.com, kind=prometheusrules, name=test-alert-config, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=prometheusrules.monitoring.coreos.com "test-alert-config" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:589)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.makeCall(RawCustomResourceOperationsImpl.java:808)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.validateAndSubmitRequest(RawCustomResourceOperationsImpl.java:821)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.validateAndSubmitRequest(RawCustomResourceOperationsImpl.java:816)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.edit(RawCustomResourceOperationsImpl.java:277)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.createOrReplaceObject(RawCustomResourceOperationsImpl.java:718)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.createOrReplace(RawCustomResourceOperationsImpl.java:216)

**Comment by rohanKanojia** [comment]
Hmm, we changed createOrReplace behavior in https://github.com/fabric8io/kubernetes-client/pull/2289

**Comment by matthyx** [comment]
Yes, I think it's related to that... I am making some local tests and will let you know.

**Comment by matthyx** [comment]
Alright, so I have understood what's causing the issue:

Prior to the refactoring, `createOrReplace(String namespace, String objectAsString)` in https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java#L215

used to call `edit(String namespace, String name, String objectAsString)` in https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java#L289

which was adding the `metadata.resourceVersion`
by calling `appendResourceVersionInObject(String namespace, String customResourceName, String customResourceAsJsonString)` in https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java#L855

And now that `createOrReplace(String namespace, String objectAsString)` is calling `createOrReplace(String namespace, Map<String, Object> customResourceObject)` in https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RawCustomResourceOperationsImpl.java#L227

this metadata is no longer added to the json...

I can send a PR that adds and calls a similar method `appendResourceVersionInObject(String namespace, String customResourceName, Map<String, Object> customResource)` to fix it if you wanna review it.
