### ISSUE TITLE
Creating a ServiceMonitor

### ISSUE THREAD

**Issue by zenbones** [fabric8io/kubernetes-client#2367]
Is there any way to create a ServiceMonitor, as in..

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

If it isn't directly wrapped by the API, can I use the client to create/install an arbitrary type from string or JsonNode or... something?

**Comment by rohanKanojia** [comment]
Please see if this helps: https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#customresource-typeless-api

**Comment by zenbones** [comment]
It does help. I think this case is common enough that wrapping it in a specific api (as in client.serviceMonitors()..., etc.) seems useful. But the above worked as a workaround.

**Comment by rohanKanojia** [comment]
https://github.com/fabric8io/kubernetes-client/pull/2412 should take care of this issue. You should be able to create `ServiceMonitor` like this once it gets merged:
```
        try (OpenShiftClient client = new DefaultOpenShiftClient()) {
            ServiceMonitor serviceMonitor = new ServiceMonitorBuilder()
                    .withNewMetadata()
                    .withName("foo")
                    .addToLabels("prometheus", "frontend")
                    .endMetadata()
                    .withNewSpec()
                    .withNewNamespaceSelector().withAny(true).endNamespaceSelector()
                    .withNewSelector()
                    .addToMatchLabels("prometheus", "frontend")
                    .endSelector()
                    .addNewEndpoint()
                    .withPort("http-metric")
                    .withInterval("15s")
                    .endEndpoint()
                    .endSpec()
                    .build();

            client.monitoring().serviceMonitors().inNamespace("rokumar").createOrReplace(serviceMonitor);
         }
```
