### ISSUE TITLE
[Question] Deleting custom resource takes too long

### ISSUE THREAD

**Issue by stanlyDoge** [fabric8io/kubernetes-client#2370]
Hi,

I am using v4.10.3 with `kubernetes v1.11.0+d4cacc0` and I am having this issue.

With code like 
```
KubernetesClient kubeClient = new DefaultKubernetesClient();
MixedOperation operation = kubeClient.customResources(CustomResourceDefinitionContext.fromCrd(Crds.MyCrd()), MyCrd.class, MyCrdList.class, DoneableMyCrd.class);
operation.inNamespace(NAMESPACE).withName("my-crd-item").withPropagationPolicy(DeletionPropagation.FOREGROUND).delete();
```

In this test, the `my-crd-item` is sometimes deleted immediately and sometimes it is hanging there ~5 minutes. Deleting resource manually (`kubectl delete my-crd-item`) removes it instantly so I do not think it is on the k8s side. On the other hand, I tried different environments and the issue is not happening there.

When debugging the test, I am running the `delete()` command multiple times. It is returning `true` but the resource is still available.

**Comment by rohanKanojia** [comment]
that's strange. I'm not sure if we have any blocking code in client while deleting resource. We simply delegate it to kubernetes via a POST call. When you're deleting resource using `kubectl delete my-crd-item`, you are using `"propagationPolicy":"Background"`. Why are you using foreground propagation policy in code then?

**Comment by stanlyDoge** [comment]
I used `kubectl delete my-crd-item` just for confirmation it is deletable.

**Comment by rohanKanojia** [comment]
oh, ok. Will try to reproduce your issue.

**Comment by stanlyDoge** [comment]
Thanks. I believe it is something with my env, but let's be sure :)

**Comment by stanlyDoge** [comment]
Ah... yeah. It was caused by my environment. After restarting it, everything works perfectly.
