### ISSUE TITLE
Support for VolumeSnapshots in 1.17

### ISSUE THREAD

**Issue by ajaykmis** [fabric8io/kubernetes-client#2382]
Hello, 

I am trying to use VolumeSnapshotting feature in kubernetes which is supported in beta in 1.17.

https://kubernetes.io/docs/concepts/storage/volume-snapshots/

But looking through the client, I didn't find any support for the classes "API Objects VolumeSnapshot, VolumeSnapshotContent, and VolumeSnapshotClass are CRDs" in this client. 

is there a plan to add support for these in fabric client? or is there another way I can use these?

Thanks in advance.

**Comment by rohanKanojia** [comment]
We do have a PR #2356 for adding extension for Volume snapshots. Do you think that would fit your use case?

**Comment by ajaykmis** [comment]
@rohanKanojia  Yes, this is exactly what I was looking for. Is there a way I can give this a try? May be build a custom version from the source. Could you point me to the instructions? 

Thanks :)

**Comment by rohanKanojia** [comment]
I think you should be able to build a SNAPSHOT version and use that for testing.

**Comment by darewreck54** [comment]
@rohanKanojia Do you have an ETA on the release?

**Comment by rohanKanojia** [comment]
@darewreck54 : Do you mean next Kubernetes Client release or release with #2356 merged? I think we would be able to cut a release within this week. But I can't give you much ETA regarding latter case since that PR hasn't gone through review yet.

**Comment by ajaykmis** [comment]
Hi @rohanKanojia , 

I tried to create a SNAPSHOT version from the PR branch. But I don't see the bundled jar. Just to confirm, I ran "mvn clean install", I see individual jar's get generated for VolumeSnapshot.jar, and kubernetes-client.jar, but I don't see anything "kubernetes-client-project.jar". 

If there's a readme, could you please share how can I create a custom version for my use?

**Comment by rohanKanojia** [comment]
I think you need to use `volumesnapshot-client` for this case
