### ISSUE TITLE
KubernetesServer JUnit rule ignores value of https when using crud mode

### ISSUE THREAD

**Issue by coopstah13** [fabric8io/kubernetes-client#2389]
[See here](https://github.com/fabric8io/kubernetes-client/blob/50c1e8d86db5dc375c25f187a6ce2e1c6a69f2b5/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesServer.java#L56)
```
  public void before() {
    mock = crudMode
      ? new KubernetesMockServer(new Context(), new MockWebServer(), new HashMap<ServerRequest, Queue<ServerResponse>>(), new KubernetesCrudDispatcher(), true)
      : new KubernetesMockServer(https);
    mock.init();
    client = mock.createClient();
  }
```
When constructing a KubernetesServer JUnit rule you can specify a value for crudMode and https, but if you specify crudMode=true then the value for https is not used when creating the KubernetesMockServer so it will always be https enabled.

**Comment by rohanKanojia** [comment]
Closed via #2390
