### ISSUE TITLE
onUpdate not working

### ISSUE THREAD

**Issue by thomno** [fabric8io/kubernetes-client#2397]
Hi,

we switched from Version 4.7.0 to 4.10.3 and our Informer creates after the resyncPeriodInMillis time a new onUpdate Event. I checked the resources they haven't changed.

Code in which I create the informers

    public List<ResourceController> createControllers(
            OpenShiftClient client,
            EventPublisher eventPublisher,
            ClientCertificateConfig clientCertificateConfig
    ) {
        List<ResourceController> controllers = new ArrayList<>();

        SharedInformerFactory informerFactory = client.informers();
        SharedIndexInformer<ConfigMap> configMapInformer = informerFactory.sharedIndexInformerFor(ConfigMap.class, ConfigMapList.class, 1 * 60 * 1000);
        SharedIndexInformer<Secret> secretInformer = informerFactory.sharedIndexInformerFor(Secret.class, SecretList.class, 1 * 60 * 1000);

        controllers.add(ControllerFactory.create(configMapInformer, eventPublisher, ResourceFilterFactory.configMapFilter()));
        controllers.add(ControllerFactory.create(secretInformer, eventPublisher, ResourceFilterFactory.secretFilter(clientCertificateConfig.getOcpSecret())));
        informerFactory.startAllRegisteredInformers();
        return controllers;
    }

Code of the onUpdate script in ControllerFactory 

    public static ResourceController<HasMetadata> create(SharedIndexInformer<? extends HasMetadata> informer, EventPublisher publisher, OperatorResourceIdentifier ori) {
        return new ResourceController<HasMetadata>((SharedIndexInformer<HasMetadata>) informer, publisher) {
            @Override
            protected void registerHandler() {
                log.info("Registering handler for resource controller");
                informer.addEventHandler(new ResourceEventHandler<HasMetadata>() {

                    @Override
                    public void onUpdate(HasMetadata oldResource, HasMetadata newResource) {
                        log.info("Resource {} has been updated", newResource.getMetadata().getName());
                    }

                });
            }
        };
    }

Is that supposed to happen?

**Comment by rohanKanojia** [comment]
KubernetesClient tries to do a relist+rewatch after every resync period. The resync plays back all the events held in the informer cache. It can be chosen based on how often you want to reconcile. You've current set the resync period to 1 minute, client is rebuilding its cache after every 1 minute(that's why you're seeing update events in your cache). If you don't want this to happen, you may want to increase your resync period to more than a few minutes.
