### ISSUE TITLE
Cannot change the type of the Service from ClusterIP to ExternalName

### ISSUE THREAD

**Issue by stefanrosca** [fabric8io/kubernetes-client#2399]
The current implementation ignores changes to the ClusterIP field (related to: [https://github.com/fabric8io/kubernetes-client/issues/1925](https://github.com/fabric8io/kubernetes-client/issues/1925)), it copies the old value from the server entity and does not include it in the PATCH call.

When editing the 'type' field from ClusterIP to ExternalName the API Servers enforces the ClusterIP field to be empty making the edit impossible using the kubernetes-client.

Validation message: Message: Service "elasticsearch-logging" is invalid: spec.clusterIP: Forbidden: must be empty for ExternalName services. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.clusterIP, message=Forbidden: must be empty for ExternalName services, reason=FieldValueForbidden, additionalProperties={})], group=null, kind=Service, name=elasticsearch-logging, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Service "elasticsearch-logging" is invalid: spec.clusterIP: Forbidden: must be empty for ExternalName services, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).

**Comment by rohanKanojia** [comment]
We have refactored createOrReplace in #2292 to follow POST -> PATCH as a fallback approach. I think we should remove this code which seems to be adding this:

https://github.com/fabric8io/kubernetes-client/blob/e8c47dc3ce9ecfc1567c4ed7b2d90f15b4cae8b6/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ServiceOperationsImpl.java#L61-L70
