### ISSUE TITLE
Why KubernetesResource extends Serializable?

### ISSUE THREAD

**Issue by jorsol** [fabric8io/kubernetes-client#2402]
Is there any need for `KubernetesResource` to extend `Serializable`?

I think the `Serializable` could be dropped since Jackson handles the de/serialization here, or is there any other use for this?

**Comment by rohanKanojia** [comment]
@manusa @oscerd : What do you think about this? Shall we drop the `Serializable` interface?

**Comment by manusa** [comment]
Related to: https://github.com/fabric8io/kubernetes-model/pull/177

Serializable interface was added around a year after the project for _some reason_.
