### ISSUE TITLE
OkHttp ConnectionPool instances are created for each client and never torn down (or not torn down quickly)

### ISSUE THREAD

**Issue by longwa** [fabric8io/kubernetes-client#2403]
I have a web application which is providing status information via the kubernetes-client.

I create the client for each request and call close() when done (groovy code)
```
    private <V> V withClient(Closure<V> body) {
        KubernetesClient client = new DefaultKubernetesClient()
        try {
            body.call(client)
        }
        finally {
            client.close()
        }
    }
```
Each time a new DefaultKubernetesClient() is created, I get a new thread:
```
Name: OkHttp ConnectionPool
State: TIMED_WAITING on okhttp3.ConnectionPool@19dd6819
Total blocked: 1  Total waited: 2

Stack trace: 
java.lang.Object.wait(Native Method)
java.lang.Object.wait(Object.java:460)
okhttp3.ConnectionPool$1.run(ConnectionPool.java:67)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
```

These threads seem to hang around for awhile (maybe forever) and if we have enough traffic, eventually the process will be killed as it is using too many threads/memory.

Is this expected behavior? I tried re-using the same client instance over and over, but occasionally the connection would be broken and it would fail. Maybe I'm not understanding what should happen here.

**Comment by longwa** [comment]
It looks like they do get cleaned up after an amount of time (5 minutes seems to be the default). 
![image](https://user-images.githubusercontent.com/361184/90293986-610b3e00-de53-11ea-878d-18adf8991de2.png)

It looks like OkHttp realizes this is an issue and recommends to re-use the connection:
```
 * <p>The threads and connections that are held will be released automatically if they remain idle.
 * But if you are writing a application that needs to aggressively release unused resources you may
 * do so.
 *
 * <p>Shutdown the dispatcher's executor service with {@link ExecutorService#shutdown shutdown()}.
 * This will also cause future calls to the client to be rejected. <pre>   {@code
 *
 *     client.dispatcher().executorService().shutdown();
 * }</pre>
 *
 * <p>Clear the connection pool with {@link ConnectionPool#evictAll() evictAll()}. Note that the
 * connection pool's daemon thread may not exit immediately. <pre>   {@code
 *
 *     client.connectionPool().evictAll();
 * }</pre>
```

**Comment by longwa** [comment]
I thought this would help, but it doesn't seem to unless I'm doing something wrong:
```
    private <V> V withClient(Closure<V> body) {
        Config config = new ConfigBuilder().build()
        OkHttpClient okHttpClient = HttpClientUtils.createHttpClient(config)
        KubernetesClient client = new DefaultKubernetesClient(okHttpClient, config)
        try {
            body.call(client)
        }
        finally {
            client.close()
            okHttpClient.dispatcher().executorService().shutdown()
            okHttpClient.connectionPool().evictAll()
        }
    }
```

**Comment by longwa** [comment]
After reworking and testing, it looks like the way to use `KubernetesClient` is just to create a singleton instance of that and let the underlying OkHttp client sort out reconnections and such (which it seems to do). 

I think if there's a change to be made here, it's really just to the documentation to pass along the warning that if you are aggressively creating `KubernetesClient()` instances, the resources may not be cleaned up quick enough.

**Comment by thinking-aloud** [comment]
Thank you for the post. I have the same issue. I patch a deployment, which takes <5 seconds and than the app sits around another 5-6 minutes, until it finally shuts down. Really annoying. A fix would be highly appreciated.

**Comment by thimo-seitz** [comment]
I've the same issue. Especially in that case there is a error in the communication (like when the renew of the token fails) there are connections left behind which are marked internally as use, so that the close() call wouldn't clean up them and non daemon threads are left alive, so the jvm wouldn't exit. Would be nice if the close()-method will clean up all used resources.

**Comment by wanglijie95** [comment]
I meet the same problem. When I run a junit test multi time, call `client.close` after every run, but there will be many `OkHttp ConnectionPool` instances are still left behind.

**Comment by wanglijie95** [comment]
@rohanKanojia , What do you think about this problem？

**Comment by rohanKanojia** [comment]
Hi, I think @manusa  can provide better insights into this problem. I remember we discussed this in past but can't somehow recall whether this was caused by using okhttp or whether there was some bug on our side.

I remember a user also complained about this on our Gitter channel but he was able to resolve it by providing his own OkHttpClient in KubernetesClient as an argument: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ExecuteCommandOnPodExample.java

**Comment by wanglijie95** [comment]
> Hi, I think @manusa can provide better insights into this problem. I remember we discussed this in past but can't somehow recall whether this was caused by using okhttp or whether there was some bug on our side.
> 
> I remember a user also complained about this on our Gitter channel but he was able to resolve it by providing his own OkHttpClient in KubernetesClient as an argument: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ExecuteCommandOnPodExample.java

Thanks for reply @rohanKanojia . I will try to provide OkHttpClient as a parameter in KubernetesClient to solve this problem.

**Comment by davinchia** [comment]
@wanglijie95 this is work for you? I think I'm also running into the same issue.
