### ISSUE TITLE
java.lang.IllegalArgumentException: Item needs to be one of [Node, Deployment, ReplicaSet, StatefulSet, Pod, DeploymentConfig, ReplicationController], but was: [Deployment]

### ISSUE THREAD

**Issue by own-idea** [fabric8io/kubernetes-client#2404]
version: 4.10.2
Deployment class has two, but Readiness.isReady method only test one. So exception throwed.

**Comment by rohanKanojia** [comment]
@own-idea : Thanks for you bug report. You're right. We're not handling extensions `Deployment` here:

https://github.com/fabric8io/kubernetes-client/blob/e8c47dc3ce9ecfc1567c4ed7b2d90f15b4cae8b6/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java#L61-L75

Would you like to create a PR to fix this?

**Comment by own-idea** [comment]
> @own-idea : Thanks for you bug report. You're right. We're not handling extensions `Deployment` here:
> 
> https://github.com/fabric8io/kubernetes-client/blob/e8c47dc3ce9ecfc1567c4ed7b2d90f15b4cae8b6/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java#L61-L75
> 
> Would you like to create a PR to fix this?

Yes.  It's my first to create a PR. So i need know the PR process first.

**Comment by rohanKanojia** [comment]
1. Fork our Github repository
2. Clone forked repository
3. create new branch from master : `git checkout -b pr/issue2404`
4. make changes to file `vi kubernetes-client/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java`
5. Check if compilation is successful: `cd kubernetes-client; mvn clean install`
6. Add tests(if possible) `vi ./kubernetes-client/src/test/java/io/fabric8/kubernetes/client/internal/readiness/ReadinessTest.java`
7. Commit changes: `git add kubernetes-client/; git commit -m "your commit msg`
8. Push your changes: `git push origin pr/issue2404`
9. Once your fix branch is pushed, create PR from Github UI against fabric8 kubernetes client master :rocket:

**Comment by own-idea** [comment]
Thanks. I will try.
