### ISSUE TITLE
Provide a way to retrieve logs for previous pod instances (similar to --previous option on kubectl)

### ISSUE THREAD

**Issue by longwa** [fabric8io/kubernetes-client#2408]
Kubectl allows for the --previous option to logs to view previous instance of the logs.
```
You can use kubectl logs to retrieve logs from a previous instantiation of a container with --previous flag, in case the container has crashed. If your pod has multiple containers, you should specify which container's logs you want to access by appending a container name to the command. See the kubectl logs documentation for more details
```
I can't seem to find a way to do that in the fabric8 API. 

Also, I'm not sure how to retrieve logs for a specific container within the pod in cases where there are multiple. Maybe this exists in the API, but I can't find an example of how to do it.

**Comment by rohanKanojia** [comment]
Do you know what api is hit behind the scenes with `--previous`? Could you please share output of `kubectl logs --previous pod/your-pod -v=8`?

For latter part, Could you please check if this works for you?

https://github.com/fabric8io/kubernetes-client/blob/653c79e586057c9e641f715d23fc8c803fbbe54b/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java#L286-L290

**Comment by longwa** [comment]
Looks like it just passes the previous=true:

```
I0818 19:57:11.540778   81327 round_trippers.go:420] GET https://<ip>:6443/api/v1/namespaces/playarea-52688c/pods/tcs-6db8ff5bbc-fqzlg/log?previous=true
I0818 19:57:11.540802   81327 round_trippers.go:427] Request Headers:
I0818 19:57:11.540807   81327 round_trippers.go:431]     Accept: application/json, */*
I0818 19:57:11.540810   81327 round_trippers.go:431]     User-Agent: kubectl/v1.18.2 (darwin/amd64) kubernetes/52c56ce
I0818 19:57:11.587698   81327 round_trippers.go:446] Response Status: 200 OK in 46 milliseconds
I0818 19:57:11.587727   81327 round_trippers.go:449] Response Headers:
I0818 19:57:11.587731   81327 round_trippers.go:452]     Cache-Control: no-cache, private
I0818 19:57:11.587734   81327 round_trippers.go:452]     Content-Type: text/plain
I0818 19:57:11.587738   81327 round_trippers.go:452]     Date: Tue, 18 Aug 2020 23:57:11 GMT
```

Not sure the best approach, I guess either adding a getPreviousLog() method or maybe a boolean (previous = true) for the getLog() method (it already has pretty print option).

I'll try the specific container approach, I didn't realize that inContainer method existed. Thanks!

**Comment by rohanKanojia** [comment]
Sorry, I think I said we don't support it without checking. I checked the code and seems like this flag is being passed:

https://github.com/fabric8io/kubernetes-client/blob/a007adfd50e6603167aae5eac481215a4159f900/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java#L159-L161

I think this should do the trick for you:
```
client.pods().inNamespace(namespace).withName("test-pod1").terminated().getLog();
```

**Comment by rohanKanojia** [comment]
The only thing we're missing is adding some documentation about these supported flags

**Comment by longwa** [comment]
Thanks, that's what I was looking for, just didn't see it initially.

**Comment by rohanKanojia** [comment]
@longwa : No worries. I think one of the main problems in this project is that there is not much documentation present for users. I'll try adding documentation for Pod options here: https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md

**Comment by longwa** [comment]
@rohanKanojia Most of the API is very intuitive and easy to discover. It's is much easier to use than the official client.

**Comment by rohanKanojia** [comment]
@longwa : Thanks a lot for your feedback. I also think our API is more friendly to java developers(but I used to think I was biased :roll_eyes: )
