### ISSUE TITLE
Should expose kube-config filename/-path

### ISSUE THREAD

**Issue by adietish** [fabric8io/kubernetes-client#2411]
As a user of the library, I'd ex. want to monitor the kube config file for changes and re-create the client. For this sake it would make sense to get the file that the client is using. 

The client currently determines the filename in Config#getKubeconfigFilename() which is private. Afaics the filename that was used isn't expose anywhere. One could move this private method to a public method in KubeConfigUtils. This method should then also take into account when no file is used.

I can contribute this PR, I just need to inputs. Thanks!

**Comment by rohanKanojia** [comment]
It sounds fine to make it public method to me. @manusa @oscerd thoughts?

**Comment by adietish** [comment]
@rohanKanojia, @manusa, @oscerd Given that Config is stateful I'd even opt for storing the filepath (once it was used) and expose it. Sounds good?
