### ISSUE TITLE
About using the method "watchLog()"

### ISSUE THREAD

**Issue by Chiarorucs** [fabric8io/kubernetes-client#2449]
Hey! Sorry to bother you with so tiny detail! 

I have to pull logs from Pod then push them to WebSocket. In PodLogExample.class , I find a example like:

```java
Config config = new ConfigBuilder().withMasterUrl(master).build();
    try (KubernetesClient client = new DefaultKubernetesClient(config);
         LogWatch watch = client.pods().inNamespace(namespace).withName(podName).tailingLines(10).watchLog(System.out)) {
      Thread.sleep(5 * 1000);
    } catch (Exception e) {
      logger.error(e.getMessage(), e);
    }
```

These codes make it true and show logs on the console. I try to shift System.out to other Outputstream, such as ByteArrayOutputstream but failed. How should I pass the Outputstream param to method watchLog() then get log content from the Outputstream with the LogWatch  instance?

Or, Use other methods?

Thank you so much!

**Comment by rohanKanojia** [comment]
Hi, I think adding output stream should work just fine. Are you getting some error when you pass `ByteArrayOutputStream`? I've tried code like this multiple times and it seems to work for me:

```
            ByteArrayOutputStream baos = new ByteArrayOutputStream(1024);
            LogWatch logWatch = client.pods().inNamespace("default")
                    .withName("pi")
                    .watchLog(baos);

            Thread.sleep(5 * 1000);
            System.out.println(baos.toString());
```

**Comment by rohanKanojia** [comment]
@Chiarorucs: polite ping, Did you get any chance to revisit this? We have a test case to verify this too:

https://github.com/fabric8io/kubernetes-client/blob/dcae060f8fef7611c792a0c59dbb221737161ab5/kubernetes-itests/src/test/java/io/fabric8/kubernetes/JobIT.java#L65-L73

**Comment by Chiarorucs** [comment]
I'm so so sorry to reply this issue so late. It's a tough and busy period for me .

After a few days later since I commit this issue, I had been awared to the delay which kubernetes client may bring.And I try to use the method Thread.sleep() and make it.  So your solution is correct!

Thank you so much and apologize again!

**Comment by qian0205** [comment]
I  want to keep getting logs and print it using system.out.println  when new logs come. How can I do it?

**Comment by rohanKanojia** [comment]
@qian0205 : Hi, Could you please check if this works?

```java
try (KubernetesClient client = new DefaultKubernetesClient()) {
  client.batch().v1()
    .jobs()
    .inNamespace("default")
    .withName("pi")
    .watchLog(System.out);

  Thread.sleep(15 * 1000L);
} catch (InterruptedException e) {
  Thread.currentThread().interrupt();
  e.printStackTrace();
}
```
