### ISSUE TITLE
isReady() from internal package make it publicly available 

### ISSUE THREAD

**Issue by saparaj** [fabric8io/kubernetes-client#2452]
Hi Fabric8io Team,

I am currently using waitUntilReady() method which blocks the thread till resources are ready, instead of waiting I need to poll the status of resources, I can see isReady method is getting called in waitUntilReady() which is in internal package, is there any external/publicly available method present with the same implementation?

The response I got from @rohanKanojia on gitter that we can create wrapper method in utils for isReady() method - https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java

Creating this issue to track it.

Thanks,
Swarda

**Comment by rohanKanojia** [comment]
This seems like an easy fix to me. Would you like to create a PR for this?

**Comment by saparaj** [comment]
Thank you @rohanKanojia, Sorry I missed your comment.
