### ISSUE TITLE
Config.fromKubeconfig throws NPE in master

### ISSUE THREAD

**Issue by Fabian-K** [fabric8io/kubernetes-client#2474]
Hi,

just noticed that https://github.com/fabric8io/kubernetes-client/pull/2437 broke `Config fromKubeconfig(String kubeconfigContents)`. In this case kubeconfigPath is null and new File() throws the NPE.

Best regards,
Fabian

**Comment by rohanKanojia** [comment]
@Fabian-K : Would it be possible for you to create a quick PR to fix this?
