### ISSUE TITLE
Issue with release 4.11.x

### ISSUE THREAD

**Issue by jpiccaluga** [fabric8io/kubernetes-client#2482]
Hello, 

Could you check the release 4.11.x?
It looks like child modules in version 4.10.3 are pulled instead of 4.11.x.

Regards

Julien

**Comment by rohanKanojia** [comment]
@jpiccaluga : Could you please elaborate? which child modules are you referring to? How can we reproduce this issue?

**Comment by manusa** [comment]
4.12.0 is already out. Could you check if this is happening with this release too?

**Comment by jpiccaluga** [comment]
Hello Marc,

Yes it looks like I have the same issue. After upgrading kubernetes-clients
to version 4.12, I cannot longer do a createOrReplace on Crd because
`io.fabric8.kubernetes.api.model.apiextensions.v1beta1.CustomResourceDefinition`
not anymore in the classpath.
I also see in the dependency tree that kubernetes-clients to version 4.12
pull dependencies of version 4.10.3.

[image: image.png]

Regards

Julien

**Comment by rohanKanojia** [comment]
@jpiccaluga : Hi, Would it be possible for you to share a reproducer with us? We have an integration test which verified creation of CustomResourceDefinition of `apiextensions/v1beta1`:

https://github.com/fabric8io/kubernetes-client/blob/579d9728635bb1346b3c4e97eff1cb517e0af249/kubernetes-itests/src/test/java/io/fabric8/kubernetes/CustomResourceDefinitionIT.java#L47-L75

**Comment by rohanKanojia** [comment]
@stanlyDoge : Hello, Did you face any issue like this when upgrading to 4.12.0?

**Comment by rohanKanojia** [comment]
@jpiccaluga : What goal did you run exactly for dependency tree? When I'm running `mvn dependency:tree`, I'm not able to see any references to 4.10.3:
```bash
kubernetes-client : $ mvn dependency:tree | grep 4.10.3
kubernetes-client : $ 
```

**Comment by stanlyDoge** [comment]
It sounds like stale .m2 to me. I had no problem with 4.11.x -> 4.12.0

**Comment by jpiccaluga** [comment]
After analysing the effective pom of my project I found out that
`org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR8` was
pulling version 4.10.3 of all ìo.fabric8:kubernetes-model-xxx`.
I fix it by declaring `io.fabric8:kubernetes-client-bom:4.12.0`
before `org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR8`
in dependencyManagement.

Thx you for your support.


Le lun. 12 oct. 2020 à 17:35, Stanislav Knot <notifications@github.com> a
écrit :

**Comment by rohanKanojia** [comment]
@jpiccaluga : cool, Shall we close this issue then :-) ?

**Comment by jpiccaluga** [comment]
@rohanKanojia Yes we can close this issue.
Thx for your support ;-)
