### ISSUE TITLE
Shared informers should be better supported with adapted clients

### ISSUE THREAD

**Issue by FWiesner** [fabric8io/kubernetes-client#2489]
I tried modifying the Istio add-on to support shared informers and had a hard time doing so. I was able to fix the other project to populate `@ApiVersion` and `@ApiGroup` accordingly, but then hit two issues that I think should be fixed on kubernetes-client to make extensibility of shared informers easier.

1. `SharedInformerFactory` uses `io.fabric8.kubernetes.client.utils.Util#getPluralFromKind(String)` which has a hard-coded list of plurals. Ideally the plural should be read from an annotation
2. the informer factory has `#sharedIndexInformerForCustomResource` and `#sharedIndexInformerFor`. Classes in the istio-client are based on `HasMetadata` and `Namespaced`, not based on `CustomResource`. So, `#sharedIndexInformerFor` should work to get a new informer - and it does so. There is just one side effect in that the shared informer factory doesn't know about that informer, so `SharedInformerFactory#startAllRegisteredInformers` will not start it and I have to manually call `run` on the informer

**Comment by shawkins** [comment]
I think this can be resolved with #3239 and the preceding changes #3230 and #3233

**Comment by manusa** [comment]
Hi @FWiesner 
Do you think this is still applicable in 5.5.0? Most of the problems you highlight should no longer be an issue.
