### ISSUE TITLE
How to use this client to force delete pods.

### ISSUE THREAD

**Issue by Mrart** [fabric8io/kubernetes-client#2491]
If pod stuck in Terminating status, How to use thic client to delete it  like "kubectl delete pod <pod_name> -n <namespace> --grace-period 0 --force".

**Comment by rohanKanojia** [comment]
Does this work:
```
client.pods().inNamespace("ns1").withName("mypod").withGracePeriod(10).delete()
```

**Comment by Mrart** [comment]
It is not worked . As the nodes has lost, and the pods is stuck and the 'metadata.deletionTimestamp' != null.

**Comment by Mrart** [comment]
@rohanKanojia . Is there any way to use --force. The pods still continue to run and don't terminate even after 30 seconds, they're stuck on "terminating".

**Comment by rohanKanojia** [comment]
```
client.pods()
        .inNamespace("test")
        .withName("foo")
        .withPropagationPolicy(DeletionPropagation.BACKGROUND)
        .withGracePeriod(0)
        .delete();
```

**Comment by Mrart** [comment]
version > 4.9.3 supported '"--force" , like "
client.pods()
        .inNamespace("test")
        .withName("foo")
        .withPropagationPolicy(DeletionPropagation.BACKGROUND)
        .withGracePeriod(0)
        .delete();
"
