### ISSUE TITLE
KubernetesClientException: too old resource version; PullRequest #1800 is not released 

### ISSUE THREAD

**Issue by FqqCS** [fabric8io/kubernetes-client#2496]
I got an issue KubernetesClientException: too old resource version with version 4.11.1
I find this issue was fixed in PullRequest #1800 ；but this happend with the latest version，and i find these code is not in master branch.

**Comment by rohanKanojia** [comment]
https://github.com/fabric8io/kubernetes-client/pull/1800#issuecomment-549561724

**Comment by FqqCS** [comment]
Thanks.  so maybe the solution is restart watch when this exception happened.
