### ISSUE TITLE
IntOrString does not support parsing of longs

### ISSUE THREAD

**Issue by LEDfan** [fabric8io/kubernetes-client#2504]
Hi 

I'm using this client for a project which creates some pods. In the configuration of this project, a JSON Patch can be specified which should be applied to the Pod before it is created.
Using Jackson and the javax.json libraries this works, except when using probes. The probes contain a value `httpGet.port` which should be either a string or an integer. In our case this should be an int, because it is just a port number.
I figured out that the fabric8 client tries to parse this value using the `IntOrString` class (https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/IntOrString.java).
The problem is that the deserializer of this class, only checks whether the input is an int. However, the Jackson library we use to parse the YAML (or JSON) creates a long for the port number value. Therefore the IntOrString does not recognize this is an integer and parses the port number as a string. When creating the Pod, kubernetes will complain that he value is ambiguous.

Here is some minimal example:

<details>

```
package eu.openanalytics.shinyproxyoperator;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import com.fasterxml.jackson.datatype.jsr353.JSR353Module;
import io.fabric8.kubernetes.api.model.Pod;

import javax.json.JsonPatch;
import javax.json.JsonStructure;

public class Reproduce2 {

    public static void main(String[] args) throws JsonProcessingException {
        String input =
                "apiVersion: v1\n" +
                "kind: Pod\n" +
                "metadata:\n" +
                "  name: example\n" +
                "spec:\n" +
                "  containers:\n" +
                "   - name: httpd\n" +
                "     image: \n" +
                "     livenessProbe:\n" +
                "      httpGet:\n" +
                "        path: /actuator/health/liveness\n" +
                "        port: 80\n" +
                "      periodSeconds: 1";

        ObjectMapper mapper = new ObjectMapper(new YAMLFactory());
        mapper.registerModule(new JSR353Module());

        // read patch
        JsonPatch patch = readPatch(mapper);

        // read pod
        Pod pod = mapper.readValue(input, Pod.class);

        System.out.println(pod.getSpec().getContainers().get(0).getLivenessProbe().getHttpGet().getPort());

        // apply patch
        JsonStructure podAsJsonValue  = mapper.convertValue(pod, JsonStructure.class);
        JsonStructure patchedPodAsJsonValue = patch.apply(podAsJsonValue);
        Pod patchedPod = mapper.convertValue(patchedPodAsJsonValue, Pod.class);

        System.out.println(patchedPod.getSpec().getContainers().get(0).getLivenessProbe().getHttpGet().getPort());
    }

    private static JsonPatch readPatch(ObjectMapper mapper) throws JsonProcessingException {
        String patch =
                "- op: add\n" +
                "  path: /spec/containers/0/env\n" +
                "  value:\n" +
                "    - name: TEST_VAR\n" +
                "      value: TEST_VALUE";

        return mapper.readValue(patch, JsonPatch.class);
    }

}
```
</details>

This creates the following ouput:
```
IntOrString(IntVal=80, Kind=0, StrVal=null, additionalProperties={})
IntOrString(IntVal=null, Kind=1, StrVal=80, additionalProperties={})
```

To work around this issue I use the following code after patching the pod (in Kotlin):
```
       if (httpGet.port.intVal == null) {
            val asInt = httpGet.port.strVal.toIntOrNull()
            if (asInt != null) {
                httpGet.port = IntOrString(asInt)
            }
        }
```

If you agree this is an issue and are willing to support the use-case, I can try to create a PR.
However, I'm not sure how we should solve this, as I see a few options:
 - change the `IntOrString` class to use long as datatype
 - add long as extra supported data type to `IntOrString` (has little advantage and only complicates things IMO)
 - check if the input is long and then try to convert it to int using the `java.lang.Math.toIntExact` function.
   Since port numbers should always fit in a Int, I believe this is the best solution. Only when the user provides a wrong input this should give some exception.

**Comment by manusa** [comment]
We already provide deserialization utils.

Is this error reproducible when using `Serialization#unmarshal` methods?
