### ISSUE TITLE
Sonar detects vulnerabilities in openshift-model-4.11.1.jar

### ISSUE THREAD

**Issue by blev007** [fabric8io/kubernetes-client#2505]
Hello,
I recently upgraded the K8s java client to 4.11.1, and when running Sonar on our projects, Sonar now detects 3 major vulnerabilities in openshift-model-4.11.1.jar. 
Are you aware of these vulnerabilities ?
I can provide you with the detailed Sonar info in a private message, if needed.
Thanks in advance.
Best regards,

**Comment by rohanKanojia** [comment]
@blev007 : Could you please send details to me and @manusa in email or gitter message[0]?

[0] https://gitter.im/fabric8io/kubernetes-client

**Comment by manusa** [comment]
Hi Bruno, I just sent you an e-mail with a brief analysis of the report.

**Comment by blev007** [comment]
Thanks Marc!

**Comment by manusa** [comment]
Closing issue, feedback provided by Bruno on email (`Wed, 21 Oct 2020 10:13:24 +0000`)
