### ISSUE TITLE
Support for kubernetes 1.16

### ISSUE THREAD

**Issue by rktechie** [fabric8io/kubernetes-client#2509]
I see in the documentation that kubernetes 1.15.3 and 1.17.0, which of the clients support kubernetes 1.16?

**Comment by Aitozi** [comment]
BTW，another question: Is version  4.1.0  support Kubernetes 1.16？

**Comment by rohanKanojia** [comment]
We updated the Kubernetes Model to Kubernetes 1.17.x in v4.7.0. In our compatibility matrix, when we say the client supports 1.17.x, we mean it supports up to Kubernetes 1.17.x(unless there is some breaking change in between Kubernetes 1.16.x and 1.17.x). 

Could you please try with versions after 4.7.0 for your setup and see if they work fine? Are you looking for something in particular related to Kubernetes 1.16.x that we might be missing?

**Comment by manusa** [comment]
It's probably safe to assume that Kubernetes Client works with 1.16.x
- We should check from which Kuberentes-Client version we are 1.16.x compliant
- We should also use this issue to reverse the compatibility matrices so that newest/more recent versions come left-most and top-most

**Comment by rohanKanojia** [comment]
I just checked compatibility with 1.16 by running our integration test suite on my branch with minikube's version set to 1.16.0: https://github.com/rohanKanojia/kubernetes-client/runs/1241248067?check_suite_focus=true

**Comment by manusa** [comment]
That's good, but we need to check from which Kubernetes Client Version we are 1.16 compliant. According to the current compatibility matrix, this should be between 4.6.0 and 4.7.0.

If we don't want to do any extra tests (probably not worth it), we should settle on 4.7.0.

**Comment by rohanKanojia** [comment]
@Aitozi  @rktechie: I've created a PR for adding Kubernetes 1.16.0 to the compatibility matrix. I would suggest using Kubernetes Client 4.7.0 and above. Could you please try it out and provide feedback?

**Comment by rohanKanojia** [comment]
polite ping, Did anyone get any chance to try KubernetesClient v4.7.0 on Kubernetes 1.16.x?

**Comment by rohanKanojia** [comment]
Closing this as I think it's resolved. Please feel free to reopen in case you're still facing problems with this.
