### ISSUE TITLE
Review release procedure

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#2518]
## Description

It has been reported by several users that they've spent a considerable amount of time dealing with breaking changes and remaining clueless upon the procedure they must follow to upgrade their code.

We need to improve our release process so we avoid such situations.

Changelog should highlight in some way if there are breaking changes. Any change that breaks backwards compatibility should include a link (or more details) with information on how to deal with the change.

**Comment by manusa** [comment]
We can maybe add an extra subheading for each release `Breaking changes`.

Each entry in one of the previous sections (Bugs, Improvements, ...) which involves a breaking change (as marked in the PR), should also include an entry in this new subsection.

**Comment by matthyx** [comment]
In my particular case, it was more a regression that went thru because of incomplete test coverage... actually I saw that you @rohanKanojia have improved it while fixing in #2490
