### ISSUE TITLE
SharedIndexInformer watches only pods of its own namespace when run in the cluster

### ISSUE THREAD

**Issue by adferrand** [fabric8io/kubernetes-client#2527]
I am trying to build a Kubernetes controller using ` fabric8io/kubernetes-client`. As of now I use the version `4.10.3`.

For that purpose I am constructing a `SharedIndexInformer` to properly watch resources events emitted by the cluster. I will take pods as resources example here.

So the `SharedIndexInformer` is constructed following this piece of code:
```java
SharedIndexInformer<Pod> sharedIndexInformer = kubernetesClient.informers().sharedIndexInformerFor(
                objectClass,
                objectClassList,
                10 * 60 * 1000);
```

Following, lot of code to attach events handler, start the indexer, have a reconciliation loop and so on.

The indexer is working perfectly fine when started from my local machine, and I see all pods being listed. However, when I run it on a pod in my cluster (with RBAC properly defined), I see only the pods for the namespace where the pod is run on.

I checked explicitly in the pod that, using `kubectl`, the associated service account was capable to list all pods in the cluster, and not only in the current namespace.

What am I missing?

Thanks in advance for your help!

**Comment by adferrand** [comment]
I close the issue here to avoid duplicate with the question I also submit on StackOverflow: https://stackoverflow.com/questions/64204044/sharedindexinformer-fabric8-kubernetes-client-watches-only-pods-of-its-own-nam

**Comment by rohanKanojia** [comment]
oh, I'm sorry. I didn't see your issue. This is also related to #2514
