### ISSUE TITLE
SelfSubjectAccessReviews broken with OpenshiftClient in 4.11.0-4.12.0

### ISSUE THREAD

**Issue by jgray1206** [fabric8io/kubernetes-client#2529]
I have been trying to follow the example docs on the SelfSubjectAccessReviews. I am able to get them to return valid responses using a DefaultKubernetesClient, but I get nulled out+empty response when using a DefaultOpenshiftClient. The POST request looks okay, which makes me think it is having troubles serializing the response into a valid SelfSubjectAccessReview.

**Comment by rohanKanojia** [comment]
What code are you trying?

**Comment by jgray1206** [comment]
I don’t think I would be allowed to post the code directly, sadly. But it is verbatim what exists in the examples docs. Instead of creating a DefaultKubernetesClient, though, I am creating a DefaultOpenshiftClient. I am checking for “update” permissions on a “builds” resource. The response comes back filled with Java default values. Changing from a Openshift to Kubernetes client fixes it instantly.

**Comment by rohanKanojia** [comment]
oh, you mean it's working for `KubernetesClient` only :cry: ? Will try to reproduce

**Comment by rohanKanojia** [comment]
I'm not able to reproduce this, here is what I'm doing:

```java
try (OpenShiftClient client = new DefaultOpenShiftClient()) {
    SelfSubjectAccessReview ssar = new SelfSubjectAccessReviewBuilder()
            .withNewSpec()
            .withNewResourceAttributes()
            .withGroup("apps")
            .withResource("deployments")
            .withVerb("create")
            .withNamespace("rokumar")
            .endResourceAttributes()
            .endSpec()
            .build();

    ssar = client.authorization().v1().selfSubjectAccessReview().create(ssar);
    System.out.println(ssar.getStatus().getAllowed());
}
```
When I run this on OpenShift 3.11 based cluster, I get this output:
```
false

```

**Comment by jgray1206** [comment]
Hmm are you able to test a situation where the request should return “true”? The client does return a valid status object, but the primitive/objects within are all defaulted. Which may explain why you got “false” there.

**Comment by rohanKanojia** [comment]
Hmm, I think you're right. It should have returned `true`. I was expecting some error while deserializing response.

**Comment by jgray1206** [comment]
Yeah it is weird. I didn’t get any errors either. Just a completely defaulted object.

**Comment by rohanKanojia** [comment]
This is extremely weird, when debugging this I can see the response returning false:
![Screenshot from 2020-10-10 01-26-42](https://user-images.githubusercontent.com/13834498/95626401-d3854c80-0a97-11eb-8436-6dc4028395e9.png)

But if I do CURL I'm able to see expected response :confused: : 
```
curl -XPOST -H "Content-Type: application/json" http://localhost:8001/apis/authorization.k8s.io/v1/selfsubjectaccessreviews  -d '{"apiVersion":"authorization.k8s.io/v1","kind":"SelfSubjectAccessReview","spec":{"resourceAttributes":{"group":"apps","namespace":"rokumar","resource":"deployments","verb":"create"}}}'
{
  "kind": "SelfSubjectAccessReview",
  "apiVersion": "authorization.k8s.io/v1",
  "metadata": {
    "creationTimestamp": null
  },
  "spec": {
    "resourceAttributes": {
      "namespace": "rokumar",
      "verb": "create",
      "group": "apps",
      "resource": "deployments"
    }
  },
  "status": {
    "allowed": true,
    "reason": "RBAC: allowed by RoleBinding \"admin/rokumar\" of ClusterRole \"admin\" to User \"rohanKanojia\""
  }
}
```
Need to check what's different here in case of client ...

**Comment by jgray1206** [comment]
Any update on this guy? Would love to be able to use this much cleaner api

**Comment by rohanKanojia** [comment]
Sorry, no update for now. I didn't get any time to revisit this. We will prioritize this for the upcoming sprint. 

Bdw, what do you see in logs when you set SlF4J logging level to trace, I think it prints request/response payload. Do you see the correct request payload being sent?

**Comment by Lutonite** [comment]
Hello!

It seems that on the latest version of openshift-client this is still an issue.

```xml
 <dependency>
    <groupId>io.fabric8</groupId>
    <artifactId>openshift-client</artifactId>
    <version>5.3.1</version>
</dependency>
```

Activating the debug log I see the following:

```
2021-05-04 09:27:34.145  INFO 1249942 --- [io-15000-exec-5] okhttp3.OkHttpClient                     : --> POST https://<OPENSHIFT_HOST>:6443/apis/authorization.k8s.io/v1/selfsubjectaccessreviews h2
2021-05-04 09:27:34.146  INFO 1249942 --- [io-15000-exec-5] okhttp3.OkHttpClient                     : Content-Type: application/json; charset=utf-8
2021-05-04 09:27:34.146  INFO 1249942 --- [io-15000-exec-5] okhttp3.OkHttpClient                     : Content-Length: 142
2021-05-04 09:27:34.147  INFO 1249942 --- [io-15000-exec-5] okhttp3.OkHttpClient                     : Host: <OPENSHIFT_HOST>:6443
2021-05-04 09:27:34.147  INFO 1249942 --- [io-15000-exec-5] okhttp3.OkHttpClient                     : Connection: Keep-Alive
2021-05-04 09:27:34.147  INFO 1249942 --- [io-15000-exec-5] okhttp3.OkHttpClient                     : Accept-Encoding: gzip
2021-05-04 09:27:34.147  INFO 1249942 --- [io-15000-exec-5] okhttp3.OkHttpClient                     : User-Agent: okhttp/3.14.9
2021-05-04 09:27:34.148  INFO 1249942 --- [io-15000-exec-5] okhttp3.OkHttpClient                     : 
2021-05-04 09:27:34.150  INFO 1249942 --- [io-15000-exec-5] okhttp3.OkHttpClient                     : {"apiVersion":"authorization.k8s.io/v1","kind":"SelfSubjectAccessReview","spec":{"resourceAttributes":{"resource":"namespaces","verb":"get"}}}
2021-05-04 09:27:34.150  INFO 1249942 --- [io-15000-exec-5] okhttp3.OkHttpClient                     : --> END POST (142-byte body)
```

Which to me shows that the `Authorization` header is not sent with the request for this particular endpoint.

I've spent some time debugging and I think I've found what is preventing the header from being set: https://github.com/fabric8io/kubernetes-client/blob/master/openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftOAuthInterceptor.java#L71

The header is only defined if the first response from the endpoint is a 401 or 403. But, SelfSubjectAccessReviews always returns a 200, even if unauthenticated. Would there be a way to force the header to be set?

**Comment by Lutonite** [comment]
@rohanKanojia Would the information I've provided just above be able to help with fixing this issue?

I think that the OAuthInterceptor for openshift-client should always add the Authorization header if a username and password or a token is provided in the config, that would also prevent having to run a request twice all the time.

**Comment by rohanKanojia** [comment]
@Lutonite : Thanks a lot for investigating this issue. Would it be possible for you to submit a PR?

**Comment by Lutonite** [comment]
I'll see what I can do 👍🏻

**Comment by rohanKanojia** [comment]
Thanks a lot!

**Comment by rohanKanojia** [comment]
@Lutonite : Shall I pick this up instead?

**Comment by Lutonite** [comment]
@rohanKanojia My apologies, I got caught up in some issues with another app which doesn't depend on this library, so I completely forgot about fixing this. I would greatly appreciate it if you can fix it instead!

**Comment by rohanKanojia** [comment]
@Lutonite : No worries, I'll submit a PR and add you for review.
