### ISSUE TITLE
Tekton extension does not support When expressions

### ISSUE THREAD

**Issue by jeffmaury** [fabric8io/kubernetes-client#2534]
When expressions are not supported. Updating to the latest Tekton Pipeline will update model

**Comment by rohanKanojia** [comment]
@jeffmaury : Thanks a lot for reporting this. We would gladly accept a PR if you're interested in fixing this.

**Comment by jeffmaury** [comment]
Working on it

**Comment by rohanKanojia** [comment]
@jeffmaury : much appreciated, Thanks!
