### ISSUE TITLE
Introduce possibility to sort results of list() operation by some label value

### ISSUE THREAD

**Issue by reste85** [fabric8io/kubernetes-client#2547]
Via kubectl it is possible to user the attribute --sort-by. Via fabric8 k8s client this is not currently possible. Keep in mind that the sorting is done client side.

Thank you!

**Comment by rohanKanojia** [comment]
I had a discussion about this with @manusa and he also said the same thing as you were saying that sorting on client is not a good idea. But we should be able to provide opinionated Comparators in `KubernetesResourceUtil` for standard `--sort-by` fields which might be helpful for sorting lists.
