### ISSUE TITLE
Provider not found

### ISSUE THREAD

**Issue by isaacpz** [fabric8io/kubernetes-client#2554]
Hi! No bugs or actions for maintainers in this issue. Just want to create it in order to document how I fixed a build error I had with this library. Hoping this helps somebody else who is searching the project issues for keywords like I was.

The error is:
```
java.util.ServiceConfigurationError: io.fabric8.kubernetes.api.KubernetesResourceMappingProvider: Provider io.fabric8.kubernetes.internal.InternalResourceMappingProvider not found
```

I am using Gradle to build my project, and after a bit of turmoil I realized that certain classes from transitive dependencies (like io.fabric8.kubernetes.internal.InternalResourceMappingProvider) were not getting shadowed into my output jar. As it turns out, this is because of the `minimize()` option I was using with the `com.github.johnrengelman.shadow` plugin for Gradle. 

To fix this issue, I simply excluded `kubernetes-client` from the `shadowJar` options in Gradle:

```
shadowJar {
    minimize {
        exclude(dependency('io.fabric8:kubernetes-client:.*'))
    }
}
```

I hope this helps somebody!

**Comment by rohanKanojia** [comment]
@isaacpz : Which version of KuberntesClient are you using? Could this be related to https://github.com/fabric8io/kubernetes-client/issues/2488 We've fixed this in v4.12.0
