### ISSUE TITLE
Hide Doneable interface from users (CRDs)

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#2564]
## Description

Custom Resource Definitions on the client require the user to declare [dummy](https://github.com/fabric8io/kubernetes-client/blob/272c4f5fa5086d935d1823c12df6d4c92e019583/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/crds/DoneableDummy.java) [implementations](https://github.com/fabric8io/kubernetes-client/blob/56bed4189bce0d205a1ecb1d37eb281692d55a07/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResourceDoneable.java) of the [`Doneable`](https://github.com/fabric8io/kubernetes-client/blob/59eb150d84a6a707b83097e544c3ff4a3a45b81a/kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/Doneable.java) interface.

This is redundant and unnecessary in most cases, since almost all `Doneable` implementations are the same (especially for CRDs). This interface simplifies the code generation process, but in the end, the real call is implemented via reflection in the [`HasMetadataOperation`](https://github.com/fabric8io/kubernetes-client/blob/ec1e20eca8996db6a6ed0b208c8e04da1b7b7b8b/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java#L86).

Regarding CRDs, the fact that a `Doneable` interface is required has lead some users to implement rather [complicated](https://github.com/ContainerSolutions/java-operator-sdk/blob/7cbf736dd94b98691747cfd241920f842286a096/operator-framework/src/main/java/com/github/containersolutions/operator/ControllerUtils.java#L45) mechanisms to bypass this: https://github.com/ContainerSolutions/java-operator-sdk/pull/66.

I think we can improve the code generation model templates with some minor changes to the dependent methods so that we can avoid this altogether. The `Doneable` interface implementing models should be kept open for extension, but defaults should be provided to improve the user experience.

**Comment by metacosm** [comment]
I completely agree with the assessment, as you already know 😄! I'd just add, as you mentioned in your last paragraph, that the purpose is not so much hiding the `Doneable` interface completely but rather not make it mandatory anymore as is currently the case. It should still be possible to pass a `Doneable` when needed.

**Comment by iocanel** [comment]
I think that there are two things here:

- Remove Doneable as a parameter (we never ever really need it). (See #2566)
- Do not generate Doneable per type.

**Comment by rohanKanojia** [comment]
Shall we close this issue?
