### ISSUE TITLE
Failed to Init KubernetesClient

### ISSUE THREAD

**Issue by zengzilu** [fabric8io/kubernetes-client#2568]
I try to init KubernetesClient like 
![image](https://user-images.githubusercontent.com/37807654/97673493-d1c30d80-1ac6-11eb-879d-e29f1938ab1f.png)

got error below 
![image](https://user-images.githubusercontent.com/37807654/97673530-e3a4b080-1ac6-11eb-9b7f-bf11159c13ac.png)

but, when try to init with "io.kubernetes.client.ApiClient" , it works fine. that means the "kubeConfigContent" content is correct. I am confused, please help .
![image](https://user-images.githubusercontent.com/37807654/97673702-29fa0f80-1ac7-11eb-90b9-7e27c6985b9e.png)

**Comment by rohanKanojia** [comment]
@zengzilu: Is your kubeconfig located in `~/.kube/config`. Your don't need to give Kubernetes Client explicit config as it autodetects kubeconfig file at this location or `KUBECONFIG` environment variable. I think this should work without any problems:
```java
try (KubernetesClient kubernetesClient = new DefaultKubernetesClient()) {
     // .. Do something
}
```

**Comment by zengzilu** [comment]
for some reason, The kubeConfig didn't located in ~/.kube/config. 
but just now, I mv the kubeconfig to ~/.kube/config, and it woks at terminal with kebectl . while I try
 `KubernetesClient kubernetesClient = new DefaultKubernetesClient()`

I got the same error .
![image](https://user-images.githubusercontent.com/37807654/97674573-b6590200-1ac8-11eb-857d-1023428b9646.png)

**Comment by zengzilu** [comment]
added, it works with another kubeconfig , diff below

![image](https://user-images.githubusercontent.com/37807654/97675316-10a69280-1aca-11eb-89e5-8348c5bd98f1.png)

both configs work fine with kubectl

but TheRight one didn't work with `KubernetesClient kubernetesClient = new DefaultKubernetesClient()` while TheLeft one works fine

is it a fabric8 limit? the "kubeconfig.users[x].user" must has "client-certificate-data" and "client-key-data"? "kubeconfig.users[x].user.token" didn't work for fabric8?

**Comment by rohanKanojia** [comment]
From error stacktrace, it looks like client is not able to find certificate data at expected location. Do you have it at the correct location? If not, Could you please configure it by providing KUBERNETES_CERTS_CA_FILE environment variable: https://github.com/fabric8io/kubernetes-client#configuring-the-client

**Comment by rohanKanojia** [comment]
We use the token kubeconfig in right section with OpenShift. I can say that it works with that format. What Kind of Kubernetes Cluster are you running? Minikube? EKS?

**Comment by zengzilu** [comment]
my cluster build with kubeadm

cluster info :  
one node cluster in virtualBox of MacOS
VM image centos7
cluster version 1.19.3
![image](https://user-images.githubusercontent.com/37807654/97678153-56655a00-1ace-11eb-92a1-37b2aebdb753.png)
