### ISSUE TITLE
Simplify assertions in `kubernetes-model-generator` ServiceTest

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#2580]
These `assertTrue` assertions should be replaced with a dedicated `assertEquals` instead. For more information, see this Sonar Rule[0]

https://github.com/fabric8io/kubernetes-client/blob/ca0a124a7695b51324ab530779dbd86b735d4f94/kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/ServiceTest.java#L101-L110

[0] https://sonarcloud.io/organizations/fabric8io/rules?open=java%3AS5785&rule_key=java%3AS5785

**Comment by allupaku** [comment]
Could you please assign ? and check the pr ?
