### ISSUE TITLE
Update To Kubernetes Model 1.19

### ISSUE THREAD

**Issue by klg71** [fabric8io/kubernetes-client#2587]
Hello,

I use Kubernetes Version 1.19 and they made some changes to the Ingress model and moved it from "v1beta" to "v1".

I think the relevant Pull-Request has already been made and merged: https://github.com/fabric8io/kubernetes-client/pull/2541

I would like to ask when you plan to release a new version including this change.

**Comment by rohanKanojia** [comment]
@klg71 : Hi, Sorry for the late reply. It's been more than a month since we last released @manusa @oscerd What do you think about cutting another release with Kubernetes Model upgrade?

**Comment by rohanKanojia** [comment]
@klg71 : We just released a new version of client[0] . Please try it out and provide feedback

[0]  https://repo1.maven.org/maven2/io/fabric8/kubernetes-client/4.13.0/
