### ISSUE TITLE
Add support for server-side dry runs

### ISSUE THREAD

**Issue by gbbirkisson** [fabric8io/kubernetes-client#2588]
Add support for server-side dry runs when managing resources.

An example with kubectl:

```
kubectl create namespace mynamespace --dry-run=server
```

**Comment by rohanKanojia** [comment]
Hi, Thanks for reporting this. Are you talking about this `dryRun` query parameter in Kubernetes write APIs[0]?

dryRun:
> When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed

[0] https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#create-pod-v1-core

**Comment by gbbirkisson** [comment]
That is correct. It goes without saying that it applies to more resources than just pods :)

This is useful for multitude of reasons. For example you can see how the final resource will look after it has gone through mutation webhooks.
