### ISSUE TITLE
Restarting informers in case of errors

### ISSUE THREAD

**Issue by thmshmm** [fabric8io/kubernetes-client#2594]
Hello, 
how can informer errors be handled? In my case the informer for the CRD sometimes fails for example with JSON parse exceptions.

I am aware of registering a listener via "addSharedInformerEventListener" but trying to restart the informers using "stopAllRegisteredInformers" and "startAllRegisteredInformers" has no effect. 

When I try to only stop the informer(s) there are some background threads which are still around after using "stopAllRegisteredInformers". Closing the OpenShift client leads to exceptions reported by a watcher but the thread is still running.

Kr thms

**Comment by manusa** [comment]
Relates to: #2010 

This issue might have been tackled by the many recent improvements and refactors dealing with Shared Informers. Note that now Informers can only be started once in their lifecycle. They should be resilient and self-healing. In case of failure, it should be reported and user is responsible to regenerate them (#3050, #3073, #3013)

Please feel free to reopen the issue if it still applies.
