### ISSUE TITLE
Should be able to sort CustomResourceDefinitionVersion(s) according to their priority

### ISSUE THREAD

**Issue by adietish** [fabric8io/kubernetes-client#2599]
When listing custom resources one has by default to display them in the version with the highest priority. One thus has to be able to sort available versions (CustomResourceDefinitionVersion) by their priority.

The kubernetes docs state the following at https://v1-17.docs.kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/:
> Version priority
>
>    Regardless of the order in which versions are defined in a CustomResourceDefinition, the version with the highest priority is used by kubectl as the default version to access objects. The priority is determined by parsing the name field to determine the version number, the stability (GA, Beta, or Alpha), and the sequence within that stability level.
>
>    The algorithm used for sorting the versions is designed to sort versions in the same way that the Kubernetes project sorts Kubernetes versions. Versions start with a v followed by a number, an optional beta or alpha designation, and optional additional numeric versioning information. Broadly, a version string might look like v2 or v2beta1. Versions are sorted using the following algorithm:
>
>* Entries that follow Kubernetes version patterns are sorted before those that do not.
>* For entries that follow Kubernetes version patterns, the numeric portions of the version string is sorted largest to smallest.
>* If the strings beta or alpha follow the first numeric portion, they sorted in that order, after the equivalent string without the beta or alpha suffix (which is presumed to be the GA version).
>* If another number follows the beta, or alpha, those numbers are also sorted from largest to smallest.
>* Strings that don’t fit the above format are sorted alphabetically and the numeric portions are not treated specially. Notice that in the example below, foo1 is sorted above foo10. This is different from the sorting of the numeric portion of entries that do follow the Kubernetes version patterns.

**Comment by rohanKanojia** [comment]
@adietish : Hi, we usually specify the version in `CustomResourceDefinitionContext` for using Custom Resources:
https://github.com/fabric8io/kubernetes-client/blob/9eee87a51d08e5c3c4fa5c1af2564ba58c054f29/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java#L394

However, we also have a deprecated method that accepts `CustomResourceDefinition`. I think we should update this converter method to pick the correct version too:
https://github.com/fabric8io/kubernetes-client/blob/9eee87a51d08e5c3c4fa5c1af2564ba58c054f29/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/CustomResourceDefinitionContext.java#L50-L58

**Comment by adietish** [comment]
@rohanKanojia excellent point with the converter! I just spotted this and was up to suggest this change.
