### ISSUE TITLE
Add additional options to get logs of a pod which already provides by Kubernetes rest api

### ISSUE THREAD

**Issue by kasundsilva** [fabric8io/kubernetes-client#260]
I have been trying get logs of a running pod with fabric8 client. 

As I understand we can get logs as following,
As I understand we can get logs as following,

String log = kube.pods().inNamespace(<namespace>).withName(<pod_name>).getLog(true);

Here through the getLog() methos it provides only snapshot logs. But from Kubernetes rest api we have more flexibility to do stuff.

String url = "https://10.245.1.2/api/v1/namespaces/<namespace>/pods/<pod_name>/log?container=tomcat-server&follow=false&previous=false&timestamps=false";

As with the **URL parameters** we have more flexibility on the output to 
- Get previous terminated pod logs
- Stream the logs of pods
- Display only the most recent #of lines of pods
- Show all logs from pods written in the certain time period

**Comment by davsclaus** [comment]
+1 sounds like great functionality

**Comment by iocanel** [comment]
Merged

**Comment by kasundsilva** [comment]
When will this be released ? This is not available in v2.2.72, the latest version.

**Comment by iocanel** [comment]
most probably later today

**Comment by kasundsilva** [comment]
Great!
