### ISSUE TITLE
Is kubernetes-model-generator/model-generator-app still relevant

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#2610]
## Description

This [module](https://github.com/fabric8io/kubernetes-client/tree/d9b36fc9e267a34c26e750eafdaa80065b56b33e/kubernetes-model-generator/model-generator-app) is still in the repo. Is it used somewhere? is it still relevant?

It doesn't seem to be part of the modules listed in the parent project.

**Comment by rohanKanojia** [comment]
Hmm, I also don't see it being used anywhere. Maybe it was used in the past but is outdated now. Let's remove this.
