### ISSUE TITLE
Update jsonschema2pojo to 1.0.2

### ISSUE THREAD

**Issue by jorsol** [fabric8io/kubernetes-client#2613]
Target to 5.0.0?

**Comment by manusa** [comment]
- https://github.com/joelittlejohn/jsonschema2pojo/releases/tag/jsonschema2pojo-1.0.2
- https://search.maven.org/search?q=g:org.jsonschema2pojo%20a:jsonschema2pojo

**Comment by manusa** [comment]
Relates to: #2519

**Comment by manusa** [comment]
The separation of [`javaType`](https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#javatype) and [`existingJavaType`](https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#existingjavatype) (https://github.com/joelittlejohn/jsonschema2pojo/issues/828) presents additional challenges on the code generation side.

All definition properties should now be converted to `existingJavaType`.
All definitions that represent a native type (e.g. `String`) should also be declared as `existingJavaType`.
All definitions that must be generated should be declared as `"type": "object"` + `javaType`.
