### ISSUE TITLE
java.lang.NoClassDefFoundError: io/fabric8/kubernetes/model/util/Helper in kubernetes-client-4.13.0

### ISSUE THREAD

**Issue by suzuhasora** [fabric8io/kubernetes-client#2622]

**Comment by manusa** [comment]
Class is here: https://github.com/fabric8io/kubernetes-client/blob/v4.13.0/kubernetes-model-generator/kubernetes-model-common/src/main/java/io/fabric8/kubernetes/model/util/Helper.java

Could you provide more details?

**Comment by suzuhasora** [comment]
Thanks!
