### ISSUE TITLE
LogWatch.close don't release thread while socket.read block long time

### ISSUE THREAD

**Issue by own-idea** [fabric8io/kubernetes-client#2626]
I expect LogWatch.close method not only close OutputStream, PipedInputStream in class LogWatchCallback, but also interrupt the thread which read log from k8s apiserver . While socket.read method block long time, then responseCallback will never called, so the thread will live long time.
```java
        Response response = getResponseWithInterceptorChain();
        signalledCallback = true;
        responseCallback.onResponse(RealCall.this, response);
 ```

thanks for reply.

**Comment by own-idea** [comment]
@rohanKanojia  do you think is this a bug or should we  can improve it ?

**Comment by rohanKanojia** [comment]
@own-idea : Hi, I would need to check the code to see why `LogWatch.close()` isn't releasing thread properly. When you add `Thread.currentThread().interrupt()` do you see any improvements?

**Comment by own-idea** [comment]
> @own-idea : Hi, I would need to check the code to see why `LogWatch.close()` isn't releasing thread properly. When you add `Thread.currentThread().interrupt()` in your modified version of `LogWatch.close()` do you see any improvements?

sorry for reply so late. Because method `onResponse` will never called if k8s apiserver never send message to client.  Currently, resource release  depends on `response.close` method, also `cleanUp` method.

**Comment by rohanKanojia** [comment]
ohk, I see. Thanks a lot for reporting this. We'll look into this in upcoming sprints.
