### ISSUE TITLE
 How do I judge whether a volume is pvc or configMap？

### ISSUE THREAD

**Issue by lrul** [fabric8io/kubernetes-client#2637]
i get volumes by method pod.getSpec().getVolumes() ，but i find that each volume has all property like pvc,configMap...,so,how do i judge volume's type?

**Comment by rohanKanojia** [comment]
Umm, There doesn't seem to be any property defined for volume type on Kubernetes. I can only this of this:
```java
if (aPod.getSpec().getVolumes().get(0).getEmptyDir() != null) {
	// EmptyDir Volume
} else if (aPod.getSpec().getVolumes().get(0).getAwsElasticBlockStore() != null) {
	// AwsElasticBlockStore
} else if (...) {
	...
}
```

**Comment by lrul** [comment]
if i create a pull request that make it easier to use，it can be merged？

**Comment by rohanKanojia** [comment]
@lrul : Yes, you're welcome to create a pull request :+1: . It would be reviewed by our committers who can provide feedback on your approach. If it looks good, it would me merged :rocket:

**Comment by rohanKanojia** [comment]
bdw, what's your approach? You might want to propose it before starting working on it.

**Comment by lrul** [comment]
it would be a small feature to help user esay to get volumes that he want，just like getConfigMap，but i still dont have 
specific idea，but it will。

**Comment by rohanKanojia** [comment]
Hmm, maybe we can add a utility method for this in [KubernetesResourceUtil](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java)
