### ISSUE TITLE
The dependency version of kubernetes-model-common is 4.4.1 in client version 4.11.0/4.12.0/4.13.0

### ISSUE THREAD

**Issue by allendang001** [fabric8io/kubernetes-client#2641]
There is no Helper in kubernetes-model-common-4.4.1.jar
my code like follow 

client.load("test.yaml")
            .inNamespace("default")
            .createOrReplace();

exception:

Caused by: java.lang.NoClassDefFoundError: io/fabric8/kubernetes/model/util/Helper

**Comment by manusa** [comment]
Relates to #2622

**Comment by allendang001** [comment]
my solution is exclude kubernetes-model-common-4.4.1.jar from client.jar and add dependency kubernetes-model-common-4.13.0.jar

**Comment by rohanKanojia** [comment]
why are you using both the jars?
