### ISSUE TITLE
Deployment - update kubernetes-examples/src/main/resources/multiple-document-template.yml apiVersion

### ISSUE THREAD

**Issue by chensir9811007** [fabric8io/kubernetes-client#2642]
使用yaml文件发布总是提示io.fabric8.kubernetes.api.model.apps.Deployment cannot be cast to io.fabric8.kubernetes.api.model.extensions.Deployment

使用 kubernetes-client/kubernetes-examples/src/main/resources/multiple-document-template.yml  这个文件
代码是 List<HasMetadata> list = client.load(LoadMultipleDocumentsFromFileExample.class.getResourceAsStream("/multiple-document-template.yml")).get();
版本是 io.fabric8 4.10.1

**Comment by rohanKanojia** [comment]
@chensir9811007 : How are you able to reproduce this error? Looking at `multiple-document-template.yml` all `Deployment` objects are of `apps/v1` apiVersion. Could you please share a full reproducer?

https://github.com/fabric8io/kubernetes-client/blob/648117efe3eace21a256cc9a64e3bd23f5e94d0b/kubernetes-tests/src/test/resources/multiple-document-template.yml#L35

**Comment by chensir9811007** [comment]
could you tell me that apps/v1 & extensions/vbeta1 diff？io.fabric-4.10.1.jar use kibernetes version all？

**Comment by chensir9811007** [comment]
> @chensir9811007 : How are you able to reproduce this error? Looking at `multiple-document-template.yml` all `Deployment` objects are of `apps/v1` apiVersion. Could you please share a full reproducer?
> 
> https://github.com/fabric8io/kubernetes-client/blob/648117efe3eace21a256cc9a64e3bd23f5e94d0b/kubernetes-tests/src/test/resources/multiple-document-template.yml#L35

https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/resources/multiple-document-template.yml。see it

**Comment by rohanKanojia** [comment]
oh, I'm sorry. Looking like there were two files with same name in `kubernetes-examples/` and `kubernetes-tests/`. I think we should update this to use `apps/v1` Deployment instead:
https://github.com/fabric8io/kubernetes-client/blob/648117efe3eace21a256cc9a64e3bd23f5e94d0b/kubernetes-examples/src/main/resources/multiple-document-template.yml#L34

I can reproduce this issue on v4.10.1 but not on master. Unfortunately, `extensions/v1beta1` doesn't seem to be there in 4.10.1 . Does it work when you update `multiple-document-template.yml` to use `apps/v1` `Deployment` instead?

I think `extensions/v1beta1` Deployment is pretty outdated. We should update this to use `apps/v1` instead.

**Comment by chensir9811007** [comment]
> 
> 
> oh, I'm sorry. Looking like there were two files with same name in `kubernetes-examples/` and `kubernetes-tests/`. I think we should update this to use `apps/v1` Deployment instead:
> 
> https://github.com/fabric8io/kubernetes-client/blob/648117efe3eace21a256cc9a64e3bd23f5e94d0b/kubernetes-examples/src/main/resources/multiple-document-template.yml#L34
> 
> I can reproduce this issue on v4.10.1 but not on master. Unfortunately, `extensions/v1beta1` doesn't seem to be there in 4.10.1 . Does it work when you update `multiple-document-template.yml` to use `apps/v1` `Deployment` instead?
> 
> I think `extensions/v1beta1` Deployment is pretty outdated. We should update this to use `apps/v1` instead.

thank you!

**Comment by rohanKanojia** [comment]
@chensir9811007: polite ping, Would you like to create a PR to update from `kubernetes-client/kubernetes-examples/src/main/resources/multiple-document-template.yml` `extensions/v1beta1` to `apps/v1`?

**Comment by rohanKanojia** [comment]
ohk, let me do it.
