### ISSUE TITLE
Include Patch Methods in generic resource/ resource list API

### ISSUE THREAD

**Issue by saparaj** [fabric8io/kubernetes-client#2647]
Along with https://github.com/fabric8io/kubernetes-client/issues/2645, Is it possible to have patch methods in generic resource/ resource list API?

Currently I can see only way to call patch methods is on specific resource - client.services().inNamespace(namespace).withName(resource.getMetadata().getName()).patch((Service)resource)

Thanks,
Swarda

**Comment by rohanKanojia** [comment]
@shawkins : Could you please share your thoughts on this? Do you think it's a good idea?

**Comment by shawkins** [comment]
@rohanKanojia I've added editable to resource(HasMetadata) in #3364 - the intention would be to eventually make that return a Resource, which would be patchable as well.  I haven't yet added that for resourceList, but it could certainly be done as well.  Alternatively you can now do things more generically using the resources method:

```
KubernetesClient client = ...
List<HasMetadata> resources = ...
resources.forEach(meta -> client.resources(meta.getClass()).withName(...).inNamespace(...).someOperation);
```
