### ISSUE TITLE
jdk1.6兼容

### ISSUE THREAD

**Issue by chensir9811007** [fabric8io/kubernetes-client#2648]
Kubernates-client是否可以兼容jdk1.6，如何修改可以兼容？

**Comment by rohanKanojia** [comment]
@chensir9811007 : Hello, Are you asking about Kubernetes-client's compatibility with JDK 6?

**Comment by chensir9811007** [comment]
> 
> 
> @chensir9811007 : Hello, Are you asking about Kubernetes-client's compatibility with JDK 6?

yes

**Comment by rohanKanojia** [comment]
Our project seems to be at JDK 8 right now. I've never tried out client on JDK 6 so I'm can't say without testing it out. Do you face any problems while trying out project on JDK 6?

**Comment by chensir9811007** [comment]
> Our project seems to be at JDK 8 right now. I've never tried out client on JDK 6 so I'm can't say without testing it out. Do you face any problems while trying out project on JDK 6?

run JDK6  java.lang.UnsupportedClassVersionError: io/fabric8/kubernetes/client/KubernetesClient : Unsupported major.minor version 52.0

**Comment by rohanKanojia** [comment]
ohk, Thanks for reporting this. Will try to reproduce. However, I would advise you to upgrade to JDK 8. JDK 6 seems pretty old ...

**Comment by manusa** [comment]
We are not going to provide support for JDK 6.
I think a more realistic question is until when are we going to support JDK 8.
