### ISSUE TITLE
PodAffinityTerm ignore empty "namespaces" parameter when JSON decode

### ISSUE THREAD

**Issue by openxxs** [fabric8io/kubernetes-client#2649]
![image](https://user-images.githubusercontent.com/2329125/101337796-122c5d00-38b7-11eb-9e8c-6bdd65ff58ad.png)
@JsonInclude(Include.NON_EMPTY) will ignore "namespaces: []",
BUT "namespaces: []" stands for all namespaces in kubernetes podAffinity and podAntiAffinity, it should not be ignored.

**Comment by rohanKanojia** [comment]
We generate our model from kubernetes source. It's marked as `omitempty` in Kubernetes source too[0]

[0] https://github.com/kubernetes/api/blob/master/core/v1/types.go#L2780

**Comment by openxxs** [comment]
I am sorry, It's my fault. Kubernetes offical document says "If omitted or empty, it defaults to the namespace of the pod where the affinity/anti-affinity definition appears."
