### ISSUE TITLE
Find way to capture unintended changes in semantics or api

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#2650]
The `kubernetes-client` does try to stay true to semnatic versioning as much as possible (at least for major changes).

Still, there are changes that may untintentionally change things, for example:

- a change in kubernetes/openshift code itself
- a change in the generator code
- an internal change that affects the client behavior.

I am pretty sure that there is tooling out there that could ensure that we capture changes in our public API during CI.

In addition, there might be tools that check the structure of the HTTP requests the client generates under a fixed set of circumstances. Even if they don't we do have our own mocking framework, so we could possibly extract infomration for there.

These are just some ideas we could possibly use to further guard our users.

**Comment by manusa** [comment]
Relates to: https://github.com/fabric8io/kubernetes-client/issues/2518

**Comment by maxandersen** [comment]
Revapi is what we are looking at in quarkus to do this. For Kubernetes which is much smaller it should be fairly easy to enable.
