### ISSUE TITLE
How to deploy Kubeflow in fabric8?

### ISSUE THREAD

**Issue by raven-jia** [fabric8io/kubernetes-client#2654]
Hi, I'm trying to connect to k8s from my java program using fabric. I have kubeflow/pytorchjob installed on the k8s, however, fabric8 client can not connect to it, saying "no resource type found kubeflow.org/v1#pytorchjob". Do you know how to fix this problem without creating kubeflow as a CRD from fabric8? Thanks!!

**Comment by rohanKanojia** [comment]
Could you please share code that you're using to deploy?

**Comment by raven-jia** [comment]
> Could you please share code that you're using to deploy?
Thanks for the reply. Here's the code

`      


        
        parallelWorkerString = FTLUtils.renderTemplate("PytorchJob.ftl", model);
        try {
            InputStream is = IOUtils.toInputStream(parallelWorkerString, "UTF-8");
            List<HasMetadata> result = k8SClusterConfig.getClient(cluster).load(is).get();
            log.info("load result: {}", JSON.toJSONString(result));
            List<HasMetadata> list = k8SClusterConfig.getClient(cluster).resourceList(result).createOrReplace();
            log.info("resourceList result: {}", JSON.toJSONString(list));
      } ...
`

**Comment by rohanKanojia** [comment]
Do you have POJO for `pytorchjob` Custom resource? If yes, you can try registering it to `KubernetesDeserializer` like this:
```
KubernetesDeserializer.registerCustomKind("kubeflow.org/v1", "PyTorchJob", PyTorchJob.class);
```

If you don't have POJO, I would suggest using the [Raw API for CustomResources](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#customresource-typeless-api)

**Comment by raven-jia** [comment]
> Do you have POJO for `pytorchjob` Custom resource? If yes, you can try registering it to `KubernetesDeserializer` like this:
> 
> ```
> KubernetesDeserializer.registerCustomKind("kubeflow.org/v1", "PyTorchJob", PyTorchJob.class);
> ```
> 
> If you don't have POJO, I would suggest using the [Raw API for CustomResources](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#customresource-typeless-api)

The raw api for crd worked!! It's exactly what I needed. Thanks a lot

**Comment by manusa** [comment]
I'm closing this issue now, feel free to open another issue if you encounter any problem.
