### ISSUE TITLE
Cannot handle non-base64 encoded cert/key data

### ISSUE THREAD

**Issue by JoshuaAndrew** [fabric8io/kubernetes-client#266]
io.fabric8.kubernetes.client.internal.CertUtils.getInputStreamFromDataOrFile(String data, String file)
and  io.fabric8.kubernetes.client.internal.CertUtils.decodePem(InputStream keyInputStream)
getInputStreamFromDataOrFile  do not need  "-----BEGIN"  but  decodePem need it

anyone come across this issue!

**Comment by jimmidyson** [comment]
Haven't seen this. Can you give a bit more detail on how to reproduce?

**Comment by davsclaus** [comment]
do you mind changing the title to be english

**Comment by JoshuaAndrew** [comment]
ConfigBuilder builder = new ConfigBuilder();
	builder.withMasterUrl(server);
	builder.withApiVersion(ReplicationController.ApiVersion.V_1.toString());
	builder.withConnectionTimeout(3600000);
	builder.withWatchReconnectInterval(2);
	builder.withWatchReconnectLimit(10);
	builder.withRequestTimeout(36000);
	builder.withUsername(username);
		
	//builder.withCaCertData(caCertData);
        //builder.withClientCertData(clientCertData);
	//builder.withClientKeyData(clientKeyData);
		
	builder.withCaCertFile("E:\\isoftstone\\workspacedeis\\svc-container\\svc-container-provider\\src\\main\\resources\\ca.crt");
	builder.withClientCertFile("E:\\isoftstone\\workspacedeis\\svc-container\\svc-container-provider\\src\\main\\resources\\client-develop.crt");
	builder.withClientKeyFile("E:\\isoftstone\\workspacedeis\\svc-container\\svc-container-provider\\src\\main\\resources\\client-develop.key");
		
	Config kubeConfig = builder.build();
	KubernetesClient kubeClient = new DefaultKubernetesClient(kubeConfig);

withCaCertFile,withClientCertFile,withClientKeyFile  is ok
but withCaCertData withClientCertData  withClientKeyData   is error

**Comment by JoshuaAndrew** [comment]
Today I fixed this issue
io.fabric8.kubernetes.client.internal.CertUtils.getInputStreamFromDataOrFile(String data, String file)
change this ByteArrayInputStream(ByteString.decodeBase64(data).toByteArray())     to ByteArrayInputStream(data.getBytes())

**Comment by jimmidyson** [comment]
The use case was using kube config files which include the cert data base 64 encoded.

We can add this in so if the data isn't base64 encoded we can use that too.
