### ISSUE TITLE
Usage of client and error/exception handling

### ISSUE THREAD

**Issue by nknkgithub** [fabric8io/kubernetes-client#2677]
Hi,

I am new to Kubernetes and I want to know usage kubernetes-client with respect to following scenarios

1. I want to contact remote kubernetes cluster and I have contents of kubeconfig file. If I want to construct config object then 

     _Config config = new ConfigBuilder().withMasterUrl("https://ip:6443").withCaCertData(cacert)
				.withClientKeyData(clientKeyData).withClientCertData(clientCertificateData).build(); 
     KubernetesClient client = new DefaultKubernetesClient(config)_

     this is the right way to construct object and form client? and is there any option for 

     - having "--insecure-skip-tls-verify" in above builder?

     - having token field ?

     - does it support oidc paramaters?

     - And if there are any errors in certificates or if server url is not proper, then the specific error is thrown or any exception       should be catched. How error/exception should be handled?

     -  Any method available which will confirm we are able to contact remote kubernetes cluster? or should we make use of getpods/nodes functions to make sure we are able to reach remote kubernetes cluster?

     -  Is there any option with which we can create kubeconfig file with the contents.

2. If equivalent of kubectl apply -f <yaml file> _i.e. https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/kubectl/equivalents/CreateOrReplaceResourceList.java_ is used , then if it fails or throws error then how it should be handled? 
3. Can we get json response for all apis used, i.e how we get via kubectl get pods -o json
4. If apply fails , due to some error then errors/exceptions are thrown? If so then how those errors/exceptions should be handled? those errors are thrown ?
5. In general how errors/exceptions will be thrown and how it should be handled in case of kubectl equivalent apis fails? 

Examples for above scenarios will be helpful

**Comment by nknkgithub** [comment]
Help is required

**Comment by rohanKanojia** [comment]
>I want to contact remote kubernetes cluster and I have contents of kubeconfig file. If I want to construct config object then

You don't need to worry about constructing `Config` object. KubernetesClient automatically builds a Config by inspecting your `~/.kube/config` or `ServiceAccount` details.

>Config config = new ConfigBuilder().withMasterUrl("https://ip:6443").withCaCertData(cacert)
.withClientKeyData(clientKeyData).withClientCertData(clientCertificateData).build();
KubernetesClient client = new DefaultKubernetesClient(config)

>this is the right way to construct object and form client? and is there any option for

>having "--insecure-skip-tls-verify" in above builder?

I'm not sure about this. Could you please try with `withTrustCerts(false)`?

> having token field ?

We have a `withOAuthToken()` which is used for token configuration

>does it support oidc parameters?

Could you please elaborate? We do have support for OIDC tokens and OIDC token refresh.

>And if there are any errors in certificates or if server url is not proper, then the specific error is thrown or any exception should be catched. How error/exception should be handled?

You would usually use client like this:
```java
try (final KubernetesClient client = new DefaultKubernetesClient()) {
  // Do stuff with client
} catch (KubernetesClientException ex) {
  // handle exception
}
```

>Any method available which will confirm we are able to contact remote kubernetes cluster? or should we make use of getpods/nodes functions to make sure we are able to reach remote kubernetes cluster?

KubernetesClient will most likely throw an exception in case it fails to connect to Kubernetes Cluster.

>Is there any option with which we can create kubeconfig file with the contents.

I think you should be able to do it using `io.fabric8.kubernetes.api.model.ConfigBuilder` to build a `KubeConfig` and then write it to file using `KubeConfigUtils.persistKubeConfigIntoFile`

>If equivalent of kubectl apply -f i.e. https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/kubectl/equivalents/CreateOrReplaceResourceList.java is used , then if it fails or throws error then how it should be handled?

Hmm, there should be a catch block for `KubernetesClientException` below that. I've shared an example above on how you should handle exception

>Can we get json response for all apis used, i.e how we get via kubectl get pods -o json

I think you should be able to it with something like this:
```java
try (KubernetesClient client = new DefaultKubernetesClient()) {
    // Get PodList object from API Server
    PodList podList = client.pods().inNamespace("rokumar-code").list();

    // Serialize Object to JSON String
    String jsonOutput = Serialization.jsonMapper().writeValueAsString(podList);
    
    // Print it
    System.out.println(jsonOutput);

} catch (JsonProcessingException e) {
    e.printStackTrace();
}
```

>If apply fails , due to some error then errors/exceptions are thrown? If so then how those errors/exceptions should be handled? those errors are thrown ?

KubernetesClient usually throws `KubernetesClientException` on APIServer errors which contains status code and other details about falures. You would need to catch it and handle it accordingly.

>In general how errors/exceptions will be thrown and how it should be handled in case of kubectl equivalent apis fails?

I don't understand. Could you please elaborate?

**Comment by nknkgithub** [comment]
Thanks @rohanKanojia for help.

I have a question, i.e.

i) I want to check whether a resource exists or not. i.e. kubectl get pod <podname> -o json. So equivalent of this is available? and output of kubectl commandline and json will be same? and I need to parse it to get status?
ii) I wanted to know when I apply object i.e using createOrReplace (equivalent of kubectl apply -f file) then whether object is successfully created or not and its status equivalent of kubectl (pending, success, error, configuration updated). How this can be done?
iii) And output of kubectl apply -f <file> -o json and the equivalent createOrReplace are same?
iv) Regarding oidc

    _kubectl config set-credentials USER_NAME \
       --auth-provider=oidc \
       --auth-provider-arg=idp-issuer-url=( issuer url ) \
       --auth-provider-arg=client-id=( your client id ) \
       --auth-provider-arg=client-secret=( your client secret ) \
       --auth-provider-arg=refresh-token=( your refresh token ) \
       --auth-provider-arg=idp-certificate-authority=( path to your ca certificate ) \
       --auth-provider-arg=id-token=( your id_token )_ 

this equivalent is available, i.e. can we construct this using kubernetes config builder?
v) Refreshing tokens using oidc is available, i.e. equivalent how kubectl refreshes tokens?
vi) createOrReplace is equivalent of kubectl apply, so any yaml file I can apply(i.e no need to know resource type? ) and I convert response to String jsonOutput as shown above ?

**Comment by rohanKanojia** [comment]
If you're interested in Kubectl equivalents, maybe you can take a look at this list[0]

[0] https://github.com/fabric8io/kubernetes-client#kubectl-java-equivalents

**Comment by rohanKanojia** [comment]
> Thanks @rohanKanojia for help.
> 
> I have a question, i.e.
> 
> i) I want to check whether a resource exists or not. i.e. kubectl get pod -o json. So equivalent of this is available? and output of kubectl commandline and json will be same? and I need to parse it to get status?

I think you should be able to do it easily `client.pods().inNamespace("xyz").list()` should give you the list and then you can use `Serialization.jsonMapper().writeValueAsString(list)` to convert it to JSON. However, I feel you don't need to convert it to json to read status. You can simply iterate over podlist and get status.

> ii) I wanted to know when I apply object i.e using createOrReplace (equivalent of kubectl apply -f file) then whether object is successfully created or not and its status equivalent of kubectl (pending, success, error, configuration updated). How this can be done?


> iii) And output of kubectl apply -f -o json and the equivalent createOrReplace are same?

KubernetesClient returns whatever Kubernetes API returns, I don't know for sure but it should be the same. Unless `kubectl` adds some extra stuff.

> iv) Regarding oidc
> 
> ```
> _kubectl config set-credentials USER_NAME \
>    --auth-provider=oidc \
>    --auth-provider-arg=idp-issuer-url=( issuer url ) \
>    --auth-provider-arg=client-id=( your client id ) \
>    --auth-provider-arg=client-secret=( your client secret ) \
>    --auth-provider-arg=refresh-token=( your refresh token ) \
>    --auth-provider-arg=idp-certificate-authority=( path to your ca certificate ) \
>    --auth-provider-arg=id-token=( your id_token )_ 
> ```
> 
> this equivalent is available, i.e. can we construct this using kubernetes config builder?

I'm not sure if this is supported.

> v) Refreshing tokens using oidc is available, i.e. equivalent how kubectl refreshes tokens?

Yes
> vi) createOrReplace is equivalent of kubectl apply, so any yaml file I can apply(i.e no need to know resource type? ) and I convert response to String jsonOutput as shown above ?

CreateOrReplace doesn't ignore updates when it applied again and again without any change, see #2454
