### ISSUE TITLE
exec and writing to stdin doesn't work with okhttp 2.6.0+

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#268]
We either need to investigate and fix the root cause, or rollback to 2.5.0, as this is a blocker.

**Comment by jimmidyson** [comment]
Agreed. I just can't find the root cause...

**Comment by jimmidyson** [comment]
Admission: I'm an idiot. Dropped sending the stream ID when sending stuff through... Fixing now.
