### ISSUE TITLE
How to translate the Deployment to yaml

### ISSUE THREAD

**Issue by yangjinlogic** [fabric8io/kubernetes-client#2680]
How to translate the Deployment to yaml,such as the  command: kubectl get deploy **** -o yaml

**Comment by yangjinlogic** [comment]
I need your help,please

**Comment by rohanKanojia** [comment]
`SerializationUtils.dumpAsYaml(deployment)` should return `Deployment` as YAML string. You can then either write it to a file or use it somewhere else.

**Comment by yangjinlogic** [comment]
> `SerializationUtils.dumpAsYaml(deployment)` should return `Deployment` as YAML string. You can then either write it to a file or use it somewhere else.

Thank you for your help，I have anothor issue,whether the SDK support trafik?Do you develop a SDK support Helm?please.

**Comment by rohanKanojia** [comment]
Umm, we have got these extensions:
- Knative
- Tekton
- Istio
- ServiceCatalog
- ChaosMesh
- VolumeSnapshot 

At the moment we don't have extension for traefik or Helm. Could you please create an issue ?
