### ISSUE TITLE
What's the difference between create and createOrReplace?

### ISSUE THREAD

**Issue by yangjinlogic** [fabric8io/kubernetes-client#2696]
What's the difference between create and createOrReplace?Whether if the RC existed it will replace it?

**Comment by rohanKanojia** [comment]
@yangjinlogic : Hi, as per current implementation `create` just does a POST request to APIServer. `createOrReplace` also does POST but it has a fallback approach of doing a PUT in case 409 is received in the initial POST request. We are discussing to refactor createOrReplace(#2454 ) to behave more like `kubectl apply`(which ignores updates when there is no modification as compared to previous applied resource). Would appreciate it if you could share feedback on that.

**Comment by manusa** [comment]
> Whether if the RC existed it will replace it?

Yes

> ...behave more like kubectl apply(which ignores updates when there is no modification as compared to previous applied resource)...

**If** the applicable resource was created previously using kubectl apply (The resource contains an annotation `kubectl.kubernetes.io/last-applied-configuration` with a JSON representation of the originally **applied** resource)
