### ISSUE TITLE
how to get resource describe info for pod,node and custom resource 

### ISSUE THREAD

**Issue by dzfancy** [fabric8io/kubernetes-client#2698]
I want to describe of my pod in kubernetes by client,In kubernetes cluster we can use `kubectl describe pods <podName>`,but i want to get same information by fabric8io/kubernetes-client,what shold i do

**Comment by rohanKanojia** [comment]
@dzfancy : Hi, Are you looking for any information in `kubectl describe` output in particular.I think you able to do it using this:
```java
try (KubernetesClient client = new DefaultKubernetesClient()) {
  Pod pod = client.pods().inNamespace("xyz").withName("podName").get();
  // Get Pod Spec .spec
  PodSpec podSpec = pod.getSpec();
  // Get Pod Status .status
  PodStatus podStatus = pod.getStatus();
}
```
