### ISSUE TITLE
Equivalent of @EnableKubernetesMockClient for OpenshiftClient?

### ISSUE THREAD

**Issue by jarebudev** [fabric8io/kubernetes-client#2699]
Hi,

Is there an equivalent for ```@EnableKubernetesMockClient``` for the OpenShiftClient? 

```
@EnableOpenshiftMockClient
class ExampleTest {

    OpenShiftClient client;

    @Test
    public void testInStandardMode() {
            ...
    }
}
```

**Comment by manusa** [comment]
This feature was recently added #2320  and there is yet no `OpenShiftClient` equivalent available.

A proper extended extension could be created under the `openshift-server-mock` module.
