### ISSUE TITLE
How to update or patch a k8s resource ?

### ISSUE THREAD

**Issue by AllenZMC** [fabric8io/kubernetes-client#2701]
How to update or patch a k8s resource ? For example, pod or service , etc.

**Comment by rohanKanojia** [comment]
We support full resource patching like this:
```java
client.pods().inNamespace(namespace).withName(podName).patch(updatedPod);
```

**Comment by AllenZMC** [comment]
Thanks! @rohanKanojia

**Comment by AllenZMC** [comment]
`Create or Replace some Pod with some existing object:
client.pods().inNamespace("default").createOrReplace(aPod)`
What does this mean and when is it used?

**Comment by rohanKanojia** [comment]
`createOrReplace()` somewhat similar to `kubectl apply`, but there is a difference. It doesn't ignore PUT when you try to issue `createOrReplace()` multiple times on a same resource (#2454 ). You would want to use it for creating resources if you're not sure if it already exists in the cluster not.
