### ISSUE TITLE
How to repleace System.out in ExecWatch

### ISSUE THREAD

**Issue by yangjinlogic** [fabric8io/kubernetes-client#2704]
I need to deployment a terminal of Pod,This is my code:

 InputStream inputStream = new ByteArrayInputStream(message.getBytes());
        OutputStream outputStream = new ByteArrayOutputStream();

        ExecWatch watch = kubernetesClientContainer.getClient().pods().inNamespace(namespace).withName(podName).readingInput(inputStream)
                .writingOutput(outputStream)
                .writingError(System.err)
                .withTTY()
                .usingListener(new SimpleListener())
                .exec();
        return  outputStream.toString();

but I cant get the data of outputStream,it will be ok if I use System.out

**Comment by rohanKanojia** [comment]
@yangjinlogic : Hi, Could you please check this example which uses `writingOutput` and `writingError` with `ByteArrayOutputStream`:

https://github.com/fabric8io/kubernetes-client/blob/6a7a7e406b5405bae2bb8219bda1bffe7ff5d7c8/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ExecuteCommandOnPodExample.java#L69-L75

**Comment by yangjinlogic** [comment]
@rohanKanojia   I use the example code,I can run the command such as "ls"、“df -h”, but I run command "cd",show this 
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"cd\": executable file not found in $PATH": unknown

**Comment by yangjinlogic** [comment]
@rohanKanojia Whether  the example code can ensure the command is successive?

**Comment by yangjinlogic** [comment]
I can run perfect in my example,and it look like a real terminal,I only can't get the data of outputStream,I am confused

**Comment by manusa** [comment]
for cd commands and such, you'll need to run those within a shell:
```
command("sh", "-c", "cd $dir && ls ")
```

**Comment by yangjinlogic** [comment]
@manusa  I can run cd command successful use the code:  ExecWatch watch = kubernetesClientContainer.getClient().pods().inNamespace(namespace).withName(podName).readingInput(System.in)
                .writingOutput(System.out)
                .writingError(System.out)
                .withTTY()
                .usingListener(new Simp())
                .exec();

but I can't run command successful use the code:
return client.pods() 
              .inNamespace(pod.getMetadata().getNamespace()) 
              .withName(pod.getMetadata().getName()) 
              .writingOutput(baos) 
              .writingError(baos) 
              .usingListener(new SimpleListener(data, baos)) 
              .exec(command);

**Comment by manusa** [comment]
Bu have you tried encapsulating the command within an sh -c as I described?

**Comment by yangjinlogic** [comment]
@manusa   yes,succeed.but I need develop a terminal of Pod,Whether I need to input " "sh","-c","cd bin" " if I want to run the command "cd bin"
