### ISSUE TITLE
Make BackwardCompatibilityInterceptor configureable

### ISSUE THREAD

**Issue by lennartfricke** [fabric8io/kubernetes-client#2716]
I've encounter problems similar to #2300 for deployments.
Accessing a non existing deployment does not result in "404 not found" but in permission denied,
mentioning extensions api group instead of apps. There is a role configured with access to apps/deployments
but not extensions/deployment.

I think the reason is the same as in #2300. The BackwardCompatibilityInterceptor converts the request to the
extension api group.

Maybe it would be good to document that behaviour more clearly and have an option to disable it.

**Comment by manusa** [comment]
We should at least add an option in the Configuration to disable the interceptor.

This would at least allow us to offer a workaround in case of future problems.
