### ISSUE TITLE
Readiness utility should be able to support extension

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#2718]
Currently the readiness utility only supports kubernetes resources.

We should use the spi in order to optionally extend the behavior to openshift, knative etc resources.

**Comment by rohanKanojia** [comment]
Umm, I think we do have Readiness supported for OpenShift resources[0]. 

https://github.com/fabric8io/kubernetes-client/blob/master/openshift-client/src/main/java/io/fabric8/openshift/client/internal/readiness/OpenShiftReadiness.java

**Comment by iocanel** [comment]
That's awesome!
I think that we need to use the spi, so that we have a signle readiness utility exposed.

**Comment by manusa** [comment]
`isReady` is an internal, subjective concept of the Fabric8 client which might or might not match what other tools consider as a `Ready` Kubernetes object (kubectl, Kubernetes dashboard(s), and so on).

We should encourage users to rely on the `waitUntilConditon` and other methods.

> Given some of the confusion with what isReady is supposed to do (https://github.com/fabric8io/kubernetes-client/issues/3474), it may be best just to direct people toward using their own predicates and leave the built-in readiness as is for now.

So yes, +1.

> It does appear some of the extension models have status ready and/or replica fields - it would be nice where applicable to at least put a static method for that resource type on the XXXClient interface.

I think this is aligned with the similar #3586 (and #3816)
