### ISSUE TITLE
ObjectMeta is ignored in Deserialization

### ISSUE THREAD

**Issue by mmanciop** [fabric8io/kubernetes-client#2722]
Hello there,

I am using fabric8 inside an Admission Controller Mutating Webhook, and I am having issues because the ObjectMeta is thrown away in deserialization. This is the decompiled code I get in the dependency:

```
@JsonDeserialize(using = com.fasterxml.jackson.databind.JsonDeserializer.None.class)
@ToString
@EqualsAndHashCode
@Buildable(editableEnabled = false, validationEnabled = false, generateBuilderPackage = true, lazyCollectionInitEnabled = false, builderPackage = "io.fabric8.kubernetes.api.builder", inline = @Inline(type = Doneable.class, prefix = "Doneable", value = "done"))
public class ObjectMeta implements KubernetesResource
```

What is the rationale for not deserializing `ObjectMeta`?

Best,
  Michele

**Comment by manusa** [comment]
If you're talking about this `@JsonDeserialize(using = com.fasterxml.jackson.databind.JsonDeserializer.None.class)`

This **doesn't** translate in _"for not deserializing `ObjectMeta`"_. This means that no custom deserializer is used for this class, but it is deserielized (---> not to be confused with `@JsonIgnore`)

If ObjectMeta is field is not getting populated, there must be some other reason.

**Comment by mmanciop** [comment]
Hi @manusa,

Yeah, I see that `@JsonDeserialize` annotation on other classes that actually do get deserialized correctly.
Any idea where I could start digging for the reasons of the failed deserialization of `ObjectMeta`?

**Comment by mmanciop** [comment]
It definitely looks like something non immediately related to Jackson, because this test passes:

```
    @Test
    void testPodMetaSerialization() throws Exception {
        final PodSpec podSpec = new PodSpec();

        final Pod pod = new PodBuilder()
            .withMetadata(new ObjectMetaBuilder().addToLabels(Collections.singletonMap("FOO", "BAR")).build())
            .withSpec(podSpec)
            .build();

        final ObjectMapper objectMapper = new ObjectMapper();
        final String serialized = objectMapper.writeValueAsString(pod);

        final Pod deser = objectMapper.readValue(serialized, Pod.class);

        assertThat(deser.getMetadata().getLabels()).containsKeys("FOO");
    }
```

**Comment by mmanciop** [comment]
OK, this was all a _HUGE_ PBKAC ;-)
In an end-to-end test I was referring to a stale object :-(

**Comment by manusa** [comment]
> OK, this was all a _HUGE_ PBKAC ;-)
> In an end-to-end test I was referring to a stale object :-(

No worries, it was clear that the problem somewhere different to jackson since ObjectMeta is heavily used in most resource, so probably the most tested class in the project.

It's good news you found the root-cause.
Thx for using the project, happy codings ;)
