### ISSUE TITLE
feat request : load a yaml for undefiled model type

### ISSUE THREAD

**Issue by Rajpratik71** [fabric8io/kubernetes-client#2728]
As far as i am able to find that , client library needs and only support predefined "models" for loading a yaml into that 

e.g.

`
    try (final KubernetesClient k8s = new DefaultKubernetesClient()) {
      CustomResourceDefinition crd = k8s.apiextensions().v1()
        .customResourceDefinitions()
        .load(LoadAndCreateCustomResourceDefinition.class.getResourceAsStream("/test-crd.yaml"))
        .get();
      k8s.apiextensions().v1().customResourceDefinitions().create(crd);
`

So , here my question and issue is how to load/apply following yaml using "kubernetes-client" library.

Below providing yaml for " Scheduling Policy" used by [Intel's Telemetry aware scheduler ](https://github.com/intel/telemetry-aware-scheduling) or many other as Kubernetes supports extending of "Kube-scheduler" by addons.

**[DeschedulerPolicy](https://github.com/intel/telemetry-aware-scheduling/blob/master/deploy/health-metric-demo/descheduler-policy.yaml)**

`
apiVersion: "descheduler/v1alpha1" 
kind: "DeschedulerPolicy" 
strategies: 
  "RemovePodsViolatingNodeAffinity": 
    enabled: true 
    params: 
      nodeAffinityType: 
        - "requiredDuringSchedulingIgnoredDuringExecution" 
`

**[TASPolicy](https://github.com/intel/telemetry-aware-scheduling/blob/master/deploy/health-metric-demo/health-policy.yaml)**

`
apiVersion: telemetry.intel.com/v1alpha1
kind: TASPolicy
metadata:
  name: demo-policy
  namespace: default
spec:
  strategies:
    deschedule:
      rules:
      - metricname: health_metric
        operator: Equals
        target: 2
    dontschedule:
      rules:
      - metricname: health_metric
        operator: Equals
        target: 1
      - metricname: health_metric
        operator: Equals
        target: 2
    scheduleonmetric:
      rules:
      - metricname: health_metric
        operator: LessThan
`

**Comment by rohanKanojia** [comment]
I think you should try our Raw CustomResource API:

https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#customresource-typeless-api

**Comment by Rajpratik71** [comment]
Thanks
