### ISSUE TITLE
how to make proxy in java client ?

### ISSUE THREAD

**Issue by sunnoy** [fabric8io/kubernetes-client#2729]
client -> proxy(client java) ->  kube-api 

proxy can help client authentication to kube-api

is java client give something like clien-go's 

```go
// TransportFor returns an http.RoundTripper that will provide the authentication
// or transport level security defined by the provided Config. Will return the
// default http.DefaultTransport if no special case behavior is needed.
func TransportFor(config *Config) (http.RoundTripper, error) {
	cfg, err := config.TransportConfig()
	if err != nil {
		return nil, err
	}
	return transport.New(cfg)
}
```

**Comment by manusa** [comment]
If you are referring to a port forwarding functionality, maybe you can check this example:
https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/PortForwardExample.java

**Comment by sunnoy** [comment]
thks ！ get it ！

**Comment by liziwl** [comment]
> If you are referring to a port forwarding functionality, maybe you can check this example: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/PortForwardExample.java
> 
> Or maybe you are referring to some sort of `kubectl proxy` command equivalent?

how to use `kubectl proxy` in this client?
