### ISSUE TITLE
Question on fips compliance

### ISSUE THREAD

**Issue by SubhraB** [fabric8io/kubernetes-client#2732]
We are using the k8s client version 4.13.0. 

I was looking at this class. `io.fabric8.kubernetes.client.internal.CertUtils`

Specifically the code below, which I see multiple instances of.
` KeyStore trustStore = KeyStore.getInstance("JKS");`

The above line of code becomes invalid when we run our application on fips mode, since the truststore format becomes BCFKS. We expect something like this.
`KeyStore trustStore = KeyStore.getInstance(KeyStore.getDefaultType());`

Is there a way to override that to make us fips compliance. FYI, we are not allowed to make insecure https calls, we have to use a truststore in BCFKS format

**Comment by DimoDonchev** [comment]
I am having the same issuе here. Really hope this gets checked out.

**Comment by gulyaev13** [comment]
@SubhraB , @DimoDonchev , I've created PR with a fix. Hope that it will be merged and solve our problem.
https://github.com/fabric8io/kubernetes-client/pull/2788

**Comment by SubhraB** [comment]
I got around it by not using the default k8s client. Buts its a little pain.

**Comment by manusa** [comment]
#2788 was merged and will be released as part of [5.4.0](https://github.com/fabric8io/kubernetes-client/milestone/23)
