### ISSUE TITLE
How to set Custom Resource version, kind and group dynamically on v5.0.0

### ISSUE THREAD

**Issue by LukaTchumburidze** [fabric8io/kubernetes-client#2738]
Kubernetes Client v5.0.0 provides annotations of version, kind and group for custom resources, however this reduces generalization ability for a class extending CustomResource class, one child can have one set of statically written annotations. Is there any way to dynamically change those values, or from 5.0.0 onwards this is not supported? In examples I could not find such case.

**Comment by rohanKanojia** [comment]
I haven't tried this myself but could you please try providing `CustomResourceDefinitionContext` in `customResource` method like this:

https://github.com/fabric8io/kubernetes-client/blob/671ffb3802745603d08782f451b9a3df75a097ea/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/TypedCustomResourceApiTest.java#L61

**Comment by rohanKanojia** [comment]
ohk, we have this method but looks like it doesn't work. This fails with this error even if I provide `CustomResourceDefinitionContext` in the method linked above:
```
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `io.fabric8.crd.CronTab`, problem: io.fabric8.crd.CronTab CustomResource must provide an API version using @io.fabric8.kubernetes.model.annotation.Group and @io.fabric8.kubernetes.model.annotation.Version annotations
 at [Source: (String)"{"apiVersion":"stable.example.com/v1","kind":"CronTab","metadata":{"name":"my-new-cron-object"},"spec":{"cronSpec":"* * * * */5","image":"my-awesome-cron-image","replicas":3}}"; line: 1, column: 2]
	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
```

bdw, Could you please elaborate your use case? Why do you want to set version, kind, and group dynamically? I think there should be two separate classes for two different CustomResources. Even if they are same with different versions, they should be in different packages(just like we have resources with same kind but different apiGroup in core Kubernetes Model)

**Comment by metacosm** [comment]
We should indeed check that we cover all the cases but I'd like more details on the use case here so that we can figure out if it's something that we need to fix.

**Comment by manusa** [comment]
I think he's probably hitting what we discussed about reusing same POJOs for different CRD versions, plus changing these fields at runtime via configuration.

If this is the case, (I haven't tried this but) I think you can overcome this by implementing the `getVersion` and `getGroup` methods in `CustomResource`<`HasMetadata` and feed those values however you want.

**Comment by LukaTchumburidze** [comment]
> ohk, we have this method but looks like it doesn't work. This fails with this error even if I provide `CustomResourceDefinitionContext` in the method linked above:
> 
> ```
> Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `io.fabric8.crd.CronTab`, problem: io.fabric8.crd.CronTab CustomResource must provide an API version using @io.fabric8.kubernetes.model.annotation.Group and @io.fabric8.kubernetes.model.annotation.Version annotations
>  at [Source: (String)"{"apiVersion":"stable.example.com/v1","kind":"CronTab","metadata":{"name":"my-new-cron-object"},"spec":{"cronSpec":"* * * * */5","image":"my-awesome-cron-image","replicas":3}}"; line: 1, column: 2]
> 	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
> ```
Yes, this is the error which I'm getting, In case I don't annotate the general class.


> I think he's probably hitting what we discussed about reusing same POJOs for different CRD versions, plus changing these fields at runtime via configuration.
> 
> If this is the case, (I haven't tried this but) I think you can overcome this by implementing the `getVersion` and `getGroup` methods in `CustomResource`<`HasMetadata` and feed those values however you want.

Yes, I was describing that. Your suggestion worked, even though, for one general POJO, above annotations are needed, because parent CustomResource can pick up and set values for it's kind/version/group, but general child class might not use them. This indeed is a workaround but at this point we have forced unused annotations for POJO.

As for the case, where this is being used:
There is a mediator component which works on CRs with various kinds and versions from plain YAMLs which were dropped by the another component. Mediator component's responsibility is to just get CRs and feed them into Kubernetes, there is no need of knowledge of various CRDs (various precise implementations of CustomResource classes in implementations), since they were introduced to kubernetes from another component.
Hence, in this case dynamic values of above members are needed.

Do you have any plans for the dynamic values or workaround is good enough from library's scope?

**Comment by metacosm** [comment]
@LukaTchumburidze wouldn't it make more sense to use something like this example: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/RawCustomResourceExample.java?

**Comment by LukaTchumburidze** [comment]
@metacosm The component, which I have described in the previous comment doesn't have precise CRDs, so using that approach (in that example the precise CRD is being used) would cause the component to get undesirably complicated.

**Comment by metacosm** [comment]
I guess I don't really understand the use case… if changing group and version dynamically works why can't the raw client work as well? That's the whole point of that client is to be able to interact with CRDs without having to use typed data. I'm probably missing something but indeed, `CustomResource` is now thought of as representing a single CR.

**Comment by shouldnotappearcalm** [comment]
I want to create a ServiceMonitor object in kubernetes (not openshift), I want to use `io.fabric8.openshift-model-monitoring`,`new DefaultKubernetesClient().customResources(CrdExample.class)` need `CrdExample` extend `CustomResource`,but `ServiceMonitor` not extend it.

I can only use one other method to achieve my needs, like the following

```java
Config config = new ConfigBuilder().build();
KubernetesClient kubernetesClient = new DefaultKubernetesClient(config);
String crdName = "servicemonitors.monitoring.coreos.com";
CustomResourceDefinition crd = new ApiextensionsAPIGroupClient().v1beta1().customResourceDefinitions().withName(crdName).get();
MixedOperation<ServiceMonitor, ServiceMonitorList, Resource<ServiceMonitor>> svcMonitorClient = kubernetesClient.customResources(CustomResourceDefinitionContext.fromCrd(crd), ServiceMonitor.class, ServiceMonitorList.class);
ServiceMonitorList serviceMonitorList = svcMonitorClient.inNamespace("default").list();
```

but <T extends HasMetadata, L extends KubernetesResourceList<T>> MixedOperation<T, L, Resource<T>> customResources(CustomResourceDefinitionContext crdContext, Class<T> resourceType, Class<L> listClass) method is deprecated in 5.1.0.

Is there any good way to solve CRD creation like ServiceMonitor?
