### ISSUE TITLE
Creating a ServiceMonitor for *Kubernetes* client (not openshift)

### ISSUE THREAD

**Issue by zenbones** [fabric8io/kubernetes-client#2740]
Is there any way to create a ServiceMonitor, as in..

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

If it isn't directly wrapped by the API, can I use the client to create/install an arbitrary type from string or JsonNode or... something?

**Comment by rohanKanojia** [comment]
Yes, you should be able to do it using the RAW API: https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#customresource-typeless-api

**Comment by zenbones** [comment]
Yes, I know I can, and that does work. I had opened this ticket before, which you responded to with the very nice work on ServiceMonitor you did for the OpenShift client. The problem is that I'm using the Kubernetes client. I guess I should bother to read the code and create a proper k8s version of ServiceMonitor, but my time is limited and the raw api does work fine, but the heart wants what the heart wants.

**Comment by rohanKanojia** [comment]
ohk, I see. I don't think it's possible to add `ServiceMonitor` in KubernetesClient Jar. Best I can think of is providing a prometheus extension that can have all POJOs for structs in `github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1` package.

If you just want to use `ServiceMonitor` with KubernetesClient using [typed custom resource API](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#customresource-typed-api). You can add this additional dependency in project which contains `ServiceMonitor`:
```xml
<dependency>
  <groupId>io.fabric8</groupId>
  <artifactId>openshift-model-monitoring</artifactId>
  <version>5.0.0</version>
</dependency>
```
and then create a `ServiceMonitor` client like this:
```java
try (KubernetesClient client = new DefaultKubernetesClient()) {
   // Create ServiceMonitor Client
   MixedOperation<ServiceMonitor, ServiceMonitorList, Resource<ServiceMonitor>> svcMonitorClient = client.customResources(ServiceMonitor.class);
   
   // Use Client for ServiceMonitor related operations
   svcMonitorClient.inNamespace("foo").list();

}
```

If you don't want to add additional dependency you can copy-paste ServiceMonitor POJOs into your project too(You can find them while building the project):
```
kubernetes-client : $ find . -iname ServiceMonitor*.java
./kubernetes-model-generator/openshift-model-monitoring/target/generated-sources/io/fabric8/openshift/api/model/monitoring/v1/ServiceMonitor.java
./kubernetes-model-generator/openshift-model-monitoring/target/generated-sources/io/fabric8/openshift/api/model/monitoring/v1/ServiceMonitorList.java
./kubernetes-model-generator/openshift-model-monitoring/target/generated-sources/io/fabric8/openshift/api/model/monitoring/v1/ServiceMonitorSpec.java
```

**Comment by zenbones** [comment]
Thank you, that's helpful. I'll poke around when I get a chance and see what works best. Feel free to close this ticket. Adding a small section in docs with advice similar to the above might be helpful for others as well.

**Comment by shouldnotappearcalm** [comment]
> ohk, I see. I don't think it's possible to add `ServiceMonitor` in KubernetesClient Jar. Best I can think of is providing a prometheus extension that can have all POJOs for structs in `github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1` package.
> 
> If you just want to use `ServiceMonitor` with KubernetesClient using [typed custom resource API](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#customresource-typed-api). You can add this additional dependency in project which contains all monitoring model including `ServiceMonitor`:
> 
> ```
> <dependency>
>   <groupId>io.fabric8</groupId>
>   <artifactId>openshift-model-monitoring</artifactId>
>   <version>5.0.0</version>
> </dependency>
> ```
> 
> and then create a `ServiceMonitor` client like this:
> 
> ```java
> try (KubernetesClient client = new DefaultKubernetesClient()) {
>    // Create ServiceMonitor Client
>    MixedOperation<ServiceMonitor, ServiceMonitorList, Resource<ServiceMonitor>> svcMonitorClient = client.customResources(ServiceMonitor.class);
>    
>    // Use Client for ServiceMonitor related operations
>    svcMonitorClient.inNamespace("foo").list();
> 
> }
> ```
> 
> If you don't want to add additional dependency you can copy-paste ServiceMonitor POJOs into your project too(You can find them while building the project):
> 
> ```
> kubernetes-client : $ find . -iname ServiceMonitor*.java
> ./kubernetes-model-generator/openshift-model-monitoring/target/generated-sources/io/fabric8/openshift/api/model/monitoring/v1/ServiceMonitor.java
> ./kubernetes-model-generator/openshift-model-monitoring/target/generated-sources/io/fabric8/openshift/api/model/monitoring/v1/ServiceMonitorList.java
> ./kubernetes-model-generator/openshift-model-monitoring/target/generated-sources/io/fabric8/openshift/api/model/monitoring/v1/ServiceMonitorSpec.java
> ```

Hello i have a question,`openshift-model-monitoring` `ServiceMonitor` not extend `CustomResource`,how to use `client.customResources(ServiceMonitor.class)` directly

**Comment by rohanKanojia** [comment]
Hmm, I'm not sure if depending upon current CustomResource API you would be able to use it. Could you please create an issue for adding support for Prometheus Extension? It should be easy to implement.

**Comment by shouldnotappearcalm** [comment]
@rohanKanojia: This is how I use it now,but `<T extends HasMetadata, L extends KubernetesResourceList<T>> MixedOperation<T, L, Resource<T>> customResources(CustomResourceDefinitionContext crdContext, Class<T> resourceType, Class<L> listClass)` method is deprecated in `5.1.0`

```java
Config config = new ConfigBuilder().build();
        KubernetesClient kubernetesClient = new DefaultKubernetesClient(config);
        String crdName = "servicemonitors.monitoring.coreos.com";
        CustomResourceDefinition crd = new ApiextensionsAPIGroupClient().v1beta1().customResourceDefinitions().withName(crdName).get();
        MixedOperation<ServiceMonitor, ServiceMonitorList, Resource<ServiceMonitor>> svcMonitorClient =
                kubernetesClient.customResources(CustomResourceDefinitionContext.fromCrd(crd), ServiceMonitor.class, ServiceMonitorList.class);
        ServiceMonitorList serviceMonitorList = svcMonitorClient.inNamespace("default").list();
```

**Comment by rohanKanojia** [comment]
Hmm, I see. We're discussing whether this should be part of API in future versions or not here https://github.com/fabric8io/kubernetes-client/issues/2738 . I think it should stay there since this can allow users to use same POJO for multiple versions too.

**Comment by shouldnotappearcalm** [comment]
Okay, the way I currently use can also achieve my needs

**Comment by rohanKanojia** [comment]
@shouldnotappearcalm : Bdw, I would appreciate it if you could add your comment on https://github.com/fabric8io/kubernetes-client/issues/2738 to make this method not deprecated . It would help us in making the right decision.

**Comment by shouldnotappearcalm** [comment]
I have added a comment to [2738](https://github.com/fabric8io/kubernetes-client/issues/2738)

**Comment by iocanel** [comment]
@shouldnotappearcalm @rohanKanojia @zenbones: FWIW, we do have a client extension as part of dekorate: https://github.com/dekorateio/dekorate/tree/master/annotations/prometheus-annotations

The extension bits: 
- client 
- model

package should move to the client as extension, or at least that was the intention.
If anyone is up to the task, I wouldn't mind moving them there.

**Comment by rohanKanojia** [comment]
@iocanel : Could you please open a separate issue for this? I think we should do it. Right now our extensions also have `mock`  module too but I think it should be easy to implement too.
