### ISSUE TITLE
Update Tekton Pipelines Model to v0.23.0

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#2742]
It's been ~7 months since we last updated Tekton Model. @Fabian-K has already created PR for updating Tekton Triggers in #2706 . But we would need to update the pipelines model too as per the latest release

https://github.com/tektoncd/pipeline/releases/tag/v0.23.0

**Comment by renannprado** [comment]
@rohanKanojia there's already a new one.

https://github.com/tektoncd/pipeline/releases/tag/v0.21.0

I'm very much looking forward for the update.

**Comment by rohanKanojia** [comment]
@renannprado : Hi, I would appreciate if you could create a PR to add support for this?

**Comment by renannprado** [comment]
@rohanKanojia sure. Please let me know what I should do. I saw that the official k8s lib has a guide about this, is there something similar in this lib?

**Comment by rohanKanojia** [comment]
We do have some docs on how to generate model for main `kubernetes-model-generator`: https://github.com/fabric8io/kubernetes-client/tree/master/kubernetes-model-generator#building but not for extensions.

Basically, you need to do what we've done in https://github.com/fabric8io/kubernetes-client/pull/2535
1. Update `go.mod` for `extensions/tekton/generator-v1beta1/`: 
https://github.com/fabric8io/kubernetes-client/blob/19aafa2dbc41951f76d915c971a3b676266ba3c4/extensions/tekton/generator-v1beta1/go.mod#L5
2. Issue `make` in `extensions/tekton/generator-v1beta1` which will generate model

**Comment by rohanKanojia** [comment]
@renannprado: polite ping, Are you still working on this issue? Do you need any help?

**Comment by renannprado** [comment]
@rohanKanojia Sorry, I haven't had the time to follow up yet. In case someone pick this one up, please send a message here. If I start to work on it, I'll send a messages here telling that I have started to do something.

**Comment by rohanKanojia** [comment]
oh, okay. Thanks a lot for the update.

**Comment by rohanKanojia** [comment]
Closed via https://github.com/fabric8io/kubernetes-client/pull/3180
