### ISSUE TITLE
Are Pod and Service operations are no longer PropagationPolicyConfigurable?

### ISSUE THREAD

**Issue by milosonator** [fabric8io/kubernetes-client#2745]
Upgrading from 4.9.0 to 4.13.10, I find the following code no longer working:

```java
kubernetesClient.services().inNamespace("myNameSpace").withLabel("myLabel").withPropagationPolicy(DeletionPropagation.BACKGROUND).delete(); // already upgraded to enum style instead of string propagation policy
```
However, I can't call `withPropagationPolicy` on this operation. Is this no longer supported, or did this not make sense to begin with, and was therefore removed? If no, how can I ensure I can set the propagation behavior for this delete operation?

Is it no longer there because the delete can't cascade to anything since Pods and Services don't have any dependents? Any help much appreciated.

**Comment by rohanKanojia** [comment]
Apologies for this. I think it affects all resources not just Pod and Service. both `cascading` and `withPropagationPolicy` seem to be unavailable. I think we broke this in between the releases. For now, you should be able to work around this :
```java
ServiceList svcList = kubernetesClient.services()
  .inNamespace("myNameSpace")
  .withLabel("myLabel")
  .list();
kubernetesClient.resourceList(svcList)
  .inNamespace("myNameSpace")
  .withPropagationPolicy(DeletionPropagation.BACKGROUND)
  .delete();
```
