### ISSUE TITLE
Informer creation behavior for custom resource with CRDContext in SharedInformerFactory

### ISSUE THREAD

**Issue by LukaTchumburidze** [fabric8io/kubernetes-client#2746]
The factory has a  method [sharedIndexInformerForCustomResource](https://github.com/fabric8io/kubernetes-client/blob/2b9158528257a2de030ca67c776c5caf37e61d40/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformerFactory.java#L132) to create an informer with a CRDContext for CRs. It's is using [sharedInformerFor](https://github.com/fabric8io/kubernetes-client/blob/2b9158528257a2de030ca67c776c5caf37e61d40/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformerFactory.java#L152) to register the informer inside the factory object. This causes a problem when registering new informers using several different CRDContexts, but using same set of classes (extending CustomResource and CustomResourceList). Case will result in creation of several informers, but registering only the one which is has been created the latest (since factory's internal map [uses only classname as key](https://github.com/fabric8io/kubernetes-client/blob/2b9158528257a2de030ca67c776c5caf37e61d40/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformerFactory.java#L158)).
Example:

```java
        SharedInformerFactory factory = defaultKubernetesClient.informers();

        CustomResourceDefinitionContext firstCrdContext = getFirstCrdContext();
        CustomResourceDefinitionContext secondCrdContext = getSecondCrdContext();

        SharedIndexInformer<MyCustomResourceClass> lostIndexInformer = factory.sharedIndexInformerForCustomResource(
                firstCrdContext,
                MyCustomResourceClass.class,
                MyCustomResourceClassList.class,
                0);

        SharedIndexInformer<MyCustomResourceClass> savedIndexInformer = factory.sharedIndexInformerForCustomResource(
                secondCrdContext,
                MyCustomResourceClass.class,
                MyCustomResourceClassList.class,
                0);

        factory.startAllRegisteredInformers();
```

As I have said `lostIndexInformer` will be rewritten by the time we reach to `startAllRegisteredInformers`. I don't think this is the right behavior, since idea of passing the different CRDContexts to factory methods means that several informers should be registered and that they should operate on different CRs which has been described in CRDContext.

**Comment by rohanKanojia** [comment]
This issue also seems related to https://github.com/fabric8io/kubernetes-client/issues/2738

We're using type as the key for informer
https://github.com/fabric8io/kubernetes-client/blob/00d23e8cece649c12e845e4032e7b5cd35071344/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformerFactory.java#L48

**Comment by rohanKanojia** [comment]
@LukaTchumburidze: Hi, Would it be possible for you to share contents for `firstCrdContext` and `secondCrdContext`

**Comment by rohanKanojia** [comment]
Bdw, these methods accepting `CustomResourceDefinitionContext` in SharedInformerFactory were removed in https://github.com/fabric8io/kubernetes-client/pull/2667 and are not part of API since v5.1.0

But I still see a way to provide different versions by providing an `OperationContext` .However this doesn't work due to apiversion always getting picked from annotation:

https://github.com/fabric8io/kubernetes-client/blob/24a5faee73701fb0d9c0750b28aa8c6fa1f85cda/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformerFactory.java#L309

```java
SharedIndexInformer<Bicycle> bicycleV1Informer = informerFactory.sharedIndexInformerForCustomResource(Bicycle.class, resyncPeriodMillis);
SharedIndexInformer<Bicycle> bicycleV1beta1Informer = informerFactory.sharedIndexInformerForCustomResource(Bicycle.class, new OperationContext().withApiGroupVersion("v1beta1"), resyncPeriodMillis);

bicycleV1beta1Informer.addEventHandler(new GenericResourceHandler<>("v1beta1-bicycle"));
bicycleV1Informer.addEventHandler(new GenericResourceHandler<>("v1-bicycle"));
```

Moreover having `Type` as the key doesn't only affect CustomResources. This informer lost behavior is also visible in standard Kubernetes resources:

```java
SharedIndexInformer<Pod> podInDefaultNamespaceInformer = informerFactory.inNamespace("default")
  .sharedIndexInformerFor(Pod.class, resyncPeriodMillis);
SharedIndexInformer<Pod> podInKubePublicNamespaceInformer = informerFactory.inNamespace("kube-system")
  .sharedIndexInformerFor(Pod.class, resyncPeriodMillis); // Overwrites previous entry
```

**Comment by LukaTchumburidze** [comment]
@rohanKanojia Since kubernetes-client's approach with CRDs has changed much during these months you're right that my example is obsolete.
However you're right that core issue still stays the same, hashmap's keys are being populated only according to types.

> I admit key should not be `Type` and should be a composite key depending upon resource's ApiGroup, ApiVersion, Namespace and Name

Currently factory does not support several `OperatorContext`s for one class as well. The key should contain `OperationContext`, since `OperationContext' might contain any queries needed for two informers to be distinguished from each other. I might be wrong on this one, but it can be checked.

**Comment by manusa** [comment]
Relates to: #2010
