### ISSUE TITLE
sharedInformerFactory.stopAllRegisteredInformers produces logs with ERROR severity

### ISSUE THREAD

**Issue by SunithaR** [fabric8io/kubernetes-client#2753]
When sharedInformerFactory.stopAllRegisteredInformers() is called, it produces logs with **ERROR** severity(see stack trace below). Since we are invoking a graceful shutdown, would be good if these messages are logged at a WARN level, instead of ERROR(signalling major issue) There is a similar issue which has been fixed - kubernetes-client/java#656, **but the log level has not been reduced.**
Can you please take a look and see if it is possible to reduce the log level or if there is any other workaround when using SharedInformer?

2021-01-26 00:21:02.192 ERROR 1 --- [ol-202-thread-1] i.f.k.c.i.cache.ProcessorListener : Processor thread interrupted: null
2021-01-26 00:21:02.192 ERROR 1 --- [-controller-Job] i.f.k.client.informers.cache.Controller : DefaultController#processLoop got interrupted null
java.lang.InterruptedException: null

**Comment by SunithaR** [comment]
@rohanKanojia PR created - https://github.com/fabric8io/kubernetes-client/pull/2754

**Comment by SunithaR** [comment]
@manusa @rohanKanojia can you please let me know the target date and release this fix will be available, so we can upgrade?

**Comment by SunithaR** [comment]
Did not hear back, so Upgraded to 5.0.2 version released on Feb 8th and it does not have the fix. @rohanKanojia @manusa can you please let me know target date and release for this fix?

**Comment by rohanKanojia** [comment]
Sorry, I think you should get it in v5.1.0(Which is going to be released within a few days)

**Comment by manusa** [comment]
Hopefully we'll get to release 5.1.0 tomorrow, stay tuned.

**Comment by SunithaR** [comment]
Thank you! was able to update to 5.1.0.
