### ISSUE TITLE
ServiceAccount getting Unauthorized

### ISSUE THREAD

**Issue by alonir** [fabric8io/kubernetes-client#2756]
Hi,

I am using fabric8 openshift-client 4.4.2 version calling project pods inside the MS and everything works fine.
but after some time , it can be hours/day i see the below error

Request processing failed; nested exception is io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.30.0.1/api/v1/namespaces/XXX/pods. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked. Unauthorized.] with root cause","exception":"\nio.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.30.0.1/api/v1/namespaces/vrz-il01-env5-authoring/pods. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked. Unauthorized.\n\tat io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:589)

and its not able to connect even if i am doing retry code and initialize the client again
try (DefaultKubernetesClient kc = new DefaultKubernetesClient(configBuilder.build())) {
            if (kc.isAdaptable(OpenShiftClient.class)) {
                isOCP = true;
                client = kc.adapt(OpenShiftClient.class);
            } else {
                client = kc;
            }

When i am restarting the pod it works, pod is deployed on open-shift environment v3.9.0.
Do you think it's a matter of define my own local role? or maybe its some known issue which was resolve on higher fabric8 version? 
Below SA/RB definition

SA definition: 
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: x-sa
  name: x-sa
  namespace: {{.Release.Namespace}}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": "before-hook-creation"

RB definition:
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: c1-dashboard-rb
  name: c1-dashboard-rb
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": "before-hook-creation"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: x
    namespace: {{.Release.Namespace}}

**Comment by alonir** [comment]
****Update ****
it seems that the service account is re-created after the couple of days while the server is up.
Is there a way on the fabric8 API to initialize it?

**Comment by fighterhit** [comment]
I also encountered this problem in v5.12.1. Any fix about this? @manusa

**Comment by manusa** [comment]
Please use a recent version of Fabric8 Kubernetes Client, either 6.13.4 or the new 7.0.1
