### ISSUE TITLE
OperationContext "withXXXX" methods return a new instance every time

### ISSUE THREAD

**Issue by ppatierno** [fabric8io/kubernetes-client#2763]
Is there any specific reason why the `OperationContext` class doesn't have a companion builder with corresponding `withXXXX` methods? The class itself has `withXXXX` method but it sounds kind of not intuitive even because each time it's going to create a new `OperationContext` instance inside and returns it.

**Comment by iocanel** [comment]
Not sure I remember all the details but here goes.
We wanted `OperationContext` to be immutable. So  each time we need to change something we create a brand new instance of it, vs a traditional setter that would straight mutate the object.

**Comment by ppatierno** [comment]
so the next question is ... any reason why it was needed to be immutable? :-)

**Comment by manusa** [comment]
Not sure what the reason for this is, although I tend to prefer immutability always.

On the other hand, the specific case makes it harder to prepare Operation implementation unit tests and OperationContext mocking (just faced a few issues with that a couple of hours ago).

**Comment by ppatierno** [comment]
my point is that because this OperationContext is part of the "external" API (because a user can use it on informers creation) it's kind of not intuitive building in this way. Anyway, if there were good reasons we can just live with it.

**Comment by manusa** [comment]
Not sure if it would make sense to align it with the other models, and provide a sundr generated builder.
