### ISSUE TITLE
Replace occurrences of `Function<T, T>` with `UnaryOperator<T>`

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#2766]
I noticed these today:

https://github.com/fabric8io/kubernetes-client/blob/0a4794f7d1581b3becb3d4f6f8c743941c6d9956/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java#L72-L74

https://github.com/fabric8io/kubernetes-client/blob/0a4794f7d1581b3becb3d4f6f8c743941c6d9956/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java#L118-L120

According to sonar[0], we can easily replace it with a specialized interface for these operations(i.e `UnaryOperator`)

[0] https://rules.sonarsource.com/java/RSPEC-4276

**Comment by manusa** [comment]
https://sonarcloud.io/project/issues?id=fabric8io_kubernetes-client&languages=java&resolved=false&rules=java%3AS4276&types=CODE_SMELL

**Comment by gandalf0151** [comment]
Hi @rohanKanojia   
Is this issue already assigned ?
Thanks
