### ISSUE TITLE
Get log with timestamp but in wrong timezone

### ISSUE THREAD

**Issue by MattewLyn** [fabric8io/kubernetes-client#2767]
I have specify the timezone in the Deployment YAML file, but when I use the log operations as the cheatsheet writes:

```
String logs = client.pods().inNamespace("aNamespace").withName("podName").usingTimestamps().tailingLines(100).getLog(true);
```

I always get a log with timestamp in UTC timezone while the kubernetes cluster deployed in the machine in +8 timezone. Is there any solution to get logs with correct timestamp?

**Comment by rohanKanojia** [comment]
Umm, I think we return whatever response we get from kubernetes api. What result do you get when you do:
```bash
kubectl logs pod/podName -n aNamespace --tail=100
```

**Comment by manusa** [comment]
Timezone/timestamp format is provided by the [API server](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#read-log-pod-v1-core):

>  If true, add an RFC3339 or RFC3339Nano timestamp at the beginning of every line of log output. Defaults to false.

If you want to change the format, you can parse each of the lines, split on the first space, and then reformat the date part to your needs.

**Comment by MattewLyn** [comment]
> Umm, I think we return whatever response we get from kubernetes api. What result do you get when you do:
> 
> ```shell
> kubectl logs pod/podName -n aNamespace --tail=100
> ```

I get logs without timestamp...

**Comment by MattewLyn** [comment]
how can I know 

> Timezone/timestamp format is provided by the [API server](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#read-log-pod-v1-core):
> 
> > If true, add an RFC3339 or RFC3339Nano timestamp at the beginning of every line of log output. Defaults to false.
> 
> If you want to change the format, you can parse each of the lines, split on the first space, and then reformat the date part to your needs.



> Timezone/timestamp format is provided by the [API server](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#read-log-pod-v1-core):
> 
> > If true, add an RFC3339 or RFC3339Nano timestamp at the beginning of every line of log output. Defaults to false.
> 
> If you want to change the format, you can parse each of the lines, split on the first space, and then reformat the date part to your needs.

I considered this way but I'd like to try a smarter way,,, so how can I add an RFC3339 at the beginning of every line of log output? Is there interfaces in the java library?

**Comment by manusa** [comment]
No, what I pasted there is the K8s spec (you can click the link and if your scroll a little, you'll see that's the description of the `useTimestamps` query parameter which only admits a `true`/`false` value). i.e. You **can't** change the output of the timestamp provided by the k8s API.

The spec says that k8s will return an RFC3339 formatted timestamp. Which means that you can safely parse (client-side) the timestamp and format it as you wish. But the API provides no way to configure/customize the timestamp format.

**Comment by MattewLyn** [comment]
> how can I know
> 
> > Timezone/timestamp format is provided by the [API server](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#read-log-pod-v1-core):
> > > If true, add an RFC3339 or RFC3339Nano timestamp at the beginning of every line of log output. Defaults to false.
> > 
> > 
> > If you want to change the format, you can parse each of the lines, split on the first space, and then reformat the date part to your needs.
> 
> > Timezone/timestamp format is provided by the [API server](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#read-log-pod-v1-core):
> > > If true, add an RFC3339 or RFC3339Nano timestamp at the beginning of every line of log output. Defaults to false.
> > 
> > 
> > If you want to change the format, you can parse each of the lines, split on the first space, and then reformat the date part to your needs.
> 
> I considered this way but I'd like to try a smarter way,,, so how can I add an RFC3339 at the beginning of every line of log output? Is there interfaces in the java library?

Kubernetes is a little hard for a rookie as me,,, I hope these simple

> No, what I pasted there is the K8s spec (you can click the link and if your scroll a little, you'll see that's the description of the `useTimestamps` query parameter which only admits a `true`/`false` value). i.e. You **can't** change the output of the timestamp provided by the k8s API.
> 
> The spec says that k8s will return an RFC3339 formatted timestamp. Which means that you can safely parse (client-side) the timestamp and format it as you wish. But the API provides no way to configure/customize the timestamp format.

All right, thanks a lot. It seems that I have to try the less smarter way (╯︵╰). Thank you again.

**Comment by MattewLyn** [comment]
(RFC3339 is not the format I want)
