### ISSUE TITLE
How to watch warning event?

### ISSUE THREAD

**Issue by johnhec** [fabric8io/kubernetes-client#2769]
When I use wather to watch pod and deployment, the event is ADDED, MODIFILED,UPDATED, but no FailedScheduling, ProvisioningFailed etc.

**Comment by rohanKanojia** [comment]
Do you get these events when you are watching using `kubectl`? I think our client returns whatever it receives from kubernetes api

**Comment by manusa** [comment]
You are confusing [events produced](https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes) by a watcher with those provided by the [core Events API](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#event-v1-core) or the [newer events.k8s.io](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#event-v1-events-k8s-io).

**Comment by johnhec** [comment]
How to use kubectl to wather

**Comment by johnhec** [comment]
Watch watch = client.pods().inAnyNamespace().withLabel(LABEL_KEY, LABEL_VALUE).watch(new Watcher<Pod>() {
                @Override
                public void eventReceived(Action action, Pod resource) {
                    if (resource.getStatus().getContainerStatuses() != null && !resource.getStatus().getContainerStatuses().isEmpty()) {
                        List<ContainerStatus> falseContainerStatuses = resource.getStatus().getContainerStatuses().stream()
                                .filter(c -> !c.getReady()).collect(Collectors.toList());
                        Boolean ready = false;
                        Integer restartCount = 0;
                        if (falseContainerStatuses.isEmpty()) {
                            ready = true;
                            int size = resource.getStatus().getContainerStatuses().size();
                            if (size > 0) {
                                restartCount = resource.getStatus().getContainerStatuses().stream()
                                        .map(c -> c.getRestartCount()).sorted().collect(Collectors.toList()).get(size-1);
                            }
                        } else {
                            restartCount = falseContainerStatuses.stream()
                                    .map(c -> c.getRestartCount()).sorted().collect(Collectors.toList()).get(falseContainerStatuses.size()-1);
                        }
                        logger.info("Pod {}: {}: {}: {}: {}", action, resource.getMetadata().getName(), resource.getMetadata().getNamespace(), ready, restartCount);
                        String[] podStr = resource.getMetadata().getName().split("-");
                        String name = podStr[0];
                        for (int i = 1; i < podStr.length-2; i++) {
                            name += "-" + podStr[i];
                        }
                        EngineUtil.updateStatus(client, resource.getMetadata().getNamespace(), name, null, null, null, ready, restartCount);
                    }
                }

                @Override
                public void onClose(KubernetesClientException e) {
                    logger.debug("Pod Watcher Closed");
                    if (e != null) {
                        logger.error(e.getMessage(), e);
                        recreateWatcher(WatchEnum.POD);
                    }
                }
            });

this is my code, that only can watcher the event of ADDED, MODIFILED,UPDATED

**Comment by johnhec** [comment]
> You are confusing [events produced](https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes) by a watcher with those provided by the [core Events API](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#event-v1-core) or the [newer events.k8s.io](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#event-v1-events-k8s-io).

**Comment by johnhec** [comment]
> 您在观看使用时会收到这些事件`kubectl`吗？我认为我们的客户会返回从kubernetes api收到的任何内容

```
Watch watch = client.pods().inAnyNamespace().withLabel(LABEL_KEY, LABEL_VALUE).watch(new Watcher<Pod>() {
                @Override
                public void eventReceived(Action action, Pod resource) {
                    if (resource.getStatus().getContainerStatuses() != null && !resource.getStatus().getContainerStatuses().isEmpty()) {
                        List<ContainerStatus> falseContainerStatuses = resource.getStatus().getContainerStatuses().stream()
                                .filter(c -> !c.getReady()).collect(Collectors.toList());
                        Boolean ready = false;
                        Integer restartCount = 0;
                        if (falseContainerStatuses.isEmpty()) {
                            ready = true;
                            int size = resource.getStatus().getContainerStatuses().size();
                            if (size > 0) {
                                restartCount = resource.getStatus().getContainerStatuses().stream()
                                        .map(c -> c.getRestartCount()).sorted().collect(Collectors.toList()).get(size-1);
                            }
                        } else {
                            restartCount = falseContainerStatuses.stream()
                                    .map(c -> c.getRestartCount()).sorted().collect(Collectors.toList()).get(falseContainerStatuses.size()-1);
                        }
                        logger.info("Pod {}: {}: {}: {}: {}", action, resource.getMetadata().getName(), resource.getMetadata().getNamespace(), ready, restartCount);
                        String[] podStr = resource.getMetadata().getName().split("-");
                        String name = podStr[0];
                        for (int i = 1; i < podStr.length-2; i++) {
                            name += "-" + podStr[i];
                        }
                        EngineUtil.updateStatus(client, resource.getMetadata().getNamespace(), name, null, null, null, ready, restartCount);
                    }
                }

                @Override
                public void onClose(KubernetesClientException e) {
                    logger.debug("Pod Watcher Closed");
                    if (e != null) {
                        logger.error(e.getMessage(), e);
                        recreateWatcher(WatchEnum.POD);
                    }
                }
            });
```

**Comment by johnhec** [comment]
> 您[会将监视](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#event-v1-events-k8s-io)者[产生](https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes)的[事件](https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes)与[核心Events API](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#event-v1-core)或[较新的events.k8s.io](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#event-v1-events-k8s-io)提供的[事件](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#event-v1-core)[混淆](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#event-v1-events-k8s-io)。

```
Watch watch = client.pods().inAnyNamespace().withLabel(LABEL_KEY, LABEL_VALUE).watch(new Watcher<Pod>() {
                @Override
                public void eventReceived(Action action, Pod resource) {
                    if (resource.getStatus().getContainerStatuses() != null && !resource.getStatus().getContainerStatuses().isEmpty()) {
                        List<ContainerStatus> falseContainerStatuses = resource.getStatus().getContainerStatuses().stream()
                                .filter(c -> !c.getReady()).collect(Collectors.toList());
                        Boolean ready = false;
                        Integer restartCount = 0;
                        if (falseContainerStatuses.isEmpty()) {
                            ready = true;
                            int size = resource.getStatus().getContainerStatuses().size();
                            if (size > 0) {
                                restartCount = resource.getStatus().getContainerStatuses().stream()
                                        .map(c -> c.getRestartCount()).sorted().collect(Collectors.toList()).get(size-1);
                            }
                        } else {
                            restartCount = falseContainerStatuses.stream()
                                    .map(c -> c.getRestartCount()).sorted().collect(Collectors.toList()).get(falseContainerStatuses.size()-1);
                        }
                        logger.info("Pod {}: {}: {}: {}: {}", action, resource.getMetadata().getName(), resource.getMetadata().getNamespace(), ready, restartCount);
                        String[] podStr = resource.getMetadata().getName().split("-");
                        String name = podStr[0];
                        for (int i = 1; i < podStr.length-2; i++) {
                            name += "-" + podStr[i];
                        }
                        EngineUtil.updateStatus(client, resource.getMetadata().getNamespace(), name, null, null, null, ready, restartCount);
                    }
                }

                @Override
                public void onClose(KubernetesClientException e) {
                    logger.debug("Pod Watcher Closed");
                    if (e != null) {
                        logger.error(e.getMessage(), e);
                        recreateWatcher(WatchEnum.POD);
                    }
                }
            });
```
this is my code,that only can watcher the event of ADDED, MODIFILED,UPDATED
