### ISSUE TITLE
How to add or replace label on existing openshift project

### ISSUE THREAD

**Issue by Richie67** [fabric8io/kubernetes-client#2772]
Hello, I'm trying to add or replace a label on an existing openshift project.

I'm using the kubernetes-client/openshift-client 4.13.1.

As far as I could see the posted request from oc commandline and the build in request from here is different.

`            OpenShiftClient client = clientProvider.getOpenshiftClient(cluster);`
`            Resource<Project, DoneableProject> resource = client.projects().withName("mynamespace");`
`            String strLabel = resource.get().getMetadata().getLabels().get("LabelInQuestion");`
`            if (strLabel == null) {`
`                // create it`
`                return resource.edit().editMetadata().addToLabels("labelInQuestion", "value").endMetadata().done();`
`            } else {`
`                // change it`
`                return resource.edit().editMetadata().removeFromLabels("LabelInQuestion").addToLabels("labelInQuestion", "value").endMetadata().done();`
`            }`

Any hint how this could be done corretly?

**Comment by rohanKanojia** [comment]
I'm not sure whether you can even update `metadata.labels` for `Project`[0]. When I try doing it I keep facing this error:
```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Project.project.openshift.io \"rokumar\" is invalid: metadata.labels[foo1]: Invalid value: \"bar1\": field is immutable, , try updating the namespace","reason":"Invalid","details":{"name":"rokumar","group":"project.openshift.io","kind":"Project","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"bar1\": field is immutable, , try updating the namespace","field":"metadata.labels[foo1]"}]},"code":422}
```
Could you please check with updating the `Namespace` instead?

[0] https://access.redhat.com/solutions/2677921

**Comment by Richie67** [comment]
Hi could confirm, that replacing the Objekt Project by Namespace was successful.
Thanks for the hint :-)

```java
            OpenShiftClient client = clientProvider.getOpenshiftClient(cluster);
            // Resource<Project, DoneableProject> resource = client.projects().withName("mynamespace");
            Resource<Namespace, DoneableNamespace> resource2 = client.namespaces().withName(projectName);

            final String refLabel = "LabelInQuestion";
            Map<String, String> oldLabels = resource2.get().getMetadata().getLabels();
            String strLabel = null;
            if (oldLabels != null) {
                strLabel = oldLabels.get(refLabel);
            }
            Namespace ns = null;
            if (strLabel == null) {
                // create it
                ns = resource2.edit().editMetadata().addToLabels(refLabel, "value").endMetadata().done(); // works
                log.info("Label does not exist, will be created");
                // NamespaceFluent.MetadataNested<DoneableNamespace> mdn = resource2.edit().editMetadata();
            } else {
                // change it
                log.info("Label exists, will be edited");
                // ns = resource2.edit().editMetadata().removeFromLabels(refLabel).addToLabels(refLabel, "value2").endMetadata().done(); // works
                ns = resource2.edit().editMetadata().addToLabels(refLabel, "value3").endMetadata().done(); // also works
            }
```
