### ISSUE TITLE
Create a list of resources including custom resources together

### ISSUE THREAD

**Issue by sundarvc** [fabric8io/kubernetes-client#2774]
Hi Team,

I have res1, res2, customres1, customres2 that need to be applied and created from one big yaml file.
Is there a way to do this without individually processing each one separately using fabric8io API ?
I know res1, res2 can be done together, but not sure how to process customres1 and customres2 together with res1 and res2.

Thanks,
Sundar

**Comment by manusa** [comment]
Could you provide more details? an example project or some code?

Not sure what you mean by "processing", are you altering what was defined in the yaml file or simply applying those resources?

**Comment by sundarvc** [comment]
@PostMapping("/apply")
	public String createAllResourcesinSSC(@RequestParam(value = "namespace") String namespace,
			@RequestBody String listOfResources) {
		logger.debug("*********** Creating All Resources  {} ", listOfResources);
		KubernetesClient client = new DefaultKubernetesClient();
		logger.debug("*********" + namespace + "*********");
		// Load Yaml into Kubernetes resources
		List<HasMetadata> result = client.load(new ByteArrayInputStream(listOfResources.getBytes())).get();
		// Apply Kubernetes Resources
		result = client.resourceList(result).inNamespace(namespace).createOrReplace();
		logger.debug("*********** Done All Resources  **********  ");
		return String.format("{\"resources\":\"%s\"}", result.toString());
	}

In the above code, if I have custom resources inside in the "listOfResources", how will it apply them in one shot using the fabric8 api.
As I understand, custom resources need the CustomResourceDefinitionContext before they can be created.

Thanks,
Sundar
