### ISSUE TITLE
OpenIDConnectionUtils#persistKubeConfigWithUpdatedToken persists access token instead of refresh token

### ISSUE THREAD

**Issue by oliviaKar** [fabric8io/kubernetes-client#2783]
https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtils.java#L263 

Here it seems like the access_token is retrieved from the updated config and persisted as the refresh token. 

The behaviour that we have observed is that the config gets refreshed once, but cannot keep getting refreshed as the persisted refresh-token is not valid.

**Comment by rohanKanojia** [comment]
@oliviaKar : Thanks a lot for reporting this. Could you please raise a quick PR to fix this?

**Comment by rohanKanojia** [comment]
@oliviaKar : Hi, Which cloud provider are you using?
