### ISSUE TITLE
Pod exec("ls","-al") shows ascii codes for color enabled output

### ISSUE THREAD

**Issue by ramukima** [fabric8io/kubernetes-client#279]
Example output below:

onfig:io.fabric8.kubernetes.client.EditableConfig@4c873330
onOpen: Response{protocol=http/1.1, code=101, message=Switching Protocols, url=https://ip:6443/api/v1/namespaces/default/pods/service-demo-erusf/exec?command=ls&command=-al&tty=true&stdin=true&stdout=true&stderr=true}
total 8092
drwxr-xr-x    4 root     root          4096 Dec 27  2014 [1;34m.[0m
drwxr-xr-x   37 root     root          4096 Jan  6 02:13 [1;34m..[0m
-rwxr-xr-x    1 root     root       8267160 Dec 27  2014 [1;32mgo-app[0m
drwxr-xr-x    4 root     root          4096 Dec 27  2014 [1;34mpublic[0m
drwxr-xr-x    2 root     root          4096 Dec 27  2014 [1;34mtemplates[0m

**Comment by ramukima** [comment]
This behavior is seen when 'tty=true' only.

**Comment by jimmidyson** [comment]
A lot of Linux commands will check if tty is attached & send colour codes if one is attached. To run `ls -al` you don't need a tty so you can either run without tty or run `ls --color=never -al`.

As this isn't a kubernetes client issue, I'm closing now.
