### ISSUE TITLE
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: http://xx:8080/api/v1/namespaces/xxx/pods?labelSelector=xx. Message: 404 page not found

### ISSUE THREAD

**Issue by own-idea** [fabric8io/kubernetes-client#2793]
kubernetes client version: 4.10.2

okhttp version: 3.12.6

sometimes i see log error, like “ ,io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: http://xx:8080/api/v1/namespaces/xxx/pods?labelSelector=xx. Message: 404 page not found”

but in fact, if i copy the link in the browser, then it will send 200 response.

has someone see this ? thanks for reply

**Comment by rohanKanojia** [comment]
Could you please provide more details? Or maybe a test case we can try out? What code do you execute?
