### ISSUE TITLE
A question about pod status

### ISSUE THREAD

**Issue by MattewLyn** [fabric8io/kubernetes-client#2794]
I'm confused with the terminating pods and running pods: I tried to print the pod.getStatus().getPhase()、pod.getStatus().getMessage()、pod.getStatus().getContainerStatuses()、pod.getStatus().getConditions()，but I can find no diffrence between a terminating pod and a running pod. So how can I distinguish them?

**Comment by rohanKanojia** [comment]
We have a PodStatusUtil[0] which you can use to check for pod status.

[0] https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/PodStatusUtil.java

**Comment by MattewLyn** [comment]
That's it. Thank you.
