### ISSUE TITLE
Question: Does JSON to DSL or rawRequest API make sense ?

### ISSUE THREAD

**Issue by ramukima** [fabric8io/kubernetes-client#280]
In many cases a client application already has a data model that can be serialized into a payload that can be sent to kubernetes API. Would it be useful to allow for making raw requests using this client library ? If not, can that json be fed into this client code for mapping the json into callable DSL API (something like a DSL builder from JSON) ? The later may not make too much sense, but if you think of the reusable code this client library has, it does make sense to me.

**Comment by jimmidyson** [comment]
You can deserialize any JSON/YAML from an `InputStream` (e.g. `FileInputStream` if from file) into any type with e.g. `client.pods().load(is)` & then create/update/edit/etc as you want. Does that cover what you are trying to do?

**Comment by jimmidyson** [comment]
Closing as no response.

**Comment by ramukima** [comment]
Apologies for having lost attention on this. Yes, the load() will cover the use case.
