### ISSUE TITLE
How to unified unit of the cpu and memory

### ISSUE THREAD

**Issue by yangjinlogic** [fabric8io/kubernetes-client#2800]
The unit of cpu and memory contain has gi、ki、m、n，etc.So,how to unified unit of the cpu and memory.

**Comment by yangjinlogic** [comment]
help

**Comment by rohanKanojia** [comment]
Sorry, but I'm not able to understand your question property. Could you please elaborate?

**Comment by yangjinlogic** [comment]
@rohanKanojia       the io.fabric8.kubernetes.api.model.Quantity  contains Ki、Mi、Gi、Ti、Pi、Ei、n,etc，sometimes the entity response those unit is not  consistent,for example,the cpu response unit is Gi,but sometimes reponse unit is Mi,so how to how to unified unit of the cpu and memory.
