### ISSUE TITLE
NPE in HasMetadataOperation patch and replace

### ISSUE THREAD

**Issue by brandonheck** [fabric8io/kubernetes-client#2802]
While testing logic that patches a secret, HasMetadataOperation encounters a NullPointerException if the resource exists but has no metadata on [line 120](https://github.com/fabric8io/kubernetes-client/blob/b015fb957047956d3656c3043e4c663957e82de9/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java#L120). There is a null check, however the operation is not performed within that null check, and an ObjectMeta is not created/set in response to the resource having no metadata.

It appears that [replace](https://github.com/fabric8io/kubernetes-client/blob/b015fb957047956d3656c3043e4c663957e82de9/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java#L74) would also suffer from the same issue.

I am testing using the [mock KubernetesServer](https://github.com/fabric8io/kubernetes-client/blob/b015fb957047956d3656c3043e4c663957e82de9/kubernetes-client/src/test/java/io/fabric8/kubernetes/server/mock/KubernetesServer.java) and understand that this scenario is not likely to occur when running against a live Kubernetes server instance. This may also be an issue in KubernetesServer, as the secret is created with metadata. I am using [createOrReplace(Secret)](https://github.com/fabric8io/kubernetes-client/blob/b015fb957047956d3656c3043e4c663957e82de9/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/CreateOrReplaceable.java#L27) to write the initial secret in my test with the basic pseudocode below:

```java
Secret secret = new SecretBuilder()
  .editOrNewMetadata()
    .withNamespace(namespace)
    .withName(name)
  .endMetadata()
  .addToData("key.json", value)
  .build();

kubeClient
  .secrets()
  .inNamespace(namespace)
  .createOrReplace(secret);
```

The code being tested is patching with this pseudocode:
```java
Secret secret = new SecretBuilder()
  .addToData("key.json", updatedValue)
  .build();

  kubeClient
    .secrets()
    .inNamespace(namespace)
    .withName(name)
    .patch(secret);
```

**Comment by brandonheck** [comment]
Debugging a bit more, I'm understanding that the issue is that the Secret being created for the patch does not have metadata rather than the resource from the Kubernetes server not having metadata. As there is no metadata being changed, I wouldn't expect it to be necessary to set the metadata before patching. I can work around this by setting the namespace and/or name on the Secret being patched in, but that somewhat seems to counter the purpose of a patch.

**Comment by rohanKanojia** [comment]
@brandonheck : Hi, Thanks a lot for reporting this. I can reproduce this using the following test:
```java
  @Test
  void testReplaceSecretNoMetadata() {
    // Given
    Secret secret = new SecretBuilder()
      .addToData("key.json", "{\"foo\":\"bar\"}")
      .build();
    server.expect().post().withPath("/api/v1/namespaces/foo/secrets")
      .andReturn(HttpURLConnection.HTTP_OK, secret)
      .once();
    server.expect().get().withPath("/api/v1/namespaces/foo/secrets/foo")
      .andReturn(HttpURLConnection.HTTP_OK, secret)
      .always();
  server.expect().put().withPath("/api/v1/namespaces/foo/secrets/foo")
      .andReturn(HttpURLConnection.HTTP_OK, new SecretBuilder(secret)
        .addToData("value.json", "{}")
        .build())
      .once();

    // When
    Secret createdSecret = client.secrets().inNamespace("foo").create(secret);
    createdSecret.getData().put("value.json", "{}");
    Secret replacedSecret = client.secrets().inNamespace("foo").withName("foo").patch(createdSecret);

    // Then
    assertNotNull(createdSecret);
    assertNotNull(replacedSecret);
  }
```

As you rightly pointed out this issue isn't going to happen in a real Kubernetes Cluster since a Secret without any metadata won't be accepted as a valid object. I can add Null checks for `resource.getMetadata()` here:

https://github.com/fabric8io/kubernetes-client/blob/6bdd75129d321ad4d7a1b40c7892ad34df4aa329/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java#L116-L120

like this:
```diff
         final UnaryOperator<T> visitor = resource -> {
           try {
+            if (resource.getMetadata() == null) {
+              throw new IllegalArgumentException("Invalid object! No .metadata provided for resource");
+            }
```

However, I think we're allowing the user to have wrong expectations by allowing the creation of a resource without any `metadata.name` or `metadata.generateName`. Maybe we should add checks there too on client side? WDYT?

**Comment by manusa** [comment]
I think the fix probably belongs to the Mock Server.
This is an invalid scenario, so whatever response we get from the Kubernetes API server when performing such request to a real cluster is what we should be returning in the Mock Server. However, if the real response is complex or unhelpful, throwing some other more helpful exception form the Mock Server might be more appropriate.

**Comment by rohanKanojia** [comment]
I think you're talking about CRUD mode. I'm not sure if @brandonheck  was using CRUD mode. This is the same test in CRUD mode from above:
```java
@EnableKubernetesMockClient(crud = true)
class SecretTest {
  KubernetesClient client;
  KubernetesMockServer server;

  @Test
  void testPatchSecretNoMetadata() {
    Secret secret = new SecretBuilder()
      .addToData("key.json", "{\"foo\":\"bar\"}")
      .build();
    Secret createdSecret = client.secrets().inNamespace("foo").create(secret);
    createdSecret.getData().put("value.json", "{}");
    Resource<Secret> secretOp = client.secrets().inNamespace("foo").withName("foo");
    secretOp.patch(createdSecret);
  }
}
```

This fails with another NullPointerException but in KubernetesAttributesExtractor:
```

Mar 11, 2021 7:49:14 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[36101] starting to accept connections
Mar 11, 2021 7:49:15 PM okhttp3.mockwebserver.MockWebServer$3 execute
SEVERE: MockWebServer[36101] connection from /127.0.0.1 crashed
java.lang.NullPointerException
	at io.fabric8.kubernetes.client.server.mock.KubernetesAttributesExtractor.extractMetadataAttributes(KubernetesAttributesExtractor.java:154)
	at io.fabric8.kubernetes.client.server.mock.KubernetesCrudAttributesExtractor.extract(KubernetesCrudAttributesExtractor.java:36)
	at io.fabric8.kubernetes.client.server.mock.KubernetesAttributesExtractor.fromResource(KubernetesAttributesExtractor.java:123)
	at io.fabric8.kubernetes.client.server.mock.KubernetesCrudDispatcher.doCreate(KubernetesCrudDispatcher.java:309)
	at io.fabric8.kubernetes.client.server.mock.KubernetesCrudDispatcher.handleCreate(KubernetesCrudDispatcher.java:97)
	at io.fabric8.kubernetes.client.server.mock.KubernetesCrudDispatcher.dispatch(KubernetesCrudDispatcher.java:74)
	at okhttp3.mockwebserver.MockWebServer$3.processOneRequest(MockWebServer.java:558)
	at okhttp3.mockwebserver.MockWebServer$3.processConnection(MockWebServer.java:516)
	at okhttp3.mockwebserver.MockWebServer$3.execute(MockWebServer.java:443)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
