### ISSUE TITLE
Remove unused imports spread across codebase

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#2803]
According to Sonar[0], we have 68 unused imports across the codebase. It doesn't affect anything but it's always nice to have cleaner import statements. In case someone is interested in a quick issue to fix, he/she can pick this issue.

[0] https://sonarcloud.io/organizations/fabric8io/issues?resolved=false&rules=java%3AS1128

**Comment by amitdaga** [comment]
Hi @rohanKanojia, I can look into this. Can you please assign it to me (if no one is working on this)?

**Comment by ArunjunaiSathish** [comment]
@rohanKanojia @amitdaga I have fixed in my local repo. Will be raising PR by Feb 15. I'm starting to contribute this repo by taking this as my first issue. Thanks!
