### ISSUE TITLE
Simplify JUnit `assertTrue/assertFalse` to the corresponding dedicated assertion

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#2805]
We have these assertions in `ConfigMapTest`:
https://github.com/fabric8io/kubernetes-client/blob/b015fb957047956d3656c3043e4c663957e82de9/kubernetes-model-generator/kubernetes-model-core/src/test/java/io/fabric8/kubernetes/api/model/ConfigMapTest.java#L71-L74

Instead of `assertTrue()` we should use `assertEquals` for comparing while asserting expected results. You can read more about this here[0]. There are other places too where this pattern is followed[1], we should refactor these to use dedicated exception.

[0] https://sonarcloud.io/organizations/fabric8io/rules?open=java%3AS5785&rule_key=java%3AS5785
[1] https://sonarcloud.io/organizations/fabric8io/issues?projects=fabric8io_kubernetes-client&resolved=false&rules=java%3AS5785

**Comment by amitdaga** [comment]
Hi @rohanKanojia, I can look into this. Can you please assign it to me (if no one is working on this)?
