### ISSUE TITLE
Simplify builder creation for classes extending CustomResource

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#2807]
At the moment custom resources need the following:

1. extend `CustomResource`
2. use `@Version` / `@Group`
3. use `@Buildable(editableEnabled=false, builderPackage="io.fabric8.kubernetes.api.builder", refs = @BuildableReference(CustomResource.class))`

In some cases, references to other resources may be needed, like: ObjectMeta, Container, Port, Volume, Mount, Env (pretty much anything our annotator adds).

Now, to get part *3* right, knowledge of how the `@Buildable` annotation is required and I'd like to change that.

## Thoughts

I am wondering if we should have in the client side and a processor (an maybe an annotation?) that have the same effect as *3*.
This could work either explicitly using a custom annotation or implicitly when we generate crds.

### Explicit

For example we could have `@KuberentesBuildable` that implied all the above.

### Implicit

We could also go into implicit mode and just assume that all custom resources are buildables. Then we could trigger the builder generation ourselves with the right parameters.
Users could still be able to pass their own `@Buidlable` annotation configuration, in which case we should let sundrio do its thing.

Thoughts?

**Comment by metacosm** [comment]
I'd rather go with the implicit way if possible.

**Comment by manusa** [comment]
+1 On the implicit

**Comment by FWiesner** [comment]
@iocanel do you have a working sundrio example builder configuration for now?

```java
@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
@EqualsAndHashCode(callSuper = true)
@JsonTypeName("FooResource")
@Buildable(editableEnabled = false,
        generateBuilderPackage = true,
        builderPackage = "io.fabric8.kubernetes.api.builder",       
        refs = {
                @BuildableReference(ObjectMeta.class),
                @BuildableReference(CustomResource.class)
        }
)
@Singular("foo")
@Plural("foos")
@Group("thebargroup.baz")
@Version("v666")
@Kind("FooResource")
public class FooResource extends CustomResource<FooSpec, Void> implements Namespaced {
  @JosonProperty("metadata")
  private ObjectMeta metadata;

  @JosonProperty("spec")
  private FooSpec spec;
}
```
this one at least gives a lot of reported clashes with 5.x

**Comment by metacosm** [comment]
@FWiesner note that in that specific configuration you don't need the `Plural`, `Kind` or even the `spec` or `metadata` fields.

**Comment by metacosm** [comment]
@iocanel could you show an example of the before and after cases, please?

**Comment by metacosm** [comment]
Note that we probably need to extend the `Buildable` quality to the spec and status classes if they exist as well. See #3076 for why.

**Comment by metacosm** [comment]
@iocanel is this still relevant with the latest sundrio changes?
