### ISSUE TITLE
How to approve/reject CSR?

### ISSUE THREAD

**Issue by tkinsoon** [fabric8io/kubernetes-client#2811]
Hi,

May I know how to approve/reject the CertificateSigningRequest?
FYI, I was able to create the CSR with the sample below
https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#certificatesigningrequest

I created a new condition and update to the existing CSR when I received the event

               CertificateSigningRequestCondition condition = new CertificateSigningRequestConditionBuilder()
                        .withLastUpdateTime("2021-02-13T11:37:35Z")
                        .withMessage("Approved By Self-Service Portal Admin")
                        .withReason("ApprovedBySelfServicePortalAdmin")
                        .withType("Approved")
                        .build();
                csr.getStatus().getConditions().add(condition)
                client.certificateSigningRequests().updateStatus(csr)

However, the status is not updated at all, appreciate your advice on this, thank you.

Regards,
TK

**Comment by tkinsoon** [comment]
``

**Comment by Tianny** [comment]
@tinakurian i met same problem.How do you solve the problem? Help

**Comment by rohanKanojia** [comment]
@Tianny : Please check if this helps

https://github.com/fabric8io/kubernetes-client/blob/51cc99a21b2844f663eac6258835f8a320bcc531/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/kubectl/equivalents/CertificateSigningRequestApproveYamlEquivalent.java#L31-L39

**Comment by Tianny** [comment]
> @Tianny : Please check if this helps
> 
> https://github.com/fabric8io/kubernetes-client/blob/51cc99a21b2844f663eac6258835f8a320bcc531/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/kubectl/equivalents/CertificateSigningRequestApproveYamlEquivalent.java#L31-L39
Thanks for your reply. But my k8s version is 1.10.x. the api version is "/apis/certificates.k8s.io/**v1beta1**/".  So i tried like this,
`        client.certificates().v1beta1().certificateSigningRequests().withName("my-cert")
`
the v1beta1() not have the approve() method.

**Comment by rohanKanojia** [comment]
@Tianny : oh, you're right. This looks like a bug to me. Could you please create an issue for this? 

Fixing this shouldn't be that hard. Just need to do the same stuff for v1beta1 CSR like done for v1 CSR in https://github.com/fabric8io/kubernetes-client/pull/3537

**Comment by rohanKanojia** [comment]
FYI `certificates.k8s.io/v1beta1` CertificateSigningRequest isn't supported since Kubernetes [1.22.0](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#certificatesigningrequest-v122). I've added it to DSL since we still have support for `client.certificates().v1beta1()` in DSL
