### ISSUE TITLE
Remove the unused private field

### ISSUE THREAD

**Issue by gandalf0151** [fabric8io/kubernetes-client#2825]
- [ ] Remove this unused "spec" private field

https://github.com/fabric8io/kubernetes-client/blob/5df8dae7fa31b009fe8971bacb50dccd63a47b6d/crd-generator/src/main/java/io/fabric8/crd/generator/apt/CustomResourceInfo.java#L34

[Sonarcloud.io issue page](https://sonarcloud.io/project/issues?fileUuids=AXeKpnxFmR8wXoZXwwEO&id=fabric8io_kubernetes-client&open=AXeKppG0mR8wXoZXwwF9&resolved=false)

**Comment by manusa** [comment]
relates to #2846

**Comment by gandalf0151** [comment]
@oscerd Kindly take a look at the PR #2861
