### ISSUE TITLE
Make `crd-generator` usable at runtime

### ISSUE THREAD

**Issue by metacosm** [fabric8io/kubernetes-client#2836]
This could help with Quarkus integration and make it possible for users to generate CRDs via other means than APT (e.g. maven plugin).

**Comment by manusa** [comment]
Does this translate into exposing the CRD-Generator core logic as an API?
If so, sound great to me. I can think of many different projects that would benefit from this.

**Comment by metacosm** [comment]
Yes, that would be the plan.
