### ISSUE TITLE
Make it possible to configure where the CRD is generated?

### ISSUE THREAD

**Issue by metacosm** [fabric8io/kubernetes-client#2842]
It would make sense to generate all kubernetes-related artifacts in a single location for a given project. As some other projects also generate kubernetes artifacts (dekorate, quarkus), it would make sense for users to be able to select where the CRDs are generated.

Thoughts, @iocanel @manusa?

**Comment by manusa** [comment]
I would go for providing a configuration option with a default value.

**Comment by metacosm** [comment]
> I would go for providing a configuration option with a default value.

Yes, that was my plan as well. I'm just not sure what's the best way to configure it.

**Comment by manusa** [comment]
In relation with #2836 it should be really easy once the CRD-Generator has its own API.

For the APT usage, then probably an annotation or a Maven->System property are the ways to go.

**Comment by metacosm** [comment]
Perhaps we could also select a better default location? What do you think, @manusa @iocanel?

**Comment by metacosm** [comment]
This issue was mostly about the Java Operator SDK work so that CRDs could be generated in the same spot as the files that the Quarkus Kubernetes extension. This was worked around in the Quarkus extension for the Java Operator SDK. While the underlying issue is still valid, there's no more need for this at the moment so closing it for now.
