### ISSUE TITLE
Secret createOrReplace throws error in case of update

### ISSUE THREAD

**Issue by paolodedo** [fabric8io/kubernetes-client#2847]
Hello!

Using _io.fabric8:kubernetes-client:5.1.1_

If I execute

```
kubernetesClient.secrets()
                .inNamespace(getNamespace())
                .createOrReplace(secret);
```

and my secret already exists, this very error is thrown:

`Exception in thread "SimpleAsyncTaskExecutor-56" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://xxx/api/v1/namespaces/test2/secrets/secret. Message: Operation cannot be fulfilled on secrets "secret": StorageError: invalid object, Code: 4, Key: /registry/secrets/test2/secret, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 5bb1f15b-4365-4e83-83bb-c7b2bbf17c8c, UID in object meta: 694aaf90-7ff5-42cf-9a5b-a2bdb5794578. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=secrets, name=secret, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Operation cannot be fulfilled on secrets "secret": StorageError: invalid object, Code: 4, Key: /registry/secrets/test2/secret, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 5bb1f15b-4365-4e83-83bb-c7b2bbf17c8c, UID in object meta: 694aaf90-7ff5-42cf-9a5b-a2bdb5794578, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict, status=Failure, additionalProperties={}).`

Instead of reapplying the secret; so, atm, I am deleting and recreating.

Is that normal?

Thanks!!

**Comment by rohanKanojia** [comment]
Umm, Would it be possible for you to share your secret with which we can reproduce this?

**Comment by paolodedo** [comment]
Thank you, but unfortunately, I cannot.

Doesn't this happen for every secret, when you try to recreate it with the same name? (in order to understand!)

**Comment by rohanKanojia** [comment]
Umm, does this code work in your K8s cluster:
```java
try (KubernetesClient client = new DefaultKubernetesClient()) {
    Secret secret = new SecretBuilder()
            .withNewMetadata().withName("secret-sa-sample").endMetadata()
            .addToData("extra", "YmFyCg==")
            .build();

    // Create
    secret = client.secrets().inNamespace("default").createOrReplace(secret);

    secret.getMetadata().setLabels(Collections.singletonMap("foo", "bar"));

    // Replace
    client.secrets().inNamespace("default").createOrReplace(secret);
}
```

**Comment by paolodedo** [comment]
> Umm, Would it be possible for you to share your secret with which we can reproduce this? looks like there is some problem in your object itself...
> 
> ```
> StorageError: invalid object, Code: 4, Key: /registry/secrets/test2/secret, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 5bb1f15b-4365-4e83-83bb-c7b2bbf17c8c, UID in object meta: 694aaf90-7ff5-42cf-9a5b-a2bdb5794578.
> ```

Well, I don't think it is an object problem, since the _create_ is made without any problem; for now, the object I am trying to replace is the same that is already present on kube...is that a problem or should it still get updated?

**Comment by paolodedo** [comment]
Thank you for the example. I was persisting old metadata and that caused the Conflict error. 
Thanks for your help 🚀
