### ISSUE TITLE
Sources for kubernetes-model not present for 4.13.0

### ISSUE THREAD

**Issue by bishtsaurabh5** [fabric8io/kubernetes-client#2852]
Hello,
kubernetes-model artifact for the version 4.13.0 does not have any sources file .
Can someone please upload the sources file in the mvn repository .
<dependency>
    <groupId>io.fabric8</groupId>
    <artifactId>kubernetes-model</artifactId>
    <version>4.13.0</version>
</dependency>

**Comment by rohanKanojia** [comment]
We had split Kubernetes model into different artifacts[0]. Which one are you referring to?

[0] https://github.com/fabric8io/kubernetes-client/tree/master/kubernetes-model-generator

**Comment by bishtsaurabh5** [comment]
I am referring to the https://repo1.maven.org/maven2/io/fabric8/kubernetes-model/4.13.0/ artifact

**Comment by manusa** [comment]
This package is empty, it's an empty artifact. There are no sources neither javadocs.

Are you probably searching for the core [artifact](https://repo1.maven.org/maven2/io/fabric8/kubernetes-model-core/4.13.0/)?
