### ISSUE TITLE
Cannot change the type of the Service from ClusterIP to ExternalName with PATCH

### ISSUE THREAD

**Issue by jorsol** [fabric8io/kubernetes-client#2853]
The PR #2472 fixed the replace method, but the patch method should also handle the update of the service to ExternalName.

It assumes a patch with ClusterIP:
https://github.com/fabric8io/kubernetes-client/blob/33a735a61a121083e4dfd0e9ba9105e62936cca6/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/ServiceOperationsImpl.java#L66-L77

**Comment by rohanKanojia** [comment]
@jorsol : Thanks a lot for reporting this, Would it be possible for you to submit a fix for this issue?

**Comment by jorsol** [comment]
Yes, I could submit a fix for this issue.

**Comment by jorsol** [comment]
Is there an ETA for 5.2.0?

**Comment by manusa** [comment]
We're planning on releasing by the end of next week or beginning of the other.
