### ISSUE TITLE
Incomplete error log in case of error in an EventHandler of an Informer

### ISSUE THREAD

**Issue by hibnico** [fabric8io/kubernetes-client#2857]
If for some reason, the user code in the EventHandler hooked into an Informer throws an exception, the resulting error logs are not informative. It logs as:
`ERROR io.fabric8.kubernetes.client.informers.cache.ProcessorListener - Failed invoking null event handler: {}`

The log format is inorrect, and it would be nice to have the stack trace.

**Comment by rohanKanojia** [comment]
It seems to be coming from here:
https://github.com/fabric8io/kubernetes-client/blob/c35c77f05392d12e77fbd7b428934f1eafb0aca6/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/ProcessorListener.java#L63

Would really appreciate it if you could raise a PR to fix this :-)

**Comment by hibnico** [comment]
I am currently pushing one, you're commenting too fast ;)
