### ISSUE TITLE
Override withResourceVersion() in custom classes

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#286]
BaseOperation, is invoking constructors via reflection for some methods.
This works in most of the XXX Operation implementation but not for:

ReplicationControllerOperationsImpl
and
BuildConfigOperationsImpl

As of 268221fd2abdb9fb8817ec0e7f017fd8334acae3 BaseOperation supports withResourceVersion() method using constructor reflection. We should override  withResourceVersion() for those two classes with a custom implementation.

**Comment by jimmidyson** [comment]
Think this is now working as it should.
