### ISSUE TITLE
Is templateRef supported when creating a replication controller ?

### ISSUE THREAD

**Issue by ramukima** [fabric8io/kubernetes-client#287]
Could not find an example how to do it if its already supported.

**Comment by iocanel** [comment]
I am not sure I understand what you mean.

There used to be a templateRef field as part of the replication controller spec but it has been removed for a while now (since July). Is this what you are talking about?

**Comment by ramukima** [comment]
Yes, thanks, thats what I was looking for. Understand it is not supported anymore.
