### ISSUE TITLE
PodUpload silently fails to upload files with long file names.

### ISSUE THREAD

**Issue by msinger-dev** [fabric8io/kubernetes-client#2871]
While investigating a test failure we found out, that PodUpload has problems with long file names. The culprit for that is the following line:
`try (final TarArchiveOutputStream tar = new TarArchiveOutputStream(gzip)) {`
(io.fabric8.kubernetes.client.dsl.internal.uploadable.PodUpload:111)

When creating a TarArchiveOutputStream without any additional configuration. the `longFileMode` member is set to 
```
/**
     * Fail if a long file name is required in the archive.
     */
    public static final int LONGFILE_ERROR = 0;
```
This option lets the upload fail once we encounter a file with a long relative file path. Another problem we found is that the exception thrown by this error is silently ignored.

**Comment by rohanKanojia** [comment]
@msinger-dev : Thanks a lot for reporting this. I think we're close to releasing our next release in coming weeks. Would it be possible for you to submit fixes for the issues you found if you have time?

**Comment by msinger-dev** [comment]
Yes, will do so.
