### ISSUE TITLE
Support a list of namespaces for informers

### ISSUE THREAD

**Issue by skonto** [fabric8io/kubernetes-client#2874]
After the introduction of the sharedInformer capabilities it would be nice to introduce a multi-namespaced cache or some other mechanism  to solve the issue described [here](https://github.com/kubernetes/kubernetes/issues/74415). Controller runtime already has a [multi-namespaced](https://github.com/kubernetes-sigs/controller-runtime/commit/fc804a411c06919561edbcb0453601c436556613#diff-cf71f1c7387ae1d9a63da1f81380effac1b826d0c3c1594c4d05da4324be2159) cache for this purpose and this feature would enhance the story for writing operators in Java. The implementation in ctr-runtime (check link above) keeps one cache/informer per ns I think we can have a similar approach in fabric.
/cc @rohanKanojia @iocanel wdyth?

**Comment by rohanKanojia** [comment]
Right now we support namespaced informers like this:
```java
SharedIndexInformer<Pod> podInformerInDefaultNamespace = informerFactory.inNamespace("default")
                    .sharedIndexInformerFor(Pod.class, 10 * 1000L);
```
I think what Stavros is suggesting is to provide a method in API to accept a list of namespaces too:
```java
SharedIndexInformer<Pod> podInformerInDefaultNamespace = informerFactory.inNamespace(Arrays.asList("ns1", "ns2", "ns3"))
                    .sharedIndexInformerFor(Pod.class, 10 * 1000L);
```

@manusa @metacosm : What do you think about adding this?

**Comment by metacosm** [comment]
I think that we need to balance what should be in the client and what should be in an SDK that sits atop of the client. The fact that the original feature is in controller-runtime seems to indicate it might be a better fit for the java-operator-sdk, perhaps? That said, the same could be said of informers, probably…

**Comment by skonto** [comment]
@metacosm We can move it to the java-operator-sdk for sure, should I open a ticket there?

**Comment by metacosm** [comment]
@skonto I don't know for sure :) It's just that if we try to equate this client to client-go, then java-operator-sdk would be more akin to controller-runtime. Since informers are already in the client, it might make sense to keep the functionality here as well.

**Comment by skonto** [comment]
Ok that was my initial thought because I felt that these capabilities fit better at the client side, because they seem pretty basic to me. How can we proceed with a design doc or a PR?

**Comment by manusa** [comment]
I subscribe what @metacosm [mentions on his comment](https://github.com/fabric8io/kubernetes-client/issues/2874#issuecomment-792659020).

I know the operator implements a Cache too and functionality similar to that provided by our Shared informers. However, I think that functionality is not built on top of the informers.

I'm not sure if more users are interested in seeing this feature at the client level, probably leaving this for a vote/open discussion would be good.

If the Operator is going to use our provided Shared informers, and their common functionality is merged upstream, it might make sense to have this here. If not, then we're duplicating efforts and providing different approaches to solve the same problem (IMHO).

**Comment by skonto** [comment]
> If the Operator is going to use our provided Shared informers, and their common functionality is merged upstream, it might make sense to have this here.

I agree there should be one place for the functionality, but people may want to build their own stuff and may dont want to use the java operator for some reason for this kind of functionality. I would vode this to be part of the client since Informers are here, it is an extension of it imho.

**Comment by manusa** [comment]
@skonto I do see your point.

Maybe it's better if we try to align with the Operator SDK team.

@metacosm @csviri are you planning on switching to SharedInformers at some point? Are you using them for other purposes?

**Comment by iocanel** [comment]
Since we have `SharedIndexInformer` in the client and since using multiple namespaces is a valid use case, I think we need to proceed and implement this, here.

If we ever decide to move the functionality over to the operator-sdk that's another story and I don't think that it should prevent us from adding features here. 
Just to clarify, I am not against a potential move.

**Comment by manusa** [comment]
> Just to clarify, I am not against a potential move.

I think we all agree on the same point. My comment was meant the other way around, Operator team moving some of their stuff upstream so at least development efforts can be aligned. Of course this would only be possible if none of the current functionality provided by the client is removed and new features like the one suggested can still be added.
That's why I'm curious on what's their take on this matter and see how to proceed.

**Comment by csviri** [comment]
@manusa Our initial idea was to wrap the informer into event sources. Event sources are quite specific context for the operator SDK, so I not see how it would fit here. So rather other way around, using informers in the JOSDK.

**Comment by manusa** [comment]
> So rather other way around, using informers in the JOSDK.

So I understand you intend to use informers there :rocket: 

When I say moving "stuff" upstream, it was more related to low-level things and not higher-level abstractions such as Event sources. If you finally move to use Shared informers I'm sure there'll be some of these implementations that we'll have to revisit.

**Comment by shawkins** [comment]
@rohanKanojia asked me about this issue.  I would say this is not needed yet in fabric8.  It is pretty straight-forward to create an informer per namespace and aggregate however you need.
