### ISSUE TITLE
.withPropagationPolicy and .withGracePeriod DSL methods can't be combined

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#2885]
## Description
Methods [`withPropagationPolicy`](https://github.com/fabric8io/kubernetes-client/blob/016242160fd040717728b4167252e35232c82364/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/PropagationPolicyConfigurable.java#L36) and [`withGracePeriod`](https://github.com/fabric8io/kubernetes-client/blob/b4873f45663b811df798f50c36c693ff44b33e1b/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/GracePeriodConfigurable.java#L29) cannot be combined to produce a DELETE request with grace period and propagation policy query params.

**Relates to:**
- #2676 
- #2883

**Comment by rohanKanojia** [comment]
Umm, Is this specific to Resource API? I can see their combination in standard kubernetes resources DSL :

https://github.com/fabric8io/kubernetes-client/blob/e9526e030916b0225658bc915f3b605fcf8ebfdf/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PropagationPolicyTest.java#L204
