### ISSUE TITLE
How to create secret  of docker-registry

### ISSUE THREAD

**Issue by yangjinlogic** [fabric8io/kubernetes-client#2887]
I want to run the command :
kubectl create secret docker-registry harbor-secret --namespace=default --docker-server=http://harbor.inner.com --docker-username=admin --docker-password=Harbor12345

**Comment by rohanKanojia** [comment]
We don't have direct support for creating Docker registry secrets on the fly. But I think you should be able to create it by manually creating Docker Config like this:
```java
public class CreateDockerSecret {
    public static void main(String[] args) throws JsonProcessingException {
        Map<String, Object> dockerConfig = createDockerConfig("http://harbor.inner.com", "admin", "Harbor12345");
        String dockerConfigAsStr = Serialization.jsonMapper().writeValueAsString(dockerConfig);

        try (KubernetesClient client = new DefaultKubernetesClient()) {
            client.secrets().inNamespace("default").createOrReplace(new SecretBuilder()
                    .withNewMetadata().withName("harbor-secret").endMetadata()
                    .withType("kubernetes.io/dockerconfigjson")
                    .addToData(".dockerconfigjson", Base64.getEncoder().encodeToString(dockerConfigAsStr.getBytes()))
                    .build());
        }
    }

    private static Map<String, Object> createDockerConfig(String dockerServer, String username, String password) {
        Map<String, Object> dockerConfigMap = new HashMap<>();
        Map<String, Object> auths = new HashMap<>();
        Map<String, Object> credentials = new HashMap<>();
        credentials.put("username", username);
        credentials.put("password", password);
        String usernameAndPasswordAuth = username + ":" + password;
        credentials.put("auth", Base64.getEncoder().encodeToString(usernameAndPasswordAuth.getBytes()));
        auths.put(dockerServer, credentials);
        dockerConfigMap.put("auths", auths);

        return dockerConfigMap;
    }
}
```

**Comment by yangjinlogic** [comment]
@rohanKanojia   oh,I love u.

**Comment by manusa** [comment]
Should this issue be treated as a feature request to improve the UX when creating Secrets (e.g. helper methods to base64 encode values, docker specific methods, or whatever kubectl offers, etc.)?

**Comment by rohanKanojia** [comment]
`kubectl` does provide a way to create secret for [docker credentials](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-by-providing-credentials-on-the-command-line). I think maybe we can provide a helper method in [KubernetesResourceUtil](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java) to create secret from credentials:

```java
public static Secret createDockerRegistrySecret(String dockerServer, String username, String password) {
  // .. Create new Secret based on provided details
}
```

**Comment by rohanKanojia** [comment]
In order to complete this task, you need to follow these steps:
- Add a utility method `createDockerRegistrySecret` in KuberntesResourceUtil
- Add a test

**Comment by laxmikantbpandhare** [comment]
> In order to complete this task, you need to follow these steps:
> 
> * Add a utility method `createDockerRegistrySecret` in KuberntesResourceUtil
> * Add a test

thank you for then information @rohanKanojia. I will look into it.

**Comment by laxmikantbpandhare** [comment]
Raised PR #3321 which will fix this issue.
