### ISSUE TITLE
OpenShiftOAuthInterceptor does not attempt to use token from OpenShift config

### ISSUE THREAD

**Issue by jpechane** [fabric8io/kubernetes-client#289]
When the intercept() method is called it tries to use OAuth token for authentication. Unfortunately it does not try to use OAuth token already present in OpenShift config class and tries to perform its own authentication. It means that it is necessary to provide OpenShift username/password to a pod rusing the client.

The intercept method should contain a code like this

``` java
        if (Utils.isNotNullOrEmpty(config.getOauthToken())) {
            setAuthHeader(builder, config.getOauthToken());
        }
```

This issue was found when apiman manager tries to import services on OpenShift

**Comment by jimmidyson** [comment]
@iocanel I'm not sure of the point of `OpenShiftOAuthInterceptor` - can you tell me the use case please? Normally we would just use the details present in config as @jpechane says above.

**Comment by iocanel** [comment]
@jimmidyson: The idea is to support basic authentication for open shift if a token is not available.

The interceptor is supposed to use the token if available and if we get an auth error (http 401 or 403), it should try to retrieve a new token, even if one is already present (it may have expired?).

So, I think that even a token is provided, but results on auth errors, we should try to do retrieve a new one (if username / password are provided).

So, I am counter proposing to change the existing behaviour with a check that username/password are provided. e.g.

 if ((response.code() == 401 || response.code() == 403) && Utils.isNotNullOrEmpty(config.getUsername() && Utils.isNotNullOrEmpty(config.getPassword) {
// retrieve token using basic auth
}

**Comment by jimmidyson** [comment]
SGTM

**Comment by jpechane** [comment]
@iocanel It is good defensive proposal. So if the result code will contain both your and my changes (to use the token) then I am happy.

**Comment by jimmidyson** [comment]
The token from config is added in https://github.com/fabric8io/kubernetes-client/blob/86f42e178f9821f71367c883ea439f1c26c48387/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java#L105-L113 so should be unaffected by this interceptor unless the token specified has been revoked or expired.

**Comment by jpechane** [comment]
@jimmidyson  ok, I see a problem then. IMHO using token and basic authentication is mutually exclusive. If username and password is set because the code you have posted will mean that the token interceptor will not be added and only basic auth will be used. Which means that the token will never be used. So I either want to use token orbasic auth but I can never combine in that way that I'd want to use basic auth if token auth fails - thats the result of using ``else if`` in https://github.com/fabric8io/kubernetes-client/blob/86f42e178f9821f71367c883ea439f1c26c48387/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java#L105-L105

**Comment by jimmidyson** [comment]
@jpechane True - they are mutually exclusive as they use the same `Authorization` header. I don't see that as a problem though.

**Comment by jpechane** [comment]
@jimmidyson Correct me if I am wrong, @iocanel wrote
> The interceptor is supposed to use the token if available and if we get an auth error (http 401 or 403), it > should try to retrieve a new token, even if one is already present (it may have expired?).
> 
> So, I think that even a token is provided, but results on auth errors, we should try to do retrieve a new > one (if username / password are provided).

So I understand it in that way that basic auth is a *fallback* in case token auth will fail. Hence my impression that they should not be mutually exclusive. If it is not the case then you are right in declaring code to be correct.

**Comment by jimmidyson** [comment]
I personally feel they should be mutually exclusive. I can't see the use case for fallback. If you have the username/password to use just use that & let the openshift auth interceptor kick in. If you have a long lived API token (e.g. service account token) then use that.

Thoughts @iocanel?

**Comment by iocanel** [comment]
I wasn't accurate in my initial comment. The open shift auth interceptor does absolutely nothing with the auth token passed via config. It will only "cache" and "reuse" tokens that are product of basic auth, kicked after any auth failure. 

We could make the mutually exclusive during the init of the openshift client, so that if username and password are provided, the original interceptor to be replaced by open shift auth interceptor.

**Comment by jimmidyson** [comment]
Should probably throw an error if both are specified?

**Comment by iocanel** [comment]
Unless we have a way to discern which values are user originating and which values are service account, or kube config or env var, originating that would be a mistake.

A user could do something like:

Config confg = new ConfigBuilder()
.withUsername("user")
.withPassword("pass")
.build();

and get an error back just because there is forgotten ~/.kube/config lying around.

I dunno, this somehow doesn't feel right.

**Comment by jpechane** [comment]
I think it feels right - of course with descriptive, not cryptic, error. It is always better to throw an error that can be easily fixed than do a silent assumptions in the code that can in the end confuse the user.

**Comment by jimmidyson** [comment]
@jpechane Is this still a problem?
