### ISSUE TITLE
DeploymentStatus is always null when using @EnableKubernetesMockClient

### ISSUE THREAD

**Issue by victor-mars-rft** [fabric8io/kubernetes-client#2893]
I'm writing a test using `@EnableKubernetesMockClient(https = true, crud = true)`, the piece of code I'm trying to test is waiting for the deployment to become ready
```kotlin
        kubernetesClient.apps().deployments().inNamespace(namespace)
            .withName(createdDeployment.metadata.name)
            .waitUntilReady(100, TimeUnit.MILLISECONDS)
```
However this always fails as `Deployment#status` is `null`.

Is there a way to make MockServer launch deployments with Status? If not, can I somehow mock or inject my own values?

Thanks for the help :)

**Comment by rohanKanojia** [comment]
I'm not sure how to do it with CRUD mode enabled. However, you should be able to set watch expectations to return Watch events with status populated values in standard Kubernetes Mock Server with crud mode disabled. Here is an example:

 https://github.com/fabric8io/kubernetes-client/blob/1b4a4561542a98d75bf7f45cd203aae8a1db4e38/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java#L227-L245

**Comment by manusa** [comment]
In CRUD mode, you could probably create the Deployment providing your own DeploymentStatus value for the Deployment#status field.

**Comment by victor-mars-rft** [comment]
@manusa I ended up solving this issue by doing something similar, I didn't want to change the code which was creating the deployment because that's what I wanted to test.

Instead I created a Watcher on my test method to stub this deployment status upon deployment creation.

```kotlin
    private fun prepareStatusWatcher() {
        client.apps().deployments().inNamespace(expectedNamespace)
            .withName(deploymentName).watch(object : Watcher<Deployment> {
                override fun eventReceived(action: Watcher.Action?, resource: Deployment?) {
                    if (action == Watcher.Action.ADDED) {
                        resource?.status = DeploymentStatusBuilder()
                            .withReplicas(1)
                            .withReadyReplicas(1)
                            .withAvailableReplicas(1)
                            .build()
                        client.apps().deployments().inNamespace(expectedNamespace)
                            .withName(deploymentName)
                            .replace(resource)
                    }
                }

                override fun onClose(cause: KubernetesClientException?) {
                }
            })
    }
```

**Comment by manusa** [comment]
Nice!
