### ISSUE TITLE
Use adapter for making a Kubernetes client into an Openshfit client.

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#29]
Currently, the client always implements both KubernetesClient and OpenshiftClient it should be really awesome if we used an adapter that would turn the KubernetesClient into an Openshift client (if open shift is available).

**Comment by jimmidyson** [comment]
What was that about beer?

**Comment by iocanel** [comment]
The KubernetesClient could have a method like:

<E extends Extension> E adapt(Class<E> extensionType);

Openshift client then could just be such an Extension.

As a bonus point the adapt() could check if the extension is usable (like what we currently do in KubernetesHelper) in the main fabric8 project.
