### ISSUE TITLE
How to get deployment status

### ISSUE THREAD

**Issue by sundarvc** [fabric8io/kubernetes-client#2904]
Hi team,

What is the api to get the status of deployment ? 
I want to know if the status for example the following: "Success", "Starting" or "Failed".

Thanks,
Sundar

**Comment by rohanKanojia** [comment]
@sundarvc : Could you please elaborate? How would you do it with `kubectl`?

**Comment by alfonzjanfrithz** [comment]
I bumped and search to this question because I have the same problem. What my case was pretty much similar, I need to know what is the current `Deployment` status in more simplified manner, whether it is `Failed`, `Progressing`, or `Complete`.

It is not very straightforward apparently with the way kubernetes describe the statuses of the deployment, because it has several conditions described [here](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#deployment-status)

I am not too sure, whether this representing the correct conclusion, It could be better but I think this may work:

```java
Map<String, Condition> conditions = new HashMap<>();
for (DeploymentCondition dc : deployment.getStatus().getConditions()) {
    Condition condition = Condition.builder()
        .type(dc.getType())
        .status(dc.getStatus())
        .message(dc.getMessage()).build();

    conditions.put(condition.getType(), condition);
}

Condition available = conditions.get("Available");
if (available != null && Condition.STATUS_TRUE.equals(available.getStatus())) {
    return COMPLETED;
}

Condition progressing = conditions.get("Progressing");
if (progressing != null) {
    if (Condition.STATUS_TRUE.equals(progressing.getStatus())) {
        return PROGRESSING;
    } else if (Condition.STATUS_FALSE.equals(progressing.getStatus())) {
        return FAILED;
    } else {
        return UNKNOWN;
    }
}
```

**Comment by alfonzjanfrithz** [comment]
> I bumped and search to this question because I have the same problem. What my case was pretty much similar, I need to know what is the current `Deployment` status in more simplified manner, whether it is `Failed`, `Progressing`, or `Complete`.
> 
> It is not very straightforward apparently with the way kubernetes describe the statuses of the deployment, because it has several conditions described [here](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#deployment-status)
> 
> I am not too sure, whether this representing the correct conclusion, It could be better but I think this may work:
> 
> * Anything "Available" means its completed
> * If there is a "Progressing" and its "True" its still "Progressing"
> * If there is a "Progressing" and its "False" its "Failed"
> * Otherwise its "Unknown"
> 
> ```java
> Map<String, Condition> conditions = new HashMap<>();
> for (DeploymentCondition dc : deployment.getStatus().getConditions()) {
>     Condition condition = Condition.builder()
>         .type(dc.getType())
>         .status(dc.getStatus())
>         .message(dc.getMessage()).build();
> 
>     conditions.put(condition.getType(), condition);
> }
> 
> Condition available = conditions.get("Available");
> if (available != null && Condition.STATUS_TRUE.equals(available.getStatus())) {
>     return COMPLETED;
> }
> 
> Condition progressing = conditions.get("Progressing");
> if (progressing != null) {
>     if (Condition.STATUS_TRUE.equals(progressing.getStatus())) {
>         return PROGRESSING;
>     } else if (Condition.STATUS_FALSE.equals(progressing.getStatus())) {
>         return FAILED;
>     } else {
>         return UNKNOWN;
>     }
> }
> ```
> 
> Original implementation could be found [here](https://github.com/th2-net/th2-infra-mgr/blob/master/src/main/java/com/exactpro/th2/inframgr/statuswatcher/ResourceCondition.java)

This doesnt work very well. The reason why is because when there is an update of the deployment, the state of the conditions will be Available: True and Progressing: True.

So my solution now was adapted from the kubectl itself. https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/polymorphichelpers/rollout_status.go 

```go
// Status returns a message describing deployment status, and a bool value indicating if the status is considered done.
func (s *DeploymentStatusViewer) Status(obj runtime.Unstructured, revision int64) (string, bool, error) {
	deployment := &appsv1.Deployment{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructured(obj.UnstructuredContent(), deployment)
	if err != nil {
		return "", false, fmt.Errorf("failed to convert %T to %T: %v", obj, deployment, err)
	}
	if revision > 0 {
		deploymentRev, err := deploymentutil.Revision(deployment)
		if err != nil {
			return "", false, fmt.Errorf("cannot get the revision of deployment %q: %v", deployment.Name, err)
		}
		if revision != deploymentRev {
			return "", false, fmt.Errorf("desired revision (%d) is different from the running revision (%d)", revision, deploymentRev)
		}
	}
	if deployment.Generation <= deployment.Status.ObservedGeneration {
		cond := deploymentutil.GetDeploymentCondition(deployment.Status, appsv1.DeploymentProgressing)
		if cond != nil && cond.Reason == deploymentutil.TimedOutReason {
			return "", false, fmt.Errorf("deployment %q exceeded its progress deadline", deployment.Name)
		}
		if deployment.Spec.Replicas != nil && deployment.Status.UpdatedReplicas < *deployment.Spec.Replicas {
			return fmt.Sprintf("Waiting for deployment %q rollout to finish: %d out of %d new replicas have been updated...\n", deployment.Name, deployment.Status.UpdatedReplicas, *deployment.Spec.Replicas), false, nil
		}
		if deployment.Status.Replicas > deployment.Status.UpdatedReplicas {
			return fmt.Sprintf("Waiting for deployment %q rollout to finish: %d old replicas are pending termination...\n", deployment.Name, deployment.Status.Replicas-deployment.Status.UpdatedReplicas), false, nil
		}
		if deployment.Status.AvailableReplicas < deployment.Status.UpdatedReplicas {
			return fmt.Sprintf("Waiting for deployment %q rollout to finish: %d of %d updated replicas are available...\n", deployment.Name, deployment.Status.AvailableReplicas, deployment.Status.UpdatedReplicas), false, nil
		}
		return fmt.Sprintf("deployment %q successfully rolled out\n", deployment.Name), true, nil
	}
	return fmt.Sprintf("Waiting for deployment spec update to be observed...\n"), false, nil
}
```
