### ISSUE TITLE
Move crd-generator tests out of kubernetes-itests

### ISSUE THREAD

**Issue by jorsol** [fabric8io/kubernetes-client#2910]
The tests/folder in https://github.com/fabric8io/kubernetes-client/tree/master/kubernetes-itests/src/test/java/io/fabric8/crd is not an "integration test", it doesn't need a connection to an active kubernetes cluster, so it should not belong to the `kubernetes-itests` module.

As this is more a "unit test" like, probably it should be inside the same `crd-generator-apt` module, or at best in the module `kubernetes-test` module.

Just as a side note, this test is not running on CI, since the e2e-tests workflow filter the tests that are from `-Dtest="io.fabric8.[kubernetes|openshift].**"` not the io.fabric8.crd.

/cc @metacosm

**Comment by metacosm** [comment]
We need to improve the coverage for the CRD generator as well.

**Comment by metacosm** [comment]
> As this is more a "unit test" like, probably it should be inside the same `crd-generator-apt` module, or at best in the module `kubernetes-test` module.

Problem is you need the artifact to exist and the annotation processor in it to run on the test sources so it's not really feasible to put the tests in the same module.

**Comment by jorsol** [comment]
> > As this is more a "unit test" like, probably it should be inside the same `crd-generator-apt` module, or at best in the module `kubernetes-test` module.
> 
> Problem is you need the artifact to exist and the annotation processor in it to run on the test sources so it's not really feasible to put the tests in the same module.

Then maybe into `kubernetes-tests`?
