### ISSUE TITLE
Trigger available Tekton pipeline task from Tekton Client

### ISSUE THREAD

**Issue by ManjunathMS35** [fabric8io/kubernetes-client#2911]
Hello team,

I just started to use kubernetes and tekton, I have a question hope it's the right place.

I want to trigger an available Tekton pipeline in Kubernetes, from the command line I do this.

```tkn pipeline start PIPELINE_NAME -s SERVICE_ACCOUNT --workspace name=shared-workspace,claimName=task-pv-claim -p GITHUB_URL='' -p GITHUB_API_PATH='' -p REPO_OWNER='' -p REPO_NAME='' -p REPO_BRANCH=''```

Is it possible to achieve the above start command using tekton-client?

Best regards,
Manjunath

**Comment by rohanKanojia** [comment]
@Fabian-K : polite ping, Could you please share your thoughts on this? Do you know if we support this in the Tekton extension?

**Comment by Fabian-K** [comment]
Yes it is! `tkn pipeline start` is just creating a PipelineRun. You can use https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#tekton-client-dsl-usage -> Create a PipelineRun as a starting point but need to adjust it to your pipeline (e.g. parameters, workspace definition etc)

**Comment by ManjunathMS35** [comment]
@Fabian-K @rohanKanojia Thank you very much for your support. I could able to achieve the ```tkn start pipeline``` by creating the PipelineRun.
