### ISSUE TITLE
Provide DSL support for All Kubernetes resources

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#2912]
We need to provide DSL support for all resources which are marked as :x: . There are the resources which are provided by running command `kubectl api-resources` on Kubernetes v1.21.0:

| ApiGroup                       |    Kind                                |  Supported   |
|--------------------------------|----------------------------------------|--------------|
|                                |       Binding                          | :heavy_check_mark: `client.bindings()`   |
|                                |       ComponentStatus                  |  :heavy_check_mark: `client.componentstatuses()`   |
|                                |       ConfigMap                        |  :heavy_check_mark: `client.configMaps()`   |
|                                |       Endpoints                        |  :heavy_check_mark: `client.endpoints()`  |
|                                |       Event                            |  :heavy_check_mark: `client.v1().events()`   |
|                                |       LimitRange                       |  :heavy_check_mark: `client.limitRanges()`   |
|                                |       Namespace                        |  :heavy_check_mark: `client.namespaces()`   |
|                                |       Node                             |  :heavy_check_mark: `client.nodes()`   |
|                                |       PersistentVolumeClaim            |  :heavy_check_mark: `client.persistentVolumeClaims()`   |
|                                |       PersistentVolume                 |  :heavy_check_mark: `client.persistentVolumes()`  |
|                                |       Pod                              |  :heavy_check_mark: `client.pods()`   |
|                                |       PodTemplate                      |  :heavy_check_mark: `client.v1().podTemplates()`   |
|                                |       ReplicationController            |  :heavy_check_mark: `client.replicationControllers()`   |
|                                |       ResourceQuota                    |  :heavy_check_mark: `client.resourceQuotas()`   |
|                                |       Secret                           |  :heavy_check_mark: `client.secrets()`   |
|                                |       ServiceAccount                   |  :heavy_check_mark: `client.serviceAccounts()`   |
|                                |       Service                          |  :heavy_check_mark: `client.services()`   |
|  admissionregistration.k8s.io  |       MutatingWebhookConfiguration     |  :heavy_check_mark: `client.admissionRegistration().v1().mutatingWebhookConfigurations()`   |
|  admissionregistration.k8s.io  |       ValidatingWebhookConfiguration   |  :heavy_check_mark: `client.admissionRegistration().v1().validatingWebhookConfigurations()`   |
|  apiextensions.k8s.io          |       CustomResourceDefinition         |  :heavy_check_mark: `client.apiextensions().v1().customResourceDefinitions()`   |
|  apiregistration.k8s.io        |       APIService                       |  :heavy_check_mark: `client.apiServices()`   |
|  apps                          |       ControllerRevision               |  :heavy_check_mark: `client.apps().controllerRevisions()` https://github.com/fabric8io/kubernetes-client/pull/2980  |
|  apps                          |       DaemonSet                        |  :heavy_check_mark: `client.apps().daemonSets()`   |
|  apps                          |       Deployment                       |  :heavy_check_mark: `client.apps().deployments()`   |
|  apps                          |       ReplicaSet                       |  :heavy_check_mark: `client.apps().replicaSets()`   |
|  apps                          |       StatefulSet                      |  :heavy_check_mark: `client.apps().statefulSets()`   |
|  authentication.k8s.io         |       TokenReview                      |  :heavy_check_mark: `client.tokenReviews()`   |
|  authorization.k8s.io          |       LocalSubjectAccessReview         |  :heavy_check_mark: `client.authorization().v1().localSubjectAccessReview()`  |
|  authorization.k8s.io          |       SelfSubjectAccessReview          |  :heavy_check_mark: `client.authorization().v1().selfSubjectAccessReview()`   |
|  authorization.k8s.io          |       SelfSubjectRulesReview           |  :heavy_check_mark: `client.authorization().v1().subjectAccessReview()`   |
|  authorization.k8s.io          |       SubjectAccessReview              |  :heavy_check_mark: `client.authorization().v1().subjectAccessReview()`   |
|  autoscaling                   |       HorizontalPodAutoscaler          |  :heavy_check_mark: `client.autoscaling().v1().horizontalPodAutoscalers()`   |
|  batch                         |       CronJob                          |  :heavy_check_mark: `client.batch().cronjobs()`   |
|  batch                         |       Job                              |  :heavy_check_mark: `client.batch().jobs()`   |
|  certificates.k8s.io           |       CertificateSigningRequest        |  :heavy_check_mark: `client.certificates().v1().certificateSigningRequests()`   |
|  coordination.k8s.io           |       Lease                            |  :heavy_check_mark: `client.leases()`   |
|  discovery.k8s.io              |       EndpointSlice                    |  :heavy_check_mark: `client.discovery().v1beta1().endpointSlices()`   |
|  events.k8s.io                 |       Event                            |  :heavy_check_mark: `client.events().v1().events()` #2907   |
|  extensions                    |       Ingress                          |  :heavy_check_mark: `client.extensions().ingresses()`   |
|  flowcontrol.apiserver.k8s.io  |       FlowSchema                       |  :heavy_check_mark: `client.flowControl().v1beta1().flowSchema()` https://github.com/fabric8io/kubernetes-client/pull/2984  |
|  flowcontrol.apiserver.k8s.io  |       PriorityLevelConfiguration       |  :heavy_check_mark: `client.flowControl().v1beta1().priorityLevelConfigurations()` https://github.com/fabric8io/kubernetes-client/pull/2984  |
|  networking.k8s.io             |       IngressClass                     |  :heavy_check_mark: `client.network().v1().ingressClasses()`   |
|  networking.k8s.io             |       Ingress                          |  :heavy_check_mark: `client.network().v1().ingresses()`   |
|  networking.k8s.io             |       NetworkPolicy                    |  :heavy_check_mark: `client.network().v1().networkPolicies()`   |
|  node.k8s.io                   |       RuntimeClass                     |  :heavy_check_mark: `client.runtimeClasses()`   |
|  policy                        |       PodDisruptionBudget              |  :heavy_check_mark: `client.policy().podDisruptionBudget()`   |
|  policy                        |       PodSecurityPolicy                |  :heavy_check_mark: `client.policy().podSecurityPolicies()`  |
|  rbac.authorization.k8s.io     |       ClusterRoleBinding               |  :heavy_check_mark: `client.rbac().clusterRoleBindings()`  |
|  rbac.authorization.k8s.io     |       ClusterRole                      |  :heavy_check_mark: `client.rbac().clusterRoles()`  |
|  rbac.authorization.k8s.io     |       RoleBinding                      |  :heavy_check_mark: `client.rbac().roleBindings()`   |
|  rbac.authorization.k8s.io     |       Role                             |  :heavy_check_mark: `client.rbac().roles()`   |
|  scheduling.k8s.io             |       PriorityClass                    |  :heavy_check_mark: `client.scheduling().v1().priorityClasses()`   |
|  storage.k8s.io                |       CSIDriver                        |  :heavy_check_mark:  `client.storage().csiDrivers()` https://github.com/fabric8io/kubernetes-client/pull/2981  |
|  storage.k8s.io                |       CSINode                          |  :heavy_check_mark: `client.storage().csiNodes()` https://github.com/fabric8io/kubernetes-client/pull/2981   |
|  storage.k8s.io                |       StorageClass                     |  :heavy_check_mark: `client.storage().storageClasses()`   |
|  storage.k8s.io                |       VolumeAttachment                 |  :heavy_check_mark: `client.storage().volumeAttachments()` https://github.com/fabric8io/kubernetes-client/pull/2981  |
| storage.k8s.io                 |       CSIStorageCapacity       |  :heavy_check_mark: `client.storage().csiStorageCapacities()` #3010 |

**Comment by manusa** [comment]
![image](https://user-images.githubusercontent.com/488391/115225258-2c503480-a10e-11eb-9552-f31087b3c828.png)
This one is still missing

**Comment by rohanKanojia** [comment]
I noticed this when i upgraded my minikube to v1.21.0 . I'm sending a PR for this.

**Comment by manusa** [comment]
New DSLs implemented in the scope of this epic/issue can be checked by running:
```shell
jbang https://github.com/marcnuri-demo/fabric8-kubernetes-client-jbang/blob/main/I002912_KubernetesDSLSupport.java
```
