### ISSUE TITLE
Strange *FluentImpl generation behavior

### ISSUE THREAD

**Issue by Fabian-K** [fabric8io/kubernetes-client#2916]
Hi,

while working on https://github.com/fabric8io/kubernetes-client/pull/2872 I noticed a strange behavior. When serializing an EventListener, one field is not included for some cases.

The field in question is `.spec.resources.customResource`. You should be able to include any K8s entity there, the example shows a Knative Service.

```yaml
apiVersion: "triggers.tekton.dev/v1alpha1"
kind: "EventListener"
metadata:
  name: "sample"
spec:
  resources:
    customResource:
      apiVersion: "serving.knative.dev/v1"
      kind: "Service"
      spec:
        ...
```

In the model generator, I mapped this to `io.fabric8.kubernetes.api.model.HasMetadata`. The generated class looks good to me:
```java
public class Resources implements io.fabric8.kubernetes.api.model.KubernetesResource
{

    @JsonProperty("customResource")
    private HasMetadata customResource;
<...>
}
```

The generated FluentImpl however has some strange logic within `withCustomResource` which I don´t understand.
```java
public class ResourcesFluentImpl<A extends ResourcesFluent<A>> extends io.fabric8.kubernetes.api.builder.BaseFluent<A> implements ResourcesFluent<A> {

    private VisitableBuilder<? extends HasMetadata,?> customResource;
    
    <...>

    public ResourcesFluentImpl(Resources instance) {
        this.withCustomResource(instance.getCustomResource()); 
        this.withKubernetesResource(instance.getKubernetesResource()); 
    }

    public A withCustomResource(HasMetadata customResource) {
        if (customResource instanceof TriggerTemplate){ this.customResource= new TriggerTemplateBuilder((TriggerTemplate)customResource); _visitables.get("customResource").add(this.customResource);}
        if (customResource instanceof TriggerBinding){ this.customResource= new TriggerBindingBuilder((TriggerBinding)customResource); _visitables.get("customResource").add(this.customResource);}
        if (customResource instanceof ClusterTriggerBinding){ this.customResource= new ClusterTriggerBindingBuilder((ClusterTriggerBinding)customResource); _visitables.get("customResource").add(this.customResource);}
        if (customResource instanceof EventListener){ this.customResource= new EventListenerBuilder((EventListener)customResource); _visitables.get("customResource").add(this.customResource);}
        return (A) this;
    }

    <...>
}
```

If I see it correctly, this will drop customResources when it´s not one of the explicitly included classes (TriggerTemplate, TriggerBinding, ...). As a consequence, in my Knative Service example the information is lost.

I hope that does make sense, let me know if you need more information!

Thanks, Fabian

**Comment by rohanKanojia** [comment]
I'm wondering if this is some bug in sundrio

**Comment by shawkins** [comment]
Addressed by https://github.com/sundrio/sundrio/issues/374 and https://github.com/sundrio/sundrio/issues/350 

We can mark this as resolved once we get a new sundrio release.
