### ISSUE TITLE
StackOverflowError  when deserializing a Custom Resource

### ISSUE THREAD

**Issue by lburgazzoli** [fabric8io/kubernetes-client#2919]
I have a custom resource defined as follow:

```java
public interface MyResource extends HasMetadata {
}

@Version(MyCamelResource.VERSION)
@Group(MyCamelResource.GROUP)
public static class MyCamelResource
    extends CustomResource<MyCamelResourceSpec, MyCamelResourceStatus> implements MyResource {

    public static final String VERSION = "v1alpha1";
    public static final String GROUP = "acme.com";
    public static final String KIND = "MyCamelResource";

}

public static class MyCamelResourceSpec {
    String foo;

    public String getFoo() {
        return foo;
    }

    public void setFoo(String foo) {
        this.foo = foo;
    }
}

public static class MyCamelResourceStatus {
    String bar;

    public String getBar() {
        return bar;
    }

    public void setBar(String bar) {
        this.bar = bar;
    }
}
```

When the CR is de-serialized it causes:

```
Exception in thread "main" java.lang.StackOverflowError
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:268)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:16)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4569)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2908)
	at com.fasterxml.jackson.core.JsonParser.readValueAsTree(JsonParser.java:2311)
```

This seems to be related to the fact that the `MyResource` interface extends `HasMetadata` because if I remove it, iit works as expected.

To reproduce it:

```java
public static void main(String... args) throws Exception {
    KubernetesDeserializer.registerCustomKind(
        MyCamelResource.GROUP + "/" + MyCamelResource.VERSION,
        MyCamelResource.KIND,
        MyCamelResource.class);

    var cr = new MyCamelResource();
    cr.setSpec(new MyCamelResourceSpec());
    cr.setStatus(new MyCamelResourceStatus());

    var ser = Serialization.jsonMapper().writeValueAsString(cr);
    var des = Serialization.jsonMapper().readValue(ser, MyCamelResource.class);
}
```

**Comment by rohanKanojia** [comment]
Umm, what is your use case? why are you adding `implements MyResource `? CustomResource already extends `HasMetadata`

https://github.com/fabric8io/kubernetes-client/blob/6e439a876f3b7973c744aa35bece70aca4700f39/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/CustomResource.java#L69

**Comment by lburgazzoli** [comment]
I have multiple implementations of MyResource that share some common behavior among with dealing with CR's metadata (here I posted a simplified version to illustrate the issue) so I added this marker interface.

The first attempt was about having a base class extending CustomResource, but had got  https://github.com/fabric8io/kubernetes-client/issues/2900

**Comment by metacosm** [comment]
@lburgazzoli #2900 should be addressed for your use case now with 5.2.1.

Also, note that you shouldn't need to register your CR manually either.

**Comment by metacosm** [comment]
@lburgazzoli If you really need this particular use case to work, add the `@JsonDeserialize` annotation to your `MyResource` interface. This will prevent the infinite loop by forcing Jackson to not attempt to look up an implicit deserializer.

**Comment by lburgazzoli** [comment]
> Also, note that you shouldn't need to register your CR manually either.

Yep but in this case it was needed as got error because the CR was not found

**Comment by lburgazzoli** [comment]
@metacosm thx!

**Comment by metacosm** [comment]
> @lburgazzoli #2900 should be addressed for your use case now with 5.2.1.

Actually, it'd be great if you could check that it indeed works and close the issue, if that's the case. And maybe close this one as well… 😄

**Comment by lburgazzoli** [comment]
I'm on it, just need to build the entire stack to check all the open issues I have :)

**Comment by lburgazzoli** [comment]
Adding @JsonDeserialize fixes StackOverflowError
