### ISSUE TITLE
How to generate Java Classes specific to Volcano CRDs?

### ISSUE THREAD

**Issue by dipanjank** [fabric8io/kubernetes-client#2920]
Hi,

I am trying to generate Java class definitions for volcano (https://github.com/volcano-sh/volcano) CRDs defined in https://github.com/volcano-sh/volcano/tree/master/config/crd/v1beta1.  Can someone advise what is the easiest way to go about it? This is a one-off task so I tried to locally add a module to the kubernetes-model-generator sub-project, but I'm unsure what kube-schema.json and validation-schema.json will look like. 

Thanks in advance,
Dipanjan

**Comment by iocanel** [comment]
I would look at the generator modules of the client extensions, which are go programs that generate those schemas out of actual golang code.

The idea is more or less is that you specify which golang structs you want to convert to Java classes, then optionally define mappings of golang types to java ones, package mappings etc and then the generator does the rest.

**Comment by dipanjank** [comment]
Thanks for the quick explanation, it really helped. I will close the issue now.
