### ISSUE TITLE
KubernetesServer in crud mode should fill out missing metadata

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#2921]
An object created by Kubernetes server will not have additional metadata fields set such as uid, namespace, resourceVersion, and generation.  The workaround is to specify those on the object being created - but this is not inline with expected behavior.  Frameworks like the java operator sdk are making assumptions about those values being non-null.

This is somewhat related to https://github.com/fabric8io/kubernetes-client/issues/2802

**Comment by rohanKanojia** [comment]
@shawkins : Thanks a lot for reporting this. I agree we should fill out these fields. Do you have some approach in mind on how to tackle this? Maybe we can fill out these fields before persisting fields in MockServer map:

https://github.com/fabric8io/kubernetes-client/blob/6e439a876f3b7973c744aa35bece70aca4700f39/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java#L83-L89

**Comment by shawkins** [comment]
It seems a little involved with the current logic in KubernetesCrudDispatcher.  You need to update both the AttributeSet and string value of the object.  And to glean the namespace you need access to AttributeSet values.  This would look something like:

https://github.com/shawkins/kubernetes-client/commit/36bf842a6bad5eaf3957ed37dd7290e15933b30f

**Comment by shawkins** [comment]
@manusa @rohanKanojia opened https://github.com/fabric8io/kubernetes-client/pull/2943 and https://github.com/fabric8io/mockwebserver/pull/59

**Comment by manusa** [comment]
Hi @shawkins 
We'll check your PR. However it involves releasing MockWebServer which we don't have an ETA yet.

**Comment by shawkins** [comment]
@manusa do you want to back out the pom change and using the namespace from the path for now?

**Comment by manusa** [comment]
It will certainly speed up things. If we cut a release for MockServer we should make the most of the effort by at least upgrade dependencies and perform some other checks which will inevitably take some time.

**Comment by shawkins** [comment]
Pulled the mockwebserver upgrade out.

**Comment by shawkins** [comment]
https://github.com/fabric8io/kubernetes-client/pull/2946 is related to this change - together they address issues seen when trying to run the java operator sdk against a mock server.
