### ISSUE TITLE
Provide a dynamic client

### ISSUE THREAD

**Issue by lburgazzoli** [fabric8io/kubernetes-client#2929]
The official Kubernetes provides two types of clients 
- **typed** which relies on k8s.io/api structs and offer a type safe, programming model
- **untyped** which uses `unstructured.Unstructured` to represent any king of Kubernetes resource

The Fabric8 Kubernetes Client, is similar to the **typed** one as it requires the Java model representing the Kubernetes resource to be known but it forces to be tightly coupled with versions and the type used and for some use cases, having unstructured capabilities could be very useful. 

We can then introduce an `Unstructured` class, like:

```java
/**
 * Represent a generic Kubernetes resource and provides helper methods
 * to access common attributes such as namespace, spec, status, etc
 */
class Unstructured implements Map<String, Object> {
}
```

Which can be leverage for something like:

```java
var gvr = new GroupVersionResourceBuilder()
    .withGroup("apps")
    .withVersion("v1")
    .withResource("deployments")
    .build()

var res = new UnstructuredBuilder()
    .withField("apiVersion", "apps/v1")
    .withField("kind", "Deployment")
    .withSection("metadata")
        .withField("name", "my-deployment")
    .build()

// update or create     
Unstructured result = client.resource(gvr).inNamespace("ns").createOrUpdate(res);

// watch
client.resource(gvr).inNamespace("ns").watch(u -> {
    System.out.printf("a=%s, k=%s, n=%s\n", u.getApiVersion(), u.getKind(), u.getName());
})
```

**Comment by rohanKanojia** [comment]
Is your use case similar to this[0]

[0] https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#customresource-typeless-api

**Comment by lburgazzoli** [comment]
Yes similar to that one but not limited to `CustomResources`

**Comment by rohanKanojia** [comment]
@lburgazzoli : I was trying out using `ConfigMap` with this raw API as per our discussion in chat but unfortunately there is a bug in Raw API which doesn't allow it to work with code API(where apiGroup is ""). So this code:
```java
        try (KubernetesClient kubernetesClient = new DefaultKubernetesClient()) {
            CustomResourceDefinitionContext context = new CustomResourceDefinitionContext.Builder()
                    .withPlural("configmaps")
                    .withVersion("v1")
                    .withGroup("")
                    .withScope("Namespaced")
                    .build();

            Map<String, Object> output = kubernetesClient.customResource(context).inNamespace("default").list();
            System.out.println(Serialization.jsonMapper().writeValueAsString(output));
        } catch (JsonProcessingException e) {
            e.printStackTrace();
        }
```

results in this error:
```
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://192.168.39.182:8443/apis//v1/namespaces/default/configmaps. Message: 404 page not found
.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:583)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.handleFailure(RawCustomResourceOperationsImpl.java:1003)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.makeCall(RawCustomResourceOperationsImpl.java:994)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.makeCall(RawCustomResourceOperationsImpl.java:981)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.list(RawCustomResourceOperationsImpl.java:526)
	at io.fabric8.ConfigMapTypeless.main(ConfigMapTypeless.java:21)
```

I think it would be nice to have a dynamic DSL support in client which would simply be a wrapper around the customresource typeless API

**Comment by iocanel** [comment]
Some comments:

1. I feel that its an overkill to use something like a `GroupVersionResourceBuilder` and I'd rather have `group`, `version` and `kind` as methods arguments. Why? Because all 3 fields are mandatory.

2. I think that they entrypoint should be different than `resource` as currently resource() is used to pass an actual resource in different forms (String, Object, etc). For the generic bit, things are a little different. Maybe `generic`, `dyanmic`, `unstructured`? I tend to prefer the `unstructured` because its the most descriptive and also because the resource is also named `Unstructured`

Also, that entry point should lead to something similar to a `MixOperation` which is quite different from what we currently have for resource.

3. I think that the actual `Unstrucutred` resource should at least implement HasMetadata. Why? Because all resources are expected to have `apiVersion`, `kind` and `metadata`. And of course it will vastly simplify things implementation wise.

```
var res = new UnstructuredBuilder()
     .withApiVersion("apps/v1")
     .withKind("Deployment")
     .withNewMetadata()
       .withName("my-deployment")
    .endMetadata()
    .addToFields("spec", mySpec) // Where mySepc is a Map<String, Object>
    .addToFields("status, myStatus) // Where myStatus is Map<String, Object>
   .build();
```

**Comment by iocanel** [comment]
> @lburgazzoli : I was trying out using `ConfigMap` with this raw API as per our discussion in chat but unfortunately there is a bug in Raw API which doesn't allow it to work with code API(where apiGroup is ""). So this code:
> 
> ```java
>         try (KubernetesClient kubernetesClient = new DefaultKubernetesClient()) {
>             CustomResourceDefinitionContext context = new CustomResourceDefinitionContext.Builder()
>                     .withPlural("configmaps")
>                     .withVersion("v1")
>                     .withGroup("")
>                     .withScope("Namespaced")
>                     .build();
> 
>             Map<String, Object> output = kubernetesClient.customResource(context).inNamespace("default").list();
>             System.out.println(Serialization.jsonMapper().writeValueAsString(output));
>         } catch (JsonProcessingException e) {
>             e.printStackTrace();
>         }
> ```
> 
> results in this error:
> 
> ```
> Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://192.168.39.182:8443/apis//v1/namespaces/default/configmaps. Message: 404 page not found
> .
> 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:583)
> 	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.handleFailure(RawCustomResourceOperationsImpl.java:1003)
> 	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.makeCall(RawCustomResourceOperationsImpl.java:994)
> 	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.makeCall(RawCustomResourceOperationsImpl.java:981)
> 	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.list(RawCustomResourceOperationsImpl.java:526)
> 	at io.fabric8.ConfigMapTypeless.main(ConfigMapTypeless.java:21)
> ```
> 
> I think it would be nice to have a dynamic DSL support in client which would simply be a wrapper around the customresource typeless API

Can't we just change that ? Also shouldn't the group in that case be null? Eitherways, we need to fix that so that it works for both null or blank.

Ping me if you need me to help with that.

**Comment by lburgazzoli** [comment]
> Some comments:
> 
>     1. I feel that its an overkill to use something like a `GroupVersionResourceBuilder` and I'd rather have `group`, `version` and `kind` as methods arguments. Why? Because all 3 fields are mandatory.
> 

Yeah, fine with me. 

The example I wrote was an adaptation of what one would do with the dynamic client provided by the official client-go implementation with the primary aime to offer some sort of similar experience between the two clients, but definitively not an issue to go with a simpler way.

>     2. I think that they entrypoint should be different than `resource` as currently resource() is used to pass an actual resource in different forms (String, Object, etc). For the generic bit, things are a little different. Maybe `generic`, `dyanmic`, `unstructured`? I tend to prefer the `unstructured` because its the most descriptive and also because the resource is also named `Unstructured`
> 

+1 for `unstructured`

> 
>     1. I think that the actual `Unstrucutred` resource should at least implement HasMetadata. Why? Because all resources are expected to have `apiVersion`, `kind` and `metadata`. And of course it will vastly simplify things implementation wise.
> 
> ```
> var res = new UnstructuredBuilder()
>      .withApiVersion("apps/v1")
>      .withKind("Deployment")
>      .withNewMetadata()
>        .withName("my-deployment")
>     .endMetadata()
>     .addToFields("spec", mySpec) // Where mySepc is a Map<String, Object>
>     .addToFields("status, myStatus) // Where myStatus is Map<String, Object>
>    .build();
> ```

+1 this matches my original idea 

I'm also thinking if the `Unstructured` object should have some helper method that accept a JSON Pointer to select a specific node, something similar to `JsonNode.at(String jsonPtrExpr)` in Jackson.

**Comment by chirino** [comment]
Keep in mind root fields don't have to be javascript objects.  So maybe update that example to:

       .addToFields("foo", myObject) // where myObject is an Object

**Comment by manusa** [comment]
> @lburgazzoli : I was trying out using ConfigMap with this raw API as per our discussion in chat but unfortunately there is a bug in Raw API which doesn't allow it to work with code API(where apiGroup is ""). So this code:
 
> Can't we just change that ? Also shouldn't the group in that case be null? Eitherways, we need to fix that so that it works for both null or blank.

I think the Raw/Typeless CustomResource API should suffice for the needs as is.
Unless I'm mistaken, cases where apiGroup is blank should only be applicable for the Core K8s API, for which we provide the necessary types. Is there a valid use-case to access the Core API in a typeless fashion?

To deal with these situations in JKube we implemented a [GenericCustomResource](https://github.com/eclipse/jkube/blob/master/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/GenericCustomResource.java) which might be something in the line of what you're proposing for the Unstructured resource so +1 for unstructured too.

**Comment by lburgazzoli** [comment]
> 
> I think the Raw/Typeless CustomResource API should suffice for the needs as is.
> Unless I'm mistaken, cases where apiGroup is blank should only be applicable for the Core K8s API, for which we provide the necessary types. Is there a valid use-case to access the Core API in a typeless fashion?
> 

I think there should not be any difference in functionality between typed and dynamic client so with the dynamic one, one should be able to deal with any kind of resource, regardless if the type exists or not.

For my specific use case, the resources I have to deal with are not known up-front so they could be custom resources, known kubernetes types and what not and having a way to access any resource in a consistent way, without having the need to probe for the type, would be very beneficial and would make the code simpler.

**Comment by manusa** [comment]
I see your point, we can try to fix the issue. However, I still see that having an "optional" group identifier may backfire at us in the future.

**Comment by rohanKanojia** [comment]
@shawkins @manusa : Shall we close this issue?

**Comment by shawkins** [comment]
There may need to be more docs.   And there was some discussion about the CustomResourceDefinitionContext class name in this scenario - it may be better to have a base ResourceDefinitionContext.

**Comment by shawkins** [comment]
This can be resolved now based upon the introduction of the ResourceDefinitionContext, related entry points, and deprecation of the Map related methods.
