### ISSUE TITLE
Calling delete() on a list should not return true if the list is empty

### ISSUE THREAD

**Issue by victornoel** [fabric8io/kubernetes-client#2931]
Hi,

I'm using the following to delete one or several jobs:
```java
boolean deleted = Optional.ofNullable(
                        client.batch().jobs()
                                .inNamespace(namespace)
                                .withLabel("label", "value)
                                .delete()
```

And this always return true even if there are no matching jobs.

IMHO `BaseOperation.deleteList()` should return the value of `delete(list)` it calls, and `BaseOperation.delete()` too.

**Comment by rohanKanojia** [comment]
Right now we're returning false in case the requested URL is not found:

https://github.com/fabric8io/kubernetes-client/blob/6e439a876f3b7973c744aa35bece70aca4700f39/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java#L699-L703

**Comment by rohanKanojia** [comment]
I was just trying to provide additional information

**Comment by shawkins** [comment]
Marking as a duplicate for #3982
