### ISSUE TITLE
can't fetch pvc status conditon list

### ISSUE THREAD

**Issue by ztyandjw** [fabric8io/kubernetes-client#2933]
version: 5.2.1

code:

![image](https://user-images.githubusercontent.com/14125652/111729535-3e8a4900-88aa-11eb-8421-a6e79558ca51.png)

can't fetch pvc status condition

![image](https://user-images.githubusercontent.com/14125652/111729380-e2bfc000-88a9-11eb-9e38-b6a12516b35a.png)

but use kubeclt could get it

![image](https://user-images.githubusercontent.com/14125652/111729403-f703bd00-88a9-11eb-8402-dc8919c1ef52.png)

**Comment by manusa** [comment]
Have you checked if the yaml output from kubectl includes data in the `status.conditions` field?
