### ISSUE TITLE
feature enhancement : Clone did not supported in most of api under kubernetes and openshift java client

### ISSUE THREAD

**Issue by bipinmaurya** [fabric8io/kubernetes-client#2934]
Let me explain the requirement,
I have want to make small change in an existing deployment and want to create a new deployment with few minor changes in the existing KuberneteClient api(e.g container resources, env. etc). 
I did not found a way to create a new deployment using the deep cloning.

Thanks,
Bipin

**Comment by manusa** [comment]
You can easily clone any resource by serializing and deserializing it. Not the most performant way, but should do the job.

**Comment by chetanmeh** [comment]
Got reference to this issue in [gitter conversation](https://gitter.im/fabric8io/kubernetes-client?at=606b1450458fc52d5f2ff88a) with @rohanKanojia  

Adding to above comment you can first clone an existing `Deployment` and then remove some of the system generated fields

```scala
private def cleanup(dep: Deployment): KDeploymentBuilder = {
    new KDeploymentBuilder(dep)
      .editMetadata()
      .withAnnotations(null)
      .withCreationTimestamp(null)
      .withGenerateName(null)
      .withGeneration(null)
      .removeFromLabels("app.kubernetes.io/managed-by")
      .withNamespace(null)
      .withOwnerReferences(null.asInstanceOf[util.List[OwnerReference]])
      .withResourceVersion(null)
      .withSelfLink(null)
      .withManagedFields(null.asInstanceOf[util.List[ManagedFieldsEntry]])
      .withUid(Null)
      .endMetadata()
      .withNewStatus()
      .endStatus()
  }
```

Here used approach taken in [kubectl-eksporter][1]. Then you can adapt this deployment per your needs. Like change the selector pattern or edit env

```scala
def withMatchLabel(key: String, value: String): DeploymentBuilder = {
    builder = builder
      .editMetadata()
      .addToLabels(key, value) //Deployment metadata label
      .endMetadata()
      .editSpec()
      .withNewSelector()
      .addToMatchLabels(key, value) // Template selector label
      .endSelector()
      .editTemplate()
      .editMetadata()
      .addToLabels(key, value) // Template spec label
      .endMetadata()
      .endTemplate()
      .endSpec()
    this
  }

def withEnv(containerName: String, env: Map[String, String]): DeploymentBuilder = {
    // editMatchingContainer would throw exception if no matching container is found
    val envVars = env.map { case (k, v) => new EnvVar(k, v, Null) }.toList.asJava
    builder = builder
      .editSpec()
      .editTemplate()
      .editSpec()
      .editMatchingContainer(_.getName == containerName)
      .addAllToEnv(envVars)
      .endContainer()
      .endSpec()
      .endTemplate()
      .endSpec()
    this
  }
```

And then redeploy this "adapted" deployment. So far this approach is working for cloning deployments in our case

[1]: https://github.com/Kyrremann/kubectl-eksporter/blob/master/eksporter.rb

**Comment by manusa** [comment]
There's a new [`clone(T resource)`](https://github.com/fabric8io/kubernetes-client/blob/1093d5bea6b9396bf5697306a1ca7dc61330104c/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java#L335) method as part of the Serialization utility class.
