### ISSUE TITLE
There is no method specified in the documentation

### ISSUE THREAD

**Issue by sleepdan** [fabric8io/kubernetes-client#2936]
Hey! There is no method specified in the documentation [here](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#customresourcedefinition). I want "Load a CustomResourceDefinition from yaml:
" as described:
```java
CustomResourceDefinition customResourceDefinition = client.customResourceDefinitions().load(new FileInputStream("/sparkapplication-crd.yml")).get();
``` 
but in class KubernetesClient (I use latest version 5.2.1 of kubernetes-client) has no method client.customResourceDefinitions().

**Comment by manusa** [comment]
Documentation needs to be updated to:
```java
CustomResourceDefinition customResourceDefinition = client.apiextensions().v1().customResourceDefinitions().load(new FileInputStream("/sparkapplication-crd.yml")).get();
```

**Comment by manusa** [comment]
Hi @sleepdan, would you like to create a PR to fix the documentation with the suggested approach?

**Comment by sleepdan** [comment]
Yes, of course, I think it would be useful for everyone.
