### ISSUE TITLE
Impossible to define standalone Tekton Trigger

### ISSUE THREAD

**Issue by goldmann** [fabric8io/kubernetes-client#2938]
Currently the only way to create a TektonTrigger is to do it via EventListener object. This is not sufficient, because with the ability to use namespace selectors within EventListeners we would not need to the register it in an EventListener and the EL would be responsible for finding TektonTriggers it should handle.

Can we register a standalone Tekton Trigger today? I don't see anything exposed in the `tektonClient.v1alpha1()`. Am I missing something? Or it's something we lack suport for?

Possibly related to #2742.

**Comment by goldmann** [comment]
Javadocs confirm what I say above - there are no Triggers exposed: https://www.javadoc.io/doc/io.fabric8/tekton-client/latest/io/fabric8/tekton/client/dsl/V1alpha1APIGroupDSL.html. But we can find TriggerBindings and TriggerTemplates. Why is that? What should be done to add it?

@rohanKanojia Any help?

**Comment by rohanKanojia** [comment]
Hello, I haven't checked what's new in recent releases ofTekton. I think we should add support for TektonTrigger in DSL if it's supported in recent versions of Tekton. @Fabian-K : WDYT??

**Comment by goldmann** [comment]
Thanks!

Yesterday after I added the comment I started looking at it and I have made some progress. It may be that I'll be submit a PR to expose it. I just need to better understand how things are generated :) I'll keep you posted.

**Comment by rohanKanojia** [comment]
@goldmann : awesome, Thanks a lot for the update.

**Comment by Fabian-K** [comment]
Oh you are right, the Trigger CRD is currently missing and needs to be added. The only reason for it is that Triggers were not initially there when I started working on the extension... and when they added it I missed to include it for generation.

If you are already working on a PR, great! Let me know if you need support.

**Comment by goldmann** [comment]
So, I've opened a draft PR so that everyone can see what kind of changes I made which made it possible for me to interact withe Tekton Triggers the way I described: https://github.com/fabric8io/kubernetes-client/pull/2948. I tested it locally in Minikube.

I would be more than happy to understand if this is the way to go so that we can move forward this patch.

**Comment by goldmann** [comment]
I would like to understand what would be the next steps to incorporate my PR?

I'm not hiding the fact that this is an important piece required in my project 😌 And I would like to move with this fast if there is willingness to accept it.

**Comment by rohanKanojia** [comment]
I see your PR is still marked as draft. Is it ready for review? If yes, I'll request project collaborators for review and we can merge it.

**Comment by goldmann** [comment]
@rohanKanojia Yep, ready, I just undrafted it. Thanks!
