### ISSUE TITLE
Reflector not stopping underlying Watcher until startWatcher is called again

### ISSUE THREAD

**Issue by hanikesn** [fabric8io/kubernetes-client#2941]
After stopping a sharedInformer it seems like the watches are still active #2939. The controller correctly calls `.stop()` on the reflector, but looking at the [reflector](https://github.com/fabric8io/kubernetes-client/blob/0d9e634a7850ca0121446ca326e93d33a556b7ec/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Reflector.java#L93):

```Java
  public void stop() {
    isActive.set(false);
  }
```

it's only marked as non-active and the Watch itself keeps running until it get's started again:

```Java
  private void startWatcher() {
    log.debug("Starting watcher for resource {} v{}", apiTypeClass, lastSyncResourceVersion.get());
    if (watch.get() != null) {
      log.debug("Stopping previous watcher");
      watch.get().close();
    }
...
```

I think the correct behavior would be to `watch.get().close()` immediately in `stop()` to make sure the watch is ended properly.

cc @rohanKanojia

**Comment by rohanKanojia** [comment]
@hanikesn : Would you like to create a PR to fix this?

**Comment by hanikesn** [comment]
I'll try to come up with something, but might take a few weeks before I can come back to thus.

**Comment by rohanKanojia** [comment]
I've tried addressing this in [#2964](https://github.com/fabric8io/kubernetes-client/pull/2964/files#diff-3695023c244c8d9e6298dd9f9cb05dbf6d5b20b3d11bdd22b5424850ec41f1d5R93) . Would appreciate it if you could review

**Comment by rohanKanojia** [comment]
Since #2964 is merged, shall we close this one?

**Comment by hanikesn** [comment]
Feel free to close it already, but I'll find some time this week to test if it resolves our issue as well and then I can close it on my own.

**Comment by rohanKanojia** [comment]
Sounds good to me. We can wait for your feedback.

**Comment by hanikesn** [comment]
I wasn't able to configure our build system to work with my custom SNAPSHOT build, so I'll wait for the 5.3.0 release to make testing easier. I'll close this for now and will reopen if the issue isn't resolved.
