### ISSUE TITLE
ClassNotFound Exception when upgrading from version 4.10 to 5.2

### ISSUE THREAD

**Issue by Etone** [fabric8io/kubernetes-client#2942]
# Whats the Problem

After upgrading the fabric8 client from version 4.10.x to 5.2, we have a weird problem with the mock server in our unit tests. It seems, that some classes (e.g., `io/fabric8/kubernetes/model/annotation/Group.class`) can no longer be detected in the class path. After invalidation all maven caches and basically resetting everything from scratch, the issue persisted. It seems that the dependencies io.fabric8.kubernetes-client and io.fabric8.mockwebserver that are embedded in the io.fabric8.kubernetes-server-mock are in the wrong versions.

# What we did to solve it

We excluded those two dependencies and added them back in their right versions, which worked. It seems this was the only solution, but this seems a bit wrong, that we have to explictily state the dependencies in our pom.xml file.

Is this a known issue when migrating we just missed? 

Thanks, if you need any more info, just leave a comment

**Comment by manusa** [comment]
All versions are tied together:
- https://github.com/fabric8io/kubernetes-client/blob/faf7555f4f15681452ac3b42cce557e2e73ba7fa/pom.xml#L26
- https://github.com/fabric8io/kubernetes-client/blob/faf7555f4f15681452ac3b42cce557e2e73ba7fa/kubernetes-client/pom.xml#L24
- https://github.com/fabric8io/kubernetes-client/blob/faf7555f4f15681452ac3b42cce557e2e73ba7fa/kubernetes-server-mock/pom.xml#L24

Are you sure it might not be something else?

**Comment by Etone** [comment]
As I said, specifying the versions on our own helped fix the build break. We had the break on our local machines as well as our CICD solution without any maven dependency caching. It seems the mockwebserver model is not up2date or something. and the problem only occurs with the mock webserver, not with the code usage.

Parts of the pom.xml that we changed
``` xml
...
    <fabric8.version>5.2.1</fabric8.version>
    <mockwebserver.version>0.1.8</mockwebserver.version>
...
 <dependency>
      <groupId>io.fabric8</groupId>
      <artifactId>kubernetes-server-mock</artifactId>
      <version>${fabric8.version}</version>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <groupId>io.fabric8</groupId>
          <artifactId>kubernetes-client</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.fabric8</groupId>
          <artifactId>mockwebserver</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>io.fabric8</groupId>
      <artifactId>mockwebserver</artifactId>
      <version>${mockwebserver.version}</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>io.fabric8</groupId>
      <artifactId>kubernetes-model-common</artifactId>
      <version>${fabric8.version}</version>
      <scope>test</scope>
    </dependency>
```

**Comment by manusa** [comment]
The `kubernetes-server-mock` artifact has a transitive dependency to the mockwebserver, why are you adding that dependency explicitly?
Is this the workaround you're talking about (meaning if you don't add the exclusions + explicit dependencies, your project won't work)?

**Comment by Etone** [comment]
Yes, this is exactly the workaround. Before that, we got a ClassNotFound exception. It seems that the transitiv dependency did not match the expected  mock-webserver and the kubernetes-model one. This came in a fresh environment (Build runs inside a container without any caching in our CICD Pipeline)
