### ISSUE TITLE
Whether it support  paging?

### ISSUE THREAD

**Issue by yangjinlogic** [fabric8io/kubernetes-client#2944]
How to  support  paging of PVC list

**Comment by rohanKanojia** [comment]
You should be able to use paging with providing limit and continue in `ListOptions`. You can read more about it here[0]:
```
client.persistentVolumeClaims().inNamespace("foo").list(new ListOptionsBuilder().withLimit(3L).withContinue("").build());
```
[0] https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#list-options
