### ISSUE TITLE
Add support for all OpenShift resources in OpenShiftClient DSL

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#2949]
This is the output(openshift specific resources filtered) of `kubectl api-resources` on an OpenShift v4.7.0 cluster.
|    APIGROUP                         |             KIND                            |  OpenShiftClient DSL    |
|-------------------------------------|---------------------------------------------|------|
|    apps.openshift.io                |            DeploymentConfig      | :heavy_check_mark: `openShiftClient.deploymentConfigs()`
|    authorization.openshift.io       |            ClusterRoleBinding      | :heavy_check_mark: ` openShiftClient.clusterRoleBindings()`
|    authorization.openshift.io       |            ClusterRole      | :heavy_check_mark: #3133 `client.clusterRoles()` 
|    authorization.openshift.io       |            LocalResourceAccessReview      | :heavy_check_mark: #3133  `client.localResourceAccessReviews()`
|    authorization.openshift.io       |            LocalSubjectAccessReview      | :heavy_check_mark: `openShiftClient.localSubjectAccessReviews()`
|    authorization.openshift.io       |            ResourceAccessReview      | :heavy_check_mark: #3133  ` client.resourceAccessReviews()`
|    authorization.openshift.io       |            RoleBindingRestriction      | :heavy_check_mark: #3133 `client.roleBindingRestrictions()`
|    authorization.openshift.io       |            RoleBinding      | :heavy_check_mark: `openShiftClient.roleBindings()`
|    authorization.openshift.io       |            Role      | :heavy_check_mark: `openShiftClient.roles()`
|    authorization.openshift.io       |            SelfSubjectRulesReview      | :heavy_check_mark: #3133 `client.selfSubjectRulesReviews()`
|    authorization.openshift.io       |            SubjectAccessReview      | :heavy_check_mark: #3133 `openShiftClient.subjectAccessReviews()`
|    authorization.openshift.io       |            SubjectRulesReview      | :heavy_check_mark: #3133  `client.subjectRulesReviews()`
|    autoscaling.openshift.io         |            ClusterAutoscaler      | :heavy_check_mark: #3193 `openShiftClient.clusterAutoscaling().v1().clusterAutoscalers()`
|    autoscaling.openshift.io         |            MachineAutoscaler      | :heavy_check_mark: #3193 `openShiftClient.clusterAutoscaling().v1beta1().machineAutoscalers()`
|    build.openshift.io               |            BuildConfig      | :heavy_check_mark: `openShiftClient.buildConfigs()`
|    build.openshift.io               |            Build      | :heavy_check_mark: ` openShiftClient.builds()`
|    cloudcredential.openshift.io     |            CredentialsRequest      | :heavy_check_mark: #3226 `openShiftClient.credentialsRequests()`
|    config.openshift.io              |            APIServer      | :heavy_check_mark: `openShiftClient.config().apiServers()`
|    config.openshift.io              |            Authentication      | :heavy_check_mark: #3111 `openShiftClient.config().authentications()` 
|    config.openshift.io              |            Build      | :x: 
|    config.openshift.io              |            ClusterOperator      | :heavy_check_mark: `openShiftClient.config().clusterOperators()`
|    config.openshift.io              |            ClusterVersion      | :heavy_check_mark: `openShiftClient.config().clusterVersions()`
|    config.openshift.io              |            Console      | :heavy_check_mark: #3111  `openShiftClient.config().consoles()` 
|    config.openshift.io              |            DNS      | :heavy_check_mark: #3111 `openShiftClient.config().dnses()` 
|    config.openshift.io              |            FeatureGate      | :heavy_check_mark: `openShiftClient.config().featureGates()`
|    config.openshift.io              |            Image      | :x: 
|    config.openshift.io              |            Infrastructure      | :heavy_check_mark: `openShiftClient.config().infrastructures()`
|    config.openshift.io              |            Ingress      | :heavy_check_mark: `openshiftClient.config().ingresses()` #2947
|    config.openshift.io              |            Network      |  :heavy_check_mark: #3111 `openShiftClient.config().networks()` 
|    config.openshift.io              |            OAuth      | :heavy_check_mark: `openShiftClient.config().oAuths()`
|    config.openshift.io              |            OperatorHub      | :heavy_check_mark: `openShiftClient.config().operatorHubs()`
|    config.openshift.io              |            Project      | :x: 
|    config.openshift.io              |            Proxy      | :heavy_check_mark: `openShiftClient.config().proxies()`
|    config.openshift.io              |            Scheduler      | :heavy_check_mark: ` openShiftClient.config().schedulers()`
|    console.openshift.io             |            ConsoleCLIDownload      | :heavy_check_mark: `openShiftClient.console().consoleCLIDownloads()`
|    console.openshift.io             |            ConsoleExternalLogLink      | :heavy_check_mark: `openShiftClient.console().consoleExternalLogLinks()`
|    console.openshift.io             |            ConsoleLink      | :heavy_check_mark: `openShiftClient.console().consoleLinks()`
|    console.openshift.io             |            ConsoleNotification      | :heavy_check_mark: `openShiftClient.console().consoleNotifications()`
|    console.openshift.io             |            ConsolePlugin      | :heavy_check_mark: #3205  `openShiftClient.console().consolePlugins()`
|    console.openshift.io             |            ConsoleQuickStart      | :heavy_check_mark: #3205 `openShiftClient.console().consoleQuickStarts()`
|    console.openshift.io             |             ConsoleYAMLSample      | :heavy_check_mark: `openShiftClient.console().consoleYAMLSamples()`
|    controlplane.operator.openshift.io |          PodNetworkConnectivityCheck      | :heavy_check_mark: #3142 `openShiftClient.operator().podNetworkConnectivityChecks()`
|    helm.openshift.io                  |          HelmChartRepository      |  :heavy_check_mark: #3150 `openShiftClient.helmChartRepositories()`
|    image.openshift.io                 |          Image      | :heavy_check_mark: ` openShiftClient.images()`
|    image.openshift.io                 |          ImageSignature      | :heavy_check_mark: #3219 `openShiftClient.imageSignatures()`
|    image.openshift.io                 |          ImageStreamImage      | :heavy_check_mark: #3219 `openShiftClient.imageStreamImages()`
|    image.openshift.io                 |          ImageStreamImport      | :heavy_check_mark: #3219 `openShiftClient.imageStreamImports()`
|    image.openshift.io                 |          ImageStreamMapping      | :heavy_check_mark: #3219 `openShiftClient.imageStreamMappings()`
|    image.openshift.io                 |          ImageStream      | :heavy_check_mark: `openShiftClient.imageStreams()`
|    image.openshift.io                 |          ImageStreamTag      | :heavy_check_mark: `openShiftClient.imageStreamTags()`
|    image.openshift.io                 |           ImageTag      | :heavy_check_mark: `openShiftClient.imageTags()`
|    imageregistry.operator.openshift.io  |        Config      | :heavy_check_mark: #3226  `openShiftClient.imageRegistryOperatorConfigs()
`
|    imageregistry.operator.openshift.io  |        ImagePruner      | :heavy_check_mark: `openShiftClient.operator().imagePruners()`
|    ingress.operator.openshift.io        |        DNSRecord      | :heavy_check_mark: `openShiftClient.operator().dnsRecords()`
|    k8s.cni.cncf.io                      |        NetworkAttachmentDefinition      | :heavy_check_mark: #3226 `openShiftClient.networkAttachmentDefinitions()`
|    machine.openshift.io                 |        MachineHealthCheck      | :heavy_check_mark: #3173 `openShiftClient.machine().machines()` 
|    machine.openshift.io                 |        Machine      | :heavy_check_mark: #3173 `openShiftClient.machine().machineSets()`
|    machine.openshift.io                 |        MachineSet      | :heavy_check_mark: #3173 `openShiftClient.machine().machineHealthChecks()`
|    machineconfiguration.openshift.io    |        ContainerRuntimeConfig      | :heavy_check_mark: #3166 `client.machineConfigurations().containerRuntimeConfigs()`
|    machineconfiguration.openshift.io    |        ControllerConfig      | :heavy_check_mark: #3166 `client.machineConfigurations().controllerConfigs()`
|    machineconfiguration.openshift.io    |        KubeletConfig      | :heavy_check_mark: #3166 `client.machineConfigurations().containerRuntimeConfigs()`
|    machineconfiguration.openshift.io    |        MachineConfigPool      | :heavy_check_mark: #3166 `client.machineConfigurations().machineConfigPools()`
|    machineconfiguration.openshift.io    |        MachineConfig      | :heavy_check_mark: #3166 `client.machineConfigurations().machineConfigs()`
|    metal3.io                            |        BareMetalHost      | :heavy_check_mark: #3226 `openShiftClient.bareMetalHosts()`
|    metal3.io                            |        Provisioning      | :x: 
|    migration.k8s.io                     |        StorageState      | :heavy_check_mark: #3224 `openShiftClient.kubeStorageVersionMigrator().storageStates()`
|    migration.k8s.io                     |        StorageVersionMigration      | :heavy_check_mark: #3224 `openShiftClient.kubeStorageVersionMigrator().storageVersionMigrations()`
|    monitoring.coreos.com                |        AlertmanagerConfig      |  :heavy_check_mark: #3142 `openShiftClient.monitoring().alertmanagerConfigs()`
|    monitoring.coreos.com                |        Alertmanager      | :heavy_check_mark: `openShiftClient.monitoring().alertmanagers()`
|    monitoring.coreos.com                |        PodMonitor      | :heavy_check_mark: `openShiftClient.monitoring().podMonitors()`
|    monitoring.coreos.com                |        Probe      | :heavy_check_mark: #3142 `openShiftClient.monitoring().probes()`
|    monitoring.coreos.com                |        Prometheus      | :heavy_check_mark: `openShiftClient.monitoring().prometheuses()`
|    monitoring.coreos.com                |        PrometheusRule      | :heavy_check_mark: `openShiftClient.monitoring().prometheusRules()`
|    monitoring.coreos.com                |        ServiceMonitor      | :heavy_check_mark: `openShiftClient.monitoring().serviceMonitors()`
|    monitoring.coreos.com                |        ThanosRuler      | :heavy_check_mark: #3142 `openShiftClient.monitoring().thanosRulers()` 
|    network.openshift.io                 |        ClusterNetwork      | :heavy_check_mark: `openShiftClient.clusterNetworks()`
|    network.openshift.io                 |        EgressNetworkPolicy      | :heavy_check_mark: `openShiftClient.egressNetworkPolicies()`
|    network.openshift.io                 |        HostSubnet      | :heavy_check_mark: #3150 `openShiftClient.hostSubnets()`
|    network.openshift.io                 |        NetNamespace      | :heavy_check_mark:  `openShiftClient.netNamespaces()`
|    network.operator.openshift.io        |        OperatorPKI      | :heavy_check_mark: #3226 `openShiftClient.operatorPKIs()`
|    oauth.openshift.io                   |        OAuthAccessToken      | :heavy_check_mark: `openShiftClient.oAuthAccessTokens()`
|    oauth.openshift.io                   |        OAuthAuthorizeToken      | :heavy_check_mark: `openShiftClient.oAuthAuthorizeTokens()`
|    oauth.openshift.io                   |        OAuthClientAuthorization      | :heavy_check_mark: #3226 `openShiftClient.oAuthClientAuthorizations()`
|    oauth.openshift.io                   |        OAuthClient      | :heavy_check_mark: `openShiftClient.oAuthClients()`
|    oauth.openshift.io                   |        UserOAuthAccessToken      | :heavy_check_mark: #3226 `openShiftClient.userOAuthAccessTokens()`
|    operator.openshift.io                |        Authentication      | :heavy_check_mark: `openShiftClient.operator().authentications()`
|    operator.openshift.io                |        CloudCredential      | :heavy_check_mark: #3142  `openShiftClient.operator().cloudCredentials()`
|    operator.openshift.io                |        ClusterCSIDriver      | :heavy_check_mark: #3142 `openShiftClient.operator().clusterCSIDrivers()` 
|    operator.openshift.io                |        Config      | :heavy_check_mark: #3142 `openShiftClient.operator().configs()`
|    operator.openshift.io                |        Console      | :heavy_check_mark: `openShiftClient.operator().consoles()`
|    operator.openshift.io                |        CSISnapshotController      | :heavy_check_mark: `openShiftClient.operator().csiSnapshotControllers()`
|    operator.openshift.io                |        DNS      | :heavy_check_mark: `openShiftClient.operator().dnses()`
|    operator.openshift.io                |        Etcd      | :heavy_check_mark: `openShiftClient.operator().etcds()`
|    operator.openshift.io                |        ImageContentSourcePolicy      | :heavy_check_mark: `openShiftClient.operator().imageContentSourcePolicies()`
|    operator.openshift.io                |        IngressController      | :heavy_check_mark: `openShiftClient.operator().ingressControllers()`
|    operator.openshift.io                |        KubeAPIServer      | :heavy_check_mark: `openShiftClient.operator().kubeAPIServers()`
|    operator.openshift.io                |        KubeControllerManager      | :heavy_check_mark: `openShiftClient.operator().kubeControllerManagers()`
|    operator.openshift.io                |        KubeScheduler      | :heavy_check_mark: `openShiftClient.operator().kubeSchedulers()`
|    operator.openshift.io                |        KubeStorageVersionMigrator      | :heavy_check_mark: `openShiftClient.operator().kubeStorageVersionMigrators()`
|    operator.openshift.io                |        Network      | :heavy_check_mark: `openShiftClient.operator().networks()`
|    operator.openshift.io                |        OpenShiftAPIServer      | :heavy_check_mark: `openShiftClient.operator().openShiftAPIServers()`
|    operator.openshift.io                |        OpenShiftControllerManager      | :heavy_check_mark: `openShiftClient.operator().openShiftControllerManagers()`
|    operator.openshift.io                |        ServiceCA      | :heavy_check_mark: `openShiftClient.operator().serviceCAs()`
|    operator.openshift.io                |        Storage      | :heavy_check_mark: #3142 `openShiftClient.operator().storages()`
|    operators.coreos.com                 |        CatalogSource      | :heavy_check_mark: `openShiftClient.operatorHub().catalogSources()`
|    operators.coreos.com                 |        ClusterServiceVersion      | :heavy_check_mark: `openShiftClient.operatorHub().clusterServiceVersions()`
|    operators.coreos.com                 |        InstallPlan      | :heavy_check_mark: `openShiftClient.operatorHub().installPlans()`
|    operators.coreos.com                 |        OperatorCondition      | :heavy_check_mark: #3207 `openShiftClient.operatorHub().operatorConditions()`
|    operators.coreos.com                 |        OperatorGroup      | :heavy_check_mark: `openShiftClient.operatorHub().operatorGroups()`
|    operators.coreos.com                 |        Operator      |  :heavy_check_mark: #3207 `openShiftClient.operatorHub().operators()`
|    operators.coreos.com                 |        Subscription      | :heavy_check_mark: `openShiftClient.operatorHub().subscriptions()`
|    packages.operators.coreos.com        |        PackageManifest      | :heavy_check_mark: #3207 `openShiftClient.operatorHub().packageManifests()`
|    project.openshift.io                 |        ProjectRequest      | :heavy_check_mark: `openShiftClient.projectrequests()`
|    project.openshift.io                 |        Project      | :heavy_check_mark: `openShiftClient.projects()`
|    quota.openshift.io                   |        AppliedClusterResourceQuota      | :heavy_check_mark: `openShiftClient.quotas().appliedClusterResourceQuotas()`
|    quota.openshift.io                   |        ClusterResourceQuota      | :heavy_check_mark: `openShiftClient.quotas().clusterResourceQuotas()`
|    route.openshift.io                   |        Route      | :heavy_check_mark: `openShiftClient.routes()`
|    samples.operator.openshift.io        |        Config      | :x: 
|    security.internal.openshift.io       |        RangeAllocation      | :x: 
|    security.openshift.io                |        PodSecurityPolicyReview      | :heavy_check_mark: #3209 `openShiftClient.podSecurityPolicyReviews()`
|    security.openshift.io                |        PodSecurityPolicySelfSubjectReview      | :heavy_check_mark: #3209 `openShiftClient.podSecurityPolicySelfSubjectReviews()`
|    security.openshift.io                |        PodSecurityPolicySubjectReview      | :heavy_check_mark: #3209 `openShiftClient.podSecurityPolicySubjectReviews()`
|    security.openshift.io                |        RangeAllocation      |  :heavy_check_mark: `openShiftClient.rangeAllocations()`
|    security.openshift.io                |        SecurityContextConstraints      | :heavy_check_mark: `openShiftClient.securityContextConstraints()`
|    template.openshift.io                |        BrokerTemplateInstance      | :heavy_check_mark: #3150  openShiftClient.brokerTemplateInstances()
|    template.openshift.io                |        Template      | :heavy_check_mark: `openShiftClient.templates();`
|    template.openshift.io                |        TemplateInstance      | :heavy_check_mark: #3150 `openShiftClient.templateInstances()`
|    tuned.openshift.io                   |        Profile      | :heavy_check_mark: #3201 `openShiftClient.tuned().profiles()`
|    tuned.openshift.io                   |        Tuned      | ::heavy_check_mark: #3201 `openShiftClient.tuned().tuneds().`
|    user.openshift.io                    |        Group      | :heavy_check_mark: `openShiftClient.groups()`
|    user.openshift.io                    |        Identity      | :heavy_check_mark: #3222 `openShiftClient.identities()`
|    user.openshift.io                    |        UserIdentityMapping      | :heavy_check_mark: #3150 `openShiftClient.userIdentityMappings()`
|    user.openshift.io                    |        User      | :heavy_check_mark: `openShiftClient.users()`
|    whereabouts.cni.cncf.io              |        IPPool      |  :heavy_check_mark: #3222 `openShiftClient.whereabouts().ippools()`
|    whereabouts.cni.cncf.io              |        OverlappingRangeIPReservation      | :heavy_check_mark: #3222 `openShiftClient.whereabouts().overlappingRangeIpReservations()`

**Comment by manusa** [comment]
OpenShift Homologous of #2912

**Comment by rohanKanojia** [comment]
Regarding the resources which are still not supported:

- `config.openshift.io/v1`: These couldn't be added since I didn't want to do a major breaking changes in openshift-model. I've created this issue to address this https://github.com/fabric8io/kubernetes-client/issues/3227
  - Build
  - Image
  - Project
 
- `metal3.io` `Provisioning`: I couldn't find this struct in [baremetal operator](https://github.com/metal3-io/baremetal-operator
- `samples.operator.openshift.io Config` + `security.internal.openshift.io RangeAllocation`: I haven't really looked into these but as  per our discussion in standup, these resources look like they are used in samples or used internally. So I'm not sure it's worth investing time in adding support for these unless someone explicitly asks.

**Comment by manusa** [comment]
I think this issue can be closed now.
