### ISSUE TITLE
waitUntilReady for specific Pods

### ISSUE THREAD

**Issue by sleepdan** [fabric8io/kubernetes-client#2957]
Hi! 
As stated in this manual ""https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#pods"", in order to wait for the status of a particular Pod to become Ready, I can do this 
`Pod pod = client.pods().inNamespace("default").withName("nginx").waitUntilReady(5, TimeUnit.MINUTES);`
    But what to do when I run several replics of same Pods and names are assigned such as "My-Pod-0, My-Pod-1, My-Pod-2" and so on. And I need to wait until their status becomes Ready, for example, using wildcards with regex in the name - `client.pods().inNamespace("default").withName("My-Pod-*").waitUntilReady(5, TimeUnit.MINUTES);` 
    How can i do this? If this is not possible, then how best to implement the expectation of several identical Pods of a certain status for all?
    Thank you!

**Comment by rohanKanojia** [comment]
Hello, we have a `client.resourceList()` DSL entrypoint which accepts a list of resources. You can have all these pods share some common label, get a list of existing pods with label and waitUntilReady for that specified list. Apart fromfetching list via labels, we're doing something similar in test ResourceList test [here](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceListTest.java#L216)

**Comment by sleepdan** [comment]
Thank you very much!
