### ISSUE TITLE
Add Group and Version annotations to generated classes

### ISSUE THREAD

**Issue by metacosm** [fabric8io/kubernetes-client#2972]

**Comment by shawkins** [comment]
@metacosm can this be closed based upon the changes for #3327

**Comment by metacosm** [comment]
Possibly… :)
The linked PR doesn't really affect the generated classes from the go model, though, iirc. This issue is about making sure that all generated classes have the `Group` and `Version` annotations properly set, so that we could also remove a bunch of code from the generated classes like all the stuff that deals with `kind`, `apiVersion`, etc. in a second/further step.

**Comment by manusa** [comment]
Related to #3589
