### ISSUE TITLE
Multiple shared informer with Kubernetes Client on OpenShift does not received events in some cases

### ISSUE THREAD

**Issue by akram** [fabric8io/kubernetes-client#2982]
Using the following example:
https://github.com/akram/kubernetes-client/blob/kubernetes-client-with-openshift-and-imagestream/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/MultipleSharedInformerExample.java

I am using a KubernetesClient with an OpenShift server.
I am creating 4 types of Informers:
```
Pod
Secret
ConfigMap
ImageStream
```

If I intialize an ImageStream informer, I do not received any event event those related to Secrets, Pods or ConfigMap. KO
If I remove the initialization of ImageStream, I receive correctly events for the first 3 (Pod, ConfigMap and Secrets). OK
If I change the client to DefaultOpenShiftClient client I receive events for the 4 types: OK

**Comment by rohanKanojia** [comment]
Hello, I was able to reproduce the issue. When I run your sample, I was able to see that I was not getting events for some specific namespaces. Every time I used to run your sample, it was a random namespace not getting picked up by informers. I ran your code on Kubernetes also(just replaced `ImageStream` with `RoleBinding`) and I noticed the same result. I wrote an equivalent `MultipleWatcherExample` and I saw the same result.

However, I noticed that every time I run it. The number of namespaces being watched(for which I was receiving events) was no more than 64. You're watching 20 namespaces and for each namespace, you're watching 4 resources, so I should be getting 80 active watchers.

I then noticed that we have a default limit of maximum concurrent requests:
https://github.com/fabric8io/kubernetes-client/blob/33db23d001c4ffce57c9c066df7bb68287a919fc/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L135

I wish I had noticed this earlier, I configured client to override maximum concurrent requests like this:
```java
        Config config =  new ConfigBuilder().withMaxConcurrentRequests(200).build();
        try (KubernetesClient client = new DefaultKubernetesClient(config)) {
            SharedInformerFactory sharedInformerFactory = client.informers();
            // ... 
        }
```
With this I was able to see watch events for all 80 namespaces :heavy_check_mark: on both Kubernetes and OpenShift.

**Comment by yanjia92** [comment]
> Hello, I was able to reproduce the issue. When I run your sample, I was able to see that I was not getting events for some specific namespaces. Every time I used to run your sample, it was a random namespace not getting picked up by informers. I ran your code on Kubernetes also(just replaced `ImageStream` with `RoleBinding`) and I noticed the same result. I wrote an equivalent [`MultipleWatcherExample`](https://github.com/rohanKanojia/kubernetes-client/blob/investigation/issue2982/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/MultipleWatcherExample.java) and I saw the same result.
> 
> However, I noticed that every time I run it. The number of namespaces being watched(for which I was receiving events) was no more than 64. You're watching 20 namespaces and for each namespace, you're watching 4 resources, so I should be getting 80 active watchers.
> 
> I then noticed that we have a default limit of maximum concurrent requests:
> https://github.com/fabric8io/kubernetes-client/blob/33db23d001c4ffce57c9c066df7bb68287a919fc/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L135
> 
> I wish I had noticed this earlier, I configured client to override maximum concurrent requests like this:
> 
> ```java
>         Config config =  new ConfigBuilder().withMaxConcurrentRequests(200).build();
>         try (KubernetesClient client = new DefaultKubernetesClient(config)) {
>             SharedInformerFactory sharedInformerFactory = client.informers();
>             // ... 
>         }
> ```
> 
> With this I was able to see watch events for all 80 namespaces ✔️ on both Kubernetes and OpenShift. You can see my code [here](https://github.com/rohanKanojia/kubernetes-client/blob/investigation/issue2982/kubernetes-examples/src/main/java/io/fabric8/openshift/examples/MultipleSharedInformerExample.java).

But what does the max concurrent request parameter to do with the missing event?

**Comment by rohanKanojia** [comment]
@yanjia92 : When I was testing this, I wasn't getting any event for some selected namespaces. Every informer opens up a watch connection of its own. In above code, we were using 80 informers to monitor 80 namespaces, which opens up 80 watchers(concurrent requests). Since the default limit is 64, I noticed there were 16 namespaces always which were not getting picked.

After increasing it to 200, I was able to see events getting received for all namespaces.

**Comment by akram** [comment]
@rohanKanojia what do we suggest for this then?
it seems that it is a configuration issue: We need to make users aware by documentation that the maximum number of resources that can be "Watched" using informers is limited by the maximum number of underlying conccurent requests of the client. So, it should be exposed in docs and maybe there should be a warning somewhere telling the user that the maximum number of client requests has been reached?

wdyt ?

**Comment by rohanKanojia** [comment]
Sounds good. We do have mention of this property in client configuration section[0] but I'm not sure if it's clear enough. Maybe we can add an FAQ about it..

Adding a warn/debug level message when number of concurrent connections approach maximum value also is very good idea.

[0] https://github.com/fabric8io/kubernetes-client#configuring-the-client
