### ISSUE TITLE
commons-codec issue

### ISSUE THREAD

**Issue by JacobCZ** [fabric8io/kubernetes-client#2998]
**Kubernetes client version:** 5.3.0
**Commons version:** 1.15

When trying to copy a file to a pod in a Spring Boot application...

```java
client.pods().inNamespace("some-namespace")
          .withName("some-pod")
          .file(someFile)
          .upload("/root/helloworld.txt");
```

I get the following error:

```io.fabric8.kubernetes.client.KubernetesClientException: Base64InputStream class is provided by commons-codec, TarArchiveOutputStream is provided by commons-compress, an optional dependency. To use this functionality you must explicitly add this dependency to the classpath.```

commons-codec is in my pom like so:

```xml
<dependency>
       <groupId>commons-codec</groupId>
       <artifactId>commons-codec</artifactId>
       <version>1.15</version>
</dependency>
```

I have checked and commons-codec is contained in the final jar.

**Comment by rohanKanojia** [comment]
I think you would need to add common-compress to your pom as well:
```
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-compress</artifactId>
			<version>${commons-compress.version}</version>
		</dependency>
```

**Comment by manusa** [comment]
I think the error message was fixed in a PR. Wasn't it?

**Comment by manusa** [comment]
https://github.com/fabric8io/kubernetes-client/pull/2967
