### ISSUE TITLE
IndexInformer cant restart after call function stop

### ISSUE THREAD

**Issue by FqqCS** [fabric8io/kubernetes-client#3013]
@Override
  public void run() {
    if (started) {
      return;
    }

    started = true;

    this.processor.run();
    controllerThread.start();
  }

  @Override
  public void stop() {
    if (!started) {
      return;
    }

    stopped = true;
    controller.stop();
    controllerThread.interrupt();

    processor.stop();
  }

After call function stop；var "started" is still true;  so when call run() again, this just return after check "started" is true.

is this correct? or is a bug?

**Comment by akram** [comment]
To my understanding, the informer is not intended to be restarted. The way I use it is: If I need to restart, I create a new one.

If you need more accurate answer, maybe wait for a maintainer to pass here.

**Comment by FqqCS** [comment]
@akram  thks 

But, when I create a new one,  memory leak happens; 
In io.fabric8.kubernetes.client.informers.cache.Controller
resync executor will not shutdown after informer stopped. and ResyncRunnable obj still in executor's queue.  this task has reference to the quque with all cache of this informer;  so mem leak happens

 ResyncRunnable resyncRunnable = new ResyncRunnable(queue, resyncFunc);
      resyncFuture = resyncExecutor.scheduleAtFixedRate(resyncRunnable, fullResyncPeriod, fullResyncPeriod, TimeUnit.MILLISECONDS);

**Comment by akram** [comment]
I think I have seen something similar yesterday and I posted  PR https://github.com/fabric8io/kubernetes-client/pull/3017  to ensure that `resyncFuture` is closed and that `resyncRunnable` is shutdown.
 
Maybe you can try to pull that branch or that commit and rebuild `kubernetes-client/kubernetes-client` to see if it fixes your issue?

**Comment by FqqCS** [comment]
it works. thx.

**Comment by rohanKanojia** [comment]
@FqqCS : Please provide a comment/review on the PR also

**Comment by FqqCS** [comment]
@akram  another case in resync
In class io.fabric8.kubernetes.client.informers.cache.Reflector
      
`
      reListAndSync();
      resyncExecutor.scheduleWithFixedDelay(this::reListAndSync, 0L, resyncPeriodMillis, TimeUnit.MILLISECONDS);
`

when it throw an exception in reListAndSync (e.g list from kubenetes may time out or some io exception ) , schedule task will stopped. then relistandsync will never exec again.

for scheduleWithFixedDelay, If any execution of the task encounters an exception, subsequent executions are suppressed.

**Comment by akram** [comment]
@FqqCS that seems to be also a good catch.

@rohanKanojia and @shawkins wdyt ? 
The `reListAndSync()` may throw  `KubernetesClientException`  which are `RuntimeException`  . So, the `reListAndSync` method may fail silently while it is run by `resyncExecutor`, and `resync` will not happen anymore probably without the user being notified.

**Comment by shawkins** [comment]
@akram @FqqCS In #3050 based upon discussion on another issue, the initial comment https://github.com/fabric8io/kubernetes-client/issues/3013#issuecomment-823208910 is correct - stop is a terminal state.

 > The reListAndSync() may throw KubernetesClientException which are RuntimeException . So, the reListAndSync method may fail silently while it is run by resyncExecutor, and resync will not happen anymore probably without the user being notified.

That has been addressed by #3018 - if the reListAndSync fails during the relist, then the general reconnect framework for watchers will keep reattempting the watch.

I'd like to take this further with https://github.com/shawkins/kubernetes-client/pull/1 which will reattempt even if the call to re-establish the watch fails and removes all unnecessary close handling.

**Comment by FqqCS** [comment]
@shawkins 
there maybe another issue in shawkins#1 ;
 if there are other type of errors, like IOException,  the reListAndSync method will not exec. and when call restartWatcher method with a big version gap for "lastSyncResourceVersion";  this may cause some failures. 

 @Override
  public void onClose(KubernetesClientException exception) {
    log.error("Watch closing");
    Optional.ofNullable(exception)
      .map(e -> {
        log.debug("Exception received during watch", e);
        return exception;
      })
      .map(KubernetesClientException::getStatus)
      .map(Status::getCode)
      .filter(c -> c.equals(HttpURLConnection.HTTP_GONE))
      .ifPresent(c -> onHttpGone.run());
    onClose.run();
  }

**Comment by shawkins** [comment]
> if there are other type of errors, like IOException, the reListAndSync method will not exec. and when call restartWatcher method with a big version gap for "lastSyncResourceVersion"; this may cause some failures.

Let me first clarify with how this is supposed to work after the change to allow the Watch framework auto-reconnect and #3055:

1. If the Informer is stopped manually, that will cause the Reflector to have isActive=false and stop any active Watch, no Watch can then be started after that point.
2. If the Watch stops abnormally, it will call the exceptional onClose method.  
2.a. If it's an http gone it will attempt to relist and reestablish the watch at the new revision.
2.a.a If this succeeds, everything is good
2.a.b If this fails, then the Watch retry framework will attempt to restart the Watch at it's last known resource - that should be out of date, causing us to repeat 2.a.
2.b. Any other exception will take no action in the Reflector - as it will be something that the Watch framework can handle and it will continue to retry.

The only remaining place that appears to call Watch (or the manager) close when not expected is https://github.com/fabric8io/kubernetes-client/blob/74cc63df9b6333d083ee24a6ff3455eaad0a6da8/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatcherWebSocketListener.java#L178 - however that shouldn't ever be hit.  The creation of the websocket is effectively async.

When you say cause some failures, are you saying you have seen issues with 2.a.b - that reattempting the Watch at an older point only to let the on http gone logic run again isn't working?

**Comment by FqqCS** [comment]
@shawkins 
tks for your reply.
my point is that when restart the Watch at it's last known resource in case 2.a.b,  this may success, and recieve too many events from kube(all change events after this resource version),too many unnecessary events are not what we expected.  maybe we restart watcher with resource version the watcher latest reciveved  is better.

**Comment by shawkins** [comment]
> maybe we restart watcher with resource version the watcher latest reciveved is better.

It is restarting at the last known version.  The Watch framework is tracking that: https://github.com/fabric8io/kubernetes-client/blob/74cc63df9b6333d083ee24a6ff3455eaad0a6da8/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java#L81

**Comment by manusa** [comment]
Is this issue still applicable?

**Comment by shawkins** [comment]
@manusa I don't believe so, there is now an expectation that stop is terminal.

**Comment by rohanKanojia** [comment]
Shall we close this one then?

**Comment by manusa** [comment]
> @manusa I don't believe so, there is now an expectation that stop is terminal.

Yes, I remember that (active/running/closed :wink:).  

> is this correct? or is a bug?

From the issue description. I'm not sure if we should document this in a better way. Or just consider the issue closed.

**Comment by shawkins** [comment]
I've updated the javadocs with #3167
