### ISSUE TITLE
DefaultController#processLoop interrupt should not display stackTrace

### ISSUE THREAD

**Issue by akram** [fabric8io/kubernetes-client#3015]
When stopping an informer, the DefaultController#processLoop displays the interruption stacktrace.
This is annoying as it makes think that this is an unexpected behaviour.

It should be replaced by:
```
log.warn("DefaultController#processLoop got interrupted {}", t.getMessage());
```

**Comment by rohanKanojia** [comment]
@akram : Thanks a lot for reporting this. I think it makes sense. Would you like to submit a PR for this?

**Comment by hibnico** [comment]
I was about to open an issue about that. I even think that for a such log, it should be at the debug level.
I you agree, I am willing to make a PR about this, searching in the entire code base about catching InterruptedExceptions and their logs, and make them in debug if not. With a quick search, I even found some `e.printStackTrace()`.

**Comment by rohanKanojia** [comment]
@hibnico : I think it's here:
https://github.com/fabric8io/kubernetes-client/blob/f8bfc5b9189af6cbbb997a2a61c036d4db8aa249/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Controller.java#L160

Would be awesome if you could send a PR :heart: .

**Comment by rohanKanojia** [comment]
Do you mean to refactor interrupted exceptions in informers package or across kuberenetes-client?

**Comment by hibnico** [comment]
I am willing to do the review the entire project, I found 41 catch. But I am just suggesting to change some InterruptedException log, not every log I found. I saw some cases where an error log or a warn was justifed.

**Comment by rohanKanojia** [comment]
oh, okay. Thanks a lot for clarification! Shall I assign this issue to you?

**Comment by hibnico** [comment]
You can, no objection.

**Comment by akram** [comment]
Hey really thank you @hibnico and @rohanKanojia , I had a branch locally with that single fix, I would have done the PR, but @hibnico seems to have done better in #3021
