### ISSUE TITLE
custom resources: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update

### ISSUE THREAD

**Issue by lburgazzoli** [fabric8io/kubernetes-client#3023]
I'm trying to use an "unstructured" client using custom resource as workaround and I have something like this:

```java
CustomResourceDefinitionContext ctx = ... ;
Map<String, Object> unstructured = ...;

return kubernetesClient
    .customResource(ctx)
    .inNamespace(namespace)
    .createOrReplace(unstructured);
```

Sometimes, I get an exception like:

```
Message: kamelets.camel.apache.org "aws-sqs-source-v1alpha1" is invalid: metadata.resourceVersion:
 Invalid value: 0x0: must be specified for an update. Received status: Status(apiVersion=v1, code=422,
 details=StatusDetails(causes=[StatusCause(field=metadata.resourceVersion, message=Invalid value: 0x0:
 must be specified for an update, reason=FieldValueInvalid, additionalProperties={})], 
group=camel.apache.org, kind=kamelets, name=aws-sqs-source-v1alpha1, retryAfterSeconds=null, uid=null, 
additionalProperties={}), kind=Status, message=kamelets.camel.apache.org "aws-sqs-source-v1alpha1" is 
invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update, 
metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, 
additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={})
```

**Comment by manusa** [comment]
Extra logic added in #2501 and contained in [CreateOrReplaceHelper](https://github.com/fabric8io/kubernetes-client/blob/db7d4eba49a5dac3ce916f782048aaecc2e40cbd/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/CreateOrReplaceHelper.java) is not applicable for Untyped/Raw custom resources.

**Comment by matthyx** [comment]
Should be add it for Raw custom resources? What's the plan to them, because as I see it, it's unusable for any replacement.

**Comment by rohanKanojia** [comment]
We don't have it in our sprint plan right now. Do you think you have some time to fix this? Just need to do what we're doing in CreateOrReplaceHelper..

**Comment by matthyx** [comment]
Thanks @rohanKanojia I will check once we merge the other PR...
