### ISSUE TITLE
sundr-codegen shaded classes

### ISSUE THREAD

**Issue by lburgazzoli** [fabric8io/kubernetes-client#3025]
I've noticed that `sudr-codegen` shades quite a lot of classes, some are re-packaged under a different package, i.e. to `io/sundr/shaded/com/github/javaparser` but others are not: i.e `org/apache/commons`, `sun/rmi`, `com/sun` and counting (~5500 classes shaded but not relocated).

In my project (an operator based on the java-operator-sdk), the `sundr-codegen` artifact is a transitive dependency of `io.fabric8:crd-generator-apt` which has provided scope so it should not be an issue at runtime, however there may be conflicts if a project depends on i.e on an apache commons lang or if a project is accidentally using one of the unshaded lib.

**Comment by iocanel** [comment]
FWIW, we are currently in the process of splitting `sundr-codegen` into individual modules, so that we can have more fine grained control over what we bring in. For example the `javaparser` and `velocity` dependencies will be completely eliminated.

**Comment by metacosm** [comment]
Is there anything we can do @iocanel?
