### ISSUE TITLE
Informer watch status

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3034]
If it's possible for the informer watch to be terminated, there needs to be a simple way to determine that.  With #3018 the informer watch should attempt to reconnect at the configuration interval.

However I'm not familiar enough with all possible scenarios that may bring the watch down and/or it may just be a good safe-guard to have this.

In our project we are working around this with a health check that looks for an informer whose last resource version has not changed in some time and that reports hasSynced false - that is taken as an indication that it's likely down and a container restart will occur.

**Comment by manusa** [comment]
Is this issue still active after the recent changes?

**Comment by shawkins** [comment]
@manusa this has been resolved.
