### ISSUE TITLE
Upgrade Mock Server TLS Version

### ISSUE THREAD

**Issue by caramelomartins** [fabric8io/kubernetes-client#3038]
Hey!

I've noticed recently that `KubernetesMockServer` is currently hardcoded with TLS v1.0:

https://github.com/fabric8io/kubernetes-client/blob/2c7cefe12d9ebf42308fce816d281bd61a2192ed/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesMockServer.java#L94

Given Oracle's recent deprecation of this in new JDK versions (https://www.oracle.com/java/technologies/javase/11-0-11-relnotes.html#JDK-8202343) would it be possible to upgrade this version to match the one that is in the `Config`, which is 1.2?

https://github.com/fabric8io/kubernetes-client/blob/74cc63df9b6333d083ee24a6ff3455eaad0a6da8/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L205

Thanks for your time and thanks for your contributions in this awesome project!

Regards,
Hugo

**Comment by rohanKanojia** [comment]
Thanks for suggesting this. I think our project is at JDK8 right now. I think we need to discuss when we would like to switch to JDK11.

**Comment by caramelomartins** [comment]
Yeah, of course. I'll open one this weekend!

**Comment by skabashnyuk** [comment]
We hit the same problem in Eclipse Che project https://github.com/eclipse/che/issues/19641 on Github CI when the latest java `11.0.11_9` was used. As a temporary workaround, we just disable these tests. At this point, we use  kubernetes-client 4.9.0. Would it be possible to backport this issue to 4.9.x or 4.x?

**Comment by skabashnyuk** [comment]
I think the time to adopt 4.13.x is similar to 5.x in Eclipse Che. So it has no sense since to backport this fix to 4.13. I'll work on 5.x and Eclipse Che here https://github.com/eclipse/che/pull/19744/files.

**Comment by AndrewGotz** [comment]
> I think the time to adapt 4.13.x is similar to 5.x in Eclipse Che. So it has no sense since to backport this fix to 4.13. I'll work on 5.x and Eclipse Che here https://github.com/eclipse/che/pull/19744/files.

Hey @skabashnyuk. I would appreciate the backport to 4.13.x if its not to difficult? Are you saying it won't be backpatched to 4.13.x? Currently we are running into the same issue with our tests and upgrading to 4.13.x would be better for us instead of trying to jump all the way to 5.x. We are currently on 4.x libraries.

**Comment by skabashnyuk** [comment]
>Hey @skabashnyuk. I would appreciate the backport to 4.13.x if its not to difficult? Are you saying it won't be backpatched to 4.13.x? Currently we are running into the same issue with our tests and upgrading to 4.13.x would be better for us instead of trying to jump all the way to 5.x. We are currently on 4.x libraries.

I was talking about the Eclipse Che code. We managed to upgrade 4.9 -> 5.x

**Comment by AndrewGotz** [comment]
I just noticed this has been marked as https://github.com/fabric8io/kubernetes-client/milestone/28 no longer necessary for the 4.13.4 milestone.

I would say if possible this would be necessary for us at least @manusa @rohanKanojia can we confirm this is still going or not with 4.13.4?

**Comment by manusa** [comment]
Since no one else requested the back-port we just aborted the milestone.

If you're still interested we can backport this one. However, will need to wait until the 5.4.0 release (to be cut hopefully before the end of this week).

**Comment by AndrewGotz** [comment]
> Since no one else requested the back-port we just aborted the milestone.
> 
> If you're still interested we can backport this one. However, will need to wait until the 5.4.0 release (to be cut hopefully before the end of this week).

Hey I do believe we would want this backpatched if possible @manusa. I'm willing to wait whenever.

**Comment by AndrewGotz** [comment]
Bumping this. @manusa @rohanKanojia Could we potentially get this backpatched if its not to much work? We temporarily downgraded java version to run these tests for one of our projects which is not ideal. Updating to the latest 5.x would also be a big undertaking at this time for our team.

**Comment by rohanKanojia** [comment]
@AndrewGotz : In 5.x major changes are only related to removal of Doneable and CustomResources. If you're not using these then migrating to 5.x might not be that involved effort.

**Comment by caramelomartins** [comment]
I believe I have submitted a PR a few months ago to resolve this. Can we close this issue?
