### ISSUE TITLE
How to customize metrics in pod  and get the metrics information

### ISSUE THREAD

**Issue by yangjinlogic** [fabric8io/kubernetes-client#3042]
How to customize metrics in pod  and get the metrics information

**Comment by rohanKanojia** [comment]
You can get metrics using our `client.top()` DSL[0]. Regarding changing metrics, You can try editing Pod's `.spec.containers[].resources` field

[0] https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#fetching-metrics
