### ISSUE TITLE
PR with volcano CRDs

### ISSUE THREAD

**Issue by dipanjank** [fabric8io/kubernetes-client#3043]
Hi fabric8io developers,

Following up on https://github.com/fabric8io/kubernetes-client/issues/2920, we managed to successfully generate Volcano related CRDs using this project. We'd like to add a new maven module (/kubernetes-client/kubernetes-model-generator/kubernetes-model-volcano) with the generate.go, kube-schema.json etc. in a PR. This will be really helpful in our end goal to open source our Volcano based cluster manager for kubernetes. Is this something you'd be happy to accept? 

Best,
Dipanjan

**Comment by rohanKanojia** [comment]
Do you mean you want to contribute a Volcano CRD [Extension](https://github.com/fabric8io/kubernetes-client/tree/master/extensions) ?

**Comment by dipanjank** [comment]
I'm happy to use whichever project structure works best. At the moment I'm using a sub-module of kubernetes-model-generator because that was the easiest way to get it working. Basically, I have a generate.go file that generates kube-schema.json for the Volcano golang struct definitions and a pom.xml that takes the json and produces java sources. It is somewhat similar to kubernetes-model-batch.
