### ISSUE TITLE
NPE when getting version when there is no build date

### ISSUE THREAD

**Issue by yevgenykuz** [fabric8io/kubernetes-client#3047]
The `fetchVersion()` method will fail with NPE when the API server doesn't return the build date.https://github.com/fabric8io/kubernetes-client/blob/74cc63df9b6333d083ee24a6ff3455eaad0a6da8/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ClusterOperationsImpl.java#L44

It happens because `SimpleDateFormat` can't parse null values.

A possible fix can be null checking before calling `buildWithDate`:
https://github.com/fabric8io/kubernetes-client/blob/74cc63df9b6333d083ee24a6ff3455eaad0a6da8/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ClusterOperationsImpl.java#L66

Or within the `buildWithDate` function itself if a default value should be provided:
https://github.com/fabric8io/kubernetes-client/blob/74cc63df9b6333d083ee24a6ff3455eaad0a6da8/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/VersionInfo.java#L104

This can be reproduced if k8s is mocked with the provided server in CRUD mode - https://github.com/fabric8io/kubernetes-client#crud-mode

**Comment by rohanKanojia** [comment]
@yevgenykuz : Thanks for reporting this! Would appreciate it if you could create a PR. What default value do you think we'll provide?

**Comment by yevgenykuz** [comment]
NP Ill open a PR later this week.
Not sure about the default value, i'd write "N/A" but it requires changing the type to String. I prefer to change as little as possible since i didn't go over the code to see what else may be affected.
