### ISSUE TITLE
Enforce informer lifecycle

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3050]
It was discussed in #3048 as to what are the expectations for calling run after stop.  The expectation is that stop should be a terminal state.

Related to this, SharedIndexInformer.addIndex is only allowed when not running, but SharedIndexInformer.getIndexer().addIndex will work always.

**Comment by akram** [comment]
Based on this assumption, would PR https://github.com/fabric8io/kubernetes-client/pull/3029 makes sense?

**Comment by shawkins** [comment]
I believe so - with the two changes from the comment.  I'll make them as code comments to further clarify.
