### ISSUE TITLE
Patch calls should use the base resource version to create a diff

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3067]
On calls to edit or patch that pass in a resource the underlying patch logic is fetching the latest resource to generate the diff - this opens up the possibility that you are creating a diff against a different starting point than what you used (although that's much more unlikely with edit).  see https://github.com/fabric8io/kubernetes-client/blob/b54d41f854d4a34ebf82cef8310f4226f702f834/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java#L114

The logic should instead check if the resource specifies a resource version and use that as the base version for the diff.  Only if there is no resource version specified should latest be assumed - or alternatively the client could require a resource version.

**Comment by manusa** [comment]
Relates to #3078

**Comment by shawkins** [comment]
Based upon discussion on the pr, it does not seem desirable to directly expose a patch(base, item) method.  Instead a patch(patchcontext, item) will be exposed - for consistency with the new patch method and flexibility.

**Comment by shawkins** [comment]
This was resolved by #3070
