### ISSUE TITLE
Simplify/consolidate thread utilization by informers

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3072]
With the current implementation each informer directly consumes a thread for:

1. Controller - resync executor thread pool
2. DefaultSharedIndexInformer - controller thread
3. SharedProcessor - executor, which is 1 thread per listener.

This becomes an issue when running lots of informers.

We should be able to consolidate or remove several of these.   #3061 for example allows the controller thread to complete.

Additionally each watch has a websocket reader thread and a scheduler thread.

**Comment by manusa** [comment]
Relates to: #2010

**Comment by manusa** [comment]
Should be fixed addressed in #3108
