### ISSUE TITLE
CertificateException due to PEM being decoded in CertUtils

### ISSUE THREAD

**Issue by sonicloong** [fabric8io/kubernetes-client#3083]
It looks like `CertUtils#getInputStreamFromDataOrFile` determines whether the certificate data is base64 encoded or not by checking if the data can be base64 decoded. However since okio considers the minus sign to be a valid character
([reference](https://github.com/square/okio/blob/465c07e7e98b091d39600a6720d8bf3c1121da34/okio/src/commonMain/kotlin/okio/-Base64.kt#L65)), even PEM data can be base64 decoded.

Observed the issue at [OpenIDConnectionUtils#getOIDCProviderTokenEndpointAndRefreshToken](https://github.com/fabric8io/kubernetes-client/blob/e8109a80f786a4d2a68b08be2f9efc94ffff5019/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtils.java#L356), which calls [getSSLContext](https://github.com/fabric8io/kubernetes-client/blob/e8109a80f786a4d2a68b08be2f9efc94ffff5019/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtils.java#L281), where the certificate data is [decoded to PEM](https://github.com/fabric8io/kubernetes-client/blob/e8109a80f786a4d2a68b08be2f9efc94ffff5019/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/OpenIDConnectionUtils.java#L286) already; the PEM is then passed to [SSLUtils#trustManagers](https://github.com/fabric8io/kubernetes-client/blob/e8109a80f786a4d2a68b08be2f9efc94ffff5019/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/SSLUtils.java#L97), then [CertUtils#createTrustStore](https://github.com/fabric8io/kubernetes-client/blob/e8109a80f786a4d2a68b08be2f9efc94ffff5019/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/CertUtils.java#L80), and eventually [CertUtils#getInputStreamFromDataOrFile](https://github.com/fabric8io/kubernetes-client/blob/e8109a80f786a4d2a68b08be2f9efc94ffff5019/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/CertUtils.java#L61). `ByteString.decodeBase64(data)` returns non-null value, therefore the PEM is decoded again.

Also observed the same issue when passing PEM data to `ConfigBuilder#withCaCertData`

## Reproduce
Use one of the DigiCert root CAs as an example
```
-----BEGIN CERTIFICATE-----
MIIDxTCCAq2gAwIBAgIQAqxcJmoLQJuPC3nyrkYldzANBgkqhkiG9w0BAQUFADBs
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSswKQYDVQQDEyJEaWdpQ2VydCBIaWdoIEFzc3VyYW5j
ZSBFViBSb290IENBMB4XDTA2MTExMDAwMDAwMFoXDTMxMTExMDAwMDAwMFowbDEL
MAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3
LmRpZ2ljZXJ0LmNvbTErMCkGA1UEAxMiRGlnaUNlcnQgSGlnaCBBc3N1cmFuY2Ug
RVYgUm9vdCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMbM5XPm
+9S75S0tMqbf5YE/yc0lSbZxKsPVlDRnogocsF9ppkCxxLeyj9CYpKlBWTrT3JTW
PNt0OKRKzE0lgvdKpVMSOO7zSW1xkX5jtqumX8OkhPhPYlG++MXs2ziS4wblCJEM
xChBVfvLWokVfnHoNb9Ncgk9vjo4UFt3MRuNs8ckRZqnrG0AFFoEt7oT61EKmEFB
Ik5lYYeBQVCmeVyJ3hlKV9Uu5l0cUyx+mM0aBhakaHPQNAQTXKFx01p8VdteZOE3
hzBWBOURtCmAEvF5OYiiAhF8J2a3iLd48soKqDirCmTCv2ZdlYTBoSUeh10aUAsg
EsxBu24LUTi4S8sCAwEAAaNjMGEwDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB/wQF
MAMBAf8wHQYDVR0OBBYEFLE+w2kD+L9HAdSYJhoIAu9jZCvDMB8GA1UdIwQYMBaA
FLE+w2kD+L9HAdSYJhoIAu9jZCvDMA0GCSqGSIb3DQEBBQUAA4IBAQAcGgaX3Nec
nzyIZgYIVyHbIUf4KmeqvxgydkAQV8GK83rZEWWONfqe/EW1ntlMMUu4kehDLI6z
eM7b41N5cdblIZQB2lWHmiRk9opmzN6cN82oNLFpmyPInngiK3BD41VHMWEZ71jF
hS9OMPagMRYjyOfiZRYzy78aG6A9+MpeizGLYAiJLQwGXFK3xPkKmNEVX58Svnw2
Yzi9RKR/5CYrCsSXaQ3pjOLAEFe4yHYSkVXySGnYvCoCWw9E1CAx2/S6cCZdkGCe
vEsXCS+0yx5DaMkHJ8HSXPfqIbloEpw8nL+e/IBcm2PN7EeqJSdnoDfzAIJ9VNep
+OkuE6N36B9K
-----END CERTIFICATE-----
```
Pass it to `ByteString#decodeBase64`, get non-null result.

**Comment by rohanKanojia** [comment]
@sonicloong : Thanks a lot for reporting this issue. I tested with your PEM string and I can reproduce this issue. I think if [`java.util.Base64`](https://docs.oracle.com/javase/8/docs/api/java/util/Base64.Decoder.html) instead of `okio.ByteString`, it will solve our issue:
```java
    byte[] bytes;
    try {
      bytes = Base64.getDecoder().decode(data);
    } catch (IllegalArgumentException illegalArgumentException) {
      bytes = data.getBytes();
    }

    return new ByteArrayInputStream(bytes);
```
I will create a PR to replace `okio.ByteString` to `java.util.Base64` here.
