### ISSUE TITLE
Replace JUnit4 Assertions(`org.junit.Assert.*`) with Junit5 Jupiter Assertions(`org.junit.jupiter.api.Assertions`)

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#3086]
Call to assertions from 'Assert' should be replaced with call to method from 'org.junit.jupiter.api.Assertions' 
Though still working, migration to org.junit.jupiter.api.Assertions/org.junit.jupiter.api.Assumptions could avoid dependency on old JUnit version.

You can find all occurrences of junit4 assertions being used by this simple grep:
```
git grep -ic "static org.junit.Assert."
```
Replacing them should be quite straightforward. In most cases, it might be as easy as changing the assertion package to Junit5 Jupiter.

**Comment by Umang228** [comment]
Could you plz specify the file which I have to change...

**Comment by rohanKanojia** [comment]
If you run `git grep -in "static org.junit.Assert."` . It would list all files with occurrences of junit4 assertions

**Comment by sumitgsh** [comment]
@rohanKanojia  is it done!! If not done would love to give a try :)

**Comment by sourabhkumar45** [comment]
ready to work on this issue, Assign if possible.

**Comment by ps-19** [comment]
ready to work on this issue, Assign if possible.
