### ISSUE TITLE
Refine the Informer Store interface

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3091]
There are several options to improve the Store interface.

The most aggressive, which would deviate from the go client, would be to remove all of the mutative / internal methods to a separate interface - add, update, delete, replace, resync, isPopulated, hasSynced would be part of a  - which would then no longer be directly exposed via the Indexer interface.  The rationale is that these either have no-op behavior or should not be called directly.

A lesser refactoring would simply align the interface with the go client, such that newer methods added in fabric8 are moved to a separate interface.

Once #3061 is committed all of the cache methods can be type-safe - no need to reference the object type.

#3090 proposes removing the isPopulated method altogether.

**Comment by shawkins** [comment]
@rohanKanojia  a full proposal for refactoring after #3108 looks like https://github.com/shawkins/kubernetes-client/pull/3

**Comment by rohanKanojia** [comment]
@shawkins : Thanks, let me review it later today :+1:

**Comment by shawkins** [comment]
Closed via #3167
