### ISSUE TITLE
Mark crd spec as required

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3096]
When extending CustomResource I would like to mark the spec as required.  The NotNull annotation however only seems to work on fields, and not methods, so this does not seem possible.

cc @metacosm

**Comment by metacosm** [comment]
Damn! 😓

**Comment by manusa** [comment]
Hi @metacosm, @shawkins,

Was this already fixed? is it still applicable?

**Comment by metacosm** [comment]
No, this hasn't been fixed but not sure how important it is

**Comment by shawkins** [comment]
> No, this hasn't been fixed but not sure how important it is

It's just a nice to have for completeness.

**Comment by metacosm** [comment]
We could put the `@NotNull` annotation on the `spec` field of `CustomResource`, though that might be a little heavy-handed…

**Comment by manusa** [comment]
Regarding version [7.0](https://github.com/fabric8io/kubernetes-client/issues/5778), one of the ideas is to completely remove CustomResource class in favor of specific interfaces for HasSpec, HasStatus, and so on ([#2829 comment](https://github.com/fabric8io/kubernetes-client/issues/2829#issuecomment-1197676790)).

I'm not sure how this issue might play in conjunction with these interfaces.

Thoughts?

**Comment by metacosm** [comment]
I guess having something implements the `HasSpec` interface would need to trigger the `required` clause on the spec. Same thing for `HasStatus`.
