### ISSUE TITLE
Watcher Restart Failed when kube restart and return 429 

### ISSUE THREAD

**Issue by FqqCS** [fabric8io/kubernetes-client#3104]
we mock an accident in test env, when we stop etcd, kube return 410 first and then return 429 for later request.
and after that the watcher never started again. 
i think maybe this is an issue for method "onClose"; when it throw an exception in method "onHttpGone.run()", method  this.onClose.run() will never exec. in our case,  method reListAndSync->getList() throw an exception because etcd is down, kube return 429 .

    public void onClose(WatcherException exception) {
        log.warn("Watch closing with exception", exception);
        Optional.ofNullable(exception).filter(WatcherException::isHttpGone).ifPresent((c) -> {
            this.onHttpGone.run();
        });
        this.onClose.run();
    }

**Comment by shawkins** [comment]
Can you clarify which version this is against?  With the latest changes in 5.4 the expectation is that the automatic retry will continue to happen until onClose completes successfully.

**Comment by FqqCS** [comment]
last time the version was <version>4.11.1</version>;
now, i upgrade to <version>5.3.1</version> and i will try test again later.
