### ISSUE TITLE
how to copy a file into pod

### ISSUE THREAD

**Issue by cc19931002** [fabric8io/kubernetes-client#3116]
As described in the title，is there any api can be helpful?

**Comment by stupid-yu** [comment]
as CHEATSHEET.md show, Upload file into a Pod

**Comment by stupid-yu** [comment]
an example shown in CHEATSHEET.md
Upload file into a Pod
```
client.pods().inNamespace(currentNamespace).withName(pod1.getMetadata().getName()).file("/tmp/toBeUploaded").upload(tmpFile.toPath());
```
 hope it will be helpful

**Comment by maxwellknoxx** [comment]
Hi, 

I would like to know if the snippet above also works for upload a file to a Persistent Volume.

Thanks

**Comment by stupid-yu** [comment]
may be it works for pod mount that volume，cause the api works for pod

**Comment by maxwellknoxx** [comment]
Hi, it's me again.

I have tried to upload a .csv file to my PV but it does not upload.

this is the snippet:
`private final Path root = Paths.get("/apps/data");

    public String uploadFile(MultipartFile file) throws IOException {
        String fileName = save(file); // saves the file on /apps/data

        List<String> podList = getPodsName();

        String podName = getPodName(podList);

        try (KubernetesClient client = new DefaultKubernetesClient()) {
            Path pathFile = this.root.resolve(fileName); // gets the file saved on  /apps/data

            File fileToUpload = new File(pathFile.toAbsolutePath().toString());
            client.pods().inNamespace("dev-dic-functional")   
                  .withName(podName) 
                  .file("/mnt/data/processor/" + fileName)
                  .upload(fileToUpload.toPath());
        }

        return getFileId(fileName);
    }`
    
    I have created a PV and PVC and later on associated it to my pod running on my namespace dev-dic-functional
    
    
Would you please help me to identify my mistake?

Thanks in advance.

**Comment by stupid-yu** [comment]
cuz this upload api works for me，if directory "/mnt/data/processor/" in pod which you want to upload exists，check  your Path parameter. 
Only two parameters need attention, wish you success!
