### ISSUE TITLE
Is there any plan to support the API for openkruise？

### ISSUE THREAD

**Issue by wpliang** [fabric8io/kubernetes-client#3117]
Is there any plan to support the API for openkruise？
[https://openkruise.io/en-us/index.html](url)

**Comment by rohanKanojia** [comment]
@wpliang : Thanks for reporting. Right now it's not in our roadmap. Would it be possible for you to contribute an extension for this? You can take a look at our current [extensions/ ](https://github.com/fabric8io/kubernetes-client/tree/master/extensions)to get an idea of how they are implemented. You can also take a look at the Cert Manager Extension PR https://github.com/fabric8io/kubernetes-client/pull/2930
