### ISSUE TITLE
Does kubernetes client support QPS and Burst override? 

### ISSUE THREAD

**Issue by Jeffwan** [fabric8io/kubernetes-client#3124]
I search qps and burst in the code base and can not find anything 
https://github.com/fabric8io/kubernetes-client/search?q=qps

I doubled check config https://github.com/fabric8io/kubernetes-client/blob/1c942a086cf775e02de1211e220fce8ad99dd5b3/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L61 and I can not find configuration neither. Can someone help confirm if it's supported in this java client?

**Comment by Jeffwan** [comment]
I find following variables and seems they should be same as `qps`? I still can not find burst equivalent option?

```
KUBERNETES_MAX_CONCURRENT_REQUESTS
KUBERNETES_MAX_CONCURRENT_REQUESTS_PER_HOST
```

**Comment by Jeffwan** [comment]
KUBERNETES_MAX_CONCURRENT_REQUESTS_PER_HOST

**Comment by manusa** [comment]
Relates to #3087
