### ISSUE TITLE
deprecate updateStatus(item) operation

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3127]
Similar to updateStatus, should be a simple update(item) method available as well?

cc @rohanKanojia

**Comment by shawkins** [comment]
Or is this not needed since update(item) should be functionally equivalent to with .lockResourceVersion(item.getMetadata().getResourceVersion()).replace(item)

**Comment by rohanKanojia** [comment]
Could you please elaborate? Would this update(item) would be doing a PUT? Or it would be doing server-side apply?

**Comment by shawkins** [comment]
> Could you please elaborate? Would this update(item) would be doing a PUT? Or it would be doing server-side apply?

Just a PUT - similar to updateStatus.

**Comment by manusa** [comment]
I really can't see the difference between what we call a replace and the new proposed update method.

**Comment by shawkins** [comment]
> I really can't see the difference between what we call a replace and the new proposed update method.

.update(item) is the same as .lockResourceVersion(item.getMetadata().getResourceVersion()).replace(item)

It's more for consistency with having updateStatus.

**Comment by manusa** [comment]
IMHO this is going to create more confusion as in:

> I see there are update and replace methods, which one should I use if I want to add a new entry to my ConfigMap?

`.lockResourceVersion(item.getMetadata().getResourceVersion()).replace(item)` I also thought optimistic-locking was on by default. I'm not sure when this changed.

**Comment by shawkins** [comment]
> IMHO this is going to create more confusion as in:

I don't disagree - would you rather deprecate updateStatus?

> .lockResourceVersion(item.getMetadata().getResourceVersion()).replace(item) I also thought optimistic-locking was on by default. I'm not sure when this changed.

Not for the replace operation - it will always fetch the latest if lockResourceVersion is not called.  I have a change ready related to this issue that would use the item resourceVersion as the first attempt if it's provided and lockResourceVersion has not been called.

**Comment by manusa** [comment]
> I don't disagree - would you rather deprecate updateStatus?

Are you suggesting to deprecate in favor of the new (more resilient) `patchStatus`? If so, I think that is probably a good idea.
The client is getting really complex and we are offering many duplicate ways of achieving the same goals, anything that simplifies the API and improves UX sound like a good idea to me.

> Not for the replace operation...

So I'm probably confused with the former `edit` implementation.
I think that the generic expectation is that if my current item has a resourceVersion, an optimistic-lock should be applied, however I might be confused and this is not how it has been working up until now (@rohanKanojia ?). (Which is probably what your change does, and which sounds as the logical expectation)

**Comment by shawkins** [comment]
> Are you suggesting to deprecate in favor of the new (more resilient) patchStatus?

Before the recent changes there was just updateStatus.   Now there are also patchStatus, editStatus, and replaceStatus - all three are related to existing fabric8 non-status methods.  updateStatus is the odd man out.

> So I'm probably confused with the former edit implementation.

Edit creates a patch and generally has the expectation that the resourceVersion will be omitted in the patch.

> Which is probably what your change does, and which sounds as the logical expectation

I'll open another pr based upon the outcome here.

**Comment by shawkins** [comment]
> I'll open another pr based upon the outcome here.

I actually ended up putting the change in the existing pr, but have opened #3149 for better tracking.

**Comment by shawkins** [comment]
Closed via #3136
