### ISSUE TITLE
Add mock server support for patch status and other patch types

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3135]
There are now more patch options that the client supports, which the mock does not:

1. patch against the status subresource
2. merge, and strategic merge patch.

**Comment by manusa** [comment]
Does #3138 cover all of the above? shall we close this issue?

**Comment by shawkins** [comment]
It covers all that will be done for now.  There wasn't a quick way to add handling for merge and strategic merge.
