### ISSUE TITLE
KubernetesMockServerExtension question

### ISSUE THREAD

**Issue by wind57** [fabric8io/kubernetes-client#3145]
I am looking at `KubernetesMockServerExtension`, specifically at these two methods:

```
  @Override
  public void beforeEach(ExtensionContext context) throws Exception {
    setKubernetesClientField(context, false);
  }

  @Override
  public void beforeAll(ExtensionContext context) throws Exception {
    setKubernetesClientField(context, true);
  }
```

And now suppose that I want to refactor [this test](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-fabric8-config/src/test/java/org/springframework/cloud/kubernetes/fabric8/config/CoreTest.java) and move it to junit-5.

Because of `beforeAll` in `KubernetesMockServerExtension`, the field `private static KubernetesClient mockClient;` will be injected with a mock. So far so good - exactly what I want.

This field : 

```
	@Autowired
	private KubernetesClient client;
```

will be injected by on of the configs provided by Spring, all good again.

But because `beforeEach` exists in `KubernetesMockServerExtension` and this code in the same class:

```
} else {
            Optional<Object> optTestInstance = context.getTestInstance();
            if (optTestInstance.isPresent())
              f.set(optTestInstance.get(), client);
          }
```

that field will be overridden with a mock that you inject. As such [this line](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-fabric8-config/src/test/java/org/springframework/cloud/kubernetes/fabric8/config/CoreTest.java#L97) will fail, for obvious reasons.

imho, `EnableKubernetesMockClient` should provide an argument to override or not the non-static client, if such is present.

There is an obvious solution here, simply rename:

```
@Autowired
private DefaultKubernetesClient client; // instead of KubernetesClient
```

but I am not a big fan of doing this.

**Comment by rohanKanojia** [comment]
I think you're right. We should provide an argument to configure whether we should initialize KubernetesClient member fields in the class. Do you think you can contribute a PR to support this?

**Comment by wind57** [comment]
@rohanKanojia [sure thing](https://github.com/fabric8io/kubernetes-client/pull/3151/files)

**Comment by wind57** [comment]
90 days and that PR has not been reviewed :| is there a way for me to accelerate that? @rohanKanojia

**Comment by rohanKanojia** [comment]
@wind57 : I'm really sorry for the delayed response :pray: . I really shouldn't have asked you to create PR straight-away before reviewing [CoreTest](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-fabric8-config/src/test/java/org/springframework/cloud/kubernetes/fabric8/config/CoreTest.java). 

I had a discussion with Marc about your PR at the time after PR creation and Marc suggested that a better solution would be to split CoreTest into two different tests with their own version of mocked and autowired KubernetesClient; having annotation to disable initialization doesn't make much sense. I think we somehow missed providing feedback on the pull request.

I'm really sorry for your time :pray: . Please let me know if it's feasible for you to split CoreTest into two different test classes or maybe we can discuss here how to solve this.

**Comment by wind57** [comment]
no worries at all! literally. I will get some time next week and will get back to you - as long this moves forward, I am good. thank you for getting back to me.

**Comment by wind57** [comment]
This will still have to be looked at, in jdk-17, when the hack done inside the extension will not work anymore. I am closing this one for the time being, let's see what other people say when they hit this. I might be the wrong person here.

**Comment by rohanKanojia** [comment]
I'm not sure if the suggestion (https://github.com/fabric8io/kubernetes-client/issues/3145#issuecomment-901368065) is a band-aid. This was originally suggested by @manusa, we had a look at the test you linked in the issue and felt the test is checking more than one stuff and should be split. Of course, we don't have the full context of why it's written this way and can't be sure of its purpose.

**Comment by wind57** [comment]
I see. This is not really about that test. I was sort of objecting ( I hope in a polite manner ), the overall idea of overriding a user provided field, in general. But again, this is my limited view on a project that I am not involved in. We do have a solution, no doubt, so either way, are are good.

Of course, since I have provided that PR, my view and desired direction is obvious :) nevertheless I tahnk you for your opinion and feedback.

**Comment by rohanKanojia** [comment]
Yes, As you already see in the comments in the beginning I was in support of your approach. But after discussion, I realized maybe it's not worth it. The annotation's purpose is to initialize KubernetesClient and KubernetesMockServer. If the user doesn't want to initialize fields, he can always opt out of using the Junit5 annotation. Adding a configuration option to undo what it's doing didn't look like the right thing to do.

**Comment by wind57** [comment]
@rohanKanojia 

>  If the user doesn't want to initialize fields, he can always opt out of using the Junit5 annotation

this! A single comment from you made me get my morning coffee and realize that you are completely right. Thank you!

Thus [the PR that agrees with you](https://github.com/spring-cloud/spring-cloud-kubernetes/pull/897)

**Comment by manusa** [comment]
Hi @wind57 
Really sorry for the late (or maybe non-existent) review and comment on this issue. I discussed the issue with Rohan internally and never got back to you (the notification got buried in my mailbox) :pray: 

I think Rohan already provided all of the context and explanations, thx.

I'm glad the split test PR went forward and everything finally worked out.

**Comment by wind57** [comment]
yup! thank you for your feedback anyway!
