### ISSUE TITLE
Ordering of additional printer columns in the CRD

### ISSUE THREAD

**Issue by lburgazzoli** [fabric8io/kubernetes-client#3153]
I noticed that the order for which the `additionalPrinterColumns` in the CRD definition is created sometimes changes which leads to different output and also to necessary changes to the files (which I check in into to the repository).

Would it be possible to either set an "order" field on the annotation or keep the ordering stable across builds ?

**Comment by iocanel** [comment]
I'm 5.4 they should be sorted by name.
If this is not enough we can introduce an order field in the annotation.

**Comment by metacosm** [comment]
I think the only thing that matters here is that the order is stable across builds, which it should now. This was addressed in #3071 (and subsequent fixes). Duplicates #3040.

**Comment by lburgazzoli** [comment]
sorry I didn't notice there were an issue already

**Comment by metacosm** [comment]
No problems! I've been known to re-create tickets for issues I already created tickets for but forgot about… 😅
