### ISSUE TITLE
crd yaml generate java class

### ISSUE THREAD

**Issue by chenwenjun-github** [fabric8io/kubernetes-client#3168]
sorry, this is a issue to ask for help, not a problem.
I want to know can I use crd yaml to generate java class via use this project, I don't find documentation about this.
Can someone give me some advice, thanks.

**Comment by rohanKanojia** [comment]
We don't support generating POJOs from CRD Yaml manifests at the moment. We have this [crd-generator](https://github.com/fabric8io/kubernetes-client/tree/master/crd-generator) which does the opposite (POJOs -> CRD Yaml manifests)

**Comment by rohanKanojia** [comment]
If you have go structs for the CustomResource, you can take a look at our [go generator scripts](https://github.com/fabric8io/kubernetes-client/blob/master/extensions/chaosmesh/generator/cmd/generate/generate.go) which can help you generate POJOs
