### ISSUE TITLE
allow overriding custom http client properties

### ISSUE THREAD

**Issue by jrhizor** [fabric8io/kubernetes-client#3170]
I would like to be able to customize client-level settings for the underlying `OkHttpClient` while still using the majority of defaults in `HttpClientUtils.createHttpClient`. 

The specific use case I'm interested in is customizing the connection pool used by the client because we're running into an issue where it blocks program closure by taking 5 min to give up an idle connection. If this was modifiable we could customize this:
```
httpClientBuilder.connectionPool(new ConnectionPool(5, 30, TimeUnit.SECONDS));
```

The reason I'd like to be able to modify this is because `HttpClientUtils.createHttpClient` sets a lot of useful defaults. I don't want to have to create and maintain a duplicate of `HttpClientUtils.createHttpClient` in my code base just so I can modify this.

This can be achieved by making `HttpClientUtils.createHttpClient` `public`. Additional overrides can be supplied via the `additionalConfig` consumer.

**Comment by manusa** [comment]
Should have been fix by #3171
