### ISSUE TITLE
OpenShiftClient.getVersion returns incorrect version for non released clusters

### ISSUE THREAD

**Issue by jeffmaury** [fabric8io/kubernetes-client#3174]
When working against a non released version where the version string is something like `4.8.0-0.nightly-2021-05-26-071911` the minor and major field are returned as null.

**Comment by manusa** [comment]
Related code:
https://github.com/fabric8io/kubernetes-client/blob/c65b4547d47d075c2d403e9a475d3d3f40b274b7/openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftClusterOperationsImpl.java#L66-L75
