### ISSUE TITLE
Service watch silently stops receiving events

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3177]
I have yet to track down a root cause.

Starting a watch in a straight-forward way:
```
kubernetesClient.services().inAnyNamespace().withLabels(Map.of("some", "label")).watch(new ListOptionsBuilder()
                .withWatch(Boolean.TRUE)
                .withResourceVersion(lastResourceVersion)
                .withTimeoutSeconds(null)
                .build(), watcher);
```
There are no abnormal onClose events yet we simply stop receiving Service events after approximately 110 minutes in the latest occurrence.  We have seen this behavior in the Watches used by informers as well.

I cannot find any existing bug reference for this behavior and it does seem related to Service events - other watches continue to function normally.

**Comment by shawkins** [comment]
Just running against minikube, I'm starting a watcher as above and then just creating service events:

```
for (int i = 0;; i++) {
            servicesOp.create(new ServiceBuilder()
                    .withNewMetadata()
                    .withName("s" + i)
                    .endMetadata()
                    .withNewSpec()
                    .withSelector(Map.of("app", "myapp"))
                    .addNewPort()
                    .withProtocol("TCP")
                    .withPort(8080)
                    .withNewTargetPort(9376)
                    .endPort()
                    .endSpec()
                    .build());
            Thread.sleep(5000);
            servicesOp.withName("s" + i).delete();
        }
```

After an hour there were no more service events, but create/deletes kept happening.

The debug level was set for io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener and confirmed that no reconnect attempts were made - implying that kubernetes did not apply an expected min timeout to the watch.  I'll see if manually specifying a timeout seems to address this.

**Comment by shawkins** [comment]
Setting a timeout just seems to get this into a bad state sooner.  With other Watches and a timeout I can see the expected behavior of a reconnect sometime after the min timeout.

**Comment by shawkins** [comment]
@manusa @metacosm any idea of what to look for here in terms of a fix?  As far as WatchConnectionManager or even OkHttp is concerned the websocket seems valid, but there are no events.

**Comment by shawkins** [comment]
There is definitely a behavioral difference compared with the go client.  If I do:

```
        var api = clientset.CoreV1().Services(`default`)
	endpoints, err := api.List(context.TODO(), metav1.ListOptions{})
	if err != nil {
		panic(err.Error())
	}
	resourceVersion := endpoints.ListMeta.ResourceVersion

	timeout := int64(120)
	watcher, err := api.Watch(context.TODO(), metav1.ListOptions{
		Watch:           true,
		ResourceVersion: resourceVersion,
		TimeoutSeconds:  &timeout,
	})
	if err != nil {
		panic(err.Error())
	}
	ch := watcher.ResultChan()

	for event := range ch {
		e := event.Type
		log.Print(e)
	}
```
The Watch is terminated at the timeout.  With the fabric8 client the Watch will continue to run, but receive no events.

**Comment by shawkins** [comment]
On the timeout, the difference with the go client: https://github.com/kubernetes/client-go/blob/ccac4151908b528bbe1a9881da437e1a0576de82/rest/request.go#L396 - is it interprets the timeout as both a parameter and a hard timeout for the request.  In practice this means that the hard timeout will always supersede the timeout parameter, which is interpreted as a min.  Simply adding a callTimeout to the OkHttpClient builder in the WatchConnectionManager won't work as OkHttp is clearing the timeout in the connection attempt (later versions don't seem to be doing that).  So this may require scheduling a close.

However even without a timeout, when I just let the go client run in this example - it will disconnect.  I'll see if I can track down why.

**Comment by shawkins** [comment]
The differences are:

* The go client always uses an http GET for a Watch.  fabric8 is using a websocket which will simply stop receiving events when you reach the timeout (at the one determined by the server if it's not specified with the ListOptions) for Services.  For other resources that I tried, you do see a close control frame.  If I switch fabric8 to use just a http GET everything works as fabric8 currently expects.

* The go client will terminate the Watch at the timeout, whereas fabric8 will schedule a reconnect.  

* The go client if you specify timeoutSeconds=X will also add the query parameter timeout=Xs

@manusa @metacosm For my purposes with Informers only the first bullet item needs immediate attention.  That does appear to be a kubernetes bug.  I can either workaround by switching fabric8 to always use just an http GET for watches, or by adding / enforcing a default timeout  with a scheduled job to reconnect the watch.  What approach do you prefer?  Or would you rather try to determine all of the resource types that could possibly be affected by this bug?

**Comment by rohanKanojia** [comment]
>  I can either workaround by switching fabric8 to always use just an http GET for watches

+1 to this from my side, I think it would be safer to add some flag `kubernetes.watch.type`(defaults to `websocket`) with which user can switch to HTTP get watch

**Comment by metacosm** [comment]
It'd be interesting to know why this happens only for some resources, though that does seem like a kubernetes issue. Did you already create a kubernetes ticket?

Another aspect to take into account is that while, obviously, watches should keep working until stopped, mimicking the go client behavior is not a particular desiderata (though, that helps migrating from one client to the other, of course).

**Comment by manusa** [comment]
I find that the current approach of using websockets and falling-back to a standard HTTP request is not really great since we might get into many non-deterministic problems based on the environment and network.

> I think it would be safer to add some flag kubernetes.watch.type(defaults to websocket) 

Rohan's proposal seems something reasonable to me. However, I'd go for a different path, which would basically be able to set the way the Watcher was to be connected (3 modes), maybe with a flag or a DSL config method:
- AUTO: (current implementation), tries to upgrade to a Websocket connection or falls-back to standard HTTP
- WEBSOCKET: Will only connect via Websocket, or fail otherwise (no fall-back)
- HTTP: Will only connect via HTTP GET, or fail otherwise (no fall-back)


Regarding the Websocket vs. HTTP.

AFAIK Websockets should be more resilient and shouldn't get affected by other "environmental" timeouts such as connections going through a Proxy. So IMO Websockets should always be preferred.

Regarding the receiving updates for service resources issue, I haven't seen anything like that before. Have you tried this in different Kubernetes versions?
Trying to fix this by scheduling automatic reconnects every n period doesn't sound like something reasonable for me. There must be an underlying cause that should get fixed.

**Comment by shawkins** [comment]
> Did you already create a kubernetes ticket?

https://github.com/kubernetes/kubernetes/issues/102464

> Another aspect to take into account is that while, obviously, watches should keep working until stopped, mimicking the go client behavior is not a particular desiderata (though, that helps migrating from one client to the other, of course).

That addresses the third bullet point - meaning it's preferable to have the auto-reconnect behavior at the base Watch layer, rather than just in the Informer or higher-level style Watches.

**Comment by shawkins** [comment]
> Have you tried this in different Kubernetes versions?

No, effectively just in 1.20.

> Trying to fix this by scheduling automatic reconnects every n period doesn't sound like something reasonable for me. 

That is effectively what the api server is supposed to do now - it's just that we're relying on the server side default / handling,  rather client side handling.  The only issue with introducing our own default is that 

> There must be an underlying cause that should get fixed.

I'll wait a bit to get more feedback on the upstream issue, so that the scope of the problem is more understood, before adding a pr for a workaround here.

**Comment by shawkins** [comment]
It appears from the upstream issue that this is a regression in 1.20 specifically for Service websocket watches, so the workaround can be pretty narrow if desired.

**Comment by shawkins** [comment]
> maybe with a flag or a DSL config method

My first thought was to try putting ``` Watchable<W> withWatchConnectionType(ConnectionType type); ``` on the Watchable interface.  That works fine, except for the NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl requires updating all ResourceHandler logic to accept an additional watch parameter.  

Given the scope of the problem I don't like the idea of addressing this with a config property - this will only affect service Watches lasting longer than 30 minutes on specific versions of kubernetes.

@manusa is it worth pursuing the dsl method, or should this just captured as a known issue with the recommended solution of restarting your service watches by whatever means is simplest.

**Comment by manusa** [comment]
> @manusa is it worth pursuing the dsl method, or should this just captured as a known issue with the recommended solution of restarting your service watches by whatever means is simplest.

I guess the issue will affect any other client "implementation". I don't know how we could "capture this as a known issue", do you mean a FAQ/troubleshooting entry?

**Comment by shawkins** [comment]
> I guess the issue will affect any other client "implementation"

Yes any client using a websocket for a Service watch.

> I don't know how we could "capture this as a known issue", do you mean a FAQ/troubleshooting entry?

Exactly.  Unless it's simple task to update the ResourceHandler logic, that's all I would do at this point.

**Comment by shawkins** [comment]
> I don't know how we could "capture this as a known issue", do you mean a FAQ/troubleshooting entry?

I assumed that a document like that existed, but I don't see anything.  I'll just close this issue - between this entry and the upstream issue a user should be able to find more on the root cause and see that the only workaround is to restart the watches / informers.
