### ISSUE TITLE
Functional differences between DefaultOpenShift and DefaultKubernetes clients

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3179]
What are the expected functional differences between these clients?

We're seeing that at least custom resource handling differs because the defaultkubernetes client specifies a default delete propagation of background, while the openshift client does not so it default to orphan.

cc @rohanKanojia @manusa

**Comment by metacosm** [comment]
My point of view on this is that there shouldn't be any functional differences between both clients i.e. the OpenShift client should be a strict superset of the Kubernetes one. If it isn't, then that is a bug, in my opinion.

**Comment by manusa** [comment]
> My point of view on this is that there shouldn't be any functional differences between both clients...

+1

> ...defaultkubernetes client specifies a default delete propagation of background, while the openshift client does not so it default to orphan.

I'm not sure about this, but I think that this might be the result of duplicate implementations not being updated in both places.

IMHO OpenShiftClient should be a superset of the KubernetesClient with DSLs for OpenShift specific resources, period. The core behavior for resource management should be the same regardless of the target cluster. Maybe we should put some effort into unifying implementations so we avoid situations like the one you mention.

**Comment by metacosm** [comment]
> IMHO OpenShiftClient should be a superset of the KubernetesClient with DSLs for OpenShift specific resources, period. The core behavior for resource management should be the same regardless of the target cluster. Maybe we should put some effort into unifying implementations so we avoid situations like the one you mention.

Not sure how easy it is to do but, imo, the `OpenShift` client should simply extend the `KubernetesClient` and simply add access to OpenShift-specific resources. This way, both implementations would be kept in sync.

**Comment by shawkins** [comment]
I may have gleaned the rationale for the delegate approach, so one possible alternative approach would be to make a generic version of the DefaultKubernetesClient - #3212

Let me know if that seems reasonable.

**Comment by manusa** [comment]
So why do you think we originally followed the delegate approach?

**Comment by shawkins** [comment]
> So why do you think we originally followed the delegate approach?

Because of the circular nature of NamespacedKubernetesClient - for methods that returned something including that type you couldn't then extend the class and return a NamespacedOpenshiftClient.  Delegation was one approach to address that.
