### ISSUE TITLE
pod metric does not have corresponding label selector variant

### ISSUE THREAD

**Issue by stevefan1999-personal** [fabric8io/kubernetes-client#3225]
https://github.com/fabric8io/kubernetes-client/pull/2091/files#diff-a6467663e5e1a2cbb5550f6696989a6e52e601bacb1ccb0dc7a6e489dafc4d90R102-R119

It is possible to filter node by using label selector, but it doesn't have the equivalent of what could be done with pod metrics

**Comment by rohanKanojia** [comment]
You're right. We seem to have inconsistency with `client.top()` here. We should try to make this consistent just like standard API.

**Comment by manusa** [comment]
The k8s metrics-server doesn't follow the standard implementation as the rest of K8s resources. We have a specific implementation to query the endpoints provided.
In this case, the implementation for Pods is missing the filter. We could try to unify both implementations (Pods, and Nodes) and fix your issue.
