### ISSUE TITLE
Missing Probe attributes

### ISSUE THREAD

**Issue by lwander** [fabric8io/kubernetes-client#323]
The Probe spec is defined [here](https://godoc.org/k8s.io/kubernetes/pkg/api/v1#Probe). The fabric8 client API is missing `TimeoutSeconds, PeriodSeconds, SuccessThreshold,` and `FailureThreshold`. The HTTPGet Probe Handler defined [here](https://godoc.org/k8s.io/kubernetes/pkg/api/v1#HTTPGetAction) is missing `HTTPHeaders,` and `URIScheme`. 

Is there any plan to add these?

**Comment by jimmidyson** [comment]
We're still working against a slightly older version of kubernetes for our generated model. We're upgrading very soon which should automatically included these new attributes. Will comment here once these a release out supporting this.

**Comment by jimmidyson** [comment]
This should now be supported in 1.3.73 which we just released. Thanks for the report!

**Comment by lwander** [comment]
Wow, that was super quick! You guys are great, thanks!

**Comment by jimmidyson** [comment]
:blush: Thanks!
