### ISSUE TITLE
Port-forward feature is failing when it runs inside a Docker container

### ISSUE THREAD

**Issue by carlosgodoytrapero** [fabric8io/kubernetes-client#3234]
The library (5.3.0 version) fails because it doesn’t determine the localhost correctly inside the Docker container.
 
You can see the ports which are exposed when it is launched by the library getting an incorrect state:
 
```shell
$ netstat -apn | grep 9090
(Not all processes could be identified, non-owned process info
will not be shown, you would have to be root to see it all.)
tcp6       0      0 :::9090                 :::*                    LISTEN      -
```

and by the kubectl port-forward command when everything works:
 
```shell
root@seliius27699:/target# kubectl port-forward -n test eric-pm-server-0 9090:9090 &
root@seliius27699:/target# netstat -pan | grep 9090
tcp        0      0 127.0.0.1:9090          0.0.0.0:*               LISTEN      44/kubectl         
tcp6       0      0 ::1:9090                :::*                    LISTEN      44/kubectl         
```
 
So, taking a look in your kubectl-api library, you have the next code:

```java
mapPortForwards.put(serviceName, defaultKubernetesClient.services().inNamespace(namespace)
                .withName(serviceName)
                .portForward(servicePort));
```

Where the defaultKubernetesClient of fabric8io doesn’t support specific localhost (we will need 0.0.0.0 for a docker container) and establish the value by itself (PortForwardable implementation always instantiates PortForwarder with localhost as null, and then calculate it internally).
 
```java
public interface PortForwarder {
  LocalPortForward forward(URL resourceBaseUrl, int port);
  LocalPortForward forward(URL resourceBaseUrl, int port, int localPort);
  LocalPortForward forward(URL resourceBaseUrl, int port, InetAddress localHost, int localPort);
  PortForward forward(URL resourceBaseUrl, int port, ReadableByteChannel in, WritableByteChannel out);
}
 
public interface PortForwardable<H, L, I, O> {
  H portForward(int port, I in, O out);
  L portForward(int port, int localPort);
  L portForward(int port);
}
```

**Comment by rohanKanojia** [comment]
Umm, we do have a `portForward(int port, int localPort)` method? Have you tried that out?

**Comment by carlosgodoytrapero** [comment]
Hi, the problem is related to the IP address really, because it must be set to 0.0.0.0 in order to be accessed outside the container.
Thanks!

**Comment by rohanKanojia** [comment]
ohk, I see.

**Comment by rohanKanojia** [comment]
@carlosgodoytrapero : Hi, You're right we always seem to be passing localhost as `null` in PortForwardWebsocket, so server always gets initialized to `ServerSocketChannel.open().bind(new InetSocketAddress(localPort))`

https://github.com/fabric8io/kubernetes-client/blob/1f5061f1f04b046ed0fb40b2a9a7432b72b452cb/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PortForwarderWebsocket.java#L80-L85

Do you think adding an additional DSL method to specify InetAddress in PortForwardable will resolve your issue?
```diff
--- a/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/PortForwardable.java
+++ b/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/PortForwardable.java
@@ -15,6 +15,8 @@
  */
 package io.fabric8.kubernetes.client.dsl;
 
+import java.net.InetAddress;
+
 public interface PortForwardable<H, L, I, O> {
 
   /**
@@ -36,6 +38,8 @@ public interface PortForwardable<H, L, I, O> {
    */
   L portForward(int port, int localPort);
 
+  L portForward(InetAddress inetAddress, int port, int localPort);
+

```

**Comment by rohanKanojia** [comment]
> Hi, the problem is related to the IP address really, because it must be set to 0.0.0.0 in order to be accessed outside the container.

@carlosgodoytrapero : Right now we're always binding ServerSocketChannel to `new InetSocketAddress(localPort)`, doesn't it create socket address with IP address as wildcard address(`0.0.0.0`)?  

I tried doing port-forward from within a Pod in Kubernetes and I was able to do it with KubernetesClient v5.4.1. I copied [PortForwardExample.java](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/PortForwardExample.java) and created a small project from it: https://github.com/r0haaaan/kubernetes-port-forward-inside-pod-java

I deployed this to my minikube cluster using Eclipse JKube:
```
mvn package k8s:build k8s:resource k8s:apply
```
After this when I check application logs, I'm able to see port-forward being successful:
```
port-forward-inside-pod : $ kubectl get pods
NAME                                               READY   STATUS             RESTARTS   AGE
k8s-port-forward-inside-pod-ccd8949b9-stkvn        1/1     Running            0          9s
port-forward-inside-pod : $ kubectl logs pod/k8s-port-forward-inside-pod-ccd8949b9-stkvn
Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
INFO exec  java -javaagent:/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar=config=/opt/jboss/container/jolokia/etc/jolokia.properties -javaagent:/usr/share/java/prometheus-jmx-exporter/jmx_prometheus_javaagent.jar=9779:/opt/jboss/container/prometheus/etc/jmx-exporter-config.yaml -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/k8s-port-forward-inside-pod-1.0-SNAPSHOT-jar-with-dependencies.jar  
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jolokia.util.ClassUtil (file:/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar) to constructor sun.security.x509.X500Name(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.jolokia.util.ClassUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Jun 25, 2021 10:09:41 AM in.rohaan.PortForwardExample main
INFO: Using namespace: default
I> No access restrictor found, access to any MBean is allowed
Jolokia: Agent started with URL https://172.17.0.30:8778/jolokia/
Jun 25, 2021 10:09:42 AM in.rohaan.PortForwardExample main
INFO: Pod test-portforward2kcfm created
Jun 25, 2021 10:09:46 AM in.rohaan.PortForwardExample main
INFO: Pod test-portforward2kcfm Port forwarded for 60 seconds at http://127.0.0.1:9001
Jun 25, 2021 10:09:46 AM in.rohaan.PortForwardExample main
INFO: Checking forwarded port:-
Jun 25, 2021 10:09:46 AM in.rohaan.PortForwardExample main
INFO: Response: 
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

```

**Comment by carlosgodoytrapero** [comment]
Hi @rohanKanojia,
sure, it could be enough for us. How can we try it? Which version/black-build/commit can contain your fix?
Many thanks in advance.
Carlos G.

**Comment by rohanKanojia** [comment]
@carlosgodoytrapero : I haven't created a PR yet. But I wasn't able to reproduce your issue, I wanted to reproduce and test fix before creating PR. I created a sample project which creates a pod and port forwards it inside the pod and it is working with v5.4.1 https://github.com/r0haaaan/kubernetes-port-forward-inside-pod-java.git 

Could you please review my previous comment? Did I reproduce your issue correctly or did i miss something?

**Comment by rohanKanojia** [comment]
> How can we try it? Which version/black-build/commit can contain your fix?

@carlosgodoytrapero : In case you want to try it this is reference to my branch: https://github.com/rohankanojia/kubernetes-client/tree/pr/issue3234

But what I observed is that this won't be necessary and you should be able to port forward from within a pod and access from outside without any explicit configuration(since default InetAddress is a wildcard one). I would really appreciate if you could try out my reproducer and provide some feedback.

**Comment by carlosgodoytrapero** [comment]
Hi,
sure, I will try it. I would need a while along these busy weeks.
Thanks for your patience.
Carlos G.

**Comment by carlosgodoytrapero** [comment]
Hi again,
I will have fewer busy weeks on the second/third week of September.
Many thanks for your patience.
Carlos G.

**Comment by carlosgodoytrapero** [comment]
Hi @rohanKanojia, seems to be fine! Sorry for the delay in my answers.
How do you deliver the patch in order to use it?
Many thanks,
Carlos G.

**Comment by carlosgodoytrapero** [comment]
Hi again @rohanKanojia, any update? Any plan to merge in master?

**Comment by rohanKanojia** [comment]
> But what I observed is that this won't be necessary and you should be able to port forward from within a pod and access from outside without any explicit configuration(since default InetAddress is a wildcard one). I would really appreciate if you could try out my reproducer and provide some feedback.

oh, I thought my commit wasn't necessary. Have you tested your project by bulding kubernetes-client based on my branch? Do you want me to create PR?

**Comment by carlosgodoytrapero** [comment]
Sorry, it was tried by my team. I thought the shot was with your branch, but let me share with them how they did.

**Comment by carlosgodoytrapero** [comment]
Hi @rohanKanojia,

I am so sorry for the delay in our answers.

We have tried again and it fails if our server has IPv4 and IPv6 at the same time. The idea is to instantiate the PortForward to the IP we need in each case as we proposed in that past.

I have seen you opened a PR according to the @manusa issue.

How much time is to be merged in master as an official delivery?

Many thanks,
Carlos G.

**Comment by rohanKanojia** [comment]
@carlosgodoytrapero : I'm waiting to get some feedback on PR from @MatanLevy . I'll try to get this PR get into v5.12.0

**Comment by carlosgodoytrapero** [comment]
Ok, it's something important for us because it always fails because of the different interfaces we have.
In order to get a plan, how much time do you usually spend to deliver a new version?
Many thanks again.
Carlos G.

**Comment by rohanKanojia** [comment]
I think our next version v5.12.0 should be out within 2-3 weeks

**Comment by carlosgodoytrapero** [comment]
Hi again,
sorry for the disturbances. 
2-3 weeks is fair enough, but is any way to try a blackbuilt? Any blackbuilt maven repo, artifactory? In order to verify the fix sooner than a sprint.
Thanks again.
Carlos G.

**Comment by rohanKanojia** [comment]
@carlosgodoytrapero : You can build a SNAPSHOT version locally and use `5.12-SNAPSHOT` in your project to see if it resolves your issue

**Comment by rohanKanojia** [comment]
There is one more option to use Jitpack https://jitpack.io/

**Comment by avensis** [comment]
Hello Rohan,

I am a member of Carlos team and I want to check your fix. I am facing some issues maybe you can help me with that.

1. I checked out pr/issue3234 kubernetes-client code
2. I run clean install and generated 5.12-SNAPSHOT in local
3. I download your project https://github.com/r0haaaan/kubernetes-port-forward-inside-pod-java
4. I added the local dependency to your test project pom
![image](https://user-images.githubusercontent.com/1147588/149819187-2b88d19d-0002-4879-b94d-6ff26db7659a.png)
5. Modified your test code to take the kubeconfig of our cluster
![image](https://user-images.githubusercontent.com/1147588/149819864-73a290d4-c566-4bc9-8588-340c4e8a22be.png)
But I am having a slf4j dependency issue.
![image](https://user-images.githubusercontent.com/1147588/149819898-6080bc68-bc70-4eb8-92e8-1c3ce0a9d70e.png)
I added that dependency manually to the test pom
![image](https://user-images.githubusercontent.com/1147588/149820014-19de2d6d-282e-4cfe-b1e9-f670f34e63a8.png)
But still displaying the error.

Any help is welcome. 

Greetings.

**Comment by rohanKanojia** [comment]
Are you referring to that NoClassDefFoundError or slf4j warning (that looks more concerning to me) ? From what I remember I had done this testing on minikube.

I have updated the project https://github.com/r0haaaan/kubernetes-port-forward-inside-pod-java . You should no longer see the slf4j warning. I tested it again on minikube using kubernetes maven plugin with kubernetes client `5.12-SNAPSHOT` and port forwarding seems to be working.

**Comment by avensis** [comment]
Hello Rohan, 

I properly checked the Feature and works as expected. 

Please can you give us a estimation about when the 5.12 version will be deployed. 

Thanks in advance.

**Comment by rohanKanojia** [comment]
If everything goes well, we might release 5.12.0 within a week
