### ISSUE TITLE
getExistingSharedIndexInformer may Incorrect

### ISSUE THREAD

**Issue by FqqCS** [fabric8io/kubernetes-client#3235]
https://github.com/fabric8io/kubernetes-client/blob/b0dbeef2f6795934ea0a0c57b2d4ed3748aa0a18/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformerFactory.java#L282

```java
 private static <T> boolean isKeyOfType(String key, Class<T> apiTypeClass) {
        String plural = HasMetadata.getPlural(apiTypeClass);
        return key.contains(plural);
    }
```

this may incorrect： return key.contains(plural); 
for example： virtualservice and service

**Comment by rohanKanojia** [comment]
yes, you're right. I'm trying to remove this string key creation logic in https://github.com/fabric8io/kubernetes-client/pull/3230

**Comment by rohanKanojia** [comment]
@FqqCS : I've added a test case for your use case in https://github.com/fabric8io/kubernetes-client/pull/3230/files#diff-775882ab5373e4fd32c8a42e81a80feabcc3e699f7346f3c171b5cd940516a59R123 .

Would be awesome if you could review

**Comment by manusa** [comment]
Relates to: #2010
