### ISSUE TITLE
Kubernetes v1.21.x Support

### ISSUE THREAD

**Issue by westernemergency** [fabric8io/kubernetes-client#3242]
Good morning,

This is a question, not an issue.

The 5.4.0 release notes of fabric8 start to mention support for Kubernetes clusters v1.21.0. Does this release support Kubernetes clusters of version 1.21.x? I do not see this mentioned on the compatibility matrix but I just wanted to make sure this wasn't an oversight.

Thanks!

**Comment by rohanKanojia** [comment]
Sorry, looks like we forgot to update the compatibility matrix after release. Would you like to submit a PR for this?

**Comment by ps-19** [comment]
@rohanKanojia will you assign me this issue??

**Comment by rohanKanojia** [comment]
@ps-19 : You'll need to add one more row for Kubernetes 1.21.1 in README.md Kubernetes compatibility matrix

https://github.com/fabric8io/kubernetes-client/blob/master/README.md#kubernetes-compatibility-matrix

**Comment by ps-19** [comment]
> row

you mean one more column at left position K8 1.21.1??

**Comment by rohanKanojia** [comment]
oh, yeah. Sorry, you're right you have to add a column

**Comment by ps-19** [comment]
> 
> 
> oh, yeah. Sorry, you're right you have to add a column

https://github.com/fabric8io/kubernetes-client/pull/3279
