### ISSUE TITLE
Provided PipedInputStream should not be closed

### ISSUE THREAD

**Issue by pdudits** [fabric8io/kubernetes-client#3243]
As reported in #2497 and #1896 utilizing `readingOut` and `readingErr` to capture execution output looses last chunk of data.

This is caused by `ExecWebSocketListener` closing both provided `PipedInputStream` as well as producing `PipedOutputStream`.

When `PipedOutputStream` is closed, it only notifies connected `PipedInputStream` that no more data will be transferred.
`PipedInputStream` would still make the rest of its buffer available. 

However as soon as `close` is invoked on `PipedInputStream` its buffer pointer is reset and any further attempt to read will cause an `IOException("Pipe closed")`.

This causes data loss and exceptions thrown to client, and the workaround is to suppress call to `close()`:

```
            PipedInputStream out = new PipedInputStream() {
                @Override
                public void close() throws IOException {
                    // k8s client errornously closes the stream when execution finishes.
                    // this prevents reading the rest of the buffer
                }
            };
            client.pods().withName(pod.getMetadata().getName())
                    .inContainer(container.getName())
                    .readingOutput(out)
                    .exec(command);
```

**Comment by rohanKanojia** [comment]
@pdudits : Thanks for reporting this, Would it be possible for you to contribute a fix for this issue?

**Comment by rohanKanojia** [comment]
@shawkins : Do you think we can take care of this issue in https://github.com/fabric8io/kubernetes-client/pull/3169 ?

**Comment by pdudits** [comment]
I can try, should be ok as long as I don't hit major obstacles in building (for example, master doesn't seem to compile on `1.8.0_292` at first attempt).

Also in `ExecWebSocketListener#inputStreamOrPipe` a `connect` call seems to be missing that would connect the provided `PipeOutputStream` to input.
