### ISSUE TITLE
ensure delete returns only when the delete operation is fully finished

### ISSUE THREAD

**Issue by victornoel** [fabric8io/kubernetes-client#3246]
Hi,

If I'm calling delete on a job for example, it takes time for the operation to really finish, but the delete call returns early, even if I used the FOREGROUND DeletionPropagation (not sure it's really linked to the matter ^^).

It would make sense to add an option so that the call only returns when everything is deleted as expected. A bit like the `--wait` parameter of kubectl works in that context (see https://github.com/kubernetes/kubernetes/issues/42594).

**Comment by victornoel** [comment]
Related to #1474

**Comment by victornoel** [comment]
Potential workaround:
```java
client.batch().v1().jobs()
    .inNamespace(namespace)
    .withName(name)
    .waitUntilCondition(Objects::isNull, 10, TimeUnit.SECONDS);
```

**Comment by manusa** [comment]
There's a different behavior between what the REST API does when performing a deletion with the foreground propagation policy and what `kubectl` does.

When you perform a `kubectl delete ... --cascade='foreground`, the command waits until every dependent resource is deleted to complete the execution.

However, when you perform the same operation using the REST API (with `foreground` PropagationPolicy), the requests returns as soon as the resource has been modified and the `deletionTimestamp` has been added to the metadata. I'm not sure if the client should take care of performing this wait/blocking for you.

Your suggestion is exactly what you need to do if you really need to provide blocking until the resource was effectively deleted.

**Comment by victornoel** [comment]
@manusa I understand. It makes sense indeed, thank you for the explanation, I will continue with my solution then!
