### ISSUE TITLE
why not support for the workqueue ?

### ISSUE THREAD

**Issue by Zephery** [fabric8io/kubernetes-client#3251]
like client-go

**Comment by rohanKanojia** [comment]
@Zephery : Could you please provide some more details of your use case? It looks like you're talking about workqueue in terms of Operators. Do you think this makes more sense in Java Operator SDK[0] ?

[0] https://github.com/java-operator-sdk/java-operator-sdk

**Comment by rohanKanojia** [comment]
Looks like you're talking about this client-go util workqueue[0] [1]. How different is this queue from standard queue implementations java offers(`LinkedBlockingQueue`)?

[0] https://pkg.go.dev/k8s.io/client-go/util/workqueue
[1] https://github.com/kubernetes/client-go/blob/master/util/workqueue/queue.go

**Comment by Zephery** [comment]
Sorry, my fault. I thought workqueue can have distribute capacity just like redis list.

My use cases is 
1.Project A(Deployment): Put some tasks in a queue, and then create  some Jobs from the queue.(Looks like i have touse redis.)
2.Project B(Job): running, and then complete.
3.Project A(Deployment): Fine parallel processing using informer to handle jobs number, If it get the complete event from informer, it will continue take a task from queue. and then create job util queue is empty.

In project A, if i set replicas to 2 or more, i don't know how to control the parallelism of my  tasks.

**Comment by rohanKanojia** [comment]
@Zephery : Do you think your use case is similar to https://github.com/fabric8io/kubernetes-client/issues/3115 ?
