### ISSUE TITLE
Some resources do not have namespace on the REST URL

### ISSUE THREAD

**Issue by KurtStam** [fabric8io/kubernetes-client#326]
The k8s URL for Users is
GET /oapi/v1/users
and not 
GET /oapi/v1/namespaces/<namespace>/users

> ConfigBuilder builder = new ConfigBuilder().withOauthToken(token);
>         OpenShiftClient osClient = null;
>         try {
>             osClient = new DefaultOpenShiftClient(builder.build());
>             //get the userName
>             User user = osClient.users().withName("~").get();

Some calls support both
GET /oapi/v1/buildconfigs
GET /oapi/v1/namespaces/<namespace>/buildconfigs

There is no good way to tell the OpenShiftClient which one to use.

Workaround:

> ConfigBuilder builder = new ConfigBuilder().withOauthToken(token);
>         OpenShiftClient osClient = null;
>         try {
>             osClient = new DefaultOpenShiftClient(builder.build());
>             //get the userName
>             User user = osClient.inAnyNamespace().users().withName("~").get();

**Comment by iocanel** [comment]
The only thing that makes sense is to ignore the namespace (if present) for resources that are not namespaced (e.g. Users). For all others cases we should play along.

**Comment by iocanel** [comment]
I think we can close now.
