### ISSUE TITLE
Cannot delete CR with spec field on Kubernetes server in CRUD mode

### ISSUE THREAD

**Issue by benediktwetzel** [fabric8io/kubernetes-client#3264]
I can create a CR with `spec` field, but when I try to delete this CR, I get a `404 client error`. It works correctly for CRs without spec field.

I read something about the `@JsonIgnoreProperties(ignoreUnknown = true)` annotations, but it does not work as expected.

For reproducibility, a simple example test function:

```Kotlin
   @JsonIgnoreProperties(ignoreUnknown = true)
    fun simpleTest(){
        val server = KubernetesServer(false,true)
        server.before()
        val resource = mapOf(
            "apiVersion" to "monitoring.coreos.com/v1",
            "kind" to "ServiceMonitor",
            "metadata" to mapOf("name" to "test-service-monitor"),
            "spec" to "" // uncomment this line and it will work
        )

        val context = CustomResourceDefinitionContext.Builder()
            .withVersion("v1")
            .withScope("Namespaced")
            .withGroup("monitoring.coreos.com")
            .withPlural("servicemonitors")
            .build()

        server.client.customResource(context).create(server.client.namespace, resource)
        server.client.customResource(context).delete(server.client.namespace, "test-service-monitor" )
    }
```

Error messages:
* `INFO: MockWebServer[58277] received request: DELETE /apis/monitoring.coreos.com/v1/namespaces/test/servicemonitors/test-service-monitor HTTP/1.1 and responded: HTTP/1.1 404 Client Error`
* `Failure executing: DELETE at: http://localhost:58277/apis/monitoring.coreos.com/v1/namespaces/test/servicemonitors/test-service-monitor.
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: DELETE at: http://localhost:58277/apis/monitoring.coreos.com/v1/namespaces/test/servicemonitors/test-service-monitor.`

What am I doing wrong, must CRDs be registered by the mock server? Is there an example?

**Comment by shawkins** [comment]
What version are you using?  This works as expected against master, which uses a generic representation for the cr, and I suspect it should work in 5.4 as well as I made a change there to ignore unknown properties.

**Comment by benediktwetzel** [comment]
We had transitivite Gradle dependencies which caused us to use an old version of the mock server. With version 5.4.1 it works correctly. Thanks you!
