### ISSUE TITLE
Mock KubernetesServer in 5.4.x does not allow to update status anymore

### ISSUE THREAD

**Issue by victornoel** [fabric8io/kubernetes-client#3267]
Hi,

Since 5.4 it's not possible to update the status of a resource when using `KubernetesServer`.

I see this has been fixed for 5.5 though in #3138 but until 5.5 is released (maybe it's soon?), it's difficult to use v5.4.

I may be missing something obvious and it's actually possible tough… I'm using the following in my tests to simulate that a job has started:
```java
server.client.batch().v1().jobs().inNamespace("default").withName("name").editStatus {
            return new JobBuilder(it)
                    .editOrNewStatus()
                    .withFailed(1)
                    .endStatus()
                    .build()
        }
```

The status is simply ignored and the resource does not change.

**Comment by shawkins** [comment]
https://github.com/fabric8io/kubernetes-client/milestone/27 should be in about a week or so.

**Comment by victornoel** [comment]
@shawkins thx, I can just wait in that case, I let you close the ticket if you don't plan to do it for 5.4.x?

**Comment by shawkins** [comment]
I have no plans, @manusa please reopen if this seems needed for 5.4.x.
