### ISSUE TITLE
waitUntilCondition resource too old exception

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3271]
I tried to do a waitUntilCondition call, that eventually errorred out with a resource too old exception.  This seems to come from WatcherException isShouldRetry - it explicitly is false when there's an http gone exception.

It should either be the other way around, or to retry no matter what the exception is.

**Comment by shawkins** [comment]
After this change the internal wait code can be mostly cleaned up:  https://github.com/fabric8io/kubernetes-client/commit/63d555d13b1ac9e683d7eb8cc159d9ba93c35490 (not all of the tests were updated yet)

However that code shows there is inconsistent handling of the interrupted exception.  At least for our own internal usage it would be better to not throw it directly from waitUntilCondition and instead use a KubernetesClientException.  Since the proposed change is already breaking wrt exception handling, could we make that change as well?

The only remaining waiting scenario is a pod list scenario, which could be addressed by #3278

**Comment by manusa** [comment]
> ...interrupted exception....instead use a KubernetesClientException...
I guess that now that the underlying behavior has changed, it no longer makes sense to have it as part of the method signature.

The change should not be breaking (strictly speaking) since KubernetesClientException is unchecked
