### ISSUE TITLE
AMQ - classes generated from CRD

### ISSUE THREAD

**Issue by lfabriko** [fabric8io/kubernetes-client#3276]
Hello, wouldn't it be possible to generate classes for AMQ CRD https://github.com/strimzi/strimzi-kafka-operator/blob/main/install/cluster-operator/040-Crd-kafka.yaml? (I can see in https://github.com/fabric8io/kubernetes-client/tree/master/extensions are e.g. for Camel-K...) thanks for info

**Comment by rohanKanojia** [comment]
@lfabriko : Hello, Doesn't strimzi contain Java classes for these CRDs already? If I'm not wrong isn't Kafka.java[0] class for your CRD?

[0] https://github.com/strimzi/strimzi-kafka-operator/blob/main/api/src/main/java/io/strimzi/api/kafka/model/Kafka.java

**Comment by lfabriko** [comment]
Hello, yes, it does. thanks for info.
