### ISSUE TITLE
Watches: IllegalStateException: stream != null

### ISSUE THREAD

**Issue by ibalashov** [fabric8io/kubernetes-client#328]
I'm trying to run Kubernetes app on GCE, where Watch API stopped working with following error:
```
Exception in thread "OkHttp Dispatcher" java.lang.IllegalStateException: stream != null
        at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:153)
        at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.squareup.okhttp.Call.getResponse(Call.java:286)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
        at com.squareup.okhttp.Call.access$100(Call.java:35)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Before GCE, I've run some tests on laptop and Watches worked OK-ish (apart from known leaked connection problem).

Any ideas what could be happening?

**Comment by jimmidyson** [comment]
I've had a quick look at okhttp source & I think this  is another manifestation of us not properly closing some calls properly. I'll try & get a fix in for that today & fingers crossed this should go away too.

**Comment by ibalashov** [comment]
@jimmidyson Thanks. I just got some new findings. Remote debugger showed (at the breakpoint of exception)
```
stream -> httpEngine -> userResponse
Response{protocol=http/1.1, code=401, message=Unauthorized, url=https://104.197.230.239/apis/extensions/v1beta1/namespaces/4finance/jobs?fieldSelector=&resourceVersion=103502&watch=true}
```
Strangely enough the very same KubernetesClient object was already successfully used to create and delete jobs, thus must be authorized properly. Does watches have own authorization? Btw, I use `configBuilder.withUsername` & `configBuilder.withPassword`, without explicit Certs or PKs.

Also, I authorized `kubectl` on that box, not sure though if this could be related.

**Comment by iocanel** [comment]
Watches do use a "cloned" instance of the http client. 

In the case of oauth we are using an interceptor which adds the token to the request. The cloned instance and the web socket call seem to handle the interceptor well. It seems that this is not the case when we use an Authenticator for basic authentication.

I am wondering if skipping username/password (and let the client use the service account) would fix your problem (as a workaround).

**Comment by ibalashov** [comment]
@iocanel Thanks for the suggestion.

Just tried without username and password. "Regular" ops (job creation) work fine, then on watch start I get the same `stream != null` error.

Btw, when username and password are not set, where does the service account info comes from?

**Comment by jimmidyson** [comment]
@ibalashov If you're running in a pod then it automatically uses the service account token from `/var/run/secrets/kubernetes.io/serviceaccount/token` but this requires the service account controller being  set up (which should be by default iirc).

Can you share something to reproduce what you're seeing & a full log please? If you enable trace logging then we can see all requests that are sent through.

**Comment by ibalashov** [comment]
@jimmidyson No, I'm running as a standalone app, not from a Pod.

I've enabled TRACE, and see a lot of failed 'Unauthorized' requests, followed by same requests only with `Authorization: Basic` field and the latter succeed. Is this expected? 
[https://gist.github.com/ibalashov/2d64486b0c145032dda9](https://gist.github.com/ibalashov/2d64486b0c145032dda9)

**Comment by jimmidyson** [comment]
@ibalashov That is expected - okhttp (the awesome underlying http client we use) sends authentication details on 401. This is pretty standard but we could override that with an interceptor to send the Authorization header if username/password are set. Could you open up a separate issue for that? And of course contributions very welcome :)

**Comment by ibalashov** [comment]
Created #329. 

It is still a mystery for me where the Kubernetes authentication comes from. I mean regular ops work even without username/password set in builder on my laptop.  Also, nothing in `/var/run/secrets/kubernetes.io`. Does it take auth info from `gcloud` tool?

**Comment by jimmidyson** [comment]
It's magic :) Well not really... By default it tries to use the standard places for auth info - ~/.kube/config for normal users on their machines & also tries token from /var/run/secrets/kubernetes.io if available. This is similar to what kubectl / oc do.

**Comment by ibalashov** [comment]
@jimmidyson Great news, I replaced `~/.kube/config` with the laptop's and Watches started to work again. The difference was that my laptop's config has lot more fields, such as client-certificate-data, client-key-data, certificate-authority-data. 

I must have setup kubernetes auth wrong, following instructions at [logging-into-a-kubernetes-cluster-with-kubectl/](http://blog.christianposta.com/kubernetes/logging-into-a-kubernetes-cluster-with-kubectl/)

In any case it would be a lot easier to find out if the error was not cryptic `stream != null`.

**Comment by jimmidyson** [comment]
That's interesting. Did you manually create the kube config file or use kubectl?

You're totally right that's an awful error message... have to think how to improve, but I still think it's related to the leaked connections.

**Comment by ibalashov** [comment]
@jimmidyson I used `kubectl` following exact steps as mentioned in the article.

**Comment by jimmidyson** [comment]
I think we're all good with this now so closing but if it comes back up we can reopen.
