### ISSUE TITLE
OpenShift Java client supports which version of OpenShift?

### ISSUE THREAD

**Issue by git-abhijit** [fabric8io/kubernetes-client#3281]
Hi, 
I want to develop a sample orchestrator in Java + Spring Boot for deploying applications on a Openshift Cluster, can I use the OpenShift  Java client ? Also which version of OpenShift API's are currently supported ? 

Is there any sample application which is invoking OpenShift API's ? 

Thanks and Regards
Abhijit

**Comment by rohanKanojia** [comment]
Umm, I think we have tested OpenShiftClient till OpenShift v4.5.x, see compatibility matrix[0]. We should probably update it with recent OpenShift versions. 

You can find OpenShift related examples here[1].

Bdw, shouldn't you be using something like Eclipse JKube OpenShift Maven Plugin for deploying your applications to OpenShift : https://www.eclipse.org/jkube/docs/openshift-maven-plugin

[0] https://github.com/fabric8io/kubernetes-client#openshift-compatibility-matrix
[1] https://github.com/fabric8io/kubernetes-client/tree/master/kubernetes-examples/src/main/java/io/fabric8/openshift/examples

**Comment by git-abhijit** [comment]
Hi Rohan,

Thanks for your quick and details response. I will go through the details shared. 

Bdw, shouldn't you be using something like Eclipse JKube OpenShift Maven Plugin for deploying your applications to OpenShift --> Yes. I forgot to mention in my previous post, we are having Maven Pugin ?  

I had earlier worked with Kubernetes java client (had added the maven dependency in the pom.xml) , so I believe similarly we have for openshift-java client right ? 

I will be used IntelliJ IDE and my application will be a maven project. 

Thanks and Regards
Abhijit

**Comment by rohanKanojia** [comment]
OpenShift-Maven-Plugin is a maven plugin based on Fabric8 Kubenretes Client.

> I had earlier worked with Kubernetes java client (had added the maven dependency in the pom.xml) , so I believe similarly we have for openshift-java client right ?

Yes, I think you're looking for https://search.maven.org/artifact/io.fabric8/openshift-client/5.4.1/jar

**Comment by git-abhijit** [comment]
Thanks Rohan.

**Comment by git-abhijit** [comment]
Hi Rohan , 

One more help, similar to Java , are we have for GoLang too ? Package in Golang which can invoke Openshift API's 

Thanks and Regards
Abhijit

**Comment by rohanKanojia** [comment]
https://github.com/openshift/client-go

**Comment by git-abhijit** [comment]
Thanks. This also supports the same version as for Java Client ?

**Comment by rohanKanojia** [comment]
I don't know. It's not aligned with our project. Since it's in OpenShift org, it's releases are aligned with OpenShift releases.

**Comment by git-abhijit** [comment]
Ok. Thanks Rohan.
