### ISSUE TITLE
HasMetadataOperation createVisitableBuilder

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3284]
I added that method for edit operations - but I can see that it's possibly not needed given we should be able to lookup the Handler does that seem reasonable?  Related to this there are apiVersion members/methods on both BaseOperation and HasMetadataOperation - should those be consolidated?

I'm also thinking it may not be a good idea to use the builder for cloning - just in case there are issues, like the one seen with CustomResource cloning, that would lead to really subtle bugs.  

@rohanKanojia @manusa WDYT?

**Comment by manusa** [comment]
Context #3070

**Comment by manusa** [comment]
> I added that method for edit operations

I'm a little bit lost here.

> Related to this there are apiVersion members/methods on both BaseOperation and HasMetadataOperation - should those be consolidated?

I only see the `apiVersion` member in BaseOperation:
https://github.com/fabric8io/kubernetes-client/blob/5751f31c5f5c4f711d19e8d2325db66d5ab3d277/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java#L109

I can't find that in the HasMetadataOperation class. Maybe you are referring to the static methods in the HasMetadata class? If this is the case, I don't think they can be consolidated. However, I'm a bit confused about the purpose of that field.

> I'm also thinking it may not be a good idea to use the builder for cloning

I think that, although it's a costly operation, we should probably use a serialize/deserialize (or convert to Map/Array+Map and back via Jackson) to stay on the safe side and avoid side-effects.

**Comment by shawkins** [comment]
> I'm a little bit lost here.

https://github.com/fabric8io/kubernetes-client/blob/289a1eceba5bf23f350ea07ace240c79506aa5e1/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java#L81

Used in 

https://github.com/fabric8io/kubernetes-client/blob/289a1eceba5bf23f350ea07ace240c79506aa5e1/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java#L89

and

https://github.com/fabric8io/kubernetes-client/blob/289a1eceba5bf23f350ea07ace240c79506aa5e1/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.java#L60

It sounds like we're in agreement to remove that latter usage.

In looking at replacing the create method with handler logic, I see

https://github.com/fabric8io/kubernetes-client/blob/e1cc9045a967af6f2ce63537b7f7ce619e6d743b/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java#L124 (above I mistakenly said HasMetadataOperation).

It appears to mean just the version.

and 

https://github.com/fabric8io/kubernetes-client/blob/e1cc9045a967af6f2ce63537b7f7ce619e6d743b/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java#L951

That one only appears to be set by CustomResourceOperationsImpl and means the group + version.
