### ISSUE TITLE
Always send Authorization header if username/password is set

### ISSUE THREAD

**Issue by ibalashov** [fabric8io/kubernetes-client#329]
Currently Authorization header is sent only after 401 is responded, which results in unnecessary network round-trips. Would be great to always include auth header if username/password is set.

**Comment by jimmidyson** [comment]
This is a great idea, but I'd like to use a caching interceptor in conjunction with the existing authenticator so that the creds are only negotiated on first request & then sent via the caching interceptor in subsequent requests.

Contibution welcome.

**Comment by iocanel** [comment]
just a clarification the described behavior affects only the open shift client. also the obtained key is cached, so the unnecessary round trip only affects the first request. so it shouldn't be hard to implement.

**Comment by jimmidyson** [comment]
@iocanel The OpenShift client is actually unaffected by this - obtaining an oauth token works great for OpenShift client. This is actually only for Kubernetes clients that use Basic auth with username & password.

**Comment by iocanel** [comment]
yeah but the k8s client will aways use basic auth if username/password exist, there is no trying with auth and fallback to basic auth if we get 401 / 403 (that particular part) is open shift only.

**Comment by jimmidyson** [comment]
Yes but it has extra round trips as okhttp client only uses Authenticator on 401/403s - see https://github.com/fabric8io/kubernetes-client/blob/86f42e178f9821f71367c883ea439f1c26c48387/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java#L80-L104 for the reason for the Authenticator.

Round trip for every call in this case is send request, receive 401/403, send basic auth header, rinse, repeat on every request. If we cache that first round trip auth header then we can pre-emptively send on subsequent requests.
