### ISSUE TITLE
Retry setting should be applied when an IOException is thrown

### ISSUE THREAD

**Issue by geoand** [fabric8io/kubernetes-client#3291]
https://github.com/fabric8io/kubernetes-client/pull/3164 introduced support for retry setting when certain HTTP 5XX responses are received from the client in order to deal with transient failures.
In the same spirit, it makes sense to use the same settings to handle IOExceptions that can be thrown for example when an application tries to contact the API server via a sidecar that has not come up yet.

**Comment by attilapiros** [comment]
Today I have a few hours at my computer and started to working on this.
Thanks @geoand for creating the issue!

**Comment by geoand** [comment]
Great, thanks 👌
