### ISSUE TITLE
how to get apiGroupList use kubernetes-client? 

### ISSUE THREAD

**Issue by gewei2000** [fabric8io/kubernetes-client#3294]
how to get apiGroupList use kubernetes-client?

**Comment by rohanKanojia** [comment]
Do you mean `ApiService`? If yes, you can get them like this:
```java
try (KubernetesClient client = new DefaultKubernetesClient()) {
    client.apiServices().list().getItems().stream()
            .map(APIService::getMetadata)
            .map(ObjectMeta::getName)
            .forEach(System.out::println);
}
```

**Comment by gewei2000** [comment]
> Do you mean `ApiService`? If yes, you can get them like this:
> 
> ```java
> try (KubernetesClient client = new DefaultKubernetesClient()) {
>     client.apiServices().list().getItems().stream()
>             .map(APIService::getMetadata)
>             .map(ObjectMeta::getName)
>             .forEach(System.out::println);
> }
> ```

io.fabric8.kubernetes.api.model.APIGroupList，this model

**Comment by gewei2000** [comment]
> Do you mean `ApiService`? If yes, you can get them like this:
> 
> ```java
> try (KubernetesClient client = new DefaultKubernetesClient()) {
>     client.apiServices().list().getItems().stream()
>             .map(APIService::getMetadata)
>             .map(ObjectMeta::getName)
>             .forEach(System.out::println);
> }
> ```

I want to get preferred version, but I don't how to get APIGroupList use this client

**Comment by rohanKanojia** [comment]
@gewei2000 : ohk, we're missing support for this.

**Comment by manusa** [comment]
This would be really useful to get the cluster available API groups and API resources:

```shell
$ kubectl proxy --port=8081
$ curl localhost:8081/apis
# For any of the available groups
$ curl localhost:8081/apis/apps/v1
```
The response for the `APIResourceList` provides the required information to interact with any group/resource in K8s. This is really useful when we need to deal with Custom Resources and we don't have a definition (CRD) for them.
An improvement for the GenericKubernetesResource operations DSL method, might include querying these endpoints and then retrieving the necessary data to infer the plural and scope of the resource.

**Comment by shawkins** [comment]
I could take this for 5.8.  ApiGroup is not annotated appropriately, so it will just take a couple of other changes to expose it via the dsl.

**Comment by manusa** [comment]
Take into account that this is not really a resource, just an additional HTTP endpoint exposed by Kubernetes.

So not the same operations that apply to the rest of resources apply for this. It makes sense in the scope of an API group (e.g. client.apps() or client.network()).

So if API groups and versions could be interfaced appropriately should be easy.

**Comment by shawkins** [comment]
Sure, I was initially thinking that it would be something like getting a handler for the ApiGroup / ApiGroupList and exposing only the list operation.  But looking at it more, that doesn't work so well with the expectations in base operation.  It would be simpler to move the isAdaptable logic into a 
ApiGroupLIst KubernetesClient.getApiGroups() method.  and/or support getting a single one as well.

**Comment by manusa** [comment]
>  ApiGroupLIst KubernetesClient.getApiGroups() method. and/or support getting a single one as well.

Yes, so basically we are looking at what was exposed in my [comment](https://github.com/fabric8io/kubernetes-client/issues/3294#issuecomment-874002876), get a list of the available groups and then for each group, be able to retrieve the available resources with their required info (plural, scope, etc.)

These new methods can be then used by the GenericResource loader to perform operations on **any** available resource (as discussed https://github.com/fabric8io/kubernetes-client/issues/3392#issuecomment-895787311 & https://github.com/fabric8io/kubernetes-client/issues/3392#issuecomment-895982955).

Some pseudo-logic:
1. Check in client cache if a given group exists
  - If it doesn't, reload group cache by using _kubernetesClient.getApiGroups()_ (#3294)
2. Check in client cache if a given resource (group+version+kind) exists
  - If it doesn't, reload resource cahce by using _kubernetesClient.getApiResources(ApiGroup)_ (#3303)
3. Use the information from the cached ApiResource(s) to determine the required plural and scope for the GenericKubernetesResourceOperationsImpl
