### ISSUE TITLE
Add implements Serializable to model classes

### ISSUE THREAD

**Issue by mattrpav** [fabric8io/kubernetes-client#3302]
.. title just about covers it. Having the models be serializable is super handy

**Comment by mattrpav** [comment]
jsonschema2pojo has support

https://joelittlejohn.github.io/jsonschema2pojo/site/0.4.34/generate-mojo.html#serializable

**Comment by manusa** [comment]
This is a topic that has been discussed several times.
All models should already implement Serializable since they implement the KubernetesResource interface which extends Serializable.
So it's the opposite #2402 (remove the Serializable interface) what has been requested and discussed on several occasions.
It would be good to know what your take is on this topic in case it's readdressed in the future.

**Comment by mattrpav** [comment]
@manusa thanks for the pointer to KubernetesResource. We use Apache Wicket which takes advantage of Serializable, and I agree that it is a good practice to keep it around and does not incur any real cost to users.

We have never run across any problems with using Serializable across other frameworks. We create single model objects that support JAXB, JSON, Serializable and JPA and they all work as expected.

**Comment by manusa** [comment]
:)
Funny you mention Apache Wicket. I was a heavy user 10 years ago. I suffered the Serializable pain too, and that's why even when using Jackson or other libraries I tend to declare classes that are being _serialized_ in one way or another Serializable.

**Comment by mattrpav** [comment]
Always excited to come across a fellow Wicket user (even past ones). Apache Wicket has been amazing for us. Upgrades since v1.4 have been very smooth and server-side render has been a great fit for us. 

Re Serializable-- agreed. It has a lot of practical benefits and sometimes you just want to write down a collection of objects and having access to a json or jaxb marshaller isn't the best fit. It works well for what it is and doesn't incur any dependency headaches.
