### ISSUE TITLE
Support for fetching APIResourceList

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#3303]
Similar to APIGroup which is accessible via `/apis` endpoint(see https://github.com/fabric8io/kubernetes-client/issues/3294), there is another NON-Restful endpoint in Kubernetes related to all available resources in a particular API group. It specifies information regarding a resource like the name of a resource and whether it is namespaced and supported operations.

Here is how it's used:
```bash
~ : $ curl localhost:8001/apis/batch/v1
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "batch/v1",
  "resources": [
    {
      "name": "jobs",
      "singularName": "",
      "namespaced": true,
      "kind": "Job",
      "verbs": [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch"
      ],
      "categories": [
        "all"
      ],
      "storageVersionHash": "mudhfqk/qZY="
    },
    {
      "name": "jobs/status",
      "singularName": "",
      "namespaced": true,
      "kind": "Job",
      "verbs": [
        "get",
        "patch",
        "update"
      ]
    }
  ]
}
```
I observed is that it's only possible to get a list of APIResource objects in a particular API group. It's not possible to get a specific APIResource object.

**Comment by manusa** [comment]
This is what is mentioned in https://github.com/fabric8io/kubernetes-client/issues/3294#issuecomment-874002876.

I think this might be exposable through our DSL, but I really think this would be very useful internally for the #2929 implementation.
