### ISSUE TITLE
Error during using networking.k8s.io/v1 apiVersion to create Ingress with Fabric8io 4.9.2

### ISSUE THREAD

**Issue by FuyaoLi2017** [fabric8io/kubernetes-client#3315]
I am using Fabric8io 4.9.2 version and can't update the version for now due to limitation. (Apache Flink version)

I want to create a Ingress using Fabric8io API, when using `networking.k8s.io/v1beta1` apiVersion. I am good. However, when I switched to `networking.k8s.io/v1`. I saw the errors below.

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.96.0.1/apis/networking.k8s.io/v1/namespaces/default/ingresses. Message: Ingress.extensions "flink-native-k8s-operator" is invalid: spec.rules[0].http.paths[0].backend: Invalid value: "": resource or service backend is required. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.rules[0].http.paths[0].backend, message=Invalid value: "": resource or service backend is required, reason=FieldValueInvalid, additionalProperties={})], group=extensions, kind=Ingress, name=flink-native-k8s-operator, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Ingress.extensions "flink-native-k8s-operator" is invalid: spec.rules[0].http.paths[0].backend: Invalid value: "": resource or service backend is required, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
```

If I don't specify the apiVersion explicitly, it will default to v1beta1 and gives me the warning message like this. In this case, it will still work.
```
2021-07-13 19:57:41,701 WARN  io.fabric8.kubernetes.client.internal.VersionUsageUtils      [] - The client is using resource type 'ingresses' with unstable version 'v1beta1'
```

I know there is spec change (https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122) from v1beta1 to v1 and probably 4.9.2 can't support it? Is there any work around to make 4.9.2 can successfully create a Ingress with `networking.k8s.io/v1`apiVersion? I think it could be hard since Kubernetes update the Ingress schema and 4.9.2 might not be putting the key-value pairs to the correct place.

>spec.backend is renamed to spec.defaultBackend
The backend serviceName field is renamed to service.name
Numeric backend servicePort fields are renamed to service.port.number
String backend servicePort fields are renamed to service.port.name
pathType is now required for each specified path. Options are Prefix, Exact, and ImplementationSpecific. To match the undefined v1beta1 behavior, use ImplementationSpecific.

Any suggestion is appreciated.

My  current implementation that will run into error above looks like this

```
final List<IngressRule> ingressRules = new ArrayList<>();
for (Tuple2<FlinkApplication, Configuration> entry : flinkApps.values()) {
    final FlinkApplication flinkApp = entry.f0;
    final String clusterId = flinkApp.getMetadata().getName();
    final int restPort = entry.f1.getInteger(RestOptions.PORT);

    String ingressHost = clusterId + Constants.INGRESS_SUFFIX;
    ingressRules.add(new IngressRule(ingressHost, new HTTPIngressRuleValueBuilder()
        .addNewPath()
        .withNewBackend().withNewServiceName(clusterId + Constants.REST_SVC_NAME_SUFFIX).withNewServicePort(restPort).endBackend()
.withNewPathType("ImplementationSpecific")
        .endPath()
        .build()));
}

final Ingress ingress = new IngressBuilder()
    .withApiVersion("networking.k8s.io/v1")
    .withNewMetadata().withName(Constants.FLINK_NATIVE_K8S_OPERATOR_NAME).endMetadata()
    .withNewSpec()
    .withRules(ingressRules)
    .endSpec()
    .build();
```

**Comment by manusa** [comment]
Changing the ApiVersion of a provided type won't work in most cases.

Your best bet is to use a CustomResource or Raw types to achieve what you want.

**Comment by manusa** [comment]
I don't have any example for that.
In the end, the Java types and builders match whatever you have in a YAML manifest. If you can get hold of a valid YAML example for your configuration, it should be trivial to convert it to the Java DSL-builder syntax.
