### ISSUE TITLE
do we have any util to convert java schema to yaml schema?

### ISSUE THREAD

**Issue by gewei2000** [fabric8io/kubernetes-client#3320]
do we have any util to convert java schema to yaml schema?

**Comment by rohanKanojia** [comment]
Could you please elaborate? Are you talking about Kubernetes resource schema? Or you just want to convert a json string to yaml. I do see some methods in IOHelper utility class for this purpose:

https://github.com/fabric8io/kubernetes-client/blob/ad080a660eefd0742b48253088d601ab66cc2313/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/IOHelpers.java#L70-L78

**Comment by gewei2000** [comment]
> Could you please elaborate? Are you talking about Kubernetes resource schema? Or you just want to convert a json string to yaml. I do see some methods in IOHelper utility class for this purpose:
> 
> https://github.com/fabric8io/kubernetes-client/blob/ad080a660eefd0742b48253088d601ab66cc2313/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/IOHelpers.java#L70-L78
I want to convert k8s resource object to a yaml template file, such as comfigmap
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: xxx
  annotations: {}
  namespace: xxx
data:
  key: string
```

**Comment by rohanKanojia** [comment]
We have `SerializationUtils.dumpAsYaml(yourConfigMap)` do you think this can fit your use case?
