### ISSUE TITLE
All Cluster Scoped Kubernetes resources should use NonNamespacedOperation

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#3325]
Kubernetes Cluster resources don't require the namespace. For these methods, we should use NonNamespacedOperation instead of MixedOperation. MixedOperation interface introduces a `inNamespace` method which is not required for these cluster scoped resources:

ComponentStatus
https://github.com/fabric8io/kubernetes-client/blob/8fe5c8c4b7709105117f916a37ed1fbb80b02ea8/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java#L296

ValidatingWebhookConfiguration
https://github.com/fabric8io/kubernetes-client/blob/8fe5c8c4b7709105117f916a37ed1fbb80b02ea8/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1AdmissionRegistrationAPIGroupDSL.java#L26
https://github.com/fabric8io/kubernetes-client/blob/8fe5c8c4b7709105117f916a37ed1fbb80b02ea8/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1beta1AdmissionRegistrationAPIGroupDSL.java#L26

MutatingWebhookConfiguration
https://github.com/fabric8io/kubernetes-client/blob/8fe5c8c4b7709105117f916a37ed1fbb80b02ea8/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1AdmissionRegistrationAPIGroupDSL.java#L27
https://github.com/fabric8io/kubernetes-client/blob/8fe5c8c4b7709105117f916a37ed1fbb80b02ea8/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/V1beta1AdmissionRegistrationAPIGroupDSL.java#L27

APIService
https://github.com/fabric8io/kubernetes-client/blob/8fe5c8c4b7709105117f916a37ed1fbb80b02ea8/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java#L446

PodSecurityPolicy
https://github.com/fabric8io/kubernetes-client/blob/8fe5c8c4b7709105117f916a37ed1fbb80b02ea8/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/V1beta1PolicyAPIGroupDSL.java#L37

**Comment by manusa** [comment]
Fixed in #3348
