### ISSUE TITLE
Update APIs for Kubernetes 1.22

### ISSUE THREAD

**Issue by fhcarter** [fabric8io/kubernetes-client#3326]
Kubernetes 1.22 (purportedly due out mid-late August 2021) is removing a number of APIs which are currently used in the Kubernetes-client.  The one I use the most is the Ingress & ingress builder, part of the extensions, which are  currently based on the extensions/v1beta1 and networking.k8s.io/v1beta1 API versions.  As of 1.22, these will no longer work.

The changes necessary & steps required are summarized in [Kubernetes API and Feature Removals](https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/).

**Comment by rohanKanojia** [comment]
These resources have been dropped in Kubernetes. But their model(go structs) still seems to be present in Kubernetes 1.22.1 source:

- admissionregistration.k8s.io/v1beta1 
https://github.com/kubernetes/api/blob/v0.22.1/admissionregistration/v1beta1/types.go
- authorization.k8s.io/v1beta1 
https://github.com/kubernetes/api/blob/v0.22.1/authorization/v1beta1/types.go
- apiextensions.k8s.io/v1beta1
https://github.com/kubernetes/apiextensions-apiserver/blob/v0.22.1/pkg/apis/apiextensions/v1beta1/types.go
- extensions/v1beta1 Ingress
https://github.com/kubernetes/api/blob/v0.22.1/extensions/v1beta1/types.go
- networking.k8s.io/v1beta1 Ingress 
https://github.com/kubernetes/api/blob/v0.22.1/networking/v1beta1/types.go
- certificates.k8s.io/v1beta1 
https://github.com/kubernetes/api/blob/master/certificates/v1beta1/types.go#L34

I think we would be able to upgrade to Kubernetes 1.22 without encountering any issue.
