### ISSUE TITLE
Add support for Server Side Apply

### ISSUE THREAD

**Issue by xaviersierra** [fabric8io/kubernetes-client#3334]
# Server Side Apply
 
Starting from kubernetes 1.16, [Server Side Apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/) it's enabled by default.
 
This feature is very useful from a operator development point of view,
 since it would require fewer requests to the Kubernetes API during the reconciliation cycle.
 
Using Server Side Apply has also the advantage that inform to users
 who owns which field of a given resource.
 
# Proposed Change
 
Add a boolean field to the io.fabric8.kubernetes.client.dsl.base.PatchContext named serverSide. That if it's true, sets the request content type to `application/apply-patch+yaml`.

**Comment by rohanKanojia** [comment]
Related to https://github.com/fabric8io/kubernetes-client/issues/2454

**Comment by shawkins** [comment]
Fabric8 6 will support server side apply with a patch call:

```
client.services().withName("name").patch(PatchContext.of(PatchType.SERVER_SIDE_APPLY), service);
```

you may need to force it if the resource was not created using the fabric8 server side apply:

```
client.services().withName("name").patch(new PatchContext.Builder().withPatchType(PatchType.SERVER_SIDE_APPLY).withForce(true).build(), service);
```

**Comment by tacf** [comment]
@shawkins Doesn't this solution provide a way to patch through the use of manifests? As in, does this only allow patching with the use of code defined objects?

**Comment by shawkins** [comment]
> As in, does this only allow patching with the use of code defined objects?

There are other patch methods that accept the patch as a string if you don't want to use the object representation.
