### ISSUE TITLE
Add ConversionReview to Kubernetes ApiExtensions Model

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#3336]
ConversionReview, ConversionRequest and ConversionResponse might be used by users who are interested in writing a conversion webhook in order to handle CustomResource conversions from one version to other.

You can find equivalent go struct here: https://github.com/kubernetes/apiextensions-apiserver/blob/master/pkg/apis/apiextensions/v1/types.go#L457

**Comment by MUzairS15** [comment]
Can I try on this?

**Comment by rohanKanojia** [comment]
Yes, sure. Here are the steps you need to follow in order to complete this:

1. Add ConversionReview in Kubernetes Model APIExtension generator:
   https://github.com/fabric8io/kubernetes-client/blob/9f0ce58d159d818a89ca0b330467fa57dd2b9c05/kubernetes-model-generator/kubernetes-model-apiextensions/cmd/generate/generate.go#L80
2. If you have golang installed run `make` to generate model. 
3. Verify you have ConversionRequest.java, ConversionResponse.java, and ConversionReview.java generated. 
4. Add test for basic serialization, deserialization of ConversionReview

**Comment by MUzairS15** [comment]
Pls assign me

**Comment by manusa** [comment]
There's no clear path to use these new types from [CustomResourceDefinitionSpec#conversion](https://github.com/fabric8io/kubernetes-client/blob/13387c759e7144d0c879b0903442a572ad54b030/kubernetes-model-generator/kubernetes-model-apiextensions/src/generated/java/io/fabric8/kubernetes/api/model/apiextensions/v1/CustomResourceDefinitionSpec.java#L60) ->
[CustomResourceConversion#webhook](https://github.com/fabric8io/kubernetes-client/blob/13387c759e7144d0c879b0903442a572ad54b030/kubernetes-model-generator/kubernetes-model-apiextensions/src/generated/java/io/fabric8/kubernetes/api/model/apiextensions/v1/CustomResourceConversion.java#L56) -> [WebhookConversion#conversionReviewVersions](https://github.com/fabric8io/kubernetes-client/blob/13387c759e7144d0c879b0903442a572ad54b030/kubernetes-model-generator/kubernetes-model-apiextensions/src/generated/java/io/fabric8/kubernetes/api/model/apiextensions/v1/WebhookConversion.java#L58) -> ...

Go [WebhookConversion#ConversionReviewVersions](https://github.com/kubernetes/apiextensions-apiserver/blob/e11bc83fa8292528c907091cbfb36adb604be352/pkg/apis/apiextensions/v1/types.go#L99) -> ?? -> [ConversionReviewVersions](ConversionReviewVersions)

Do you have any example @rohanKanojia ?

**Comment by rohanKanojia** [comment]
Conversion webhooks for CRDs are launched in the cluster and put behind a Service object, and that service object is referenced by the conversion webhook specification in the CRD manifest.

I don't have any concrete example. I found this by a quick search on web(written using client-go): https://github.com/madorn/crd-conversion-webhook
