### ISSUE TITLE
Add Private Constructors to Utility classes to hide implicit ones

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#3339]
As per the Sonar rule[0], Utility classes, which are collections of static members, are not meant to be instantiated. Even abstract utility classes, which can be extended, should not have public constructors.

Java adds an implicit public constructor to every class which does not define at least one explicitly. Hence, at least one non-public constructor should be defined.

You can find all classes where we need to add private constructors here[1]

[0] https://sonarcloud.io/organizations/fabric8io/rules?open=java%3AS1118&rule_key=java%3AS1118
[1] https://sonarcloud.io/organizations/fabric8io/issues?resolved=false&rules=java%3AS1118

**Comment by MUzairS15** [comment]
Pls assign me.

**Comment by KamalSinghKhanna** [comment]
Hey is this issue still open I would like to give it a try.

**Comment by rohanKanojia** [comment]
@MUzairS15 : Are you still working on this? If not, can we assign this to @KamalSinghKhanna ?

**Comment by MUzairS15** [comment]
ok, you can assign to @KamalSinghKhanna

**Comment by rohanKanojia** [comment]
> ok, you can assign to @KamalSinghKhanna

When I wrote this comment yesterday, I didn't notice you already had a PR open https://github.com/fabric8io/kubernetes-client/pull/3351 . Do you think there is still more work to be done in scope of this issue which is not covered by your PR?

**Comment by MUzairS15** [comment]
I don't think so, but I saw your comment so I thought there is something more to do that I am missing.
@KamalSinghKhanna you can go through #3351 and  https://sonarcloud.io/organizations/fabric8io/issues?resolved=false&rules=java%3AS1118 and check is there something more required.

**Comment by rohanKanojia** [comment]
I think you updated all files in your PR. I'll create some other good first issues.

**Comment by rohanKanojia** [comment]
@KamalSinghKhanna : Hi, I've created https://github.com/fabric8io/kubernetes-client/issues/3355 . Feel free to pick it up in case you're interested.
