### ISSUE TITLE
Remove useless curly braces around lambda statements

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#3342]
As per this Sonar rule[0], there is no need to have curly braces around single-line lambda statements. We can simply remove it. For example this code:

https://github.com/fabric8io/kubernetes-client/blob/d70d021b5c7dbbf7a94c2821164f67459500d2f5/extensions/service-catalog/examples/src/main/java/io/fabric8/servicecatalog/examples/ListServiceClassesByBroker.java#L32-L34

can be rewritten as:
```java
 list.getItems().stream()
     .forEach(b -> System.out.println(b.getSpec().getExternalName() + "\t\t\t\t" + b.getMetadata().getName()));
```

You can find all occurrences where we need to remove useless braces here[1]

[0] https://sonarcloud.io/organizations/fabric8io/rules?open=java%3AS1602&rule_key=java%3AS1602
[1] https://sonarcloud.io/organizations/fabric8io/issues?projects=fabric8io_kubernetes-client&resolved=false&rules=java%3AS1602

**Comment by Shatakshi0805** [comment]
could you please assign this to me.

**Comment by aadityasinha-dotcom** [comment]
Is this issue open?
