### ISSUE TITLE
Remove or refine CreateOnlyResourceOperationsImpl

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3350]
The usage of CreateOnlyResourceOperationsImpl creates a parallel set of logic for HasMetadata resources that is not needed to just satisfy the dsl.

After the commit of #3327 this could be done with:

Create 
```
public interface NamespacedInOutCreateable<I,O> extends Namespaceable<InOutCreateable<I, O>>, InOutCreateable<I, O>  {}
```
and 
```
public interface InOutCreateableDeletable<I,O> extends InOutCreateable<I, O>, Deletable, Nameable<InOutCreateableDeletable<I,O>>  {}
```
To replace references to NamespacedCreateOnlyResourceOperationsImpl and ImageStreamXXXOperationsImpl in the dsl api.

Handlers.getCreateOnlyOperation(Class<T> type, OkHttpClient client, Config config) -- just returns the HasMetadataOperation with an inferred list type (so it can do more than just creates). 

Handlers.getNamespacedCreateOnlyOperation(Class<T> type, OkHttpClient client, Config config) -- will create a wrapper class around the operation returned above to implement the inNamespace method.

And a similar method/wrapper for InOutCreateableDeletable.

For all instances where in and out are the same type and there's no special handling in the operation, the classes can be replaced with these invocations - which appears to be all of them currently.  Those operations will also be available for resource(item) calls - but should fail for anything other than a create.  It might also be a good idea to just use Createable<T>, rather than InOutCreatable<T, T> in the api as well.

@rohanKanojia @manusa WDYT?

**Comment by manusa** [comment]
Blocked on #3327 

So I guess that what you are suggesting is that instead of returning xxxOperationsImpl in the method signatures we return a specific interface. The DSL will then be limited by the scope of these interfaces despite the underlying xxxOperationsImpl we use.

So the purpose of the issue is to implement interfaces that combine the required operations, right? I think this is a good improvement.

**Comment by shawkins** [comment]
> So the purpose of the issue is to implement interfaces that combine the required operations, right?

Yes.  For example on the Handler utility class creating a NamespacedInOutCreateable would look like:

```
  public static <T extends HasMetadata> NamespacedInOutCreateable<T, T> getNamespacedCreateOnlyOperation(Class<T> type, OkHttpClient client, Config config) {
    
    return new NamespacedInOutCreateable<T, T>() {
      private HasMetadataOperation<T, ?, ?> operation = getOperation(type, KubernetesResourceUtil.inferListType(type), client, config); 
      
      @Override
      public InOutCreateable<T, T> inNamespace(String name) {
        return operation.inNamespace(name);
      }
      
      @Override
      public T create(T item) {
        return operation.create(item);
      }
      
      @Override
      public T create(T... item) {
        return operation.create(item);
      }
      
    };
  }
```

Of course you don't necessarily need these wrappers defined in Handlers.
