### ISSUE TITLE
How to describe node?

### ISSUE THREAD

**Issue by CaseCy** [fabric8io/kubernetes-client#3354]
I want to get the info about the reuquests and limits in node , in kubectl ,I use `kubectl describe node` , but I can not find in fabric8io

**Comment by rohanKanojia** [comment]
I think `kubectl` calculates it on its own by fetching data from APIServer. I saw a similar question on StackOverflow[0] a few months ago. Could you please check if this helps your use case?

[0] https://stackoverflow.com/questions/67673662/how-to-get-the-node-cpu-and-memory-value-using-java-io-fabric8-kubernetes-clie

**Comment by CaseCy** [comment]
thanks for that ，I am coding for a project that create job with limit cpu core , I need to know the node's requests and limits that remain to decide whether created automatically,the top way can get the usaged of node(it's real usage) ,but it can't help for commit job to k8s, I think I can only caculate it manually
