### ISSUE TITLE
When I try to run my operator, nothing is happening.

### ISSUE THREAD

**Issue by emrealpogunc** [fabric8io/kubernetes-client#3356]
Hello,
I'm having an issue right now and pretty much don't know the reason behind it So, you can find how it displays on my screen at the end of this message. Basically I tried to do everything exactly as how it seemed but unfortunately neither the pods get created nor I can see any changes whatsoever. I tried many things and yet nothing has changed. You can also find my **"pom.xml"** file down below. I probably did some minor mistake but the difficult part is that I'm not having any errors. 

All the necessary files can be found from here (I tried to recreate this Operator Project).
[https://github.com/rohanKanojia/podsetoperatorinjava](url)

`
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>intellijFiles</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>16</maven.compiler.source>
        <maven.compiler.target>16</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>kubernetes-client</artifactId>
            <version>5.6.0</version>
       </dependency>
    </dependencies>
    <build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>2.3.2</version>
            <configuration>
                <source>1.8</source>
                <target>1.8</target>
            </configuration>
        </plugin>
    </plugins>
</build>
</project>
`

![Screenshot from 2021-07-27 20-20-17](https://user-images.githubusercontent.com/76528314/127200262-d5bd967c-dd6b-4d0d-a47c-cba5aa54f89e.png)
![Screenshot from 2021-07-27 20-29-09](https://user-images.githubusercontent.com/76528314/127200362-583bb8f6-886f-4bef-86b2-406c948d13ae.png)

**Comment by rohanKanojia** [comment]
@emrealpogunc: Hi, a Kubernetes Operator usually reacts on a Custom Resource. Are you creating a CustomResource(PodSet) in this case(`kubectl apply -f src/main/resources/cr.yaml`? The expected behavior is:
1. User creates a PodSet
2. Operator detects a PodSet is created and it creates child pods with specified number of replicas

**Comment by emrealpogunc** [comment]
> @emrealpogunc: Hi, a Kubernetes Operator usually reacts on a Custom Resource. Are you creating a CustomResource(PodSet) in this case(`kubectl apply -f src/main/resources/cr.yaml`? The expected behavior is:
> 
>     1. User creates a PodSet
> 
>     2. Operator detects a PodSet is created and it creates child pods with specified number of replicas

I've found the mistake! My "cr.yaml" file had a small issue (I'm the sole responsible of this issue) so I rewrote the whole "cr. yaml" file which was fairly short and now it's working perfectly! Thank you so much I'm really relieved now ^_^ Just got the notification, thank you once again!
