### ISSUE TITLE
 Kubernetes Context reset to the default one

### ISSUE THREAD

**Issue by ZviMints** [fabric8io/kubernetes-client#3362]
Hey
I'm using `fabric8io` to create `k8sClient` as follows:
```
  private[this] val client = new DefaultKubernetesClient(Config.autoConfigure( "my wrong context"))
```
and then when I'm calling the following function:
```diff
 def pauseConnector(): Unit = {
    logger.info(s"[KubernetesService] - pauseConnector() Triggered")

    val connector = getConnector()
    connector.getSpec.setPause(true)
-    println(client.getConfiguration.getCurrentContext)  // Will use my current context and not fail
    Crds.kafkaConnectorOperation(client).inNamespace(config.connectorNamespace).withName(config.connectorName).replace(connector)

    Crds.kafkaConnectorOperation(client)
      .inNamespace(config.connectorNamespace)
      .withName(config.connectorName)
      .waitUntilCondition(connector => {
        connector != null &&
          connector.getSpec.getPause == true && {
          ConnectorTask.getTasks(connector)
          match {
            case Left(failureOnFindTasks) => logger.info(failureOnFindTasks); false
            case Right(tasks) => tasks.forall(_.state.equalsIgnoreCase("Paused"))
          }
        }
      }, config.timeout.toMillis, TimeUnit.MILLISECONDS)

    logger.info(s"[KubernetesService] - Connector: ${connector.getMetadata.getName} Paused")
  }
```
I want to make sure that I'm operation only on the specific context if exists, any reason why its not happening? is that issue on `fabric8io` client?

**Comment by manusa** [comment]
The config.autoConfigure(...) method tries to provide a valid configuration on a best-effort basis with the provided values and some opinionated defaults.

In your case, it tries to use the provided argument as a context, but since it's not found, it will fail-over and use the default context. If it fails, it will even try some further approaches until it finds one suitable.

If you want to make sure that only a given context is used, you should either manually configure the client, or validate that the **auto**configuration inferred by the client matches your expectations.

**Comment by ZviMints** [comment]
Thanks @manusa 
I though there some already implemented client which will not fall over to the default context
I used ensuring as follows:
```scala
 def createAndValidateKubernetesClient(cluster: String, namespace: String): NamespacedKubernetesClient = {
    val k8sClient = new DefaultKubernetesClient(Config.autoConfigure(cluster)).inNamespace(namespace)
    Try {
        k8sClient.getConfiguration.getCurrentContext.getName == cluster &&
        k8sClient.getNamespace == namespace
    } match {
      case Success(isValid) if isValid => k8sClient
      case _ => throw KubernetesEnvironmentSuppliedInvalid(s"Invalid Environment Supplied to KubernetesClient with cluster: $cluster, namespace: $namespace, currentContext: ${k8sClient.getConfiguration.getCurrentContext}, currNamespace: ${k8sClient.getNamespace}")
    }
  }
```
Thanks!
I'm closing this ticket

**Comment by artem-zinnatullin** [comment]
Hi 👋  all, I've stumbled upon exact same issue while working on K8S Deployer that relies on fabric8 client and I must say this defaulting to current context from `~/.kube/config` in case fabric8 can't pick up the context passed as parameter is **very dangerous**.

It essentially leads to whole code working against wrong cluster that has nothing to do with fabric8 configured parameters…

I would suggest to change this behavior to explicit failure in a major release upgrade just to avoid people ruining clusters they didn't even expect to touch!
