### ISSUE TITLE
Support `x-kubernetes-preserve-unknown-fields` for CRD generation

### ISSUE THREAD

**Issue by metacosm** [fabric8io/kubernetes-client#3368]
See https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#controlling-pruning

Relates to java-operator-sdk/java-operator-sdk#458

**Comment by manusa** [comment]
Was this fixed by #3684?

**Comment by metacosm** [comment]
> Was this fixed by #3684?

As far as I'm aware, yes.
