### ISSUE TITLE
Why `ServiceMonitor` is only on OpenShiftClient

### ISSUE THREAD

**Issue by kenfinnigan** [fabric8io/kubernetes-client#3376]
`ServiceMonitor` is a valid Resource type in Kubernetes, so I wanted to ask why retrieving, creating, deleting, etc of a `ServiceMonitor` is only possible through the `OpenShiftClient` and not the `KubernetesClient`?

**Comment by rohanKanojia** [comment]
@kenfinnigan : I wasn't aware of this resource. Are you able to see `ServiceMonitor` in standard Kubernetes resources?
```
kubectl api-resources | grep ServiceMonitor
```

**Comment by rohanKanojia** [comment]
Related to https://github.com/fabric8io/kubernetes-client/issues/2740 https://github.com/fabric8io/kubernetes-client/issues/2915

**Comment by kenfinnigan** [comment]
Ah ok, see what you mean @rohanKanojia.

So you're correct that the `ServiceMonitor` resource is not part of vanilla Kubernetes at present.

However, it's also not OpenShift specific, which is where my head was with thinking about the separation. My understanding was `OpenShiftClient` was for OpenShift specific bits, as opposed to everything that isn't vanilla Kubernetes.

**Comment by rohanKanojia** [comment]
I think since OpenShift 4.x, OpenShift started coming with pre-installed operators. This ServiceMonitor[0] resource becomes available by prometheus-operator[1].

I checked with a fresh CRC installation and ServiceMonitor is available :
```
~ : $ crc start
INFO Checking if running as non-root              
INFO Checking if running inside WSL2              
INFO Checking if crc-admin-helper executable is cached 
INFO Checking for obsolete admin-helper executable 
INFO Checking if running on a supported CPU architecture 
INFO Checking minimum RAM requirements            
INFO Checking if Virtualization is enabled        
INFO Checking if KVM is enabled                   
INFO Checking if libvirt is installed             
INFO Checking if user is part of libvirt group    
INFO Checking if active user/process is currently part of the libvirt group 
INFO Checking if libvirt daemon is running        
INFO Checking if a supported libvirt version is installed 
INFO Checking if crc-driver-libvirt is installed  
INFO Checking if systemd-networkd is running      
INFO Checking if NetworkManager is installed      
INFO Checking if NetworkManager service is running 
INFO Checking if dnsmasq configurations file exist for NetworkManager 
INFO Checking if the systemd-resolved service is running 
INFO Checking if /etc/NetworkManager/dispatcher.d/99-crc.sh exists 
INFO Checking if libvirt 'crc' network is available 
INFO Checking if libvirt 'crc' network is active  
INFO Loading bundle: crc_libvirt_4.8.2...         
INFO Creating CodeReady Containers VM for OpenShift 4.8.2... 
INFO Generating new SSH Key pair...               
INFO Generating new password for the kubeadmin user 
INFO Starting CodeReady Containers VM for OpenShift 4.8.2... 
INFO CodeReady Containers instance is running with IP 192.168.130.11 
INFO CodeReady Containers VM is running           
INFO Updating authorized keys...                  
INFO Check internal and public DNS query...       
INFO Check DNS query from host...                 
INFO Verifying validity of the kubelet certificates... 
INFO Starting OpenShift kubelet service           
INFO Waiting for kube-apiserver availability... [takes around 2min] 
INFO Adding user's pull secret to the cluster...  
INFO Updating SSH key to machine config resource... 
INFO Waiting for user's pull secret part of instance disk... 
INFO Changing the password for the kubeadmin user 
INFO Updating cluster ID...                       
INFO Updating root CA cert to admin-kubeconfig-client-ca configmap... 
INFO Starting OpenShift cluster... [waiting for the cluster to stabilize] 
INFO 2 operators are progressing: authentication, openshift-controller-manager 
INFO Operator authentication is progressing       
INFO Operator authentication is progressing       
INFO All operators are available. Ensuring stability... 
INFO Operators are stable (2/3)...                
INFO Operators are stable (3/3)...                
INFO Adding crc-admin and crc-developer contexts to kubeconfig... 
Started the OpenShift cluster.

The server is accessible via web console at:
  https://console-openshift-console.apps-crc.testing

Log in as administrator:
  Username: kubeadmin
  Password: ApAsC-Ra6A3-3ruES-uhz4E

Log in as user:
  Username: developer
  Password: developer

Use the 'oc' command line interface:
  $ eval $(crc oc-env)
  $ oc login -u developer https://api.crc.testing:6443
~ : $ oc get crd | grep servicemonitor
servicemonitors.monitoring.coreos.com                             2021-07-22T11:05:33Z
```

[0] https://docs.openshift.com/container-platform/4.4/rest_api/monitoring_apis/servicemonitor-monitoring-coreos-com-v1.html
[1] https://github.com/prometheus-operator/prometheus-operator/blob/master/pkg/apis/monitoring/v1/types.go#L816

**Comment by kenfinnigan** [comment]
Right, I guess my point is that `ServiceMonitor` might be by default available in OpenShift, but it's not specific to OpenShift. I can install the Prometheus operator in vanilla Kubernetes and the `ServiceMonitor` is available.

Fine with closing if this is how it needs to be, it just seemed odd to have non OpenShift specific APIs only available in `OpenShiftClient`

**Comment by rohanKanojia** [comment]
I think you should still be able to use `ServiceMonitor` using KuberntesClient customResource DSL methods. There is also an option to use dynamic client (GenericKubernetesResource) for this as well.

https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#customresource-typed-api
https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#customresource-typeless-api

**Comment by kenfinnigan** [comment]
Thanks for the links @rohanKanojia.

Happy for this to be closed

**Comment by rohanKanojia** [comment]
@kenfinnigan : Do you think providing a Fabric8 Prometheus extension for all resources in `monitoring.coreos.com` apiGroup makes sense? (#2915) . We already have extensions for Knative, Tekton, Service Catalog, CertManager etc.

**Comment by kenfinnigan** [comment]
If there's already groups for other non vanilla Kubernetes bits, it probably makes sense to have one for Prometheus as it's a common piece now
