### ISSUE TITLE
Why does this library hang my program when used in a kotlin coroutine? (Newbie kotlin question)

### ISSUE THREAD

**Issue by blockjon** [fabric8io/kubernetes-client#3382]
I'm learning kotlin and I've created a coroutine that creates a kuberntes pod with fabric8io/kubernetes-client. In my coroutine, I have logic that uses this call:

```
client.pods().inNamespace("mynamespace").create(somePod)
```

The good news is that the kuberntes pod does get created.

For some reason I do not fully understand, something about that line causes my program to ultimately hang. My program does not exit normally. I think it might be hanging on some kind of thread.

I see this in the IntelliJ thread dump:

```
"OkHttp Http2Connection@4284" daemon prio=5 tid=0x14 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
```

Thank you for any help or guidance you can provide.

**Comment by manusa** [comment]
Could you provide a reproducible example?

Where is the client created? OkHttp has a thread pool that is shutdown whenever the client is [closed](https://github.com/fabric8io/kubernetes-client/blob/750faafb50506c1d444409958dec0aca8407dd5c/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BaseClient.java#L72). This process might take some time to complete.

**Comment by manusa** [comment]
https://gitter.im/fabric8io/kubernetes-client?at=61118632025d436054bfb22b
