### ISSUE TITLE
deprecate KubernetesClient.customResource

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3386]
Given the support for genericKubernetesResources, customResources should now be deprecated.

**Comment by manusa** [comment]
I'm not sure I would fully agree on this one in case it refers to the class `CustomResource` and **not** the method [`KubernetesClient#customResources`](https://github.com/fabric8io/kubernetes-client/blob/8d380a350231c7d26710b68f02731659418aa999/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java#L116). (I recall having discussed this elsewhere, but I can't find the reference now.)

CustomResources are treated differently by Kubernetes and have specific areas of the API dedicated to them. They have specific validation, subresources, etc. which might not be shared by the rest of the K8s resources. Through the `CustomResource` class, we're also enforcing users to adopt best practices such as using Spec and Status fields.

Regarding the DSL method(s), they are already deprecated. We should update any documentation, example, quickstart, etc. to use the new methods and remove these methods in a future release after a prudent period.

**Comment by shawkins** [comment]
> Regarding the DSL method(s), they are already deprecated. We should update any documentation, example, quickstart, etc. to use the new methods and remove these methods in a future release after a prudent period.

Sorry, I wasn't specific - KubernetesClient.customResource https://github.com/fabric8io/kubernetes-client/blob/47efc3d7fa473cc2cbe40fe689fe368d4983e18d/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java#L260 is not yet deprecated, it's what I'm referring to here.

**Comment by manusa** [comment]
There's a subtle difference with RawCustomResourceX and GenericKubernetesResource. I'm all in for deprecating, but I would wait for feedback before completely removing it.

**Comment by manusa** [comment]
Fixed by #3395
