### ISSUE TITLE
Watching Pod resources ignores label filters

### ISSUE THREAD

**Issue by armisz** [fabric8io/kubernetes-client#3389]
Hi,
Starting with Kubernetes client version 5.5.0 watching Pods ignores the labels set as filter.

My code is:
```
  public void watchPodsWithLabels(WatchFunction<Pod> watchFunction, Map<String, String> labels) {
    final MixedOperation<Pod, PodList, PodResource<Pod>> pods = openShiftClient.pods();
    if (labels != null && !labels.isEmpty()) {
      log.info("start watching pods with labels {}", labels);
      pods.withLabels(labels);
    }
    final Consumer<Watcher<Pod>> startWatchCommand = pods::watch;
    startWatchCommand.accept(new MyWatcher<>(watchFunction, startWatchCommand));
  }
```

The produced logs reveal that the filter set is not considered when building the request:
```
[2021-08-09 11:39:06,666] [INFO] [main] [{}] [c.a.c.c.s.o.OpenshiftService] - start watching pods with labels {c.c.a.com/kind=something}
[2021-08-09 11:39:06,667] [DEBUG] [main] [{}] [io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager] - Watching https://10.225.0.1/api/v1/namespaces/dev/pods?watch=true
```

In fact, I receive all pods in my namespace, not only the ones having the label set. For some reason using filters work for watching ConfigSets and Secrets, only watching Pods seem to be affected. I think this is a regression.

Please have a look and kind regards
Michael

**Comment by rohanKanojia** [comment]
Could this be a regression due to https://github.com/fabric8io/kubernetes-client/issues/3275 ? Are you able to filter using the new `.withNewFilter().withoutLabels(labels).endFilter()` DSL method?

**Comment by shawkins** [comment]
This is not a regression.  It was a correction to the behavior of the api.  pods.withLabels(labels); - should not modify the current context, it returns a new one - pods = pods.withLabels(labels);

**Comment by armisz** [comment]
Thanks for the heads up. But why does it work for Secrets and ConfigMaps?

**Comment by shawkins** [comment]
> But why does it work for Secrets and ConfigMaps?

It shouldn't.

**Comment by armisz** [comment]
Just for the record: For some reason it does, I have logs for it.

I have now adopted my code to the proposed ` xyz = xyz.withLabels(labels)` pattern. Works fine, thx again!

**Comment by shawkins** [comment]
> Just for the record: For some reason it does, I have logs for it.

If you get a chance, please review the other scenarios - it's the same code path for Pods, Secrets, and ConfigMaps - so it would be surprising if they have different behavior.
