### ISSUE TITLE
wait logic on RollableScalableResource<Deployment>

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3398]
If I do something like:

```
deployment.scale(0, true);
deployment.scale(1, true);
```

The second wait is only checking the replicas, not the available/unavailable replicas.  Is that by design - such that I need to also do deployment.waitUntilReady or should that be handled in the scale call?

**Comment by manusa** [comment]
The problem now is that if we change the behavior, it might affect any user who is actually depending on the current behavior.

If used in combination with deployment#isReady, it should work as you expect, since Readiness **does** check for replica availability.

**Comment by manusa** [comment]
Methods added in #25

**Comment by shawkins** [comment]
Ok, I'll add a javadoc clarifying the meaning of wait.
