### ISSUE TITLE
Use format specifiers for Slf4j logger instead of String concatenation wherever possible

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#3399]
We have some places in code where we're using string concatenation in logging statements. For example here:

https://github.com/fabric8io/kubernetes-client/blob/7d20990da82829dfbc62f9023e2e9ec4541b280d/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L475

Instead of string concatenation, we should use format specifiers instead:
```java
LOGGER.debug("Found service account host and port: {}", hostPort);
```
This is reported as a code smell[0] by sonar and we should try to fix this. You can find all occurrences of LOGGER with string concatenation here[1].

[0] https://sonarcloud.io/organizations/fabric8io/rules?open=java%3AS3457&rule_key=java%3AS3457
[1] https://sonarcloud.io/organizations/fabric8io/issues?projects=fabric8io_kubernetes-client&resolved=false&rules=java%3AS3457

**Comment by kumarav1nash** [comment]
@rohanKanojia you can assign this issue to me, I will work on this issue.

**Comment by param-thakker** [comment]
@rohanKanojia is this still open to work?

**Comment by kumarav1nash** [comment]
@param-thakker I'm working on this
