### ISSUE TITLE
Integrate the client DSL with a mocking framework

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#34]
Ideally one should be able to do:

client.services().inNamespace("default").withName("myservice").get().andReturn(myRef).once();
client.services().inNamespace("default").withName("myservice").get().andReturn(myRef).anyTimes();
client.services().inNamespace("default").withName("myservice").get().andThrow(Error);

client.replay();
//do things with the client
client.verify();

**Comment by jimmidyson** [comment]
@iocanel can we close this now?
