### ISSUE TITLE
Replace C-style array declaration with Java-style array declaration across codebase

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#3400]
We have a few places in code with C-Style array declaration:

https://github.com/fabric8io/kubernetes-client/blob/7d20990da82829dfbc62f9023e2e9ec4541b280d/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/KubernetesVersionExample.java#L26

This is reported as a code smell by sonar. This should be updated to Java-style array declarations for better readability:
```java
  public static void main(String[] args) 
```

You can read more about this Sonar rule here[0].

There are other places in code too where it needs to be updated. You can find all those places listed by sonar here[1]

[0] https://sonarcloud.io/organizations/fabric8io/rules?open=java%3AS1197&rule_key=java%3AS1197
[1] https://sonarcloud.io/organizations/fabric8io/issues?projects=fabric8io_kubernetes-client&resolved=false&rules=java%3AS1197

**Comment by shayaan-absar** [comment]
@rohanKanojia 
Hi, I'm new to opensource and would like to contribute if that's okay.

**Comment by shayaan-absar** [comment]
@rohanKanojia 
Hi, I'm new to opensource and would like to contribute.

**Comment by shayaan-absar** [comment]
@rohanKanojia Which one do I select for type of change?

**Comment by rohanKanojia** [comment]
@shayaan-absar : Sorry, I don't understand. Could you please elaborate your question?

**Comment by shayaan-absar** [comment]
@rohanKanojia When I am opening a pull a request it asks me to select a 'type of change' e.g. Bug fix, feature. I am unsure which one to select.

**Comment by rohanKanojia** [comment]
Umm, this usually counts as a cleanup task. Maybe you can leave box unchecked and check chore box.

**Comment by shayaan-absar** [comment]
@rohanKanojia I've finished the pull request. Is there anything else I need to do?

**Comment by rohanKanojia** [comment]
@shayaan-absar : No, it just needs to be reviewed and merged.

**Comment by ps-19** [comment]
Is this issue resolved?
