### ISSUE TITLE
AbstractCustomResourceHandler: Replace lambda with a method reference.

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#3401]
We have this lambda in AbstractCustomResourceHandler:
https://github.com/fabric8io/kubernetes-client/blob/7d20990da82829dfbc62f9023e2e9ec4541b280d/crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractCustomResourceHandler.java#L74-L78
This can be updated to use method reference instead for better readability:
```java
    Map<String, Property> additionalPrinterColumns = new HashMap<>(additionalPrinterColumnDetector.getProperties());
    additionalPrinterColumns.forEach((path, property) -> {
      Map<String, Object> parameters = property.getAnnotations().stream()
        .filter(a -> a.getClassRef().getName().equals("PrinterColumn")).map(AnnotationRef::getParameters)
        .findFirst().orElse(Collections.emptyMap())
```

**Comment by param-thakker** [comment]
Hi @rohanKanojia, can you please assign this to me? I would love to work on it!

**Comment by aadityasinha-dotcom** [comment]
Is this issue open? 
@rohanKanojia Can I work on this issue?

**Comment by ps-19** [comment]
is this issue resolved?

**Comment by aadityasinha-dotcom** [comment]
@ps-19 I am working on it right now.

**Comment by ps-19** [comment]
I'm always ready to help you. Feel free to ask.

**Comment by aadityasinha-dotcom** [comment]
Sure!!
