### ISSUE TITLE
Unable to get resources from `Handlers.get(kind, apiVersion)`

### ISSUE THREAD

**Issue by Sgitario** [fabric8io/kubernetes-client#3413]
Before `fabric8:kubernetes-client:5.7.0`, we were getting some useful information doing:

```
HasMetadata current = oc.resource(it).fromServer().get();
if (current == null) {
    ResourceHandler<HasMetadata, ?> handler = Handlers.get(it.getKind(), it.getApiVersion());
    if (handler != null && !handler.getApiVersion().equals(it.getApiVersion())) {
        throw new OpenShiftTestException("Couldn't load " + readableKind(it.getKind()) + " '"
                + it.getMetadata().getName() + "' from API server, most likely because"
                + " the 'apiVersion' doesn't match: has '" + it.getApiVersion() + "', but"
                + " should have '" + handler.getApiVersion() + "'");
    }
    throw new OpenShiftTestException("Couldn't load " + readableKind(it.getKind()) + " '"
            + it.getMetadata().getName() + "' from API server");
}
```

More info in: https://github.com/quarkus-qe/quarkus-openshift-test-suite/blob/03313df3b33a2b4e0f1b2725bd207ec5a6414cc2/common/src/main/java/io/quarkus/ts/openshift/common/util/AwaitUtil.java#L72

After 5.7.0, as part of this PR: https://github.com/fabric8io/kubernetes-client/pull/3327, this is no longer possible. 
Do we have some alternatives to get the same data in 5.7.0?

**Comment by shawkins** [comment]
You are looking for cases where the api version of the resource doesn't match the handler?

The handlers are all class based, you can use HasMetadata.getApiVersion(clazz) to know what the api version is expected to be.

Under what circumstances were things not matching?

**Comment by Sgitario** [comment]
Thanks for your reply @shawkins ! Closing
