### ISSUE TITLE
load deplyoment adds additional `additionalProperties` field

### ISSUE THREAD

**Issue by benediktwetzel** [fabric8io/kubernetes-client#3419]
I am trying to load a deployment from a JSON string via the fabric8 Kubernetes client.

```kotlin
        val deploymentString = "{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"finalizers\":[],\"managedFields\":[],\"ownerReferences\":[],\"additionalProperties\":{}},\"spec\":{\"additionalProperties\":{}},\"additionalProperties\":{}}\n"
        val stream =  ByteArrayInputStream(deploymentString.encodeToByteArray())
        val deployment = client.apps().deployments().load(stream).get()
        println(deployment)
```

The result is almost unchanged, but the loaded resource nests the `additionalProperties` further. For example, if the `additionalProperties` field is empty, the loaded resource has the following field: `additionalProperties={additionalProperties={}}`. I  expect this: `additionalProperties={}`.

The full print is: `Deployment(apiVersion=apps/v1, kind=Deployment, metadata=ObjectMeta(annotations=null, clusterName=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels=null, managedFields=[], name=null, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={additionalProperties={}}), spec=DeploymentSpec(minReadySeconds=null, paused=null, progressDeadlineSeconds=null, replicas=null, revisionHistoryLimit=null, selector=null, strategy=null, template=null, additionalProperties={additionalProperties={}}), status=null, additionalProperties={additionalProperties={}})`

Is this correct or a small bug?
`

**Comment by manusa** [comment]
Are you using the Fabric8 provided Serializer??
