### ISSUE TITLE
createOrReplace is used as a replacement for apply, but does not work when replacing

### ISSUE THREAD

**Issue by DimoDonchev** [fabric8io/kubernetes-client#3420]
Should createOrReplace work similar to kubectl apply or kubectl create?

When i try to modify a service with createOrReplace which already exists i get an error:
Message: Service "gateway-external" is invalid: spec.ports[0].nodePort: Invalid value: 32005: provided port is already allocated.
This is the exact same output when I use kubectl create.
Is it possible to simulate kubectl apply via code which would not throw this error but instead would return:
service/gateway-external configured

**Comment by rohanKanojia** [comment]
Relates to #2454 https://github.com/fabric8io/kubernetes-client/issues/3334
