### ISSUE TITLE
Add support for VPA (vertical pod autoscaler)

### ISSUE THREAD

**Issue by matthyx** [fabric8io/kubernetes-client#3430]
Do you think it would make sense to add support for https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler or is it just enough to let people use the [Resource Typed API](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#resource-typed-api) and create their POJOs?

**Comment by matthyx** [comment]
@rohanKanojia what do you think?

**Comment by rohanKanojia** [comment]
@matthyx : Sorry I was on PTO yesterday. I'm not able to find VerticalPodAutoscaler on fresh minikube based kubernetes setup
```
kubernetes-repos : $ kubectl api-resources | grep VerticalPodAutoscaler
kubernetes-repos : $
```

In the repository you linked, I see [vpa-crd.yaml](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/deploy/vpa-crd.yaml#L13) looks like it's a CustomResource.

Do you know if in the future these are going to be moved to [kubernetes/api/autoscaling](https://github.com/kubernetes/api/tree/master/autoscaling) ? If not, I think we can add an extension just like cert-manager.

**Comment by matthyx** [comment]
Indeed it's still an external CR... but documented in [OpenShift](https://docs.openshift.com/container-platform/4.8/nodes/pods/nodes-pods-vertical-autoscaler.html) so an extension it would be.
If nobody else is interested, I can take a look.

**Comment by matthyx** [comment]
btw I have started... you can assign me
