### ISSUE TITLE
Issue with Editable* Resources since 5.7.0

### ISSUE THREAD

**Issue by Fabian-K** [fabric8io/kubernetes-client#3433]
Hi,

with the release 5.7.0, there is an issue with Resources where Editable* are generated for. I think this is basically everything using the model-annotator - e.g. tekton.

Whenever a API URL is constructed, e.g. `io.fabric8.kubernetes.client.dsl.base.OperationSupport.getNamespacedUrl`, the necessary parts are extracted from the annotations like `@Version` or `@Group`. These annotations are part of the entity class. However, when passing an Editable* class (which inherits from the Entity class), these values are null because e.g. HasMetadata.getGroup only checks the annotations on the instance itself and not on superclasses.

Do you think the model-annotator should be updated to not generate the Editable* classes? Should it even be removed and replaced by the annotator that is used for core k8s? (I don´t know the differences between these).

Thanks, Fabian

**Comment by manusa** [comment]
Caused by #3327
