### ISSUE TITLE
Setting User-Agent Header

### ISSUE THREAD

**Issue by lwander** [fabric8io/kubernetes-client#344]
Hey,

Is it possible to set the User-Agent header for requests sent to ones Kubernetes cluster in this API? I'm asking for the purpose of recording usage metrics.

Thanks,
Lars

**Comment by jimmidyson** [comment]
Yeah was thinking of adding that but haven't got around to it. Would be happy for a contribution if you're able - should just be a case of adding option to Config & setting in client create.

**Comment by lwander** [comment]
I'll take a look!
