### ISSUE TITLE
Pod logs for all containers like --all-containers in kubectl

### ISSUE THREAD

**Issue by z0mb1ek** [fabric8io/kubernetes-client#3446]
Hi. How can I get all logs for pod? For example pod with init container and main container. 
May be I can get logs for list of containers in each, but I cannot find any methods to get all containers in pod

**Comment by manusa** [comment]
Relates to #2712

**Comment by z0mb1ek** [comment]
I don't see where I can get containers names for .inContainer() call

**Comment by rohanKanojia** [comment]
I checked and looks like `inContainer` works for both regular containers and initContainers. You can easily get a list of all container names and init container names like this:
```java

    try (KubernetesClient client = new DefaultKubernetesClient()) {
      Pod createdPod = client.pods()
        .load(PodInitContainerGetLog.class.getResourceAsStream("/pod-init-demo.yml"))
        .get();

      List<String> containerNames = createdPod.getSpec().getContainers().stream()
        .map(Container::getName)
        .collect(Collectors.toList());

      List<String> initContainerNames = createdPod.getSpec().getInitContainers().stream()
        .map(Container::getName)
        .collect(Collectors.toList());

    }
```
