### ISSUE TITLE
Mock KubernetesServer not performing cleanup

### ISSUE THREAD

**Issue by kenfinnigan** [fabric8io/kubernetes-client#3461]
When creating pods in the mock server with `mockServer.getClient().pods().create(pod1)`, deleting them at the end of a test with `mockServer.getClient().pods().delete()` does not result in the pods being removed in subsequent tests.

**Comment by shawkins** [comment]
What version is this on?  Older versions of the mock logic had an issue with inferring the namespace of the object created.  That was addressed by #3156.  This works fine on latest from what I can tell.

**Comment by kenfinnigan** [comment]
5.6.0 of the fabric8 client

**Comment by rohanKanojia** [comment]
I'm not able to reproduce this. I tried adding a new test case to PodCrudTest like this but it is passing for me:
```java
  @Test
  void testDeleteActuallyRemovesPods() {
    // Given
    Pod pod1 = new PodBuilder().withNewMetadata().withName("pod1").addToLabels("testKey", "testValue").endMetadata().build();

    // When
    client.pods().inNamespace("foo").create(pod1);
    client.pods().inNamespace("foo").withName("pod1").delete();

    // Then
    assertNull(client.pods().inNamespace("foo").withName("pod1").get());
  }
```

Would appreciate it if we could get some more information.

**Comment by kenfinnigan** [comment]
@rohanKanojia does your example use the mock server? It looks like it's using the actual client

**Comment by rohanKanojia** [comment]
PodCrudTest is using `@EnableKubernetesMockClient` annotation which initializes mock server and client automatically:

https://github.com/fabric8io/kubernetes-client/blob/2dbfe29926cf25285ad1fb3bda2318afdf2d0f31/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodCrudTest.java#L41-L45

**Comment by kenfinnigan** [comment]
Thanks @rohanKanojia 

The main difference I see is that I didn't delete a specific pod, but all pods with:
```
mockServer.getClient().pods().delete();
```

Is that the problem? I need to delete the pods by name?

**Comment by shawkins** [comment]
Under the covers pods().delete() will perform a list and delete each individually.

**Comment by kenfinnigan** [comment]
Is there a problem with how I create the pod?

I've used `mockServer.getClient().pods().create(pod1);`

**Comment by rohanKanojia** [comment]
If you don't specify namespace Kubernetes Mock Server assumes namespace to be test(This is done in order to mock default context behavior we have in `.kube/config` files):

https://github.com/fabric8io/kubernetes-client/blob/2dbfe29926cf25285ad1fb3bda2318afdf2d0f31/kubernetes-client/src/test/java/io/fabric8/kubernetes/server/mock/KubernetesMockServer.java#L77-L85

Anyway, even if I trim namespace test is passing:
```java
  @Test
  void testDeleteActuallyRemovesPods() {
    // Given
    Pod pod1 = new PodBuilder().withNewMetadata().withName("pod1").addToLabels("testKey", "testValue").endMetadata().build();

    // When
    client.pods().create(pod1);
    client.pods().delete();

    // Then
    assertNull(client.pods().withName("pod1").get());
  }
```
I think if you check logs of test maybe they can provide some insight on what namespace is getting picked by tests:
```
[INFO] Running io.fabric8.kubernetes.client.mock.PodCrudTest
Sep 14, 2021 9:48:59 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[39897] starting to accept connections
Sep 14, 2021 9:48:59 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[48149] starting to accept connections
Sep 14, 2021 9:49:00 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[48149] received request: POST /api/v1/namespaces/test/pods HTTP/1.1 and responded: HTTP/1.1 200 OK
Sep 14, 2021 9:49:00 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[48149] received request: GET /api/v1/namespaces/test/pods HTTP/1.1 and responded: HTTP/1.1 200 OK
Sep 14, 2021 9:49:00 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[48149] received request: DELETE /api/v1/namespaces/test/pods/pod1 HTTP/1.1 and responded: HTTP/1.1 200 OK
Sep 14, 2021 9:49:00 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[48149] received request: GET /api/v1/namespaces/test/pods/pod1 HTTP/1.1 and responded: HTTP/1.1 404 Client Error
Sep 14, 2021 9:49:00 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections

```

**Comment by rohanKanojia** [comment]
ohk, I am able to reproduce this issue with the test shown below. I've prepared a reproducer project https://github.com/rohankanojia-forks/fabric8-k8s-client-mockwebserver-issue3461-reproducer (which is based on v5.6.0). I'm also able to reproduce this on master.

```java
  @Test
  void testDeleteAllPodsInDifferentNamespaces() {
    // Given
    Pod pod1 = new PodBuilder().withNewMetadata().withName("p1").addToLabels("testKey", "testValue").endMetadata().build();
    Pod pod2 = new PodBuilder().withNewMetadata().withName("p2").addToLabels("testKey", "testValue").endMetadata().build();
    Pod pod3 = new PodBuilder().withNewMetadata().withName("p3").addToLabels("testKey", "testValue").endMetadata().build();
    client.pods().inNamespace("ns1").create(pod1);
    client.pods().inNamespace("ns2").create(pod2);
    client.pods().inNamespace("ns3").create(pod3);

    // When
    client.pods().delete();
    PodList ns1Pods = client.pods().inNamespace("ns1").list();
    PodList ns2Pods = client.pods().inNamespace("ns2").list();
    PodList ns3Pods = client.pods().inNamespace("ns3").list();

    // Then
    assertTrue(ns1Pods.getItems().isEmpty());
    assertTrue(ns2Pods.getItems().isEmpty());
    assertTrue(ns3Pods.getItems().isEmpty());
  }
```

**Comment by rohanKanojia** [comment]
Sorry, false alarm. `client.pods().delete()` would delete pods in all namespaces only when there is no namespace set in Config(In case of mockwebserver, it's always `test`. It's done to mock having namespace set in current context of `.kube/config`:
```yaml
contexts:
- context:
    cluster: api-sandbox-test-com:6443
    namespace: rokumar-dev
    user: rokumar/api-sandbox-test-com:6443
  name: rokumar-dev/api-sandbox-test-com:6443/rokumar
current-context: rokumar-dev/api-sandbox-test-com:6443/rokumar
```

In the case of mockwebserver, the namespace set would be always `test`. In order to delete pods in all namespaces, this should always work:
```java
client.pods().inAnyNamespace().delete();
```

**Comment by kenfinnigan** [comment]
@rohanKanojia that seems to work for most tests, but I did hit one error.

I happened to notice that any watcher I installed with `client.pods().inAnyNamespace().watch(podWatcher)` is not removed with the delete.

Is there a way to remove a watcher?

**Comment by shawkins** [comment]
Watches require an explicit close.  If the client is closed that should do it as well.

**Comment by kenfinnigan** [comment]
By "explicit close", do you mean calling `onClose()` for the watcher? Or another way to close the watcher, as I can't find anything obvious?

**Comment by rohanKanojia** [comment]
I think he's referring to watcher.close() method. Something like this:

https://github.com/fabric8io/kubernetes-client/blob/04e0b2e2530751c90aeb9c0465ad3219c46a636f/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java#L148-L158

**Comment by kenfinnigan** [comment]
Thank you!

I'd completely missed there was a `Watch` instance I could capture that had the `close()` on it!

All seems good now, thanks again for the help
