### ISSUE TITLE
How to mock pod metrics?

### ISSUE THREAD

**Issue by kenfinnigan** [fabric8io/kubernetes-client#3467]
Is there a way to mock the data for pod metrics such that calling:
```
client.top().pods().metrics("namespace", "pod").getContainers()
```

will return valid metrics?

I've tried this:
```
ContainerMetrics containerMetrics1 = new ContainerMetricsBuilder().withUsage(Map.of("cpu", new Quantity("2m"))).build();
PodMetrics metrics1 = new PodMetricsBuilder()
                .withNewMetadataLike(pod1.getMetadata()).endMetadata()
                .withContainers(containerMetrics1)
                .build();

mockServer.getClient().top().pods().inNamespace("test").withName("my-pod-1").metric().setContainers(List.of(containerMetrics1));
```

but it fails with:
```
2021-09-14 09:04:18,885 INFO  [okh.moc.MockWebServer] (MockWebServer /127.0.0.1:50133) MockWebServer[50129] received request: GET /apis/metrics.k8s.io/v1beta1/namespaces/test/pods/my-pod-1 HTTP/1.1 and responded: HTTP/1.1 404 Client Error
```

**Comment by manusa** [comment]
I'd doubt if this could be mocked using CRUD (which is what I assume you're trying to accomplish here). This could be implemented as an extra-feature in the mockserver by providing some additional handlers (I think).

The metrics are obtained querying the metrics-server's custom HTTP endpoints (i.e. they are not resources->~~REST~~).

However, it should be possible  to do using the non-CRUD mode.

**Comment by kenfinnigan** [comment]
So there's no way to "fake" metrics in a mock situation to verify internals read metrics properly?

If so, that's fine, just want to make sure I'm not doing something wrong and it should work

**Comment by z-dian** [comment]
hello,i'm doing the saming things like you , i want to get the pods metrics in java, to use it in other ways ,can you tell me ,what should i do?
