### ISSUE TITLE
Make it possible to customize Informer Cache key function 

### ISSUE THREAD

**Issue by lburgazzoli** [fabric8io/kubernetes-client#3472]
The `Cache` class - which is  one of the implementation of the Store interface - has an options to configure the key and index function: 

https://github.com/fabric8io/kubernetes-client/blob/04e0b2e2530751c90aeb9c0465ad3219c46a636f/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Cache.java#L61

Which by default are based on metadata name and namespace:

https://github.com/fabric8io/kubernetes-client/blob/04e0b2e2530751c90aeb9c0465ad3219c46a636f/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/Cache.java#L57-L59

The default key function uses a mix of `instanceOf` and reflection to extract the `namespace` and `name` from a given object and then concatenate the extracted values to create a key which seems inefficient when the type is know  thus, it would be nice to let developers be able to provide custom key function (in addition to the index one) i.e. by using the object UID as a key or by not using any reflection/instanceof. 

As an additional note: while working on the java-operator-sdk, I was trying to understand how complex it would be to replace the custom cache the operator sdk provides with an informer and one of the issues I found was the need to adapt between the behavior of the cache implementations provided by the two projects as:

- the java-operator-sdk uses object's UID as a key for the cache
- the fabric8 client uses namespace + name as a key (as stated before)

I think it would be possible to adapt the java-operator-sdk to adopt the same behavior of the fabric8 client but IMHO, it would be very nice if the fabric8 client would provide a way to customize its cache behavior as it would ease the integration.

**Comment by shawkins** [comment]
A proposal would be to add Informable.withKeyFunction(function) and Informable.withNamespaceIndex(boolean)

**Comment by shawkins** [comment]
@lburgazzoli see if #3472 is roughly what you need.

It might be a good idea to capture what else you may be looking for in terms of control over the cache - such as locking, using a disk backed store, etc.?  Or do you think that the current simple ConcurrentHashMap implementation will suffice?

**Comment by lburgazzoli** [comment]
> @lburgazzoli see if #3472 is roughly what you need.
> 

It seems to be what I need. Thank you very much


> It might be a good idea to capture what else you may be looking for in terms of control over the cache - such as locking, using a disk backed store, etc.? Or do you think that the current simple ConcurrentHashMap implementation will suffice?

I don't have yet an idea but as you suggested, having some locking mechanism (maybe provided as a decorated cache/store) seems reasonable and useful. An off-heap backed-store would probably also be something to explore.

**Comment by shawkins** [comment]
> I don't have yet an idea but as you suggested, having some locking mechanism (maybe provided as a decorated cache/store) seems reasonable and useful. An off-heap backed-store would probably also be something to explore.

What I'm thinking is that if you need even more customization, then the Cache or a Store should be pluggable rather than focusing on the individual options.

**Comment by shawkins** [comment]
The questions from https://github.com/fabric8io/kubernetes-client/pull/3943#issuecomment-1067962930 would be applicable here.  It's not completely clear what the usage scenario for the usage of the cache / events.  If needed we can separate out the changes from that pr that add uid as an option for the key function.
