### ISSUE TITLE
Version 5.7 transitive dependency issue

### ISSUE THREAD

**Issue by pmbsa** [fabric8io/kubernetes-client#3475]
Hi, I just uplifted to version 5.7(3) from 5.6. I Appear to have a problem with the common-model dependency that is coming through the transitive dependencies  is on 4.4.1 which doesnt have all the required classes for the new version of the api. I am not sure if there is something specific to my environment that is causing this, it seems strange that it isnt causing everybody an issue but I thought I would raise it just in case.

thanks
Paul

**Comment by rohanKanojia** [comment]
Do you think your issue is similar to https://github.com/fabric8io/kubernetes-client/issues/3436 ?

**Comment by manusa** [comment]
The model module structure has changed since 4.4.1, please review that the artifacts you depend on still exist or have been renamed.

**Comment by pmbsa** [comment]
I can see the model structures have changes yes. thats why I am querying what is happening. The issue sound similar to  #3436 BUT I can confirm that there are NO fabric8 dependencies in the project until I add the kubernetes-client. There is no spring-cloud usage at all for sure and if I remove the kubernetes-client from the pom I can see all fabric8 resources removed.

Its easy enough to fix with an exclusion but I thought it was curious none the less.. Its very possible its something to do with me working from within a Bank which has its own complex means of getting dependencies from mvn. If nobody else is having this issue I am happy to assume that is the case.

**Comment by yougogirl** [comment]
I have this issue with 5.8.0 as well. If there are no other dependencies in the project, all the kubernetes-model-* jars are all on 5.8.0 whereas when there are many other dependencies, the kubernetes-model-* dependencies fall back to 4.13.3

As you say, when I remove the kubernetes-client dependency from the pom, none of these are imported. The moment I bring in 5.8.0 in one particular project, such overriding imports happen.
