### ISSUE TITLE
Move Kubernetes Assertions to Fabric8 Kubernetes Client

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#3494]
I would like to propose moving Kubernetes Assertions(https://github.com/fabric8io/kubernetes-assertions) module into Fabric8 Kubernetes Client.

This module was earlier located in Fabric8 Platform repository: https://github.com/fabric8io/fabric8/tree/v3.0.12/components/kubernetes-assertions . I found out about this due to a [twitter conversation](https://twitter.com/jvanzyl/status/1230476204353970182?s=20) where  I realized this was buried beneath already archived fabric8 platform repository. At that time, I had created a new repository under fabric8io organization and updated it to latest kubernetes-client at that time and created a new release. But now it's outdated again and we need to update it as per latest kubernetes-client. 

It would be better if we move it to this repository since it already contains other testing utilities like kubernetes-server-mock. This way this repository would serve as an umbrella for all Java things around Kubernetes.

**Comment by manusa** [comment]
Is this still interesting?
Is someone interested in this feature?

**Comment by rohanKanojia** [comment]
I don't think anyone is interested.
