### ISSUE TITLE
Error when upload file to container

### ISSUE THREAD

**Issue by vmasyagin** [fabric8io/kubernetes-client#3497]
Good afternoon.
```xml
<dependency>
	<groupId>io.fabric8</groupId>
	<artifactId>kubernetes-client</artifactId>
	<version>5.8.0</version>
</dependency>
```
Good afternoon, trying to upload a file to a container like this:
```java
io.fabric8.kubernetes.client.Config config = new ConfigBuilder()
                .withMasterUrl(String.format("https://%s:%s/", namespace.getHost(), namespace.getPort()))
                .withTrustCerts(true)
                .withOauthToken(namespace.getToken())
                .build();
        try (KubernetesClient k8s = new DefaultKubernetesClient(config)) {
            File fileToUpload = new File(srcFile);
            k8s.pods().inNamespace(namespace.getName())     // <- Namespace of Pod
                    .withName(pod)                 // <- Name of Pod
                    .inContainer(container)        //
                    .dir(targetFile)               // <- Path of directory inside Pod
                    .upload(fileToUpload.toPath());       // <- Local Path of directory
        }
```
Please tell me what could be the cause of the following error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: io/fabric8/kubernetes/model/annotation/Group
	at io.fabric8.kubernetes.api.model.HasMetadata.getGroup(HasMetadata.java:89)
	at io.fabric8.kubernetes.client.dsl.base.ResourceDefinitionContext.fromResourceType(ResourceDefinitionContext.java:51)
	at io.fabric8.kubernetes.client.ResourceHandlerImpl.<init>(ResourceHandlerImpl.java:43)
	at io.fabric8.kubernetes.client.Handlers.register(Handlers.java:42)
	at io.fabric8.kubernetes.client.BaseKubernetesClient.<clinit>(BaseKubernetesClient.java:129)
	at ru.diasoft.micro.iaas.service.ContainerProviderImpl.main(ContainerProviderImpl.java:151)
Caused by: java.lang.ClassNotFoundException: io.fabric8.kubernetes.model.annotation.Group
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 6 more
```

**Comment by manusa** [comment]
The stacktrace seems to report that there's something wrong with your dependencies.

Please check if you have any additional k8s client dependency that was forgotten. You might also want to clear your local .m2 repo for the client (io/fabric8/...)

**Comment by vmasyagin** [comment]
Yes, I also have the following dependencies connected:
<code>
<dependency>
	<groupId>io.kubernetes</groupId>
	<artifactId>client-java</artifactId>
	<version>13.0.0</version>
</dependency>
<dependency>
	<groupId>io.fabric8</groupId>
	<artifactId>openshift-client</artifactId>
	<version>5.8.0</version>
</dependency>
<code>

**Comment by vmasyagin** [comment]
Clearing of local .m2 repo for the client (io/fabric8/...) didn't help. Removed from dependencies openshift-client, the result is the same. Is there a way to make both clients friends in one project?

**Comment by rohanKanojia** [comment]
Does it work when you try having all `io.fabric8:kubernetes-client`, `io.fabric8:openshift-client` and official client dependencies? I don't remember if I also tried with openshift-client but I was able to get both clients working in same project for some demo project[0]

[0] https://github.com/rohanKanojia/fabric8-official-java-client-comparison/blob/master/pom.xml

**Comment by vmasyagin** [comment]
The problem is that one of the libraries had a dependency on io.fabric8:openshift-client version 4.9.1. I changed the version to 4.9.1 in my project and the problem went away. But there is one peculiarity. If I upload a text file with the content "My file", then a file with the content "My fil" arrives in the container. That is, the last letter disappears. Is this a known bug of version 4.9.1 or am I doing something wrong?

**Comment by vmasyagin** [comment]
I raised the io.fabric8:openshift-client version in the library to version 5.8.0, raised the io.fabric8:kubernetes-client version in the program to 5.8.0 and again I get the problem described at the very beginning. The fabric8 local repository cleaned up, re-downloaded. Any thoughts what might be wrong now?

**Comment by rohanKanojia** [comment]
It's a bit difficult to find out just from the error. Would it be possible for you to share some public project which has the same configuration and reproduces issue?
