### ISSUE TITLE
Support IPv6 based clusters

### ISSUE THREAD

**Issue by ctron** [fabric8io/kubernetes-client#3499]
According to issue #2632, there seems not to be any support for IPv6 based clusters.

I think there should be. Simply to kill the argument of "Java can't work Kubernetes properly, let's use Go for operators".

Issue #2632 proposes do switch to okhttp4, which seems to have some implication. However, I think there be some solution to this issue. If this is #2632, or  #2764, some something else! Maybe okhttp3 can be fixed? I don't know, I just think that the fabric8 client should work on as many Kubernetes configurations as possible!

**Comment by rohanKanojia** [comment]
In past, we had submitted PR[0] for hostname fix to okhttp3 but it wasn't accepted(https://github.com/fabric8io/kubernetes-client/issues/2632#issuecomment-748434878). I think our only option is to move away from okhttp to some other library.

[0] https://github.com/square/okhttp/pull/6483

**Comment by manusa** [comment]
You can replace the OkHttp 3 dependency with OkHttp 4 and it should do the trick.

**Comment by manusa** [comment]
In any case, yes we need to move away from OkHttp and provide a robust, open, and sutainable solution.
