### ISSUE TITLE
on windows if we can't find ~/.kube we should look in %HOMEDRIVER%\%HOMEPATH%

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/kubernetes-client#350]
which seems to be where oc.exe puts things

see thread:
https://groups.google.com/forum/#!topic/fabric8/7Iq4NQo2twY

**Comment by jimmidyson** [comment]
That is annoying... maybe we can try that location too...

**Comment by jmandawg** [comment]
Well, this is the actual logic for taken from origin source @ "\origin-1.1.4\Godeps\_workspace\src\k8s.io\kubernetes\pkg\util\homedir\homedir.go":

You prob just want to duplicate that code when searching for ~/.kube/config

// HomeDir returns the home directory for the current user
func HomeDir() string {
	if runtime.GOOS == "windows" {
		if homeDrive, homePath := os.Getenv("HOMEDRIVE"), os.Getenv("HOMEPATH"); len(homeDrive) > 0 && len(homePath) > 0 {
			homeDir := homeDrive + homePath
			if _, err := os.Stat(homeDir); err == nil {
				return homeDir
			}
		}
		if userProfile := os.Getenv("USERPROFILE"); len(userProfile) > 0 {
			if _, err := os.Stat(userProfile); err == nil {
				return userProfile
			}
		}
	}
	return os.Getenv("HOME")
}

**Comment by jimmidyson** [comment]
@jmandawg We'd love a PR to fix this if you're up for it. None of us run windows so easier for you to test :) I reckon we should replace the `tryKubeConfig` with this exact logic (unless the path is overridden via `KUBECONFIG` env var).

**Comment by jmandawg** [comment]
Here is a patch, i tested on windows with no issues.  Basically just a port of their method. 

[config.patch.txt](https://github.com/fabric8io/kubernetes-client/files/199861/config.patch.txt)
