### ISSUE TITLE
java.lang.NoClassDefFoundError: io/fabric8/kubernetes/internal/KubernetesDeserializer

### ISSUE THREAD

**Issue by joshiste** [fabric8io/kubernetes-client#3500]
With 5.8.0 running on OSGI we get a NoClassDefFoundError.

The `io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperationsImpl` from the `kubernetes-client` module is referencing the `io.fabric8.kubernetes.internal.KubernetesDeserializer` class from the `kubernetes-model-core` module which declares the package `io.fabric8.kubernetes.internal` as private and doesn't export it.

```

java.lang.NoClassDefFoundError: io/fabric8/kubernetes/internal/KubernetesDeserializer                                                                                                                                   
     at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperationsImpl.<init>(HasMetadataOperationsImpl.java:62)                                                                                                    
     at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperationsImpl.<init>(HasMetadataOperationsImpl.java:39)                                                                                                    
     at io.fabric8.kubernetes.client.ResourceHandlerImpl.operation(ResourceHandlerImpl.java:70)                                                                                                                          
     at io.fabric8.kubernetes.client.Handlers.getOperation(Handlers.java:65)                                                                                                                                             
     at io.fabric8.kubernetes.client.Handlers.getNonListingOperation(Handlers.java:69)                                                                                                                                   
     at io.fabric8.kubernetes.client.V1AuthorizationAPIGroupClient.selfSubjectAccessReview(V1AuthorizationAPIGroupClient.java:40)

```

**Comment by hakontro** [comment]
@manusa did you investigate this? I'm seeing a similar issue when trying to run a Spark 3.2.0 cluster on Openshift.
```
java.lang.NoClassDefFoundError: Could not initialize class io.fabric8.kubernetes.internal.KubernetesDeserializer
jdk.internal.reflect.GeneratedConstructorAccessor49.newInstance(Unknown Source) java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
```

**Comment by rohanKanojia** [comment]
@hakontro @hanneshofmann @joshiste : How can I reproduce this issue? I'm trying to load a Deployment YAML with `client.apps().deployments().load(...)` in but it's passing for me.

**Comment by hakontro** [comment]
@rohanKanojia What openshift version are you on? I think it's related to a version issue between openshift and the 5.4.1 client (for me at least)

**Comment by rohanKanojia** [comment]
I'm trying to reproduce this issue via a unit test in https://github.com/fabric8io/kubernetes-client/blob/master/platforms/karaf/itests/src/test/java/io/fabric8/kubernetes/karaf/itests/KubernetesDeserializerTest.java

I'm on master branch

**Comment by joshiste** [comment]
@rohanKanojia Ok just found out, that the KubernetesDeserializerTest (in master) is using the kubernetes-client-5.11.1-bundle.jar and not the kubernetes-client-5.11.1.jar 

the key difference is that the former has osgi statements in the manifest as the latter has not - may be that's the difference here?

**Comment by rohanKanojia** [comment]
@joshiste : Umm, you're right, I'm able to see `KubernetesDeserializer.class` in `kubernetes-client-5.12-SNAPSHOT-bundle.jar` but not in `kubernetes-client-5.12-SNAPSHOT.jar`.

Does that mean that your issue gets resolved if you switch to bundle jar?

**Comment by joshiste** [comment]
I guess so, but still have to test...

**Comment by rohanKanojia** [comment]
@hakontro @hanneshofmann : Would it be possible for you to try out using `kubernetes-client-*-bundle.jar` instead of `kubernetes-client*.jar` to see if it resolves your issue?

https://github.com/fabric8io/kubernetes-client/blob/7f76db5f80e8a824526a5e83e2938c259c904776/platforms/karaf/itests/pom.xml#L36-L41

**Comment by rohanKanojia** [comment]
@hakontro @hanneshofmann @joshiste : polite ping, Did anyone get any chance to test with kubernetes client bundle jar to see if it resolved the issue? Would appreciate it if we could get feedback on this.

**Comment by hanneshofmann** [comment]
Sorry - I am currently OOO and I don't have access to any machine to test it. As far as I recall, we used the bundle jar back then when the issue has occured. I will try to verify this once again at the beginning of next week.

**Comment by hakontro** [comment]
I'll get it tested on Monday, thanks for looking into it!

**Comment by rohanKanojia** [comment]
@joshiste @hakontro @hanneshofmann : polite ping Did you get some time to test with bundle jar?

Apologies for these annoying pings. I hope this is the last one :pray:

**Comment by hakontro** [comment]
Tried it out now, doesn't seem to affect the issue in my case. Np about the pings, thanks for taking the time anyways!

**Comment by rohanKanojia** [comment]
I see. Let me prepare a seprate reproducer project to reproduce the issue.

**Comment by hanneshofmann** [comment]
Same for me. Even when using the bundle version, the exception occurs at runtime.

From an OSGi point of view the issue seems to be clear: bundle A (client jar) uses a class (deserializer) from bundle B (model jar) which is not exported/imported properly. Because the import cannot be resolved at runtime, the exception is raised by the JVM.

To check why the existing integration test is passing successfully, it could be helpful to verify the class loader (I assume it is using a shared class loader whereas each bundle has its own in an OSGi environment).

**Comment by rohanKanojia** [comment]
Hello guys, I have tried preparing a reproducer project https://github.com/rohankanojia-forks/kubernetes-client-osgi-demo . Basically, I'm just creating a Book custom resource. I'm sure control that goes through HasMetadataOperationsImpl and custom resource class is registered via KubernetesDeserializer

```java
  public void createBook() {
    try (KubernetesClient client = new DefaultKubernetesClient()) {
      MixedOperation<Book, BookList, Resource<Book>> fooClient = client.customResources(Book.class, BookList.class);
      Book foo = fooClient.load(getClass().getResourceAsStream("/test-foo.yml")).get();
      foo.getMetadata().setName("book" + count);
      fooClient.inNamespace("default").createOrReplace(foo);
    }
  }
```

I deployed this application to Kubernetes using Kubernetes Maven Plugin where it's run in a Karaf based image:
```sh
$ eval $(minikube -p minikube docker-env)
$ mvn k8s:build k8s:resource k8s:apply
...
$ kubectl get pods
NAME                                          READY   STATUS    RESTARTS   AGE
kubernetes-client-osgi-demo-db47c6f76-p77zm   1/1     Running   0          14s
```

As expected I was able to see Book resources being created every second:
```
kubernetes-client-osgi-demo : $ kubectl get book -w
NAME     AGE
book1    49s
book10   4s
book2    44s
book3    39s
book4    34s
book5    29s
book6    24s
book7    19s
book8    14s
book9    9s
book11   0s
book12   0s
```

Could you please check if I have prepared the reproducer correctly :pray: ? It could be possible that I have missed something since I'm not familiar with OSGi.

**Comment by hanneshofmann** [comment]
Thanks a lot for the sample project, @rohanKanojia.  

I cloned the source and tinkered around with it: it seems to be working. Though, I am not very confident that the sample project is exactly behaving as "OSGi" - but to be fair, I cannot tell why. I was modifying the source to directly import and initialize a class from a non-imported bundle packages, e.g.:
-  add `io.fabric8.kubernetes.internal.KubernetesDeserializer.registerCustomKind(null, null, null);` to `K8sBookGenerator#createBook`

This should result in the mentioned exception given that the package `io.fabric8.kubernetes.internal` is not exported by the `kubernetes-model-core` bundle, but the method could be executed.

I cannot promise that I manage to do it but I try my best to provide an executable reproduction project (maybe tomorrow).

**Comment by rohanKanojia** [comment]
@hanneshofmann : Thanks a lot for your quick response :pray:

When I add this line to `createBook` method and deploy application to minikube using kubernetes maven plugin. I see this in my logs:

`mvn k8s:log`
```
[INFO] k8s: java.lang.NullPointerException: null
[INFO] k8s: 	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:?]
[INFO] k8s: 	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:?]
[INFO] k8s: 	at io.fabric8.kubernetes.internal.KubernetesDeserializer$Mapping.registerKind(KubernetesDeserializer.java:239) ~[!/:?]
[INFO] k8s: 	at io.fabric8.kubernetes.internal.KubernetesDeserializer.registerCustomKind(KubernetesDeserializer.java:133) ~[!/:?]
[INFO] k8s: 	at org.eclipse.jkube.quickstart.karaf.K8sBookGenerator.createBook(K8sBookGenerator.java:42) ~[!/:?]
[INFO] k8s: 	at org.eclipse.jkube.quickstart.karaf.K8sBookGenerator.generateOrder(K8sBookGenerator.java:31) ~[!/:?]
[INFO] k8s: 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[INFO] k8s: 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
[INFO] k8s: 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[INFO] k8s: 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
[INFO] k8s: 	at org.apache.camel.util.ObjectHelper.invokeMethodSafe(ObjectHelper.java:2111) ~[!/:2.25.1]
[INFO] k8s: 	at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:483) ~[!/:2.25.1]
[INFO] k8s: 	at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:302) ~[!/:2.25.1]
[INFO] k8s: 	at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:275) ~[!/:2.25.1]
[INFO] k8s: 	at org.apache.camel.component.bean.AbstractBeanProcessor.process(AbstractBeanProcessor.java:198) ~[!/:2.25.1]
[INFO] k8s: 	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:53) ~[!/:2.25.1]
[INFO] k8s: 	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [!/:2.25.1]
[INFO] k8s: 	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [!/:2.25.1]
[INFO] k8s: 	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [!/:2.25.1]
[INFO] k8s: 	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [!/:2.25.1]
[INFO] k8s: 	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [!/:2.25.1]
[INFO] k8s: 	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197) [!/:2.25.1]
[INFO] k8s: 	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79) [!/:2.25.1]
[INFO] k8s: 	at java.util.TimerThread.mainLoop(Timer.java:556) [?:?]
[INFO] k8s: 	at java.util.TimerThread.run(Timer.java:506) [?:?]

```

**Comment by hanneshofmann** [comment]
Yes - I see the same exception and I think is expected. It essentially means that the JVM is executing `KubernetesDeserializer.registerCustomKind` and the internal logic causes the NPE (as we are passing null values to the method). 

The "OSGi behaviour" would be that the JVM is throwing `java.lang.NoClassDefFoundError: io/fabric8/kubernetes/internal/KubernetesDeserializer` because the class should not be in the bundle's class loader. As mentioned in the previous comment, I will try my best to sketch an example production project soon.

**Comment by rohanKanojia** [comment]
@hanneshofmann : Which OSGi framework are you using? Can I try running this application there?

**Comment by hanneshofmann** [comment]
Originally, we discovered this issue with Karaf 4.2.x but I was also able to reproduce it back then with Felix as well. At the moment, I unfortunately have nothing to share.

**Comment by sunix** [comment]
hello.
Looking at @rohanKanojia example,
`io/fabric8/kubernetes/internal/KubernetesDeserializer.class`
in `./target/features-repo/io/fabric8/kubernetes-model-core/5.11.2/kubernetes-model-core-5.11.2.jar`
but also
in `./target/features-repo/io/fabric8/kubernetes-client/5.11.2/kubernetes-client-5.11.2-bundle.jar`

Looking at the MANIFEST.MF, the package `io.fabric8.kubernetes.internal` is exported in  `kubernetes-client-5.11.2-bundle.jar` but not in `kubernetes-model-core-5.11.2.jar` (marked as private-package).

In my opinion, by chance our karaf example is picking the one in `kubernetes-client-5.11.2-bundle.jar` where it is trying to pick it from kubernetes-model-core-5.11.2.jar in @joshiste and @hanneshofmann  cases somehow.

**Comment by sunix** [comment]
what you could try is to use `kubernetes-client-5.11.2-bundle.jar` but not the other kubernetes client modules.

**Comment by manusa** [comment]
Is this issue still applicable in version 6.x?

**Comment by happyzzz1997** [comment]
In version 6.8.1, the same issue exists. This method does not work.`<bundle>wrap:mvn:io.fabric8/kubernetes-model-core/6.8.1$Export-Package=io.fabric8.kubernetes.internal,*;version="6.8.1"&amp;Private-Package=schema,&amp;overwrite=merge</bundle>
`

**Comment by manusa** [comment]
> In version 6.8.1, the same issue exists. This method does not work.`<bundle>wrap:mvn:io.fabric8/kubernetes-model-core/6.8.1$Export-Package=io.fabric8.kubernetes.internal,*;version="6.8.1"&amp;Private-Package=schema,&amp;overwrite=merge</bundle> `

Hi @happyzzz1997,
Could you please create a new issue with all details that apply to your project.
It would be good if you could also provide a minimal reproducer project so that we can actually check what's going on.
