### ISSUE TITLE
kubernetes-client-5.8.0.jar has /OSGI-INF with osgi data but the META-INF/MANISFEST.MF file is almost empty

### ISSUE THREAD

**Issue by joshiste** [fabric8io/kubernetes-client#3503]
For me it looks like the kubernetes-client-5.8.0.jar should be an OSGI compatible jar (as it has some services in /OSGI) but its manifest is almost empty:

```
Manifest-Version: 1.0
Build-Jdk-Spec: 1.8
Created-By: Maven Jar Plugin 3.2.0
```

**Comment by joshiste** [comment]
Marking it as stale won't make the bug disappear. I'm looking into providing a PR for this.

**Comment by rohanKanojia** [comment]
@joshiste : Are you working on this issue? If not, I can try fixing this issue.

**Comment by joshiste** [comment]
Ok just found out that there is the normal jar and the bundle-jar for the client. One with all the OSGI info and one without. Does anyone know why there is this distinction?

**Comment by rohanKanojia** [comment]
Umm, not sure. Tracing back the commit which changed the packaging to `jar` from `bundle` https://github.com/fabric8io/kubernetes-client/commit/35dc05cfb93a0df5871f09ce406683712c3389b0

**Comment by manusa** [comment]
Is this issue still applicable?
