### ISSUE TITLE
OpenShift >4.8 model update and compatibility matrix update

### ISSUE THREAD

**Issue by AbrahamArellano** [fabric8io/kubernetes-client#3505]
Hi team,

I would like to request the upgrade of the openshift-client to support OpenShift 4.8 and the upcoming 4.9 API model.

We tested successfully (only basic object creation) the current library with **OpenShift 4.7**, however, the documented **supportability matrix** only confirms the tests until **OpenShift 4.5**.

Thanks

**Comment by rohanKanojia** [comment]
I'm using OpenShift 4.9.8 and I was only able to see these two additional resources which were not mentioned in #2949:
```
NAME                      APIVERSION              NAMESPACED   KIND

egressrouters     network.operator.openshift.io        true         EgressRouter
apirequestcounts  apiserver.openshift.io               false        APIRequestCount
```

I'll submit a PR for updating existing OpenShift Model deps to latest version and add support for these new resources to OpenShiftClient DSL
