### ISSUE TITLE
Request to extend model to cover ACM

### ISSUE THREAD

**Issue by AbrahamArellano** [fabric8io/kubernetes-client#3506]
Hi team,

I would like to request the extension of the model to cover also Advanced Cluster Management. Currently our team is using the library in order to deploy clusters with ACM and it was required to extend the model to some of the following objects:
- ClusterDeployment
- ClusterDeploymentControlPlaneConfig
- ClusterDeploymentPlatform
- InstallConfig
- ManagedCluster
- etc.

In addition, would it be ideal to take advantage of the different functions available out of the box by RHACM as Java methods:
https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.3/html-single/apis/index#rhacm-docs_apis_cluster_jsoncreatecluster

Thanks

**Comment by rohanKanojia** [comment]
@AbrahamArellano : The resource URL doesn't look like it follows standard Kubernetes API (`/apis/{group}/{version}/{plural}`) convention:
```
create()        POST /cluster.open-cluster-management.io/v1/managedclusters
get()           GET /cluster.open-cluster-management.io/v1/managedclusters/{cluster_name}
list()          GET /cluster.open-cluster-management.io/v1alpha1/managedclustersets
delete()        DELETE /cluster.open-cluster-management.io/v1/managedclusters/{cluster_name}
```

Are the abovementioned objects custom resources? I installed Cluster manager and klusterlet on my OpenShift cluster but these were the only additional resources in `operator.open-cluster-management.io/v1` apigroup:
```sh
kubernetes-client : $ kubectl api-resources | grep open-cluster
clustermanagers                                        operator.open-cluster-management.io/v1        false        ClusterManager
klusterlets                                            operator.open-cluster-management.io/v1        false        Klusterlet
```

**Comment by AbrahamArellano** [comment]
Hi @rohanKanojia , the challenge here is to use the library to operate with the ACM API, and in order to create managed clusters, delete them and so on, we need the capabilities to create those entities in OpenShift.
For that the ACM API describes the objects we would need.
https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.3/html-single/apis/index#rhacm-docs_apis_cluster_jsoncreatecluster

**Comment by rohanKanojia** [comment]
@AbrahamArellano : Thanks for your reply. I have created a draft PR(https://github.com/fabric8io/kubernetes-client/pull/3641) for [Open Cluster Management](https://open-cluster-management.io/) extension which provides support for the following resources provided in https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.3/html/apis/apis

- ManagedCluster `cluster.open-cluster-management.io/v1`
- ManagedClusterSet  `cluster.open-cluster-management.io/v1beta1`
- ManagedClusterSetBinding `cluster.open-cluster-management.io/v1beta1`
- Channel `apps.open-cluster-management.io/v1`
- Subscription `apps.open-cluster-management.io/v1`
- PlacementRule  `apps.open-cluster-management.io/v1`
- Application `app.k8s.io/v1beta1`
- HelmRelease `apps.open-cluster-management.io/v1`
- Policy `policy.open-cluster-management.io/v1`
- MultiClusterObservability `observability.open-cluster-management.io/v1beta2`
- SearchCustomization `search.open-cluster-management.io/v1alpha1`
- MultiClusterHub `operator.open-cluster-management.io/v1`
- Placements API `cluster.open-cluster-management.io/v1alpha1`
- PlacementDecisions API `cluster.open-cluster-management.io/v1alpha1`
- DiscoveryConfig `discovery.open-cluster-management.io/v1alpha1`
- DiscoveredCluster `discovery.open-cluster-management.io/v1alpha1`

Would appreciate if you could find time to try it out and provide feedback if there is something that needs to be added.
