### ISSUE TITLE
Need examples on Openshift client

### ISSUE THREAD

**Issue by pgandhap** [fabric8io/kubernetes-client#3507]
Hi everyone , 

In the Kubernetes-client code there are many examples for kubernetes-client ( like pods , services , replication controller , jobs etc., )  . But coming to openshift there are only few examples (i.e, to create deployment and one more example for replication controller ) . Iam looking more examples under openshift like to create Jobs under namespaces , HorizontalPodAutoscaler ,Persistent volume etc., and more advanced concepts  for openshift . Can anyone share more examples on OpenShift Client .....

**Comment by manusa** [comment]
There are lot's of examples here:

https://github.com/fabric8io/kubernetes-client/tree/master/kubernetes-examples/src/main/java/io/fabric8/openshift/examples
