### ISSUE TITLE
Provide a callback handler for ssl cert handling

### ISSUE THREAD

**Issue by jcantrill** [fabric8io/kubernetes-client#353]
When connecting to a cluster, the trustmanager may not have the proper certs to allow the connection.  Currently, the configuration only allows trust all or none.  We can provide a  way for the user of the client to be able to callback and ask if a connection is trusted.  In jbosstools we do this by presenting the user with a dialog.  Something like https://github.com/openshift/openshift-restclient-java/blob/master/src/main/java/com/openshift/internal/restclient/http/UrlConnectionHttpClient.java#L372  which has been in place since the openshift v2 client.

**Comment by jimmidyson** [comment]
The configuration allows for specifying a trusted CA certificate via `ConfigBuilder.withCaCertData` or `ConfigBuilder.withCaCertFile`. The use of a callback in this case is really only any good for interactive sessions which this client is a bit low level for using directly. I personally would expect a wrapper that catches the cert exception, presents any dialogue that you need & the reconfigure the client with the appropriate CA cert (or disable cert checks).

However, I'm not averse to having this callback if you think it has wider value than a single use case.

**Comment by jcantrill** [comment]
@jimmidyson I think this usecase is probably only applicable to interactive sessions.  I can envision how we might utilize it in a wrapper around this client so if we think it would be better placed there, I can be talked down from my very short horse

**Comment by jimmidyson** [comment]
Let's go for the wrapper. If you need any more info in the thrown exception let me know & we can add in as required. Sound OK?
