### ISSUE TITLE
Not identifying ECDSA client key when configured with `Config.fromKubeconfig`

### ISSUE THREAD

**Issue by rnorth** [fabric8io/kubernetes-client#3535]
I'm wondering if I might be using the library wrong, but I'm encountering an issue:

* When obtaining a `Config` object using `Config.fromKubeconfig`, where the config data is sourced from a YAML string; and
* when the config YAML data includes an ECDSA client key

It appears that the client key is being misidentified as RSA by the fabric8 client. A repro example may be informative: https://github.com/testcontainers/testcontainers-java/pull/4582/files#diff-13f914d232c020ecc4968745d184ef069d9ef0fc522eaa37342d8de96f503b19R35. in this code, if `config.setClientKeyAlgo("EC");` is removed, the client will consistently fail with `java.io.IOException: Invalid DER: object is not integer`.

From what I can tell:
* The `Config` class's `getKeyAlgorithm` method ought to be able to identify the key type correctly
* However, `getKeyAlgorithm` is only called via `configFromSysPropsOrEnvVars`, which in turn is called by `autoConfigure`.
* The only time `autoConfigure` is invoked is when instantiating a `Config` object initially; this happens _before_ the provided YAML kubeconfig contents is applied.
* Thus the `Config` object continues to default to RSA, when the actual key data is for an ECDSA key

i.e. (comments mine):
```
  public static Config fromKubeconfig(String context, String kubeconfigContents, String kubeconfigPath) {

    Config config = new Config(); // <-- this is the only place from which getKeyAlgorithm is ultimately invoked

    if(kubeconfigPath != null)
      config.file = new File(kubeconfigPath);

    loadFromKubeconfig(config, context, kubeconfigContents); // <-- this is where the provided kubeconfigContents is applied - too late for the key algorithm to be correctly updated

    return config;
  }
```

**Comment by MUzairS15** [comment]
@manusa I am able to reproduce the problem by creating a kubeconfig yaml with EC as key algorithm and also figured out that if in https://github.com/fabric8io/kubernetes-client/blob/9c766ffd82248a861845a0d36f2116b91f1221b8/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L589 
along with assignig details such as `setCaCertFile` `setClientCertFile` `setClientCertData` and others we need to setClientKeyAlgo as well otherwise it continue to be RSA scheme. So can you assign me this issue?

**Comment by MUzairS15** [comment]
Can anyone assign me this issue?

**Comment by MUzairS15** [comment]
Can anyone review PR raised for this issue https://github.com/fabric8io/kubernetes-client/pull/3581#issue-1050900951
