### ISSUE TITLE
Move apiversion getter to common interface

### ISSUE THREAD

**Issue by jcantrill** [fabric8io/kubernetes-client#354]
Currently all resources have a 'getApiVersion' but they method signature is not common to all of them.

**Comment by jimmidyson** [comment]
Adding `String HasMetadata.getApiVersion()` would make most sense but would mean we had to change all our versions from enums to Strings. I'm happy to do that as long as we accept that this is a breaking change, although considering the fact that there is only one API version for each resource type atm I doubt anyone actually wants to override the API version yet.

**Comment by jimmidyson** [comment]
@iocanel Any thoughts?

**Comment by jimmidyson** [comment]
I've made the necessary changes to the model, all works fine. Now we just need to decide if we can accept the breaking change... I personally can live with it.

**Comment by jimmidyson** [comment]
OK without any discussion I'm going to do it :-b Updated model already, releasing then will update the client soonish.
