### ISSUE TITLE
Minor Code Refactor Issue) Using `Math.max` ​​instead of the ternary operator 

### ISSUE THREAD

**Issue by heesuk-ahn** [fabric8io/kubernetes-client#3546]
## Refactoring Suggestions 

Looking at the code, there is a very small refactorable issue, so I suggest the following. :)

If we use `Math.max` instead of the `ternary operator`, we can express this code more intuitively.

https://github.com/fabric8io/kubernetes-client/blob/04e0b2e2530751c90aeb9c0465ad3219c46a636f/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/DefaultSharedIndexInformer.java#L193

```
    return Math.max(desired, check);
```

**Comment by manusa** [comment]
Fixed in #3556
