### ISSUE TITLE
URLUtils.isValidURL

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3548]
In this method there's a check of if the string form contains the string null, presumably to guard against null concatenation.  However in general it's quite possible for the string "null" to appear in a valid URL.

https://github.com/fabric8io/kubernetes-client/blob/d1740ffeaa624bd63b6d929b25d764a477c1c17e/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/URLUtils.java#L151

**Comment by manusa** [comment]
To be clear, the only thing you should remove is the `url.contains("null")` check, the rest should stay.

**Comment by manusa** [comment]
@MUzairS15  are you working on this and going to provide a PR?

**Comment by rohanKanojia** [comment]
Looks like @MUzairS15 had created PR but didn't link the issue https://github.com/fabric8io/kubernetes-client/pull/3558

**Comment by MUzairS15** [comment]
Sorry @manusa I didn't mention the issue, thankyou @rohanKanojia for mentioning
