### ISSUE TITLE
When I run the Prometheus command, I get a 404.

### ISSUE THREAD

**Issue by ho-yasla** [fabric8io/kubernetes-client#3551]
![image](https://user-images.githubusercontent.com/92026433/138984323-ef23b7f7-41b1-499a-b24b-904615ad77e8.png)

![image](https://user-images.githubusercontent.com/92026433/138984382-e690415b-46ca-44ca-9fd0-d8a441537fe1.png)

When I run the Prometheus command, I get a 404.

**Comment by manusa** [comment]
Can this be closed (#3538 was fixed)?
