### ISSUE TITLE
How to resolve "Timeout: Too large resource version" In Java client ?

### ISSUE THREAD

**Issue by kkkkun** [fabric8io/kubernetes-client#3552]
We has a problem. It has fixed in kubernetes https://github.com/kubernetes/kubernetes/issues/91073 
How to fix same question In Java

**Comment by kkkkun** [comment]
> However our implementation never attempts to list with a resourceVersion, so you should never get a Too large resource version result at that point.

If the Java reflector doesn't list with a resourceVersion, The client would not get 'Too Large resourceVersion'.
If so, the issue will be closed. and client not do anything change.

**Comment by shawkins** [comment]
> If so, the issue will be closed. and client not do anything change.

Okay, I see this exception won't occur on the watch, so yes it won't happen in the client currently.  Only if we start allowing listing and the informer list to use the resourceVersion will this become a concern.  Marking as closed for now.
