### ISSUE TITLE
OkHttp connection leak on retries within OperationSupport.retryWithExponentialBackoff

### ISSUE THREAD

**Issue by ahus1** [fabric8io/kubernetes-client#3561]
I received the following log messages in my current project, after enabling `kubernetes.request.retry.backoffLimit`. Before that, I saw 500 responses from the Kubernetes API while I was overloading it with requests.

```
A connection to *** was leaked. Did you forget to close a response body?

java.lang.Throwable: response.body().close()
	at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:149) ~[okhttp-3.14.9.jar:?]
	at okhttp3.internal.connection.Transmitter.callStart(Transmitter.java:116) ~[okhttp-3.14.9.jar:?]
	at okhttp3.RealCall.execute(RealCall.java:78) ~[okhttp-3.14.9.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.retryWithExponentialBackoff(OperationSupport.java:591) ~[kubernetes-client-5.9.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:564) ~[kubernetes-client-5.9.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:527) ~[kubernetes-client-5.9.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleDelete(OperationSupport.java:295) ~[kubernetes-client-5.9.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.deleteThis(BaseOperation.java:619) ~[kubernetes-client-5.9.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:535) ~[kubernetes-client-5.9.0.jar:?]
```

I tracked this down to the following code snippet in [OperationSupport.java](https://github.com/fabric8io/kubernetes-client/blob/51475cd8e5ce997211dda223ac9cb782205ce4be/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java#L586-L609). 

On retry, the previous response body isn't closed before the next retry starts. See code nippet below, with necessary additions marked with `NEW CODE START` and `NEW CODE END`.

I'd be happy to create a PR, at the same time I'm unsure how to write a unit test for this. Please advise how to write a unit test for this, or if you would be willing to accept a unit test without additional tests.

```
        if (numRetries < requestRetryBackoffLimit && response.code() >= 500) {
          retryInterval = retryIntervalCalculator.getInterval(numRetries);
          LOG.debug("HTTP operation on url: {} should be retried as the response code was {}, retrying after {} millis", request.url(), response.code(), retryInterval);
          // NEW CODE START
          if(response.body() != null) {
            response.body().close();
          }
          // NEW CODE END
        } else {
          return response;
        }
```

**Comment by shawkins** [comment]
Given that @manusa will be cutting a release soon, it would be best to just open a PR with this fix and not worry about the test, so it can be included in 5.10.  

I had come to the same conclusion about this in the refactoring to support replacing okhttp - https://github.com/shawkins/kubernetes-client/blob/okhttp/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java#L578  My intention was to address that and several other related issues - namely that the httpclients created by utils / interceptors are not properly closed - and backkport the fix to master.  However I didn't make it around to that yet.

**Comment by ahus1** [comment]
I double checked with the current employer/project setup; will be difficult to check all the boxes in the PR template regarding license. 

Will have a different setup next year, I can then backport your changes, and check all the other relevant boxes in the PR template. Sorry for that.

**Comment by shawkins** [comment]
Here's the backport of just the code changes - https://github.com/fabric8io/kubernetes-client/pull/3565

@manusa can you see about including that in 5.10?

**Comment by manusa** [comment]
This was reported in other sections.
Any Response should be accessed in a try-with-resources block to make sure it gets closed even if the body is never accessed:
```
try (Response response = client.newCall(request).execute()) {
// ...
```

**Comment by shawkins** [comment]
> Any Response should be accessed in a try-with-resources block to make sure it gets closed even if the body is never accessed

The way the code is structured means that there isn't a single try block for this - you can end up retrying the request multiple times, then finally returning the one that succeeds.  If we want something that looks more like a try / catch we'll need to refactor.

With the okhttp refactoring I see that the Java client does not seem to share a similar concern about how resources are held.  The code in that branch now resembles the java 11 client - the expectation is that if you return a InputStream or Reader that you are responsible for calling close on those.  The notion of closure with okhttp is actually quite complex - see https://square.github.io/okhttp/3.x/okhttp/index.html?okhttp3/ResponseBody.html - that list off all of the possible ways in which a response is closed.  I can add back an HttpResponse.close if needed, but I liked the simplicity of this approach.

**Comment by manusa** [comment]
> Here's the backport of just the code changes...

> With the okhttp refactoring I see that the Java client does not seem...

I didn't understand the "backport" part, I get it now. OK, let's merge your patch.
