### ISSUE TITLE
Add support for Volcano extension

### ISSUE THREAD

**Issue by Yikun** [fabric8io/kubernetes-client#3579]
Volcano is a Kubernetes native system for high-performance workloads, which has been accepted by Cloud Native Computing Foundation (CNCF) as its first and only official container batch scheduling project.

There were some initial discussion on https://github.com/fabric8io/kubernetes-client/issues/3043 .

This issue would be a start and help to track the process on Volcano extension.

[1] https://volcano.sh/en/
[2] https://github.com/volcano-sh/volcano/issues/1825

**Comment by rohanKanojia** [comment]
Related to #3043 #2920
