### ISSUE TITLE
Use SharedIndexInformer with CustomResource

### ISSUE THREAD

**Issue by nautiam** [fabric8io/kubernetes-client#3585]
Hello,

I wrote the watching for CustomResource. At first, I used Watcher, but I got the error "Kubernetes too old resource version". Then, I referred this thread https://stackoverflow.com/questions/61409596/kubernetes-too-old-resource-version to use **SharedIndexInformer**, but the method _**sharedIndexInformerForCustomResource()**_ is deprecated in openshift-client 5.9.0. Can anyone show me an example to watching CustomResource event?

```
SharedInformerFactory sharedInformerFactory = openShiftClient.informers();
SharedIndexInformer<GenericKubernetesResource> podInformer = sharedInformerFactory.sharedIndexInformerForCustomResource(context, 30 * 1000L);
...
```

Thanks,

**Comment by shawkins** [comment]
You will either use SharedInformerFactory.sharedIndexInformerFor(clazz ...

Or if you are customizing the context, instead use Informable.inform - which is available off of the regular dsl:

client.resources(clazz)...inform

**Comment by rohanKanojia** [comment]
From user's @nautiam snippet, it doesn't look like he is using any POJO for his custom resource. I think he is using [sharedIndexInformerForCustomResource(ResourceDefinitionContext genericResourceContext, long resyncPeriodInMillis)](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/SharedInformerFactory.java#L174)

Why was this method marked Deprecated? As far as I remember idea was to deprecate all methods which involve OperationContext as parameter but I don't see it here.

**Comment by shawkins** [comment]
> it doesn't look like he is using any POJO for his custom resource

Sorry, I should have included:

client.genericKubernetesResources(context)...inform

> Why was this method marked Deprecated?

We don't want to expose the OperationContext for direct usage.  It also gets confusing in terms of keeping track of existing informers.

**Comment by manusa** [comment]
> client.genericKubernetesResources(context)...inform

If this is not in the cheatsheet, maybe we should update it.

**Comment by nautiam** [comment]
I used SharedInformer in order to update events happening to my resource after a certain interval of time. But it always get  the status of all resources, I just want to see the status of changed resources since the last time. For example, if a resource is deleted or added, it will be shown, but if it unchanged in the interval, it will be skipped. Is there anyway to do it?

**Comment by nautiam** [comment]
> I used SharedInformer in order to update events happening to my resource after a certain interval of time. But it always get the status of all resources, I just want to see the status of changed resources since the last time. For example, if a resource is deleted or added, it will be shown, but if it unchanged in the interval, it will be skipped. Is there anyway to do it?

The answer is set resync to 0L. Thanks @rohanKanojia for your help.
```
kubernetesClient.genericKubernetesResources(context).inNamespace("default").inform(new ResourceEventHandler<GenericKubernetesResource>() {
                @Override
                public void onAdd(GenericKubernetesResource genericKubernetesResource) {

                }

                @Override
                public void onUpdate(GenericKubernetesResource genericKubernetesResource, GenericKubernetesResource t1) {

                }

                @Override
                public void onDelete(GenericKubernetesResource genericKubernetesResource, boolean b) {

                }
            }, 0);
```
