### ISSUE TITLE
openshift-server-mock not listed in dependencyManagement in main pom

### ISSUE THREAD

**Issue by ahus1** [fabric8io/kubernetes-client#3588]
The main pom.xml (in the root folder of the project, with `<artifactId>kubernetes-client-project</artifactId>` contains in almost all modules provided by this project. In our setup we use this for the dependency management: 

```
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.fabric8</groupId>
        <artifactId>kubernetes-client-project</artifactId>
        <version>${version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
 ```

I found that this doesn't work for getting the right version of `openshift-server-mock` as this is not listed in the `dependencyManagement` section of the `kubernetes-client-project`'s pom.xml.

I therefore ask for it to be added (and maybe other modules that might be missing - haven't checked yet). 

The workaround for us is to add the `openshift-server-mock` as an explicit dependency in the dependency-management.

**Comment by manusa** [comment]
https://github.com/fabric8io/kubernetes-client/blob/865e0ddf67b99f954aa55ab14e5806d53ae149ec/pom.xml#L369

**Comment by ahus1** [comment]
After #2108 being implemented, the code has changed, and I wonder if using `kubernetes-client-project` for dependency management was intended in the first place. 

There doesn't seem to be a true `bom` dependency (at least not any more).

Closing this issue.

**Comment by manusa** [comment]
I'm reopening because so far this is the only bom-like module we have.
