### ISSUE TITLE
Golang generator does not support interfaces

### ISSUE THREAD

**Issue by Sgitario** [fabric8io/kubernetes-client#3591]
The golang generator for extensions used to map Golang model to Java model is not working when Golang model contains interfaces. For example, given the Golang model:

Go type `Tracing_CustomTag` that uses a field `Type` which is an interface `isTracing_CustomTag_Type`:
```go
type Tracing_CustomTag struct {
	Type                 isTracing_CustomTag_Type `protobuf_oneof:"type"`
}
```

Where the interface is defined in:

```go
type isTracing_CustomTag_Type interface {
	isTracing_CustomTag_Type()
	MarshalTo([]byte) (int, error)
	Size() int
}
```

The implementations of this interface are defined in:

```go
type Tracing_CustomTag_Literal struct {
	Literal *Tracing_Literal `protobuf:"bytes,1,opt,name=literal,proto3,oneof" json:"literal,omitempty"`
}
type Tracing_CustomTag_Environment struct {
	Environment *Tracing_Environment `protobuf:"bytes,2,opt,name=environment,proto3,oneof" json:"environment,omitempty"`
}
type Tracing_CustomTag_Header struct {
	Header *Tracing_RequestHeader `protobuf:"bytes,3,opt,name=header,proto3,oneof" json:"header,omitempty"`
}
```

When running the go generator against a model that contains interfaces, the command fails with `No type mapping found for XXX`.

**Comment by metacosm** [comment]
Note that both this issue and #3592 are addressed by the generator used by https://github.com/snowdrop/istio-java-api

**Comment by manusa** [comment]
Can this one be closed now?

**Comment by Sgitario** [comment]
Yes, sorry. The PR was not linked.
