### ISSUE TITLE
`waitUntilReady` leaves watches/websocket open upon timeout

### ISSUE THREAD

**Issue by rnorth** [fabric8io/kubernetes-client#3598]
It appears that `waitUntilReady` for a Pod will leave a Watch, and therefore websocket connection, open if the Pod fails to become ready in time. This can lead to a buildup of open websocket connections to the k8s API, and eventually resource exhaustion.

We've not dug into every nuance, but in our usage we are deleting the pod after the timeout occurs. The watch seems to remain open despite both the timeout and the deletion.

One workaround seems to be to use a custom Watcher, and manually ensure that the ensuing `Watch` is closed when a failure occurs.

**Comment by shawkins** [comment]
What version of fabric8 is this on?

**Comment by rnorth** [comment]
We've observed this with 5.9.0 and 5.7.2.

**Comment by shawkins** [comment]
Under the covers the logic should terminate the informer / watch when the future completes - https://github.com/fabric8io/kubernetes-client/blob/278ca235dc4ab5653e82dbe2960004ab62f021e4/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java#L881

However I do see that the cancel is being applied to the wrong future.  I've opened a pr for this.

**Comment by rnorth** [comment]
Aha, great, thank you @shawkins
