### ISSUE TITLE
if using kubernetes (and not openshift) then we need to use a different URL to access templates / buildconfigs

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/kubernetes-client#36]
so kubernetes does not have templates or buildconfigs. So right now we have a shim service to implement those entities in a service called 'templates'
https://github.com/fabric8io/quickstarts/blob/master/apps/templates/src/main/java/io/fabric8/templates/TemplatesService.java#L60

so if not on openshift; we need to not use this:
```
        config.setOpenShiftUrl(config.getMasterUrl() + "oapi/" + config.getOapiVersion() + "/");
```
but something like
```
        config.setOpenShiftUrl(config.getMasterUrl() + "api/" + config.getApiVersion() + "proxy/namespaces/default/services/templates/oapi/" + config.getOapiVersion() + "/");
``` 
etc

**Comment by jimmidyson** [comment]
We should expose the kubernetes & openshift api prefixes to config builder so this can be overridden. Please don't default these in the client depending on environment.

**Comment by jstrachan** [comment]
so you'd rather things just not work OOTB on kubernetes?

**Comment by jimmidyson** [comment]
IMO this is sugar for fabric8 specific functionality, not a generic reusable Java client.

**Comment by jstrachan** [comment]
The KubernetesClient supports Templates and BuildConfigs which are never gonna work on vanilla kubernetes right? So the client should have some ability to map the openshift URIs to something that might actually have a chance of working on vanilla kubernetes - which means either totally replacing openshiftUrl or defining some prefix to add before the `/oapi` part of the path. 

I'm all for letting the user of the client configure these things explicitly. Plus having an environment variable folks can use to default the non-openshift URL to use for openshift resources. 

However it would really help if there was a sensible OOTB default so that things just worked without us having to litter throughout the fabric8 code explicit configuration for non-openshift client usage - provided a service is running with some canonical name (e.g. its `templates` today - happy to switch that to any name that makes you more happy).

e.g. I'd like kubernetes-client to default; if not an openshift environment, to using a proxy service URL to access templates / buildConfigs and other OS resources to delegating to a k8s service; with the name of that service to come from an environment variable with some default (that fabric8 can then implement).

The converse is not pleasant. e.g. configuring the kubernetes client in a maven plugin in a jenkins build job inside jenkins pod in either kubernetes or openshift is not an easy thing to configure. Having a sensible default seems to make sense. 

e.g. use an env var for the name of the kubernetes service to delegate to for openshift APIs sounds a reasonable OOTB behaviour. Clients can always completely configure the exact openshiftUrl or openshiftUrlPrefix or openshiftApiServiceName or whatever - while still having things that mostly work OOTB

**Comment by jimmidyson** [comment]
How about having a factory class in fabric8 to do the configuration? Just don't see it being part of a generic client. But off on holiday now so do whatever you like ;)

**Comment by jstrachan** [comment]
I don't grok why openshiftUrlPrefix and openshiftApiServiceName can't be 2 more properties on Config like all the others and have sensible defaults; then users can configure anything they want - but things can have sensible OOTB defaults too

**Comment by iocanel** [comment]
Since we already have the distinction between KubernetesClient and OpenshiftClient I think that Templates should move from the KubernetesClient to the OpenshiftClient.

Each client type should have its own ConfigBuilder with each own uniqueue options. 

If we feel that we need to support hybrid env, then we should hack a hybrid/composite client, rather than spoiling our default client impl.
