### ISSUE TITLE
How to update a Knative Service?

### ISSUE THREAD

**Issue by CWL-1688** [fabric8io/kubernetes-client#3622]
> I have created a Knative Service using Knative extension

```java
 HashMap<String, String> annoMap = new HashMap<>();
        annoMap.put("autoscaling.knative.dev/minScale","3");
        Container container = new Container();
        container.setImage("quay.io/rhdevelopers/knative-tutorial-greeter:quarkus");
        io.fabric8.knative.serving.v1.Service service = new ServiceBuilder()
                .withNewMetadata()
                .withName("greeter-10")
                .withNamespace("default")
                .endMetadata()
                .withNewSpec()
                .withNewTemplate()
                .withNewMetadata()
                .withAnnotations(annoMap)
                .endMetadata()
                .withNewSpec()
                .withContainers(container)
                .endSpec()
                .endTemplate()
                .endSpec().build();
        knativeClient.services().create(service);
```

> Everything worked correctly so far
>
> I want to update this Service , like set the minScale = 3 
>
> How should I do?

**Comment by rohanKanojia** [comment]
Do you mean you want to update the annotation value? Could you please try this:
```java
knativeClient.services()
  .inNamespace("default")
  .withName("greeter-10")
  .edit(s -> new ServiceBuilder(s)
    .editMetadata()
    .withAnnotations(Collections.singletonMap("autoscaling.knative.dev/minScale","3"))
    .endMetadata()
    .build());
```

**Comment by CWL-1688** [comment]
Sorry that I  didn't make myself clear.

What I want is
update the  annotation value under **spec.template.metadata.annotations** 
 Or put a new annotation "autoscaling.knative.dev/minScale","1" , to set the min Pod of Service

Following your advice 

```java
 void testScale(){
        io.fabric8.knative.serving.v1.Service service = knativeClient.services().inNamespace("default").withName("greeter-10").get();
        log.warn(JSONUtil.toJsonPrettyStr(service));
        knativeClient.services()
                .inNamespace("default")
                .withName("greeter-10")
                .edit(s -> new ServiceBuilder(s)
                        .editMetadata()
                        .withAnnotations(Collections.singletonMap("autoscaling.knative.dev/minScale","1"))      // update Service, set  minScale from 3 -> 1
                        .endMetadata()
                        .build());
    }
```

I got this

>  Failure executing: PATCH at: http://192.168.1.33:8443/apis/serving.knative.dev/v1/namespaces/default/services/greeter-10. Message: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: annotation value is immutable: metadata.annotations.serving.knative.dev/creator
invalid key name "autoscaling.knative.dev/minScale": metadata.annotations
autoscaling annotations must be put under "spec.template.metadata.annotations" to work
invalid value: : metadata.annotations.serving.knative.dev/lastModifier. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: annotation value is immutable: metadata.annotations.serving.knative.dev/creator
invalid key name "autoscaling.knative.dev/minScale": metadata.annotations
autoscaling annotations must be put under "spec.template.metadata.annotations" to work
invalid value: : metadata.annotations.serving.knative.dev/lastModifier, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
