### ISSUE TITLE
How does withPath() match a regular link?

### ISSUE THREAD

**Issue by SaturnWorld** [fabric8io/kubernetes-client#3626]
Hi! I'm using KubernetesMockServer,like this:

`KubernetesMockServer server = new KubernetesMockServer(false);`
`server.expect().get().withPath("/api/v1/users/user_id").andReturn(200, "admin").once();`

But user_id is a variable value, what am I supposed to do with it?

Does the withPath() method support passing regularity like this?

`server.expect().get().withPath("/api/v1/users/.*").andReturn(200, "admin").once();`

**Comment by manusa** [comment]
Could you share more details about your test?

If you are testing something concrete, I don't understand why you would need a variable there.
