### ISSUE TITLE
WatcherWebSocketListener causes NullPointerException in OperationSupport

### ISSUE THREAD

**Issue by JoergSiebahn** [fabric8io/kubernetes-client#3629]
### Describe the bug

When `WatcherWebSocketListener` pushes an Exception in `onFailure` [for 200 or 503](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatcherWebSocketListener.java#L74) it passes `null` as `status` to `OperationSupport#requestFailure`. 

The parameter `status` [is not checked for `null`](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java#L688) in `OperationSupport`.

That leads to a `NullPointerException` instead of a `KubernetesClientException`.

### Fabric8 Kubernetes Client version

5.10.1@latest

### Steps to reproduce

It is hard to describe how to reproduce the bug as it is an implementation detail. I realized it first in unit tests when upgrading `io.javaoperatorsdk:operator-framework` from 1.9.0 to 1.10.0 and `io.fabric8:kubernetes-server-mock` from 5.4.1 to 5.10.1.

But also without describing how to reproduce, the linked code in `WatcherWebSocketListener` and `OperationSupport` should shows that it can't work.

### Expected behavior

A `KubernetesClientException` is returned from `OperationSupport#requestFailure`.

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

macOS

### Fabric8 Kubernetes Client Logs

```shell
java.lang.NullPointerException
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:688)
	at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.onFailure(WatcherWebSocketListener.java:69)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Additional context

Running in unit test with `io.fabric8:kubernetes-server-mock:5.10.1`.

Independent from this bug report, my assumption is that something in the requests to the Kubernetes API changed and the mocked responses are not valid in my test case any more. My operator implementation does not show this behavior in an E2E test with Kind. However, the NPE will be thrown whenever this code is reached although that may never be the case in real world scenarios.

**Comment by manusa** [comment]
Fixed by #3631
