### ISSUE TITLE
Cannot create informers to capture the pod metrics

### ISSUE THREAD

**Issue by vegoutha** [fabric8io/kubernetes-client#3639]
Tried to create informer with resource object `PodMetrics` and observed the below error:

**Code Snippet:**
```
 client.get.resources(classOf[PodMetrics]).inform()
```

**Error message:**
```
Failure executing: GET at: https://localhost:5125/apis/metrics.k8s.io/v1beta1/namespaces/default/podmetrics. 

Message: the server could not find the requested resource. 
```

Listed the api-resources with APIVERSION "metrics.k8s.io/v1beta1":
```
nodes                                          metrics.k8s.io/v1beta1                 false        NodeMetrics
pods                                           metrics.k8s.io/v1beta1                 true         PodMetrics
```

GET URL is supposed to be `https://localhost:5125/apis/metrics.k8s.io/v1beta1/namespaces/default/pods`

@rohanKanojia Please let me know how to capture the pod metrics using informers.

**Comment by shawkins** [comment]
@vegoutha it looks like the metadata for pod and node metrics is not correct as it's just using the default plural.  The workaround would be to use generic logic:

client.genericKubernetesResources(new ResourceDefintionContext.Builder().withGroup("metrics.k8s.io").withVersion("v1beta1").withPlural("pods").withNamespaced(true).build()).inform

You can convert between a GenericKubernetesResource and PodMetrics by using Serialization.jsonMapper().convertValue(genericResource, PodMetrics.class) or just use the generic.

**Comment by manusa** [comment]
https://github.com/fabric8io/kubernetes-client/issues/3639#issuecomment-989868438

Does this actually work?

Metrics HTTP API is not standard, I wasn't sure that this could actually work.

**Comment by shawkins** [comment]
> Does this actually work?

It should, or at least it will hit the endpoint he is wanting to.

There reason that informers don't work here is that they are pulling the plural from the class.  Regular node/pod metric operations are working because the plural is being passed via the *OperationImpl.

**Comment by vegoutha** [comment]
Thanks @shawkins . Workaround provided in the above comment https://github.com/fabric8io/kubernetes-client/issues/3639#issuecomment-989868438 works for me.

**Comment by shawkins** [comment]
Also related to this is that NodeMetrics is currently marked as Namespaced, and it should not be.
