### ISSUE TITLE
How to mock `writingErrorChannel`?

### ISSUE THREAD

**Issue by benediktwetzel** [fabric8io/kubernetes-client#3644]
For testing, we need to mock the exec command like this: 

```Kotlin
server
    .expect()
    .withPath("/api/v1/namespaces/test/pods/pod1/exec?command=ls&stdout=true&stderr=true")
    .andUpgradeToWebSocket()
        .open(OutputStreamMessage("Test-Output"))
        .done()
    .always()
```

But we also need to mock the result of the `.writingErrorChannel()` and `.writingOutput()` functions to be able to mock the exit code of a command. How is this possible?

In the following code example only the ByteArrayOutputStream `out` is not empty.

```Kotlin
var out: ByteArrayOutputStream = ByteArrayOutputStream()
var error: ByteArrayOutputStream = ByteArrayOutputStream()
var errChannelStream: ByteArrayOutputStream = ByteArrayOutputStream()

 client.pods()
     .inNamespace(client.namespace)
     .withName("pod1")
     .writingOutput(out)
     .writingError(error)
     .writingErrorChannel(errChannelStream)
     .exec("ls")
```

**Comment by davinkevin** [comment]
I have almost the same requirement, but only for exit code. I didn't found in the codebase example or code allowing to provide an `exec` returned-code to the mock-server.

**Comment by SoerenHenning** [comment]
I haven't tested this, but when looking at this blog post by Red Hat [Executing commands in Pods using K8s API (Communication protocol)](https://cloud.redhat.com/blog/executing-commands-in-pods-using-k8s-api) and the source code of [ExecWebSocketListener#onMessage](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java#L234), it looks like the first byte in the web socket stream indicated whether a message is coming from out, err or errChannel. Unfortunately, [OutputStreamMessage](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/OutputStreamMessage.java) does not allow to configure the stream ID. To get your requirements resolved, it's probably best to implement your own extension to [`WebSocketMessage`](https://github.com/fabric8io/mockwebserver/blob/master/src/main/java/io/fabric8/mockwebserver/internal/WebSocketMessage.java).

For providing this functionality in the mock server, I think we have two options: Either make `OutputStreamMessage` to support all types of streams (maybe with static factory methods `.out(String body)`, `.err(String body)` and `.errorChannel(String body)`) or to explicitly create classes `ErrorStreamMessage` and `ErrorChannelStreamMessage`. Any thoughts of the maintainers?

**Comment by manusa** [comment]
> it looks like the first byte in the web socket stream indicates whether a message is coming from out, err or errChannel

Yes.


You need to mock the WebSocket communication for this to work. It would be great if someone finally implements the test and they could share it in our cheatsheet or examples.
