### ISSUE TITLE
how to use command

### ISSUE THREAD

**Issue by yusanshui** [fabric8io/kubernetes-client#3647]
I want to create a pod with command

```yaml
command:
          - /bin/bash
          - -ec
          - |
            [[ -f "/opt/bitnami/scripts/git/entrypoint.sh" ]] && source "/opt/bitnami/scripts/git/entrypoint.sh"
``` 
I wrote like this in java

```java
.withCommand("/bin/bash","-ec","[[ -f \"/opt/bitnami/scripts/git/entrypoint.sh\" ]] && source \"/opt/bitnami/scripts/git/entrypoint.sh\"")
```
but I got this
```yaml
command:
          - /bin/bash
          - -ec
          - ' [[ -f "/opt/bitnami/scripts/git/entrypoint.sh" ]] && source "/opt/bitnami/scripts/git/entrypoint.sh" '
```
then it remindered me crashloopbackoff
what should I do ?

**Comment by manusa** [comment]
Shouldn't both YAMLs be equivalent (despite one is using a scalar value and the other a String)

**Comment by yusanshui** [comment]
> Shouldn't both YAMLs be equivalent (despite one is using a scalar value and the other a String)?

I knew. Remove `\"` in [[ -f \"/opt/bitnami/scripts/git/entrypoint.sh\" ]]
