### ISSUE TITLE
Doc:Update CHEATSHEET.md

### ISSUE THREAD

**Issue by Hugo-Ho** [fabric8io/kubernetes-client#3655]
### Is your task related to a problem? Please describe

Add the usage document content of clusterrole

### Describe the solution you'd like

Add the usage document content of clusterrole

**Comment by rohanKanojia** [comment]
@Hugo-Ho : Thanks a lot for your PR :+1: . I see we don't have any docs for any other RBAC Kubernetes resource as well. Would it be possible for you to add docs for those too? It shouldn't be different from ClusterRole.

- Role
- RoleBinding
- ClusterRoleBinding

**Comment by Hugo-Ho** [comment]
> @Hugo-Ho : Thanks a lot for your PR 👍 . I see we don't have any docs for any other RBAC Kubernetes resource as well. Would it be possible for you to add docs for those too? It shouldn't be different from ClusterRole.
> 
> * Role
> * RoleBinding
> * ClusterRoleBinding

OK, but I need some time, because I've been using RBAC related methods recently. When I finish the development at hand, I'll add the corresponding document content
