### ISSUE TITLE
Couldn't create client with custom dispatcher after v5.11

### ISSUE THREAD

**Issue by Yikun** [fabric8io/kubernetes-client#3663]
### Describe the bug

```scala
val dispatcher = new Dispatcher(ThreadUtils.newDaemonCachedThreadPool("kubernetes-dispatcher"))
val baseHttpClient = HttpClientUtils.createHttpClient(config)
val httpClientWithCustomDispatcher = baseHttpClient.newBuilder()
  .dispatcher(dispatcher)
  .build()
new DefaultKubernetesClient(httpClientWithCustomDispatcher, config)
```

Before v5.11, we can set dispatcher using below code, in v5.11 we do [feactor on okhttp usage](https://github.com/fabric8io/kubernetes-client/issues/3547) in https://github.com/fabric8io/kubernetes-client/pull/3549.

Looks like we should add new interface to set custom dispatcher in `io.fabric8.kubernetes.client.http.HttpClient.Builder` to keep compatibility？

### Fabric8 Kubernetes Client version

next (development version)

### Steps to reproduce

As below

### Expected behavior

We can set dispatcher

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.22.3@latest

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
value dispatcher is not a member of io.fabric8.kubernetes.client.http.HttpClient.Builder
```

**Comment by Yikun** [comment]
maybe cc @rohanKanojia @manusa

**Comment by shawkins** [comment]
There are several ways to still do this.  The best should be to use OkHttpClientFactory and override the additionalConfig method:

```
    Dispatcher dispatcher = new Dispatcher(ThreadUtils.newDaemonCachedThreadPool("kubernetes-dispatcher"))
    OkHttpClientFactory factory = new OkHttpClientFactory() {
      @Override
      protected void additionalConfig(okhttp3.OkHttpClient.Builder builder) {
        builder.dispatcher(dispatcher);
      }
    };
    new DefaultKubernetesClient(factory.createHttpClient(config), config);
```

**Comment by Yikun** [comment]
@shawkins Thanks for your reply and suggestion, it works.

BTW, have we decided which httpclient would be mainly used to replace `OkHttpClient`? It would be helpful to do some investegations on potenial upgrade.

**Comment by shawkins** [comment]
The likely plan will be to support both the okhttpclient and a jdk based https://github.com/shawkins/httpclient simultaneous for a while.

Before that new httpclient is supported there is also some additional refatoring needed to create either an httpclient api or a full client api module - #3645 has a draft pr of what a full client api would look like.  Then we'll likely want to bump the minimum jre support up to 11 - however there is a java bug that prevents the jdk client from working properly unless running on java 16+, so that may not be an option for every user.

**Comment by Yikun** [comment]
@shawkins Thanks for reply

**Comment by manusa** [comment]
Thanks for taking care of this Steven.
Closing the issue because I think that your problem was solved. Please feel free to open a new one if you problem persists.
