### ISSUE TITLE
Behaviour of resource .list() when filtered

### ISSUE THREAD

**Issue by tacf** [fabric8io/kubernetes-client#3669]
Hello,

I'm currently migrating from 5.6 to 5.11 and bumped into a single failing test on our end. The basic gist of the test is to create a pod, associate an event with it and then validate some internal logic that gets the pod status, we're using the mocked kubernetes server (autowired). The weird behaviour that we've found is that when trying to fetch the events (in our get pod status function) using the `.withField("involvedObject.name", podName)` we're not getting the same single event that we created. After fidling around what is even weirder is that the act of using a filter like `withFields` seems not to be working properly

Listing events without filter
![event_list](https://user-images.githubusercontent.com/3844722/146843766-f59aafa8-1cb0-4d77-9602-b99c12a5daa7.png)

Listing with o simple filter
![event_filtered_list](https://user-images.githubusercontent.com/3844722/146843825-aeb4edb1-04ad-49dd-b707-6b2a32841b05.png)

(I've also tried with other filtering functions as well as replacing the `withFields` by the more specific `withInvolvedObject()`

Are we missing any particular details on how this works? 

Let me know if i can provide with further details.

Thanks in advance

**Comment by manusa** [comment]
MockServer provides only field selector support for a few fields (name and namespace, I think).

**Comment by tacf** [comment]
Hi,

Yes, just confirmed you info. Think we can close this (i'll try to do so better search next time)

Thanks

Happy Holidays
