### ISSUE TITLE
add kubernetes-client example for secret

### ISSUE THREAD

**Issue by Hugo-Ho** [fabric8io/kubernetes-client#3677]
### Is your task related to a problem? Please describe

add kubernetes-client example for secret

### Describe the solution you'd like

add kubernetes-client example for secret

**Comment by siddhikhapare** [comment]
I want to contribute in mentioned doc. Can you explain me what kind of example want to add of secret? I am beginner. I have  little bit gone through this concept. Do you want to add secrets as volume mount. Can you provide me resources? As a beginner May I contribute in this doc?
