### ISSUE TITLE
CRD generator doesn't respect Jackson serialization/deserialization

### ISSUE THREAD

**Issue by andreaTP** [fabric8io/kubernetes-client#3681]
### Describe the bug

Having a Java class that defines:

```java
    private String myTest = null;

    public String getTest() {
        return myTest;
    }
```

generates a CRD with the following:

```yaml
              myTest:
                type: string
```

But when trying to read a corresponding CR from Kubernetes fails with the following:

```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "myTest" , not marked as ignorable
```

### Fabric8 Kubernetes Client version

5.10.1@latest

### Steps to reproduce

Try to read a CR using the `kubernetes-client` where the Jackson serialization have a mismatch with the name of the fields.

The viable workaround is to annotate the field to respect the generate CRD name e.g.:

```java
    @JsonProperty("myTest")
    private String myTest = null;

    public String getTest() {
        return myTest;
    }
```

### Expected behavior

The generated CRD should respect the Jackson serialization/deserialization informations. 

In general it should be possible to have a clean round-trip for arbitrary Java classes:

```
Java -> CRD -> CR in Kubernetes -> client reads the CR
```

### Runtime

Kubernetes (vanilla), other (please specify in additional context)

### Kubernetes API Server version

1.22.3@latest

### Environment

Linux, other (please specify in additional context)

**Comment by andreaTP** [comment]
cc. @metacosm

**Comment by andreaTP** [comment]
Maybe a good start would be to respect the following properties: https://github.com/strimzi/strimzi-kafka-operator/blob/399eb729201576e54367eb47a0cf07a1fd70c806/crd-generator/src/main/java/io/strimzi/crdgenerator/CrdGenerator.java#L120-L138

**Comment by metacosm** [comment]
Hmm, I don't think that the use case you mention is supposed to work… even in Jackson or, at least, it's relying on implicit behavior that should be avoided. With your example, it's not obvious for a human what the intent is: are you supposed to want a `myTest` property or a `test` one, or both? If you annotate your field with `JsonProperty` then the intent is clearer, though, I guess in that example, this might result in two properties being generated `myTest` and `test` if you don't mark the accessor with `JsonIgnore`… Not sure actually.

**Comment by andreaTP** [comment]
It only creates one property.
I agree that using `JsonProperty` annotation makes the intent much clearer.

I think that the available workaround make this issue pretty low in priority, I opened it mostly for tracking purposes.

I believe that we should somehow document what the generator takes in consideration (currently `JsonProperty`, `JsonPropertyDescription` and `NotNull`) so that we settle the right expectations.

**Comment by metacosm** [comment]
Agreed.
