### ISSUE TITLE
PersistentVolume wrongly requires namespace

### ISSUE THREAD

**Issue by parikhyash** [fabric8io/kubernetes-client#369]
@jimmidyson @iocanel 

- Persistent volumes in Kubernetes are not namespace specific. They are not created in a particular namespace.
- However, the client errors out when I don't provide a namespace while creating a persistent volume.
- This was not the case earlier with version 2.2.85
- I'm seeing this issue after upgrading to 2.2.101

Code:
```java
client.persistentVolumes().load(is).create();
```
"is" above is an input stream.

Error:

```
Caused by: com.xxx.xxx.xxx.exception.ResourceException: ResourceException (0): Namespace not specified. But operation requires namespace.
	at com.xxx.xxx.xxx.postPersistentVolume(KubeClient.java:240) ~[na:na]
	at com.xxx.xxx.xxx.postPersistentVolume(KubeClient.java:232) ~[na:na]
```

**Comment by ravilr** [comment]
looks like this change introduced the regression:
https://github.com/fabric8io/kubernetes-client/commit/6c3ead0f607283df779cf609ae6555bf84144185

 io.fabric8.kubernetes.client.dsl.internal/PersistentVolumeOperationsImpl.java requires overridden isResourceNamespaced() returning false.

**Comment by jimmidyson** [comment]
Good catch. Would you be able to submit a PR to fix?

**Comment by parikhyash** [comment]
@jimmidyson I'll submit a PR for this soon.

**Comment by jimmidyson** [comment]
Thank you!

**Comment by parikhyash** [comment]
@jimmidyson How I can pull in the latest build in my pom.xml? I tried upgrading io.fabric8/kubernetes-api to the new version (2.2.102), but it doesn't seem to have pulled in the changes. I still see the same error as earlier.

**Comment by jimmidyson** [comment]
As you can see from https://github.com/fabric8io/kubernetes-client/commits we haven't fine a release with this fix in yet. We'll try to release today & I'll update here once available. BTW do you use kubernetes-api or this library directly? Just wondering for future releases.

**Comment by parikhyash** [comment]
I am currently have kuberntes-api as a dependency, but I think I can shift to just kubernetes-client since those are the only classes I use.

Just saw that a new release version got pushed. Thanks!

**Comment by jimmidyson** [comment]
Oh yeah - new release 1.3.83 went out earlier! Sorry for not telling you sooner.
