### ISSUE TITLE
NodeAffinity cant not set  RequiredDuringSchedulingRequiredDuringExecution 

### ISSUE THREAD

**Issue by szsuyuji** [fabric8io/kubernetes-client#3702]
Client version 5.11.1

how to set RequiredDuringScheduling**RequiredDuringExecution**
![image](https://user-images.githubusercontent.com/1931764/147632736-a34cdecb-a2db-47d6-8a34-8155d50565e4.png)
the current api model only support IgnoredDuringExecution

**Comment by rohanKanojia** [comment]
@szsuyuji : Were you able to resolve this? I can see setters `setPreferredDuringSchedulingIgnoredDuringExecution` and `setRequiredDuringSchedulingIgnoredDuringExecution` in NodeAffinity class

**Comment by szsuyuji** [comment]
@rohanKanojia  tks,  RequiredDuringScheduling**_RequiredDuringExecution_**  attribute  is still  unimplemented in kubenetes , so i closed this issue
