### ISSUE TITLE
How to delete LivenessProbe or ReadinessProbe from a Deployment

### ISSUE THREAD

**Issue by libin0811** [fabric8io/kubernetes-client#3703]
I want to delete LivenessProbe from a Deployment ,but I can not find a method to do that .is there any method to do that ?
here is my try
`client.apps()
.deployments()
.inNamespace(namespace)
.withName(deploymentName)
.edit()
.editSpec()
.editTemplate()
.editSpec()
.editContainer(0)`

**Comment by rohanKanojia** [comment]
@libin0811 : I'm able to do it via simple JSON patch request:

```java
try (KubernetesClient client = new DefaultKubernetesClient()) {
  client.apps()
      .deployments()
      .inNamespace(namespace)
      .withName(deploymentName)
      .patch(PatchContext.of(PatchType.JSON), "[{\"op\": \"remove\", \"path\":\"/spec/template/spec/containers/0/livenessProbe\"}]");
}
```

**Comment by libin0811** [comment]
> 

Thank you for reply, can i see your pom dependency because i have some error to use PatchContext.of(PatchType.JSON)

**Comment by rohanKanojia** [comment]
@libin0811 : I'm using Fabric8 Kubernetes Client v5.11.0
