### ISSUE TITLE
Wait/Query if a change to an statefulset is applied to all pods

### ISSUE THREAD

**Issue by keppi2** [fabric8io/kubernetes-client#3710]
### Is your enhancement related to a problem? Please describe

After createOrReplace on an sts, i would like to wait till my change/rollout was applied to all pods of sts.

### Describe the solution you'd like

I got to know that sts does not support any state/condition if this change is applied to all pods. I got to know that with 
`kubectl rollout status statefulsets/NAME` you can query for the status of this rollout.
I didn't identified any implementation for rollout in kubernetes-client, so i would ask if we can add this? or is there already any activity/workaround for this?

### Describe alternatives you've considered

Best would be if kubernetes directly describes as status of sts if changes are rolled out, but i think this is not implemented (yet).

**Comment by shawkins** [comment]
Under the covers createOrReplace will use the replace method, which uses the RollingUpdater class - https://github.com/fabric8io/kubernetes-client/blob/7ef49cd34e2de0d68422e17ce24fe15e48b63f17/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/apps/v1/RollingUpdater.java

It has built in logic to wait until all pods are ready.  Is this not what you are observing?
