### ISSUE TITLE
SharedIndexInformer events not detecting Terminating state of a pod

### ISSUE THREAD

**Issue by yevsh** [fabric8io/kubernetes-client#3726]
### Is your enhancement related to a problem? Please describe

I need to detect when pod is entering "Terminating" state.

```
SharedInformerFactory factory = kubernetesClient.informers();
informer=factory.sharedIndexInformerFor(Pod.class, new OperationContext().withNamespace("ns"),10 * 1000L);
informer.addEventHandler(new ResourceEventHandler<Pod>() {...}
```

Delete event is triggered when pod is completely terminated, but I need when it begins the termination.

### Describe the solution you'd like

n/a

**Comment by shawkins** [comment]
> Delete event is triggered when pod is completely terminated, but I need when it begins the termination.

You should check the pod status in onUpdate.

**Comment by yevsh** [comment]
I printed 
oldPod.getStatus() and newPod.

I didn't see under condition anything about "terminating".

What am I missing?

**Comment by shawkins** [comment]
> What am I missing?

Seems like it would be under status.phase.  You can also check individual containers under status.containerStatuses[id].state

**Comment by yevsh** [comment]
for old pod:

containerStatus
state->running=ContainerState(running=ContainerStateRunning(startedAt=2022-01-11T06:42:13Z, additionalProperties={}), terminated=null, waiting=null, additionalProperties={})
state->teminated=null

for new pod:
containerStatus
state->running=ContainerState(running=ContainerStateRunning(startedAt=2022-01-11T06:42:13Z, additionalProperties={}), terminated=null, waiting=null, additionalProperties={})
state->teminated=null

**Comment by shawkins** [comment]
See https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase - Terminating is not actually a phase:

```
Note: When a Pod is being deleted, it is shown as Terminating by some kubectl commands. This Terminating status is not one of the Pod phases. A Pod is granted a term to terminate gracefully, which defaults to 30 seconds. You can use the flag --force to terminate a Pod by force.
```

So you'll need to instead check for the metadata.deletionTimestamp as an indication that the pod is terminating.
