### ISSUE TITLE
Can't close a watcher

### ISSUE THREAD

**Issue by remy-phelipot** [fabric8io/kubernetes-client#373]
Hello,

It seems the client is unable to close the HTTP connection while watching the pod. Indeed, an "OkHttp" thread is still running, waiting for content of the kubernetes API. I suspect the following code to cause the problem:

```java
public class WatchConnectionManager<T, L extends KubernetesResourceList> implements Watch {
...

Request request = new Request.Builder()
      .get()
      .url(httpUrlBuilder.build())
      .addHeader("Origin", requestUrl.getProtocol() + "://" + requestUrl.getHost() + ":" + requestUrl.getPort())
      .build();
    clonedClient.setReadTimeout(0, TimeUnit.MILLISECONDS);

...
```

Indeed the timeout for the connection is set to 0, meaning there is no timeout at all.

Here is a minimal example of this problem (the program is still running after client.close() is displayed):
```java
import io.fabric8.kubernetes.api.model.Pod;
import io.fabric8.kubernetes.client.*;


public class Test {
    public static void main(String[] args) {
        KubernetesClient client = new DefaultKubernetesClient();

        Watch watch = client.pods().inNamespace("default").watch(new Watcher<Pod>() {
            public void eventReceived(Action action, Pod pod) {
                System.out.println(pod.getMetadata().getResourceVersion());
            }

            public void onClose(KubernetesClientException e) {
                System.out.println("client closed");
            }
        });

        watch.close();
        client.close();
        System.out.println("client.close();");
    }
}
```

EDIT: Tested with kubernetes-client v1.3.82

**Comment by iocanel** [comment]
@remy-phelipot: Thanks for the feedback. I'll have a look asap.

**Comment by Project0** [comment]
Any update on this? Its still not working with version 1.3.92

**Comment by jimmidyson** [comment]
Tested example above with latest master (no changes from 1.3.95) & client & watch both close properly.

**Comment by ZenithKaizer** [comment]
Hi everbody, any update on this? Its still not working with version 1.3.95.

**Comment by jimmidyson** [comment]
Can you please share code to reproduce the issue. I ran the code example above with 1.3.95 & it closes just fine.

**Comment by ZenithKaizer** [comment]
@jimmidyson I am running exactly the code above with 1.3.95.

**Comment by ZenithKaizer** [comment]
Hi, Even when upgrading kubernetes-client to latest (1.3.96), I still have that issue with our initial example code above. 

Here is my maven file: 
![capture-1 2](https://cloud.githubusercontent.com/assets/8982756/15863370/09528ee2-2cd3-11e6-8fa8-cf48e4e905a1.PNG)

Here is the output of my console when I execute that example code. 
![capture-1 3](https://cloud.githubusercontent.com/assets/8982756/15863459/5b264678-2cd3-11e6-9571-59432104d601.PNG)

The program never end.  I am working with Java 8 on Windows 7. 
Plz I need your help on this issue. Thks...

**Comment by jimmidyson** [comment]
Running this on Linux works fine... Must be something Windows specific I guess. I don't' have a Windows env to try to debug this on unfortunately so any help with a PR would be really appreciated.

**Comment by ZenithKaizer** [comment]
Hi, 
After some further investigations we found that, the problem that we were facing, after upgrading to Kubernetes-Client 1.3.95, was not an fabric8 issue. The issue was caused by our kurbernetes instance not replying at all to the `writerClose` messages send by the `RealWebSocket`, as show in the code bellow : 
```java
public abstract class RealWebSocket implements WebSocket
...
@Override public void close(int code, String reason) throws IOException {
    if (writerSentClose) throw new IllegalStateException("closed");
    writerSentClose = true;

    try {
      writer.writeClose(code, reason);
    } catch (IOException e) {
      if (connectionClosed.compareAndSet(false, true)) {
        // Try to close the connection without masking the original exception.
        try {
          close();
        } catch (IOException ignored) {
        }
      }
      throw e;
    }
  }
...
}
```
We then, change our kubernetes installation and it works. Thks !

**Comment by jimmidyson** [comment]
@ZenithKaizer Ah interesting! What did you do to your kubernetes installation to get this to work? Just in case others hit the same issue.

**Comment by jimmidyson** [comment]
Closing now but feel free to reopen if this is still an issue for anyone.

**Comment by ZenithKaizer** [comment]
@jimmidyson we were using kubemark release with hollow-nodes to emulate real nodes for testing purposes : https://github.com/kubernetes/kubernetes/blob/release-1.2/docs/proposals/kubemark.md. All were performing well then, except for this `watch.close();`
We just switch to standard kubernetes binairies and it works! 
Thanks ....

**Comment by jimmidyson** [comment]
@ZenithKaizer Thanks for the info - will watch out for that. Wonder if it makes sense to have a timeout in the close somehow, although have to be careful of not leaking resources. Will think on that,
