### ISSUE TITLE
Document CRD Generator

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#3731]
### Description

The CRD generator is getting more and more complex. There are now, many different configuration options, and available annotations.

A proper document should be created to illustrate the different options to configure and annotate POJOs to generate CRD resources.

_Originally posted by @andreaTP in https://github.com/fabric8io/kubernetes-client/issues/3681#issuecomment-1000289698_

_Originally posted by @manusa in https://github.com/fabric8io/kubernetes-client/issues/3689#issuecomment-1007516885_

**Comment by DHARUNKUMAR7** [comment]
Hi..! I would like to work on this issue can you please guide me to get started..

**Comment by andreaTP** [comment]
Hi @DHARUNKUMAR7 , I have started a very minimal document here:

https://github.com/fabric8io/kubernetes-client/pull/3732

I would say that you can elaborate on top of that.

**Comment by manusa** [comment]
Added in https://github.com/fabric8io/kubernetes-client/pull/3732 and https://github.com/fabric8io/kubernetes-client/pull/3797
