### ISSUE TITLE
AssertionError on OpenShift in fips mode

### ISSUE THREAD

**Issue by skabashnyuk** [fabric8io/kubernetes-client#3738]
### Describe the bug

One of the CRW (upstream of Eclipse Che) customers reported a bug that says that after some upgrade, the che-server is not able to start when running on OpenShift in fips mode. I assume it was caused by an upgrade of java to 11.0.13. Because it was working before.  According to the document, https://access.redhat.com/documentation/en-us/openjdk/11/html-single/configuring_openjdk_11_on_rhel_with_fips/index fips mode become default behavior since RHEL 8.3. Previously to enable it you'll have to enable it with `-Dcom.redhat.fips=true` . Our default kubernetes client version 5.7.3. I was able to use 5.10.2 with a small patch for HttpClientUtils to get a real issue. 

My assumption: it is caused by this code

```java
...
public abstract class SSLContextImpl extends SSLContextSpi {
..
    private X509TrustManager chooseTrustManager(TrustManager[] tm)
            throws KeyManagementException {
        // We only use the first instance of X509TrustManager passed to us.
        for (int i = 0; tm != null && i < tm.length; i++) {
            if (tm[i] instanceof X509TrustManager) {
                if (SunJSSE.isFIPS() &&
                        !(tm[i] instanceof X509TrustManagerImpl)) {
                    throw new KeyManagementException
                        ("FIPS mode: only SunJSSE TrustManagers may be used");
                }

                if (tm[i] instanceof X509ExtendedTrustManager) {
                    return (X509TrustManager)tm[i];
                } else {
                    return new AbstractTrustManagerWrapper(
                                        (X509TrustManager)tm[i]);
                }
            }
        }

        // nothing found, return a dummy X509TrustManager.
        return DummyX509TrustManager.INSTANCE;
    }
```
Which expects TrustManager to be an instance of X509TrustManagerImpl in fips mode.
However we got `io.fabric8.kubernetes.client.internal.SSLUtils$1` see  https://github.com/fabric8io/kubernetes-client/blob/2ef6ee90490f448752e61c912925e823805fd2ab/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/SSLUtils.java#L97-L138

### Fabric8 Kubernetes Client version

5.10.1@latest

### Steps to reproduce

1. Setup OpenShift cluster with fips mode
2. Build a code with image `registry.access.redhat.com/ubi8-minimal:8.5-218` and java `11.0.13+8-LTS`. It's important to have 13th patch
3. Run any code that communicates with k8s cluster 

### Expected behavior

The error should not happen.

### Runtime

OpenShift

### Kubernetes API Server version

1.22.3@latest

### Environment

Linux

### Fabric8 Kubernetes Client Logs
Original exception from 5.7.3
```


Caused by: AssertionError
	at HttpClientUtils.createHttpClient(HttpClientUtils.java:141)
	at HttpClientUtils.createHttpClient(HttpClientUtils.java:66)
	at KubernetesClientFactory.<init>(KubernetesClientFactory.java:72)
	at CheServerKubernetesClientFactory.<init>(CheServerKubernetesClientFactory.java:43)
	at HttpClientUtils.createHttpClient(HttpClientUtils.java:66)
	at KubernetesClientFactory.<init>(KubernetesClientFactory.java:72)
	at OpenShiftClientFactory.<init>(OpenShiftClientFactory.java:74)
	at OpenShiftClientFactory$$FastClassByGuice$$166068897.GUICE$TRAMPOLINE(<generated>)
	at OpenShiftClientFactory$$FastClassByGuice$$166068897.apply(<generated>)
	at DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at ConstructorInjector.provision(ConstructorInjector.java:114)
	at ConstructorInjector.construct(ConstructorInjector.java:91)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
```

Exception from the patched version of 5.10.2
```
Caused by: KubernetesClientException: An error has occurred.                                                                                                                                                 │
│     at KubernetesClientException.launderThrowable(KubernetesClientException.java:103)                                                                                                                        │
│     at KubernetesClientException.launderThrowable(KubernetesClientException.java:97)                                                                                                                         │
│     at HttpClientUtils.createHttpClient(HttpClientUtils.java:160)                                                                                                                                            │
│     at HttpClientUtils.createHttpClient(HttpClientUtils.java:85)                                                                                                                                             │
│     at KubernetesClientFactory.<init>(KubernetesClientFactory.java:77)                                                                                                                                       │
│     at OpenShiftClientFactory.<init>(OpenShiftClientFactory.java:72)                                                                                                                                         │
│     at OpenShiftClientFactory$$FastClassByGuice$$171156543.GUICE$TRAMPOLINE(<generated>)                                                                                                                     │
│     at OpenShiftClientFactory$$FastClassByGuice$$171156543.apply(<generated>)                                                                                                                                │
│     at java.base/NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                                                             │
│     at java.base/NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                                                           │
│     at java.base/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                                                   │
│     at java.base/Method.invoke(Method.java:566)                                                                                                                                                              │
│     at Bootstrap.start(Bootstrap.java:345)                                                                                                                                                                   │
│     at Bootstrap.main(Bootstrap.java:476)                                                                                                                                                                    │
│ Caused by: KeyManagementException: FIPS mode: only SunJSSE TrustManagers may be used                                                                                                                         │
│     at java.base/SSLContextImpl.chooseTrustManager(SSLContextImpl.java:133)                                                                                                                                  │
│     at java.base/SSLContextImpl.engineInit(SSLContextImpl.java:95)                                                                                                                                           │
│     at java.base/SSLContext.init(SSLContext.java:297)                                                                                                                                                        │
│     at SSLUtils.sslContext(SSLUtils.java:86)                                                                                                                                                                 │
│     at HttpClientUtils.createHttpClient(HttpClientUtils.java:157)                                                                                                                                            │
│     ... 60 more

```

### Additional context

https://access.redhat.com/documentation/en-us/openjdk/11/html-single/configuring_openjdk_11_on_rhel_with_fips/index
https://github.com/eclipse/che/issues/20991
https://issues.redhat.com/browse/CRW-2606
Upgrade to 5.11.x for Eclipse Che is complicated due to significant changes in OkHttpClient configuration

**Comment by aadityasinha-dotcom** [comment]
@skabashnyuk  Can I work on this issue?

**Comment by skabashnyuk** [comment]
@manusa can you explain how this pr https://github.com/fabric8io/kubernetes-client/pull/3867 changes the way how this TrustManager https://github.com/fabric8io/kubernetes-client/blob/2ef6ee90490f448752e61c912925e823805fd2ab/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/SSLUtils.java#L97-L138 is used in  HttpClient?

**Comment by manusa** [comment]
That trust manager is used only if you use the flag to trust all certs. I reopened the issue because I haven't tried this specific scenario.

However, the issue is not with the Trust Manager itself, but with the underlying trust store (KeyStore). When running in FIPS mode, the default value for `KeyStore.getDefaultType()` is `PKCS11`. However, the default system trust store is of type `pkcs12`. So when trying to load the **default** JAVA_HOME trust store (`lib/security/cacerts`), which is of type `pkcs12` with a KeyStore of type `PKCS11` an Exception is thrown.

As I said, I haven't test the trust all scenario, but it should be valid too.

**Comment by skabashnyuk** [comment]
We do use keystore in our code. When we importing certifiactes. https://github.com/eclipse-che/che-server/blob/470e5b86be8f31f19ae29a3d48bd3e8af73521bd/dockerfiles/che/entrypoint.sh#L311
I'm not sure about the format of it but the issue I have is that when `config.isTrustCerts()=true`  here https://github.com/fabric8io/kubernetes-client/blob/2ef6ee90490f448752e61c912925e823805fd2ab/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/SSLUtils.java#L97-L138
constructed TrustManager from an anonymous class that is forbidden in FIPS mode.

**Comment by manusa** [comment]
Your scenario might be a little bit more complex. Anyway, with the current fix, you could specify the trust store type via the `javax.net.ssl.trustStoreType` in case you are supplying your own version.

I'll probably do a SNAPSHOT release in a few hours. I'll try with the trust all flag then. But for your more specific usage, a minimal reproducer project would be very helpful.

**Comment by manusa** [comment]
I've been further analyzing this issue.

As discussed internally, the issue is only reproducible in JDK11 environments on FIPS mode when the client is set to trust all certificates.

As mentioned in the issue description, the problematic code in the JDK (11) is:
https://github.com/openjdk/jdk/blob/42de356cbd3d750cc3567ac814f7c85323877cea/src/java.base/share/classes/sun/security/ssl/SSLContextImpl.java#L125-L143

The linked code is enforcing the provided TrustManager to be FIPS compliant (which makes sense from a strict point of view), by checking it's an instance of the JDK provided Impl. Apparently there was a change of opinion in this enforcement and this check is no longer performed in JDK17, where the issue is not reproducible.

Anyway, considering that a FIPS environment should (must) use strict security measures, it makes absolutely no sense to be able to configure the client to trust all certificates in this mode. I don't think we should further try to mitigate this enforcement.
If the user has chosen to trust any certificate, they should also be strictly disabling Java's FIPS mode either by `-Dcom.redhat.fips=false` or by providing their own security policies.

**Comment by skabashnyuk** [comment]
>, it makes absolutely no sense to be able to configure the client to trust all certificates in this mode

Can you elaborate on that? In our case, all certificates come from OpenShift 
https://docs.openshift.com/container-platform/4.9/security/certificate_types_descriptions/service-ca-certificates.html
We get them using `service.beta.openshift.io/inject-cabundle: true`

**Comment by manusa** [comment]
The following TrustManager:

https://github.com/fabric8io/kubernetes-client/blob/2ef6ee90490f448752e61c912925e823805fd2ab/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/SSLUtils.java#L96-L97

is only enabled if the client is configured to trust all certificates (KUBERNETES_TRUST_CERTIFICATES).

**Comment by skabashnyuk** [comment]
What does that mean for `Eclipse Che` that uses Kubernetes client on openshift with fips mode enabled? Set `isTrustCerts` to false?

**Comment by manusa** [comment]
`isTrustCerts` defaults always to false unless stated otherwise.

Meaning that I assume Eclipse Che's deployment at some point is setting an env variable (or a Java system property) KUBERNETES_TRUST_CERTIFICATES=true.

**Comment by skabashnyuk** [comment]
Yes. Most likely we set it to true. Should we avoid doing that on Fips mode?

**Comment by manusa** [comment]
> Should we avoid doing that on Fips mode?

Well, this is the point. The JVM is telling you that your TrustManager (the one provided by the Client due to this setting) is not compliant with FIPS mode.

So given that the ENV variable is provided, another flag disabling FIPS in the JVM should be provided too. At least, this is what makes sense from my PoV. In the end, your runtime is omitting FIPS standards and is not compliant.

**Comment by skabashnyuk** [comment]
Closing as explained.
