### ISSUE TITLE
Add kubernetes duration human readable formats

### ISSUE THREAD

**Issue by mattnelson** [fabric8io/kubernetes-client#3748]
### Is your enhancement related to a problem? Please describe

I would like to be able to get a formatted duration display that matches how kubernetes displays them.

### Describe the solution you'd like

Building on top of the age support added in #2590. Add two new helpers to `KubernetesResourceUtil` to match duration formatting from upstream kubernetes.

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/duration/duration.go

### Describe alternatives you've considered

I could not find any alternate implementations that match kubernetes duration rounding pattern, most specifically around the human duration that support variable significant digits.

**Comment by jackson216** [comment]
can i try this?
