### ISSUE TITLE
Prevent modifications to passed in objects

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3756]
### Is your task related to a problem? Please describe

Related to #3078 and possibly to https://github.com/java-operator-sdk/java-operator-sdk/issues/830 modifications should not be directly made to passed in objects.

### Describe the solution you'd like

Simply reverting the change is not quite enough.  As the object could have been obtained from a cache that simply creates a narrow race condition.  More than likely the only solution is to clone prior to making the modification.  The impetus for that cloning is mitigated if cloning were enforced for any resource obtained by the informer cache.

**Comment by shawkins** [comment]
Related to this, do we want another issue on write protecting the informer caches?

**Comment by manusa** [comment]
> Related to this, do we want another issue on write protecting the informer caches?

Wasn't this something we discarded?

It's OK for me, but given the additional processing overhead, it should be something configurable.

**Comment by shawkins** [comment]
> It's OK for me, but given the additional processing overhead, it should be something configurable.

That is the idea, to propose/collect possible solutions - that would be optional:

secrets().withImmutableStore().inform()
or
SharedInformer.getImmutableStore() - returns a store that returns copies.

Either could be implemented with a wrapper that clones or adding logic for storage functions - for example to hold just strings in memory.
