### ISSUE TITLE
KubernetesMockServer should allow overriding its default `/version` expectation

### ISSUE THREAD

**Issue by joshiste** [fabric8io/kubernetes-client#3758]
### Is your enhancement related to a problem? Please describe

I want to override the VersionInfo returned by the `io.fabric8.kubernetes.client.server.mock.KubernetesServer`.

### Describe the solution you'd like

Some easy way to specify the version the mock shall return

### Describe alternatives you've considered

```
this.server.expect().get().withPath("/version")
                .andReturn(200, new VersionInfo.Builder().withMajor("1").withMinor("18+").build())
                .always();
```
This doesn't work for me as the expectation from `KubernetesMockServer#onStart()` is returned

### Additional context

introduced with #3562

**Comment by joshiste** [comment]
Currently using this as workaround:
```
KubernetesMockServer mock = this.server.getKubernetesMockServer();
mock.clearExpectations();
mock.expect().get().withPath("/").andReturn(200, new RootPathsBuilder().addToPaths(mock.getRootPaths()).build()).always();
mock.expect().get().withPath("/version")
    .andReturn(200, new VersionInfo.Builder().withMajor("1").withMinor("18+").build())
    .always();
```

**Comment by manusa** [comment]
Related to https://github.com/quarkusio/quarkus/issues/23023

**Comment by manusa** [comment]
Hi @joshiste 
The default version expectation provisioning was added as a feature in #3562 (#3536).

[Your approach](https://github.com/fabric8io/kubernetes-client/issues/3758#issuecomment-1015429844) is the recommended ATM. However, we left the door open for future improvements.

One of the alternatives would be to expose the VersionInfo field:

https://github.com/fabric8io/kubernetes-client/blob/258f49aa97e1c4fd986a3a98de411116c1760307/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesMockServer.java#L44

However, I'm not convinced about this approach.

Feedback is welcome ;)
