### ISSUE TITLE
Removing the Arquillian profiles present in the main pom.xml 

### ISSUE THREAD

**Issue by ShubhamRwt** [fabric8io/kubernetes-client#3759]
### Is your task related to a problem? Please describe

While building the project I used the `mvn clean install` command to build the project. After the  build completed successfully, there were two profiles with dependencies `arquillian-cube-openshift-starter` and `arquillian-cube-kubernetes-starter` which were not resolved even after the build completed successfully. On further investigation what I figured out was that maybe these two profiles are really not required when we build our project.  Is there a reason they are still there or can they be removed?

### Describe the solution you'd like

Remove the two profiles corresponding to  `arquillian-cube-openshift-starter` and `arquillian-cube-kubernetes-starter`

### Describe alternatives you've considered

Let them stay in main pom.xml file

**Comment by manusa** [comment]
> Remove the two profiles corresponding to `arquillian-cube-openshift-starter` and `arquillian-cube-kubernetes-starter`

I understand you're suggesting to remove the dependencies

> Is there a reason they are still there or can they be removed?

Yes there is a reason, these dependencies are used for our integration tests.

**Comment by manusa** [comment]
To extend a little bit more, we've discussed removing Arquillian altogether, since it doesn't add much value to our tests at this point.

So once we remove the Arquillian dependencies from our tests, we can safely remove these dependencies.

**Comment by rohanKanojia** [comment]
@manusa : We're not using these profiles in our integration tests workflow:
https://github.com/fabric8io/kubernetes-client/blob/4c386fd99606513a0979749be58bf8f604e5451a/.github/workflows/e2e-tests.yml#L84

Maybe they were used in past but not anymore. Even after removing the arquillian dependencies from the profiles, integration ests still seem to be passing. I was helping Shubham yesterday when he noticed this. I had asked him to create an issue.

**Comment by manusa** [comment]
Aren't we running the kubernetes-itests module verify goal? If not, something is not OK in the pipeline.

https://github.com/fabric8io/kubernetes-client/blob/bac0d785db78d10f40c45703d44a331516eaa3a5/kubernetes-itests/pom.xml#L52

I'm really not following when you talk about "profiles" and don't mention the profile id. Are you talking about the profile that "declares" those dependencies? Are you talking about the dependencies themselves?

**Comment by rohanKanojia** [comment]
profiles id under question are `itests-kubernetes` and `itests-openshift`

**Comment by manusa** [comment]
These profiles contain redundant info plus aren't ever activated.

Probably leftovers after switching to GH actions.

**Comment by ShubhamRwt** [comment]
I tried running `mvn clean verify -Pitests-openshift` after removing the profile ids `itests-kubernetes` and `itests-openshift` and it still worked

**Comment by manusa** [comment]
> I tried running `mvn clean verify -Pitests-openshift` after removing the profile ids `itests-kubernetes` and `itests-openshift` and it still worked

I'm sure you got a warning about a missing profile ;)

**Comment by rohanKanojia** [comment]
> I tried running mvn clean verify -Pitests-openshift after removing the profile ids itests-kubernetes and itests-openshift and it still worked

When specified profile isn't present, maven runs normal build with a warning for profile not being found.

**Comment by ShubhamRwt** [comment]
Ahh Okay. Thanks @manusa and @rohanKanojia. But I still feel that these two profiles should be looked into since the deps under these profiles were not getting fetched until I run the `itests`. The problems which I was facing yesterday @rohanKanojia

**Comment by ShubhamRwt** [comment]
This dependency 
```
        <dependency>
          <groupId>org.arquillian.cube</groupId>
          <artifactId>arquillian-cube-kubernetes-starter</artifactId>
          <version>${arquillian.cube.version}</version>
          <scope>test</scope>
        </dependency>
``` 
under the `itests-Kubernetes` profile doesn't get resolved even after I run  the `mvn clean verify -Pitests-kubernetes`
