### ISSUE TITLE
Extension Jar packages don't contain the META-INF/jandex.idx index file

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#3761]
### Describe the bug

The bundling configuration for the extension modules is not considering the META-INF/jandex.idx file.

### Fabric8 Kubernetes Client version

other (please specify in additional context)

### Steps to reproduce

`mvn package`

`target/classes/META-INF` contains a valid jandex.idx file

`target/$artifact-$version.jar` archive doesn't contain the `META-INF/jandex.idx` file 

### Expected behavior

`target/$artifact-$version.jar` should contain the `META-INF/jandex.idx` file 

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

other (please specify in additional context)

**Comment by rohanKanojia** [comment]
It looks like we just add this property to each extension model/client module; `META-INF/jandex.idx` file should be included in the generated jar file

```xml
    <properties>
        <osgi.include.resources>
          /META-INF/jandex.idx=target/classes/META-INF/jandex.idx
        </osgi.include.resources>
    </properties>
```
