### ISSUE TITLE
[crd-gen] Primitive type Long should translate to "integer"

### ISSUE THREAD

**Issue by andreaTP** [fabric8io/kubernetes-client#3763]
### Describe the bug

According to the CRD specification a Java `Long` type should be translated to an `integer`:

> 'number' (all formats) | double
'integer' (all formats) | int (64)

https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/

### Fabric8 Kubernetes Client version

next (development version)

### Steps to reproduce

Add a `Long` property field to your CRD and it gets translated to `number`.

In the code:
https://github.com/fabric8io/kubernetes-client/blob/4c386fd99606513a0979749be58bf8f604e5451a/crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java#L93-L94

### Expected behavior

A `Long` should be translated to an `integer`

### Runtime

Kubernetes (vanilla), other (please specify in additional context)

### Kubernetes API Server version

next (development version)

### Environment

other (please specify in additional context)

### Additional context

cc. @metacosm

**Comment by manusa** [comment]
Fixed by #3764
