### ISSUE TITLE
Clean up `HasMetadata` and `CustomResource` API

### ISSUE THREAD

**Issue by metacosm** [fabric8io/kubernetes-client#3765]
### Is your enhancement related to a problem? Please describe

Methods that are currently scoped or target only for `CustomResource` implementations could make sense for wider use for classes that implement `HasMetadata`. We also need to unify the methods on `HasMetadata` as well because some methods are only available as static versions when they would also make sense as instance methods (e.g. `getGroup`)… Generally speaking it feels that a lot of what's currently specific to `CustomResources` could also be applicable to `HasMetadata` and maybe `CustomResource` should only be a sort of marker interface?

### Describe the solution you'd like

Unify `CustomResource` and `HasMetadata` APIs.

**Comment by rohanKanojia** [comment]
@metacosm : polite ping, are you still working on this? I was wondering if we could take this up

**Comment by metacosm** [comment]
Hi @rohanKanojia, nope… Wanted to but there was always something else I needed to do first :(
Feel free to re-assign.
