### ISSUE TITLE
Autoscaling API support

### ISSUE THREAD

**Issue by ramukima** [fabric8io/kubernetes-client#377]
Is there a plan to support the Autoscaling APIs soon ? Reference: http://kubernetes.io/docs/api-reference/autoscaling/v1/operations/

**Comment by iocanel** [comment]
We will as soon as possible.

**Comment by jpechane** [comment]
See https://github.com/fabric8io/kubernetes-client/pull/379

**Comment by iocanel** [comment]
Well thanks to @jpechane it was really really soon!

Thanks Jiri!
