### ISSUE TITLE
Job immediately goes to NotReady

### ISSUE THREAD

**Issue by hambone01** [fabric8io/kubernetes-client#3779]
### Describe the bug

versions: 
 Docker Desktop for Windows 4.3.2
 DD Kubernetes: 1.22.4
 fabric8: kubernetes-client:   5.6.0 and 5.10.1 and 5.11.2

When running the [example Job code](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/JobExample.java), the started Job immediately goes to the NotReady status. Kubectl describe shows the reason

Readiness probe failed: Get "http://10.1.1.85:15021/healthz/ready": dial tcp 10.1.1.85:15021: connect: connection refused

The problem is made evident when the following line is run
> 			PodList podList = client.pods().inNamespace(namespace).withLabel("job-name", job.getMetadata().getName()).list();

podList always comes back with all null values. 

If I insert a break point just after the line
>client.batch().v1().jobs().inNamespace(namespace).createOrReplace(job);

and wait for a few seconds, then when I step-over the line
> PodList podList = client.pods().inNamespace(namespace).withLabel("job-name", job.getMetadata().getName()).list();

podList is no longer all nulls. However, even with this little success, this line
>client.pods().inNamespace(namespace).withName(podList.getItems().get(0).getMetadata().getName())
					.waitUntilCondition(pod -> pod.getStatus().getPhase().equals("Succeeded"), 1, TimeUnit.MINUTES);

always times out.

### Fabric8 Kubernetes Client version

5.10.1@latest

### Steps to reproduce

Setup the latest Docker Desktop + Kubernetes
Run the fabric8 Job example code.

### Expected behavior

Job run to Completed and prints the computer version of Pi.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Windows

### Fabric8 Kubernetes Client Logs

```shell
How do I get these?
```

**Comment by rohanKanojia** [comment]
Could this be something related to misconfiguration in your cluster? 

I just tried running JobExample on a remote [OpenShift Developer Sandbox Cluster](https://developers.redhat.com/developer-sandbox) and for me example seems to be running okay:
```
kubernetes-examples : $ mvn exec:java -Dexec.mainClass=io.fabric8.kubernetes.examples.JobExample
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< io.fabric8:kubernetes-examples >-------------------
[INFO] Building Fabric8 :: Kubernetes :: Client Examples 5.12-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:3.0.0:java (default-cli) @ kubernetes-examples ---
[io.fabric8.kubernetes.examples.JobExample.main()] INFO io.fabric8.kubernetes.examples.JobExample - Creating job pi.
[io.fabric8.kubernetes.examples.JobExample.main()] INFO io.fabric8.kubernetes.examples.JobExample - 3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679821480865132823066470938446095505822317253594081284811174502841027019385211055596446229489549303819644288109756659334461284756482337867831652712019091456485669234603486104543266482133936072602491412737245870066063155881748815209209628292540917153643678925903600113305305488204665213841469519415116094330572703657595919530921861173819326117931051185480744623799627495673518857527248912279381830119491298336733624406566430860213949463952247371907021798609437027705392171762931767523846748184676694051320005681271452635608277857713427577896091736371787214684409012249534301465495853710507922796892589235420199561121290219608640344181598136297747713099605187072113499999983729780499510597317328160963185950244594553469083026425223082533446850352619311881710100031378387528865875332083814206171776691473035982534904287554687311595628638823537875937519577818577805321712268066130019278766111959092164201989380952572010654858632788659361533818279682303019520353018529689957736225994138912497217752834791315155748572424541506959508295331168617278558890750983817546374649393192550604009277016711390098488240128583616035637076601047101819429555961989467678374494482553797747268471040475346462080466842590694912933136770289891521047521620569660240580381501935112533824300355876402474964732639141992726042699227967823547816360093417216412199245863150302861829745557067498385054945885869269956909272107975093029553211653449872027559602364806654991198818347977535663698074265425278625518184175746728909777727938000816470600161452491921732172147723501414419735685481613611573525521334757418494684385233239073941433345477624168625189835694855620992192221842725502542568876717904946016534668049886272327917860857843838279679766814541009538837863609506800642251252051173929848960841284886269456042419652850222106611863067442786220391949450471237137869609563643719172874677646575739624138908658326459958133904780275901
```

When I check pod status, for me they seem to be in completed state:
```
k8s-client : $ kubectl get pods -w
NAME          READY     STATUS    RESTARTS   AGE
pi--1-zx2gg   1/1       Running   0          8s
pi--1-zx2gg   0/1       Completed   0         12s

```

**Comment by hambone01** [comment]
Personally, I think it is Docker Desktop's kubernetes 1.22.5 causing the problem. This worked before I upgraded to the latest Docker Desktop which gave me the 1.22.5 kubernetes. I am trying down grading now.

I was hoping it was a known thing.

**Comment by hambone01** [comment]
It turned out to be Istio sidecar injection. I had sidecar injection turned on in the default namespace, which is where I was starting the Job. I turned off sidecar injection and the Job works.

Thank you for taking the time to answer my question, I really do appreciate it.
