### ISSUE TITLE
DeletionTimestamp and Finalizer support in Mock server

### ISSUE THREAD

**Issue by scrocquesel** [fabric8io/kubernetes-client#3805]
### Is your enhancement related to a problem? Please describe

I'm writing an operator and would like to test how it behaves when deleting a resource. In CRUD mode, when a resource is deleted, it is remove even if finalizers is not empty.

### Describe the solution you'd like

I expect delete to update the resource with a deletionTimestamp if finalizers collection is not empty. When the operator will remove its finalizer and update the CR, if the finalizers collection is empty, the resource should be deleted.

I should be able to wait for the resource to be deleted (wait while get CR is not null) and assert the operator does its cleanup job.

### Describe alternatives you've considered

I tried to update the resource with edit to set a deletionTimestamp but is seems to be not saved.

```
client.resources(CRD.class).inNamespace("foo").withName("bar").edit(p -> {
    p.getMetadata().setDeletionTimestamp("2022-02-06T14:21:44.719489Z");
    return p;
});
```

what works is to replace the CR.

```
var cr = client.resources(CRD.class).inNamespace("foo").withName("bar").get();
cr.getMetadata().setDeletionTimestamp("2022-02-06T14:21:44.719489Z");
client.resource(cr).createOrReplace();
```

**Comment by amydentremont** [comment]
+1 on this, I was just writing a test and was surprised that my CR with a finalizer had actually been deleted

**Comment by derlin** [comment]
Any news on this ? As Red Hat announced a Java Operator SDK preview, testing finalizers and dependent resources deletion will become a common use case: [Write Kubernetes with the Java Operator SDK | Red Hat Developer](https://developers.redhat.com/articles/2022/02/15/write-kubernetes-java-java-operator-sdk#why_write_operators_in_java_)
