### ISSUE TITLE
java crd generate not working

### ISSUE THREAD

**Issue by chestarss** [fabric8io/kubernetes-client#3815]
### Describe the bug

crd to java pojo , some error when use java pojo

### Fabric8 Kubernetes Client version

5.10.1@latest

### Steps to reproduce

crd files
https://github.com/karmada-io/karmada/tree/master/charts/_crds/bases

`ls ~/project/karmada/charts/_crds/bases|xargs -I{} java-gen -crd bases/{} -dest /tmp/test`

### Expected behavior

project/karmada-java-client/target/classes/generated/io/karmada/work/v1alpha2/ResourceBindingSpecFluentImpl.java:19:78
java: 找不到符号
  符号:   类 ResourceBindingSpecFluent
  位置: 程序包 io.karmada.work.v1alpha2

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.20.12

### Environment

macOS

**Comment by chestarss** [comment]
maybe my pom.xml is error, where can i get java pojo pom.xml example

**Comment by manusa** [comment]
This feature hasn't been released yet. I understand that you built the tool yourself or that you downloaded it from the SNAPSHOTS [repo](https://oss.sonatype.org/content/repositories/snapshots/io/fabric8/java-generator-cli/)?

/cc @andreaTP

**Comment by chestarss** [comment]
> 

yes

**Comment by andreaTP** [comment]
Hi @chestarss ! Thanks for your interest in this feature and for testing it out!

I managed to compile the output of the provided CRDs using a pom file like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <artifactId>example</artifactId>
  <groupId>io.fabric8</groupId>
  <version>0.0.1</version>
  <name>Example</name>
  <properties>
    <maven.compiler.release>11</maven.compiler.release>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
  </properties>
  <dependencies>
    <dependency>
      <groupId>io.fabric8</groupId>
      <artifactId>kubernetes-client</artifactId>
      <version>5.12.0</version>
    </dependency>
    <dependency>
      <groupId>io.sundr</groupId>
      <artifactId>builder-annotations</artifactId>
      <version>0.50.3</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.18.22</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>javax.validation</groupId>
      <artifactId>validation-api</artifactId>
      <version>2.0.1.Final</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
</project>
```

Please be aware that the generator is outputting a number of warnings that will be solved by #3802 or #3817

**Comment by chestarss** [comment]
![image](https://user-images.githubusercontent.com/11288347/153108016-c106ccee-278c-4470-9f37-2a9c38c2fbe2.png)

**Comment by chestarss** [comment]
I can't import generated builder class.  what configure missing?  target/generated  add to classpath?

**Comment by andreaTP** [comment]
@chestarss the problem is in your build configuration, not related to anything produced by this repository.

You can find here a minimal example that shows the "karmada" generated code does compile:
https://github.com/andreaTP/example_karmada

and can be used as expected:
https://github.com/andreaTP/example_karmada/blob/main/src/main/java/Main.java

**Comment by chestarss** [comment]
> @chestarss the problem is in your build configuration, not related to anything produced by this repository.
> 
> You can find here a minimal example that shows the "karmada" generated code does compile: https://github.com/andreaTP/example_karmada
> 
> and can be used as expected: https://github.com/andreaTP/example_karmada/blob/main/src/main/java/Main.java

thank you very much
