### ISSUE TITLE
Exception is buried which makes usage very hard

### ISSUE THREAD

**Issue by mariusstaicu** [fabric8io/kubernetes-client#3818]
### Describe the bug

Whenever using auto configuration with "EC" algo the underlying http client fails with exception:
**_JcaPEMKeyConverter is provided by BouncyCastle, an optional dependency. To use support for EC Keys you must explicitly add this dependency to classpath._**

However, this exception is buried in _HttpClientUtils.java:214:_

`
    } catch (Exception e) {
      KubernetesClientException.launderThrowable(e);
    }
`
This causes the users of this library to look for the source of the problem in other places.

### Fabric8 Kubernetes Client version

other (please specify in additional context)

### Steps to reproduce

1. on kubernetes-client version 5.12.1
2. try to configure to a local k3s using auto config - it will be using EC algo
3. the result is that the client is burying the root cause mentioned before and it will issue a confusing exception like this: **_Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target_** which is very confusing, since this is not the cause of the problem

### Expected behavior

The main cause of the failure shown in logs should be **_JcaPEMKeyConverter is provided by BouncyCastle, an optional dependency. To use support for EC Keys you must explicitly add this dependency to classpath._** and not **_Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target_**.

This can be done by not burying the initial exception.

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

1.20.12

### Environment

Linux

### Additional context

fabric8 kubernetes-client version: 1.15.2
kubernetes cluster: k3s

**Comment by shawkins** [comment]
This was not an intentional swallowing of that exception, it should be throwing instead.  After #3654 we'll add the appropriate throws.
