### ISSUE TITLE
[java-gen] Dockerize java-generator-cli

### ISSUE THREAD

**Issue by OneCricketeer** [fabric8io/kubernetes-client#3820]
### Is your enhancement related to a problem? Please describe

I would like to use the features developed in #3693 without necessarily requiring a JVM on the host machine. 

### Describe the solution you'd like

Packaging the tool as a Docker container would help. 

### Describe alternatives you've considered

Write own `Dockerfile` and `wget` the binary (if it were actually published).

**Comment by manusa** [comment]
I'm not sure distributing a container image is the best approach to solve the described problem. i.e. you're basically substituting a requirement, from a JVM to a Docker/Container image runner/engine

If the idea of the CLI is popular and goes forward, then it might be easier to generate binaries for the major platforms.

Personally, I feel that a source generator via a Maven Plugin or an annotation processor would be the most natural way to go.

I'm really curious about the use case where you are generating Java files and don't have a JVM available (e.g. what are those files used for then?). Is it some step in a CI job?

**Comment by OneCricketeer** [comment]
@manusa We have used golang operator-sdk to define and create CRDs. But we also parse and build those objects from a Java API.

The Go project doesn't have the benefit of using a Maven plugin.

We also don't have full access to the CI/CD systems, but running containers (or downloading a binary, I suppose) is supported

**Comment by manusa** [comment]
As I understand, you want to generate those Java files from the Go Operator project.
How are you going to distribute those files then? I understand, you would have some similar troubles to package and deploy these artifacts.

My understanding of the workflow for this feature was quite the opposite: Me, as a consumer/client of a (non-managed) operator, I want to generate typed classes to interact with it. I include the CRDs as resources and I can (automagically) use the generated Java types with the Fabric8 client.

From the opposite PoV, a consistent behavior would be to distribute not only Java types, but types for any other programming language.

Anyway, let's see if more people chime in.

**Comment by OneCricketeer** [comment]
> How are you going to distribute those files then?

Artifactory Maven repo, ideally 

> similar troubles to package and deploy these artifacts. 

Possibly, but I can run a separate container with Maven/Gradle and mount the generated Java files to get class files, then package and deploy those. But that would actually require a valid POM/Gradle file for the project, which is currently not generated. 

> not only Java types, but types for any other programming language 

Like swagger-codegen, I completely agree.

**Comment by OneCricketeer** [comment]
To clarify the above idea, here is the workflow:

Steps:
1. Build Go operator - this results in a CRD definition, I believe (another team controls this)
2. With CRD YAML in hand, we can download it from Git repo and use `java-gen` command to get `.java` files
3. With those source-files, somehow compile them; possibly [hand-crafting a POM xml](https://github.com/fabric8io/kubernetes-client/issues/3815#issuecomment-1032464550)
4. Hook in `mvn package deploy` to (3) and deploy to company Maven repo
5. Add (4) dependency to external Java project. 

Goal: Replace manual copy-paste between Go `struct`  `json:` tags and Java classes w/ Jackson annotations like we do now. 

Github actions / Gitlab / CircleCI / TravisCi Runners can only(?) run containers, from what I understand, thus why I see the reason to containerize the tool, even if it still early release stage.
