### ISSUE TITLE
What is the latest version based on Java 8

### ISSUE THREAD

**Issue by saowu** [fabric8io/kubernetes-client#3828]
### Discussed in https://github.com/fabric8io/kubernetes-client/discussions/3827

<div type='discussions-op-text'>

<sup>Originally posted by **saowu** February  9, 2022</sup>
What is the latest version based on Java 8</div>

**Comment by saowu** [comment]
![image](https://user-images.githubusercontent.com/33569619/153197907-0dc38cd4-d847-4a71-9ea6-8e2db3479733.png)
Current Java environment 8

**Comment by manusa** [comment]
That's just a reference to this
https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/19fb8f93c59dfd791f62d41f332db9e306bc1422/src/java.base/share/classes/java/io/InputStream.java#L699-L709
