### ISSUE TITLE
Using both v4 and v5 customeResource is not compatible

### ISSUE THREAD

**Issue by chestarss** [fabric8io/kubernetes-client#3839]
### Describe the bug

I have two customResource  dependencies from outside,  one is a v4 based CR implementation and the other is v5 based

4.x CR like this
```
public class DnaApp extends CustomResource implements Namespaced

public class DnaAppList extends CustomResourceList<DnaApp>
```

5.x CR like this
```
@io.fabric8.kubernetes.model.annotation.Version("v1alpha1")
@io.fabric8.kubernetes.model.annotation.Group("policy.karmada.io")
public class PropagationPolicy extends io.fabric8.kubernetes.client.CustomResource<PropagationPolicySpec, java.lang.Void> implements io.fabric8.kubernetes.api.model.Namespaced {
}
```

In 4.x io.fabric8.kubernetes.client.CustomResource not have spec fileds,
so i can't call like this
```
PropagationPolicy propagationPolicy = new PropagationPolicy();
propagationPolicy.setSpec(xxx) ; //not have this method
```

When I upgraded the client to v5, the v4 CR DnaApp started not working again.

 berfore code
```
OpenShiftClient client = this.getClient(cluster);
        CustomResourceDefinitionContext dnaAppCrdContext = this.getDnaAppCrdContext();
        MixedOperation<DnaApp, DnaAppList, DoneableDnaApp,
                io.fabric8.kubernetes.client.dsl.Resource<DnaApp, DoneableDnaApp>> dnaAppClient = client
                .customResources(dnaAppCrdContext, DnaApp.class, DnaAppList.class, DoneableDnaApp.class);
```

after upgraded 5.x i remove Doneable but not compatiable,
because DnaAppList implement from CustomResourceList not KubernetesResourceList.

```
MixedOperation<DnaApp, DnaAppList,
                io.fabric8.kubernetes.client.dsl.Resource<DnaApp>> dnaAppClient = client
                .customResources(dnaAppCrdContext, DnaApp.class, DnaAppList.class);
```

### Fabric8 Kubernetes Client version

5.10.1@latest

### Steps to reproduce

1、both use 4.x customResource vs 5.x customResource

### Expected behavior

how can  working together 4.x customResource vs 5.x customResource

### Runtime

OpenShift

### Kubernetes API Server version

1.22.3@latest

### Environment

Linux, macOS

**Comment by rohanKanojia** [comment]
@chestarss : Did you had a look at our migration guide?

https://github.com/fabric8io/kubernetes-client/blob/master/doc/MIGRATION-v5.md

**Comment by chestarss** [comment]
> @chestarss : Did you had a look at our migration guide?
> 
> https://github.com/fabric8io/kubernetes-client/blob/master/doc/MIGRATION-v5.md

yes, i read it .
I can't update the CR implementation because it's an external dependency

**Comment by manusa** [comment]
I understand that you're trying to use CustomResource classes generated with different major versions of the client. This is **not** possible.
