### ISSUE TITLE
Pod.evict return and exception handling

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3853]
### Is your enhancement related to a problem? Please describe

Pod.evict returns Boolean, but can only be two valued. The 429 is indistinguishable from a 404 - in most other api calls 404 would be an exception.

### Describe the solution you'd like

It should return a boolean and throw an exception on a 404.

**Comment by manusa** [comment]
I don't think #3844 takes care of this issue

**Comment by shawkins** [comment]
> I don't think https://github.com/fabric8io/kubernetes-client/pull/3844 takes care of this issue

No, this issue hasn't been worked yet.

**Comment by shawkins** [comment]
Other places in the api returning Boolean should likewise be changed to boolean - unless for some reason three valued logic is expected.

**Comment by shawkins** [comment]
This will need to wait until #3845 to reduce conflicts.
