### ISSUE TITLE
How to create clients via api

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3865]
### Is your enhancement related to a problem? Please describe

After #3654 DefaultKubernetesClient and DefaultOpenShiftClient ended up in their respective -client modules.  So we need a way to construct clients via just the api.

### Describe the solution you'd like

An initial proposal was https://github.com/fabric8io/kubernetes-client/pull/3654/commits/2d22886a71419d0fa5c35a20b752ade204973619 - to introduce client specific builders.  

They are using reflection - if that is not a good choice (for example for quarkus), we can switch to a service loader, or even do like slf4j and create/remove dummy classes in the api modules.

Whatever the outcome of this is, the highest level construct should be used to hold state for things like the Handlers - so that we can avoid static references.

### Describe alternatives you've considered

Alternatives could include just a single client KubernetesClientBuilder:

new KubernetesClientBuilder().withConfig(...).build().adapt(OpenShiftClient.class)

**Comment by shawkins** [comment]
cc @rohanKanojia @metacosm @manusa

**Comment by manusa** [comment]
My personal preference would be for the single builder approach + adapt.

I guess that this is the closest approach to what we already have. In addition to minimize breakages, it's an existent pattern, so some users should already know their way around it.

I understand that the resulting scenarios would be:
- Recommended approaches:
  - `KubernetesClient kc = new KubernetesClientBuilder()./* configure */.build();`
  - `OpenShiftClient oc = new KubernetesClientBuilder()./* configure */.build().adapt(OpenShiftClient.class);` (requires openshift-client-api module)
  - `CamelKClient cc = new KubernetesClientBuilder()./* configure */.build().adapt(CamelKClient.class);` (requires extension module)
- Alternatives:
  - Legacy support: `KubernetesClient kc = new DefaultKubernetesClient()` (requires kubernetes-client module)
  - `OpenShiftClient oc = new DefaultOpenShiftClient()` (requires openshift-client module)

**Comment by shawkins** [comment]
The consideration behind a separate OpenShiftClientBuilder was to explicitly reference the OpenShiftConfig.

**Comment by shawkins** [comment]
It sounds like we'll keep just a single builder, and add a doc note about specific configs.  The only danger is that the config must not be modified by the logic in the creation of the base client, otherwise the OpenShift specific nature of the config will be lost.

Also AutoAdaptableKubernetesClient - should be deprecated

**Comment by manusa** [comment]
> Also AutoAdaptableKubernetesClient - should be deprecated (since it's in -client, it is by default)

#3921
