### ISSUE TITLE
[java-gen] Support default attributes

### ISSUE THREAD

**Issue by OneCricketeer** [fabric8io/kubernetes-client#3869]
### Describe the bug

`default` fields are not converted into the Java models. 

Example: https://github.com/fabric8io/kubernetes-client/blob/1d7d869681faafe166e5581bcde0f928499ef765/java-generator/core/src/test/resources/akka-microservices-crd.yml#L44-L47

This includes all types

- `integer`
- `boolean`
- `string`
- `object`
- etc.

### Fabric8 Kubernetes Client version

5.10.1@latest

### Steps to reproduce

1. Have CRD with `default` attributes
2. Use `java-gen` util
3. Inspect Java model output to see defaults are not applied via field attributes or in getter methods

### Expected behavior

For the above example, I would expect

```java
@JSONProperty("replicas")
int replicas = 1;
```

Or 

```java
@JSONProperty("replicas")
Integer replicas;

public Integer getReplicas() {
  return Optional.ofNullable(this.replicas).orElse(1); // example
}
```

I understand that object types will be more complicated, but maybe some `FooSpec_DEFAULT` instance could be created. 

### Runtime

Kubernetes (vanilla), minikube

### Kubernetes API Server version

1.21.6

### Environment

Linux, macOS

**Comment by andreaTP** [comment]
Just to make sure we take the specification into account when we implement this (it's rather tricky):
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#defaulting
and
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#defaulting-and-nullable

Additional note on the need to tweak Jackson as well, probably something on those lines:
```java
@JsonSetter(nulls=Nulls.SKIP)
@JSONProperty("replicas")
Integer replicas = 1;
```

**Comment by fabiobrz** [comment]
I was playing a bit with this, and have a potential - although not complete - candidate. 
While working on the implementation I was wondering whether it would be good to base the changes on top of https://github.com/fabric8io/kubernetes-client/pull/3817, since that would take the nested structure package into account, which could be key for properly setting object-type defaults.

WDYT @andreaTP? (CC @manusa in case you'd want to assign)

**Comment by andreaTP** [comment]
In #3817 we are making a lot of improvements toward a more correct generation.

At this point almost anything else will conflict with it, I hope we can prioritize a review there 🙂 .

Also I do believe that an implementation of `default` would greatly benefit from the changes of the nested structure (e.g. the absolute naming of all types)

**Comment by fabiobrz** [comment]
> In #3817 we are making a lot of improvements toward a more correct generation.
> At this point almost anything else will conflict with it, I hope we can prioritize a review there slightly_smiling_face .

+1

> Also I do believe that an implementation of `default` would greatly benefit from the changes of the nested structure (e.g. the absolute naming of all types)

Exactly what I meant. Right then, I'll have a try on your topic branch. 
Thanks for your feedback @andreaTP !
