### ISSUE TITLE
OSGI handling of HttpClient implementations

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3878]
This is tricky, so consider it more like thinking out loud rather than a change request.

I would move the `kubernetes-httpclient-okhttp` to it's own feature, along with it's dependencies. I would also provide a feature for `kubernetes-httpclient-okhttp`.

Then I would either decouple `kubernetes-client` from `kubernetes-httpclient-okhttp` and let users decide what to use or just refer to it (but most probably the first). The former adds an extra step for the user, the latter is less flexible. In both cases the idea is that we communicate this way which are the pluggable parts.

Again, this is something that we can do afterwards. I prefer merging this faster and add this touches later on.

_Originally posted by @iocanel in https://github.com/fabric8io/kubernetes-client/pull/3857#discussion_r809746974_

**Comment by iocanel** [comment]
I can see the following approaches:

1. Expose a managed service for the `KubernetesClient` in the API that will use the `HttpClient` implementation as a service.

2. Expose nothing in the API and just expose a fat `KubernetesClient` object from the downstream modules.

Both approaches are fine by me.

**Comment by manusa** [comment]
Not sure if this is applicable yet, specially as exposed in the issue description.
