### ISSUE TITLE
Filtering resources by labelselectors with informers (versus watchers)

### ISSUE THREAD

**Issue by MichaelVoegele** [fabric8io/kubernetes-client#3879]
### Is your enhancement related to a problem? Please describe

I have written a controller that deploys some egress-http-proxy (squid) for our users when they create a configmap with certain data. Those configmaps have a specific label to identify them, e.g. my-company/kind=egress-http-proxy.

I have originally written the code using a watcher as follows:
client.configMaps().inAnyNamespace().withLabel("my-company/kind", "egress-http-proxy").watch(new Watcher<ConfigMap>() {...}

-> with watcher there is the possiblility to filter the configmaps by label

I have now switched my code from watcher to informer:

SharedInformerFactory sharedInformerFactory = client.informers();
SharedIndexInformer<ConfigMap> egressHttpProxyInformer = sharedInformerFactory.sharedIndexInformerFor(ConfigMap.class, 15 * 60 * 1000L);
egressHttpProxyInformer.addEventHandler(new EgressHttpProxyEventHandler(client));

As with the watcher, I would like to filter the configmaps to be informed about with a label, but I was not able to figure out a way on how to achieve this. I am now filtering out the configmaps in the code when receiving the events. But with the store that is synced with the informers, the memory footprint of the application gets quite high (we have one very large cluster with over 38000 configmaps, from which about 1000 are egress-http-proxy configmaps).

I know an option would be to introduce a custom resource for the purpose (like EgressHttpProxy), then the filtering wouldn't be required, but I am interested in the possibility anyway.

Questions:
1. Is there already a possibility to filter the resources to be informed about by label?
2. If not, is there a specific reason, why this option is not offered?
3. Would it be an idea to support that? -> feature request

Thanks a lot for your reply.

Michael

### Describe the solution you'd like

I would like to be able to filter the resources to be informed about with labels.

**Comment by shawkins** [comment]
> Is there already a possibility to filter the resources to be informed about by label?

Recent versions of fabric8 support Informable:

client.configMaps().inAnyNamespace().withLabel("my-company/kind", "egress-http-proxy").inform

That will create an informer with all of the filtering options at that context.

**Comment by MichaelVoegele** [comment]
Hey @shawkins, thank you very much for your quick reply, that's exactly what I was looking for. I already changed my implementation to this and it looks good. Awesome!
