### ISSUE TITLE
Update v5.12.1 release note doc

### ISSUE THREAD

**Issue by Yikun** [fabric8io/kubernetes-client#3882]
### Is your enhancement related to a problem? Please describe

We might need to doc "autoConfiguration" changes in https://github.com/fabric8io/kubernetes-client/releases/tag/v5.12.1
for fabric8io/kubernetes-client@81c11ca.

It bring some behavior changes on "autoConfiguration". I know it is right fix, : )

Before this, if users specify a wrong context, autoconfigure will use current context instead of wrong context.

### Describe the solution you'd like

We'd better to add note for users to take care of this change.

### Additional context

FYI, we [hit this changes](https://github.com/apache/spark/pull/35557#issuecomment-1046609601) in here.

**Comment by Yikun** [comment]
cc @manusa

**Comment by Yikun** [comment]
And also I just want to make sure what's the use of this.autoConfigure? : )

https://github.com/fabric8io/kubernetes-client/blob/81c11ca5c2044eac2cbebe5107945ec95011e8f4/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L242

 because, it's also a change (isn't be set after https://github.com/fabric8io/kubernetes-client/commit/81c11ca) when call `autoConfigration`.

**Comment by sunix** [comment]
It seems https://github.com/fabric8io/kubernetes-client/commit/81c11ca has been introduced in this PR https://github.com/fabric8io/kubernetes-client/pull/3796

**Comment by manusa** [comment]
Added note both to v5.12.1 (change was there), and to v5.12.2 so it gets notified in the mailing list too.

**Comment by Yikun** [comment]
@manusa Thanks!
