### ISSUE TITLE
The Watch.close interface should throw IOException rather than eating it.

### ISSUE THREAD

**Issue by hsaputra** [fabric8io/kubernetes-client#390]
The ``public interface Watch` has method close() that in implementation could throw IOException.

It is better to declare throw IOException in the `Watch` interface to client could handle the problem.

**Comment by jimmidyson** [comment]
Yeah good point. Websocket transport (which is the only transport we support with this client) is only available in Kubernetes 1.2+.

**Comment by hsaputra** [comment]
So, what is the best version for client for Kubernetes 1.1.x release?

**Comment by hsaputra** [comment]
Using 1.3.83 but seemed like getting 400 HTTP status when connecting to Kubernetes 1.1 API server

**Comment by jimmidyson** [comment]
For any operations or just watch?

**Comment by hsaputra** [comment]
So far I have seen it in watch

**Comment by jimmidyson** [comment]
Watch will only work with 1.2+, everything else would be compatible (with exception of things like replication sets that are only available in 1.2+ too).

**Comment by hsaputra** [comment]
So, is there any release that is designated to connect to Kub 1.1 releases?
