### ISSUE TITLE
Get a Shell access to a pod

### ISSUE THREAD

**Issue by ho-yasla** [fabric8io/kubernetes-client#3900]
Is there any REST API to open a shell like we do by command` kubectl exec -it {pod-name} -- /bin/bash` this opens a shell in the terminal and commands can be run inside the container.

I tried using exec API from the example and commands are executing also but there is an issue in it, for example:
If I want to check the current path by typing the command pwd, I get a response like /apps. If I type command cd ../ to go back and check the directory again, I get the same directory as /apps.

I need a shell-like access to a specific container in the pod, is there any way to do it?

**Comment by sunix** [comment]
Hello, @ho-yasla 
Could you provide a concrete example of what you have tried so far?

As far as I understand, you are trying to make several calls and these calls are not keeping the context.
If you wish to execute a set of commands in the same terminal, you should provide a complete shell script to the execute method.
For instance,
```
.exec("sh", "-c", "cd ../; ls; echo 'Hello world!'");
```
