### ISSUE TITLE
addEventHandlerWithResyncPeriod OnDelete triggered not correctly for POD of a JOB

### ISSUE THREAD

**Issue by yevsh** [fabric8io/kubernetes-client#3914]
### Describe the bug

I have a JOB that starts a pod that attached to it.

I want to get podInformer  event , once the POD is terminated, but the onDelete event is triggered while pod is still running. 

```
podInformer.addEventHandlerWithResyncPeriod(new ResourceEventHandler<Pod>() {
      @Override
      public void onAdd(Pod pod) {             
      }
      @Override
      public void onUpdate(Pod oldPod, Pod newPod) {              
      }
      @Override
      public void onDelete(Pod pod, boolean deletedFinalStateUnknown) {               
          handle(pod);
      }
  }, 10 * 20 * 1000L);
private void handle(Pod pod) {
   LOGGER.info("{}",pod.getMetadata().getName());
}
```

?

### Fabric8 Kubernetes Client version

5.10.1@latest

### Steps to reproduce

1. Start kubernetes JOB
2. wait till pod is started
3. event will be triggered while pod is still running

### Expected behavior

OnDelete event triggered after pod of the job is completed. 

### Runtime

OpenShift

### Kubernetes API Server version

1.21.6

### Environment

Linux

**Comment by shawkins** [comment]
onDelete is called only once the pod has been removed.  If you are watching the pod based upon some filtering, such as labels, if those labels are removed, that will be processed as a delete.

Just in case it's not clear - a resync emits update events for resources already in the cache and is not relevant to this example.

**Comment by yevsh** [comment]
Not sure I understood.

I am watching the pod with: oc get pods

but while job is still in "Running" state , OnDelete is called.

**Comment by shawkins** [comment]
> Not sure I understood.

How did you create the podInformer?  If it's filtering by a field that could change, then it's possible to see a delete event relative to that filter - for example if you are filtering on a label that gets removed, that will be processed as a delete.

If that is not the case, then you are likely looking at the wrong pod.  If you are sure that is the correct pod, try providing a reproducing class / project.

**Comment by yevsh** [comment]
` podInformer = kubernetesClient.pods().inNamespace("ns").inform();`

The pod is correct one, as 
`  LOGGER.info("{}",pod.getMetadata().getName());`

prints its name

**Comment by shawkins** [comment]
I cannot recreate what you are describing using the JobIT test in the project.  Please create a reproducer or a more complete log the events - that would highlight what you are seeing.

**Comment by yevsh** [comment]
will try to do this tomorrow, thanks.
