### ISSUE TITLE
Deprecate SerializationUtils

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#3916]
SerializationUtils + [Jackson Mixins](https://github.com/fabric8io/kubernetes-client/tree/f23c9707f5016bf5d1cfdefe3e599814277d760d/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/serializationmixins) seems like an old initiative to provide better serialization tooling. It seems that later on in the project Serialization class was implemented too (maybe in a different repo) and has since replaced most of what SerializationUtils does.

The logical step is to remove SerializationUtils now and figure out the best way to cover for the functionality gap (shall we keep the mixins? shall we provide specific mapper override for ReplicationControllers? etc.)

---

Possibly related to #3796 

Also this yaml mapper differs from the one in Serialization - dumpAsYaml, should just be Serialization.asYaml.

dumpWithoutRuntimeStateAsYaml is really specific to ReplicationControllers - seems like it should be moved / renamed - maybe introduce ReplicationContollerResource.getYaml()

_Originally posted by @shawkins in https://github.com/fabric8io/kubernetes-client/issues/3866#issuecomment-1049943700_

**Comment by shawkins** [comment]
PatchUtils already understands the basic ObjectMetaMixIn, but does not have specific logic to strip the status.  That seems like something that could be generalized - but it requires knowing if status is a subresource.  This logic would also be useful to have should we need to implement the apply annotation.
