### ISSUE TITLE
Adapting api and checks performed

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3922]
ExtensionAdapter/ ExtensionAdapterSupport / APIGroupExtensionAdapter: 
- APIGroupExtensionAdapter is broken - could be made to work using calls to getApiResources(apiVersion) - but the getAPIGroupName as an apiVersion is not consistently specified.  In some classes it's just group, others just version, and others the full apiVersion.
- ExtensionAdapterSupport caching strategy is not generally safe, there could be a timing issue wrt the initial ask for support or you could later remove the extension.  Could just be a check of getApiGroup(name) rather than investigating the rootPaths
- In either of the above cases, a similar strategy as https://github.com/shawkins/kubernetes-client/compare/extension-api...shawkins:extension-mock?expand=1 could be used to intercept or even provide implementations for getApiGroup and getApiResources to provide mock support.
- OpenShift is the odd man out as it checks across everything for at least one openshift.  That makes it more involved to provide alternative BaseClient logic (not simply based upon the client class type).

My general question is how much of this is useful to implement / retain?  Possibilities include:
- make this work as originally envisioned - isAdaptable and adapt will both check for support at both the overall client and api level.  Caching of support may need to be refined to have a timeout.  It may be better to have an exclusion list on EnableKubernetesMock of supported clients, rather than an inclusion list.
- Expanding on the previous comment - separate the notion of isAdaptable and adapt.  adapt could do no checks (neither in ExtensionAdapter nor BaseClient) of support, and isAdaptable could be deprecated/renamed to isSupported - and potentially do no caching.  The idea would be that clients would be making only infrequent calls to isSupported, but adapt should generally be expected to work and is called both internally and by clients.

_Originally posted by @shawkins in https://github.com/fabric8io/kubernetes-client/issues/3876#issuecomment-1054317024_

**Comment by manusa** [comment]
As agreed, we should deprecate `Client#isAdaptable` method and point to the new `isSupported` method. The new behavior of `isAdaptable` checks if the **client** can be converted/adapted to the Extension specific client implementation. With the current code-base isAdaptable resulting in false would only be possible in the case of OpenShift: a user has a dependency to the OpenShift Client API, but not to the OpenShift Client module (the call client.isAdaptable(OpenShiftClient.class) or client.adapt(OpenShiftClient.class) would fail).

The `isSupported` method checks if the configured cluster actually supports the Extension (is OpenShift, has the required CRDs deployed, etc.). The value is not cached, so for every invocation the check is performed.
