### ISSUE TITLE
Shared informer expose cache enablement

### ISSUE THREAD

**Issue by cr-moriluz** [fabric8io/kubernetes-client#3938]
We ran into a problem with shared informer's memory usage (java 11, fabric v5.12.1), it seems that for big clusters with thousands of pods the cache gets too big to keep in-memory and our heap space ran out. We can increase the memory limits but that would also grow in time as we deploy our app on bigger clusters. See object usage from heapdump:

<img width="1239" alt="Screen Shot 2022-03-01 at 18 48 40" src="https://user-images.githubusercontent.com/54932893/156929522-5e225358-f85f-4b3b-8917-8ecc8fbb6697.png">

Since the cache is created per resourceType we watch as well, it can get pretty hectic. Is there anyway to limit the cache for such cases or optimize the memory usage in a different way? So far we've increased the resync period to 30 minutes and limited the number of threads given to the informer which dropped us down to around 1GB-1.5GB, but its a short term solution as we will need to add more resourceTypes soon and deploy on much bigger clusters.

Any input would help.

**Comment by shawkins** [comment]
How many informers are you creating?  okhttp currently uses two threads per watch / informer.

Based upon your heap, it seems like there may be a huge event backlog - each of the SerialExecutor lambda instances should indicate an item that an event has yet to be processed.

> So far we've increased the resync period to 30 minutes

Do you even need a resync?

> limited the number of threads given to the informer

That could explain the backlog.  If you use the dsl Informable.inform method that will not use a separate thread for event handling - and instead reuse the okhttp socket processing thread.

> Is there anyway to limit the cache for such cases or optimize the memory usage in a different way?

Other than the considerations above, there's not a lot you can currently do - but there will be a even more options in fabric8 6.

**Comment by cr-moriluz** [comment]
Thanks @shawkins! referring to the SerialExecutor instance, do you mean it could be just several huge events? I assume theres no current way to protect the informer from such cases.. 

I do notice it can happen after a long while where the informer behaves nicely. The app can run for a week or so and all of the sudden the heap spikes and the heapdump shows the SerialExector as the main blame thats hold 50% of the memory.

![Screen Shot 2022-03-10 at 13 56 24](https://user-images.githubusercontent.com/54932893/157657075-326ee714-1763-40ca-8be2-0a371e7fda53.png)

**Comment by shawkins** [comment]
No, this shouldn't be about the size of the events, but the number of them.  The SerialExecutor is just a gate keeper.  It makes sure that events are processed in an ordered manner.  If its executor threads are held by other work, then it will be unable to work down its queue.

**Comment by manusa** [comment]
Hi @cr-moriluz 
We released 6.0.0-RC1 last week. I'm not sure if you could give it a try and see if some of the new options suit your needs. Also if the overall performance and thread handling improvements are working for you.
It'd be great to have your feedback ;)
