### ISSUE TITLE
DefaultKubernetesClient namespace resolution

### ISSUE THREAD

**Issue by luismoramedina** [fabric8io/kubernetes-client#394]
Hi, we are working on getting services of the current namespace from a pod, we are using the *DefaultKubernetesClient*. This client does not load automatically the namespace because is using a KUBERNETES_NAMESPACE environment variable that is not present on the openshift projects.

We have read about another ways to resolve the namespace:

1. Use /var/run/secrets/kubernetes.io/serviceaccount/namespace file (http://kubernetes.io/docs/user-guide/accessing-the-cluster/#accessing-the-api-from-a-pod). For kubernetes 1.2 and later.

2. The POD_NAMESPACE environment variable, for earlier versions. See the kubernetes client code: https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/clientcmd/client_config.go#L341-L342

What kubernetes version supports the fabric8 kubernetes-client?

Are you planning to support the way kubernetes 1.2 resolves current namespace (as described in point 1.)? Are you interested in a pull request with this behaviour?

Thank you.

**Comment by iocanel** [comment]
@luismoramedina: the idea is to support the latest version possible and pull request are always welcome :-)

**Comment by jimmidyson** [comment]
Fixed by #395
