### ISSUE TITLE
Scaling StatefulSet filtered using label selectors

### ISSUE THREAD

**Issue by bhavin192** [fabric8io/kubernetes-client#3948]
### Is your enhancement related to a problem? Please describe

I'm trying scale a StatefulSet by selecting it using its labels. For example, kubectl allows following:
```console
$ kubectl scale statefulset -l release=yb,app.kubernetes.io/name=yb-tserver --replicas=4
statefulset.apps/yb-yugabyte-yb-tserver scaled
```
But when we filter StatefulSets with label selectors, the `scale()` method is not there. 

### Describe the solution you'd like

I'm thinking of something similar like this:
```java
client
    .apps()
    .statefulSets()
    .withLabel("release", "yb")
    .withLabel(appLabel, "yb-tserver")
    .scale(4);
```

### Describe alternatives you've considered

So far I have tried using `list()`, and then getting the first StatefulSet out of it. But when I tried to load the StatefulSet into client, the `scale()` method was not present. So, I had to use the `metadata.name`.

```java
StatefulSet sts =
    client
	.apps()
	.statefulSets()
	.withLabel("release", "yb")
	.withLabel(appLabel, "yb-tserver")
	.list()
	.getItems()
	.get(0);

// This was not possible (should I create a separate issue for this?)
client.resource(sts).scale(4);

// I had to do this instead
client
    .apps()
    .statefulSets()
    .withName(sts.getMetadata().getName())
    .scale(4);
```

### Additional context

When `kubectl` finds multiple StatefulSets filtered the label selectors, it just scales all of them.

```console
$ kubectl scale statefulset -l release=yb --replicas=4
statefulset.apps/yb-yugabyte-yb-master scaled
statefulset.apps/yb-yugabyte-yb-tserver scaled
```

**Comment by shawkins** [comment]
// This was not possible (should I create a separate issue for this?)
client.resource(sts).scale(4);

That won't be possible because we don't know the type of Resource to return.  At a minimum you'd have to specify
client.resource(sts, RollableScalableResource.class).scale(4); - and then you'd have to cast to RollableScalableResource<StatefulSet>

Alternatively fabric8 6 will support:

client.apps().statefulSets().withItem(sts).scale(4);

@manusa @rohanKanojia is resource a better method name than withItem here?

For now you would do something like:

```
var statefulSets = client.apps().statefulSets();
statefulSets
  .withLabel("release", "yb")
  .withLabel(appLabel, "yb-tserver")
  .list().getItems()
  .forEach(s -> statefulSets.withName(s.getName()).scale(4));
```

I think we can easily make that better with an enhancement that would add a resourceList or similar method that would return a List of the Resource subclasses:

```
var statefulSets = client.apps().statefulSets();
statefulSets
  .withLabel("release", "yb")
  .withLabel(appLabel, "yb-tserver")
  .resourceList().forEach(s -> s.scale(4));
```

**Comment by bhavin192** [comment]
> That won't be possible because we don't know the type of Resource to return. At a minimum you'd have to specify
client.resource(sts, RollableScalableResource.class).scale(4); - and then you'd have to cast to RollableScalableResource<StatefulSet>
>
> Alternatively fabric8 6 will support:
> 
> client.apps().statefulSets().withItem(sts).scale(4);

Right, that makes sense. This new method seems to be useful. 

Thank you for the `forEach` idea, that gives us same behavior as kubectl scale. `forEach` didn't come to my mind as I'm not much used to writing Java :smile: 

Does it makes sense to add an example for this in the docs/examples directory (I can add it if we agree to do so).

**Comment by shawkins** [comment]
> Does it makes sense to add an example for this in the docs/examples directory (I can add it if we agree to do so).

Yes, an example would be good.  Then either this issue or a new one could be for adding a resourceList method to clean this up a bit.

**Comment by shawkins** [comment]
a resources method was added with #3973 

```
client.apps().statefulSets()
  .withLabel("release", "yb")
  .withLabel(appLabel, "yb-tserver")
  .resources()
  .forEach(s -> s.scale(4));
```
