### ISSUE TITLE
Add an entry in the FAQ for the usage of the optional Bouncy Castle dependencies

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#3949]
Despite providing an explicit message, users still struggle to deal with the Bouncy Castle requirement.

Add an entry in the FAQ about the requirement to include the Bouncy Castle optional dependency.

#1798 #3818 https://github.com/quarkusio/quarkus/pull/21849#

**Comment by Urjaswi-2655** [comment]
@sunix  I want to work on this issue.
We have to add FAQ in [kubernetes-client](https://github.com/fabric8io/kubernetes-client)/[doc](https://github.com/fabric8io/kubernetes-client/tree/master/doc)/FAQ.md Right?
But what should be in the FAQ? 
I went through the issues 
https://github.com/fabric8io/kubernetes-client/pull/1798
 https://github.com/fabric8io/kubernetes-client/issues/3818 
https://github.com/quarkusio/quarkus/pull/21849
But did not understand anything. 
Through I have read about Bouncy Castle ( https://www.baeldung.com/java-bouncy-castle ) from here.

**Comment by siddhikhapare** [comment]
I want to make changes to fix this issue. @sunix @manusa Can you provide resource to me regarding this issue?

**Comment by siddhikhapare** [comment]
@manusa  @sunix I am beginner to contribute in kubernetes-client project so can you explain me which kind of usage of optional Bouncy Castle dependency entry should add in FAQ.md file? from where should I explore regarding this dependencies?

**Comment by sunix** [comment]
@siddhikhapare maybe something similar to https://github.com/quarkusio/quarkus/pull/21849/files#diff-fec6743f849bdff1c8d65b6cc45761d94ab2b5fdc5d6869e1db0243ecf0db63aR306-R321
@manusa is that correct ?

**Comment by manusa** [comment]
Something like that, yes. But ideally, you should try to experiment in your environment and see if that entry is accurate enough and your failing setup works after adding those dependencies.

**Comment by Devamparikh** [comment]
Hey, Can you assign this to me?

**Comment by Devamparikh** [comment]
Can someone review #4237 please?
