### ISSUE TITLE
Jdk HTTP client authentication failure

### ISSUE THREAD

**Issue by hypnoce** [fabric8io/kubernetes-client#3950]
### Describe the bug

Using the JDK http client, websocket connection (while using exec) returns 401.

### Fabric8 Kubernetes Client version

next (development version)

### Steps to reproduce

  public static void main(String[] args) throws IOException {
    final Config config = new ConfigBuilder().build();
    DefaultKubernetesClient kubeClient = new DefaultKubernetesClient(new JdkHttpClientFactory().createHttpClient(config), config);
    final PodResource<Pod> podPodResource = kubeClient.pods().withName("pod_name");
    podPodResource.file("/file").copy(Paths.get("file"));
  }

### Expected behavior

Kubernetes client should download the file

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.21.6

### Environment

Windows, Linux, macOS, Amazon, Azure, GKE, Dev Sandbox (workspaces.openshift.com), other (please specify in additional context)

**Comment by manusa** [comment]
Thanks for the early feedback

/cc @shawkins
