### ISSUE TITLE
chore: Add entry in changelog for new JDK HTTPclient

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#3956]
I had the same thought about removing the fix entry.  There are already some entries in the migration guide and the faq about the client usage.

Either with #3887 or another issue we'll need to add the jdk to the release build.

_Originally posted by @shawkins in https://github.com/fabric8io/kubernetes-client/pull/3951#discussion_r822621428_

**Comment by shawkins** [comment]
The changelog can point to the migration guide.  On the release build you are currently running that against java 8 right?

**Comment by manusa** [comment]
> On the release build you are currently running that against java 8 right?

Non-snapshot release pipeline is not ready yet, but the [SNAPSHOTs](https://github.com/fabric8io/kubernetes-client/blob/master/.github/workflows/release-snapshots.yaml) is (you can check this one for reference).

_**Once updated**_, the release is performed in three steps.
- All modules (except non-Java 8 compatible) are built using Java 8 and pushed to the staging repository
- Modules depending on a specific Java version (currently only httpclient-jdk) are built and pushed to the staging repository
- Staging repository is closed and released

For the final versions this should work fine.

For the SNAPSHOT version there are some inconsistencies in the generated artifacts, since they are timestamped. So the Java 11 module has a latter timestamp than the rest, but this doesn't seem to be a problem so far.
