### ISSUE TITLE
`PodOperationsImpl` should call `listener.onOpen` before marking the future as complete

### ISSUE THREAD

**Issue by AdrianFarmadin** [fabric8io/kubernetes-client#3957]
### Describe the bug

The `buildAsync` method in `OkHttpWebSocketImpl` class is called with `ExecWebSocketListener` as parameter.
The `ExecWebSocketListener` is opening `outputPipe` and `errorPipe` in `onOpen`.
If the `future` is completed before the `outputPipe` and `errorPipe` are open, then the consumer can read from the pipes before they are open.
This can cause `Pipe not connected` exception.

The pipes should be first open and then the future should be marked as complete.

### Fabric8 Kubernetes Client version

other (please specify in additional context)

### Steps to reproduce

1. Execute command with `PodOperationsImpl` and define `outPipe` and `errPipe`
2. Start reading lines from streams immediately after the command is started

```
ExecWatch watch = client.getPodResource(pod)
                .inContainer(getNameOfFirstContainer())
                .readingOutput(outputStream)
                .readingError(errorStream)
                .exec(args);
// start reading lines from outputStream and errorStream
```

### Expected behavior

No `Pipe not connected` exception

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

### Additional context

Fabric8 Kubernetes Client version > 5.11
Kubernetes API Server version: v1.20.11

**Comment by sunix** [comment]
Hey @AdrianFarmadin 
Thanks for reporting.
Are you working on this issue? Shall I assign it to you?

**Comment by AdrianFarmadin** [comment]
Hi @sunix, yes, I'm working on it. You can assign it to me

Pull request: https://github.com/fabric8io/kubernetes-client/pull/3958
