### ISSUE TITLE
Unable to edit Pods when Kubernetes cluster is running on AWS

### ISSUE THREAD

**Issue by lwander** [fabric8io/kubernetes-client#396]
Hey,

When I install a Kubernetes cluster using [these steps](http://kubernetes.io/docs/getting-started-guides/aws/) and the default profile, I'm unable to make edits to pods.

Here is code that breaks (in groovy). It's a degenerate example for the sake of being short.

```
def client = new DefaultKubernetesClient()
client.pods().inNamespace("default").withName("exiting-pod").edit().done() 
```

Originally, this threw the error message:

```Forbidden! User null doesn't have permission.```

which looked promising since the username wasn't populated, but that's simply because the default kubeconfig generated when creating an AWS kubernetes cluster doesn't populate a `users.user.username` field and only relies on the client certs. I switched the default context in the kubeconfig file to use the install-script populated basic auth pair and the error message changed to 

```Forbidden! User admin doesn't have permission.```

What's odd is that this exact code works on when the cluster is running on GKE, all operations on replication controllers work against this cluster on AWS, and I can run 

```kubectl edit pod existing-pod --namespace default```

without running into any permission errors, although it's using the same credentials that fail for that same command with this client library.

I'm using library version `kubernetes-api:2.2.102`.

**Comment by lwander** [comment]
The patch I submitted addresses the `null` in the first 403 message. (Unfortunately doesn't fix the issue).

**Comment by iocanel** [comment]
@lwander: It sounded extremely weird that it was working using ``kubectl`` but not by this client, so I followed your steps and managed to reproduce that myself.

After bumping my head against the wall for a while, I realised that kubectl edit is using the "PATCH" method, while the kubernetes-client is using the "PUT" method. 

Now, if we want to also use patch in the client I could see 2 possible approaches here:

1. Do a get, edit, compare and patch.
2. Don't get and just patch.

(1): is what we currently do, but without the compare part, which I am not sure if its something we can easily do or not.

(2): is having the edit command use a blank object so that we can create a patch out of it. This is also tricky.

@jimmidyson: Thoughts.

**Comment by jimmidyson** [comment]
@iocanel So PUT doesn't work but PATCH does? That seems a bit weird to me. Documentation on PATCH semantics are https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md#patch-operations. From those docs PUT is only supported when sending through the whole resource. Can you see if the whole resource is actually being sent through?

**Comment by iocanel** [comment]
@jimmidyson: kubectl edit uses patch and doesn't send the whole resource. Our client uses put and sends the whole resource.

**Comment by lwander** [comment]
Any thoughts on what to do about this?

**Comment by iocanel** [comment]
@lwander: for now I think that the way to work around it is to tune authorisation so that PUT is allowed.

**Comment by lwander** [comment]
Authorization on which end? Fixing kubernetes would only allow the client library to work with future version of kubernetes, which isn't ideal.

**Comment by iocanel** [comment]
@lwander: I think that its just a configuration thing. You need to fix kubernetes configuration to allow PUT requests from the specified user.

**Comment by lwander** [comment]
Ah, I see. I'll look into the config and report here how to get around this.

**Comment by dgarbus** [comment]
@iocanel: I do not believe that this particular issue is authorization-related. I am able to do a PUT using curl with the same credentials that the kubernetes client should be using (Kubernetes admin user):

```
curl -i --cacert /home/spinnaker/.kube/credentials/ca.pem --cert /home/spinnaker/.kube/credentials/admin-full.pem -H "content-type: application/json" -XPUT https://kubernetes-test.aws.example.com/api/v1/namespaces/example-apps/pods/helloworld-v000-4e8a8 -d '
> {
>   "kind": "Pod",
>   "apiVersion": "v1",
>   "metadata": {
>     "name": "helloworld-v000-4e8a8",
>     "generateName": "helloworld-v000-",
>     "namespace": "example-apps",
>     "selfLink": "/api/v1/namespaces/example-apps/pods/helloworld-v000-4e8a8",
>     "uid": "bc86fb3a-2120-11e6-9a25-0a262711386d",
>     "creationTimestamp": "2016-05-23T19:58:36Z",
>     "labels": {
>       "replication-controller": "helloworld-v000",
>       "test_tag": "test_value"
>     },
>     "annotations": {
>       "kubernetes.io/created-by": "{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicationController\",\"namespace\":\"example-apps\",\"name\":\"helloworld-v000\",\"uid\":\"bc861a91-2120-11e6-9a25-0a262711386d\",\"apiVersion\":\"v1\",\"resourceVersion\":\"4008278\"}}\n"
>     }
>   },
>   "spec": {
>     "volumes": [
>       {
>         "name": "default-token-jmzym",
>         "secret": {
>           "secretName": "default-token-jmzym"
>         }
>       }
>     ],
>     "containers": [
>       {
>         "name": "hello-phoenix",
>         "image": "quay.io/example/hello_phoenix:latest",
>         "ports": [
>           {
>             "name": "http",
>             "containerPort": 80,
>             "protocol": "TCP"
>           }
>         ],
>         "resources": {},
>         "volumeMounts": [
>           {
>             "name": "default-token-jmzym",
>             "readOnly": true,
>             "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
>           }
>         ],
>         "terminationMessagePath": "/dev/termination-log",
>         "imagePullPolicy": "Always"
>       }
>     ],
>     "restartPolicy": "Always",
>     "terminationGracePeriodSeconds": 30,
>     "dnsPolicy": "ClusterFirst",
>     "serviceAccountName": "default",
>     "serviceAccount": "default",
>     "nodeName": "ip-172-28-1-219.ec2.internal",
>     "securityContext": {},
>     "imagePullSecrets": [
>       {
>         "name": "example-registry"
>       }
>     ]
>   }
> }
> '
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Content-Type: application/json
Date: Mon, 23 May 2016 20:02:59 GMT
Transfer-Encoding: chunked

{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "helloworld-v000-4e8a8",
    "generateName": "helloworld-v000-",
    "namespace": "example-apps",
    "selfLink": "/api/v1/namespaces/example-apps/pods/helloworld-v000-4e8a8",
    "uid": "bc86fb3a-2120-11e6-9a25-0a262711386d",
    "resourceVersion": "4008680",
    "creationTimestamp": "2016-05-23T19:58:36Z",
    "labels": {
      "replication-controller": "helloworld-v000",
      "test_tag": "test_value"
    },
    "annotations": {
      "kubernetes.io/created-by": "{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicationController\",\"namespace\":\"example-apps\",\"name\":\"helloworld-v000\",\"uid\":\"bc861a91-2120-11e6-9a25-0a262711386d\",\"apiVersion\":\"v1\",\"resourceVersion\":\"4008278\"}}\n"
    }
  },
  "spec": {
    "volumes": [
      {
        "name": "default-token-jmzym",
        "secret": {
          "secretName": "default-token-jmzym"
        }
      }
    ],
    "containers": [
      {
        "name": "hello-phoenix",
        "image": "quay.io/example/hello_phoenix:latest",
        "ports": [
          {
            "name": "http",
            "containerPort": 80,
            "protocol": "TCP"
          }
        ],
        "resources": {},
        "volumeMounts": [
          {
            "name": "default-token-jmzym",
            "readOnly": true,
            "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
          }
        ],
        "terminationMessagePath": "/dev/termination-log",
        "imagePullPolicy": "Always"
      }
    ],
    "restartPolicy": "Always",
    "terminationGracePeriodSeconds": 30,
    "dnsPolicy": "ClusterFirst",
    "serviceAccountName": "default",
    "serviceAccount": "default",
    "nodeName": "ip-172-28-1-219.ec2.internal",
    "securityContext": {},
    "imagePullSecrets": [
      {
        "name": "example-registry"
      }
    ]
  },
  "status": {
    "phase": "Running",
    "conditions": [
      {
        "type": "Ready",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2016-05-23T19:58:38Z"
      }
    ],
    "hostIP": "172.28.1.219",
    "podIP": "10.2.16.8",
    "startTime": "2016-05-23T19:58:36Z",
    "containerStatuses": [
      {
        "name": "hello-phoenix",
        "state": {
          "running": {
            "startedAt": "2016-05-23T19:58:38Z"
          }
        },
        "lastState": {},
        "ready": true,
        "restartCount": 0,
        "image": "quay.io/example/hello_phoenix:latest",
        "imageID": "docker://sha256:10dca9255bcf4fcc0fe51c5d8a8fccf4ccc10faddf1d921c66d41f839d2693d4",
        "containerID": "docker://0a72fbb2264b2d252ff39e2066541e399a78b5af5cd1e3f631e3256ac5e36b04"
      }
    ]
  }
}
```

Editing this same pod fails with a 403 when executed by Spinnaker (with this client).

**Comment by jimmidyson** [comment]
Suspicious that both reports use client certs. Could someone please send the trace of the requests by setting log level to TRACE (depends on your slf4j logging implementation how you do that).

@iocanel Did you say you'd reproduced this?

**Comment by lwander** [comment]
I've been able to reproduce this with both client certs and basic auth.

**Comment by iocanel** [comment]
@jimmidyson: yeah I did reproduce it myself. 

I can't recall though if I tried a simple PUT from curl (which is something that I should to support my theory). I'll try again :-)

**Comment by lwander** [comment]
@jimmidyson can I set the log level when creating the k8s client?

**Comment by iocanel** [comment]
@lwander: check the examples project which does use debug logging.

**Comment by lwander** [comment]
This one? https://github.com/fabric8io/kubernetes-client/tree/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples

I think I'm missing it because I only see logging done by the code calling the client library.

**Comment by iocanel** [comment]
@lwander: So, the kubernetes-client is using slf4j for logging. This is actually an abstraction of the actual logging implementation. Regardless of what the ``code calling the client`` is using for logging, there should be a binding so that slf4j can hook to it.

The [examples](https://github.com/fabric8io/kubernetes-client/tree/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples) are using log4j2 for logging. so we add to the pom the log4j2/slf4 binding and they configure logging by modifying the log4j configuration file [log4j2.yml]( https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/resources/log4j2.yaml) file.

If your app is using something else for logging, just configure the logging of the app. If this is not enough then add proper slf4j binding.

**Comment by lwander** [comment]
I know very little Java and can't get the logging to start after an hour of twiddling with the build settings & classpath. Since you have a working example and know your way around this could you capture the log output during the failing operation?

**Comment by jimmidyson** [comment]
Thank you for trying - sorry it's not as easy as it could be (damn Java :-b). I'll try to reproduce tomorrow & work on a fix.

**Comment by lwander** [comment]
Thanks @jimmidyson

**Comment by jimmidyson** [comment]
@iocanel Did you repro this against a local/vagrant installation of kubernetes or on AWS? Don't suppose you have an env I can test against?

**Comment by lwander** [comment]
Friendly ping, any update on this?

**Comment by Cocotton** [comment]
I'd be interested in any updates too.

**Comment by emjburns** [comment]
Same here! Any update?

**Comment by jimmidyson** [comment]
Sorry haven't been able to look at it, other things to work on.

Would really appreciate it if someone has time to look at it - fix would be very welcome!

**Comment by dberuben** [comment]
Same issue here ... Any update?

**Comment by iocanel** [comment]
@jimmidyson: what more is to be done here? I thought that since the patch was introduced this should be considered fixed (and apparently I am wrong).

**Comment by jimmidyson** [comment]
@iocanel Well I thought so too...

Could anyone on this thread let us know if you're having the same problem with kubernetes-client 1.3.98? Also a minimal code example & a TRACE level log would be awesome as mentioned above.

**Comment by iocanel** [comment]
Also, I recall having issues with the way we patches are handled in openshift 1.2 but worked great in 1.3.0 alpha. Haven't tried with vanilla kubernetes though.

**Comment by lwander** [comment]
Going to update to client library and let you know

**Comment by lwander** [comment]
I think it's fixed! Thanks @iocanel and @jimmidyson

**Comment by jimmidyson** [comment]
Excellent! Thanks for letting us know @lwander.

**Comment by Cocotton** [comment]
Thanks!
