### ISSUE TITLE
Order of additionalPrinterColumns

### ISSUE THREAD

**Issue by stefanbethke** [fabric8io/kubernetes-client#3974]
### Is your enhancement related to a problem? Please describe

kubectl shows the additionalPrinterColumns in the order they are defined in the CRD. Unless I've missed it, it is not possible to influence the order of @PrinterColumns in the CRD. It seems to be ordered alphabetically.

I have two printer columns .status.milestone and .status.error, and I would like them printed in that order. However, right now error comes first.

I can work around this by manually swapping the entries in the CRD, and it's only cosmetic anyway, but it would be nice to have.

### Describe the solution you'd like

Some additional attribute like order or index that the generator uses to order the additionalPrinterColumns in the CRD.

### Additional context

See https://github.com/java-operator-sdk/java-operator-sdk/issues/1028

**Comment by manusa** [comment]
"duplicate" of #3153

/cc @metacosm @lburgazzoli
