### ISSUE TITLE
Bulk format the entire codebase

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3984]
### Is your task related to a problem? Please describe

To cut down on the amount of noise in PRs it would be good to bulk format everything now that we haven't seen additional issues with spotless.

### Describe the solution you'd like

Bulk format everything.  At worst the existing prs would need to be rebased, but generally the changes should be mergable.

**Comment by manusa** [comment]
I'd personally dislike this since it interferes a lot with the work done when figuring out bugs and "bisecting" them. It's much easier for me to reformat a contributor's (who might struggle with formatting) active PR in a subsequent commit. Maybe we can further discuss

**Comment by manusa** [comment]
> It seems like it's pretty infrequent that something needs back ported.

I hope you're right with this :sweat_smile: :wink:
