### ISSUE TITLE
How to check if a Deployment is ready with the mock server

### ISSUE THREAD

**Issue by subnetmarco** [fabric8io/kubernetes-client#3985]
### Is your enhancement related to a problem? Please describe

I am testing the creation of a new `Deployment` in a test with `@EnableKubernetesMockClient(crud = true)`. I can successfully create the `Deployment` and - in my test - watch that indeed it has been created:

```java
Watch watch = client.apps().deployments().inNamespace("ns1").watch(new Watcher<Deployment>() {
  @Override
  public void eventReceived(Action action, Deployment resource) {
    assertEquals(Action.ADDED, action);
    assertEquals("httpbin", resource.getMetadata().getName());
    eventLatch.countDown();
  }

  @Override
  public void onClose(WatcherException arg0) {
    // Do nothing
  }
});
```

What I am struggling with right now, is to close the loop and properly test that the `Deployment` is indeed running with the right amount of replicas (using the mock server), and I cannot seem to find any indication on how to do that. Any tips?

### Describe the solution you'd like

Instructions - or an example - to properly test that the `Deployment` is running with the proper amount of replicas.

**Comment by shawkins** [comment]
The mock support is not a full api server nor kubernetes platform, so entries that look like Pods are not created for a Deployment.  You'd have your test logic add them via crud operations or a KubernetesServer expectation.

**Comment by subnetmarco** [comment]
@shawkins thanks for the pointers. Do you know where I can find a pragmatic example for using ` KubernetesServer` expectation to change the status of a deployment over time in the test?

**Comment by rohanKanojia** [comment]
Could you please try something like this? In mocking watch during expectations mode, try sending a WatchEvent with Deployment status field updated to match ready fields https://github.com/fabric8io/kubernetes-client/blob/15ba0dd6c7e452c8f53905f23e3c22d35e9b1d9b/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ResourceTest.java#L254-L258
