### ISSUE TITLE
Exec didn't work when running against a http protocol url exposed by kubectl proxy

### ISSUE THREAD

**Issue by Evliess** [fabric8io/kubernetes-client#3986]
### Describe the bug

Exec didn't work when running against a http protocol url exposed by kubectl proxy

### Fabric8 Kubernetes Client version

5.10.1@latest

### Steps to reproduce

Reproduce steps:
1. Use kubectl proxy to expose API server
```
kubectl proxy --address='0.0.0.0' --accept-hosts='^*$'
```

2. Init the ApiClient
```
String MASTER_URL = "http://192.168.88.128:8001"; 
final ConfigBuilder configBuilder = new ConfigBuilder();
configBuilder.withMasterUrl(MASTER_URL);
Config config = configBuilder.build();
final KubernetesClient client = new DefaultKubernetesClient(config)
```
3. Call the ExecWatch API

```
ExecWatch ignore = newExecWatch(client, "default", "pod-example", columns, lines);

```
5. Hit the problem:

```
Caused by: java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196)
	... 5 more
```

BTW:
From the Apiclient, I can list all the pod in the namespace. The client is ok I think.

### Expected behavior

I can exec "df -h" command against the running pod.

### Runtime

minikube

### Kubernetes API Server version

1.22.3@latest

### Environment

Linux

**Comment by Evliess** [comment]
Resolved it by myself

**Comment by lwl8851206** [comment]
> Resolved it by myself

I had met the same issue , could you share how you fixed it ?

**Comment by shinunandakumar** [comment]
We are facing the same issue when executing commands inside the pod.
@Evliess can you explain how you fixed the issue ?
