### ISSUE TITLE
When the CA of Kube apiserver is not the root CA, the client will fail to initialize

### ISSUE THREAD

**Issue by lidajia** [fabric8io/kubernetes-client#3987]
### Describe the bug

The kubernetes-client inintialized failed, while the kube-apiserver's CA Contains multi-level CA.

### Fabric8 Kubernetes Client version

5.10.1@latest

### Steps to reproduce

deploy kube-apiserver with a Self signed sub CA，like this：
![ca](https://user-images.githubusercontent.com/7565495/159220773-c586061d-1e95-461d-a1ee-e05298ae1fee.png)

then init kubernetes client. see error：
![error](https://user-images.githubusercontent.com/7565495/159220458-f99ff529-c136-49a3-8c48-bdcd58d415f8.jpg)

### Expected behavior

the client init succeeded

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.20.12

### Environment

Linux

### Additional context

_No response

_

**Comment by lidajia** [comment]
keep active

**Comment by manusa** [comment]
I think this was actually tackled on v6.x. Please try with newer versions of the client and create a new issue in case it's not handled.
