### ISSUE TITLE
Can't get actual token for authorize on OpenShift private registry

### ISSUE THREAD

**Issue by russian-coder** [fabric8io/kubernetes-client#399]
I use basic authorization method:

```
OpenShiftConfig config = new OpenShiftConfigBuilder()
                .withPassword(password)
                .withUsername(userName)
                .withMasterUrl(masterURL)
                .withTrustCerts(true)
                .build();
```

How can I get authorization token like: `oc whoami -t?`

I need it for authorization on OpenShift private registry automatically.

**Comment by iocanel** [comment]
This is something that is currently not supported.

The client will only read ``.kube/config`` and not update it. So ``oc whoami -t`` will no work if u actually logged in via java client.

@jimmidyson: wdyt on this? should we update/create .kube/config?
