### ISSUE TITLE
Move ResourceID from java-operator-sdk 

### ISSUE THREAD

**Issue by lburgazzoli** [fabric8io/kubernetes-client#3991]
### Is your task related to a problem? Please describe

Move ResourceID from java-operator-sdk 

### Describe the solution you'd like

The Java Operator SDK provides an utility class that is used to track a resource namespace/name pair: [ResourceID](https://github.com/java-operator-sdk/java-operator-sdk/blob/main/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/ResourceID.java).

That class seems to be useful in general so it would be nice to move such class to this repo

**Comment by csviri** [comment]
Just to mention that in controller runtime, this is called `ObjectKey`. It might be beneficial to be consistent with naming.
https://github.com/kubernetes-sigs/controller-runtime/blob/c46b410039fdc9d620a4217bc7c63c5a7fffae46/pkg/client/interfaces.go#L31-L31

**Comment by rohanKanojia** [comment]
Umm, from the class name it's not quite clear to me what purpose it's serving. Plus there are no javadocs for it as well. Why is toString representation name is different from the actual class name?

**Comment by csviri** [comment]
> Why is toString representation name is different from the actual class name?

This is a bug, will fix it. Probably the rename was not smart enough :)

**Comment by manusa** [comment]
> Just to mention that in controller runtime, this is called ObjectKey.

We should be consistent with the Golang equivalents. ObjectKey or at most ResourceKey should be preferred.

Would this be used for SharedInformers? What are other use-cases and purposes for this Class? Where would this class live?

**Comment by csviri** [comment]
I'm not sure it makes sense in terms of fabric8 client. 

In JOSDK, it is used in eventing to represent the related resource. Like when a informer should trigger a reconciliation, the `ResourceID` is the id of the custom resource id what is managed by the controller.

**Comment by lburgazzoli** [comment]
The reason of my proposal is that the concept of ObjectKey is somehow already present in the fabric8 client:

- in [KubernetesResourceUtil](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/KubernetesResourceUtil.java#L127-L133) there is a `getQualifiedName` for which a qualified name is represented by a namespace + name
- informers have a concept of key mapper in which most of the time, the key extractor generates a namespace + name

So namespace + name is a thing and i.e. I'm using the same concept in one of my application (not an operator, so can't use ResourceID) but if ObjectKey would be a class defined from fabric8, then we sould have consistent naming across the stack to express this namespace + name  concept.

That said, I can keep my copy in my app if adding such class to fabric8 does not make sense  :)
