### ISSUE TITLE
Fabric8io watch container restart failure

### ISSUE THREAD

**Issue by lwQAQ** [fabric8io/kubernetes-client#4004]
### Describe the bug

K8s liveness probe monitors the container. When the container is unhealthy, the liveness probe restarts the container. Fabric 8io cannot monitor the container restart,o events received。Manually killing the container or container restart caused by container memory overflow can be monitored, but the liveness probe cannot

### Fabric8 Kubernetes Client version

5.8.0

### Steps to reproduce

watch container events

### Expected behavior

can watch container events

### Runtime

minikube

### Kubernetes API Server version

1.22.3@latest

### Environment

Windows

**Comment by manusa** [comment]
Containers are not Kubernetes resources. You should be able to achieve this by watching the Pods (maybe filter by name), and analyze the PodStatus to see what's going on.
You should be notified of both, the killed + deleted Pod, and its successor.
