### ISSUE TITLE
Remove outdated shared test classes in the kubernetes-client module

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#4006]
### Is your task related to a problem? Please describe

The classes contained in the following **test** package [io.fabric8.kubernetes.server.mock](https://github.com/fabric8io/kubernetes-client/tree/7ef49cd34e2de0d68422e17ce24fe15e48b63f17/kubernetes-client/src/test/java/io/fabric8/kubernetes/server/mock) are outdated and should be removed.

Same should apply for the [classes that extend](https://github.com/fabric8io/kubernetes-client/tree/7ef49cd34e2de0d68422e17ce24fe15e48b63f17/openshift-client/src/test/java/io/fabric8/openshift/client/server/mock) these.

### Describe the solution you'd like

Delete these classes

**Comment by harshitasao** [comment]
Hi @manusa . I'm new to Kubernetes and would like to learn and contribute. Is it possible for me to work on this problem? According to the explanation, I believe I need to remove the classes from the files. Is this the appropriate path for me?

**Comment by manusa** [comment]
> I believe I need to remove the classes from the files

I haven't analyzed much the issue or the impact, but yes, the requirement is to delete the two linked packages (the directories and files contained).

> Is this the appropriate path for me?

I don't think you are going to learn much about Kubernetes or this project just by deleting some files. However, it might be a good exercise and starting point to learn how to contribute to the project (fork&clone, compile, create a branch, commit changes, create a PR, etc.)

**Comment by harshitasao** [comment]
Thank you for your help. So, could you please assign this issue to me.

**Comment by harshitasao** [comment]
Thank you for your help. So, could you please assign this issue to me.

**Comment by manusa** [comment]
> Thank you for your help. So, could you please assign this issue to me.

Sorry, I missed this message. Are you still interested in contributing the fix?
