### ISSUE TITLE
Consider Deployments & StatefulSets ready when desired replica count is 0

### ISSUE THREAD

**Issue by amydentremont** [fabric8io/kubernetes-client#4009]
### Is your enhancement related to a problem? Please describe

Scaling StatefulSets and Deployments down to 0 desired replicas is a real use case for my company. We especially scale java application deployments down to 0 replicas temporarily to "pause" them in a kubernetes cluster, so that when we run java apps locally in Intellij for testing they're not completing with a java app running in the kubernetes cluster to process/update resources. 
The issue is, [`Readiness.isDeploymentReady`](https://github.com/fabric8io/kubernetes-client/blob/v5.8.0/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java#L147-L154) always returns `false` for deployments with a desired replica count of 0, because k8s sets `availableReplicas` to `null` instead of `0` in this case on the deployment resource. (The `Readiness.isDeploymentReady` logic linked always returns false if `availableReplicas` is `null`.)
For StatefulSets, it's the same issue but with `readyReplicas` being null instead of 0 when the desired replica count is 0, and [`Readiness.isStatefulSetReady`](https://github.com/fabric8io/kubernetes-client/blob/v5.8.0/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java#L128-L134) not accounting for this. 

We have implemented an extension of `Readiness` where `isReady` does return true for deployments and StatefulSets with spec.replicas=0, but we can't override the `isStatefulSetReady` and `isDeploymentReady` methods since they're static. We could copy them into another class with our own behavior instead, but I'm afraid someone would still be bound to use `Readiness.isDeploymentReady` and be confused by the inconsistent behavior.

### Describe the solution you'd like

Ideally, `isStatefulSetReady` and `isDeploymentReady` would check if spec.replicas is 0, and if so, consider the statefulSet/deployment ready if `readyReplicas`/`availableReplicas` is null or 0 (with the current version of k8s, they will only be null not 0, but might as well check for 0 too so it's handled if k8s changes this at some point). 

For example [the statefulSet case](https://github.com/fabric8io/kubernetes-client/blob/v5.8.0/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java#L128-L134) would be like this: 
```
public static boolean isStatefulSetReady(StatefulSet ss) {
    Utils.checkNotNull(ss, "StatefulSet can't be null.");
    StatefulSetSpec spec = ss.getSpec();
    StatefulSetStatus status = ss.getStatus();

    if (status == null || status.getReplicas() == null) {
      return false;
    }
    if (spec.getReplicas().intValue() == 0) {
       return status.getReadyReplicas() == null || status.getReadyReplicas() == 0;
    } else if (status.getReadyReplicas() == null) {
        return false;
    }
    ....
```

I understand that it's slightly odd to consider these StatefulSets and Deployments ready, but I think it's technically fair since the desired state has been achieved from the spec in these cases, and that's truly helpful for us to be able to check (whereas I don't see how not considering them ready in this case could be helpful for another use case).

### Describe alternatives you've considered

(copied from above)
We have implemented an extension of `Readiness` where `isReady` does return true for deployments and StatefulSets with spec.replicas=0, but we can't override the `isStatefulSetReady` and `isDeploymentReady` methods since they're static. We could copy them into another class with our own behavior instead, but I'm afraid someone would still be bound to use `Readiness.isDeploymentReady` and be confused by the inconsistent behavior.

### Additional context

Example statefulset with 0 replicas, in this case it was 0 replicas from the start rather than scaling down but the outcome is the same. (edited from a real example)
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: {config}
  creationTimestamp: "timestamp"
  generation: 1
  name: test-statefulset
  namespace: example-amy-test
  resourceVersion: "123"
  uid: 5678
spec:
  podManagementPolicy: OrderedReady
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-statefulset
  serviceName: test-statefulset
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-statefulset
    spec:
      containers:
        - image: docker.image/build
          imagePullPolicy: IfNotPresent
          name: test-statefulset
          resources:
            limits:
              cpu: 1m
              memory: 1m
            requests:
              cpu: 2m
              memory: 2m
          terminationMessagePath: /term
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  collisionCount: 0
  currentRevision: test-statefulset-683474yc8
  observedGeneration: 1
  replicas: 0
  updateRevision: test-statefulset-683474y8
```

Example of a deployment scaled to 0 replicas (edited from a real example)
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "14"
  creationTimestamp: "timestamp"
  generation: 14
  labels:
    app: example-widgetset-translator
    deployConfig: example-cluster-translators
    deployGroup: example
    javaapps.java.hubspot.com/name: example-widgetset-translator
  name: example-widgetset-translator
  namespace: example-amy-test
  ownerReferences:
    - apiVersion: java.hubspot.com/v1
      blockOwnerDeletion: true
      controller: true
      kind: JavaApp
      name: example-widgetset-translator
      uid: kjshjdbhbh
  resourceVersion: "2987444"
  uid: sh8s7d7gdbshdb7d7b
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: example-widgetset-translator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        app: example-widgetset-translator
        deployConfig: example-cluster-translators
        deployGroup: example
        name: example-widgetset-translator
      namespace: example-amy-test
    spec:
      containers:
        - args:
            - <args>
          env:
            - name: IS_DEPLOYED
              value: "true"
            - name: JAVA_APP_NAME
              value: example-widgetset-translator
          image: docker.image/build123
          imagePullPolicy: IfNotPresent
          terminationMessagePath: /term
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /path
              name: path
          workingDir: /path/app
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: example-operator
      serviceAccountName: example-operator
      terminationGracePeriodSeconds: 30
      volumes:
        - flexVolume:
            driver: test/path
            options:
              artifactGitBranch: master
              artifactGitOrganization: Org
              artifactGitRepo: Repo
              artifactModule: module
              buildNumber: "123"
          name: artifact
status:
  conditions:
    - lastTransitionTime: "2022-03-23T19:06:12Z"
      lastUpdateTime: "2022-03-23T19:06:12Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-03-16T21:34:10Z"
      lastUpdateTime: "2022-03-23T19:20:31Z"
      message: ReplicaSet "example-widgetset-translator-7875449d9" has successfully
        progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 14
  ```

**Comment by manusa** [comment]
This is an interesting change (I have a similar logic [here](https://github.com/manusa/yakc/blob/dca4633aefa17b6508c325259f467c4923bb6719/quickstarts/quarkus-dashboard/src/main/frontend/src/deployments/selectors.js#L19-L23)), however it's a big behavioral change and also might or might not be semantically correct depending on how "readiness" is defined (AFAIK readiness is not an official term with a provided spec, despite being a heavily used term).

An argument against this might be that the status of a deployment only shows the `readyReplicas`(thus introducing the term) if the number of requested replicas is > 0.

I'll mark this as discussion so we can tentatively consider it as a breaking behavioral change for v6.0.0.

/cc @iocanel @oscerd @rohanKanojia @shawkins @metacosm @csviri @andreaTP

**Comment by csviri** [comment]
From purely pragmatic aspect I believe this is right, for example we are using `waitUntilReady` in some places, I would expect this method to return if the target replica count is basically reached. 

Readiness is probably just well defined for pods. Where it really there is an explicit readiness probe. Of course it makes sense to assume that if all pods are ready then the `deployment` / `stateful set` / `replica set`. 

( From mathematical point of view this cannot be decided afaik [see](https://en.wikipedia.org/wiki/Vacuous_truth) )

**Comment by amydentremont** [comment]
Yeah mathematically it depends on how readiness is defined. I suppose readiness being "all desired pods are created/ready" wouldn't technically imply readiness, but "the desired ready replica count is met" would.

Though, pragmatically it would depend on if users think of ready as "the desired spec has been met" vs maybe "the deployment/statefulset is ready to accept traffic". I could see an argument for the latter being useful, but it also seems impractical to not have anything to indicate the desired spec being met too 🤷 

Worth mentioning that it's not clear that the behavior to not consider these deployments/statefulsets as ready was really intentional in the first place. It might've been a an unthought-of side effect of k8s setting `availableReplicas` and `readyReplicas` to null instead of 0 here, since if they were set to 0 instead, both cases would be considered ready - [deployments](https://github.com/fabric8io/kubernetes-client/blob/v5.8.0/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java#L147-L163) and [statefulsets](https://github.com/fabric8io/kubernetes-client/blob/v5.8.0/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/internal/readiness/Readiness.java#L128-L144). Though, I understand that there still might be other users relying on the current behavior regardless.

**Comment by amydentremont** [comment]
> if users think of ready as "the desired spec has been met"

On this point, I should mention that this isn't the current concept of readiness in the repo, though it is my company's custom defintion of readiness. We've implemented our readiness client to check both the concept of readiness here (ready replicas/available replicas equalling the desired number of replicas) and that any updates to the resources have been observed and processed - so we also check the observed generation against the current generation and `updatedReplicas`, plus depending on the updateStrategy for StatefulSets we check `currentReplicas` and `currentRevision`.

I'm personally not sure if there's a use case for readiness without capturing the update processing. The main use case at my company is to update a resource and then wait for it to become ready (or failed), and without checking that the updates have been processed, we'd get a lot of false positives where the resource is considered ready immediately because the `availableReplicas` == `spec.replicas` before the update is actually observed and `availableReplicas` goes down to `0` again.
