### ISSUE TITLE
Remove the need for the openshift-client dependency

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#4014]
There are things in the openshift client that prevent it from being an api only dependency.  We'd have to refactor to account for:

- Operations that contribute at the collection level, like ProjectOperations
- Operations that read logs, there's no existing exposed method on Client for this.
- the client logic that switches the httpclient / configuration to openshift specific.  OpenShiftConfig, Readiness, and the OpenShiftOAuthInterceptor could all be moved to client to facilitate this.
- OpenShiftNamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl - it's a whole other abstraction
- CreateOnlyResourceOperationsImpl
- ManagedOpenShiftClient

_Originally posted by @shawkins in https://github.com/fabric8io/kubernetes-client/issues/3966#issuecomment-1075415793_

**Comment by linnjason678** [comment]
Is an open shift better process to be in ?

**Comment by linnjason678** [comment]
Is removing open shift better for the client,

**Comment by shawkins** [comment]
Marking as closed.  There is too much refactoring to make this happen any time soon.
