### ISSUE TITLE
Too many `NonNamespaceOperation` methods have been removed in 5.12.1

### ISSUE THREAD

**Issue by metacosm** [fabric8io/kubernetes-client#4022]
### Describe the bug

 #3772 removed some methods from `NonNamespaceOperation`, which is fine but it also removed methods / interfaces that it shouldn't have. More specifically, `Replaceable` and `Deletable` should probably still be part of the `NonNamespaceOperation`.

Moving forward, for 6.0, it might make sense to trim down the DSL interfaces so that only the orthogonal ones are kept so that it's easier to figure out what an interface actually provides?

### Fabric8 Kubernetes Client version

other (please specify in additional context)

### Steps to reproduce

N/A

### Expected behavior

Non-mutable methods should still be available from `NonNamespaceOperation`.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

other (please specify in additional context)

### Additional context

This actually targets 5.12.1.

**Comment by rohanKanojia** [comment]
I understand `Deletable` should be part of NonNamespaceOperation but why would we want `Replaceable` to be under NonNamespaceOperation? As per my knowledge this operation has strict requirement of name.

**Comment by rohanKanojia** [comment]
ohk, I got my answer. When name is not provided it will be inferred from resource `.metadata`. Sorry for noise.
