### ISSUE TITLE
Add DeploymentRollback resource

### ISSUE THREAD

**Issue by ravilr** [fabric8io/kubernetes-client#404]
@jimmidyson @iocanel 
Can we get this added:
http://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/#_v1beta1_deploymentrollback

**Comment by iocanel** [comment]
@ravilr: Yeah I think that we could.

**Comment by jimmidyson** [comment]
@ravilr Do you know how to use this resource? I can't see any examples for it anywhere. Is this actually a managed resource or an internal representation?

**Comment by ravilr** [comment]
from http://kubernetes.io/docs/api-reference/extensions/v1beta1/operations/ (there isn't a direct permalink to the actual operation):
```
create rollback of a DeploymentRollback
POST /apis/extensions/v1beta1/namespaces/{namespace}/deployments/{name}/rollback
with bodyParameter as v1beta1.DeploymentRollback
```	
so, this looks like being used in subresource rollback operation of deployment resource.  

For our use case, where we deploy multiple deployment resources for an app,  i realized that it is better to keep the source definition of the deployments in version control somewhere, change it there and keep applying/replace() that, even for rollbacks, rather than using this operation.

**Comment by jimmidyson** [comment]
Agreed. We don't support any subresources at the moment so until we do you've come up with the best solution. I'm going to close this issue & raise another one to discuss subresources in general as we need to support them properly.

**Comment by Siva10** [comment]
@jimmidyson Hi . I would like to use the API
`POST /apis/extensions/v1beta1/namespaces/{namespace}/deployments/{name}/rollback`
to rollback a deployment to its previous version in rollout history.
Is there any proposal to support this feature in your roadmap ? Or to achieve this do we have to still do replace() as mentioned by @ravilr ?
Thanks in advance

**Comment by Zephery** [comment]
+1 anyone can help?

**Comment by chamhaw** [comment]
+1

**Comment by rohanKanojia** [comment]
I think we already have support for `DeploymentRollback` resource

https://github.com/fabric8io/kubernetes-client/blob/cf186055d12925d5abf78d534db6c0f5618ecec9/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentTest.java#L432-L447

**Comment by manusa** [comment]
BTW, DeploymentRollback is actually deprecated:
- https://github.com/kubernetes/api/blob/master/extensions/v1beta1/types.go#L150
- https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-back-to-a-previous-revision
- https://github.com/rancher/rancher/blob/0f2accee571048b1102e825581c9685ce0e9ed74/pkg/api/customization/workload/workload.go#L156

**Comment by rohanKanojia** [comment]
Yeah, I'm aware of this. But it's still there in Kubernetes 1.17. We need to consider this whenever kubernetes folks decide to remove it's support in future releases.

**Comment by ashwiniramesha** [comment]
`rollback` is officially removed in `apps/v1` version. 

ref: https://github.com/kubernetes/client-go/issues/398#issuecomment-382546959
https://github.com/kubernetes/client-go/issues/346

Is there an alternative available in `fabric8io` to perform deployment rollbacks with this version ?
