### ISSUE TITLE
Quantity.java need a method like getAmountInBytes for cpu

### ISSUE THREAD

**Issue by zjfplayer** [fabric8io/kubernetes-client#4041]
### Is your enhancement related to a problem? Please describe

There is already a method called getAmountInBytes in the Quantity class for calculating memory, which can be used to easily convert memory units. But there is no way to convert cpu units, I can only know the error when creating resourcequota:

`Error from server (BadRequest): ResourceQuota in version "v1" cannot be handled as a ResourceQuota: v1.ResourceQuota.Spec: v1.ResourceQuotaSpec.Hard: unmarshalerDecoder: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$', error found in #10 byte of ...|:"1000abc","memory":|..., bigger context ...|espace":"default"},"spec":{"hard":{"cpu":"1000abc","memory":"200Gi","pods":"10"},"scopeSelector":{"m|...`

But I don't know the meaning of eEinumkKMGTP, I only know that m and n represent cpu unit milli-core and nano-core respectively.And the official website does not have a clear cpu unit comparison, can you provide a method to convert cpu into milli-core or core

Thank you very much

### Describe the solution you'd like

 provide a method to convert cpu into milli-core or core in Quantity class

### Describe alternatives you've considered

Tell me the meaning of these units ""eEinumkKMGTP"

**Comment by qhh0205** [comment]
+1

**Comment by manusa** [comment]
Needs to be ported from client-go
