### ISSUE TITLE
`RequestMetadata.from` method doesn't properly extract components

### ISSUE THREAD

**Issue by metacosm** [fabric8io/kubernetes-client#4049]
If the request URI starts with a `/`, the segments have empty components which results in the method not properly extracting the components.

**Comment by shawkins** [comment]
@rohanKanojia @metacosm does this mean that the prs should not move forward yet?

Would it be simpler to just put uri path on the KubernetesClientException rather than the constituent parts?

**Comment by metacosm** [comment]
> @rohanKanojia @metacosm does this mean that the prs should not move forward yet?
> 
> Would it be simpler to just put uri path on the KubernetesClientException rather than the constituent parts?

Going to try to finish this as I think it's valuable to provide the context for an exception if we can provide it. Using the URI path would obviously be the easy fall back.
