### ISSUE TITLE
Deployment use createOrUpdate method return MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable, reason=FieldValueInvalid

### ISSUE THREAD

**Issue by menglingqiang** [fabric8io/kubernetes-client#4061]
I create a deployment use deployment use createOrUpdate. when I change image and use createOrUpdate again throw exception" MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable, reason=FieldValueInvalid"，how can I fix this？ I know deployment label is immutable, and I can change image use rolling().updateImage(), Is there  a simple method I can use? maybe I want to change deployment other attributes
`client().
            .apps()
            .deployments()
            .inNamespace(deployment.getMetadata().getNamespace())
            .createOrReplace(deployment);`

**Comment by shawkins** [comment]
There are a whole host of similar issues with createOrReplace.  The workaround is to use a "create or edit" approach so that instead of a replace, you are issuing a patch.  With fabric8 6 there will also be basic support for server side apply.
