### ISSUE TITLE
Issues resuming builds

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#4067]
### Is your task related to a problem? Please describe

If I incrementally build the project and use -rf to resume from a particular module, kubernetes-tests will often times fail to build with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:testCompile (default-testCompile) on project kubernetes-test: Compilation failure
[ERROR] Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: io.fabric8.crd.generator.apt.CustomResourceAnnotationProcessor Unable to get public no-arg constructor
[ERROR] 
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:testCompile (default-testCompile) on project kubernetes-test: Compilation failure
Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: io.fabric8.crd.generator.apt.CustomResourceAnnotationProcessor Unable to get public no-arg constructor
```

Going back and rebuilding crd-generator does not seem to help the situation.  Only starting the full build over again seems to get out of this state.

### Describe the solution you'd like

To resume the build at kubernetes-tests.

**Comment by manusa** [comment]
I'm not sure if it's related to this, but sundrio processing needs a clean slate.

**Comment by manusa** [comment]
so for instance, if you try to build the full project and it fails halfway through, you need to perform a full clean, else it will fail.
