### ISSUE TITLE
How to query a deployment status

### ISSUE THREAD

**Issue by menglingqiang** [fabric8io/kubernetes-client#4071]
I use DeploymentCondition "status" and "type" to judge deployment status. There are many combinations. How to easily know the status of the deployment? now I judge the status use like this

`public OperationResult.StatusEnum getStatus(Deployment deployment) {`
`       String type = deployment.getStatus().getConditions().get(0).getType(); `
`       String status = deployment.getStatus().getConditions().get(0).getStatus();`
`       if ("Available".equals(type)){`
`           return Boolean.valueOf(status.toLowerCase(Locale.ROOT))`
`               ? OperationResult.StatusEnum.SUCCESS`
`               : OperationResult.StatusEnum.FAILED;`
`       }`
`       return OperationResult.StatusEnum.PENDDING;`
`   }`

**Comment by shawkins** [comment]
See Readiness.isDeploymentReady - that checks that at least the specified number of replicas is ready.  Of course you can also specifically check the conditions as well.

**Comment by menglingqiang** [comment]
> isDeploymentReady
ok,Thank you
