### ISSUE TITLE
Unable to use `.extensions()` when multiple clients are configured with SSL

### ISSUE THREAD

**Issue by lwander** [fabric8io/kubernetes-client#408]
When multiple clients are registered, each adaptor is registered [here](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Adapters.java#L43). Unfortunately, it's registering the adaptor by [class type](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BaseClient.java#L60), which means if multiple adaptors with the same class (i.e. multiple clients exist) are added, the old ones are overwritten. 

My inclination is to register the adaptor with a string combining details about the cluster with the adaptor class to facilitate this. @iocanel I believe you wrote that adaptor code, WDYT?

**Comment by iocanel** [comment]
@lwander: Do we have a use case of requiring different adaptors of the same class?

**Comment by lwander** [comment]
Yup, when talking to multiple clusters I run into this issue.

**Comment by lwander** [comment]
The reason being: your adaptors store SSL config, so right now the client library can authenticate with at most one cluster over HTTPS.

**Comment by iocanel** [comment]
So we need a single adaptor, but we need to guarantee that configuration doesn't get mixed up, right?

**Comment by iocanel** [comment]
@lwander: still I think I miss something. The adapters do not have state, so I am not sure what you mean by ``your adaptors store SSL config``. Can you please provide some more info?

**Comment by lwander** [comment]
When the adaptor is [registered](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BaseClient.java#L57), it states that [`adapt(Client)`](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BaseClient.java#L70) should return the [`OkHttpClient`](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BaseClient.java#L46) that this instance of `BaseClient` was instantiated with. That `OkHttpClient` stores cluster-specific auth details instantiated [here](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java#L73) from the config specific to [`BaseClient`](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BaseClient.java#L41). Since you have a global adaptor registry that keys by class, these adaptors are overwritten each time a new `BaseClient` is instantiated.

**Comment by lwander** [comment]
Another fix might be to change [`return httpClient.clone()`](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/BaseClient.java#L70) to `return ((BaseClient) client).httpClient.clone()`

**Comment by iocanel** [comment]
@lwander: you are absolutely right :-)
