### ISSUE TITLE
How to access service from outside k8s using client

### ISSUE THREAD

**Issue by zcz3313** [fabric8io/kubernetes-client#4096]
I have done it by following command
```shell
curl --cacert /etc/kubernetes/pki/ca.crt --key /etc/kubernetes/pki/apiserver-kubelet-client.key --cert /etc/kubernetes/apiserver-kubelet-client.crt https://apiserver.cluster.local:6443/api/v1/namespace/default/services/${myservice}/proxy/ 
```
But I couldn't find any way or example using this sdk, any help would be appreciated!

**Comment by rohanKanojia** [comment]
@zcz3313 : Are you trying to list the service or are you trying to access kubernetes APIServer?

**Comment by zcz3313** [comment]
> @zcz3313 : Are you trying to list the service or are you trying to access kubernetes APIServer?

@rohanKanojia Thanks for your reply. 
What I want is accessing my service from outside k8s through kubernetes apiserver proxy.
And I found some example code as follow:
![image](https://user-images.githubusercontent.com/8746495/165462622-a124921b-b823-4f8e-bbb7-e4487d9fead5.png)

But I can't find any fluent method like above codes.
I have to do it now as follow:
![image](https://user-images.githubusercontent.com/8746495/165462796-715c7110-4707-4ae7-9791-15daa550c035.png)

Hoping there is a fluent coding way to achieve it.

**Comment by manusa** [comment]
Have you tried the port forwarding features of the client?

**Comment by zcz3313** [comment]
> Have you tried the port forwarding features of the client?

I don't think port-forward feature is the exactly way I want.
Anyway thanks, I have achieve it by myself using decorator pattern and builder pattern。

![image](https://user-images.githubusercontent.com/8746495/169493489-90f6b47f-88ed-45db-8825-95847d4cc76c.png)
