### ISSUE TITLE
Deleting deployment does  not delete associated pods 

### ISSUE THREAD

**Issue by mohanpindyala** [fabric8io/kubernetes-client#410]
I am trying to delete deployment and its associated pods using following code 

`kubernetesClient
                .extensions()
                .deployments()
                .withLabels(labels).delete();`

It doesn't delete pods associated with it . Is there a alternative to delete pods too ?

where as when I delete using kubectl it deletes pods as well.

**Comment by jimmidyson** [comment]
This _should_ be fixed in 1.3.92 which we released a few days ago. Are you using that version or an older one?

**Comment by mohanpindyala** [comment]
I am using 1.3.92

**Comment by jimmidyson** [comment]
Reproduced. Looks like we don't handle cascading deletes properly when we're deleting potential multiple resources, as `withLabels` implies. Working on a fix.

**Comment by ravilr** [comment]
@jimmidyson 
As a workaround till your fix is released, explicitly scale each deployment to 0, and then delete, should also work right?

**Comment by jimmidyson** [comment]
Good idea - that should work nicely.

**Comment by mohanpindyala** [comment]
thanks guys , let me try that in the meantime.
