### ISSUE TITLE
Support In, NotIn requirements in label selector in kubernetes-server-mock

### ISSUE THREAD

**Issue by ortex** [fabric8io/kubernetes-client#4113]
### Is your enhancement related to a problem? Please describe

kubernetes-server-mock doesn't support `In`, `NotIn` requirements in label selector

### Describe the solution you'd like

I guess first need add supporting to https://github.com/fabric8io/mockwebserver
* add `IN`, `NOT_IN` AttributeType's
* add supporting `IN`, `NOT_IN` AttributeType's to io.fabric8.mockwebserver.crud.AttributeSet#matches

And then add support to kubernetes-server-mock
* support parsing new AttributeType's in io.fabric8.kubernetes.client.server.mock.KubernetesAttributesExtractor#extractLabelSelector

**Comment by ortex** [comment]
For the parsing new AttributeType's in io.fabric8.kubernetes.client.server.mock.KubernetesAttributesExtractor#extractLabelSelector I see two ways:
Just splitting by comma doesn't work anymore

1) but it's possible to use some hacks, e.g.:

```java
String labelSelector = "foo=bar,app in (core1,core2),app2 in (core1,core2),l notin (none1,none2)";
Pattern pattern = Pattern.compile("\\(.*?\\)");
Matcher matcher = pattern.matcher(labelSelector);

String preparedLabelSelector = labelSelector;
Map<String, String> replacements = new HashMap<>();
for (int i = 0; matcher.find(); i++) {
  String setValues = labelSelector.substring(matcher.start(), matcher.end());

  String replacement = "values#" + i;
  preparedLabelSelector = preparedLabelSelector.replaceFirst(Pattern.quote(setValues), replacement);
  replacements.put(replacement, setValues);
}
// preparedLabelSelector = foo=bar,app in values#0,app2 in values#1,l notin values#2
// replacements = {values#1=(core1,core2), values#2=(none1,none2), values#0=(core1,core2)}
for (String requirement : preparedLabelSelector.split(",")) {
  for (Map.Entry<String, String> entry : replacements.entrySet()) {
    requirement = requirement.replace(entry.getKey(), entry.getValue());
  }
  // requirement = foo=bar
  // requirement = app in (core1,core2)
  // requirement = app2 in (core1,core2)
  // requirement = l notin (none1,none2)

  // todo: support parsing new requirements in parseLabel
  Attribute label = parseLabel(requirement);
  ...
}
```

2) Use grammar https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/labels/selector.go#L843-L851 and use something like antlr for lex parser. Probably overengineering :)

3) Use some other approach

**Comment by rohanKanojia** [comment]
@ortex : I would appreciate it if you could contribute to this feature.

**Comment by ortex** [comment]
Hi @rohanKanojia 
I've made a PR https://github.com/fabric8io/mockwebserver/pull/74. Maybe you could make a code review or ask someone to do it?

**Comment by ortex** [comment]
I suppose this issue could be reopened now?

**Comment by manusa** [comment]
I think that this was already tackled in https://github.com/fabric8io/mockwebserver/pull/74 and later merged to this repo

**Comment by ortex** [comment]
not exactly. 

New labels doesn't support in https://github.com/fabric8io/kubernetes-client/blob/main/junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesAttributesExtractor.java#L270-L315

**Comment by manusa** [comment]
We can leave the issue open in case someone wants to contribute the feature.

We recently provided the [Kube API test module](https://github.com/fabric8io/kubernetes-client/blob/2ccf5587988ee999bf22010235b5c09dbcd2c248/doc/kube-api-test.md) which should cover this use case (and more).
I'm not sure it's worth investing time in improving or adding extra-features to the Mock Web Server.
