### ISSUE TITLE
fail to upload file to azure k8s

### ISSUE THREAD

**Issue by ttbadr** [fabric8io/kubernetes-client#4130]
client version: 5.12.2
azure k8s version:1.21.9

when I upload a file from local to the azure k8s pod, the file is created in the pod, but no content in it. no any exception throw.

**Comment by shawkins** [comment]
How reproducible is this?

And is there any chance you could try this with the latest 6.0 snapshot?

**Comment by ttbadr** [comment]
> How reproducible is this?
> 
> And is there any chance you could try this with the latest 6.0 snapshot?

I think you can reproduce it just simply using API to upload a text file to the AKS(azure k8s service).
where I can get the latest 6.0 snapshot?

**Comment by shawkins** [comment]
> where I can get the latest 6.0 snapshot?

Maven central snapshots.  There was a nightly job added to keep it updated https://github.com/fabric8io/kubernetes-client/blob/0be7c02912e17ee1460340ab462be64afc3396f5/.github/workflows/release-snapshots.yaml

**Comment by rohanKanojia** [comment]
@ttbadr : polite ping, Did you get any chance to try out our 6.0-SNAPSHOT version?

**Comment by ttbadr** [comment]
@rohanKanojia I tried the 6.0-SNAPSHOT version, and still have the issue.

**Comment by rohanKanojia** [comment]
@ttbadr : Could you please share some reproducer project with us?

**Comment by ttbadr** [comment]
> @ttbadr : Could you please share some reproducer project with us?

[upload.zip](https://github.com/fabric8io/kubernetes-client/files/8751225/upload.zip)
@rohanKanojia

**Comment by manusa** [comment]
Hi @ttbadr 
Unfortunately we don't have any AKS cluster to test this. Your code looks pretty standard and should work.
Have you noticed if any other features is failing too? especially those related to WebSockets (waitUntilReady, watch, inform, etc.)
Also, are you able to use the download feature?
