### ISSUE TITLE
How can I query a deployment events use fabric8io sdk?

### ISSUE THREAD

**Issue by menglingqiang** [fabric8io/kubernetes-client#4132]
How can I query a deployment evnets use afbric8io sdk? 
like" kuberctl get events -n default"

**Comment by rohanKanojia** [comment]
Does this help?

https://github.com/fabric8io/kubernetes-client/blob/381c3ba26dd626e963f8c8756be088e7a4732891/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/kubectl/equivalents/EventsGetEquivalent.java#L32-L36

**Comment by menglingqiang** [comment]
> 

thanks, but I cant`t find event.getMessage() method in v1 or v1beta1 version

**Comment by menglingqiang** [comment]
> Could you please check if this helps?
> 
> https://github.com/fabric8io/kubernetes-client/blob/381c3ba26dd626e963f8c8756be088e7a4732891/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/kubectl/equivalents/EventsGetEquivalent.java#L32-L36
thanks, but I cant`t find event.getMessage() method in v1 or v1beta1 version

**Comment by rohanKanojia** [comment]
@menglingqiang : Which class are you referring to? Here we're using `io.fabric8.kubernetes.api.model.Event`; Even in `kubectl get events` v1 Event resource is returned.

**Comment by menglingqiang** [comment]
> @menglingqiang : Could you please elaborate which class you are referring to? Here we're using `io.fabric8.kubernetes.api.model.Event`; Even in `kubectl get events` v1 Event resource is returned.

ok, thanks
