### ISSUE TITLE
Mock Server Resource Status Patch Increases Generation Metadata on Resource

### ISSUE THREAD

**Issue by csviri** [fabric8io/kubernetes-client#4139]
### Is your task related to a problem? Please describe

When I patch a resource status in the mock kubernetes api server, it increases the generation in metadata.

### Describe the solution you'd like

It should not increase the metadata according to Kubernetes specs, see here:
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#subresources

`The .metadata.generation value is incremented for all changes, except for changes to .metadata or .status.`

**Comment by shawkins** [comment]
See the KubernetesCrudDispatcher.shouldIncreaseGeneration method - can you provide the patch that is tripping up this logic?

**Comment by csviri** [comment]
Yep, can take a look.
