### ISSUE TITLE
Bug: ClassNotFoundException: io.fabric8.kubernetes.model.annotation.Group in 5.12.2 version

### ISSUE THREAD

**Issue by rktechie** [fabric8io/kubernetes-client#4141]
### Is your task related to a problem? Please describe

Im using `io.fabric8:kubernetes-client:5.12.2` and on running a simple client creation code:
`KubernetesClient client = new DefaultKubernetesClient();`

im getting the following errors:
Caused by: java.lang.ClassNotFoundException: io.fabric8.kubernetes.model.annotation.Group
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]

So what can be done to fix this?

### Describe the solution you'd like

We should not be seeing the ClassNotFoundException. Some regression has happened while releasing a new version

### Describe alternatives you've considered

If i downgrade to the version 4.12.0 then i dont see this error anymore.

**Comment by shawkins** [comment]
You have a dependency issue - a conflicting version of kubernetes-model-common is being used in your project.

**Comment by rktechie** [comment]
CMD: ./gradlew operatorprovider:dependencyInsight --dependency kubernetes-model-common

Seems like fabric8 is itself downgrading it. You can see the dependency tree below:

io.fabric8:kubernetes-model-common:4.4.1 (selected by rule)
   variant "compile" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-api
      org.gradle.category            = library (not requested)

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.version         = 11
   ]

io.fabric8:kubernetes-model-common:5.12.2 -> 4.4.1
+--- io.fabric8:kubernetes-model-admissionregistration:5.12.2
|    \--- io.fabric8:kubernetes-client:5.12.2
|         \--- compileClasspath
+--- io.fabric8:kubernetes-model-apiextensions:5.12.2
|    \--- io.fabric8:kubernetes-client:5.12.2 (*)
+--- io.fabric8:kubernetes-model-apps:5.12.2
|    \--- io.fabric8:kubernetes-client:5.12.2 (*)
+--- io.fabric8:kubernetes-model-autoscaling:5.12.2
|    \--- io.fabric8:kubernetes-client:5.12.2 (*)
+--- io.fabric8:kubernetes-model-batch:5.12.2
|    \--- io.fabric8:kubernetes-client:5.12.2 (*)
+--- io.fabric8:kubernetes-model-certificates:5.12.2
|    \--- io.fabric8:kubernetes-client:5.12.2 (*)
+--- io.fabric8:kubernetes-model-coordination:5.12.2
|    \--- io.fabric8:kubernetes-client:5.12.2 (*)
+--- io.fabric8:kubernetes-model-core:5.12.2
|    +--- io.fabric8:kubernetes-client:5.12.2 (*)
|    +--- io.fabric8:kubernetes-model-rbac:5.12.2
|    |    \--- io.fabric8:kubernetes-client:5.12.2 (*)
|    +--- io.fabric8:kubernetes-model-admissionregistration:5.12.2 (*)
|    +--- io.fabric8:kubernetes-model-apps:5.12.2 (*)
|    +--- io.fabric8:kubernetes-model-autoscaling:5.12.2 (*)
|    +--- io.fabric8:kubernetes-model-apiextensions:5.12.2 (*)
|    +--- io.fabric8:kubernetes-model-batch:5.12.2 (*)
|    +--- io.fabric8:kubernetes-model-certificates:5.12.2 (*)
|    +--- io.fabric8:kubernetes-model-coordination:5.12.2 (*)
|    +--- io.fabric8:kubernetes-model-discovery:5.12.2
|    |    \--- io.fabric8:kubernetes-client:5.12.2 (*)
|    +--- io.fabric8:kubernetes-model-events:5.12.2
|    |    \--- io.fabric8:kubernetes-client:5.12.2 (*)
|    +--- io.fabric8:kubernetes-model-extensions:5.12.2
|    |    \--- io.fabric8:kubernetes-client:5.12.2 (*)
|    +--- io.fabric8:kubernetes-model-flowcontrol:5.12.2
|    |    \--- io.fabric8:kubernetes-client:5.12.2 (*)
|    +--- io.fabric8:kubernetes-model-networking:5.12.2
|    |    \--- io.fabric8:kubernetes-client:5.12.2 (*)
|    +--- io.fabric8:kubernetes-model-metrics:5.12.2
|    |    \--- io.fabric8:kubernetes-client:5.12.2 (*)
|    +--- io.fabric8:kubernetes-model-policy:5.12.2
|    |    \--- io.fabric8:kubernetes-client:5.12.2 (*)
|    +--- io.fabric8:kubernetes-model-scheduling:5.12.2
|    |    \--- io.fabric8:kubernetes-client:5.12.2 (*)
|    +--- io.fabric8:kubernetes-model-storageclass:5.12.2
|    |    \--- io.fabric8:kubernetes-client:5.12.2 (*)
|    \--- io.fabric8:kubernetes-model-node:5.12.2
|         \--- io.fabric8:kubernetes-client:5.12.2 (*)
+--- io.fabric8:kubernetes-model-discovery:5.12.2 (*)
+--- io.fabric8:kubernetes-model-events:5.12.2 (*)
+--- io.fabric8:kubernetes-model-extensions:5.12.2 (*)
+--- io.fabric8:kubernetes-model-flowcontrol:5.12.2 (*)
+--- io.fabric8:kubernetes-model-metrics:5.12.2 (*)
+--- io.fabric8:kubernetes-model-networking:5.12.2 (*)
+--- io.fabric8:kubernetes-model-node:5.12.2 (*)
+--- io.fabric8:kubernetes-model-policy:5.12.2 (*)
+--- io.fabric8:kubernetes-model-rbac:5.12.2 (*)
+--- io.fabric8:kubernetes-model-scheduling:5.12.2 (*)
\--- io.fabric8:kubernetes-model-storageclass:5.12.2 (*)

(*) - dependencies omitted (listed previously)

**Comment by shawkins** [comment]
I cannot reproduce this locally with maven or gradle.  It seems like you have a constraint in your project that is forcing the downgrade.

**Comment by rohanKanojia** [comment]
@rktechie : Could you please share a reproducer project with us? It will help us in reproducing your issue.

**Comment by meileinb** [comment]
try this
<dependency>
  <groupId>io.fabric8</groupId>
  <artifactId>kubernetes-client</artifactId>
  <version>6.0.0</version>
  <exclusions>
      <exclusion>
          <groupId>io.fabric8</groupId>
          <artifactId>kubernetes-model-common</artifactId>
      </exclusion>
  </exclusions>
</dependency>

<dependency>
  <groupId>io.fabric8</groupId>
  <artifactId>kubernetes-model-common</artifactId>
  <version>6.0.0</version>
</dependency>

**Comment by shawkins** [comment]
@meileinb the project in question is using gradle.  If it were using maven the above is not necessary - the 5.12 and 6.0 intra-project dependencies are correct.
