### ISSUE TITLE
Deprecate and remove xxx-mock modules

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#415]
kubernetes-mock and openshift-mock have been there to allow us mock the DSL. 

The last couple of months we've been using the mockwebserver DSL which imho works great, requires very little maintenance (compared to xxxx-mock) and its equally cool.

So why don't we send xxx-mock to beliz?

Thoughts?

**Comment by jimmidyson** [comment]
:+1: for a 1.4 release.
