### ISSUE TITLE
When I run some cmd instruction I an`t get the resopnse

### ISSUE THREAD

**Issue by guozy936003796** [fabric8io/kubernetes-client#4167]
### Is your task related to a problem? Please describe

The image is my code,when the paramList is [cd ../] I can`t get server response 
emmm I want to know ,has people to use the kubeclient execWatch function to do interactive shell

### Describe the solution you'd like

if you has some example please help me, thanks! 

### Describe alternatives you've considered

when I can`t get the respoonse ,I try to use the kubernetes-java-client . But ,whether the token flush, server always ask me  Exception 401 unauthentic.
 T^T
I don`t know how to down my job .

### Additional context

![1653408558(1)](https://user-images.githubusercontent.com/42803803/170083127-0aa6b4d7-e704-43be-80d5-c682dbd64673.png)

**Comment by guozy936003796** [comment]
emm, I can`t get server response for example in the image,I only get the interactive result...
![1653409473(1)](https://user-images.githubusercontent.com/42803803/170085325-4469eb25-41fa-4410-831f-c5d520b76426.png)
![1653409473(1)](https://user-images.githubusercontent.com/42803803/170085428-c0fff57f-def1-4c7e-a7d4-85c37cb278e9.png)

if you can help me ,I will study english well..

**Comment by guozy936003796** [comment]
> Could you please check this example? There are other exec examples also in [kubernetes-examples/ ](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/)folder
> 
> https://github.com/fabric8io/kubernetes-client/blob/2d73f03fe2a280f9fdec055f5f7b894179d1f94f/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ExecExample.java#L49-L56

When I refer to the case for verification，I still unable to get the returned OutPutStream

**Comment by hudac** [comment]
Try without `.withTTY()`. That worked for me.
