### ISSUE TITLE
Change ENV `kubernetes_websocket_ping_interval` to uppercase

### ISSUE THREAD

**Issue by dcoliversun** [fabric8io/kubernetes-client#4196]
### Is your task related to a problem? Please describe

No related to a problem. Just code style.

### Describe the solution you'd like

Change ENV `kubernetes_websocket_ping_interval` to uppercase for same code style.
https://github.com/fabric8io/kubernetes-client/blob/63f5921fa11eb4883346ca8c35db5a10190725d9/README.md?plain=1#L108

**Comment by sunix** [comment]
Thanks @dcoliversun, would you like to create a PR for that? Let us know. Thanks

**Comment by dcoliversun** [comment]
@sunix OK :)  please assign this issue to me

**Comment by sunix** [comment]
Thanks a lot !
