### ISSUE TITLE
Maven / Gradle Plugin for CRD Generator

### ISSUE THREAD

**Issue by flashpixx** [fabric8io/kubernetes-client#4209]
### Is your enhancement related to a problem? Please describe

In complex environments it is hard to generate POJOs on CRD based on manual execution of https://github.com/fabric8io/kubernetes-client/tree/master/java-generator

### Describe the solution you'd like

It would be nice to store the CRD file within the directory of the project and during Maven / Gradle lifecycle it builds the POJOs of the CRD file, this improves and speed-up the development process and makes it easy to update to new CRDs.
So a plugin for code generation which can be integrated into the build system could be helpful

**Comment by manusa** [comment]
It's unclear if you're talking about the CRD-to-Java generator or the Java-to-CRD generator.

The Java-to-CRD generator can be triggered as an annotation processor which should bind to you compile lifecycle phase regardless of the build tool (Gradle, Maven, and so on).
Isn't this working for you?

The CRD-to-Java generator **already** has a Maven plugin that you can use in your build:
```xml
<plugin>
  <groupId>io.fabric8</groupId>
  <artifactId>java-generator-maven-plugin</artifactId>
  <version>6.0.0-RC1</version>
  <executions>
    <execution>
      <goals>
        <goal>generate</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <source>src/main/resources/</source>
    <codeStructure>FLAT</codeStructure>
    <extraAnnotations>true</extraAnnotations>
    <alwaysPreserveUnknown>true</alwaysPreserveUnknown>
    <suffixStrategy>TOP_LEVEL</suffixStrategy>
  </configuration>
</plugin>
```

**Comment by andreaTP** [comment]
@manusa I think that this issue shows that we are lacking documentation:
 - the [readme of the java-generator](https://github.com/fabric8io/kubernetes-client/blob/master/java-generator/README.md) is outdated and incomplete
 - it's hard for the users to grasp how to use the tool
 
 Maybe we should add a page to the [doc folder](https://github.com/fabric8io/kubernetes-client/tree/master/doc), wdyt?

**Comment by manusa** [comment]
> Maybe we should add a page to the [doc folder](https://github.com/fabric8io/kubernetes-client/tree/master/doc), wdyt?

Yes, please :pray: 

I will probably blog about this feature before 6.0 GA is out too.

**Comment by andreaTP** [comment]
@manusa I'll take the docs and am happy to collaborate on a Blog if you want 🙂 (for reference I have written something [here](https://andreaperuffo.com/posts/java-shell-4-kube/) )

**Comment by manusa** [comment]
> @manusa I'll take the docs and am happy to collaborate on a Blog if you want slightly_smiling_face (for reference I have written something [here](https://andreaperuffo.com/posts/java-shell-4-kube/) )

Thx :raised_hands: 

I think I read your blog entry when you published it, definitely something to reference.

The goals is to spread the word about the new release as much as possible. So the more articles, posts, videos, and so on that we manage to publish, the better to get the word out about this new awesome release.

**Comment by andreaTP** [comment]
@flashpixx can you check https://github.com/fabric8io/kubernetes-client/blob/master/doc/java-generation-from-CRD.md

it should be covering, at least, the maven part of this issue.

**Comment by flashpixx** [comment]
Great thanks, I have it configured in this way and everything works fine
