### ISSUE TITLE
IntOrString is broken for ints with value 0

### ISSUE THREAD

**Issue by jpechane** [fabric8io/kubernetes-client#421]
See the code
```java
        public IntOrString deserialize(JsonParser jsonParser, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            ObjectCodec oc = jsonParser.getCodec();
            JsonNode node = oc.readTree(jsonParser);
            IntOrString intOrString = new IntOrString();
            int asInt = node.asInt();
            if (asInt != 0) {
                intOrString.setIntVal(asInt);
            } else {
                intOrString.setStrVal(node.asText());
            }
            return intOrString;
        }
```
When a 0 is set explicitly on such a field in a JSON file it is incorrectly translated into string which can then be expected in a specific format - an example is deploymentConfig - rolling update strategy when maxSurge is set to 0. It is converted to string "0" but if datatype is string then OpenShift expecs it to be in format "0%"

**Comment by jpechane** [comment]
Fixed in https://github.com/fabric8io/kubernetes-model/pull/145

**Comment by jimmidyson** [comment]
Funny everyone's been finding this issue at the same time. Will get a release out today hopefully.
