### ISSUE TITLE
apiextensions().v1beta1().customResourceDefinitions()

### ISSUE THREAD

**Issue by fastrunner** [fabric8io/kubernetes-client#4210]
### Is your task related to a problem? Please describe

io.fabric8.kubernetes.api.model.GenericKubernetesResource cannot be cast to io.fabric8.kubernetes.api.model.apiextensions.v1beta1.CustomResourceDefinition

### Describe the solution you'd like

tks

**Comment by manusa** [comment]
Could you please provide more context (code that triggers the issue, version you are using, and so on)

**Comment by fastrunner** [comment]
the yaml contents  as follows:

apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: kubeflow-test
spec:
  owner:
    kind: User
    name: user@example.com
---------------------------------------------------------
the code content :

         try {
             InputStream inputStream = resourceLoader.getResource("classpath:profile.yaml").getInputStream();
             CustomResourceDefinition resourceDefinition = kubernetesClient.apiextensions().v1beta1().customResourceDefinitions().load(inputStream).get();
             kubernetesClient.apiextensions().v1beta1().customResourceDefinitions().createOrReplace(resourceDefinition);
         } catch (IOException e) {
            e.printStackTrace();
        }

**Comment by fastrunner** [comment]
sorry, client version is 5.12.2

**Comment by fastrunner** [comment]
It was solved in the following way, but another problem occurred，

CustomResourceDefinition customPro = Serialization.unmarshal(resourceLoader.getResource("classpath:profile.yaml").getInputStream(), CustomResourceDefinition.class);
client.apiextensions().v1beta1().customResourceDefinitions().createOrReplace(customPro);

----------------------------------------------------------------------------
the error as follow

io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.4.40:6443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions. Message: Profile in version "v1beta1" cannot be handled as a CustomResourceDefinition: no kind "Profile" is registered for version "kubeflow.org/v1beta1" in scheme "k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go:52". Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=Profile in version "v1beta1" cannot be handled as a CustomResourceDefinition: no kind "Profile" is registered for version "kubeflow.org/v1beta1" in scheme "k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go:52", metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).

**Comment by rohanKanojia** [comment]
@fastrunner : I think you're misunderstanding. Profile is a Custom Resource not a Custom Resource Definition

**Comment by rohanKanojia** [comment]
Please check this[0] in order to get an idea of how to create CustomResource without type.

[0] https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#resource-typeless-api

**Comment by fastrunner** [comment]
@rohanKanojia tks very much
