### ISSUE TITLE
Unable to use waitUntilCondition

### ISSUE THREAD

**Issue by aleboulanger** [fabric8io/kubernetes-client#4223]
### Is your task related to a problem? Please describe

I can't find a way to use an example of waitUntilCondition described in your readme file
https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#kubernetes-client-dsl-usage

### Describe the solution you'd like

this example from the readme should compile 

`Pod pod = client.pods().inNamespace("default").withName("nginx").waitUntilCondition(pod -> pod.getStatus().getPhase().equals("Succeeded"), 1, TimeUnit.MINUTES)`

**Comment by manusa** [comment]
Could you please share the Kubernetes client version you're using?

**Comment by sunix** [comment]
Also what is the compilation error ?
