### ISSUE TITLE
Mocking client#getApiResources(string)

### ISSUE THREAD

**Issue by hschoefer** [fabric8io/kubernetes-client#4233]
### Is your enhancement related to a problem? Please describe

In a @SpringBootTest I inject the KubernetesClient by using the annotation @EnableKubernetesMockClient with mock server in mode crud. This allows me to register a CustomResourceDefinition (e.g. kafka.strimzi.io/v1beta2) with an injected KubernetesClient.

If I want to look up API resources with kubernetesClient.genericKubernetesResources(apiVersion, kind) the result list is everytime empty. As far as I understand this API calls internally /apis/kafka.strimzi.io/v1beta2 to build a ResourceDefinitionContext. This behavior works with a real cluster nut not with the mock servers.

With the mock server it's possible to create a CRD but it won't "register" entries under /apis/kafka.strimzi.io/v1beta2.

How can I prepare the the mock server to provide this functionality, too?

### Describe the solution you'd like

Provide an API to prepare the mock.

### Describe alternatives you've considered

I tried to create a mock result by build an instance of APIResourceList with an APIResource entry by calling the mock server via [1] . But this doesn‘t help. The mock server seems to deserialize it as CRD under /apis/apiextensions.k8s.io.

[1] (Kotlin)
`kubernetesClient.httpClient.newHttpRequestBuilder().uri("${kubernetesClient.configuration.masterUrl}/apis/kafka.strimzi.io/v1beta2").post("application/json", jacksonObjectMapper().writeValueAsString(apiResourceList)).build()`

**Comment by sunix** [comment]
@shawkins do you have any ideas for that issue?

**Comment by shawkins** [comment]
@sunix @hschoefer the comments on #3960 and the linked Q/A post which has sample code for creating the expected mock endpoints.
