### ISSUE TITLE
Is there a function for monitoring the progress of pod upload files

### ISSUE THREAD

**Issue by qmyflame** [fabric8io/kubernetes-client#4236]
### Is your task related to a problem? Please describe

When I upload a file to the pod, I don't know how long to wait

### Describe the solution you'd like

Add a monitor, you can get the size of the uploaded file from the status of this monitor

**Comment by shawkins** [comment]
This seems doable, but to be non-breaking would need to introduce another DSL method - withUploadMonitor(monitor).upload(...)  - or new upload methods - .monitoredUpload(...) - as the return value from upload is currently just a boolean.

Is this something that you can contribute?

**Comment by Ananya2001-an** [comment]
@shawkins for knowing the waiting time of file upload can't we add a timer and log it ?

**Comment by shawkins** [comment]
> for knowing the waiting time of file upload can't we add a timer and log it ?

The request seems to be more for a programmatic monitor.  It could provide bytes sent, total bytes (for files, input streams will have unknown sizes), and even the std error stream - #4254
