### ISSUE TITLE
WebSocket output issue

### ISSUE THREAD

**Issue by jingjing0921** [fabric8io/kubernetes-client#4239]
### Describe the bug

In a springboot(2.6.6) maven project, I try to execute command on pod with Fabric8 Java Kubernetes client, then send the output with WebSocket, but the output is alway same with the input command, not the result of the command, see the screenshot of the postman. The kubernetes API server version is Kubernetes v1.22.2.
**Code:**
**1. TestServerEndpoint** 
@Component
@ServerEndpoint("/test/{clusterId}/{namespace}/{pod}")
@Slf4j
public class TestServerEndpoint {

    private static final ExecutorService executorService = Executors.newFixedThreadPool(10);
    private static final Map<String, ExecWatch> SESSION_EXEC_WATCH_MAP = new ConcurrentHashMap<>();

    @OnOpen
    public void onOpen(Session session, @PathParam(value = "clusterId")String clusterId,
                       @PathParam(value = "namespace")String namespace,
                       @PathParam(value = "pod") String pod) {
        IK8sBaseService baseService = SpringContextUtil.getBean("k8sBaseService");
        KubernetesClient client = baseService.getK8sClient(clusterId);

        ExecWatch watch = client.pods().inNamespace(namespace).withName(pod)
                .writingInput(new PipedOutputStream())
                .readingOutput(new PipedInputStream())
                .readingError(new PipedInputStream())
                .withTTY()
                .exec("env", "TERM=xterm", "COLUMNS=180", "LINES=50", "bash", "-i");
        SESSION_EXEC_WATCH_MAP.put(session.getId(), watch);
    }

    @OnMessage
    public void onMessage(String message, Session session) {
        ExecWatch watch = SESSION_EXEC_WATCH_MAP.get(session.getId());
        InputStreamPumper.pump(watch.getOutput(), (b, o, l) -> session.getBasicRemote().sendText(new String(b, o, l)),
                executorService);
        OutputStream watchInput = watch.getInput();
        try {
            watchInput.write(message.getBytes());
        } catch (Exception e) {
            log.error("Send Message Error!");
        }
    }

    @OnClose
    public void onClose(Session session) {
        ExecWatch watch = SESSION_EXEC_WATCH_MAP.get(session.getId());
        WebSocketUtils.sendMessage(session, "The shell will now close.");
        if(null != watch){
            watch.close();
        }
    }

    @OnError
    public void onError(Session session, Throwable throwable) {
        log.error("Got Error:" + session.getId() + " " + throwable.getMessage());
        ExecWatch watch = SESSION_EXEC_WATCH_MAP.get(session.getId());
        if(null != watch){
            watch.close();
        }
    }
}

**2. WebSocketConfig**
@Configuration
public class WebSocketConfig {
    @Bean
    public ServerEndpointExporter serverEndpointExporter(){
        return new ServerEndpointExporter();
    }
}

**screenshot:**
![image](https://user-images.githubusercontent.com/10624279/176333060-dfc2bd1b-ac08-4dd7-b641-47d7f2909e0d.png)

### Fabric8 Kubernetes Client version

5.12.2

### Steps to reproduce

1. Run the project
2. Test the endpoint with postman

### Expected behavior

get the result of the command executed

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Windows

**Comment by shawkins** [comment]
@jingjing0921 the behavior I see is that your input commands need to be terminated with a new line to be executed.  Also the withTTY option seems to echo the input.

**Comment by jingjing0921** [comment]
close
