### ISSUE TITLE
Can't Create/Update Nodes

### ISSUE THREAD

**Issue by fecogc** [fabric8io/kubernetes-client#424]
Whenever I tried to create a Node using a name like 

10.0.0.1

`Node n = new NodeBuilder().withNewMetadata().withName("1.0.0.1").endMetadata().build();`

`java.lang.IllegalStateException: Constraint Violations:
	EditableObjectMeta name:must match "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"

	at io.fabric8.kubernetes.api.model.ObjectMetaBuilder.validate(ObjectMetaBuilder.java:67)
	at io.fabric8.kubernetes.api.model.ObjectMetaBuilder.build(ObjectMetaBuilder.java:40)
	at io.fabric8.kubernetes.api.model.NodeFluentImpl$MetadataNestedImpl.and(NodeFluentImpl.java:133)
	at io.fabric8.kubernetes.api.model.NodeFluentImpl$MetadataNestedImpl.endMetadata(NodeFluentImpl.java:136)`

I get Constraint Violations, but if I create a Node using a yaml/json file with the apiserver. It suceeds

`{
  "kind": "Node",
  "apiVersion": "v1",
  "metadata": {
    "name": "10.0.0.1"
  }
}`

**Comment by jimmidyson** [comment]
Looks like we've got wrong constraints in there for node name, which are less restrictive than other resource names. Will look at fixing up soon.

**Comment by fecogc** [comment]
may I know if theres a workaround or will this get fixed in the next version?

**Comment by jimmidyson** [comment]
Only workaround would be to remove validation-api (or corresponding impl) from classpath which I assume you don't want to do for other reasons. We should probably be able to disable validation via the DSL - thoughts @iocanel?

And of course I'm looking at a proper fix anyway - should be in next version.

**Comment by iocanel** [comment]
Currently, the only way to disable validation is by removing the impl from the class path.
I would expect that each impl may have external hooks for disabling validation via system properties etc, so it may worth having a look there.

I think that we need also need to have a similar way to turn on and off validation in the model side.

**Comment by jimmidyson** [comment]
fabric8io/kubernetes-model#150 will bring in the fix for name validation. Metadata names are now validated (hopefully) in line with Kubernetes/OpenShift requirements & are configurable per type to make this easier in future. We'll release model & client in the next few days so you can use it.
