### ISSUE TITLE
Openshift Client ignores NO_PROXY setting

### ISSUE THREAD

**Issue by brubrz** [fabric8io/kubernetes-client#4247]
### Describe the bug

The ConfigBuilder ignores .withNoProxy() Setting. I must set the HttpProxy to null in order to connect to my PaaS.

### Fabric8 Kubernetes Client version

6.0.0-RC1

### Steps to reproduce

Does not work:

        Config config = new ConfigBuilder()
                .withNoProxy("*.my.domain.com") // does not work: Socket Exception: "read timed out"
                .build();

        try (final KubernetesClient client = new KubernetesClientBuilder().withConfig(config).build()) {

            System.out.println(Arrays.toString(config.getNoProxy()));
            System.out.println(client.getConfiguration().getCurrentContext().getName());
            System.out.println(config.getUsername());
            System.out.println(config.getOauthToken());

            client.pods().inNamespace("default").list().getItems().stream().map(pod -> pod.getMetadata().getName()).forEach(System.out::println);

Weird workaround that works:

        Config config = new ConfigBuilder()
                .withHttpProxy(null)
                .withHttpsProxy(null)
                .build();

        try (final KubernetesClient client = new KubernetesClientBuilder().withConfig(config).build()) {
            //client.authorization().v1().localSubjectAccessReview()

            System.out.println(Arrays.toString(config.getNoProxy()));
            System.out.println(client.getConfiguration().getCurrentContext().getName());
            System.out.println(config.getUsername());
            System.out.println(config.getOauthToken());

            client.pods().inNamespace("default").list().getItems().stream().map(pod -> pod.getMetadata().getName()).forEach(System.out::println);

### Expected behavior

        Config config = new ConfigBuilder()
                .withNoProxy("*.my.domain.com")
                .build();

This should work / not be ignored.

### Runtime

OpenShift

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Windows

### Additional context

Kubernetes API Server version:    v1.21.11+6b3cbdd

**Comment by shawkins** [comment]
The implementation https://github.com/fabric8io/kubernetes-client/blob/10e9f188911ef00e66d3b5731e073ccc6d38f8da/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java#L72 does not expect wildcards.  It's looking only for an exact match to the ip or host.

**Comment by brubrz** [comment]
In that case, I would really appreciate an error msg. It appears to me as if the code is passing an IP that could not be parsed along to another component to let it fail there? I think an uparsable ip should result in an error:

```public static URL getProxyUrl(Config config) throws MalformedURLException {
    URL master = new URL(config.getMasterUrl());
    String host = master.getHost();
    if (config.getNoProxy() != null) {
      for (String noProxy : config.getNoProxy()) {
        if (isIpAddress(noProxy)) {
          if (new IpAddressMatcher(noProxy).matches(host)) {
            return null;
          }
        } else {
          if (host.contains(noProxy)) {
            return null;
          }
         // the proxy string was not parsable                    <--------------------- 
        }
      }
    }
```

**Comment by manusa** [comment]
The NO_PROXY env var support was added in #209 to fix an issue with Fabric8 Maven Plugin (https://github.com/fabric8io/fabric8/issues/5178).

The spec was taken from http://www.gnu.org/software/wget/manual/html_node/Proxies.html

> **no_proxy**
> This variable should contain a comma-separated list of domain extensions proxy should not be used for. For instance, if the value of no_proxy is ‘.mit.edu’, proxy will not be used to retrieve documents from MIT.

However, the GNU emacs spec does support wildcards https://www.gnu.org/software/emacs/manual/html_node/url/Proxies.html

> The NO_PROXY environment variable specifies URLs that should be excluded from proxying (on servers that should be contacted directly). This should be a comma-separated list of hostnames, domain names, or a mixture of both. Asterisks can be used as wildcards, but other clients may not support that. 

The one for OpenShift doesn't accept wildcard characters either.

---

Regarding the current implementation, I think it's fine and I wouldn't overcomplicate it.

However, I think that the line
```java
if (host.contains(noProxy)) {
```
should be changed to
```java
if (host.endsWith(noProxy)) {
```
or even something a little bit more involved that actually checks for subdomains if expressed as `.example.com` or not if expressed as `example.com`


>  I would really appreciate an error msg

>  so in this case * would cause an exception.

Yes, this would improve the usability.
