### ISSUE TITLE
Lombok's `EqualsAndHashCode` for CR should have `callSuper=true`

### ISSUE THREAD

**Issue by grossws** [fabric8io/kubernetes-client#4259]
### Describe the bug

CRD to Java generator with `Config#objectExtraAnnotations` set should generate `@lombok.EqualsAndHashCode(callSuper = true)` for CR classes since generated class has no fields and spec is accessible via `CustomResource` superclass.

Since it doesn't have `callSuper = true` lombok produces something like this:

```java
package us.containo.traefik.v1alpha1;

import io.fabric8.kubernetes.api.model.Namespaced;
import io.fabric8.kubernetes.client.CustomResource;
import io.fabric8.kubernetes.model.annotation.Group;
import io.fabric8.kubernetes.model.annotation.Version;

@Version(
  value = "v1alpha1",
  storage = true,
  served = true
)
@Group("traefik.containo.us")
public class IngressRoute extends CustomResource<IngressRouteSpec, Void> implements Namespaced {
  public IngressRoute() {
  }

  public String toString() {
    return "IngressRoute()";
  }

  public boolean equals(final Object o) {
    if (o == this) {
      return true;
    } else if (!(o instanceof IngressRoute)) {
      return false;
    } else {
      IngressRoute other = (IngressRoute)o;
      return other.canEqual(this);
    }
  }

  protected boolean canEqual(final Object other) {
    return other instanceof IngressRoute;
  }

  public int hashCode() {
    int result = true;
    return 1;
  }
}
```

### Fabric8 Kubernetes Client version

6.0.0-RC1

### Steps to reproduce

1. Get some CRD (e.g. `kubectl get crd/middlewares.traefik.containo.us -o yaml > crd.yaml`)
2. Run `jbang io.fabric8:java-generator-cli:6.0.0-RC1 -t generated -s crd.yaml --add-extra-annotations`

### Expected behavior

Generated CR class to have `@lombok.EqualsAndHashCode(callSuper = true)`

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

### Additional context

Kubelet version 1.23.6
Kubernetes flavor `k3s` v1.23.6+k3s1

**Comment by andreaTP** [comment]
I completely missed this one 😓 , looks reasonable, @rohanKanojia let me know if have any trouble picking this up 👍 the relevant line of code is this:
https://github.com/fabric8io/kubernetes-client/blob/e28f569f1552845615c4425def484edb937883cb/java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObjectExtraAnnotations.java#L27
