### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#4271]
### Is your task related to a problem? Please describe

Remove any inappropriate language from our repo**s** (white, black, master, slave...)

### Describe the solution you'd like

`master` branch should be renamed to `main`

### Additional context

- https://www.redhat.com/en/blog/making-open-source-more-inclusive-eradicating-problematic-language
- https://blogs.eclipse.org/post/mike-milinkovich/eclipse-foundation-support-black-community

### Checks
- CI pipelines are not referencing `master` in any way ---> they will still work
- Documentation generation doesn't reference the branch name
- Website sources and processes (https://github.com/jkubeio/jkube-website) don't reference the `master` branch
- ...

**Comment by gastaldi** [comment]
Actually, CI pipelines are referencing the `master` branch: https://github.com/fabric8io/kubernetes-client/blob/master/.github/workflows/build.yml#L26

We should change those before changing the default branch to `main` in https://github.com/fabric8io/kubernetes-client/settings.
