### ISSUE TITLE
Removal of deprecated extension xxx-server-mock modules

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#4272]
### Is your task related to a problem? Please describe

The usage of these modules are no longer required since the generic Kubernetes Mock Server can be used instead (is preferred).

> - Extension specific `EnableXXXMockClient` and `XXXMockServer` classes have been deprecated.  You can simply use `EnableKubernetesMockClient` and `KubernetesMockServer` instead. Dependencies on the xxx-mock jar are then no longer needed, just a dependency to `kubernetes-server-mock`.

https://github.com/fabric8io/kubernetes-client/blob/43af167c663031dac37f08dda36e35e512462071/doc/MIGRATION-v6.md#L238

### Describe the solution you'd like

Removal of the extensions/xxx-server-mock

**Comment by shawkins** [comment]
This duplicates #3924 do you want to close the other one?
