### ISSUE TITLE
Can not generator java class from crd files

### ISSUE THREAD

**Issue by cutiechi** [fabric8io/kubernetes-client#4307]
### Describe the bug

class io.fabric8.kubernetes.api.model.apiextensions.v1beta1.CustomResourceDefinition cannot be cast to class io.fabric8.kubernetes.api.model.apiextensions.v1.CustomResourceDefinition (io.fabric8.kubernetes.api.model.apiextensions.v1beta1.CustomResourceDefinition and io.fabric8.kubernetes.api.model.apiextensions.v1.CustomResourceDefinition are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @4a5905d9)

### Fabric8 Kubernetes Client version

6.0.0

### Steps to reproduce

![图片](https://user-images.githubusercontent.com/27606234/181414389-fca1be6e-e713-491e-b4ec-c70911f11914.png)

### Expected behavior

How to generator java class for crd v1beta1?

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.22

### Environment

Linux, macOS

**Comment by manusa** [comment]
Unfortunately, I don't think we support v1beta1 `CustomResourceDefinition`s.

You can try to use a compatible cluster to perform a conversion for you and then use the updated CRD.

The following references might help:
- https://github.com/kubernetes/kubernetes/issues/87231
- https://redhat-connect.gitbook.io/certified-operator-guide/ocp-deployment/operator-metadata/update-crds-from-v1beta1

**Comment by andreaTP** [comment]
Correct, the `java-generator` doesn't currently support `v1beta1`, can you try following @manusa 's suggestions?

Out of curiosity, is the CRD you are using available? I'm wondering how many Operators are unable to generate a `v1` version of the CRD nowadays.

**Comment by cutiechi** [comment]
@manusa @andreaTP Mainly want to be compatible with k8s 1.13

**Comment by andreaTP** [comment]
K8s 1.13 is [EOL since 2019-10-15](https://kubernetes.io/releases/_print/#non-active-branch-history), unless there is a very very compelling motivation this is not something we can afford to support, unfortunately.

**Comment by manusa** [comment]
Try to run post your CRD to a 1.16 cluster (minikube or whatever), and download its v1beta1 version.

**Comment by cutiechi** [comment]
I successfully built with v1 version, testing compatibility with 1.13

**Comment by andreaTP** [comment]
Hi @cutiechi , any update on this? would you consider this issue solved?

**Comment by cutiechi** [comment]
Only use it for now

**Comment by andreaTP** [comment]
Please re-open or just comment if you have additional questions!
