### ISSUE TITLE
Delete on resources is broken

### ISSUE THREAD

**Issue by dsimansk** [fabric8io/kubernetes-client#431]
Related to #428.
Sorry @jimmidyson, I should have figured it out sooner. The resources're are deleted sequentially in my code. So the DC is fine now. But jumping to Pod delete operation is broken.

Update: It seems, I'm a bit careless on Friday. Nevermind my previous comment. I'd assume there's a common issue with those constructors in  BaseOperations class. It has surfaces with RCs and pods also.

```
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withName(BaseOperation.java:180)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withName(BaseOperation.java:58)
	at com.redhat.xpaas.openshift.OpenshiftUtil.lambda$deletePod$16(OpenshiftUtil.java:370)
	at com.redhat.xpaas.openshift.OpenshiftUtil.withDefaultUser(OpenshiftUtil.java:169)
	at com.redhat.xpaas.openshift.OpenshiftUtil.deletePod(OpenshiftUtil.java:369)
	at com.redhat.xpaas.openshift.OpenshiftUtil.lambda$cleanProject$71(OpenshiftUtil.java:916)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.redhat.xpaas.openshift.OpenshiftUtil.cleanProject(OpenshiftUtil.java:916)
	at com.redhat.xpaas.openshift.OpenshiftUtil.cleanProject(OpenshiftUtil.java:878)
	at com.redhat.xpaas.openshift.OpenshiftUtil.cleanProject(OpenshiftUtil.java:871)
	at com.redhat.xpaas.amq.template.AbstractAmqTemplateTest.createApplicationFromTemplate(AbstractAmqTemplateTest.java:81)
	at com.redhat.xpaas.amq.template.AbstractAmqTemplateTest.createApplicationFromTemplate(AbstractAmqTemplateTest.java:69)
	at com.redhat.xpaas.amq.template.BasicTemplateTest.testCreateApplication(BasicTemplateTest.java:20)

```

**Comment by jimmidyson** [comment]
Would you be able to try with master? Think I fixed this earlier today. Will check tests later to ensure there's regression.

**Comment by dsimansk** [comment]
Actually, I've tried with version 1.3.95 that have your fixes. It's strange that DC delete seems to be working but Pod and RC are throwing NoSuchMethod exception.

**Comment by jimmidyson** [comment]
Hmm odd. Does [this](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java#L105-L120) test case look the same as your code, for pods at least?

**Comment by dsimansk** [comment]
I've been able to narrow it down a bit. It seems that Config and OpenShiftConfig is causing the problem.
In my case, I've started with `OpenShiftConfig` and then switched to `Config` initialization.
If I initialize the client with `Config` I can delete all Kubernetes resources, but for example can't delete Route because of [constructor](https://github.com/fabric8io/kubernetes-client/blob/master/openshift-client/src/main/java/io/fabric8/openshift/client/dsl/internal/RouteOperationsImpl.java#L34) expecting `OpensShiftConfig`. And vice versa [pod constructor](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java#L80) can't be deleted with `OpenShiftConfig`.

**Comment by dsimansk** [comment]
See example exception `OpenShiftClient` + `OpenShiftConfig` deleting RC https://gist.github.com/dsimansk/3bdbd61a6fe01dbe352c224016bbcf3e

**Comment by jimmidyson** [comment]
Thank you for narrowing it down. What you've found makes perfect sense due to the use of reflection for constructors. Will try to fix up tomorrow. Not sure why unit tests don't show it up but we should absolutely have tests for that.

**Comment by dsimansk** [comment]
Indeed blaming reflection for everything. Tried a few hacks today. It seems pretty impossible to decide the type [here](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java#L635-L640) without accessing `OpenShiftConfig.class`, that on the other hand would bring cyclic dependency. 
Not sure about those unit tests, maybe I did some stupid mistake trying to get it working.
Anyway, looking forward to your fix glhf:)

**Comment by jimmidyson** [comment]
Could you share a minimal bit of code to reproduce? Still not sure why I can't repro via unit tests. Are you using at least 1.3.95 or master?

**Comment by jimmidyson** [comment]
I can't reproduce this I'm afraid - guess I'm missing something. This works fine, going from kube client with kube config, adapting to openshift client, using that to perform both kube & openshift requests:

```java
Config config = new ConfigBuilder().withMasterUrl(master).build();

try (KubernetesClient client = new DefaultKubernetesClient(config)) {
  ProjectRequest request = null;
  OpenShiftClient openShiftClient = client.adapt(OpenShiftClient.class);
  try {
    request = openShiftClient.projectrequests().createNew().withNewMetadata().withName("thisisatest").endMetadata().withDescription("Jimmi").withDisplayName("Jimmi").done();

    client.replicationControllers().withName("jimmi").delete();
  } finally {
    if (request != null) {
      openShiftClient.projects().withName(request.getMetadata().getName()).delete();
    }
  }
}
```

**Comment by jimmidyson** [comment]
Aha reproduced - working on fix now.

**Comment by dsimansk** [comment]
Cool. I've fetched your PR and can confirm that it's working for our use case also. The regression is gone for good :) 
Thanks for fixing this quickly.

**Comment by jimmidyson** [comment]
Thanks for confirming.
