### ISSUE TITLE
When I get istio resources object (Gateway, VirtualService), found ValueInstantiationException

### ISSUE THREAD

**Issue by Encounter77** [fabric8io/kubernetes-client#4315]
### Describe the bug

version info:
- fabric kubernates client version: 5.11.2
- fabric istio client version: 5.11.2
- kubernates version: 1.18.10
- istiod version: 1.11.8

### Fabric8 Kubernetes Client version

5.11.2

### Steps to reproduce

1. call fabric istio client
```
 istioClient.v1alpha3().virtualServices().inNamespace(namespace).withName(name).get()
```
2. found AnalysisMessageBaseLevel null exception, value is 3
```
public static AnalysisMessageBaseLevel fromValue(String value) {
	AnalysisMessageBaseLevel constant = CONSTANTS.get(value);
	if (constant == null) {
		throw new IllegalArgumentException(value);
	} else {
		return constant;
	}
}
```

### Expected behavior

1. get istio resource successful
2. how do I view the relationship between istio client version and istio component version

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `io.fabric8.istio.api.analysis.v1alpha1.AnalysisMessageBaseLevel`, problem: 3
 at [Source: (BufferedInputStream); line: 1, column: 1580] (through reference chain: io.fabric8.istio.api.networking.v1alpha3.VirtualService["status"]->io.fabric8.istio.api.meta.v1alpha1.IstioStatus["validationMessages"]->java.util.ArrayList[0]->io.fabric8.istio.api.analysis.v1alpha1.AnalysisMessageBase["level"])
```

**Comment by Encounter77** [comment]
- jackson.version: 2.13.3

**Comment by Encounter77** [comment]
See the enumeration contains only the property

```
public enum AnalysisMessageBaseLevel {

    UNKNOWN("UNKNOWN");

}
```
i use `kubectl get vs xxx -n xxx -o json`, find `level` return `3`, is different from the value defined by the enumeration
```
"status": {
	"validationMessages": [
		{
			"documentation_url": "https://istio.io/v1.11/docs/reference/config/analysis/ist0101/?ref=status-controller",
			"level": 3,
			"type": {
				"code": "IST0101"
			}
		},
		{
			"documentation_url": "https://istio.io/v1.11/docs/reference/config/analysis/ist0101/?ref=status-controller",
			"level": 3,
			"type": {
				"code": "IST0101"
			}
		}
	]
}
```

**Comment by manusa** [comment]
Hi @Sgitario,
Do you know what might be causing this?

**Comment by Sgitario** [comment]
For some reason, the transformer didn't find the enum values for AnalysisMessageBase.Level. I will take a deeper look during this week.

**Comment by Sgitario** [comment]
fyi https://github.com/fabric8io/kubernetes-client/pull/4328
