### ISSUE TITLE
Better Lease Object Handling on Leader Election Cancel

### ISSUE THREAD

**Issue by csviri** [fabric8io/kubernetes-client#4318]
### Is your enhancement related to a problem? Please describe

Will describe the problem in context of operators, considering the following situation:

The controllers are deployed in a way that there are multiple instances running with leader election on. Let's say a new version of the controller is released, in this case the old ones needs to be stopped and one of the new controllers becomes the leader.

In the current implementation when a leader election is cancelled it just stops renewing the lease. However this can cause a delay for the new instances to become a leader (the delay is  <=  [lease duration] + [retry period] ).

### Describe the solution you'd like

Would it be better to on cancel delete or update a Lease object to indicate that now there is no leader?

**Comment by shawkins** [comment]
> Would it be better to on cancel delete or update a Lease object to indicate that now there is no leader?

Makes sense.

**Comment by manusa** [comment]
The [release](https://github.com/kubernetes/kubernetes/blob/f0bd02ca5e1773396288149f4faab25d2f9c6dfe/staging/src/k8s.io/client-go/tools/leaderelection/leaderelection.go#L287-L290) + [releaseOnCancel](https://github.com/kubernetes/kubernetes/blob/f0bd02ca5e1773396288149f4faab25d2f9c6dfe/staging/src/k8s.io/client-go/tools/leaderelection/leaderelection.go#L149-L154) feature is missing and needs to be ported.

**Comment by shawkins** [comment]
The pr has https://github.com/fabric8io/kubernetes-client/pull/4322/files#diff-46850c90b4117631201b452d6d1b2bc5cc7de7270ccda4d69e5ac2c829938419R120 - which takes the current record and sets the duration to 0.  It can of course be made to look like the go code, but I'm not sure why they would leave a 1 second duration or reset the acquireTime as the current is already the leader.

**Comment by manusa** [comment]
> which takes the current record and sets the duration to 0

I'm not sure either, `0` might be interpreted as indefinite duration :shrug:?

In any case, I think we should port the exact behavior to avoid errors or future bugs due to inconsistent behaviors.

**Comment by shawkins** [comment]
> I'm not sure either, 0 might be interpreted as indefinite duration shrug?

No, the time comparison is based upon "time + duration > now" in both the go client and java client.

> In any case, I think we should port the exact behavior to avoid errors or future bugs due to inconsistent behaviors.

The go implementation must have changed a good bit - for example they are no longer relying on timestamps in the record, rather there is a local observedTime instead.

It seems like we'll need a substancial update to this code to keep in sync.

**Comment by manusa** [comment]
> No, the time comparison is based upon "time + duration > now" in both the go client and java client.

The following is what the OpenAPI spec says about the field.

`leaseDurationSeconds is a duration that candidates for a lease need to wait to force acquire it. This is measure against time of last observed RenewTime.`

Which does clarify how this field is intended to be used.

> The go implementation must have changed a good bit

I was just referring to the provision of the replacement record (for the scope of this issue), and in scope of the new values (leaseDurationSeconds, etc.). ----> Basically set the holder identity to null and the duration to 1, not because it makes sense, but because it's what client-go is doing.

**Comment by shawkins** [comment]
closed via #4322
