### ISSUE TITLE
LeaderElection leader transitions

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#4320]
LeaderTransitions is resetting on a change of leadership, and incrementing while holding the lock.  I think this should instead be to increment on a change and to leave the value alone will renewing.

**Comment by manusa** [comment]
The leader election record leaderTransitions field should only increment after a **change** of leadership.

Related client-go code in [leaderelection.go](https://github.com/kubernetes/kubernetes/blob/f0bd02ca5e1773396288149f4faab25d2f9c6dfe/staging/src/k8s.io/client-go/tools/leaderelection/leaderelection.go#L358-L363):
```go
	// 3. We're going to try to update. The leaderElectionRecord is set to it's default
	// here. Let's correct it before updating.
	if le.IsLeader() {
		leaderElectionRecord.AcquireTime = oldLeaderElectionRecord.AcquireTime
		leaderElectionRecord.LeaderTransitions = oldLeaderElectionRecord.LeaderTransitions
	} else {
		leaderElectionRecord.LeaderTransitions = oldLeaderElectionRecord.LeaderTransitions + 1
	}
```

**Comment by shawkins** [comment]
Yes the pr has https://github.com/fabric8io/kubernetes-client/pull/4322/files#diff-46850c90b4117631201b452d6d1b2bc5cc7de7270ccda4d69e5ac2c829938419R200
