### ISSUE TITLE
update compatibility-matrix for kubernetes 1.24

### ISSUE THREAD

**Issue by pierreyvesv** [fabric8io/kubernetes-client#4323]
### Is your task related to a problem? Please describe

Hello,
Kubernetes 1.24 is not listed in the compatibility list, and it list compatibility up to Kubernetes 1.23.3
https://github.com/fabric8io/kubernetes-client#compatibility-matrix

### Describe the solution you'd like

I see that the task " Upgrade Fabric8 Kubernetes Model to Kubernetes v1.24.0 #4031 " has been done.
https://github.com/fabric8io/kubernetes-client/issues/4031

Could the compatibility list be updated with the addition of kubernetes 1.24 ?

https://github.com/fabric8io/kubernetes-client#compatibility-matrix

Thanks

**Comment by rohanKanojia** [comment]
@pierreyvesv : Thanks for noticing! Would appreciate if you could create a PR to fix this

**Comment by pierreyvesv** [comment]
Hi @rohanKanojia ,

here it is https://github.com/fabric8io/kubernetes-client/pull/4329

Regards,
