### ISSUE TITLE
Attach to pod feature

### ISSUE THREAD

**Issue by kuzznya** [fabric8io/kubernetes-client#4333]
### Is your enhancement related to a problem? Please describe

For our current project, we need the ability to attach to the container in a pod to send stdin and read stdout. If I understood correctly, currently there is no way to do it.

### Describe the solution you'd like

Implement `kubectl attach` equivalent the same way as `kubectl exec` is implemented. The main concern regarding the implementation of such feature is that its' DSL would clash the existing one for `exec` (e.g. `redirectingInput().redirectingOutput().exec("...")`). In my point of view, the DSL should be extended instead of copying, i.e.:
```java
ExecWatch execResult = client.pods().withName("...").inContainer("session").redirectingInput().exec("ls");
AttachWatch attachResult = client.pods().withName("...").inContainer("session").redirectingInput().attach("ls");
```

### Describe alternatives you've considered

The alternative way to support such case would be to give a user the ability to use WebSockets directly [as it is implemented in official kubernetes-client](https://github.com/kubernetes-client/java/blob/master/examples/examples-release-15/src/main/java/io/kubernetes/client/examples/WebSocketsExample.java) (though, just to mention, official kubernetes-client has the `attach` feature). I don't like such approach, but it may be easier to implement.

### Additional context

I'm ready to try to implement this feature by myself after syntax & requirements will be clear.

**Comment by shawkins** [comment]
> If I understood correctly, currently there is no way to do it.

On the ExecWatch you can access the redirected streams, which will be attached to the running process.  If you execute something like ls, that will of course terminate quickly - see also the exit code completable future.  If you for example start a shell as the exec command, that will remain open and you can continue to interact with it via the streams.

**Comment by kuzznya** [comment]
> If you for example start a shell as the exec command

Actually this is exactly the task that I'm trying to solve. You are right and this is the way how I tried to implement this feature, but I faced one major problem with this approach: the connection can be lost (due to app failure / rescheduling / client websocket reconnection / some other problems). In that case I am unable to re-attach to the same shell, so I'm losing its context and history. This is why I would like to use `attach` instead of `exec` - in that case even after reconnection I get the same shell.

**Comment by shawkins** [comment]
> Actually this is exactly the task that I'm trying to solve.

It may help to clarify - do you want a new process, or are you trying to attach to the main process of the pod?  It looked like in your initial description that you may have been simply wanting to open a new process/shell, which is supported.  

However attach is not supported. The dsl for that would look like ...attach() - there would be no arguments for the command.

> the connection can be lost (due to app failure / rescheduling / client websocket reconnection / some other problems)

App failure or rescheduling results in a new process - whether we're talking about one started by exec or the pod main process.   Even if there is an auto reconnect, it won't be the same.

**Comment by kuzznya** [comment]
> do you want a new process, or are you trying to attach to the main process of the pod?

I'm trying to attach to the main process (that is actually a shell) of the pod. In that case I can reconnect to the same process (with same previously defined env vars, for example).


> App failure or rescheduling results in a new process

Sorry, I didn't clarify that in my previous message - I meant rescheduling or failure of my app with k8s client, not of a pod with a shell.

**Comment by shawkins** [comment]
> I'm trying to attach to the main process (that is actually a shell) of the pod. In that case I can reconnect to the same process (with same previously defined env vars, for example).

Sounds good.

> I'm ready to try to implement this feature by myself after syntax & requirements will be clear.

Try adding ExecWatch attach() as a method on https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/Execable.java

Then add the attach implementation on PodOperationsImpl - you should be able to reuse most of the exec logic.
