### ISSUE TITLE
spring-cloud-kubernetes-fabric8-leader v2.1.3 does not refresh k8s auth tokens

### ISSUE THREAD

**Issue by henrik242** [fabric8io/kubernetes-client#4342]
### Describe the bug

When using spring-cloud-kubernetes-fabric8-leader v2.1.3, the auth tokens against k8s aren't refreshed automatically.

### Fabric8 Kubernetes Client version

5.10.2 (according to the spring-cloud-kubernetes-fabric8-autoconfig v2.1.3 POM)

### Steps to reproduce

We are getting warnings in our GCP audit logs from our usage of spring leader election:
```
[authentication.k8s.io/stale-token](http://authentication.k8s.io/stale-token): 
  "subject: system:serviceaccount:default:my-app-api, seconds after warning threshold: 798"
```
spring-cloud-kubernetes-fabric8-leader should have their k8s libraries updated to be able to refresh the auth token. The [kubernetes java library](https://github.com/kubernetes-client/java) version 14.0.0 or later should be OK since it includes a [token refresh fix](https://github.com/kubernetes-client/java/pull/1810).

### Expected behavior

The k8s auth tokens should be refreshed regularly.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.22

### Environment

GKE

**Comment by manusa** [comment]
Duplicate of #2112 #2271

**Comment by henrik242** [comment]
@manusa Thanks! Am I right to assume that #4264 is the fix for this?

**Comment by manusa** [comment]
Maybe not for all cluster flavors, but for most of them yes.

It'll be part of 6.1.0 which I'm currently preparing to release.

**Comment by henrik242** [comment]
@manusa Great work! Will there be an accompanying `spring-cloud-kubernetes-fabric8-leader` in the near future too?

**Comment by manusa** [comment]
We're not involved with that project, but I hope so.

I recall @wind57 was interested on upgrading https://github.com/spring-cloud/spring-cloud-kubernetes/issues/1048, maybe he can provide more details.

**Comment by henrik242** [comment]
this is still an issue

**Comment by henrik242** [comment]
https://github.com/spring-cloud/spring-cloud-kubernetes/pull/1165 has been merged!
