### ISSUE TITLE
IllegalStateException with vaild field value

### ISSUE THREAD

**Issue by AlexandrRS** [fabric8io/kubernetes-client#435]
```
openShiftClient
                .roleBindings()
                .inNamespace(nameSpace)
                .withName("system:image-pullers")
                .edit()
                .addToGroupNames("system:serviceaccounts:" + projectName)
                .done();
```

Code below throws exception `IllegalStateException` (fieldname must be match ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$). You use javax.validation.Validation. This is not the best idea, because "system:image-pullers" is a valid value.

**Comment by jimmidyson** [comment]
Thanks for the report - working on fixing this right now actually (similar report with dodgy validations in #424).
