### ISSUE TITLE
HttpClient Jetty depends on JUnit - JUnit dependencyManagement is incomplete

### ISSUE THREAD

**Issue by Xylaant** [fabric8io/kubernetes-client#4360]
### Is your task related to a problem? Please describe

The HttpClient Jetty package leaks its dependencies on junit-jupiter-engine and junit-jupiter-params to downstream users.  This is because the scope tag isn't properly provided in the pom.xml  For example, see the httpclient-jdk pom.xml, which sets the scope to test, as expected.

### Describe the solution you'd like

The junit dependencies should be test scoped.  This should just be an update to the pom.xml to be in line with the other httpclient implementations.

### Describe alternatives you've considered

Users will need to manually exclude the junit dependencies when using the httpclient-jetty

**Comment by rohanKanojia** [comment]
@Xylaant : Could you please raise a PR to fix this?
