### ISSUE TITLE
error updating pods in fabric8 cd pipeline on plain kubernetes

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/kubernetes-client#437]
Using Kubernetes v1.2.2

Error from kubernetes-client..

In the fabric8 CD pipeline feature we are able to create pods for the first time however subsequent updates fail.

`hudson.AbortException: Error during kubernetes apply: Failure executing: PUT at: https://kubernetes.default.svc/api/v1/namespaces/fabric8/pods/pipeline-test-project-1zkl8. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..`

After doing a bit of manual testing using the REST api it looks like the error returned is..

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Pod \"nginx\" is invalid: spec: Forbidden: pod updates may not change fields other than `containers[*].image` or `spec.activeDeadlineSeconds`",
  "reason": "Invalid",
  "details": {
    "name": "nginx",
    "kind": "Pod",
    "causes": [
      {
        "reason": "FieldValueForbidden",
        "message": "Forbidden: pod updates may not change fields other than `containers[*].image` or `spec.activeDeadlineSeconds`",
        "field": "spec"
      }
    ]
  },
  "code": 422
}
```

More details of the investigation can be found in the original error  https://github.com/fabric8io/fabric8/issues/5969

**Comment by jimmidyson** [comment]
Reproduced & now have a better error message in kube client with the exact error so it's easier to diagnose if it happens in future (which it may :(). This may take some time to work through, figuring out how to send only changed fields might be best.

**Comment by rawlingsj** [comment]
You did it!!  just tested and updates are working on plain kubernetes.  many thanks @jimmidyson!

I just need to update fabric8, kubernetes-pipeline and our jenkins image, but it tested locally just fine.

**Comment by rawlingsj** [comment]
tested with kubernetes-client 1.3.96
