### ISSUE TITLE
Alternative to oc whoami --show-token

### ISSUE THREAD

**Issue by Sparker0i** [fabric8io/kubernetes-client#4375]
When I login to my cluster using a username+password combo in the OC CLI tool, I am able to do `oc whoami --show-token` and it displays the OAuth Bearer token with which I am logged in and which is used by the tool to make requests to the cluster.

Using this Openshift-Client library v5, I write a code like this to login to the cluster:

```scala
val config = new OpenShiftConfigBuilder()
  .withMasterUrl(clusterUrl)
  .withTrustCerts(true)
  .withUsername(apiUser)
  .withPassword(apiPassword)
  .withNamespace(namespace)
  .build()

val _ocClient = new DefaultOpenShiftClient(config)
```

Is there a way we can programatically get access to the token being used just like the command used in the oc cli?

**Comment by manusa** [comment]
Have you tried this:
```java
client.getConfiguration().getOauthToken();
// Or
client.getConfiguration().getPassword();
```

Maybe the token is accessible in one of those.

**Comment by Sparker0i** [comment]
Sorry for the late response, `getPassword` works, but it just prints the same `apiPassword` that I had passed. Doing with `getOauthToken()` is returning null unfortunately.

But surprisingly I'm able to perform other operations on the cluster, so surprising how the oauthtoken is returning null..

**Comment by Sparker0i** [comment]
Sorry I've got to open this up again. So we have two kinds of clusters. One where we can login with a service account token directly and another one where we have to give a user name and password.

When we login to both kind of clusters using this library, we are able to perform operations. 
However when we try to run the `getOauthToken()` for the second cluster, it shows `null`, despite being able to perform other kind of operations with the cluster like listing pods in a namespace, creating jobs etc..
