### ISSUE TITLE
How Can I Use URL to Files to Create The Resource

### ISSUE THREAD

**Issue by stupid-yu** [fabric8io/kubernetes-client#4376]
Hello，Is there any Implementation for this api

**Comment by rohanKanojia** [comment]
@stupid-yu : You mean download a file and then create resource?

**Comment by stupid-yu** [comment]
@rohanKanojia yes，just like the case as follow
`kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml`

**Comment by stupid-yu** [comment]
Agree with u,Thanks a lot.
