### ISSUE TITLE
[java-gen] - Generated Java model should include new specific annotations (min, max, etc.)

### ISSUE THREAD

**Issue by fabiobrz** [fabric8io/kubernetes-client#4384]
### Is your enhancement related to a problem? Please describe

[Support for specific annotations](https://github.com/fabric8io/kubernetes-client/pull/4348) (e.g.: `@Max`, `@Min`, `@Pattern`, etc.), was added recently but the Java generator doesn't generate any of such annotations.

### Describe the solution you'd like

The Java generator should take the related keywords into account when they appear in CRDs (e.g.: `maximum`, `minimum`, `pattern`, etc.), and generate the corresponding annotations for them to appear in the Java model.

### Describe alternatives you've considered

N/A

### Additional context

See:
* [Introduce specific annotations for the generators](https://github.com/fabric8io/kubernetes-client/pull/4348) and specifically https://github.com/fabric8io/kubernetes-client/pull/4348#issuecomment-1236555434
* [Add support for Min, Max, Pattern and Nullable on CRD generator fields](https://github.com/fabric8io/kubernetes-client/pull/4298)

**Comment by derlin** [comment]
Those new annotations look great !
I see you did a release of the kubernetes-client, but the `generator-annotations` module still isn't available on maven central. Given the doc has been updated, it is quite confusing ^^'. Do you plan to release the annotations soon ?

**Comment by andreaTP** [comment]
@derlin which version are you using?
The Java generator is available only 6+

**Comment by derlin** [comment]
I am using 5.13.3 and tried the latest version (5.13.4). Maybe this is where I am confused, then. Could you explain the difference between the 5.x and 6.x tracks ?

**Comment by andreaTP** [comment]
I actually cannot find `generator-annotations` even for version `6.1.1` : https://repo1.maven.org/maven2/io/fabric8/ ( `crd-generator` is fine instead)
@manusa was it ever shipped?

Regarding the difference you can read more here: https://developers.redhat.com/articles/2022/07/15/new-http-clients-java-generator-and-more-fabric8-600

**Comment by manusa** [comment]
This is part of the 6.2.0 milestone, it will be available once we cut this release.

**Comment by bachmanity1** [comment]
This is actually a little confusing because [documentation](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CRD-generator.md) has already been updated but release is not out yet. I've spent last couple of hours figuring out why imports related to this feature are not working in my project only to realize that this feature is not available yet.

**Comment by andreaTP** [comment]
Hi @bachmanity1 , sorry for the confusion and trouble, `fabric8` `6.2.0` is out now and since we don't have it properly "versioned" I encourage you to browse the docs using the appropriate `tag` e.g.:
https://github.com/fabric8io/kubernetes-client/tree/v6.2.0/doc
