### ISSUE TITLE
Config.fromKubeconfig does not respect the result of method loadFromKubeconfig

### ISSUE THREAD

**Issue by own-idea** [fabric8io/kubernetes-client#4391]
### Is your enhancement related to a problem? Please describe

the method `fromKubeconfig` in Config class ignore the method `loadFromKubeconfig` result, it maybe inappropriate.
```java
  public static Config fromKubeconfig(String context, String kubeconfigContents, String kubeconfigPath) {
    // we allow passing context along here, since downstream accepts it
    Config config = new Config();
    if (kubeconfigPath != null)
      config.file = new File(kubeconfigPath);
    loadFromKubeconfig(config, context, kubeconfigContents);
    return config;
  }
```

### Describe the solution you'd like

we should throw exception when the method `loadFromKubeconfig`  return false. Absolutely, the change is breaking.

**Comment by Jatinkhatri-hub** [comment]
Hi, I am new to open source and would like to work on this issue. Can you help me how to get started?

**Comment by own-idea** [comment]
> Hi, I am new to open source and would like to work on this issue. Can you help me how to get started?
you may see [the comment](https://github.com/fabric8io/kubernetes-client/issues/2404#issuecomment-674806565)

**Comment by Jatinkhatri-hub** [comment]
Thanks for your help.

**Comment by Jatinkhatri-hub** [comment]
@own-idea  I am not fully able to understand what the issue is can you describe the issue a little bit more?
