### ISSUE TITLE
BackwardsCompatibilityInterceptor add support for cronJob batch/v1

### ISSUE THREAD

**Issue by own-idea** [fabric8io/kubernetes-client#4400]
### Is your enhancement related to a problem? Please describe

when i use `client.batch().v1().cronjobs().inNamespace("demo").withName("demo").`, but kube-apiserver don't have batch/v1 version only v1/beta1. I think we may add the support.

### Describe the solution you'd like

add the code below in class `BackwardsCompatibilityInterceptor`
```java
notFoundTransformations.put(new ResourceKey("CronJob", "cronjobs", "batch", "v1"),
        new ResourceKey("CronJob", "cronjobs", "batch", "v1beta1"));
```

**Comment by manusa** [comment]
Although the interceptor covers similar cases for other resources such as Deployment, DaemonSet, and so on, it's main purpose is/was to provide compatibility with older OpenShift clusters.

I'm or very fond of the other intercepts where we _"desperately"_ try to operate with resource structured using a new version schema, with an older one.

That said, have you compered the structure/schema of CronJob in `v1` and `v1beta1`. Are they compatible? are the differences subtle and only incremental for the newer version?

**Comment by own-idea** [comment]
> Although the interceptor covers similar cases for other resources such as Deployment, DaemonSet, and so on, it's main purpose is/was to provide compatibility with older OpenShift clusters.
> 
> I'm or very fond of the other intercepts where we _"desperately"_ try to operate with resource structured using a new version schema, with an older one.
> 
> That said, have you compered the structure/schema of CronJob in `v1` and `v1beta1`. Are they compatible? are the differences subtle and only incremental for the newer version?

thank for your reply. I compared CronJob `v1` and `v1beta1` , it seems compatible.

**Comment by manusa** [comment]
> thank for your reply. I compared CronJob `v1` and `v1beta1` , it seems compatible.

Would you like to create a PR with this change?

**Comment by own-idea** [comment]
> > thank for your reply. I compared CronJob `v1` and `v1beta1` , it seems compatible.
> 
> Would you like to create a PR with this change?

yes
