### ISSUE TITLE
events().inAnyNamespace does not report an event for newly created namespace if watch established using same connection as that used to create the namespace

### ISSUE THREAD

**Issue by buildlackey** [fabric8io/kubernetes-client#441]
I am including a small program that replicates this problem:
  events().inAnyNamespace does not report an event for newly created namespace if the watch is established using the same connection as that used to create the namespace.

If you run the program below without any modification you will see  a line like the one below in 
your output:

    EVENT =>  .. <lots of event stuff > 

However if you uncomment the lines in the comment block labeled  "TO REPRODUCE BUG" and comment out this line ->     

```
getConnection.events(). inAnyNamespace(). watch(getEventReceivedHandler)
```
You will no longer see that output. This seems to have something to do with what connection 
you are using to create the event, which at first glance does not seem to be correct behavior.
thanks in advance for looking at this. 
 /chris

```
import com.typesafe.scalalogging.StrictLogging
import io.fabric8.kubernetes.api.model.{Event, Namespace}
import io.fabric8.kubernetes.client.Watcher.Action
import io.fabric8.kubernetes.client._
import scala.collection.JavaConverters._

object LabelTest  extends App with StrictLogging {

  val k8sUrl = "http://localhost:8080"
  val namespaceName = "junk6"

  def go(): Unit = {
    val kube: KubernetesClient = getConnection

    createEventWatch(kube)
    Thread.sleep(2 * 1000)

    val retval: Namespace = kube.namespaces().createNew()
      .withApiVersion("v1")
      .withNewMetadata()
      .withName(namespaceName)
      .withLabels(Map("animal" -> "dog").asJava)
      .endMetadata()
      .done()

    Thread.sleep(20 * 1000)
  }

  def getConnection = {
    val configBuilder =   new ConfigBuilder()       /*   For newer fabric8, replace with:  Config.builder() */
    val config =
      configBuilder.
        withMasterUrl(k8sUrl).                    /* For older fabric8, replace with:  masterUrl  */
        build()
    new DefaultKubernetesClient(config)
  }

  def createEventWatch(kube: KubernetesClient) = {
    /*

    // TO REPRODUCE BUG:  you need to uncomment the lines in this comment block

    kube.
      events().
      inAnyNamespace().
      watch(getEventReceivedHandler)
     */

    // TO REPRODUCE BUG:  please comment out the line below, and UNCOMMENT the lines above
    getConnection.events(). inAnyNamespace(). watch(getEventReceivedHandler)


    def getEventReceivedHandler: Watcher[Event] = {
      new Watcher[Event]() {
        override def eventReceived(action: Action, resource: Event) {
          logger.info("EVENT => {}: {}", action, resource)
        }

        override def onClose(e: KubernetesClientException) {
          if (e != null) {
            logger.error("improper close of k8s event watcher", e)
          } else {
            logger.error("improper close of k8s event watcher")
          }
        }
      }
    }
  }

  go()
}


```

**Comment by jimmidyson** [comment]
Is it just the create event for the namespace that's not working or any events for creating resources in the new namespace too? I've just recreated not receiving the create event for the new namespace via curl which indicates it's a problem with Kubernetes itself rather than the fabric8 client. I would expect, however, to receive events for resources created in the new namespace though.

If you're interested in receiving events for new namespaces then you can watch namespaces directly (`client.namespaces().watch(...)` rather than events).

**Comment by jimmidyson** [comment]
I've just confirmed that it is only the create namespace event that doesn't get received & this is reproducible via curl to the API server. Closing as this is an issue with Kubernetes, not this client. Will raise an issue with Kubernetes & cc you in so you can track if you want to.

**Comment by buildlackey** [comment]
>re: 
Is it just the create event for the namespace that's not working or any events for creating resources in the new namespace too? 
>

i only experienced issues wi/ the create event for the namespace itself  (as shown in the sample program).   thanks  /cb

**Comment by jimmidyson** [comment]
Thanks for confirming - I've opened kubernetes/kubernetes#26911 to see if this can be fixed in Kubernetes.
