### ISSUE TITLE
Comment based CI checks

### ISSUE THREAD

**Issue by fabiobrz** [fabric8io/kubernetes-client#4411]
### Is your task related to a problem? Please describe

Currently there's no way to trigger the project CI checks for PRs other than pushing changes or closing/reopening a PR.

Both the solutions above seem not to fit properly since:
1. pushing changes might be undesirable and confusing, once a PR has been reviewed and approved already
2. closing/reopening allows for running the CI checks as many times as a contributor would, so why don't provide them with a command instead?

### Describe the solution you'd like

To trigger the CI checks by issuing conventional comments to the PR, e.g.: `/test` or something like that.

### Describe alternatives you've considered

Closing/reopening a PR, but it isn't really much different.

**Comment by manusa** [comment]
I'm not sure if there's a built-in way for GH Actions to react to PR comments or something similar. If there is, then certainly this can be a good addition (also as long as the 'approve test run' action has been performed by maintainers -> crypto mining, etc.)

If it's not possible, then creating this could be done, but would require hosting a webhook listener with the required repo permissions elsewhere. Personally, I don't see this worth the effort.

> pushing changes might be undesirable and confusing, once a PR has been reviewed and approved already

If the PR has been reviewed+**approved**, the checks should be passing in the first place.

**Comment by fabiobrz** [comment]
Thanks for your feedback @manusa 

> I'm not sure if there's a built-in way for GH Actions to react to PR comments or something similar. If there is, then certainly this can be a good addition (also as long as the 'approve test run' action has been performed by maintainers -> crypto mining, etc.)

+1, thanks. I'll have a look around since I am collecting some knowledge for a similar issue elsewhere.

> If it's not possible, then creating this could be done, but would require hosting a webhook listener with the required repo permissions elsewhere. Personally, I don't see this worth the effort.

+1, at such point closing/reopening would be one acceptable tradeoff.

> If the PR has been reviewed+**approved**, the checks should be passing in the first place

Correct, although I found myself in this situation in the morning after I had green CI checks, the PR reviewed and approved, but pushed to squash commits.

**Comment by fabiobrz** [comment]
> +1, thanks. I'll have a look around since I am collecting some knowledge for a similar issue elsewhere.

BTW - this looks promising, the job could discriminate based on the actual comment phrase, and quit if not matching any of the allowed values: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only

I could report after I experiment on a fork that I own, since it seems this would only work on the default branch.
FYI @manusa

**Comment by rohanKanojia** [comment]
@fabiobrz : polite ping, are you still working on this issue? Shall I reopen it or leave it as it is?

**Comment by fabiobrz** [comment]
> @fabiobrz : polite ping, are you still working on this issue? Shall I reopen it or leave it as it is?

Hi @rohanKanojia - sorry for the late reply. I had to stop working on some projects for quite some time. I'll resume from here, although currently with low prio. Maybe I'll reach out to you in order to reopen as soon as I've got something.
