### ISSUE TITLE
Pod execWatch exec method shell execution result is incorrect

### ISSUE THREAD

**Issue by WishTimeLe** [fabric8io/kubernetes-client#4437]
### Describe  Problem
The scenario is to perform shell conditional filtering by grep, but the effect is not satisfactory.
I suspect the request param is forcibly overwritten by single quotes.

### Fabric8 Kubernetes Client version
5.1.1

### Results show
![image](https://user-images.githubusercontent.com/59165885/191467691-3f0d4587-ab27-4546-9a41-c02723d5dbf1.png)
![image](https://user-images.githubusercontent.com/59165885/191469011-f57b629f-737a-41d6-93e3-4df18271ea30.png)

**Comment by rohanKanojia** [comment]
@WishTimeLe : We have improved our exec a lot in 6.x versions of client. Is it possible for you to migrate to latest version?

**Comment by WishTimeLe** [comment]
@rohanKanojia：I just tried to upgrade the Client version to 6.1.1 with the same result

**Comment by shawkins** [comment]
@WishTimeLe the current logic treats each string after the first as an argument to that command - not as part of a separate shell command.  I believe you have to do this as an argument to sh: exec("sh", "-c", "df -h | grep tmpfs")

**Comment by WishTimeLe** [comment]
@shawkins Thank you. That's what I want to know and use
