### ISSUE TITLE
KnativeClient.isSupported doesn't check all of the applicable API Groups

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#4447]
### Describe the bug

Initially reported: https://github.com/quarkusio/quarkus/issues/28171
With fix: https://github.com/quarkusio/quarkus/pull/28172

The current implementation of `isSupported()` for `KnativeClient` is:
```java
  public boolean isSupported() {
    return hasApiGroup("knative.dev", true);
  }
```

This is not taking into consideration all of the API groups our models support:
* serving.knative.dev
* flows.knative.dev
* networking.internal.knative.dev
* etc.

### Fabric8 Kubernetes Client version

6.0.0

### Steps to reproduce

- In a cluster with Knative CRDs, invoke the `KnativeClient.isSupported` method.
- `false` is returned instead of `true`

### Expected behavior

`true` should be returned instead

### Suggested fix

The [check](https://github.com/fabric8io/kubernetes-client/blob/0308e299313a12c72b9313730a397e894d7278b0/extensions/knative/client/src/main/java/io/fabric8/knative/client/DefaultKnativeClient.java#L242-L246) should not be exact:
```java
  public boolean isSupported() {
    return hasApiGroup("knative.dev", false);
  }
```

**Comment by shawkins** [comment]
This change should be applied to DefaultServiceCatalogClient as well.

**Comment by rohanKanojia** [comment]
@shawkins : I'm not sure if I understand. From my understanding we only want to use `hasApiGroup("<>", true)` only when the client is dealing with model types that come from a single apiGroup. All resources in `service-catalog` module seem to be coming from `servicecatalog.k8s.io` apiGroup:

https://github.com/fabric8io/kubernetes-client/blob/c134637413abe2bf984e8f2c8fa37fc1bf15f1e1/extensions/service-catalog/generator/cmd/generate/generate.go#L57-L59

Isn't it working as expected? Or perhaps I've misunderstood the problem.
