### ISSUE TITLE
How to use `kubectl proxy` in this client?

### ISSUE THREAD

**Issue by liziwl** [fabric8io/kubernetes-client#4465]
How to use `kubectl proxy` in this client?

I want to setup a apiserver proxy like `kubectl proxy` do. I checked example in this repo but I don't find one can be used.

**Comment by rohanKanojia** [comment]
Umm, Do you know how does `kubectl proxy` work? I'm checking `kubectl proxy -v=9` but I'm not able to see any REST API calls. I'm not sure whether there is any REST API exposed for it.

**Comment by liziwl** [comment]
Proxying feature seems for debug, and I agree that it probably doesn't need to be implemented in the Java client.
