### ISSUE TITLE
Loading a template with an Integer parameter value fails deserialisation 

### ISSUE THREAD

**Issue by donovanmuller** [fabric8io/kubernetes-client#448]
Using the OpenShift client, I have a `Template` with a `Service` like this:

```
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        name: "deployment-test"
      name: "deployment-test"
    spec:
      template:
        metadata:
          labels:
            name: "deployment-test"
      ports:
        - name: http
          port: ${SERVER_PORT}
          targetPort: http
      selector:
        name: "deployment-test"
```

When trying to load the template:

```
client.templates().load(new ClassPathResource("template.yaml").getInputStream()).get();
```

 I get:

```
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of java.lang.Integer from String value '${SERVER_PORT}': not a valid Integer value
 at [Source: N/A; line: -1, column: -1] (through reference chain: io.fabric8.openshift.api.model.Template["objects"]->java.util.ArrayList[3]->io.fabric8.kubernetes.api.model.Service["spec"]->io.fabric8.kubernetes.api.model.ServiceSpec["ports"]->java.util.ArrayList[0]->io.fabric8.kubernetes.api.model.ServicePort["port"])
    at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:55) ~[jackson-databind-2.6.6.jar:2.6.6]
```

using the following parameter value:

```
...
parameters:
  - name: SERVER_PORT
    displayName: HTTP port
    value: 8080 // can be "8080", doesn't matter, same issue
    required: true
```

This is probably/maybe related to https://github.com/openshift/origin/issues/3946...

**Comment by jimmidyson** [comment]
Yeah looks like it's not supported by OpenShift at the moment. We generate the Java model from OpenShift's Go source so inherit the same issues that there's nothing much we can do about I'm afraid.

**Comment by jstrachan** [comment]
Though wouldn't the http port for the service always be '80' anyway? ;)

**Comment by jimmidyson** [comment]
Well yes I personally wouldn't make the service port configurable, but there may be a use case I'm missing that requires that.

**Comment by sutaakar** [comment]
Current OpenShift version seems to support Integer parameters values [1]. Are there some plans to add this feature also here into the client?

[1] https://docs.openshift.org/latest/dev_guide/templates.html#writing-parameters

**Comment by tremes** [comment]
JBoss templates uses this option - e.g https://github.com/jboss-container-images/datagrid-7-image/blob/datagrid-services-dev/templates/caching-service.json#L149 and so the attempt to load (or access) them is failing.

**Comment by denismaggior8** [comment]
Any news on this? I’ve the same problem with OKD 3.11 which actually support integer template params...

**Comment by manusa** [comment]
@denismaggior8 Which version of kubernetes-client are you using?

I can't recall if we already tackled this in #1977 (#959).

**Comment by denismaggior8** [comment]
@manusa, I use the following dependencies:

<dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>kubernetes-client</artifactId>
            <version>4.9.1</version>
        </dependency>

        <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>openshift-client</artifactId>
            <version>4.9.1</version>
        </dependency>

**Comment by manusa** [comment]
Ok, thx.
We'll review again. I'm recalling that there was some problem when using the double brace syntax and numbers (was working OK for boolean values). We'll check again.

**Comment by stefanofiore15** [comment]
Same problem either uploading, downloading or processing  template. 
Cannot deserialize value of type `java.lang.Integer` from String "${PORT}": not a valid Integer value
Even using or removing quotes, still same error is showing up.

**Comment by shawkins** [comment]
Logged more recently as #3460
