### ISSUE TITLE
testSerializeYamlWithAlias failing

### ISSUE THREAD

**Issue by DobromirM** [fabric8io/kubernetes-client#4484]
### Is your task related to a problem? Please describe

`testSerializeYamlWithAlias` in `SerializationTest` is failing due to incorrect assertion.

### Describe the solution you'd like

Change the assertion.

**Comment by DobromirM** [comment]
Fixes #4484

**Comment by andreaTP** [comment]
The test is correctly passing on `master` in CI.
Where is the failure occurring? Is is a reproducible environment?

**Comment by manusa** [comment]
This is already covered by https://github.com/fabric8io/kubernetes-client/pull/3612/files
