### ISSUE TITLE
KubernetesResourceList resources are not handled properly by AbstractWatchManager

### ISSUE THREAD

**Issue by StupidScience** [fabric8io/kubernetes-client#4496]
### Describe the bug

In #4365 was introduced [change](https://github.com/fabric8io/kubernetes-client/pull/4365/files?diff=unified&w=1#diff-7ca5806d751b9d76ce33e1adbef2dabd2ef3c10d499aeb66215451bd8bbff802L285-R295) that in a nutshell changed from this:
```
if (object instanceof KubernetesResourceList) {}
else if (object instanceof HasMetadata) {}
```
to 
```
if (object instanceof HasMetadata) {
  if (object instanceof KubernetesResourceList) {}
}
```

But AFAIU KubernetesResourceList doesn't implement HasMetadata so any event will end up with error `io.fabric8.kubernetes.client.WatcherException: Invalid object received: ...`

### Fabric8 Kubernetes Client version

5.12.4

### Steps to reproduce

1. Send event with any List resource to watcher
2. Got an exception

### Expected behavior

List resources expected to be handled

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

other (please specify in additional context)

**Comment by shawkins** [comment]
@StupidScience what watch is this happening with specifically?  I can see in the history that the list handling was added for api group watches - and I don't see that a mock or a integration test was ever specifically added.

**Comment by StupidScience** [comment]
@shawkins not sure that I get your question. Do you mean what specific resource watcher? If yes then in our case it is for Endpoints.

**Comment by shawkins** [comment]
@StupidScience what kubernetes version are you on?

**Comment by StupidScience** [comment]
@shawkins it occurred in our tests actually with mock KubernetesServer after update to 5.12.4. Rollback to 5.12.3 fix the issue.

**Comment by shawkins** [comment]
@StupidScience from what I can see the api server does not (at least with v1.22.2) respond with a list object when you watch Endpoints.  It would be great to capture definitively where this is still happening.

**Comment by manusa** [comment]
I agree with Steven, the following code:
https://github.com/fabric8io/kubernetes-client/blob/0394a0e3d9c2fe4afd0aaa7098b140553b371af3/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/AbstractWatchManager.java#L292-L308

should be simply replaced to:

```java
        HasMetadata hasMetadata = (HasMetadata) object;
        updateResourceVersion(hasMetadata.getMetadata().getResourceVersion());
        eventReceived(action, hasMetadata);
```
