### ISSUE TITLE
Delete job not delete pods

### ISSUE THREAD

**Issue by fatduo** [fabric8io/kubernetes-client#450]
Hi,
When I use 
`client.extensions().jobs().inNamespace("defalut").delete(job)`
to delete a job, the pods of job cannot be deleted.

I use kubernetes-client 1.3.97

ps. I saw some notes at
[https://groups.google.com/forum/#!topic/fabric8/nxlrLynzXwU](url)

Did the pr commit?

**Comment by yaoyu26** [comment]
I met the same problem
i use like this,
'client.extensions().jobs().inNamespace(namespace).withName(jobName).cascading(true).delete();'
although i use 'cascading(true)' ,pod still exist.

**Comment by jimmidyson** [comment]
Can you try with 1.3.98 please?

**Comment by jimmidyson** [comment]
Closing as this should now be fixed.

**Comment by liketic** [comment]
I met this problem in the latest 4.3.0.

**Comment by rohanKanojia** [comment]
@liketic : Can you provide a test case?

**Comment by liketic** [comment]
@rohanKanojia I delete the job as:
```
            ScalableResource<Job, DoneableJob> job = client.batch().jobs()
                    .inNamespace(clusterConfig.getNamespace())
                    .withName(k8sJobName);
            Job runningJob = job.get();
            if (runningJob == null) {
                LOG.warn("Job {} does not exist!", k8sJobName);
                return;
            }
            // Ensure all tasks are finished(succeed or failed) before delete job.
            job.delete();
            LOG.info("Salve job {} has been deleted", k8sJobName);
```
The job has been deleted successfully. However, the pods are still there.

**Comment by rohanKanojia** [comment]
do you have `cascading()` flag in the dsl in case of jobs? If yes, Can you try again with it set to true?

**Comment by rohanKanojia** [comment]
I mean something like this:
```
client.batch().jobs().inNamespace(namespace).withName("xyz").cascading(true).delete();
```

**Comment by liketic** [comment]
Thank you @rohanKanojia , seems that works.
