### ISSUE TITLE
kubernates client should be able to use customized ObjectMapper for deserialize response

### ISSUE THREAD

**Issue by HuangZhenQiu** [fabric8io/kubernetes-client#4502]
### Is your enhancement related to a problem? Please describe

For new K8 operator in development, it is easy for developers in community to change the CRD with new fields. It is also common that platform services talk with api server for CR deployment or update. If operator is upgraded with such breaking changes, the backend service will fail to create CR due the the deserialization issue. The reason behind it is that io.fabric8.kubernetes.client.dsl.base.OperationSupport is using a predefined ObjectMapper in io.fabric8.kubernetes.client.utils.Serialization . It will be easier for user to maintain and upgrade the system if we can support customized ObjectMapper in io.fabric8.kubernetes.client.Config by add an new field to set DeserializationConfig.Feature.FAIL_ON_UNKNOWN_PROPERTIES = false

class:  io.fabric8.kubernetes.client.KubernetesClientException 
      msg:  An error has occurred. 
      stack: [ [[-]](https://splunk-if.icloud.apple.com/en-US/app/search/search?sid=1665762331.71304_9CB3C60F-F367-4337-BF50-8496D2B860DF&dispatch.sample_ratio=1&display.page.search.mode=verbose&q=search%20index%3Daci-spark%20source%3D%22%2Fopt%2Flogs%2Fravel.log%22%20*error*&earliest=-15m&latest=now#) 
        io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:103) 
        io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:97) 
        io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:319) 
        io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:271) 
        io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:557) 
        io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:518) 
        io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:487) 
        io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:457) 
        io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:698) 
        io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:184) 
        io.fabric8.kubernetes.client.dsl.base.BaseOperation.require(BaseOperation.java:165) 
        io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.requireFromServer(HasMetadataOperation.java:120) 
        io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:188) 
        io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:141) 
        io.fabric8.kubernetes.client.utils.CreateOrReplaceHelper.replace(CreateOrReplaceHelper.java:69) 
        io.fabric8.kubernetes.client.utils.CreateOrReplaceHelper.createOrReplace(CreateOrReplaceHelper.java:61) 
        io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:318) 
        io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:83) 
        io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:308) 
        io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:83)

### Describe the solution you'd like

Add a new config field ignoreUnknownField in io.fabric8.kubernetes.client.Config. io.fabric8.kubernetes.client.dsl.base.OperationSupport will create a ObjectMapper with ignoreUnknownField config to call io.fabric8.kubernetes.client.utils.Serialization to deserialize responses.

**Comment by HuangZhenQiu** [comment]
It is handled in  https://github.com/fabric8io/kubernetes-client/issues/1308.

**Comment by shawkins** [comment]
@HuangZhenQiu another thing to consider rather than doing this at the mapper level is the approach of adding an additionalProperties map to your model objects.  That provides more flexibility - as you can optionally retain those fields, or detect / handle api mismatches.
