### ISSUE TITLE
Improve test stability

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#4507]
### Is your task related to a problem? Please describe

Both the regular and integration tests are routinely failing.

### Describe the solution you'd like

Diagnose and update the test logic - from some of the recent prs:

Timeout is too short:
https://github.com/fabric8io/kubernetes-client/actions/runs/3272864707/jobs/5384383421#step:4:30639
https://github.com/fabric8io/kubernetes-client/actions/runs/3275507794/jobs/5390447428#step:4:33888
Testing locally an informOnCondition can take over 300ms, 1 second on github is cutting it too close.  Based upon the other test timeouts it seems like 10s is the most common in use for mock tests, so I'll update the tests to that.

Karaf artifact related:
https://github.com/fabric8io/kubernetes-client/actions/runs/3272243272/jobs/5383015653#step:4:44624
https://github.com/fabric8io/kubernetes-client/actions/runs/3249472532/jobs/5331916273#step:4:51981
- not sure what's going on there.

Delete never processed:
https://github.com/fabric8io/kubernetes-client/actions/runs/3250738892/jobs/5335104309#step:6:441
https://github.com/fabric8io/kubernetes-client/actions/runs/3284978788/jobs/5411769181#step:6:456
- cannot reproduce these, I believe this is just another issue with the timeout being too short.  In local runs some of the dependent resource deletion took up to 10 seconds.

**Comment by manusa** [comment]
The Karaf tests were already refactored a while back, we managed to improve their stability, but with newer versions of Karaf, it seems to have degraded again.

For the timeouts, we should really try to make the tests run quicker. We already did a few iterations on this in the past. We should probably spend again some time on this. Many of the new tests should also be split into multiple, more granular cases with single assertions (this should also improve their stability).

For the delete operations, I also remember refactoring part of this not so long ago. IIRC in some cases we're performing unnecessary assertions, but I need to further check this.
