### ISSUE TITLE
Remove model properties

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#4515]
It's been so long that I can't really recall the need for model properties. I would assume though that it was added to serve code generation purposes in the client. Possibly, at some point it was needed to generate `ResourceHandlers` or `OperationImpl`.

_Originally posted by @iocanel in https://github.com/fabric8io/kubernetes-client/issues/4511#issuecomment-1285086837_

**Comment by shawkins** [comment]
cc @rohanKanojia @manusa any object to removing the legacy model.properties files?  We will still need the manifest.vm if we move forward with #4511

**Comment by manusa** [comment]
please go ahead

**Comment by shawkins** [comment]
Let's first decide on #4511

**Comment by manusa** [comment]
> Let's first decide on #4511

Noted. For some reason I'm reviewing my pending tasks/emails/notifications in a very random order :sweat_smile:

**Comment by manusa** [comment]
Since we seem to agree that #4511 is the way to go forward with the `KubernetesDeserializer`, we should close this issue now.
