### ISSUE TITLE
TokenRefreshInterceptor doesn't respect kubernetes.disable.autoConfig flag

### ISSUE THREAD

**Issue by vanjadardic** [fabric8io/kubernetes-client#4519]
### Describe the bug

TokenRefreshInterceptor doesn't respect kubernetes.disable.autoConfig flag.

### Fabric8 Kubernetes Client version

6.2.0

### Steps to reproduce

Instantiate client using
```java
KubernetesClientBuilder().withConfig(Config.fromKubeconfig(someconfig)).build();
```
but also have a file at `/var/run/secrets/kubernetes.io/serviceaccount/token` with some different token than in `someconfig`.
After 1 minute my calls start failing with `"Unauthorized! Token may have expired! Please log-in again."`.

### Expected behavior

Calls don't start failing.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

**Comment by shawkins** [comment]
kubernetes.disable.autoConfig is currently only used by the Config() constructor.  It is not used for any other purpose.

Presumably your problem stems from https://github.com/fabric8io/kubernetes-client/blob/43b67939fde91046ab7fb0c362f500c2b46eb59e/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/TokenRefreshInterceptor.java#L76

It seems like this logic should be handling 3 cases - auto configured, from file, and direct contents.

```
Config newestConfig = config;
final String currentContextName = config.getCurrentContext() != null ? config.getCurrentContext().getName() : null;
if (config.getAutoConfigure()) {
  newestConfig = Config.autoConfigure(currentContextName);
}
if (config.getFile() != null) {
  // reload from file
  newestConfig = ...
}
// else contents supplied directly, no refresh
```

@vanjadardic does that match your expectations?

cc @rohanKanojia @manusa

**Comment by vanjadardic** [comment]
Yes, that would make the configuration/refresh logic behave according to my expectations.

**Comment by denisMihaylov** [comment]
We stumbled upon this issue when we moved to 6.2.0 and this auto configure option completely blocks our scenarios. We cannot use 5.x.x because it does not support Kubernetes 1.24. When do you plan to release 6.3.0 and is there another workaround that we can use in the meantime?
