### ISSUE TITLE
`SharedIndexInformer` should not stop on missing rbac permissions when calling `start()`

### ISSUE THREAD

**Issue by csviri** [fabric8io/kubernetes-client#4527]
### Describe the bug

Currently when I `start()`   `SharedIndexInformer` and the informer does not have sufficient permissions for the resources, the informer is stopped.

This is inconsistent with the behavior, that when I start the informer and remove rbac permissions for the resource, the informer will try to reconnect over and over again.

### Fabric8 Kubernetes Client version

6.2.0

### Steps to reproduce

I prepared an integration test for this case:
https://github.com/java-operator-sdk/java-operator-sdk/blob/992b2a1e05155ab3e4c6526a17dc7e15d9d866a4/operator-framework/src/test/java/io/javaoperatorsdk/operator/RBACBehaviorIT.java#L55-L67

(Note to try it out those tests  with `minikube` use the following command to start minikube: `minikube start --extra-config=apiserver.min-request-timeout=3`
so the API server disconnects watch in every 3  seconds and do the permission checking again on watch connect - it is not strictly needed for this test however. 
)

### Expected behavior

To retry to reconnect event there are no sufficient permissions on the startup.

### Runtime

minikube

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

**Comment by shawkins** [comment]
This duplicates #4408

**Comment by csviri** [comment]
Ahh, see it now, thx, will close this issue.
