### ISSUE TITLE
File upload unusual behaviour on a ' character

### ISSUE THREAD

**Issue by BrianDevC** [fabric8io/kubernetes-client#4535]
### Describe the bug

A file or folder with the single quote ' character in the path name will exhibit unusual behaviour on the upload.

For example if uploading to /data/te'st/file.txt

The following two folders will be created. All square brackets[] added here to emphasize individual folders, they do not show up in the test.

**Empty folder:**
/[data]/[te'st]/

**Folder with empty file.txt**
/[data]/[te\st && base64 -d - >]/[data]/[te\\st]/file.txt

### Fabric8 Kubernetes Client version

5.12.4

### Steps to reproduce

```
String path = "/data/te'st/file.txt";
            client
                    .pods()
                    .withName(podName)
                    .file(path)
                    .upload(inputStream);
```

### Expected behavior

**Empty folder:**
/data/te'st/

**Folder with empty file.txt**
/data/te\st && base64 -d - >/data/te\\st/file.txt

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.24

### Environment

Linux

### Additional context

Looks to be the area that's causing the issue is here:
https://github.com/fabric8io/kubernetes-client/blob/0f997aade423fe2612250096cf87015d040d7099/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/uploadable/PodUpload.java#L139

Specifically inside the shellQuote function:
```
  public static String shellQuote(String value) {
    return "'" + value.replace("'", "'\\\\''") + "'";
  }
```

**Comment by shawkins** [comment]
> Specifically inside the shellQuote function:

Yes, that's unfortunately adding an extra escape.  Are you interested in submitting a fix?

**Comment by BrianDevC** [comment]
I am actually, just pulling everything down to give it a go. Probably should have specified to avoid duplication of efforts!
