### ISSUE TITLE
Builder methods expecting HasMetadata/KubernetesResource are not correct

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#4540]
When the builder logic generates the handling for a method like IngressControllerSpec.unsupportedProperties it creates a method impl for withUnsupportedProperties that does an instanceOf check for the known buildable types.  If you use something like GenericKubernetesResource, or RawExtension that is not an explicitly known type - it is silently ignored.  At the very least an exception should be thrown.

For usability at a minimum we need to add GenericKubernetesResource and RawExtension as buildable everywhere - with either a method added or a pointer from the exception when an unknown type is used about converting to these types - either wrapping with RawExtension, or using Serialization.jsonMapper().convertValue(resource, GenericKubernetesResource.class).

cc @iocanel @manusa

**Comment by iocanel** [comment]
The first part needs to be addressed in sundrio.

For the second part I need to refresh my memory as I don't recall by heart how GenericKubernetesResource and RawExtension work.

**Comment by shawkins** [comment]
@iocanel do you want me to copy the first part over to sundrio?
