### ISSUE TITLE
Cannot cast VirtualService to Resource in Istio-client extension

### ISSUE THREAD

**Issue by yoavgeva** [fabric8io/kubernetes-client#4542]
### Describe the bug

Trying to create Istio resource VirtualService, by using the istio-client extension.

```java

class IstioTest {

private static final String namespace = "main;
private static final HasMetadata EXAMPLE_RESOURCE_ISTIO_V1BETA1 = new io.fabric8.istio.api.networking.v1beta1.VirtualService("networking.istio.io/v1beta1", "VirtualService", null, null, null);

@Mock
    private IstioClient istioClient;

   @Mock
    private V1beta1APIGroupDSL v1beta1APIGroupDSL;
 @Mock
    private MixedOperation mixedOperation;

@Mock
    private NonNamespaceOperation nonNamespaceOperation;

@Test 
public void istioTest(){
 when(istioClient.v1beta1()).thenReturn(v1beta1APIGroupDSL);
        when(v1beta1APIGroupDSL.virtualServices()).thenReturn(mixedOperation);
        when(mixedOperation.inNamespace(NAMESPACE)).thenReturn(nonNamespaceOperation);
        when(nonNamespaceOperation.resource(EXAMPLE_RESOURCE_ISTIO_V1BETA1)).thenReturn(EXAMPLE_RESOURCE_ISTIO_V1BETA1);
istioClient.v1beta1().virtualServices().inNamespace(namespace)
                                .resource((io.fabric8.istio.api.networking.v1beta1.VirtualService)EXAMPLE_RESOURCE_ISTIO_V1BETA1))
                        .createOrReplace();
}

}

```

### Fabric8 Kubernetes Client version

6.2.0

### Steps to reproduce

1. run code above with 6.2.0 istio and mockito

### Expected behavior

error "class io.fabric8.istio.api.networking.v1beta1.VirtualService cannot be cast to class io.fabric8.kubernetes.client.dsl.Resource"

to not apper

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

other (please specify in additional context)

### Additional context

it's a test

**Comment by shawkins** [comment]
The exception is correct:

when(nonNamespaceOperation.resource(EXAMPLE_RESOURCE_ISTIO_V1BETA1)).thenReturn(EXAMPLE_RESOURCE_ISTIO_V1BETA1);

the resource method returns an instance / subclass of Resource<VirtualService>, not the VirtualService.

**Comment by yoavgeva** [comment]
@shawkins I agree the exception is correct, I am saying VirtualService was suppose to implement Resource, I am using the virtualServices API to create a VirtualService, what other item should I give if not a VirtualService? is there an other item ?
