### ISSUE TITLE
Log watch request has not been opened within: 10000 millis

### ISSUE THREAD

**Issue by JianhangLin43** [fabric8io/kubernetes-client#4549]
### Describe the bug

When I call watchlog, Log watch request has not been opened within: 10000 millis is prompted, but no data output。

### Fabric8 Kubernetes Client version

5.12.4

### Steps to reproduce

k8sClient.pods().inNamespace(namespace).withName(podName).tailingLines(100).withPrettyOutput().watchLog();

### Expected behavior

Logs are generated.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.24

### Environment

Linux

**Comment by JianhangLin43** [comment]
watchlog usage problem

**Comment by shawkins** [comment]
Can you provide a thread dump?  This could be related to #4482 in that we're unexpectedly blocking on more input - but it won't be exactly the same issue as the code changed substantially since 5.12.
