### ISSUE TITLE
Support PatchContext for patchStatus method

### ISSUE THREAD

**Issue by gyfora** [fabric8io/kubernetes-client#4572]
### Is your enhancement related to a problem? Please describe

Currently the patchStatus method does not expose the PatchContext which makes it impossible to define PatchType which could be very useful in many cases.

In the current way it is for instance impossible to set `null` values in the status using the `patchStatus` as those are ignored in the default strategy.

### Describe the solution you'd like

Add a variant of patchStatus that takes the context as parameter.

**Comment by shawkins** [comment]
@gyfora last I checked patching status with anything other than json merge was not supported.  Do you have an example of a resource and alternative patch type that is supported?

**Comment by gyfora** [comment]
I don't really know what is supported, personally I would love to be able to set `null` values in the status using patch :)
