### ISSUE TITLE
MockClient / Server does not respect `lockResourceVersion()`

### ISSUE THREAD

**Issue by gyfora** [fabric8io/kubernetes-client#4573]
### Describe the bug

When using the KubernetesMockServer and KubernetesMockClient I am trying to test locking on a resource version before doing a status update.

Seems like no matter what version I lock on the update goes through (when it should fail if I understand correctly).

Am I missing something here?

### Fabric8 Kubernetes Client version

6.2.0

### Steps to reproduce

When using the KubernetesMockServer and EnableKubernetesMockClient (crud = true)
```
        var v1 = kubernetesClient.resource(TestUtils.buildApplicationCluster()).createOrReplace();

        // Crate resource v2
        v1.getSpec().setImage("i2");
        kubernetesClient.resource(v1).replace();

        v1.getStatus().setError("e2");
        // This should fail as we are locking on v = 1 instead of v = 2
        kubernetesClient.resource(v1).lockResourceVersion().replaceStatus();
```

### Expected behavior

We should get an error when locking on the old version (v1)

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

macOS

**Comment by shawkins** [comment]
> Am I missing something here?

The crud mock server is very far from a complete replacement for a real kubernetes instance.  Issues like this are treated as enhancements - the behavior will keep getting more robust but there's no expectation that it will be a full / drop-in replacement.  

The workaround is to register a non-crud style expectation with the server specifically for behavior that is not covered.

**Comment by gyfora** [comment]
The problem I am facing is that I cannot seem to be able to register custom resources with the mock server (non-crud style)

```
kubernetesClient.apiextensions().v1().customResourceDefinitions().load("mycrd.yml").createOrReplace()
```

I get:
```
POST at: https://localhost:62585/apis/apiextensions.k8s.io/v1/customresourcedefinitions. Message: Not Found.
```

**Comment by shawkins** [comment]
> The problem I am facing is that I cannot seem to be able to register custom resources with the mock server (non-crud style)

non-crud requires registering explicit expectations, see https://github.com/fabric8io/kubernetes-client/blob/2b735ba6932f6dc7b92c4fe8cbd6781fcd45e55a/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ConfigMapTest.java

calls like server.expect().withPath...

Also keep in mind there are also no stateful side-effects when using non-crud expectations.

**Comment by gyfora** [comment]
ah I see, so it's basically impossible to write a test for locking like using the mockserver

**Comment by shawkins** [comment]
> ah I see, so it's basically impossible to write a test for locking like I tried using the mockserver

Not impossible, just more difficult.  Many of test classes in that mock kuberenetes-tests module are written against the non-crud server.  Also when you use EnableKubernetesMockClient(crud = true) the resulting server is in a hybrid mode - it will first check the expectations, before consulting the crud logic.

**Comment by gyfora** [comment]
Ok thank you for the explanation! I will try to work with what we have now :)

**Comment by shawkins** [comment]
Treating this as a duplicate since Tom has already opened a pr against #4739
