### ISSUE TITLE
False negative warning combining spec's pojo and Java Bean Validation in CRD generator

### ISSUE THREAD

**Issue by nicoloboschi** [fabric8io/kubernetes-client#4577]
### Is your enhancement related to a problem? Please describe

In my operator I integrated the POJO class to hibernate in order to validate the spec's attribute at the application level. (other than the CRD level). 
So I ended up with a class like this
```
class MySpec {
   @javax.validation.constraints.NotNull;
   @io.fabric8.generator.annotation.Required;
   String name;
}
```

During the build I get this error:
`[WARN] Annotation: javax.validation.constraints.NotNull on property: name is deprecated. Please use: io.fabric8.generator.annotation.Required instead`

Reading the [doc](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CRD-generator.md#iofabric8generatorannotationrequired) I understand why there is the warning. However, in this case, it's intentional and I'd like to turn off the warning.

### Describe the solution you'd like

A flag to not print the warning

### Additional context

Using 6.2.0

**Comment by andreaTP** [comment]
Hi @nicoloboschi ,
what you are asking makes sense to me but I would try to remove the deprecated `javax.validation.constraints.NotNull` in version `6.3` other than adding a flag to skip the warning.

Other than that, please note that the warning should not influence the behavior at all.

WDYT @manusa ?

An alternative idea would be to try to configure the `crd-generator` logger on the fly with Java properties.

**Comment by nicoloboschi** [comment]
If the plan is to drop the support (and therefore the warning) in 6.3, I believe it's better to wait for it then. 

I assume adding a specific property can be kind of weird since it's just a build warning.
