### ISSUE TITLE
[client.secrets] createOrReplace is deprecated but its in the doku

### ISSUE THREAD

**Issue by teimyBr** [fabric8io/kubernetes-client#4580]
### Describe the bug

The method createOrReplace(Secret) from the type ItemWritableOperation<Secret> is deprecated

but this is in the doku 
Create or Replace an existing Secret:
Secret createdSecret = client.secrets().inNamespace("default").createOrReplace(secret1);
at https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#secret

Can you remove it and write something how to do it. 

So i can i replace a secret ? 

delete and create ? 

### Fabric8 Kubernetes Client version

6.2.0

### Steps to reproduce

Look at the doku 

Create or Replace an existing Secret:
Secret createdSecret = client.secrets().inNamespace("default").createOrReplace(secret1);

### Expected behavior

Doku is right

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.23

### Environment

Linux

**Comment by manusa** [comment]
```java
Secret createdSecret = client.secrets().inNamespace("default").createOrReplace(secret1);
```

Should be changed to
```java
Secret createdSecret = client.secrets().inNamespace("default").resource(secret1).createOrReplace();
```

**Comment by SaumyaBhushan** [comment]
Hi @manusa Can I take this ?
