### ISSUE TITLE
Add support for MultiClusterService and MultiClusterIngress

### ISSUE THREAD

**Issue by itetradev** [fabric8io/kubernetes-client#4583]
### Is your enhancement related to a problem? Please describe

I am trying to set up a Multi Cluster Ingress on GCP. I have set up my clusters following the provided guides by Google. I am at the step where I need to deploy my ingresses following this guide: https://cloud.google.com/kubernetes-engine/docs/how-to/multi-cluster-ingress

In my implementation, I am creating accounts for users and each account needs a deployment backing it. I am upserting that deployment using fabic8's Kubernetes client. When I try to set the kind to the Service to `MultiClusterService` or the kind of the Ingress to `MultiClusterIngress` I get the following error 

> Message: MultiClusterService in version "v1" cannot be handled as a Service: no kind "MultiClusterService" is registered for version "v1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30". Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=MultiClusterService in version "v1" cannot be handled as a Service: no kind "MultiClusterService" is registered for version "v1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30", metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).

My cluster is on v1.22.

### Describe the solution you'd like

I would like fabric8 to support `MultiClusterService` and `MultiClusterIngress` kinds to enable me to manage my Multi CLuster Implementation

**Comment by rohanKanojia** [comment]
@itetradev : Are these MultiClusterService/Ingress CustomResourceDefinitions?

**Comment by rohanKanojia** [comment]
It's possible to use Custom resources using Fabric8 either via [typed](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#resource-typed-api) (provide your own POJOs) or [typeless](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#resource-typeless-api) (dynamic) APIs. Did you get any chance to try them out? Or is it model types for these objects something you're looking for?

**Comment by itetradev** [comment]
I am going to have a look at your suggestion. Thanks.
