### ISSUE TITLE
ClassCastException when using a default empty array in CRD

### ISSUE THREAD

**Issue by tomverelst** [fabric8io/kubernetes-client#4584]
### Describe the bug

I have a CRD that has an array property in the spec that defaults to `[]`.

```
foo:
  default: []
  items:
    properties:
      bar:
        type: string
    required:
      - bar
    type: object
type: array
```

I generate my Java classes using the `io.fabric8:java-generator-maven-plugin:6.2.0` plugin (with `generator-annotations`). This results in the following generated code in my custom resource's Spec class:

```
    @com.fasterxml.jackson.annotation.JsonProperty("foo")
    @com.fasterxml.jackson.annotation.JsonSetter(nulls = com.fasterxml.jackson.annotation.Nulls.SKIP)
    private java.util.List<Foo> foo = io.fabric8.kubernetes.client.utils.Serialization.unmarshal("[]", java.util.List.class);;
```

When I attempt to initiate the spec class, it throws the following exception:

```
Caused by: java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.util.Map (java.util.ArrayList and java.util.Map are in module java.base of loader 'bootstrap')
at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:237)
```

This error disappears when I remove the `default: []` property from the array property.

### Fabric8 Kubernetes Client version

6.2.0

### Steps to reproduce

Run the following code:

```
io.fabric8.kubernetes.client.utils.Serialization.unmarshal("[]", java.util.List.class);
```

### Expected behavior

Expect to have an `ArrayList` to be returned from the function call

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

macOS

### Fabric8 Kubernetes Client Logs

```shell
java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.util.Map (java.util.ArrayList and java.util.Map are in module java.base of loader 'bootstrap')
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:237)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:351)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:287)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:272)
```

**Comment by shawkins** [comment]
Should be addressed by #4533

**Comment by tomverelst** [comment]
> Should be addressed by #4533

Aha, cheers, did search for similar issues but did not find that one!

**Comment by andreaTP** [comment]
@tomverelst we already fixed this, can you try to use the snapshot release and see if that solves your issues?

**Comment by tomverelst** [comment]
Tested it and verified it works 👍 @andreaTP 

Thanks all, closing this issue
