### ISSUE TITLE
fabric8 istio-client (6.2.0) - KubernetesClientImpl error

### ISSUE THREAD

**Issue by Samodhap** [fabric8io/kubernetes-client#4589]
### Describe the bug

I'm creating a Quarkus application that can use fabric8 istio-client (6.2.0) to deploy istio resources onto kubernetes cluster. When creating a simple istioclient with fabric8 istio-client  version 6.2.0, application fails to start with following error. 

``
"exceptionType":"java.lang.ClassNotFoundException","message":"io.fabric8.kubernetes.client.impl.KubernetesClientImpl"
``

No such errors occur with version 6.1.1

### Fabric8 Kubernetes Client version

6.2.0

### Steps to reproduce

1. Add dependency 
```
        <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>istio-client</artifactId>
            <version>6.2.0</version>
        </dependency>
```
2.  Create simple istio client
        ```
        ConfigBuilder config = new ConfigBuilder();
        IstioClient  istioClient = new DefaultIstioClient(config.build());
```

3. Run the Quarkus application

### Expected behavior

Quarkus application to start without any errors.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.24

### Environment

macOS

**Comment by shawkins** [comment]
Presumably you are already pulling in the quarkus dependency on fabric8.  Please use mvn dependency:tree to confirm.  This may be causing a mixing of fabric8 versions that is manifesting as a classnotfound.  Please make sure the versions align - see also https://github.com/fabric8io/kubernetes-client/blob/master/doc/FAQ.md#ive-tried-adding-a-dependency-to-kubernetes-client-but-im-still-getting-weird-class-loading-issues-what-gives

**Comment by Samodhap** [comment]
Thanks for the quick reply. This solved the issue.
