### ISSUE TITLE
Getting warnings while maven compile when using crd-generator-apt dependency

### ISSUE THREAD

**Issue by prateekkohli21** [fabric8io/kubernetes-client#4595]
### Describe the bug

I am getting the below warnings when I am adding crd-generator-apt dependency to my pom:

[WARNING] No SupportedSourceVersion annotation found on io.fabric8.crd.generator.apt.CustomResourceAnnotationProcessor, returning RELEASE_6.
[WARNING] Supported source version 'RELEASE_6' from annotation processor 'io.fabric8.crd.generator.apt.CustomResourceAnnotationProcessor' less than -source '11'
[WARNING] No SupportedSourceVersion annotation found on io.sundr.resourcecify.internal.processor.ResourcecifyProcessor, returning RELEASE_6.
[WARNING] Supported source version 'RELEASE_6' from annotation processor 'io.sundr.resourcecify.internal.processor.ResourcecifyProcessor' less than -source '11'
[INFO] 4 warnings
[WARNING] COMPILATION WARNING :
[INFO] -------------------------------------------------------------
[WARNING] No SupportedSourceVersion annotation found on io.fabric8.crd.generator.apt.CustomResourceAnnotationProcessor, returning RELEASE_6.
[WARNING] Supported source version 'RELEASE_6' from annotation processor 'io.fabric8.crd.generator.apt.CustomResourceAnnotationProcessor' less than -source '11'
[WARNING] No SupportedSourceVersion annotation found on io.sundr.resourcecify.internal.processor.ResourcecifyProcessor, returning RELEASE_6.
[WARNING] Supported source version 'RELEASE_6' from annotation processor 'io.sundr.resourcecify.internal.processor.ResourcecifyProcessor' less than -source '11'
[INFO] 4 warnings
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] warnings found and -Werror specified
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.997 s
[INFO] Finished at: 2022-11-22T12:31:12+05:30

### Fabric8 Kubernetes Client version

6.0.0

### Steps to reproduce

Adding crd-generator-apt dependency, and running mvn compile with -Werror enabled while using java 11.

### Expected behavior

No warnings.

### Runtime

minikube

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Windows

**Comment by prateekkohli21** [comment]
Thanks for the quick response @andreaTP.

I am using java 11, below is my pom:

<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.acme</groupId>
  <artifactId>quarkus-getting-started</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
    <maven.compiler.release>11</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <skipITs>true</skipITs>
    <surefire-plugin.version>3.0.0-M7</surefire-plugin.version>
    <fabric8.kubernetes-client.version>6.1.1</fabric8.kubernetes-client.version>
  </properties>
  <dependencies>
  <dependency>
    <groupId>io.javaoperatorsdk</groupId>
  <artifactId>operator-framework-core</artifactId>
  
    <version>4.0.0</version>
  </dependency>
  <dependency>
    <groupId>io.fabric8</groupId>
    <artifactId>kubernetes-client-api</artifactId>
    <version>${fabric8.kubernetes-client.version}</version>
  </dependency>
  <dependency>
    <groupId>io.fabric8</groupId>
    <artifactId>kubernetes-model-core</artifactId>
    <version>${fabric8.kubernetes-client.version}</version>
  </dependency>
  <dependency>
    <groupId>io.fabric8</groupId>
    <artifactId>kubernetes-model-common</artifactId>
    <version>${fabric8.kubernetes-client.version}</version>
  </dependency>
  <dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-annotations</artifactId>
    <version>2.12.6</version>
  </dependency>
  <dependency>
    <groupId>io.fabric8</groupId>
    <artifactId>crd-generator-apt</artifactId>
    <version>${fabric8.kubernetes-client.version}</version>
    <scope>provided</scope>
  </dependency>
</dependencies>
<build>
  <plugins>
      <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.1</version>
          <executions>
            <execution>
                <id>default-compile</id>
                <phase>compile</phase>
                <goals>
                    <goal>compile</goal>
                </goals>
                <configuration>
                    <compilerArgs>
                        <arg>-Xlint:unchecked,deprecation</arg>
                        <arg>-Werror</arg>
                    </compilerArgs>
                    <showWarnings>true</showWarnings>
                </configuration>
            </execution>
        </executions>
      </plugin>
  </plugins>
</build>
</project>

**Comment by manusa** [comment]
I think this might be a Sundrio related issue.

**Comment by prateekkohli21** [comment]
Is there any way to avoid these warnings while maven compile?
