### ISSUE TITLE
Can't access ClusterServiceVersions on non OpenShift cluster

### ISSUE THREAD

**Issue by jeffmaury** [fabric8io/kubernetes-client#4604]
### Describe the bug

In order to list operators installed on a cluster, we should use the `operators.coreos.com/v1alpha1:ClusterServiceVersion`.

This resource is available through `OpenShiftOperatorHubAPIGroupDSL`. But this one is available through the OpenShiftClient.

But this resource is available on raw Kubernetes cluster once you installed the Operator Lifecycle Manager.

So today it is possible only if user uses `OpenShiftOperatorHubAPIGroupClient` passing the Kubernetes client as a parameter which I'm not sure is a public supported API

### Fabric8 Kubernetes Client version

5.12.4

### Steps to reproduce

See https://github.com/redhat-developer/intellij-openshift-connector/pull/484/files#diff-e332bfa50ae6e995739ad7ae9869734c6299f0d4286bf72d9fc3876207fe89fbR485

### Expected behavior

 Should be possible to adapt `KubernetesClient` to `OpenShiftOperatorHubAPIGroupDSL`

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.23

### Environment

Windows

**Comment by shawkins** [comment]
@jeffmaury did you try the adapt method on 5.12?  If you received an exception about openshift support, then please try fabric8 6+ as the adapt method no longer perform additional support checks - as long as the target implementation is available, you'll get that client.  There is now a separate supports method.

**Comment by jeffmaury** [comment]
Adapt did not work with 5.12, we can't migrate yet to 6+ as it's not backward compatible but it's on our roadmap

**Comment by rohanKanojia** [comment]
as a workaround you can try accessing ClusterServiceVersion using [GenericKubernetesResource API](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#resource-typeless-api)

**Comment by jeffmaury** [comment]
I need a typed access to this resource so I found another workaround

**Comment by manusa** [comment]
> I need a typed access to this resource so I found another workaround

What was the other workaround?

---

Not sure what your workaround was. Here is another suggestion:

If the model is in a separate module, add the dependency to that module and then register the model in the KubernetesDeserializer.

**Comment by jeffmaury** [comment]
> > I need a typed access to this resource so I found another workaround
> 
> What was the other workaround?
> 
> Not sure what your workaround was. Here is another suggestion:
> 
> If the model is in a separate module, add the dependency to that module and then register the model in the KubernetesDeserializer.

See https://github.com/redhat-developer/intellij-openshift-connector/pull/484/files#diff-e332bfa50ae6e995739ad7ae9869734c6299f0d4286bf72d9fc3876207fe89fbR513
