### ISSUE TITLE
Patch with empty collections

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#4606]
### Is your enhancement related to a problem? Please describe

For non-json patches - json merge, strategic merge - if an object has an empty collection intended to remove items, that will simply be omitted from the serialization and no change will be made.

Server side apply because of the tracking of the managed fields and different semantics, will remove a collection as expected.

### Describe the solution you'd like

The existing model logic and patch methods make this difficult to deal with.  The fields are annotated to omit if empty.  The builder logic will always set a default empty list or map.

To make this "work" the implementation logic for the non-json patches would also have to use a base object to determine what is being modified, then the serialization logic adapted to account for explicitly empty collections - this would likely involve a conversion to the map representation and explicitly setting the empty collections, they would then be emitted with the serialization.

One option is for edit / accept to have a PatchContext parameter.  Those operations have a clear base.  Unfortunately with all of the other methods because the json merge / strategic merge could refer to a partial realization of the object it's not clear what the base is.

Another option is to just recommend that users move on to using server side apply.

**Comment by manusa** [comment]
The problem with most solutions is that they are not very clear and user-friendly. We'll also offering yet another configuration option to the already flexible patch operation.
The proposed solution also requires having an original object, which in the end would imply some of the replace/update requirements which might not make it ideal for patches.

IMO we should wait to see if this is something that cannot be workedaround and requested by the community. I'm not sure if @csviri still needs this ¿?

**Comment by csviri** [comment]
@manusa no I don't need it anymore.
