### ISSUE TITLE
Jetty httpclient does not apply interceptors to websocket requests

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#4620]
The OkHttp and JDK implementations apply the interceptors to websocket requests as well.  This is quite unnatural for most client frameworks, but was supported by OkHttp, so it carried forward into our common implementation.

**Comment by manusa** [comment]
#4626 fixed this one partially, interceptors are now considered for the WebSocket HTTP requests.

afterFailure events still need to be intercepted.
