### ISSUE TITLE
Update Kubernetes Model to latest Kubernetes v1.26.0

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#4652]
### Is your task related to a problem? Please describe

Kubernetes 1.26 just got released[0]. We should update our model to latest version. Here is a link to blogpost containing changes in this version[1]

[0] https://github.com/kubernetes/kubernetes/releases/tag/v1.26.0
[1] https://kubernetes.io/blog/2022/11/18/upcoming-changes-in-kubernetes-1-26/

### Describe the solution you'd like

+ Update Fabric8 Kubernetes Model to Kubernetes 1.26

**Comment by manusa** [comment]
I'm closing this one since it's not in our backlog
