### ISSUE TITLE
Pods.withName() not working

### ISSUE THREAD

**Issue by cesartl** [fabric8io/kubernetes-client#466]
StringBuilder b = new StringBuilder();

        final List<Pod> pods = client.pods().inAnyNamespace().list().getItems();

        pods.stream().forEach(p -> {
            b.append(p.getMetadata().getName()).append(": ");
            final Pod pod = client
                    .pods()
                    .withName(p.getMetadata().getName())
                    .get();
            if (pod != null) {
                b.append(p.getMetadata().getName());
            } else {
                b.append("null");
            }
            b.append("\n");
        });

For me `b.toString()` returns all the pods and `null` next to it. I don't seem to be able to retrieve any pods by their name. It works using the REST API though.

**Comment by jimmidyson** [comment]
I assume this is just some dummy code for the purpose of this bug? In this example you already have the pod list so don't need to get it again.

However, if you are trying to loop over the pods & retrieve them again individually for whatever reason you'll need to specify the namespace as well to avoid potential conflicts:

```
final Pod pod = client
                .pods()
                .inNamespace(p.getMetadata().getNamespace())
                .withName(p.getMetadata().getName())
                .get();
```

**Comment by cesartl** [comment]
yes I was just trying to illustrate the problem. I'm not actually using this code.

Your solution fixed it thanks. I had also tried specifying a namespace but I was using `client.getNamespace` which returns `null`

Thanks

**Comment by jimmidyson** [comment]
Cool - thanks for letting us know.
