### ISSUE TITLE
Java CRD generator is not compatible with Java 8 due to @javax.annotation.processing.Generated annotation

### ISSUE THREAD

**Issue by adriansuarez** [fabric8io/kubernetes-client#4661]
### Describe the bug

The generated Java classes produced by java-generator-maven-plugin have the `@javax.annotation.processing.Generated` annotation despite the fact that my project has `maven.compiler.source=8` and `maven.compiler.target=8`.

I noticed that there is a hidden `--skip-generated-annotations` flag for the `java-gen` tool that should suppress adding of the annotation, but this is not exposed through the Maven plugin.

### Fabric8 Kubernetes Client version

6.3.0

### Steps to reproduce

1. Create a Maven project that includes the following in `pom.xml`:
```
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <!-- generate Java classes for CRDs -->
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>java-generator-maven-plugin</artifactId>
                <version>6.3.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <source>...</source>
                </configuration>
            </plugin>
            ...
        </plugins>
    </build>
```
2. Supply CRD manifests that are referenced in `<source>...</source>` for the java-generator-maven-plugin.
3. Run a Maven build using `mvn clean package` or whatever. This will fail due to the presence of the `@javax.annotation.processing.Generated` on the generated classes.

### Expected behavior

The build succeeds and the generated Java code is compiled.

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

other (please specify in additional context)

### Fabric8 Kubernetes Client Logs

```shell
K8s version is irrelevant. This is strictly a code generator issue.
```

**Comment by andreaTP** [comment]
Hi @adriansuarez !
The flag to avoid emitting the "Generated" annotation is exposed even in the Maven Plugin as we are using it in this repo for Java 8 compatibility too:
https://github.com/fabric8io/kubernetes-client/blob/3a270abd173dec52c95e9a457b0deda433a12929/java-generator/it/src/it/cert-manager/pom.xml#L83

I hope this solves this issue, cheers!

**Comment by andreaTP** [comment]
You are right that it's an "hidden" flag, but Java 8 is out of support now and we really want to move forward.

I think this is fine but let's ask another opinion to @manusa

**Comment by manusa** [comment]
> Should it be documented?
> You are right that it's an "hidden" flag, but Java 8 is out of support now and we really want to move forward.

Regardless of the Java 8 support, which I don't think we need to advertise or promote in any way (for the generator), IMO we should document any configuration field/flag the generator provides. Why do you think we shouldn't provide documentation for **all** of the available options?

**Comment by andreaTP** [comment]
@manusa historically we kept some configurations hidden because they were discouraged or possibly harming the generation.
But I have no super strong opinions.

**Comment by manusa** [comment]
Yes, now that you mention I recall we might have already talked about it. Nonetheless, this one seems like it should be documented. Those flags that are discouraged could be marked with an `(advanced) ` prefix in the description.
