### ISSUE TITLE
Set a timeout client side in informer watches

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#4675]
> I am wondering why Fabric8 is not specifying default timeout for watch requests?

Its never been requested as a feature.  The understanding is that api server will enforce its default timeout (30 minutes I believe), with some jitter of its own.

_Originally posted by @shawkins in https://github.com/fabric8io/kubernetes-client/issues/4670#issuecomment-1348622780_

**Comment by shawkins** [comment]
This is unfortunately a bit messy for us to address - the timeoutSeconds value will end up as a url parameter.  Any test based upon the non-crud mock server will need its expectation changed - however unless we provide a way to override the random spread strategy, we won't know the values ahead of time.  Another option is to update the non-crud mock logic to support path wildcards / pattern matching.

**Comment by manusa** [comment]
> Another option is to update the non-crud mock logic to support path wildcards / pattern matching.

IIRC this will involve a complete refactor of the way expectations are matched, since the path is used as a key in a map.

**Comment by shawkins** [comment]
> IIRC this will involve a complete refactor of the way expectations are matched, since the path is used as a key in a map.

Didn't say it would be easy :)
