### ISSUE TITLE
Files from kube configs should be resolved relative to the kube config

### ISSUE THREAD

**Issue by mikekap** [fabric8io/kubernetes-client#468]
Given `~/.kube/config`
```
...
- cluster:
    certificate-authority: stage/ca.pem
...
```

When searching for the certificate authority, `kubectl` attempts to read `~/.kube/stage/ca.pem`. Unfortunately `kubernetes-client` currently attempts to read `$CWD/stage/ca.pem` instead, where `$CWD` is wherever you happen to be running your binary.

**Comment by jimmidyson** [comment]
Good catch! Fancy sending in a PR to fix?
