### ISSUE TITLE
extension: cert-manager acme-resources Order / Challenge using wrong value in @Group Annotation

### ISSUE THREAD

**Issue by grafjo** [fabric8io/kubernetes-client#4688]
### Describe the bug

Following cert-manager acme classes are using the wrong k8s api group: `cert-manager.io` instead of `acme.cert-manager.io`
* [Order](https://github.com/fabric8io/kubernetes-client/blob/master/extensions/certmanager/model-v1/src/generated/java/io/fabric8/certmanager/api/model/acme/v1/Order.java#L73)
* [Challenge](https://github.com/fabric8io/kubernetes-client/blob/master/extensions/certmanager/model-v1/src/generated/java/io/fabric8/certmanager/api/model/acme/v1/Challenge.java#L73)

This leads to empty results using `Order` or `Challenge` using current cert-manager extension.

Using kubectl requesting those resources with api-version `cert-manager.io` throws errors:
* `kubectl get orders.v1.cert-manager.io`
* `kubectl get challenges.v1.cert-manager.io`

Using kubectl requesting those resources with api-version `acme.cert-manager.io` works:
* `kubectl get orders.v1.acme.cert-manager.io`
* `kubectl get challenges.v1.acme.cert-manager.io`

### Fabric8 Kubernetes Client version

6.3.1

### Steps to reproduce

Running this java code throws in both cases exceptions
```java
            OrderList orders = certManagerClient.v1().orders().list();
            if(orders.getItems().isEmpty()) {
                throw new IllegalStateException("No orders found!");
            }
```

```java

            ChallengeList challenges = certManagerClient.v1().challenges().list();
            if(challenges.getItems().isEmpty()) {
                throw new IllegalStateException("No challenges found!");
            }
```

### Expected behavior

Using the correct value in `@Group`-annotation with `acme.cert-manager.io` for `Order` and `Challenge` returns existing resources

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

**Comment by rohanKanojia** [comment]
@grafjo: Could you please create a PR to fix this issue? You need to do this:

1. Change ApiGroup from `cert-manager.io` to `acme.cert-manager.io` here:
https://github.com/fabric8io/kubernetes-client/blob/dbb96cf361d81bb034687ce60a4b7496ac9287da/extensions/certmanager/generator-v1/cmd/generate/generate.go#L61
3. Run `make` . You would need to install go.
4. Add a test to verify group has been updated to `acme.cert-manager.io`

**Comment by grafjo** [comment]
@rohanKanojia running make fails 

```
make
go mod vendor
go: downloading k8s.io/apiextensions-apiserver v0.24.2
go: downloading github.com/cert-manager/cert-manager v1.9.0-beta.1.0.20220829113803-8465f1223efb
go: downloading k8s.io/apimachinery v0.24.2
go: downloading k8s.io/klog v1.0.0
go: downloading k8s.io/utils v0.0.0-20220210201930-3a6ce19ff2f9
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading sigs.k8s.io/structured-merge-diff/v4 v4.2.1
go: downloading sigs.k8s.io/json v0.0.0-20211208200746-9f7c6b3444d2
go: downloading github.com/google/gofuzz v1.2.0
go: downloading k8s.io/klog/v2 v2.70.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading golang.org/x/net v0.0.0-20220802222814-0bcc04d9c69b
go: downloading github.com/json-iterator/go v1.1.12
go: downloading github.com/go-logr/logr v1.2.2
go: downloading sigs.k8s.io/gateway-api v0.5.0
go: downloading k8s.io/api v0.24.2
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading golang.org/x/text v0.3.7
CGO_ENABLED=0 GO111MODULE=on GO15VENDOREXPERIMENT=1 go run -mod=vendor -a ./cmd/generate/generate.go > ../model-v1/src/main/resources/schema/certmanager-schema.json
# sigs.k8s.io/json/internal/golang/encoding/json
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
make: *** [Makefile:28: gobuild] Error 2
```

so I switched to master branch run make again and even there it fails 
```
go mod vendor
CGO_ENABLED=0 GO111MODULE=on GO15VENDOREXPERIMENT=1 go run -mod=vendor -a ./cmd/generate/generate.go > ../model-v1/src/main/resources/schema/certmanager-schema.json
# sigs.k8s.io/json/internal/golang/encoding/json
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
make: *** [Makefile:28: gobuild] Error 2
```

running on ubuntu 22.04 and go version `go version go1.15.15 linux/amd64`

Regarding a test to verify group has been update: do you mean adding a unit-test here https://github.com/grafjo/kubernetes-client/tree/master/extensions/certmanager/tests ?

**Comment by rohanKanojia** [comment]
@grafjo : I'm using go 1.18. Could you please check if upgrading go version works?

> Regarding a test to verify group has been update: do you mean adding a unit-test here [grafjo/kubernetes-client@master/extensions/certmanager/tests](https://github.com/grafjo/kubernetes-client/tree/master/extensions/certmanager/tests?rgh-link-date=2022-12-16T19%3A57%3A05Z) ?

Yes, this would be good.

**Comment by grafjo** [comment]
@rohanKanojia thx for your help mate - 1.18 did work. 

Please have a look at the PR.
