### ISSUE TITLE
Occasional stackoverflow compiling the project 

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#4696]
I've seen this locally as well: https://github.com/fabric8io/kubernetes-client/actions/runs/3732428563/jobs/6331854071#step:4:9187

This mostly seems to happen during compiling the api module.

**Comment by manusa** [comment]
Haven't seen this locally but did on the CI jobs.

It looks like some Sundr.io crazyness

**Comment by shawkins** [comment]
cc @iocanel

**Comment by iocanel** [comment]
Isn't it the same issue we had with the crd generator a while back?
