### ISSUE TITLE
User permission error for ManagedKubernetesClient

### ISSUE THREAD

**Issue by lburgazzoli** [fabric8io/kubernetes-client#470]
I'm experiencing an issue moving from DefaultKubernetesClient to ManagedKubernetesClient in an [OSGi application](https://github.com/lburgazzoli/fabric8-karaf-k8s) :

Environment:
- fabric8's openshift vm
- karaf 4.0.5 running outside a pod

When using DefaultKubernetesClient inside OSGi I can access to the resources I need (i.e. configmaps) whereas when I use ManagedKubernetesClient or ManagedOpenshiftClient (obtained via @Reference) I see the following error:

```
Failure executing: GET at: https://172.28.128.4:8443/api/v1/namespaces/default/configmaps?labelSelector=karaf-id%3Dkaraf-1. Message: Forbidden! User admin/172-28-128-4:8443 doesn't have permission..
```

**Comment by lburgazzoli** [comment]
The cause of the issues is that in ManagedKubernetesClient all the Config properties are set to null if they are not available in system properties or env thus the automatic config done by i.e Config::tryKubeConfig are cleaned out.

So it maybe better to call withXyz only if the value is present and not to use any explicit default as already provided by Config class.

@iocanel make sense ?

**Comment by rohanKanojia** [comment]
@lburgazzoli : Do you still have this project available https://github.com/lburgazzoli/fabric8-karaf-k8s locally or maybe something similar to it? I'm trying to use ManagedKuberntesClient in an osgi project but I keep getting NPE.

**Comment by lburgazzoli** [comment]
@rohanKanojia unfortunately not :(

**Comment by rohanKanojia** [comment]
oh, okay. Thanks for quick reply
