### ISSUE TITLE
update networkpolicies may have some problem

### ISSUE THREAD

**Issue by chaojiniubi** [fabric8io/kubernetes-client#4703]
### Describe the bug

I try to update some networkpolicies,but exception alwasys happen. So, I debug and found this.
![image](https://user-images.githubusercontent.com/57648526/208813623-983e88f3-e92a-4795-8e3d-644b01e617ed.png)
![image](https://user-images.githubusercontent.com/57648526/208813687-37ef65fd-74a4-4697-afe8-61c2fbd7b0b1.png)
![image](https://user-images.githubusercontent.com/57648526/208813912-347b1d01-1303-452b-8f0a-c185f92d8344.png)
I guess this api may not use that way.  when I remove the param,this api seem to be good.
![image](https://user-images.githubusercontent.com/57648526/208814091-7214cc4e-f09a-4e92-aa75-570e8b2ca8d8.png)
my networkpolicies string
![image](https://user-images.githubusercontent.com/57648526/208814305-ffea4e7a-67fc-4c67-841c-6e9ddbc0f512.png)

### Fabric8 Kubernetes Client version

5.9.0

### Steps to reproduce

1.ceart one networkpolicies for one namespace
2.try to update with client

### Expected behavior

networkpolicies update.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

### Additional context

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by shawkins** [comment]
Can you provide stacktraces?  I'm not quite sure what behavior you are seeing here.  Is the createOrReplace call failing at the replace task with a 404?  That would be strange as it would have already attempted the create.
