### ISSUE TITLE
kubernetes-client osgi manifest

### ISSUE THREAD

**Issue by lburgazzoli** [fabric8io/kubernetes-client#473]
I've noticed that kubernetes-client exports the very same package as okhttp, okio, etc so even though the version is different we may clash with official versions:

- Export-Package:
```
	dk.brics.automaton;version=1.3.100,
	com.mifmif.common.regex;uses:="com.mifmif.common.regex.util,dk.brics.automaton";version=1.3.100,
	com.mifmif.common.regex.util;version=1.3.100,
	com.squareup.okhttp;uses:="javax.net,javax.net.ssl,okio";version=1.3.100,
	com.squareup.okhttp.internal;
		uses:="com.squareup.okhttp,
			com.squareup.okhttp.internal.http,
			com.squareup.okhttp.internal.io,
			com.squareup.okhttp.internal.tls,
			javax.net.ssl,
			okio";
		version=1.3.100,
	com.squareup.okhttp.internal.framed;uses:="com.squareup.okhttp,okio";version=1.3.100,
	com.squareup.okhttp.internal.http;
		uses:="com.squareup.okhttp,
			com.squareup.okhttp.internal,
			com.squareup.okhttp.internal.framed,
			com.squareup.okhttp.internal.io,
			okio";
		version=1.3.100,
	com.squareup.okhttp.internal.io;uses:="com.squareup.okhttp,com.squareup.okhttp.internal.framed,com.squareup.okhttp.internal.http,okio";version=1.3.100,
	com.squareup.okhttp.internal.tls;uses:=javax.net.ssl;version=1.3.100,
	com.squareup.okhttp.internal.ws;uses:="com.squareup.okhttp,com.squareup.okhttp.ws,okio";version=1.3.100,
	com.squareup.okhttp.logging;uses:=com.squareup.okhttp;version=1.3.100,
	com.squareup.okhttp.ws;uses:="com.squareup.okhttp,okio";version=1.3.100,
	okio;version=1.3.100
```

Then the import package says it needs them:

- Import-Package
```
	com.mifmif.common.regex,
	com.mifmif.common.regex.util,
	com.squareup.okhttp,
	com.squareup.okhttp.internal,
	com.squareup.okhttp.internal.framed,
	com.squareup.okhttp.internal.http,
	com.squareup.okhttp.internal.io,
	com.squareup.okhttp.internal.tls,
	com.squareup.okhttp.internal.ws,
	com.squareup.okhttp.logging,
	com.squareup.okhttp.ws,
	dk.brics.automaton,
	okio,
``

I think that they should not be exported/imported or they should be repackages.

**Comment by lburgazzoli** [comment]
Btw, I made the bundles for okio and okhttp on smix:
- org.apache.servicemix.bundles.okio
- org.apache.servicemix.bundles.okhttp

**Comment by lburgazzoli** [comment]
PR sent https://github.com/fabric8io/kubernetes-client/pull/475

**Comment by iocanel** [comment]
my osgi mojo is fading, but afair importing and exporting the same package is a way to avoid clashes, by exporting internal package if no import candidate is found (if the package is already there its just being used).

**Comment by iocanel** [comment]
I guess you can easily test if remember correctly by trying to add the smx bundles into the mix.

**Comment by lburgazzoli** [comment]
Sorry, the issue was not really well-explained. 

I'm thinking what happens if you, as example, will release version 1.9 of kubernetes-client and there is a bundle requiring okio >= 1.9, such bundle will may end up resolving okio package from kubernetes-client as it exort okio;version=1.9 but the real okio shaded in kubernetes-client may be far behind 1.9 (as today it is 1.6).

Am I wrong ?
