### ISSUE TITLE
The watch reports 403 error

### ISSUE THREAD

**Issue by liuyun888** [fabric8io/kubernetes-client#4745]
**follow WatchExample.java,I wrote the following code**：
`
 
    @Override
    public void run(String... args) {
        if (!isActive) {
            logger.info("未启用k8s监听");
            return;
        }

        Config config = new ConfigBuilder().withTrustCerts(true).withMasterUrl(masterUrl)
                .withOauthToken(token).withNamespace("default").build();

        try (KubernetesClient client = new KubernetesClientBuilder().withConfig(config).build();
             //注册监控事件
             Watch ignored = commonCmWatch(client)) {

            while (true) {

            }
        } catch (Exception e) {
            logger.info("注册监控事件异常: {}", e.getMessage(), e);
        }
    }
    private static Watch commonCmWatch(KubernetesClient client) {

        return client.configMaps().watch(new Watcher<ConfigMap>() {

            @Override
            public boolean reconnecting() {
                return true;
            }

            @Override
            public void eventReceived(Action action, ConfigMap resource) {
                logger.info("接收到监控事件 {}: {}", action.name(), resource.getMetadata().getName());
                if ("common-cm".equals(resource.getMetadata().getName())) {
                    updateConfigmap(client);
                }
            }

            @Override
            public void onClose(WatcherException e) {
                logger.error("监控事件错误: {}", e.getMessage(), e);
            }

            @Override
            public void onClose() {

                logger.info("监控事件关闭");
            }
        });
    }
`
It runs normally at first, but an error is reported 30 minutes later

`2023-01-09 16:02:14.936  WARN 1 --- [109.38:6443/...] i.f.k.c.d.i.WatchConnectionManager       : Exec Failure: HTTP 403, Status: 403 - Forbidden`

**Comment by shawkins** [comment]
Do not override reconnecting - that is only if the Watcher itself is in charge of re-establishing the watch.  Leaving it at the default means that the watch manager will be in charge of re-connecting.

**Comment by manusa** [comment]
In addition to what shawkins mentions, are any of the other operations failing too? maybe related to token expiry.

**Comment by liuyun888** [comment]
It is the same phenomenon before override reconnecting

**Comment by liuyun888** [comment]
Token is generated in this way

![image](https://user-images.githubusercontent.com/37199221/211438949-effcc559-7c89-41de-9897-f689d28c728b.png)

**Comment by shawkins** [comment]
What is the expiry of the token you are associating with the Config?  If the Config is not aware of a kubeconfig file it won't be able to pick up new tokens.

**Comment by liuyun888** [comment]
Thank you, it has been solved. After the serviceAccount is specified in the deployment, there is no problem.
