### ISSUE TITLE
Use SnakeYAML Engine instead of Jackson to work with YAML

### ISSUE THREAD

**Issue by asomov** [fabric8io/kubernetes-client#4754]
### Is your enhancement related to a problem? Please describe

Jackson does not support all the features of SnakeYAML Engine (anchors and aliases, security settings etc)

### Describe the solution you'd like

Migrate completely to SnakeYAML Engine

### Additional context

I can try to contribute

**Comment by asomov** [comment]
@sunix I have the PR already

**Comment by manusa** [comment]
Hi, don't worry, you were assigned the issue just for bookkeeping reasons :)

**Comment by asomov** [comment]
feel free to ping me when I can help

**Comment by manusa** [comment]
Fixed by #4836 (#4753)

**Comment by mswintermeyer** [comment]
Hey folks, thanks for addressing this! When do you think a release of kubernetes-client will be released that includes this fix? kubernetes-client is incompatible with snakeyaml 2.x in the meantime.

**Comment by manusa** [comment]
W want to release v6.5.0 by the end of this week
