### ISSUE TITLE
`NullPointerException` when creating resource list with v6.4.0

### ISSUE THREAD

**Issue by csviri** [fabric8io/kubernetes-client#4782]
### Describe the bug

See error here: https://github.com/java-operator-sdk/java-operator-sdk/actions/runs/3959219630/jobs/6781760733

logs:
```
java.lang.NullPointerException
	at io.fabric8.kubernetes.api.builder.BaseFluent.builderOf(BaseFluent.java:31)
	at io.fabric8.kubernetes.api.model.KubernetesListFluentImpl.addToItems(KubernetesListFluentImpl.java:122)
	at io.fabric8.kubernetes.api.model.KubernetesListFluentImpl.withItems(KubernetesListFluentImpl.java:231)
	at io.fabric8.kubernetes.client.impl.KubernetesClientImpl.resourceList(KubernetesClientImpl.java:331)
	at io.javaoperatorsdk.operator.junit.AbstractOperatorExtension.before(AbstractOperatorExtension.java:169)

```

code:
```java

 kubernetesClient
        .resourceList(infrastructure)
        .createOrReplace();

```

### Fabric8 Kubernetes Client version

SNAPSHOT

### Steps to reproduce

Run the releated end to end test in JOSDK.  
1. start minikube
2. run this junit test: https://github.com/java-operator-sdk/java-operator-sdk/blob/e3ea21deed64f16c8c31188fc9c9acc8fe8a7f36/sample-operators/mysql-schema/src/test/java/io/javaoperatorsdk/operator/sample/MySQLSchemaOperatorE2E.java

### Expected behavior

No error.

### Runtime

Kubernetes (vanilla), minikube

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

**Comment by shawkins** [comment]
A list of a single null item will cause this NPE.  This appears to be true of any such sundrio builder method call like this and not particular to the kuberneteslist.  Probably needs addressed in sundrio.

**Comment by csviri** [comment]
Checking, that there are indeed some underlying null elements (only 1 real one, 2 nulls). 
It reason seems to be because of resource loading here:
https://github.com/java-operator-sdk/java-operator-sdk/blob/e3ea21deed64f16c8c31188fc9c9acc8fe8a7f36/sample-operators/mysql-schema/src/test/java/io/javaoperatorsdk/operator/sample/MySQLSchemaOperatorE2E.java#L46-L47

**Comment by csviri** [comment]
The problem was caused by the behavior change in get:

`client.load(new FileInputStream("...")).get()` should be `client.load(new FileInputStream("...")).items()` from now. So might an RTFM problem from my side :)

closing the issue.
