### ISSUE TITLE
If passing API token instead of OAuth Token to OpenShift client not able to get connected with the cluster

### ISSUE THREAD

**Issue by jagriti007** [fabric8io/kubernetes-client#4787]
### Describe the bug

If trying to connect with Openshift cluster by providing API token (which is permanent) instead of Oauth token(which is temperary) its not working

this is the piece of code we are trying with 
`Config config = new ConfigBuilder()
			        .withMasterUrl(<mater_url>)
			        .build();
			    config.setOauthToken(<oauth_token>);
		        OpenShiftClient osClient = new DefaultOpenShiftClient(config);`

Trying this with Spring boot application and OpenShift cluster in IBM cloud

### Fabric8 Kubernetes Client version

5.8.1

### Steps to reproduce

When pass AIP token connection got failed but when pass Oauth token it get connected 
**Is there any way by with we can also connect to Openshift cluster by using API key and access should be admin level so that able to fetch all the resourses/workloads in the cluster**

### Expected behavior

On passing the API token also it should get connected with cluster in same as it is getting connected in case of Oauth token 

### Runtime

OpenShift

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Windows

**Comment by shawkins** [comment]
Either way what you provide will be used as the bearer token.  Is the api token formatted differently?

**Comment by Mursalin7** [comment]
@shawkins .. Format of api token is the same as auth token.

**Comment by shawkins** [comment]
@jagriti007 If the only thing that changes between success and failure is the usage of the api token, then I'm not quite sure what is going on.  Can you verify through oc login --token that your api token works for a different client?

**Comment by Mursalin7** [comment]
Yes oc login with apikey works ,
oc login -u apikey -p {token} --server={servername
}

**Comment by shawkins** [comment]
> But how can i connect via api is the main question.

It's not clear what is going wrong.  No special action is needed, the client will sent the oauth token setting as the bearer token either way.  What kind of an error are you getting from the api server?
