### ISSUE TITLE
Add a convenient way to make sure a `SharedIndexInformer` is done watching

### ISSUE THREAD

**Issue by rdesgroppes** [fabric8io/kubernetes-client#4794]
### Is your enhancement related to a problem? Please describe

Right now, the only way to make sure a `SharedIndexInformer` is done watching is by polling:
```java
  boolean isWatching();
```

`SharedIndexInformer` exposes a way to get notified when a `stop` has been requested:
```java
  CompletionStage<Void> stopped();
```
... but, as of version 6.4.0, the watch is likely to be still running _after_ completion:
```java
  public void stop() {
    stopFuture.complete(null);
[...]
    stopWatcher();
  }
```

### Describe the solution you'd like

Either:
1. make above `stop` blocking
2. or call `stopFuture.complete(null)` from within:
```java
  private synchronized void stopWatcher() {
    Optional.ofNullable(watchFuture).ifPresent(theFuture -> {
      watchFuture = null;
      theFuture.cancel(true);
      theFuture.whenComplete((w, t) -> {
        if (w != null) {
          stopWatch(w);
        }
      });
    });
  }
```
3. or expose something like:
```java
  CompletionStage<Void> doneWatching();
```

### Describe alternatives you've considered

```java
            while (informer.isWatching()) {
                LOGGER.warn("Informer still watching after shutdown...");
                // pause thread...
            }
```

**Comment by shawkins** [comment]
> the watch is likely to be still running after completion

Is the high-level issue that event processing continues after the stop call and the future is completed?  Or just that you expect the websocket to be closed when the future completes?  It would be straight-forward to ensure event processing has stopped by adding a check of the stopped future in ReflectorWatcher.eventReceived.

**Comment by rdesgroppes** [comment]
The inconvenience I observe is indeed that:
> event processing continues after the stop call and the future is completed
