### ISSUE TITLE
The attribute of ‘responseHeaderModifier’   is not in class named io.fabric8.kubernetes.api.model.gatewayapi.v1beta1.HTTPRouteFilter

### ISSUE THREAD

**Issue by chenylh** [fabric8io/kubernetes-client#4804]
### Describe the bug
Class io.fabric8.kubernetes.api.model.gatewayapi.v1beta1.HTTPRouteFilter is missing attribute ‘responseHeaderModifier’

Reference address：
 https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRouteFilter 

### Fabric8 Kubernetes Client version

6.4.0

### Steps to reproduce

io.fabric8.kubernetes.api.model.gatewayapi.v1beta1.HTTPRouteFilter

### Expected behavior

io.fabric8.kubernetes.api.model.gatewayapi.v1beta1.HTTPRouteFilter

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

macOS

### Fabric8 Kubernetes Client Logs

```shell
io.fabric8.kubernetes.api.model.gatewayapi.v1beta1.HTTPRouteFilter
```

### Additional context

io.fabric8.kubernetes.api.model.gatewayapi.v1beta1.HTTPRouteFilter

**Comment by shawkins** [comment]
I think this requires updating the go.mod in kubernetes-model-generator to use v0.6.0 of the gateway dependency.  @rohanKanojia @manusa how is this typically handled?

**Comment by rohanKanojia** [comment]
I think we need to modify this to use v0.6.0

https://github.com/fabric8io/kubernetes-client/blob/70bb38bb1d27150cff49630f9fd67cbef2cc0961/kubernetes-model-generator/go.mod#L96

I'm working on updating k8s model at the moment. Let me take care of this
