### ISSUE TITLE
Add `.addOwnerReference` to the Resource Builders

### ISSUE THREAD

**Issue by csviri** [fabric8io/kubernetes-client#4814]
### Is your enhancement related to a problem? Please describe

Would like to add owner reference using the builders. For example:

Currently just able to do it like this:
```
   ConfigMap cm = new ConfigMapBuilder()
        .withMetadata(new ObjectMetaBuilder()
            .withName(primary.getMetadata().getName())
            .withNamespace(primary.getMetadata().getNamespace())
            .build())
        .build();
    cm.addOwnerReference(primary);
```

### Describe the solution you'd like

```
   ConfigMap cm = new ConfigMapBuilder()
        .withMetadata(new ObjectMetaBuilder()
               .withName(primary.getMetadata().getName())
               .withNamespace(primary.getMetadata().getNamespace())
            .build())
            .withOwnerReference(primary);
        .build();    
```
or maybe rather:

```
   ConfigMap cm = new ConfigMapBuilder()
        .withMetadata(new ObjectMetaBuilder()
               .withName(primary.getMetadata().getName())
               .withNamespace(primary.getMetadata().getNamespace())
               .withOwnerReference(primary);
            .build())            
        .build();    
```

**Comment by rohanKanojia** [comment]
Umm, I'm not sure I understand your question correctly. Does current method for providing ownerReference doesn't suffice?

```java
ConfigMap cm = new ConfigMapBuilder()
  .withNewMetadata()
    .withName(primary.getMetadata().getName())
    .withNamespace(primary.getMetadata().getNamespace())
    .addNewOwnerReference()
      .withKind("FooResource")
      .withName("foo-resource")
      .withApiVersion("test.example.com/v1")
      .withController(true)
    .endOwnerReference()
    .endMetadata()
    .addToData(data)
  .build()
```

**Comment by rohanKanojia** [comment]
What is the type of `primary` field in the code snippet you shared?

**Comment by shawkins** [comment]
@csviri this would either require new annotation(s) in sundrio - it doesn't understand the relationship between the metadata ownerReferences field and the HasMetadata addOwnerReference function - or it may know to use a similar method if it existed on ObjectMeta.  

cc @iocanel

**Comment by csviri** [comment]
> What is the type of `primary` field in the code snippet you shared?

it is just an other kubernetes resources the name primary is irrelevant. Basically any kind of `hasMetadata`.

**Comment by csviri** [comment]
> Umm, I'm not sure I understand your question correctly. Does current method for providing ownerReference doesn't suffice?
> 
> ```java
> ConfigMap cm = new ConfigMapBuilder()
>   .withNewMetadata()
>     .withName(primary.getMetadata().getName())
>     .withNamespace(primary.getMetadata().getNamespace())
>     .addNewOwnerReference()
>       .withKind("FooResource")
>       .withName("foo-resource")
>       .withApiVersion("test.example.com/v1")
>       .withController(true)
>     .endOwnerReference()
>     .endMetadata()
>     .addToData(data)
>   .build()
> ```

This is nice, but would be nicer if I could add directly the target resource instance.

**Comment by manusa** [comment]
ATM there are already a methods in the HasMetadata interface that can be used, however it's not part of the builder:

https://github.com/fabric8io/kubernetes-client/blob/e7f6fa3057fd871ada09f90e49bf9ecadb6f0c44/kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/HasMetadata.java#L347-L368


Adding this to the builder would require a hackish approach or some tuning on Sundrio.
