### ISSUE TITLE
Duplicate dependencies in java-generator/it/src/it/extensions/pom.xml

### ISSUE THREAD

**Issue by clara0** [fabric8io/kubernetes-client#4830]
### Describe the bug

Two dependencies in `java-generator/it/src/it/extensions/pom.xml` are defined twice:
```xml
<dependency>
  <groupId>io.sundr</groupId>
  <artifactId>builder-annotations</artifactId>
  <version>@sundrio.version@</version>
  <scope>provided</scope>
</dependency>
```
and
```xml
<dependency>
  <groupId>org.projectlombok</groupId>
  <artifactId>lombok</artifactId>
  <version>@lombok.version@</version>
  <scope>provided</scope>
</dependency>
```

### Fabric8 Kubernetes Client version

SNAPSHOT

### Steps to reproduce

N/A

### Expected behavior

N/A

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

1.25.3@latest

### Environment

other (please specify in additional context)

### Additional context

Bug is present regardless of runtime/environment.

**Comment by andreaTP** [comment]
Thanks a lot!
