### ISSUE TITLE
give a way to judge watch is force closed 

### ISSUE THREAD

**Issue by own-idea** [fabric8io/kubernetes-client#4862]
### Is your enhancement related to a problem? Please describe

watch is force closed, because of HTTP_GONE , but i can not identify this. so i can not decide the reconnect is needed.

### Describe the solution you'd like

```java
public interface Watch extends Closeable {

  /**
   * Close the Watch.
   */
  void close();

}
```

add the method `isForceClosed()`

**Comment by shawkins** [comment]
That logic generally goes in the Watcher supplied to the watch method - see the onClose(WatcherException) method.

**Comment by own-idea** [comment]
> That logic generally goes in the Watcher supplied to the watch method - see the onClose(WatcherException) method.

thanks.
