### ISSUE TITLE
DEFAULT_REQUEST_RETRY_BACKOFFLIMIT value

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#4863]
## Description

Will be applicable after merging #4825

The current value for `Config.DEFAULT_REQUEST_RETRY_BACKOFFLIMIT` is currently set to `0`.
https://github.com/fabric8io/kubernetes-client/blob/7ff51aa97548ec4f3d1da4803ef7b585b57fe53f/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java#L147

This means that the ExponentialBackoffIntervalCalculator will never actually do a retry by default.

https://github.com/fabric8io/kubernetes-client/blob/7ff51aa97548ec4f3d1da4803ef7b585b57fe53f/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/ExponentialBackoffIntervalCalculator.java#L69-L71

Should this value changed to something else (for example 5) in order to take advantage of the `HttpClient` retry functionality?

**Comment by shawkins** [comment]
> Should this value changed to something else (for example 5) in order to take advantage of the HttpClient retry functionality?

I'm in favor of that.  My guess at a the default retries from the go client: https://github.com/kubernetes/client-go/blob/58ff029093df37cad9fa28778a37f11fa495d9cf/rest/request.go#L157

This will help mitigate or remove the need for the timeout handling introduced in #4637  - as it should be 500s that we're seeing prior to being able to perform pod operations.
