### ISSUE TITLE
FullExample includes deprecated method for Namespace creation

### ISSUE THREAD

**Issue by oreillymj** [fabric8io/kubernetes-client#4864]
### Is your task related to a problem? Please describe

The method for creating a namespace is marked as deprecated.
Is their a location for finding replacements for deprecated methods?

### Describe the solution you'd like

It would be useful if the full example could be updated.
https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/FullExample.java#L65

**Comment by liziwl** [comment]
I also encounter this problem. I update from 5.12.0 to 6.4.1.

`client.pods().inNamespace(namespace).create(pod);` but i found this method is deprecated in 6.4.1 version.

How to change the code?

**Comment by rohanKanojia** [comment]
It needs to be updated to 
```
client.pods().inNamespace(namespace).resource(pod).create();
```

**Comment by oreillymj** [comment]
Maybe this requires a separate issue, but the reason I came across the deprecated code is that while trying to create a pod from an Inputstream, I get the error below.

2023-02-13 16:39:26 - createPodFromInputStream()-> got resource from Inputstream
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: name not specified for an operation requiring one.
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.requireFromServer(BaseOperation.java:182)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:142)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:93)
        at Main.createPodFromInputStream(Main.java:616)


The code is again based on the examples ( [PodCreateYamlEquivalent  ](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/kubectl/equivalents/PodCreateYamlEquivalent.java)), down to the [yaml ](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/resources/test-pod.yaml ) file for the pod.

InputStream pod_resource_inputstream = Main.class.getClassLoader().getResourceAsStream("json/test-pod.yaml");
            if (pod_resource_inputstream!=null) {
                PodResource podresource = client.pods().load(pod_resource_inputstream);

                if (podresource != null) {
                    System.out.println(dt() + "createPodFromInputStream()-> got resource from Inputstream");
                    client.pods().inNamespace("test").create(podresource.get());  **<--- Exception triggered here**
                    System.out.println(dt() + "createPodFromInputStream()-> created pod with deprecated method");
                    client.pods().inNamespace("test").resource(podresource.get()).create();
                }

**Comment by rohanKanojia** [comment]
Should be fixed by https://github.com/fabric8io/kubernetes-client/pull/4912
