### ISSUE TITLE
Improve performance of the java-generator

### ISSUE THREAD

**Issue by andreaTP** [fabric8io/kubernetes-client#4865]
Suggestion from @mariofusco as he used async profiler against the `java-generator`, thanks for the amazing work 🙏 !

He noticed that one possible optimization would be to reduce the amount of work that JavaParser should do when parsing plain Strings e.g. [here](https://github.com/fabric8io/kubernetes-client/blob/7ff51aa97548ec4f3d1da4803ef7b585b57fe53f/java-generator/core/src/main/java/io/fabric8/java/generator/nodes/JObject.java#L159) :

```java
clz.addImplementedType("io.fabric8.kubernetes.api.model.KubernetesResource");
```

can be more efficient narrowing down the scope of the JavaParser string parsing:

```java
clz.addImplementedType( toClassOrInterfaceType( "io.fabric8.kubernetes.api.model.KubernetesResource" ) );
```

**Comment by mariofusco** [comment]
Just to be clear that `toClassOrInterfaceType` is not a JavaParser method, but an utility method that for instance in Drools has been implemented in [this way](https://github.com/kiegroup/drools/blob/main/drools-model/drools-model-codegen/src/main/java/org/drools/model/codegen/execmodel/generator/DrlxParseUtil.java#L642). 

So you can simply add the same method to your code base and reuse it:

```
    public static ClassOrInterfaceType toClassOrInterfaceType( String className ) {
        String withoutDollars = className.replace("$", "."); // nested class in Java cannot be used in casts
        return withoutDollars.indexOf('<') >= 0 ? StaticJavaParser.parseClassOrInterfaceType(withoutDollars) : new ClassOrInterfaceType(null, withoutDollars);
    }
```

Also note that when you're sure that the type name doesn't refer to an inner class or has generics, as in your example, you can rewrite that statement in an even simpler and more efficient way as it follow:

`clz.addImplementedType( tnew ClassOrInterfaceType(null, "io.fabric8.kubernetes.api.model.KubernetesResource" ) );`
