### ISSUE TITLE
Snapshot build removed from sonatype repo

### ISSUE THREAD

**Issue by lmyslinski** [fabric8io/kubernetes-client#4898]
### Describe the bug

Hey, sorry to bother you with this since I know it's not the official build - I've been using the `6.5-SNAPSHOT` build of the java generator maven plugin, but today all of our CI as well as my local builds started failing due to the artifacts being missing from sonatype repo:

```
[INFO] --- java-generator:6.5-SNAPSHOT:generate (default) @ mlnative ---
[WARNING] The POM for io.fabric8:kubernetes-client:jar:6.5-20230221.112333-38 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.604 s
[INFO] Finished at: 2023-02-22T14:26:26+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:java-generator-maven-plugin:6.5-SNAPSHOT:generate (default) on project mlnative: Execution default of goal io.fabric8:java-generator-maven-plugin:6.5-SNAPSHOT:generate failed: Plugin io.fabric8:java-generator-maven-plugin:6.5-SNAPSHOT or one of its dependencies could not be resolved: io.fabric8:kubernetes-client:jar:6.5-20230221.112333-38 was not found in https://oss.sonatype.org/content/repositories/snapshots during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of ossrh has elapsed or updates are forced -> [Help 1]
```
Any chance you've been doing some manual housekeeping? I know it's totally possible that it's an issue on Sonatype's side, since I find it unlikely that you'd be manually deleting upcoming snapshot versions

### Fabric8 Kubernetes Client version

SNAPSHOT

### Steps to reproduce

Pom.xml:

```
  <pluginRepositories>
    <pluginRepository>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <id>ossrh</id>
      <name>Sonatype OSS Repository (Snapshots)</name>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </pluginRepository>
  </pluginRepositories>
 ``` 
```
      <plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>java-generator-maven-plugin</artifactId>
        <version>6.5-SNAPSHOT</version>
        <executions>
          <execution>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <source>...</source>
        </configuration>
      </plugin>
 ```

### Expected behavior

Jar is found

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

**Comment by manusa** [comment]
I think this is related to: https://status.maven.org/incidents/1wlz7yhdm0wp

**Comment by manusa** [comment]
We've been trying to push the SNAPSHOT for 2 days, but still no success

https://github.com/fabric8io/kubernetes-client/actions/workflows/release-snapshots.yaml

**Comment by lmyslinski** [comment]
That's what I thought, I couldn't find those on my own. All clear now, thanks a lot

**Comment by manusa** [comment]
We still can't publish the SNAPSHOTS :sweat: 

We'll need to sync with the Sonatype folks.

**Comment by manusa** [comment]
After deleting a few files for `io.fabric8:open-cluster-management-discovery-model:6.5-SNAPSHOT` it seems that the problem was solved. The latest run was successful:
https://github.com/fabric8io/kubernetes-client/actions/runs/4249910718
