### ISSUE TITLE
Add support for editing Security Context Constrains

### ISSUE THREAD

**Issue by josefkarasek** [fabric8io/kubernetes-client#491]
Current impl doesn't override `edit()` method so default one from `BaseOperation` is used - `KubernetesClientException: Cannot edit read-only resources` is thrown.

I'll happily submit a PR, but don't know where to start.
I believe that the key part of implementing the edit() method is to create `DoneableSecurityContextConstraints` object, but so far failing to do so.

Thx a lot.

https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/SecurityContextConstraintsOperationsImpl.java

**Comment by jimmidyson** [comment]
Thanks for the report! Simpler than that... `SecurityContextConstraintsOperationsImpl` wasn't extending the correct superclass.. Will be in next release.

**Comment by josefkarasek** [comment]
Yes I noticed that. Currently somewhere in the middle of finishing it. Extending HasMetada now - then will benefit from its `edit()` impl. Can submit PR sometime next week.

**Comment by jimmidyson** [comment]
Ah thanks! I've already submitted a PR #493 which should be merged soon. This should be in the next release which I'll try to cut today.

**Comment by josefkarasek** [comment]
Perfect! Thx

On 12 Aug 2016 4:21 p.m., "Jimmi Dyson" <notifications@github.com> wrote:
>
> Ah thanks! I've already submitted a PR #493 which should be merged soon.
This should be in the next release which I'll try to cut today.

**Comment by josefkarasek** [comment]
Failing to add to `users` when the list is empty. Probably affects all other lists.
The following operation fails: https://github.com/kubernetes/kubernetes/blob/59f918cae0105a55efa515d0cd7dfe3b56ead627/vendor/github.com/evanphx/json-patch/patch.go#L415

**Comment by jimmidyson** [comment]
Opened #502 to track the newly discovered bug.
