### ISSUE TITLE
Add kustomize api

### ISSUE THREAD

**Issue by hypnoce** [fabric8io/kubernetes-client#4929]
### Is your enhancement related to a problem? Please describe

Ability to manipulate kustomization files in Java.

### Describe the solution you'd like

Generate kustomize api (sigs.k8s.io/kustomize/api) to kubernetes-model-generator

**Comment by rohanKanojia** [comment]
@hypnoce : Could you please elaborate on your use case a bit? I don't see any standard  CRUD resource being generated in kustomize model. Why would a java developer need to use these structs? Is it to help him manipulate Kubernetes manifests? Wouldn't java specific tools like [Eclipse JKube](https://github.com/eclipse/jkube) would be preferred in that scenario?

**Comment by hypnoce** [comment]
Hey @rohanKanojia 

Indeed, the kustomize api (integrated in kubectl since version 1.14) is intended to be use only locally and is not a traditional k8s CRUD resource.
The usage is the ability to parse, validate, enrich a kustomize files/objects from Java to then be used by kubectl or any kustomize engine.
JKube does not support the kustomize api. Also JKube leverages this project to get all the generated APIs.

Let me know if it's clear enough. Thanks

**Comment by hypnoce** [comment]
@rohanKanojia was this clear enough ? Thanks.

**Comment by hypnoce** [comment]
@shawkins as far as I know, kustomize API is only used in kubectl cli and not exposed as a CRUD resource in the API server.

**Comment by manusa** [comment]
I'm still not sure how are you going to use these types from Java, I'm genuinely interested because we might want to do the same in JKube.

Regarding the PR, since this is not  an API resource, the `Group` and `Version` annotations should be removed. Also, there seems to be a different `ObjectMeta` type here, we should probably try to reuse the generic one.

**Comment by andreaTP** [comment]
I'm sympathetic to having the `kustomize` functionalities exposed in Java.
For context, from a historical POV, `kustomize` used to be an external tool and they incorporated it into `kubectl` only at a later stage.

I'm a little scared by the handling of "edge cases" as `kustomize` functionalities are often lacking proper formal documentation and we end up looking at the source code more often than we would like ( [example](https://rm3l.org/using-system-envvars-with-kustomize/) ).

That said if anyone wants to step up and propose bare `kustomize` functionalities in Java, I think we can consider including the project in `fabric8` (but this is my personal opinion).

**Comment by manusa** [comment]
We have Kustomize functionalities in JKube already https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin/#_resource_fragments

We're not Kustomize-API compliant (if that's a thing) but we do provide a similar templating functionality

**Comment by hypnoce** [comment]
Catching-up with the comments :) :

> I'm still not sure how are you going to use these types from Java, I'm genuinely interested because we might want to do the same in JKube.

@manusa We are reading a kustomization.yaml file, enriching it  for strategicmergepatch based on a internal config format and writing it before executing kubectl. It is clear enough ?

> Regarding the PR, since this is not an API resource, the Group and Version annotations should be removed. Also, there seems to be a different ObjectMeta type here, we should probably try to reuse the generic one.

Will look at it

> I'm a little scared by the handling of "edge cases" as kustomize functionalities are often lacking proper formal documentation and we end up looking at the source code more often than we would like

@andreaTP I found the documentation on https://kustomize.io pretty complete. WDYT ?

> We have Kustomize functionalities in JKube already

@manusa Indeed, JKube shares some similarities with kustomize, but does not support the same configuration format nor has all the functionalities we are looking for (strategicMergePatch...). WDYT ?

**Comment by hypnoce** [comment]
@manusa for the objectmeta, seems like kustomize has its own which is a partial copy of the generic one : https://github.com/kubernetes-sigs/kustomize/blob/master/api/types/objectmeta.go 

Do you think we should still override it during code generation ? What if they add specific fields in objectmeta ?

**Comment by hypnoce** [comment]
@manusa I removed groups and version annotations from the generated resources. Let me know if that's what you had in mind.

**Comment by jiefangqudetian** [comment]
where to see the demo?

**Comment by jiefangqudetian** [comment]
> @rohanKanojia was this clear enough ? Thanks.

not clear, no use case

**Comment by rohanKanojia** [comment]
@hypnoce : Do you have any demo repository where you're using kustomize api?
