### ISSUE TITLE
kubernetes-client is incompatible with Snakeyaml 2.x

### ISSUE THREAD

**Issue by mswintermeyer** [fabric8io/kubernetes-client#4933]
kubernetes-client's latest release is incompatible with Snakeyaml 2.x, because that release removes some default constructors and methods that don't set LoaderOptions or LoadSettings. This may have already been fixed on master with https://github.com/fabric8io/kubernetes-client/pull/4836, but there has not yet been a release since then so it's hard to verify if that's the case.

```
java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshalYaml(Serialization.java:379)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:202)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:167)
```

**Comment by manusa** [comment]
Fixed by #4836 / #4753 / #4754

You can use our nightly build snapshots to verify (6.5-SNAPSHOT)

```
      <repositories>
        <repository>
          <id>sonatype-snapshots</id>
          <url>https://oss.sonatype.org/content/repositories/snapshots</url>
          <releases><enabled>false</enabled></releases>
          <snapshots><enabled>true</enabled></snapshots>
        </repository>
      </repositories>
```

**Comment by fvaleri** [comment]
@manusa thanks for the update.

Do you have any ETA for 6.5.0 release?

**Comment by manusa** [comment]
We want to deliver by the end of this week, not sure if it will be possible though. Anyway, as soon as possible.

**Comment by manusa** [comment]
[v6.5.0](https://github.com/fabric8io/kubernetes-client/releases/tag/v6.5.0) was just released, could you please confirm if this is working now so we can close the issue

**Comment by fvaleri** [comment]
@manusa no major issue, thanks again.
