### ISSUE TITLE
S2I and Docker binary builds are broken 

### ISSUE THREAD

**Issue by dsimansk** [fabric8io/kubernetes-client#495]
Since the PR https://github.com/fabric8io/kubernetes-client/pull/492 both binary methods seems to be broken. See Jira issue for details https://issues.jboss.org/browse/OSFUSE-258

**Comment by rohanKanojia** [comment]
@dsimansk : polite ping, is this still an issue? Shall we close this?

**Comment by dsimansk** [comment]
@rohanKanojia based on the comments from linked Jira the original issue was resolved. Imo this can be closed safely.
