### ISSUE TITLE
[Suggestion]SharedInformerFactory should be closed automatically when KubernetesClient is closed 

### ISSUE THREAD

**Issue by litiliu** [fabric8io/kubernetes-client#4952]
### Is your enhancement related to a problem? Please describe

I'm using kubernetes-client:5.8.0. I created a DefaultKubernetesClient() to communicate with k8s cluster, and regsitered an SharedIndexInformer to DefaultKubernetesClient.  When I call DefaultKubernetesClient.close() method, i found informers are still not closed.  In my understand, informer is using kubernetesClient to watch resources? so informers should be closed when kubernetesClient is closed.

My code like this:
````java
KubernetesClient client = getClient();
SharedInformerFactory sharedInformerFactory = client.informers();
SharedIndexInformer<FlinkDeployment> flinkDeploymentInformer = sharedInformerFactory.sharedIndexInformerFor(FlinkDeployment.class, 10 * 1000L);
flinkDeploymentInformer.addEventHandler();
~
client.close();
````

### Describe the solution you'd like

All of registered Informers should be closed when KubernetesClient is called to be closed.

### Describe alternatives you've considered

add notice to user when call create informer method, if Informers can't be closed automatically.

**Comment by shawkins** [comment]
What side effects are you seeing?  Are there some threads still running?  Closing the client will close the httpclient and all communication will cease with the api server.  In later versions of the httpclient those threads will be shut down as well.

**Comment by litiliu** [comment]
> What side effects are you seeing? Are there some threads still running? Closing the client will close the httpclient and all communication will cease with the api server. In later versions of the httpclient those threads will be shut down as well.

I think it's difficult for user to understand why the informers are still running after closing the client.  I wish all the communication should stop after i close the client.

**Comment by shawkins** [comment]
If you can confirm behavior like this on a more recent client version - at least 6.0+ - we can look into it more, but I don't believe that informers will be running in any meaningful way after you close the kubernetes client with recent versions.
