### ISSUE TITLE
Remove deprecated gateway-api APIs

### ISSUE THREAD

**Issue by thiagogcm** [fabric8io/kubernetes-client#4956]
### Is your enhancement related to a problem? Please describe

As of gateway-api v0.6.0, GatewayClass, Gateway, and HTTPRoute resources on v1alpha2 are deprecated for removal:
https://github.com/kubernetes-sigs/gateway-api/pull/1405

### Describe the solution you'd like

Cleanup such resources

**Comment by manusa** [comment]
We might consider this as part of 7.0 to clean up our extensions

**Comment by manusa** [comment]
Deprecated classes have been removed in #6227 as part of the new model generation strategy (#6130).
