### ISSUE TITLE
When sending a binary file, the inNamespace property is ignored

### ISSUE THREAD

**Issue by Sgitario** [fabric8io/kubernetes-client#4958]
### Describe the bug

Having two projects in my OpenShift cluster:
- project X1
- project Y2

When I have selected one project via: `oc project Y2`

And I select another project when instantiating the binary:
```java
client.buildConfigs()
  .inNamespace("X1")
  .withName(buildConfig.getMetadata().getName())
  .instantiateBinary()
  .withTimeoutInMillis(openshiftConfig.buildTimeout.toMillis())
  .fromFile(binaryFile);
```

This always fails with:

```
An exception: 'Can't instantiate binary build, due to error reading/writing stream. Can be caused if the output stream was closed by the server.See if something's wrong in recent events in Cluster = Scheduled openshift-1-build.174ac21d46e1ac2d Successfully assigned ...
```

My guess is that internally is using the Y2 project.

### Fabric8 Kubernetes Client version

6.4.1

### Steps to reproduce

See in description.

### Expected behavior

It should use the one selected in `inNamespace(xx)` and it should work fine.

### Runtime

OpenShift

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

**Comment by manusa** [comment]
Can this one be related to the other problem with the [binary build](https://github.com/eclipse/jkube/issues/2024) (#4899) and the timeout too?

**Comment by Sgitario** [comment]
> Can this one be related to the other problem with the [binary build](https://github.com/eclipse/jkube/issues/2024) (#4899) and the timeout too?

I thought it could be related. But didn't see any change related to namespace in the pull request. However, I will try with 6.5-SNAPSHOT.

**Comment by Sgitario** [comment]
I've just confirmed that this is working fine using 6.5-SNAPSHOT. 
Sorry for the alert!

**Comment by manusa** [comment]
> I've just confirmed that this is working fine using 6.5-SNAPSHOT. Sorry for the alert!

No worries, better safe than sorry :sweat_smile:
