### ISSUE TITLE
Java generator CLI defaults to uppercase enum without setting -enum-uppercase option

### ISSUE THREAD

**Issue by claverone** [fabric8io/kubernetes-client#4969]
### Describe the bug

```java-generator-cli-6.5.0.sh``` provides the ```-enum-uppercase``` option to uppercase the enum values. Presumably enums could be produced in mix-case without providing this option. Instead, it appears that this option is enabled by default making it impossible to get mixed-case enums.

This issue can be fixed by changing ```DEFAULT_UPPERCASE_ENUM = true``` to ```false``` in ```java-generator/core/src/main/java/io/fabric8/java/generator/Config.java```.

### Fabric8 Kubernetes Client version

6.5.0

### Steps to reproduce

1. ```./java-generator-cli-6.5.0.sh --source=./java-generator/core/src/test/resources/folder/jokerequests-crd.yml --target=/tmp```
2. ```cat /tmp/io/javaoperatorsdk/samples/v1alpha1/JokeRequestSpec.java```

Result:

```
cat ./tmp/io/javaoperatorsdk/samples/v1alpha1/JokeRequestSpec.java
        @com.fasterxml.jackson.annotation.JsonProperty("Pun")
        PUN("Pun"),
        @com.fasterxml.jackson.annotation.JsonProperty("Christmas")
        CHRISTMAS("Christmas"),
        @com.fasterxml.jackson.annotation.JsonProperty("Spooky")
        SPOOKY("Spooky"),
        @com.fasterxml.jackson.annotation.JsonProperty("Any")
        ANY("Any"),
        @com.fasterxml.jackson.annotation.JsonProperty("Misc")
        MISC("Misc"),
        @com.fasterxml.jackson.annotation.JsonProperty("Programming")
        PROGRAMMING("Programming"),
        @com.fasterxml.jackson.annotation.JsonProperty("Dark")
        DARK("Dark");
```

### Expected behavior

Expected:

```
cat ./tmp/io/javaoperatorsdk/samples/v1alpha1/JokeRequestSpec.java
        @com.fasterxml.jackson.annotation.JsonProperty("Pun")
        Pun("Pun"),
        @com.fasterxml.jackson.annotation.JsonProperty("Christmas")
        Christmas("Christmas"),
        @com.fasterxml.jackson.annotation.JsonProperty("Spooky")
        Spooky("Spooky"),
        @com.fasterxml.jackson.annotation.JsonProperty("Any")
        Any("Any"),
        @com.fasterxml.jackson.annotation.JsonProperty("Misc")
        Misc("Misc"),
        @com.fasterxml.jackson.annotation.JsonProperty("Programming")
        Programming("Programming"),
        @com.fasterxml.jackson.annotation.JsonProperty("Dark")
        Dark("Dark");
```

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

macOS

**Comment by andreaTP** [comment]
Hi @claverone and thanks for taking the time to file this issue!
The option to emit enums with full uppercase can be easily switched off by passing this argument to the cli:

```bash
--enum-uppercase=false
```

The full command of your example would be:

```bash
./java-generator-cli-6.5.0.sh --enum-uppercase=false --source=./java-generator/core/src/test/resources/folder/jokerequests-crd.yml --target=/tmp
```
(The option is also exposed by the Maven Plugin).

Let me know if this solves your issue!

**Comment by andreaTP** [comment]
Thanks for getting back @claverone !
I close this issue, feel free to re-open or file a new one in case I missed something.
