### ISSUE TITLE
informer's watcher cannot reconnect from 503 resp

### ISSUE THREAD

**Issue by Metal-joker** [fabric8io/kubernetes-client#4974]
### Describe the bug

Sometimes k8s api server may return 503 to websocket upgrade request when api server just recover from stress, but web socket listener seems ingored this situation, didn't schedule a new reconnect attempt. this will cause informer hang forever.
https://github.com/fabric8io/kubernetes-client/blob/c112f2d63c2d6ad9906c822fe80eec3dcbc1bb0d/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatcherWebSocketListener.java#L88-L92

### Fabric8 Kubernetes Client version

other (please specify in additional context)

### Steps to reproduce

1. init a informer
2. somehow stress out your k8s server, I used tool named `stress`
3. stop the stress program and check if api server returns 503 to informer's upgrade requests
4. informer hang.

### Expected behavior

informer should reconnect.

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

### Additional context

Fabric8 Kubernetes Client version: 5.3.1 and last time I check, this bug can also be reproduced in 6.5.0, but i didn't dive into it because 6.5.0 code is far different from 5.31
Kubernetes API Server version: v1.19.8+k3s-, i used k3s for test.

**Comment by shawkins** [comment]
5.3.1 is far too old at this point to draw any conclusions about.  If we can stick with what you are seeing with 6.5.0 that would be be good.  It would be best to produce a debug log and also to use the informer's stopped future to capture if the informer is stopping.  

In general the informer logic will react to 503, or any error, in one of several ways.  If it is the initial attempt at starting the informer, it may error out - if started synchronously that would be thrown as an exception to the caller, if started asynchronously it will be an exceptional completion of the stopped future.  If the informer is already running as long as the error is not in the form of a non-http gone WatcherException, then the informer will recover.  If there is a non-http gone WatcherException, it will be captured as the exceptional completion of the stopped future.  However the cases that produce a non-http gone WatcherException as supposed to be limited - basically a protocol error such that event processing cannot continue.

So once you provide a log and if the informer has stopped, we'll be able to explain the behavior you are seeing.  If it's simply that your informer is failing to start or is later stopping, you may override that behavior with an exceptionHandler.
