### ISSUE TITLE
create volcano vcjob via vcjob.yaml

### ISSUE THREAD

**Issue by smlHao** [fabric8io/kubernetes-client#4987]
### Is your enhancement related to a problem? Please describe

java  code  Implement the following functions: kubectl apply -f vcjob.yaml
vcjob as flowing:
                          apiVersion: batch.volcano.sh/v1alpha1
                          kind: Job
                          metadata:
                            name: tensorflow-dist-mnist
                          spec:
                            minAvailable: 3
                            schedulerName: volcano
                            plugins:
                              env: []
                              svc: []
                            policies:
                              - event: PodEvicted
                                action: RestartJob
                            queue: default
                            tasks:
                              - replicas: 1
                                name: ps
                                template:
                                  spec:
                                    containers:
                                      - command:
                                          - sh
                                          - -c
                                          - |
                                            PS_HOST=`cat /etc/volcano/ps.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
                                            WORKER_HOST=`cat /etc/volcano/worker.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
                                            export TF_CONFIG={\"cluster\":{\"ps\":[${PS_HOST}],\"worker\":[${WORKER_HOST}]},\"task\":{\"type\":\"ps\",\"index\":${VK_TASK_INDEX}},\"environment\":\"cloud\"};
                                            python /var/tf_dist_mnist/dist_mnist.py
                                        image: volcanosh/dist-mnist-tf-example:0.0.1
                                        name: tensorflow
                                        ports:
                                          - containerPort: 2222
                                            name: tfjob-port
                                        resources: {}
                                    restartPolicy: Never
                              - replicas: 2
                                name: worker
                                policies:
                                  - event: TaskCompleted
                                    action: CompleteJob
                                template:
                                  spec:
                                    containers:
                                      - command:
                                          - sh
                                          - -c
                                          - |
                                            PS_HOST=`cat /etc/volcano/ps.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
                                            WORKER_HOST=`cat /etc/volcano/worker.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
                                            export TF_CONFIG={\"cluster\":{\"ps\":[${PS_HOST}],\"worker\":[${WORKER_HOST}]},\"task\":{\"type\":\"worker\",\"index\":${VK_TASK_INDEX}},\"environment\":\"cloud\"};
                                            python /var/tf_dist_mnist/dist_mnist.py
                                        image: volcanosh/dist-mnist-tf-example:0.0.1
                                        name: tensorflow
                                        ports:
                                          - containerPort: 2222
                                            name: tfjob-port
                                        resources: {}
                                    restartPolicy: Never

### Describe the solution you'd like

 KubernetesClient client = new DefaultKubernetesClient();

VcJob vcjob = client.vcjobs().load(new File("/home/sml/spark-kerberos-demo/src/ vcjob.yaml");
 client.vcjobs().createOrReplace(vcjob);

**Comment by smlHao** [comment]
> There is model support for volcano scheduling v1beta1. Are you asking for model support for batch alpha1 as well?
> 
> > VcJob vcjob = client.vcjobs().load(new File("/home/sml/spark-kerberos-demo/src/ vcjob.yaml");
> > client.vcjobs().createOrReplace(vcjob);
> 
> You can do this as an untyped operation as well:
> 
> ```
> client.load(new File("/home/sml/spark-kerberos-demo/src/vcjob.yaml").createOrReplace();
> ```  

thanks your fast reply !!!!   the code test  valid ,will use this to impl functions

ask this  because volcano-client had done queue and podgroup api  and there are differences betwween kubenetes job and volcano job

**Comment by mafei-github** [comment]
@smlHao client.load(new File("/home/sml/spark-kerberos-demo/src/vcjob.yaml").createOrReplace();
Excuse me, is that how you solved it?

**Comment by smlHao** [comment]
> @smlHao client.load(new File("/home/sml/spark-kerberos-demo/src/vcjob.yaml").createOrReplace(); Excuse me, is that how you solved it? ![图片](https://private-user-images.githubusercontent.com/174586581/358485798-c62e6b33-7b60-476a-95d1-b04729351458.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTI5NzcsIm5iZiI6MTcyMzc5MjY3NywicGF0aCI6Ii8xNzQ1ODY1ODEvMzU4NDg1Nzk4LWM2MmU2YjMzLTdiNjAtNDc2YS05NWQxLWIwNDcyOTM1MTQ1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNzE3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDcwMWZiYTY0ZGY0MTM5NzE0MzU2NGJjOWFkZDFhZmI3NDQ2NDdmYWRjNDRiZGQ4ZWMwODNhNTg0MjRhZWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._v1zEeBAs6bugGcxI1FsW2kuwYGywBoAN5TVosUUA3E)

Hi,Maybe your kubernets-client version is newer, You can do this as an untyped operation as well:
InputStream in = new FileInputStream(new File("/home/sml/spark-kerberos-demo/src/vcjob.yaml");
client.load(in).createOrReplace();
in.close();
