### ISSUE TITLE
Remove the usage Serialization yaml mapper

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#4998]
The yaml mapper is mostly not needed and can be avoided entirely with logic similar to what is done for parsing.  This will also remove the need for the method to clear the mapper.

**Comment by andreaTP** [comment]
The `yaml` mapper is used under the scenes by the java generator as most of the provided CRDs are in `yaml` format.

What would be a viable substitution for it?

**Comment by shawkins** [comment]
@andreaTP the unmarshall methods and asYaml will handle deserialization and serialization.  Do you have a scenario that requires direct access to the mapper?
