### ISSUE TITLE
Clashing package names in istio model dependencies

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [fabric8io/kubernetes-client#5000]
### Describe the bug

In our project, we use Istio resources with v1beta1 (gateway) and v1alpha3 (envoy filter) versions.

Therefore, in `build.gradle.kts` we use these dependencies:
```kotlin
implementation("io.fabric8:istio-model-v1beta1:6.3.1")
implementation("io.fabric8:istio-model-v1alpha3:6.3.1")
```

Both of these packages contain duplicated packages with the same name:
- io.fabric8.istio.api.analysis.v1alpha1
- io.fabric8.istio.api.meta.v1alpha1

As a result, when we build the application using quarkus, we got a warning:
```
Detected a split package usage which is considered a bad practice and should be avoided. Following packages were detected in multiple archives: 
- "io.fabric8.istio.api.analysis.v1alpha1" found in [io.fabric8:istio-model-v1alpha3::jar, io.fabric8:istio-model-v1beta1::jar]
- "io.fabric8.istio.api.meta.v1alpha1" found in [io.fabric8:istio-model-v1alpha3::jar, io.fabric8:istio-model-v1beta1::jar]
```

### Fabric8 Kubernetes Client version

6.3.1

### Steps to reproduce

1. Generate gradle quarkus application
2. Add following dependencies: 
```kotlin
implementation("io.fabric8:istio-model-v1beta1")
implementation("io.fabric8:istio-model-v1alpha3")
```
3. Run `./gradlew build`

### Expected behavior

Package names are unique across different packages - there are no clashing package names.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

macOS

**Comment by rohanKanojia** [comment]
> make the v1beta1 jar depend on v1alpha3 and remove the duplicates from v1beta1.

I would prefer this approach.

**Comment by AleksanderBrzozowski** [comment]
> > make the v1beta1 jar depend on v1alpha3 and remove the duplicates from v1beta1.
> 
> I would prefer this approach.

@rohanKanojia Hm, not sure if it is correct way to solve it.
This means that if I add a `v1beta1` dependency, I would have one resource available from two packages, for example istio `Gateway` class will be available with both `beta` and `alpha` package.

I wonder what is the reason that `v1beta1` contains package with `v1alpha1` name inside 🤔

**Comment by AleksanderBrzozowski** [comment]
@shawkins I mean that for example these two classes will be available on classpath when I add v1beta1 dependency:
- `io.fabric8.istio.api.networking.v1beta1.Gateway`
- `io.fabric8.istio.api.networking.v1alpha3.Gateway`
