### ISSUE TITLE
Best practices around KubernetesClient and SharedIndexInformer lifetimes?

### ISSUE THREAD

**Issue by VVKot** [fabric8io/kubernetes-client#5029]
I am wondering what is the expect pattern of usage for `KubernetesClient` and `SharedIndexInformer`? Both implement `AutoCloseable`, and examples provided use try-with-resources: https://developers.redhat.com/articles/2023/01/04/how-use-fabric8-java-client-kubernetes#how_to_use_the_fabric8_kubernetes_client This makes sense for one-off operations like "create pod", but not for informers. In a production application, I need informer to be created once and run for the whole lifetime of the application. Concretely:

1. Is the best practice for one-off operations to create a new `KubernetesClient` and close it immediately afterwards? Any downside to doing so? For example, I'd be worried about creating a lot of underlying okhttp clients with associated overhead and then shutting them down.
2. What is the best practice for creating informers? Create a single client and create all informers off of it on startup, close informers and client on application shutdown?

Maybe @shawkins @manusa @rohanKanojia ?

**Comment by shawkins** [comment]
> Is the best practice for one-off operations to create a new KubernetesClient and close it immediately afterwards?

As long as your rate of interaction with the server is very low that's fine.  However if your application though only interacts with a single api server, you should consider just tying the kubernetesclient life cycle to the application life cycle.

> What is the best practice for creating informers? Create a single client and create all informers off of it on startup, close informers and client on application shutdown?

Yes, that is the basic pattern.  Explicitly closing the informers is not needed as everything will be cleaned up by the closure of the httpclient.
