### ISSUE TITLE
Create Config-Map from my properties file, using k8s client

### ISSUE THREAD

**Issue by Parneet-Raghuvanshi** [fabric8io/kubernetes-client#5031]
Hello 👋,
I am trying to create a config-map form a file, using k8s client.

content of **application.properties**, I have this file as `File` java object.
```
propertyOne="Something_One"
propertyTwo="Something_Two"
```
now I have no clue, how I should create a config-map.
**ConfigMapBuilder** has few options for `.withData()` or `.addToData()` but these consumes only `Map<String, String>`

My goal is to create this config-map, and assign this to a Pod using **EnvFromSourceBuilder**, by using config-map name and assigning that to my **ContainerBuilder**, and only blocker is creating Config-Map.

Can anyone please help me out, thanks in advance :)

**Comment by rohanKanojia** [comment]
Do you think your use case can be covered by this PR https://github.com/fabric8io/kubernetes-client/pull/4712 ? See [example](https://github.com/fabric8io/kubernetes-client/pull/4712/files#diff-b95b04f298d96edfaaefd6c00f835dba2dd308eee090ba0c8ea35c22610b2851R80).

**Comment by Parneet-Raghuvanshi** [comment]
> Do you think your use case can be covered by this PR #4712 ? See [example](https://github.com/fabric8io/kubernetes-client/pull/4712/files#diff-b95b04f298d96edfaaefd6c00f835dba2dd308eee090ba0c8ea35c22610b2851R80).

Yes, Thanks @rohanKanojia , I think that's what I need.
So at the end we are just converting file to String,
```
final byte[] bytes = Files.readAllBytes(file);
final String value = Base64.getEncoder().encodeToString(bytes);
```
and then adding that as data right?

**Comment by rohanKanojia** [comment]
Yes, file contents are loaded in ConfigMap data. It more or less tries to emulate what `kubectl` does. This was originally ported from [Eclipse JKube](https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin/)'s ConfigMap support.

**Comment by Parneet-Raghuvanshi** [comment]
@rohanKanojia, by using this the env I get from pod is weird,

![Screenshot 2023-04-05 233250](https://user-images.githubusercontent.com/54593571/230166479-e53b9304-86f7-46f6-bcf2-2b278174ae6a.png)

here, it append the file name, did you get the same result with pod? or is this Ok?
my pod spec ->
```
spec:
  containers:
  - name: demo-container
    image: nginx
    envFrom:
    - configMapRef:
        name: my-config-map
```

**Comment by Parneet-Raghuvanshi** [comment]
I think I have to use **volumeMount** instead of **envFrom**.
Thanks again @rohanKanojia.
