### ISSUE TITLE
 support Deployment action?

### ISSUE THREAD

**Issue by yaakua** [fabric8io/kubernetes-client#505]
The operation can not support Deployment action?
http://kubernetes.io/docs/user-guide/deployments/

**Comment by donovanmuller** [comment]
Have you seen `client.extensions().deployments()`.
Check [this test](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentTest.java) for examples.

**Comment by yaakua** [comment]
ok,i see

**Comment by jimmidyson** [comment]
Thanks @donovanmuller for helping out - appreciated.
