### ISSUE TITLE
Create a "status/need-triage" label to track issues that have not been reviewed

### ISSUE THREAD

**Issue by sunix** [fabric8io/kubernetes-client#5055]
### Is your task related to a problem? Please describe

Like in Eclipse che, a bot is automatically adding the label https://github.com/eclipse/che/labels?q=triage

### Describe the solution you'd like

-

**Comment by gbraad** [comment]
@sunix Have you followed-up on this?

The easiest way to address this is by editing the [issue template(s)](https://github.com/fabric8io/kubernetes-client/tree/master/.github/ISSUE_TEMPLATE) and add the following to the frontmatter:

```yaml
---
labels: "status/need-triage"
---
```
