### ISSUE TITLE
support DeploymentConfig retry 

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/kubernetes-client#507]
we can trigger builds...

``` java
            client.buildConfigs().inNamespace(namespace).withName(name).trigger(new WebHookTrigger(true, null));
```

but there doesn't seem to be a way to retry deployment configs that fail

``` java
            client.().inNamespace(namespace).withName(name).trigger / retry?
```

e.g. like the `oc deploy foo --retry | --cancel" commands

**Comment by donovanmuller** [comment]
or even

```
$ oc deploy app --latest
```

for cases where a deployment is required.

**Comment by rohanKanojia** [comment]
still looks like a relevant issue

**Comment by manusa** [comment]
`DeploymentConfig` is being deprecated: https://access.redhat.com/articles/7041372

`Deployment` resource operations implement `RollableScalableResource` which should provide features similar to those requested in this issue.

``` java
client.apps().deployments().withName("name").rolling().restart()
```
