### ISSUE TITLE
HttpClient E2E test failures

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#5091]
### Description
E2E tests for the Vert.x and Jetty HttpClient implementations are failing.

**Comment by shawkins** [comment]
At least for vert.x this is likely due to the change to use an inputstream, rather than a byte[] for simple requests.  I'll try to track this down why this isn't completing.  We also use the inputstream result for things like logs, so this may be indicative of a larger problem.

**Comment by manusa** [comment]
Currently checking for Jetty, but it looks like sth within the recent changes completely broke these clients.

**Comment by manusa** [comment]
Might relate to #5064
