### ISSUE TITLE
should binaryData field type in configMap be Map<String, byte[]>

### ISSUE THREAD

**Issue by own-idea** [fabric8io/kubernetes-client#5096]
### Is your task related to a problem? Please describe

no, just curious. 
In k8s , [https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/config-map-v1/](https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/config-map-v1/)

`binaryData`  is defined as map[string][]byte

### Describe the solution you'd like

```java
    private Map<String, byte[]> binaryData = new LinkedHashMap<String, byte[]>();

```

**Comment by rohanKanojia** [comment]
I think this is due to our go struct to json schema generator converting byte array into strings:

https://github.com/fabric8io/kubernetes-client/blob/5eb8bf56695b3e2bfacc99539d21078def5fe320/kubernetes-model-generator/pkg/schemagen/generate.go#L131-L132

**Comment by shawkins** [comment]
> Can't you simply convert the string to byte array directly?

Converting to / from string shouldn't be needed - the jackson logic will handle the base64 encoding for json, and it looks like a small tweak to the yaml output would handle that case as well. 

However going back now and changing the models would be difficult/messy (for several releases inserting hand modified classes with deprecated methods) or a breaking change.

**Comment by shawkins** [comment]
To follow a bit more if the generate.go logic is changed to map to byte[] instead, that highlights some bugs in japa / jsonschema2pojo - it sees byte[] are a primitive declaration, not as an array type causing exceptions.  That is probably what caused this initial choice.  There is a workedaround, but as mentioned above both the generated classes and the generated builders would need replaced with versions of the affected classes with methods supporting both string and byte[].  As far as I can tell there's no good way to automate that.  

I'd be in favor of closing this.
