### ISSUE TITLE
looks like DeploymentConfig is not Scalable like D/RS/RC

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/kubernetes-client#512]
see the code here: https://github.com/jstrachan/fabric8-maven-plugin/blob/5ab71754d60a8db60ced08780e4ea06180f9827d/plugin/src/main/java/io/fabric8/maven/plugin/AbstractDeployMojo.java#L664-L664

**Comment by iocanel** [comment]
@jstrachan: the problem I have implementing this is that DeploymentConfig doesn't seem to offer a way to see the number of replicas currently active (e.g. via status as Deployment does).

So, I'll try to get the corresponding replication controller and check its status, unless a better idea is available.

@jimmidyson: wdyt?

**Comment by jimmidyson** [comment]
Check out latest kube model - seem to remember those fields being added.

If not then we'll need to scale the active RC ourselves.

**Comment by jstrachan** [comment]
I think you can scale by updating the spec.replicas on a DC; that's what the console does AFAIK

**Comment by jimmidyson** [comment]
Yes but to properly scale we need to wait until desired == actual & @iocanel says those fields aren't available on DC. I'm sure they were added some time recently-ish.

**Comment by jstrachan** [comment]
not sure how big a deal waiting is TBH. On k8s the scale on a Deployment may wait - but even if it does wait for the pod to be created, it takes a while longer for the pod to go from pending > running > ready. 

If folks really want to wait until there are N ready pods, that sounds like a custom Pod Watcher?

**Comment by jstrachan** [comment]
Eg I don't really need any waiting right now for a DC ;)

**Comment by jimmidyson** [comment]
Oh sorry I was talking of reaping rather than scaling. Pretty sure scaling doesn't wait by default, but will double check unless @iocanel can remember?

**Comment by jimmidyson** [comment]
Checked. Scale by default does not wait, but you have the option to wait if you so wish - how nice are we?

**Comment by jstrachan** [comment]
yay thanks!
