### ISSUE TITLE
Document a way how to use TokenRequest for existing ServiceAccount

### ISSUE THREAD

**Issue by pjastrzabek-roche** [fabric8io/kubernetes-client#5133]
### Is your task related to a problem? Please describe

I am trying to create new expiring token for existing ServiceAccount, basically equivalent of

```
kubect create serviceaccount my-service-account -n xxx
kubectl create token my-service-account -n xxx --duration=1h
```

I see there is TokenRequestBuilder and TokenRequest but the latter do not extend HasMetadata thus I cannot use generic API for creation.

Is there any way to call this api?

### Describe the solution you'd like

Having an API for easy token creation.
See something similar in go sdk
https://github.com/kubernetes/client-go/blob/686b396dc0681d7f140bd2ee6b3c3bdea56cab4d/kubernetes/typed/core/v1/serviceaccount.go#L214

**Comment by rohanKanojia** [comment]
Looks like we don't support this yet. We need to add support for this resource

https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/

**Comment by pjastrzabek-roche** [comment]
What could be possible timeframe for adding this? Due to this we have to use other client just for this usecase.

**Comment by rohanKanojia** [comment]
@pjastrzabek-roche : Hi, I plan to pick this up when I upgrade Kubernetes model to v1.27.0 #5056 . Hopefully, I will be able to start working on this next week.

**Comment by rohanKanojia** [comment]
@pjastrzabek-roche : I've created a PR adding DSL method `tokenRequest()` to ServiceAccount DSL. Would appreciate if you could review if it's as per your expectations. You can see sample usage [here](https://github.com/rohanKanojia/kubernetes-client/blob/pr/issue5133-dsl/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/ServiceAccountTest.java#L100).

**Comment by pjastrzabek-roche** [comment]
Functional-wise this is what we need. LGTM!
