### ISSUE TITLE
Upgrade okhttp to 3.14.9

### ISSUE THREAD

**Issue by melin** [fabric8io/kubernetes-client#5134]
### Is your enhancement related to a problem? Please describe

Other projects use okhttp 3.14.9 more, okhttp relies on okio, okio 1.15 and 1.17 have compatibility problems

### Describe the solution you'd like

Upgrade okhttp to 3.14.9

**Comment by manusa** [comment]
Covered in #4296 

However, we'll probably bump into a 4.x version instead.

For your specific project you can override/exclude our transitive OkHttp dependency and use whichever you prefer.

**Comment by manusa** [comment]
Considering Quarkus no longer depends on the OkHttp client (at least for production), we should move forward to use OkHttp 4 instead.

Closing this issue and #4296 in favor of #2632.
