### ISSUE TITLE
Upgrade Fabric8 Knative Extension Model to v0.37.0

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#5140]
### Is your task related to a problem? Please describe

Just like we're updating tekton extension in #4989, we should also bump knative extension to latest version (0.37.0 right now)

### Describe the solution you'd like

Upgrade Knative extension model to v0.37.0

**Comment by andreaTP** [comment]
IIRC the knative CRDs are already exposing a good API.
This makes it a good candidate to switch to totally generated extensions in the `knative` repository.

Any reference to a specific repository/CRDs we should look at?
Anyone from `knative` that can help and evaluate this effort?

**Comment by andreaTP** [comment]
Switching to the `java-generator` is going to be a breaking change, even if we test all of the types we need to convert them again.

**Comment by andreaTP** [comment]
The `java-generator` is not going to generate the same types as the current extension.

**Comment by manusa** [comment]
If it's possible, we should follow the same approach we did for Camel-K.
- The official repository to host an extension generated by our Java Generator (analogous to https://github.com/apache/camel-k/pull/3994)
- Deprecation of our extension (analogous to #5107)
- Removal of our extension (analogous to #5171)

**Comment by rohanKanojia** [comment]
This seems to be blocking my work on #5113 . 

For now we can proceed with just updating go dependencies.

I've created #5348 for migration to Java generator task.
