### ISSUE TITLE
Remove JUnit5 `org.junit.jupiter:junit-jupiter-migrationsupport` dependency from codebase

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#5141]
### Is your task related to a problem? Please describe

We seem to be including this dependency in most of our poms:
https://github.com/fabric8io/kubernetes-client/blob/c76762a58d809d47d5a36734a096eeb74e474f7d/pom.xml#L837-L841

I think it was added during JUnit5 refactor to maintain compatibility with JUnit4 `@Rule`, when mockserver had to be used with a `@Rule`. But now that we've migrated to JUnit5 extension `@EnableKubernetesMockServer`. This dependency should not be required.

I only see one place where we're using `@Rule` in a JUnit5 test, but it can easily be replaced with `@TempDir` JUnit5 annotation: 
https://github.com/fabric8io/kubernetes-client/blob/c76762a58d809d47d5a36734a096eeb74e474f7d/uberjar/src/test/java/io/fabric8/kubernetes/clnt/UberJarTest.java#L49-L50

You can find all the occurrences of this dependency by searching for `junit-jupiter-migrationsupport` in project.

### Describe the solution you'd like

Remove all occurrences of `org.junit.jupiter:junit-jupiter-migrationsupport` dependency. For most places, it should be as trivial as removing the dependency from pom.

**Comment by akshaya-hub** [comment]
can i work on this

**Comment by akshaya-hub** [comment]
@rohanKanojia  after removing the org.junit.jupiter:junit-jupiter-migrationsupport dependency I got an error with the Maven test

**Comment by rohanKanojia** [comment]
@akshaya-hub : Are you getting error in UberJarTest? You can try replacing TemporaryFolder Rule there with `@TempDir` annotation.

**Comment by akshaya-hub** [comment]
@rohanKanojia  ok i will try
