### ISSUE TITLE
execWatch.exitCode().get() stuck forever

### ISSUE THREAD

**Issue by missedone** [fabric8io/kubernetes-client#5159]
### Describe the bug

In my use case, i need to call a python/bash script with `kubectl exec`

1. I tried with the code below, the line `execWatch.exitCode().get()` stuck and never return. **with the TeeOutputStream to stdout, I clearly see the script was finished**.

```
TeeOutputStream tos = new TeeOutputStream(baos, System.out);
ExecWatch execWatch = kc.pods().inNamespace(namespace).withName(podName).writingOutput(tos).writingError(tos).exec(cmdAndArgs.toArray(new String[0])));
int exitCode = execWatch.exitCode().get();
```

2. I tried with the ExecListener as well, see the same issue and noticed that `onExit`, `onClose` and `onFailure` callback methods were never hit.

3. I tried with the `kubectl exec` cli with the exact same args copied from the debug window, it worked.

so sounds like something is wrong with handling the WebSocket underneath.

### Fabric8 Kubernetes Client version

6.6.2

### Steps to reproduce

see description above

### Expected behavior

`execWatch.exitCode().get()` can return properly

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.24

### Environment

Linux, macOS

### Fabric8 Kubernetes Client Logs

```shell
no log shown up
```

**Comment by shawkins** [comment]
Can you provide a reproducer, and be sure to include what httpclient you are using?  If the exec is terminating we certainly expect some notification of that.

**Comment by missedone** [comment]
The python script is a complex one, I just noticed that run with `-tty` matters which can solve the issue, so it might be something wrong in the script which rely on tty
