### ISSUE TITLE
useless and misleading message in Config.fromKubeconfig

### ISSUE THREAD

**Issue by spwangxp** [fabric8io/kubernetes-client#5166]
https://github.com/fabric8io/kubernetes-client/blob/14833dadf9555e1393c2945d5910e9f23e8a06d3/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java#L751

https://github.com/fabric8io/kubernetes-client/blob/14833dadf9555e1393c2945d5910e9f23e8a06d3/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java#L547

is there any reason to add this message?

**Comment by shawkins** [comment]
> Also, this looks like it was probably consumed by a downstream project that very likely is no longer active.

I'd vote for removing what is set in the config and deprecating getErrorMessages.  The kubernetes status or what's in HttpStatusMessage should cover the bases well enough.
