### ISSUE TITLE
Replace createOrReplace entries in CHEATSHEET with createOr or serverSideApply

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#5176]
Child of #5057 

> We should also try to update the [doc/CHEATSHEET.md](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#server-side-apply) . It seems to be pointing to old patch method

We need to remove `createOrReplace` entries from CHEATSHEET

_Originally posted by @manusa in https://github.com/fabric8io/kubernetes-client/issues/5174#issuecomment-1562666166_

**Comment by akshaya-hub** [comment]
@manusa   is this issue closed or can i work on this issue

**Comment by rohanKanojia** [comment]
@akshayamadhuri : This issue requires some prior knowledge about KubernetesClient DSL. You would need to know which method to replace deprecated `createOrReplace` with depending upon the situation. It is not a good candidate for getting started with contributing to the project.
