### ISSUE TITLE
The supported istio version is relatively backward, the definition of HTTPDirectResponse resource is missing

### ISSUE THREAD

**Issue by xiong-frank** [fabric8io/kubernetes-client#5182]
### Is your enhancement related to a problem? Please describe

Currently, the latest version of istio is `1.17.2`, and starting from version `1.15.0`, istio supports adding `HTTPDirectResponse` in `VirtualService` to express the direct response of specified routing rules, but I cannot be found the resource definition in `fabric8io/kubernetes-client/extensions/istio`, resulting in the inability to operate some istio resources using the api here.

### Describe the solution you'd like

`fabric8io/kubernetes-client/extensions/istio` can include the resource definitions of `HTTPDirectResponse` 
 in the next update, and it is best to keep in sync with the latest version of [istio resources](https://istio.io/latest/docs/reference/config/networking/virtual-service).

### Describe alternatives you've considered

My current approach is to clone the `fabric8io/kubernetes-client` repository, edit the file [extensions/istio/model-v1beta1/src/main/resources/schema/istio-schema.json](https://github.com/fabric8io/kubernetes-client/blob/master/extensions/istio/model-v1beta1/src/main/resources/schema/istio-schema.json), add the corresponding resource definition in it according to the introduction of the [istio official api](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPDirectResponse), and then repackage it for me, but I hope that `fabric8io/kubernetes-client` can do the same, and add `HTTPDirectResponse` resource to the schema file, it's best to keep in sync with istio official api resources.

**Comment by yimoucao** [comment]
+1 the Java models here for Istio is outdated. It's best to keep it up-to-date with Istio official. 
One of unsupported features I found: `LoadBalancerSettings-SimpleLB` has 6 enums including `Unspecified`, while https://github.com/fabric8io/kubernetes-client/blob/main/extensions/istio/model-v1alpha3/src/generated/java/io/fabric8/istio/api/networking/v1alpha3/LoadBalancerSettingsSimpleLB.java#L12-L15


Istio Doc: https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings-SimpleLB
Istio API: https://github.com/istio/api/blob/master/networking/v1alpha3/destination_rule.pb.go#L241-L269

@manusa

**Comment by manusa** [comment]
We'll try to find some time to update the models.However, if someone is interested in providing a PR for such purpose, we'll appreciate it.

**Comment by rohanKanojia** [comment]
@xiong-frank Istio Model has been updated to v1.21.0 . Would be great if you could try it out and provide feedback. It should be available after today's nightly build.

In order to use `6.13-SNAPSHOT`. You need to add this to your project's `pom.xml` or `~/.m2/settings.xml`
```xml
      <repositories>
        <repository>
          <id>sonatype-snapshots</id>
          <url>https://oss.sonatype.org/content/repositories/snapshots</url>
          <releases><enabled>false</enabled></releases>
          <snapshots><enabled>true</enabled></snapshots>
        </repository>
      </repositories>
```

**Comment by xiong-frank** [comment]
@rohanKanojia  I'm so Sorry, I just saw your reply now, I'm glad to hear that you have updated the istio model, but I can't wait, so I took my own solution before you update to 1.21, and I don't plan to use the istio api you provided.
But I am willing to share the solution I took, which is also thanks to the CRD converter tool you provided, so thank you for that.

* Download istio schema from the istio official repository：[istio/api/blob/master/kubernetes/customresourcedefinitions.gen.yaml](https://github.com/istio/api/blob/master/kubernetes/customresourcedefinitions.gen.yaml)
* Edit the istio schema. This is because in order to maintain backward compatibility during the iteration process, istio/api retained some obsolete fields in its CRD definition. These fields have different styles but the same semantics, which will cause conflicts in the generated code. For example, there are three fields in the `HTTPRoute` type: `mirror_percent`, `mirrorPercent`, and `mirrorPercentage`. When generating a Java class, three `getMirrorPercentage()` methods will be generated, resulting in code errors. Therefore, the CRD file must be edited to resolve the problem.
  * Find the definition of `HTTPRoute`, which contains three fields representing mirrorPercentage: `mirror_percent`, `mirrorPercent`, and `mirrorPercentage`. These three fields are equivalent, and `mirrorPercentage` is the latest definition. However, `mirror_percent` and `mirrorPercent` will result in the generation of the same `getter/setter` code, so delete the `mirror_percent` field.
  * Find the `allowOrigin` and `allowOrigins` fields in the definition of `HTTPRoute/corsPolicy`. Both fields are optional List types. The `allowOrigins` field is the latest definition. However, due to naming reasons and the naming rules of proto-buffer when generating Java code, the same `hasAllowOrigin()` methods will be generated. Therefore, delete the `allowOrigin` field.
  * Find the `jwks_uri` and `jwksUri` fields in the definition of `RequestAuthentication/jwtRules`. As in the previous case, `jwksUri` is the latest definition, so delete the `jwks_uri` field.
* Use fabricio/kubernetes-client CRD generator plugin to convert. There are two ways: use command line tool or maven plugin to convert.
  * Use command line tool
    ```shell
    PLUGIN_VERSION=6.13.0

    # dowmload command line tool
    wget https://oss.sonatype.org/content/repositories/releases/io/fabric8/java-generator-cli/$PLUGIN_VERSION/java-generator-cli-$VERSION.sh
    chmod a+x java-generator-cli-$PLUGIN_VERSION.sh
    # show version
    ./java-generator-cli-$PLUGIN_VERSION.sh --version

    # specify edited istio CRD schema file
    K8S_CRD_FILE=<path to istio-CRD file>
    # specify a output dir
    CRD_GEN_DIR=<specify a output dir>

    # convert
    ./java-generator-cli-$PLUGIN_VERSION.sh -add-extra-annotations -s $K8S_CRD_FILE -t $CRD_GEN_DIR
    ```
  * Use maven plugin
    ```xml
    <build>
      ... 
      <plugins>
        ...
        <plugin>
            <groupId>io.fabric8</groupId>
            <artifactId>java-generator-maven-plugin</artifactId>
            <version>6.13.0</version>
            <configuration>
                <!-- specify edited istio CRD schema file -->
                <source>${project.basedir}/src/main/resources/crd/customresourcedefinitions.gen.yaml</source>
                <!-- specify a output dir -->
                <target>${project.basedir}/src/main/java</target>
                <extraAnnotations>true</extraAnnotations>
            </configuration>
            <executions>
                <execution>
                    <goals>
                        <goal>generate</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
      </plugins>
    </build>
    ```
