### ISSUE TITLE
Visitors are called too often (sometimes)

### ISSUE THREAD

**Issue by rhuss** [fabric8io/kubernetes-client#521]
I still don't know how I get to this situation :
![image](https://cloud.githubusercontent.com/assets/99080/18794391/a02b7e46-81bf-11e6-952a-d2102478f2da.png)

but it seems that sometimes the list of `_visitables` contains more elements than `items`. In fact it happens that my visitors are called in this more times than matching elements are in the list.

I will try to investigate further, could also that I do sth wrong (of course ;-)

**Comment by rhuss** [comment]
Here's another example with 2 (!) `DeploymentSpecBuilder` as part of a `DeploymentBuilder`

![image](https://cloud.githubusercontent.com/assets/99080/18794722/3ede94d2-81c1-11e6-85c0-b92cbc983037.png)

**Comment by iocanel** [comment]
Interesting! It seems that when we replace an item or a whole collection we need to remove it from the visitables too. I'll fix that on the sundrio side.

**Comment by rohanKanojia** [comment]
Closing this one since https://github.com/sundrio/sundrio/issues/69 is closed already
