### ISSUE TITLE
KubernetesResourceUtil issues

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#5220]
The KubernetesResourceUtil methods related to resource names, labels, and annotations are not sufficiently documented or in some cases wrong.  Resources names may be up to 253 characters, not just 63.  Annotation and label keys name portion is limited to 63 chars, but they may contain a / separated prefix and with its own restrictions and the total character may be up to 253 characters long. 
 Annotation values are not restricted.

**Comment by manusa** [comment]
Is it possible that these restrictions have changed in recent (mind the wording, meaning 1.14 or earlier).

**Comment by shawkins** [comment]
> Is it possible that these restrictions have changed in recent (mind the wording, meaning 1.14 or earlier)?

None of what's mentioned in the description would be very recent, but yes it's entirely possible that the util methods were more applicable quite a long time ago.  At this point I don't see a need to separate out rules by version, we'll start with just bringing things up-to-date and expanding the javadocs were needed.

**Comment by manusa** [comment]
> At this point I don't see a need to separate out rules by version

Neither do I. I was just curious about why were these rules implemented in the first place with _wrong_ assumptions. The project's age seems to be taking a toll in some of our most foundational utilities. We (my team) might need to spend some time thoroughly reviewing those.
