### ISSUE TITLE
Improve deletion of Generic Resources

### ISSUE THREAD

**Issue by syr** [fabric8io/kubernetes-client#5227]
### Is your enhancement related to a problem? Please describe

For deleting genericKubernetesResources I always have to pass context information (as documented here https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#resource-typeless-api) using one of both:

```
  MixedOperation<GenericKubernetesResource, GenericKubernetesResourceList, Resource<GenericKubernetesResource>> genericKubernetesResources(
      ResourceDefinitionContext context);

  
  MixedOperation<GenericKubernetesResource, GenericKubernetesResourceList, Resource<GenericKubernetesResource>> genericKubernetesResources(
      String apiVersion, String kind);
```

With my custom GenericKubernetesResource implementation class having already all context information...

``` 
@Group(API_GROUP)
@Version(API_VERSION)
@Kind(KIND)
@Plural(PLURAL)
public class MyCustomGenericKubernetesResource extends GenericKubernetesResource implements Namespaced { ... }
```

..I wonder if there is a way to not having to pass the context explicitly and redundantly like 

```
public class MyCustomGenericKubernetesResource extends GenericKubernetesResource implements Namespaced { 

... 
    public static ResourceDefinitionContext getContext() {
        return new ResourceDefinitionContext.Builder()
                .withGroup(API_GROUP)
                .withVersion(API_VERSION)
                .withKind(KIND)
                .withNamespaced(true)
                .build();
    }
...

}	

kubernetesClient
	.genericKubernetesResources(MyCustomGenericKubernetesResource.getContext())
	.inNamespace(namespace)
	.withName(jobName)
	.delete()



```
To make it very clear:

        return new ResourceDefinitionContext.Builder()
                .withGroup(API_GROUP)		// > redundant to @Group(API_GROUP)
                .withVersion(API_VERSION)	// > redundant to @Version(API_VERSION)
                .withKind(KIND)				// > redundant to @Kind(KIND)
                .withNamespaced(true)		// > redundant to implements Namespaced
                .build();
```

### Describe the solution you'd like

kubernetesClient
	.genericKubernetesResources(MyCustomGenericKubernetesResource.class)
	.inNamespace(namespace)
	.withName(jobName)
	.delete()

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

**Comment by shawkins** [comment]
```
kubernetesClient
	.genericKubernetesResources(MyCustomGenericKubernetesResource.class)
	.inNamespace(namespace)
	.withName(jobName)
	.delete()
```
Have you tried:
```
kubernetesClient
	.resources(MyCustomGenericKubernetesResource.class)
	.inNamespace(namespace)
	.withName(jobName)
	.delete()
```
The client does not ascribe any special meaning to "custom" vs "built-in" - the metadata expectations are the same either way.

**Comment by syr** [comment]
No I obviously missed that. Thanks for the hint

**Comment by rohanKanojia** [comment]
@syr : Is it possible for you to create PR to update CHEATSHEET?

**Comment by syr** [comment]
> @syr : ~Is it possible for you to create PR to update CHEATSHEET?~
> 
> Already present [here](https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#resource-typed-api).

Hm not sure if it's only me, but when I read the docs, I stopped reading when there was crontab topics starting, that's why I didn't see before

**Comment by rohanKanojia** [comment]
@syr : I added CronTab example from Kubernetes [docs](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/). 

is it possible for you to update it from a new user perspective?

**Comment by syr** [comment]
@rohanKanojia I added a new section by https://github.com/fabric8io/kubernetes-client/pull/5237 
Please check also for correctness, as this is my beginner understanding.

**Comment by rohanKanojia** [comment]
@syr : Thanks a lot!
