### ISSUE TITLE
have an .apply() method that wraps up create() or replace() based on if the resource already exists

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/kubernetes-client#523]
we've got apply when using the 

```java
kubernetesClient.resource(foo).apply()
```

but we don't have an apply when using the DSL to find a resource:

```java
kubernetes.extensions().deployments().inNamespace("foo").withName("bar").apply(resource);
```
it'd be nice to be able to apply stuff generically

**Comment by iocanel** [comment]
Now both styles support the following methods:

createOrReplace() and createOrReplaceNew() for inlining.

apply() from resource has been deprecated.
