### ISSUE TITLE
Don't send empty patches

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#5232]
Even if the json patch is empty we're still sending it to the server.

**Comment by shawkins** [comment]
json patches where the diff is empty.

**Comment by sunix** [comment]
hey @shawkins let us know if you are planning to work on it.

**Comment by shawkins** [comment]
> let us know if you are planning to work on it

Not currently.

**Comment by rohanKanojia** [comment]
@shawkins : I think what Sun meant is whether it's on your work queue for future.

**Comment by shawkins** [comment]
> I think what Sun meant is whether it's on your work queue for future.

Not yet, thinking about it more there should be little actual difference on the api server side - they make a similar claim in the context of server side apply that when there's nothing to be patched it's a very light-weight operation.  This was something that I was initially thinking would get us out of a remote call, but that's not the case since a get still has to be performed.  I'll just marked as closed.
