### ISSUE TITLE
VertxHttpClient.derivedClients infinite growth

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#5235]
## Description

To be able to properly clear the resources, we added a List of `VertxHttpClient` derived client instances to the `VertxHttpClient` class.
Each time a new request is performed (`NamespacedKuberetesClientAdapter.getClient` --> `getClient().adapt(type)'), a new instance is added to the list.

This might be problematic for long-lived request intensive applications, since the list of live references to unused `VertxHttpClient` instances will grow indefinitely.

**Comment by shawkins** [comment]
Now that none of the derived options affect the client directly this can removed so that we just share a single instance.

**Comment by manusa** [comment]
> Now that none of the derived options affect the client directly this can removed so that we just share a single instance.

Awesome, this was leaking slowly but steadily

**Comment by manusa** [comment]
I can confirm that in 6.7.2 after the #5241 fix, the leak is resolved.

So this is actually solving a big memory leak for those applications that are intensive in requests to the kubernetes-api. I have been running the same application for hours now and everything is OK. Before, the heap space would have grown to several hundreds of MiB under the same conditions.
