### ISSUE TITLE
OpenshiftClient scale deploymentConfig Error

### ISSUE THREAD

**Issue by cgcgccg** [fabric8io/kubernetes-client#5236]
### Describe the bug

When I use openshift-client v6.7.1 to scale openshift deploymentConfig like below:
<img width="766" alt="image" src="https://github.com/fabric8io/kubernetes-client/assets/53556178/15d0814c-659c-468b-bbfe-027bed0d5915">

It will return error like this:
<img width="1233" alt="image" src="https://github.com/fabric8io/kubernetes-client/assets/53556178/fd34388f-1ba8-419a-a9d6-0a554562149a">

### Fabric8 Kubernetes Client version

6.7.1

### Steps to reproduce

Init openshift client
then use scale func
will return this error

### Expected behavior

openshift client can scale deploymentConfig normal

### Runtime

OpenShift

### Kubernetes API Server version

1.25.3@latest

### Environment

Windows, Linux

**Comment by manusa** [comment]
We changed the way we scale resources to use the scale subresource. Maybe the OpenShift cluster is not supporting this operation. Could you share your cluster details (version, and so on).

/cc @shawkins

**Comment by cgcgccg** [comment]
> We changed the way we scale resources to use the scale subresource. Maybe the OpenShift cluster is not supporting this operation. Could you share your cluster details (version, and so on).
> 
> /cc @shawkins

Hi, this is the version info:
Openshift version : 4.10
and
<img width="340" alt="image" src="https://github.com/fabric8io/kubernetes-client/assets/53556178/3748bf40-8f12-4191-89a2-b13ee4e7fa43">

**Comment by cgcgccg** [comment]
> Sure enough:
> 
> ```
> {"kind":"Scale","apiVersion":"extensions/v1beta1", ...
> ```
> 
> Supprising that it's still using the deprecated api.

Thanks shawkins. So that's mean I should config my openshift-client apiVersion is v1beta1, is right?

**Comment by shawkins** [comment]
> So that's mean I should config my openshift-client apiVersion is v1beta1, is right?

No, it means that /scale on a DeploymentConfig resource understands v1beta1 scale, not v1.

I guess they haven't committed to addressing this upstream: https://bugzilla.redhat.com/show_bug.cgi?id=1931897 https://issues.redhat.com/browse/OCPBUGS-865

**Comment by cgcgccg** [comment]
> 

I understand. Thanks.

**Comment by manusa** [comment]
> So that's mean I should config my openshift-client apiVersion is v1beta1, is right?

We'll probably release a 6.7 patch to address this and other issues.
