### ISSUE TITLE
how to watch a container's log for a pod with multiple containers?

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/kubernetes-client#524]
Looks like the methods taking a container name are deprecated: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/Loggable.java#L32

**Comment by iocanel** [comment]
It has been deprecated in favor of `inContainer(String containerName)`.

      LogWatch watch =   client.pods().inNamespace(namespace).withName(podName).inContainer(containerName).tailingLines(10).watchLog(System.out))

which should be working fine.
