### ISSUE TITLE
SharedIndexInformer and eventHandler issue

### ISSUE THREAD

**Issue by zihan9826** [fabric8io/kubernetes-client#5247]
### Is your task related to a problem? Please describe

In my project, I'm using an informer run for the whole lifetime of the application in order to monitor some events for namespace scoped. But I don't find a way to replace/delete the eventHandler once some of the logic has been done. is the only way for one-off operations to create a new informer after the logic is done in the eventHandler?

### Describe the solution you'd like

just wondering the way to close the eventHandler after SharedIndexInforme running.

**Comment by zihan9826** [comment]
> 

thanks for the reply, shawkins! please tell me more detail about forwarding calls to a collection of handlers plz! Does it seem the same as keeping add eventHandler to the informer?

**Comment by shawkins** [comment]
@zihan9826 I mean create a handler like the following which is added to the informer, then when you want create a short-lived handler - add it to the delegated handlers, rather than to the informer.  If it's possible for your handlers to throw exceptions, then you'll want to add handling for that as well so that one throwing an exception doesn't cause the others to miss an event.

```
public class DelegatingResourceEventHandler<T> implements ResourceEventHandler<T> {

  // add/remove your own handlers here
  List<ResourceEventHandler<? super T>> handlers = new ArrayList<>();

  public void onNothing() {
    handlers.forEach(ResourceEventHandler::onNothing);
  }

  public void onAdd(T obj) {
    handlers.forEach(h -> h.onAdd(obj));
  }

  public void onUpdate(T oldObj, T newObj) {
    handlers.forEach(h -> h.onUpdate(oldObj, newObj));
  }
  
  ...
```

**Comment by sunix** [comment]
Hi @zihan9826 is the workaround working for your usecase? let us know, thanks.

**Comment by zihan9826** [comment]
@sunix @shawkins  Thanks a  lot for the reply!
