### ISSUE TITLE
Create test to ensure HttpLoggingInterceptor doesn't consume bytes

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#5251]
## Description

Relates to #5250

In #5146 we removed by mistake the `copy` instruction for the consumed `ByteBuffer`. 
This has basically reintroduced the problems (https://github.com/eclipse/jkube/issues/2000, https://github.com/eclipse/jkube/issues/1950) that were originally addressed by our HttpLoggingInterceptor feature.

We need to add a specific test to ensure that this is not a problem again.

**Comment by rohanKanojia** [comment]
I can reproduce the original issue using a unit test in AbstractHttpLoggingInterceptorTest, by test do you mean a unit test or an E2E test?

**Comment by manusa** [comment]
A black-boxed unit test that ensures the behavior (i.e. avoid mocking and verify calls to things like `BufferUtil::copy`)
