### ISSUE TITLE
Flakey jdk httpclient test

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#5260]
JdkHttpClientTest>OkHttpClientTest.testRequest:172 expected: <true> but was: <false>

https://github.com/fabric8io/kubernetes-client/actions/runs/5281986557/jobs/9557051169#step:4:47345

There's no good reason that should be failing, at the very least onClose and onError should have callbacks so that we can easily capture if something is unexpectedly happening before the message is received.

**Comment by manusa** [comment]
There are two tests with the same path expectation, shouldn't really be a problem with the test setup anyway.
I think there's already another test covering this use-case, so maybe we can just delete it.

**Comment by shawkins** [comment]
> I think there's already another test covering this use-case, so maybe we can just delete it.

It's definitely covered by other tests, so I'm good with that change as well.

**Comment by manusa** [comment]
IMO the end goal would be to remove the `httpclient-tests` and cover any gaps in the `AbstractXxxTest` tests
