### ISSUE TITLE
Refine KubernetesSerialization interface

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#5274]
As a follow-up to #5265 we should at least expand the constructParametricType method.  It may also be useful to think about encapsulating the detail of using the TypeReference class.

cc @metacosm

**Comment by shawkins** [comment]
@metacosm @csviri can you confirm all that you may want here to resolve this issue?

**Comment by csviri** [comment]
I don't know about anything that was not settled.

**Comment by metacosm** [comment]
We need to check the SSA matching algorithm to see if it can be made more typesafe with this new support but we can already get by without. @csviri
