### ISSUE TITLE
Upgrade OpenShift Model to latest version of OpenShift API

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#5286]
### Is your task related to a problem? Please describe

We should upgrade our OpenShift Model to latest version of OpenShift. 

I checked on an OpenShift 4.13.0 cluster and I see these resources missing:

- config.openshift.io/v1      ImageDigestMirrorSet
- config.openshift.io/v1            ImageTagMirrorSet
- helm.openshift.io/v1beta1            ProjectHelmChartRepository
- infrastructure.cluster.x-k8s.io/v1beta1                Metal3Remediation
- infrastructure.cluster.x-k8s.io/v1beta1                Metal3RemediationTemplate
- machine.openshift.io/v1                                ControlPlaneMachineSet
- operators.coreos.com/v1                               OLMConfig

### Describe the solution you'd like

OpenShift Model should be aligned with the latest versions of OpenShift

**Comment by manusa** [comment]
Can this one be closed now?

**Comment by rohanKanojia** [comment]
Yes, I think so.
