### ISSUE TITLE
Using kubernetes-client to find no k8s-deployment roll back to the historical version of the method 

### ISSUE THREAD

**Issue by mingworkspace** [fabric8io/kubernetes-client#529]
hi，The functions of  K8S-API deployment are as follows ：
（1） Checking Rollout History of a Deployment
$ kubectl rollout history deployment/nginx-deployment
（2）Now we’ve decided to undo the current rollout and rollback to the previous revision:
kubectl rollout undo deployment/nginx-deployment
（3）rollback to a specific revision by specify that in --to-revision:
$ kubectl rollout undo deployment/nginx-deployment --to-revision=2 

Whether there is a corresponding interface, I hope to provide support for the above functions, thank you

**Comment by yunlzheng** [comment]
+1

**Comment by xunchangguo** [comment]
only support deployments workload?
