### ISSUE TITLE
Question about time string format

### ISSUE THREAD

**Issue by christopherlim98** [fabric8io/kubernetes-client#5295]
### Is your enhancement related to a problem? Please describe

I am not sure how timestamp string formats look like. Can anyone confirm if it follows RFC 3339, and whether Timestamps class can parse it properly? https://javadoc.io/static/com.google.protobuf/protobuf-java-util/3.0.0/com/google/protobuf/util/Timestamps.html

### Describe the solution you'd like

Would appreciate if there was documentation giving example format and whether it follows RFC 3339.

**Comment by manusa** [comment]
There are many model classes that contain timestamps. Unfortunately they have different treatment.
For those that are typed as `String` they are following whatever format the Kube API returns. For those that are typed using a Date related type, they are serialized using Jackson's `JavaTimeModule`.
