### ISSUE TITLE
Updating javadoc for fabric8?

### ISSUE THREAD

**Issue by ggallen** [fabric8io/kubernetes-client#5303]
### Is your task related to a problem? Please describe

Is there no javadoc for fabric8?

https://www.javadoc.io/doc/io.fabric8/kubernetes-model/6.7.2/index.html

The latest I see if 4.9.2?

### Describe the solution you'd like

Javadoc is available.

### Describe alternatives you've considered

N/A

### Additional context

N/A.

**Comment by rohanKanojia** [comment]
Kubernetes Model was split into smaller jars in https://github.com/fabric8io/kubernetes-client/pull/2137 .

I think you should check for specific module you're interested in. For example:

- Core : https://www.javadoc.io/doc/io.fabric8/kubernetes-model-core/latest/index.html 
- Apps : https://www.javadoc.io/doc/io.fabric8/kubernetes-model-apps/latest/index.html
