### ISSUE TITLE
Flakey interation test DefaultSharedIndexInformerIT.testPodSharedIndexInformerGetsEvents

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#5322]
This test failed recently https://github.com/fabric8io/kubernetes-client/actions/runs/5500845926/jobs/10024106597#step:6:419

It's not a great test because it doesn't do it's own setup - it just relies on some pod being see across all namespaces and has a pretty short timeout.

**Comment by manusa** [comment]
This doesn't seem to be applicable anymore, closing.
