### ISSUE TITLE
Migrate Knative Extension to generate model types from CRD using  Fabric8 Java Generator

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#5348]
IIRC the knative CRDs are already exposing a good API.
This makes it a good candidate to switch to totally generated extensions in the `knative` repository.

Any reference to a specific repository/CRDs we should look at?
Anyone from `knative` that can help and evaluate this effort?

_Originally posted by @andreaTP in https://github.com/fabric8io/kubernetes-client/issues/5140#issuecomment-1561029766_

**Comment by manusa** [comment]
See https://github.com/fabric8io/kubernetes-client/issues/5140#issuecomment-1561225876

The idea is not to migrate our extension but rather deprecate it and remove it.
