### ISSUE TITLE
client.events().inAnyNamespace() is not a function

### ISSUE THREAD

**Issue by MD-AZMAL** [fabric8io/kubernetes-client#5350]
### Describe the bug

I tried running the following example from the readme.
```java
client.events().inAnyNamespace().watch(new Watcher<Event>() {

  @Override
  public void eventReceived(Action action, Event resource) {
    System.out.println("event " + action.name() + " " + resource.toString());
  }

  @Override
  public void onClose(KubernetesClientException cause) {
    System.out.println("Watcher close due to " + cause);
  }

});
```

But i came to know that client.events() returns `io.fabric8.kubernetes.client.dsl.EventingAPIGroupDSL` which does not has inAnyNamespace() method

### Fabric8 Kubernetes Client version

6.7.2

### Steps to reproduce

Executing the above code, gave an error saying cannot find inAnyNamespace()

### Expected behavior

To watch events

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.24

### Environment

Azure

### Additional context

The context is i want to watch the changes in my cluster, be it pod, services, crds and anything if there is any change i want the kubernets-client to watch over it. If this is not the correct way or something else is supposed to be done please let me know

**Comment by rohanKanojia** [comment]
@MD-AZMAL : Instead of `client.events()` Could you please try `client.v1().events()`?

**Comment by MD-AZMAL** [comment]
@rohanKanojia  sure, i'll try this and let you know

**Comment by MD-AZMAL** [comment]
@rohanKanojia it worked! any reason why we have to use it via v1(), is it deprecated in the newer version?

**Comment by manusa** [comment]
There are multiple versions of the `events.k8s.io`: `v1` and `v1beta1`.
`v1` is the current stable version. However, it was introduced after `v1beta1`.
The DSL entry-point allows you to select with which version you want to work with. At this point `v1beta1` doesn't make much sense unless you work with a cluster older than v1.25, since as of that version this API is no longer served.

**Comment by MD-AZMAL** [comment]
> There are multiple versions of the `events.k8s.io`: `v1` and `v1beta1`. `v1` is the current stable version. However, it was introduced after `v1beta1`. The DSL entry-point allows you to select with which version you want to work with. At this point `v1beta1` doesn't make much sense unless you work with a cluster older than v1.25, since as of that version this API is no longer served.

Got it, thanks for helping. I think we can close the issue
