### ISSUE TITLE
Remove OpenShiftMockServer

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#5351]
## Description

OpenShiftMockServer is deprecated since [v6.0.0](https://github.com/fabric8io/kubernetes-client/releases/tag/v6.0.0) (#3913), we should completely remove this class.

_Originally posted in #5349_

**Comment by shawkins** [comment]
@manusa based upon our recent conversations, do you want to hold off on this until 7? Or do you feel okay about removing deprecated test stuff in a minor release?

**Comment by manusa** [comment]
Hey @shawkins, sorry for the extremely belated reply.
Let's hold on until we clarify what release strategy we want to adopt.
