### ISSUE TITLE
Unable to resolve dependency

### ISSUE THREAD

**Issue by vishal-biyani** [fabric8io/kubernetes-client#536]
Groovy grape is not able to resolve the dependency as it can't find the jar, is anyone else facing the same?

```
WARN: 	[NOT FOUND  ] io.fabric8#kubernetes-client-project;1.4.14!kubernetes-client-project.jar (2650ms)
WARN: ==== jcenter: tried
WARN:   https://jcenter.bintray.com/io/fabric8/kubernetes-client-project/1.4.14/kubernetes-client-project-1.4.14.jar
	resolve done (50ms resolve - 2653ms download)

:: problems summary ::
:::: WARNINGS
		[NOT FOUND  ] io.fabric8#kubernetes-client-project;1.4.14!kubernetes-client-project.jar (2650ms)

	==== jcenter: tried

	  https://jcenter.bintray.com/io/fabric8/kubernetes-client-project/1.4.14/kubernetes-client-project-1.4.14.jar


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Error in resolve:
	Error grabbing Grapes -- [download failed: io.fabric8#kubernetes-client-project;1.4.14!kubernetes-client-project.jar]
```

**Comment by vishal-biyani** [comment]
Has the kubernetes-client-project changed to "kubernetes-client" ? I see the JAR files for later in jcenter but not the former one

**Comment by jimmidyson** [comment]
No name change - kubernetes-client-project is the parent project for various modules, kubernetes-client is the module with that JAR.

**Comment by vishal-biyani** [comment]
Thanks @jimmidyson for claification. So for writing kubernetes client should kubernetes-client  be enough?

**Comment by vishal-biyani** [comment]
Hi @jimmidyson Is there a good reference on DSL which can be used to call Kube APIs? I could not find in Javadoc/Source code

**Comment by jimmidyson** [comment]
Not really unfortunately... it aims to be fluent so hopefully pretty readable. There are a number of examples in the source repo you can learn from too.
