### ISSUE TITLE
Ease the transition away from createOrReplace

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#5377]
We have two options:

- simply changing the definitions of createOrReplace and replace to be inline with what could be expected - that is change replace to be update and strip the retry and non-locking behavior from createOrReplace.  Yes this would be a breaking change and require additional documentation, but it would work most of the time with existing code.
- or introduce a generalized createOr(Function<Resource, T> conflictAction) method - such that you could do createOr(Resource::update), createOr(Resource::patch).  This could also be expressed in a more dsl-like way with resource.onConflict(Resource::update).create() or something that would be cross-cutting resource.createIfNotFound().update()

_Originally posted by @shawkins in https://github.com/fabric8io/kubernetes-client/issues/5337#issuecomment-1653494385_

**Comment by Bwvolleyball** [comment]
The code instructions for the deprecated `createOrReplace()` are frustratingly obtuse. Does not feel like this project was ready to deprecate that command.

**Comment by shawkins** [comment]
@Bwvolleyball please see the FAQ link in the Javadocs and the updates from #5367
