### ISSUE TITLE
how to develop webssh with kubernetes-client?

### ISSUE THREAD

**Issue by tiandizhiguai** [fabric8io/kubernetes-client#5383]
### Is your enhancement related to a problem? Please describe

Now, I want to develop a webssh with the kubernetes-client and xtermjs, but I have some questions.

when I run the following command in k8s cluster, it has output, like this:

```shell
[root@centos05 ~]# kubectl exec -it hello-1-qa-dhorse-7849ddf747-snzbk -- /bin/sh
/ # 
```

it output the '/ #'

but, when i run the command with kubernetes-client, it output nothing, code is: 

```java
public class SHHTest {
	private static final Logger logger = LoggerFactory.getLogger(SHHTest.class);
	private static final CountDownLatch execLatch = new CountDownLatch(1);

	private static String token = "xxx";
	
	public static void main(String[] args) {
		Config config = new ConfigBuilder()
				 .withTrustCerts(true)
				 .withMasterUrl("https://192.168.109.137:6443")
				 .withOauthToken(token)
				 .build();
		try (final KubernetesClient k8s = new KubernetesClientBuilder().withConfig(config).build()){
			ByteArrayOutputStream out = new ByteArrayOutputStream();
			ByteArrayOutputStream error = new ByteArrayOutputStream();

			ExecWatch execWatch = k8s.pods().inNamespace("default")
					.withName("hello-1-qa-dhorse-7849ddf747-snzbk")
					.writingOutput(out)
					.writingError(error)
					.usingListener(new MyPodExecListener())
					.exec("/bin/sh");

			boolean latchTerminationStatus = execLatch.await(5, TimeUnit.SECONDS);
			if (!latchTerminationStatus) {
				logger.warn("Latch could not terminate within specified time");
			}
			logger.info("Exec Output: {} ", out);
			
			execWatch.getInput();
			
			execWatch.close();
		} catch (InterruptedException ie) {
			Thread.currentThread().interrupt();
			logger.warn("Interrupted while waiting for the exec: {}", ie.getMessage());
		}
	}

	private static class MyPodExecListener implements ExecListener {
		@Override
		public void onOpen() {
			logger.info("Shell was opened");
		}

		@Override
		public void onFailure(Throwable t, Response failureResponse) {
			logger.info("Some error encountered");
			execLatch.countDown();
		}

		@Override
		public void onClose(int i, String s) {
			logger.info("Shell Closing");
			execLatch.countDown();
		}
	}
}
```

'logger.info("Exec Output: {} ", out);' output nothing. so, to make a webssh, what should I do? Many thanks.

### Describe the solution you'd like

Sorry, I don't have a solution.

**Comment by shawkins** [comment]
There are a couple of nuances to running an interactive shell that kubectl is encapsulating.  For fabricat8 you would do something like:

```
    ByteArrayOutputStream out = new ByteArrayOutputStream();
    ByteArrayOutputStream error = new ByteArrayOutputStream();

    ExecWatch exec = client.pods().withName("pod")
        .redirectingInput() // matches the -i interactive / stdin behavior of kubectl
        .writingOutput(out)
        .writingOutput(error)
        .withTTY() // matches the -t behavior of kubectl, if you want to show the output on a ternminal
        .exec("sh");

    // the output will now show a prompt if TTY is used 

    // to issue a command
    exec.getInput().write("ls\n".getBytes(StandardCharsets.UTF_8)); // note that it needs a trailing new line
    exec.getInput().flush(); // because there is buffering by default a flush will force the command to be sent
    // you may also consider wrapping the input in a Writer or a higher abstraction to handle these concerns
     
    // check the output for results
```

It is also usually simpler to use ExecWatch.exitCode, rather than using a ExecListener.

**Comment by tiandizhiguai** [comment]
I've tried that, and it works. Thanks for your suggestion.

**Comment by manusa** [comment]
I don't really see the need for that.

However, I do recall I had to do some manual stuff in order to make things work correctly in [YAKD](https://github.com/manusa/yakd).

https://github.com/manusa/yakd/blob/f750188140c3706ed92ce51f111a7087484b7b56/src/main/java/com/marcnuri/yakd/pod/PodExecEndpoint.java

I can't remember what the issue was at the moment. I had to end up re-implementing the exec feature downstream in order to support further piping to a frontend consumer. Not sure if it was the stream handling, the truncation of the codes, or just something else.

**Comment by caozhongyang** [comment]
> There are a couple of nuances to running an interactive shell that kubectl is encapsulating. For fabricat8 you would do something like:
> 
> ```
>     ByteArrayOutputStream out = new ByteArrayOutputStream();
>     ByteArrayOutputStream error = new ByteArrayOutputStream();
> 
>     ExecWatch exec = client.pods().withName("pod")
>         .redirectingInput() // matches the -i interactive / stdin behavior of kubectl
>         .writingOutput(out)
>         .writingOutput(error)
>         .withTTY() // matches the -t behavior of kubectl, if you want to show the output on a ternminal
>         .exec("sh");
> 
>     // the output will now show a prompt if TTY is used 
> 
>     // to issue a command
>     exec.getInput().write("ls\n".getBytes(StandardCharsets.UTF_8)); // note that it needs a trailing new line
>     exec.getInput().flush(); // because there is buffering by default a flush will force the command to be sent
>     // you may also consider wrapping the input in a Writer or a higher abstraction to handle these concerns
>      
>     // check the output for results
> ```
> 
> It is also usually simpler to use ExecWatch.exitCode, rather than using a ExecListener.

But When I Stop my java process, the remote shell process still in the pod, please tell me how todo?
