### ISSUE TITLE
CRD generator is not deterministic

### ISSUE THREAD

**Issue by Donnerbart** [fabric8io/kubernetes-client#5388]
### Is your enhancement related to a problem? Please describe

We're using the K8s client in a Quarkus Operator SDK application. We have configured the CRD generation of Quarkus, that is basically triggered on every test execution.

Since the CRD generation is not deterministic, the CRD file is constantly changed. Complex CRDs (for example, our current CRD is 3399 lines long) lead to multiple problems:
* When using the IntelliJ Kubernetes Plugin, you constantly see a `Reload schema` overlay on YAML files. 
![image](https://github.com/fabric8io/kubernetes-client/assets/4196298/0562b060-5097-4689-a79c-df25e415d5ae)
* It's very hard to determine if the CRD file contains actual changes, or if its content is just in a different order.
* Since we include default K8s resources in our CRD (Metadata, StatefulSetSpec, ServiceSpec), we cannot assume that the CRD is still the same as long as we don't touch our custom resource classes. On every update of the K8s client we could inherit CRD changes, that could force us to bump our CRD version (which is a fine trade-off for us, since we need to offer the full feature set of a StatefulSet and Service spec configuration).
* We have the generated CRD file in version control, so we constantly have a modified file in our change sets.
* It's very hard to setup automatic tests between, for example, an operator and depending Helm charts repository, to assert that both CRD files are still the same (for example, for an automated CI test that ensured both projects are in sync).

### Describe the solution you'd like

The CRD file should be generated deterministically, so the output is the same when the input hasn't changed. Preferably all elements are sorted alphabetically.

### Describe alternatives you've considered

We're using an external YAML sorter, but this is additional tooling we have to setup. This also doesn't solve the issues during development, when the CRD file is constantly changed when executing a simple test.

I have a technical solution for the `crd-generator` that I can offer as PR.

**Comment by metacosm** [comment]
Sorting things should indeed be performed as a first step. In-memory diff might be difficult to perform, unless we perform an equality check on each objects, which might not properly implement `equals`. If the yaml output is still not deterministic, performing the diff on the generated yaml would prove fruitless as it would most likely fail all the time, thus slowing things down for no good reason.
