### ISSUE TITLE
Exception, while concurrent deploymentConfig update

### ISSUE THREAD

**Issue by kfucGG** [fabric8io/kubernetes-client#5400]
Hello guys, while testing getting this error: Failure executing PATCH at: {url}
Message: Operation cannot be fulfilled on deploymentconfig.apps.openshift.io "{deployment_name}" the object has been modified.
I tryed to using Thread.sleep but exception anyway occurs, have any bestpractice for avoid this problem?

**Comment by rohanKanojia** [comment]
Do you have some reproducer code for this?

Looks like your object's resourceVersion gets updated in between the call https://github.com/kubernetes/kubernetes/issues/28149. Are you sure object isn't getting modified in between the calls?
