### ISSUE TITLE
what's useness about validationEnabled in construct of ConfigBuilder

### ISSUE THREAD

**Issue by sodaRyCN** [fabric8io/kubernetes-client#5409]
kubenetes-client version 6.0.0
as title describe, the validationEnabled filed seems like  it is not used.

**Comment by manusa** [comment]
cc/ @iocanel @shawkins

**Comment by shawkins** [comment]
> as title describe, the validationEnabled filed seems like it is not used.

I don't believe it is used.

Our Buildable annotations have validationEnabled=false, but the code generator adds this constructor parameter regardless.  Sundrio could be enhanced to omit the parameter.

**Comment by manusa** [comment]
TL;DR
Field is not used in Kubernetes Client. Sundrio can be improved to omit the addition of this field to the Builders. (needs a fix in Sundrio if we want to add the improvement)

**Comment by shawkins** [comment]
I've wored the upstream issue, so we'll get this at some point in the future.
