### ISSUE TITLE
exec with redirectingOutput/redirectingError throws exception

### ISSUE THREAD

**Issue by elexx** [fabric8io/kubernetes-client#5416]
### Describe the bug

When running `exec` in a container and the executable returns with a non-zero exitcode it is not possible to get the redirected output and errorstreams, without collecting the streams manually. See "Steps to reproduce" and "Expected behavior" for an example.

### Fabric8 Kubernetes Client version

6.8.1

### Steps to reproduce

1. start a pod `kubectl run alpine --image alpine:latest -- sleep infinity`
2. run 
```java
var process = client.pods().withName("alpine").inContainer("alpine")
    .redirectingOutput()
    .redirectingError()
    .exec("stat", ".dockerenvx")) { // This file does not exist!

System.out.println("EXITCODE: " + process.exitCode().join());
System.err.println("STDERR: " + new String(process.getError().readAllBytes(), StandardCharsets.UTF_8));
System.out.println("STDOUT: " + new String(process.getOutput().readAllBytes(), StandardCharsets.UTF_8));
```
3. get exception from `readAllBytes()` in `process.getError().readAllBytes()`
```text
Exception in thread "main" java.io.IOException: closed
	at io.fabric8.kubernetes.client.dsl.internal.ExecWatchInputStream.current(ExecWatchInputStream.java:97)
	at io.fabric8.kubernetes.client.dsl.internal.ExecWatchInputStream.read(ExecWatchInputStream.java:126)
	at java.base/java.io.InputStream.readNBytes(InputStream.java:409)
	at java.base/java.io.InputStream.readAllBytes(InputStream.java:346)
	at Main.main(Main.java:17)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: process exited with a non-zero exit code: 1
	at io.fabric8.kubernetes.client.dsl.internal.ExecWatchInputStream.onExit(ExecWatchInputStream.java:63)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1909)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
	at Main.main(Main.java:14)
```

### Expected behavior

1. run a slightly modified version, using `writingOutput` and `writingError` instead of `redirectingXYZ()`:
```java
var stdoutStream = new ByteArrayOutputStream();
var stderrStream = new ByteArrayOutputStream();
var process = client.pods().withName("alpine").inContainer("alpine")
    .writingOutput(stdoutStream)
    .writingError(stderrStream)
    .exec("stat", ".dockerenvx")) { // This file does not exist!

System.out.println("EXITCODE: " + process.exitCode().join());
System.err.println("STDERR: " + stderrStream.toString(StandardCharsets.UTF_8));
System.out.println("STDOUT: " + stdoutStream.toString(StandardCharsets.UTF_8));
```
2. get the output:
```text
EXITCODE: 1
STDERR: stat: can't stat '.dockerenvx': No such file or directory
STDOUT: 
```

### Runtime

Kubernetes (vanilla), minikube

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

**Comment by shawkins** [comment]
This comes down to the semantics of how abnormal process completion should be handled by the streams.  The current handling for the redirect streams is they treat a non-successful termination as a failure that should be reported as you are seeing.  Whereas you are wanting it to be ignored by the streams and just treated as EOF.  

If you use another method other than readAllBytes, you can still read the data that was supplied to the streams.

@manusa @rohanKanojia any thoughts on this - if we just silently handle it the user should definitely check the exit code, otherwise they won't know about the abnormal termination.

**Comment by elexx** [comment]
Thanks for your quick response.

I see. So the problem actually is, the stream never returns an EOF `-1` but an exception while reading beyond the last actual byte. Which means I can't consume the stream without try-catching the whole consuming loop.

I would prefer your suggestion of not throwing an exception. Especially since the exception is only thrown when reading one of the 2 streams. If I just ignore the redirected streams I don't get an exception. That forces me to check the exit code anyway for an abnormal termination.

**Comment by shawkins** [comment]
> I would prefer your suggestion of not throwing an exception

This could be viewed as a breaking change, so it will need more discussion.

> Especially since the exception is only thrown when reading one of the 2 streams.

I don't quite follow this, they should each have the same behavior.

**Comment by elexx** [comment]
I meant, just doing this wont throw any exception:
```java
var process = client.pods().withName("alpine").inContainer("alpine")
    .redirectingOutput()
    .redirectingError()
    .exec("stat", ".dockerenvx"));
process.exitCode().join();
```
So to actually get an exception from an abnormal termination I need to consume stdout or stderr beyond the (not marked) end of the stream.

**Comment by shawkins** [comment]
> So to actually get an exception from an abnormal termination I need to consume stdout or stderr beyond the (not marked) end of the stream.

That's correct, but it's also not the usage that is expected - there is only a small buffer manintained on the streams, so the above is relying on that they won't fill up before the exit needs handled.  If there is too much data, the non-blocking io will simply stop requesting from the websocket and the whole thing will appear to hang because the output / error are not being consumed.

**Comment by elexx** [comment]
That's a very good point!

For now I think I'll keep the ByteArrayStreams for buffering the outputs. If you should decide to change the behavior of the redirected output to return EOF instead of an exception and want me to provide an MR please feel free to ping me.
