### ISSUE TITLE
Missing custom resource Pipe in camel-k-client

### ISSUE THREAD

**Issue by lfabriko** [fabric8io/kubernetes-client#5433]
### Is your enhancement related to a problem? Please describe

While testing Camel K via TNB, we use camel-k-client; since upstream release 2.0, KameletBinding should be replaced by `Pipe`.

### Describe the solution you'd like

Would it be possible to update Camel-K model to 2.0 (currently set to [1.9.2](https://github.com/fabric8io/kubernetes-client/blob/v6.7.2/extensions/camel-k/generator-v1/go.mod#L4))?

**Comment by rohanKanojia** [comment]
@lfabriko : Are you sure you've created this issue on correct repository? Camel K is no longer part of Fabric8 https://github.com/fabric8io/kubernetes-client/issues/5171

**Comment by lfabriko** [comment]
I see, thank you for info.
