### ISSUE TITLE
409 conflict status code when create pod

### ISSUE THREAD

**Issue by zhouhaibing089** [fabric8io/kubernetes-client#544]
I am trying to use kubernetes-client(1.4) to create pods.

```java
private Pod createPod() throws Exception {
    return client.pods().inNamespace("kube-system").createNew()
        .withNewMetadata()
            .withName("nginx")
            .addToLabels("server", "nginx")
        .endMetadata()
        .withNewSpec()
            .addNewContainer()
                .withName("nginx")
                .withImage("nginx")
                .addNewPort().withContainerPort(80).endPort()
            .endContainer()
        .endSpec()
        .done();
}
```

most of the times, the code works pretty well, but occasionally, I will get a `KubernetesException` which has status code 409 and message like:

```
Failure executing: 
  POST at: https://192.168.0.1/api/v1/namespaces/kube-system/pods. Message: pods "nginx" already exists. 
  Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=pods, name=nginx, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=pods "nginx" already exists, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
```

**Comment by jimmidyson** [comment]
That's a response from the API server - does a pod with that name already exist?

**Comment by zhouhaibing089** [comment]
@jimmidyson I am pretty sure there is no pod with the given name "nginx"  before the call mentioned above.

**Comment by zhouhaibing089** [comment]
there is a guard to make sure that:

```java
client.pods().inNamespace(namespace).withName("nginx").get()
```

**Comment by zhouhaibing089** [comment]
sorry for this noise, it looks like a bug in our code.

**Comment by jimmidyson** [comment]
No worries. Glad you found the problem.

**Comment by SovitSourav** [comment]
V1ConfigMap apacheConfigmap = null;
apacheConfigmap = api.createNamespacedConfigMap(namespace, apacheConfigmapBody, includeUninitialized,null, null);

After executing the above method in my k8s i'm getting the below error, can anyone please help me out
Exception occured while Creating the Apache ConfigMap	io.kubernetes.client.ApiException: Conflict

**Comment by xfeng-github** [comment]
> V1ConfigMap apacheConfigmap = null; apacheConfigmap = api.createNamespacedConfigMap(namespace, apacheConfigmapBody, includeUninitialized,null, null);
> 
> 在我的 k8s 中执行上述方法后，我收到以下错误，任何人都可以帮我解决 创建 Apache ConfigMap io.kubernetes.client.ApiException: Conflict 时发生的异常

Hello，这个问题后来是怎么解决的呢，我也遇到了同样的问题，

**Comment by rohanKanojia** [comment]
@xfeng-github : Seems like you're using the other kubernetes client library.

With Fabric8 Kubernetes Client you can do it via `createOrReplace` method

```xml
        <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>kubernetes-client</artifactId>
            <version>5.11.2</version>
        </dependency>
```

```java
		try (final KubernetesClient client = new DefaultKubernetesClient()) {
			ConfigMap configMap1 = new ConfigMapBuilder()
					.withNewMetadata()
					  .withName("configmap1")
					.endMetadata()
					.addToData("one", "1")
					.addToData("two", "2")
					.addToData("three", "3")
					.build();

			client.configMaps().inNamespace(namespace).createOrReplace(configMap1);
		}
```
