### ISSUE TITLE
Is the timeout of Config invalid?

### ISSUE THREAD

**Issue by tiandizhiguai** [fabric8io/kubernetes-client#5447]
### Is your enhancement related to a problem? Please describe

I list namespaces of cluster:

```java
private KubernetesClient client(String basePath, String accessToken) {
	 Config config = new ConfigBuilder()
			 .withTrustCerts(true)
			 .withMasterUrl(basePath)
			 .withOauthToken(accessToken)
			 .withConnectionTimeout(1000)
			 .withRequestTimeout(1000)
			 .build();
	return new KubernetesClientBuilder()
			.withConfig(config)
			.build();
}

NamespaceList namespaceList = null;
try(KubernetesClient client = client(clusterPO.getClusterUrl(), clusterPO.getAuthToken())){
	logger.info("start time: {}", new Date());
	try {
		namespaceList = client.namespaces().list();
	}catch(Exception e) {
		e.printStackTrace();
	}
	logger.info("end time: {}", new Date());
}
```

log is: 

```shell
start time: Wed Sep 13 18:06:23 CST 2023
end time: Wed Sep 13 18:06:54 CST 2023
```

The connectionTimeout of Config is 1 second(1000ms).
However, the end time differs from the start time by 30 seconds, why isn't it 1 second?

### Describe the solution you'd like

None

**Comment by shawkins** [comment]
Please use trace logging to see at a more detailed level what is happening.  By default 10 retries with an exponetial backoff are supported.  The connectionTimeout applies only to the time it takes to establish the http connection, and the request timeout applies to each individual attempt.

**Comment by tiandizhiguai** [comment]
Yes, i see Config.DEFAULT_REQUEST_RETRY_BACKOFFLIMIT is 10, i don't know why the default is 10 retries, shouldn't it be fewer retries or no retry?

**Comment by shawkins** [comment]
10 matches kubectl I believe.

**Comment by tiandizhiguai** [comment]
Ok, many thanks!

**Comment by manusa** [comment]
This is the default behavior for the client. However, you can always set `kubernetes.request.retry.backoffLimit` to `0` which will prevent for any retries. This might be specially interesting for (mock) tests where you're actually verifying your app's behavior for failing scenarios.

I'm closing this issue, please reopen or open a new one in case your problem is not resolved.
