### ISSUE TITLE
Add an Ambassador extension to fabric8 (similar to existing istio extension)

### ISSUE THREAD

**Issue by musabshak** [fabric8io/kubernetes-client#5453]
This would allow creating Ambassador resources easily using fabric8 k8s client. Currently, workaround is to use [GenericKubernetesResource](https://developers.redhat.com/articles/2023/01/05/how-use-fabric8-kubernetes-client#) API. However, this does not integrate well with the Java operator sdk ([josdk](https://javaoperatorsdk.io/)). 

Existing istio extension: https://github.com/fabric8io/kubernetes-client/tree/864dd19a738388cf1c625e34f82bc8d11d39da28/extensions/istio

Do the same for Ambassador resources (Mapping, TLSContext, etc): https://www.getambassador.io/docs/emissary/latest/topics/using/intro-mappings

**Comment by andreaTP** [comment]
Hi @musabshak and thanks for your interest in the project!

From the fact that you opened #5452 I understand that you attempted to use the `java-generator` already, apart from the "sundrio" detail, have you found any issue/limitation using it without generating the extra annotations?

We are in the (extremely slow) process of getting rid of the extensions in favor of using the java-generator in the upstream projects (you have an [example in Camel-k](https://github.com/apache/camel-k/tree/main/java) ).

The Ambassador project seems to be closed source, are you in contact with any developers there?
I'm happy to start a conversation and support the integration ( another [example](https://github.com/chaos-mesh/chaos-mesh/pull/4087) ).

**Comment by musabshak** [comment]
Thanks for the quick response!

The Ambassador ("Emissary", as it is now called), is open source I believe: https://github.com/emissary-ingress/emissary. They have a Slack channel where they're pretty responsive - it is linked at the bottom of their landing page: https://www.getambassador.io/

Using the `java-generator` upstream to auto-create the extension-equivalent code would be super neat haha, if it works out!

> have you found any issue/limitation using it without generating the extra annotations?
I've had some issues with the plugin converting CRD yaml `enum` to Java enum. One concrete bug is #5457.

**Comment by andreaTP** [comment]
Thanks for getting back @musabshak !

Let's try to proceed like this:
- fix any bug that's triggered by their CRD
- get a stable release out
- start the conversation for generating "official java clients" from their projects

**Comment by andreaTP** [comment]
Hey @musabshak , now that 6.9 has been released we can proceed with the plan.
A couple of questions:

- do you mind verifying that we have closed and fixed all of the bugs?
- do you want to drive the conversation with the "emissary" team? (I'm a bit busy those days and I don't wanna delay everyone) feel free to keep me in cc. though

**Comment by andreaTP** [comment]
Hey @musabshak I completely lost track of this one, any update?

**Comment by csviri** [comment]
Hi, note that `GenericKubernetesResource` will be supported from the next release of Java Operator SDK, see:

https://github.com/operator-framework/java-operator-sdk/pull/2136

**Comment by musabshak** [comment]
@andreaTP Thanks for following up and apologies for the late response. 

I [ended up using](https://gerrit-review.googlesource.com/c/k8s-gerrit/+/386014) the `java-generator` plugin to generate POJOs for Ambassador resources in the OSS operator project I had been working on. 

Glad to hear that `GenericKubernetesResource` will be supported in josdk moving forward - it would certainly have simplified the changes I had needed to make earlier haha. Thanks again for the help and responsiveness!

**Comment by musabshak** [comment]
I am closing this issue with the following conclusion:

If your project uses the `fabric8io/kubernetes-client` library and you find yourself needing to refer to Ambassador (or other custom resources), just generate POJOs using the `java-generator`plugin. If your project happens to be a `josdk` project, using the `GenericKubernetesResource` (soon to be supported with `josdk`), may work for your usecase.

**Comment by andreaTP** [comment]
Thanks for feedback much appreciated!
