### ISSUE TITLE
Question about using optional flags when using `rollout undo` command 

### ISSUE THREAD

**Issue by Baytwt** [fabric8io/kubernetes-client#5469]
Hello, I'm considering using fabric8 to do the commomd:

`kubectl  -n <namespace> rollout undo deploy <deployment> --to-revision=2 --v=9`

There's an example in  `RolloutUndoEquivalent.java`:

```java
Deployment deployment = client.apps().deployments()
      .inNamespace("default")
      .withName("nginx-deployment")
      .rolling()
      .undo();
```

I'm wondering how to add the flags `--to-revision` and `--v` to it.

**Comment by shawkins** [comment]
@Baytwt --to-revision does not have support yet in the fabric8 client, it always defaults to the last revision.  --v I believe is a verbosity level option for the client - that is controlled in fabric8 with the logging config.
