### ISSUE TITLE
java.lang.OutOfMemoryError in thread 'OkHttpDispatcher'

### ISSUE THREAD

**Issue by sidjainbp** [fabric8io/kubernetes-client#5476]
### Describe the bug

The pod is crashing due to OutOfMemoryError while registering shared informers in an AKS cluster with Microsoft Defender enabled. PFA the exception stack:

> Exception in thread "OkHttp Dispatcher" java.lang.OutOfMemoryError: Java heap space
> 	at okio.Buffer.readByteArray(Buffer.kt:1429)
> 	at okio.Buffer.readByteArray(Buffer.kt:1424)
> 	at okio.RealBufferedSource.readByteArray(RealBufferedSource.kt:238)
> 	at okhttp3.ResponseBody.bytes(ResponseBody.kt:124)
> 	at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl$OkHttpResponseImpl.<init>(OkHttpClientImpl.java:133)
> 	at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl$4.onResponse(OkHttpClientImpl.java:277)
> 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.base/java.lang.Thread.run(Unknown Source)

### Fabric8 Kubernetes Client version

6.4.1

### Steps to reproduce

PS: Hard to replicate, occurs very rarely.
1. In an AKS cluster, enable microsoft defender with default policies.
2. In a java service, add shared informers for kubernetes resources (Pod, Deployment, Service, StatefulSet, Secret, ConfigMap) and start all informers.
4. Reduce the memory allocated for the deployment.
5. Start the deployment with reduced allocation.

### Expected behavior

The pod should crash with OutOfMemoryError in the thread 'OkHttpDispatcher'.

### Runtime

OpenShift

### Kubernetes API Server version

1.25.3@latest

### Environment

Azure

### Fabric8 Kubernetes Client Logs

```shell
Exception in thread "OkHttp Dispatcher" java.lang.OutOfMemoryError: Java heap space
	at okio.Buffer.readByteArray(Buffer.kt:1429)
	at okio.Buffer.readByteArray(Buffer.kt:1424)
	at okio.RealBufferedSource.readByteArray(RealBufferedSource.kt:238)
	at okhttp3.ResponseBody.bytes(ResponseBody.kt:124)
	at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl$OkHttpResponseImpl.<init>(OkHttpClientImpl.java:133)
	at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl$4.onResponse(OkHttpClientImpl.java:277)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by shawkins** [comment]
Just the stacktrace is not sufficient to diagnose an OOM error.  You'll need to examine a heap dump to see what is holding the memory of your vm at the time of the error.  From there we can determine if anything related to fabric8 is causing your issue.

**Comment by sidjainbp** [comment]
I have extracted a couple of heap dumps from the AKS cluster (not the one in which this issue occurred, however reduced memory allocation to the pod and simulated OOM error).
[Google Drive Link](https://drive.google.com/drive/folders/1Z6g_6pln8G6lUubsFNrDfmvqfbZilkZA?usp=sharing)

**Comment by shawkins** [comment]
@sidjainbp looking at the second heap dump there isn't much retained under io.fabric8 nor okhttp3 classes.  You are probably going to need to produce a heap dump from when the OOM occurs.  Also you haven't mentioned what amount of memory you are seeing the OOM at nor what you have seen as a typical amount of memory usage by your VM such that the OOM would be indicative of a leak or similar issue from within fabric8.

**Comment by shawkins** [comment]
Also the raw heap dumps provide the entire vm state - giving public direct access to those should be done with caution.
