### ISSUE TITLE
Release Fabric8 Kubernetes Client 6.9.0 + 6.9.1 + 6.9.2

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#5479]
### Description

Issue to track the required tasks to release Fabric8 Kubernetes Client 6.9.0 + 6.9.1 + 6.9.2.
- [x] https://github.com/fabric8io/kubernetes-client/milestone/65
- [x] https://github.com/fabric8io/kubernetes-client/milestone/68
- [x] https://github.com/fabric8io/kubernetes-client/milestone/69
- [x] Prepare release
- [x] Quarkus Version Bump
  https://github.com/fabric8io/kubernetes-client/issues/5522
  https://github.com/sundrio/sundrio/issues/438
  https://github.com/fabric8io/kubernetes-client/issues/5564
  https://github.com/dekorateio/dekorate/pull/1269
  https://github.com/fabric8io/kubernetes-client/issues/5574
  https://github.com/dekorateio/dekorate/pull/1272
  https://github.com/quarkusio/quarkus/pull/36312
- [x] Create issue for next release (and milestone if needed)
  https://github.com/fabric8io/kubernetes-client/issues/5500

**Comment by xiaoma20082008** [comment]
please wait this [pr439](https://github.com/sundrio/sundrio/pull/439) about `io.sundr`'s support of `lombok` when you want bumping `io.sundr` up to `0.101.2`
