### ISSUE TITLE
[openshift-client] Deleting a DeploymentConfig does not delete the deployer pod

### ISSUE THREAD

**Issue by donovanmuller** [fabric8io/kubernetes-client#548]
Similar to #518 in that if you (`cascading = true`) delete a dc, everything (dc, rc, pods) gets deleted _except_ the deployer pod. 

The deployer pod also does not have the labels that the dc, rc or pods do, so finding the corresponding deployer pod for a dc is rather nasty. I currently have this which works but feels dirty:

``` java
    // if appId relates to an app with name 'some-app'
    client.deploymentConfigs().withName(appId).cascading(true).delete();
    ...
    // clean up the deployment pods. E.g. some-app-1-deploy
    for (Pod pod : client.pods().withLabel("openshift.io/deployer-pod-for.name").list().getItems()) {
        if (pod.getMetadata().getName().startsWith(appId))  {
            client.pods().withName(pod.getMetadata().getName()).cascading(true).delete();
    }
}
```

A cascading delete for a `DeploymentConfig` should also delete the deployer pods in OpenShift.

**Comment by iocanel** [comment]
I'll have a look asap.
