### ISSUE TITLE
Upgrade okio-jvm dependency

### ISSUE THREAD

**Issue by gabesotto** [fabric8io/kubernetes-client#5485]
### Is your task related to a problem? Please describe

The version of okio-jvm used (3.0.0) is vulnerable to a ddos attack. The fix is in 3.1.0.
Fixed here: https://github.com/square/okio/pull/1280

### Describe the solution you'd like

Upgrade to atleast 3.1.0 but the most recent version is 3.5.0

**Comment by Mandeep56Singh** [comment]
hello gabesotto
is know only java is enough to work on this issue . 
if not , what other things do i need to know in order to solve this issue ?
I would appreciate your help.

**Comment by gabesotto** [comment]
Hey @Mandeep56Singh 

You shouldn't need any java code, you just need to update your dependencies.
I'm not super familiar with your dependency management but in your `pom.xml` your okhttp is severly out of date:

`  <okhttp.version>3.12.12</okhttp.version>
    <okhttp.bundle.version>3.12.1_1</okhttp.bundle.version>
    <okio.version>1.15.0</okio.version>
    <okio.bundle.version>1.15.0_1</okio.bundle.version>`
    
    You should update okhttp to `4.11` if possible: https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp
    
  Also potentially okio? but You will need to review your dependency tree with maven to see what depends on what. But if you update okhttp & okio to the newest version it should resolve this issue.

**Comment by gabesotto** [comment]
@Mandeep56Singh 

Another thing I just discovered - it seems they backported the fix to `okio 1.17.6` 
https://github.com/square/okio/pull/1334
https://repo1.maven.org/maven2/com/squareup/okio/okio/1.17.6/

I'm still not sure how the depdency between okhttp & okio works in your system but its possible you maybe able to just update that one if you don't want a major version jump.

**Comment by ggee** [comment]
`   <okhttp.version>3.12.12</okhttp.version>`

Yes, this version needs to be updated as vulnerabilities have been reported in use.  My security scans are failing because of this version.
