### ISSUE TITLE
How to load Istio resource in kubernetes java client ?

### ISSUE THREAD

**Issue by shubhampanth-fareye** [fabric8io/kubernetes-client#5486]

**Comment by rohanKanojia** [comment]
@shubhampanth-fareye : Could you please check [examples section](https://github.com/fabric8io/kubernetes-client/tree/main/extensions/istio/examples/src/main/java/io/fabric8/istio/api/examples/v1beta1) in Istio extension?

**Comment by shubhampanth-fareye** [comment]
Hi @rohanKanojia 

I am using KubernetesClient java client (6.3.1) and i have a virtual service yaml and i want to add this virtual service in the client 
could you help in the same

**Comment by rohanKanojia** [comment]
You can check out [VirtualServiceExample](https://github.com/fabric8io/kubernetes-client/blob/main/extensions/istio/examples/src/main/java/io/fabric8/istio/api/examples/v1beta1/VirtualServiceExample.java), you have to load the YAML into object like I showed in previous comment

**Comment by shubhampanth-fareye** [comment]
VirtualService virtualService = istioClient.v1beta1().virtualServices().load(
                VirtualServiceExample.class.getResourceAsStream("/virtualService.yaml")
        ).get();  
Can i skip using the POJO  VirtualServiceExample in above

**Comment by rohanKanojia** [comment]
@shubhampanth-fareye : What do you mean by skipping POJO? You can directly apply the YAML like this:
```
istioClient.v1beta1().virtualServices().load(
            VirtualServiceExample.class.getResourceAsStream("/virtualService.yaml")
    ).serverSideApply();
```

**Comment by shubhampanth-fareye** [comment]
Actually my yaml is stored in S3 and will be downloading it from there so i cannot use any class as VirtualServiceExample.class

**Comment by shubhampanth-fareye** [comment]
@rohanKanojia 
If i already have a targetStream of the yaml file can i directly load it into it

VirtualService virtualService = istioClient.v1beta1().virtualServices().load(targetStream).get();

**Comment by rohanKanojia** [comment]
> @rohanKanojia If i already have a targetStream of the yaml file can i directly load it into it
> 
> VirtualService virtualService = istioClient.v1beta1().virtualServices().load(targetStream).get();

I think that should work. Are you facing some error when you run it?

**Comment by sunix** [comment]
hi @shubhampanth-fareye 
Is your issue resolved ? let us know. Thanks
