### ISSUE TITLE
Ensure that the result of CRD generation is always the same, if Java classes do not change

### ISSUE THREAD

**Issue by thomasdraebing** [fabric8io/kubernetes-client#5508]
### Is your enhancement related to a problem? Please describe

In some situations, notably if multiple versions of a CustomResource exist, the result of CRD generation differs from run to run in the order in which the versions are added to the list. While this doesn't change the behaviour of Kubernetes, since the version order does not matter, it causes unnecessary changes if checked into git or applied to the cluster.

### Describe the solution you'd like

There should be an ordered List of CR versions in the generated CRD either from oldest to newest or newest to oldest version.

**Comment by andreaTP** [comment]
Thanks for taking the time to report this issue @thomasdraebing 👍 

We recently improved the situation by ordering properties( #5390 ), I think it's reasonable to also order the versions in a deterministic way.

Would you be willing to submit a PR for this?

cc. @metacosm
