### ISSUE TITLE
Cannot build karak-itests module

### ISSUE THREAD

**Issue by metacosm** [fabric8io/kubernetes-client#5512]
### Describe the bug

Maven build fails with:

Execution add-features-to-repo of goal org.apache.karaf.tooling:karaf-maven-plugin:4.4.4:features-add-to-repository failed: An API incompatibility was encountered while executing org.apache.karaf.tooling:karaf-maven-plugin:4.4.4:features-add-to-repository: java.lang.ExceptionInInitializerError: null

: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
[ERROR]  - with linked exception:
[ERROR] [java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory]

### Fabric8 Kubernetes Client version

SNAPSHOT

### Steps to reproduce

Simply run: mvn clean install -DskipTests

### Expected behavior

Build should work

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

macOS

**Comment by metacosm** [comment]
For documentation purpose: 
The issue occurs because my maven repository location is a symbolic link to a location on a different volume. That seems to be causing issue with the OSGi toolchain. Workaround is to either build without that module or to build using a local repository using `-Dmaven.repo.local`. Interestingly, though, passing the "real" location of the repository to that property (i.e. resolving the symbolic link) doesn't work for some reason either.

**Comment by manusa** [comment]
> Interestingly, though, passing the "real" location of the repository to that property (i.e. resolving the symbolic link) doesn't work for some reason either.

Maybe it's the real location of the .m2 directory what's affecting the build.

Anyway, happy to see that you managed to fix the issue. Thanks for reporting and providing feedback.
