### ISSUE TITLE
How to disable the kubernetes-client

### ISSUE THREAD

**Issue by cesartl** [fabric8io/kubernetes-client#552]
Hi,

I'm using the kubernetes-client with io.fabric8.kubeflix:ribbon-discovery and it works create when deploying my application in my k8s cluster.

However when I'm trying to run the app locally it prevent my application from starting. In the log I see:

    12:03:27.260 [main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client from Kubernetes config...
    12:03:27.267 [main] DEBUG io.fabric8.kubernetes.client.Config - Found for Kubernetes config at: [/Users/Cesar/.kube/config].

Then the application hangs. When I use the Jvisualvm sampler I see that the application is hanging on some OKHttp classes and it doesn't start.

Is there way to prevent the kubernetest client from creating connections to my k8s cluster?

**Comment by cesartl** [comment]
Not related to kuberntes-client, please ignore

**Comment by nikkatalnikov** [comment]
@cesartl having the same issue with minikube. how did you manage to fix?

**Comment by cesartl** [comment]
Hey @nikkatalnikov, to be honest, I don't remember. It was so long ago.
