### ISSUE TITLE
Issues with module-info after upgrading to 6.9.0

### ISSUE THREAD

**Issue by Sidhardha95** [fabric8io/kubernetes-client#5520]
### Describe the bug

We are previously on version 6.7.2 and we are trying to uptake 6.9.0 

But our builds are failing with below error 

```
[ERROR] error: module knative.client reads package io.fabric8.kubernetes.api.builder from both kubernetes.model.core and kubernetes.model.common
[ERROR] error: module knative.model reads package io.fabric8.kubernetes.api.builder from both kubernetes.model.core and kubernetes.model.common
[ERROR] error: module com.fasterxml.jackson.databind reads package io.fabric8.kubernetes.api.builder from both kubernetes.model.core and kubernetes.model.common
[ERROR] error: module org.reflections reads package io.fabric8.kubernetes.api.builder from both kubernetes.model.core and kubernetes.model.common
[ERROR] error: module org.checkerframework.checker.qual reads package io.fabric8.kubernetes.api.builder from both kubernetes.model.core and kubernetes.model.common
[ERROR] error: module com.fasterxml.jackson.core reads package io.fabric8.kubernetes.api.builder from both kubernetes.model.core and kubernetes.model.common
[ERROR] error: module kubernetes.model.common reads package io.fabric8.kubernetes.api.builder from both kubernetes.model.core and kubernetes.model.common
[ERROR] error: module kubernetes.client.api reads package io.fabric8.kubernetes.api.builder from both kubernetes.model.common and kubernetes.model.core
[ERROR] error: module kubernetes.model.core reads package io.fabric8.kubernetes.api.builder from both kubernetes.model.core and kubernetes.model.common
```

This is our module-info.java 

```
module com.demo {
    requires com.fasterxml.jackson.annotation;
    requires kubernetes.model.core;
    requires static org.checkerframework.checker.qual;
    requires org.reflections;
    requires java.logging;
    requires com.fasterxml.jackson.databind;
    requires org.graalvm.sdk;
    requires knative.model;
    requires knative.client;
    requires kubernetes.model.common;
    requires kubernetes.client.api;
}
```

### Fabric8 Kubernetes Client version

6.9.0

### Steps to reproduce

1. Just build with latest fabric8 client 

### Expected behavior

Build should be successful

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

1.25.3@latest

### Environment

macOS

**Comment by shawkins** [comment]
This relates to the change to add an edit/toBuilder method to each model object.  I unwittingly introduced a split package.  The simplest change would be to move the .api packages from core to common.  @manusa @rohanKanojia any objections?

**Comment by rohanKanojia** [comment]
> The simplest change would be to move the .api packages from core to common

This change will be transparent to the end user, right? If yes, no objection from my side.

**Comment by shawkins** [comment]
> This change will be transparent to the end user, right? If yes, no objection from my side.

It should be.  core already depends on common, and I wouldn't expect anyone to complain if common got a little larger.

**Comment by shawkins** [comment]
Looking at this more closely, it's not a split package problem.  It's an issue with the osgi bundling - having the builder package still listed in core is copying the classes from common.
