### ISSUE TITLE
Does the kubernetes client support draining a node?

### ISSUE THREAD

**Issue by zenbones** [fabric8io/kubernetes-client#5526]
I need to automate cordon/drain and then deleting a node. I see the delete, but was wondering if it drains first or if there's another way to do that via the client?

**Comment by shawkins** [comment]
Unfortunately not yet.  The kubectl drain functionality is largely implemented on the client side https://github.com/kubernetes/kubectl/blob/7b29ca0b6c54021902b46fe33e41a13792749670/pkg/drain/drain.go which has not yet been ported to the java client.

If you don't care about evicting, then a cordon and deletion of all pods on a node would do the trick.  

```
List<Pod> pods = client.pods()
                    .inAnyNamespace()
                    .withField("spec.nodeName", toDrain)
                    .delete();
```

**Comment by zenbones** [comment]
No, I'll need to act upon a specific node. I guess I'll need to do this from a shell with a user with rights and a proper .kube setup... not happy making. But not your fault either. Thanks for the response.

**Comment by shawkins** [comment]
@zenbones let me show this more completely:

```
String toDrain = "some node name";

// cordon
client.nodes().withName(toDrain).accept(node -> node.getSpec().setUnschedulable(true));

// wait at most 2 minutes for all the existing pods on the node to be deleted
List<Pod> pods = client.pods()
                    .inAnyNamespace()
                    .withField("spec.nodeName", toDrain)
                    .withTimeout(2, TimeUnit.MINUTES)
                    .delete();

// you can log the pods deleted, or not use withTimeout and do your own logic of when things are cleaned up enough

// now allow scheduling again
client.nodes().withName(toDrain).accept(node -> node.getSpec().setUnschedulable(false));
```

Or you can try to emulate the kubectl logic that implements eviction when possible instead of just doing a delete.

**Comment by zenbones** [comment]
Thank you. Clear enough.
