### ISSUE TITLE
Rolling restart fails with mock CRUD server

### ISSUE THREAD

**Issue by adamish** [fabric8io/kubernetes-client#5530]
### Describe the bug

Rolling restart fails with mock CRUD server. 

It appears that rolling().restart() issues a patch of type **"application/strategic-merge-patch+json"** but this is not handled by class io.fabric8.kubernetes.client.server.mock.crud.PatchHandler, specifically io.fabric8.kubernetes.client.server.mock.crud.PatchHandler.getMergeType(String)

### Fabric8 Kubernetes Client version

6.9.0

### Steps to reproduce

Run test case

```
import org.junit.jupiter.api.Test;

import io.fabric8.kubernetes.api.model.apps.DeploymentBuilder;
import io.fabric8.kubernetes.client.NamespacedKubernetesClient;
import io.fabric8.kubernetes.client.server.mock.KubernetesServer;

class PatchTest {
	@Test
	void patch() {
		KubernetesServer mockServer = new KubernetesServer(true, true);
		mockServer.before();
		NamespacedKubernetesClient client = mockServer.getClient();

		client.apps().deployments()
				.resource(new DeploymentBuilder().withNewMetadata().withName("dave-rigby").and().build()).create();

		client.apps().deployments().withName("dave-rigby").rolling().restart();
	}
}
```

### Expected behavior

No exceptions. Rolling restart to be simulated.

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

**Comment by shawkins** [comment]
Generally we'll consider this an enhancement, not a bug - the mock server doesn't work for quite a bit of functionality.  You'll want to consider using a light-weight kubernetes or https://github.com/java-operator-sdk/jenvtest for your testing.
