### ISSUE TITLE
EOS of v5.x

### ISSUE THREAD

**Issue by PilotPaul** [fabric8io/kubernetes-client#5534]
What's the End of Support of version v5.x and 6.x?

**Comment by manusa** [comment]
Not sure what do you mean with "End of Support", as in support by whom?

We're providing best effort to patch any reported vulnerabilities or any other critical fixes to version 5.12.

For v6, we recommend to always use the latest minor release. Nonetheless, we'll try to provide security fixes for minor versions that might be critical for downstream projects that depend on the client.

Do you have any specific request?

**Comment by PilotPaul** [comment]
> Not sure what do you mean with "End of Support", as in support by whom?
> 
> 
> 
> We're providing best effort to patch any reported vulnerabilities or any other critical fixes to version 5.12.
> 
> 
> 
> For v6, we recommend to always use the latest minor release. Nonetheless, we'll try to provide security fixes for minor versions that might be critical for downstream projects that depend on the client.
> 
> 
> 
> Do you have any specific request?

No, thx a lot, I'll continue to use v5.12.
