### ISSUE TITLE
[proposal] Include accessory libraries to the BOM

### ISSUE THREAD

**Issue by andreaTP** [fabric8io/kubernetes-client#5535]
### Is your enhancement related to a problem? Please describe

Using the `kubernetes-client-bom` is extremely convenient, but it would be nice to include "accessory" libraries like `sundrio` and `lombok` to make sure that those versions are aligned to the one used in this project.

### Describe the solution you'd like

Include some transitive dependencies to the `kubernetes-client-bom` BOM.

### Describe alternatives you've considered

Is there any issue?

**Comment by manusa** [comment]
Sounds reasonable to me.

However, the BOM is generated using a Sundrio-based Maven Plugin. I'm not sure if it works for `provided` scoped dependencies. If it works, it's just a matter of adding the required entries.

**Comment by manusa** [comment]
Note that this should be part of the `kubernetes-client-bom-with-deps` artifact.
