### ISSUE TITLE
When I upload Dir ，Files will not be accurately placed in the corresponding folder

### ISSUE THREAD

**Issue by y335283348** [fabric8io/kubernetes-client#5557]
### Describe the bug

kubernetesClient.pods().inNamespace(namespace)
                .withName(podName).dir(podPath) // <- Path of directory inside Pod
                .upload(dirToUpload.toPath()); // <- Local Path of directory
the dir in local
/test -- dir
  /test/a.txt -- file
  /test/dir2 -- dir
    /test/dir2/b.txt -- file

when I upload to Pod

the dir in pod
/test -- dir
  /test/a.txt -- file
  /test/dir2 -- dir
  /test/b.txt -- file

### Fabric8 Kubernetes Client version

6.9.1

### Steps to reproduce

kubernetesClient.pods().inNamespace(namespace)
                .withName(podName).dir(podPath) // <- Path of directory inside Pod
                .upload(dirToUpload.toPath()); // <- Local Path of directory
the dir in local
/test -- dir
  /test/a.txt -- file
  /test/dir2 -- dir
    /test/dir2/b.txt -- file

when I upload to Pod

the dir in pod
/test -- dir
  /test/a.txt -- file
  /test/dir2 -- dir
  /test/b.txt -- file

### Expected behavior

the dir upload to pod should be same with load dir

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

**Comment by shawkins** [comment]
Could not reproduce this.  Please reopen if you have a more complete reproducer.
