### ISSUE TITLE
Create an extension for KubeVirt

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#5570]
### Is your enhancement related to a problem? Please describe

Create an extension for KubeVirt

### Describe the solution you'd like

Create an extension for KubeVirt

**Comment by andreaTP** [comment]
Thanks for the input!

As a general advice, we are moving extensions off of this repo, deprecating them in favor of the java-generator.

If KubeVirt is exposing a CRD interface you can try to use it and, in case, report any issue.

**Comment by iocanel** [comment]
I am really skeptic about moving extensions off this repository as this creates more versions that needs to be aligned, more projects in the release train etc.

Can you point me to the java generator?

**Comment by manusa** [comment]
> I assume you are referring to: https://github.com/fabric8io/kubernetes-client/blob/main/doc/java-generation-from-CRD.md#java-generation-from-crd

Let me give it a spin and bootstrap something to see if it works for this use case.

**Comment by iocanel** [comment]
Maybe we could use these: https://github.com/kubevirt/kubevirt/blob/main/manifests/generated/kv-resource.yaml

**Comment by manusa** [comment]
> Maybe we could use these: https://github.com/kubevirt/kubevirt/blob/main/manifests/generated/kv-resource.yaml

That should work too.
Let me check.

**Comment by andreaTP** [comment]
Thanks for getting back @iocanel !

> I am really skeptic about moving extensions off this repository as this creates more versions that needs to be aligned, more projects in the release train etc.

I think it worked out pretty well, i.e. for the `camel-k` extension

https://github.com/apache/camel-k/blob/0c1c01d11b0c9ad8f9c7e36187999a1f9b521998/java/crds/pom.xml#L83-L97

Let me know how it goes! BTW you can try out things with a command like:

```
jbang io.fabric8:java-generator-cli:6.9.2 -u https://raw.githubusercontent.com/kubevirt/kubevirt/main/manifests/generated/kv-resource.yaml -t tmp
```

**Comment by iocanel** [comment]
> Thanks for getting back @iocanel !
> 
> > I am really skeptic about moving extensions off this repository as this creates more versions that needs to be aligned, more projects in the release train etc.
> 
> I think it worked out pretty well, i.e. for the `camel-k` extension.

Things may turn out fine for the individual extension. But what about the user that needs to combine two or more extensions that will have different version numbers from the client ? They will need a compatibility matrix that will be out of sync more often than not. For downstream projects it is hard already to keep everything aligned. Moving things outside will not make things any better.

In the old days, we kept model and client separately. It did make sense as client was way more volatile than the model that does not really change that often. It was painful to manage and people always had to figure out if the version of the dependencies are matching.

> https://github.com/apache/camel-k/blob/0c1c01d11b0c9ad8f9c7e36187999a1f9b521998/java/crds/pom.xml#L83-L97
> 
> Let me know how it goes! BTW you can try out things with a command like:
> 
> ```
> jbang io.fabric8:java-generator-cli:6.9.2 -u https://raw.githubusercontent.com/kubevirt/kubevirt/main/manifests/generated/kv-resource.yaml -t tmp
> ```

Thanks I will try it out.

**Comment by manusa** [comment]
This branch (https://github.com/manusa/kubernetes-client/tree/extension/kubevirt) contains a working module with the generated extension.

The idea is that downstream users set up their project with whatever combination of CRDs they need the same way as I did for this extension/model:

```xml
      <plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>java-generator-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <extraAnnotations>true</extraAnnotations>
          <generatedAnnotations>false</generatedAnnotations>
          <urls>
            <url>https://raw.githubusercontent.com/kubevirt/kubevirt/v1.0.1/manifests/generated/kv-resource.yaml</url>
          </urls>
          <packageOverrides>
            <io.kubevirt.v1>io.fabric8.kubevirt.v1</io.kubevirt.v1>
            <io.kubevirt.v1alpha3>io.fabric8.kubevirt.v1alpha3</io.kubevirt.v1alpha3>
          </packageOverrides>
        </configuration>
      </plugin>
```

With just a few lines of configuration you get a fully-functional model and target the exact version of the CRD you want.

> Moving things outside will not make things any better.

That's true. However, for the extensions we maintain we get the opposite problem (extensions are out of sync with the upstream project we're providing the extension for).

IMO the only good solution for this is that users actually set up their project with the java generator. This way they keep control of both, the client version and the CRD/operator/... version.

**Comment by andreaTP** [comment]
> IMO the only good solution for this is that users actually set up their project with the java generator. This way they keep control of both, the client version and the CRD/operator/... version.

Strongly agree. This way we are not on the hook for the compatibility matrix and the user is in full control, we have experimented with this approach, for example, [here](https://github.com/bf2fc6cc711aee1a0c2a/e2e-test-suite/blob/1e8a4d982b2659e74e5b60ebf0f44f746491361c/pom.xml#L325-L347).
