### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of com.fasterxml.jackson.core:jackson-databind:jar

### ISSUE THREAD

**Issue by Bing-ok** [fabric8io/kubernetes-client#5591]
## Issue description
Hi, there are multiple versions of **_com.fasterxml.jackson.core:jackson-databind_** in **_kubernetes-client-6.8.0/java-generator/core_**. As shown in the following dependency tree, according to Maven "nearest wins" strategy, only **_com.fasterxml.jackson.core:jackson-databind:2.15.2_** can be loaded, **_com.fasterxml.jackson.core:jackson-databind:2.3.2_** will be shadowed.

However, several methods defined in shadowed version **_com.fasterxml.jackson.core:jackson-databind:2.3.2_** are referenced by client project via **_io.fabric8:kubernetes-client:6.8.0_** but missing in the actually loaded version **_com.fasterxml.jackson.core:jackson-databind:2.15.2_**.

For instance, the following missing method(defined in **_com.fasterxml.jackson.core:jackson-databind:2.3.2_**) are actually referenced by **_kubernetes-client-6.8.0/java-generator/core_**, which will introduce a runtime error(i.e., "NoSuchMethodError") into **_kubernetes-client-6.8.0/java-generator/core_**.

1. **_<com.fasterxml.jackson.databind.DeserializationConfig: com.fasterxml.jackson.databind.cfg.MapperConfigBase 'with'(com.fasterxml.jackson.databind.cfg.HandlerInstantiator)>_** is invoked by **_kubernetes-client-6.8.0/java-generator/core_** via the following path:
```
path--
<io.fabric8.java.generator.FileJavaGenerator: void runOnSingleSource(java.io.File,java.io.File)> io.fabric8:java-generator-core:6.8.0;
<io.fabric8.kubernetes.client.utils.Serialization: void clinit> ();
<io.fabric8.kubernetes.client.utils.KubernetesSerialization: void init> ();
<io.fabric8.kubernetes.client.utils.KubernetesSerialization: void init> (com.fasterxml.jackson.databind.ObjectMapper,boolean);
<io.fabric8.kubernetes.client.utils.KubernetesSerialization: void configureMapper(com.fasterxml.jackson.databind.ObjectMapper)> io.fabric8:kubernetes-client-api:6.8.0;
<com.fasterxml.jackson.databind.DeserializationConfig: com.fasterxml.jackson.databind.cfg.MapperConfigBase 'with'(com.fasterxml.jackson.databind.cfg.HandlerInstantiator)>
```
## Suggested fixing solutions:
1. Change dependency **_io.fabric8:kubernetes-client_** from **_6.8.0_** to **_6.9.2_**.Because the newer version **_io.fabric8:kubernetes-client:6.9.2_** does not invoke the above missing methods, such changing cn solve the problem. And change dependency **_io.fabric8:kubernetes-model-common_** from **_6.8.0_** to **_6.9.2_**.Because the newer version **_io.fabric8:kubernetes-model-common:6.9.2_** does not invoke the above missing methods, such changing cn solve the problem.

Please let me know if the solution you agree to? I can submit a PR to fix it.

Thank you very much for your attention.
Best regards,

## Dependency tree----
<pre><code>
[INFO] |     \- org.apache.commons:commons-lang3:jar:3.12.0:test
[INFO] \- io.fabric8:mockwebserver:jar:0.2.2:test
[INFO]    +- com.squareup.okhttp3:mockwebserver:jar:3.12.12:test
[INFO]    |  +- (com.squareup.okhttp3:okhttp:jar:3.12.12:test - version managed from 3.12.12; omitted for duplicate)
[INFO]    |  \- (junit:junit:jar:4.12:test - omitted for conflict with 4.13.2)
[INFO]    +- <b>(com.fasterxml.jackson.core:jackson-databind:jar:2.15.2:test - version managed from 2.13.0; omitted for duplicate)</b>
[INFO]    \- (io.fabric8:zjsonpatch:jar:0.3.0:test - omitted for duplicate)
</code></pre>

### Fabric8 Kubernetes Client version

6.8.1

### Steps to reproduce

NULL

### Expected behavior

NULL

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
NULL
```

**Comment by shawkins** [comment]
> Please let me know if the solution you agree to? I can submit a PR to fix it.

I don't follow what is being proposed.  The expectation is that fabric8 should be used via it's bom with all versions aligned.  Only in very special circumstances would would mix fabric8 dependency versions or introduce a different version of jackson.
