### ISSUE TITLE
Is it normal that informer's WebSocket is frequently closed and reopened?

### ISSUE THREAD

**Issue by felipeek** [fabric8io/kubernetes-client#5606]
### Describe the bug

This is not necessarily a bug, but something that we noticed in our clusters (also in different cloud providers).

When we enable fabric8 debug logs, we see lots of this message:
```
{"timestamp":"2023-11-22 13:49:29,187","logLevel":"DEBUG","threadName":"OkHttp https://100.64.0.1/...","loggerName":"io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener","message":"WebSocket close received. code: 1000, reason: "}
```
followed by:
```
{"timestamp":"2023-11-22 13:48:53,846","logLevel":"DEBUG","threadName":"OkHttp https://100.64.0.1/...","loggerName":"io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener","message":"WebSocket successfully opened"} |  
```

Sometimes the WebSocket remais open for less than a second. In the last hour, the websocket was closed and reopened 82 times in one of our clusters and 54 times in the other.

Even though it keeps getting restarted, the informer is functional. However it seems odd that it keeps restarting. Is this expected? If it's not, would you have any hints for us to look for the root cause?

Thank you!

### Fabric8 Kubernetes Client version

other (please specify in additional context)

### Steps to reproduce

We have a regular informer, initialized like this:

```
this.k8sClient = new KubernetesClientBuilder().build();
this.sharedInformerFactory = this.k8sClient.informers();

[...]

this.k8sCrInformer = this.sharedInformerFactory.sharedIndexInformerFor(OurCustomResource.class, INFORMER_CACHE_RESYNC_PERIOD_MS);
this.k8sCrInformer.addEventHandler(ourCustomResourceWorker);
this.k8sCrInformer.stopped().thenRunAsync(onK8sCfcInformerStoppedAction);
```

### Expected behavior

I would expect that the websocket would remain open for more time

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Amazon, Azure, GKE

### Fabric8 Kubernetes Client Logs

```shell
{"timestamp":"2023-11-22 13:49:29,187","logLevel":"DEBUG","threadName":"OkHttp https://100.64.0.1/...","loggerName":"io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener","message":"WebSocket close received. code: 1000, reason: "}
{"timestamp":"2023-11-22 13:48:53,846","logLevel":"DEBUG","threadName":"OkHttp https://100.64.0.1/...","loggerName":"io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener","message":"WebSocket successfully opened"} |  
```

### Additional context

kubernetes-client 6.9.0

k8s server version: v1.26.7

**Comment by manusa** [comment]
> However it seems odd that it keeps restarting. Is this expected? If it's not, would you have any hints for us to look for the root cause?

It might be normal for the watcher to restart every few minutes, but not 82 times in an hour.

For some reason the websocket connection is getting closed. However, everything in the logs indicates that this is a graceful close, so it might have to do with the kind of resources you're watching.

The good thing about informers is that they are built for resiliency, so even in this extreme events everything should keep working.

Maybe @shawkins has some idea about what might be happening.

**Comment by shawkins** [comment]
> Maybe @shawkins has some idea about what might be happening.

From the client side we added a ~5-10 minute timeout to websockets (included as a timeout parameter and enforced with a scheduled task) - this was to match what kubectl does.  I'll double check with their impending switch to websockets if they will keep or increase that timeout.  Other than that if the websocket is closing that should be coming from the server side.  In particular if the api server pod or some other intermediate network issue occurs that could cause us to close the websocket.  If you could provide a larger trace log we should be able to confirm why the closures are initiated.

**Comment by felipeek** [comment]
Hi shawkins, thanks for the response. Just to confirm, you mean to enable fabric8 trace-level logs and then post here all logs that happened during the open/close?

**Comment by cr-liorholtzman** [comment]
@shawkins Have to mention that we also see this behavior at https://github.com/fabric8io/kubernetes-client/issues/5599, could it be what fails the upload?

**Comment by shawkins** [comment]
> @shawkins no the upload is a of a small file and ends after less then second..

It sounds like what you are describing is that shortly after the websocket is established that the server side is closing the websocket.  Can you provide more of a log to confirm this?
