### ISSUE TITLE
Support authentication with certificate in exec-credentials

### ISSUE THREAD

**Issue by qingboooo** [fabric8io/kubernetes-client#5608]
### Is your task related to a problem? Please describe

In class io.fabric8.kubernetes.client.Config, it is only support authenticate with token, authenticate with certificate is unsupported and marked as TODO.

Due to there is no token generated by ExecConfig and certificate is not supported yet, so all requests treat as anonymous request

`WARN    No token returned`

`Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://[server]:6443/api/v1/namespaces/sandbox/secrets. Message: secrets is forbidden: User "system:anonymous" cannot list resource "secrets" in API group "" in the namespace "sandbox". Received status: Status(apiVersion=v1, code=403, details=StatusDetails(causes=[], group=null, kind=secrets, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=secrets is forbidden: User "system:anonymous" cannot list resource "secrets" in API group "" in the namespace "sandbox", metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={}).`

### Describe the solution you'd like

Implement TODO item, add support to authenticate with certificate

### Additional context

Fabric8 Kubernetes Client version: 6.8.1

**Comment by manusa** [comment]
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#input-and-output-formats

> To use bearer token credentials, the plugin returns a token in the status of the [ExecCredential](https://kubernetes.io/docs/reference/config-api/client-authentication.v1beta1/#client-authentication-k8s-io-v1beta1-ExecCredential)
> ```json
>  {
>    "apiVersion": "client.authentication.k8s.io/v1",
>    "kind": "ExecCredential",
>    "status": {
>      "token": "my-bearer-token"
>    }
>  }
>  ```


> **Alternatively**, a PEM-encoded client certificate and key can be returned to use TLS client auth. If the plugin returns a different certificate and key on a subsequent call, k8s.io/client-go will close existing connections with the server to force a new TLS handshake.
>
> If specified, clientKeyData and clientCertificateData must both must be present
>
> ```json
> {
>   "apiVersion": "client.authentication.k8s.io/v1",
>   "kind": "ExecCredential",
>   "status": {
>     "clientCertificateData": "-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----",
>     "clientKeyData": "-----BEGIN RSA PRIVATE KEY-----\n...\n-----END RSA PRIVATE KEY-----"
>   }
> }
> ```
