### ISSUE TITLE
Support for OVN networking API (k8s.ovn.org/v1) for Openshift 4.12+

### ISSUE THREAD

**Issue by lherman-vd** [fabric8io/kubernetes-client#5636]
### Is your enhancement related to a problem? Please describe

Since OpenShift switched their recommended networking API to the OVN stack (meaning they removed the old `network.openshift.io/v1` endpoints like `network.openshift.io/v1/NetNamespaces` and `network.openshift.io/v1/EgressFirewall`) we can't use the provided DSL methods from openshift-client anymore in the clusters that have migrated to the new stack.

### Describe the solution you'd like

It'd be nice to add the `k8s.ovn.org/v1` APIs to the built-in DSL for openshift-client so that we can reference to either APIs depending on the cluster version and capabilities.

### Describe alternatives you've considered

I'm using the [typeless API](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md#resource-typeless-api) for now but it's verbose and hard to maintain.

### Additional context

API docs for OVN:
- https://docs.openshift.com/container-platform/4.12/rest_api/network_apis/network-apis-index.html
- https://docs.openshift.com/container-platform/4.12/rest_api/network_apis/egressfirewall-k8s-ovn-org-v1.html
- https://docs.openshift.com/container-platform/4.12/rest_api/network_apis/egressip-k8s-ovn-org-v1.html

**Comment by rohanKanojia** [comment]
Is this OVN API enabled in OpenShift by default? Do I have to install some operator to add these resources? I'm not able to access these on OpenShift 4.13.12 (CRC).

**Comment by lherman-vd** [comment]
Our OpenShift rep recommended us to directly enable the OVN api when we starting building a new cluster, I think the migration process for existing clusters is detailed here: https://docs.openshift.com/container-platform/4.12/networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.html

**Comment by rohanKanojia** [comment]
I see. We would need to add support for these resources. 

As a workaround, you can try generating POJOs for OVN CRDs using [Fabric8 Java Generator](https://github.com/fabric8io/kubernetes-client/blob/main/doc/java-generation-from-CRD.md)

**Comment by manusa** [comment]
> Is this OVN API enabled in OpenShift by default? Do I have to install some operator to add these resources? I'm not able to access these on OpenShift 4.13.12 (CRC).

Could you please verify if by using the cluster bot to start an OVN variant cluster these types are enabled?

**Comment by rohanKanojia** [comment]
Umm, yes I can see OVN types when  I create a cluster using cluster bot:
```
adminpolicybasedexternalroutes        apbexternalroute    k8s.ovn.org/v1                                false        AdminPolicyBasedExternalRoute
egressfirewalls                                           k8s.ovn.org/v1                                true         EgressFirewall
egressips                             eip                 k8s.ovn.org/v1                                false        EgressIP
egressqoses                                               k8s.ovn.org/v1                                true         EgressQoS
egressservices                                            k8s.ovn.org/v1                                true         EgressService

```

**Comment by rohanKanojia** [comment]
@lherman-vd : It would be nice if you could provide some early feedback now that the functionality has been merged. I've created a [demo project](https://github.com/rohankanojia-forks/fabric8-open-virtual-networking-extension-demo) showcasing OVN networking extension. 

After the nightly SNAPSHOT build, you should be able to access `k8s.ovn.org/v1` resources by adding this dependency . You would need to configure your project to use SNAPSHOTs.
User would need to add this dependency in order to use this extension:
```xml
    <dependency>
      <groupId>io.fabric8</groupId>
      <artifactId>open-virtual-networking-client</artifactId>
      <version>${fabric8.version}</version>
    </dependency>
```

Here is an example of sample usage:
```java
    try (OpenVirtualNetworkingClient ovnClient = new KubernetesClientBuilder().build().adapt(OpenVirtualNetworkingClient.class)) {
      EgressFirewall egressFirewall = new EgressFirewallBuilder()
          .withNewMetadata()
          .withName("default")
          // ...
          .build();
      egressFirewall = ovnClient.v1().egressFirewalls().resource(egressFirewall).serverSideApply();

      egressFirewall = ovnClient.v1().egressFirewalls().resource(egressFirewall).get();
      System.out.println(egressFirewall.getMetadata().getName() + " Created");
    }
```

**Comment by lherman-vd** [comment]
Apologies, I was on holiday the past few weeks. 
Thank you for working on it :tada: , I'll test the integration in our project asap.
