### ISSUE TITLE
can't create deployment when i set the resourceRequirements 

### ISSUE THREAD

**Issue by swqmaven** [fabric8io/kubernetes-client#564]
kubernetes-client version 1.4.18
kubernetes 1.4.1

can't create deployment when i set the resourceRequirements 
i used the following code:
``
Quantity cpuQuantity = new Quantity();
        cpuQuantity.setAmount("0.5");
        Quantity memoryQuantity = new Quantity();
        memoryQuantity.setAmount("100M");
        limitsRequests.put("cpu",cpuQuantity);
        limitsRequests.put("memory",memoryQuantity);
       resourceRequirements.setLimits(limitsRequests);
        resourceRequirements.setRequests(limitsRequests);
        container.setResources(resourceRequirements);
``
is the current version not support or my code error?
thanks for someone help!

**Comment by swqmaven** [comment]
the second problem:
if i set livenessProbe it can't be work! the error is port " Invalid value: \"\"  "
this is my code:
``
HTTPGetAction httpGetAction = new HTTPGetAction();
                IntOrString intOrString = new IntOrString();
                intOrString.setIntVal(Integer.valueOf(clusterConfig.getPort()));
                intOrString.setStrVal(clusterConfig.getPort());
                intOrString.setKind(1);
                httpGetAction.setPort(intOrString);
                httpGetAction.setPath(clusterConfig.getPath());
                livenessProbe.setHttpGet(httpGetAction);
``
the problem is IntOrString to set port and it does't work! the kubernets api get null value?
is the version not support or my code error ?
thanks for help

**Comment by iocanel** [comment]
Just use:
    
    IntOrString intOrString = new IntOrString(clusterConfig.getPort());

P.S: When pasting code it always help to leave empty 1 line before and after the code and also prefix each line with 4 spaces.

**Comment by iocanel** [comment]
Also, it is much more easier to use the provided builder for creating those objects.

**Comment by swqmaven** [comment]
thanks help close it .the problem is IntOrString deserialize
