### ISSUE TITLE
about jackjson convert lost some attribute value

### ISSUE THREAD

**Issue by swqmaven** [fabric8io/kubernetes-client#565]
Used jackjson convert Deployment to json is right,but json convert to Deployment  class lost some IntOrString value!!!  like : httpGetAction set port.

this is the code  deployment json convert to Deployment class lost some IntOrString value

``
"livenessProbe": {
						"exec": null,
						"failureThreshold": null,
						"httpGet": {
							"host": null,
							"httpHeaders": [],
							"path": "/healthz",
							"port": {
								"intVal": 8080,
								"kind": 0,
								"strVal": null
							},
							"scheme": null
						},
						"initialDelaySeconds": 2,
						"periodSeconds": null,
						"successThreshold": null,
						"tcpSocket": null,
						"timeoutSeconds": 30
					},
ObjectMapper mapper = new ObjectMapper();
Deployment deployment = mapper.readValue(jsonStr,Deployment.class);
``

**Comment by iocanel** [comment]
This is a duplicate for #566, so I am going to close this one as I've already commented on the other.
