### ISSUE TITLE
is a bug? about IntOrString deserialize

### ISSUE THREAD

**Issue by swqmaven** [fabric8io/kubernetes-client#566]
json convert deployment class some used IntOrString attr inner value was lost!

**Comment by swqmaven** [comment]
you just consider "port": 8080"  
This situation is not considered
``
 "\t\t\t\t\t\t\t\"port\": {\n" +
                "\t\t\t\t\t\t\t\t\"intVal\": 8080,\n" +
                "\t\t\t\t\t\t\t\t\"kind\": 0,\n" +
                "\t\t\t\t\t\t\t\t\"strVal\": 8080\n" +
                "\t\t\t\t\t\t\t},\n" +
``

**Comment by iocanel** [comment]
Even though Kubernetes internally uses a structure like this: https://github.com/kubernetes/kubernetes/blob/master/pkg/util/intstr/intstr.go#L41

I don't see it supporting the case you describe. I am no golang expert but this is what I get from:
https://github.com/kubernetes/kubernetes/blob/master/pkg/util/intstr/intstr.go#L69

Also, I've never seen a doc or an example using it, so I am assuming its an internal representation?

Can you please provide a pointer to where you found a doc or example with this use case?

**Comment by iocanel** [comment]
@jimmidyson: what do you say?

**Comment by jimmidyson** [comment]
Agree with you @iocanel. `IntOrString` is serialised to a single string attribute in JSON. The internal fields should not be present in serialized resource.

**Comment by swqmaven** [comment]
@iocanel @jimmidyson i think this kind of transformation is relatively.  you can used original model convert json and  used the same json convert model  the result is same  original model

**Comment by iocanel** [comment]
Sure, but I don't think if that you serialize the model *(using jackson)* you'll end up with this kind of json. If this is the case, then I agree its a bug.
