### ISSUE TITLE
Update base container image for model generators

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#5672]
@rohanKanojia This should be updated for the rest of the models

_Originally posted by @manusa in https://github.com/fabric8io/kubernetes-client/pull/5618#discussion_r1435145678_

**Comment by rohanKanojia** [comment]
Sorry but I don't find any references to `DOCKER_IMAGE_GOLANG` in any other place than in `generateModelDocker.sh` . Could you please elaborate what needs to be done here?

**Comment by rohanKanojia** [comment]
https://github.com/fabric8io/kubernetes-client/pull/5618#discussion_r1435147979
