### ISSUE TITLE
The v1 Version  gateway-api  not yet supported

### ISSUE THREAD

**Issue by chenylh** [fabric8io/kubernetes-client#5673]
### Describe the bug

https://github.com/kubernetes-sigs/gateway-api/tree/main/apis/v1

### Fabric8 Kubernetes Client version

6.9.2

### Steps to reproduce

https://github.com/kubernetes-sigs/gateway-api/tree/main/apis/v1

### Expected behavior

https://github.com/kubernetes-sigs/gateway-api/tree/main/apis/v1

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
https://github.com/kubernetes-sigs/gateway-api/tree/main/apis/v1
```

### Additional context

https://github.com/kubernetes-sigs/gateway-api/tree/main/apis/v1

**Comment by rohanKanojia** [comment]
We need to bump gateway-api to 1.0.0 :

https://github.com/fabric8io/kubernetes-client/blob/c550866337a7be1be24279a61f5dcf268e9366bb/kubernetes-model-generator/go.mod#L27

**Comment by chauncyAAA** [comment]
hello,[rohanKanojia](https://github.com/rohanKanojia):

How to create Kubernetes Gateway resource? Is there any examples ?
Istio ingressGateway can run IstioClient.v1beta1().gateways().
what about gateway-api?

Any pointers will be much appreciated!

**Comment by rohanKanojia** [comment]
@chauncyAAA : Are you asking about Istio's Gateway or `sigs.k8s.io` Gateway? This issue is about the latter.

**Comment by chauncyAAA** [comment]
@rohanKanojia  I am interested about sigs.k8s.io Gateway,also gateway.networking.k8s.io.Is there some way to create it?

> @chauncyAAA : Are you asking about Istio's Gateway or `sigs.k8s.io` Gateway? This issue is about the latter.

**Comment by rohanKanojia** [comment]
I have a PR open for Kubernetes 1.29.0 model upgrade https://github.com/fabric8io/kubernetes-client/pull/5686

I can bump `sigs.k8s.io` to `1.0.0` once this gets merged.

In the meantime, you can try using [`GenericKubernetesResource` API ](https://github.com/fabric8io/kubernetes-client/blob/main/doc/CHEATSHEET.md#resource-typeless-api) to manipulate unsupported resources.
