### ISSUE TITLE
use services.withName get null

### ISSUE THREAD

**Issue by swqmaven** [fabric8io/kubernetes-client#568]
my service "nginx-uszbxdhh" in default namespaces and used  the following code get null
Service service = client.services().withName("nginx-uszbxdhh").get();

**Comment by iocanel** [comment]
The default/current namespace for the client is not necessarily the one named 'default'.

The default/current namespace for the client is specified via configuration or gets detected by factors like:

- system properties
- env variables
- ~/.kube/config
- /var/run/secrets/kubernetes.io/serviceaccount/namespace

So, you should check what's the clients default namespace using: 

    client.getNamespace();

then figure out if its the correct value and how it got there. 

Last but not least you can be explicit about the namespace you want to use:

    Service service =  client.services().inNamespace("default").withName("nginx-uszbxdhh").get();

**Comment by swqmaven** [comment]
@iocanel  Thanks very much . I had found the usage mode .
