### ISSUE TITLE
Kind is `null` in for `GenericKubernetesResource` informer `ResourceEventHandler

### ISSUE THREAD

**Issue by csviri** [fabric8io/kubernetes-client#5729]
### Describe the bug

When I create an informer that uses `GenericKubernetesResource` the kind of the existing resources is `null`, sample:

```java
var informer = client.genericKubernetesResources("v1","ConfigMap").inAnyNamespace().runnableInformer(0);
        informer.addEventHandler(new ResourceEventHandler<GenericKubernetesResource>() {
            @Override
            public void onAdd(GenericKubernetesResource configMap) {
                System.out.println("config map kind "+configMap.getKind());
            }

            @Override
            public void onUpdate(GenericKubernetesResource configMap, GenericKubernetesResource t1) {
            }

            @Override
            public void onDelete(GenericKubernetesResource configMap, boolean b) {
            }
        });
        informer.start();
```
It is already `null` in cache.
It is strange that, if I create a new `ConfigMap` with the client, it gets propagated properly.

### Fabric8 Kubernetes Client version

6.10.0

### Steps to reproduce

See sample above. Try it with minikube for example.

### Expected behavior

Kind field is propagated

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
No specific logs
```

**Comment by shawkins** [comment]
@csviri the issue seems to be that off of a list operation the api server populates the list kind, but not the individual item kinds, so this would affect any generic list operation not just what the informer is using. 

When you receive an event, that's just a single resource and does have the kind populated.

We can probably workaround this by setting the kind ourselves.
