### ISSUE TITLE
Basic authentication fails with special characters in password

### ISSUE THREAD

**Issue by jpraet** [fabric8io/kubernetes-client#5781]
I am trying to connect to an OpenShift cluster with username / password. My password contains a ["£"](https://www.fileformat.info/info/unicode/char/00a3/index.htm) character.

https://github.com/fabric8io/kubernetes-client/blob/2281ae45afdad76f1d26780acc11c2497cf75bc4/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java#L121

I think maybe it should be `usernameAndPassword.getBytes(StandardCharsets.UTF_8)`?

**Comment by shawkins** [comment]
> I think maybe it should be usernameAndPassword.getBytes(StandardCharsets.UTF_8)?

Yes it probably should be - can you open a pr for that?
