### ISSUE TITLE
Cannot get pod logs withTimestamps

### ISSUE THREAD

**Issue by pmcq** [fabric8io/kubernetes-client#579]
Query parameter `timestamps` is a part of the read log operation, and PodOperationsImpl does have a variable `withTimestamps` but there is no method to set it, and parameter isn't passed in getLogParameters.

https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java#L104-L123

**Comment by CNaiko** [comment]
The latest version, still have this issue.

**Comment by rohanKanojia** [comment]
@pmcq : I see you have started working on this, I would check if I can find time to fix this. Would appreciate if you can work on this and submit a PR

**Comment by pmcq** [comment]
Not sure I understand - I had submitted https://github.com/fabric8io/kubernetes-client/pull/930 and had just been waiting around for reply, but I'm glad the issue is now closed.

**Comment by rohanKanojia** [comment]
@pmcq : I didn't test your PR on my machine(since you added tests also which were passing) and your changes seemed appropriate to me as per my knowledge of this project. Was it working for you? Or did I just merged something I wasn't supposed to ;-P .

**Comment by rohanKanojia** [comment]
@pmcq : ah, okay. You submitted two PRs #1270 and #930  for the same issue. I somehow missed that. Sorry for the noise

**Comment by pmcq** [comment]
Yeah the second PR was from a different contributor - I was just asking since I had already submitted a PR but you had asked if I could submit one.  Doesn't really matter - the important thing is the issue is closed :)
