### ISSUE TITLE
kube-api-test artifact not being published

### ISSUE THREAD

**Issue by janpetryk** [fabric8io/kubernetes-client#5819]
### Describe the bug

https://repo.maven.apache.org/maven2/io/fabric8/

In the list of fabric8 artifacts I don't see `kube-api-test` project. 

Makes it impossible to use this for testing. 

### Fabric8 Kubernetes Client version

6.10.0

### Steps to reproduce

1. I want to include `kube-api-test` in my project
2. I add the dependency of `testImplementation 'io.fabric8:kube-api-test:6.10'`
3. I get the error of 

```   
> Could not find io.fabric8:kube-api-test:6.10.
    Searched in the following locations:
       - https://repo.maven.apache.org/maven2/io/fabric8/kube-api-test/6.10/kube-api-test-6.10.pom
```

### Expected behavior

I want to be able to use `kube-api-test` outside of `kubernetes-client` project.

### Runtime

irrelevant

### Kubernetes API Server version

irrelevant

### Environment

macOS

**Comment by csviri** [comment]
@janpetryk kube api test was not released yet, I guess coming in 6.11 or 7.0

**Comment by janpetryk** [comment]
Oh, I am sorry then. I was under the impression that it was released, given it is mentioned in the main readme file.

**Comment by manusa** [comment]
https://github.com/fabric8io/kubernetes-client/pull/5711

6.11.0
Hope we can release shortly (plan was this week but it might be delayed to Monday next week)

**Comment by rohanKanojia** [comment]
It should be possible to use nightly builds though. See

**Comment by janpetryk** [comment]
@csviri @manusa @rohanKanojia 

Thank you for your replies, I didn't plan to use `kube-api-test` in the final version of the code, however I wanted to play with it a little and lack of the released artifact caught my eye. 

Issue can be closed now.
