### ISSUE TITLE
CRDGenerator: Add support for Meta-Annotations/Combined-Annotations

### ISSUE THREAD

**Issue by baloo42** [fabric8io/kubernetes-client#5823]
### Is your enhancement related to a problem? Please describe

At the moment the CRDGenerator does not support Meta-Annotations / Combined-Annotations.

### Describe the solution you'd like

A user of the CRDGenerator should be able to combine the existing CRDGenerator annotations in own annotations.
The CRDGenerator must detect those indirect usages and must generate the CRDs in the same way as it would if the CRDGenerator annotations are used directly.

### Additional context

An overview what Meta-Annotations/Combined-Annotions are can be found here:
https://dzone.com/articles/what-are-meta-annotations-in-java

Some other frameworks support such kind of a feature, too:

- Spring:
  https://docs.spring.io/spring-framework/reference/core/beans/classpath-scanning.html#beans-meta-annotations

- Jakarta Bean Validation:
  https://jakarta.ee/specifications/bean-validation/3.0/jakarta-bean-validation-spec-3.0.html#constraintsdefinitionimplementation-multipleconstraints
  https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/#section-constraint-composition
  https://www.baeldung.com/java-bean-validation-constraint-composition

**Comment by andreaTP** [comment]
Thanks for bringing this up @baloo42 !

As mentioned on the related issue:

> I would love to see a strawman on how we can leverage this feature.
If I understand the problem space correctly with meta-annotations we should be able to combine, for example, `io.fabric8.generator.annotation.Max` with `org.hibernate.validator.Max`

I'm supportive of this but we need a little design phase before starting to crunch any code.
