### ISSUE TITLE
How to set multiline human-readable string

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [fabric8io/kubernetes-client#5825]
### Is your enhancement related to a problem? Please describe

Kubernetes annotations are key value pairs, and both of the types are strings. It is possible though to use multiline string feature from yaml to apply proper formatting, that is human readable, for example:

```yaml
metadata:
  annotations:
    proxy.istio.io/config: |
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
```

I was wondering if it is possible to do the same using fabric8 kubernetes client. When we use new line `\n`, it is not displayed correctly when fetching the resource from cluster.

### Describe the solution you'd like

I would like to be able to provide a multiline string using fabric8 kubernetes client, so that the properties set using the client are human readable

**Comment by shawkins** [comment]
Yes you can use multi-line strings with the fabric8 client. It should handle valid yaml without a problem. What version of client are you using? And can you provde a full example of what you think is happening - are you creating the resource with yaml via the fabric8 client?

**Comment by manusa** [comment]
I guess that for that case you'd need to tune the KubernetesSerialization serializer settings to use scalars instead of quotes strings

**Comment by shawkins** [comment]
The reason I asked about the version of the client, is that this should happen automatically on newer versions - the logic in Snake YAML will check for the presense of an embedded newline and will instead choose a literal style.

**Comment by shawkins** [comment]
And to clarify on older versions this is just a formatting issue - the resource on the server will be the same either way.

**Comment by AleksanderBrzozowski** [comment]
> The reason I asked about the version of the client, is that this should happen automatically on newer versions - the logic in Snake YAML will check for the presense of an embedded newline and will instead choose a literal style.

So we were using old version, `6.7.2` as far as I remember. I will try with 6.10 and let know if it helps 🙂

**Comment by shawkins** [comment]
> The result is:

@AleksanderBrzozowski sorry for not following you completely. The problem is with this:

```
       .withData<String, String>(mapOf(
            "foo" to "| bar \n bar2"
        ))
```

You are trying to set the data as it would appear in the yaml, and the result is the actual string "| bar \n bar2". This is not what you want to do. You sould set the value of data to the actual string value - it's not particular to a given format.

**Comment by AleksanderBrzozowski** [comment]
Ok, this works as expected:

```
"bar\n bar2"
```

The result is:

```
data:
  foo: |-
    bar
     bar2
```

However, this doesn't:

```
"bar \n bar2"
```

and the result is:

```
data:
  foo: "bar \n bar2"
```

**Comment by shawkins** [comment]
> However, this doesn't:

Snake yaml rules are quite a bit more complicated than at first glance, so while it detects a literal style is preferred it's this code that determines what is allowable: https://github.com/snakeyaml/snakeyaml/blob/b1b4a6bcee793d1032e336d32a37dbf897d35240/src/main/java/org/yaml/snakeyaml/emitter/Emitter.java#L1113

I'd guess this is a snakeyaml bug/issue - even if you remove our logic overrides and put the default scalar style as literal that value still won't display as a literal style. Feel free to capture something upstream in snakeyaml, but this will be of low importance to fabric8 because this is stylistic and does not affect correctness.

**Comment by AleksanderBrzozowski** [comment]
Ok, so I ran some examples today, and it turns out that the [following line](https://github.com/fabric8io/kubernetes-client/blob/cd25a626372084126108f6c3f1b1012aa5f46bfc/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/OperationSupport.java#L394) is invoked:

```java
      patchForUpdate = getKubernetesSerialization().asJson(updated);
```

which uses JSON for serialization. And it turns out that the result from my local kubernetes Api server for this request body:

```
{"apiVersion":"v1","kind":"ConfigMap","metadata":{"name":"test","namespace":"default"},"data":{"foo":"foo\n bar2"}}
```

is:

```yaml
apiVersion: v1
data:
  foo: |-
    foo
     bar2
kind: ConfigMap
metadata:
  name: test
  namespace: default
```

Can you provide me an example how I can sort this out? Should I first serialize the resource using YamlMapper, and then pass it as a yaml to kubernetes client?

**Comment by shawkins** [comment]
@AleksanderBrzozowski Let me give a more of an overview of how things work.

When you interact with the fabric8 client, you do so through yaml, json, or an object model. In most instances we internally convert the incoming yaml or json into the object model representation for any further manipulation. When the fabric8 client interacts with the api server it's via json - https://kubernetes.io/docs/reference/using-api/ supports only json or protobuf serialization.

How you format incoming yaml for the fabric8 kubernetes client is up to you - as long as it's valid. How the fabric8 kubernetes client emits yaml, if you use an asYaml method, does not affect the correctness of the data, just the yaml formatting.

Does that make things clearer?

**Comment by AleksanderBrzozowski** [comment]
@shawkins Yeah, now it is clear, thanks!
Closing the issue 🙂
