### ISSUE TITLE
KubernetesMockClient no longer in this repository?

### ISSUE THREAD

**Issue by khabinov** [fabric8io/kubernetes-client#583]
Hi,

First of all, huge thanks for creating this library. In one of the projects that I'm currently working on, I'm using `kubernetes-mock` maven package to mock `KubernetesClient` class. It seems however that at some point (https://github.com/fabric8io/kubernetes-client/commit/04fbc79f42da65d082ba11b7000699d6d5d41d6c) `kubernetes-mock` source code was removed from this repository. I'm wondering if there is anything else I can use instead in my tests to mock `KubernetesClient`? Or, was `kubernetes-mock` source migrated to another repository?

Thanks in advance!

**Comment by jbridger** [comment]
Hi,

We're also wondering what to do now that the `KubernetesMockClient` has been removed.

We were on `1.4.7`, but we encountered an issue that was fixed from this pull request: https://github.com/fabric8io/kubernetes-client/pull/459/.

After that fix was merged in, no releases were made, and then the mock package was removed entirely for being obsolete.

We've spent a lot of time searching and we've not found a documented alternative.

We'd appreciate it if you could advise us on this.

**Comment by adamdougal** [comment]
Also facing the same issue, any update?!
