### ISSUE TITLE
java-generator doesn't handle all integer formats

### ISSUE THREAD

**Issue by Mawi137** [fabric8io/kubernetes-client#5857]
### Is your enhancement related to a problem? Please describe

Since version 6.9.0 there is an extra check on the integer formats, but only int32 and int64 are covered. We are using uint and uint64 in our CRDs and are unable to update the java-generator because of this limitation.

### Describe the solution you'd like

Can support for uint, unit8 ... uint64 be added to the format check?

**Comment by andreaTP** [comment]
Hi @Mawi137 and thanks for your interest in the project!

According to [the documentation](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#format) `uint` is not a supported format.

That said, from the [OpenAPI spec](https://swagger.io/docs/specification/data-models/data-types/):

> An optional format modifier serves as a hint

more specifically:

> However, format is an open value, so you can use any formats, even not those defined by the OpenAPI Specification

So I overall agree with relaxing the check.
We should remove [this exception](https://github.com/fabric8io/kubernetes-client/blob/0c80a66d10bf7096864246ce453413e0da4edbd2/java-generator/core/src/main/java/io/fabric8/java/generator/nodes/AbstractJSONSchema2Pojo.java#L160) and fallback to the same as `format == null`.
Nice to have: produce a warning in these situations.

Would you like to send a PR with the changes?

**Comment by Mawi137** [comment]
Hi

Thanks for you quick reply! 
Our CRDs are generated from Rust code which does allow unsigned integers. However, it makes more sense to follow the Kubernetes spec. So thanks for pointing out that only int32 and int64 are supported. We'll adapt it on our side.
