### ISSUE TITLE
Kube API Test dependency not resolvable

### ISSUE THREAD

**Issue by ivanchuchulski** [fabric8io/kubernetes-client#5898]
### Describe the bug

Hello, I'm trying to use the Kube API Test artifact in a project, but Maven is unable to resolve the dependency. 

I see that in the New Features section of the [release notes of **6.11.0** ](https://github.com/fabric8io/kubernetes-client/releases/tag/v6.11.0) the Kube API Test is mentioned, but nonetheless the artifact isn't available in the [Maven central repositoty](https://repo.maven.apache.org/maven2/). I've found [this issue](https://github.com/fabric8io/kubernetes-client/issues/5819) in which it was also mentioned the the feature should come in **6.11.0**.

I also tried to use the **6.12.0** version, but the same problematic behavior is observed. 

### Fabric8 Kubernetes Client version

6.12.0

### Steps to reproduce

1. Add the following dependency to a pom.xml file:
```
        <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>kube-api-test</artifactId>
            <version>6.12.0</version>
            <scope>test</scope>
        </dependency>
```
2. Run `mvn clean install`
3. The following error is observed from the command output:
```
[ERROR] Failed to execute goal on project kube-api-server-test: Could not resolve dependencies for project org.example:kube-api-server-test:jar:1.0-SNAPSHOT: Could not find artifact io.fabric8:kube-api-test:jar:
6.12.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

### Expected behavior

Dependency is downloaded and project build is successful.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Windows, other (please specify in additional context)

### Additional context

K8s version: irrelevant

**Comment by ivanchuchulski** [comment]
Hello, thank you for the fast reply! 

In the previous issue I've linked it was mentioned that somewhere you also have nightly builds I suppose from the current state of `main` branch. How those could be referenced/used?

**Comment by manusa** [comment]
Yes, I suggested that, but despite asking for feedback, apparently nobody tested the nightly build because the SNAPSHOT module isn't released either.

I'll try to merge #5898 today which should allow the nightly build pipeline to release the module in a few hours.

**Comment by manusa** [comment]
You need to add this to your project's pom.xml or m2 settings.xml
```xml
      <repositories>
        <repository>
          <id>sonatype-snapshots</id>
          <url>https://oss.sonatype.org/content/repositories/snapshots</url>
          <releases><enabled>false</enabled></releases>
          <snapshots><enabled>true</enabled></snapshots>
        </repository>
      </repositories>
```
Then, set the Kubernetes Client version to the latest SNAPSHOT ---> `6.13-SNAPSHOT`

**Comment by ivanchuchulski** [comment]
Hello, I added the settings you've mentioned, but the dependency is still not resolvable:
`[ERROR] Failed to execute goal on project kube-api-test-tryout: Could not resolve dependencies for project org.example:kube-api-test-tryout:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: io.fabric8:kube-api-test:jar:6.13-SNAPSHOT (absent): Could not find artifact io.fabric8:kube-api-test:jar:6.13-SNAPSHOT in sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]`

**Comment by rohanKanojia** [comment]
something is odd... I only see parent pom being uploaded here https://oss.sonatype.org/content/repositories/snapshots/io/fabric8/kube-api-test-parent/

**Comment by manusa** [comment]
Yes, I was worried about that.
We need to manually add the child repositories too.

**Comment by manusa** [comment]
I have just released the SNAPSHOTS manually with the updated CI pipeline fix, could you please confirm if it's working now?

**Comment by ivanchuchulski** [comment]
Yes, now I've managed to resolve it. Thank you very much!

**Comment by manusa** [comment]
Awesome, I'll try to release a 6.12.1 patch version to make the module GA.

**Comment by manusa** [comment]
https://github.com/fabric8io/kubernetes-client/releases/tag/v6.12.1
