### ISSUE TITLE
Allow generated classes to implement additional interfaces

### ISSUE THREAD

**Issue by matteriben** [fabric8io/kubernetes-client#5900]
### Is your enhancement related to a problem? Please describe

I'd like the ability to generate classes using the java-generator that are declared to implement existing interfaces, such as `ObservedGenerationAware`.

https://github.com/operator-framework/java-operator-sdk/blob/main/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/ObservedGenerationAware.java

### Describe the solution you'd like

Provide some extra configuration information to the java-generator so that it can declare a generated class to implement a given interface.

**Comment by matteriben** [comment]
PR is here: https://github.com/fabric8io/kubernetes-client/pull/5901

**Comment by csviri** [comment]
Just one remark, the automatic observed generation handling might be removed in v5, see: https://github.com/operator-framework/java-operator-sdk/issues/2329

**Comment by matteriben** [comment]
> Could you please expand on the specific use case?

This enhancement request was motivated by the `ObservedGenerationAware` interface, which allows JOSDK to handle observed generation for us automatically. I'm not aware of any other use cases for this enhancement request.

> Ideally generated classes should be as "simple" and "straightforward" as possible, have you evaluated alternatives?

That makes perfect sense, thank you for clarifying the goals.

The alternatives seemed to be modifying the generated classes, which we wanted to avoid. But it seems now the alternative may be to remove support for automatic observed generation handling.

> Just one remark, the automatic observed generation handling might be removed in v5, see: [operator-framework/java-operator-sdk#2329](https://github.com/operator-framework/java-operator-sdk/issues/2329)

If the `ObservedGenerationAware` interface is indeed going away, then I think we can drop this enhancement request.
