### ISSUE TITLE
[The situation is critical] can't close exec watch

### ISSUE THREAD

**Issue by jackloveme** [fabric8io/kubernetes-client#592]
## **version** : 1.4.16

## **code:**
ExecWatch exec = dkc.pods().withName("dmo-nginx-testnginxfan-v123u07").redirectingOutput().exec("/etc/confd/test.sh");
...........

 if (exec != null){
    exec.close();
}

## situation:

Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:57)
	at io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener.close(ExecWebSocketListener.java:107)
	at com.sohu.fanhao.DockercfgContentGenerator.main(DockercfgContentGenerator.java:222)
Caused by: java.io.IOException: closed
	at okhttp3.internal.ws.WebSocketWriter.writeControlFrameSynchronized(WebSocketWriter.java:119)
	at okhttp3.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.java:111)
	at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:168)
	at io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener.close(ExecWebSocketListener.java:104)
	... 1 more

@valdar @jstrachan @KurtStam @mikekap @christian-posta

**Comment by fanhaozzu** [comment]
。。。。。。。。

**Comment by iocanel** [comment]
It seems like its already closed for some reason. Not sure if I can make anything more out of it.

How does this: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ExecExample.java work for you?

**Comment by fanhaozzu** [comment]
i'am very confused that writer is closed.

Code:

        ExecWatch is = null;
        InputStream ist = null;
        try {
            java.io.PipedOutputStream pos = new java.io.PipedOutputStream();
            is = dkc.pods().withName("dmo-nginx-testnginxfan-v1-23u07").redirectingInput().redirectingOutput().exec("/bin/ls");
            ist = is.getOutput();

            byte[] buffer = new byte[1024];
            int len = ist.read(buffer);
            if (len != -1) {
                String str = new String(buffer, 0, len, "UTF-8");
                System.out.println(str);
            }

        } catch (IOException e) {
            System.out.println(e.getMessage());
        } finally {
            if (is != null) {
                is.close();
            }
        }

**Comment by fanhaozzu** [comment]
thank you, dear iocanel. https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ExecExample.java can't help me

**Comment by fanhaozzu** [comment]
I debug find that when read :

step 1:WebSocketCall.class : createWebSocket 
......
   while (webSocket**.readMessage**()) {
    }
.......
 public boolean **readMessage(**) {
    try {
      reader.**processNextFrame**();
      return !readerSentClose;
    } catch (IOException e) {
      readerErrorClose(e);
      return false;
    }
  }

step 3: WebSocketReader.class: **processNextFrame**
    **readHeader();**
    if (isControlFrame) {
      **readControlFrame();**
    } else {
      readMessageFrame();
    }

 private void **readControlFrame() t**hrows IOException {
    switch (opcode) {
      case OPCODE_CONTROL_CLOSE:
        frameCallback.**onClose**(code, reason);
}
step 4: RealWebSocket.class
      @Override public void **onClose(fi**nal int code, final String reason) {
        readerSentClose = true;
        replyExecutor.execute(new NamedRunnable("OkHttp %s WebSocket Close Reply", url) {
          @Override protected void execute() {
            **peerClose**(code, reason);
          }
        });
 }


  private void **peerClose**(int code, String reason) {
            if (!writerSentClose) {
      try {
        writer.**writeClose**(code, reason);
      } catch (IOException ignored) {
      }
    }

step 5: WebSocketWriter:

  public void **writeClose(**int code, String reason) throws IOException {
    synchronized (this) {
      **writeControlFrameSynchronized**(OPCODE_CONTROL_CLOSE, payload);
      writerClosed = true;
    }
  }

  private void writeControlFrameSynchronized(int opcode, Buffer payload) throws IOException {
    if (writerClosed) throw new **IOException("closed");**
}
