### ISSUE TITLE
Unable to Generate List Class for CRD using java-generator-maven-plugin

### ISSUE THREAD

**Issue by fengyinqiao** [fabric8io/kubernetes-client#5936]
### Describe the bug

Hello,

I'm using the Fabric8 Kubernetes Client (version 6.12.0) to automatically generate Java classes from a CRD. The generation process successfully creates the individual resource class (`ElasticSearch.class`), but it does not generate the corresponding list class (`ElasticSearchList.class`).

### Environment
- MacOS 13.5
- Java Version: 17
- Kubernetes Version: 1.20
- Fabric8 Kubernetes Client Version: 6.12.0

### Issue Description
When I run the Maven generation plugin (`java-generator-maven-plugin`), it only generates the `ElasticSearch.class` and not the `ElasticSearchList.class`. My Maven plugin configuration is as follows:

```xml
<!-- Maven plugin configuration here -->
<plugin>
      <groupId>io.fabric8</groupId>
      <artifactId>java-generator-maven-plugin</artifactId>
      <version>6.12.0</version>
      <executions>
	      <execution>
		      <goals>
			      <goal>generate</goal>
		      </goals>
		      <configuration>
			      <source>src/main/resources/kubernetes</source>
			      <alwaysPreserveUnknown>true</alwaysPreserveUnknown>
		      </configuration>
	      </execution>
      </executions>
</plugin>
```

### Fabric8 Kubernetes Client version

6.12.1

### Steps to reproduce

1. Configure the Maven plugin as shown above.
2. Run the Maven generation command.
3. Observe that only ElasticSearch.class is generated, not ElasticSearchList.class.

### Expected behavior

generates both the `ElasticSearch.class` and the `ElasticSearchList.class`

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

macOS

**Comment by manusa** [comment]
AFAIR we no longer generate Kubernetes Resource List objects.

You should reuse `DefaultKubernetesResourceList`-> `io.fabric8.kubernetes.api.model.KubernetesList` and the associated builder if needed.

/cc @shawkins @andreaTP

**Comment by fengyinqiao** [comment]
Can you give an example? @manusa thanks!

**Comment by rohanKanojia** [comment]
@fengyinqiao : Could you please check if this helps?

https://github.com/fabric8io/kubernetes-client/blob/eaf7cffbdda42582480b95cafd587a9ceac39ca1/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceCrudTest.java#L108-L110

**Comment by manusa** [comment]
```java
new KubernetesListBuilder()
  .addToItems(new ElasticSearchBuilder()
    // ....
    .build())
  .build()
```

```java
KubernetesResourceList<ElasticSearch> res = client.resources(ElasticSearch.class).list();
```

**Comment by fengyinqiao** [comment]
> @fengyinqiao : Could you please check if this helps?
> 
> https://github.com/fabric8io/kubernetes-client/blob/eaf7cffbdda42582480b95cafd587a9ceac39ca1/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/CustomResourceCrudTest.java#L101-L110

It does help, but is cronTabClient singleton? Whether I can use it globally after initialization, whether it has a race mode that can be used concurrently? @rohanKanojia  thanks!

**Comment by andreaTP** [comment]
From the java-generator I think we never generated the "Kubernetes Resource List".

This should be sufficient for all the use-cases I'm aware of: `client.resources(ElasticSearch.class)`

@fengyinqiao what are you trying to achieve?

**Comment by fengyinqiao** [comment]
> From the java-generator I think we never generated the "Kubernetes Resource List".
> 
> This should be sufficient for all the use-cases I'm aware of: `client.resources(ElasticSearch.class)`
> 
> @fengyinqiao what are you trying to achieve?

I am new to fabric8-k8s-client and use client-go/controller-runtime before.
```
//      List<ElasticSearch> ElasticSearchs = client.resources(ElasticSearch.class, ElasticSearch List.class).inNamespace(namespace).list().getItems();
        List<ElasticSearch> ElasticSearchs = client.resources(ElasticSearch.class).inNamespace(namespace).list().getItems();
```
I thought there was only the first way to list CR,  what‘s the difference between them?

**Comment by manusa** [comment]
There's no difference, the latter calls the former with a null parameter.

https://github.com/fabric8io/kubernetes-client/blob/25ecf8460eb132ae2945342b33f64a4240a2b91c/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java#L142

This means that the client will query the cluster to retrieve the required information such as the plural, and so on.

I'm closing this issue, since the main topic was already covered.
