### ISSUE TITLE
[EPIC] CRD-Generator v2

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#5948]
### Discussed in https://github.com/fabric8io/kubernetes-client/discussions/5942

We've decided to commit a v2 implementation of the crd generator along side the existing one so that it can be part of fabric8 6.

#### Tasks
- https://github.com/fabric8io/kubernetes-client/issues/5950
- https://github.com/fabric8io/kubernetes-client/issues/5951
- https://github.com/fabric8io/kubernetes-client/issues/5952
- https://github.com/fabric8io/kubernetes-client/issues/5944
- https://github.com/fabric8io/kubernetes-client/issues/5945

**Comment by manusa** [comment]
closing since I mistakenly duplicated it in #6616 which is no more up to date.
