### ISSUE TITLE
Align crd generator v1 and v2 output

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#5951]
The v1 output should sort the required list.

Also the v1 handling for JsonFormat shape needs to leave the type as string in most cases.

v2 will use set the printer column type to be the actual property type. v1 will continue to use string in some cases.

**Comment by matteriben** [comment]
> Also the v1 handling for JsonFormat shape needs to leave the type as string in most cases.

I think these lines in v1 need to be removed to align handling for JsonFormat shape with v2:
https://github.com/fabric8io/kubernetes-client/blob/a8fba97b2a22bf805894ec33e9982ec37e4e8a8d/crd-generator/api/src/main/java/io/fabric8/crd/generator/AbstractJsonSchema.java#L159-L162
Thank you!

**Comment by shawkins** [comment]
I believe we've addressed all known issues.
