### ISSUE TITLE
Enable parallel processing with crd-generator v2

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#5952]
The v2 generator will need to be parallized at the clazz level.

There will need to be a ResolvingContext instance for each usage - the SchemaGenerator isn't thread-safe. But they could all share the "seen" Jackson schema instances so that any common classes would not need to be re-resolved.

**Comment by baloo42** [comment]
I think this feature has already been implemented with #5949:

https://github.com/fabric8io/kubernetes-client/blob/main/crd-generator/api-v2/src/main/java/io/fabric8/crdv2/generator/CRDGenerator.java#L194

Parallel execution is also enabled by default in the maven plugin and in the CLI.

**Comment by shawkins** [comment]
@baloo42 looks like we're good to resolve this properly.
