### ISSUE TITLE
ResourceListTest.testCreateOrReplaceWithDeleteExisting flakiness

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#5953]
https://github.com/fabric8io/kubernetes-client/actions/runs/8831445429/job/24246684439?pr=5949#step:4:73186 shows a failure with 

```
ResourceListTest.testCreateOrReplaceWithDeleteExisting:178 expected: <6> but was: <7>
```

We'll need to double check if the condition should look for at least that many requests, not exactly.

**Comment by manusa** [comment]
It's been flaky for a while.

Maybe asserting the number of requests is not exactly what we want.

**Comment by shawkins** [comment]
The issue here is a race condition between stopping the reflector due to the condition being satisfied and starting the watch. If an attempt is made to start the watch you end up with a 7th request.
