### ISSUE TITLE
Ambiguity with BaseOperation createOrReplace()

### ISSUE THREAD

**Issue by sayedasadali** [fabric8io/kubernetes-client#602]
[relevant code](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java#L352-L362)

```
  @Override
  public T createOrReplace(T item) {
    if (Utils.isNullOrEmpty(name) && item instanceof HasMetadata) {
      return withName(((HasMetadata)item).getMetadata().getName()).createOrReplace(item);
    }
    if (get() == null) {
      return create(item);
    } else {
      return replace(item);
    }
  }

```
For the case of first-time creation of a resource. The `get()` here constructs a url using `getNamespacedUrl` which results in something like: `http://<kube_master>/api/v1/<resource>`. This url usually returns a `<resource>List` and the condition `get() == null` is never true!

meaning that the replace workflow is invoked. which predictably fails at a PUT on the non-existent resource.

example usage (this will fail): `client.resourceQuotas().inNamespace(namespace).load(resourceQuotaInputStream).createOrReplace(resourceQuota);`

relevant PR: #538 
kubernetes-client version tested with: v1.4.16 (however, this code hasn't been updated in the subsequent releases)

am I understanding this wrong? or will the `createOrReplace()` workflow never behave as expected?

**Comment by sayedasadali** [comment]
i ran into this once earlier and used the workaround of:
- check of existence
- if yes, replace
- else create

which is essentially what createOrReplace promises to do. I encountered this again while trying to create a workflow for another resource and wondered if this had been solved/addressed by now.

**Comment by iocanel** [comment]
For the first time creation of the resource the url will be: `http://<kube_master>/api/v1/<resource>/<name>` and will be null.

The name is either passed before createOrReplace(item) or is picked up from the item.

**Comment by jimmidyson** [comment]
@iocanel `get()` doesn't have an item at this point so name can't be taken from the passed in item. If `name` is not already set then it should be set from the passed in item before `get` is called I think.

**Comment by jimmidyson** [comment]
Or at least `name` should be checked to see if it has a value. From the above code, wondering if there's either a problem in `load` not setting the `name` correctly or if the passed in input stream doesn't have a `name` set on the resource?

**Comment by iocanel** [comment]
@jimmidyson: We do check if name is null and try to get it from the item:

     if (Utils.isNullOrEmpty(name) && item instanceof HasMetadata) {
          return withName(((HasMetadata)item).getMetadata().getName()).createOrReplace(item);
     }

**Comment by jimmidyson** [comment]
Ah but we don't check if the item has a name...

**Comment by sayedasadali** [comment]
in my observation:
`client.resourceQuotas().inNamespace(namespace).withName(resourceQuotaName).createOrReplace(resourceQuota);` succeeds.

however, `client.resourceQuotas().inNamespace(namespace).createOrReplace(resourceQuota);` fails. even though the `resourceQuotaName` is present in the resource object

**Comment by jimmidyson** [comment]
That is different from the original issue (you used load in the original example) & now that makes more sense.

@iocanel That DSL looks valid, right? We should use the name from the passed in resource if none is already set.

**Comment by jimmidyson** [comment]
OK thanks for the update @sayedasadali. Problem is in load - see https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/BaseOperation.java#L254 & precisely the `getName()` call in the constructor. Need to unmarshal & use the name from the unmarshaled resource.

**Comment by sayedasadali** [comment]
the unmarshaling problem explains the behavior I reported
Thanks @jimmidyson and @iocanel for taking a look at this
