### ISSUE TITLE
Leader election unrecoverable after Readiness probe failed

### ISSUE THREAD

**Issue by tagorenathv** [fabric8io/kubernetes-client#6020]
### Describe the bug

We are using LeaderElection with java-spring-boot-3 using Fabric8 client. 
Recently, we encountered issue as no active leader for this lease as well as no leader election invoked. 
On investigation we found Readiness probe failed log:

> Request to probe app failed: Get "http://10.44.x.x:8080/healthcheck": context deadline exceeded (Client.Timeout exceeded while awaiting headers), original URL path = /app-health/xxxx/readyz

After this, holderIdentity is marked as `''` and leaseDurationSeconds became `1` from 15.

Is this behaviour is caused due to Fabric8 client ?
Any possibility for recovering in these cases ?

### Fabric8 Kubernetes Client version

6.9.2

### Steps to reproduce

Code used for leader election process invoke:

```
@PostConstruct
  public void initLeaderElection() {
    try {
      if (!useLeaderElection) {
        log.info("useLeaderElection is disabled");
        return;
      }

      client = new KubernetesClientBuilder().build();
      runLeaderElectionProcess();
    } catch (Exception e) {
      log.error("Exception during leader election initialization: {}", e.getMessage(), e);
    }
  }

  private void runLeaderElectionProcess() {
    try {
      String namespace = Optional.ofNullable(client.getNamespace()).orElse(defaultNamespace);
      String identity = Optional.ofNullable(System.getenv("HOSTNAME"))
          .orElse(UUID.randomUUID().toString());

      if (identity == null || identity.isEmpty()) {
        throw new IllegalStateException("HOSTNAME environment variable must be set");
      }

      appContext.setIdentity(identity);

      log.info(
          "Starting leader election for namespace: {}, role: {}, identity: {}",
          namespace,
          leaderRole,
          identity);
      var leaderElector =
          client
              .leaderElector()
              .withConfig(
                  new LeaderElectionConfigBuilder()
                      .withName(leaderRole)
                      .withLeaseDuration(Duration.ofSeconds(15L))
                      .withLock(new LeaseLock(namespace, leaderRole, identity))
                      .withRenewDeadline(Duration.ofSeconds(10L))
                      .withRetryPeriod(Duration.ofSeconds(2L))
                      .withReleaseOnCancel()
                      .withLeaderCallbacks(
                          new LeaderCallbacks(
                              () -> {
                                log.info("{} started leading", identity);
                                appContext.setLeader(true);
                              },
                              () -> {
                                log.info("{} stopped leading", identity);
                                appContext.setLeader(false);
                              },
                              newLeader -> {
                                log.info("New leader is: {}", newLeader);
                                appContext.setLeader(identity.equals(newLeader));
                              }))
                      .build())
              .build();

      CompletableFuture<?> future = leaderElector.start();
      future
          .thenRun(() -> log.info("Leader election completed"))
          .exceptionally(
              e -> {
                log.error("Leader election process failed", e);
                return null;
              });

    } catch (Exception e) {
      log.error("Exception during leader election process: {}", e.getMessage(), e);
      throw e;
    }
  }

```

### Expected behavior

Leader election process should auto-recovers on any case. 
Should not allow null or empty holderIdentity.

### Runtime

Kubernetes (vanilla), other (please specify in additional context)

### Kubernetes API Server version

1.24

### Environment

other (please specify in additional context)

### Fabric8 Kubernetes Client Logs

```shell
2024-05-22 13:56:24 Request to probe app failed: Get "http://10.44.xx.xxx:8080/healthcheck": context deadline exceeded (Client.Timeout exceeded while awaiting headers), original URL path = /app-health/xxxx/readyz
2024-05-22 13:56:24 New leader is: 
2024-05-22 13:56:24 xxxx-<node-id>-<pod-short-code> stopped leading
2024-05-22 13:56:24 Leader election completed
```

### Additional context

GCP GKS cluster

**Comment by shawkins** [comment]
What you are seeing should come from releaseOnCancel. If the leader elector is leading at the time it is shutdown, then it will release the lock by setting an empty leader and short duration (this matches the go client behavior).

> Any possibility for recovering in these cases ?

Having an empty leader should not prevent new leaders from being elected. 

The basic lifecylce of a leaderElector currently is 1 leadership only - #5635

**Comment by tagorenathv** [comment]
@shawkins Thank you for referring to [releaseOnCancel](https://github.com/fabric8io/kubernetes-client/blob/0f6c696509935a6a86fdb4620caea023d8e680f1/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extended/leaderelection/LeaderElector.java#L124). Now I got it why we have empty holderIdentity & leaseDurationSeconds to 1 as per [this](https://github.com/fabric8io/kubernetes-client/blob/0f6c696509935a6a86fdb4620caea023d8e680f1/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/extended/leaderelection/LeaderElector.java#L147-L163) code.

However, There is only 1 pod running/participating, and it was leader for a long while. When readiness probe fail occurred, as per above code i assume it released leader lock. Further no logs that states leader election process triggered. 
On service restart, again leader election triggered and this time new pod got lock and became leader. 

So this behaviour of no leader election trigger post canceling is as expected ?

**Comment by shawkins** [comment]
> So this behaviour of no leader election trigger post canceling is as expected ?

Yes that is expected when releaseOnCancel is set. It allows for another elector to quickly take over.

**Comment by tagorenathv** [comment]
Could you please confirm below understanding:

If there is no releaseOnCancel set, then pod will continue participating in election process as usual even on cancel. 
Then our case would have solved in next cycle (say 15sec as per our config) ?

If yes, any further downsides of not setting releaseOnCancel ?

**Comment by shawkins** [comment]
> If there is no releaseOnCancel set, then pod will continue participating in election process as usual even on cancel.

No, cancelling means the elector will stop trying to obtain the lease. 

If you don't set releaseOnCancel and the leader elector owning the lease is shutdown, then the lease will remain held by the old owner until the duration is up.

**Comment by tagorenathv** [comment]
ah Ok. Back to my main question, why further leader election is not triggered? 
Ideally, the client should continue participating in the election process (auto recover) correct?

Example Scenario:
- When a pod releases the lease (due to cancellation or other reasons), it should wait for a short period (e.g., a few seconds) and then attempt to re-acquire the lease.
- If the attempt to acquire the lease fails due to a network issue or a temporary API server unavailability, the process should wait for a predefined retry period and then try again.

Benefits:
- Ensuring continuous participation in the leader election process improves the reliability and availability of the leader election mechanism.
- It prevents scenarios where no pod holds the leadership, which can lead to service disruption.

**Comment by shawkins** [comment]
> why further leader election is not triggered?

Once cancelled, the leader elector does not attempt to reaquire the lease. You have to create a new leader elector.

**Comment by tagorenathv** [comment]
QQ. Mentioning logs I attached to the issue:
> 2024-05-22 13:56:24 Request to probe app failed: Get "http://10.44.xx.xxx:8080/healthcheck": context deadline exceeded (Client.Timeout exceeded while awaiting headers), original URL path = /app-health/xxxx/readyz
2024-05-22 13:56:24 New leader is: 
2024-05-22 13:56:24 xxxx-<node-id>-<pod-short-code> stopped leading
2024-05-22 13:56:24 Leader election completed

We got the log: `Leader election completed` but not `Leader election process failed`

So, with the existing code, we didn't get any exceptions. Rather thread closed gracefully.
Is there an existing way to differentiate cancel case or case that explains that we need to create a new leader elector?

**Comment by shawkins** [comment]
The sample code you have above doesn't show the usage of future.cancel() - that is where you should know that it's the cancel case.

> or case that explains that we need to create a new leader elector?

You can consider using future.onComplete - anytime the start future completes, but you want to keep an elector running you start another one.
