### ISSUE TITLE
kubectl get apps -A equivalent

### ISSUE THREAD

**Issue by kakliniew** [fabric8io/kubernetes-client#6021]
Hello,

I want to get all apps in cluster in any namespace and find ones with specified name and then return namespaces of those apps, but Im unable using this library. Is it even possible?

```java
kubectl get apps -A -o json | jq -r '.items[].metadata | select(.name==\""  + appName + "\") | .namespace'
```
Apps are deployed using helm install or rancher install

~~My second problem is that I need to find services and get ports of those services (namespace set and service name too)~~
Edit: managed to solve:
```
client.services().inNamespace("namespace").withName("name").get().getSpec().getPorts()
```

**Comment by shawkins** [comment]
apps is the name of a custom resource type?

If you have a class representation you can get all of the resources using:

client.inAnyNamespace().resouces(Apps.class) - then operate over the returned list

If you don't have a class representation you can use the generic / dynamic form:

client.inAnyNamespace().genericKubernetesResources(apiVersion, "apps") - then operate over the returned list

> -My second problem is that I need to find services and get ports of those services (namespace set and service name too)-
client.services().inNamespace("namespace").withName("name").get().getSpec().getPorts()

What you are showing seems fine. What problem are you having?

**Comment by kakliniew** [comment]
Thank you! Will try it tomorrow. 

The second problem I managed to solve. I have crossed out the question and given the solution, in case anyone is looking for it in the future.

**Comment by kakliniew** [comment]
solved:
```
client.genericKubernetesResources("catalog.cattle.io/v1", "App").inAnyNamespace().list().getItems()
					.forEach(app -> {
						if(appName.equals(app.getMetadata().getName())){
							foundNamespaces.add(new ArrayList<String>() {{
								add(cluster);
								add(app.getMetadata().getNamespace());
							}});
						}
				});
```
