### ISSUE TITLE
Watcher.eventReceived is still called after Watch.close

### ISSUE THREAD

**Issue by lonly-banlangen** [fabric8io/kubernetes-client#6031]
### Describe the bug

I use `Resource.watch` to bind watcher and watch.
then I call `Watch.close` to stop watch, and edit the resource.
finally `Watcher.eventReceived` is been called, the action is modified, maybe watch envent is continue, not stoped

code is:
```
Resource<ConfigMap> resource = client.inNamespace(xxx)
                .configMaps()
                .withName(xxx);
watch = resource.watch(watcher);

# other thread to stop the watch
watch.close()
```

### Fabric8 Kubernetes Client version

5.12.4

### Steps to reproduce

it's alwayse happend after `Watch.close` has been called

**Kubernetes Version**
`1.22.1`

**Java Version**
Java 8

### Expected behavior

`Watcher.eventReceived` should not be called

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

**Comment by lonly-banlangen** [comment]
> Please use a more recent release, I believe this was already addressed.

Which version solves this problem?

**Comment by shawkins** [comment]
At first glance I don't see an issue title directly matching. You should try upgrading to the latest release possible.

**Comment by lonly-banlangen** [comment]
thanks

**Comment by lonly-banlangen** [comment]
After test, the version `6.7.0` is OK
