### ISSUE TITLE
Conflict Error with serverSideApply() and Differences with kubectl

### ISSUE THREAD

**Issue by fengyinqiao** [fabric8io/kubernetes-client#6047]
### Title:
Conflict Error with serverSideApply() and Differences with kubectl

### Body:
**Environment:**
- Kubernetes version: 1.22
- Fabric8 Kubernetes Client version: 6.9.2
- Java version: 17

**Description:**
I am encountering an issue when using the `serverSideApply()` method from the fabric8 Kubernetes client to update Kubernetes resources, where it leads to a conflict error. This error does not occur when using `kubectl apply` with or without the `--server-side=true` flag. The error message is as follows:

```plaintext
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://xxx:6443/apis/elasticsearch.k8s.elastic.co/v1/namespaces/elastic-system/elasticsearches/temp-680?fieldManager=fabric8. Message: Apply failed with 1 conflict: conflict with "elastic-operator" using elasticsearch.k8s.elastic.co/v1: .spec.nodeSets. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[StatusCause(field=.spec.nodeSets, message=conflict with "elastic-operator" using elasticsearch.k8s.elastic.co/v1, reason=FieldManagerConflict, additionalProperties={})], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Apply failed with 1 conflict: conflict with "elastic-operator" using elasticsearch.k8s.elastic.co/v1: .spec.nodeSets, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict, status=Failure, additionalProperties={}).
```

**Code Snippet:**
```java
HasMetadata applied = client.resource(resource).serverSideApply();
```

Interestingly, using the following `kubectl` commands works without any issues:
```bash
kubectl apply --server-side=true -f xxx.yaml
kubectl apply -f xxx.yaml
```

Additionally, setting `forceConflicts()` in the fabric8 client resolves the issue:
```java
HasMetadata applied = client.resource(resource).forceConflicts().serverSideApply();
```

**Issue:**
It's unclear why the fabric8 client's default behavior differs from `kubectl`, where `--force-conflicts` defaults to `false`. This inconsistency leads to unexpected errors and behavior differences when migrating scripts or automations from `kubectl` to the fabric8 client.

**Expected Behavior:**
The fabric8 client's `serverSideApply()` should handle conflicts in a manner consistent with `kubectl`, or the differences should be clearly documented to guide developers on handling such situations.

**Steps to Reproduce:**
1. Use `serverSideApply()` to update a resource that may have a potential conflict.
2. Observe the error.
3. Compare with `kubectl apply --server-side=true` and `kubectl apply`.

**Proposed Solution or Question:**
Could the fabric8 team provide insights into this discrepancy? Is there a plan to align the fabric8 client's behavior with `kubectl` or a workaround that should be implemented for handling conflicts?

### Fabric8 Kubernetes Client version

6.9.2

### Steps to reproduce

1. Use `serverSideApply()` to update a resource that may have a potential conflict.
2. Observe the error.
3. Compare with `kubectl apply --server-side=true` and `kubectl apply`.

### Expected behavior

The fabric8 client's `serverSideApply()` should handle conflicts in a manner consistent with `kubectl`, or the differences should be clearly documented to guide developers on handling such situations.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux, macOS

### Fabric8 Kubernetes Client Logs

```shell
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://xxx:6443/apis/elasticsearch.k8s.elastic.co/v1/namespaces/elastic-system/elasticsearches/temp-680?fieldManager=fabric8. Message: Apply failed with 1 conflict: conflict with "elastic-operator" using elasticsearch.k8s.elastic.co/v1: .spec.nodeSets. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[StatusCause(field=.spec.nodeSets, message=conflict with "elastic-operator" using elasticsearch.k8s.elastic.co/v1, reason=FieldManagerConflict, additionalProperties={})], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Apply failed with 1 conflict: conflict with "elastic-operator" using elasticsearch.k8s.elastic.co/v1: .spec.nodeSets, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Conflict, status=Failure, additionalProperties={}).
```

**Comment by shawkins** [comment]
@fengyinqiao the fabric8 behavior here looks correct.

```
kubectl apply --server-side=true -f xxx.yaml
kubectl apply -f xxx.yaml
```

If the first command created the resource, the field manager will be kubectl, so there will be no conflict when doing the next apply.

> Additionally, setting forceConflicts() in the fabric8 client resolves the issue:

This is expected. The error message is telling you that you are trying to assume ownership of a field that already has a manager:

```
Apply failed with 1 conflict: conflict with "elastic-operator" using elasticsearch.k8s.elastic.co/v1: .spec.nodeSets
```
