### ISSUE TITLE
Retry in watch operations

### ISSUE THREAD

**Issue by KaanSimsek** [fabric8io/kubernetes-client#6055]
### Is your enhancement related to a problem? Please describe

I have a watch operation for a crd. I am currently trying to enable retry in watch so when action fails it will retry. For example when an modified event came and something went wrong I want watcher to retry. But it does not. Are there any ways to do this currently?

### Describe the solution you'd like

I dont have a solution

**Comment by shawkins** [comment]
There is nothing built-in to the fabric8 client. There are several frameworks, or just the use of a work queue that could help you do this. Also the java operator SDK does have retry built-in.
