### ISSUE TITLE
Add support for `v1.APIVersions` in KubernetesClient

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#6066]
### Is your task related to a problem? Please describe

I bumped into this issue while writing tests for https://github.com/eclipse-jkube/jkube/issues/2663 where I use KubernetesMockServer via Helm CLI.

Kubernetes APIServer provides an endpoint to allow clients to discover the API at `/api` which is the root path of the legacy v1 API.

I'm not able to see any support in KubernetesClient for achieving this. [APIVersions](https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/types.go#L1067) object is also absent from Kubernetes Model

### Describe the solution you'd like

- [ ] APIVersions resource is added to Kubenetes Model
- [ ] Support for `/api` endpoint is added to KubernetesClient DSL 

### Describe alternatives you've considered

I'm using raw JSON string at the moment as a workaround that's a bit ugly.

**Comment by manusa** [comment]
We do have logic in place for `/apis` (`APIGroupList`, `APIGroup`).

And also for `/api/v1` -or any other version- (`APIResourceList`, `APIResource`).

See `getApiGroups` and `getApiResources`.

Can you please elaborate on the use-case of this or on why it's specifically needed.

**Comment by rohanKanojia** [comment]
`/api/v1` returns a APIResourceList just like `/apis/{group}/{version}`

`/api` endpoint is different as it allows clients to discover the API server. It's used by `kubectl` and `helm` CLI before making any request.
