### ISSUE TITLE
 Issue with fabric8 client version 6.12.1 failing on Permissions

### ISSUE THREAD

**Issue by alonir** [fabric8io/kubernetes-client#6075]
### Describe the bug

Hi,

Getting the below error on fabric 8 client version 6.12.1

talog.environment.OCPClient","applicationName":"XXX","message":"KC error messages 
{401=Unauthorized! Configured service account doesn't have access. Service account may have been revoked., 403=Forbidden!Configured service account doesn't have access. Service account may have been revoked.} ","exception":""}

When downgrading the fabric8 client version to 6.4.1 it worked

it is using the below kubernetes client/server version on Azure.

Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.7", GitCommit:"07a61d861519c45ef5c89bc22dda289328f29343", GitTreeState:"clean", BuildDate:"2023-10-18T11:42:32Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.9", GitCommit:"587f5fe8a69b0d15b578eaf478f009247d1c5d47", GitTreeState:"clean", BuildDate:"2024-04-17T00:10:39Z", GoVersion:"go1.21.9", Compiler:"gc", Platform:"linux/amd64"}

### Fabric8 Kubernetes Client version

SNAPSHOT

### Steps to reproduce

Use fabric8 client version 6.12.1.

### Expected behavior

Should work as on 6.4.1 version 

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Azure

**Comment by rohanKanojia** [comment]
>  Configured service account doesn't have access. 

@alonir : Are you running this code inside a Pod? It could be possible that you haven't configured it properly to have required permissions.

**Comment by alonir** [comment]
Yes i am running inside the pod.
i am using rolebinding with roleRef
roleRef:
  kind: ClusterRole
  name: edit

I tried also to create my own Role with all needed permissions but it didn't work.
Pay attention that once I rolled down to 6.4.1 version without any other change it worked.

**Comment by rohanKanojia** [comment]
> Pay attention that once I rolled down to 6.4.1 version without any other change it worked.

@alonir : that's strange, I tried with latest version of KubernetesClient and was able to run code inside pod , I used [this demo project](https://github.com/rohanKanojia/kubernetes-client-inside-pod) for testing.

**Comment by alonir** [comment]
its not failing on all environments  worked on OCP/AWS, it failed only on azure , i wasn't able to isolate the problem.

**Comment by rohanKanojia** [comment]
@alonir : Is it possible to share more details? It's highly likely that ServiceAccount isn't configured with correct Role. Is it possible to share YAML for the ClusterRole that's bound to the ServiceAccount

**Comment by rohanKanojia** [comment]
@alonir : I checked again with my [reproducer](https://github.com/rohanKanojia/kubernetes-client-inside-pod) project by configuring a Role, RoleBinding, and ServiceAccount I was able to run KubernetesClient inside KubernetesCluster with expected permissions. I used KubernetesClient v6.12.1 and v6.13.0 but both produced the same result.

Could you please check again whether this issue is specific to KubernetesClient or some configuration error in your Kubernetes environment? Would it be possible for you to share a minimal reproducible example for your problem with us? Or maybe you can try deploying my reproducer and see if it reproduces your issue?
