### ISSUE TITLE
Pod uid not set as specified when creating it with Kubernetes Mock Server 

### ISSUE THREAD

**Issue by Goshoy** [fabric8io/kubernetes-client#6095]
### Describe the bug

Hi,

I am using io.fabric8.kubernetes.client.server.mock.KubernetesServer in CRUD mode. When I try to create a Pod using the KubernetesClient from the server and specify uid for the pod it is not taken into account and different one is assigned.

I am not completely sure if this is possible to work at all, so my question is if this is expected to work? If setting random uids is possible I would highly appreciate a little help to find what I am missing.

I am using version 6.13.0 of kubernetes-server-mock.

Best Regards,
Georgi

### Fabric8 Kubernetes Client version

SNAPSHOT

### Steps to reproduce

First create server and obtain the client:
KubernetesServer kubernetesServer = new KubernetesServer(false, true);
KubernetesClient kubernetesClient = kubernetesServer.getKubernetesClient();

Then using the client try to create a Pod:
kubernetesClient.pods().inNamespace("test").resource(newPodBuilder().withNewMetadata().withName("test").withUid("someUid").endMetadata().build()).create();

Check the pods to see that the uid of the pod is not set to "someUid":
System.out.println(kubernetesClient.pods().list());

### Expected behavior

The created Pod to have as uid the specified one.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

macOS

**Comment by manusa** [comment]
> When I try to create a Pod using the KubernetesClient from the server and specify uid for the pod it is not taken into account and different one is assigned.

This won't work, the MockWebServer's CrudDispatcher takes care of assigning a random uid when the resource is created (overriding any value you might have provided).

I haven't checked, but I assume this is the exact same behavior as the real Kubernetes API server has.

Why would you need to set a manual Uid (especially in CRUD mode)?

If you need this, then you can always use the expectation mode, but it would be better to know exactly what your use case is.
