### ISSUE TITLE
Model getters have different annotations than fields (breaks native)

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#6098]
There are still some methods that are not annotated like in `io.fabric8.kubernetes.api.model.ObjectMeta` (annotations, labels):

```java
    @JsonProperty("annotations")
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Map<String, String> annotations = new LinkedHashMap<String, String>();

    @JsonProperty("annotations")
    public Map<String, String> getAnnotations() {
        return annotations;
    }

    @JsonProperty("annotations")
    public void setAnnotations(Map<String, String> annotations) {
        this.annotations = annotations;
    }
```

_Originally posted by @jorsol in https://github.com/fabric8io/kubernetes-client/issues/6086#issuecomment-2202693436_

**Comment by manusa** [comment]
OK, this has to do with the [Fabric8DefaultRule](https://github.com/fabric8io/kubernetes-client/blob/25ecf8460eb132ae2945342b33f64a4240a2b91c/kubernetes-model-generator/kubernetes-model-jsonschema2pojo/src/main/java/io/fabric8/kubernetes/jsonschema2pojo/Fabric8DefaultRule.java) which should really extend a different Rule. `DefaultRule` should be used to provide default values for fields and not to annotate fields.

Logic in this class should be moved to `KubernetesCoreTypeAnnotator` inside the propertyField method: 

https://github.com/fabric8io/kubernetes-client/blob/5136bb073f56c0edc70e1057f6fed933f6eea0d9/kubernetes-model-generator/kubernetes-model-jsonschema2pojo/src/main/java/io/fabric8/kubernetes/jsonschema2pojo/KubernetesCoreTypeAnnotator.java#L222

**Comment by jorsol** [comment]
It seems to be affected by the same but the `overhead` (which was the reported issue on Quarkus https://github.com/quarkusio/quarkus/issues/39934) still misses the annotation:
https://github.com/fabric8io/kubernetes-client/blob/409be3b32de4f0f7d74d99186b4df98c042d0132/kubernetes-model-generator/kubernetes-model-core/src/generated/java/io/fabric8/kubernetes/api/model/PodSpec.java#L416-L419

**Comment by manusa** [comment]
Oh dear, I thought I checked that field specifically :facepalm: :facepalm: :facepalm: :facepalm: :facepalm:.
