### ISSUE TITLE
Issuing exec with OpenShiftClient causes 406: Not Acceptable.

### ISSUE THREAD

**Issue by amisevsk** [fabric8io/kubernetes-client#610]
Hello, I've got an issue with trying to execute a command in a pod. 

Trying to call `exec()` with `OpenShiftClient` causes a `KubernetesClientException` with message "406: Not Acceptable". Doing the same with `KubernetesClient` works correctly.

It looks like it's due to `OpenShiftOAuthInterceptor` adding `"Accept: application/json"` as a header to all API requests, while OpenShift `exec` does not return json. Changing [the relevant line](https://github.com/fabric8io/kubernetes-client/blob/5f5e6ec69ad6c3cb7a9cbf38db5f8680fdddc794/openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftOAuthInterceptor.java#L57) to `builder.header("Accept", "*/*");` or removing it altogether causes exec to work as expected.

The problem can be reproduced by replacing `KubernetesClient` with `OpenShiftClient` in [ExecExample.java](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ExecExample.java).

**Comment by jimmidyson** [comment]
How ironic that that bug in itself is, um, not acceptable.

Would you be able to send in a PR? We need to test whether the lack of the `Accept: application/json` header causes any issues. Can't think of any so would prefer to just remove it, or at least check if it's already set before overwriting it perhaps?

**Comment by amisevsk** [comment]
I'll write up a quick PR for testing when I have a moment. As far as I know, the kubernetes-generated request does not have an accept header set, so checking before will not work, but I'll double check.

**Comment by jimmidyson** [comment]
Thanks! I can't remember now why the accept header is explicitly added here, not sure it's required. 

However, if it is required for exec as you detailed, then we can add the header in exec & then we will be able to check it here, if needed? In fact, perhaps we should remove it from here, set it in the base request & override as required eg in exec request?

**Comment by amisevsk** [comment]
Looking at it now, I see two fairly easy options:

1. Add `Accept: */*` to [`PodOperationsImpl#exec()`](https://github.com/fabric8io/kubernetes-client/blob/5f5e6ec69ad6c3cb7a9cbf38db5f8680fdddc794/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java#L172), and check for existing Accept header in `OpenShiftOAuthInterceptor`. 

2. Don't add accept header in `OpenShiftOAuthInterceptor`, or add `Accept: application/json, */*` instead. This should prevent all 406 responses, while still behaving as before for non-problem cases.

Option 1 has the advantage of being a small scope change and easier to test, at the expense of feeling like a bit of a band-aid. This issue could occur with other requests that don't return json, but I'm not familiar enough to say if this is a concern.

Option 2 would require more testing to make sure this doesn't break anything else, but would solve the issue for any calls that don't produce json. It also does not affect the KubernetesClient implementation, whereas Option 1 makes most of its changes there.

What do you think? Is one of these preferable over the other? I'm leaning towards 2) mostly because it seems to me like the purpose of `OpenShiftOAuthInterceptor` is to deal with OpenShift authentication, so I'm not clear on why the addition of the header is necessary. The OpenShift docs don't mention it as a requirement, as far as I can tell.

**Comment by iocanel** [comment]
I prefer option 2.

I think that our release frequency gives us flexibility here.

**Comment by jimmidyson** [comment]
Agreed option 2, no need for that header to be added at all AFAIK.

**Comment by amisevsk** [comment]
Closing, fixed in PR #616
