### ISSUE TITLE
io.fabric8.kubernetes-client:version6.13.0 io.sundr.builder-annotations:version0.103.1

### ISSUE THREAD

**Issue by mafei-github** [fabric8io/kubernetes-client#6103]
```
java: java.lang.IllegalStateException: No template renderer found for:jar:file:/D:/Maven/apache-maven-3.8.5/conf/repository/io/fabric8/kubernetes-model-gatewayapi/6.13.0/kubernetes-model-gatewayapi-6.13.0.jar!/manifest.vm
java.lang.RuntimeException: java.lang.IllegalStateException: No template renderer found for:jar:file:/D:/Maven/apache-maven-3.8.5/conf/repository/io/fabric8/kubernetes-model-gatewayapi/6.13.0/kubernetes-model-gatewayapi-6.13.0.jar!/manifest.vm
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:239)
	at org.jetbrains.jps.javac.ExternalJavacProcess.compile(ExternalJavacProcess.java:189)
	at org.jetbrains.jps.javac.ExternalJavacProcess.access$400(ExternalJavacProcess.java:28)
	at org.jetbrains.jps.javac.ExternalJavacProcess$CompilationRequestsHandler$1.run(ExternalJavacProcess.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalStateException: No template renderer found for:jar:file:/D:/Maven/apache-maven-3.8.5/conf/repository/io/fabric8/kubernetes-model-gatewayapi/6.13.0/kubernetes-model-gatewayapi-6.13.0.jar!/manifest.vm
	at io.sundr.transform.internal.TemplateTransformationProcessor.lambda$process$0(TemplateTransformationProcessor.java:141)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.sundr.transform.internal.TemplateTransformationProcessor.process(TemplateTransformationProcessor.java:141)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 9 more
```

**Comment by manusa** [comment]
Could you share more details about your project?

It might be that your jar archive is corrupt or your project is having trouble loading it.
The mentioned resource does exist in the officially released artifact: https://repo1.maven.org/maven2/io/fabric8/kubernetes-model-gatewayapi/6.13.0/kubernetes-model-gatewayapi-6.13.0.jar

**Comment by manusa** [comment]
This is used to generate the `META-INF/services/io.fabric8.kubernetes.api.model.KubernetesResource` file at the Kubernetes Client compile time.

It's not necessary for downstream usage. If you are using the Kubernetes Client in your project, then this is not a required resource
From your screenshot, I'm completely confused about what you're trying to do. For some reason it looks like if you're actually recompiling the Kubernetes Client project.

**Comment by mafei-github** [comment]
1:
![图片](https://github.com/fabric8io/kubernetes-client/assets/174586581/6520e1ca-facf-45d6-b965-5e0bd9ce6e55)
2:
![图片](https://github.com/fabric8io/kubernetes-client/assets/174586581/3c81f175-e9e6-450e-a1e5-282924f5c653)
Are these two steps the way to use Java to access Volcano? 
How to create a pod inside a container?

**Comment by mafei-github** [comment]
![图片](https://github.com/fabric8io/kubernetes-client/assets/174586581/fbd68306-8dbf-4d62-a4a7-0a44fd081b6e)
![图片](https://github.com/fabric8io/kubernetes-client/assets/174586581/7a57040b-52da-4f49-8780-0f7d700f2a06)
This is a pod created before, it is possible
![图片](https://github.com/fabric8io/kubernetes-client/assets/174586581/1be765bf-917b-4ad7-b821-395709db33b0)
![图片](https://github.com/fabric8io/kubernetes-client/assets/174586581/b402e1b4-987f-47b3-93d4-c91a5f57445a)
![图片](https://github.com/fabric8io/kubernetes-client/assets/174586581/0ea5766d-b7ca-4005-9e1a-bfd43e293cc7)
May I ask why this cannot inherit the client's IP and port

**Comment by manusa** [comment]
That code is sort of deprecated.

The way you should instantiate your client for Volcano (or any other extension or model type) is by:
```java
try (
  KubernetesClient kc = new KubernetesClientBuilder().build();
  VolcanoClient volcanoClient = kc.adapt(VolcanoClient.class)
) {
  volcanoClient.//...
}
```

> May I ask why this cannot inherit the client's IP and port

That's weird, both clients are initialized the same way.

Anyway, as you can see in the previous snippet, the right approach is to adapt your original client to a volcano client: `client.adapt(VolcanoClient.class).queues().//...`

**Comment by mafei-github** [comment]
![图片](https://github.com/user-attachments/assets/78b7410e-b479-4fe0-98f8-727a78aa5748)
![图片](https://github.com/user-attachments/assets/d21d19f4-b116-417b-858c-beb7a9211f67)
![图片](https://github.com/user-attachments/assets/3dd6c92c-5102-4b94-b677-98b4d6cb822d)

**Comment by rohanKanojia** [comment]
@mafei-github : Could you please share code snippets instead of screenshots? Could you please check with `kubectl` whether you have `v1beta1.VolcanoJob` resource installed in your Kubernetes cluster?

**Comment by mafei-github** [comment]
![图片](https://github.com/user-attachments/assets/ff5c332f-f0f6-4e20-aef5-9f4728fddf71)
queue、podgroup
volcanojob?

**Comment by mafei-github** [comment]
How to create colcanojob in this project

**Comment by rohanKanojia** [comment]
@mafei-github : It looks like VolcanoJob resource isn't added to the model of volcano extension. We need to add it to the model and client DSL

**Comment by mafei-github** [comment]
public interface V1beta1APIGroupDSL extends Client {
    MixedOperation<PodGroup, PodGroupList, Resource<PodGroup>> podGroups();
    MixedOperation<Queue, QueueList, Resource<Queue>> queues();
    MixedOperation<VolcanoJob, VolcanoJobList, Resource<VolcanoJob>> volcanoJobs();
}
------
VolcanoJob volcanoJob = new VolcanoJobBuilder()
                        .withNewMetadata()
                        .withNamespace(namespace)
                        .withName("test-job")
                        .withLabels(baseLabels)
//                        .withResourceVersion("66").withSelfLink("/apis/scheduling.volcano.sh/v1beta1/volcanojob/test-job")
                        .endMetadata()
                        .withNewSpec()
                        .withSchedulerName("volcano")
                        .withMinAvailable(1)
                        .withWeight(2)
                        .withPriorityClassName("high-priority")
                        .withMaxRetry(3)
                        .withQueue("queue.com")
                        .withVolumeMounts(volumeMounts)
                        .withVolumes(volumes)
                        .withTasks(tasks)
                        .endSpec()
                        .build();
                    VolcanoJob orReplace = defaultVolcanoClient.v1beta1().volcanoJobs().inNamespace(namespace).createOrReplace(volcanoJob);
-----
public class V1beta1APIGroupClient extends ClientAdapter<V1beta1APIGroupClient> implements V1beta1APIGroupDSL {
    @Override
    public V1beta1APIGroupClient newInstance() {
        return new V1beta1APIGroupClient();
    }

    @Override
    public MixedOperation<PodGroup, PodGroupList, Resource<PodGroup>> podGroups() {
        return resources(PodGroup.class, PodGroupList.class);
    }

    @Override
    public MixedOperation<Queue, QueueList, Resource<Queue>> queues() {
        return resources(Queue.class, QueueList.class);
    }

    @Override
    public MixedOperation<VolcanoJob, VolcanoJobList, Resource<VolcanoJob>> volcanoJobs() {
        return resources(VolcanoJob.class, VolcanoJobList.class);
    }

}
-----
java.lang.IllegalStateException: No adapter available for type:class com.dmai.model.common.k8s.volcano.client.V1beta1APIGroupClient

**Comment by rohanKanojia** [comment]
@mafei-github Is it possible for you to create a draft pull request? It'll be easier to check with that.

**Comment by mafei-github** [comment]
[2NPU-volcanojob.txt](https://github.com/user-attachments/files/16244276/2NPU-volcanojob.txt)
java.lang.IllegalStateException: com.fasterxml.jackson.databind.JsonMappingException: Conflicting setter definitions for property "volumes": com.dmai.model.common.k8s.volcano.model.src.scheduling.VolcanoJobSpec#setVolumes(1 params) vs com.dmai.model.common.k8s.volcano.model.src.scheduling.VolcanoJobSpec#setVolumeMounts(1 params)

**Comment by mafei-github** [comment]
step  one:create queue
![图片](https://github.com/user-attachments/assets/c29608aa-7d53-42cc-be52-53204896e65f)
is ok
![图片](https://github.com/user-attachments/assets/755949bc-1bb0-4f19-af2c-41d1c1449abd)
-------------
step two:create podgroup
![图片](https://github.com/user-attachments/assets/2a372986-f63b-48ce-bbd4-607ca46a56a0)
is ok 
![图片](https://github.com/user-attachments/assets/79595335-e2f0-4294-b8ea-1d4b6b7cc01f)
The queue and podgroup in the first two steps actually refers to this project
--------------
step three:create volcanojob
![图片](https://github.com/user-attachments/assets/b8464819-31ad-4a5c-afa0-89944069741a)
It's not ok
I modified this based on the original k8s job reference

**Comment by manusa** [comment]
Could you please create a GitHub repository with some sort of reproducer (or whatever **public** code you already have). Maybe this way we can provide better suggestions.
Otherwise it's hard for us to understand what problems you're facing.

**Comment by mafei-github** [comment]
![图片](https://github.com/user-attachments/assets/89ce12aa-1bf5-471f-b166-9dd7bd7b03a2)
![图片](https://github.com/user-attachments/assets/82ba57c8-659e-4e66-a331-d94462bd58f7)

**Comment by mafei-github** [comment]
![图片](https://github.com/user-attachments/assets/89ce12aa-1bf5-471f-b166-9dd7bd7b03a2)
![图片](https://github.com/user-attachments/assets/82ba57c8-659e-4e66-a331-d94462bd58f7)

**Comment by rohanKanojia** [comment]
@mafei-github : Could you please provide a resource where all volcano resources and supported apiGroups are listed? We can add them in upcoming release.

**Comment by mafei-github** [comment]
Do we need to support this interface on the k8s SDK? Does the latest version of K8S currently not support this interface?

**Comment by mafei-github** [comment]
![图片](https://github.com/user-attachments/assets/fdc5482d-aa95-4eb7-b9b0-ccf9d0087c2d)
Does this not support v1alpha1 version?

**Comment by rohanKanojia** [comment]
@mafei-github : No, it doesn't look like we support it at the moment.

Would  it be possible for you to contribute these to  KubernetesClient ?

**Comment by mafei-github** [comment]
Of course I am willing, what should I do?
![图片](https://github.com/user-attachments/assets/e0c96c54-1d73-49e8-b610-f701b61296e2)

I am using this template 
Do I need any more information to create this error message using the k8s client in Java?

**Comment by rohanKanojia** [comment]
@mafei-github : Okay, let me try to explain the steps:

## Model Generation


To add new resources to Volcano Model, you would need to edit [`extensions/volcano/generator-v1beta1/cmd/generate/generate.go`](https://github.com/fabric8io/kubernetes-client/blob/main/extensions/volcano/generator-v1beta1/cmd/generate/generate.go) and then issue `make` (requires GoLang 1.21) in `generator-v1beta1` . You can also run build inside a docker container:
```shell
sh kubernetes-model-generator/generateModelDocker.sh extensions/volcano/generator-v1beta1
```

If you want to add other apiGroups `v1alpha1` you would need to add new module `generator-v1alpha1 and `model-v1alpha1` respectively


## VolcanoClient DSL changes
In order to make these added types available in VolcanoClient, you would need to add new resources in `V1beta1APIGroupDSL` and [`V1beta1APIGroupClient`
](https://github.com/fabric8io/kubernetes-client/blob/main/extensions/volcano/client/src/main/java/io/fabric8/volcano/client/V1beta1APIGroupClient.java) . For new resources in `v1alpha1` apiGroup, equivalent `V1Alpha1APIGroupDSL` and `V1Alpha1APIGroupClient` would need to be created.

There is a similar old pull request that adds some resource types to volcano extension https://github.com/fabric8io/kubernetes-client/pull/3849

**Comment by manusa** [comment]
Besides this, remember that you can also use the official CRDs published by Volcano in conjunction with the Java generator Maven Plugin: https://github.com/fabric8io/kubernetes-client/blob/main/doc/java-generation-from-CRD.md

**Comment by mafei-github** [comment]
Do I need to refer to this template myself and write the code for the V1Alpha1APIGroupDSL extension that supports Volcano for this project?https://github.com/fabric8io/kubernetes-client/pull/3849

**Comment by rohanKanojia** [comment]
@mafei-github : Sorry I don't understand. Is your question reply to Marc's comment about using the[ Java Generator](https://github.com/fabric8io/kubernetes-client/blob/main/doc/java-generation-from-CRD.md) or to my comment about submitting a PR?

**Comment by mafei-github** [comment]
![图片](https://github.com/user-attachments/assets/3a1b376d-eb19-4193-8585-846abbe61c11)

**Comment by rohanKanojia** [comment]
@mafei-github : If you want to solve problem just for yourself (generate Volcano Java classes from CRD) . Follow https://github.com/fabric8io/kubernetes-client/blob/main/doc/java-generation-from-CRD.md?rgh-link-date=2024-07-18T08%3A44%3A53Z

> write the code for the V1Alpha1APIGroupDSL extension that supports Volcano for this project?

If you want to modify the codebase to provide support for new Volcano types, you would need to add code

**Comment by mafei-github** [comment]
According to this tutorial, can I solve the problem I am currently facing

**Comment by rohanKanojia** [comment]
@mafei-github : I haven't tried it myself but you should be able to do it. 

You need to place volcano CRDs in project and then configure [java-generator-maven-plugin](https://github.com/fabric8io/kubernetes-client/blob/main/doc/java-generation-from-CRD.md#quick-start-maven) to generate Java classes corresponding to missing volcano CRDs. See this blogpost for more details : [How to generate code using Fabric8 Kubernetes Client
](https://developers.redhat.com/articles/2023/01/24/how-generate-code-using-fabric8-kubernetes-client#)
Then you can use KubernetesClient to interact with volcano resources like this:
```
kubernetesClient.resources(VolcanoJob.class, VolcanoJobList.class).inNamespace("default").list()
```

**Comment by mafei-github** [comment]
this is why?
![图片](https://github.com/user-attachments/assets/cae82ef4-e4ea-447a-9a64-ac86fbc054c8)

**Comment by rohanKanojia** [comment]
@mafei-github : Have you added entry for v1alpha1 client here?

https://github.com/fabric8io/kubernetes-client/blob/6b7abd95db9ca554b81dee165ec9fb7bfe86ed8d/extensions/volcano/client/src/main/java/io/fabric8/volcano/client/VolcanoExtensionAdapter.java#L37-L38

**Comment by mafei-github** [comment]
It still doesn't work？
![图片](https://github.com/user-attachments/assets/ab336fd9-5079-4763-827a-12b6c7c1ed79)

**Comment by rohanKanojia** [comment]
@mafei-github : You're missing `@Override` annotation.

You need to add both clients, something like this:
```java
  @Override
  public void registerClients(ClientFactory factory) {
    factory.register(V1beta1APIGroupDSL.class, new V1beta1APIGroupClient());
    factory.register(V1alpha1APIGroupDSL.class, new V1alpha1APIGroupClient());
  }
```

**Comment by mafei-github** [comment]
It still doesn't work？?
![Uploading 图片.png…]()

**Comment by rohanKanojia** [comment]
@mafei-github : Please push your changes in some branch and share it with us. It's really hard to figure out what you're missing just looking at these screenshots.

**Comment by mafei-github** [comment]
ok.
But I still don't have permission through Gitub or using tokens?
remote: Permission to fabric8io/kubernetes-client.git denied to mafei-github. 
fatal: unable to access 'https://github.com/fabric8io/kubernetes-client/': The requested URL returned error: 403
![图片](https://github.com/user-attachments/assets/ef050f80-842d-43a7-9387-39f5a4a332b7)

**Comment by rohanKanojia** [comment]
@mafei-github : You need to [fork the project](https://github.com/fabric8io/kubernetes-client/fork) and push your branch to your fork. Then you can create a pull request to merge your branch (in your fork) to Fabric8 Kubernetes Client main

**Comment by mafei-github** [comment]
![图片](https://github.com/user-attachments/assets/805a48b3-55ea-4ea5-a73a-5acbe05b3087)
![图片](https://github.com/user-attachments/assets/a665d252-8be1-41d4-9001-0f6f63d9a6c2)
![图片](https://github.com/user-attachments/assets/4c506440-49ae-49c1-9a1f-e13edb56ff34)
remote: Permission to fabric8io/kubernetes-client.git denied to mafei-github.
fatal: unable to access 'https://github.com/fabric8io/kubernetes-client.git/': The requested URL returned error: 403

**Comment by rohanKanojia** [comment]
@mafei-github : please take a look at my previous comment https://github.com/fabric8io/kubernetes-client/issues/6103#issuecomment-2283089639 

You need to push your branch to `https://github.com/mafei-github/kubernetes-client.git` not `https://github.com/fabric8io/kubernetes-client.git`

**Comment by mafei-github** [comment]
1. I cut a new branch volcano.v1alpha1-test from the main branch, but I can't push it 
2. I randomly cut a branch, for example, on June 13th. I made the code more convenient, but still couldn't push it

**Comment by mafei-github** [comment]
ok, https://github.com/mafei-github/kubernetes-client.git
![图片](https://github.com/user-attachments/assets/c3e6f744-0dc2-477d-8224-4ecf46c362da)

**Comment by mafei-github** [comment]
Failure executing: POST at: https://10.196.10.137:6443/apis/batch.volcano.sh/v1alpha1/jobs. Message: Not Found.
but 
![图片](https://github.com/user-attachments/assets/9ed7bd87-b4ab-40c7-9e21-49773bbcb451)
![图片](https://github.com/user-attachments/assets/2649c4be-4500-4e2c-b11e-b89a4fa96cb7)
Is it due to inconsistency between the FHIR version and Kubernetes version?

**Comment by mafei-github** [comment]
![357650532-90661f7e-1a4e-4ae3-95e5-81bd8a7a29db](https://github.com/user-attachments/assets/a6382993-3f66-4f22-9a4d-9ec7ffd67183)

I have written these contents in the local project, which can be done for queue and podgroup, but not for job

**Comment by mafei-github** [comment]
Can you answer my question?

**Comment by rohanKanojia** [comment]
@mafei-github : I'll try to pull your branch and check it later today. If I find something wrong, I'll try to push to your branch

**Comment by mafei-github** [comment]
@rohanKanojia Thank you

**Comment by mafei-github** [comment]
I have noticed a phenomenon,
defaultVolcanoClient.queues().createOrReplace(queue);This code is normal，because  By default, client.podGroups() use v1beta1 version,
but
efaultVolcanoClient.v1beta1().queues().createOrReplace(queue);
No adapter available for type:class com.dmai.model.common.k8s.volcano.client.impl.V1beta1APIGroupClient

**Comment by mafei-github** [comment]
@rohanKanojia Can you answer my question? Thank you
