### ISSUE TITLE
kubernetesclient exception on watch process

### ISSUE THREAD

**Issue by souravgupta6nov1992** [fabric8io/kubernetes-client#6105]
### Describe the bug

We are using fabric kubernetesclient to watch on secrets where when we see any modification event, we need to update our application with certain changes. this behaviour is working fine for us. we do receive proper update events but along with that keep getting continuous exceptions:
`io.fabric8.kubernetes.client.KubernetesClientException: not ready after 10 SECONDS\n\tat io.fabric8.kubernetes.client.utils.Utils.waitUntilReadyOrFail(Utils.java:176)\n\tat io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.waitUntilReady(WatcherWebSocketListener.java:120)\n\tat io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.waitUntilReady(WatchConnectionManager.java:80)\n\tat io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:579)\n\tat io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:554)\n\tat io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:91)\n\tat `

PFB how we are configuring the watch:
`kubernetesClient = new DefaultKubernetesClient();
this.kubernetesClient.secrets().inNamespace(this.nameSpace).watch(new Watcher<Secret>() {
	                @Override
	                public void eventReceived(Watcher.Action action, Secret secret) {
                        }
`
We are not able to comprehend the reason for these errors as it seems that client was able to connect to kubeapi server since we are receiving update events.
We are not sure what this 10 seconds signify.

### Fabric8 Kubernetes Client version

other (please specify in additional context)

### Steps to reproduce

this error always comes whenever we deploy our application and start the watch process
initialize kubernetesclinet to connect to kube api server
watch on secrets in a namespace through fabric client library
see the error logs

### Expected behavior

no error logs

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.23

### Environment

Linux

### Additional context

fabric kubernetes client version:5.10.2

**Comment by shawkins** [comment]
It is not able to establish a web socket connection within 10 seconds. Also please use a newer version of the client - newer versions allow for this operation to be retried.

**Comment by souravgupta6nov1992** [comment]
@shawkins can you point out from which version this retry change is there

**Comment by shawkins** [comment]
Certainly by 6.9. Please try to use the lastest version possible though.
