### ISSUE TITLE
upgrade okhttp 4.12

### ISSUE THREAD

**Issue by melin** [fabric8io/kubernetes-client#6109]
### Is your enhancement related to a problem? Please describe

okhttp 3.12 version is older, the other library version is 4.12, easy to cause conflicts

### Describe the solution you'd like

upgrade okhttp 4.12

**Comment by rohanKanojia** [comment]
Duplicate of https://github.com/fabric8io/kubernetes-client/issues/2632

Meanwhile you can check this workaround [here](https://github.com/fabric8io/kubernetes-client/blob/main/doc/KubernetesClientWithIPv6Clusters.md)
