### ISSUE TITLE
Supporting batch/v1 instead of extensions/v1beta1 for Jobs

### ISSUE THREAD

**Issue by asteriosk** [fabric8io/kubernetes-client#611]
Hi everyone, is there any plan in supporting the new batch API of Kubernetes (batch/v1)? 

I cannot make the client work with  the batch/v1 API version for jobs (kubernetes-client still searches under extensions/v1beta1).

The extensions API for Jobs [is deprecated.](https://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/#_v1beta1_job)

Is there any workaround which could help me?

Cheers,
Asterios

**Comment by piyush1594** [comment]
Right now in the latest client, you can use batch/v1 and extensions/v1beta1 Hence closing this.
