### ISSUE TITLE
Which example should I refer to regarding leader election?

### ISSUE THREAD

**Issue by FunTK** [fabric8io/kubernetes-client#6128]
### Describe the bug

It's just a question.
Currently, we are using the same spring boot application in multiple pods.
In order to be able to perform specific logic on only one pod, so we are going to apply leader election in our project.

Here are two examples.

**SingleThreadExample** 
https://github.com/fabric8io/kubernetes-client/blob/main/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/LeaderElectionExamples.java#L49

**ConcurrentExample** 
https://github.com/fabric8io/kubernetes-client/blob/main/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/LeaderElectionExamples.java#L76

Should we use ConcurrentExample?

Thanks in advance

### Fabric8 Kubernetes Client version

SNAPSHOT

### Steps to reproduce

.

### Expected behavior

.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux, Amazon

**Comment by rohanKanojia** [comment]
> Currently, we are using the same spring boot application in multiple pods.


@FunTK : Could you please provide more details about your use case? By same do you mean there is only a single instance?

**Comment by FunTK** [comment]
there are three pods for same service
it is not single instance

But could you tell me which example to use for the two cases(single
instance and multiple instance) ?

2024년 7월 11일 (목) 오후 6:57, Rohan Kumar ***@***.***>님이 작성:

**Comment by manusa** [comment]
These examples are used to showcase the capabilities of the leader election implementation of the Fabric8 Kubernetes Client.

The multi-threaded example just showcases how leading election works. The example spawns multiple processes that can eventually become leaders. It continues by killing the new leader after a couple of seconds. After a leader is killed, one of the spawned processes should become the new leader, and so on.

The single threaded example shows the code you need to implement to take advantage of this leader election process.

> and do we need to add lease in deployment.yaml file as below?
> or it lease is made automatically?

The lease is created by the Kubernetes Client (provided that this is the leader election method you've configured -LeaseLock-). This is the mechanism used to ensure that only a single process becomes leader by acquiring this lease.
