### ISSUE TITLE
Add wait functionality for the resource that it makes sense

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#613]
There are lots of places where we need to wait for resource to become ready, to name a few:

- arquillian extension
- jenkins plugins
- etc

and in each place we use different code.

Resources that we could add wait functionality:

- Deployment
- ReplicaSet
- Pod
- Service
- ReplicationController
- DeploymentConfig

The result coud look like:

    Pod p = client.pods().inNamespace("myns").withName("mypod").await(5, TimeUnit.MINUTES);

or using a resource

    HasMetadata item = client.resouce(myresource).await(5, TimeUnit.MINUTES);

or using load

    List<HasMetadata> items = client.load(is).waitingUntilReady(5, TimeUnit.MINUTES).createOrReplace();

In case of failure to become ready we could throw an unchecked version of a TimeoutException.

@jimmidyson: Thoughts?B

**Comment by jimmidyson** [comment]
Yeah great idea.

Prefer to be consistent in naming, await perhaps isn't expressive enough? ` client.pods().inNamespace("myns").withName("mypod").await(5, TimeUnit.MINUTES)` - what am I waiting for? I assume `Ready` status but would be clearer to be named `waitUntilReady` perhaps? But then what does ready mean for a deployment for example?

With `client.resouce(myresource).await(5, TimeUnit.MINUTES)` if the resource type isn't "waitable" what should happen? Throw exception, or return immediately?

It's a shame that `createOrReplace` has to be the terminal method in `client.load(is).waitingUntilReady(5, TimeUnit.MINUTES).createOrReplace()` - doesn't read so well.

**Comment by iocanel** [comment]
`waitUntilReady` seems good to me.

In all cases waitUntilReady should mean that the required number of pods is ready.  
So for deployments specifically we should check the matching replica set and ensure that the the ready replicas match the spec.

If a resource is not waitable we should return asap for two reasons:
- an non waitable resource is ready anyway.
- I think that in most cases no one will just wait on a single resource, but in a list of resources (waitable and non waitables). So its a one way really.

I agree that these are not great: 

    client.load(is).waitingUntilReady(5, TimeUnit.MINUTES).createOrReplace()
    client.load(is).createOrReplace(5, TimeUnit.MINUTES)

so how about:

    client.load(us).createOrReplaceAnd().waitUntilReady(5, TimeUnit.MINUTES);

**Comment by jimmidyson** [comment]
All sounds good to me!

**Comment by kolleroot** [comment]
Hi, again. I'm very glad about the new feature but I think, I've found a bug. When kubernetes has to pull the image for one of the containers, the pod is in phase "Pending". During this phase, the conditions list is empty and in io.fabric8.kubernetes.client.internal.readiness.Readiness#getPodReadyCondition(Pod) an exception will be thrown.
I think, you not only have to check the conditions but also if pod is in the "Running" phase.

**Comment by cougil** [comment]
Hi!
Regarding with this approach I don't know if this is a similar issue, but when we are trying to recreate a Pod that it is already started and it takes a bit longer to delete, the recreation of the pod fails because it tries to delete and immediately create it, and because it is not already removed, the creation fails.
Best,

**Comment by rohanKanojia** [comment]
I think it can be closed
