### ISSUE TITLE
Remove deprecated methods in Utils class

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#6159]
## Description

Part of #5778 

The following methods must be removed from `Utils`:

- `getPluralFromKind(String kind)`
  https://github.com/fabric8io/kubernetes-client/blob/e0647d70f528e5d043f2827f1a6b81055c3302fc/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java#L350-L351

Dependencies must be updated accordingly.

**Comment by vaidikcode** [comment]
@manusa, how should we handle the use of this method in kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/base/ResourceDefinitionContext.java within the protected void validate method?

**Comment by manusa** [comment]
This needs to be evaluated:
- #6313 
- #6314

It's unclear if we still want to remove it or not.
