### ISSUE TITLE
Increased pod log rate limit

### ISSUE THREAD

**Issue by LiDarling** [fabric8io/kubernetes-client#6195]
### Is your enhancement related to a problem? Please describe

GET /api/v1/namespaces/{namespace}/pods/{name}/log  support  "limitBytes".It prevents browser websocket crashes.__

### Describe the solution you'd like

watchlog method add parameter "limitBytes".

**Comment by rohanKanojia** [comment]
@LiDarling : Which version of KubernetesClient are you using? I can see `limitBytes` DSL option

https://github.com/fabric8io/kubernetes-client/blob/8ce08c74f8072630121d4e72a14d41d061df299a/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/dsl/BytesLimitTerminateTimeTailPrettyLoggable.java#L26

It should be accessible like this:
```java
kubernetesClient.pods().withName("foo").limitBytes(10).watchLog()
```

**Comment by LiDarling** [comment]
sorry, I didn't find this method before, thank you.
