### ISSUE TITLE
Remove deprecated fields or methods in `io.fabric8.kubernetes.client.Config` class

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#6208]
### Is your task related to a problem? Please describe

The following fields/ methods must be removed from `io.fabric8.kubernetes.client.Config`:

- https://github.com/fabric8io/kubernetes-client/blob/74ba92421cdfc1fa00842fb4ac8273b0e27759d4/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java#L203-L207
- https://github.com/fabric8io/kubernetes-client/blob/74ba92421cdfc1fa00842fb4ac8273b0e27759d4/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java#L317-L318

Dependencies must be updated accordingly.

### Describe the solution you'd like

Deprecated methods are removed in v7 and documentation should point to updated methods (if there are any references to old methods)

**Comment by vaidikcode** [comment]
@rohanKanojia Can you tell me more about the current situation of issue and what are all the steps I need to follow to solve this?

**Comment by manusa** [comment]
I duplicated this issue by accident in:
- #6521 (fixed by #6522): Removal of `impersonateGroup` field
- #6528 (fixed by #6529): Removal of deprecated constructors

Closing the issue as completed.
