### ISSUE TITLE
Not able to upload file on AWS EKS - file is empty on container

### ISSUE THREAD

**Issue by fhussonnois** [fabric8io/kubernetes-client#6212]
### Describe the bug

Using the `CopyOrReadable#upload` method on AWS EKS cluster doesn't work (*Note, however, that in very rare cases this works* - no explication for that). 

The tar file is well created on the target container, but it's empty and the method returns `false` (similar to that issue: https://github.com/fabric8io/kubernetes-client/issues/5043).

```i.f.k.c.d.i.uploadable.PodUpload upload file size validation failed, expected 3584, but was 0```

and on the container: 

```
/working-dir # ls -l
-rw-r--r--    1 root     root             0 Jul 29 19:52 fabric8-00000000-0000-0000-0000-000000000019.tar
```

It seems that using `cat` for piping stdin with exec is not always reliabled.

Does anyone in the community already face a similar problem? Thanks for your help 

### Fabric8 Kubernetes Client version

6.13.1

### Steps to reproduce

Using the same approach with `kubectl` leads to the same result : 

`echo "test" | kubectl exec -i -n default aws-eks-run-python-9nwmi -c init-files -- sh -c "cat - > /working-dir/test"` (i.e., an empty file).

I took a look at what is done by the official Kubernetes client (see : https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/Copy.java#L412-L424) which uses a single step to process the tar file.

Using their approach works for us: 

```bash
cat test.tar | kubectl exec -i -n default aws-eks-run-python-9nwmi -c init-files -- sh -c "tar -xmf - -C /working-dir"
```

### Expected behavior

`CopyOrReadable#upload` should work.

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Amazon

### Fabric8 Kubernetes Client Logs

```shell
DEBUG WorkerThread f.k.c.i.i.DefaultSharedIndexInformer Ready to run resync and reflector for v1/namespaces/default/pods with resync 0
DEBUG WorkerThread f.k.c.i.i.DefaultSharedIndexInformer Resync skipped due to 0 full resync period for v1/namespaces/default/pods
DEBUG WorkerThread i.f.k.c.u.internal.PodOperationUtil Timed out waiting for Pod to become Ready: Timed out waiting for [0] milliseconds for [Pod] with name:[****] in namespace [default]., will still proceed
DEBUG OkHttp Dispatcher i.f.k.c.i.impl.cache.Reflector Listing items (1) for v1/namespaces/default/pods at v66426
DEBUG ****.amazonaws.com/... i.f.k.c.d.i.ExecWebSocketListener exec message received on channel errorChannel: {"metadata":{},"status":"Success"}
DEBUG WorkerThread f.k.c.i.i.DefaultSharedIndexInformer Ready to run resync and reflector for v1/namespaces/default/pods with resync 0
DEBUG WorkerThread f.k.c.i.i.DefaultSharedIndexInformer Resync skipped due to 0 full resync period for v1/namespaces/default/pods
DEBUG WorkerThread i.f.k.c.u.internal.PodOperationUtil Timed out waiting for Pod to become Ready: Timed out waiting for [0] milliseconds for [Pod] with name:[****] in namespace [default]., will still proceed
DEBUG ****.eks.amazonaws.com/... i.f.k.c.d.i.ExecWebSocketListener Exec Web Socket: On Close with code:[1000], due to: []
DEBUG OkHttp Dispatcher i.f.k.c.i.impl.cache.Reflector Listing items (1) for v1/namespaces/default/pods at v66427
DEBUG ****.eks.amazonaws.com/... i.f.k.c.d.i.ExecWebSocketListener exec message received 2 bytes on channel stdOut
DEBUG ****.eks.amazonaws.com/... i.f.k.c.d.i.ExecWebSocketListener exec message received on channel errorChannel: {"metadata":{},"status":"Success"}
DEBUG ****.eks.amazonaws.com/... i.f.k.c.d.i.ExecWebSocketListener Exec Web Socket: On Close with code:[1000], due to: []
DEBUG WorkerThread i.f.k.c.d.i.uploadable.PodUpload upload file size validation failed, expected 3584, but was 0
```

### Additional context

Kubernetes: 

* **EKS Kubernetes version: 1.30**
* **AMI version :** 1.30.0-20240703
* **Node Instance Type:** m5.large 

Java: 21

**Comment by shawkins** [comment]
No progress was made since this was last looked at: https://github.com/fabric8io/kubernetes-client/issues/5599#issuecomment-1828064880

> Using the same approach with kubectl leads to the same result

That seems quite strange given that it works on other platforms. Can you experiment with this a little more to see what could be happening - is it related to the command / syntax, or the file size?

> Using their approach works for us:

Except that is not guarenteed due to a bug in the websocket protocol https://github.com/kubernetes/kubernetes/issues/89899

The two step approach was to make people aware of when the upload was not sucessful.

**Comment by fhussonnois** [comment]
Hi @shawkins,  I did some other experiments, as you suggested, but I didn't notice any errors or differences when running different `kubectl` commands with the `v9` verbosity level.  

However, I found a trick. By adding another command after the `cat` everything works as expected (e.g., `echo $?` or `sleep 0`)!

```bash
cat ./3150193551304389127.py.tar | kubectl exec -i -n default aws-eks-run-python-9xdmb -c init-files -- sh -c "cat - > /working-dir/3150193551304389127.py.tar && echo $?"
``` 

Honestly, I can't really explain why this work. Maybe, with some environement the connection is closed before the `cat` command had a chance to capture the EOF and the stdin input stream is not properly closed.

I've pushed a PR for this: https://github.com/fabric8io/kubernetes-client/pull/6213

**Comment by shawkins** [comment]
> However, I found a trick. By adding another command after the cat everything works as expected (e.g., echo $? or sleep 0)!

That's great!

> Honestly, I can't really explain why this work. 

I'm a little fuzzy on why this would work also. From the client side once we finish the upload stream, we close the websocket - no explicit EOF can be sent / recieved due to the protocol bug. The server side then behaves non-deterministically wrt to what has already been sent. Most of the time what has been received / buffered will be processed by the command, but sometimes not - which results in truncation. Adding another command to the chain doesn't seem related to this - but if it works, it seems like a rather benign change.

> I've pushed a PR for this: https://github.com/fabric8io/kubernetes-client/pull/6213

Thank you, we'll review it.
