### ISSUE TITLE
The java project uses a dependency io.fabric8 -> kubernetes-client -> version 6.13.1, and did not find a way to create Gateway and HTTPRoute resources.

### ISSUE THREAD

**Issue by ChaoY000000** [fabric8io/kubernetes-client#6219]
### Is your enhancement related to a problem? Please describe

The java project uses a dependency io.fabric8 -> kubernetes-client -> version 6.13.1, and did not find a way to create Gateway and HTTPRoute resources. Creating Gateway and HTTPRoute resources in a custom resource way did not find a way to create them. What is the plan?

### Describe the solution you'd like

Is there an API similar to creating Ingress resources? For example, the following cases:
k8sClient.network().v1().ingresses().inNamespace(dto.getNamespace()).createOrReplace(ingress)

### Describe alternatives you've considered

I wanted to create a custom resource, but KubernetesClient didn't find the API either.

**Comment by rohanKanojia** [comment]
@ChaoY000000 : Are you talking about Istio Gateway and HTTPRoute resources? You can use the Istio Java Client extension. You would need to add this dependency: 

https://github.com/fabric8io/kubernetes-client/blob/806a918669aa328cbc3dc0be8d1c7339d06bdacb/extensions/istio/examples/pom.xml#L31-L33

then use client to create Gateway like this:

https://github.com/fabric8io/kubernetes-client/blob/806a918669aa328cbc3dc0be8d1c7339d06bdacb/extensions/istio/examples/src/main/java/io/fabric8/istio/api/examples/v1beta1/GatewayExample.java#L44-L60
