### ISSUE TITLE
Remove .json files (kube-schema.json, validation-schema.json, $$$extension.json)

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#6222]
## Description

Part of #6130

Remove `.json` files that were previously generated by the Go-JSONSchema generation.

These include:
- `kube-schema.json`
- `validation-schema.json`
- `$$$extension-schema.json`

**Comment by vaidikcode** [comment]
@manusa Could you please assign this issue to me? Also, do I need to delete every file with the names kube, validation, certmanager, and openclustermanager-schema.json? If not, is there a way to identify the files generated by the Go-JSONSchema generation?

**Comment by manusa** [comment]
This need to wait until all model generation has been refactored to use OpenAPI (currently 5 extensions are yet to be completed).
