### ISSUE TITLE
Issue: java.lang.NoClassDefFoundError: io/fabric8/kubernetes/client/KubernetesClientBuilder

### ISSUE THREAD

**Issue by penev-ff** [fabric8io/kubernetes-client#6223]
### Is your enhancement related to a problem? Please describe

In our app, we are utilizing the io.fabric8:kubernetes-client:6.13.1 library to interact with the Kubernetes API.
Additionally, we have a Maven zip assembly that bundles all the dependencies into a single zip file:

```xml
<dependencySets>
   <dependencySet>
	<includes>
            ...
            <include>io.fabric8:kubernetes-client</include>
            ...
	</includes>
    </dependencySet>
</dependencySets>
```

When we run the app, we get the following error on startup:

```java
Exception in thread "main" java.lang.NoClassDefFoundError: io/fabric8/kubernetes/client/KubernetesClientBuilder
Caused by: java.lang.ClassNotFoundException: io.fabric8.kubernetes.client.KubernetesClientBuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
```

I've checked the zip assembly file and the `kubernetes-client-6.13.1.jar` is there.
However, I realized that the `KubernetesClientBuilder` class is part of the `io.fabric8:kubernetes-client-api:6.13.1` file which is a transitive dependency of the `io.fabric8:kubernetes-client:6.13.1` and the "api" jar file is not included in the zip assembly file.

Should we include all the transitive dependencies in the zip assembly file or is there a better way to handle this?

### Describe the solution you'd like

Some libraries provide a self-contained jar file that includes all required dependencies in a single artifact.

**Comment by rohanKanojia** [comment]
@penev-ff : As far as I remember KubernetesClientBuilder is in `kubernetes-client-api` module. Does it work if you also include `io.fabric8:kubernetes-client-api` module?

**Comment by penev-ff** [comment]
Maybe including the `io.fabric8:kubernetes-client-api` module will resolve the Exception.
However, maybe some other jars like the `kubernetes-model-core` will be needed as well.
 
Given this, I think it is better to include the something like the uber-jar in order to avoid any potential runtime issues.
Is there a similar uber-jar without the OpenShift Model + Client because we don't need them?
We will be very happy if such a jar exists.

**Comment by manusa** [comment]
I guess that your best option is to create your own uber jar with the specific needs for your project or fine-tune the plugin that generates your assembly.

So maybe a module in your project that declares the dependencyManagement using `kubernetes-client-bom-with-deps` and then uses the maven shade plugin following the pattern in [kubernetes-openshift-uberjar](https://github.com/fabric8io/kubernetes-client/blob/497afaf6c8064d8b54f025239739b4908506f5c7/uberjar/pom.xml) or what's exposed in https://maven.apache.org/plugins/maven-shade-plugin/examples/includes-excludes.html.

**Comment by penev-ff** [comment]
@manusa Thanks for sharing this approach. This is actually the direction we were thinking of as well. 
We will give it a try. I am closing the issue as no further input is needed.
