### ISSUE TITLE
404 Failure executing: POST at: https://10.196.10.137:6332/apis/batch.volcano.sh/v1alpha1/jobs. Message: Not Found.

### ISSUE THREAD

**Issue by mafei-github** [fabric8io/kubernetes-client#6251]
### Describe the bug

Failure executing: POST at: https://10.196.10.137:6332/apis/batch.volcano.sh/v1alpha1/jobs. Message: Not Found.
but There is this resource in k8s
![图片](https://github.com/user-attachments/assets/1ef02097-3396-4d12-8860-ff0216ca6f65)
![图片](https://github.com/user-attachments/assets/a56d959e-4345-4042-8fc6-eb0770edb3f9)
Is it due to inconsistency between the kubectl version and Kubernetes version?

### Fabric8 Kubernetes Client version

6.13.2

### Steps to reproduce

![图片](https://github.com/user-attachments/assets/30b35c7b-daca-4a8a-a8d2-1165b167a7be)

### Expected behavior

![图片](https://github.com/user-attachments/assets/53602db6-48d2-4a20-80d9-c737eeaded5c)

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.23

### Environment

Windows

**Comment by rohanKanojia** [comment]
@mafei-github : Hello, your pull request https://github.com/fabric8io/kubernetes-client/pull/6244 hasn't been reviewed + or merged yet. Why have you reported this issue on v6.13.2?

It would help if you also addressed review comments on https://github.com/fabric8io/kubernetes-client/pull/6244
