### ISSUE TITLE
No adapter available for type:class com.dmai.model.common.k8s.volcano.client.impl.V1alpha1APIGroupClient

### ISSUE THREAD

**Issue by mafei-github** [fabric8io/kubernetes-client#6256]
### Describe the bug

![图片](https://github.com/user-attachments/assets/738e6861-08ec-4c60-904f-c7a47bb5651f)
No adapter available for type:class com.dmai.model.common.k8s.volcano.client.impl.V1alpha1APIGroupClient

### Fabric8 Kubernetes Client version

6.13.3

### Steps to reproduce

![图片](https://github.com/user-attachments/assets/738e6861-08ec-4c60-904f-c7a47bb5651f)
No adapter available for type:class com.dmai.model.common.k8s.volcano.client.impl.V1alpha1APIGroupClient

### Expected behavior

![图片](https://github.com/user-attachments/assets/738e6861-08ec-4c60-904f-c7a47bb5651f)
No adapter available for type:class com.dmai.model.common.k8s.volcano.client.impl.V1alpha1APIGroupClient

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.23

### Environment

Windows

**Comment by mafei-github** [comment]
@smlHao Have you encountered this problem before, but I still can't solve it according to your method? Can I ask for your advice?

**Comment by smlHao** [comment]
> @smlHao Have you encountered this problem before, but I still can't solve it according to your method? Can I ask for your advice?

Hi, Don`t see this error, Maybe you should keep compatibility between kubernets-client version and Valcano version

**Comment by mafei-github** [comment]
kubernets-client version is 6.13.0
<fabric.io.version>6.13.0</fabric.io.version>

Valcano version is 1.7.0
volcanosh/vc-scheduler:v1.7.0

kubectl version v1.23.1

**Comment by smlHao** [comment]
> @smlHao Please help me take a look, thank you kubernets-client version is 6.13.0 <fabric.io.version>6.13.0</fabric.io.version>
> 
> Valcano version is 1.7.0 volcanosh/vc-scheduler:v1.7.0
> 
> kubectl version v1.23.1

langchain4j-prd.yaml
langchain4j-local.yaml

> @smlHao Please help me take a look, thank you kubernets-client version is 6.13.0 <fabric.io.version>6.13.0</fabric.io.version>
> 
> Valcano version is 1.7.0 volcanosh/vc-scheduler:v1.7.0
> 
> kubectl version v1.23.1

kubernets-client version  6.13.0  seems to don`t implement alpha1 version , try to modify your code or vocal.yaml with beta1 version ?

![image](https://github.com/user-attachments/assets/605c6d4c-4e80-4ade-abe5-414459018a81)

**Comment by mafei-github** [comment]
@smlHao But does Volcano's API resources require v1alpha1 version?
![图片](https://github.com/user-attachments/assets/ef2f873e-be04-4c39-a11d-cd5f672d7e80)

**Comment by smlHao** [comment]
> @smlHao But does Volcano's API resources require v1alpha1 version? ![图片](https://private-user-images.githubusercontent.com/174586581/358533886-ef2f873e-be04-4c39-a11d-cd5f672d7e80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDA0NDQsIm5iZiI6MTcyMzgwMDE0NCwicGF0aCI6Ii8xNzQ1ODY1ODEvMzU4NTMzODg2LWVmMmY4NzNlLWJlMDQtNGMzOS1hMTFkLWNkNWY2NzJkN2U4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwOTIyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zM2U4OGZkOWEzNzYwYjEwNWM4NWIxMWFlYzkyOTA3MDU1YTA5NGViZmY5YzFiZTRkODUyN2M4Y2NhN2Q0ZDM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CefJy0UCPcNEGYsWle_YcpM7nxEFROPhqtamQG6D2Z4) I know kubernets-client version 6.13.0 seems to don`t implement alpha1 version ![图片](https://private-user-images.githubusercontent.com/174586581/358535708-e5a2a8d1-11f9-4fe1-a217-838cbf3e7eb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDA0NDQsIm5iZiI6MTcyMzgwMDE0NCwicGF0aCI6Ii8xNzQ1ODY1ODEvMzU4NTM1NzA4LWU1YTJhOGQxLTExZjktNGZlMS1hMjE3LTgzOGNiZjNlN2ViNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwOTIyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wY2FmNTAxNmY1NzJlZDVjMTFkZDQxNGVjOWQ2MDllYzhhYjEyMTJmZDliZGNiNmQ1OTRhMGU3NTUwOGE2OTUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n3vwrPC1KSuTC1aPb8wObfwNxPKHNcLBVwwBl0MFymw)

You can ask the Volcano community whether Volcano1.7.0 already supports beta1 version or not ， if not,  lowered your Volcano version , look forward to your contribution

**Comment by smlHao** [comment]
> @smlHao But does Volcano's API resources require v1alpha1 version? ![图片](https://private-user-images.githubusercontent.com/174586581/358533886-ef2f873e-be04-4c39-a11d-cd5f672d7e80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDA0NDQsIm5iZiI6MTcyMzgwMDE0NCwicGF0aCI6Ii8xNzQ1ODY1ODEvMzU4NTMzODg2LWVmMmY4NzNlLWJlMDQtNGMzOS1hMTFkLWNkNWY2NzJkN2U4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwOTIyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zM2U4OGZkOWEzNzYwYjEwNWM4NWIxMWFlYzkyOTA3MDU1YTA5NGViZmY5YzFiZTRkODUyN2M4Y2NhN2Q0ZDM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CefJy0UCPcNEGYsWle_YcpM7nxEFROPhqtamQG6D2Z4) I know kubernets-client version 6.13.0 seems to don`t implement alpha1 version ![图片](https://private-user-images.githubusercontent.com/174586581/358535708-e5a2a8d1-11f9-4fe1-a217-838cbf3e7eb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDA0NDQsIm5iZiI6MTcyMzgwMDE0NCwicGF0aCI6Ii8xNzQ1ODY1ODEvMzU4NTM1NzA4LWU1YTJhOGQxLTExZjktNGZlMS1hMjE3LTgzOGNiZjNlN2ViNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwOTIyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wY2FmNTAxNmY1NzJlZDVjMTFkZDQxNGVjOWQ2MDllYzhhYjEyMTJmZDliZGNiNmQ1OTRhMGU3NTUwOGE2OTUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n3vwrPC1KSuTC1aPb8wObfwNxPKHNcLBVwwBl0MFymw)

You can ask the Volcano community whether Volcano1.7.0 already supports beta1 version or not ， if not,  lowered your Volcano version , look forward to your contribution

**Comment by mafei-github** [comment]
@smlHao I saw on the Volcano official website that when Volcano v1.7.0 was released, the support for Kubernetes was upgraded to v1.25. However, I am not sure if this is the reason why Kubernetes is currently v1.23.1 here

**Comment by smlHao** [comment]
> @smlHao I saw on the Volcano official website that when Volcano v1.7.0 was released, the support for Kubernetes was upgraded to v1.25. However, I am not sure if this is the reason why Kubernetes is currently v1.23.1 here Because in k8s, it is possible to create this type of job by directly applying - f

WeChat  Search for 'smlhao', add me as a friend, and I'll invite you to the 'volcano' WeChat group?

**Comment by manusa** [comment]
The Volcano extension was completely refactored and updated for v7.0.0 which is now available:

- https://repo1.maven.org/maven2/io/fabric8/kubernetes-client/7.0.0/
- https://github.com/fabric8io/kubernetes-client/releases/tag/v7.0.0

Every type should be now available as part of the extension model.
