### ISSUE TITLE
KubeApiTest should use the new approach for binary download

### ISSUE THREAD

**Issue by csviri** [fabric8io/kubernetes-client#6277]
### Is your enhancement related to a problem? Please describe

The go controller runtimes envtest binaries are now moved from GCP to github release. KubeApiTest also uses those, we should migrate it also, see for details:
https://github.com/kubernetes-sigs/controller-runtime/pull/2811

### Describe the solution you'd like

Use binaries from github release

### Describe alternatives you've considered

There are no really alternatives, we don't want to build these binaries ourselves.

**Comment by csviri** [comment]
@manusa  I can take this one and fix it

**Comment by manusa** [comment]
> @manusa  I can take this one and fix it

Awesome, thx 🙌
