### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by markov404** [fabric8io/kubernetes-client#6280]
### Is your enhancement related to a problem? Please describe

https://github.com/fabric8io/kubernetes-client/tree/main?tab=readme-ov-file#following-events:~:text=()%0A%09%09.build()%3B-,Following%20events,-Use%20io.fabric8

KubernetesClientException is not actual exception

### Describe the solution you'd like

change KubernetesClientException to WatcherException

**Comment by rohanKanojia** [comment]
@markov404 : Could you please raise a pull request to fix this?
