### ISSUE TITLE
Is there any way to wait until a resource is created?

### ISSUE THREAD

**Issue by kolleroot** [fabric8io/kubernetes-client#629]
Hi, I'm creating kubernetes resources to run some unit tests and I would like to wait until the resources are created and ready (e. g. a namespace or pod).

I found https://github.com/fabric8io/kubernetes-client/blob/6e6690c18254b8a72fc9b202e214e2f9e33e1daf/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/RollingUpdater.java#L176-L218 but is there any nicer way to do this?

My current solution is, to just hope it works and most of the time it does.

**Comment by iocanel** [comment]
@kolleroot: Please have a look here at #613, which is something that I am working atm.

If this covers, you then we could possibly close this one as duplicate. wdyt?

**Comment by kolleroot** [comment]
Thanks @iocanel  for the quick reply. I don't know, why I haven't found this issue but this is exactly what I was looking for. I'm realy looking forwart to this feature. It would make my live a lot easier.
Sorry for the duplicate.
