### ISSUE TITLE
A simple sample to get job logs

### ISSUE THREAD

**Issue by masalinas** [fabric8io/kubernetes-client#6300]
### Describe the bug

I need a simple sample where:

1. Execute a job (the job can use a minute to be executed aprox)
2. Get all logs from the job every one second for example
3. Remove the job executed correctly

### Fabric8 Kubernetes Client version

SNAPSHOT

### Steps to reproduce

I need a simple sample where:

1. Execute a job (the job can use a minute to be executed aprox)
2. Get all logs from the job every one second for example
3. Remove the job executed correctly

### Expected behavior

Get the jobs in batch mode every 1 second for example

### Runtime

minikube

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

**Comment by rohanKanojia** [comment]
@masalinas : Do you want to schedule your job after a fixed interval? If yes, Do you think CronJob resource would be better suited for this use case?

**Comment by masalinas** [comment]
My user case is:

- From frontend a user we select a job and send a requets to backend to be execured.
- A backend microservice got the request and send a command to kubernetes to execute this job
- The microservice must recover any log generated from the job and send to a topic in a websocket server, where tje frontend user is subscribed. The he receive the log in real time.
- When the jobs finalize, it must be removed after some seconds

Right not create the job and create a watch to recover the state of the job and remove it when finalize is coded by me, but recover the logs using the watchLog is not posible and I did not find any sample similar to my User case, this is the reason to send this task, if you know how use correctly the watchLog to recocer any log generated by my job during the executing to be send in realtime to a topic.

Thanks

**Comment by rohanKanojia** [comment]
> create the job and watch it to recover the state of the job and remove it when it finalizes is coded by me correctly

@masalinas : Looking at the code, it doesn't look that you're watching Job logs, but the Job resource itself. You need to check for the Job status to verify whether it's finished or not, then invoke `getLog()` to get logs of the job.

Here is an example of watching Job logs directly using `watchLog` https://github.com/fabric8io/kubernetes-client/blob/7b728e752d3279d392383ee3bd437f6435ab7fe5/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/kubectl/equivalents/PodLogsFollowEquivalent.java#L27

**Comment by masalinas** [comment]
Yes I understand you, I only watched the state of the job not the logs, and your sample code is the default one included in the library, but **I would like to recover the logs during execution not only at the end**,  is it possible?. Do you have any sample or pattern to show this use case?

Regards

**Comment by rohanKanojia** [comment]
@masalinas : It should be possible to get logs during execution using `watchLog(OutputStream)`. Instead of `System.out` you can pass `ByteArrayOutputStream` and then read that later when you need it.

**Comment by rohanKanojia** [comment]
@masalinas : Here is an example of watching job logs in real time: 

https://github.com/fabric8io/kubernetes-client/blob/2f313928e46b8361494bd023cbef2d1a29833f0d/kubernetes-itests/src/test/java/io/fabric8/kubernetes/JobIT.java#L47-L51
