### ISSUE TITLE
Allow per-request configuration changes

### ISSUE THREAD

**Issue by jimmidyson** [fabric8io/kubernetes-client#631]
From @iocanel in https://github.com/redhat-ipaas/ipaas-rest/pull/65#discussion_r97195525:

If we break the Config object, in two parts:

properties that affect the connection (e.g. url, keys, certificates)
properties that don't affect the connection (token, credentials, timeout values)
we could possibly allow partial client reconfiguration:

DSL style

```java
 client.withRequstConfiguration(config).pods().list();
```

Functional Style

```java
PodList list =  client.withRequstConfiguration(config, new Function<KubernetesClient, PodList> {
        public PodList apply(KubernetesClient client) {
              return client.pods().list();
        }
 });
```

Lamda syle

```java
PodList list =  client.withRequstConfiguration(config, c -> c.pods.list());
```

While I love the Lamda style personally, as we're still on Java 7 for now, we're probably going to have to go with DSL style.

**Comment by iocanel** [comment]
@jimmidyson: The question is how we perform the split without breaking existing clients.
