### ISSUE TITLE
Remove unneeded dependency declarations in kubernetes-model-generator

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#6327]
## Description

Part of #6130

The kubernetes-model-generator module `kubernetes-model-generator/pom.xml` file contains multiple dependency declarations that seem to be unused.

The following lines should be removed:

https://github.com/fabric8io/kubernetes-client/blob/781441a34232ee9a34baf6e116ff25dcfe29acde/kubernetes-model-generator/pom.xml#L92-L138

**Comment by vaidikcode** [comment]
@manusa  Should I proceed with removing these dependencies? Will doing so interfere with the ongoing generator-related tasks?

**Comment by manusa** [comment]
You can try to remove these if you want. If the build passes, then it will be OK to merge.
Let me assign this issue to you.
