### ISSUE TITLE
Cannot get limit amount of data returned from pod logs

### ISSUE THREAD

**Issue by pmcq** [fabric8io/kubernetes-client#633]
Pod operations also does not support limitBytes query parameter:
https://kubernetes.io/docs/api-reference/v1/operations/

From what I can tell this would mean that for a long-running pod trying to get logs would result in creating a massive string.

https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/PodOperationsImpl.java#L110

**Comment by iocanel** [comment]
absolutely right! We need to add support for `limitBytes`

**Comment by serhii-samoilenko** [comment]
@iocanel, can you please take a look at my PR?

**Comment by serhii-samoilenko** [comment]
The fix for this issue was included in version 2.2.0.
I think, it can be closed.

**Comment by jimmidyson** [comment]
Thanks!
