### ISSUE TITLE
[crd-generator] Support declaring additionalPrinterColumns based on object metadata

### ISSUE THREAD

**Issue by btlem** [fabric8io/kubernetes-client#6345]
### Is your enhancement related to a problem? Please describe

When using the CRD generator and the `@PrinterColumn` annotation, there seemingly is not a mechanism to create a printer column based on object metadata (specifically `creationTmestamp`). When no additional printer columns are declared, kubectl and other tools will show a field called `AGE` based on resource.metadata.creationTimestamp. This column is quite useful for general management operations. However, when using the annotation this field is no longer shown and needs to be explicitly declared (ref: https://github.com/kubernetes/kubectl/issues/903)

### Describe the solution you'd like

Support an additional annotation or some mechanism to supply a printer column without needing an explicit field declaration (potentially class level annotation)

**Comment by shawkins** [comment]
Covered by #3069
