### ISSUE TITLE
Support scale subresource in CRD generator

### ISSUE THREAD

**Issue by pvcnt** [fabric8io/kubernetes-client#6444]
### Is your enhancement related to a problem? Please describe

I don't seem to be able to attach a [scale subresource](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource) to a CRD that is generated using crd-generator-apt.

### Describe the solution you'd like

Some annotations or an interface to implement to generate the required bits in the CRD YAML would be perfect.

**Comment by baloo42** [comment]
The scale subresource will be added automatically if a field is marked with `@SpecReplicas`, `@StatusReplicas` or `@LabelSelector`. This applies to crd-generator-apt (api-v1) and the new implementation in api-v2.

Example:
https://github.com/fabric8io/kubernetes-client/tree/main/crd-generator/api/src/test/java/io/fabric8/crd/example/webserver

Have you tried that?

**Comment by pvcnt** [comment]
Looks like what I need, I just could not find any docs about this. I see that you opened an issue for this, I'm hence closing this one. Thanks!
