### ISSUE TITLE
Client should accept valid response status codes range

### ISSUE THREAD

**Issue by nikhiljindal** [fabric8io/kubernetes-client#647]
From https://github.com/kubernetes/kubernetes/issues/33196

Looks like the client only accepts status ok (http code 200) as success for deletion: https://github.com/fabric8io/kubernetes-client/blob/112fdc2974f8ebd04839bd44595c9c836f808c4d/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java#L202
We want to update the apiserver to send 202 in case of asynchronous deletion.

Please fix the client so that the apiserver change does not break it.

Please feel free to comment on the original issue in case of any questions

**Comment by jimmidyson** [comment]
This should be applied across all requests.

**Comment by iocanel** [comment]
We will delegate to okhttp clients isSuccesfull() which literaly does:

     return code >= 200 && code < 300;

**Comment by jimmidyson** [comment]
Perfect

**Comment by jimmidyson** [comment]
Done.
