### ISSUE TITLE
question: how to generate/create Java K8s client for CRD?

### ISSUE THREAD

**Issue by rafhuys-klarrio** [fabric8io/kubernetes-client#6494]
I ran the Java generator on https://github.com/traefik/traefik/blob/06e64af9e9b4fffd3e0d2772343a31bc0de23c40/integration/fixtures/k8s/01-traefik-crd.yml#L726 and I see the `MiddlewareList` class is not generated, whereas with the included [Certmanager](https://github.com/fabric8io/kubernetes-client/tree/9b3fd528a84bd5580d9fafb074f43d2e3b5af549/extensions/certmanager/model-v1/src/generated/java/io/fabric8/certmanager/api/model/v1) example, there is a `CertificateList` class generated. Should I create the `MiddlewareList` class manually, or can the generator create this?

I also struggle to find documentation how to properly create a Kubernetes Client for (in my case) Traefik.io Middlewares. Again, is the included `Certmanager` extention a good example to follow?

**Comment by rohanKanojia** [comment]
@rafhuys-klarrio : I think you should be able to use KubernetesClient with just the actual type `k8sClient..resources(Middleware.class)`. For storing results of `list()` operations you can use `KubernetesResourceList<Middleware>`

**Comment by rafhuys-klarrio** [comment]
this might work indeed @rohanKanojia . Let me check thanks!

Maybe one more thing. In my tests I load some yaml like this: 

```
    val client = new io.fabric8.kubernetes.client.KubernetesClientBuilder().build()
    val result = client.load(new ByteArrayInputStream(s.getBytes(StandardCharsets.UTF_8))).items()
```

the Middleware in the `result` is actually parsed as `io.fabric8.kubernetes.api.model.GenericKubernetesResource`. How should I make the parser use the generated Middleware classes?

**Comment by rohanKanojia** [comment]
@rafhuys-klarrio : I think you should be able to do it via creating a MixedResources object and then using it as a client for CustomResource. Please see [TypedCustomResourceIT](https://github.com/fabric8io/kubernetes-client/blob/main/kubernetes-itests/src/test/java/io/fabric8/kubernetes/TypedCustomResourceIT.java#L92) , there should be a `load(` method available 

https://github.com/fabric8io/kubernetes-client/blob/641b2c874cea4531cd8382910f317832800a7122/kubernetes-itests/src/test/java/io/fabric8/kubernetes/TypedCustomResourceIT.java#L92

https://github.com/fabric8io/kubernetes-client/blob/641b2c874cea4531cd8382910f317832800a7122/kubernetes-itests/src/test/java/io/fabric8/kubernetes/TypedCustomResourceIT.java#L139

**Comment by rafhuys-klarrio** [comment]
you're 100% correct, I'm sorry. I was mislead by the the `println(petList)` which mentions `CustomResource` but indeed the types do line up! Nice.

The `load()` on the `petClient` also seems to do the job. Tx!
