### ISSUE TITLE
Upgrade okio to resolve security vulnerability

### ISSUE THREAD

**Issue by cowwoc** [fabric8io/kubernetes-client#6495]
### Describe the bug

Dependency maven:com.squareup.okio:okio:1.15.0 is vulnerable

Upgrade to 3.4.0

GHSA-w33c-445m-f8w7,  Score: 5.9

GzipSource does not handle an exception that might be raised when parsing a malformed gzip buffer. This may lead to denial of service of the Okio client when handling a crafted GZIP archive, by using the GzipSource class.

Read More: https://osv.dev/vulnerability/GHSA-w33c-445m-f8w7

Results powered by OSV

### Fabric8 Kubernetes Client version

SNAPSHOT

### Steps to reproduce

Adds dependency to pom.xml:

```
<dependency>
  <groupId>io.fabric8</groupId>
  <artifactId>kubernetes-client</artifactId>
</dependency>
```

IntelliJ warns about the aforementioned vulnerability

### Expected behavior

Upgrade to version 3.4.0 or higher to resolve the vulnerability

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Windows, Linux, macOS

### Fabric8 Kubernetes Client Logs

```shell
N/A
```

**Comment by cowwoc** [comment]
Yeesh. Your version of okio is over 6 years old (!!)

It's definitely overdue for an upgrade.

**Comment by manusa** [comment]
As of Kubernetes Client v7.0.0 the dependency is (will) no longer (be) there.

You should be able to verify this in our nightly builds.

See:
- #6441
- #5778 
- #2632 
- #5613
