### ISSUE TITLE
leaseResource.update() returns NPE for lease obtained successfully

### ISSUE THREAD

**Issue by ylt1534** [fabric8io/kubernetes-client#6526]
### Describe the bug

I tried to leverage this client to acquire the lease lock to complete leader election. I ever tried [this sample code under single thread](https://github.com/fabric8io/kubernetes-client/blob/main/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/LeaderElectionExamples.java) but not easy to debug thus currently the code is like the following pic shows. By debugging we can know at this point, the lease is acquired successfully, then i update the holder identity of the lease and try to update it, but the leaseResource.update() continuously throw NPE. 
![image](https://github.com/user-attachments/assets/32a08a84-3416-4cbc-8ac7-8bf7e391dec6)

By digging into the source code, i think the reason might be the clone call is not correct. What we expect is to clone the variable `got` instead of cloning item itself right? The item here is null, the clone would always fail. Would appreciate if you could let me know if this is a known issue/bug, thanks!
![image](https://github.com/user-attachments/assets/6b46b5de-10e6-4c88-b723-f07bf4e7ad26)

### Fabric8 Kubernetes Client version

6.13.4

### Steps to reproduce

1. create a lease resource in minikube
2. package image and run in minkube
3. remote debug in intellij

the code:
public static void main(String[] args) throws InterruptedException {

        System.out.println("################## Start my hello world ####################");
        final String lockIdentity = generateId().toString();
        while (true) {

            System.out.println("################## Start acquiring lease ####################");

            try (KubernetesClient client = new KubernetesClientBuilder().build()) {
                Resource<Lease> leaseResource = client.leases().inNamespace("default").withName("my-lease");
                System.out.println("Lease resource: " + leaseResource);
                Lease lease = leaseResource.get();
                if (lease.getSpec().getHolderIdentity() == null || lease.getSpec().getHolderIdentity().isEmpty()) {
                    // Logic to acquire lease
                    System.out.println("Attempting to acquire lease...");

                    lease.getSpec().setHolderIdentity(lockIdentity);
                    lease.getSpec().setRenewTime(ZonedDateTime.now()); // Example
                    lease.getSpec().setAcquireTime(ZonedDateTime.now()); // Example

                    System.out.println("Lease holder identity: " + lease.getSpec().getHolderIdentity());
                    leaseResource.update();
                    System.out.println("Lease acquired!");
                } else {
                    System.out.println("Lease already held by: " + lease.getSpec().getHolderIdentity());
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

//            try (KubernetesClient kc = new KubernetesClientBuilder().build()) {
//                LeaderElector leader = kc.leaderElector()
//                        .withConfig(
//                                new LeaderElectionConfigBuilder()
//                                        .withReleaseOnCancel()
//                                        .withName("Sample Leader Election configuration")
//                                        .withLeaseDuration(Duration.ofSeconds(15L))
//                                        .withLock(new LeaseLock(NAMESPACE, NAME, lockIdentity))
//                                        .withRenewDeadline(Duration.ofSeconds(10L))
//                                        .withRetryPeriod(Duration.ofSeconds(2L))
//                                        .withLeaderCallbacks(new LeaderCallbacks(
//                                                () -> {
//                                                    System.out.println("STARTED LEADERSHIP");
//                                                    try {
//                                                        leaderTask();
//                                                    } catch (InterruptedException e) {
//                                                        throw new RuntimeException(e);
//                                                    }
//                                                },
//                                                () -> System.out.println("STOPPED LEADERSHIP"),
//                                                newLeader -> System.out.printf("New leader elected %s%n", newLeader)))
//                                        .build())
//                        .build();
//                CompletableFuture<?> f = leader.start();
//                try {
//                    f.join();
//                } catch (Exception e) {
//                    e.printStackTrace();
//                }
//                System.out.println("################## Lease acquired?? ####################");
//                Thread.sleep(10000);
//                f.cancel(true);
//                Thread.sleep(5000);
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
            System.out.println("################## End acquiring lease ####################");

        }

    }

### Expected behavior

throw NPE

### Runtime

minikube

### Kubernetes API Server version

1.25.3@latest

### Environment

Windows

### Fabric8 Kubernetes Client Logs

```shell
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "resource" is null
        at io.fabric8.kubernetes.client.utils.KubernetesSerialization.clone(KubernetesSerialization.java:364)
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.clone(HasMetadataOperation.java:69)
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.update(HasMetadataOperation.java:135)
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.update(HasMetadataOperation.java:121)
        at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.update(HasMetadataOperation.java:44)
        at org.example.App.main(App.java:61)
```

**Comment by shawkins** [comment]
> What we expect is to clone the variable got instead of cloning item itself right? The item here is null, the clone would always fail. Would appreciate if you could let me know if this is a known issue/bug, thanks!

No, what that code is doing is setting the resourceVersion on what the user passed in. The client however should not directly modify what the user provided, so it's doing a clone first.

The issue here is a misunderstanding of how the api currently functions - and the lack of a clear error message for leaseResource.update().

When you do leaseResource.get() - provides the current state of the resource, that reference is not retained or associated with leaseResource. When you call resource.update() then there is no current item and you get an NPE.

To update the edited version of the resource, you can use client.resource(lease).update()

**Comment by ylt1534** [comment]
Thanks @shawkins ! that works for me!
