### ISSUE TITLE
Slow running of tests

### ISSUE THREAD

**Issue by wind57** [fabric8io/kubernetes-client#6560]
### Describe the bug

We have some tests in spring-cloud-kubernetes that I recently noticed are running very slow. For example:

```
@EnableKubernetesMockClient
class Test {

	private KubernetesMockServer mockServer;

	private KubernetesClient mockClient;

        @Test
	void test() {
		String namespace = "default";
		String path = "/api/v1/namespaces/" + namespace + "/configmaps";

		mockServer.expect().withPath(path).andReturn(500, "Internal Server Error").always();

		mockClient.configMaps().inNamespace("default").list().getItems();
	}

```

on my machines runs in around 15 to 18 seconds. This is against version `kubernetes-server-mock:6.9.2` and `kubernetes-client-api:6.9.2`

I am trying now to see what is going on with a profiler, but may be you already know of this issue?

### Fabric8 Kubernetes Client version

6.13.4

### Steps to reproduce

Just run the test above

### Expected behavior

Much faster running of the test

### Runtime

Kubernetes (vanilla), other (please specify in additional context)

### Kubernetes API Server version

1.25.3@latest

### Environment

macOS

**Comment by manusa** [comment]
Yes, if you want to test for failures, you can either disable the automatic retry, or set a lower backoff interval.
