### ISSUE TITLE
Remove deprecated methods from CustomResource class

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#6627]
## Description

Part of #6602 

The following methods are deprecated and no longer used, they must be removed the `CustomResource` class:

https://github.com/fabric8io/kubernetes-client/blob/32b34730825404610265ef817cea1c7d126f6d88/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/CustomResource.java#L207-L213

https://github.com/fabric8io/kubernetes-client/blob/32b34730825404610265ef817cea1c7d126f6d88/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/CustomResource.java#L221-L227

**Comment by currantino** [comment]
Hey, I'm ready to fix this
