### ISSUE TITLE
Remove deprecated methods from KubernetesClientException class

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#6629]
## Description

Part of #6602 

The following constructors and methods are deprecated and no longer used, they must be removed the `KubernetesClientException` class:

https://github.com/fabric8io/kubernetes-client/blob/25ecf8460eb132ae2945342b33f64a4240a2b91c/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClientException.java#L66-L74

https://github.com/fabric8io/kubernetes-client/blob/25ecf8460eb132ae2945342b33f64a4240a2b91c/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClientException.java#L76-L84

https://github.com/fabric8io/kubernetes-client/blob/25ecf8460eb132ae2945342b33f64a4240a2b91c/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClientException.java#L162-L173

**Comment by asharan2buff** [comment]
Can I take this up?

**Comment by asharan2buff** [comment]
@rohanKanojia created PR : https://github.com/fabric8io/kubernetes-client/pull/6633

**Comment by asharan2buff** [comment]
@rohanKanojia ran mvn spotless:apply. Please retrigger checks
