### ISSUE TITLE
Various problems with Exec()

### ISSUE THREAD

**Issue by amisevsk** [fabric8io/kubernetes-client#669]
Hello, I'm having a few issues using `exec()` in a OpenShift pod.

1. Threads are being leaked with every call to `exec()`. This seems to be a because a) `HttpClientUtils.java` creates a new `OkHttpClient` on each call to `createHttpClient()`, and b) the `InputStreamPumper` created in `ExecWebSocketListener` never ends.

2. The input streams provided by `ExecWebSocketListener` are never closed. This means that anything reading the output of an `exec()` will either end in an exception, or hang forever.
   
3. Maybe related to (1), but some `OkHttpClient` threads stay alive forever. `ExecExample` and `ExecPipesExample` both don't terminate when reaching the end of `main()`.
 
I've modified `ExecPipesExample.java` to show the issue [here](https://gist.github.com/amisevsk/c39c3b006176feee9f29a8e7d1c55cb0). The above code logs `Interrupted while pumping stream` on each iteration, because the `InputStreamPumper` blocks on the last `read()` call, even after the websocket is closed. This problem also occurs in `ExecExample` if you try to read from an output stream provided to `writingOutput()`. Also, after the last iteration, there are ten `OkHttp ConnectionPool` and `OkHttp Dispatcher` threads (due to 1a) and ten generically named threads resulting from the pumper created in the `ExecWebSocketListener` constructor never finishing (it probably shouldn't be created at all if input is null)

A potential fix is to reuse the `OkHttpClient` in `HttpClientUtils.java` and make sure `ExecWebSocketListener` cleans up properly in `onClose()`, but I'm not sure how this would affect other methods. 

I can provide more detail if necessary, let me know what you think.

**Comment by iocanel** [comment]
@amisevsk: Some comments:

`createHttpClient()` is something that is only called when creating a new instance of the client. exec() is cloning the OkHttpClient but its not creating a new one. The clone instance is expected to share connection pool, executors etc with the original instance, so I am not sure if this is an issue.

Exec operations are returning a handle to the caller, which should be used to call close() when done. But I think that you are right. We should also call close() when `onClose()` is called and also we should demonstrate the how exec() is meant to be used in the examples.

**Comment by iocanel** [comment]
Hmmm, the `ExecExample` and `ExecPipesExample` do call close on the watch (via try-with-resources). Which means, that there is something else going on here.

**Comment by iocanel** [comment]
@amisevsk: There multiple issues here:

- We should close() stream pumpler and executor when onClose() is called.
- We should make sure we don't close websocket, executor etc more than once.
- The example creates multiple instances of the client doesn't close() anything (neither client instances nor watches).

I took the liberty of improving and adding your example inside the `kubernetes-examples` module and also fixed all the identified issues are part https://github.com/fabric8io/kubernetes-client/pull/675

**Comment by amisevsk** [comment]
@iocanel Thanks for the fix! I've tried it out and everything looks good to me. The `createHttpClient()` bit was a mistake on my part, the example was kind of hastily thrown together.

I'm closing the issue as resolved.
