### ISSUE TITLE
Publish changelogs

### ISSUE THREAD

**Issue by foxish** [fabric8io/kubernetes-client#672]
As we upgrade between versions of clients, it would be useful to know of the major changes which occur.
For example, this release (2.0.7) contains also, changes to okhttp client version which is notable but not immediately evident to someone who does not go over the closed PRs and commits.

**Comment by ash211** [comment]
Yes please.  As a downstream project it's hard for me to gauge the magnitude of changes and where I should be focusing my regression testing if I don't know what the changes are.  I also don't know what benefits I get from upgrading so am less motivated to upgrade in general.
