### ISSUE TITLE
Edit buildconfig deletes buildhistory 

### ISSUE THREAD

**Issue by kaimago** [fabric8io/kubernetes-client#682]
simple edit of a buildconfig deletes the existing buildhistory everytime.

```java
openShiftClient.buildConfigs()									 
					.inNamespace(buildConfig.getMetadata()
					                          .getNamespace())
			                 .withName(buildConfig.getMetadata()
								        .getName())
					.edit()
					 .done();
```

Is this a bug or feature ?

Using kubernetes-client version 2.1.0
openshift-version 3.3.x

**Comment by sherl0cks** [comment]
bump. can we get some info on this? It's rather unexpected behavior

**Comment by sherl0cks** [comment]
looks like you can avoid this behavior by setting the `cascading` property to `false`.
```
openShiftClient.buildConfigs().inNamespace(namespace).withName(buildConfigName).cascading(false).edit() 
```

**Comment by kaimago** [comment]
thanks for the reply :)
But behaviour is still the same.
Same happens also when I patch the buildconfig.
Any more info which I can provide ?

Now using
kubernetes-client 2.5.7
opensift-version v3.5.5.31

**Comment by kaimago** [comment]
With 4.0.4 it's working

**Comment by kaimago** [comment]
With 4.0.4 it's working
