### ISSUE TITLE
Need to support SecurityContext.hostNetwork for Kubernetes model API

### ISSUE THREAD

**Issue by chlung** [fabric8io/kubernetes-client#690]
Hi,

Please support hostNetwork field in io.fabric8.kubernetes.api.model.SecurityContext.  So, we can use Spinnaker to set the value when build a container.

Thanks, Chasling

**Comment by jimmidyson** [comment]
Can you point me to the field you're talking about? `hostNetwork` is on PodSpec AFAIK - from Go source https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L2298.

I can't see that field on SecurityContext - https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L4261

**Comment by chlung** [comment]
Thanks for prompt reply.  I am referring the following information

Kubernetes API
https://godoc.org/k8s.io/kubernetes/pkg/api#PodSecurityContext

type PodSecurityContext struct {
    // Use the host's network namespace.  If this option is set, the ports that will be
    // used must be specified.
    // Optional: Default to false
    // +k8s:conversion-gen=false
    // +optional
    HostNetwork bool<https://godoc.org/builtin#bool>

Need to add the same field in SecurityContext
http://www.javadoc.io/doc/io.fabric8/kubernetes-model/1.0.67

Thanks, Chasling

**Comment by jimmidyson** [comment]
You're looking at the internal Kubernetes types there, not the versioned API types which uses `HostNetwork` field on `PodSpec` (https://godoc.org/k8s.io/kubernetes/pkg/api/v1#PodSpec).

I'm going to close this - please feel free to reopen if this doesn't solve your issue.

**Comment by chlung** [comment]
I want to make sure if this should be the same one.

From  https://godoc.org/k8s.io/kubernetes/pkg/api/v1#PodSpec

// Host networking requested for this pod. Use the host's network namespace.
    // If this option is set, the ports that will be used must be specified.
    // Default to false.
    // +k8s:conversion-gen=false
    // +optional
    HostNetwork bool<https://godoc.org/builtin#bool> `json:"hostNetwork,omitempty" protobuf:"varint,11,opt,name=hostNetwork"`

Thanks, Chasling

**Comment by jimmidyson** [comment]
Here's the relevant conversion: https://github.com/kubernetes/kubernetes/blob/3604cdc6a9d084b1c141319616db14316051f0f0/pkg/api/v1/conversion.go#L541 so yes, it is.

**Comment by chlung** [comment]
Thanks.


I download kubernetes-api:2.2.192, and it does not include it yet.  Which version of jar that I need to use to ensure the code will compatible with SecurityContext.hostNetwork.

**Comment by jimmidyson** [comment]
You probably only need kubernetes-client, not kubernetes-api which is a consumer of this library with a few extras, but specific to fabric8 rather than generic like kubernetes-client. Advice is to always use the latest :)
