### ISSUE TITLE
Add support for node.Spec.Taints

### ISSUE THREAD

**Issue by foxish** [fabric8io/kubernetes-client#691]
Taints are first class fields in the Node object's spec as of Kubernetes 1.6

**Comment by devent** [comment]
Is there an update on this? I wanted to use `kubernetes-client` to modify taints on the nodes, but I can't find the api. 

* kubernetes-api 2.3.4
* kubernetes-client 2.6.1

**Comment by piyush1594** [comment]
Support for node.spec.taints is there is the latest client. I think we can close this issue @rohanKanojia @dev-gaur

**Comment by rohanKanojia** [comment]
Thanks for the heads up :+1:
