### ISSUE TITLE
Relations between versions - APIs

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/kubernetes-client#695]
The project kubernetes has released different versions : 1.3, 1.4, 1.5, 1.6 & 1.7 which are supported by OpenShift for at least the versions 1.3 & 1.4

Fabric8 project generates Kubernetes Java classes (= kubernetes model project) which are released under versions : 1.0.x

Questions : 

- How can I match a kubernetes Api version (= 1.4) with the kubernetes model version ?
- As kubernetes Model is packaged with the kubernetes-client [1] project (and also used by Arquillian Cube/ CE Arquillian ? and Fabric8 Maven Plugin), how can we correlate the version of the model with the version of the Kubernetes Api as kubernetes Client is released under version number 1.x and now 2.x ?
- Why do we have a Kubernetes Client version 2.x and also version 1.x ?
- Is there a table summarising the relation between the Kubernetes Release / OpenShift Release / Kubernetes Java Model / Kubernetes Client ? 

[1] : https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/pom.xml#L156-L159

**Comment by rohanKanojia** [comment]
https://github.com/fabric8io/kubernetes-client#compatibility-matrix
