### ISSUE TITLE
io.fabric8.kubernetes.client.ConfigBuilder is not exist

### ISSUE THREAD

**Issue by boom-shakalaka** [fabric8io/kubernetes-client#704]
where can i find the class io.fabric8.kubernetes.client.ConfigBuilder?

**Comment by subaprasanna** [comment]
Can you please direct us to where we can find the is file?

**Comment by samwelkey** [comment]
the same, missing the class io.fabric8.kubernetes.client.ConfigBuilder...
help qwq///

**Comment by ArtemZ** [comment]
Same here, can't find it...

**Comment by piyush1594** [comment]
Hey, mentioning the steps to located the file 

1. `git clone https://github.com/fabric8io/kubernetes-client`
2. `cd kubernetes-client`
3. `mvn clean install -DskipTests`
4. `cd kubernetes-client/target/generated-sources/annotations/io/fabric8/kubernetes/client/`
5. `cat ConfigBuilder.java`

Thanks
