### ISSUE TITLE
Support `rollout latest dc/<name>`

### ISSUE THREAD

**Issue by heiko-braun** [fabric8io/kubernetes-client#709]
It would nice if the client API would support to trigger a new rollout of a deployment

**Comment by heiko-braun** [comment]
In earlier versions of this was called `oc deploy --latest` I think

**Comment by iocanel** [comment]
The equivalent should be something like:

    client.deplyomentConfigs().inNamespace("somens").withName("myconfig").deployLatest();

and if you need to wait for the rollout

    client.deplyomentConfigs().inNamespace("somens").withName("myconfig").deployLatest(true);

**Comment by heiko-braun** [comment]
ok, `deployLatest(true)` works fine. But it's deprecated. I'll leave this open as a reminder to update the API to `rollout latest`

**Comment by heiko-braun** [comment]
thanks @iocanel !

**Comment by manusa** [comment]
Shouldn't this be covered by now with: 
https://github.com/fabric8io/kubernetes-client/blob/82db0fc1eb532ffcd92260226fc68c980d2ac4f8/README.md#L615

#1064 #1364

**Comment by shawkins** [comment]
Marking as closed, latest has been removed from kubectl only restart is supported, which as Marc noted is already supported by the fabric8 client.
