### ISSUE TITLE
Support multiple certificate entries in CA data/file

### ISSUE THREAD

**Issue by mccheah** [fabric8io/kubernetes-client#731]
Sometimes, Kubernetes users may provide CA files or data that contain multiple certificate entries:

    -----BEGIN CERTIFICATE-----
    abcdef…
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    hijklm…
    -----END CERTIFICATE-----

However, `CertUtils` only creates the trustStore using the first certificate it finds in the data. We should create the truststore with an entry for every certificate provided in the data or file.

**Comment by mccheah** [comment]
Never mind, this was fixed in 2.2.3 - we were using an older version.

**Comment by ash211** [comment]
Fixed in https://github.com/fabric8io/kubernetes-client/pull/696
