### ISSUE TITLE
InputStreamPumper seems to never complete on its own

### ISSUE THREAD

**Issue by amisevsk** [fabric8io/kubernetes-client#732]
If I submit an `InputStreamPumper`, the returned `Future` is never done. This makes running execs in Pods difficult, since we have to wait until we think we're done reading input, as in `ExecLoopExample.java`.

Briefly looking into the issue, it seems like the `ExecWatch.getOutput()` pipe is never closed, and the last call to read from it in `InputStreamPumper` blocks.

An modified version of `ExecLoopExample.java` showing this issue is at this [gist](https://gist.github.com/amisevsk/001f519646e7c634e836cb2a2ed2ec96). Running the sample code will repeatedly print "future is not done yet", until eventually crashing with an IOException.

Version info:
kubernetes-client: 2.2.8 (tested with current HEAD and happens there too)
openshift v1.4.1+3f9807a
kubernetes v1.4.0+776c994
(running locally on minishift)

**Comment by amisevsk** [comment]
Looking at it more, it looks like ExecWebSocketListener's `out` and `err` OutputStreams are not closed when the WebSocket is closed. Adding `out.close()` to EWSL's `onClosing()` method causes the example to work as expected.

**Comment by iocanel** [comment]
@amisevsk: I think that the `ExecWebSocketListener` should only close streams that are managed internally. Any stream that has been passed externally, should be the responsibility of the caller to close.

For example:

    client.pods().withName('mypod').writingOutput(out).exec(cmd)

Of course when the stream is managed internally (e.g. when using redirects), the stream should be closed as you suggest:

     client.pods().withName('mypod').redirectingOutput().exec(cmd)

I'll work on it tomorrow, or I can assign it to you if you want to also contribute the fix.

Thanks.

**Comment by amisevsk** [comment]
@iocanel Thanks for looking at it! I'm a bit bogged with other issues at the moment, so I don't think I have time to take a look right now. We're currently using the second case (`redirectingOutput()`) so we have no way to close the write end as far as I can tell.

**Comment by amisevsk** [comment]
Direct link to relevant PR, for convenience: https://github.com/fabric8io/kubernetes-client/issues/732

**Comment by amisevsk** [comment]
Closing -- out of date and no longer a problem.
