### ISSUE TITLE
Creating a pod with DSL throws exception with message: resourceVersion may not be set on objects to be created

### ISSUE THREAD

**Issue by htamas** [fabric8io/kubernetes-client#734]
I'm testing against a Minikube running locally on my machine (OS X El Capitan)

Here is the pod creation code: 
```          
 Pod pod = kube.pods().createNew()
                .withApiVersion("v1")
                .withNewMetadata()
                .withNamespace("default")
                .withName("pi")
                .and()
               .withNewSpec().addNewContainer().withName("pi").withImage("perl").withCommand("perl", "-Mbignum=bpi", "-wle", "print bpi(2000)")
                .and()
                .withRestartPolicy("Never")
                .and()
                .done();
```

And the message: `Failure executing: POST at: https://192.168.99.100:8443/api/v1/namespaces/default/pods. Message: resourceVersion may not be set on objects to be created. Received status: Status(apiVersion=v1, code=500, details=null, kind=Status, message=resourceVersion may not be set on objects to be created, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=null, status=Failure, additionalProperties={}).`

If I create the pod with normal objects like this:
```
EditableObjectMeta meta = new EditableObjectMeta();
meta.setName("pi");
meta.setNamespace("default");
meta.edit();

EditableContainer piContainer = new EditableContainer();
piContainer.setName("pi");
piContainer.setImage("perl");
piContainer.setCommand(Arrays.asList("perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"));

PodSpec podSpec = new EditablePodSpec();
podSpec.setContainers(Collections.singletonList(piContainer));
podSpec.setRestartPolicy("Never");
Pod pod = new Pod("v1", "Pod", meta, podSpec, null);
kube.pods().create(pod);
```
It works fine. Am I doing something wrong?

**Comment by rohanKanojia** [comment]
@htamas : Is this still an issue?

**Comment by htamas** [comment]
@rohanKanojia I think we eventually used an other library for our solution, so I can't check, sorry.
