### ISSUE TITLE
provide a way to invoke `resource.edit()` which detects if the resource really has changed and avoids doing a change

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/kubernetes-client#737]
e.g. the jenkins-sync-plugin we do lots of edits to a resource like `Build` with values and annotations. It'd be nice if we could have a way to check if the resource really has changed (e.g. if the labels/annotations/name changes in metadata or the json of the `spec` changes etc) to avoid folks having to manually do this - which is error prone by hand doing deep comparisons for changes.

so maybe something like
```
kubernetesClient.services().inNamespace("foo").withName("bar).editIfModified().editMetdata().addAnnotation(foo, bar).endMetadata().done();
```
where `editIfModified()` works like `edit()` but it also checks the resource first to see if its really been modified and if not silently do nothing on `done()`

**Comment by jstrachan** [comment]
@iocanel am guessing there is no feature like this already?

**Comment by iocanel** [comment]
AFAIK, there is no such feature in place. 

I do like the idea, I am not crazy about the name `editIfModified`. I am wondering though if this is something we should ALWAYS do, as I don't see any point in performing an actual update if nothing has changed.

**Comment by jstrachan** [comment]
Agreed. Maybe we add an optional `forceUpdate()` to the DSL to force updates if nothings changed?

**Comment by rohanKanojia** [comment]
This issue still makes sense
