### ISSUE TITLE
Minor API issue: Watcher<T> should probably be Watcher<T extends HasMetadata>

### ISSUE THREAD

**Issue by ljnelson** [fabric8io/kubernetes-client#744]
Hello; thanks for your work on this project.

It seems to me that the `Watcher` class should not take an undifferentiated type parameter but should instead use `T extends HasMetadata`.  (Creating, say, a `Watcher<Integer>` is currently permitted but we all know such a thing would never be called.)

I base this off the [only location I could find in the source base where the `eventReceived` method is called](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.java#L207-L217), and the payload is forced into being a subclass of `HasMetadata`.

**Comment by jimmidyson** [comment]
Sounds reasonable to me. Fancy sending in a PR?

**Comment by shawkins** [comment]
Marking this as out-of-date / not needed.  The only places that need watchers will already be appropriately typed.  The casting needed in AbstractWatchManager is more related to the typing of WatchEvent - which can be a KubernetesResource.
