### ISSUE TITLE
Failing build

### ISSUE THREAD

**Issue by khogeland** [fabric8io/kubernetes-client#752]
Looks like the build has been broken for a few weeks due to a dependency license check failing. Currently using snapshots, but waiting for a release to be cut, because I depend on https://github.com/fabric8io/kubernetes-client/pull/745. Is the failure being looked at?

**Comment by jimmidyson** [comment]
Hey @khogeland. The master build isn't failing btw - that was a dodgy link in the README to a PR build.

Are you using unreleased functionality or is the latest release ok for you to use?

**Comment by jimmidyson** [comment]
Closing this now - please reopen if this is still an issue.
