### ISSUE TITLE
Deleting Deployments with `.cascading(true)` creates a new replica set

### ISSUE THREAD

**Issue by lwander** [fabric8io/kubernetes-client#758]
When I invoke 
```groovy
client.extensions()
  .deployments()
  .inNamespace(namespace)
  .withName(name)
  .cascading(true)
  .delete()
```

On some deployment `abc`, the client library deletes the deployment `abc` as well as the current replica set it's managing, but leaves behind a new replicaset `abc-<random number>` with 0 pods.

My client library is at version 2.2.14

**Comment by binjianwu** [comment]
I have the same question,Do you have a solution？

```
        <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>openshift-client</artifactId>
            <version>2.5.8</version>
        </dependency>
```

```
 @Override
    public void deleteDeployment(String namespace, String name) {
        OpenShiftClient client = openshiftClient.getClient();
        boolean deleted = client.extensions()
                .deployments()
                .inNamespace(namespace)
                .withName(name)
                .cascading(true)
                .delete();
    }
```

but:
![image](https://user-images.githubusercontent.com/18679696/28914615-eb3ee444-786e-11e7-9e04-9ba3b21494c2.png)

**Comment by GrigorievNick** [comment]
Same here

**Comment by rohanKanojia** [comment]
@GrigorievNick : Hmm, Could you please raise a PR to fix this in case you have time?

**Comment by GrigorievNick** [comment]
@rohanKanojia I can do it, but after long pause. 1 month.
Sorry but I plan long trip, with out notebook.

I think, thta i find root cause,
`DeploymentReaper` -> line 238
```
      Deployment deployment = oper.cascading(false).edit().editSpec().withReplicas(0).endSpec().done();
```
But i change this, a lot of thing stop work.
I will need much more time to test such fix, then i have.
If it ok, i can come back to this issue at the end of May.
