### ISSUE TITLE
apiVersion in group batch of Job should support both v1 and v2alpha1

### ISSUE THREAD

**Issue by lvjiangzhao** [fabric8io/kubernetes-client#763]
related [611](https://github.com/fabric8io/kubernetes-client/issues/611), [697](https://github.com/fabric8io/kubernetes-client/issues/697), [698](https://github.com/fabric8io/kubernetes-client/pull/698)
I wonder why we support v2alpha1 with v1 missing. At the moment, we could not use batch/v1 Job with this client. Is there a plan to involve this ?

**Comment by piyush1594** [comment]
Right now in the latest client, you can use batch/v1 and extensions/v1beta1 Hence closing this.
