### ISSUE TITLE
Does kubernetes-client 2.3.1 support the StorageClass of k8s 1.6.2 ?

### ISSUE THREAD

**Issue by zhaorendong** [fabric8io/kubernetes-client#764]
I want to create StorageClass, but I don't know wether kubernetes-client 2.3.1 support the StorageClass of k8s 1.6.2 ?

**Comment by richard-julien** [comment]
After some search in the project to resolve the same problem i realize that the current kubernetes-client use a kubernetes-model based on openshift release. So a bit too old ;) So i tried to fork the model and the client to generate the stuff on kubernetes 1.6.2.
I dont have all the features I think but you can try my fork https://github.com/richard-julien/kubernetes-client to be able to use storageClass.

**Comment by zhaorendong** [comment]
Ok ,I will have a try,Thank you!

**Comment by oscerd** [comment]
Done here:

https://github.com/fabric8io/kubernetes-client/pull/978

It will be available in 3.1.9
