### ISSUE TITLE
Is this api supports Kubernetes Cron Job?

### ISSUE THREAD

**Issue by amalkasubasinghe** [fabric8io/kubernetes-client#770]
Is this api supports Kubernetes Cron Job?
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#schedule
If so, someone please share a sample with me.

I want to create Cron Jobs via Java API and get the statistics of it

**Comment by ttony** [comment]
I Checked the code, somehow there is model for cronjob however, there is no handler for it. When will this feature available? i am vote for it as well.

**Comment by hrishin** [comment]
Add support for following operations to handle cron jobs:
 - Create cron job
 - Get/List cron job(s)
 - Delete cron jobs

Tasks:
- Implement feature code
- add unit test

**Comment by pluttrell** [comment]
Just curious if anyone knows when this feature will make it into a release that gets published to maven repos? Thanks!

**Comment by rohanKanojia** [comment]
@pluttrell : Hi, We would be releasing kubernetes-client `4.0.4` in a a week or two :)

**Comment by chrisjs** [comment]
is there a way to use `v1beta1` rather than `v2alpha1` as in the PR when using the API?

**Comment by rohanKanojia** [comment]
Um, for now it's being hardcoded here:
https://github.com/fabric8io/kubernetes-client/blob/3bf0cc75fb7cb66aed7788a93e50b1a46ee09ce2/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/CronJobOperationsImpl.java#L33-L35

Do you any specific usecase in which you need `v1beta`? I would then have to consider making this somehow configurable.

**Comment by chrisjs** [comment]
yes, don't want to enable alpha versions. also its deprecated - per the docs `Note: CronJob resource in batch/v2alpha1 API group has been deprecated starting from cluster version 1.8. You should switch to using batch/v1beta1, instead, which is enabled by default in the API server. Examples in this document use batch/v1beta1 in all examples.`

**Comment by rohanKanojia** [comment]
ah, I see. Then it makes more sense to have `v1beta1` rather than having `v2alpha1` . Could you please file an issue for this change so that I doesn't get lost in this chat ;-) ? I'll accomodate this change before doing release, which is probably next week.
