### ISSUE TITLE
Deleting based on YAML file.

### ISSUE THREAD

**Issue by razavi1371** [fabric8io/kubernetes-client#773]
Hello

It seems there is no function in the API to delete a service or deployment using YAML file.
For deleting a service, you need to save the save the name of the service and delete it using
client.services().withName(serviceName).delete();
Is there a better way or it is the only way?

Thanks

**Comment by traviswinter** [comment]
This has probably long been solved, but you can accomplish this by building the YAML into  HasMetadata objects using "_kubeClient.load(yamlInputStream).get();_" then calling "_kubeClient.resource(object ).inNamespace(namespace).delete()_".
