### ISSUE TITLE
Watcher with resource RoleBinding not working

### ISSUE THREAD

**Issue by MichaelVoegele** [fabric8io/kubernetes-client#775]
Hello

I created a watcher for ConfigMap before with:
`openShiftClient.configMaps().inAnyNamespace().watch(new Watcher<ConfigMap>() {...});`
-> This works perfectly.

I now created a watcher for RoleBinding with:
`openShiftClient.roleBindings().inAnyNamespace().watch(new Watcher<RoleBinding>() {...});`
-> This ends with:
```
2017-06-07 14:51:10,261 [main] DEBUG io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager - Connecting websocket ... io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@b9fc7d
2017-06-07 14:51:10,916 [main] DEBUG io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager - Watching via HTTP GET ... io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager@7c28c1
2017-06-07 14:51:11,166 [OkHttp https://osconsole.pink.eu-west-1.aws.openpaas.axa-cloud.com/...] ERROR io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager - Unknown message received: {"kind":"RoleBindingList","apiVersion":"v1","metadata":{"selfLink":"/oapi/v1/rolebindings"},"items":[...]}
2017-06-07 14:51:11,167 [OkHttp https://osconsole.pink.eu-west-1.aws.openpaas.axa-cloud.com/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager - Submitting reconnect task to the executor
2017-06-07 14:51:11,167 [Executor for Watch 8136897] DEBUG io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager - Scheduling reconnect task
```

I tested this with versions 2.3.1 and 2.2.14.

I think, this is an issue. Could you please fix this?

Thank you, regards
Michael

**Comment by MichaelVoegele** [comment]
Hello

I have seen that the successful watch with ConfigMap uses the class WatchConnectionManager only. The unsuccessful watch tries first WatchConnectionManager, the request returns 200 instead of 101 as expected, and then WatchHTTPManager is used.

Any ideas?

Regards
Michael

**Comment by MichaelVoegele** [comment]
Hi

Could I please get some feedback on this issue? Is it an issue or is it somehow expected? That would be nice.

Thank you
Michael

**Comment by rhuss** [comment]
@iocanel any idea what this could be ?

**Comment by jimmidyson** [comment]
It looks like watching role bindings isn't supported by the OpenShift REST API:

```bash
$ oc get rolebinding -w              

NAME                    ROLE                    USERS       GROUPS                             SERVICE ACCOUNTS   SUBJECTS 
admin                   /admin                  developer                                                          
system:deployers        /system:deployer                                                       deployer            
system:image-builders   /system:image-builder                                                  builder             
system:image-pullers    /system:image-puller                system:serviceaccounts:myproject                       
Error from server (NotFound): the server could not find the requested resource (get rolebindings)
```

That last error shows that the standard watch URL (e.g. `https://openshiftapi/oapi/v1/watch/namespaces/myproject/rolebindings`) doesn't exist for that resource kind.

You'll need to raise an issue with OpenShift to understand why.

Out of interest, why do they want to watch role bindings?

**Comment by MichaelVoegele** [comment]
Our use-case is the following:
- we provide egress functionality to customers in an automated way (egress: call external services either on the internet or in core it/company internal network, and this per tenant)
- customer creates configmap, a controller listens to configmap changes and deploys a proxy (squid or haproxy) to a shadow project of the customers main project
- in order for the customer to see if the proxies are running or to have a look at the logs of the proxies, we give view rights on the shadow projects (everyone or every group that has any right on the main project is taken over to the shadow project as viewer only)
- the controller I implemented creates the shadow project when the first proxy is needed (the projects are peered, meaning set netid on shadow project equal to the netid of the main project, by the way: netnamespace in openshift provides this and netnamespace does not exist in fabric8 client, I did an own implementation)
- so when the shadow namespace is created, rolebindings are taken over as view
- changes in rolebindings on the main project shall be taken over as view to the shadow project -> listener

**Comment by MichaelVoegele** [comment]
OpenShift needs to support that, therefore, closing this issue.
