### ISSUE TITLE
define nodeAffinity for pod template

### ISSUE THREAD

**Issue by yancs** [fabric8io/kubernetes-client#777]
Is it possible to use node affinity with kubernets-client, I can only find nodeSelector, but I need to use node affinity to select nodes with matchExpressions.
thanks.

**Comment by kenangell** [comment]
I need this too.

**Comment by piyush1594** [comment]
There is Pod.podspec.affinity.nodeaffinity field in the latest client. Closing this. Feel free to reopen it if you face some issue.
