### ISSUE TITLE
Manually release the okhttpclient connections on close()

### ISSUE THREAD

**Issue by ahab94** [fabric8io/kubernetes-client#781]
Using close on the AutoAdaptableKubernetesClient isn't freeing up the okhttpclient connection threads.
Is there any other way to manually free up the resources consumed up by the client?
The OkHttp ConnectionPool are stacking up for me, want to release that manually. Is there a way around that or something on the cards for the future?

kubernetes-client version 2.3.1

**Comment by rohanKanojia** [comment]
@ahab94 : Is it still an issue in client 4.4.0 ? There was a bug in okhttp, we updated it.

**Comment by ahab94** [comment]
Hey @rohanKanojia, we switched client and it worked. Cant confirm if it's still the case.

**Comment by rohanKanojia** [comment]
oh, cool. Thanks for the feedback. Let's close it then :)
