### ISSUE TITLE
LocalSubjectAccessReview Question

### ISSUE THREAD

**Issue by alfredo-quiroga** [fabric8io/kubernetes-client#786]
Hi:

I have been unable to find how to properly structure a call to find out if a user has access to get/list projects. Any help with this is really appreciated.

Thank you in advance.

```
oc version
oc v1.5.0-alpha.3+cf7e336
kubernetes v1.5.2+43a9be4
features: Basic-Auth

```
I am trying to use the following:

```
final SubjectAccessReviewResponse subjectAccessReviewResponse = openshiftClient.getConnector().subjectAccessReviews().inNamespace("default")
.create(new LocalSubjectAccessReviewBuilder().withNamespace("default").withVerb("get")
						.withResource("namespaces").withUser("developer").build());
```

However, I get the following exception:

```{"timestamp":1497551322073,"status":500,"error":"Internal Server Error","exception":"io.fabric8.kubernetes.client.KubernetesClientException","message":"Failure executing: POST at: https://localhost:8443/oapi/v1/namespaces/default/subjectaccessreviews. Message: LocalSubjectAccessReview in version \"v1\" cannot be handled as a SubjectAccessReview: converting (v1.LocalSubjectAccessReview) to (api.SubjectAccessReview): Groups not present in src. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=LocalSubjectAccessReview in version \"v1\" cannot be handled as a SubjectAccessReview: converting (v1.LocalSubjectAccessReview) to (api.SubjectAccessReview): Groups not present in src, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).","path":"/results"}```

**Comment by rohanKanojia** [comment]
@alfredo-quiroga : Still facing problems with LocalSubjectAccessReview? It's been a while
