### ISSUE TITLE
apiserver return 404 when create job 

### ISSUE THREAD

**Issue by zimmem** [fabric8io/kubernetes-client#788]
apiserver version 1.5

io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: http://10.1.4.2:8080/apis/batch/v2alpha1/namespaces/default/jobs. Message: the server could not find the requested resource. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=null, name=null, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=the server could not find the requested resource, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).

**Comment by SGD14** [comment]
Same problem here, there is no way to make jobs api calls use v1 api instead of v2alpha1.

It seems we need to wait for this https://github.com/fabric8io/kubernetes-client/pull/779 pull request to get accepted and deployed with the fix.

**Comment by Ajk4** [comment]
I am also affected. I managed to work around it though.

More details for interested:

Check method `ExtensionsAPIGroupClient#jobs` it calls some shortened constructor for JobOperationsImpl class without apiVersion, thats results in using `v2alpha1` value in base constructor. You can use the full constructor, provide apiVersion and fill rest of arguments with same values as shortened constructor.

My workaround code in scala:
```
import io.fabric8.kubernetes.client.ExtensionsAPIGroupClient
import io.fabric8.kubernetes.client.dsl.ExtensionsAPIGroupDSL
import io.fabric8.kubernetes.client.dsl.internal.JobOperationsImpl

object ExtensionsJobsApiVersionFixer {

  implicit class FixedApiVersionOps(extensions: ExtensionsAPIGroupDSL) {

    // Default constructor passes api version = "v2alpha1"
    // see https://github.com/fabric8io/kubernetes-client/issues/788
    //
    // This workaround mimics original constructor client.extensions().jobs()
    // but provides proper api value.
    def jobsWithApiFixed(): JobOperationsImpl = {
      val extensionsClient = extensions.asInstanceOf[ExtensionsAPIGroupClient]

      new JobOperationsImpl(
        extensionsClient.getHttpClient,
        extensions.getConfiguration,
        "v1",
        extensions.getNamespace,
        null,
        null,
        null,
        null,
        false,
        -1,
        new java.util.TreeMap[String, String],
        new java.util.TreeMap[String, String],
        new java.util.TreeMap[String, Array[String]],
        new java.util.TreeMap[String, Array[String]],
        new java.util.TreeMap[String, String]
      )
    }

  }

}
```

**Comment by piyush1594** [comment]
I think we can close this issue, this is not the case anymore. cc @rohanKanojia @dev-gaur

**Comment by rohanKanojia** [comment]
Thanks :+1: , closing it for now.
