### ISSUE TITLE
Does this client supports drain command?

### ISSUE THREAD

**Issue by gjw0317** [fabric8io/kubernetes-client#789]
Does this client supports drain command?

https://kubernetes.io/docs/user-guide/kubectl/v1.6/#drain

If so, someone please share a sample with me.

**Comment by anitakar** [comment]
To drain resources you need to use eviction api (https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/). Eviction is an operation on pod (example url: http://127.0.0.1:8080/api/v1/namespaces/default/pods/quux/eviction). I do not see evict operation on pod so I guess drain operation is not supported.

**Comment by rohanKanojia** [comment]
@gjw0317 : Is drain command supported in latest Kubernetes versions? Your link is giving 404
