### ISSUE TITLE
Manifest file missing osgi headers

### ISSUE THREAD

**Issue by emanoelxavier** [fabric8io/kubernetes-client#822]
When attempting to use this client within a bundle I encountered resolution issues. When digging deeper I noticed that although this project pom contains the maven-bundle plugin it does not include the osgi headers (.e.: Bundle-Name) in the manifest file. This is also the case on the dependencies available on maven central. 
Once I changed the code with this
```
<artifactId>maven-bundle-plugin</artifactId>
<extensions>**true**</extensions> 
```
and
```
<packaging>bundle</packaging>
```
Looks like the manifest now includes the headers. 
If this is by design it seems this is not a proper osgi bundle in which case please provide instructions on how it should be used with osgi.

**Comment by oscerd** [comment]
Hello @emanoelxavier 

How do you try to use this as bundle? For example in camel we define a feature and we use a bundle dependency like this one

```
<bundle dependency='true'>mvn:io.fabric8/kubernetes-client/${kubernetes-client-version}/jar/bundle</bundle>
```

Can you elaborate a bit more? Thanks :-)
