### ISSUE TITLE
duplicate classes in kubernetes-client and openshift-client jars

### ISSUE THREAD

**Issue by errantepiphany** [fabric8io/kubernetes-client#828]
The following classes exist in both the kubernetes-client and openshift-client jar 2.5.7 distributions.

```
io.fabric8.kubernetes.client.ConfigBuilder
io.fabric8.kubernetes.client.ConfigFluent
io.fabric8.kubernetes.client.ConfigFluentImpl
```

If one uses the maven-enforcer-plugin's ban-duplicated-classes capability, these classes cause builds to fail unless the plugin is configured to ignore them.

The duplicate classes should get removed from the openshift-client jar since they already exist in kubernetes-client jar. If they are supposed to be different, they should be named or packaged differently to avoid collision.

**Comment by errantepiphany** [comment]
Not sure if this has been addressed yet... I will need to look in the jars to see...

**Comment by wilx** [comment]
I have just hit this too. I am trying to clean up build so that `org.apache.maven.plugins.enforcer.BanDuplicateClasses` passes.
