### ISSUE TITLE
Why there is no RoleBinding or RoleBindingBuilder in kubernetes package

### ISSUE THREAD

**Issue by sugarbyheart** [fabric8io/kubernetes-client#831]
I have noticed that, there is `RoleBinding` or `RoleBindingBuilder` in `io.fabric8.openshift.api.model`, but I cannot find them in `io.fabric8.kubernetes.api.model`, it that mean there is no way to deal with `RoleBinding` in Kubernetes cluster?

**Comment by dtandersen** [comment]
Did you find out if openshift worked? I also need to create rolebindings in kubernetes.

**Comment by piyush1594** [comment]
This has been resolved using #1111
