### ISSUE TITLE
envFrom on Container

### ISSUE THREAD

**Issue by joan38** [fabric8io/kubernetes-client#834]
Hi,

How do we set `envFrom` on a `Container`?
See: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/

Cheers

**Comment by joan38** [comment]
https://github.com/fabric8io/kubernetes-model/issues/216

**Comment by yunlzheng** [comment]
How's this going? When i use fabric java client upgrade the deployment the envFrom fields will missing. and cause the pod crashed.

**Comment by rohanKanojia** [comment]
@yunlzheng : Hi, Is it still an issue? I see the linked issue in kubernetes-model is closed.
