### ISSUE TITLE
client.Pod vs model.Pod

### ISSUE THREAD

**Issue by joshk0** [fabric8io/kubernetes-client#839]
Hi there, apologies if this is a stupid question, but I find it very strange that when I create a Pod, I cannot watch it or get its log from the returned object. I have to do something like this instead:

```java
    // Create the Pod object.
    final Pod createdPod = client.pods().create(pod);

    // We don't know the actual, created Pod name ahead of time. (I use 'generateName')
    final String podName = createdPod.getMetadata().getName();

    // We can't just do createdPod.getLog(), we have to get the Pod from the Client.
    setOutput(OUTPUT, client.pods().inNamespace(podNamespace).withName(podName).getLog());
```

I would prefer for it to look like this:

```java
    // Create the Pod object.
    final Pod createdPod = client.pods().create(pod);
    setOutput(OUTPUT, createdPod.getLog());
```

Is there a reason why the returned object is not of the correct type to call these getLog and watch methods on?

**Comment by joshk0** [comment]
Bump

**Comment by rohanKanojia** [comment]
Umm, Not sure if this is possible right now because `Pod` resource maps to the go structs in kubernetes. So what you see as returned object is just the deserialized form of kube server response. Although you can do something like this:
```
        client.pods().create(pod);
        PodResource<Pod, DoneablePod> createdPod = client.pods().inNamespace(namespace).withName("xyz");
        setOutput(OUTPUT, createdPod.getLog());
```

**Comment by joshk0** [comment]
Thats fine. I don't even work with this project anymore as 2 years have passed. Anyway, if this is by design, I'm not going to push it further. :) Thanks for answering
