### ISSUE TITLE
Parsing CustomResources

### ISSUE THREAD

**Issue by yoks** [fabric8io/kubernetes-client#840]
We have custom resources definition in our kubernetes cluster e.g.
https://kubernetes.default/apis/example.com/v1/namespaces/default/routerrules/

I not found any way to aquire this resource, is there any way i can provide custom definition or request raw json and parse it myself?

**Comment by Frusty** [comment]
I would be interested into this as well. Are there "clean" ways using the client to list and interact with CustomResources?

**Comment by rjeberhard** [comment]
While I'd prefer a way to create a fluent resource, I'd be happy with just being able to access the resource.  Has anyone figured out a way to even access a custom resource?

**Comment by jstrachan** [comment]
here's a PR to support working with CRD instances
https://github.com/fabric8io/kubernetes-client/pull/890

e.g. here's it in action to list instances of a CRD and create/replace one:
https://github.com/jstrachan/kubernetes-client/blob/b0db77a88e9ff831c67e063061bcc0467e8fee9a/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java#L106-L109

**Comment by valdar** [comment]
I guess this one can be closed.
