### ISSUE TITLE
InputStreamPumper should not use InputStream.available()

### ISSUE THREAD

**Issue by davidwtf** [fabric8io/kubernetes-client#843]
In version 2.6.1，InputStreamPumper used in.avaliable() at line 59. In the 'watchLog' processing, the InputStream is from okio.RealBufferedSource。According to okio.RealBufferedSouce's source code, available() returns buffer.size, the buffer never set until read(). 
But the InputStreamPumper doesn't read() before calling available(), so available() alwalys returns 0.
I cannot get logs when change to 2.6.1 from 2.4.1.

**Comment by kfSnow** [comment]
Nice diagnosis! I also noticed the log streaming break when I updated from 2.2.9 to 2.6.1 since I needed the recent Jobs API version fix. I got as far as concluding it just never read anything in the pumper.

**Comment by jwendell** [comment]
@davidwtf, why did you close this one? I don't think it is fixed...

**Comment by davidwtf** [comment]
Sorry, I've seen the code changed, thought it's fixed. @jwendell

**Comment by iocanel** [comment]
It seems that we can neither use `available()` nor switch to blocking (pumper no longer responds to interruption. So, I am seriously considering rolling back to blocking and have the `close()` method of the pumper actually close the socket (via the `onClose()` callable).

Before, I implement something like this, I'd like to hear thoughts about it, and if anyone would like to pick this up :-)

**Comment by jwendell** [comment]
@iocanel when you say `close the socket` what do you mean? Is that possible?

**Comment by jwendell** [comment]
Currently we are closing the response body's stream, which makes InputStreamPumper's `in.read()` to return. That does not solve the problem of the hanging threads though, as I stated in #844 .

**Comment by iocanel** [comment]
We need to do two things:

- revert the stream pumper to non blocking
- make sure we close the stream / socket when we are done

The Log watch stuff was already working like that, until  61ae6ed broke it.
The ExecWebsocketListener though wasn't working like that.

What I had in mind is to do to the exec web socket listener something similar. (just closing the response body is not enough and doesn't work).

**Comment by iocanel** [comment]
I've tried a lot of different things, but I can't find one size that fits, all.

I will create two different implementation of the pumper and use each where it makes sense.
