### ISSUE TITLE
How to achieve the vim in terminal?

### ISSUE THREAD

**Issue by smile-soul** [fabric8io/kubernetes-client#846]
Hi,
  I want to achieve the vim in terminal, but i don't know how to achieve the terminal, In client I already have been used websocket and achieve the most of unix commands. I don't know how to achieve to edit a file of methods.  i saw the terminal was used to send a word through websocket.
 But i still can't  understand the theory of the vim in terminal.please give me a example.

thanks.

**Comment by oscerd** [comment]
Can you please explain a bit more? It's not clear.

**Comment by smile-soul** [comment]
Thanks
   I have searched the source code and resolved the problem.
