### ISSUE TITLE
The client is hitting a wrong API endpoint 

### ISSUE THREAD

**Issue by roughbits01** [fabric8io/kubernetes-client#847]
Hello,

When I try to get a list of resources (for example, the list of nodes) using kubernetes-client, it tries to access http://192.168.99.100:30000/api/v1/nodes so I get an error (404 Not Found) while the correct endpoint is http://192.168.99.100:30000/api/v1/node (without the s).

Thank you in advance.

**Comment by rohanKanojia** [comment]
Is this still an issue? I can see correct plural form here: 
https://github.com/fabric8io/kubernetes-client/blob/736ac8df8c64da96b877628fd46b8299b3383e71/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/NodeOperationsImpl.java#L33-L36
