### ISSUE TITLE
unable to connect to openshift project behind proxy

### ISSUE THREAD

**Issue by VR1998** [fabric8io/kubernetes-client#848]
Hello
We are trying to configure kubernetes plugin to connect to openshift project via external jenkins instance.
However we are getting the following message in the log

Aug 23, 2017 9:43:25 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesFactoryAdapter createClient
FINE: Creating Kubernetes client: KubernetesFactoryAdapter [serviceAddress=https://xxx.xxxx.xxxx:8443, namespace=cicd-jenkins-intg, caCertData=null, credentials=org.csanchez.jenkins.plugins.kubernetes.OpenShiftTokenCredentialImpl@53c4116e, skipTlsVerify=true, connectTimeout=0, readTimeout=0]
Aug 23, 2017 9:43:35 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$DescriptorImpl doTestConnection
FINE: Error connecting to https://xxx.xxxx.xxxx:8443
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Pod]  with name: [null]  in namespace: [cicd-jenkins-intg]  failed.

We tried to enable following environment variable

export KUBERNETES_HTTP_PROXY=xxxx.xxxx.xxxx
export KUBERNETES_HTTPS_PROXY=xxxx.xxxx.xxxx
export KUBERNETES_NO_PROXY=.xxx,.xxx
export KUBERNETES_SERVICE_HOST=xxxx
export KUBERNETES_SERVICE_PORT=8443
export KUBERNETES_MASTER=https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}

Not sure if they are being used by plugin or not.

Any ideas what could be wrong here ?

**Comment by carlossg** [comment]
this is a duplicate of https://issues.jenkins-ci.org/browse/JENKINS-55123
