### ISSUE TITLE
Projected Volumes

### ISSUE THREAD

**Issue by podviaznikov** [fabric8io/kubernetes-client#851]
It seems that there is new feature in k8s called projected volumes https://kubernetes.io/docs/tasks/configure-pod-container/configure-projected-volume-storage/

That allows to do following things: https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/tasks/configure-pod-container/projected-volume.yaml#L18

I couldn't find it but it seems that this feature is not yet supported in the client. Is this true or did I miss something?

**Comment by oscerd** [comment]
It's not supported yet.

**Comment by podviaznikov** [comment]
@oscerd do you know about timeline on that? is it on the roadmap or not really?

**Comment by oscerd** [comment]
This is a question for @iocanel and @jimmidyson :-)

**Comment by jimmidyson** [comment]
We don't have a roadmap... sorry! Features like this get updated as required/requested. The quickest way for this to happen is for people to send in PRs that add this.

I'm sure @iocanel would agree, but if anyone is interested in helping to maintain this project, we would be really grateful.

**Comment by hrishin** [comment]
@podviaznikov it's available now in the recent release :)
