### ISSUE TITLE
Editing a pod that has tolerations causes error

### ISSUE THREAD

**Issue by faceitdev** [fabric8io/kubernetes-client#853]
I have a pod running on the cluster that contains tolerations and taints.

I want to edit the labels, and I try to do 

```java
mypod = client.pods().withName(podname)
.edit()
.withNewMetadata()
.addToLabels(newmetadata)
.endMetadata()
.done();
```

but the operation fails because

"Forbidden: existing toleration can not be modified except its tolerationSeconds, spec: Forbidden: pod updates may not change fields other than `containers[*].image` or `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)]."
I guess the client is trying to patch the resource by sending everything, instead of only what changed.

This is the example found in the documentation, am I doing something wrong?

**Comment by jrfeenst** [comment]
I ran into a similar issue when adding labels to pods. The patch json was:

[{"op":"add","path":"/metadata/labels/userName","value":"joelfeenstra"},{"op":"add","path":"/metadata/labels/sessionId","value":"node0wp8vdbz3qjgvgnbr4m464p9i1"},{"op":"remove","path":"/metadata/ownerReferences/0/bloc
kOwnerDeletion"},{"op":"remove","path":"/spec/containers/0/terminationMessagePolicy"},{"op":"remove","path":"/spec/containers/1/terminationMessagePolicy"},{"op":"remove","path":"/spec/containers/2/terminationMessagePolicy"},{"op":"remove",
"path":"/spec/containers/3/terminationMessagePolicy"},{"op":"remove","path":"/spec/volumes/0/emptyDir/sizeLimit"},{"op":"remove","path":"/spec/volumes/1/emptyDir/sizeLimit"},{"op":"remove","path":"/spec/automountServiceAccountToken"},{"op"
:"remove","path":"/spec/schedulerName"},{"op":"remove","path":"/status/qosClass"}]

I think either the json diff needs to ignore pod fields that can't be edited, or the updated pod needs to properly copy all of these fields from the current pod.

**Comment by igorcanadi** [comment]
We ran into a similar issue -- editing a deployment using the fabric8 client drops the tolerations from the deployment.

**Comment by tudor** [comment]
Does the model need to be updated first (https://github.com/fabric8io/kubernetes-model/issues/214)? or can the code be changed to passthrough fields that can't be edited, as @jrfeenst suggested above?

**Comment by matthyx** [comment]
Good news everyone, the model now supports toleration!
Is anyone interested in adding this support to the client, or should I do it?
Also, can someone mark https://github.com/fabric8io/kubernetes-client/issues/826 as a duplicate?

**Comment by chirino** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  chirino@gmail.com
    Domain hiramchirino.com has exceeded the max emails per hour (164/150 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from out-6.smtp.github.com ([192.30.252.197]:52329)
	by host313.hostmonster.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1f0Nmg-0013ZN-9i
	for hiram@hiramchirino.com; Mon, 26 Mar 2018 02:47:18 -0600
Date: Mon, 26 Mar 2018 01:47:05 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1522054025;
	bh=mXVXTjdYGVySIYQq98TzChPO8NBJspWqZKfey1bSCv4=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=HjGyfFEi3qKvv5J5FNSRXaSA/mN7W5PZiLhia9/d+599xRx2Pkd2o4now+a6XvBMq
	 z9cwBpDsXBeK/IgOYPzpx/PI0zo+GxtZhf5+48ulvGkdt2BIda7BjJv7ZpDPy+M6n1
	 jb2LnhQ2GGSfc3InFmPMpGUQLrwXJRTmfQU9lAEA=

**Comment by piyush1594** [comment]
Hey @faceitdev ,

Can you please try this,

`client.pods().withName(podName).patch(pod);`

Thanks

**Comment by piyush1594** [comment]
Hey @matthyx 

Have you tried this also? Is this still an issue or we can close this.

**Comment by matthyx** [comment]
@piyush1594 I have tried successfully that on a pod with tolerations:
```
client.pods().withName(podname)
	.edit()
	.editOrNewMetadata()
	.addToAnnotations("key1", "value1")
	.endMetadata()
	.done();
```
So, to me this issue is solved too.

**Comment by piyush1594** [comment]
cool, Thanks a lot for trying. I am closing this.
