### ISSUE TITLE
watch pods eventReceived is  a few days ago dirty data,kubernetes is nothing。

### ISSUE THREAD

**Issue by xuqinghou** [fabric8io/kubernetes-client#854]
watch pods eventReceived is  a few days ago dirty data,kubernetes is nothing。

**Comment by oscerd** [comment]
Can you elaborate a bit more please?

**Comment by xuqinghou** [comment]
Watch watch = client.pods().watch(new Watcher<Pod>() {
					@Override
					public void eventReceived(Action action, Pod pod) {
		                //Here received event is historical data，this moment kubernetes is no event.
		                //this pod start time is 2017-08-29T06:03:38Z，Here received event is repeated at 2017-08-30T22:03:38Z
					}

					@Override
					public void onClose(KubernetesClientException e) {


					}
				})
