### ISSUE TITLE
How to detect server version

### ISSUE THREAD

**Issue by rjeberhard** [fabric8io/kubernetes-client#861]
We will be supporting CustomResourceDefinitions, but also need to support ThirdPartyResource variants for server versions < 1.7.  How can I detect the server version?

For instance, if I had the following environment:

[rjeberha@den00qkr operator]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

How could I detect with kubernetes-client that this server doesn't support CustomResourceDefinitions?

**Comment by piyush1594** [comment]
@rjeberhard 

Support for this has been added in https://github.com/fabric8io/kubernetes-client/pull/1054 and available in client 3.1.12 Thanks
