### ISSUE TITLE
add weakly typed API for accessing unknown types

### ISSUE THREAD

**Issue by jhalliday** [fabric8io/kubernetes-client#864]
Sometimes new extensions to the server API come along. It would be useful to allow these to be accessed from existing client versions, without needing to wait for a new client release to add explicit object types for them. see e.g. issues/863 for TemplateInstance support.

**Comment by rohanKanojia** [comment]
we have added another raw custom resource api which is weakly typed.Have a look at this example:
https://github.com/fabric8io/kubernetes-client/blob/736ac8df8c64da96b877628fd46b8299b3383e71/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/RawCustomResourceExample.java#L36-L50

**Comment by rohanKanojia** [comment]
Closing this as we seem to have this support
