### ISSUE TITLE
"Namespace not specified." exception on a non-namespaced OpenShift operation

### ISSUE THREAD

**Issue by dimonv** [fabric8io/kubernetes-client#881]
Hello all,

I'm trying to execute ClusterRoleBindingOperationsImpl  but getting an exception:
`io.fabric8.kubernetes.client.KubernetesClientException: Namespace not specified. But operation requires namespace.`
But the OpenShift doc says:
> You can also manage role bindings for the cluster policy using the following operations. The -n flag is not used for these operations because the cluster policy uses non-namespaced resources.
> 

I think it is a bug, unless I use it in a wrong way.
Please provide an example.

Thanks and kind regards,
Dmitri

**Comment by rohanKanojia** [comment]
Could you please provide a test case to reproduce your issue?
