### ISSUE TITLE
LogWatch following not working

### ISSUE THREAD

**Issue by thorbenvh8** [fabric8io/kubernetes-client#883]
Hi,
`String namespace = "namespace";
String name = "name";
String container = "container";
this.kubernetesClient.pods()
			.inNamespace(namespace)
			.withName(name)
			.inContainer(container)
			.tailingLines(0)
			.watchLog(System.out);`

Running a container with the following simple image code
``while true; do echo `date`; sleep 1; done``
was good for testing for me.
It should give me sysouts every second to the console.

It was working in 2.4.1,
tested with 2.6.3 and 3.0.0 (both not working)
I debugged a little and somehow the InputStreamPumper (method run()) was trying to push informations but the in.available() was always 0.

Am I using the api wrong, did something change?
Any help would be very appreciated :)

**Comment by zxbu** [comment]
I hava a same problem

**Comment by zxbu** [comment]
I have the same problem

**Comment by zxbu** [comment]
My solution：
Copy 2.4.1`s PodOperationsImpl.java、LogWatchCallback.java、InputStreamPumper.java to my self project,
And use 
```
 PodOperationsImpl podOperations = new PodOperationsImpl(defaultKubernetesClient.getHttpClient(), defaultKubernetesClient.getConfiguration(), namespace);
```

**Comment by asacbp** [comment]
Nice finding @zxbu 

Looking at those three files and the diff from 2.4.1 the following seem to be the only real changes unless I missed something:

https://github.com/fabric8io/kubernetes-client/commit/61ae6ed33fbe19dd49d3b34d206257e77d39355e

https://github.com/fabric8io/kubernetes-client/commit/239c4faf0e8c254ddb07ce6c0d11dfcf5a742159

@zxbu maybe try to back either of these out of your local build?

**Comment by thorbenvh8** [comment]
i tried it out it was simple :)
it is in [61ae6ed](https://github.com/fabric8io/kubernetes-client/commit/61ae6ed33fbe19dd49d3b34d206257e77d39355e)

replace 
`while (in.available() > 0 && keepReading && !Thread.currentThread().isInterrupted()) {`
with
`int length;
				while (this.keepReading && !Thread.currentThread()
					.isInterrupted() && (length = this.in.read(buffer)) != -1) {`

i will make a pull request for this :)

thanks so much for all your help :)

**Comment by thorbenvh8** [comment]
sorry im some how not able to create a new branch and a pull request, always giving me access denied.
I wonder what im doing wrong here. Maybe @zxbu you can create the pull request? :)

**Comment by zxbu** [comment]
@thorbenvh8 I`ve just  created a new pull request.

**Comment by thorbenvh8** [comment]
@zxbu thank you
just one question. was i doing something wrong or do you need special rights?

**Comment by asacbp** [comment]
3.0.3 release works great. this issue can be closed! @thorbenvh8 ^^

**Comment by hrishin** [comment]
this issue is fixed
