### ISSUE TITLE
Quantity doesn't honor the unit

### ISSUE THREAD

**Issue by rhuss** [fabric8io/kubernetes-client#885]
When using the two-argument constructor of Quantity like in `new Quantitity("256","Mi")`, then the unit is ignored when creating the descriptors. Workaround: `new Quantity("256 Mi")`

See https://github.com/syndesisio/syndesis-rest/issues/713 where this happened in the wild.

**Comment by boxcee** [comment]
Facing the same issue.

**Comment by slandelle** [comment]
No reason to automatically close this issue.

**Comment by rohanKanojia** [comment]
we recently added a stale bot, it usually removes the label if you comment ;-)

**Comment by slandelle** [comment]
Hence my comment

**Comment by rhuss** [comment]
@rohanKanojia btw, you can configure in stale-bot a label .e.g "never-stale", which, when applied, keeps the issue open forever.

See e.g. https://github.com/syndesisio/syndesis/blob/e08608e848142874edbe7938aea8e325d3d27edd/.github/stale.yml#L3-L6

**Comment by rohanKanojia** [comment]
@dev-gaur : Hi, do you have `never-stale` configuration on stale bot on this repo?

**Comment by rhuss** [comment]
@rohanKanojia yes -> https://github.com/fabric8io/kubernetes-client/blob/1e027b27de29ae230fa992914a1714216dd124b7/.github/stale.yml#L19-L21

You just have to create those label and then apply it to this issue.

**Comment by rohanKanojia** [comment]
@rhuss : Thanks, I've added the label

**Comment by rhuss** [comment]
@rohanKanojia I think it should be `status/never-stale`, not only `never-stale`. 

Alternatively, adapt the `stale.yml`

**Comment by rohanKanojia** [comment]
ah, apologies. Let me update label name
