### ISSUE TITLE
io.fabric8.kubernetes.client.internal.CertUtils.createTrustStore() fails if decoded certificate has an extra newline

### ISSUE THREAD

**Issue by traviswinter** [fabric8io/kubernetes-client#902]
Encountered an issue where the Kubernetes client could not connect because there was an extra newline at the end of the decoded certificate (it must have been there when it was decoded).  This causes the pemInputStream.available() to show 1 (since there's 1 additional byte) and causes the client to error out.

I'm not too familiar with certificate standards, but I was able to use the Kubernetes config file directly with the base64 encoded certificate even with the extra newline at the end.

Not sure if this project would like to make that code a little more robust (maybe in the getInputStreamFromDataOrFile() method) by removing any extra newlines except for the last one.

ex (added . to indicate newlines):

>  GUbDzbzv
> -----END CERTIFICATE-----
>  .
>  .

versus:

>  GUbDzbzv
> -----END CERTIFICATE-----
>  .

**Comment by rohanKanojia** [comment]
@traviswinter : Polite ping, is this still an issue on the latest version?
