### ISSUE TITLE
Pod Exec Websocket Error

### ISSUE THREAD

**Issue by ckanner** [fabric8io/kubernetes-client#904]
When I run the ExecExample，it occurs the error ```io.fabric8.kubernetes.client.KubernetesClientException: Upgrade request required```. I use kubernetes proxy, and set ```--disable-filter=true```.
I debug this problem, and find okhttpclient use HTTP 1.1 to exec watch.
Is there any solution?

**Comment by rohanKanojia** [comment]
@kunal-kushwaha : Could you please check if this error is still there in ExecExample? Have you tried it before?

**Comment by kunal-kushwaha** [comment]
@rohanKanojia: I just ran this example and it did not show any errors.

**Comment by rohanKanojia** [comment]
@kunal-kushwaha : Thanks, let's close it then.
