### ISSUE TITLE
Support ImageStreamImage ?

### ISSUE THREAD

**Issue by kaimago** [fabric8io/kubernetes-client#905]
Is kubernetes-client supporting openshift ImageStreamImage api ? Couldn't find it :(

**Comment by hrishin** [comment]
@kaimago here you go for the example https://github.com/fabric8io/kubernetes-client/blob/ef8057f363e2fbe6c28958de98c492be260ac865/kubernetes-examples/src/main/java/io/fabric8/openshift/examples/ImageStreamTagExample.java

**Comment by kaimago** [comment]
Thanks :)
