### ISSUE TITLE
Support complete app deployment with multiple pods, services using yaml file

### ISSUE THREAD

**Issue by rishi-anand** [fabric8io/kubernetes-client#906]
As one can deploy a **complete app from kubernetes dashboard by uploading yaml file** and **based on content of yaml file respective kubernetes resource is created**. 

Using _fabric8 kubernetes-client_, I am able to _create a kubernetes resource using yaml file but I have to select the resource I am about to create_. Below is the example of creating pod from yaml file.

Example: 
```
            InputStream inputStream = new FileInputStream("/Users/risanand/test.yml");
            Pod podTemplate = client.pods().load(inputStream).get();
            Pod createdPod = client.pods().create(podTemplate);
```

There should be an api to create kubernetes resource without specifying resource type after getting client handle.

Please let me know if such api is already there in place.

**Comment by rishi-anand** [comment]
@iocanel, @jimmidyson, @fusesource-ci Please help on this. I am trying to create a small project where I will be given a complete yaml file with all tiers defined in it and I have to get all resources up and running.

**Comment by iocanel** [comment]
@rishi-anand: You can just use: `client.load(inputstream).create()` or `client.load(inputstream).createOrReplace()`.

**Comment by rishi-anand** [comment]
Thanks @iocanel 👍

**Comment by harshajith** [comment]
However, this still does not work if you have multiple yml resources embedded in one file, it only creates the first resource and ignores the rest.

**Comment by oscerd** [comment]
@harshajith this is already part of an issue: https://github.com/fabric8io/kubernetes-client/issues/1004
