### ISSUE TITLE
Thread Safe?

### ISSUE THREAD

**Issue by OmriShiv** [fabric8io/kubernetes-client#907]
Looking through the documentation and parts of the code, I'm wondering if it thread safe. I have it declared once in a wrapper and being reused, just want to make sure I don't run into any issues.

**Comment by jimmidyson** [comment]
Yes the client is thread safe.

**Comment by egor-ryashin** [comment]
I guess that information should be in a class description.

**Comment by rohanKanojia** [comment]
@egor-ryashin : Could you please elaborate? You mean the information is still missing in latest versions?

**Comment by egor-ryashin** [comment]
This no information in the class description (ie javadoc):
![image](https://user-images.githubusercontent.com/14215045/68599592-e4a59200-04b1-11ea-928d-be8d7abc0d5c.png)

**Comment by rohanKanojia** [comment]
Could you please raise a pr to fix this, if possible?

सोम, 11 नव॰ 2019, 21:04 को Egor Riashin <notifications@github.com> ने लिखा:

**Comment by egor-ryashin** [comment]
@rohanKanojia I wonder if you mean `raise an issue`?

**Comment by rohanKanojia** [comment]
I meant send us a patch to add that documentation. But if you don't have
time, I'm good with opening issue for this.

सोम, 11 नव॰ 2019, 21:33 को Egor Riashin <notifications@github.com> ने लिखा:
