### ISSUE TITLE
is v1.Binding supported?

### ISSUE THREAD

**Issue by raffaelespazzoli** [fabric8io/kubernetes-client#908]
I looking for this API:
https://kubernetes.io/docs/api-reference/v1.8/#binding-v1-core
I can't find it and I'm thinking that it is not supported.
can someone advise?

**Comment by rohanKanojia** [comment]
we added support for RBAC during initial 4.x releases. Can we close this if you were looking for that?

**Comment by rohanKanojia** [comment]
Duplicate of #1816
