### ISSUE TITLE
How to use TimeBuilder and Time to create events with version 3.x

### ISSUE THREAD

**Issue by MichaelVoegele** [fabric8io/kubernetes-client#909]
Hi
So far, with version 2.x, I used the following to create events:
`Date currentTimestamp = new Date();
String timestamp = currentTimestampAsIso8601(currentTimestamp);
eventBuilder.withFirstTimestamp(timestamp).withLastTimestamp(timestamp).withCount(new Integer(1)).withKind(EVENT_KIND).withType(type).withReason(reason).withMessage(message);
...`
With version 3.x, `io.fabric8.kubernetes.api.model.TimeBuilder` and `io.fabric8.kubernetes.api.model.Time` need to be used to create events.
Unfortunately, I cannot get this working, I am getting some exceptions about invalid format.
Is there any example on how to use TimeBuilder and Time to create events?
Thank you and regards
Mike

**Comment by iocanel** [comment]
I don't see that class being part of the model. It seems that its missing from kubernetes-model 2.x. We need to check if it has been replaced or if it somehow slipped.

**Comment by jimmidyson** [comment]
Although the type in kubernetes API is Time, it is simply a date formatted (rfc3339 iirc) as a string. The time builder probably complicates things from the 2.x way of doing things.

**Comment by MichaelVoegele** [comment]
Hello
Thank you for your answers. I see now with version 3.1.0 that things changed back to as they were with version 2.x. So, no more issue with 3.1.0.
Regards
