### ISSUE TITLE
 How to identify proper fabric8io/kubernetes-client version for k8s 1.8?

### ISSUE THREAD

**Issue by duyanghao** [fabric8io/kubernetes-client#911]
I want to update `fabric8io/kubernetes-client` to support our  `k8s cluster`(**1.8 version**).But there seems to be no reference about correspondence between `fabric8io/kubernetes-client` and `k8s` version [here](https://github.com/fabric8io/kubernetes-client).

Addition:
I am using `fabric8io/kubernetes-client` version: 2.2.

**Comment by rishi-anand** [comment]
You can use version 3.0.3 to use k8s 1.8 features.
Deployment, replica set etc is supported as extensions.

```
            Deployment deployment = client.extensions().deployments()
                    .inNamespace("default")
                    .withName("nginx-deployment").get();

```

**Comment by Rafaesp** [comment]
What abot https://kubernetes.io/docs/api-reference/v1.8/#networkpolicy-v1-networking ?

**Comment by rohanKanojia** [comment]
https://www.ndtv.com/offbeat/watch-aircrafts-grand-entrance-through-clouds-is-viral-2081423?pfrom=home-lateststories
