### ISSUE TITLE
Add possibility to change MaxRequests on Dispatcher in HttpClientUtils

### ISSUE THREAD

**Issue by thorbenvh8** [fabric8io/kubernetes-client#914]
Just an improvement, instead of being only able to update the MaxRequestsPerHost for the dispatcher. You can now update the MaxRequests as well (default otherwise always 64).

Thanks for merging this quickly :)

**Comment by ckanner** [comment]
I also occurs the phenomenon.When there are many websocket's connections, some of them will stay in the executor pool and waiting for to schedule.The reason is the ```maxRequestsPerHost``` and ```maxRequests``` to limit them.

So I use the way to fix this problem
```java
final Config config = new ConfigBuilder()
            .withMasterUrl(k8sProperties.getRestUri())
            .withTrustCerts(true)
            .withNamespace(k8sProperties.getNamespace())
            .build();
        final Dispatcher dispatcher = new Dispatcher();
        dispatcher.setMaxRequestsPerHost(k8sProperties.getMaxRequests());
        dispatcher.setMaxRequests(k8sProperties.getMaxRequests());
        final OkHttpClient httpClient = HttpClientUtils.createHttpClient(config).newBuilder().dispatcher(dispatcher).build();
        KubernetesClient client = new AutoAdaptableKubernetesClient(httpClient, config);
```

May be the ```Config``` class can support defines the maxRequests.

**Comment by thorbenvh8** [comment]
please see the pull request, I did exactly that :)

**Comment by ckanner** [comment]
I know. The pull request doesn't merge to the master branch.
