### ISSUE TITLE
waitUntilReady does not work for big timeouts

### ISSUE THREAD

**Issue by bouskaJ** [fabric8io/kubernetes-client#917]
For example:
```
...waitUntilReady(5L, TimeUnit.MINUTES);
```
does not work because it timeouts too early.

I think the main problem is on [this](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/DeploymentOperationsImpl.java#L165) line.

```
return periodicWatchUntilReady(10, System.currentTimeMillis(), Math.max(timeUnit.toMillis(amount) / 10, 1000L), amount);
```

And if I see the documentation of *periodicWatchUntilReady* method it says:
```
 /**
   * A wait method that combines watching and polling.
   * The need for that is that in some cases a pure watcher approach consistently fails.
   * @param i           The number of iterations to perform.
   * @param started     Time in milliseconds where the watch started.
   * @param interval    The amount of time in millis to wait on each iteration.
   * @param amount      The maximum amount in millis of time since started to wait.
   * @return            The {@link ReplicationController} if ready.
   */
```

So if I understand it correctly, the param amount is the timeout in **MILIS** but in my case the param is in **MINUTES**.

Shouldn't the code looks like:
```
return periodicWatchUntilReady(10, System.currentTimeMillis(), Math.max(timeUnit.toMillis(amount) / 10, 1000L), timeUnit.toMillis(amount));
```

**Comment by piyush1594** [comment]
@bouskaJ I think the issue has been fixed now, Can you please check and confirm?
