### ISSUE TITLE
How to create a CronJob?

### ISSUE THREAD

**Issue by jorgesartori** [fabric8io/kubernetes-client#920]
To create a deployment, I just invoke the method: KubernetesClient.extensions().deployments().createOrReplace(io.fabric8.kubernetes.api.model.extensions.Deployment);
So, I have a cronjob model created (io.fabric8.kubernetes.api.model.CronJob) but I didn't find a equivalent KubernetesClient method to create (or replace) it.

**Comment by rohanKanojia** [comment]
Duplicate of #770
