### ISSUE TITLE
Add more CRUD tests

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#923]
As of 3.1.0 our https://github.com/fabric8io/kubernetes-client/tree/master/kubernetes-server-mock supports CRUD mode, which means that instead of setting expectations, it acts as a simple crud.

Such example is https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodCrudTest.java

This test needs improvements:
- test how update works
- test listing with labels

We also need to write similar tests for other types too:

- Deployment
- Service
- ConfigMap
- Secret
- DeploymentConfig
- Route

The more types we cover the merrier.

**Comment by hrishin** [comment]
@iocanel CRUD support looks interesting.
Is it compatible with OpenShift v3.6 and v3.7?

**Comment by iocanel** [comment]
I expect it to work with openshift too. It should be completely independent of the Openshift version.
Now, if you are talking about api groups, we might need to to some tuning.
