### ISSUE TITLE
Unable to update StatefulSet if spec contains an empty "array" property

### ISSUE THREAD

**Issue by osoriano** [fabric8io/kubernetes-client#931]
**What happened**:
I made a call to:
```java
DefaultKubernetesClient(new Config())
    .apps().statefulSets()
    .inNamespace(namespace).createOrReplace(statefulSet)
```
where `statefulSet` is an object without any volumeClaimTemplates.

**What you expected to happen**:
The statefulset should have been updated.

**Anything else we need to know?**:
When Kubernetes stores the StatefulSet object using protobuf encoding, it can't distinguish between null and an empty list. If an empty volumeClaimTemplates list was sent, it will be retrieved as null.

StatefulSet VolumeClaimTemplates cannot be updated. ([See the ValidateStatefulSetUpdate function in kubernetes](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/validation/validation.go#L141)). However, when the client tries to update the statefulSet, it will send an empty volumeClaimTemplates list (due to initializeCollections set to true in the schema2pojo library). This causes a mismatch which results in the error from Kubernetes:

```
updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.
```

**Environment**:
- Kubernetes 1.8.3 using etcd storage backend with protobuf encoder

**Related**
https://github.com/fabric8io/kubernetes-client/issues/502
https://github.com/kubernetes/kubernetes/issues/43203
https://github.com/kubernetes/kubernetes/pull/43422

**Comment by jglick** [comment]
I am not sure I understand what the originally reported problem was, but I have a problem which at least sounds related. `PatchUtils` configures its mapper `without(SerializationFeature.WRITE_EMPTY_JSON_ARRAYS)` as of #615, from [ENTESB-8247](https://issues.jboss.org/browse/ENTESB-8247). I am working with a CRD whose validator requires a certain array-valued field of a struct to be non-null. If I use `Resource.replace` and pass it an object with that field initialized to `Collections.emptyList()`, all is well. But if I change the `replace` call to `patch`, I get an error from the validator complaining that the field is null; debugging `OperationSupport.handlePatch` confirms that the field is missing from the `JsonNode diff`. The only workaround I could find was to add to my program a static initializer

```java
PatchUtils.patchMapper().setConfig(PatchUtils.patchMapper().getSerializationConfig().with(SerializationFeature.WRITE_EMPTY_JSON_ARRAYS));
```
