### ISSUE TITLE
OpenShiftServer in CRUD mode returns all objects regardless of query

### ISSUE THREAD

**Issue by anderssv** [fabric8io/kubernetes-client#936]
I'm writing some tests and wanted to use OpenShiftServer with CRUD mode enabled. It seems to return all the objects regardless of the type/query I give the client.

I did some debugging and I think the culprit is because OpenShiftMockServer is instantiated with a  KubernetesAttributesExtractor which doesn't match the "/oapi/*" URLs (it matches "/api/*") so the query attributes are always blank.

**Comment by piyush1594** [comment]
This is duplicate of #1144  and has been resolved with #1145
