### ISSUE TITLE
When fabric8io/kubernetes-client supports StorageClass?

### ISSUE THREAD

**Issue by zhaorendong** [fabric8io/kubernetes-client#941]
I had found StorageClass in fabric8io/kubernetes-model, but  I can't create StorageClass by fabric8io/kubernetes-client-3.1.1.

**Comment by oscerd** [comment]
There is no handler for that. Contributions are welcome.

**Comment by oscerd** [comment]
Done with this 

https://github.com/fabric8io/kubernetes-client/pull/978

**Comment by oscerd** [comment]
It will be released in 3.1.9
