### ISSUE TITLE
kubernetes version compatability

### ISSUE THREAD

**Issue by jiaj12** [fabric8io/kubernetes-client#946]
I think we should add a section refer to the k8s version compatability.

I work on f8 java client version 3.0.3 but it doesn't support k8s 1.6.2&1.4.9. Return error while update nodes. But it works fine with k8s 1.7.10.

a version compatability on the readme.md would be helpful for new users.

I already built a pull request

**Comment by smanikim** [comment]
+1 as I am also facing issue with respect to api versioning in 1.8

**Comment by piyush1594** [comment]
Now, this is in readme. Closing this.
