### ISSUE TITLE
how to use client.extensions().deployments().createOrReplace correctly 

### ISSUE THREAD

**Issue by readless** [fabric8io/kubernetes-client#948]
i use the code 
`Config config = new ConfigBuilder()
                .withMasterUrl("*")
                .withUsername("*")
                .withPassword("*")
                .withTrustCerts(true)
                .build();
        KubernetesClient client = new DefaultKubernetesClient(config);
        long s1 =System.currentTimeMillis();
        Deployment deployment = client.extensions().deployments()
                .inNamespace("project-5f52405f1966f40f8cf9b6fcb82462a535fbe143")
                .withName("app-32ae78bd5744c321b6c35d719173a46d65a80da9").get();
        deployment.getSpec().setReplicas(5);
        client.extensions().deployments().createOrReplace(deployment);`

but i get the error 
`Failure executing: POST at: https://1.1.1.1:6443/apis/extensions/v1beta1/namespaces/project-5f52405f1966f40f8cf9b6fcb82462a535fbe143/deployments. Message: Deployment in version "v1beta1" cannot be handled as a Deployment: v1beta1.Deployment: ObjectMeta: v1.ObjectMeta: Labels: Generation: Finalizers: []string: CreationTimestamp: unmarshalerDecoder: parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006", parsing 175 ...7:31:25Z"}... `

how can i do

**Comment by rishi-anand** [comment]
@readless, I am performing below operation

```
            Deployment deployment1 = client.extensions().deployments().inNamespace("default").withName("nginx-deployment").get();
            deployment.getSpec().setReplicas(1);
            client.extensions().deployments().createOrReplace(deployment1);
            logger.info("updated deployment OK");
```
and I am getting below exception:
```
19:47:02.535 [main] INFO fabric8.service.ListPods - deployment :
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://104.154.224.241/apis/extensions/v1beta1/namespaces/default/deployments. Message: resourceVersion should not be set on objects to be created. Received status: Status(apiVersion=v1, code=500, details=null, kind=Status, message=resourceVersion should not be set on objects to be created, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=null, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:409)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:226)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:773)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:356)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:425)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:422)
	at fabric8.service.ListPods.testObj(ListPods.java:61)
	at fabric8.service.ListPods.main(ListPods.java:29)
```

**Comment by piyush1594** [comment]
Hi @readless @rishi-anand 

If you want to edit some resource object on your cluster. This can be done like this (giving an example of deployment) : 

`Deployment deployment = client.extensions().deployments().inNamespace("namespace-name")
      .withName("deployment-name").edit().editSpec().withReplicas(5).endSpec().done(); `

Please try to do in this way. If you still face some problem, revert us back.

Thanks

**Comment by rishi-anand** [comment]
@piyush1594, 
This is how I am doing now and it works.

```
io.fabric8.kubernetes.api.model.extensions.Deployment deployment = client
                        .extensions().deployments().inNamespace(deploymentContext.nameSpace())
                        .withName(deploymentContext.name()).scale(count, true);
```

**Comment by piyush1594** [comment]
Hi @rishi-anand 

Thanks for another solution, it looks good. The method I have suggested can be used to do any type of editing in the resource like it's a generalized method to edit a resource.

By the way, Thanks for solution

**Comment by piyush1594** [comment]
Since this is resolved, I am closing this. Thanks

**Comment by CathySha** [comment]
@piyush1594 
I use ConfigMap as Volume in the deployment. I'm trying to update a deployment with different Volume and VolumeMount.(see example below)

I tried all the following ways including the way you provided:

(I use io.fabric8.kubernetes.api to do the operations on kubernetes.)

1)

client().extensions().deployments().inNamespace(namespaceName).withName(deploymentName).replace(deployment);

2)

client().extensions().deployments().inNamespace(namespaceName).withName(deploymentName).createOrReplace(deployment);

3)

client().extensions().deployments().inNamespace(namespaceName).withName(deploymentName).cascading(false).replace(deployment);

4)

client().extensions().deployments().inNamespace(namespaceName).withName(deploymentName).edit().editSpec().editTemplate().editSped().removeAllFromVolumes(volumes).endSpec().endTemplate().endTemplate().endSpec().done();

5)

client().extensions().deployments().inNamespace(namespaceName).withName(deploymentName).edit().editSpec().editTemplate().editSped().removeFromVolumes(volume).endSpec().endTemplate().endTemplate().endSpec().done();

All the above commands don't work!...

I also tried :

client().extensions().deployments().inNamespace(namespaceName).withName(deploymentName).edit().editSpec().editTemplate().editSped().AddToVolumes(volume).endSpec().endTemplate().endTemplate().endSpec().done();

and it works.

i.e. only ADD works, but REMOVE doesn't work....

Is it a BUG or not ? Did I use it in the right way? I just want to update the deployment with different Volume (ConfigMap type) and VolumeMount, how should I do? Thank you!

Example: The old Deployment is like this: (I only show the main part)

kind: Deployment
metadata:
  name: d2
  namespace: n1
  spec:
    replicas: 1
    template:
      metadata:
        creationTimestamp: null
      spec:
        containers:
        - image: x.x.x.x
          imagePullPolicy: IfNotPresent
          name: c2
          volumeMounts:
          - mountPath: /var
            name: configmapvolume1
          - mountPath: /var/a
            name: configmapvolume2
        volumes:
        - configMap:
            defaultMode: 420
            items:
            - key: a.yml
              path: a.yml
            name: a
          name: configmapvolume1
        - configMap:
            defaultMode: 420
            items:
            - key: c.yml
              path: c.yml
            name: a
          name: configmapvolume2
The new Deployment is like this:(I only show the main part)

kind: Deployment
metadata:
  name: d2
  namespace: n1
  spec:
    replicas: 1
    template:
      metadata:
        creationTimestamp: null
      spec:
        containers:
        - image: x.x.x.x
          imagePullPolicy: IfNotPresent
          name: c2
          volumeMounts:
          - mountPath: /var/b
            name: configmapvolume1
        volumes:
        - configMap:
            defaultMode: 420
            items:
            - key: b.yml
              path: b.yml
            name: b
          name: configmapvolume1

**Comment by oscerd** [comment]
You already ask here https://github.com/fabric8io/kubernetes-client/issues/1146 @CathySha please avoid cross-posting in all the issues.

**Comment by CathySha** [comment]
@oscerd Sorry for that ...
Because no one answered me, and I need it urgently.
