### ISSUE TITLE
Close() doesn't immediately close the connection

### ISSUE THREAD

**Issue by ahab94** [fabric8io/kubernetes-client#960]
So we have a use case where we have to make connection to multiple kubernetes clusters and in quick succession. What i have noticed is the on calling  `close()`  on kubernetes-client it is not releasing the `ok-http-connection-pool` instead it's being timed out. Is that expected?

**Comment by ahab94** [comment]
@piyush1594 i see you are replying actively, do you happen to anything on this issue?

**Comment by piyush1594** [comment]
Hi @ahab94 

I never came across this use case and problem. I generally use a single cluster and `client.close()` do my work. I will take a look at the issue and will let you know about my findings.

CC @hrishin @iocanel please help if you have the context for this.

Thanks

**Comment by ahab94** [comment]
Hey @piyush1594 
Actually in our use case we concurrently connect with multiple clusters and after certain logic close them.
One thing i have noticed is that the okhttp connectionpool stays there even after `instance.close()`.
This is what it looks like after several instances have been created and close;
```BASH
OkHttp ConnectionPool
OkHttp ConnectionPool
OkHttp ConnectionPool
OkHttp ConnectionPool
OkHttp ConnectionPool
OkHttp ConnectionPool
OkHttp ConnectionPool
OkHttp ConnectionPool
OkHttp ConnectionPool
OkHttp ConnectionPool
OkHttp ConnectionPool
OkHttp ConnectionPool
OkHttp ConnectionPool
OkHttp ConnectionPool
OkHttp ConnectionPool
OkHttp ConnectionPool
OkHttp ConnectionPool
OkHttp ConnectionPool
OkHttp ConnectionPool
OkHttp ConnectionPool
OkHttp ConnectionPool
OkHttp ConnectionPool
OkHttp ConnectionPool
```
Which is extra resources, only being closed on timeout.
