### ISSUE TITLE
Add support for service catalog feature

### ISSUE THREAD

**Issue by hrishin** [fabric8io/kubernetes-client#973]
Need add DSL API's for Service Catalog resources

- Broker
- ServiceClass
- Instance
- Binding

Need support following set of operations
- Load resource/Create
- Get/List
- Update
- Delete

Tasks:
 - Add java model classes : [model#issue](https://github.com/fabric8io/kubernetes-model/issues/225)
 - Implement feature code
 - Add unit tests
 - Add integration tests

**Comment by rohanKanojia** [comment]
@dev-gaur : There is an extension of this api maintained by spring-boot team:

https://github.com/snowdrop/servicecatalog-java-api

Did you check this before marking this as a potential gsoc task???

**Comment by theexplorist** [comment]
https://github.com/fabric8io/kubernetes-model/issues/225 Maybe this may clarify it! In comments the extension is mentioned!

**Comment by dev-gaur** [comment]
@rohanKanojia Let's close this one if there's no scope for any work here.

**Comment by iocanel** [comment]
There is no need to reimplement: https://github.com/snowdrop/servicecatalog-java-api

I am discussing the possibility of merging into this project.

**Comment by rohanKanojia** [comment]
Okay, Ioannis got approval for moving service catalog client into our repository. I think we should add that api as another module in our project.
