### ISSUE TITLE
Add contributor guideliness

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#980]
Currently the number of contributions is such, that it takes a lot of time to review. Also, it takes a lot of back and forth, which is a burden for the contributors themselves.

If we had a clean contributors, guideline, we could eliminate minor issues like:
- missing tests
- formating
- missing headers
- semantic versioning handling etc.

**Comment by pradeepto** [comment]
This is definitely required and I wanted to talk to you @iocanel  about this. Thank you for creating this task. I I don't think I can do the whole thing myself but I will help out with this definitely.

**Comment by piyush1594** [comment]
@iocanel @pradeepto I have added a contribution.md [here](https://github.com/fabric8io/kubernetes-client/blob/master/CONTRIBUTING.md). Can you please take a look. If all seems fine, we can close this.

**Comment by piyush1594** [comment]
@pradeepto @iocanel I am closing this as the file is already added. Thanks
