### ISSUE TITLE
Support for Job spec.backoffLimit

### ISSUE THREAD

**Issue by nmnellis** [fabric8io/kubernetes-client#981]
Add kubernetes Job spec.backoffLimit
https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#pod-backoff-failure-policy

**Comment by piyush1594** [comment]
This issue is already discussed here [model-239](https://github.com/fabric8io/kubernetes-model/issues/239), to have a point of discussion, I am closing this.

Thanks
