### ISSUE TITLE
orphaned pod occasionally lingering around after deployment is deleted

### ISSUE THREAD

**Issue by huaixichen** [fabric8io/kubernetes-client#990]
Currently we use kubernetes-client Java SDK to interact with K8S cluster, and do with following to delete a deployment:

```
client.extensions().ingresses().inNamespace(namespace).withName(name).delete();
```
Occasionally we see orphaned pod is lingering around in the cluster after deployment is deleted. The orphaned pod here is referring to that its relevant deployment and replicaset are both deleted.

Diging into the DeploymentReaper codes, it looks slightly different with the Reaper implementation in the GO SDK. 

```
@Override
    public boolean reap() {
      Deployment deployment = oper.edit().editSpec().withReplicas(0).endSpec().done();
      waitForObservedGeneration(deployment.getStatus().getObservedGeneration());
      reapMatchingReplicaSets(deployment.getSpec().getSelector());
      return false;
    }
```

VS

```
func (reaper *DeploymentReaper) Stop(namespace, name string, timeout time.Duration, gracePeriod *metav1.DeleteOptions) error {
	deployments := reaper.dClient.Deployments(namespace)
	rsReaper := &ReplicaSetReaper{reaper.rsClient, reaper.pollInterval, reaper.timeout}

	deployment, err := reaper.updateDeploymentWithRetries(namespace, name, func(d *extensions.Deployment) {
		d.Spec.RevisionHistoryLimit = util.Int32Ptr(0)
		d.Spec.Replicas = 0
		d.Spec.Paused = true
	})
	if err != nil {
		return err
	}

	// Use observedGeneration to determine if the deployment controller noticed the pause.
	if err := deploymentutil.WaitForObservedDeploymentInternal(func() (*extensions.Deployment, error)            {
		return deployments.Get(name, metav1.GetOptions{})
	}, deployment.Generation, 1*time.Second, 1*time.Minute); err != nil {
		return err
	}
   ...
}
```
The difference is that the Java based DeploymentReaper issue a scaling operation for deployment only,  while the GO based one triggers a "paused" action additionally.  Furthermore, the Java based DeploymentReaper uses the deployment.status.observedGenration as input for waitForObservedGeneration() method, while the Go one uses deployment.Generation as input. 

I am not sure if such difference would  be the cause for the orphaned pod, but at least the behavior looks inconsistent between the JAVA and GO SDK. 

Could anyone help to clarify on this?  

Appreciated any help! Thanks!

**Comment by huaixichen** [comment]
any help?

**Comment by sjhnnn** [comment]
1

**Comment by rohanKanojia** [comment]
@huaixichen : Did you use `cascading()` flag to delete dependents also?
