### ISSUE TITLE
Fluent object not container AdditionalProperties map

### ISSUE THREAD

**Issue by fbird** [fabric8io/kubernetes-client#993]
Hi, 
I found the fluent object not contain the AdditionalProperties object, so when i use builder to build the kubernetes resource, it always miss AdditionalProperties, am i miss something?

wait for your reply, thx

**Comment by piyush1594** [comment]
Hi @fbird 

Can you please elaborate more like this is specific to any resource or general problem for all resources and which version of Kubernetes client you are using?

Thanks

**Comment by fbird** [comment]
hi @piyush1594 

thanks for your reply,  it is a general problem, all the resource has the same problem, and my kubernetes client version is 3.0.3

**Comment by skonto** [comment]
I see the same, so I dig into the generated Pod.java and it seems the field is ignored during serialization/deserialization:

`    @JsonIgnore
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();`
