### ISSUE TITLE
Egress rules feature request

### ISSUE THREAD

**Issue by ahab94** [fabric8io/kubernetes-client#995]
Is anyone working on integrating Egress rule apis to kubernetes client, if so when can it be expected to be done?

**Comment by piyush1594** [comment]
Hi @ahab94 

As far as I know, Egress Rule is part of Network Policy. We have added the support for NetworkPolicy here #750 

Right now we are supporting till Kubernetes 1.7 and Egress rule feature is available from Kubernetes 1.8. That's the reason it's not available here. As we will add the support for Kubernetes 1.8, it will become available.

Thanks

**Comment by ahab94** [comment]
Thanks @piyush1594, closing the issue.

**Comment by dennis-benzinger-hybris** [comment]
Are egress network policies supported now?

**Comment by piyush1594** [comment]
Its WIP right now, you can see #1020
