### ISSUE TITLE
Kubernetes/Openshift mock server should be able to take customized config for client

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#998]
For now, in order to create a client for any Kubernetes/Openshift mock server, we simply request mock server like this:
```
        OpenShiftClient client = mockServer.createOpenShiftClient();
```
This works fine, but it would be nice if we could pass our own created `Config` object while creating Kubernetes/Openshift client. Right now we're just forced to use a `config`; Have a look at the following file [`KubernetesMockServer.java`](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesMockServer.java):
```
    public NamespacedKubernetesClient createClient() {
        Config config = new ConfigBuilder()
                .withMasterUrl(url("/"))
                .withTrustCerts(true)
                .withTlsVersions(TLS_1_0)
                .withNamespace("test")
                .build();
        return new DefaultKubernetesClient(config);
}
```
I'm not sure why Custom config for the client is not provided for mock server, There must be something which i'm missing(any security/comparibility issue) that is forcing us to use mock server this way. But i'd like to see if we could have it, we could customize lots of things like `ConnectionTimeout`, `ConcurrentRequestsPerHosts` etc.

**Comment by Krishan-Sharma** [comment]
I am not entirely sure about OpenShiftClient but I think KubernetesServer allows you to override default config for mock server.This was done as part of this change (https://github.com/fabric8io/kubernetes-client/commit/8679f337fafeed779f3d6f36c803a0b867afde69).
